### ISSUE TITLE
Cmangos-classic building error

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1001]
**Current behavior**: 

[ 39%] Building CXX object src/game/CMakeFiles/game.dir/vmap/BIH.cpp.o
/home/mangos/cmangosserver/src/game/vmap/BIH.cpp: In member function ‘void BIH::subdivide(int, int, std::vector<unsigned int>&, BIH::buildData&, AABound&, AABound&, int, int, BIH::BuildStats&)’:
/home/mangos/cmangosserver/src/game/vmap/BIH.cpp:60:19: error: ‘logic_error’ is not a member of ‘std’
             throw std::logic_error("negative node extents");
                   ^
/home/mangos/cmangosserver/src/game/vmap/BIH.cpp:66:23: error: ‘logic_error’ is not a member of ‘std’
                 throw std::logic_error("invalid node overlap");
                       ^
src/game/CMakeFiles/game.dir/build.make:1894: recipe for target 'src/game/CMakeFiles/game.dir/vmap/BIH.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/vmap/BIH.cpp.o] Error 1
CMakeFiles/Makefile2:629: recipe for target 'src/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Operating system**: 
Debian 8 x64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Muehe** [comment]
Can you try this?

```diff
diff --git a/src/game/vmap/BIH.cpp b/src/game/vmap/BIH.cpp
index c3af37d..7f1466e 100644
--- a/src/game/vmap/BIH.cpp
+++ b/src/game/vmap/BIH.cpp
@@ -19,6 +19,7 @@
 #include "BIH.h"
 
 #include <cmath>
+#include <stdexcept>
 
 void BIH::buildHierarchy(std::vector<uint32>& tempTree, buildData& dat, BuildStats& stats)
 {
```

**Comment by wowmui** [comment]
perfect! THANKS!!
