### ISSUE TITLE
[Classic]priests spell Mind control Crash!

### ISSUE THREAD

**Issue by kuramajssken001** [cmangos/issues#1002]
**Current behavior**: 

**Expected behavior**: 

**Steps to reproduce**:

1. 
2. 
3. 
[mangosd.exe_[18-7_11-3-4].txt](https://github.com/cmangos/issues/files/368304/mangosd.exe_.18-7_11-3-4.txt)

**Client version**: 

**Commit hash**: 

**Database version**: 

**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Phatcat** [comment]
Should be handled with https://github.com/cmangos/mangos-classic/commit/e010c157cbbe4c767ef1b22ca1f06044d0145f07

**Comment by kuramajssken001** [comment]
thank you @Phatcat

**Comment by Phatcat** [comment]
Not my work, so thank @cyberium =)
