### ISSUE TITLE
[CLASSIC] Player in Instance Die, Player Off-line Crash!

### ISSUE THREAD

**Issue by kuramajssken001** [cmangos/issues#1003]
**Current behavior**: 

**Expected behavior**: 

**Steps to reproduce**:
1. 
2. 
3. 

**Client version**: 

**Commit hash**: 

**Database version**: 

**Operating system**: 

[mangosd.exe_[18-7_11-23-52].txt](https://github.com/cmangos/issues/files/368305/mangosd.exe_.18-7_11-23-52.txt)

**Comment by Fiver** [comment]
confirm!!! and .saveall command have same problem!

**Comment by kuramajssken001** [comment]
@Fiver 你怎么又弄魔兽了。消失这么久。。。。。

**Comment by sidsukana** [comment]
confirmed

**Comment by cala** [comment]
Could you please fill the crash report more properly?

**Comment by Fiver** [comment]
@kuramajssken001 一直在弄啊！很久不冒头了

**Comment by sidsukana** [comment]
```diff --git a/src/game/Map.cpp b/src/game/Map.cpp
index 0bce643..9e70526 100644
--- a/src/game/Map.cpp
+++ b/src/game/Map.cpp
@@ -551,7 +551,8 @@ void Map::Update(const uint32& t_diff)
     }
 
     // Send world objects and item update field changes
-    SendObjectUpdates();
+    if (HavePlayers())
+        SendObjectUpdates();
 
     // Don't unload grids if it's battleground, since we may have manually added GOs,creatures, those doesn't load from DB at grid re-load !
     // This isn't really bother us, since as soon as we have instanced BG-s, the whole map unloads as the BG gets ended
```

**Comment by sidsukana** [comment]
```diff
diff --git a/src/game/Map.cpp b/src/game/Map.cpp
index 0bce643..9e70526 100644
--- a/src/game/Map.cpp
+++ b/src/game/Map.cpp
@@ -551,7 +551,8 @@ void Map::Update(const uint32& t_diff)
     }
 
     // Send world objects and item update field changes
-    SendObjectUpdates();
+    if (HavePlayers())
+        SendObjectUpdates();
 
     // Don't unload grids if it's battleground, since we may have manually added GOs,creatures, those doesn't load from DB at grid re-load !
     // This isn't really bother us, since as soon as we have instanced BG-s, the whole map unloads as the BG gets ended
```

**Comment by Fiver** [comment]
@sidsukana    thanks, it work！

**Comment by kuramajssken001** [comment]
@sidsukana Thanks!

**Comment by kuramajssken001** [comment]
@Fiver 把企鹅号留下

**Comment by sidsukana** [comment]
This does **not** solve the problem!

**Comment by sidsukana** [comment]
With more then 1 players in instance will be crash for the same reason....

**Comment by sidsukana** [comment]
Can you confirm this crash on TBC, wotlk ?

**Comment by kuramajssken001** [comment]
@sidsukana Classic

**Comment by Fiver** [comment]
`@@ -1580,11 +1580,11 @@ bool Player::TeleportTo(uint32 mapid, float x, float y, float z, float orientati
         // lets reset far teleport flag if it wasn't reset during chained teleports
         SetSemaphoreTeleportFar(false);
         // setup delayed teleport flag
         // if teleport spell is casted in Unit::Update() func
         // then we need to delay it until update process will be finished
-        if (SetDelayedTeleportFlagIfCan())
+        if (!GetSession()->isLogingOut() && SetDelayedTeleportFlagIfCan())
         {
             SetSemaphoreTeleportNear(true);
             // lets save teleport destination for player
             m_teleport_dest = WorldLocation(mapid, x, y, z, orientation);
             m_teleport_options = options;
@@ -1631,11 +1631,11 @@ bool Player::TeleportTo(uint32 mapid, float x, float y, float z, float orientati
             // lets reset near teleport flag if it wasn't reset during chained teleports
             SetSemaphoreTeleportNear(false);
             // setup delayed teleport flag
             // if teleport spell is casted in Unit::Update() func
             // then we need to delay it until update process will be finished
-            if (SetDelayedTeleportFlagIfCan())
+            if (!GetSession()->isLogingOut() && SetDelayedTeleportFlagIfCan())
             {
                 SetSemaphoreTeleportFar(true);
                 // lets save teleport destination for player
                 m_teleport_dest = WorldLocation(mapid, x, y, z, orientation);
                 m_teleport_options = options;

`

hack fix! should not crash again!

**Comment by Fiver** [comment]
hack fix!!should not crash again

[patch0.txt](https://github.com/cmangos/issues/files/369811/patch0.txt)

**Comment by Fiver** [comment]
`diff --git a/src/game/Player.cpp b/src/game/Player.cpp`
`index 8ae085b..f7449e9 100644`
`--- a/src/game/Player.cpp`
`+++ b/src/game/Player.cpp`
`@@ -1518,7 +1518,7 @@ ChatTagFlags Player::GetChatTag() const`
`     return CHAT_TAG_NONE;`
` }`

`-bool Player::TeleportTo(uint32 mapid, float x, float y, float z, float orientation, uint32 options /*=0*/, AreaTrigger const* at /*=nullptr*/)`
`+bool Player::TeleportTo(uint32 mapid, float x, float y, float z, float orientation, uint32 options /*=0*/, AreaTrigger const* at /*=nullptr*/, bool isAllowNoDelay /*=false*/)`
` {`
`     if (!MapManager::IsValidMapCoord(mapid, x, y, z, orientation))`
`     {`
`@@ -1582,7 +1582,7 @@ bool Player::TeleportTo(uint32 mapid, float x, float y, float z, float orientati`
`         // setup delayed teleport flag`
`         // if teleport spell is casted in Unit::Update() func`
`         // then we need to delay it until update process will be finished`
`-        if (SetDelayedTeleportFlagIfCan())`
`+        if (!isAllowNoDelay && SetDelayedTeleportFlagIfCan())`
`         {`
`             SetSemaphoreTeleportNear(true);`
`             // lets save teleport destination for player`
`@@ -1633,7 +1633,7 @@ bool Player::TeleportTo(uint32 mapid, float x, float y, float z, float orientati`
`             // setup delayed teleport flag`
`             // if teleport spell is casted in Unit::Update() func`
`             // then we need to delay it until update process will be finished`
`-            if (SetDelayedTeleportFlagIfCan())`
`+            if (!isAllowNoDelay && SetDelayedTeleportFlagIfCan())`
`             {`
`                 SetSemaphoreTeleportFar(true);`
`                 // lets save teleport destination for player`
`@@ -4499,7 +4499,7 @@ void Player::RepopAtGraveyard()`
`     if (ClosestGrave)`
`     {`
`         bool updateVisibility = IsInWorld() && GetMapId() == ClosestGrave->map_id;`
`-        TeleportTo(ClosestGrave->map_id, ClosestGrave->x, ClosestGrave->y, ClosestGrave->z, GetOrientation());`
`+        TeleportTo(ClosestGrave->map_id, ClosestGrave->x, ClosestGrave->y, ClosestGrave->z, GetOrientation(), 0, nullptr, GetSession()->isLogingOut());`
`         if (updateVisibility && IsInWorld())`
`             UpdateVisibilityAndView();`
`     }`
`diff --git a/src/game/Player.h b/src/game/Player.h`
`index 5f79918..dac693e 100644`
`--- a/src/game/Player.h`
`+++ b/src/game/Player.h`
`@@ -857,7 +857,7 @@ class MANGOS_DLL_SPEC Player : public Unit`
`         void AddToWorld() override;`
`         void RemoveFromWorld() override;`

`-        bool TeleportTo(uint32 mapid, float x, float y, float z, float orientation, uint32 options = 0, AreaTrigger const* at = nullptr);
`+        bool TeleportTo(uint32 mapid, float x, float y, float z, float orientation, uint32 options = 0, AreaTrigger const* at = nullptr, bool isAllowNoDelay = false);`
`         bool TeleportTo(WorldLocation const& loc, uint32 options = 0)`
`         {`

**Comment by Muehe** [comment]
@Fiver enclose with lines containing three back ticks and write diff behind the opening one ([See here](https://guides.github.com/features/mastering-markdown/#examples) and click on code to see an example).

**Comment by Fiver** [comment]
@Muehe  OK!

**Comment by kuramajssken001** [comment]
@Fiver Not available

**Comment by sidsukana** [comment]
Need remove player from old map while teleported
```diff
diff --git a/src/game/Map.cpp b/src/game/Map.cpp
index 0bce643..89ae457 100644
--- a/src/game/Map.cpp
+++ b/src/game/Map.cpp
@@ -599,7 +599,7 @@ void Map::Remove(Player* player, bool remove)
     if (p.x_coord >= TOTAL_NUMBER_OF_CELLS_PER_MAP || p.y_coord >= TOTAL_NUMBER_OF_CELLS_PER_MAP)
     {
         // invalid coordinates
-        player->ResetMap();
+        //player->ResetMap();
 
         if (remove)
             DeleteFromWorld(player);
@@ -624,7 +624,7 @@ void Map::Remove(Player* player, bool remove)
     SendRemoveTransports(player);
     UpdateObjectVisibility(player, cell, p);
 
-    player->ResetMap();
+    //player->ResetMap();
     if (remove)
         DeleteFromWorld(player);
 }
diff --git a/src/game/MovementHandler.cpp b/src/game/MovementHandler.cpp
index 6c6685d..26fa686 100644
--- a/src/game/MovementHandler.cpp
+++ b/src/game/MovementHandler.cpp
@@ -101,6 +101,10 @@ void WorldSession::HandleMoveWorldportAckOpcode()
 
     GetPlayer()->SetSemaphoreTeleportFar(false);
 
+	if (GetPlayer()->IsInWorld())
+		if (Map* oldMap = GetPlayer()->GetMap())
+			oldMap->Remove(GetPlayer(), false);
+
     // relocate the player to the teleport destination
     if (!map)
         map = sMapMgr.CreateMap(loc.mapid, GetPlayer());

warning: LF will be replaced by CRLF in src/game/MovementHandler.cpp.
The file will have its original line endings in your working directory.

```

**Comment by jimmybrancaccio** [comment]
Can anyone confirm if this is still an issue in any versions?

**Comment by Phatcat** [comment]
I can't reproduce this on classic,

Had 2 clients on, grouped, put both of them in stockades, let one of them die, then disconnected that client, waited for the client to be shown as disconnected on the other client, no crash, then i did a .saveall , everything got saved fine, no crash, then I had the other player in the instance be killed, no crash. Don't really know what else to test with this, but I ain't getting it to crash.

**Comment by kuramajssken001** [comment]
Thanks for your reply. I have solved this problem. @Phatcat
