### ISSUE TITLE
[All] Fix Linux installation

### ISSUE THREAD

**Issue by Muehe** [cmangos/issues#1004]
**Current behavior:**
Build errors when compiling extractors. Some errors are fixed on Wotlk only.

**Expected behavior:**
Build fine.

**Steps to reproduce:**

1. Be on Linux (confirmed for Debian/Ubuntu)
2. Compile core and map extractors

**Commit hash:**
https://github.com/cmangos/mangos-classic/commit/29bdc0bc150a6ccb7766a68dea19cec5a55245fb
https://github.com/cmangos/mangos-tbc/commit/2ad4040460c2242346d1a482f757728e3408e834
https://github.com/cmangos/mangos-wotlk/commit/013d153e1fa747050f9d19949a45a253f6f62463
https://github.com/cmangos/mangos-cata/commit/05252710f411897867fd2e4695309a2db8410d25

**Operating system:**
Debian/Ubuntu

**Additional information:**

* All of these errors appeared on classic. http://cmangos.net/thread-7481-post-46306.html#pid46306
* The last two appeared on Wotlk. http://cmangos.net/thread-7481-post-46129.html#pid46129 (Step 11)
* TBC and Cata not tested, but the code suggests they will throw errors too (includes are missing/wrong).
* First error is fixed in Wotlk, but not the other cores
* Second error seems fixed in Wotlk too, but not sure how (CMake/VS includes maybe)

**Error 1.:** (Missing backport)

* In commit https://github.com/cmangos/mangos-wotlk/commit/da00c388546ca181ca83635f9d85a96ae4a3f586, needs backport to classic, tbc and cata.
* See #902 

```diff
diff --git a/contrib/mmap/src/MapBuilder.cpp b/contrib/mmap/src/MapBuilder.cpp
index 309d5bc..08302f8 100644
--- a/contrib/mmap/src/MapBuilder.cpp
+++ b/contrib/mmap/src/MapBuilder.cpp
@@ -25,6 +25,8 @@
 #include "DetourNavMeshBuilder.h"
 #include "DetourCommon.h"
 
+#include <climits>
+
 using namespace VMAP;
 
 namespace MMAP
```

**Error 2.:** (Obsolete, see https://github.com/anathemareborn/core/commit/e66323dacad6a490f5b678fb14671f020f83aa44 for better way of fixing.)

* Alternate method of fixing in https://github.com/cmangos/mangos-wotlk/commit/1cb24973faee7ba168a52ac2134e61e94b16115b but I am unsure which is right, hard path or however that commit gets it working...
* See #902

```diff
diff --git a/src/game/MoveMapSharedDefines.h b/src/game/MoveMapSharedDefines.h
index 0a88e42..74be6c8 100644
--- a/src/game/MoveMapSharedDefines.h
+++ b/src/game/MoveMapSharedDefines.h
@@ -20,7 +20,7 @@
 #define _MOVE_MAP_SHARED_DEFINES_H
 
 #include "Platform/Define.h"
-#include "../recastnavigation/Detour/Include/DetourNavMesh.h"
+#include "../../dep/recastnavigation/Detour/Include/DetourNavMesh.h"
 
 #define MMAP_MAGIC 0x4d4d4150   // 'MMAP'
 #define MMAP_VERSION 4
```

**Error 3.:** (Missing backport)

* http://cmangos.net/thread-7481-post-46129.html#pid46129 (Step 11)
* See https://github.com/cmangos/mangos-classic/pull/171
* See #1001 
* _Fixed in https://github.com/cmangos/mangos-wotlk/commit/76176af80c23c3e582750d8a4500ee99a176be56_

```diff
diff --git a/src/game/vmap/BIH.cpp b/src/game/vmap/BIH.cpp
index c3af37d..7f1466e 100644
--- a/src/game/vmap/BIH.cpp
+++ b/src/game/vmap/BIH.cpp
@@ -19,6 +19,7 @@
 #include "BIH.h"
 
 #include <cmath>
+#include <stdexcept>
 
 void BIH::buildHierarchy(std::vector<uint32>& tempTree, buildData& dat, BuildStats& stats)
 {
```

**Error 4.:** (Missing backport, maybe use `cstring` instead)

* http://cmangos.net/thread-7481-post-46129.html#pid46129 (Step 11)
* _Fixed in https://github.com/cmangos/mangos-wotlk/commit/9e33a021dd26331b0016f8f44fdeb2a00d76b027_

```diff
diff --git a/src/game/vmap/WorldModel.cpp b/src/game/vmap/WorldModel.cpp
index b5cf7f1..acfcb15 100644
--- a/src/game/vmap/WorldModel.cpp
+++ b/src/game/vmap/WorldModel.cpp
@@ -20,6 +20,8 @@
 #include "VMapDefinitions.h"
 #include "MapTree.h"
 
+#include <cstring>
+
 using G3D::Vector3;
 using G3D::Ray;
```

*Edit: Added link to https://github.com/cmangos/mangos-classic/pull/171*
*Edit 2: Added links to https://github.com/cmangos/mangos-wotlk/commit/9e33a021dd26331b0016f8f44fdeb2a00d76b027 and https://github.com/cmangos/mangos-wotlk/commit/76176af80c23c3e582750d8a4500ee99a176be56*, marked error 1, 3 and 4 as missing backports and 2 as obsolete.

**Comment by Muehe** [comment]
Updated links.

**Comment by wowmui** [comment]
Linking CXX executable mangosd
../game/libgame.a(Player.cpp.o): In function Player::Player(WorldSession*)': Player.cpp:(.text+0x20ced): undefined reference toAntiCheat::AntiCheat(Player)'
../game/libgame.a(Player.cpp.o): In function Player::~Player()': Player.cpp:(.text+0x40917): undefined reference toAntiCheat::~AntiCheat()'
../game/libgame.a(Player.cpp.o): In function Player::_SaveInventory()': Player.cpp:(.text+0x412c3): undefined reference toAntiCheat::_DoAntiCheatCheck(AntiCheat
Check)'collect2: error: ld returned 1 exit status
src/mangosd/CMakeFiles/mangosd.dir/build.make:271: recipe for target 'src/mangosd/mangosd'
failedmake[2]: ** [src/mangosd/mangosd] Error 1
CMakeFiles/Makefile2:685: recipe for target 'src/mangosd/CMakeFiles/mangosd.dir/all' faile
dmake[1]: *** [src/mangosd/CMakeFiles/mangosd.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

CMAKE OPTION:-DCMAKE_INSTALL_PREFIX=/home/cmangos/run -DPCH=1 -DDEBUG=0
What happened.... T_T

**Comment by cyberium** [comment]
No anticheat in our code.

**Comment by cyberium** [comment]
Thank alot @Muehe for this work. I think all issues should be resolved now.

**Comment by cyberium** [comment]
In fact there is still one error after all binaries installed. -> http://cmangos.net/thread-7481-post-46428.html#pid46428
If someone know how to fix that :)

**Comment by adellaci** [comment]
@cyberium 
I think i found a fix

**/contrib/extractor/CMakeLists.txt**
`# This file is part of the CMaNGOS Project. See AUTHORS file for Copyright information
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cmake_minimum_required (VERSION 2.6)
set(EXECUTABLE_NAME "ad")
project (${EXECUTABLE_NAME})

add_subdirectory (libmpq)
add_subdirectory (loadlib)

add_compile_options(-INCLUDE_BINDINGS_DIR=./libmpq) # added to fix libmpq with ad

include_directories (${MANGOS_MAP_EXTRACTOR_SOURCE_DIR}/libmpq)
include_directories (${MANGOS_MAP_EXTRACTOR_SOURCE_DIR}/loadlib)

link_directories (${MANGOS_MAP_EXTRACTOR_SOURCE_DIR}/libmpq)
link_directories (${MANGOS_MAP_EXTRACTOR_SOURCE_DIR}/loadlib)

add_executable (${EXECUTABLE_NAME} dbcfile.cpp mpq_libmpq.cpp System.cpp)

target_link_libraries (${EXECUTABLE_NAME} libmpq)
target_link_libraries (${EXECUTABLE_NAME} loadlib)

install(TARGETS ${EXECUTABLE_NAME} DESTINATION ${BIN_DIR}/tools)`
