### ISSUE TITLE
[Classic] CalculateLevelPenalty should not exist

### ISSUE THREAD

**Issue by dagochen** [cmangos/issues#1005]
**Current behavior**: 
Spells are influenced by https://github.com/cmangos/mangos-classic/blob/29bdc0bc150a6ccb7766a68dea19cec5a55245fb/src/game/Unit.cpp#L2362.

**Expected behavior**: 
This was introduced with Prepatch 2.0.1 for BC and has nothing to do with Classic.
**Steps to reproduce**:
1. Get +dmg/+heal Gear. 
2.  Cast lowlevel Spell
3. Check the damage/healing.

Sources:
http://www.wowdaily.info/a.asp?a=2013881&pda=yes
http://wowwiki.wikia.com/wiki/Patch_2.0.1

**Comment by sidsukana** [comment]
https://github.com/cmangos/mangos-classic/pull/139/commits/d881a4dc0c869c3cec0a1d9613eb6800f3b049e7

**Comment by dagochen** [comment]
Are you sure about the formula you are using? Is there a penalty for spells lower than lvl 20 at all?

**Comment by sidsukana** [comment]
Yes, it's from valkyrie-wow source ;)

**Comment by dagochen** [comment]
Any non-private-server source? Just because I make it complete different on my own server its not yet correct working ....just saying...it still might be wrong?

**Comment by sidsukana** [comment]
I open PR https://github.com/cmangos/mangos-classic/pull/173
you can check formula with http://wow.gamepedia.com/index.php?title=Spell_power&direction=prev&oldid=298315#Penalty_Rules

**Comment by dagochen** [comment]
Thanks! Thats what I was looking for!

**Comment by Phatcat** [comment]
Level penalty was very much a thing back in classic, just read basically any raid healing guide from back in the day. (this is all in relation to bonuses, right?) Downranking was a thing blizzard was very much aware of back then, yes.

**Comment by dagochen** [comment]
Why close Oo this is wrong in classic...?

**Comment by Phatcat** [comment]
Sorry, I thought this issue was saying there was no level penalty in vanilla at all, that was my bad. `*crawls away in shame*`

**Comment by dagochen** [comment]
there are 2 different penalties:
a) for spellLevel
b) for caster->GetLevel()

a) is correct, b) is not and was introduced with 2.x

**Comment by Phatcat** [comment]
And then they removed it altogether when removing ranks in wrath, no?

**Comment by dagochen** [comment]
Dont know about that ;) I am just interested in classic :D

**Comment by evil-at-wow** [comment]
Yup. Pactically speaking WoTLK had no downranking because spells often used a base % of your mana which was usually the same for all ranks.

Although I remember some kind of exception here and there, such as casting a Rank 1 Life Tap just on my warlock just before pulls to trigger the Glyph of Life Tap, which gave us 20% or so of our spirit as spellpower for a while. Good times.
