### ISSUE TITLE
[TBC] Very low melee damage

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#1006]
Mobs do very low melee damage on all levels, even without gear.
http://i.imgur.com/63uyf2J.jpg

**Comment by kuramajssken001** [comment]
does have a problem.
@stavaren @cala

**Comment by kuramajssken001** [comment]
@stavaren 

UPDATE creature_template set DamageMultiplier=1

**Comment by stavaren** [comment]
cheers!

**Comment by Qingle** [comment]
Is this also an issue still?

**Comment by Phatcat** [comment]
Well, it's a DB thing if anything so not really a core issue, should probably be moved to tbc-db now that issues can be raised there. I do not know how much it still applies, but I havn't heard about this getting fixed.

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/45893bfaa03f67fba5a4e5dbb0971312dab42c1b

**Comment by killerwife** [comment]
Resolved in above link.
