### ISSUE TITLE
[Wotlk] Player move flags damaged after dismount/unboard etc...

### ISSUE THREAD

**Issue by Grz3s** [cmangos/issues#1007]
**Current behavior**: 
Players cant move ...after.. unboard/dismount / exit charmed creature

**Expected behavior**: 
Players should move normaly after dismounting/leaving veh. etc.

**Steps to reproduce**:

1.  Create a Death Knight....
And start 3rd quest "Death comes from on High"
Player will control "Eye of Acherus".. Then use ability "recall.. Player will leave charmed creature ... and.. you cant move!

2.  start quest "grand theft palomino"
Player need to control stolen horse...  press "Deliver stolen horse" Player will be dismounted from horse... and you cant move! 

3. start next quest "Into the realm of shadows"
same as above... player need to bring Horsemans Horse back... Press "Horseman's Call" ...  Player will be dismounted... and you cant move!

4. start quest "Massacre at Light's Point"
Player need to control "Scarlet Cannon" .. to destroy 100 enemies... Press "Leave Vehicle" button... and player will do it... but you wont be able to move... 
Funny with this one .... is that we can jump on that Gun again.. to control it...  and  this will alow us to move controlled vehicle. (it shouldn't happen) @xfurry just fixed it few weeks ago...

I didn't check more... but im sure... that they're more....

Also... Death Knights have their mount... after dismounting it... player can move normaly. (strange)

BTW:
After relogin... player can move normaly.

**Client version**: 
3.3.5a

**Commit hash**: 

**Database version**: 
Newest UDB

**Operating system**: 
Win7

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by xfurry** [comment]
Strange, I remember that this didn't happen some time ago. 
Any idea since when did this start happening?

**Comment by Grz3s** [comment]
no idea :( ... I had few weeks off from this :(

**Comment by xfurry** [comment]
This is really odd.
I will have a look at this as soon as I have the chance. I know that there were a few changes in the core lately, but I can't recall anything that might result in such behavior.

**Comment by cyberium** [comment]
its probably due to one of my change, i reworked all controling unit situation. I remember same kind of issue that i had to fix. So i'll take this one @xfurry if you dont mind.

**Comment by xfurry** [comment]
I think I remember seeing this issue myself some time ago when I worked on Putricide and I tested the abomination vehicle. I thought it's just a local issue with that vehicle....

@cyberium thanks.
It would help if you can at least point us in the right direction.

**Comment by xfurry** [comment]
@Grz3s @cyberium this should fix the problem: http://paste2.org/Cjh4KL35
I did a brief test and it fixes the problem and it doesn't look to create any other problems.

Anyway, poke @Exxenoz in case you have time to have a quick look at the impact of my change.

**Comment by cyberium** [comment]
hum didnt wanted to push @xfurry change now, but well let's see if there is any regression on that code because it fix the issue.
