### ISSUE TITLE
[TBC] DoTs does not break Stealth/Prowl(Cat form druid)

### ISSUE THREAD

**Issue by HeyForms** [cmangos/issues#1008]
**Current behavior**: 
- Do not break the Stealth when you recive a DoT damage like Corruption

**Expected behavior**: 
- Break the Stealth when you recive any damage from DoTs while in Stealth

**Steps to reproduce**:

1. Get any DoT spell. Like Corruption, Ignite, etc
2. Use Vanish (or Stealth if you are out of combat)
3. You keep reciving damage from the DoTs but does not break the Sstealth.

**Client version**: 
WoW 2.4.3 build 8606

**Operating system**: 
Windows Server 2012 R2 64bits 64x

**Comment by SilvioDoMine** [comment]
Same problem, anyone?

**Comment by cyberium** [comment]
Could you please try it in last revision?

**Comment by SilvioDoMine** [comment]
Totaly working. Thanks @cyberium.

**Comment by HeyForms** [comment]
Working! Ty @cyberium
