### ISSUE TITLE
mmaps

### ISSUE THREAD

**Issue by madmax765** [cmangos/issues#1009]
**Current behavior**: 

**Expected behavior**: 
errors out vmap_assembler.exe
**Steps to reproduce**:

1.  ad.exe -f 0
2. vmapExtractor.exe -l
3. mkdir vmap\
4. vmap_assembler.exe Buildings vmaps
5.mkdir mmaps
6. MoveMapGen.exe

**Client version**: 
WOTLK
**Commit hash**: 
5b0f690dcf91a61a967acf772578619ccff9b749
**Database version**: 
Silvermoon Rev. 397
**Operating system**: 

Windows 10 pro 64x
[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

 I thought it was me or my pc doing this So i posted it in the help section. But seems to happen to some one else too 
http://cmangos.net/thread-7523.html 
So im posting it here now. Thanks

**Comment by Phatcat** [comment]
Yeah, for some strange reason some of us have to do the extraction process somewhat more 'manually' than others.

Now, what I do when I have to do this (which you optimally only have to do once for each core you wanna be able to run)

- Step 1. run ad.exe
- Step 2. run vmapExtractor.exe
- Step 3. open cmd.exe, change current location to wow client location (using cd\ and cd <path>) 
- Step 4. run command `vmap_assembler Buildings vmaps`
- (optional) Step 5. run command ExtractResources.sh (also in cmd - much faster than git bash in windows 10) - Tell it no to everything else than mmaps

**Comment by madmax765** [comment]
Thanks you . But i did half to make the folder mmaps. But lest I got the mmaps now.. Maybe a note can be added in to the read me folder :D
