### ISSUE TITLE
[Classic] Debian BUILD Error 

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1010]
Linking CXX executable mangosd
../game/libgame.a(Player.cpp.o): In function `Player::Player(WorldSession*)':
Player.cpp:(.text+0x20ced): undefined reference to `AntiCheat::AntiCheat(Player*)'
../game/libgame.a(Player.cpp.o): In function `Player::~Player()':
Player.cpp:(.text+0x40917): undefined reference to `AntiCheat::~AntiCheat()'
../game/libgame.a(Player.cpp.o): In function `Player::_SaveInventory()':
Player.cpp:(.text+0x412c3): undefined reference to `AntiCheat::_DoAntiCheatCheck(AntiCheat
Check)'collect2: error: ld returned 1 exit status
src/mangosd/CMakeFiles/mangosd.dir/build.make:271: recipe for target 'src/mangosd/mangosd'
 failedmake[2]: *** [src/mangosd/mangosd] Error 1
CMakeFiles/Makefile2:685: recipe for target 'src/mangosd/CMakeFiles/mangosd.dir/all' faile
dmake[1]: *** [src/mangosd/CMakeFiles/mangosd.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

CMAKE OPTION:-DCMAKE_INSTALL_PREFIX=/home/cmangos/run -DPCH=1 -DDEBUG=0

**Client version**: 
cmangos-classic
**Commit hash**: 

**Database version**: 

**Operating system**: 
Debian x64 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by sidsukana** [comment]
AntiCheat? mangos doesn't have anti cheat)

**Comment by cyberium** [comment]
yeah good try :)
