### ISSUE TITLE
Classic - Clearcasting broken

### ISSUE THREAD

**Issue by dazidkk** [cmangos/issues#1011]
Clearcasting is supposed, to reduce mana cost by 100%.

Atm Clearcasting does not, reduce mana cost with 100%.

http://db.vanillagaming.org/?spell=16870
http://db.vanillagaming.org/?spell=16246

**Comment by Phatcat** [comment]
Not only mana cost, but clearcasting should reduce any cost to 0, be it rage, energy or mana.
(I used to sport a hybrid DPS bear spec back in the day (awesome for solo) - clearcasting was part of that build)
