### ISSUE TITLE
Classic - Double CC

### ISSUE THREAD

**Issue by dazidkk** [cmangos/issues#1012]
If you polymorph a target fearing it afterwards, it results in once the fear effect ends, the target is able to move around freely even tho, the target is still polymorphed.
This seems to happen with other cc's aswell, such as blind.

**Comment by dazidkk** [comment]
Might be caused by an missing "checker", at the end of the cc. Not sure tho

**Comment by dazidkk** [comment]
Bug seems to be caused due to both void units, Feared and confused use the same way to stop the movement.
`GetMotionMaster()->MovementExpired(false);`

**Comment by Phatcat** [comment]
@Warlockbugs Again, this seems to be related to what you're working with, sort of. sorry if it's not.

But once again tagging you for pretty much the same reason as just before ;D

**Comment by Warlockbugs** [comment]
This is fixed in [CC patch] (https://github.com/cmangos/mangos-tbc/pull/114).

**Comment by Warlockbugs** [comment]
Should be fixed in https://github.com/cmangos/mangos-classic/commit/47664238b4e0e82ad0a6762beefcbf5e33c6b462.
