### ISSUE TITLE
boost error :(

### ISSUE THREAD

**Issue by hendoneh** [cmangos/issues#1016]
i have problem !! 

TBC Cmangos << 

windows 7 sp1 64bit

install boost .. and have problem with compile 

![liberror](https://cloud.githubusercontent.com/assets/3288065/17341626/b3b3c0f0-590a-11e6-8e4f-a996946ad062.jpg)

**Comment by cyberium** [comment]
There is no boost error, please search on our forum the complete install guide and recheck all your steps.

**Comment by SilvioDoMine** [comment]
@hendoneh You need to add other variable in the system named "BOOST_LIBRARY", and set to the URL: C:\local\boost_1_61_0\lib64-msvc-14.0 (assuming that your boost is installed at disk C

**Comment by hendoneh** [comment]
try that .. but again have error :(
