### ISSUE TITLE
[TBC] Warrior Devastate does not applicate Sunder Armor

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1018]
**Current behavior**: 
When a Warrior Protection uses Devastate does not applicate Sunder Armor, and the tank gives no threat to the mob.
**Expected behavior**: 
When you use Devastate should give a application of Sunder Armor to the current target.
**Steps to reproduce**:

1. Get a Warrior 70, train all spells (including Sunder Armor)
2. Put talent spec to Protection till reach Devastate
3. Use it in any mob

**Client version**: 
WoW 2.4.3 build 8606

**Operating system**: 
Windows Server 2012 R2 64bits 64x

**Comment by Appled** [comment]
OregonCore's approach could be used atleast for temporary if not for permanent fix.
https://github.com/OregonCore/OregonCore/blob/master/src/game/SpellEffects.cpp#L4653

**Comment by SilvioDoMine** [comment]
@Appled If I copy this code and compile, should work? Or I have to alter something?

**Comment by Appled** [comment]
I am not sure. There may be some mismatches in function names but other than that it should work.

**Comment by SilvioDoMine** [comment]
@Appled can you help me with that? I don't know much about c++ and cmangos. I only help others with database issues XD

**Comment by Appled** [comment]
I am quite busy with another PR but I quickly wrote this. I didn't test this ingame. As my source is abit outdated currently I wasn't able to create a proper patch file but I think you can apply it manually. Please report if it works. If it works, someone could wrap it into a PR.
https://gist.github.com/Appled/42c6f20cca32352fc7b109b9bf4fc073

**Comment by SilvioDoMine** [comment]
Totally working. It's a nice pelliative, thank you @Appled. Closing this issue.

**Comment by Appled** [comment]
That's great to hear. But you should reopen this issue so the team or a contributor can find the patch and consider is it worth to apply.

**Comment by Muehe** [comment]
@Appled Naming the file *.patch on Github Gist enables syntax highlighting for diffs.

**Comment by dazidkk** [comment]
I dont know much about the tbc core, but aint this caused due to a missing spellfamilymask?

**Comment by Lillecarl** [comment]
This issue should not be closed. And this is probably a great example of how what @killerwife 's "spellscript" system is good for.

**Comment by Lillecarl** [comment]
"// only highest rank is shown in spell book, so simply check if shown in spell book"

This is also bad, not how it should be in 2.4.3. In 2.4.3 all spells should be shown so we can cast cheaper frostbolts for slowing etc...

**Comment by killerwife** [comment]
actually, this thread is how I got to know laizerox, I will export the script soon :D 
and lillercarl, I a spell is an ability only one I shown

**Comment by Laizerox** [comment]
@Lillecarl Warrior, rogue spells have a flag to hide lower ranks in client. Mages and other classes have multiple ranks.

**Comment by Lillecarl** [comment]
@Laizerox The more you know, thanks! :)

Anyhow, i think this is a great example of where the "spellscript" system would be useful.

**Comment by Appled** [comment]
@Muehe fixed that. First time using gist to be honest.

This patch is just straight copy-paste from OregonCore, I didn't look at better solution, I just wrote it compatible with cmangos for OP.

**Comment by killerwife** [comment]
There is actually a spell attribute that tells to hide shit. And all classes can have them. But for spellscript example, id first need the spellscript system to gain tracktion, @cyberium said he is waiting for others, and others are inactive, end of story
Also i need a neat way to pass parameters from overloaded functions. Then I guess its done

**Comment by killerwife** [comment]
@Appled ill try to export @Laizerox solution today when im home from work, and we can compare.

**Comment by Appled** [comment]
@killerwife Most likely @Laizerox solution is better as I only invested time to this patch about 10 minutes, and 5 minutes of that was VS crashing :D

**Comment by Phatcat** [comment]
https://github.com/lovelol/server/commit/c80a61854def9c0d08b59bf92b4c2f219755492c

**Comment by Phatcat** [comment]
> "// only highest rank is shown in spell book, so simply check if shown in spell book"

> This is also bad, not how it should be in 2.4.3. In 2.4.3 all spells should be shown so we can cast cheaper frostbolts for slowing etc...

This is however a misunderstood comment; Warriors and Rogues have never had all their ranks displayed in the book, only the highest rank. There is no casting lower ranks for melee classes as far as I'm aware.

Pretty sure same goes for druid feral spells.

**Comment by killerwife** [comment]
@Phatcat u can close this :)

**Comment by Phatcat** [comment]
Are you sure about that one? 
https://github.com/cmangos/mangos-tbc/pull/109 hasn't been merged yet (and has merge conflicts)

**Comment by Phatcat** [comment]
Sorry, not merge conflicts, build errors.

**Comment by killerwife** [comment]
When I made it there weren't any T_T. Oh well looks like im blind.

**Comment by Phatcat** [comment]
Should be taken care of by https://github.com/cmangos/mangos-tbc/commit/89fde25ddd480e49b99c9876acd65a56c9e64cd4
