### ISSUE TITLE
[TBC] Bug on Script of Quest City of Light - ID 10211

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1019]
The NPC does not whisper the player with the speeches, just walkes. And when it was supposed to end the quest, the npc re-start walking again and the quest don't get completed.

I assume it's something with the script, becouse the text is in the database and no error appears at the console. 

I'm using the last revision of the core

**Comment by Qingle** [comment]
Does this bug still exist?

**Comment by xfurry** [comment]
I don't think that this is still an issue. On 3.x works fine.
@killerwife can confirm this for 2.x

**Comment by jimmybrancaccio** [comment]
@killerwife Would you be able to confirm if this is resolved in 2.x ? Thank you!

**Comment by killerwife** [comment]
Yes. Resolved by fixing EAI.
