### ISSUE TITLE
[TBC] Zul'Aman Chests Bugged

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1020]
**Current behavior**: 
When you kill the boss in time, you can't loot the chests of the instance.

**Expected behavior**: 
If you kill the boss in event time, you should free the prisioner and loot the chest.

**Steps to reproduce**:
1. Enter a fresh ZA
2. Start the instance event at Harrison Jones
3. Kill a boss within 20 minutes
4. You can't free the prisioner or loot the chest/chest is empty.

**Comment by BenDol** [comment]
was this progressed?

**Comment by AnonXS** [comment]
za instance code hasnt been refactored in a while, so it's likely for stuff to be broken, but you might need some additional db data for stuff to work out as intended so its not only a core code issue.

**Comment by MantisLord** [comment]
Fixed - All the chest events have been completed. Just a few additional RP scripts remain in ZA.
I'll be working on them myself in the next few weeks but if anyone has an interest in helping, please reach out to me. I can provide the necessary data and direction.
