### ISSUE TITLE
Classic - Lightning Shield

### ISSUE THREAD

**Issue by dazidkk** [cmangos/issues#1021]
If you have 2 shamans, and both use lightning Shield, it instantly procs all of the charges.

**Comment by dazidkk** [comment]
Found a fix, if anyone have the spellfamilymask for the trigger of the shield proc.
https://db.valkyrie-wow.org/?spell=26363

**Comment by Phatcat** [comment]
Was this fixed, or..?

**Comment by sidsukana** [comment]
@Phatcat https://github.com/cmangos/mangos-classic/pull/184

**Comment by Phatcat** [comment]
Ah, I see. Well, it hasn't been merged yet so let's keep this open for now.

**Comment by cyberium** [comment]
Someone can confirm its still not working? I cant reproduce.
