### ISSUE TITLE
Water walking cannot be cast on warriors [Fixed]

### ISSUE THREAD

**Issue by tbsp** [cmangos/issues#1022]
**Current behavior**: 
Attempting to cast water walking on a warrior displays "Invalid Target"

**Expected behavior**: 
Water walking successfully cast on target.

**Steps to reproduce**:

1. As a shaman with the water walking spell (546) and fish oil (17058), target a warrior and cast the spell
2. 
3. 

**Client version**: 
2.4.3 8606

**Commit hash**: 

**Database version**: 

**Operating system**:

**Comment by tbsp** [comment]
I believe this fixes the bug. In addition, water walking is now castable on priests in shadow form and stealthed rogues.

```
@@ -5297,7 +5297,7 @@ SpellCastResult Spell::CheckCast(bool strict)
                     Player const* player = static_cast<Player const*>(expectedTarget);

                     // Player is not allowed to cast water walk on shapeshifted/mounted player
-                    if (player->GetShapeshiftForm() != FORM_NONE || player->IsMounted())
+                    if (player->IsInDisallowedMountForm() || player->IsMounted())
                         return SPELL_FAILED_BAD_TARGETS;
                 }
```

**Comment by SilvioDoMine** [comment]
Working, thank you @tbsp.

**Comment by Phatcat** [comment]
If this has been fixed I'm just gonna go right ahead and close this.

**Comment by tbsp** [comment]
This isn't actually fixed in master. I changed the title to reflect that a fix was included in the issue (via a comment) because I was hoping it might get some attention and be implemented. I suppose I'll try to submit the fix as a pull request myself instead.

Sorry about that.
