### ISSUE TITLE
[TBC] Nalorakk Mobs Bug

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1023]
**Current behavior**: 
As soon as you reach the 1ª wave of Nalorakk Mobs, he comes to you with the adds and starts the boss fight.

**Expected behavior**: 
The boss should run to the 2° wave

Im using a clean and update core/database

**Client version**: 
2.4.3 8606

**Comment by SilvioDoMine** [comment]
I tried to change the UnitClass to give some immune to the boss, and the firsts mobs to be attackable. He aparrently works fine, but when all adds are dead and  he is at the final spot, I can't attack him.

**Comment by AnonXS** [comment]
UnitFlags in DB and UnitFlag remove in Script at final waypoint.

**Comment by BenDol** [comment]
Was this resolved?

**Comment by MantisLord** [comment]
Should be resolved now. Ensure you started the raid properly using Harrison and the gong event if you still have a problem similar to this one.
