### ISSUE TITLE
[TBC] Huge BUG Arcane Missiles

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1025]
**Current behavior:**
When you use Arcane Missiles, the spell hits everyone in the party of the target.

**Expected behavior:**
The spell should hit ONLY the target.

**Steps to reproduce:**
1. Requires 3 people or more, and I need be a mage with Arcane Missiles.
2. 2 people group up and leave the mage alone
3. Duel or hit one of the targets with Arcane Missiles
4. The spell will hit both.

**Client version:**
2.4.3

**Comment by kartoffelsup** [comment]
This is due to the removal of the break here: https://github.com/cmangos/mangos-tbc/commit/7b0c0b6fc787d8ca715faded6b360e6fe471a2a3#diff-b4db11cbf2813cd24b3c165885fc08a7L2144

**Comment by SilvioDoMine** [comment]
@kartoffelsup this is may the cause of unkown crashes as well? Is already on the principal repository to fix it?

**Comment by SilvioDoMine** [comment]
@kartoffelsup or I have to undo this updates to get back on normal?

**Comment by kartoffelsup** [comment]
The pull request has been merged. Can you pull from master and test this again?

**Comment by SilvioDoMine** [comment]
I'll recompile and test as soon as I wake.

**Comment by SilvioDoMine** [comment]
@kartoffelsup aparently works, I tried to reproduce the issue and it's not happening anymore. Great job.
