### ISSUE TITLE
[CLASSIC][TBC] Wyvern Sting Spell Issues

### ISSUE THREAD

**Issue by dazidkk** [cmangos/issues#1026]
Wyvern Sting, Dosent get removed on damage taken, resulting in making it a 10sec stun :p

**Comment by SilvioDoMine** [comment]
This still an issue at Cmangos-TBC.

**Comment by dazidkk** [comment]
Seems like its the mechanic effect, Sleep(asleep)
Which doesn't break on damage taken.

**Comment by jimmybrancaccio** [comment]
@dazidkk or @SilvioDoMine Can you confirm if this is still an issue?

**Comment by CabrasDaPeste** [comment]
This issue is solved, and can be safely closed now, @jimmybrancaccio.

**Comment by jimmybrancaccio** [comment]
Awesome, thank you for the update @CabrasDaPeste 👍
