### ISSUE TITLE
[TBC] Bug "Half-dead" when you get killed while casting spell

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1027]
**Current behavior**: 
When you get killed while casting a spell, you stay with 1 HP, but you can't move or recive any damage. And you can still cast damage/heal spells. This occourss too many times in PvP.

**Expected behavior**: 
When you get killed, just die.

**Steps to reproduce**:
1. Die while you're in the middle of the cast of something

**Client version**: 
2.4.3

**Comment by cyberium** [comment]
@SilvioDoMine i cant reproduce it myself. Are you able to reproduce this 100%?

**Comment by SilvioDoMine** [comment]
It's very hard to me reproduce this by myself. And I have some prints-screens, and this occour very frequently to healers and casters.
http://prntscr.com/c4uack
http://prntscr.com/c4ubce

**Comment by evil-at-wow** [comment]
If this is the same bug I've seen on old cores with holy priests not really dying, a more or less doable way to reproduce this could be the following:
* Take a holy priest (any class) but make sure you have the spirit of redemption talent.
* Jump in the lava in Blackrock, say near the elf that teleports you to Molten Core.
* You will die quickly from the lava damage, and become the spirit of redemption. When that stops, you're either dead (good) or half-dead (bad), in which case you have 1 hp and are unable to move.

You still need some luck to trigger the 1 hp state, which makes it annoying to debug, but you often needed a few tries only to trigger it.

**Comment by SilvioDoMine** [comment]
I'm searching ways to reproduce that with 100% chance. I'm also getting this while I'm dying with Last Stand with a warrior.

**Comment by cyberium** [comment]
duplicate
https://github.com/cmangos/issues/issues/462
