### ISSUE TITLE
[TBC] Battlegrounds Spirit healers sometimes does not revive

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1028]
**Current behavior**: Sometimes in the Battlegrounds, the Spirit Healer of the faction  bug, and does not revive anyone, so, everyone need to wait another 30 seconds to revive.

**Expected behavior**: 
The Battleground Spirit Healer should aways revive the players.

**Steps to reproduce**:
1. Isn't a thing that occour 100% of the time, and I didn't find a pattern to aways reproduce this issue.

**Comment by cyberium** [comment]
should be fixed
