### ISSUE TITLE
[CLASSIC] Seal of Command Spell Issues

### ISSUE THREAD

**Issue by dazidkk** [cmangos/issues#1029]
The proc dosent seem to be affected by spellpower, which it should.

http://wowwiki.wikia.com/wiki/Seal_of_Command_(old)?oldid=327126

**Comment by Qingle** [comment]
Seems to be right DB side
https://github.com/Qingle/mangos-classic/blob/master/sql/base/mangos.sql#L10087

**Comment by jimmybrancaccio** [comment]
@dazidkk Can you confirm if this is still an issue for you?

**Comment by Warlockbugs** [comment]
Spell damage bonus coefficient [is definitely in](https://github.com/cmangos/mangos-classic/blob/master/sql/base/mangos.sql#L10502). Closing this as resolved.
