### ISSUE TITLE
Classic - Auto Shoot Hunter / Wand Auto Shoot ISSUE

### ISSUE THREAD

**Issue by dazidkk** [cmangos/issues#1030]
Hunter's Autoshoot dosent stop when you deselect your target, but keeps shotting.
This happens with Wands aswell.

Another issue, is selecting a new target. 
It keeps shooting at the old target.

**Comment by cala** [comment]
I'm pretty certain this is expected behaviour on Classic, at least for wand shot and presumabely for auto shot as well.

**Comment by dazidkk** [comment]
So the only ways to stop shooting, is clicking the auto shoot again? or turn around

**Comment by dazidkk** [comment]
Pretty sure, its supposed to stop shooting on right clicking away from the target

**Comment by Phatcat** [comment]
Sorry for being late to this: https://github.com/cmangos/issues/issues/978

For all intended purposes you were gonna have to close this issue as a dublicate, but feel free to carry on the discussion on that issue. I am not sure on this, I played a druid almost exclusively in vanilla. no ranged for us.

**Comment by Phatcat** [comment]
https://www.youtube.com/watch?v=SwLjJH8LXfc&list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n 2:23
This is intended, yes.
