### ISSUE TITLE
[TBC] Server crashing Hunter Spell: Eyes of the Beast

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1031]
I'm using cmangos-tbc with the lasted tbc-db, and the server is crashing a lot lately since I updated to the last version (I was using a much older version of cmangos).

I found that the spell "Eyes of the Beast" are making the server crash when you use it, after the channeling.
I don't belive thats the only bugged spell because the crashes are frequently. Anyway, can someone think in one solution to this spell? Thx

**Comment by cyberium** [comment]
Thank but already opened -> https://github.com/cmangos/issues/issues/968
