### ISSUE TITLE
[TBC] Crashing when double login with the same account

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1035]
**Current behavior**: 
If you already have a account XX logged, and anyone connect to the same account XX, the server crashes and shutdown

**Expected behavior**: 
If someone log into a account that is already online, the person online gets kicked.

**Comment by SilvioDoMine** [comment]
Sorry, duplicate of #979

**Comment by Phatcat** [comment]
That's okay, but since this brings nothing new to the table really I'm gonna close this. 
Thanks for reporting anyways. If you experience a bug already reported you can always bump the old issue and say it's still an issue on current master. This one we're aware of, though.

**Comment by SilvioDoMine** [comment]
Sorry @Phatcat, I'm kinda new here and I'm trying to find things to make our core the better. Thanks for the tips.

**Comment by dazidkk** [comment]
Seemed like they came to a conclusion regarding only deleting the delete, in world. Which never fixed the issue for me.

**Comment by SilvioDoMine** [comment]
@dazidkk  Im using a older version of the core atm, to don't crash. When they do another update or fix, will test this issue again, with their conclusion.

**Comment by dazidkk** [comment]
Oh, so it dosent crash on the older versions?

**Comment by ulfgebhardt** [comment]
The core seems ridged in general at the moment, many crashes on several issues...

**Comment by dazidkk** [comment]
Im using the classic core, but seems to be a problem cross the cores.
Any other issues, you know of?

**Comment by ulfgebhardt** [comment]
There were like 5 Requests regarding Crashes and Similar Stuff with several Spells but i think they were reported on TBC Repo. I can definetly confirm the Duplicate Login Crash.

**Comment by dazidkk** [comment]
Hm, Thanks for the Links there's no clear explanation to whats causing these crashes tho, so i tried getting a little knowledge by asking them.
Then i can test them regarding the classic core.
Thanks! :+1:

**Comment by SilvioDoMine** [comment]
The TBC core at the moment is very unstable because of the frequently crashes, and I'm trying to report what is aparently causing the things here too. I hope we find them all.
