### ISSUE TITLE
[CLASSIC] Pet Issues With Dash

### ISSUE THREAD

**Issue by dazidkk** [cmangos/issues#1036]
If you send your pet at a target and use the pet ability dash afterwards, it registers it as an attack instead of an buff/aura.

Another issue, is auto use prowl dosent work :p

**Comment by Phatcat** [comment]
yeah, pet spell casting has issues.. lots of issues sadly. thank you for reporting.

**Comment by dazidkk** [comment]
Dunno but it seems to handle prowl, as a debuff?

**Comment by Phatcat** [comment]
I'll look into this as soon as I'm done with a bit of DB work as well as finishing some of my engineering work (that PR has been standing forever)

**Comment by dazidkk** [comment]
No worries, thanks for your time :+1:

**Comment by Phatcat** [comment]
https://github.com/cmangos/issues/issues/697

**Comment by Phatcat** [comment]
two and a half years but I got around to it eventually...

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/df77a1d5a219cf68358134e1e3d0ace81ca9350f
