### ISSUE TITLE
[TBC] Naj'entus Spine Does Not Get Removed After Right Clicking the Object

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1038]
**Current behavior**: 
When the Boss Naj'entus throw a Naj'entus Spine on a random player, and other player pick the object up, the debuff of the spine keeps 20s dealing damage and stun to the target.

**Expected behavior**: 
After other player pick the object up, should the debuff be removed with it.

**Steps to reproduce**:
1. Loggon two accounts and start a fight with Naj'entus
2. Wait him throw a Naj'entus spine
3. Try to pick up the Spine with other char and see that the debuff keeps stunning and dealing damage to the target untill its over.

**Client version**: 
2.4.3

**Operating system**: 
Windows Server 64x

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/145729745-4f7eee06-019b-4ab1-b546-f33b8f8541df.png)

spine dot goes away when go is clicked.
