### ISSUE TITLE
[TBC] Doom Blossom's of Teron Gorefiend does not despawn after kills him

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1039]
**Current behavior**: 
The immune mobs don't dispawn, and it keeps alive giving damage and stucking all players in combat.

**Expected behavior**: 
After the boss death, everything should dispawn and leave combat for all players.

**Client version**: 
2.4.3 TBC

**Operating system**: 
Windows Server 64x

**Comment by Grz3s** [comment]
check this:
```sql
DELETE FROM creature_linking_template WHERE entry = 21876;
INSERT INTO creature_linking_template VALUES
(21876, 530, 21877, 8208, 100);
```
it may be forgotten in TBC

**Comment by Phatcat** [comment]
I can tell you right now possessing stuff does not work very well in the core atm. Leads to crashes and stuff sadly.

**Comment by Grz3s** [comment]
@Phatcat 
it worked fine before.... (I can only say about Wotlk)... 
now ... if your controled creature gets aggro from anyone ...you loosing control on it... he just runs for few secs .. out of your control... ...and this repeats every moment, when you are  hit by someone :(
Basically it looks now like this:
https://youtu.be/kdSEk3BS9SU

**Comment by cyberium** [comment]
Well iam probably responsible of that, i'll check that asap but not now.
Completly new way to control creature/player on wotlk at the moment. So it need to be tested/debuged.

**Comment by SilvioDoMine** [comment]
I guess I explained wrong. I was talking about the boss on Black Temple.

**Comment by AnonXS** [comment]
http://www.wowhead.com/npc=23123/doom-blossom Doom Blossom 23123 (SD2 Backport)
http://www.wowhead.com/npc=22871/teron-gorefiend (22871) - boss_teron_gorefiend

```
DELETE FROM creature_linking_template WHERE entry = 23123;
INSERT INTO creature_linking_template VALUES
(23123, 564, 22871, 4128, 0); -- FLAG_SELFKILL_ON_DEATH, FLAG_DESPAWN_ON_EVADE
```

**Comment by AnonXS** [comment]
Reworked / Resolved here: https://github.com/cmangos/tbc-db/commit/e4555a08113beb2395899c95694a7331ce2d6843#diff-8882d83d44ad5da160640aa84df413a6R26733

But probably follow some wired on spawn movement script where they follow the mob they summon themselves by casting 40186 on spawn.
