### ISSUE TITLE
Trainer auto selection

### ISSUE THREAD

**Issue by lively158** [cmangos/issues#1040]
**Current behavior**:  Learn one spell and the highlighter disappears and if you have an unavailable spell next in line, you have to reselect the next available one 
 
**Expected behavior**: When learning a spell from a trainer the next available (green) spell is then automatically selected for you allowing you to basically spam "learn"

**Steps to reproduce**:

1. go to trainer
2. learn spells
3. hit unavailable spell

**Client version**: 1.12.1

**Commit hash**:  cfbd781

**Database version**: 

**Operating system**: win x64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Phatcat** [comment]
Gonna have to close this:
https://www.youtube.com/watch?v=SwLjJH8LXfc&list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n - 49:55

**Comment by Phatcat** [comment]
(When you learn a spell nothing should be selected afterwards, though, which we may currently be doing)
