### ISSUE TITLE
[WotLK] Server crash when fighting Ursoc

### ISSUE THREAD

**Issue by Darth-Postal** [cmangos/issues#1042]
**Current behavior**: 
Server crash when fighting [Ursoc](http://www.wowhead.com/npc=26633/ursoc)
**Expected behavior**: 
Shouldn't crash.
**Steps to reproduce**:
1. Attack Ursoc.
2. Fight for about 10 seconds.
3. Crash [mangosd.exe_[11-8_20-48-14].txt](https://github.com/cmangos/issues/files/413938/mangosd.exe_.11-8_20-48-14.txt)
**Client version**: 
3.3.5a
**Commit hash**: 
https://github.com/cmangos/mangos-wotlk/commit/05bcf17075265df2a5a6058bf6aa97789ad0b253
**Database version**: 
UDB 521
**Operating system**: 
Win7 x64 SP1

Tried it 4 times on 4 chars - 4 crashes. Same crashlog.
PS. Last time I tried to do this quest was somewhere around April and it worked fine. Maybe this will help find the issue.
PPS. Tried this on Debug build. also got a crash. Here is report: 
[mangosd.exe_[11-8_22-20-2].txt](https://github.com/cmangos/issues/files/414044/mangosd.exe_.11-8_22-20-2.txt)

**Comment by Phatcat** [comment]
Hey hey, would you look at that, a Summon effect, that looks like mine.

**Comment by Phatcat** [comment]
O.o
> 010F4BFC  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+C8E1DF
010CD59C  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+C66B7F
00F1BC72  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+AB5255
00F1710F  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+AB06F2
00F15D65  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+AAF348
00F333C8  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+ACC9AB
00F30EA7  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+ACA48A
00F1D842  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+AB6E25
00F27ADD  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+AC10C0
0072E633  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+2C7C16
00C81AAC  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+81B08F
00C8ADA3  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+824386
00C8EF9C  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+82857F
00C907A6  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+829D89
0079E283  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+337866
0053ACB7  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+D429A
007D8BF4  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+3721D7
007BA0BF  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+3536A2
007BA120  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+353703
007BA1F3  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+3537D6
007B9F65  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+353548
007D8A6D  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+372050
007B7A4A  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+35102D
007B7AD9  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+3510BC
007B7BF5  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+3511D8
007D80C2  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+3716A5
00B7533D  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+70E920
0065F7FF  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+1F8DE2
005CE359  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+16793C
0061F951  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+1B8F34
0061F155  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+1B8738
0061F352  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+1B8935
0061F1B4  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+1B8797
0061FB19  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+1B90FC
0061FA27  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+1B900A
004C35B2  00000000  ?HandleNpcAddWeaponCommand@ChatHandler@@IAE_NPAD@Z+5CB95

what the heck is going on in that creature script

**Comment by Darth-Postal** [comment]
This is from ACID:
```
-- Ursoc
('2663302','26633','0','0','100','1','3000','6000','9000','13000','11','52581','1','0','0','0','0','0','0','0','0','0','Ursoc - Cast Crunch Armor'),
('2663301','26633','0','0','100','1','10000','13000','21000','25000','11','52583','4','1','0','0','0','0','0','0','0','0','Ursoc - Cast Old God\'s Influence'),
('2663303','26633','0','0','100','1','15000','20000','50000','60000','11','52560','0','1','0','0','0','0','0','0','0','0','Ursoc - Summon Blood of the Old God'),
```
I'm 100% sure I've seen [Old God's Influence](http://www.wowhead.com/spell=52583/old-gods-influence) and I'm pretty sure I've seen [Crunch Armor](http://www.wowhead.com/spell=64002/crunch-armor) on my char during the fight before the crash.

But I'm 100% sure I've never seen [Summon Blood of the Old God](http://www.wowhead.com/spell=52560/summon-blood-of-the-old-god), so I think that's what causes the crash.

If you need any testing or more dumps, let me know.

**Comment by Phatcat** [comment]
Actually, we located and.... well... I would say fixed the crash but the higher ups would have me hanged for that. I've provided a failsafe for now. The issue had nothing to do with that add weapon stuff, but lies with the spell effect. It needs more work. basically the crash was caused by an always failing race-condition.

**Comment by Darth-Postal** [comment]
Thank you for looking into this. Should I close it then?

**Comment by Phatcat** [comment]
yes, this mob is unrelated and should be working now so you can go ahead and close it.

**Comment by Darth-Postal** [comment]
OK. Thanks.

**Comment by Darth-Postal** [comment]
I can confirm that https://github.com/cmangos/mangos-wotlk/commit/7d882c6060e97e937ea1bae192fd6d08a508e272 fixed the issue. :thumbsup:
