### ISSUE TITLE
Unknown Crash on possibly all cores (TBC and Wrath)

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1043]
I have this crash happen to me sometimes when I forcefully terminate client (alt+f4) and let the server continue running in the background, then roughly about 15 - 20 minutes later it will crash:

TBC crashlog:
[mangosd.exe_[13-8_19-39-11].txt](https://github.com/cmangos/issues/files/416692/mangosd.exe_.13-8_19-39-11.txt)

Wrath crashlog:
[mangosd.exe_[12-8_9-50-53].txt](https://github.com/cmangos/issues/files/416693/mangosd.exe_.12-8_9-50-53.txt)

I usually work on the classic core and it doesn't happen there, at least I can't find a single crash log like it for classic. I have this one for classic instead, though;
[mangosd.exe_[8-8_1-48-59].txt](https://github.com/cmangos/issues/files/416694/mangosd.exe_.8-8_1-48-59.txt)

**Comment by killerwife** [comment]
This is related to Mind control, and after using it, it causes Heap corruption. I.e. the time when it will crash depends on system. On my machine I get a crash within 4 seconds, 4 different stack traces, all of them useless.

**Comment by Phatcat** [comment]
You go ahead and tell me why it doesn't crash if I stay in game then. also why would it crash when I'm not even doing anything even remotely related to MC?

**Comment by Phatcat** [comment]
The last one, the one from classic, that could in fact be related to Mind Control as I can't tell for sure what I was doing at that time. 

I can however confirm to have been doing absolutely nothing but terminate the session on the TBC and Wrath crash logs and at least confirm those 2 to be unrelated to mind control.

**Comment by Phatcat** [comment]
Yeah, I can get this crash to happen 100% of the time (on wrath, havn't tried this specifically on tbc) by entering on my level 71 warlock and simply alt+f4'ing while ingame = instant crash with that crash log.

Am I the only one having this issue?

**Comment by kotishe** [comment]
Also have no crash log if enter on Isle of Queltanas, try reextract maps compile with debug dont help...

**Comment by Phatcat** [comment]
I'm not entirely sure by this, but it would explain why I seem to be one of the only ones to have this specific issue, and why it isn't happening to me on classic but only tbc and wrath.

My database names are not default for tbc and wrath. this is because I initially set up classic on this machine, but in order to properly work on porting my own work I needed to set up the other cores and with that I of course chose different database names as they were already taken for my classic setup.

**Comment by Lillecarl** [comment]
database names doesn't matter whatsoever. FYI :)

**Comment by Phatcat** [comment]
Then I am totally blank on this one.

**Comment by Phatcat** [comment]
Not happening anymore. Not even able to force it. Closing this if it doesn't happen again very soon.
