### ISSUE TITLE
[Classic] Crash with no log on use of .tele command

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1045]
![skaermbillede 60](https://cloud.githubusercontent.com/assets/1907820/17653118/bfae0292-628f-11e6-9034-1ed032f046cc.png)

Happened right after using `.tele light` from the ally camp in WPL. Note how I still have the Flight Master as my target from the camp in WPL.

Will look into this myself, just noting it here so I don't forget as I am currently busy with something else.

**Comment by Phatcat** [comment]
Yeah, I just had this issue happen to me on the wrath core; 

It probably has nothing to do with our code as it seems to happen because my hardware can't keep up with demand spikes from the server (which I would imagine also could happen by teleporting straight into a heavily crowded (and also scripted) area. - yes, for 6 years old hardware it's heavily crowded :p)

Happened on the Wrath branch when I used the command `.learn all_crafts` - exactly the same warning prompt saying just about the same thing before crashing the server with no log.

Re-booted it and tried doing the command again on the same char on the spot, and this time it didn't crash but the client did hang for about 30 sec - 1 min. (in between teaching all the recipies and giving you achievements)

**Comment by evil-at-wow** [comment]
I can't help but think that sounds like a race condition. Sometimes you're lucky, and sometimes you're not and the server crashes...

But things like that are usually fairly hard to prove/find, sadly.

**Comment by Phatcat** [comment]
This is unrelated to the crash but related to the scrrenshot; should we really be informing the player twice that he just recieved an item?

**Comment by Phatcat** [comment]
And to answer my own question; No. No we shouldn't.

https://www.youtube.com/watch?v=SwLjJH8LXfc&list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n
5:33

**Comment by cyberium** [comment]
cannot reproduce
