### ISSUE TITLE
Bug with loot

### ISSUE THREAD

**Issue by DescCore** [cmangos/issues#1046]
**Current behavior**: -

**Expected behavior**: -

**Steps to reproduce**:-

1. When you fly in a group loot it shows 1 item again you press another, but if you quickly clicked previous rags if not burned it remains the boss and can not pick up
2. you press RMB on the boss and when he finishes loot ie the last time you clicked, you loot it as soon as you close the menu loot the boss immediately respawn knitted and again in a circle all

Sorry My english very bad, i russian.
по русски:
1.когда ты лутаешь в групплуте сделано тут таким образом ты нажимаешь пкм на моба он показывает 1 шмотку ещё раз нажимаешь ещё одну но при этом если ты быстро нажал предыдущую шмотку если не сролили то она остаётся у босса и забрать нельзя

2. ты нажимаешь пкм на босса и когда у него заканчивается лут т.е ты последний раз нажал, вы его лутаете как только закрываешь меню лута то сразу же босс респавнится заного и опять по кругу всё

**Client version**: 1.12.1

**Commit hash**: -

**Database version**: classicdb

**Operating system**: Linux

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by DescCore** [comment]
ты нажимаешь пкм на босса и когда у него заканчивается лут т.е ты последний раз нажал, вы его лутаете как только закрываешь меню лута то сразу же босс респавнится заного и опять по кругу всё это баг 2 по русски

**Comment by Phatcat** [comment]
Gonna need the name or the id of the boss you say have bugged loot.

**Comment by DescCore** [comment]
Hello, bug 2. work for all npc, drop item quality green or better harvest 10 clicks and npc spwan/
Bug 1. testing in instnace moltencore,

**Comment by Warlockbugs** [comment]
He means that group loot roll prompts are not initiated for all items matching the threshold at once, but one item per mob loot request. One has to keep right-clicking the mob until all items are being prompted.

**Comment by Phatcat** [comment]
Oooohhhhh... Now I get it.

you only get prompted for one roll at a time even if the mob looted has several items which should be rolled for, or in other words; roll windows don't stack and neither do they 'get in line' behind the others.

(How many are they supposed to display at once? 2 or 3? - the rest should be hidden until you've clicked one of the windows away, in a one-out one-in fashion)

**Comment by DescCore** [comment]
Yes yes, and else yoir pick item on will be, and bug #2 respawn bosses you can wear for hours

**Comment by Phatcat** [comment]
@cyberium I'm pretty sure I've seen you work on loot. Could it be related to some of your changes?

**Comment by cyberium** [comment]
iam pretty sure that was working as intended before. So i may (or someone) introduced that regression somewere.
Thank i'll look on it.

**Comment by DescCore** [comment]
respetcted ciberium check the bug and fix please

**Comment by DescCore** [comment]
i tested bugck now, it works help please fix bug

**Comment by DescCore** [comment]
@cyberium your you can fixed a bug? or call somebody who can help.

**Comment by DescCore** [comment]
@Warlockbugs your read a bugs?

**Comment by Phatcat** [comment]
@DescCore Please don't be that impatient.

**Comment by DescCore** [comment]
@cyberium  thanks for fix
@Phatcat sorry, thanks
