### ISSUE TITLE
[Wrath] Mind Control bugs

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1047]
~~Bug 1:~~ Solved.
~~- Possessed creatures are not updated to run but instead keep walk speed of the mob. Doesn't matter if the mob is running as you mind control it, as soon as you possess it, it will be set to walk speed instead of run speed.~~ 

~~Bug 2:
- Not able to attack neutral mobs (can neither attack the wolves nor other defias)~~

~~Steps to reproduce:
1. Create a human priest.
2. Enter the world with said human priest.
3. Skip cutscene and enter command `.learn 605`
4. Cross the water and pick a random Defias mob
5. Cast Mind Control on said Defias Mob.
6. Profit.~~

~~Bug 3:~~ Solved.
~~- Possessed mobs will run away in fear at low health, while you still possess them of course~~

~~Steps to reproduce:
7. On that same priest, use command `.level 20` and `.tele molsen`
8. Get close to and possess a Defias Trapper with Mind Control.
9. Let other mobs get you down to low health.
10. Profit.~~

~~(and two small ones that have already been reported and have their own issues on the tracker already; moving further away from the player with the possessed mob than the initial spell check range will cancel the channel, and so will attacking anything (only by melee - you can cast possessed spells fine it would seem) - the broken attacking seems to be on my part since that very much has to do with both PetHandler and PetAI so I will do anything I can to help solve the issue)~~

**Comment by kuramajssken001** [comment]
https://github.com/cmangos/issues/issues/1002

**Comment by Phatcat** [comment]
Yeah, I guess, but this is really only for Wrath. Mind Control doesn't crash on Wrath as the systems are not the same across the cores.

**Comment by Phatcat** [comment]
Solved by latest changes to mind control.
