### ISSUE TITLE
[Classic] A Crash from isVisibleForInState

### ISSUE THREAD

**Issue by kuramajssken001** [cmangos/issues#1048]
[mangosd.exe_[16-8_9-10-52].txt](https://github.com/cmangos/issues/files/419602/mangosd.exe_.16-8_9-10-52.txt)

 Hi,Guys

I don't know how this is caused.

**Comment by Phatcat** [comment]
sounds like it's yet another unconditioned use of a pointer variable which may be null. Will look into this.

**Comment by cyberium** [comment]
cannot reproduce, we need more info.
