### ISSUE TITLE
[TBC] Druid Combo Points with Grounding Totem

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1051]
**Current behavior**: 
When the druids uses spells that generate combo point such Mangle and Clawn while the target are with Grounding Totem, the combo points may disappear from the target randomly.

**Expected behavior**: 
The combo points should keep at the target.

**Steps to reproduce**:
1. Get a equipped druid with high chance of critical
2. Use mangle or clawn on a target that have the buff Grouning Totem
3. When the spell Mangle or Clawn crits (yellow indicator) the combopoints resets.

**Client version**: 
2.4.3 8606

Video of the issue: 
https://www.youtube.com/watch?v=_zcKV7tXcy0&feature=youtu.be

I was looking methods to reproduce this issue 100% and I think is something connected to the Critical of the spells that generate combo points, because this bug appears when this spells crit.

**Comment by kartoffelsup** [comment]
This is due to the Talent 'Primal Fury' which triggers spell -> 16953 on criticals (1 extra combo point on current target). It matches:
`if (spell && (spell->m_spellInfo->DmgClass == SPELL_DAMAGE_CLASS_NONE || spell->m_spellInfo->DmgClass == SPELL_DAMAGE_CLASS_MAGIC))`
in SelectMagnetTarget. I'm guessing there is a missing Attribute/Flag check somewhere. :/

**Comment by SilvioDoMine** [comment]
I thoutgh thats too. But even when I reset the talents, the issue keep happening. Anyway, await if someone knows how to temporarely fix it.

**Comment by Warlockbugs** [comment]
There was a bigger issue with talents like this, it was fixed in https://github.com/cmangos/mangos-tbc/commit/2a16767e8e27b7bb4a1eaf3f3994b4fadb3c3564. Please, re-check if this affected your issue.

**Comment by jimmybrancaccio** [comment]
@SilvioDoMine Do you have the bandwidth to further test this and confirm if it's resolved?

**Comment by CabrasDaPeste** [comment]
This issue is fixed and this can be safely closed now, @jimmybrancaccio.
