### ISSUE TITLE
Random possible bugs

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#1053]
I recently stumbled upon a server changelog from a private server and as a matter of fact I know that they have partly a version of CMaNGOS. I am sure some of those bugs are present on here as well.

https://tbc-twinhead.twinstar.cz/?fixreport=show-set&id=16

It is for education purposes only, I dont wanna advertise anything. I just know someone might be interested in fixing them, @WarlockBugs maybe. I will definitely take a crack at them myself as well.

**Comment by SilvioDoMine** [comment]
This would be a HUGE advance for us.

**Comment by Warlockbugs** [comment]
Some of this are already fixed and waiting for a merge or already merged, e.g. spell coeffs. Some are incorrect, e.g. CoR doesn't remove fear, but disables fleeing (A try-hard warlock can juggle feared mob to prevent it wandering too far away).

**Comment by AnonXS** [comment]
this is not really an issue report and can be closed.

**Comment by jimmybrancaccio** [comment]
Closed as per above comment. Please create a new case if there are any further issues.
