### ISSUE TITLE
[CLASSIC] Quality Control Against Joana's 1 - 60 Leveling Guide [Video 1/54]

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1054]
https://youtu.be/SwLjJH8LXfc?list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n

I will be opening 1 ticket per video only, to try and keep it at a minimum. I will maybe make duplicate reports throughout the series but I'll try to keep it to a minimum.

1:22
There is no LocalDefense (O.o ?) but instead a WorldDefense in vanilla? - I don't recall this at all.
(Pretty sure the /sky channel that is joined is for an addon, as that channel is pushed to /4 on a later relog, and general rightfully takes up /2, and then WorldDefense takes up spot /3 ...
(can be seen in video 2 at around the 54:11 mark)

Edit*: I tried looking into this but couldn't find where default channels are set for new players.

5:33
~~We should not be informing the player twice in the message log that he just recieved a quest reward, which we currently do.~~ fixed

9:30
~It should not say 'interrupted' when a target gets too close if you you get interrupted mid-shot while you have auto shot activated still, it should rather say 'target is too close'~

~Edit*: This happens because we only handle interrupting auto shoot with one generic message, we at least want interrupted, target too close and target too far away', all 3 are needed specifically for hunters ranged auto shoot.~ fixed

34:22
Around this area there is a bugged spot on cmangos classic (mobs will constantly keeps going in combat with you just to go evading right after) - seems to be related to pathing inside that cave on some spots as moving away from that spot allowed the mobs to path to me (I have mmaps enabled)

41:27
Notice how the first auto shot is taking longer than the second auto shot, and how the second (the interrupted, but still actually fired) auto shot; notice how smooth the transition from firing to standstill is; it is in stark contrast to current cmangos where we switch unnaturally from one animation to the other; we need to do a transition.

**Comment by Chaosvex** [comment]
"There is no LocalDefense (O.o ?) but instead a WorldDefense in vanilla?"

Patch 0.8 (http://wow.gamepedia.com/Patch_0.8)
- Players rank 11 or higher can now chat in the WorldDefense channel.
- "The "zone under attack" messages are now in two separate chat channels. By default they are both off; to join either type /join LocalDefense and /join WorldDefense."

Patch 1.6.0 (http://wow.gamepedia.com/Patch_1.6.0)
- "The WorldDefense and LocalDefense channels will now display your rank as well as your name when chatting."

**Comment by Phatcat** [comment]
Yeah, watching the video indicate that WorldDefense is on by default. 
On cmangos we have LocalDefense on by default, so under any circumstance it's wrong.
I didn't know youi had to be a certain rank to actually speak in WorldDefense, that comes slightly as a surprise.

**Comment by kartoffelsup** [comment]
> Players rank 11 or higher can now chat in the WorldDefense channel.

Sounds more like a bugfix. As in: Everyone was able to join WorldDefense except Players at Rank 11 or higher.

**Comment by Chaosvex** [comment]
It wasn't, it was rank 11+ only.

**Comment by Phatcat** [comment]
> Furthermore, also notice how her bow attacks are reset every time she fires using an instant attack; on current cmangos we do not reset timers so we fire an auto shot almost immediately after the instant shot; this error may also apply to instant melee attacks.

It was: https://github.com/cmangos/issues/issues/1069
