### ISSUE TITLE
[Classic] DetailsEmote not working

### ISSUE THREAD

**Issue by ThePlaform** [cmangos/issues#1055]
**Current behavior**: 
Quests with DetailsEmote does not play emotes on npcs.
**Expected behavior**: 
DetailsEmote should play emotes on npcs when showing the quest text.
**Steps to reproduce**:
1. Goto Gwennyth in Auberdine (.go creature 39063)
2. Click on quest "Washed Ashore"
3. NPC should play the emotes specified in quest_template.

**Client version**: 
1.12.1

**Comment by HarTstaRx** [comment]
It seems it happens with all the quests, or at least not exclusively with that one. "Worgen in the Woods" 4/4 fails also on reproducing DetailsEmote1

**Comment by HarTstaRx** [comment]
Can it be related to [this commit](https://github.com/cmangos/mangos-classic/commit/276404c891c74ade417cdd52ee8fe05a899a6684)? As far as I see there is some code commented out on GossipDef.cpp that seems related to DetailsEmotes. 

Can someone else shed some light into this?

**Comment by cyberium** [comment]
should be fixed by https://github.com/cmangos/mangos-classic/commit/29596f8f1c4c7344b162b04b42dd5822762ac600
