### ISSUE TITLE
[TBC] Can't transfer masterloot and other loot issues.

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1058]
----

**Comment by evil-at-wow** [comment]
The current behavior sounds correct. I'm not sure what to make of the bold part. Do you mean that other players can't even look at the loot?

What I mean with 'it sounds correct' is that the moment a creature dies, its loot policy is set in stone. Changing it after the creature dies will not change who can see or get parts of the loot of the dead creature.

So to clarify with the master looter example: if a boss dies while character X was master looter, only X will be able to hand out loot for that boss, even if you change loot settings after the boss died! So if you then change the master looter to character Y, it is still only character X that will be able to hand out loot for the boss, but it will be character Y that will be the one able to hand out loot for all bosses you kill from that point on.
