### ISSUE TITLE
Hunters don't have Parry Skill on TBC

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1059]
**Current behavior**: 
Hunters don't have PARRY skill, even if they are Survival with Deflection (which increases the parry chance).

**Expected behavior**: 
They should have parry, to use spells like Counterattack and Deterrence.

**Client version**: 
2.4.3 TBC 8086

**Comment by dazidkk** [comment]
Aint this a db issue?

**Comment by Phatcat** [comment]
This is not a core issue, skills are not hardcoded into the core, they're loaded from the db. 
You need to talk to the TBC-DB team @TBC-DB (I can however confirm this, hunters do miss the parry skill which they should be able to learn from their trainer at level... 6 or 8 I think... should be somewhat easy to look up. They learn it 2 levels later than the regular melee classes, that's what I remember reading at least.)
closing this as it's not a core issue.

**Comment by killerwife** [comment]
Yes, slow updates are being done but XS hasn't devved in a month due to IRL stuff. Eventually we will get there.

**Comment by Phatcat** [comment]
You guys should consider opening up issue tickets for TBC-DB.

**Comment by Phatcat** [comment]
http://wowwiki.wikia.com/wiki/Parry?oldid=1054970 don't listen to me about the levels, I was all wrong on that one.
