### ISSUE TITLE
[CLASSIC] NPC's Guardian Pets Despawn on Caster Death

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1063]
**Current behavior**: 

When a NPC summons a guardian pet, the pet is despawned as soon as the NPC dies.
I thought this have been fixed recently, at least I know I tested a PR with this fixed, but it may not have been pushed or it may have been removed. 

**Expected behavior**: 

When a NPC dies, its guardian pets should remain until they are killed or the spell duration expires.

**Steps to reproduce**:
1. `.npc add 10416`
2. attack the NPC and wait for the NPC to summon one or more guardians 
3. kill the NPC (`.die`): the guardian pets are removed AND the guardian pets the NPC summons on death are spawned and remove instantly: they should all remain there and in combat

**Client version**: 

Classic 12.1

**Commit hash**: 

https://github.com/cmangos/mangos-classic/commit/4c176a3c3f07a3a873998455e3c9d32f412d4192

**Database version**: 

Classic DB v1.6.5

**Operating system**: 

Mac OS X 10.6

**Comment by Phatcat** [comment]
Yeah, I have noticed this too.
To the best of my knowledge I very much believe this call to despawn is external. Also going by the flow of the AI selector, NPCs minions actually never even use PetAI, they use other AIs... this is by the way why I never got anywhere by adding evade functionality into the PetAI...
It's certainly not something I've introduced (at least not on purpose) because I remember it back from working on the initial pet patching. You specifically giving me great feedback on how they'd behave after their master had died...

**Comment by killerwife** [comment]
Sounds like a good idea to add Guardian AI, since PetAI users cant exist without owner afaik :) (at least thats how I understand PetAI)

**Comment by Phatcat** [comment]
Cyberium is actually doing some initial work on a GuardianAI, so.. you called it ;)

**Comment by killerwife** [comment]
Makes sense.

**Comment by Phatcat** [comment]
Yeah. Player's guardians weren't working if they had EventAI set either, so hopefully it can become the sort of general AI for all minions not controlled by the player.

**Comment by xfurry** [comment]
Guardian pets are considered PetAI in the current code.
GuardAI is assigned to creatures who are defined as Guards (city guard).

Usually, pets won't be assigned to eventAI, however they can be assigned to SD2.
I think there is a reason why PetAI should come first, compared to eventAI.

```c++
CreatureAI* selectAI(Creature* creature)
    {
        CreatureAI* scriptedAI = sScriptMgr.GetCreatureAI(creature);
        if (scriptedAI)
        {
            // charmed creature may have some script even if its not supposed to be that way (ex: Eye of Acherus)
            if (creature->isCharmed())
                return scriptedAI;

            // Allow scripting AI for normal creatures and not controlled pets (guardians and mini-pets)
            if (!creature->IsPet() || !static_cast<Pet*>(creature)->isControlled())
                return scriptedAI;
        }

        CreatureAIRegistry& ai_registry(CreatureAIRepository::Instance());

        const CreatureAICreator* ai_factory = nullptr;

        std::string ainame = creature->GetAIName();

        // select by NPC flags _first_ - otherwise EventAI might be choosen for pets/totems
        // excplicit check for isControlled() and owner type to allow guardian, mini-pets and pets controlled by NPCs to be scripted by EventAI
        Unit* owner = nullptr;
        if (creature->IsPet() && ((Pet*)creature)->isControlled())
        {
            Unit* controler = creature->GetOwner() ? creature->GetOwner() : creature->GetCharmer();
            if (controler && controler->GetTypeId() == TYPEID_PLAYER && controler->isAlive())
                ai_factory = ai_registry.GetRegistryItem("PetAI");
        }
        else if (creature->IsTotem())
            ai_factory = ai_registry.GetRegistryItem("TotemAI");

        // select by script name
        if (!ai_factory && !ainame.empty())
            ai_factory = ai_registry.GetRegistryItem(ainame.c_str());

        if (!ai_factory && creature->IsGuard())
            ai_factory = ai_registry.GetRegistryItem("GuardAI");
```

**Comment by Phatcat** [comment]
guardian pets only use pet ai if their owner is a player. i dont know how you got guards mixed into this?

**Comment by cyberium** [comment]
Yeah it was a reason to set PetAI, it was the most accurate at that time.
Iam having an almost working GuardianAI wich will be far better just because we'll be able to use EventAI for Guardians pet. So each Guardian reaction will be implementable.
The thing is EventAI is actualy designed for creature reaction. So there is some adjustement to do to make it also useable for Pet.

At my point of view (tell me if iam wrong) a guardian pet (and btw what is the difference with a protector pet?) is like a wild pet. I mean its a creature by its own just follow its master and have some abilities. So its a pet that can have threatlist and do almost what it want. Thats why i think EventAi is perfect for that.

actual result

[![Timbermaw Ancestror](https://img.youtube.com/vi/egEHQ5VuOAw/0.jpg)](https://www.youtube.com/watch?v=egEHQ5VuOAw)

**Comment by Grz3s** [comment]
:+1: 
This is good news @cyberium ...
EventAi allow us to give texts on spawn etc for guardians.. also they can use abilities etc...or do a special reaction (req for quests -- example //do smth on spell hit)
About despawn issue... eventAi wont handle it...maybe update in your patch...if owner dies... they will despawn ... 
 I would love to test your patch on this quest:
https://github.com/unified-db/Database/issues/90

**Comment by Phatcat** [comment]
@cyberium We want all creature's pets to act like that as all pets that are not controlled player pets should 'have a mind of their own', such as you explained.

**Comment by cyberium** [comment]
Actual state
[![Q11611](https://img.youtube.com/vi/KNRo1E6elcw/0.jpg)](https://www.youtube.com/watch?v=KNRo1E6elcw)

**Comment by cala** [comment]
I'm bumping this issue as it is still active and make some fights far easier than they should.

**Comment by Warlockbugs** [comment]
Is there a way to see if guardian should be despawned or stay in the world? I can imagine there are exceptions to this rule.

**Comment by cala** [comment]
To my knowledge, guardians always despawn when their spawn duration (from spell template) expires*. I can't think of generic exceptions to this rule (at least in Classic). There are possibly some bosses who summon guardians with specific despawn rules but I think this case should be handle in bosses script and not forced into a generic rule for guardians. 


* I have to check if a spell with infinite duration exists and investigate the related guardian if so.

**Comment by Tobschinski** [comment]
Pretty sure they never de-spawn in combat, unless explicitly done so. At least a handful of guardians never did when I checked their behavior about a year ago.

They de-spawned when the master was dead / timer expired and the creature returned home.

**Comment by cala** [comment]
> They de-spawned when the master was dead / timer expired and the creature returned home.

Unless I misunderstood your sentence, there is probably some rule about this because if guardians despawn when their master dies (actual core behaviour, and wrong in my opinion), we will never be able to have correct behaviour for [Bile Spewer](http://www.wowhead.com/npc=10416/bile-spewer#comments) that releases 4 guardians by the time of its death. In current core, the spell is cast, but does nothing as master is dead (possibly the guardians are removed as soon they are added to the world, we may need to check).

**Comment by cala** [comment]
... or we need to make them enter combat on spawn. I re-read the discussions of the Pet patch from @Phatcat and we specifically discussed this point: https://github.com/cmangos/mangos-classic/pull/124#issuecomment-221848649
(the whole conversation may be worth re-reading)

**Comment by Tobschinski** [comment]
The Bile Spewer were indeed one of the creatures I checked, Bile Slimes are in combat with the players.

**Comment by AnonXS** [comment]
http://www.wowhead.com/npc=784/skullsplitter-beastmaster#comments
http://www.wowhead.com/npc=756/skullsplitter-panther#comments

Carnagefiend on 2009/08/10 (Patch 3.1.3)
These things are annoying in general. With their masters you get a nice two for one battle ahead. If you get a bunch of these on you with their masters, get ready to have to kill the troll and their equally beefy pets afterwards as a reward. Not only that, but they cannot be looted OR skinned.

By Smilodon (7,345 –  1·14·33)  on 2008/09/22 (Patch 3.0.1) |   |  
These guys can call their pet during battle even after you have already killed it! So do the wise thing and kill the Beastmaster first. The pets DO however give full and separate experience for their level (And they should as they are no cakewalk), so if you are on an EXP grind feel free to kill the pet first.

By dasnicholas (128 –  0)  on 2007/10/31 (Patch 2.2.3) |   |  
Pet's of NPC's do not drop anything....


By Gammaray (370 –  5)  on 2008/05/21 (Patch 2.4.2) |   |  
For some reason these panthers don't seem to be skinnable.

---

Maybe despawn is related to wether they grant xp/loot/can be skinned/ can be resummoned during combat/ how beefy they are etc.

**Comment by Phatcat** [comment]
> I re-read the discussions of the Pet patch from @Phatcat

And I re-tested the 3 cases you did back in the day. I can say there's already a slight regression; 

> if caster is killed: if pet has AI: it keeps on attacking the target, which is OK. It pet has no AI it remains stuck which is wrong, it should auto-attack.

Now has become

if caster is killed: pet despawns.

This is not intended and we can realize that quite easy by taking a look in Joana's leveling guide right around here; https://youtu.be/x9M61jaHFVM?t=331 (5:31) that when the master is dead then the pet will stay alive and keep fighting.


For case 2

Regarding the whole should guardians pets (those summoned through SPELL_EFFECT_SUMMON_GUARDIAN) despawn when the master dies, here is a rather 'generic' mob with very generic guardians spawned, according to a comment on allakhazam, they should NOT despawn when the master dies, and this is a mob who will spawn endless waves of this guardian, so this would be one of those ideal mobs to have their guardians despawned on master death, yet that is not the case;

> Carry some EZ Thro **after you kill swarmer pop it** and Drop it on yourself works wonders on the little buggers

https://web.archive.org/web/20060515161108/http://wow.allakhazam.com:80/db/mob.html?wmob=5457

Case 3 seems fine, If the player dies, the guardian is despawned, If the guardian has an ai in eventai it will be used, all seems to be as intended.

**Comment by AnonXS** [comment]
how it should work: 

https://www.youtube.com/watch?v=r_o2eCTAeSA

https://www.youtube.com/watch?v=szdvVx7oNxE

https://www.youtube.com/watch?v=Ou6BXj7YfNQ

https://www.youtube.com/watch?v=9KPsXblEGO0

**Comment by Phatcat** [comment]
I think I've found why all guardians are despawned on death..

```
void Unit::SetDeathState(DeathState s)
{
    ...
    RemoveGuardians();
    ...
}
```

https://github.com/cmangos/mangos-classic/blob/18908dd604d6474d50a95f633b0e517c4cf7565d/src/game/Entities/Unit.cpp#L7875

**Comment by Phatcat** [comment]
Yeah, I've solved this locally, just polishing then I'll open a PR.

**Comment by cala** [comment]
Closed by 
https://github.com/cmangos/mangos-classic/commit/95e4931316804f93256c9cd87761abb214edc5e9
Thanks @Phatcat !

**Comment by AnonXS** [comment]
memo: Need to do a new issue for "temp" guardian respawn behavior

**Comment by Phatcat** [comment]
Also need to open new issue(s) explaining some of the other issues with creature's pets/guardians/wild summons.. or maybe just update https://github.com/cmangos/issues/issues/931
