### ISSUE TITLE
[CLASSIC] Creatures Bug Out When Switching Targets While Affected by Poly/Blind/Fear etc...

### ISSUE THREAD

**Issue by NosFade** [cmangos/issues#1064]
This issue has been reported before: #243  #923 but I believe it hasn't been properly explained.

**Current behavior**: 
This bug happens while a creature is affected by crowd control abilities such as polymorph, blind, scatter shot & fear that cause it to enter confused movement state.

If the creature changes targets either because of a change in threat (caused by a healer for example) or being taunted it will immediately (while still being technically affected by CC) stop its confused movement and heads directly for the new target with top aggro. From that point on it will not attack or cast spells on any target even after the CC has expired. It will simply follow its target and sit there until killed.

**Expected Behaviour**:
Creature should continue updating threat list while crowd controlled but not change its movement until CC is finished.

**To Reproduce**: 
1. Get a crowd controller and a healer.
2. Cast Polymorph/Scatter Shot/Fear/Blind on a creature
3. Heal the crowd controller (must be damaged to gain threat). The healer should now have top aggro.

**Comment by Warlockbugs** [comment]
Please, check the behavior now after https://github.com/cmangos/mangos-classic/commit/47664238b4e0e82ad0a6762beefcbf5e33c6b462.

**Comment by katz1** [comment]
@Warlockbugs 
I am still experiencing this issue. I just finished deadmines with 3 mages and the polymorphed mobs often went inactive after the poly was over.

**Comment by w5860363** [comment]
@katz1 This is another instance of BUG in which the human spirit will not be transferred to another target even if the player uses the spell  https://github.com/cmangos/mangos-classic/commit/47664238b4e0e82ad0a6762beefcbf5e33c6b462 update https://github.com/mangoszero/server/blob/81394c33414e045b830437e3a414de6f3e081d4d/src/game/Object/Unit.cpp#8616 Be deleted

**Comment by w5860363** [comment]
Maybe it's a https://github.com/cmangos/mangos-classic/commit/00f8b5ee622269f3aee362101c989fc0fa65cb83 problem
@Warlockbugs

**Comment by Warlockbugs** [comment]
Fixed some time ago with rewrites of both CCs handling and AI.
