### ISSUE TITLE
[Crash] On unboard passengers from vehicle

### ISSUE THREAD

**Issue by xfurry** [cmangos/issues#1066]
**Current behavior**: 
Core crash on passenger unboard from vehicle.
Somehow, changing the combat movement behavior and initializing movement, while the passenger isn't fully unboarded yet, triggers a crash.

**Backtrace**:
http://paste2.org/0ntJUBLX

**Steps to reproduce**:

1. .go object id 194914
2. walk around the instance to make sure that the grid is loaded
3. wait for 5-10 min
4. crash happens

**Client version**: 
3.3.5a
**Commit hash**: 
https://github.com/cmangos/mangos-wotlk/commit/adc30e5760df53064824d6a89e0311c5a3118ec9
**Database version**: 
https://github.com/unified-db/Database/commit/d8d94465d5fa6520d358ccb946c561b3cc15a007

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Phatcat** [comment]
confirmed. Just reproduced on latest master.

5 - 10 min? It took my server more than an hour -.-

my char had even logged out and I was in character selection screen when the crash finally kicked in. same backtrace pretty much: https://gist.github.com/Phatcat/01e2c6508eab519091269c826809654f

**Comment by cyberium** [comment]
Ok, from the crash log its not due to latest change in core.
So i cannot reproduce it, but its maybe for reason in your title you refer to Vehicle unboard. Where do you see such vehicule? I see the big transport only :/

Could you precise that?

**Comment by Phatcat** [comment]
I couldn't find no vehicle either, and I never boarded nor unboarded anything and the crash still kicked in for me.... after my char had been afk and logged out for quite some time, though..
