### ISSUE TITLE
[TBC] Talent Improved Retribution Aura Doesn't Work

### ISSUE THREAD

**Issue by cooler-SAI** [cmangos/issues#1067]
**Current behavior**: 
Paladins with Talents Retrebution don't have bonus points with Talent - Improved Retribution Aura
Nothing happens when you have 25% bonus or 50% Bonus in Talents - Aura do base attack points

**Expected behavior**: 
Improved Retribution Aura Talent should make Bonis Damage points to NPC

**Steps to reproduce**:
1. Create Paladin
2. Make Retribution Talent = Improved Retribution Aura
3. Kick any NPC

**Client version**: 2.4.3

**Commit hash**: https://github.com/cmangos/mangos-tbc/commit/78b02eaa0671a0107f4c2ccf20170c55aa6201a4

**Database version**: https://github.com/TBC-DB/Database/commit/a38dbd07f5ee604162507119b6c890dac5d01e05

**Operating system**:  Windows 7

**Comment by Qingle** [comment]
Doesn't seem to exist in SpellMgr, unless its stored somewhere else.
Anyone confirm?

**Comment by al3xc1985** [comment]
@killer i think is working. If you don't remember fixing it, leave it on me to test it tonight

**Comment by al3xc1985** [comment]
I checked that one and it ia working perfect
@killerwife can be closed
