### ISSUE TITLE
[TBC] Crash when returning a pet charmed

### ISSUE THREAD

**Issue by Poloolop10** [cmangos/issues#1068]
**Current behavior:**
The server crash when the player return a pet charmed.

**Steps to reproduce:**
Spell Enslaved a demon or quests for learning taming beasts for the hunter ...
All in rapport with spellAura: Mod Charm

**Client version:** 2.4.3

**Commit hash:** cmangos/mangos-tbc@78b02ea

**Database version:** TBC-DB/Database@a38dbd0

**Operating system:** Windows 7

**Comment by SilvioDoMine** [comment]
The hunter spell to controll the pet still crashing the tbc too. I don't know if have any problem with this part of pet system.

**Comment by Poloolop10** [comment]
Before rework pet system, i'm sure that worked. I try to have a crashlog.

**Comment by cyberium** [comment]
Confirmed i'll push a fix soon.

**Comment by Phatcat** [comment]
https://github.com/cmangos/mangos-tbc/commit/839ffa6cc212757faa6448c544b514db2f6aae1a should have taken care of this.

**Comment by SilvioDoMine** [comment]
@Phatcat, this could fix the pet eyes of the beast there are currently crashing the cmangos-tbc?

**Comment by Phatcat** [comment]
It has. Tested it myself before closing this. Eyes of the beast should work. Maybe not perfect, but no crashing on possessing anymore.
