### ISSUE TITLE
Melee Issues

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1069]
## Bug 1: Melee Auto attack stops after miss on player

Pretty much speaks for itself, easy to reproduce.

Open up 2 clients.
Make a char on each client of opposing factions.
have the two players meet up in the world and enable pvp on both
have 1 player start hitting the other. If he misses, he will stop attacking.
## Bug 2: Instant melee spells trigger an attack instead of resetting it

Again, speaks a bit for itself, even easier to reproduce than bug 1

Make a rogue
Engage in melee and use sinister strike a couple of times

**Comment by Swater96** [comment]
Regarding #2 in the case of Hunters, multi-shot and arcane shot add an extra free shot in the shoot cycle so if I understand your report correctly I believe this behavior to be working as intended on cmangos.

**Comment by Phatcat** [comment]
https://github.com/cmangos/issues/issues/1054 -> https://youtu.be/SwLjJH8LXfc?list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n
> 41:27
(...) notice how her bow attacks are reset every time she fires using an instant attack; on current cmangos we do not reset timers so we fire an auto shot almost immediately after the instant shot; this error may also apply to instant melee attacks. #1069

**Comment by Swater96** [comment]
https://youtu.be/FaV6oAteJGI?t=2h56m58s 

Point still stands.

**Comment by Phatcat** [comment]
You're right, I am blind -.- thank you for correcting me.
