### ISSUE TITLE
[TBC] Spell Animations Not Displayed on Item Usage

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#1070]
Current behaviour:

Player uses Item ID 31763 and the "player animation" is shown, but the "projectile animation" isnt shown.
When spell is cast manually using .cast 38782, the animations are shown properly.

Expected behaviour:

In both cases, animations should be shown the same way.

Way to reproduce:

Go to deaths door zone in Blades edge mountains.
.quest add 10910
.gm on (because mobs are invisible in public TBC-DB, if you remove the invis EXTRA_FLAG in DB not needed)
use item in bag, and compare to .cast 38782

Tested on clean mangos-tbc with current TBC-DB.

Few important notes:

I tested changes on SMSG_SPELL_GO, and SMSG_SPELL_START, which resulted in nothing. In sniff castflag 0x08 was used, and was tested in both these packets, to no avail. Also tried shifting packet insides around, which did nothing but break the spell even more.

My guess is that like with GO loot window disappearing, this is related to some sort of packet order problem. Currently we do the following: CMSG_USE_ITEM, SMSG_SPELL_START, SMSG_SPELL_GO.

Welcome any advice. Since this is related to basically everything, gonna tag appropriate people. Also anyone with different versions, please test it on classic/WotLK.

@cyberium @Laizerox @Fabi @xfurry @namreeb

**Comment by AnonXS** [comment]
Seems to be working fine now. (Animation + Script)

**Comment by BenDol** [comment]
Confirmed this is working on the latest TBC core/db
