### ISSUE TITLE
Less effective spells override more powerful ones

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1073]
Also mentioned briefly here; https://github.com/cmangos/issues/issues/950 (I thought it was about time it had its own ticket)

**Current behavior**: 

You are able to override buffs with less effective buffs.

**Expected behavior**: 

You should not be able to apply a less effective buff on a target if it overrides a more effecient one from the same spell family (ie, with a strong scroll of intellect active, a low level mage cannot buff you arcane intellect). 

It should show an error stating something like "A more powerful spell is already active".

This even goes for same ranked spells, as in if a healing over time spell is in effect with a higher +healing bonus than what another player tries to casts then it won't apply it. This I remember very well from healing back in vanilla.

**Steps to reproduce**:

1. cast rank 2 arcane intellect on a player
2. cast rank 1 arcane intellect on that same player right after

**Comment by Warlockbugs** [comment]
This is already fixed as a part of my work on auras rewrite for TBC, as well as being able to overwrite buff amplified by talents. Its currently being tested and polished.

**Comment by Phatcat** [comment]
Well that is just music to my ears. Mucho <3

**Comment by Warlockbugs** [comment]
Almost complete in:
https://github.com/cmangos/mangos-tbc/commit/f14a867aa666df8869f9cf8d37ae654389d35ba9
https://github.com/cmangos/mangos-classic/commit/0206d01e4c31ae1a0795c191f60615bb25829277
WoTLK port is not finished yet as it needs more groundwork done for partial effect application. If you would like to have a carbon copy of TBC for WotLK as a temporary transitional but functional aura stacking, let me know.
