### ISSUE TITLE
[TBC] After frost nova, movements npc bug

### ISSUE THREAD

**Issue by Poloolop10** [cmangos/issues#1076]
**Current behavior**: 

After cast spell frost nova, movements npc are bugs, npc teleport at waypoint where he should have been without immobilization.
Bug remains when npc respawn.

**Steps to reproduce**:

1. Do a mage.
2. Cast spell frost nova
3. See the result

**Client version**: 
TBC 2.4.3

**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/70f1b5b4da9526c4044c4a0472819d369769e9aa

**Database version**: 
https://github.com/TBC-DB/Database/commit/a38dbd07f5ee604162507119b6c890dac5d01e05

**Operating system**: 
Windows 7

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
Should be fixed in https://github.com/cmangos/mangos-tbc/commit/bbe7bd7c44d48ed24e5e57bc64bc3e81690f51ac.
