### ISSUE TITLE
[TBC] Cast spell cheap or blind on npc out of combat bug

### ISSUE THREAD

**Issue by Poloolop10** [cmangos/issues#1077]
**Current behavior**: 

When mage cast cheap or rogue cast blind on npc out of combat, npc don't enter in combat.
When npc is cheap or blind if player comes near him, npc enter in combat and follow player with effects aura cheap or blind.
Then when cheap or blind is finished, npc follow player without attack mellee and don't cast spell.

**Steps to reproduce**:

1. Do a mage or rogue
2. Cast spell cheap or blind on npc out of combat.
3. Go near npc for entering combat and see the result.

**Client version**: 
TBC 2.4.3

**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/70f1b5b4da9526c4044c4a0472819d369769e9aa

**Database version**: 
https://github.com/TBC-DB/Database/commit/a38dbd07f5ee604162507119b6c890dac5d01e05

**Operating system**: 
Windows 7

**Comment by Warlockbugs** [comment]
CC effects interactions are being fixed in [#114](https://github.com/cmangos/mangos-tbc/pull/114)

**Comment by Poloolop10** [comment]
nice, thx a lot.

**Comment by Warlockbugs** [comment]
Should be fixed in https://github.com/cmangos/mangos-tbc/commit/bbe7bd7c44d48ed24e5e57bc64bc3e81690f51ac.
