### ISSUE TITLE
[WOTLK]mangods crash - src\game\vmap

### ISSUE THREAD

**Issue by mangostaters** [cmangos/issues#1082]
**Current behavior**: When running Mangosd.exe in either my classic or WotLK builds, it stops working after the below text appears in the prompt; I am met with a "mangosd.exe has stopped working" message in Windows. Cloned from two days ago.

**Expected behavior**: Mangosd runs

**Steps to reproduce**:

1. Follow install instructions webpage
2. Run mangosd.exe

**Client version**: Classic 1.12.1 and WotLK 3.3.5a

**Commit hash**: (New to this; no idea)

**Database version**: Classic DB 1.7; WotLK DB listed as "UDB_0.12.2_mangos_11792_SD2_2279.sql" in folder

**Operating system**: Windows 10 64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)
**ClassisDB Crash Log**
[mangosd.exe_[14-9_19-39-57].txt](https://github.com/cmangos/issues/files/475245/mangosd.exe_.14-9_19-39-57.txt)
**WotLK Crash Log**
[mangosd.exe_[14-9_20-27-33].txt](https://github.com/cmangos/issues/files/475247/mangosd.exe_.14-9_20-27-33.txt)

**Classic DB last text on mangosd.exe prompt when it crashes:**
Loading grids for active creatures or transports...

Creature (Entry: 683 Guid: 2259) enters grid[10,31]
..\..\src\game\vmap\MapTree.cpp:179: Error: Assertion in VMAP::StaticMapTree::getObjectHitPos failed: maxDist < std::numeric_limits<float>::max()..\..\src\game\vmap\DynamicTree.cpp:213: Error: Assertion in DynamicMapTree::getObjectHitPos failed: maxDist < std::numeric_limits<float>::max()

**WotLK DB last text on mangosd.exe prompt when it crashes:**
Loading grids for active creatures or transports...
Creature (Entry: 930 Guid: 4232) enters grid[12,29]
Creature 4232 used AI is EventAI.
Sending SMSG_SPELL_START id=3616
Sending SMSG_SPELL_GO id=3616
Spell 3616 Effect0 : 6 Targets: Creature (Entry: 930 Guid: 4232), -, -
Spell: Aura is: 42
Aura: construct Spellid : 3616, Aura : 42 Target : 1 Damage : 1
Holder of spell 3616 now is in use
Creature (Entry: 930 Guid: 4344) enters grid[12,29]
..\..\src\game\vmap\MapTree.cpp:175: Error: Assertion in VMAP::StaticMapTree::getObjectHitPos failed: maxDist < std::numeric_limits<float>::max()..\..\src\game\vmap\DynamicTree.cpp:214: Error: Assertion in DynamicMapTree::getObjectHitPos failed: maxDist < std::numeric_limits<float>::max()

**Comment by katz1** [comment]
I have the exact same issue on a fresh classic x64 release build.

**Comment by Grz3s** [comment]
offtopic - not realted to crash: (or maybe?)
@mangostaters mangostaters
```quote
Database version:  WotLK DB listed as "UDB_0.12.2_mangos_11792_SD2_2279.sql" in folder
```
this full DB pack is few years old... Did u add all updatepacks? (403...... 408)...
For correct instal UDB pls look here:
https://github.com/unified-db/Database#installation

this crash not happening in my core
win7 x64

**Comment by Grz3s** [comment]
Again... this is offtop (maybe not related to your crash)
./InstallFullDB.sh is preety easy for win/Linux... 
if somehow it doesn't work for you correctly ...pl report it with details .. on:
https://github.com/unified-db/Database/issues
we'll try to help...

**Comment by katz1** [comment]
@Grz3s 
I updated my classic DB with the InstallFullDB.sh as I always did and it did not report anything strange. Just to be sure I dropped my complete DB and reinstalled it again, the error is still present.

Welcome to the classic DB helper InstallFullDB.sh

```
> ATTENTION: Your database mangos will be reset to classic DB!
> Please bring your repositories up-to-date!
> Press CTRL+C to exit
> ....................
> Process classic database v1.7 'The Scourge's Capital'.
> mysql: [Warning] Using a password on the command line interface can be insecure.
> Process database updates
>    process update updates/1451_fire_effiy.sql
> mysql: [Warning] Using a password on the command line interface can be insecure.
>    process update updates/1452_rumsey_rum.sql
> mysql: [Warning] Using a password on the command line interface can be insecure.
>    process update updates/1453_katrina_shimmerstar.sql
> mysql: [Warning] Using a password on the command line interface can be insecure.
>    process update updates/1454_z2685_01_mangos_event_linkedto.sql
> mysql: [Warning] Using a password on the command line interface can be insecure.
>    process update updates/1455_legionnaire_mangos_string.sql
> mysql: [Warning] Using a password on the command line interface can be insecure.
> Updates applied
> 
> 
> Applying additional core updates from path ../mangos-classic/
> 
> All core updates applied
> Applying ../mangos-classic/sql/scriptdev2//scriptdev2.sql ...
> mysql: [Warning] Using a password on the command line interface can be insecure.
> Recent state of ScriptDev2 applied
> Applying ../acid//acid_classic.sql ...
> mysql: [Warning] Using a password on the command line interface can be insecure.
> Recent state of ACID applied
> 
> You have now a clean and recent classic DB database loaded into mangos
> Enjoy using classic DB
```

**Comment by Phatcat** [comment]
https://github.com/cmangos/issues/issues/1080

**Comment by mangostaters** [comment]
Understood; I'll perform those steps later this evening and provide details there if it doesn't work. Should I mark this as closed since this issue should be posted elsewhere?

**Comment by Phatcat** [comment]
nah, let's just leave this open for now.

**Comment by yushicsm** [comment]
I have the exact same issue on a fresh classic x64 release build on Windows 7.
![crash](https://cloud.githubusercontent.com/assets/19855348/18570024/3f8f207e-7bd9-11e6-81c2-f4760ca32e31.png)
But when i use this https://github.com/cmangos/mangos-classic/releases/download/Last_mangos-classic_PreBuild/mangos-classic_x64_Release.zip
the crash not happening
So i guess the problem happening on the process of compiling。

**Comment by mangostaters** [comment]
@yushicsm That build has allowed it to work, thank you. However, any suggestions on what I should do for the WotLK version?

**Comment by mangostaters** [comment]
@Grz3s Hey, for the UDB database, I was following the instructions for getting it from the Installation Instructions page; is there a better one out there or will the patches (403-408) bring it up to date?

**Comment by cyberium** [comment]
Is that crash is related to only VS2013 builds?

**Comment by mangostaters** [comment]
Edit: As of 9-16-16, both clients are working following fresh downloads from below and recompiling/databasing:


WotLK
UDB (your mangos/database folder): github.com/unified-db/Database
Cmangos (your mangos/mangos folder): github.com/cmangos/mangos-wotlk
Mangos WotLK Prebuild (your mangos/run folder): github.com/cmangos/mangos-wotlk/releases *

Classic
ClassicDB (your mangos/database folder): github.com/classicdb/database
Cmangos (your mangos/mangos folder): github.com/cmangos/mangos-classic
Mangos Classic Prebuild (your mangos/run folder): github.com/cmangos/mangos-classic/releases *

*Remember to copy and edit the .conf files named in the Installation Instructions (mangosd, realmd, ahbot)!

**Comment by katz1** [comment]
@cyberium 
It is possible, I am using VS2013 with boost_1_60_0.
I tried Win32 and debug builds as well, but no change.

**Comment by xfurry** [comment]
:+1: 
Same for me. I already raised this last Sunday

**Comment by cyberium** [comment]
Then for those who want you can take the released binaries till we found the issue. Because i dont have vs2013 for now so i"ll not be able to work on it till next week.

**Comment by katz1** [comment]
@cyberium 
I tried reverting that commit, but it did not solve the issue in classic for me.

**Comment by Laizerox** [comment]
This commit is related to issue https://github.com/cmangos/mangos-wotlk/commit/37e828c3e016d9c7105e22da76123017a2cdff48 if you revert it, then everything will load fine.

**Comment by cyberium** [comment]
Nice find Thank you for that.
But now we have to found a better way than simpli reverting that commit. Maybe @sidsukana have an alternative for VS2013?

**Comment by mangostaters** [comment]
@cyberium Could using VS 2015 be an answer or does that present more problems?

**Comment by cyberium** [comment]
If you want a fast solution yes. VS2015 fully dupport c++11 and this issue does not exist on it. Else we'll fix VS2013 in following days so...

**Comment by mangostaters** [comment]
Does either 2015 or 2013 make for a better running game, or does it matter?

**Comment by cyberium** [comment]
Its always a good idea to have latest compiler. But it should not change result code in the term that it will 'improve' game experience. So using 2013 or 2015 should not matter.

Thank for all your lovely :-1:

**Comment by cala** [comment]
@cyberium : Tobi made me do it. I had no other choice: he was threatening me with a big trout, you know how he is!
