### ISSUE TITLE
db_create_mysql.sql crash

### ISSUE THREAD

**Issue by mangostaters** [cmangos/issues#1083]
**Current behavior**: Gitbash stops and produces error in picture 

**Expected behavior**: Create mysql databases

**Steps to reproduce**:

1. Use xampp
2. Set sql path
3. Gitbash in mangos folder with following line from the Installation Instructions: mysql -uroot -p < mangos/sql/create/db_create_mysql.sql
4. Wonder if I'm posting this in the correct area

**Client version**: WotLK 3.3.5a

**Commit hash**: ?

**Database version**: WotLK DB listed as "UDB_0.12.2_mangos_11792_SD2_2279.sql" in folder

**Operating system**: Win 10 64x
![db create issue](https://cloud.githubusercontent.com/assets/22204157/18574464/9a01646c-7b8a-11e6-9e9e-e32d72033c68.jpg)

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
This is not a cmangos bug, you are having an issue with mysql client. Try to use a more common graphical mysql client, such as MySQL Workbench for running scripts.

**Comment by mangostaters** [comment]
Understood, thank you. After using SQLYog (I had a hard time figuring out Workbench), can I still just double click the install full db shell script and be good to go, or do I have to execute the SQL script from SQLYog?

**Comment by Warlockbugs** [comment]
With graphical clients you have to do it manually, but you have more control and more elaborate output about problems.

**Comment by Phatcat** [comment]
why xampp to begin with? you're on windows, you can just get mysql and use cmd;

open cmd.exe
use the command `cd\` (cd = change directory, then backslash tells it to change it all the way to the root of the drive)
then simply use command `mysql -uroot -p < <full file path + name.sql>` , in your case that seems to be:

`mysql -uroot -p < Mangos-WotLK/mangos/sql/create/db_create_mysql.sql`

**Comment by mangostaters** [comment]
Ah, I did not know that; the very first WoW single player thing I did used Xampp to start MySQL, so it was just a habit. Next time I do everything from scratch I'll try that. 

Also, everything is working right now by using SQLYog for the databases. Should I close the topic?

**Comment by Phatcat** [comment]
Yeah, you should close it, especially considering this is not a core issue ;)
