### ISSUE TITLE
hangs server after reboot

### ISSUE THREAD

**Issue by DescCore** [cmangos/issues#1084]
Hello all, After using commands .server restart server hangs.
server logs do not record
Write: aura 42 now is remove mode 5 
After.
Halthing process...
OC: Linux Debian 8.2

**Comment by DescCore** [comment]
@cyberium seen such freezes

**Comment by Laizerox** [comment]
Problem is that CLI thread never finishes because of blocking getline function.

If you press enter then mangosd will shutdown properly.

**Comment by cyberium** [comment]
Should be fixed
