### ISSUE TITLE
You can not let your pet 1.12.1

### ISSUE THREAD

**Issue by DescCore** [cmangos/issues#1086]
when the questions at the pet taming hunters pet can not let go
Perhaps you can not let go even after passed quest

**Comment by Phatcat** [comment]
You're most likely going to have to reword that, I don't quite understand what you're saying..

Are you saying that there are issues with the hunter quest to learn to tame pets? that you can't abandon those pets, or..?

**Comment by cyberium** [comment]
I can confirm there is some problems for thoses quests 'tame the beast' from test i did yesterday.

**Comment by mangostaters** [comment]
I worked around that by using the .die command on the quest pets that you have to tame with the rod. You'll need GM status on your account to do it, but it removes the pet so you can tame another.

**Comment by DescCore** [comment]
@cyberium Yes, player can't let go of a pet at all, and pet can not be sent into the attack, write: this objective can not be attacked

**Comment by Phatcat** [comment]
This is the same issue as https://github.com/cmangos/issues/issues/1075 (so actually a double post, but with some additional info so I'm thinking of letting both issues stand)

There are currently a few work-arounds to this issue from a player's perspective; one is having gm commands and using .die on it, like @mangostaters suggested. The other is (and I know, not the most fun choise) to let the pet get so unhappy that it disbands from you itself)

**Comment by Phatcat** [comment]
https://github.com/cmangos/issues/issues/1109

**Comment by Phatcat** [comment]
Now that https://github.com/cmangos/mangos-classic/pull/210 has been merged this should be solved.
