### ISSUE TITLE
[TBC] VS2013 VC120 Compile Errors Win 10 64x

### ISSUE THREAD

**Issue by mangostaters** [cmangos/issues#1088]
**Current behavior**: Compiling TBC VC120, results in three errors:
Error   281 error C1083: Cannot open source file: '....\src\game\AggressorAI.cpp': No such file or directory  
C:\Mangos-TBC\mangos\win\VC120\c1xx game

Error   694 error LNK1181: cannot open input file 'C:\Mangos-TBC\mangos\win\VC120\game__x64_Release\game.lib'  
C:\Mangos-TBC\mangos\win\VC120\LINK mangosd

Error   811 error LNK1181: cannot open input file 'mangosd.lib' 
C:\Mangos-TBC\mangos\win\VC120\LINK ScriptDev2

**Expected behavior**: Complete compile

**Steps to reproduce**:
1. Use VS2013
2. Use compile file VC120 from mangos/win
3. Use settings "release" and "64x" in build configuration menu per installation instructions
   -I use 64bit boost, which has worked for WOTLK and Classic

**Client version**: TBC 2.4.3

**Commit hash**: ?

**Database version**: The changelog says 0.12.3, but just in case, this is the DB version I cloned:
https://github.com/cmangos/mangos-tbc

**Operating system**: Win 10 64x

**Comment by Mymaqn** [comment]
I personally had the same problem. I worked around it by compiling it with VS2015 instead and of course I compiled the vs140 version. Hope this helps!

**Comment by Phatcat** [comment]
You still having compiling issues on current master with VC120?

**Comment by IgoCfRd** [comment]
I still compiled with VC120 today,and still had the same problem.

**Comment by kuramajssken001** [comment]
Yeah, Me too

**Comment by cyberium** [comment]
Should be fixed
