### ISSUE TITLE
[WotLK] Very few Tirisfal Pumpkins with long respawn

### ISSUE THREAD

**Issue by mangostaters** [cmangos/issues#1090]
**Current behavior**: Only 8 Tirisfal Pumpkins are spawning at Solliden Farmstead with, as of 10 minutes later, a *very* long respawn time.

**Expected behavior**: Plenty of pumpkins (more than the 10 needed for the quest) with much faster respawn.

**Steps to reproduce**:

1. Create undead character (I am a level 6 warlock).
2. Leave starting area and accept quest "Fields of Grief" (be level 6 to accept) from the deathguard at the fork in the road just outside the starting area gate.
3. Proceed to Solliden Farmstead to the west, at the westernmost edge of Tirisfal Glades.
4. Very few pumpkins should have spawned.

**Client version**: WotLK 3.3.5a

**Commit hash**: ?

**Database version**: DB listed as "UDB_0.12.2_mangos_11792_SD2_2279.sql" in folder

**Operating system**: Win 10 64x

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Phatcat** [comment]
This is actually more a DB issue as none of this is hardcoded, you should want to take it up with the DB team of your choise (I'm guessing https://github.com/unified-db/Database). Gonna close this here as there's nothing we can do core side to solve this.

**Comment by mangostaters** [comment]
For future reference, how do we know if it's a DB or cmangos issue?
