### ISSUE TITLE
[WOTLK] Undercity South and West Elevators are Inverted

### ISSUE THREAD

**Issue by mangostaters** [cmangos/issues#1091]
**Current behavior**: Gates close when elevator is on a floor, then open when it is on the other floor.
Example: When elevator is up top, the gate up top is closed so you cannot go on it or exit the elevator. It opens when it is on the bottom floor, thus leading to you falling to your death.

**Expected behavior**: Respective doors open when elevator is on their level.

**Steps to reproduce**: Go to Undercity's southern and western elevators and watch. Eastern elevator seems to work as intended.

**Client version**: WotLK 3.3.5a

**Commit hash**: ?

**Database version**: DB listed as "UDB_0.12.2_mangos_11792_SD2_2279.sql" in folder

**Operating system**: Win 10 64x

**Comment by jimmybrancaccio** [comment]
Could possibly be fixed along with #1501.

**Comment by killerwife** [comment]
Indeed resolved.
