### ISSUE TITLE
[TBC] Attunemen the Huntsman Spawns as Friendly

### ISSUE THREAD

**Issue by Mymaqn** [cmangos/issues#1092]
**Current behavior**
Midnight spawns a friendly Attunemen the huntsman
**Expected behavior**: 
Midnight spawns a hostile Attunemen the Huntsman
**Steps to reproduce**:
Enter Karazhan, damage midnight to roughly 25%. Attunemen the huntsman will then spawn as friendly

**Client version**: 
2.4.3

**Commit hash**: 
Sorry don't know what this is

**Operating system**: 
Windows 10

**Database version**: 
Wasn't sure which one you wanted but I've got
TBCDB_1.5.0_cmangos-tbc
and all up to 
s2331_01_mangos_event_linkedto
from updates installed

Note:
I don't know how the coding exactly works, but I fixed this by changing his factionid to a hostile one (45) instead of a friendly one. (35)
Hope this helps!

**Comment by SilvioDoMine** [comment]
This is a database problem?

**Comment by Phatcat** [comment]
either that or SD2, depends what is handling this.

**Comment by Mymaqn** [comment]
As far as I'm concerned it's just a small database problem. For some reason his factionid was messed up.
But since it's the mangos database, I thought I would post it here

**Comment by Saben65** [comment]
Faction 45 is Ogres, isn't it?

```SQL
SELECT `name`,`factionalliance`,`factionhorde` FROM `creature_template` WHERE `entry` IN (16151,16152);
```
```
name                  factionalliance  factionhorde  
--------------------  ---------------  --------------
Midnight                            7               7
Attumen the Huntsman               35              35
```

Probably better to change it to 7 (creature), no?

```SQL
UPDATE `creature_template` SET `factionalliance`=7,`factionhorde`=7 WHERE `entry`=16152;
```

**Comment by Qingle** [comment]
Well if monster is aggressive to everyone a raid then yes.

**Comment by MantisLord** [comment]
In current DB Attumen the Huntsman has Faction 16 and Midnight has Faction 7 which also matches WotLK-DB. Closing.
