### ISSUE TITLE
[TBC] Guard Roberts, not healable for priest quest

### ISSUE THREAD

**Issue by Mymaqn** [cmangos/issues#1093]
**Current behavior**: 
Guard Roberts is not healable nor buffable

**Expected behavior**: 
Guard Roberts should be healable AND buffable

**Steps to reproduce**:
1. Make a human priest and make it level 6
2. Take the priest quest in northshire inside the temple, turn it in (in goldshire) and take the next quest
3. Try to heal Guard Roberts

**Client version**: 
2.4.3
**Commit hash**: 
(still new, don't know what this is)

**Database version**: 
TBCDB_1.5.0_cmangos-tbc
and updates up until
s2331_01_mangos_event_linkedto.sql

**Operating system**: 
Windows 10

NOTE:
Fixed this personally by using HeidiSQL to manipulate the creature template and changing his factionid from 12 to 10, however this causes him to be PVP flagged.

**Comment by Phatcat** [comment]
Could you please try out this commit:
https://github.com/Phatcat/mangos-tbc/commit/d34fc34afcedcf6ec931613bbda7af97a0054c15

**Comment by cala** [comment]
If I remember correctly, these flags are supposed tonbe set DB side. The NPC was working correctly last time I checked on Classic and I remember UDB pushing a fix fot that NPC recently, so this is likely TBC-DB that is missing some fixes.

**Comment by Phatcat** [comment]
I see
  `unit_flags` int(10) unsigned NOT NULL default '0',
  `dynamicflags` int(10) unsigned NOT NULL default '0',
I don't see a UnitByteValue ?
If this is normally set DB side, then why is these npcs flags handled sd2 side:
https://github.com/cmangos/mangos-tbc/blob/master/src/scriptdev2/scripts/world/npcs_special.cpp#L523

**Comment by Phatcat** [comment]
you are right it indeed works on classic, although with some bugs, but the spells can be cast on him 
(the script depends on which order you cast them it would seem, as casting fortitude rank 1 on him first does nothing it would seem, also if you cast fortitude rank 3 on him it will bug out and you can no longer cast any spells on him at all.)

**Comment by Mymaqn** [comment]
I think the npcflags are handled sd2 side, because he's supposed to be healable on a pve server without the user getting pvp flagged. The only other NPC's that are healable which exist are guards in the cities. If you heal a guard, their factionid, is made so you get pvp-flagged too.
I hooe this helps

**Comment by xfurry** [comment]
I think this is a DB issue.
You should modify the creature_template_addon and set some PvP flag for this npc. That should fix it.

**Comment by Phatcat** [comment]
well, my proposed commit does so you are able to cast buffs/heals on him and not get flagged for pvp yourself; I did not notice if you get flagged for pvp or not on classic/wrath, I think not,

**Comment by AnonXS** [comment]
http://wowwiki.wikia.com/wiki/Quest:Garments_of_the_Light_(Elwynn_Forest)
http://www.wowhead.com/quest=5624/garments-of-the-light

**Comment by cala** [comment]
Closing then.
