### ISSUE TITLE
Quest: Plague Lands (ID: 2118)

### ISSUE THREAD

**Issue by Primus11** [cmangos/issues#1096]
http://www.wowhead.com/quest=2118/plagued-lands

Finishing the quest is not working.

I took the quest, went to a "Rabid Thistle Bear" and captured him with the trap. After returning him to the quest giver "Tharnariun", the bear disappers but the quest is not completed.

Client version: 2.4.3

Database version: TBC-DB (18.09.2016)

Operating system: Win 10

**Comment by killerwife** [comment]
There is a PR pending that will fix this. It just has to be processed.

**Comment by cyberium** [comment]
Should be fixed by @killerwife thanks.
