### ISSUE TITLE
[Classic] Charge underground

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1097]
I managed to charge underground with a warrior in Elwynn Forest targeting a murloc around 75, 85. The terrain is a bit tricky, there is a rock underneath the surface and you will end up on it instead of the ground. See the chat on the picture for the exact position, it's really easy to reproduce.

![chargeunderground](https://cloud.githubusercontent.com/assets/18726138/18639116/ec9a287a-7e92-11e6-912e-0811633b651a.jpg)

**Comment by Phatcat** [comment]
yeah, our maps are probably not the best extracted, or blizzard found a way to compensate serverside, because there are several issues with pet pathing and caves in particular as well.

**Comment by cyberium** [comment]
Its known problem with mmap/vmap there is already other issues about that.
