### ISSUE TITLE
[WOTLK] Quality Control Against Let's Play WoW Draenei Shaman 1 - 80 [video 1/142]

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1098]
https://www.youtube.com/watch?v=aJWK6sSWWno&list=PL28173C4849CA7E04&index=1
(Set to 0.25 speed)

2:12
The quest to turn in 'Shaman Training' has a blue question mark in the gossip menu while it should be yellow.
(ref https://github.com/unified-db/Database/issues/251#issuecomment-248453891)

3:37
Draenei Survivors are supposed to be dazed the second they are hit with the gift of naaru, get up, say something, then stop being dazed/confused (pay attention during 3:41), and then run away
Currently gets up, says nothing, stays confused/dazed and walks away.
(ref https://github.com/unified-db/Database/issues/251#issuecomment-249320649)

4:03
Items are presented in wrong order, it should go chests -> leggings -> belts -> boots -> wrists -> gloves -> shields (may be core issue if all shops are handled uniformly)
(ref https://github.com/unified-db/Database/issues/251#issuecomment-249324520)

6:48
When Inoculation Crystal is used on Nestlewood Owlkin it should move around confused for a bit before despawning and not just stand still before despawning.
(ref https://github.com/unified-db/Database/issues/251#issuecomment-249414622)

**Comment by evil-at-wow** [comment]
Played time could and still can be shown with /played, as you probably know.

I can confirm that at least at the end of TBC (2.4) the time played was not shown automatically when you gained a level. According to one of my screenshots, the messaging back then was as follows:
```
Congratulations, you have reached level 2!
You have gained 15 hit points and 23 mana.
Your Stamina increases by 1.
Your Intellect increases by 1.
Your Spirit increases by 1.
```

And I just noticed that not all stats increased every level. The screenshot for level 3, a few minutes later, mentions Strength, Agility, Intellect and Spirit, but not Stamina! You learn something every day.

**Comment by Phatcat** [comment]
Yeah, so showing the time played and time played last level is vanilla exclusive (remember this is important to actually know how long you spent in the previous level - this is what you can nevre really find out anymore. Yes, you can still do a /played, but you in order to find out how long you spent in a specific level you'd have to do a /played right before you dinged (and then add in that extra time yourself) - it's just not the same..

**Comment by Phatcat** [comment]
Yeah not blizzlike, most likely an addon, pulled out of the issue ticket at least.

**Comment by Phatcat** [comment]
Actually gonna close this cause the rest most likely is related to patch differences.

**Comment by Phatcat** [comment]
Ignore the previous comments, this now covers different points in the video.

**Comment by Phatcat** [comment]
https://github.com/unified-db/Database/issues/251#issuecomment-249417468 for more info relating to these issues.
