### ISSUE TITLE
[Classic] Character tutorial setting is not saved or loaded correctly

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1100]
Every time I start the client and log in with a character the 'Show Tutorials' setting in Interface Options / Basic is turned on.

First I thought that this is a bug in the client itself (or an issue in my environment), but after looking around a bit I found a **character_tutorial** table which suggests the server can be related? I receive a PVP tip every time I enter a PVP zone after login because of this issue.

![pvptip](https://cloud.githubusercontent.com/assets/18726138/18679895/bd767628-7f61-11e6-96d9-79d47c8b45c7.jpg)

**Comment by katz1** [comment]
I believe the issue is with **WorldSession::LoadTutorialsData**.
The DB has the correct flag values according to https://github.com/cmangos/issues/wiki/character_tutorial. The tutorial flags are read correctly from the DB at the start of LoadTutorialsData, but the read values are halved when they are loaded to WorldSession's **m_Tutorials** _(both of the values are unsigned)_. So instead of the 4294967295 values which mean that tutorials are disabled, the world session will load 2147483647 everywhere, and these will overwrite the DB values as well.

**Comment by katz1** [comment]
This turned out to be fun, atol("4294967295") can return only 2147483647, and casting that to uint32 will not change a thing. So the real issue is with Field::GetUInt32(), which could potentially cause trouble elsewhere as well.

**Comment by katz1** [comment]
Changing the atol inside **Field::GetUInt32** to atoll will fix the problem, but this could have some core dev attention. @cyberium maybe?

**Comment by cyberium** [comment]
Ah i remember a similar issue. Ill check that asap. Thank for your investigation that help. I confirm this issue that i noticed but didnt had chance to investigate on it.

**Comment by killerwife** [comment]
We encountered this issue when migrating spell_dbc :) atoll fixes it

**Comment by devmaximus** [comment]
yes, i was dealing with this issue 5 months ago when migrating spells from dbc to core database. it was a painful find.

![image](https://cloud.githubusercontent.com/assets/1082629/18691381/1bde821a-7f48-11e6-859f-af6457afd7a5.png)
