### ISSUE TITLE
[TBC] Polymorph or blind don't enter combat the creature with the caster

### ISSUE THREAD

**Issue by Poloolop10** [cmangos/issues#1101]
**Current behavior**: 
Actually spells polymorph or blind (see others) the creature don't enter combat with the caster

**Expected behavior**: 
Spells polymorph, blind etc.. must do enter combat the creature with the caster

**Steps to reproduce**:

1. Make a mage and cast polymorph on a target out of combat
2. Or make a rogue and cast blind on a target out of combat
3. In all cases creature don't enter combat

**Client version**: 
TBC 2.4.3

**Commit hash**: 
Last commit

**Database version**: 
Last commit

**Operating system**: 
All

**Comment by Warlockbugs** [comment]
This is a general defect in spell hit detection system, not related directly to CC. You also may have noticed that full resists and immunes made against hostile creatures do not put caster in combat aswell.
Perhaps, the WIP positive/negative detection PR https://github.com/cmangos/mangos-tbc/pull/127 contains the API needed to resolved this issue for all spell hits. If other developers agree with this, i'll add it to my todo list.

**Comment by Warlockbugs** [comment]
This will be fixed in PR https://github.com/cmangos/mangos-tbc/pull/127.

**Comment by Poloolop10** [comment]
cool, nice work!

**Comment by Warlockbugs** [comment]
Fixed in https://github.com/cmangos/mangos-tbc/commit/d99037131a31893920219fd7d7720a7c94d70c96.

**Comment by Poloolop10** [comment]
Again a little bug:
When cast blind or polymorph on a npc out of combat who is in a group, in first he come on us and then he come back at start's position with effect confuse.

**Comment by Warlockbugs** [comment]
I believe that may be an AI/movement generator issue. You are welcome to open a new issue.
