### ISSUE TITLE
Periodic damage not ticking on constantly refreshed auras

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1103]
Currently on cmangos we have an issue with auras getting refreshed, also having their ticking times reset, what I mean is that if you fight a mob which constantly wants to reproc poison on you, the poison will never actually harm you, because every time the poison is reapplied, the time before the damage ticks in will also be reset.

Can be reproduced easily by going to the northern part of Felwood to the Toxic Horrors, then pull 2 or 3 into combat at the same time; notice how the dots don't seem to ever get a tick in on you, put gm mode on and leave the mobs; notice how the dots start ticking on you.

Yeah, this makes fighting... probably a lot.. of different mobs too easy on cmangos.

**Comment by jimmybrancaccio** [comment]
@Phatcat Does this apply to all versions or only a specific version?

**Comment by Phatcat** [comment]
If nothing else it affects Classic, but i don't see why it wouldn't affect the other cores. I dont have the ability to test it on any core at the time being.

**Comment by Phatcat** [comment]
This issue has been resolved.
