### ISSUE TITLE
Issue with blind or polymorph on a npc out of combat who is in a group

### ISSUE THREAD

**Issue by Poloolop10** [cmangos/issues#1105]
**Current behavior**:

When cast blind or polymorph on a npc out of combat who is in a group, in first he come on us and then he come back at start's position with effect confuse.

**Steps to reproduce**:

1. Make a rogue or mage, learn blind or polymorph
2. Cast blind or polymorph on a npc out of combat who is in a group.

**Client version**: 
TBC 2.4.3

**Commit hash**: 
Last

**Database version**: 
Last

**Operating system**: 
All

**Comment by Warlockbugs** [comment]
Potential suspects: movement generators / AI. I don't have much experience with this stuff yet, so don't expect a quick fix this time.

**Comment by Warlockbugs** [comment]
Should be fixed in https://github.com/cmangos/mangos-tbc/commit/f852f018a6951ae96dded9435477de222b219797. The movement generator thing requires a major rewrite, it causes bugs on all levels and we have to deal with it somehow.

**Comment by Poloolop10** [comment]
it doesn't work !

     if (HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_CONFUSED))
    {
        StopMoving(true);
         GetMotionMaster()->MoveConfused();
    }
     else if (HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_FLEEING))
    {
        StopMoving(true);
         GetMotionMaster()->MoveFleeing(IsInWorld() ?  GetMap()->GetUnit(casterGuid) : nullptr, time);
    }

it work with StopMoving(true);
