### ISSUE TITLE
Toxic Horror [7132]

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1106]
**Current behavior**

weird things happening with debuffs (you may have to be a little patient)

**Expected behavior**: 

should keep stacking up debuffs untill limit is reached, from here they should just keep getting reset; not get removed like they are.

**Steps to reproduce**:

go to the place in northern felwood that is filled with them (near the graveyard) ,
give yourself alot of health
get in a fight with at least 2 of them at the same time

**Client version**: 

Classic (pretty sure I tested it on tbc and found it was the same, but not entirely sure, I was a bit stoned)

**Comment by Jaypy** [comment]
Not sure what the weird things are. Debuff stacking seems normal to me.. maybe elaborate a little on that.

I did notice that they aren't immune to frost damage, which they should be. (http://wowwiki.wikia.com/wiki/Toxic_Horror)

**Comment by Warlockbugs** [comment]
This was reported before new aura stacking system was applied.
@Phatcat 
Please, verify if this issue is already fixed.

**Comment by Phatcat** [comment]
I'll re-test this and bring an update.

**Comment by Phatcat** [comment]
This has been solved. Nice work :+1:
https://github.com/cmangos/issues/issues/1103 still applies.
