### ISSUE TITLE
[WOTLK] Quality Control Against Let's Play WoW Deathknight [Part 1]

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1108]
https://www.youtube.com/watch?v=kyFHLarxJSg

~~5:12
The Unworthy Initiate you free should turn to face you and then say something, 
they should then walk back towards the wall, kneel down and then after a bit of time transform
currently they don't turn towards you or say anything.~~

~~6:37
Some 'flavour' text should appear on the screen and in your message log, currently doesn't.
6:54
More flavour text~~

7:00
~~Spells are displayed on the action bar in the wrong order, attack shouldn't be available~~ **fixed** - The eye itself should appear on the special action bar along with abandoning the eye (ability on key 5) in the forms/aura/stance bar, which it should also replace (on cmangos it is not overwritten)
![wrongbar](https://user-images.githubusercontent.com/1907820/51076637-4b43fe80-169b-11e9-895e-bb242ea2d0be.PNG)
![image](https://user-images.githubusercontent.com/1907820/51076660-92ca8a80-169b-11e9-8c0d-d169763e7411.png)

7:00 - 9:30
(especially visible at 8:05)
Aggro range is too short on cmangos, they don't seem to all come running and get angry with you when you channel at their building (like they should)
they don't react to me here, I can go -very- close before they react, and they basically don't care about me stealing intel, also their attacks don't seem to be able to go as far as in the video
most of the scarlet mobs seem very passive. Basically it shouldn't be possible to get close enough to analyse the builds without also drawing aggro, on cmangos it seems like it's impossible to draw aggro unless you fly directly into mobs.

**Comment by Phatcat** [comment]
@Grz3s Nothing of this was DB side, right?

**Comment by cyberium** [comment]
Flavour text and first metionned issue seem to be db side.

**Comment by Phatcat** [comment]
I was thinking the first one was done with SD2 giving the complexity, but it was a guess in all honesty.

Do we support that kind of flavour text core side? I havn't played wrath and don't remember seeing that during vanilla / tbc so I don't know where else to go confirm/deny it as a general issue?

**Comment by Grz3s** [comment]
@Phatcat
first it is done by sd2.. (i can try to redo it in DB)... 

Second:
this text you talking  about??? (this pic..is from your DB...taken few mins ago) :)
![text](https://cloud.githubusercontent.com/assets/2374069/19409470/f1866b76-92cb-11e6-9ffd-40f69963cd87.jpg)

**Comment by Phatcat** [comment]
Yes, that is the flavour text I was talking about. Is this yet another false report? comeon, what is going on at my end, really...

**Comment by Grz3s** [comment]
also for first quest .. all texts are there:
![dwadaw](https://cloud.githubusercontent.com/assets/2374069/19414038/f3b1cd38-9338-11e6-8b12-09fb50918e37.jpg)

**Comment by Phatcat** [comment]
@Grz3s 
Could this
> 7:00
Spells are displayed on the action bar in the wrong order, attack shouldn't be available

Be db side?

**Comment by Grz3s** [comment]
@Phatcat  ...Partly..
i can set correct order for spells...(fix will be added into DB soon*)
From sniff:
```code
ServerToClient: SMSG_PET_SPELLS_MESSAGE (0x0174) PetGUID: Full: 0x1C39244C201BD7C000007F00005ACA8B Creature/0 R3657/S127 Map: 609 Entry: 28511 Low: 5950091
CreatureFamily: 0
Specialization: 0
TimeLimit: 0
PetModeAndOrders: 257
(PetModeAndOrders) ReactState: Defensive
(PetModeAndOrders) CommandState: Follow
(PetModeAndOrders) Flag: 0
(ActionButtons) [0] Action: 8
(ActionButtons) [0] SpellID: 51859
(ActionButtons) [1] Action: 9
(ActionButtons) [1] SpellID: 51904
(ActionButtons) [2] Action: 10
(ActionButtons) [2] SpellID: 52006
(ActionButtons) [3] Action: 11
(ActionButtons) [3] SpellID: 0
(ActionButtons) [4] Action: 12
(ActionButtons) [4] SpellID: 52694
(ActionButtons) [5] Action: 13
(ActionButtons) [5] SpellID: 0
(ActionButtons) [6] Action: 14
(ActionButtons) [6] SpellID: 0
(ActionButtons) [7] Action: 15
(ActionButtons) [7] SpellID: 0
(ActionButtons) [8] Action: 16
(ActionButtons) [8] SpellID: 0
(ActionButtons) [9] Action: 17
(ActionButtons) [9] SpellID: 0
```
You can see that attack is not even there:

FIX:
```sql
DELETE FROM creature_template_spells WHERE entry = 28511;
INSERT INTO creature_template_spells (entry, spell1, spell2, spell3, spell4, spell5) VALUES
(28511, 51859, 51904, 52006, 0, 52694); 
```
Core adds attack by itself. ... and all spells are moved 1 place ahead because of that.
So: This need to be fixed in core.

**Comment by cyberium** [comment]
@Grz3s yes you are right attack have to be added core side. But there is a problem with that. There is no rule to add or not that spell depending to the target currently.
I found that trinity hardcoded some values for that purpose ->https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L10532

So this need certainly more research to know when to add or not hat attack spell.

**Comment by Phatcat** [comment]
As you can see I have edited the post this year, so this has been replicated this year, and the things that are not crossed over still applies as of January 2019. Get your toxic 'needs replication' label off my issue (all of them preferably), I am fully capable of keeping my own issues up to date, thank you.

**Comment by cyberium** [comment]
@Phatcat You really need to learn how to speak with people. You clearly have lack of knowledge on that.
So one lesson for you, its free, **even if you are right, try to be respectful over those who do mistake by trying to help**. We all do mistake.

To others, yes you also have to learn that some have lack of knowledge on people relation and sometime there is nothing to do.

Don't bother to add another comment here. Everything are said.

**Comment by Phatcat** [comment]
@cyberium I know how to speak to people, I just don't believe in false pleasantries and this behavior is really ticking me off for several reasons which are purely out of love and respect for this project and anyone who has chosen to contribute. This includes issue reporters who are thoroughly getting the short end of the stick here.
