### ISSUE TITLE
No reduced fall damage as cat?

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1111]
**Current behavior**: 

Full on fall damage

**Expected behavior**: 

Not only reduced fall damage, but also increased drop height before damage even kicks in at all

**Steps to reproduce**:
1. make a druid
2. `.level 59`
3. `.learn all_myclass`
4. `.tele blackrocksp`
5. enter blackrock spire
6. try recreating this on cmangos: https://www.youtube.com/watch?v=nUED5cXa-Wk (not doable)

**Comment by SilvioDoMine** [comment]
Its strange because I checked, and the reduced fall damage was working on a few revisions ago.

**Comment by Phatcat** [comment]
Not once, but twice you take fall damage as cat on the way down there..

![smallfall](https://cloud.githubusercontent.com/assets/1907820/19155070/5df49396-8bdd-11e6-9313-3a64484f83f3.JPG)
![longfall](https://cloud.githubusercontent.com/assets/1907820/19155077/66a2ce9a-8bdd-11e6-96b6-abc699f08842.JPG)

**Comment by Phatcat** [comment]
This was on classic by the way, have not tested the other cores so it may indeed still be working fine on tbc.

**Comment by MrMarvin** [comment]
Good news, everyone! 

This seems to be only a defect/misunderstanding in how the `.learn all_myclass` commands works. It is simply missing some druid spells, such as the passive '[Feline Grace](http://wow-one.com/database/index.php?spell=20719)'.
When manually (or via `.learn 20719`) learning the spell, the fall damage aura is correctly applied when in Cat Form. Verified in debugger and by replaying the linked retail video.

I haven't really looked into how the sTalentStore and the talent masking works yet... However I would consider this bug closed.

When learning the spell from trainer:
![feline_grace_learned](https://cloud.githubusercontent.com/assets/100136/20691591/434d2ef8-b5d2-11e6-92c5-40a6d0a4f47d.PNG)
After using `.learn all_myclass` at the class trainer:
![feline_grace_not_learned_by_all_myclass](https://cloud.githubusercontent.com/assets/100136/20691600/5230211e-b5d2-11e6-990e-c14d5097680b.PNG)
