### ISSUE TITLE
[CLASSIC] Naxx - Grobbulus Poison Cloud Missing.

### ISSUE THREAD

**Issue by Jaypy** [cmangos/issues#1113]
**Current behavior**: 
Grobbulus doesn't make a poison cloud when either casting on himself, or when the Mutation Injection expires.

**Expected behavior**: 
When Grobbulus casts Poison Cloud or the Mutation Injection expires on a given player, it should produce a poison cloud ring that expands and persists untill the fight ends.

**Steps to reproduce**:
1. Enter Naxxramas and find Grobbulus located in the Abomination Wing.
2. Engage Grobbulus and get injected.
3. Wait for the debuff to expire or get dispelled.

**Client version**: 
"Version 1.12.1 (5875) (Release)"
**Commit hash**: 
"0564eda80067f912b9efa414525cd001486eeb13"
**Database version**: 
"Classic DB version 1.6.5 'The Wailing Pet, The MidSummer Joy and all that sort of things'. For core Classic z2683."
**Operating system**: 
Windows 10 64-bit

**Comment by Qingle** [comment]
So to clarify. 
- He's not doing the poison clouds on his position (requiring no movement from the tank)
- He's not producing a poison cloud when Mutagen Injection is either dispelled or if the buff runs out.

**Comment by al3xc1985** [comment]
@killerwife can be closed... script 100% in core by cala

**Comment by cala** [comment]
Thanks. Same comment as for Sapphiron.
