### ISSUE TITLE
[TBC] Magtheridon's Lair

### ISSUE THREAD

**Issue by violentResolution** [cmangos/issues#1114]
**Current behavior**:
While casting the Nova Magtherion will stop cast if the Tank is moving.
I think it has to to something with the Timer - sometimes the Boss is just
standing around and is doing nothing.

**Expected behavior**: 
While casting Nova dont stopcast or cast any other Spells.

**Steps to reproduce**:
1. Go to Magtheridon's lair
2. Start the encounter and wait till Magtheridon is casting the Nova
3. While casting move your Character

**Client version**: 
2.4.3

**Commit hash**: 

**Database version**: 
Using World DB: TBC-DB 1.4.3 - 006 'PRE-RELEASE BETA BUILD' for CMaNGOS-TBC
Using creature EventAI: ACID 2.4.3 (The Burning Crusades) for CMaNGOS-TBC (2.4.3 Client)

**Operating system**: 
Win 10

**Comment by killerwife** [comment]
Magtheridons lair is pretty much completely broken in open source. I have a working version, BUT for it to be exported in any capacity to open source, I will need to first implement generic target ignoring (which solves your issue), which causes orientation desync. If I get around to that, the script export is quite trivial, but it will need TBC-DB public release, and I do not have repository access currently. So not anytime soon. @X-Savior is MIA and I currently only have time to provide a working DB version. (which will happen soon)

There are currently 15+ issues on the bossfight if I remember correctly. And as we are the only ones doing TBC development, I don't see anyone making it happen sooner.

**Comment by killerwife** [comment]
Sidenote, if you want to start helping with TBC content development (for open source ofc) message me on IRC. Manpower is always welcome.

**Comment by al3xc1985** [comment]
@killerwife  i kniw that targeting was implemented, but i I dont't remember if you exported magtheridon. If you remember, close it please

**Comment by killerwife** [comment]
Magtheridons lair should now be fine.
