### ISSUE TITLE
Moongraze Buck

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1115]
**Current behavior**: 

Theese mooses are overpowered on cmangos; they seem to attack a bit too fast, not directly by attack speed, though (read below)
It seems like they are somtimes able to do 3 melee attacks right after each other (they will do a melee attack, then go straight for the knock-down effect and then straight for melee attack again, they don't seem to be able to do that on retail)

**Expected behavior**: 

https://www.youtube.com/watch?v=BGk9x8_H6II&list=PL28173C4849CA7E04&index=2 - 8:20 (set to slower speed)

**Comment by xfurry** [comment]
Maybe it's because of some acid script / c_addon auras. Did you check those?

**Comment by Phatcat** [comment]
I had it reported on udb and @Grz3s said it was a core side issue, I have not looked into it at all myself yet, no. I know he checked the acid script, dunno if he checked the c_addon auras but if they're db side then I think he did.

**Comment by Phatcat** [comment]
This may very well be related to https://github.com/cmangos/issues/issues/1069

**Comment by Grz3s** [comment]
Problem is more simple than you both may think (not that simple to fix unfortunately).
I saw many time ppl conplained about creatures doing male and cast spells in same time...(we fixed this by using simple code:
-  between 0-8yards male only
-  between 9-xyards - casts only
- above x -- male again
But is this really fixing our problem??? what about skills that not req. mana ...not req time to cast..??
I think your case is an good example for this:   

Let me explain.
Creature has male attack speed in his template (90% has 2000ms.) ... so every 2secs he will do male to his oponent.
```quote
We can show it on this scheme:
.. - 2secs
x - male attack
..x..x..x..x..x..x..x..x.x (...) --- so as we can see here every 2secs creature will do male
```
But what will happen if we'll give that creature EAI skills?
Skill will be added into this "plan" like this.
take our mob
```sql
-- Moongraze Buck
('1720101','17201','0','0','100','1','6000','11000','9000','17000','11','31274','1','0','0','0','0','0','0','0','0','0','Moongraze Buck - Cast Knockdown'),
```
```quote
so his skill will be added somewhere between 6 and 11th second ..

..x..x..xSkillx..x..x..x..x
```
now we can see why @Phatcat  says that he saw 3 attacks almost all together.

Problem is that skills should "REPLACE" male .. not only be "added" into list...
Correct behaviour should look like this:

```quote
..x..x..x..skill..x..x..x
```
Whole EventAI system (imho) is not synchronized with creatures ... it just adds stuff .. that may create funny situations like you just showed.  Probably this req. a lots of work.. maybe @cyberium  will be interested  .. :)

**Comment by killerwife** [comment]
Currently GCD, melee swing timer with spells, and cooldowns in general do not work properly. @cyberium  is aware, prolly need to fix it sometime in the future. Same issue occurs on Gruul's Lair trash with ACID, mob spams 3 high damage abilities and oneshots tanks in some instances.

**Comment by Phatcat** [comment]
This is as far as I can tell not related to cooldowns, but rather with melee swing timer, yes, as it affects players as well where there currently aren't any major issues with cooldowns. Gonna point to my earlier comment of the player being able to do something extremely similar;

> This may very well be related to #1069

**Comment by cyberium** [comment]
> ..x..x..x..skill..x..x..x

i dont think thats right. Ability and melee attack can occur same time and its not same timer.

> ..x..x..xSkillx..x..x..x..x

Sound more correct for me. Skill may fired in unpredictible time. So that said, there is maybe some skill that share melee timer. And those skill have to be fired only folowing first scheme.
We have to identify them and do some test and find a way to generalize them so we will be able to handle them correctly.

@Phatcat melee timer can be considered as a GCD for creature and should be generalized for all spell they can uses. Its the minimum interval time between two ability.

**Comment by killerwife** [comment]
@cyberium skills should reset melee timer unless they have "DOES NOT RESET TIMER" attribute :)

**Comment by Phatcat** [comment]
> ..x..x..xSkillx..x..x..

Is wrong as well.

> ..x..x..xSkill..x..x..x..

should always be possible, but not this (unless they have DOES NOT RESET TIMER , of course):

> ..x..x..x..Skillx..x..x..

**Comment by Phatcat** [comment]
> melee timer can be considered as a GCD for creature and should be generalized for all spell they can uses. Its the minimum interval time between two ability.

I think if we change that to:

> melee timer can be considered as a GCD for creature and should be generalized for all spell they can uses. Its the minimum interval time between **an abillity and the next offensive action**

and take the attribute mentioned by killerwife into consideration then we may be close.

**Comment by Phatcat** [comment]
On second thought, that wouldn't solve this issue for players; I think the issue is the way we generally handle these kind of instant melee attacks, not factoring in resetting melee swing timer when we should, but in fact triggering it instead (Please, go try make a rogue and hit sinister strike on a mob a few times if you havn't already)

With that being said I don't think cyberium is wrong, as we kind of need a kind of global cooldown on mob abilities not to be able to spam mob spells as a player when mind controlling them through the priests' Mind Control ability.
