### ISSUE TITLE
[WotLK] Fall Damage on Griffon.

### ISSUE THREAD

**Issue by CamilleMoon** [cmangos/issues#1116]
**Current behavior**: Not sure if it's database or core but taking a griffon from Acherus to Deaths Breach results in dying from fall damage, It also happens periodically when taking a griffon to major cities as well

**Expected behavior**: No fall damage on dismount from griffon

**Steps to reproduce**:

1. Go to Death Knight starting area
2. Take the Griffon to Deaths Breach
3. 

**Client version**: 3.3.5a

**Commit hash**: 3b35223d60b7a4dc7da2f86061f337bd436119f5

**Database version**: Latest UDB 

**Operating system**: [Unix] Ubuntu Server 16.04

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Fabi** [comment]
Same than https://github.com/cmangos/issues/issues/1061 I guess?

**Comment by CamilleMoon** [comment]
Yes very similar, the only difference, though a minor one is that it's on WotLK.

**Comment by Grz3s** [comment]
lol confirmed...
this is something new :o

**Comment by CamilleMoon** [comment]
It was a pleasant surprise for me, got on griffon, got some coffee and came back boom dead lol ^^

**Comment by cyberium** [comment]
For those who get that could you please try this fix then try to reproduce?

```diff
diff --git a/src/game/TaxiHandler.cpp b/src/game/TaxiHandler.cpp
index 8a5a07c..e4fabb7 100644
--- a/src/game/TaxiHandler.cpp
+++ b/src/game/TaxiHandler.cpp
@@ -234,7 +234,12 @@ void WorldSession::HandleMoveSplineDoneOpcode(WorldPacket& recv_data)
             GetPlayer()->m_taxi.ClearTaxiDestinations();    // clear problematic path and next
     }
     else
+    {
         GetPlayer()->m_taxi.ClearTaxiDestinations();        // not destinations, clear source node
+
+        // has taxi flight just finished reset fall information to avoid receiving fall damage
+        GetPlayer()->SetFallInformation(0, movementInfo.GetPos()->z);
+    }
 }
 
 void WorldSession::HandleActivateTaxiOpcode(WorldPacket& recv_data)
```

**Comment by Warlockbugs** [comment]
I know exactly why it happens and how to fix it, but this requires major taxi system changes, which i plan to do at a later point in the future.

**Comment by cyberium** [comment]
I think if those 4 lines fix the issue and dont require the whole rewrite it will be better for now (better than a promesse i mean). So if you want to revamp all taxi code its another thing. But thank you nice to now you have plan about it.

**Comment by Grz3s** [comment]
:+1:  yes it fixes  this problem

**Comment by cyberium** [comment]
Nice to know come on irc now :)

**Comment by CamilleMoon** [comment]
Yes,after I applied the patch, it seems to fix the issue, thank you. ^^

**Comment by Phatcat** [comment]
Closed by:
https://github.com/cmangos/mangos-wotlk/commit/efb071631915cb670fe3b6191e1c336a1813dbae
https://github.com/cmangos/mangos-tbc/commit/bf4d2cc4512ef1be719da969666a9aa11a357419
https://github.com/cmangos/mangos-classic/commit/779f1d4d207aea793eb64d762651766e221e8f57
