### ISSUE TITLE
[Classic] Crash in LBRS 

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1117]
**Current behavior**:
mangosd crashes in LBRS when fighting a group with a Scarshield Warlock (NPC 9257) a few moments after it summoned a scarshield portal. Crash report: https://gist.github.com/cala/76d3faa7356a0bce4ee0113e4b5497eb

**Expected behavior**: 
mangosd should not crash and the portal should spawn more NPCs (Warlock summons portal via spell, portal summons NPCs via spells)

**Steps to reproduce**:
1. Apply following AI code:

``` SQL
-- Fixed AI script for NPC 9707 (Scarshield Portal)
DELETE FROM creature_ai_scripts WHERE creature_id = 9707;
INSERT INTO `creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES
(970701, 9707, 11, 0, 100, 0, 0, 0, 0, 0, 11, 15127, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Scarshield Portal - Cast Summon Burning Imp on Spawn'),
(970702, 9707, 0, 0, 50, 1, 11000, 11000, 11000, 11000, 11, 16002, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Scarshield Portal - Cast Summon Burning Felhound'),
(970703, 9707, 0, 0, 10, 0, 20000, 20000, 0, 0, 11, 16004, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Scarshield Portal - Cast Summon Burning Felguard'),
(970704, 9707, 7, 0, 100, 1, 0, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Scarshield Portal - Despawn on Evade');

-- Fixed AI script for creatures summoned by NPC 9707 (Scarshield Portal)
DELETE FROM creature_ai_scripts WHERE creature_id IN (9708, 10261, 10263);
INSERT INTO `creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES
(1026101, 10261, 0, 0, 100, 1, 5000, 5000, 5000, 15000, 11, 15980, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Burning Felhound - Manaburn'),
(1026301, 10263, 11, 0, 100, 0, 0, 0, 0, 0, 11, 16074, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Burning Felguard - Cast Summon Burning Felguard Spawn on Spawn'),
(1026302, 10263, 0, 0, 100, 1, 10000, 10000, 10000, 10000, 11, 16046, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Burning Felguard - Blast Wave'),
(1026303, 10263, 0, 0, 100, 1, 5000, 5000, 15000, 20000, 11, 15548, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Burning Felguard - Thunderclap'),
(1026304, 10263, 0, 0, 100, 1, 5000, 7000, 4000, 6000, 11, 15580, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Burning Felguard -  Strike');
```
1. Enter LBRS and move to the first group with a warlock
2. Let him summon a portal. Enjoy the crash.

As I'm currently testing a new AI script for LBRS, this may come from something missing in the DB when summoning on of those NPCs, yet it should not lead to a crash in my opinion.

**Client version**: 
1.12.1
**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/ec9152dbd09ea6c1b6126ef627af24327e333560
**Database version**: 
Classic DB v1.7
**Operating system**: 
Mac OS X 10.6.8

**Comment by Phatcat** [comment]
Crash denied on my end ; try re-testing again against current master.

**Comment by Phatcat** [comment]
(I did apply the sql code before attempting to re-create, of course)

seems like the portal summons both the felhound and the imp fine, never saw the felguard on my end,
the portal itself was acting a bit strange acting like a mob, chasing and attacking the player.

**Comment by BeerfishWoW** [comment]
Portals attacking players. That's only a 'bit' strange. ^^

**Comment by cala** [comment]
> Portals attacking players. That's only a 'bit' strange. ^^

As I said: 
> As I'm currently testing a new AI script for LBRS

So, no surprise in those weird behaviours. :wink:
I cannot reproduce this crash either. Let's close it, I will reopen it if needed. Thank you very much for checking.
