### ISSUE TITLE
[Classic] Random crash (DBSave() ?)

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1119]
Random crash while playing. Crash log https://gist.github.com/cala/2328411b88499a68970bae9a3fa2f67e

**Client version**: 
1.12.1
**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/ec9152dbd09ea6c1b6126ef627af24327e333560
**Database version**: 
Classic DB v1.7
**Operating system**: 
Mac OS X 10.6.8

**Comment by Jose123456** [comment]
I just had a similar crash. Player 1 had just looted an item and was trying to trade it to player 2. Backtrace: https://gist.github.com/anonymous/0d5a27a550826bbcfa8b04edd7d948a8

I think what's happening is that the Item instance is being destroyed after the call to `Item::GetBagSlot` and before the call to `Item::GetSlot`. Notice how the `this` pointer changes from `0x7fa75ce79340` to `0x7fa700000000`.

Maybe `Item` is being destroyed [here](https://github.com/cmangos/mangos-classic/blob/master/src/game/Item.cpp#L674)?

**Comment by cyberium** [comment]
Cannot reproduce sorry, Next time please look at console output too and try to give more data about what item you are manipulating.
