### ISSUE TITLE
[Classic] Non-Optimal Misc Engineering Items

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1120]
**Current behavior**: 

Goblin Rocket Boots do not behave like they should; they should force you forward with increased speed and not just give you increased movement speed. also I don't see how we could ever be using the backfire effects when we in the db call the success spell directly from the item.

Gnomish rocket Boots suffer from some of the same issues as goblin rocket Boots (I don't remember if these should force you forward as well, but the missing backfires applies here as well)

Gnomish Harm Prevention Belt suffers from the same backfire issues

**Expected behavior**: 

Should be able to backfire / behave with side effects that is mentioned at the respective items, but on cmangos they all always just work.

**Comment by Lillecarl** [comment]
Does this affect other cmangos versions too?

**Comment by cyberium** [comment]
I think all ingé effect should be implemented one by one :/
