### ISSUE TITLE
[TBC] Crash with worldsession

### ISSUE THREAD

**Issue by gpcore** [cmangos/issues#1122]
**Current behavior**: Crash

**Expected behavior**: Crash

**Steps to reproduce**:

Dont know i look only logs

**Client version**: TBC

**Commit hash**: https://github.com/cmangos/mangos-tbc/commit/e1608b3f2a82601d4f98417701a757bd97088dab

**Database version**: tbc 1.5.0

**Operating system**: Windows 7 Service Pack 1

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)
[mangosd.exe_[15-10_22-32-2].txt](https://github.com/cmangos/issues/files/531451/mangosd.exe_.15-10_22-32-2.txt)

**Comment by Fabi** [comment]
yo man. you are not using your linked commit hash or the crash log is not from your linked commit hash or from a custom core. 

your crashlog says, that you are using something before https://github.com/cmangos/mangos-tbc/commit/c9a000a93798255875ae3d2632e6471772fd3ae6

**Comment by gpcore** [comment]
core clear i am compile core on my home pc and put bins on server machine, its maybe my problem?

**Comment by gpcore** [comment]
core clear i am compile core on my home pc and put bins on server machine, its maybe my problem?

**Comment by namreeb** [comment]
I'm going to close this for now.  The crash log references code which doesn't exist anymore.  If you have a crash using the current code, please feel free to open a new issue.
