### ISSUE TITLE
Cant run bins from github

### ISSUE THREAD

**Issue by gpcore** [cmangos/issues#1127]
**Operating system**: Win 7

Hello. Guys i cant run BINs from github DEBUG
System says i need 
msvcp140d.dll
vcruntime140d
ucrtbased.dll

I am download them solo but got error not found procedure
I am compile my debug build its run fine
Can you link where i can get your files i mean its vc++ 2015 version? i am install it but no luck..
i need same dlls for run your bins ty

**Comment by gpcore** [comment]
bins this rev
https://github.com/cmangos/mangos-tbc/commit/e1608b3f2a82601d4f98417701a757bd97088dab

**Comment by Fabi** [comment]
u always referencing this commit even if u don't use it. Are you a bot or something like that?
And I think this is not an issue, but related to support.... Open a thread on cmangos.net forum please (and use the latest binaries).
