### ISSUE TITLE
Qiraji Resonating Crystal

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1130]
**Current behavior**: 

Able to take out scarabs from AQ40. the only AQ40 mount that could be rode outside of AQ40 is the legendary mount; Black Qiraji Resonating Crystal which.... by the way is missing it's cast time

**Expected behavior**:

Should not still be mounted when they leave the instance. Probably people should be dismounted by leaving aq40 specifically.

**Steps to reproduce**:
1. `.additem 21218`
2. `.tele ahn'q`
3.  enter AQ40
4. use the scarab mount.
5. exit AQ40
6. now that you've confirmed the first bug, let's just recreate the black scarab one as well
7. `.additem 21176`
8. use the black scarab mount.

**Comment by cala** [comment]
Weird, I thought to have fix this one or two years ago and the issue was specific to Classic because TBC introduced in spell DBC the ability to restrict the use of a spell to an area.

May be related to how the auras are refreshed/reapplied. There is certainly something wrong here as I noticed two new issues recently, one that I reported about the combustion spell for mages on character load and one not reported yet: in Eastern Plaguelands, everytime a player captures one of the PVP tower,   a new Lordaeron Echoes aura is applied but the previous one is not removed until the player has some form of aura refresh like druid shapeshift.

**Comment by Phatcat** [comment]
Actually I just found yet another issue with the BLACK scarab mount;
you are able to use it in other areas where you shouldn't be allowed to mount up at all.

reproduce by;
1. `.tele diremaule`
2. try using a normal mount, any mount really.
3. now try using the black scarab mount.

**Comment by dagochen** [comment]
There are some more problems with it. If you are sitting on the black scarab mount and reuse the item, you dont get dismounted like other mounts. Instead you will be dismounted and upmounted again. Some other features like instantly switching mount to black scarab mount from another mount is not yet working. I am not 100% sure if that should work and if it is blizzlike, but there are several sources saying it did work that way.

Wrath-Logo-Small Patch 3.0.3 (04-Nov-2008): Converted into a normal mount, which removed one of its unique features - the ability to start summoning the mount while still in combat as long as the player was out of combat at the completion of the summon.
Bc icon Patch 2.2.0 (25-Sep-2007): Before this patch: unlike normal mounts, one could cast it while falling and mount up mid-air. (Though, if you landed while casting and took damage it interrupted the cast). Additionally, you could "insta switch" to the scarab mount while flying or running with another mount.

http://wowwiki.wikia.com/wiki/Black_Qiraji_Resonating_Crystal

**Comment by jimmybrancaccio** [comment]
Can anyone confirm which version(s) this affects? All three?

**Comment by cala** [comment]
The casting time for the Black Qiraji Tank should be fixed by https://github.com/cmangos/classic-db/commit/267137dfa8d04775f6733e976263680869452ab4

The other issue probably needs an update of the AQ40 script, I'll handle that later.

(issue's labels updated)

**Comment by cala** [comment]
And the AQ40 specific mounts are also fixed inn 
https://github.com/cmangos/mangos-classic/commit/de4e5e24332a934cb0d39e12eb8bbe6f86ff1cad.

At least, it is fixed for Classic. As area restriction for spells were added in DBC starting with TBC, I'm unsure this issue exists for TBC+ (and thus if this fix is also needed there).
