### ISSUE TITLE
[CLASSIC] Noggenfogger Elixir

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1131]
**Current behavior**: 

on cmangos currently your polymorph just takes over, and the effect is now effectively gone.

**Expected behavior**: 

Noggenfogger needs to be stronger, it needs to power through any polymorph;
https://youtu.be/LrljwQrM3uE?t=3m34s

**Steps to reproduce**:
1. Make a druid
2. .level 59
3. .learn all_myclass
4. .additem 8529
5. Drink the elixir, try a few times until you stop breathing (haha)
6. enter bear form
7. as a bonus, remove bear form again.

**Comment by kartoffelsup** [comment]
But only on Classic (afaik they fixed this in TBC)

**Comment by Phatcat** [comment]
Still polymorph seems to want to take priority while noggenfogger should have precedence. At least the transform is not totally lost as it is reapplied on morphing out of form again.
