### ISSUE TITLE
SPELL_AURA_MOD_INVISIBILITY - Blurry effect Stopped working

### ISSUE THREAD

**Issue by Grz3s** [cmangos/issues#1133]
**Current behavior**: 
With recent CmangoS ..all spells with Aura Id 18 (SPELL_AURA_MOD_INVISIBILITY), ... not gives player blurry effect anymore.
Im not sure when it was broken ... but it maybe effect of @Warlockbugs (aura stacking rules?)
Would be nice to have it back (like it was before) :)
Thanks

**Expected behavior**:
Spells with this aura should give player nice visual blurry effect:
few Examples:
1st:
```code
Spell: ID - 6298 Form of the Moonstalker 
Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 200
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 18 (SPELL_AURA_MOD_INVISIBILITY), value = 200, misc = 0 (0), miscB = 0, periodic = 0
```
http://www.wowhead.com/item=5387/enchanted-moonstalker-cloak#screenshots:id=59995
http://www.wowhead.com/item=5387/enchanted-moonstalker-cloak#screenshots:id=71613
this is how should work

2nd:
```code
ID - 30448 Shadow of the Forest
Effect 2: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 100
Targets (21, 0) (TARGET_SINGLE_FRIEND, NO_TARGET)
Aura Id 18 (SPELL_AURA_MOD_INVISIBILITY), value = 100, misc = 0 (0), miscB = 0, periodic = 0
```
should look like this: 
https://www.youtube.com/watch?v=f00kCEI8t60&list=PL28173C4849CA7E04&index=3  watch from 2:55

**Steps to reproduce**:
1.  Cast 30447 on yourself or one of above 2 spells  ... 

**Client version**: 
Newest
**Database version**: 
Wotlk-DB (Newest)
**Operating system**: 
Win7

**Comment by Laizerox** [comment]
@Grz3s Wotlk repo doesnt have effect rules yet because these rules in wotlk are bit different and we lack support for it (partial effect application on aura apply).

In short all stacking rules are same as before on wotlk repo

**Comment by Grz3s** [comment]
ok then... so need to find what damaged it :(

**Comment by Grz3s** [comment]
sor my mistake
