### ISSUE TITLE
[WotLK] Ubuntu 16.04 Failed compiling scriptdev2.

### ISSUE THREAD

**Issue by CamilleMoon** [cmangos/issues#1134]
Failed to compile ScriptDev2, Do we have to go back to including ScriptDev2 in Bindings or link the folder itself?
 
[ 38%] Linking CXX executable mangosd
/usr/bin/ld: cannot find -lscriptdev2
collect2: error: ld returned 1 exit status
src/mangosd/CMakeFiles/mangosd.dir/build.make:289: recipe for target 'src/mangosd/mangosd' failed
make[2]: *** [src/mangosd/mangosd] Error 1
CMakeFiles/Makefile2:1057: recipe for target 'src/mangosd/CMakeFiles/mangosd.dir/all' failed
make[1]: *** [src/mangosd/CMakeFiles/mangosd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Client version**: 3.3.5a

**Commit hash**: 409f11f9acc006769a38896b3b36b1263805535e

**Database version**: UDB Latest

**Operating system**: Ubuntu Server 16.04

**Comment by Warlockbugs** [comment]
Should be fixed in https://github.com/cmangos/mangos-wotlk/commit/83b4e01f6af73c506c319eaa59b9424fb1ccd35a.

**Comment by CamilleMoon** [comment]
Sweet thank you!
