### ISSUE TITLE
[TBC][WOTLK] Paladin Seal Effects Don't Work After Re-Logging In

### ISSUE THREAD

**Issue by natiewow** [cmangos/issues#1135]
**Current behavior**: 
Paladin Seals do nothing after client relog. The buff icon stays in place but none of the effects work until the Seal is reapplied. Judgement buttons are active and can be used normally.

**Steps to reproduce**:
1. Make a Paladin and put on your starting Seal
2. Log out and on again
3. Hit any mob and notice the seal not doing damage

The issue is present for all the later Seals as well.

**Client version**: 
3.3.5a

**Commit hash**: 
cmangos/mangos-wotlk@492d9b86b4a47cd87cd691d0f56c74524c60497c

**Database version**: 
UDB 0.12.2 (408) for CMaNGOS-WOTLK

**Operating system**: 
FreeBSD 11-RELEASE

**Comment by Warlockbugs** [comment]
The same applies to Combustion after logout. The potential fix is here: https://github.com/cmangos/mangos-tbc/pull/133#discussion_r82487482.

**Comment by al3xc1985** [comment]
This cannbe closed
