### ISSUE TITLE
[TBC] Debug core crash in 10 sec

### ISSUE THREAD

**Issue by gpcore** [cmangos/issues#1136]
**Current behavior**: 
Compiled core on vs13 or vs15 in Debug mode. No error, server run fine. Server crashing in 10 sec every time in idle mode. I am not truing connect or somthing. Just run, wait 5-10 sec got crash

Server console say list row
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\random(2224): invalid min and max arguments for uniform_int

**Client version**: 
2.4.3
**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/e871f4a5ad6c6c2cd9b64bbd8a4052d0ba739682
**Database version**: 
tbc-db
**Operating system**: 
Windows 7 SP1

[mangosd.exe_[31-10_8-8-5].txt](https://github.com/cmangos/issues/files/560921/mangosd.exe_.31-10_8-8-5.txt)

**Comment by Lillecarl** [comment]
Can anyone else reproduce this? Seems rather machine specific, I've ran cmangos on Windows without getting this error.

**Comment by namreeb** [comment]
The code looks okay to me.  Maybe try a fresh recompile?

**Comment by gpcore** [comment]
I am test it on 2 diff machine both win7
I am test fresh compile

I am just cant test core on my home machine with out debug mode

Lillecarl its possible machine specific but how i can fix it... i dont know

**Comment by cyberium** [comment]
It should be fixed on latest revesion. Can you retry it please and confirm it work?

Its ahbot crash.
