### ISSUE TITLE
[TBC] Eye of the Beast crash

### ISSUE THREAD

**Issue by gpcore** [cmangos/issues#1137]
**Current behavior**: 
When you cast spell Eye of the Beast and relog from game you crashing server

**Steps to reproduce**:

1. Use spell Eye of the Beast
2. Relog from game or just leave game

**Client version**: 
2.4.3
**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/e871f4a5ad6c6c2cd9b64bbd8a4052d0ba739682
**Database version**: 
tbc-db
**Operating system**: 
Linux openSuse

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)
[crash.txt](https://github.com/cmangos/issues/files/561119/crash.txt)

**Comment by SilvioDoMine** [comment]
Issue confirmed, waiting any fix a long time ago. #968 #1031 #1068

**Comment by Phatcat** [comment]
There is a big patch that cyberium has pull requested on both classic and tbc bringing about a lot of improvements to pets, especially in regards to charmed pets (which all should get ported to wotlk as well, though they may have to wait a bit longer).

Classic: https://github.com/cmangos/mangos-classic/pull/210
TBC: https://github.com/cmangos/mangos-tbc/pull/139

Currently the changes are getting peer reviewed which takes a bit of time, especially with larger patches.
If you are interested in helping move the process along in getting these merged, then there is always a need for more testers to test out and give feedback on the changes.

**Comment by gpcore** [comment]
I am tested this pull request. Core crash on use spell Eye of the Beast
..\..\src\game\AI\PetAI.cpp:128: Error: Assertion in PetAI::UpdateAI failed: charminfo

**Comment by Phatcat** [comment]
should be solved in https://github.com/cmangos/mangos-tbc/commit/65067e440885d6278252d6a65c2495b2f6701e72
