### ISSUE TITLE
[CLASSIC] Shadowguard Does Not Trigger Blackout

### ISSUE THREAD

**Issue by Itzamnaaj** [cmangos/issues#1138]
**Current behavior**: 

As a troll priest with the Blackout talent and Shadowguard active, being hit by an attacker will not trigger Blackout.

**Expected behavior**: 

Shadowguard damage should have a chance to trigger Blackout, according to the patch notes from 1.11 ( source: http://wowwiki.wikia.com/wiki/Patch_1.11 ):

"Shadowguard: This Troll Priest racial spell now works with Vampiric Embrace, Blackout, and Shadow Weaving. In addition, the damage from Shadowguard will now consume charges of the Zandalarian Hero Charm's Unstable Power aura. The range on Shadowguard has been extended to hit anyone within vision range."

The following sequence of events should occur (using Shadowguard (rank 1) as an example):

- Shadowguard (rank 1) (spellID: 18137) is active on the player as an aura.
- Player is hit by an attacker.
- Shadowguard (rank 1) triggers spell 28376, damaging the attacker.
- If player has the Blackout talent (spellID: 15268, 15323, 15324, 15325, 15326), there is a 2-10% chance the attacker is affected by Blackout (spellID: 15269), a 3 second stun.

**Steps to reproduce**:

1. Make a troll priest character, level to 20.
2. Cast Shadowguard, recast if all charges are consumed.
3. Aggravate a hostile NPC, just let him attack you and trigger Shadowguard.
4. After 200 or so Shadowguard triggers with Blackout (rank 5), you can be pretty sure Blackout does not trigger.

**Client version**: 

1.12.1 (5875).

**Commit hash**: 

d8bca976881ef241299c2f9da46c85300567170a

**Database version**: 

Classic-DB, commit hash: 0afdf3619063716958c06b681e8f5443a50c7789.

**Operating system**: 

Gentoo GNU/Linux.

**Extra information**:

Shadowguard and Blackout may be a problematic combination because a triggered spell (Shadowguard, spellID: 28376) needs to trigger another triggered spell (Blackout, spellID: 15269). This may be indicative of a problem with the generic code handling EffectTriggerSpell. I recall TrinityCore having no problem with Shadowguard and Blackout, perhaps one could take a look at their triggered spell handling to see how they handle it?

**Comment by killerwife** [comment]
Related to SPELL_ATTR_EX3_UNK26 (blackout) and SPELL_ATTR_EX3_UNK9(shadowguard damage triggered proc). I am planning to implement them for some time now, will try to do it over the weekend.

**Comment by Itzamnaaj** [comment]
Thank you, Killerwife. If you need any debugging, let me know.

**Comment by killerwife** [comment]
https://gist.github.com/killerwife/504ed15d92bbd043e0e4721066670450 @Itzamnaaj this fixes the issue, but sadly discovered another one: Blackout procs Shadow Vulnerability

Sooner or later I figure out this problem and then I will PR this all.

**Comment by Itzamnaaj** [comment]
Great work killerwife, I will keep this patch applied until your pull request gets accepted.

If this patch introduces any other regressions, I will post them here.

**Comment by Itzamnaaj** [comment]
Hello,

Has anyone looked at this bug lately? It's still a problem on revision z2697.
