### ISSUE TITLE
[TBC]VS2013 error c1083 mangos-tbc-Last_mangos-tbc_PreBuild

### ISSUE THREAD

**Issue by kuramajssken001** [cmangos/issues#1139]
Error c1083 can not open  “..\..\src\game\AggressorAI.cpp”: No such file or directory	D:\Code\TBC\mangos-tbc-Last_mangos-tbc_PreBuild\mangos-tbc-Last_mangos-tbc_PreBuild\win\VC120\c1xx	game

**Comment by Lillecarl** [comment]
@cyberium This one should be closed, CI proves this isn't valid.

**Comment by cyberium** [comment]
yes i
