### ISSUE TITLE
Quest availability

### ISSUE THREAD

**Issue by Muehe** [cmangos/issues#1140]
Ok, so this is the situation in DB:

**Quest ID** | **PrevQuestId** | **NextQuestId** | **ExclusiveGroup**
--- | --- | --- | ---
203 | 0 | 574 | -203
204 | 0 | 574 | -203
207 | 203 | 0 | 0
574 | 0 | 0 | 0

And the Wiki says 

> **if ExclusiveGroup < 0**
>
> Allows to define a group of quests of which all must be completed and rewarded to start next quest. E.g. if quest 1000 dependent from one of quests 1200, 1201 and 1202 and all this quests have same negative exclusive group then all this quest must be completed and rewarded before quest 1000 can be started.

Judging by this explanation I would expect quest 207 and 574 to become available once 203 and 204 are finished, yet only 574 behaves like that. 207 becomes available once 203 is finished.

**Comment by killerwife** [comment]
So the idea is you cant set 2 quests in NextQuestId.
Likely what needs to be added is add negative value to PrevQuestId so that it signifies exclusive group previous to it rather than singular quest.

**Comment by Muehe** [comment]
Negative PrevQuestId already has an assigned meaning, it indicates a parent quest that has to be active.

**Comment by killerwife** [comment]
Well I wonder if something like Exclusive Group Quest 1 -> Next Quest can happen or only something like Exclusive Group Quests -> Next Quest.

**Comment by Muehe** [comment]
Well, this would work for letting both quests appear after the group is finished:

**Quest ID** | **PrevQuestId** | **NextQuestId** | **ExclusiveGroup**
--- | --- | --- | ---
203 | 0 | 207 | -203
204 | 0 | 574 | -203
207 | 0 | 0 | 0
574 | 0 | 0 | 0

Still wondering if this is intended behaviour though. If it is, the wiki explains it kind of confusingly...

**Comment by killerwife** [comment]
Please research this + quests in question and let me know. Maybe we might need to break down this logic into a separate table to enable more flexibility. (such as 2 quest exclusive group leading into 3 quest followup group)

**Comment by Muehe** [comment]
Unfortunately the quests at hand give no hints to the order they should be acquired in. But I have found one quest chain that could be interesting:


**Quest ID** | **PrevQuestId** | **NextQuestId** | **ExclusiveGroup**
--- | --- | --- | ---
2761 | 2760 | 2765 | -2761
2762 | 2760 | 2765 | -2761
2763 | 2760 | 2765 | -2761
2764 | 2761 | 0 | 0
2765 | 0 | 0 | 0

So right now you do three quests to get awarded Expert Blacksmith! (2765) and this guy praises you as one of his finest pupils, but after doing only 2761 you get the quest Galvan's Finest Pupil (2764) which talks about the training being finished and sends you on to another student of his. Doesn't seem right.

**Comment by killerwife** [comment]
Yes you are very likely right. Issue is do we change one logic into another or do we need to introduce new columns/tables so that both (quest 1 into next) and (quest group into next) are preserved.

**Comment by cyberium** [comment]
Summon @cala @Grz3s here. Do we need to change some table behavior here?

**Comment by Tobschinski** [comment]
Schmoozerd wanted to use conditions instead, as far as I remember

**Comment by Grz3s** [comment]
hi ... yes ... we do have some issues with this part and smth should be done. (added)
I Cant say much about issue @Muehe reported here... but problably its true...
I also reported something else in same subject:
https://github.com/cmangos/wotlk-db/issues/7
and also ... conditions were (IMHO) solution for that.

**Comment by killerwife** [comment]
Except, I already implemented conditions and am working on a legit PR as of right now. Just hold on fellas, tomorrow PR is there and in a week its merged :)

**Comment by cala** [comment]
Let me some time to look at this issue and make my opinion, please.

**Comment by killerwife** [comment]
The PR will not be merged for the next week AT LEAST. So no problem.

**Comment by Muehe** [comment]
@Grz3s What's needed in the issue you linked are two different (positive) ExclusiveGroups for three quests (also impossible in the current system), the issue I reported is that there can not be n+1 quests opened up by the same (negative) ExclusiveGroup, with n being number of quests in that group.

@killerwife Do you plan on removing the current system? Seems to be redundant if I understand the conditions stuff correctly...

**Comment by killerwife** [comment]
Quest grouping definitely has to stay so that we can identify groups. The other things like "required skill" could be removed. Problem is these implementations need someone with a lot of free time to change it to the new system. Likely I would need to implement new condition "has quest group completed" and "has quest group taken". The exact specifications need to be researched, but I am happy to implement them, since the condition_id table enables many things.

**Comment by Muehe** [comment]
Well from what I red [here](https://github.com/cmangos/issues/wiki/Conditions), conditions are combinable with binary operators and should cover most, if not all, of the group fields (PrevQuestId/NextQuestId/ExclusiveGroup).

**Comment by killerwife** [comment]
Maybe, but I have plans for ExclusiveGroup, even if I rename it to QuestGroup.

**Comment by Muehe** [comment]
@killerwife Closed by https://github.com/cmangos/mangos-classic/commit/808442a5bc7cecf5783769a55e84004726c48263?

**Comment by killerwife** [comment]
Yup, in theory. Afaik fixed issues for wotlk branch, should fix for you too.

**Comment by jimmybrancaccio** [comment]
Checking in here to see if this is a case we can close out. Thanks guys!

**Comment by Muehe** [comment]
I'm unsure what, if anything, @killerwife has done about the ominous plans for `ExclusiveGroup`, would be interested to know.

Also with the condition system now implemented I think there is a discussion to be had about keeping DB fields which could be replaced by conditions. I know this would be a pretty big change, but having two systems in place which handle the same stuff seems unwise. DRY principle and possibility of conflicting data for the same quest when both systems are used unknowingly are what motivates my thinking here. So I would like to know what other peoples opinion about this.

Apart from that I guess the issues with the quests I noted above might still exist (have not tested) but they would probably better be handled in new DB issues now.

**Comment by killerwife** [comment]
ExclusiveGroup is still limited, but its still a valid use. I added condition column to quest_template which enables us to handle more complex conditions. The reason against using conditions everywhere, is potential issue of updating quest givers when something critical changes. Right now I have not found such an issue in classic and tbc, there might be an issue with Cold Weather Flying in wotlk I think. Other than that, DB structure at the moment enables us to do everything, albeit in a bit of a duplicate manner.

**Comment by al3xc1985** [comment]
@killerwife can ir be closed?

**Comment by killerwife** [comment]
This can be closed, exclusive group is now debugged and working and conditions do what is too complex for it.
