### ISSUE TITLE
InstallFullDB error applying z2688_01_mangos_flametongue.sql

### ISSUE THREAD

**Issue by BareRose** [cmangos/issues#1141]
**Current behavior**: 
InstallFullDB.sh fails with error:
Append core update z2688_01_mangos_flametongue.sql to database mangos ERROR 1054 (42S22) at line 1: Unknown column 'required_z2687_01_mangos_spell_chain' in 'db_version'
**Expected behavior**: 
There should be no error, it should simply be able to apply the update correctly.
**Steps to reproduce**:
1. Follow install instructions up to the part where you're told to run InstallFullDB.sh
2. Run InstallFullDB.sh
3. Get error as described above.

**Client version**: 
1.12.1
**Commit hash**: 
8c94d21
**Database version**: 
classicdb
**Operating system**: 
Windows7 64bit (Also compiled everything in 64bit)

**Comment by Grz3s** [comment]
Reason for this is this commit:
https://github.com/cmangos/classic-db/commit/93920f2bf602a08ae9eeda18e1116c791986fb5d
First:
Its 2688 not 2687..(title)
Second:
Author forgot to change this ...in InstallFullDB.sh
```code
(...)
 LAST_CORE_REV="**2687**"     <---- here ... should be 2688
 # process future release folders 
 NEXT_MILESTONES="0.12.4 0.12.5" 
(...)
```

**Comment by cala** [comment]
Fixed. Should be pushed soon.

**Comment by BeerfishWoW** [comment]
I ran into this one, too, thank you for this fix!
