### ISSUE TITLE
[TBC] Cannot Have More Than One Fireball/Frostbolt on a Target at Any One Time

### ISSUE THREAD

**Issue by Tixlenra** [cmangos/issues#1142]
**Current behavior**: 
When casting Fireball/Frostbolt, if another mage casts a Fireball at a lower rank, it doesn't allow them to cast because 'a more powerful spell is already active' - if you cast a Fireball at the same rank, the debuff on the first mages fireball refreshes.

**Expected behavior**: 
Should be able to cast Fireball/Frostbolt regardless. _I also have a hunch that if it affects these two abilities, a variety of other abilities are affected aswell._

**Steps to reproduce**:

1. Cast fireball a rank higher than your friend/even the same rank
2. Get a friend to cast Fireball
3. Observe

**Client version**: 
TBC

**Commit hash**: 
bf2bb58f6d449fefec46d774e48bb2774c5e3d84

**Database version**: 
0d7deb3567037d2d2ec3b7913688b9de098f3dad

**Operating system**: 
Windows

**Comment by Phatcat** [comment]
Could be that the 'a more powerful spell is already active' should only be checked on effect 0, just like dispel effects on the classic core only should look at effect 0 or it would break some spells like abolish poison, it could be a similar type of thing here.

**Comment by AnonXS** [comment]
resolved
