### ISSUE TITLE
[WotLK] Cenarion Hold crash

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1144]
**Current behavior**: 

![telecrash](https://cloud.githubusercontent.com/assets/1907820/20227922/20bbc88a-a84f-11e6-8b7d-d241fdca7ace.JPG)

**Expected behavior**: 

No explosions.

**Steps to reproduce**:

1. make an alliance char
2. `.level 79`
3. `.tele cenarionhold`

Hmm.... on closer inspection of my server log there it may be totally unrelated to teleporting and all related to some cenarion hold content..

**Client version**: 
3.3.5a - tested and DENIED on 1.12.1 - teleporting to cenarion hold on the classic branch seems to have no issue at all.

**Operating system**: 

Windows 10

**Comment by Phatcat** [comment]
Now it happened again on `.tele darnassus` - what the...
> https://github.com/cmangos/issues/issues/1045

**Comment by namreeb** [comment]
Can you post a stack trace?

**Comment by Phatcat** [comment]
No stack trace sadly, it seems to be happening 100% of the time (at least the cenarion hold one) - I can try running it visual studio debugging mode and see if it can tell me where the program aborts?

**Comment by namreeb** [comment]
Yes please.  If you click Retry on that error window that appears it will attach Visual Studio.  There should be a call stack window that gives you the stack trace.

**Comment by Phatcat** [comment]
usually I look in the crash folder for the stack trace since I'm on windows, but for this issue it seems to not create a crash dump.

![callstack](https://cloud.githubusercontent.com/assets/1907820/20228990/53897410-a854-11e6-9a6f-f1109e9210ff.JPG)

**Comment by Grz3s** [comment]
have same crash there...
related to this?  (maybe there someone with repeatable quest)
https://github.com/cmangos/issues/issues/1148

**Comment by Darth-Postal** [comment]
I don't know if it's related, but after updating to the latest core, mangosd.exe just closes when I fly over Wintergrasp in a taxi. There is no crash dump. It just closes. Like if someone pressed Ctrl-C.

Steps to reproduce:
1. Go to Dalaran Taxi NPC.
2. Select River's Heart (Scholazar) as destination.
3. After you enter Wintergrasp, mangosd.exe just closes.

**Comment by cyberium** [comment]
Could you please rebuild last version and check if its still the case?
It should be fixed by -> https://github.com/cmangos/mangos-wotlk/commit/832f9793f1acfc4d4d5c87a5763da64f8518e302

**Comment by cyberium** [comment]
https://github.com/cmangos/mangos-wotlk/tree/master/src/shared
SystemConfig.h is indeed here so i dont know what happening on your side.
So maybe redo a clone or a -> git reset --hard origin/master
assuming origin is github/cmangos/mangos-wotlk ofc

**Comment by Darth-Postal** [comment]
`git reset --hard` worked :+1:  No idea what happened there. I only did the usual git pull to update. Didn't modify anything.

https://github.com/cmangos/mangos-wotlk/commit/832f9793f1acfc4d4d5c87a5763da64f8518e302 also worked :+1:  (at least for my Wintergrasp taxi crash). Made several flights back and forth - no crashes.

Thank you!

**Comment by cyberium** [comment]
Ok then i think i can close this. Thank for the feedback.
