### ISSUE TITLE
[TBC] Hellfire Gateways incorrect rotations

### ISSUE THREAD

**Issue by Saben65** [cmangos/issues#1145]
**Current behavior**: 
![Example](https://i.gyazo.com/4852607651ec403c1d804f107031833f.jpg)

Portals have incorrect rotation (currently set to 0) which causes them to cut into the ground.
```SQL
select * from `gameobject` WHERE `guid` IN (24223,24222,25120,25256,25257,50347);
```
**Expected behavior**: 
They should lay flat on the ground.

**Steps to reproduce**:

1. .go -336 1519 49 for one example

**Client version**: 
2.4.3

**Commit hash**: 
99e508c52c805d1def882626e6ff79d1e52128c0

**Database version**: 
TBC-DB 1.5.0 'PRE-RELEASE BUILD' for CMaNGOS-TBC

**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Suggested Fix:**
```SQL
UPDATE `gameobject` SET `rotation0`=0.06277, `rotation1`=-0.082591, `rotation2`=0.992224, `rotation3`=-0.06878 WHERE `guid`=24223; -- Gateway Shaadraz
UPDATE `gameobject` SET `rotation0`=-0.042582, `rotation1`=-0.058682, `rotation2`=0.995897, `rotation3`=0.054151 WHERE `guid`=24222; -- Gateway Murketh
UPDATE `gameobject` SET `rotation0`=0.101759, `rotation1`=0.005215, `rotation2`=0.9523, `rotation3`=0.28765 WHERE `guid`=25120; -- Portal Xilus
UPDATE `gameobject` SET `rotation0`=0.077892, `rotation1`=-0.124166, `rotation2`=0.683997, `rotation3`=0.714607 WHERE `guid`=25256; -- Portal Grimh
UPDATE `gameobject` SET `rotation0`=0.106593, `rotation1`=-0.075655, `rotation2`=0.96054, `rotation3`=0.245516 WHERE `guid`=25257; -- Portal Kaalez
UPDATE `gameobject` SET `rotation0`=0.06086, `rotation1`=-0.078313, `rotation2`=0.995058, `rotation3`=0.00479 WHERE `guid`=50347; -- Portal Kruul
```

**Comment by Grz3s** [comment]
WotlkDB has ..all correct (sniffed) data for these... so if u need them ;)

**Comment by Saben65** [comment]
I wanna say I got it from Sniff data as well, but if I did not then they were pulled from TrinityCore.

**Comment by Phatcat** [comment]
Since this has now been opened at tbc-db where it fits, I will close this one.

Not saying you have to, but you should check your data against wotlk-db if it's already implemented there, as we like to keep our repos as synced up as possible, and we do value pure sniff data over tc data (unless you got your from tbc sniff data and there's a difference between it and the data in wotlk-db)
