### ISSUE TITLE
Dagger Hills, Westfall crash.

### ISSUE THREAD

**Issue by DaMadBoy** [cmangos/issues#1148]
**Current behavior**: 
When walking towards the area, where a quest item is located for the quest Dry Times (116) the server crashes and continues to crash everytime you try to log in. 

**Expected behavior**: 
To walk around the area without the server crashing.

**Steps to reproduce**:

1. Teleport to Westfall.
2. Walk up to Dagger Hills.
3. Move towards the quest item in quest 116.

**Client version**: 
12340 Wrath of the Lich King

**Commit hash**: 

**Database version**:
UDB 0.12.2(408) WOTLK

**Operating system**: 
Ubuntu Server 16.04

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)
Core was generated by `/root/cmangos/bin/mangosd'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fba0cc0e428 in __GI_raise (sig=sig@entry=6)
   at ../sysdeps/unix/sysv/linux/raise.c:54
54    ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fb9fac60700 (LWP 24369))]
(gdb) bt
#0  0x00007fba0cc0e428 in __GI_raise (sig=sig@entry=6)
   at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fba0cc1002a in __GI_abort () at abort.c:89
#2  0x00007fba0d76d84d in __gnu_cxx::__verbose_terminate_handler() ()
  from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fba0d76b6b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fba0d76b701 in std::terminate() ()
  from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fba0d796d38 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fba0cfa970a in start_thread (arg=0x7fb9fac60700)
   at pthread_create.c:333
#7  0x00007fba0ccdf82d in clone ()
   at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by Grz3s** [comment]
Confirmed
Build x64 for win7...
Same DB.

It looks like that removing NPC 239..Grimbooze Thunderbrew
http://www.wowhead.com/npc=239/grimbooze-thunderbrew
Fixes Issue... 
But ofc he cannot be removed... (only wants to say where problem is)... Ill do some more tests today to check what exact. is happening with him (gossip /quests relations? / or smth else)

**Comment by Grz3s** [comment]
Ok i have found where issue is:
Quest 117 ..has SpecialFlag = 1 Repeatable. ( and this crashes server) ... removing this flag ..and all works fine..
Also i checked diff. quest to make sure thats correct... creature:
Rivern Frostwind <Wintersaber Trainer> c.10618 .. offers quest 5201 .. with this flag = crashes server.
Skybreaker Squad Leader c.31737 offers quest 13284 .. with this flag = crashes server.
"houston we have a problem" :(
