### ISSUE TITLE
[CLASSIC] Echeyakee's Grace Not Cast (+ Other Quest Rewards Buffs)

### ISSUE THREAD

**Issue by HanFox** [cmangos/issues#1150]
**Current behavior**: The buff is not received on completion of the [Echeyakee](http://db.vanillagaming.org/?quest=881) quest.

**Expected behavior**: Receive a +2(?) Spirit buff for 30mins called [Echeyakee's Grace](http://www.wowhead.com/spell=5320/echeyakees-grace)

**Steps to reproduce**:

1. Get the quest from [Sergra Darkthron](http://www.wowhead.com/npc=3338/sergra-darkthorn) in The Barrens.
2. Summon Echeyakee with the horn and kill/subdue him.
3. Hand in quest to get buff.

**Client version**: 1.21.1 (5875)

**Commit hash**: https://github.com/cmangos/mangos-classic/commit/f9abcf3304e16a74348f82a09f734f05e01e2c0d

**Database version**: https://github.com/cmangos/classic-db/commit/ff98f2a40e64939e0e3020cf8bc5a966ce477e92 (with https://github.com/cmangos/classic-db/commit/b1bd5d345bd267e7ceadb4bbf2a767bc03bed886 manually applied)

**Operating system**: Client and Server are both on Arch Linux (Client is emulated via Wine).

**Other**: I'm not sure if it's a +2 buff or was originally a +1 buff. I didn't take a note before I completed the quest.
Considering some checks I did, it seems to have been missing for a while (i.e. in Feb 2015 it was posted on the Nost forum that it was missing: https://forum.nostalrius.org/viewtopic.php?f=6&t=724#p6686).
I only checked Classic. It may be missing from other versions, too.

**EDIT:** I prodded around in the db and it appear that the RewSpellCast (which I suspect is meant to be the buff?) is set to 5320, but I don't know where the actual spell would be.

**Comment by evil-at-wow** [comment]
The RewSpellCast number you mention is the spell ID, and [5320](http://www.wowhead.com/spell=5320/echeyakees-grace) even seems to be the correct spell. Spells are not defined in the database but in the client files (more specifically in the dbc files that the server also needs; this is one of the reasons why you need to extract a few client files to run the server).

So the buff not being applied could end up being a core issue (I didn't check).

**Comment by HanFox** [comment]
Ah, I guess that's the point of Warden to make sure you've not altered files then. I never knew. I thought the db would have the spells, too ;)

Regardless, it also appears that the buffs from [Mangletooth](http://db.vanillagaming.org/?npc=3430) when giving him Blood Shards do not work either. So I guess that when it comes to quest buffs the core is just missing the event to cast them?

**Comment by MrMarvin** [comment]
Quest reward spells are triggered by[ `Player::RewardQuest(...)` on the Player object](https://github.com/cmangos/mangos-tbc/blob/master/src/game/Entities/Player.cpp#L13073). This function includes logic to decide who is the appropriate caster of the reward spell, [depending on a few details of the to-be-cast spell](https://github.com/cmangos/mangos-tbc/blob/master/src/game/Entities/Player.cpp#L13213-L13218): 

```c++
Unit* caster = this;
[...]
 if (spellProto->Effect[i] == SPELL_EFFECT_LEARN_SPELL ||
                            spellProto->Effect[i] == SPELL_EFFECT_CREATE_ITEM ||
                            spellProto->EffectImplicitTargetA[i] == TARGET_UNIT ||
                            spellProto->EffectImplicitTargetA[i] == TARGET_UNIT_FRIEND)
                    {
                        caster = (Unit*)questGiver;
                        break;
}
```
This logic was introduced by @boxa in in late 2016 with https://github.com/cmangos/mangos-tbc/commit/456db02a42 . While the understanding that

> Some of these spells have self cast, but others don't, so just having the player cast them is not the way to go, just as always having the questgiver cast them is wrong as well

appears to hold true, **the decision for `EffectImplicitTargetA{1,2,3} == TARGET_UNIT` (and `TARGET_UNIT_FRIEND`) seems incorrect.**

Looking at TBC, these are the Spells that would be cast by the Quest NPC:
```sql
SELECT q.entry, q.Title, s.Id, s.SpellName, s.Effect1, s.EffectImplicitTargetA1, s.EffectImplicitTargetA2, s.EffectImplicitTargetA3 FROM tbcmangos.quest_template as q JOIN tbcmangos.spell_template  as s ON q.RewSpellCast = s.id WHERE s.Effect1 in (36, 24) OR s.Effect2 in (36, 24) OR s.Effect3 in (36, 24) OR s.EffectImplicitTargetA1 in (25, 21) OR s.EffectImplicitTargetA2 in (25, 21) OR s.EffectImplicitTargetA1 in (25, 21);
```

|entry|Title|Id|SpellName|Effect1|EffectImplicitTargetA1|EffectImplicitTargetA2|EffectImplicitTargetA3|
|---|---|---|---|---|---|---|---|
|5061|Aquatic Form|1446|Aquatic Form|36|0|0|0|
|96|Call of Water|5396|Healing Stream Totem|36|0|0|0|
|31|Aquatic Form|1446|Aquatic Form|36|0|0|0|
|755|Rites of the Earthmother|1126|Mark of the Wild|6|21|0|0|
|772|Rite of Vision|1126|Mark of the Wild|6|21|0|0|
|873|Isha Awak|5325|Strength of Isha Awak|6|21|0|0|
|881|Echeyakee|5320|Echeyakee\'s Grace|6|21|0|0|
|882|Ishamuhale|5321|Ishamuhale\'s Rage|6|21|0|0|
|883|Lakota\'mani|5322|Lakota\'mani\'s Thunder|6|21|0|0|
|884|Owatanka|5323|Speed of Owatanka|6|21|0|0|
|885|Washte Pawne|5324|Washte Pawne\'s Resolve|6|21|0|0|
|889|Spirit of the Wind|16618|Spirit of the Wind|6|25|0|0|
|1470|Piercing the Veil|7763|Teach Summon Imp|36|0|0|0|
|1471|The Binding|11520|Teach Summon Voidwalker|36|0|0|0|
|1474|The Binding|11519|Teach Summon Succubus|36|0|0|0|
|1485|Vile Familiars|7763|Teach Summon Imp|36|0|0|0|
|1498|Path of Defense|8121|Path of Defense|36|0|0|0|
|1504|The Binding|11520|Teach Summon Voidwalker|36|0|0|0|
|1513|The Binding|11519|Teach Summon Succubus|36|0|0|0|
|1518|Call of Earth|8073|Stoneskin Totem|36|0|0|0|
|1521|Call of Earth|8073|Stoneskin Totem|36|0|0|0|
|1527|Call of Fire|2075|Searing Totem|36|0|0|0|
|1531|Call of Air|8385|Swift Wind|6|25|25|0|
|1532|Call of Air|8385|Swift Wind|6|25|25|0|
|1598|The Stolen Tome|7763|Teach Summon Imp|36|0|0|0|
|1599|Beginnings|7763|Teach Summon Imp|36|0|0|0|
|1652|The Tome of Valor|5503|Sense Undead|36|0|0|0|
|1661|OLD The Tome of Nobility|13820|Summon Warhorse|36|0|0|0|
|1665|Bartleby\'s Mug|8121|Path of Defense|36|0|0|0|
|1678|Vejrek|8121|Path of Defense|36|0|0|0|
|1683|Vorlus Vilehoof|8121|Path of Defense|36|0|0|0|
|1689|The Binding|11520|Teach Summon Voidwalker|36|0|0|0|
|1719|The Affray|8616|Path of the Berserker|36|0|0|0|
|1739|The Binding|11519|Teach Summon Succubus|36|0|0|0|
|1785|The Tome of Divinity|7329|Redemption|36|0|0|0|
|1788|The Tome of Divinity|7329|Redemption|36|0|0|0|
|1795|The Binding|1373|Teach Summon Felhunter|36|0|0|0|
|1819|Ulag the Cleaver|8121|Path of Defense|36|0|0|0|
|2203|Badlands Reagent Run II|11522|Restorative Potion|36|0|0|0|
|2359|Klaven\'s Tower|2995|Poisons|36|0|0|0|
|2480|Hinott\'s Assistance|2995|Poisons|36|0|0|0|
|2501|Badlands Reagent Run II|11522|Restorative Potion|36|0|0|0|
|2756|The Old Ways|11132|Teach Orcish War Leggings|36|0|0|0|
|2771|A Good Head On Your Shoulders|11203|Teach Ornate Mithril Helm|36|0|0|0|
|2772|The World At Your Feet|11204|Teach Ornate Mithril Boots|36|0|0|0|
|2773|The Mithril Kid|11205|Teach Ornate Mithril Breastplate|36|0|0|0|
|3381|OLD A Meeting with the Master|12510|Teleport to Azshara Tower|5|25|0|0|
|3421|Return Trip|12521|Teleport from Azshara Tower|6|25|25|0|
|3503|Meeting with the Master|12510|Teleport to Azshara Tower|5|25|0|0|
|3567|To the Top|12242|Twin Colossals Teleport|6|25|25|0|
|3639|Show Your Work|20221|Goblin Engineering|36|0|0|0|
|3641|Show Your Work|20220|Gnomish Engineering|36|0|0|0|
|3643|Show Your Work|20220|Gnomish Engineering|36|0|0|0|
|4490|OLD Summon Felsteed|5785|Teach Summon Felsteed|36|0|0|0|
|5042|Agamaggan\'s Strength|16612|Agamaggan\'s Strength|6|25|0|0|
|5043|Agamaggan\'s Agility|17013|Agamaggan\'s Agility|6|25|0|0|
|5044|Wisdom of Agamaggan|7764|Wisdom of Agamaggan|6|25|0|0|
|5045|Rising Spirit|10767|Rising Spirit|6|25|0|0|
|5046|Razorhide|16610|Razorhide|6|25|25|0|
|5141|Dragonscale Leatherworking|10657|Dragonscale Leatherworking|36|0|0|0|
|5143|Tribal Leatherworking|10661|Tribal Leatherworking|36|0|0|0|
|5144|Elemental Leatherworking|10659|Elemental Leatherworking|36|0|0|0|
|5145|Dragonscale Leatherworking|10657|Dragonscale Leatherworking|36|0|0|0|
|5146|Elemental Leatherworking|10659|Elemental Leatherworking|36|0|0|0|
|5148|Tribal Leatherworking|10661|Tribal Leatherworking|36|0|0|0|
|5217|Return to Chillwind Camp|10937|Power Word: Fortitude|6|21|0|0|
|5220|Return to Chillwind Camp|10937|Power Word: Fortitude|6|21|0|0|
|5223|Return to Chillwind Camp|10937|Power Word: Fortitude|6|21|0|0|
|5226|Return to Chillwind Camp|10938|Power Word: Fortitude|6|21|0|0|
|5230|Return to the Bulwark|23947|Power Word: Fortitude|6|25|0|0|
|5232|Return to the Bulwark|23947|Power Word: Fortitude|6|25|0|0|
|5234|Return to the Bulwark|23947|Power Word: Fortitude|6|25|0|0|
|5236|Return to the Bulwark|23948|Power Word: Fortitude|6|25|0|0|
|6001|Body and Heart|19179|Bear Form|36|0|0|0|
|6002|Body and Heart|19179|Bear Form|36|0|0|0|
|6032|Sacred Cloth|19437|Mooncloth Boots|36|0|0|0|
|6081|Training the Beast|5300|Beast Training|36|0|0|0|
|6082|Taming the Beast|1579|Tame Beast|36|0|0|0|
|6085|Taming the Beast|1579|Tame Beast|36|0|0|0|
|6086|Training the Beast|5300|Beast Training|36|0|0|0|
|6088|Taming the Beast|1579|Tame Beast|36|0|0|0|
|6089|Training the Beast|5300|Beast Training|36|0|0|0|
|6102|Taming the Beast|1579|Tame Beast|36|0|0|0|
|6103|Training the Beast|5300|Beast Training|36|0|0|0|
|6125|Power over Poison|8947|Cure Poison|36|0|0|0|
|6130|Power over Poison|8947|Cure Poison|36|0|0|0|
|6607|Nat Pagle, Angler Extreme|18249|Artisan Fishing|36|0|0|0|
|6610|Clamlette Surprise|18261|Artisan Cook|36|0|0|0|
|6622|Triage|10847|Artisan First Aid|36|0|0|0|
|6624|Triage|10847|Artisan First Aid|36|0|0|0|
|6741|More Booty!|21163|Polished Armor|6|25|0|0|
|6781|More Armor Scraps|21163|Polished Armor|6|25|0|0|
|7223|Armor Scraps|21163|Polished Armor|6|25|0|0|
|7224|Enemy Booty|21163|Polished Armor|6|25|0|0|
|7463|Arcane Refreshment|10143|Conjure Water|36|25|0|0|
|7493|The Journey Has Just Begun|19213|Pattern: Onyxia Scale Cloak|36|25|0|0|
|7497|The Journey Has Just Begun|19213|Pattern: Onyxia Scale Cloak|36|25|0|0|
|7583|Suppression|20700|Ritual of Doom|36|0|0|0|
|7603|Kroshius\' Infernal Core|1413|Inferno|36|0|0|0|
|7631|Dreadsteed of Xoroth|23160|Teach Summon Dreadsteed|36|0|0|0|
|7647|Judgment and Redemption|23215|Summon Charger|36|0|0|0|
|7946|Spawn of Jubjub|23853|Jubling Cooldown|77|25|0|0|
|7961|Waskily Wabbits!|1579|Tame Beast|36|0|0|0|
|8250|Magecraft|12510|Teleport to Azshara Tower|5|25|0|0|
|8257|Blood of Morphaz|9884|Mark of the Wild|6|21|21|21|
|8313|Sharing the Knowledge|24802|Smoked Desert Dumplings|36|0|0|0|
|8336|A Fistful of Slivers|24829|Fortitude of the Sin\'dorei|6|21|21|0|
|8344|Windows to the Source|7763|Teach Summon Imp|36|0|0|0|
|8798|A Yeti of Your Own|26012|Tranquil Mechanical Yeti|36|0|0|0|
|9065|The \"Chow\" Quest (123)aa|3246|Chicken Other|6|25|0|0|
|9324|Stealing Orgrimmar\'s Flame|46709|Has Completed all Torch Quests|77|25|0|0|
|9325|Stealing Thunder Bluff\'s Flame|46709|Has Completed all Torch Quests|77|25|0|0|
|9326|Stealing the Undercity\'s Flame|46709|Has Completed all Torch Quests|77|25|0|0|
|9330|Stealing Stormwind\'s Flame|46709|Has Completed all Torch Quests|77|25|0|0|
|9331|Stealing Ironforge\'s Flame|46709|Has Completed all Torch Quests|77|25|0|0|
|9332|Stealing Darnassus\'s Flame|46709|Has Completed all Torch Quests|77|25|0|0|
|9364|Fragmented Magic|28285|Polymorph: Pig|36|0|0|0|
|9451|Call of Earth|8073|Stoneskin Totem|36|0|0|0|
|9485|Taming the Beast|1579|Tame Beast|36|0|0|0|
|9509|Call of Water|5396|Healing Stream Totem|36|0|0|0|
|9554|Call of Air|8385|Swift Wind|6|25|25|0|
|9555|Call of Fire|2075|Searing Totem|36|0|0|0|
|9582|Strength of One|8121|Path of Defense|36|0|0|0|
|9593|Taming the Beast|1579|Tame Beast|36|0|0|0|
|9600|Redemption|7329|Redemption|36|0|0|0|
|9619|The Rune of Summoning|11520|Teach Summon Voidwalker|36|0|0|0|
|9673|Beast Training|5300|Beast Training|36|0|0|0|
|9675|Beast Training|5300|Beast Training|36|0|0|0|
|9685|Redeeming the Dead|7329|Redemption|36|0|0|0|
|9691|Return to Silvermoon|5503|Sense Undead|36|0|0|0|
|9712|OLD The Thalassian Warhorse|34768|Summon Warhorse|36|0|0|0|
|9737|True Masters of the Light|34766|Summon Charger|36|0|0|0|
|10021|Restoring the Light|43090|Force Cast Blessed Vial Cleanup DND|140|25|0|0|
|10124|Forward Base: Reaver\'s Fall|35998|Set Rails Flag|16|25|0|0|
|10350|Behomat|8121|Path of Defense|36|0|0|0|
|10449|Apothecary Zelana|35998|Set Rails Flag|16|25|0|0|
|10483|Ill Omens|35998|Set Rails Flag|16|25|0|0|
|10831|Becoming a Mooncloth Tailor|26799|Mooncloth Tailoring|36|0|0|0|
|10832|Becoming a Spellfire Tailor|26796|Spellfire Tailoring|36|0|0|0|
|10833|Becoming a Shadoweave Tailor|26800|Shadoweave Tailoring|36|0|0|0|
|10897|Master of Potions|28676|Potion Master|36|0|0|0|
|10899|Master of Transmutation|28674|Transmutation Master|36|0|0|0|
|10901|The Cudgel of Kar\'desh|39145|The Mark of Vashj|3|25|0|0|
|10902|Master of Elixirs|28678|Elixir Master|36|0|0|0|
|11001|Vanquish the Raven God|40123|Swift Flight Form|36|0|0|0|
|11409|Now This is Ram Racing... Almost.|44358|Dismount Ram - Quest|140|25|0|0|
|11318|Now This is Ram Racing... Almost.|44358|Dismount Ram - Quest|140|25|0|0|
|11123|Inspecting the Ruins|42169|Reflective Dust|61|0|21|0|
|11124|Inspecting the Ruins|42169|Reflective Dust|61|0|21|0|
|11010|Bombing Run|40198|Bombing Run: On Quest Complete|140|25|0|0|
|11023|Bomb Them Again!|40198|Bombing Run: On Quest Complete|140|25|0|0|
|11061|A Father\'s Duty|41109|Periodic - Summon Torkus Jr.|6|25|0|0|
|11102|Bombing Run|40198|Bombing Run: On Quest Complete|140|25|0|0|
|11122|There and Back Again|44358|Dismount Ram - Quest|140|25|0|0|
|11293|Bark for the Barleybrews!|44358|Dismount Ram - Quest|140|25|0|0|
|11294|Bark for the Thunderbrews!|44358|Dismount Ram - Quest|140|25|0|0|
|11407|Bark for Drohn\'s Distillery!|44358|Dismount Ram - Quest|140|25|0|0|
|11408|Bark for T\'chali\'s Voodoo Brewery!|44358|Dismount Ram - Quest|140|25|0|0|
|11412|There and Back Again|44358|Dismount Ram - Quest|140|25|0|0|
|11513|Intercepting the Mana Cells|44934|Sunwell Portal Quests Flag|16|25|0|0|
|11514|Maintaining the Sunwell Portal|44934|Sunwell Portal Quests Flag|16|25|0|0|
|11691|Summon Ahune|45926|Ahune - Summoning Rhyme Aura|6|25|0|0|
|11933|Stealing the Exodar\'s Flame|46709|Has Completed all Torch Quests|77|25|0|0|
|11935|Stealing Silvermoon\'s Flame|46709|Has Completed all Torch Quests|77|25|0|0|
|11964|Incense for the Summer Scorchlings|47107|Give Summer Scorchling Incense|140|25|0|0|
|11966|Incense for the Festival Scorchlings|47107|Give Summer Scorchling Incense|140|25|0|0|

Manually testing a subset of the above quests led me to believe that the Effect type 6 (`SPELL_EFFECT_APPLY_AURA`) spells need to actually be cast by the player, not the NPC.

Changing the above mentioned function to
```patch
@@ -13212,9 +13212,7 @@ void Player::RewardQuest(Quest const* pQuest, uint32 reward, Object* questGiver,
                 for (uint8 i = 0; i < MAX_EFFECT_INDEX; ++i)
                 {
                     if (spellProto->Effect[i] == SPELL_EFFECT_LEARN_SPELL ||
-                            spellProto->Effect[i] == SPELL_EFFECT_CREATE_ITEM ||
-                            spellProto->EffectImplicitTargetA[i] == TARGET_UNIT ||
-                            spellProto->EffectImplicitTargetA[i] == TARGET_UNIT_FRIEND)
+                        spellProto->Effect[i] == SPELL_EFFECT_CREATE_ITEM)
                     {
                         caster = (Unit*)questGiver;
                         break;
```
makes the quests here and in #1512 work properly. However, its a little weird that the http://www.wowhead.com/spell=5320/echeyakees-grace buff is not actually shown as a buff, only indication of the working aura is the green *+2 spirit* in the character sheet. (I was not able to immediately verify that's legit "blizzlike".)
Also I manually tested some of the `SPELL_EFFECT_LEARN_SPELL` quests, which also work as expected.

**Does anyone know of a known good test case that would proof my fix incomplete?**

**Comment by MrMarvin** [comment]
> Does anyone know of a known good test case that would proof my fix incomplete?

I found that


| entry | Title | Id | SpellName | Effect1 | EffectImplicitTargetA1|
|-- | -- | -- | -- | -- | --|
|755 | Rites of the Earthmother | 1126 | Mark of the Wild | 6 | 21|

Does not cast Mark of the Wild correctly on the player. However 

| entry | Title | Id | SpellName | Effect1 | EffectImplicitTargetA1|
|-- | -- | -- | -- | -- | --|
|5236 | Return to the Bulwark | 23948 | Power Word: Fortitude | 6 | 25|

works just well. So its not as simple as deciding if its a player skill (as given by `SpellFamilyName <> 0`) or not.

Definitely needs some more investigation.

**Comment by MrMarvin** [comment]
> Does anyone know of a known good test case that would proof my fix incomplete?

A little more research:

|Quest reward spell | Cast Player -> Player (patch from [above](https://github.com/cmangos/issues/issues/1150#issuecomment-472541089))  |Cast NPC -> Player (current code base) |
|---|---|---|
| qID: 755 (Rites of the Earthmother), sID: 1126 (Mark of the Wild)| ✅ Animation and effect on player  | ❌ Nothing happens|
| qID: 5236 (Return to the Bulwark), sID: 23948 (Power Word: Fortitude, not the Players spell, its a longer buff duration version)|✅, Animation and effect on player. Odd, but works. | ✅ Works, NPC animation, effect on Player (as in [here](https://youtu.be/jKPDoC8EraY?list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n&t=1459)| 
|qID: 8336 (A Fistful of Slivers), sID: 24829 (Fortitude of the Sin'dorei)|✅|❌ Nothing happens|
|qID: 881 (Echeyakee), sID: 5320 (Echeyakee's Grace)| ✅ Works as [expected](https://www.youtube.com/watch?v=OAA86_GuQ7E&feature=youtu.be&t=2h1m56s) )|❌ Nothing happens|
|qID: 873 (Isha Awak), sID: 5325 (Strength of Isha Awak)|✅|❌ Nothing happens|
|qID: 889 (Spirit of the Wind, Mangletooth blood shard repeatable), sID: 16618 (Spirit of the Wind)|✅ Works|❌ casts on NPC|
|qID: 9554 (Call of Air), sID: 8385 (Swift Wind)|✅, same as ->, due to having the `SPELL_EFFECT_CREATE_ITEM` effect |✅|
|qID: 3421 (Return Trip), sID: 12521 (Teleport from Azshara Tower)|✅ Works|❌ NPC does animation, no effect|
|qID: 10901 (The Cudgel of Kar'desh), sID: 39145 (The Mark of Vashj)|❓Player animation, not sure ...|❓ NPC animation, not sure what should have happened on Player|
|qID: 2601 (The Basilisk's Bite), sID: 10690 (Infallible Mind)|✅, same as ->, due to having the `SPELL_EFFECT_CREATE_ITEM` effect|✅, Animation and effect on Player (expected?)|
|qID: 10897 (Master of Potions), sID: 28676 (Potion Master)|✅, same as ->, due to having the `SPELL_EFFECT_LEARN_SPELL` effect|✅|

**Comment by BenDol** [comment]
.go creature Sergra Darkthron
.quest add 889
.quest complete 889

**Comment by killerwife** [comment]
Soon will push fix, but one thing to note for the future. The spell has an attribute which makes it not show up clientside nonetheless.
