### ISSUE TITLE
[WotLK] Server Crash on Startup with AHBot Enabled

### ISSUE THREAD

**Issue by dscime** [cmangos/issues#1151]
**Current behavior**: 

Starting mangosd with the command below (adjusted as necessary for build/run paths):

/home/wrath/wotlk-mangos/run/bin/mangosd -c /home/wrath/wotlk-mangos/run/etc/mangosd.conf -a /home/wrath/wotlk-mangos/run/etc/ahbot.conf

Server will crash with message below:

"Sorting and cleaning items for AHBot seller...
terminate called after throwing an instance of 'std::domain_error'
  what():  Unrecognized item prototype class
Aborted (core dumped)"

Commenting out or removing '-a' option for AuctionHouseBot will allow the server to initialize.

**Expected behavior**: 

Server initializes with AHBot functionality.

**Steps to reproduce**:

1. Build clean Ubuntu server
1. Build clean WotLK server
2. Load clean databases
3. Copy AHBot.conf file to run path
4. Set AuctionHouseBot.Seller.Enabled = 1 in AHBot.conf
5. Set AuctionHouseBot.Buyer.Enabled = 1 in AHBot.conf
6. Run command /home/wrath/wotlk-mangos/run/bin/mangosd -c /home/wrath/wotlk-mangos/run/etc/mangosd.conf -a /home/wrath/wotlk-mangos/run/etc/ahbot.conf

**Client version**: 
World of Warcraft Client Patch 3.3.5a

**Commit hash**: 
[Mangos-WotLK Commit: 68ba55c051527f809e0a96b678e933d1421f14ec](https://github.com/cmangos/mangos-wotlk/commit/68ba55c051527f809e0a96b678e933d1421f14ec)

**Database version**: 
[WotLK-DB Commit: e84a899745f3cdf49235d8bdef108988c575f482](https://github.com/cmangos/wotlk-db/commit/e84a899745f3cdf49235d8bdef108988c575f482)

**Operating system**: 
Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-47-generic x84_64)

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Rog360** [comment]
Also happening on Windows 7 32bit... :(

**Comment by dscime** [comment]
I can add that this behavior is not seen in Classic Mangos.  I have two Mangos servers running independently and the AuctionHouseBot functions perfectly in Classic.
