### ISSUE TITLE
[TBC][WOTLK] Druid Talent "Brambles" Not Modifying Thorns

### ISSUE THREAD

**Issue by mangostaters** [cmangos/issues#1152]
**Current behavior**: 3 points in Brambles in Balance Tree not increasing level 2 thorns (current level) by 75%; damage remains at 6

**Expected behavior**: Damage is increased by 75%; current 6 would be 10.5

**Steps to reproduce**:

1. Make drood
2. Level sufficiently for Brambles to be level 3
3. See results when enemies hit you

**Client version**: 3.3.5a

**Commit hash**: 

**Database version**: DB listed as "UDB_0.12.2_mangos_11792_SD2_2279.sql" in folder

**Operating system**: Win 10 64x

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
Seems to be working fine now.

**Comment by berserkingyadis** [comment]
Ive tested this just now on tbc core and it seems to be working.

Tested with Thorns (Level 2) which does 6 base damage and with full skilled Brambles talent damage in tooltio goes up to 10-11. Damage to mobs also is 10-11.

@AnonXS 

tbc core commit: 4a04c15feeb570b44dae9789ebd21abadbdfd1f5

**Comment by al3xc1985** [comment]
@killerwife works perfect..can be closed
