### ISSUE TITLE
[WOTLK] Tame Beast (Quest Item)

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#1154]
**Current behavior**: 
After you tame a pet, that pet goes back to his first point and do nothing. He doesn't respond to any commands. Also, you cannot dismiss the pet, until you log off!
**Expected behavior**: 
The pet should be usable like all other pets, also you should dismiss it at your will!
**Steps to reproduce**:

1.  draenei hunter
2. reach level 10
3. start the tame beast quest line

**Client version**: 
Wotlk 3.3.5
**Commit hash**: 

**Database version**: 
UDB 408
**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Phatcat** [comment]
Taken care of in; https://github.com/cmangos/mangos-wotlk/commit/8a2f4b6e92d3667aecc2734e88360720290264ca
