### ISSUE TITLE
[WOTLK] Tamed Pet

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#1155]
**Current behavior**: 
After you complete the quest and get the tame beast spell, the tamed pet doesn't have the abbilities on the bar, you need to dismiss and call back so the abilities to appear on the bar!
In the Log, it shows you that the pet learn the abilities, but they don't appear on his bar!
**Expected behavior**: 
After you tame it, he shows up with abilities on the bar!
**Steps to reproduce**:

1. Draenei hunter
2. Complete the tame beast quest line
3. Tame a nightsaber

**Client version**: 
Wotlk 3.3.5a
**Commit hash**: 

**Database version**: 
UDB 408
**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Lillecarl** [comment]
@cyberium Did your newly merged pet PR affect this?

**Comment by cyberium** [comment]
should be fixed yes
