### ISSUE TITLE
Summon creature bug

### ISSUE THREAD

**Issue by Ve1vet** [cmangos/issues#1156]
**Current behavior**: 
Zul'Aman boss Janalai encounter. Summon(spell 42493) creaure 23598(Dragonhawk) from eggs. Creature can't get in combat because it can't have threatlist.
ERROR:Creature entry 23598 call SetInCombatWithZone but creature cannot have threat list.
So creature don't attack at all because can't get in combat.

**Comment by Phatcat** [comment]
Should be taken care of in https://github.com/cmangos/mangos-tbc/commit/6ed3c7b61c8bc9a654156c2108c4c7b826027b16
