### ISSUE TITLE
[WOTLK] Shadow Vault's Neutral Taxi Node Works Only for Horde

### ISSUE THREAD

**Issue by Darth-Postal** [cmangos/issues#1157]
Well this is a weird one... Basically, even if you learn every other flight node in Northrend, Shadow Vault's Flight Master [Morlia Doomwing](http://www.wowhead.com/npc=30314) knows no flight paths if you are Alliance. Works perfectly fine for Horde.

Shadow Vault is connected only to Neutral nodes ([Source](http://wow.gamepedia.com/Shadow_Vault#Travel_connections)) and Ebon Blade is Neutral faction, so Flight Master should work exactly the same for both factions.

To verify that it's not a DB issue, I spawned a copy of perfectly working Dalaran Flight Master right next to Morlia. He immediately refused to service Alliance too.

![wowscrnshot_111916_161941](https://cloud.githubusercontent.com/assets/19946716/20456173/f1586a06-ae77-11e6-8533-b337a0e606aa.jpg)
![wowscrnshot_111916_161945](https://cloud.githubusercontent.com/assets/19946716/20456175/fb5d70b4-ae77-11e6-9fda-fcd7a59f4628.jpg)

Then I did the reverse thing and put Morlia next to Dalaran guy. She worked fine there. So I believe there is nothing wrong with her DB-wise.

![wowscrnshot_111916_163458](https://cloud.githubusercontent.com/assets/19946716/20456179/246f3992-ae78-11e6-8fa5-90ad1f54a461.jpg)

**Current behavior**: 
Shadow Vault Flight Master doesn't know any paths for Alliance.

**Expected behavior**: 
Flight Master should know this [list of paths](http://wow.gamepedia.com/Shadow_Vault#Travel_connections) for both factions.

**Steps to reproduce**:
1. Go to Shadow Vault as Alliance player, who learned at least one Flight Node from [this list](http://wow.gamepedia.com/Shadow_Vault#Travel_connections)
2. Talk to [Morlia Doomwing](http://www.wowhead.com/npc=30314)

**Client version**: 
3.3.5a

**Commit hash**: 
https://github.com/cmangos/mangos-wotlk/commit/832f9793f1acfc4d4d5c87a5763da64f8518e302

**Database version**: 
Wotlk-DB r602

**Operating system**: 
Win7 x64

**Comment by xfurry** [comment]
Might be a phasing aura issue (which is still a DB issue).
Will have a look soon.
