### ISSUE TITLE
[WOTLK] Missing Spell 54191 "Lifeblood Siphon"

### ISSUE THREAD

**Issue by Darth-Postal** [cmangos/issues#1158]
[Spell s54191 "Lifeblood Siphon"](http://www.wowhead.com/spell=54191/lifeblood-siphon) is cast by [item i40397 "Lifeblood Gem"](http://www.wowhead.com/item=40397/lifeblood-gem) for [quest q12805 "Salvaging Life's Strength"](http://www.wowhead.com/quest=12805/salvaging-lifes-strength). It seems to be missing from Core.

Video of the quest [here](https://www.youtube.com/watch?v=FKDISSCb2p4).

**Comment by killerwife** [comment]
Spell seems to exist just fine. Closing
