### ISSUE TITLE
[TBC] Quests/BUG: Test Flight: The Zephyrium Capacitorium

### ISSUE THREAD

**Issue by cooler-SAI** [cmangos/issues#1161]
**Current behavior**: 
Quest doesn't work. Nothing happens
**Expected behavior**: 
http://www.wowhead.com/quest=10557/test-flight-the-zephyrium-capacitorium
**Steps to reproduce**:

1. Quest can't be completed

**Client version**: 
2.4.3
**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/cb94341110e2bfa47c34960c1439028307eee661
**Database version**: 
Last TBCDB
**Operating system**: 
Win 7 x32

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Fix coming in next few months, got a full DBscript when I get to that commit from TBC-DB.
