### ISSUE TITLE
[TBC] Quest - What Came First, the Drake or the Egg?

### ISSUE THREAD

**Issue by cooler-SAI** [cmangos/issues#1162]
**Current behavior**: 
Quest doesn't work. Nothing happens
**Expected behavior**: 
http://www.wowhead.com/quest=10609/what-came-first-the-drake-or-the-egg
**Steps to reproduce**:

1. Quest can't be completed

**Client version**: 
2.4.3
**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/cb94341110e2bfa47c34960c1439028307eee661
**Database version**: 
Last TBCDB
**Operating system**: 
Win 7 x32

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Needs DB patch, will get to it in coming months when I get to exporting that commit.

**Comment by berserkingyadis** [comment]
Was this commit exported?
