### ISSUE TITLE
[TBC] Quest - Gauging the Resonant Frequency

### ISSUE THREAD

**Issue by cooler-SAI** [cmangos/issues#1163]
**Current behavior**: 
Quest doesn't work. Nothing happens
**Expected behavior**: 
http://www.wowhead.com/quest=10594/gauging-the-resonant-frequency
**Steps to reproduce**:

1. Quest can't be completed

**Client version**: 
2.4.3
**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/cb94341110e2bfa47c34960c1439028307eee661
**Database version**: 
Last TBCDB
**Operating system**: 
Win 7 x32

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Needs core patch and DB export, will get to it maybe in the coming months.

**Comment by xfurry** [comment]
> Needs core patch

Please be more specific. What core patch is required?

**Comment by killerwife** [comment]
@xfurry Creature has spell party aura, for which owner needs to be set correctly. We do not support setting owner on SUMMON WILD, meaning it has to be explicitly set in this case. Then there is the issue of IsHostileTo being bugged in the case of owner being set (we do some really stupid stuff there that breaks on multiple occasions, namely this and chess event) where mobs owner is hostile, but object is friendly to all (faction 35). Also requires custom Aura counting (we usually count stacks, here we need to count applications, unsupported by public atm). That pretty much sums it up.

**Comment by AnonXS** [comment]
@killerwife

**Comment by killerwife** [comment]
Should work as intended now.
