### ISSUE TITLE
[TBC] Quest - Picking Up Some Power Converters - Quest Doesn't Work

### ISSUE THREAD

**Issue by cooler-SAI** [cmangos/issues#1164]
**Current behavior**: 
Quest doesn't work. Nothing happens
**Expected behavior**: 
http://www.wowhead.com/quest=10584/picking-up-some-power-converters
**Steps to reproduce**:

1. Quest can't be completed

**Client version**: 
2.4.3
**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/cb94341110e2bfa47c34960c1439028307eee661
**Database version**: 
Last TBCDB
**Operating system**: 
Win 7 x32

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Qingle** [comment]
So the item doesn't work, or there are no cores?

**Comment by cooler-SAI** [comment]
Item work not correctly, They aggro player then and I can't complete quest. you can go and test it

**Comment by Lillecarl** [comment]
Probably related to the spell not working properly?

**Comment by berserkingyadis** [comment]
Ok ive tested this and this is what I have observed.

Recording of testing: https://gfycat.com/glitteringpertinentfruitbat

What works:
- You get "Protovoltaic Magneto Collector" from q giver
- Clicking on the Power Converter (aim is off somehow, takes a bit to target with mouse)spawns the Electromental.
- Using the item "Protovoltaic Magneto Collector" on the mob encases them in the blue bubble (Electromental -> Encased Electromental) .
- Killing the Electromental does not yield quest completion, you have to encase it.
- Killing encased Electromental yields quest completion.

What doesnt work:
- Electromentals are moving and auto attacking, they should only be casting a lightning bolt like spell.
- Power Converter is hard to click.
- Power Converter seems to be re-usable.


Didnt find a video from retail back in the day yet. Here is a one that seems to be newer: https://www.youtube.com/watch?v=c9709tHOTu4
