### ISSUE TITLE
vmapsextractor binary naming isn't consistent across platforms

### ISSUE THREAD

**Issue by Lillecarl** [cmangos/issues#1165]
On mangos-tbc the naming of the binary for vmapsextractor is inconsistent, which make the default ExtractResources.sh fail, on Mac it's installed as "vmap_extractor" but on windows it seems to be vmapExtractor.

**Comment by Razfury** [comment]
This was solved in https://github.com/cmangos/mangos-classic/commit/badeb0025a33cc201f7408379ec9d9ae82fac83a

should be closed!

**Comment by Muehe** [comment]
I am pretty sure this isn't fixed in the [TBC](https://github.com/cmangos/mangos-tbc/blob/master/contrib/extractor_scripts/ExtractResources.sh#L166) and [WotLK](https://github.com/cmangos/mangos-wotlk/blob/master/contrib/extractor_scripts/ExtractResources.sh#L166) repos yet.

**Comment by cyberium** [comment]
i will port the fix :) Thanks all of you
