### ISSUE TITLE
Character database structure mismatch with core.

### ISSUE THREAD

**Issue by Lillecarl** [cmangos/issues#1167]
**Current behavior**: 
mangos>Monthly quests reset for all characters.
SQL: UPDATE saved_variables SET NextMonthlyQuestResetTime = '1480568400'
SQL ERROR: Unknown column 'NextMonthlyQuestResetTime' in 'field list'

**Expected behavior**: 
Not this error

**Steps to reproduce**:
Steps I did:
Downloaded world db from GitHub release
imported world db.
imported chardb
imported realmdb

**Client version**: 
2.4.3
**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/cb94341110e2bfa47c34960c1439028307eee661
**Database version**: 
https://github.com/cmangos/tbc-db/commit/cb30c4e087b942e4c18f0570987cdee2d8f06a3d
**Operating system**: 
Mac osx

https://github.com/cmangos/mangos-tbc/search?utf8=✓&q=NextMonthlyQuestResetTime

This NextMonthlyQuestResetTime isn't showing up anywhere in characters.sql.

**Comment by Lillecarl** [comment]
Seems like porting gone wrong, or someone missed updating characters.sql to match with updates properly.

**Comment by Warlockbugs** [comment]
Tagging @Killerwife

**Comment by Ve1vet** [comment]
@Lillecarl just apply couple sql udates. Thats it. This always was normal things.

**Comment by cyberium** [comment]
Right i didnt thought about adding a full characters.sql and a realmd.sql.
The purpose of that sql is to get fastly a ready to go DB so i think i should add it.

**Comment by Lillecarl** [comment]
You all are missing the point that CMaNGOS doesn't/shouldn't even start if the version mismatches, and it didn't when i just imported characters.sql.

**Comment by cyberium** [comment]
You right it characters.sql in repos should be updated. I mixed DB stuff and CORE stuff.

**Comment by Saben65** [comment]
https://github.com/cmangos/mangos-tbc/commit/9e02f873833ade01a9e3fcbcc8c77699b8ffa7f6#diff-8e6465725e74907650d865a69a472ca2

It was an update.

**Comment by killerwife** [comment]
Meh, @Warlockbugs was right to tag me, I added a separate file but didnt edit main schema, because I forgot to make it foolproof. Somewhere in the updates for character db is an alter table for saved variables. Will sort it out this evening.

**Comment by Lillecarl** [comment]
Thanks @killerwife :)

**Comment by killerwife** [comment]
@Lillecarl fixed in https://git.io/v1J8D
