### ISSUE TITLE
[Classic] - Server Crash On Startup - Undefined Symbol

### ISSUE THREAD

**Issue by dscime** [cmangos/issues#1170]
**Current behavior**: 

Server crashes on startup with error below:

mangos>/home/mangos/classic-mangos/run/bin/mangosd: symbol lookup error: /usr/local/lib/libmangosscript.so: undefined symbol: _ZN8Creature17CanInitiateAttackEv

**Expected behavior**: 

Expect server to properly initialize and run.

**Steps to reproduce**:

1. Build clean Ubuntu Server
2. Build clean Classic Mangos server
3. Populate databases
4. Attempt to start server with command /home/mangos/classic-mangos/run/bin/mangosd -c /home/mangos/classic-mangos/run/etc/mangosd.conf -a /home/mangos/classic-mangos/run/etc/ahbot.conf

**Client version**: 
World of Warcraft Client Patch 1.12

**Commit hash**: 
[Commit hash 9fb6d59:](https://github.com/cmangos/mangos-classic/commit/9fb6d59548617af6944b6f58240fa74eb8588ae7)

**Database version**: 
[Database version 5df7f7c:](https://github.com/classicdb/database/commit/5df7f7c28debfc8b5660e796505ef36c16b4a0bc)

**Operating system**: 
Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-47-generic x86_64)

[Server.log attached](https://gist.github.com/dscime/6d0de869c2ec3662df1516b9f2417ebf)

**Comment by cyberium** [comment]
You have to rebuild mangoscript (SD2)

**Comment by dscime** [comment]
Issue persisted after a make clean && make -j4

Issue was caused by libmangosscript.so in /usr/local/lib

After removing this file, the server started successfully.

**Comment by cyberium** [comment]
you need that file or no bosses and special event will work.

**Comment by dscime** [comment]
There is a copy of ibmangosscript.so located in /home/mangos/classic-mangos/run/lib/

I believe the old file located in /usr/local/lib was from an old build.  The original issue was improperly reported as affecting a clean install.  That one is a little egg on my face.

**Comment by cyberium** [comment]
It always worth, now you'll never be caught at that stuff ;)
