### ISSUE TITLE
Thrall Gossip

### ISSUE THREAD

**Issue by robinsch** [cmangos/issues#1171]
**Current behavior**: 
Thrall is missing it's gossip text.

```sql
DELETE FROM `npc_gossip` WHERE `npc_guid` = 4770;
INSERT INTO `npc_gossip` (`npc_guid`, `textid`) VALUES (4770, 4477);
```

![](https://i.gyazo.com/3c86ee194d2d8f4d8fad091319b38d74.png)

**Comment by cyberium** [comment]
DB issue, @cala , @Grz3s, @killerwife
