### ISSUE TITLE
[CLASSIC/TBC/WOTLK] Charge in Some Places Where There's a Cave Beneath Can Cause Character to Fall Under Textures

### ISSUE THREAD

**Issue by ryancheung** [cmangos/issues#1172]
**Current behavior**: 
Some of the path points generated with `.mmap path` go to the underground if there's a cave underground.
**Expected behavior**: 
Some of the path points generated with `.mmap path` should go to the ground, not some position in the cave beneath it.
**Steps to reproduce**:

1. Create a warrior character
2. .go xyz 2988.1645 -2745.4511 123.5873
3. Target Cannibal Ghoul(Entry 8530)
4. Cast Charge to it.
5. You'll charge to the underground and fall.

**Client version**: 
1.12.1
**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/d3cabb899a5f2e535f7f504f37cc191e2da7f088
**Database version**: 

**Operating system**: 
macOS 10.12

**`mmap path` Screenshot**
![image](https://cloud.githubusercontent.com/assets/240899/20700518/b1c0209a-b648-11e6-9333-b6834ff7c2dc.png)

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cyberium** [comment]
One thing you can do is to test that PR ang give us some feedback -> https://github.com/cmangos/mangos-classic/pull/215

**Comment by ryancheung** [comment]
@cyberium OK, I already tested the PR. It solved the problem as @mityada said. But still, not this one.

**Comment by ryancheung** [comment]
The PR solved the problem encountered in the cave, but this case is above the cave.

**Comment by cyberium** [comment]
ok if you tested cmangos/mangos-classic#215 and it seem to work for you why did you not yet tested what is suggested https://github.com/cmangos/mangos-classic/pull/215#issuecomment-263087820 and give us some feedback?

**Comment by Phatcat** [comment]
I can't reproduce falling through the map in this specific area, I can however completely ignore obstacles (perhaps not all but a good chunk of them) in this area with my charge, charging through trees... Tested on classic.

**Comment by jimmybrancaccio** [comment]
Please correct me if I am wrong, but this one is not 100% resolved yet?

**Comment by ryancheung** [comment]
Just tested in current cmangos-tbc core, it's still have the bug.
![movemapbug](https://user-images.githubusercontent.com/240899/60235162-64eba200-98d9-11e9-8aa5-18a2f7bd6307.png)

**Comment by ryancheung** [comment]
@killerwife Does the map/vmap/mmap format is the same as wow1.12.1? If it is (or kinda similar), maybe the code of mmap generation can be improved with https://github.com/lh-server/core.
LH core's MoveMap works almost blizzlike.

**Comment by evil-at-wow** [comment]
A quick look at the LH core's repository shows their mmap code is at least based on MaNGOS code, so it should be quite similar. I don't know what they do different of course, but it could be interesting to check.

**Comment by AnonXS** [comment]
This topic has to be researched, different extractor settings and "philosophies" have to be counterchecked to achieve an overall better square one for extractor settings.

**Comment by al3xc1985** [comment]
@killerwife this I know that was fixed. And relared problems with charge

**Comment by killerwife** [comment]
Are you sure? This seems like not much was done to fix this. Our pathfinder wasn't changed in the meantime. Only thing we changed is the last point pick.

**Comment by al3xc1985** [comment]
I will recheck in some of this days and come back

**Comment by al3xc1985** [comment]
I rechecked it and worked perfect
@killerwife can be closed
