### ISSUE TITLE
Hunter Pet revive

### ISSUE THREAD

**Issue by Ve1vet** [cmangos/issues#1174]
**Current behavior**: 
Can't ressurect hunter pet if he dissapear.
1. You try to call pet - get error: "Your pet is dead".
2. You can cast Revive pet, but it do nothing.

**Expected behavior**: 
If your pet dies & coprse dissapear:
1. You sould call pet(his corpse spawns), then cast Revive Pet.
2. If you try to revive pet w/o calling him(no corpse spawned), you should get an error, that you don't have pet.

**Steps to reproduce**:
1. Take hunter.
2. Let your pet die.
3. Wait until his corpse dissapear.
4. Call pet(get error)
5. Revive pet, no error, do nothing(sometomes pet spawns & dissapear immediately).

**Client version**: 
2.4.3
**Operating system**: 
Windows 10/Linux OpenSUSE.

**Comment by opnoack** [comment]
I have exactly the same problem at the moment. First my pet dies and then I died. After resurrection I tried to revive my pet but it won't appear. How can I fix this?

**Comment by pnlambert** [comment]
I am seeing this issue with WOTLK.
I have the referenced change from issue 1174 and it doesn't appear to have helped.

**Comment by cyberium** [comment]
ok ill reinvestigate that then.

**Comment by cyberium** [comment]
Should be fixed thanks

**Comment by pnlambert** [comment]
Is there a change? I don't see anything changed since November 30?
