### ISSUE TITLE
[TBC] Quest: Waste Not, Want Not (#10055)

### ISSUE THREAD

**Issue by Argonn** [cmangos/issues#1175]
**Current behavior**: 
When you are on the quest to loot the Salvaged Metal & Salvaged Wood. You can pickup the quest item without the object getting destroyed.

The object will remain on the floor (glittering and all) but you are not able to use the object again, so thats good.

**Expected behavior**: 
When you loot any of the 2 objects, they should disappear for some time.

**Steps to reproduce**:

1.  Give yourself the quest 10055
2.  Teleport to x: -380 Y: 2721 Z:34
3. Use the Salvageable Metal right infront of you.

**Client version**: 

**Commit hash**: 

**Database version**: 

**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Darth-Postal** [comment]
Maybe `.gm on`?

**Comment by Argonn** [comment]
No, GM is(was) off. I tried it again, it seems that the wood is working properly, but the gears are not. The gear pointed out in my first post, is a good example.

**Comment by killerwife** [comment]
Simple fix. Chest does not have correctly set refill flag. The gears are not supposed to be refillable. Fix coming sometime during my next 530 commits that I have pending.

**Comment by Darth-Postal** [comment]
This was fixed in https://github.com/cmangos/tbc-db/commit/bb7215ed0c72af91401575c3fba445eb396adc86
