### ISSUE TITLE
[TBC] Quest - Teleport This! - Issue/Bug

### ISSUE THREAD

**Issue by cooler-SAI** [cmangos/issues#1176]
**Current behavior**: 
Quest doesn't work
**Expected behavior**: 
http://www.wowhead.com/quest=10857/teleport-this
**Steps to reproduce**:

1. Quest can't be completed, When you controlling Demon and He cast spells - nothing happened

**Client version**: 
2.4.3
**Commit hash**: 
https://github.com/cmangos/mangos-tbc/commit/cb94341110e2bfa47c34960c1439028307eee661
**Database version**: 
Last TBCDB
**Operating system**: 
Win 7 x32

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Should be working now.
