### ISSUE TITLE
[CLASSIC] Monsters Do Not Aggro if Another Monster is Attacking You

### ISSUE THREAD

**Issue by mlchai** [cmangos/issues#1180]
**Current behavior**: 
When attacked by a red monster, other red monsters around the area will not attack you unless you aggro them.

**Expected behavior**: 
When attacked by a red monster, other red monsters should attack you if they come into contact with the monster already attacking you.

**Steps to reproduce**:

1. Go to East Vale Logging Camp or Stone Cairne Lake in Elwynn Forest
2. Aggro a red monster (pref caster)
3. Run away from the caster but try to kite it near another red monster without aggroing the monster yourself. The attacking monster should be right next to or very near another red monster.

**Client version**: 
1.12.1

**Commit hash**: 

**Database version**: 

**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
No new complaints on this, closing likely due to being fixed.
