### ISSUE TITLE
[CLASSIC][TBC][WOTLK] gm Command '.learn all_myclass' Includes Wrong Talents and Spells and is Missing Others

### ISSUE THREAD

**Issue by MrMarvin** [cmangos/issues#1183]
**Current behavior**: 
When using the GM command `.learn all_myclass`, some talents and/or spells are not properly learned. Also, some classes learn talents which they should not be able to learn at all, like hunter pet talents.

**Expected behavior**: 
All classes learn exactly the talents and spells for their class.

**Steps to reproduce**:
1. create a horde warrior
2. login
3 `.learn all_myclass`.
4. `.go creature Sorek`.
5. check what Sorek can train you
6. open Spellbook, see that "Thunderstomp" (the hunters spell) is learned under 'General'.

**Client version**: 
1.12
**Commit hash**: 
f6aea67 @ mangos-classic.git
**Database version**: 
c2610f9 @ classic-db.git

**Operating system**: 
Server on linux, client on Win10

What we know so far is that both Warrior and Druids (see #1111) have this issue. I suspect this applies to the other classes as well!
For Warriors (and any other class that gets an Armor type upgrade while leveling) it is an actual problem because they cant wear the, say, Tier1 sets right after `.level 59`.

This also applies to Weapon skills. Some skills, like 'Two handed Axes" are not learned, even when using `.learn all`. Which teaches "Two-Handed Swords" properly, btw.
![not_learning_weapons](https://cloud.githubusercontent.com/assets/100136/20874509/e52ecada-bab2-11e6-80db-97e38a4d9da4.png)

**Comment by Lillecarl** [comment]
Was your expectation that it should teach you all spells and wepskills that you can learn from trainers at maxlevel?

**Comment by Rushor** [comment]
learning all spells including talents will fuckup the class if you try to do classtesting and analyse spelldamage or whatever

**Comment by MrMarvin** [comment]
> Was your expectation that it should teach you all spells and wepskills that you can learn from trainers at maxlevel?

Yes, all spells and passives my class trainer will teach me, without taking into account any chosen talent points.
Not totally sure about weapon skills tho, but yes, I did expected to be able to use two handed axes on my gm created warrior out of the box.

> learning all spells including talents will fuckup the class if you try to do classtesting and analyse spelldamage or whatever

What do you mean @Rushor? The talents currently not learned for druids are for example the passive [Feline Grace](http://www.wowhead.com/spell=20719/feline-grace).

Maybe I wasn't clear in my wording unfortunately. By 'talent' I did not mean anything player chosen like from your talents tree, but in a broader sense skills and passives from your respective class trainers.

**Comment by ulfgebhardt** [comment]
.learn all_myclass includes alot of Spells which do not belong to the player, can be found in the general tab in the spellbook.

**Comment by AnonXS** [comment]
e.g warriors dont learn "offhand spell" by doing ```.learn all_myclass```, which they all should regardless of talents.

**Comment by Baynar** [comment]
Can confirm this, .learn all_myclass or spells will cause you to learn spells that the class should not have (gm spells, creature spells)

This issue was present on OregonCore too, the command should be using Npc Trainer templates to  teach all spells not to guess spells by spell family since spell family's might change and the command will be broken again.

**Comment by Lillecarl** [comment]
My vote would go for removing the command completely, it's not good for anything, and hardcoding spell lists is about as stupid as it gets.

**Comment by jimmybrancaccio** [comment]
@cyberium @killerwife @cala @Warlockbugs Would like to get your guys' input on the above comment from @Lillecarl. Thanks!

**Comment by killerwife** [comment]
In next export, I will export a commit by @MantisLord which solves this.

**Comment by jimmybrancaccio** [comment]
Awesome, thank you @killerwife. Once the export has been done and merged, I will move this into Needs Testing.

**Comment by al3xc1985** [comment]
@killerwife this can be closed

**Comment by killerwife** [comment]
Yes.
