### ISSUE TITLE
ERROR:MMAP:loadMap

### ISSUE THREAD

**Issue by apo126** [cmangos/issues#1191]
Latest mangos-wotlk 13cac8f  reports the below bugs:

ERROR:MMAP:loadMap: 0005134.mmtile was built with generator v4, expected v5
ERROR:MMAP:loadMap: 0013429.mmtile was built with generator v4, expected v5
ERROR:MMAP:loadMap: 5303455.mmtile was built with generator v4, expected v5

Does that mean I need to extract all dbcs, maps, vmaps, mmaps again? Is there any way to only extract the above mentioned maps?

**Comment by Grz3s** [comment]
source:
https://github.com/cmangos/mangos-wotlk/commit/b651490c1397803ceacb8fea1c7ccd96c36ad4c0
```quote
* Correct Nav type for WMO objects (picked from TC, author @zorix)
more info here: TrinityCore/TrinityCore#18364
* Allow to npc and pets jump over small fences
* Change mmap files version to 5
All strongly tested on live servers, works very well
!WARNING: required mmap files reextraction!
```

**Comment by cyberium** [comment]
yes i didnt yet tested it but it require VMAPS/MMAP extraction for sure

**Comment by cala** [comment]
So we can safely close this, I guess.
