### ISSUE TITLE
How to correctly build all extractors?

### ISSUE THREAD

**Issue by apo126** [cmangos/issues#1192]
Please offer some help.

The laterest cmangos requires new mmap, but I did not find any extractors in my "extractor_binary" file after finishing building. It seems that those tools are not included to be built in mangosdVC120.sln.

So how to build those tools? What tools are required if I want to extract dbc, map, vmap, and mmap?

**Comment by Muehe** [comment]
https://github.com/cmangos/mangos-wotlk/commit/9a697d73a4d7398443268c9cd972f6b7009a6777

>  **Remove provided binaries**
>
> There is no reason now to provide them directly has it was.
>
> I will include them in prebuild binaries so you could be assured its
latest versions and virus free.

https://github.com/cmangos/mangos-classic/releases
https://github.com/cmangos/mangos-tbc/releases
https://github.com/cmangos/mangos-wotlk/releases

**Comment by apo126** [comment]
@Muehe Up to now, the latest release does not have extractors. In my opinion, it is better to put those extractors in a separate file. If you need it, you will download it.

**Comment by Muehe** [comment]
Well I'm on Linux, just saw that commit message and thought it to be accurate. Maybe @cyberium can say more?

**Comment by cyberium** [comment]
There is nothing to say here except you have now to compile all extractors yourself or download prebuild one :)

I just pushed the pre build extractor patch so now you can download them https://github.com/cmangos/mangos-wotlk/releases
For those on wotlk look the comments -> https://github.com/cmangos/mangos-wotlk/commit/94e862d4b5e7b39d500505d6ca1029edc679ddb5

(other core will be updated soon)
