### ISSUE TITLE
 Unknown column 'required_z2684_01_mangos_creature_template' in 'db_version'

### ISSUE THREAD

**Issue by flyinskyin2013** [cmangos/issues#1195]
> Trying to retrieve last core update packaged in database ...
grep: updates/*: No such file or directory
  Found last core revision in DB is 2684

> Trying to apply additional core updates from path cmangos/mangos ...
    Appending core update z2685_01_mangos_event_linkedto.sql to database mangos
ERROR 1054 (42S22) at line 1: Unknown column 'required_z2684_01_mangos_creature_template' in 'db_version'
ERROR: cannot apply cmangos/mangos/sql/updates/mangos/z2685_01_mangos_event_linkedto.sql

**Comment by flyinskyin2013** [comment]
shell command.


>./InstallFullDB.sh

**Comment by Lillecarl** [comment]
https://github.com/cmangos/classic-db/releases You can download the complete latest database here! :)

**Comment by flyinskyin2013** [comment]
thxs,
Now,new problem is : 
        In client, I can login in my account,but I can not login in any server in server-lists

**Comment by cala** [comment]
Greetings and welcome. I seems you are experiencing newcommer installation issue. I point you to our forums where these would be better handled: http://cmangos.net/index.php . We reserve our tracker to code issues and bugs. After checking, the DB installs itself correctly, so I'm closing this.

**Comment by flyinskyin2013** [comment]
thxs
