### ISSUE TITLE
ERROR:Pet::InitStatsForLevel

### ISSUE THREAD

**Issue by apo126** [cmangos/issues#1196]
Cmangos wotlk: 604e2ab
World DB: WoTLKDB v1.0 'Echoes of Northrend' for CMaNGOS-WOTLK 12943 with 623 update

In Server.log, there are some errors as follows:

ERROR:Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 3 Guid: 2) (entry: 21135) using ClassLevelStats; not enough data to do it!
ERROR:Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 4 Guid: 3) (entry: 21135) using ClassLevelStats; not enough data to do it!
ERROR:Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 5 Guid: 4) (entry: 21135) using ClassLevelStats; not enough data to do it!
ERROR:Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 6 Guid: 5) (entry: 21135) using ClassLevelStats; not enough data to do it!
ERROR:Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 13 Guid: 9) (entry: 21135) using ClassLevelStats; not enough data to do it!
ERROR:Pet::InitStatsForLevel> Error trying to set stats for creature Pet (Petnumber: 14 Guid: 10) (entry: 21135) using ClassLevelStats; not enough data to do it!

But I only have one pet, and its entry is 3619. Could you please help check how to fix?

**Comment by Grz3s** [comment]
i'll fix it on monday evening ...

**Comment by Grz3s** [comment]
Can be closed.
