### ISSUE TITLE
[WotLK] Some issues with Warlock and Hunter pets

### ISSUE THREAD

**Issue by Darth-Postal** [cmangos/issues#1198]
Noticed some issues with Warlock and Hunter pets:

**1. Pets get reduced max health and mana upon LvL up.**
When your pet levels up, it's max health and mana values get a significant reduce. Can be fixed by mounting/dismounting. This affects both Warlock and Hunter pets.
![lvlup_before](https://cloud.githubusercontent.com/assets/19946716/21457186/dde8dc20-c935-11e6-8163-da71e7867418.png)![lvlup_after](https://cloud.githubusercontent.com/assets/19946716/21457189/e4152c02-c935-11e6-96fd-91924f45f397.png)
Before LvL up....................................................................................After LvL up

**2. Pets loose most mana and some health upon mounting/dismounting.**
When you dismount, your pet has less health and mana then before. Affects both Warlock and Hunter pets.
![mount_before](https://cloud.githubusercontent.com/assets/19946716/21457243/6bca62f2-c936-11e6-910d-ce39a64f1904.png)![mount_after](https://cloud.githubusercontent.com/assets/19946716/21457244/6fe7c37a-c936-11e6-8991-571273e144f3.png)
Before mounting....................................................................................After dismounting

**3. Right-clicking Warlock's pet and selecting "Dismiss" does nothing.**
Works fine in older core from November. So this is new.

**4. Warlock's pet becomes "Unknown" after some time playing.**
![unknown](https://cloud.githubusercontent.com/assets/19946716/21457318/052fe606-c937-11e6-9d7f-06b1e4273632.png)

**5. Dismissed Hunter's pet is still visible on character selection screen and is with you upon login.**
When you dismiss Hunter's pet, you still can see it on character selection screen and the pet is with you upon login.

**6. Hunter's pet looses most of it's health upon login/call.**
If your pet with you upon login (which is always the case because of problem 5, described above), it has very little health. Same thing if you dismiss/call your pet.
![logout_before](https://cloud.githubusercontent.com/assets/19946716/21459154/8e30972c-c944-11e6-9e04-cf06c0786797.png)![logout_after](https://cloud.githubusercontent.com/assets/19946716/21459161/928095ac-c944-11e6-8456-8307277500ed.png)
Before logout/dismiss pet...........................................................................After login/call pet

**Commit hash**: 
https://github.com/cmangos/mangos-wotlk/commit/a7cfe25ad468f676628b9b4aea1bb491b269082b
**Database version**: 
WotLK-DB r644
**Operating system**: 
Win7 x64

**Comment by killerwife** [comment]
I can add one more:
Stats are not being calculated properly. We do not add INT to mana, resulting in lvl 70 IMP having less mana than lvl 70 VOIDWALKER.

**Comment by wowmui** [comment]
Me too. And I can add one more.
Spell Eyes of the Beast(ID 1002) 
When cast this spell,  The enemies will ignore pets and attack hunter. if hunter died in the casting  pet will loss forever or losa his action bar.
And if cancel or finish spell casting , pet will ignore ''stay'' order and follow hunter again. 
warlock pet have casting issues. 
For example: Succubus's Seduction and Imp's Firebolt.
Succubus will cancel Seduction herself ,and Imp will in every gap between the casting moving to target.

**Comment by cyberium** [comment]
Should be fixed thanks.

Please verify.

**Comment by Darth-Postal** [comment]
Just tested the updates. Here are the results:

1. Pets get reduced max health and mana upon LvL up. - **FIXED!** 👍 

2. Pets loose most mana and some health upon mounting/dismounting. - **99% FIXED.** 😄  
There is still a small difference in pet's health mana before and after mounting/dismounting, but it's barely noticeable.
![01before](https://cloud.githubusercontent.com/assets/19946716/21816468/f140a078-d768-11e6-88f0-3b541441b08e.png)![01after](https://cloud.githubusercontent.com/assets/19946716/21816474/f5564118-d768-11e6-968d-b665b7c027b4.png)
Before mounting....................................................................................After dismounting

3. Right-clicking Warlock's pet and selecting "Dismiss" does nothing. - **FIXED!** 👍 

4. Warlock's pet becomes "Unknown" after some time playing. - **NOT FIXED** 👎 
My little buddy Ziltip bacame unknown after just 5 minutes of playing.

5. Dismissed Hunter's pet is still visible on character selection screen and is with you upon login. - **NOT FIXED** 👎 

6. Hunter's pet looses most of it's health upon login/call.  - **99% FIXED.** 😄  
Just like in problem 2 above, there is still a very small difference in health before dismiss and after call.

**NEW ISSUE!** 😢 
7. Hunter Pet's talent [Wild Hunt](http://wotlk.openwow.com/spell=62762) no longer works.
I had Rank 1 of this talent (+20% stamina and AP contribution), leveled up my pet, selected Rank 2 (+40% stamina and AP contribution) and my pet's health remained exactly the same. I'm fairly sure it worked before (at least Rank 1 did).

**Comment by killerwife** [comment]
7. https://github.com/cmangos/mangos-wotlk/commit/a36790b63d17e74e239f3c5dc516035373cce928
Likely related. The previous formula was wrong, i dunno how talent was implemented but likely I affected something.

**Comment by killerwife** [comment]
And 2,6 related to blood pact. If you turn it off, it will likely work properly. Related to proper reapplication of STAT buffs I think.

**Comment by Darth-Postal** [comment]
About 2 and 6, I've seen the same tiny difference for Hunter's pets too. No Blood Pact there. Also, Blood Pact shouldn't affect mana.

About 7, I don't know if formula was correct, I don't remember how much health did I get from Rank 1 and was it really 20%, but I did get some. After I selected Rank 2 today, I got zero. Tried dismissing/calling the pet - same health as before I selected Rank 2.

**Comment by killerwife** [comment]
Ok I honestly have no clue how that talent was/is implemented. Sorry.

**Comment by cyberium** [comment]
Ok so there is still some work to do Thank for this review @Darth-Postal ;)

**Comment by wowmui** [comment]
@cyberium Great work!  Crash issues are no longer exists!
 But About 3 and 5 is not really fixed.
In classic core I check the PetHandler.cpp and I only found Abandon option (maybe?). warlock pets never need this ,and they should have only Dismiss option. 
Although Eyes of the Beast and pet casting AI are stil has those issues at this time. But I have no clue abount those problems.
Thanks Cmangos team again!

**Comment by Darth-Postal** [comment]
Just tested the latest core. The health/mana difference after mounting/dismounting and dismissing/calling is gone completely. 👍 Problem with Hunter pet on login screen is also gone 👍

Here are the overall test results:

```diff
+1. Pets get reduced max health and mana upon LvL up. - **FIXED!** 👍 
+2. Pets loose most mana and some health upon mounting/dismounting. - **FIXED!** 👍  
+3. Right-clicking Warlock's pet and selecting "Dismiss" does nothing. - **FIXED!** 👍 
-4. Warlock's pet becomes "Unknown" after some time playing. - **NOT FIXED** 👎 
+5. Dismissed Hunter's pet is still visible on character selection screen and is with you upon login. - **FIXED!** 👍 
+6. Hunter's pet looses most of it's health upon login/call.  - **FIXED!** 👍 
-7. Hunter Pet's talent [Wild Hunt](http://wotlk.openwow.com/spell=62762) no longer works. - **NOT FIXED** 👎 
```

**Comment by killerwife** [comment]
@Darth-Postal we had a very long conversation and the talent never worked. We need to implement a new subsystem for passives for it to be implemented properly. It will be done soon-ish, dont worry.

**Comment by Darth-Postal** [comment]
Thank you and everyone else involved! 👍 Great job!

**Comment by wowmui** [comment]
@killerwife 
![image](https://cloud.githubusercontent.com/assets/12601614/21954300/dd6de37c-da87-11e6-9479-402de0c544a0.png)
Hi! There is a screenshot about my issues  any idea ?

**Comment by Phatcat** [comment]
Yeah, for case 7 that issue is an oldie; https://github.com/cmangos/issues/issues/295

So only thing left in this issue is case 4. That may be a tricky one, though.

**Comment by killerwife** [comment]
All of these issues should now be resolved.
