### ISSUE TITLE
Thank you!!!

### ISSUE THREAD

**Issue by cyberium** [cmangos/issues#1199]
**Current behavior**: 
We are still alive, maintaining 3 differents core. Improving them almost every days.

**Expected behavior**: 
To be in a good health to be able to continue this work with all of you guys.

**Steps to reproduce**:
1. Turn on your computer.
2. Turn on your brain.
3. Have fun coding/testing/reviewing.

**Client version**: WoTLK, TBC, CLASSIC
**Database version**: wotlk-db, tbc-db, classic-db
**Operating system**: Our/Your Heart.

## Merry Christmas and Happy New Year.

Special thanks to CMaNGOS devs who are making open source still possible. I will not quote them all but iam sure you know them ;)

**Comment by Tobschinski** [comment]
?????

**Comment by wowmui** [comment]
I want join developer. I can fix some bugs and some can't. Where can I discuss them with you guys?

**Comment by Rushor** [comment]
confirmed

**Comment by cala** [comment]
I can reproduce this and I will probably for some more time !

**Comment by AbaddonL4G** [comment]
got stuck here:
2. Turn on your brain.

**Comment by Lillecarl** [comment]
@wowmui You should start submitting pullrequests.

**Comment by cyberium** [comment]
Should be fixed thanks! ;-)
