### ISSUE TITLE
[CLASSIC][TBC][WOTLK] Too Many ERROR:Creature (GUIDLow: ***) Errors

### ISSUE THREAD

**Issue by apo126** [cmangos/issues#1200]
Cmangos wotlk: a7cfe25
World DB: WoTLKDB v1.0 'Echoes of Northrend' for CMaNGOS-WOTLK 12943 with 647 update

ERROR:Creature (GUIDLow: 12449) X: 68.507660 Y: 0.393653 (original) in grid[32,32]cell[0,0] instead grid[32,32]cell[1,0]
ERROR:Creature (GUIDLow: 12449) X: 71.370155 Y: -1.018846 (original) in grid[32,32]cell[1,0] instead grid[32,31]cell[1,7]

**Comment by apo126** [comment]
ERROR:Creature (GUIDLow: 12460) X: 465.476776 Y: 80.719337 (original) in grid[32,32]cell[7,1] instead grid[32,32]cell[6,1]

**Comment by apo126** [comment]
ERROR:Creature (GUIDLow: 12506) X: 444.213074 Y: -466.506104 (original) in grid[32,31]cell[6,0] instead grid[32,31]cell[6,1]
ERROR:Creature (GUIDLow: 12507) X: 443.915619 Y: -466.539063 (original) in grid[32,31]cell[6,0] instead grid[32,31]cell[6,1]
ERROR:Creature (GUIDLow: 12518) X: 334.460327 Y: -382.506378 (original) in grid[32,31]cell[4,2] instead grid[32,31]cell[5,2]
ERROR:Creature (GUIDLow: 12517) X: 333.998199 Y: -384.364166 (original) in grid[32,31]cell[4,2] instead grid[32,31]cell[5,2]

**Comment by apo126** [comment]
ERROR:Creature (GUIDLow: 12567) X: 780.236633 Y: -0.391192 (original) in grid[33,32]cell[3,0] instead grid[33,31]cell[3,7]
ERROR:Creature (GUIDLow: 12568) X: 779.461792 Y: -0.116627 (original) in grid[33,32]cell[3,0] instead grid[33,31]cell[3,7]
ERROR:Creature (GUIDLow: 12569) X: 800.680969 Y: -21.016535 (original) in grid[33,31]cell[3,7] instead grid[33,31]cell[4,7]
ERROR:Creature (GUIDLow: 12569) X: 799.838623 Y: -18.985886 (original) in grid[33,31]cell[4,7] instead grid[33,31]cell[3,7]
ERROR:Creature (GUIDLow: 12568) X: 789.160583 Y: 0.092393 (original) in grid[33,31]cell[3,7] instead grid[33,32]cell[3,0]
ERROR:Creature (GUIDLow: 12567) X: 789.158936 Y: 0.040194 (original) in grid[33,31]cell[3,7] instead grid[33,32]cell[3,0]
ERROR:Creature (GUIDLow: 12569) X: 800.341980 Y: -20.892668 (original) in grid[33,31]cell[3,7] instead grid[33,31]cell[4,7]
ERROR:Creature (GUIDLow: 5) X: 794.121643 Y: -0.687845 (original) in grid[33,32]cell[3,0] instead grid[33,31]cell[3,7]

**Comment by wowmui** [comment]
me too (classic)

**Comment by ulfgebhardt** [comment]
Also present in tbc

**Comment by AnonXS** [comment]
resolved? extracted data issue? CMaNGOS Discord https://discord.gg/Dgzerzb has link to most recent data.

**Comment by killerwife** [comment]
I would like to know that as well. If someone sees this in 2 months, close it.

**Comment by jimmybrancaccio** [comment]
I'll do some replication on this and close if I'm not seeing anything. Thanks @AnonXS & @killerwife!

**Comment by jimmybrancaccio** [comment]
Cool, thank you @Grz3s! Closing this one out as resolved. If anyone sees any further issues with this please don't hesitate to open a new case.
