### ISSUE TITLE
[WOTLK] The Tome of Divinity - Resurrection of Henze Faulk

### ISSUE THREAD

**Issue by opnoack** [cmangos/issues#1201]
**Current behavior**: 
Using the tome on henze doesn't ressurect him but the item disappears and the quest is not finished.

**Expected behavior**: 
The tome should ressurect henze. The quest should be finished or finishable.

**Steps to reproduce**:

1. Create Paladin
2. Take the quest "the tome of divinity" from a paladin teacher around level 14
3. Try to ressurect henze Faulk at the heroes vigil

**Client version**: 
3.3.5a

**Commit hash**: 
Cloned the master last Saturday.

**Database version**: 
Same

**Operating system**: 
Client Windows 10
Server Ubuntu 14.04

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Grz3s** [comment]
quest works perfectly fine with WoTLKDB 1.0
https://github.com/cmangos/wotlk-db/commits/master

**Comment by Grz3s** [comment]
quest is done by sd2 ..
and works perfectly fine with current wotlk core (i tested it few Times)
This is how it works..
https://youtu.be/JPhrGLlPQ9o

**Comment by jimmybrancaccio** [comment]
As per @Grz3s it seems like this is a non-issue. I am closing this for now, however if you're still experiencing any problem, please open a new issue in GitHub so we may further investigate. Thanks!
