### ISSUE TITLE
Error when running InstallFullDB.sh

### ISSUE THREAD

**Issue by xathian** [cmangos/issues#1203]
On a new server setup I am trying to update the database, but after running InstallFullDB.sh, I get this error:

> Processing database updates ...
    Appending Updates/1451_fire_effiy.sql
    Appending Updates/1452_rumsey_rum.sql
    Appending Updates/1453_katrina_shimmerstar.sql
    Appending Updates/1454_z2685_01_mangos_event_linkedto.sql
ERROR 1067 (42000) at line 3: Invalid default value for 'start_time'
ERROR: cannot apply Updates/1454_z2685_01_mangos_event_linkedto.sql

I have no idea what to do to solve this.

**Comment by hlarsen** [comment]
cmangos/classic-db#23 should take care of it

**Comment by Muehe** [comment]
This can also be solved by changing your sql_mode. You have to remove the `NO_ZERO_DATE` and the `NO_ZERO_IN_DATE` modes. http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date

**Comment by Lillecarl** [comment]
https://github.com/cmangos/wotlk-db/releases
https://github.com/cmangos/tbc-db/releases
https://github.com/cmangos/classic-db/releases

Use the prebuilt databases if experiencing errors, they should work for you! 👍
