### ISSUE TITLE
[CLASSIC] Shadowfang Keep - Issue with Door Behind Fenrus

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1204]
I was running Shadowfang Keep a few times and had some issues with the door behind Fenrus the Devourer.

After you kill Fenrus, Arugal appears above and summons 4 Arugal's Voidwalker mobs. If you pull these mobs right away and kill them, the door behind Fenrus opens as expected.

The problem occurs if you don't pull and kill the 4 voids right away for whatever reason (don't pull them at all, break the combat with a skill or die). In this case the voidwalkers start to patrol the stairs leading to the room. During this patrol, some or all of the voidwalkers in the group can disappear by gliding somewhere out of the map. When this happens, the doors can no longer be opened, because the scripts (correctly) checks for 4 voidwalker kills before opening the door.

Easy reproduce:
- .go creature fenrus
- Kill the dog
- Don't engage the 4 voidwalkers, just follow them as they start to patrol
- See some of them getting lost, especially at the bottom of the stairs

**Comment by OriginsDev** [comment]
Solution to this is simply remove and waypoints associated with those voidwalkers so they don't leave?
Also you have appropriate maps enabled such as vmaps / mmaps?

**Comment by Rushor** [comment]
why do they even have waypoints?
