### ISSUE TITLE
[Classic]Pet Double Max health

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1205]
**Current behavior**: 
Hunter pet and worlock pet have double max health when change map or resummon and curhealth is correct. Maybe Set/GetMaxHealth() issue?
**Expected behavior**: 
Pets should get max health normally.
**Steps to reproduce**:

1.  Create a hunter or warlock character.
2. Tame or summon a pet.
3. Resummon or transferred to other places and watching pet's max health.

**Client version**: 
1.12.1
**Commit hash**: 
dbb1ff713b946628f3682978c814120c576e7c06
**Database version**: 
2692_04
**Operating system**: 
Linux or Windows

**Comment by al3xc1985** [comment]
this bug is also in tbc and wotlk

**Comment by cyberium** [comment]
Should be fixed thanks
