### ISSUE TITLE
[Classic] mangosd.exe crash

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1206]
**Current behavior**: 
This is Crash log

[mangosd.exe_[2-1_22-2-0].txt](https://github.com/cmangos/issues/files/680931/mangosd.exe_.2-1_22-2-0.txt)

I have only 20 players on my server. Every 20 minutes to crash once.

I can't understand where the problem is . Can anyone help me ?
**Expected behavior**: 
 I hope to find the problem, do not crash.
**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
z2692_04
**Operating system**: 
Win 2008 R2

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by wowmui** [comment]
[mangosd.exe_[3-1_7-17-3].txt](https://github.com/cmangos/issues/files/681608/mangosd.exe_.3-1_7-17-3.txt)

**Comment by Lillecarl** [comment]
Crashes on gist: https://gist.github.com/Lillecarl/04c77e419a557ffbd63c1dbbdc13b34a

**Comment by cyberium** [comment]
Should be fixed thanks
