### ISSUE TITLE
[TBC] Lost in Battle Quest Issue

### ISSUE THREAD

**Issue by thrd92** [cmangos/issues#1209]
**Current behavior**: Quest doesn't work

**Expected behavior**: http://www.wowhead.com/quest=4921/lost-in-battle

**Steps to reproduce**:

1. Quest can't be completed, it's imopssible to examine beaten corpse (right-click menu that appears doesn't contain a clickable element "Examine corpse in detail ...").

**Client version**: 2.4.3

**Commit hash**: https://github.com/cmangos/mangos-tbc/commit/cc977e14c0b2717675e38154351dc82da91e0d7a

**Database version**: Last TBCDB

**Operating system**: Windows 8.1 x64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by ulfgebhardt** [comment]
UPDATE creature_template SET GossipMenuId=2871 WHERE entry=10668;
DELETE FROM gossip_menu WHERE entry IN (2871,2872);
INSERT INTO gossip_menu (entry, text_id) VALUE (2871, 3557),(2872, 3558);
DELETE FROM conditions WHERE condition_entry=1075;
INSERT INTO conditions (condition_entry,type,value1,value2) VALUE(1075,9,4921,0);
DELETE FROM gossip_menu_option WHERE menu_id=2871;
INSERT INTO gossip_menu_option (menu_id,id,option_icon,option_text,option_id,npc_option_npcflag,action_menu_id,action_poi_id,action_script_id,box_coded,box_money,box_text,condition_id) VALUES
(2871, 0, 0, 'I inspect the body further.', 1, 1, 2872, 0, 2871, 0, 0, NULL, 1075);
DELETE FROM dbscripts_on_gossip WHERE id=2871;
INSERT INTO dbscripts_on_gossip (id,delay,command,datalong,datalong2,buddy_entry,search_radius,data_flags,dataint,dataint2,dataint3,dataint4,x,y,z,o,comments) VALUES
(2871,0,8,10668,0,0,0,0,0,0,0,0,0,0,0,0,'Quest 4921 - Kill credit');

**Comment by ulfgebhardt** [comment]
But i remember some Server where the 3 Mobs which killed the Wife Appear after you talk to the Corpse - im not sure thats blizzlike tho. This SQL-Fix does not spawn mobs but completes the Quest on Gossip.

**Comment by Darth-Postal** [comment]
Perhaps TBC-DB needs backport of https://github.com/unified-db/Database/commit/531480b073faf96c324a2cf77eb5237f06d4d0e6 ?

**Comment by Rushor** [comment]
> But i remember some Server where the 3 Mobs which killed the Wife Appear after you talk to the Corpse - im not sure thats blizzlike tho. This SQL-Fix does not spawn mobs but completes the Quest on Gossip.

no not blizzlike https://www.youtube.com/watch?v=jEFlzIAtjDc

**Comment by killerwife** [comment]
wotlk-db backports are all done on my end. If you have seen the sheer amount of PRs right now on cmangos-tbc, then thats what needs to be addressed first. And those by no means are all that are needed.

**Comment by Darth-Postal** [comment]
> If you have seen the sheer amount of PRs right now on cmangos-tbc, then thats what needs to be addressed first.

This isn't a core issue. Core part was implemented here: https://github.com/cmangos/mangos-tbc/commit/20a460bdc8ea34a40de66e2ca213f920baa53f77

**Comment by killerwife** [comment]
Yes but the only reason I am able to update tbc-db alone is linearity. If I start cherry-picking fixes which should/should not be out there, I will no longer have enough time to work on something new.

**Comment by ulfgebhardt** [comment]
Updated Gossip-Text to the one shown in the video

```
UPDATE creature_template SET GossipMenuId=2871 WHERE entry=10668;
DELETE FROM gossip_menu WHERE entry IN (2871,2872);
INSERT INTO gossip_menu (entry, text_id) VALUE (2871, 3557),(2872, 3558);
DELETE FROM conditions WHERE condition_entry=1075;
INSERT INTO conditions (condition_entry,type,value1,value2) VALUE(1075,9,4921,0);
DELETE FROM gossip_menu_option WHERE menu_id=2871;
INSERT INTO gossip_menu_option (menu_id,id,option_icon,option_text,option_id,npc_option_npcflag,action_menu_id,action_poi_id,action_script_id,box_coded,box_money,box_text,condition_id) VALUES
(2871, 0, 0, 'Examine corpse in detail...', 1, 1, 2872, 0, 2871, 0, 0, NULL, 1075);
DELETE FROM dbscripts_on_gossip WHERE id=2871;
INSERT INTO dbscripts_on_gossip (id,delay,command,datalong,datalong2,buddy_entry,search_radius,data_flags,dataint,dataint2,dataint3,dataint4,x,y,z,o,comments) VALUES
(2871,0,8,10668,0,0,0,0,0,0,0,0,0,0,0,0,'Quest 4921 - Kill credit');
```

**Comment by killerwife** [comment]
Tested the other day seems to be working fine.
