### ISSUE TITLE
[WOTLK] Illidan Stormrage May Have Some Errors with It's Scripting

### ISSUE THREAD

**Issue by apo126** [cmangos/issues#1210]
Cmangos wotlk: e2dfec1
World DB: WoTLKDB v1.0 'Echoes of Northrend' for CMaNGOS-WOTLK 12943 with 699 update

In Black Temple, after death of Flame of Azzinoth, Illidan Stormrage will not come down to the ground and you can not attack him. Please check.

**Comment by xfurry** [comment]
Maybe something related to https://github.com/cmangos/mangos-wotlk/blob/master/src/scriptdev2/scripts/outland/black_temple/boss_illidan.cpp#L1632

I know that some things were changed in related to this function.

**Comment by apo126** [comment]
@xfurry Yesterday I tried again. Even for one hour, Illidan still hovers in the sky.

**Comment by AnonXS** [comment]
Duplicate https://github.com/cmangos/issues/issues/1617, "Black Temple - Illidan Encounter Review"
