### ISSUE TITLE
[CRASH] anyone help me please!

### ISSUE THREAD

**Issue by Rapth** [cmangos/issues#1211]
**Current behavior**: just played a hunter.killing mobs in Uderbog, 10-20 min, 100% will encouter a crash,
log says: error  assert Worldobject::GetTerrain failed

**Expected behavior**: 

**Steps to reproduce**:just played a hunter.killing mobs in Uderbog, 10-20 min, 100% will encouter a crash,
log says: error  assert Worldobject::GetTerrain failed

1. 
2. 
3. 

**Client version**: 2.4.3

**Commit hash**: 527c636 

**Database version**: 1.5

**Operating system**: win 10 64 bit
[mangosd.exe_[6-1_21-32-49].txt](https://github.com/cmangos/issues/files/690393/mangosd.exe_.6-1_21-32-49.txt)

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Actually, I do have a fix. On pet delete we call MoveFollow in destructor chain, causing this crash. All you need to do is delay MoveFollow until next UpdateAI and it will no longer crash. Fix will come soon-ish.

**Comment by Rapth** [comment]
@killerwife thank you，i will check it soon！

**Comment by killerwife** [comment]
https://github.com/killerwife/mangos-tbc/commit/de6fdfeeb4b5188ab8024f763b7c5831cf2c8797 This is temporary fix, but I am sure @cyberium will refactor it somehow. You can use this until then.

**Comment by Rapth** [comment]
@killerwife  awesome！！

**Comment by wowmui** [comment]
@killerwife Thanks! Any idea on my issues?
[mangosd.exe_[6-1_23-27-54].txt](https://github.com/cmangos/issues/files/690661/mangosd.exe_.6-1_23-27-54.txt)

I'm very confused.

**Comment by Rapth** [comment]
@wowmui  you just have the same issue as mine
