### ISSUE TITLE
[CLASSIC] If Player Logs Out When Dead, They Lose Their Offhand Item/Weapon

### ISSUE THREAD

**Issue by gaosheng136** [cmangos/issues#1212]
**Current behavior**: 

**Expected behavior**: 

**Steps to reproduce**:

1. [Classic] if player dead to logout, off hand  would  lose
2. 
3. 

**Client version**: 
 1.12.3
**Commit hash**: 
5d797e2ea448eec6c7ebefdfd93598a401005dfe
**Database version**: 
z2693_01_mangos_gameobject_template.sql
**Operating system**: 
win2008 r2

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by ulfgebhardt** [comment]
also present in tbc. Offhand will be sent via Mail

**Comment by wowmui** [comment]
Me too !
hope fix it ,thanks.

**Comment by Lillecarl** [comment]
So we should implement a blizzard bug? Haha

**Comment by ulfgebhardt** [comment]
No this is a bug happening.

**Comment by yushicsm** [comment]
when a player dead and logout,
the Dual Wield will be invalid

**Comment by cala** [comment]
Is this still happening? I don't remember seeing it in a while.

**Comment by jimmybrancaccio** [comment]
Closing this out due to inactivity. If this is still an issue please create a new issue so we may further investigate.
