### ISSUE TITLE
[classic] Newest Core Crash again

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1213]
**Current behavior**: 
LoadPetFormDB crash
[mangosd.exe_[8-1_22-16-19].txt](https://github.com/cmangos/issues/files/692140/mangosd.exe_.8-1_22-16-19.txt)
AND
[mangosd.exe_[8-1_14-14-56].txt](https://github.com/cmangos/issues/files/692155/mangosd.exe_.8-1_14-14-56.txt)
[mangosd.exe_[8-1_14-35-4].txt](https://github.com/cmangos/issues/files/692154/mangosd.exe_.8-1_14-35-4.txt)
[mangosd.exe_[8-1_14-51-34].txt](https://github.com/cmangos/issues/files/692149/mangosd.exe_.8-1_14-51-34.txt)
[mangosd.exe_[8-1_14-53-11].txt](https://github.com/cmangos/issues/files/692157/mangosd.exe_.8-1_14-53-11.txt)
[mangosd.exe_[8-1_14-54-17].txt](https://github.com/cmangos/issues/files/692152/mangosd.exe_.8-1_14-54-17.txt)
[mangosd.exe_[8-1_14-55-37].txt](https://github.com/cmangos/issues/files/692143/mangosd.exe_.8-1_14-55-37.txt)
[mangosd.exe_[8-1_15-0-57].txt](https://github.com/cmangos/issues/files/692141/mangosd.exe_.8-1_15-0-57.txt)
[mangosd.exe_[8-1_15-3-43].txt](https://github.com/cmangos/issues/files/692148/mangosd.exe_.8-1_15-3-43.txt)
[mangosd.exe_[8-1_15-6-43].txt](https://github.com/cmangos/issues/files/692146/mangosd.exe_.8-1_15-6-43.txt)
[mangosd.exe_[8-1_15-13-23].txt](https://github.com/cmangos/issues/files/692145/mangosd.exe_.8-1_15-13-23.txt)
[mangosd.exe_[8-1_15-22-29].txt](https://github.com/cmangos/issues/files/692159/mangosd.exe_.8-1_15-22-29.txt)
[mangosd.exe_[8-1_15-26-48].txt](https://github.com/cmangos/issues/files/692150/mangosd.exe_.8-1_15-26-48.txt)
[mangosd.exe_[8-1_15-32-43].txt](https://github.com/cmangos/issues/files/692158/mangosd.exe_.8-1_15-32-43.txt)
[mangosd.exe_[8-1_15-40-4].txt](https://github.com/cmangos/issues/files/692144/mangosd.exe_.8-1_15-40-4.txt)
[mangosd.exe_[8-1_15-42-57].txt](https://github.com/cmangos/issues/files/692153/mangosd.exe_.8-1_15-42-57.txt)
[mangosd.exe_[8-1_15-47-39].txt](https://github.com/cmangos/issues/files/692142/mangosd.exe_.8-1_15-47-39.txt)
[mangosd.exe_[8-1_15-49-17].txt](https://github.com/cmangos/issues/files/692151/mangosd.exe_.8-1_15-49-17.txt)
[mangosd.exe_[8-1_21-22-9].txt](https://github.com/cmangos/issues/files/692147/mangosd.exe_.8-1_21-22-9.txt)
[mangosd.exe_[8-1_21-52-7].txt](https://github.com/cmangos/issues/files/692156/mangosd.exe_.8-1_21-52-7.txt)

lots of crash log. T_T
**Expected behavior**: 
please....
**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 
1.12.1
**Commit hash**: 
5d797e2ea448eec6c7ebefdfd93598a401005dfe
**Database version**: 
Classic-db z2693_01
**Operating system**: 
Win10 x64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Hyperorx** [comment]
Can confirm this, same issue is happening from our end with the crash.

**Comment by Rapth** [comment]
latestcore is literally buggy . it is under developing.

**Comment by Hyperorx** [comment]
Cyberium linked me to a patch to the pet.cpp. So far our hunters are not crashing the server instantly 👍  The CMangos team has been amazing, and helpful. Keep up the good work!

**Comment by Rapth** [comment]
YES they are genius!

**Comment by cyberium** [comment]
Should be fixed thanks
