### ISSUE TITLE
[Classic] Sprok dialogue missing

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1214]
Talking to [Sprok](http://db.vanillagaming.org/?npc=8320) will show *Missing US text*.
I don't know what he should say, or if you should be able to talk to him at all.

**Comment by Rushor** [comment]
this should be his text http://i.imgur.com/dAM7Q3e.png

**Comment by killerwife** [comment]
DELETE FROM npc_text WHERE id IN(17880);
INSERT INTO npc_text VALUES
('17880', 'This teleporter will transport you to Grom''gol in Northern Stranglethorn.$B$BUsually.$B$BI mean, sometimes it''ll just disintegrate you, or reduce all your soft tissues into a greenish, foul-smelling mist, but mostly it''s safe!$B$B...mostly.', '', '0', '100', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '0');

@cala

**Comment by katz1** [comment]
@Rushor 
That is strange, is it really transporting to Grom'gol?
Because the teleporter currently sends you back to Booty Bay, it might be another issue?

**Comment by killerwife** [comment]
@katz1 You are indeed correct, it was all moved in the cataclysm. And since I am an airhead I did not notice that. Thx, I will botch the text somehow or find it on the web.

**Comment by killerwife** [comment]
Also I have reason to believe http://www.wowhead.com/npc=7853/scooty#comments has incomplete gossip as well in all DBs :) Not 100% sure, gotta find a powerleveling vid or smth.

**Comment by cyberium** [comment]
not a core issue
