### ISSUE TITLE
[CLASSIC] Issues with Pets Armor Issues and Creature Sometime Ignore Aggro and Drain Soul Cast

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1215]
**Current behavior**: 
**Pets Armor lower than normally stats**:
guess 
https://github.com/cmangos/mangos-classic/commit/27366aab8ef51086f87b8f15a2a3492383b4383f
caused this problem.

**loadPetFromDB crash**:
guess https://github.com/cmangos/mangos-classic/commit/934c09e2ce26dbfa866a1049b738c4a63a34152d
caused this issue.

**sometimes creature can't attack player ,Especially ranged class. Like mage , hunter**.
guess 
https://github.com/cmangos/mangos-classic/commit/7518e0b89215f0d1a68e67799e63d09ed73b1cae
caused this problem.

Drain Soul resist by caster himself and debuff keep on target

guess 
https://github.com/cmangos/mangos-classic/commit/2b46e840da4dd24b1fbbf2716c6dc8a0d026c4b8
caused this problem.

**Expected behavior**: 

maybe we can fix those issues?

**Steps to reproduce**:

1. create a hunter or warlock character.
2.  summon pet.
3. press Shift+P  ,value of armor is not correct.
4. Play warlock and Improve shadow resistance, cast Drain Soul on enemy and spell log displayed Your Drain Soul resisted by yourself. Also enemy keeps the Drain Soul debuff.

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
z2693_01
**Operating system**: 
WIN10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
duplicate https://github.com/cmangos/issues/issues/1778
