### ISSUE TITLE
[TBC] Opening Chests Should Call Nearby Mobs

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/issues#1216]
Opening Chests (and other GOs?) should call nearby mobs. This was present since Vanilla.
Im unsure this applies to all GOs or just Chests.

**Current behavior**: 
Opening a Chest with a Mob nearby which is not aggroed will not call the Mob.

**Expected behavior**: 
Opening a Chest with a Mob nearby which is not aggroed should call the Mob.
A possible Implementation can be to call surrounding mobs like Raptors do on low HP on interact with the GO. This also applies to Mobs which are grey in levelrange to the Player.

**Steps to reproduce**:

1. Find a Chest
2. LOS a Mob close to the Chest
3. Open it
4. Mob does not aggro.

**Client version**: 
2.4.3

**Commit hash**: 
Latest TBC

**Database version**: 
Latest TBC

**Comment by killerwife** [comment]
Likely requires a pack of mobs to be called upon when chest is opened. This is however not implemented at the moment at all.

**Comment by Warlockbugs** [comment]
AFAIK gameobjects and chests may have faction set. Maybe it should pull nearby mobs of allied faction ids?

**Comment by robinsch** [comment]
Faction doesn't help here.
