### ISSUE TITLE
[CLASSIC][TBC][WOTLK] Charge Lets You Fall Underground With Some Paths

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/issues#1217]
[Warrior] Charge lets you fall underground with some paths

**Current behavior**: 
When you charge a Mob it can happen that you fall underground and die. This is 100% reproducable.

Starting Point:
![wowscrnshot_010817_214624](https://cloud.githubusercontent.com/assets/1238238/21753400/91ed9590-d5ec-11e6-8284-38a59007d245.jpg)

After fall underground, .gm fly on and moving upwards:
![wowscrnshot_010817_214702](https://cloud.githubusercontent.com/assets/1238238/21753402/9b25ed2e-d5ec-11e6-95a6-a9c1c54d3da3.jpg)

Exact Coordinates in Chat:
![wowscrnshot_010817_214723](https://cloud.githubusercontent.com/assets/1238238/21753403/a04a130c-d5ec-11e6-8ea6-6dbfcac7c4d0.jpg)

Charging with .gm fly on results in success and no fall underground:
![wowscrnshot_010817_214817](https://cloud.githubusercontent.com/assets/1238238/21753405/a5190c26-d5ec-11e6-9833-c1c94e61f479.jpg)

**Expected behavior**: 
Players should in no case fall underground.

Note: This is very frustrating for the Player since you cannot recieve your corpse back(they are underground and out of reach). The Player has no other choice then to ress at the spirithealer which gives him malus and monetary loss.

**Steps to reproduce**:

1. Make a Warrior
2. .learn all_myclass (& .gm on)
3. .go xy 1537 540 1
4. Move to the Position in the Screenshot
5. Charge the Mob where you teleported onto (Guid: 29968)
6. Fall underground

Note: Notice the Area infront of you where you start the Charge is not walkable. Charge passes it tho.

This is most likely a Problem with mmaps/vmaps(?). Im giving this illustrated example to make it easier to reproduce. It seems to happen (more often?) when you charge onto edges in steep areas.

**Client version**: 
2.4.3

**Commit hash**: 
Latest TBC

**Database version**: 
Latest TBC

**Operating system**: 
Debian Server, Windows Client.

**Related**
https://github.com/cmangos/issues/issues/1097

**Comment by wowmui** [comment]
all cmangos core have same issues!

**Comment by ulfgebhardt** [comment]
I was told that there is a new vmaps/mmaps on the rise and that i should temper with the charge effect to prevent the fall. So i did and im sharing this so you dont need to.

From 65c4e95a2100553ae0dd1af35884015eb6f3e825 Mon Sep 17 00:00:00 2001
From: Ulf Gebhardt <ulf.gebhardt@webcraft-media.de>
Date: Wed, 11 Jan 2017 01:36:26 +0100
Subject: [PATCH] #290 charge fix (value)

```
---
 src/game/SpellEffects.cpp | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/src/game/SpellEffects.cpp b/src/game/SpellEffects.cpp
index dc793bd..c2af3fa 100644
--- a/src/game/SpellEffects.cpp
+++ b/src/game/SpellEffects.cpp
@@ -6834,13 +6834,13 @@ void Spell::EffectCharge(SpellEffectIndex /*eff_idx*/)
     // TODO: research more ContactPoint/attack distance.
     // 3.666666 instead of ATTACK_DISTANCE(5.0f) in below seem to give more accurate result.
     float x, y, z;
-    unitTarget->GetContactPoint(m_caster, x, y, z+0.1f, 3.666666f);
+    unitTarget->GetContactPoint(m_caster, x, y, z, 3.666666f);
 
     if (unitTarget->GetTypeId() != TYPEID_PLAYER)
         ((Creature*)unitTarget)->StopMoving();
 
     // Only send MOVEMENTFLAG_WALK_MODE, client has strange issues with other move flags
-    m_caster->MonsterMoveWithSpeed(x, y, z, 24.f, true, true);
+    m_caster->MonsterMoveWithSpeed(x, y, z+1.5f, 24.f, true, true);
 
     // not all charge effects used in negative spells
     if (unitTarget != m_caster && !IsPositiveSpell(m_spellInfo->Id, m_caster, unitTarget))
@@ -6863,7 +6863,7 @@ void Spell::EffectCharge2(SpellEffectIndex /*eff_idx*/)
         return;
 
     // Only send MOVEMENTFLAG_WALK_MODE, client has strange issues with other move flags
-    m_caster->MonsterMoveWithSpeed(x, y, z, 24.f, true, true);
+    m_caster->MonsterMoveWithSpeed(x, y, z+1.5f, 24.f, true, true);
 
     // not all charge effects used in negative spells
     if (unitTarget && unitTarget != m_caster && !IsPositiveSpell(m_spellInfo->Id, m_caster, unitTarget))
-- 
2.8.3.windows.1
```

**Comment by dagochen** [comment]
hackfix ;)

Better fix movement and we wont have any problems with pathfinding and spells related to it. Similar to charge effects there is disoriented movement falling through walls and floor sometimes.

**Comment by ulfgebhardt** [comment]
Yes i agree - but im not capable of understanding this vmaps/mmaps

**Comment by dagochen** [comment]
There are already several discussions about this and I know from 1-2 devs who are working on this already or in the near future.

**Comment by Phatcat** [comment]
Will no longer fall to your death, seems like you are force-pushed up and out of the ground but definitely something is going on because while charging in that area you're definitely going through the terrain and can see so clearly.

**Comment by AnonXS** [comment]
Charge Movement seems to work better in that regard then being feared at these locations.

**Comment by al3xc1985** [comment]
@killerwife i believe this 2 can be closed

**Comment by killerwife** [comment]
This can definitely still happen but the iteration of this bug described in this issue is definitely now extant.
