### ISSUE TITLE
[Classic] if player dead , some item  enchant  Invalid, such as item 19782    

### ISSUE THREAD

**Issue by gaosheng136** [cmangos/issues#1219]
Current behavior:

Expected behavior:

Steps to reproduce:

[Classic] if player dead , some item  enchant  Invalid, such as item 19782    
Client version:
1.12.3
Commit hash:
5d797e2ea448eec6c7ebefdfd93598a401005dfe
Database version:
z2693_01_mangos_gameobject_template.sql
Operating system:
win2008 r2

**Comment by cyberium** [comment]
Sound like this spell is not passive where it should be.

@cala, @killerwife i just tested
```sql
UPDATE spell_template SET Attributes = Attributes | 0x040 WHERE Id = 24148;
```

And it work.
What is your thought?

**Comment by killerwife** [comment]
Passive in TBC. I approve.

**Comment by cala** [comment]
Works on Classic. :+1:
We need to fix this by core SQL update though, if I remember correctly the workflow regarding the `spell_template` table.

**Comment by cala** [comment]
Question to @cyberium about the proper way to push this update: do I update directly into the `/sql/base/dbc/cmangos_fixes/Spell.sql` or do I need to create an SQL update file, let's say in `/sql/updates/mangos/` as usual?

**Comment by cyberium** [comment]
You dont have to force this sql update by changing revision for spell_template change. Its only a data change finaly not a scheme change. So only change the cmangos_fixes/Spell.sql file with the new request and a little comment to explain the need of it is enough.
