### ISSUE TITLE
Paladin Class Quest - The Tome of Divinity - Broken/Missing Script Behaviour

### ISSUE THREAD

**Issue by OriginsDev** [cmangos/issues#1222]
**Current behavior**: 
Quest ID = 1786 (The Tome of Divinity)
NPC ID = 6172 (Henze Faulk)
Item ID = 6866 (Symbol of Life)

When on the quest '1786' the player finds NPC '6172' in a dead state most likely set by a flag, he is then resurrected with the use of item '6866'. However he doesn't have his flag changed to then become *alive / interactable*

**Expected behavior**: 
The NPC Should then be removed from its "Dead state" so the player can use the gossip action to hand in the quest once the item above has been used on him.
A good thing is that using the item is registering the quest complete, you just can't hand it in to a dead body :)

**Steps to reproduce**:

1.  add quest - 1786
2.  find npc - 6172 (Defias lake in Elwyn top right)
3. use item - 6866 on the npc 

**Client version**: 
1.12.1

**Commit hash**: 
#no-idea

**Database version**: 
Latest Pre-compiled

**Operating system**: 
Windows

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by OriginsDev** [comment]
Fix is basically upon use of item 6866 change death state of NPC Target from ON to OFF
This can be tested in game proved working with the GM command (.npc setdeathstate on/off)

**Comment by OriginsDev** [comment]
Note: it appears this class quest is also available for dwarf paladin's also which will have it's own npc - but fixing one will fix the other

**Comment by Grz3s** [comment]
what ver You talking about? (classicDB, TBCDB or WotLKDB) ??
This was reported week or 2 ago ...
quest work fine in WoTLKDB.. 
I even recorded quick avi to show how it works ...
https://www.youtube.com/watch?v=JPhrGLlPQ9o

**Comment by OriginsDev** [comment]
Hi where can I find this script?

**Comment by OriginsDev** [comment]
@Grz3s - seems almost all class quests for paladin aren't working - is the westfall quest working on your db? 
Thanks

**Comment by Grz3s** [comment]
https://github.com/cmangos/mangos-wotlk/blob/master/src/scriptdev2/scripts/world/npcs_special.cpp
```quote
npc_redemption_target   100%    Used for the paladin quests: 1779,1781,9600,9685
```

**Comment by OriginsDev** [comment]
Thank you sir!

**Comment by OriginsDev** [comment]
This has been resolved as my problem - I have checked and the script does exist in vanilla and is working - there was an error in my compile.
