### ISSUE TITLE
Pet Action Bar is missing after reloading UI clientside

### ISSUE THREAD

**Issue by dagochen** [cmangos/issues#1224]
**Current behavior**: 
Pet action bar is missing after player uses /console reloadui 
**Expected behavior**: 
Pet action bar is still there.
**Steps to reproduce**:

1. Create Hunter
2. .npc tame a beast
3. /console reloadui

**Client version**: 
Any :) bug exists in every core (from cmangos to trinity and whatever else...) 

**Fix**: 
void WorldSession::HandleRequestPetInfoOpcode( WorldPacket & /*recv_data */)
This Handler should call _player->PetSpellInitialize();

**Comment by Rushor** [comment]
nice

**Comment by Rushor** [comment]
fix works fine, ty!

**Comment by killerwife** [comment]
I am afraid the correct code is

    if(_player->GetPet())
        _player->PetSpellInitialize();
    else if(_player->GetCharm())
        _player->CharmSpellInitialize();

**Comment by dagochen** [comment]
Damn I always forget about this warlocks and their demons :P

**Comment by killerwife** [comment]
Thats not warlocks, thats charm effects, meaning Chess event, mind control mimicking items, etc.

**Comment by dagochen** [comment]
Not sure if CharmSpellInitialize does anything at all for chess event...? Or is this classic only implementation?
 
if (cinfo && cinfo->CreatureType == CREATURE_TYPE_DEMON && getClass() == CLASS_WARLOCK)
        {
            for (uint32 i = 0; i < CREATURE_MAX_SPELLS; ++i)
            {
                if (charmInfo->GetCharmSpell(i)->GetAction())
                    ++addlist;
            }
        }

**Comment by killerwife** [comment]
All pets have charmInfo since the rewrite.

**Comment by dagochen** [comment]
hmm k
