### ISSUE TITLE
NpcFlags depending on conditions

### ISSUE THREAD

**Issue by Grz3s** [cmangos/issues#1226]
[Wotlk Core] Fresh  -- it may be also problem for other cores also.
[WotlkDB] - fresh
Issue Source:
https://github.com/unified-db/Database/issues/49

Hi
Some NPC's should become vendors/repairers .. after player meets X conditions...
Will give an example here:

Npc Koren in Karazhan
http://www.wowhead.com/npc=16388/koren
He becomes vendor and repairer if player has honored reputation with "The Violet Eye"
Currently we have to set NPCFLAG = 4227 (1 gossip 2 gossip 128 vendor 4096 repairer)
so he has all these options from begining....  (will explain below why)

Sniff shows that he should have NPCFLag = 3 ... 
Also should have gossip_menu_option ... for that vendor/repaiers with condition

So i made that:
```sql
UPDATE creature_template SET NpcFlags = 3 WHERE entry = 16388;
DELETE FROM gossip_menu_option WHERE menu_id = 7435;
INSERT INTO gossip_menu_option (menu_id, id, option_icon, option_text, option_id, npc_option_npcflag, action_menu_id, action_poi_id, action_script_id, box_coded, box_money, box_text, condition_id) VALUES
(7435,0,1,'I\'m in need of your skill as a blacksmith, Koren.',3,128,0,0,0,0,0,NULL,1131);
DELETE FROM conditions WHERE condition_entry = 1131;
INSERT INTO conditions (condition_entry, type, value1, value2) VALUES
(1131,5,967,5);
```
unfortunately ... core will show an error here.
```quote
 Table gossip_menu_option for menu 7435, id 0 has `npc_option_npcflag` = 128 but creatures using this menu does not have corresponding `NpcFlags`. Option will not accessible in game.
 Table `npc_vendor` has data for creature (Entry: 16388) without vendor flag, ignoring
```
Any idea how to fix it?

**Comment by Grz3s** [comment]
ok 
After more diggin.. i found that he should have more gosspis...
and this looks like helps with this issue...
So im going to close it...

**Comment by Saben65** [comment]
@Grz3s Did you ever get this fixed, or did you need some sniff data or anything?
