### ISSUE TITLE
[Classic] Warlock pets abandon / Dismiss

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1228]
**Current behavior**: 
If you summon a new pet , you will not get a dismiss option and get a abandon option. I think warlock should not have "Abandon" option. Because if you abandon pets will cause pet's spell lost.
![image](https://cloud.githubusercontent.com/assets/12601614/21959688/84d8ffe4-db09-11e6-95f2-74eb9a5587fb.png)

**Expected behavior**: 
Warlock at any time should not have abandon options. They will only have dismiss. At least in the vanilla wow.
**Steps to reproduce**:

1. create a warlock character.
2. summon imp or other pets.
3. Right click on the pet will displayed the "Abandon" option instead of dismiss.

**Client version**: 
1.12.1
**Commit hash**: 
f62c79e21f1011188daaff3d983bd6fe8d225376
**Database version**: 
z2693
**Operating system**: 
Any client
[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
Fixed in https://github.com/cmangos/mangos-classic/commit/b9a8e9b42b24eeb77531039d30400efdc638ae46.
