### ISSUE TITLE
[Classic] Davine Favor can't effect holy light and flash of light

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1229]
**Current behavior**: 
Holy Light and Flash of Light can not enhanced by Davine Favor at all.
Holy Shock can cancel the Divine Favor 's buff , but but crit chance is not affected by Divine Favor.
![image](https://cloud.githubusercontent.com/assets/12601614/21959849/4cda9746-db0f-11e6-97d1-8856aa9704c0.png)

**Expected behavior**: 
These spells should be affected by Divine Favor.
**Steps to reproduce**:

1. play holy talents Paladin.
2. cast Davine Favor.
3. cast Holy Light or other spells.

**Client version**: 
1.12.1
**Commit hash**: 
f62c79e21f1011188daaff3d983bd6fe8d225376
**Database version**: 
z2693_01
**Operating system**: 
WIN10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
Thanks for the report. Evil copy-past was involved :smile:
Fixed https://github.com/cmangos/mangos-classic/commit/f103aa390406795fffabe198167845d8598311c8
