### ISSUE TITLE
[Classic] Event and Script probleme 

### ISSUE THREAD

**Issue by Xemuth** [cmangos/issues#1230]
**Current behavior**: 

For exemple : the lazy peon quest wont work because nothing happen when I use the  Foreman's Blackjack into one of this peon 
another exemple is : If I tp naxx as Gm and go to Saphiron lair the animation for apparition of saphiron will be played but he will never appear 
 
**Expected behavior**: 

ScriptDev2 script working

**Steps to reproduce**:

follow the https://github.com/cmangos/issues/wiki/Installation-Instructions for ubuntu 16.04

**Client version**: 
wow 1.12.1
**Commit hash**: 

f62c79e21f1011188daaff3d983bd6fe8d225376 

**Database version**: 
Classic-db Lunar Festival

**Operating system**: 
Ubuntu server 16.04

**Comment by Xemuth** [comment]
Ok I Finnaly find an fixing to this issue, http://cmangos.net/thread-7481.html  
To fix the mangos core have to be built into  /opt I guess

**Comment by cala** [comment]
Closing it then, thank you.
