### ISSUE TITLE
[CLASSIC] Crashing

### ISSUE THREAD

**Issue by gaosheng136** [cmangos/issues#1231]
Current behavior:

Expected behavior:

Steps to reproduce:

[Classic] 

 this is  some new crash log
[mangosd.exe_[21-1_19-49-14].txt](https://github.com/cmangos/issues/files/722851/mangosd.exe_.21-1_19-49-14.txt)
[mangosd.exe_[23-1_12-46-56].txt](https://github.com/cmangos/issues/files/722852/mangosd.exe_.23-1_12-46-56.txt)
[mangosd.exe_[23-1_13-32-34].txt](https://github.com/cmangos/issues/files/722853/mangosd.exe_.23-1_13-32-34.txt)

Client version:
1.12.3
Commit hash:
5d797e2ea448eec6c7ebefdfd93598a401005dfe
Database version:
z2693_01_mangos_gameobject_template.sql
Operating system:
win2008 r2

**Comment by cyberium** [comment]
Thank. I think i know where to look.
But are you able to reproduce it? What step do you use?

**Comment by gaosheng136** [comment]
"getFirst() " BUG     the crash  frequent occurrence

**Comment by gaosheng136** [comment]
some new crash log ,holp fix

**Comment by jimmybrancaccio** [comment]
@gaosheng136 Are you still experiencing issues with this? Can you provide the exact steps we can use to replicate this issue?

**Comment by jimmybrancaccio** [comment]
Closing this issue out. If anyone is still having a problem, please open a new issue with full details.
