### ISSUE TITLE
[Classic] VS2013 build error: cannot specify explicit initializer for arrays

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1233]
`uint32 chance[Sides] = {0};`

`error C2536: 'Die<SpellPartialResist,SPELL_PARTIAL_RESIST_NONE,4>::Die<SpellPartialResist,SPELL_PARTIAL_RESIST_NONE,4>::chance' : cannot specify explicit initializer for arrays (..\..\src\game\Unit.cpp)	mangos-classic\src\shared\Util.h	105`

I am guessing this only works in VS2015.

**Comment by gaosheng136** [comment]
me too

**Comment by Fabi** [comment]
stop using vs 2013

**Comment by cyberium** [comment]
@Fabi @Lillecarl  Till now vs2013 is still supported.
@Warlockbugs its a way to initialize an array? Maybe we could use something a bit more verbose that will be compatible with 2013?

**Comment by Fabi** [comment]
even if its supported: stop using vs 2013

**Comment by llloko** [comment]
Would be nice to hear something about that from Warlockbugs, too. 
Why drop vs 2013 support for one line of code? Sure, i can update to vs 2015, but i want to avoid that as long as possible.

**Comment by Warlockbugs** [comment]
This is a part of slightly bigger upcoming update.

**Comment by Warlockbugs** [comment]
Should be fixed.

**Comment by llloko** [comment]
it works! 1000 thanks 2 U & all CMaNGOS developers
