### ISSUE TITLE
[Classic] Brocade Bracers

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1235]
The item Brocade Bracers (3379) should have grey rarity I believe.

![brocade](https://cloud.githubusercontent.com/assets/18726138/21963265/05945614-db38-11e6-85a2-b46676a1cb0c.jpg)

**Comment by ulfgebhardt** [comment]
In the tbc-db it has the right quality. Did you delete your cache before testing?

![item 3379](https://cloud.githubusercontent.com/assets/1238238/22206889/409b5e88-e17d-11e6-85e4-378dded13ec9.png)

**Comment by katz1** [comment]
It was indeed a cache issue, thanks for pointing out.
