### ISSUE TITLE
[Classic] Nightlash (The Dead Fields quest)

### ISSUE THREAD

**Issue by wtfcolt** [cmangos/issues#1236]
**Current behavior**: 
Nightlash casts a spell to 'sacrifice' a gnoll to heal herself. This spell is being cast on the player sometimes, which is an instant kill. It does 1000 shadow damage.
**Expected behavior**: 
Nightlash should only target the gnolls, not a player, with this spell
**Steps to reproduce**:

1.  .go creature nightlash
2.  damage her until she casts her 'Spirit Heal' spell
3.  profit

**Client version**: 
1.12.1
**Commit hash**: 
2e439ab63f2d7c52c5b55ecf09fbef283eb0fb4a
**Database version**: 
Classic DB - https://github.com/cmangos/classic-db/commit/86703be17512406af8bfd60d1dbbd66822a78bcb
**Operating system**: 
Ubuntu Server 16.04 LTS

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Zooke** [comment]
https://github.com/cmangos/wotlk-db/issues/33
https://github.com/cmangos/issues/issues/775

This npc has been an issue for a long time.

**Comment by Rushor** [comment]
tc code currently

```sql
-- Nightlash SAI
SET @ENTRY := 1983;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,7000,9000,21000,25000,11,3485,0,0,0,0,0,2,0,0,0,0,0,0,0,"Nightlash - In Combat - Cast 'Wail of Nightlash'"),
(@ENTRY,0,1,0,74,0,100,1,0,30,0,0,11,3477,0,0,0,0,0,9,0,0,0,0,0,0,0,"Nightlash - On Friendly Between 0-30% Health - Cast 'Spirit Steal' (No Repeat)");
```

could you provide the spellid of 'sacrifice' ?

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/commit/e73b245e4c67abcb3b324bdb38db97ebc9246d1f

This fixes the issue. The sacrifice spell is Spirit Heal.

**Comment by cyberium** [comment]
Should be fixed thanks (try latest revision)

**Comment by cala** [comment]
Closed by final part: https://github.com/cmangos/classic-db/commit/85d8b21c637f26b78c19b50e5d0064ab72531ee5
