### ISSUE TITLE
[Classic] Pets Crashing Server Problem

### ISSUE THREAD

**Issue by Picas2** [cmangos/issues#1237]
**Current behavior**: 
I recently discovered a serious problem on my server. When I have a companion pet active and I run through the Darnassus portal to Rut'theran village the pet stays behind in Darnassus and then when I go to resummon the companion pet in Rut'theran village the server immediately crashes and I get mangosd.exe has stopped working. We tested this multiple times with multiple companion pets and it's always the same result. Additionally, we have the same problem when running onto a boat where the pet stays on the dock and when I resummon the pet on the boat the server crashes. The companion pet also cannot be summoned on a boat by itself. Instances and summoning players via the warlock summoning spell works fine unless the player is summoned from the warlock spell onto the boat where it will crash. We tested this on two different latest builds.

**Expected behavior**: 
Server not to fatally crash when pet is resummoned.

**Steps to reproduce**:

1. Summon any companion pet in Darnassus (Panda Cub, Crimson Snake, etc.)
2.  Run through portal to Rut'theran Village
3.  Resummon companion pet

**Client version**: 
World of Warcraft 1.12.1

**Commit hash**: 
Latest Classic

**Database version**: 
Latest Classic

**Operating system**: 
Windows Server 2012 R2

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

https://gist.github.com/Picas2/c644e403e061852292e87f1bca8557f7

**Comment by cyberium** [comment]
please provide crashlog
This is not reproducible for me.
Give us more detail. What class do you use? Hunter, warlock?

As i cannot reproduce that i will close this issue if no better infos to reproduce it are provided.

**Comment by Picas2** [comment]
I've used both a Warrior and a Druid and summoned the Panda Cub from the Panda Collar (item ID 13583) and the Crimson Snake. Summoning any companion pet is what is causing the issue not a Hunter/Warlock pet, I just got on to update that as I realize I wasn't fully clear the issue is with companion pets.

So steps to reproduce would be:

    Summon any companion pet in Darnassus (Such as crimson snake or panda cub)
    Run through portal to Rut'theran Village
    Resummon companion pet

Also you can reproduce the issue this way:

Summon any companion pet on the boat from Menethil Harbor to Darkshore

This is where I'm getting the fatal crash, I'm getting Event 1000 error in Windows Event Viewer, here's the details I got from event viewer https://gist.github.com/Picas2/1e2265da9b40b98ffb97f5a7e812d3ac

**Comment by Picas2** [comment]
Just want to report that the very latest build has resolved this issue, thank you
