### ISSUE TITLE
[CLASSIC] Warrior Doesn't Go Into Combat When Casting Bloodrage

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1239]
**Current behavior**: 
![image](https://cloud.githubusercontent.com/assets/12601614/21970321/19830ba4-dbe0-11e6-920d-ecd8ad094a3e.png)

**Expected behavior**: 
Warriors should into combat when they casted Bloodrage.
**Steps to reproduce**:

1. player a warrior
2. cast Bloodrage
3. warrior isn't considered in combat for the duration of Bloodrage.

**Client version**: 
1.12.1
**Commit hash**: 
fea8e7bd4be36b50f05eeadb33e6a5a74b88595d
**Database version**: 
z2693_01
**Operating system**: 
WIN 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by OriginsDev** [comment]
Hi I will look into this tommorow!
Thanks,
Drikish

**Comment by AnonXS** [comment]
```
Patch 2.3.0 (13-Nov-2007):

    Bloodrage should no longer initiate combat, though it will prevent rage decay for the duration.
    Warriors no longer remain in combat indefinitely if this ability is active while zoning.
```
true for vanilla

**Comment by Phatcat** [comment]
Problem still present on classic, warriors don't enter combat on using bloodrage while they should (at least for classic)
