### ISSUE TITLE
[TBC] The Script of the Old Hillsbrad Doesnt Work Correctly

### ISSUE THREAD

**Issue by Rapth** [cmangos/issues#1240]
**Current behavior**: just see the screenshot below, these mobs didint attack Thrall and can't be attacked by player.
![20170116162651](https://cloud.githubusercontent.com/assets/24927660/21976420/b3593010-dc0c-11e6-9466-679693644a74.jpg)

**Expected behavior**: 

**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 2.4.3

**Commit hash**: latest

**Database version**: 1.5.0

**Operating system**: windows 10 10586

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by jimmybrancaccio** [comment]
Hello,

Thank you for taking the time to submit this issue. Please resubmit it with the exact steps needed to replicate the issue.

Thanks,
