### ISSUE TITLE
[CLASSIC] Eyes of the Beast Has Two Problems

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1241]
**Current behavior**: 
1: Hunter casting Eye of the Beast lets pet to attack creatures , and creatures attack hunter instead of pet.
If hunter cancel the spell , creatures will attack the pet.
If the hunter died in the channel of the Eye of the Beast,  the pet will disappear forever or the pet's action bar will display wrong spell.
![image](https://cloud.githubusercontent.com/assets/12601614/22004765/595da14e-dc99-11e6-856e-f1655706f1cf.png)

2: If the pet is set to stay mode, cancel the Eye of the Beast will let the pet ignore this command and back to the hunter side. This means the Eye of the Beast can not let the pet stay in a location.
**Expected behavior**: 
Perhaps the root of both problems is not the Eye of the Beast spells dealing with. Maybe more complex issues. Please help hunters!!!
**Steps to reproduce**:

1. play a hunter 
2. cast Eye of Beast.
3. To do the above I said. You will find these problems.

**Client version**: 
1.12.1
**Commit hash**: 
f08bc37e35b7d822f495cb1822c24a0d150a20e5
**Database version**: 
z2693_01
**Operating system**: 
WIN10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by wowmui** [comment]
@Warlockbugs 
@killerwife
 any idea? Where should I check?

**Comment by codestothestars** [comment]
>  If the hunter died in the channel of the Eye of the Beast, the pet will disappear forever or the pet's action bar will display wrong spell.

It's hard to tell whether it's exactly the same issue, but something similar and odd happened to me, as well. I died after using Eyes of the Beast, and when I called my pet after resurrecting, it had reverted back to its default NPC name, clicking Pet Details did absolutely nothing, and its action bar was completely empty. I checked the `character_pet` table in the database and saw that, oddly, this pet's `id` had become `0`. I don't know what value it had originally, but I updated it to `1` and thankfully that resolved the issue!

Unfortunately I don't know any more about what actually went wrong. At some point I might try to find out more.

**Comment by Phatcat** [comment]
> 1: Hunter casting Eye of the Beast lets pet to attack creatures , and creatures attack hunter instead of pet.

This has been resolved, units correctly engage the possessed pet and not the player.

> If the hunter died in the channel of the Eye of the Beast, the pet will disappear forever or the pet's action bar will display wrong spell.

My pet did not disappear forever **but it had no action bar at all upon calling it back after ressing.**

> 2: If the pet is set to stay mode, cancel the Eye of the Beast will let the pet ignore this command and back to the hunter side. This means the Eye of the Beast can not let the pet stay in a location.

This part has been resolved. The pet will even run back to where you told it to stay before moving it in eyes of the beast after the duration expires/is cancelled.

**Comment by killerwife** [comment]
Closing this as there have been too many reworks inbetween of charms.
