### ISSUE TITLE
[Classic] lastest core crash (skill upgrade issues)

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1243]
**Current behavior**: 
[mangosd.exe_[17-1_15-10-7].txt](https://github.com/cmangos/issues/files/710285/mangosd.exe_.17-1_15-10-7.txt)
maybe the https://github.com/cmangos/mangos-classic/commit/3a3ee5d9aebac570adaf8e7ec1c395bc0002ef81 miss something.
**Expected behavior**: 

**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 
1.12.1
**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/3a3ee5d9aebac570adaf8e7ec1c395bc0002ef81
**Database version**: 
z2693_01
**Operating system**: 
WIN2008 R2

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by katz1** [comment]
I got this as well, it is related to [this](https://github.com/cmangos/mangos-classic/commit/3a3ee5d9aebac570adaf8e7ec1c395bc0002ef81) commit.
