### ISSUE TITLE
[CLASSIC] Rogue Talent Bug - Dirty Tricks Not Working

### ISSUE THREAD

**Issue by gaosheng136** [cmangos/issues#1246]
Ensure this is working properly in Classic builds:

https://wow.gamepedia.com/Dirty_Tricks_(old)

**Comment by Lillecarl** [comment]
http://db.hellground.net/?spell=14076
Dirty Tricks
Rank 1
Instant
Increases the range of your Blind and Sap abilities by 2 yards and reduces the energy cost of your Blind and Sap abilities by 25%.

**Comment by jimmybrancaccio** [comment]
@gaosheng136 Is this is still an issue with the latest commits?

**Comment by jimmybrancaccio** [comment]
@killerwife For the sake of making this issue have some value, I am going to adjust it so it focuses on ensuring Improved Sap (https://wow.gamepedia.com/Dirty_Tricks_(old)) is tested as working.

**Comment by killerwife** [comment]
Improved sap now works.
