### ISSUE TITLE
[Classic] Cluck! quest is always active

### ISSUE THREAD

**Issue by Gacnt** [cmangos/issues#1247]
**Current behavior**: 
All chickens that are in Goldshire are always acting as quest givers instead of critters, all you need to do is right click them and they will give you the **Cluck!** quest

Quest behaviour is defined here:
https://github.com/cmangos/mangos-classic/blob/master/src/scriptdev2/scripts/world/npcs_special.cpp#L69-L101

**Expected behavior**: 
Chickens should just act as any other critter, but upon spamming `/chicken` it will  randomly flag them as quest givers and you will be able to start the **Cluck!** quest, until then they should just be critters, kind of a hidden easter egg quest thing

**Steps to reproduce**:

1. Go to Goldshire
2. Look at any chicken 
3. 

**Client version**: 
1.12.1

**Commit hash**: 
Latest

**Database version**: 
Latest

**Operating system**: 
Windows

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
Closed, see https://github.com/cmangos/issues/issues/1251 for more infos.
