### ISSUE TITLE
[WOTLK] Summoned Creatures Despawn Time

### ISSUE THREAD

**Issue by Grz3s** [cmangos/issues#1248]
**Current behavior**: 
All summoned creatures (elite, normal etc) despawn ~10 secs after killed (no dif if we'll loot them or not)

**Expected behavior**: 
Summoned creatures should despawn in same way how static ones shold (corpse decay is in .config file)
Its huge problem specialy for Bosses or some main quest creatures (hard to kill) 
Examples:
Event with Urok DoomHowl in Blacrock Spire
I recorded ..avi ... to show another bug (not important now)
But u can see on it ... that all summoned creatures include Boss despawns quick :/
https://www.youtube.com/watch?v=NZ2InMD3wNY

**Steps to reproduce**:

1.  summon any creature using commands
2.  kill it
3.  Loot or not (will despawn ~10secs)

**Client version**: 
3.3.5 a

**Commit hash**: 
https://github.com/cmangos/mangos-wotlk/commit/dc25c9d2f4fd687543477ace36b41582aafd9f62

**Database version**: 
WotlkDB [734]

**Operating system**: 
Win7 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Darth-Postal** [comment]
This happens with static-spawned creatures too.

Easy way to reproduce:
1. Use `.npc add 17968` to spawn Archimonde somewhere.
2. Use `.damage 999999` to kill Archimonde.
3. Watch him despawn in 10 seconds, looted or not.

**Comment by cyberium** [comment]
its because there is not respawn delay for these invoked creature.
I need to find a correct policy for summoned/Invoked/ and other type of creature that are not normaly spawned by db. Its a bit obscure for me at this moment.

**Comment by xfurry** [comment]
> Event with Urok DoomHowl in Blacrock Spire

Another example is the first 2 bosses event in Halls of Reflection.

**Comment by AnonXS** [comment]
Fixed as per @Grz3s
