### ISSUE TITLE
[TBC] Alterac Valley Banners Only Usable Once Per Player

### ISSUE THREAD

**Issue by highrules** [cmangos/issues#1250]
The banners in AV battleground are only once useable for a player.
Means that when a player assaults a point and another retabs it, the player cant re-assault the point.
This happens on every assault point in alterac valley.
I tested it especially tested for the horde flag [entry: 178943].
The flags in template should be fine - also replaced them already with the ones in arathi basin [entry=180060].

However, if you relog and login again - you can use these banners one more time and the bug comes up again.

The code of SpawnBGObject should be fine - debugged it and it comes up with the right values.
If you click on this flag a spell 'opening', i guess its id is 3365 should be casted, which it will do the first time.
The second time you want to use that flag, neither a goUse nor a spellcast opcode is fired.

version: 2.4.3

Somebody fixed this already or have an idea how to fix it?

Greetings, Highrules

**Comment by robinsch** [comment]
Somehow it works if you teleport out of the map and back in. I tried to call client remove functions and force update of the go whenever it changes banner. Sadly that didn't work out.

**Comment by highrules** [comment]
I got a "wild" horde banner working if i remove the return after bg->EventPlayerClickedOnFlag(player, gameObjTarget); in Spell::EffectOpenLock.
So i assume that the battleground code isn't working as expected. I also tried every force update i have available. I guess the client thinks this gameObject is still in state GO_ACTIVE and so can not be opened.
But i'm questioning myself why is arathi basin even working

**Comment by robinsch** [comment]
No the state is correctly send, otherwise your client wouldn't show the icon while hovering over it. I don't even get to the point where something is called on go click. Nothing, not even a spell cast.

**Comment by highrules** [comment]
wanna go teamspeak? :D

**Comment by robinsch** [comment]
I can to the same result. Did you try to resend the gameobject query opcode. I did not try to spawn a new object, with new guid, did you tried that?

**Comment by highrules** [comment]
yeah that's what I meant with "wild" gameobject. When you remove the return after bg->EventPlayerClickedOnFlag(player, gameObjTarget); in Spell::EffectOpenLock and spawn a new one, it'll do fine.

**Comment by robinsch** [comment]
Spawning a new object with the same guid doesn't work. Using a new generated guid works fine, but that doesn't work out with the BG code.

**Comment by highrules** [comment]
We could search for the old guid in the list and replace it with the new guid but that'd pretty awfull

**Comment by robinsch** [comment]
I'm trying to implement a spawnId (just like dynamic guid implementation) that will handle the bg code and spawn them with a new guid. Should work according to my observations. Will report later.

**Comment by highrules** [comment]
Actually this would be blizzlike, new GOs had new guids in sniffs *hype*

**Comment by robinsch** [comment]
Okay, I basicly did just implement a stupid spawnId which is always the GUID. Then save those banners by SpawnId instead of guid in m_EventObjects. Also split m_EventObjects.gameobjects and banners, because you need to wipe the guidvector and don't want to search the old guid and delete it (because why?). Then spawn a new object and put it in the guidvector.

I'm just left with a visual that causes the old banner despawn a tiny bit delayed.

**Comment by highrules** [comment]
okay I did the "because why?" part but i replaced the guid with the ObjectGuid::Set method

**Comment by robinsch** [comment]
With my stupid code I need to make the old banner invisible -> setrespawntime and updateobjectvisibility is a bit delayed in my clients.

**Comment by highrules** [comment]
I guess world update is then more frequently than GameObject::Update function in your case, but I'm pretty sure your my code is worse.

**Comment by kelno** [comment]
I have the same bug in my own core implementation, I tried using cmangos to compare until I realized cmangos had the same bug.

I haven't resolved the issue but here are some notes and a video on how to reproduce:
https://github.com/ValorenWoW/sunstrider-core/issues/41

**Comment by kelno** [comment]
I have found the exact issue:
The client expects gameobject state to change after having clicked a button, it prevents clicking it until it has received that state change.
The flag does change state (from STATE_READY to STATE_ACTIVATED to STATE_READY again) but it does so while invisible to the player so this update is never sent to the client.
Sending the STATE_ACTIVATED update before destroying the object does fix this issue.

**Comment by BenDol** [comment]
@kelno did you want to submit a PR with the fixes? If not I can port it over as a PR. Up to you.
