### ISSUE TITLE
[TBC]repeat login cause issues

### ISSUE THREAD

**Issue by Rapth** [cmangos/issues#1252]
**Current behavior**: 
When you login a account that is already logged in ,may cause some issues:
1.lost everything in  inventory 
2.character can't be saved
3.character still shows online when logged out until server restart.

**Expected behavior**: 

**Steps to reproduce**:

1. just double login a account
2. 
3. 

**Client version**: 2.4.3

**Commit hash**: latest

**Database version**: 1.5.0

**Operating system**: win10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
Duplicating: https://github.com/cmangos/issues/issues/1177

**Comment by Lillecarl** [comment]
Duplicate of #1177 closing this and keeping original open.
