### ISSUE TITLE
[Classic] Core update z2694 not applying, server won't start.

### ISSUE THREAD

**Issue by BareRose** [cmangos/issues#1254]
Using newest classic-db and mangos-classic, attempting to start mangosd.exe results in error:

```
2017-01-26 03:15:49 ERROR:SQL: SELECT required_z2694_01_characters_instance FROM character_db_version LIMIT 1
2017-01-26 03:15:49 ERROR:query ERROR: Unknown column 'required_z2694_01_characters_instance' in 'field list'
2017-01-26 03:15:49 ERROR:The table `character_db_version` in your [CHARACTER] database indicates that this database is out of date!
2017-01-26 03:15:49 ERROR:
2017-01-26 03:15:49 ERROR:  [A] You have: --> `z2686_01_characters_reset_talents.sql`
2017-01-26 03:15:49 ERROR:
2017-01-26 03:15:49 ERROR:  [B] You need: --> `z2694_01_characters_instance.sql`
2017-01-26 03:15:49 ERROR:
2017-01-26 03:15:49 ERROR:You must apply all updates after [A] to [B] to use mangos with this database.
```

Weirdly, InstallFullDB.sh outputs this:

```
> Trying to apply additional core updates from path C:/Mangos/mangos ...
    Appending core update z2694_01_mangos_instance_encounters.sql to database mangos
  CORE UPDATE PROCESSED: 1
  CORE UPDATE FOUND BUT ALREADY IN DB: 13
```

Meaning that the update's name is `z2694_01_mangos_instance_encounters.sql`, yet mangosd.exe expects `z2694_01_characters_instance.sql` for some reason. Clearly something went wrong with the updates.

Using Windows 7 64bit, newest cmangos-classic (hash: cebd61b3211aa5c42d49002f744992f30dbf4bb6), newest classic-db (hash: 5d6c7cd5bff533abb3245ce93bd32f532c5714f3).

**Comment by Lillecarl** [comment]
https://github.com/cmangos/mangos-classic/blob/master/sql/updates/characters/z2694_01_characters_instance.sql

You need to apply the character database update on the character database too.

**Comment by BareRose** [comment]
Why is InstallFullDB.sh not doing that then? Or is there a reason character db updates have to be done manually?

**Comment by Lillecarl** [comment]
AFAIK it only does world db?

On Thu, Jan 26, 2017, 10:39 BareRose <notifications@github.com> wrote:

Why is InstallFullDB.sh not doing that then? Or is there a reason character
db updates have to be done manually?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/cmangos/issues/issues/1254#issuecomment-275345547>, or mute
the thread

**Comment by BareRose** [comment]
Nah the config lets you specify a core path so it can grab core updates from sql/updates there. Since character db updates are in there one would expect them to be applied too, but the script only does sql/updates/mangos. IMO this should either be changed or clarified in the config (add a note that it only grabs sql/updates/mangos).

**Comment by cyberium** [comment]
The InstallFullDB.sh script is not supposed to handle character db. That db could be anywere in your server or in another one with another user credential. So handling it in the script require adding a bunch of code.
The main reason for me is its DB provider script. So db devs should not care about other db than world db.

**Comment by BareRose** [comment]
That's fair enough. Making that more clear in the config or script itself would be good though. Or re-working the way the db installing works, think having a script for each DB (the one for mangos db would be what InstallFullDB is now) and an additional script that asks the user which ones to apply (for convenience) too.

This would also pave the way for other convenience scripts to be added in the future, e.g. one to create the dbs from scratch (to make initial setup easier).

**Comment by Lillecarl** [comment]
Help us rewrite the wiki better then.

**Comment by BareRose** [comment]
Not sure how this relates to the wiki, but if I find the time I might go ahead and re-work the db scripts and make a PR. We'll see.
