### ISSUE TITLE
[TBC][WOTLK] Paladin Auras UI Display Issue

### ISSUE THREAD

**Issue by natiewow** [cmangos/issues#1256]
**Current behavior**: 
Auras from all Paladins in a group show as selected on the aura bar.

![auras-cmangos](https://cloud.githubusercontent.com/assets/23014480/22339250/9fdad8ec-e3e9-11e6-8cee-c956fb35502c.jpg)

**Expected behavior**:
Only Paladin's own aura should be selected.

![auras-retail](https://cloud.githubusercontent.com/assets/23014480/22339258/a5225488-e3e9-11e6-81ec-66d922dbf56e.jpg)

**Client version**: 
Tested 2.4.3, 3.3.5a

**Commit hash**: 
https://github.com/cmangos/mangos-wotlk/commit/8794ef0920e52d59cfa0c2e9466a2fd2d8f52f76
https://github.com/cmangos/mangos-tbc/commit/893fc6074e6f678390ff2f405e31978e96bff470

**Database version**: 
https://github.com/cmangos/wotlk-db/commit/5536be83ece6a9b85765e556fcfe8d2ce61b19a7
https://github.com/cmangos/tbc-db/commit/5050660126c9f8336a8667ea402382a07eb77175

**Comment by al3xc1985** [comment]
working perfect,, @killerwife  close
