### ISSUE TITLE
classis characters sql some bug

### ISSUE THREAD

**Issue by gaosheng136** [cmangos/issues#1257]
**Current behavior**: 

**Expected behavior**: 

**Steps to reproduce**:
Sql Has been updated to the latest
but server log:
2017-01-28 20:41:10 ERROR:SQL: INSERT INTO instance VALUES ('70', '533', '0', '0',, '')
2017-01-28 20:41:10 ERROR:SQL ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' '')' at line 1

 and the new characters base lose :
ALTER TABLE instance ADD COLUMN `encountersMask` int(10) unsigned NOT NULL DEFAULT '0' AFTER resettime;
**Client version**: 
1.123
**Commit hash**: 
cebd61b3211aa5c42d49002f744992f30dbf4bb6
**Database version**: 
z2694_01_characters_instance
**Operating system**:

**Comment by wowmui** [comment]
CMaNGOS-Classic\src\game\MapPersistentStateMgr.cpp
In line 261 
`    CharacterDatabase.PExecute("INSERT INTO instance VALUES ('%u', '%u', '" UI64FMTD "', '%u',, '%s')", GetInstanceId(), GetMapId(), (uint64)GetResetTimeForDB(), GetCompletedEncountersMask(), data.c_str());
`
change to 
`    CharacterDatabase.PExecute("INSERT INTO instance VALUES ('%u', '%u', '" UI64FMTD "', '%u', '%s')", GetInstanceId(), GetMapId(), (uint64)GetResetTimeForDB(), GetCompletedEncountersMask(), data.c_str());
`

**Comment by cyberium** [comment]
Fixed
