### ISSUE TITLE
[CLASSIC][TBC][WOTLK] Issues with Attacking Possessed Units

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1258]
**Current behavior**: 
Creature can't attack possessed unit.
**Expected behavior**: 
Creature should attack possessed units normally.
**Steps to reproduce**:

1. Use possessed spell (1002 Eyes of the Beast, 126 Eye of Kilrogg, 19832 (Orb of Domination Possess), etc.)
2. Creature can't attack Unit effected by possessed spell.
3. Cancel spell , and creature attack again.

**Client version**: 
any cmangos core have these issues.
**Commit hash**: 
Lastest
**Database version**: 
Lastest
**Operating system**: 
Win 2008R2

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by wowmui** [comment]
In older core these won't happen. Maybe PossessedAI or Unit::TakePossessOf() and Unit::ResetControlState() have something wrong or missed?

**Comment by cyberium** [comment]
@Warlockbugs i just tried "eyes of the beast"(2899) it seem to work but the attacked target select the hunter as hostile target instead of the pet. Maybe related to some of your latest changes.

**Comment by Warlockbugs** [comment]
I am reworking all relations APIs (including hostility). Smaller APIs it depends on are making it into the core right now, so i can't guarantee it being 100% free of minor transitional quirks. What we have right now will be ultimately scrapped and replaced with appropriate reverse engineered stuff for each version.

**Comment by al3xc1985** [comment]
@killerwife i believe this can be closed
