### ISSUE TITLE
sometime crash 

### ISSUE THREAD

**Issue by wowmui** [cmangos/issues#1259]
**Current behavior**: 
[mangosd.exe_[20-1_22-32-2].txt](https://github.com/cmangos/issues/files/736899/mangosd.exe_.20-1_22-32-2.txt)
[mangosd.exe_[28-1_15-9-21].txt](https://github.com/cmangos/issues/files/736900/mangosd.exe_.28-1_15-9-21.txt)
Maybe the lastest commits miss something?
I have no idea with these logs. Please,thanks.
**Expected behavior**: 

**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 
1.12.3
**Commit hash**: 
cebd61b3211aa5c42d49002f744992f30dbf4bb6
**Database version**: 
5d6c7cd5bff533abb3245ce93bd32f532c5714f3
**Operating system**: 
WIN 2008 r2

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by gaosheng136** [comment]
These two crash mee too, holp fix

**Comment by wowmui** [comment]
You mean "hope". :)

**Comment by cyberium** [comment]
What would realy help is a step to reproduce.
I know how to fix the crash but i need first to see if there is no better way to fix it.

**Comment by wowmui** [comment]
@cyberium I'm sorry. I really do not know which specific action caused the crash. I will research more. :)
But could you point out what could have caused these crashes? Thank you for your reply.

**Comment by cyberium** [comment]
duplicate https://github.com/cmangos/issues/issues/1231
