### ISSUE TITLE
Acid Events 23 & 27

### ISSUE THREAD

**Issue by Grz3s** [cmangos/issues#1260]
**Current behavior**: 
23   EVENT_T_AURA
27   EVENT_T_MISSING_AURA
Both works only in combat
Theyre used already in scripts when some casters loosing theirs (Frost, fire, shadow armor - spells)...
And its not natural that they can reapply that aura only on combat??

```quote
Note:
I understand that events:
24   EVENT_T_TARGET_BUFFED
28   EVENT_T_TARGET_MISSING_AURA 
ReQ combat to work:
```

**Expected behavior**: 
Both events should work "**IN"** and "**OUT of combat**" 

**Steps to reproduce**:
Easy to create any *test* EAI... 
example:
```sql
Delete from `creature_ai_scripts` where `creature_id`= 2319;
Insert into `creature_ai_scripts` values
('231901','2319','11','0','100','0','0','0','0','0','11','12544','0','1','0','0','0','0','0','0','0','0','Syndicate Wizard - Cast Frost Armor on Spawn'),
('231902','2319','27','0','100','1','12544','1','5000','5000','11','12544','0','1','0','0','0','0','0','0','0','0','Syndicate Wizard - Cast Frost Armor on Missing Buff');
UPDATE creature_template SET AIName = 'EventAI' WHERE `entry` = '2319'; 
```
```quote
.npc add 2319    -- npc will spawn with aura applied
.unaura 12544    --  should cast that aura after max 5secs (wont work :) )

now.
do the same in combat with that npc.
.unaura 12544 ... and u'll see that aura will be applied again.
```

Thanks

**Client version**: 
3.3.5a

**Commit hash**: 
https://github.com/cmangos/mangos-wotlk/commit/8794ef0920e52d59cfa0c2e9466a2fd2d8f52f76

**Database version**: 
WoTLKDB

**Operating system**: 
win7

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cyberium** [comment]
Fixed
