### ISSUE TITLE
[CLASSIC] Nimboya Dialogue Missing

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1261]
The dialogue of NPC Nimboya is missing:

![nimboya](https://cloud.githubusercontent.com/assets/18726138/22402512/0570b886-e5fa-11e6-895c-54b98b0a68b9.jpg)

**Comment by Grz3s** [comment]
DB issue 

I've both nimboyas and Kin'weelays texts
but gossip id and text id are missing :/ (need someone with sniff)
Cataclysm changed them (so must 3.3.5a latest)

```sql
-- Kin'weelay
-- missing gossip id and missing text
-- from vid
'Hello! The spirits say you here to aid my chief. Say it loud, they do.'


-- Nimboya
-- missing gossip id and missing text
-- from vid
'Eh? You have business with Nimboya?'
```
