### ISSUE TITLE
[Classic] Ghost-o-plasm Round Up

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1262]
The quest Ghost-o-plasm Round Up does not seem to be working.
You can place the Crate of Ghost Magnets in the described location, but no ghosts are appearing to catch.

![ghost](https://cloud.githubusercontent.com/assets/18726138/22402537/30c590f0-e5fb-11e6-8dd7-cc3a3d3d1ab9.jpg)

**Comment by evil-at-wow** [comment]
This is currently a work in progress, see cmangos/classic-db#21 and the resulting TBC pull request cmangos/mangos-tbc#166.
