### ISSUE TITLE
[Classic] Portals of the Legion

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1263]
In the quest Portals of the Legion, you can keep using the Hand of Iruxos on the same Demon Portal to spawn Demon Portal Guardians to complete the quest quickly in one place.
I am not sure how this should work, maybe the Demon Portal object should despawn after slaying the guardian?

![portals](https://cloud.githubusercontent.com/assets/18726138/22402566/e889a21c-e5fb-11e6-9053-0446066f1169.jpg)

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/3c1ef7353dbbd9a4c84f5aadbcdd4ef5f5b7eedf thank you for your report.
