### ISSUE TITLE
[CLASSIC] Arathi Charms Not Working

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1265]
In the Arathi Highlands the various elementals can drop 'charm' items:
Burning Charm (4479)
Thundering Charm (4480)
Cresting Charm (4481)

As shown in their description, these can be used to banish an elemental of a certain kind. You can use the items on the described target, but nothing happens after casting.
I am not sure how this banishing should work, I assume you should not get xp / loot from the elemental after banishing it, but this has to be confirmed.

**Comment by Darth-Postal** [comment]
> I am not sure how this banishing should work, I assume you should not get xp / loot from the elemental after banishing it, but this has to be confirmed.

It seems it should insta-kill the elemental and give XP/Loot, but only if you hit it with normal attack/spell first. [Source](http://www.wowhead.com/item=4479/burning-charm#comments:id=124554)

**Comment by Warlockbugs** [comment]
These spells are dummy effects and require manual scripting.

Spell Id | Name
------------ | -------------
4130 | Banish Burning Exile
4131 | Banish Cresting Exile
4132 | Banish Thundering Exile
