### ISSUE TITLE
[CLASSIC] Bugs with Passive Pet Spells - Talent SPELL ID 20576 and 19619

### ISSUE THREAD

**Issue by gaosheng136** [cmangos/issues#1267]
Current behavior:

Expected behavior:

Steps to reproduce:
Repeated taming pet ，Players can damage unlimited increase,and WARLOCK PET Talent SPELL
Client version:
1.123
Commit hash:
ebd61b3211aa5c42d49002f744992f30dbf4bb6
Database version:
z2694_01_characters_instance
Operating system:

**Comment by wowmui** [comment]
I can confirm this serious bug!

**Comment by wowmui** [comment]
Only exists in the cmangos-classic
![image](https://cloud.githubusercontent.com/assets/12601614/22456199/feff49a8-e7cb-11e6-9e78-ee054243b5bc.png)
![image](https://cloud.githubusercontent.com/assets/12601614/22456262/5da86e08-e7cc-11e6-8b97-53b7fe44761e.png)

Steps to reproduce:
1: Play hunter 
2: learn Unleashed Fury
3: Cast Tame Beast, abandon pet 
4: Increase hunter's damage 
This is STACKABLE!!

**Comment by killerwife** [comment]
Seems to be resolved after skill rework
