### ISSUE TITLE
[WOTLK] DoTs are not supposed to be calculated as binary spells at apply.

### ISSUE THREAD

**Issue by Ramonoo** [cmangos/issues#1269]
**Current behavior**: 
Applying a dot is calculated as binary

**Expected behavior**: 
Applying a dot should not be calculated as a binary.

**Steps to reproduce**:

1. Breakpoint IsBinarySpell
2. Cast a Dot
3. Observe the return value of the function )

**Client version**: 
3.3.5a

**Commit hash**: 
[f12571ce7f8e40ac9ace45783964ab5ba1c33c4a](https://github.com/cmangos/mangos-wotlk/blob/master/src/game/SpellMgr.h#L369)

**Database version**: 
N/A

**Operating system**: 
N/A

I dont have any definitive proof apart from my own knowledge. The best i could find is here:
http://wowwiki.wikia.com/wiki/Binary_Spell
"DoTs used to be binary spells, but this was changed."

I have no idea about spells like holy fire which both have a dot effect and a damage effect. I could not find any documentation on this.

**Comment by Warlockbugs** [comment]
From [this](https://web.archive.org/web/20161015101615/https://dwarfpriest.wordpress.com/2008/01/07/spell-hit-spell-penetration-and-resistances/) source:
> DoTs like Vampiric Touch and Shadow Word: Pain are binary in their initial cast, but each damage tick can fall victim to resists just as a non-binary spell.

The line you refer to [was already present](http://wowwiki.wikia.com/wiki/Binary_spell?oldid=1432574) at the time this post was written and meant for ticks, not initial casts.

Holy Fire is non-binary.

**Comment by Ramonoo** [comment]
Your source is clearly a source from TBC times. My beliefs are that this changed during WOTLK.

**Comment by Warlockbugs** [comment]
I suppose, this settles it for now.
