### ISSUE TITLE
Quest Bijou's Belongings [4982/5001]

### ISSUE THREAD

**Issue by MantisLord** [cmangos/issues#1270]
Two problems with this quest in current WotLK-DB and TBC-DB:

1. http://www.wowhead.com/quest=4982 should be Horde only
http://www.wowhead.com/quest=5001 should be Alliance only
Suggested fix:
```
UPDATE quest_template SET RequiredRaces = 690 WHERE entry = 4982;
UPDATE quest_template SET RequiredRaces = 1101 WHERE entry = 5001; 
```
2. Missing some object spawns and pooling added with https://github.com/cmangos/classic-db/commit/6737ca8dfe5d5c7107abfc5113071d994dbdf12b

**Comment by Grz3s** [comment]
nice :+1:
