### ISSUE TITLE
[TBC] [WotLK] [ACID] Amani Berserker (15643) uses wrong spell

### ISSUE THREAD

**Issue by MantisLord** [cmangos/issues#1271]
Creature currently uses http://www.wowhead.com/spell=8269/frenzy - increases attack speed by 60%.

It appears the correct spell is actually http://www.wowhead.com/spell=8599/enrage - increases attack speed by 30% and damage by 10%.

Evidence:
http://www.wowhead.com/spell=8599/enrage#used-by-npc
http://www.wowhead.com/npc=15643/amani-berserker#comments:id=196890

Suggested fix:
Change spell ID to 8599 for creature 15643 in ACID for WotLK-DB and TBC-DB.

**Comment by Grz3s** [comment]
yes you're right here
![spell](https://cloud.githubusercontent.com/assets/2374069/22486685/68674a04-e802-11e6-8aa2-fffc2a0b4019.jpg)
