### ISSUE TITLE
[Classic] [TBC] [WotLK] [ACID] Boiling and Scalding Elemental fixes

### ISSUE THREAD

**Issue by MantisLord** [cmangos/issues#1272]
Scalding Elemental (10756) should cast spell Scald (17276)
Boiling Elemental (10757) should cast spell Steam Jet (11983)

Both creatures seem to move too fast currently and should be immune to all frost damage: 
http://www.wowhead.com/npc=10756/scalding-elemental#comments:id=123893
http://www.wowhead.com/npc=10757/boiling-elemental#comments:id=32933

Suggested fix:
SpeedRun is from TDB
`UPDATE creature_template SET SchoolImmuneMask = 16, SpeedRun = 0.85714 WHERE entry IN (10756,10757);`

Add ACID for spells - Is there any way to determine correct timings? Or should the values just be guessed?

Edit:
I see we have another NPC who casts Steam Jet already...
`-- Dark Iron Steamsmith
('584001','5840','9','0','100','1','0','5','12000','15000','11','11983','0','1','0','0','0','0','0','0','0','0','Dark Iron Steamsmith - Cast Steam Jet'),`
So maybe same timings could be used for Boiling Elemental.

**Comment by cala** [comment]
Thanks. Closed by https://github.com/cmangos/classic-db/commit/6815566082a0d5ecaefc038ffa0aed01eea8723e
