### ISSUE TITLE
[CLASSIC] Overlord Mok'Morokk Displayed HP

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1273]
In the quest Challenge Overlord Mok'Morokk (1173) you have to fight Overlord Mok'Morokk (4500), who is initially friendly then turns hostile. His stats seems to be correct, but his displayed HP is around 1% when the battle starts.

The issue reminds me very much of this: https://github.com/classicdb/database/issues/847 (which @cyberium already solved)

**Comment by killerwife** [comment]
this should be resolved as of now
