### ISSUE TITLE
[CLASSIC] Sapphiron Icebolt

### ISSUE THREAD

**Issue by terassiel** [cmangos/issues#1274]
**Current behavior**: 
After entering Phase 2 Sapphiron(15989) just bounces up and down untill casting Frost Breath (28524), killing everybody.
**Expected behavior**: 
After entering Phase 2 Sapphiron should cast Ice Bolt(28526, triggering 28522) on random targets turning them into LOS breaking iceblocks (needed to survive the Frost Breath).
**Steps to reproduce**:
Just start the encounter and wait till Phase 2 

**Client version**: 
1.12.1

**Comment by al3xc1985** [comment]
@killerwife this can be closed... 100% scripted in core

**Comment by cala** [comment]
Ah yes. I was unaware of this issue or I would have closed it when reworking Sapphiron
