### ISSUE TITLE
[WotLK] Realmd Fails at loading Dungeon Encounters.

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#1277]
**Current behavior**: Realmd starts with error

**Expected behavior**: Realmd start without error

**Steps to reproduce**:

1. sh ./realmd.sh
2. 
3. 

**Client version**: 3.3.5

**Commit hash**: CMaNGOS/0.18 (2017-02-05 09:16:14 - f0d9535b58a5c7b73b5ba9d25a5e7e772ccd3c3f)

**Database version**: required_12951_01_mangos_item_template 

**Operating system**: Ubuntu 14.04 Server

CMaNGOS/0.18 (2017-02-05 09:16:14 - f0d9535b58a5c7b73b5ba9d25a5e7e772ccd3c3f)

When i start 'realmd' th get the following error.

2017-02-05 09:30:43 Loading Dungeon Encounters...
2017-02-05 09:30:43 ERROR:SQL: SELECT MAX(id) FROM instance_dungeon_encounters
2017-02-05 09:30:43 ERROR:query ERROR: Table 'mangos.instance_dungeon_encounters' doesn't exist
2017-02-05 09:30:43 ERROR:Error loading instance_dungeon_encounters table (not exist?)

It is true that i do not have a table called "instance_dungeon_encounters", but i have have a table called "instance_encounters". Was the table miss referenced?

**Comment by adellaci** [comment]
I've searched through all of the queries for that database mangos and can not find a statement that creates 'instance_dungeon_encounters'. Have i missed a step?

**Comment by Grz3s** [comment]
adellaci...
https://github.com/cmangos/mangos-wotlk/commit/284526e629e82888e5b184cf5f7b0657f348b1a6

Now pls look at YourSources\..\sql\base\dbc\original_data
DungeonEncounter.sql  is there

Now:
If your InstallFullDB.config is set correctly Here:
```sql
## Define the path to your core's folder (This is optional) -- ****MUST BE SET****
##   If set the core updates located under sql/updates from this mangos-directory will be added automatically
CORE_PATH=" xxxx "  -- here
```
This file and spell_template will be loaded correctly..

**Comment by jimmybrancaccio** [comment]
@Grz3s Thanks for the helpful comment. I've run into this issue too, however I do have `CORE_PATH` set. My install is in `/home/mangos/mangos` so it should be using the path `/home/mangos/mangos/sql/updates/mangos` correct?

I did run the database tool twice because I was having another issue (which it didn't correct, had to manually import a mangos DB update file and a character DB update file).

Any other ideas? Thanks! 😄

**Comment by Grz3s** [comment]
from wiki:
```quote
With the default configuration, you only need to change CORE_PATH to:

CORE_PATH="/c/Mangos/mangos"
(for *nix /home/mangos/mangos)

* You may actually have to set  CORE_PATH="../mangos"  (assuming default paths from this guide), if the tilde is not properly resolved into your home folder path, causing InstallFullDB.sh to complain about not finding "/home/mangos/mangos". Tested on openSUSE 12.3.
```

So for example ...
I'm on win7
and this is mine:
```code
CORE_PATH="E:\WOWSERV\CmangoS\mango\mangos-wotlk"

**Comment by jimmybrancaccio** [comment]
@Grz3s So, I just noticed that parameter seems to indicate it's going to load the SQL updates from `sql/updates` but not necessary from `sql/base/dbc/original_data`. I did however adjust my path to be `../mangos`. Didn't see any noticeable difference upon running the InstallFullDB.sh script, and the realm still complains about the missing `instance_dungeon_encounters` table. 😢

**Comment by Grz3s** [comment]
are you running correct InstallFullDB.sh?? from here:
https://github.com/cmangos/wotlk-db/blob/master/InstallFullDB.sh

This part takes care of your missing file:
```code
# Apply dbc folder
  echo "> Trying to apply $CORE_PATH/sql/base/dbc/original_data ..."
  for f in "$CORE_PATH/sql/base/dbc/original_data/"*.sql
  do
    echo "    Appending DBC file update `basename $f` to database $DATABASE"
    $MYSQL_COMMAND < $f
    if [[ $? != 0 ]]
    then
      echo "ERROR: cannot apply $f"
      exit 1
    fi
  done
  echo "  DBC datas successfully applied"
  echo
  echo
  # Apply dbc changes (specific fixes to known wrong/missing data)
  echo "> Trying to apply $CORE_PATH/sql/base/dbc/cmangos_fixes ..."
  for f in "$CORE_PATH/sql/base/dbc/cmangos_fixes/"*.sql
  do
    echo "    Appending CMaNGOS DBC file fixes `basename $f` to database $DATABASE"
    $MYSQL_COMMAND < $f
    if [[ $? != 0 ]]
    then
      echo "ERROR: cannot apply $f"
      exit 1
    fi
  done
  echo "  DBC changes successfully applied"
  echo
  echo
```

**Comment by jimmybrancaccio** [comment]
@Grz3s Something funky must have happened, or the repository schema naming has changed since I last did an update. I had a Database folder which apparently is now for Cata. Downloaded the new WoTLK DB tool, and that seems to have done the trick. For whatever reason it didn't like using my 'mangos' MySQL user and I had to resort to using root (which I really hate, but it worked). 👍

Thanks for the halpz!

**Comment by adellaci** [comment]
Thank you all for the info. It works now. I do not use the "InstallFullDB" when I'm doing updates, i handle it manually. I do when I'm a starting from scratch. Other then that i just process everything that is in the "update" folder and "scriptdev2". So my bad. I'll pay closer attention to other folders that my change outside of core applications. I guess it is time to wipe the server and start from scratch so i can edit the installation instructions that i wrote.

Again thank you for pointing the change out to me.

**Comment by regneq** [comment]
heh,  I was using manual update and ran across this issue as well.  Little did I know about the changes here and I ended up wiping my character.  Oh well,  some of us don't use the automated update via scripting.
