### ISSUE TITLE
Core crash on vmaps loading

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1279]
**Current behavior**: 
When loading vmaps/Lochmodanwoodfence02.m2.vmo the server crashes (Classic core). Crash log can be found [here](http://pastebin.com/zj0ryxnE).

**Expected behavior**: 
Should not crash. ;-)

**Steps to reproduce**:

1.  Load a character with GM privileges
2. `.tele stonewrou`
3. Be disconnected because mangosd.exe crashed

**Client version**: 
1.12.1

**Commit hash**: 
https://github.com/cmangos/mangos-classic/commits/master

**Database version**: 
https://github.com/cmangos/classic-db/commit/b92deed2b84ced4197afd631f160479717c09150

**Operating system**: 
Mac OS X 10.6

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
As an update the error was caused by the strangely missing file: `Lochmodanwoodfence02.m2.vmo` causing a crash when the server tried to load it. Readding the file fixed the crash (thanks @cyberium )
However, I think that the core should notify an error in the case of a missing *map file instead of crashing.
Thus, I'm letting this issue open for now.

**Comment by cyberium** [comment]
Not reproducible
