### ISSUE TITLE
WOTLK some blue "!" become yellow

### ISSUE THREAD

**Issue by rmzV** [cmangos/issues#1281]
came from here
https://github.com/cmangos/wotlk-db/issues/75
this isues cant be fixed in core
atleast 
this 2 quest givers,
alterac valley repitable onces
and
10110. hellfire fortification. (horde side , dunno about ally) affected

i am on latest build as for today 09.02.2017

**Comment by jimmybrancaccio** [comment]
Hello, thank you for taking the time to submit these issues. Please resubmit them if you're still having issues with them utilizing the bug reporting template (shown when you open a new issue).
