### ISSUE TITLE
WOTLK City of light

### ISSUE THREAD

**Issue by rmzV** [cmangos/issues#1282]
I am on BE char and still cant complete this quest
servant just not talking anything and after ending 1 row starting another
some screenshots in attachement

latest core and db as of
09.02.2017
![1](https://cloud.githubusercontent.com/assets/22476199/22773464/5891bd0a-eeb3-11e6-959e-dce3ece3dcfc.jpg)
![2](https://cloud.githubusercontent.com/assets/22476199/22773465/58bd695a-eeb3-11e6-9d0e-efd6bee4bd9b.jpg)

**Comment by Darth-Postal** [comment]
This was already reported here: https://github.com/cmangos/issues/issues/1218

**Comment by jimmybrancaccio** [comment]
Closing this as a duplicate of #1218.
