### ISSUE TITLE
[TBC]Restarter not working.

### ISSUE THREAD

**Issue by DanielBallaSZTE** [cmangos/issues#1283]
run-mangosd is not restarting the core sometimes.

https://github.com/cmangos/issues/issues/1084

There was a discussion of this before, the problem still is like that. 
As soon as you type in input, the restarter continues. Seems like the server can't shutdown properly.

**Comment by DanielBallaSZTE** [comment]
up

**Comment by DanielBallaSZTE** [comment]
Up, still not working. 
The fix didn't work.

**Comment by ulfgebhardt** [comment]
Apply this PR https://github.com/cmangos/mangos-tbc/pull/179 and check again pls. This should solve the Problem
