### ISSUE TITLE
Classic - Flasks Stacking

### ISSUE THREAD

**Issue by dazidkk** [cmangos/issues#1287]
Issue:
Flasks stack  which they're not supposed to do.

http://db.vanillagaming.org/?item=13506
http://db.vanillagaming.org/?item=13510
http://db.vanillagaming.org/?item=13511
http://db.vanillagaming.org/?item=13512
http://db.vanillagaming.org/?item=13513

**Comment by Warlockbugs** [comment]
This is because [spell_elixir table](https://github.com/cmangos/mangos-classic/blob/master/sql/base/mangos.sql#L11834) is a straight backport from a newer version and misses them. In general, classic core tables like this are in decline compared to other branches. The same applies to your question about scaling.

**Comment by Warlockbugs** [comment]
Update: it's in there, but the table needs a heavy cleanup anyway, and functionality in the core side needs a re-check.

**Comment by Warlockbugs** [comment]
Found some issues: Chromatic Resistance flask is missing from the list, and Petrification has the same attribute as Food Buffs, which causes it to be detected as a food buff and stack with flasks (we have a limitation of one specific per spell). Consumables definitely need a bit of a rework.

**Comment by dazidkk** [comment]
If i remember correctly https://github.com/cmangos/mangos-classic/pull/139/commits/31090dfac823725454de1778e28caa66c38c63dd used to fix the stacking issue for the older revisions.

But seems to be in a conflict with https://github.com/cmangos/mangos-classic/commit/77b79313f253edf953bcb950f8c391f4d3980b37 regarding the newer revisions.

**Comment by Warlockbugs** [comment]
It absolutely is in conflict. This is also a bad idea to break forward compatibility with other branches by redefining existing mask values like this patch does. Zanza needs it's own new elixir category in all cores, ZG didn't go anywhere.

In fact, we could probably extend existing elixir table into full-blown unified spell specifics table for all cores and de-hardcode existing specifics. This will also eliminate the need for code alterations we use to categorize spells between expansions, as well as improve performance by using static lookup. I don't think we have any dynamic categories, everything is static anyway. A single 64-bit mask is probably enough to contain all spell specifics and categories in the game across expansions.

**Comment by cyberium** [comment]
poke @Warlockbugs

**Comment by Warlockbugs** [comment]
The particular issue itself was fixed, i think (?).

**Comment by cala** [comment]
It is, I closed the DB issue but forgot to close this one also.

**Comment by cala** [comment]
And I even managed to forgot to close it two times in a row. -_-"

**Comment by Tobschinski** [comment]
you get one more chance

**Comment by cala** [comment]
Yeah!
