### ISSUE TITLE
[CLASSIC] Reckoning Trigger Spell Broken

### ISSUE THREAD

**Issue by dazidkk** [cmangos/issues#1288]
Issue: 
At the moment Reckoning is completely broken. 
In the earlier revisions, we had the issue where Reckoning would trigger, but it wouldnt stack up more than 1. 
But as it goes for now, it wont even trigger once nor stack, so you can guess that its probaly one of the newer commits, which is causing the trigger issue.

Other Stuff to take into consideration:
The Paladin talent, Redoubt(Same mechanics as reckoning)  have no issue working. 

// Reckoning (Rank 5)
http://db.vanillagaming.org/?spell=20182
// Redoubt (Rank 5)
http://db.vanillagaming.org/?spell=20137

**Comment by w5860363** [comment]
https://github.com/mangoszero/server/blob/f26fb7adc603a9527418c9fa2560c1a6ee5928ac/src/game/WorldHandlers/Spell.cpp#L2962
and https://github.com/mangoszero/server/commit/f26fb7adc603a9527418c9fa2560c1a6ee5928ac

**Comment by dazidkk** [comment]
?

**Comment by dazidkk** [comment]
Same issue, even with those commits.

**Comment by w5860363** [comment]
test Did you test it? @dazidkk These are not applied to cmangos

**Comment by dazidkk** [comment]
Yes i did, but its a issue where something is hindering the reckoning talent from even triggering.

**Comment by killerwife** [comment]
I tested reckoning yday and it now worked
