### ISSUE TITLE
Checking with PVS-Studio static analyser

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [cmangos/issues#1292]
To demonstrate the capabilities of our analyzer, we regularly perform analysis of open source projects. We had recently checked the CMaNGOS project.

Here is the link to the article about it: http://www.viva64.com/en/b/0476/
Official page of the analyzer: http://www.viva64.com/en/pvs-studio/

If you have any questions, or if you are interested in the evaluation of our static analyzer or in any other source code quality control services that our company provides, please contact us at support@viva64.com.

**Comment by dagochen** [comment]
wow so much work and time put into this ;) great work and very nice described.

**Comment by jimmybrancaccio** [comment]
Much appreciated. One of the core developers will be in touch should we be further interested.
