### ISSUE TITLE
[WOTLK] Cast Spell: Treatment Effects

### ISSUE THREAD

**Issue by virusav** [cmangos/issues#1294]
Hi all.
If I'm not mistaken, but now some of the effects of the spell can stop all castes.

It seems that a spell cast must be in one of the following options:
1. Each of the spell effects should be treated separately and should not affect the entire cast as a whole. Perhaps the effect of the next processing to be completed only after the previous one.
Example: If a spell with three effects Damage Done, then immune to the same effect shall not interrupt the action of others.
2. Example spell 42261 suggests that cast spells trigger should not affect the caste "parent" spell.

Have someone some information from Sniff, as it is on the official server?
Is there any sense in my assumptions?

**Comment by Warlockbugs** [comment]
1. Partial (or independent) effect application is an ongoing objective for several months. I reshape various combat APIs to support it properly step by step.
2. This is just a silly description for a self-stun. Literally, it starts with a pun.

**Comment by virusav** [comment]
That is, after processing spell's effects will work 42261 spell and others like him?

**Comment by virusav** [comment]
Checking relevance.

**Comment by killerwife** [comment]
This is now possible using m_partialApplicationMask but it needs to be verified against said spell on retail.

**Comment by killerwife** [comment]
Closing this as i believe this got resolved by not interrupting spells that are already being processed.
