### ISSUE TITLE
[TBC] Double Login On Charscreen Disconnects Both Clients

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/issues#1295]
This is a remaining Problem with double login after https://github.com/cmangos/mangos-tbc/pull/180 which fixes https://github.com/cmangos/issues/issues/1177 . This Problem is also present without that PR.

**Current behavior**: 

Logging in an Account which is in Character-Select-Screen twice causes both clients to be disconnected.

Note: This does not apply if the already logged-in Client is in the World with a Character - then the behaviour is like expected.

**Expected behavior**: 

The second Client should not be disconnected, but end up on the Character-Select-Screen while the first client should get disconnected.

**Steps to reproduce**:

1. Login Account to Char-Selection
2. Login Account again on another Client
3.  Disconnect on both

**Client version**: 

2.4.3

**Commit hash**: 

latest tbc

**Database version**: 

latest tbc

**Comment by BenDol** [comment]
Not able to reproduce this in the latest TBC core/db.
