### ISSUE TITLE
[Feature][Question] AllowTwoSide.Interaction.Group + Trade

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/issues#1297]
If you AllowTwoSide.Interaction.Group = 1 you get the Option "Trade" in the Playermenu - u cant trade with the traditionally opposing faction tho - it tells you "Target is unfriendly".

Changing if the coresponding check in https://github.com/cmangos/mangos-tbc/blob/21644add3a3293e9c256463f2d65868113a8237c/src/game/TradeHandler.cpp#L636 for TRADE_STATUS_WRONG_FACTION so it does not check the faction,

```
if (false && pOther->GetTeam() != _player->GetTeam())
{
        info.Status = TRADE_STATUS_WRONG_FACTION;
        SendTradeStatus(info);
        return;
}
```

does not change the error message.

Question: is this clientside? 

Note: This same behaviour appears if you have ".gm on".

**Current behavior**: 

Playermenu shows trade option, on clicking it or /trade you get the error message "Target is unfriendly".
The client shows the other Player as friendly when in group (green circle, green name).

**Expected behavior**: 

Trade should be possible.

**Steps to reproduce**:

1. AllowTwoSide.Interaction.Group = 1
2. Group with opposing faction member
3. Trade with opposing faction member
4. "Target is unfriendly"

**Client version**: 
2.4.3

**Commit hash**: 
latest tbc

**Database version**: 
latest tbc

In WOTLK it must be possible since this screenshot exists:

![start trade](https://cloud.githubusercontent.com/assets/16046064/20657085/21f9a8f8-b56e-11e6-9dff-cd9075569d93.png)

![do trade](https://cloud.githubusercontent.com/assets/16046064/20657094/2aedef96-b56e-11e6-9f9c-84a471b07536.png)

Source: https://github.com/azerothcore/azerothcore-wotlk/issues/266

**Comment by evil-at-wow** [comment]
Yes, this is client side. I remember it was possible to trade with players from the other faction back in the days - 2007 and early 2008 - where the core was still MaNGOS and required older patches (like 2.2.3). I don't remember if it was 2.3 or 2.4 that broke this trading, but all of a sudden the code stopped working with a newer client.

It's the same with WoTLK clients. In fact, the WoTLK client is even worse: with a 2.4.3 client you can still have mixed parties and they can cast on each other (say a horde priest healing an alliance tank). The WoTLK client doesn't even want to do that...

That doesn't mean the screenshot is fake of course. No doubt the client uses the factions of the players involved to allow/disallow certain actions. What that core you've linked to has done is no doubt a workaround with factions to trick the client into believing the other player is friendly...

**Comment by ulfgebhardt** [comment]
If what you say is true, there is several solutions to the problem

**Possible Solutions**
1. ignore
2. remove the trade (and follow) option from the playermenu for crossfaction members of your party
3. finally make a open source client <- prefered

**Comment by Viste** [comment]
in wotlk all is ok you can go to inst in group of 2 faction but some inst bugs when you do that. YO CAN TRADE BUFF Etc need only evil-at-wow say shit. I'm(shkura blood elf, all other is Drenei and Human)
![wowscrnshot_031017_133109](https://cloud.githubusercontent.com/assets/281977/23792641/deaa5450-0598-11e7-84ae-18842f2077b6.jpg)
![wowscrnshot_031017_133112](https://cloud.githubusercontent.com/assets/281977/23792642/deac49c2-0598-11e7-8642-d10e2cf43b76.jpg)

**Comment by ulfgebhardt** [comment]
Question is: is it possible to do so on TBC or does the Client itself prohibits this?

**Comment by Viste** [comment]
in trinity and ascent in old days works fine

**Comment by ulfgebhardt** [comment]
on 2.4.3? or on other clients? @Viste

**Comment by Viste** [comment]
on 2.4.3

**Comment by Viste** [comment]
only 1 thing trade anvible only if you in party

**Comment by cyberium** [comment]
https://github.com/cmangos/issues/issues/596#issuecomment-328064614

**Comment by Warlockbugs** [comment]
This issue for crossfaction groups should be revisited as it was fixed with related patches above for all branches.

**Comment by SilvioDoMine** [comment]
@Warlockbugs Should GM be allowed to have channel crossfaction and trade crossfaction even if AllowTwoSide is off? To help in support
