### ISSUE TITLE
[WOTLK] SPELL_EFFECT_CREATE_ITEM: SendEquipError

### ISSUE THREAD

**Issue by virusav** [cmangos/issues#1300]
If an item is created by spell, but in the bags there is no place:
```DIFF
        // convert to possible store amount
        if (msg == EQUIP_ERR_INVENTORY_FULL || msg == EQUIP_ERR_CANT_CARRY_MORE_OF_THIS)
            num_to_add -= no_space;
```
In the end, the player does not receive a message about the impossibility of creating the item.

1. Why do we need above check?
2. Is checking on the possibility of adding the item to the player should not be in the same function that you would invoke in the right places?

**Comment by virusav** [comment]
Checking relevance.

**Comment by jimmybrancaccio** [comment]
Tagging core devs to see if we can get some further insight on this - @cyberium @killerwife @cala @Warlockbugs

**Comment by jimmybrancaccio** [comment]
@virusav Are you still having this issue in the latest code/core?

**Comment by virusav** [comment]
I don't have a server right now, so I can't check.

**Comment by jimmybrancaccio** [comment]
@virusav or anyone that needs access to test or replicate stuff I can provide any of the cores on the latest commits. Just ping me on Discord and we'll make it happen.

**Comment by natrist** [comment]
Can you post the file name?

**Comment by cyberium** [comment]
This should be fixed. Please let me know if its not working as it should.
