### ISSUE TITLE
[CLASSIC][TBC][WOTLK] Fleeing NPC Does Not Rely on Pathfinding

### ISSUE THREAD

**Issue by Valkirie** [cmangos/issues#1310]
**Current behavior**: When a NPC is low health and starts fleeing to the nearest ally. It goes straight to that point and don't rely on path-finding anymore.

**Expected behavior**: NPC should use path-finding to find the way to its ally.

**Steps to reproduce**:

1.  Find a NPC.
2.  Bring it low life.
3.  See it running through walls.

**Client version**: 1.12.1

**Commit hash**: b6d5f1fb5594397fe1d4822258a0b7d7ad8daa5a

**Database version**: 1587

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by BareRose** [comment]
Can confirm this happening in Tiragarde Keep where fleeing mobs would just kinda disappear to whereever while fleeing, completely ignoring walls.

**Comment by cala** [comment]
I also confirm this happening on Classic core, in instance Blackrock Spire (upper part).

**Comment by wowmui** [comment]
Anywhere!

**Comment by yushicsm** [comment]
Anywhere!

**Comment by AnonXS** [comment]
duplicate https://github.com/cmangos/issues/issues/1720 with more, more recent data
