### ISSUE TITLE
[TBC] Servercrash (1/3 times) on player kick

### ISSUE THREAD

**Issue by DanielBallaSZTE** [cmangos/issues#1311]
The server keeps on crashing when kicking an other players. Happens like every 3rd time. It's 100% random though.
Here's the crash log.

Wed Feb 22 01:30:23 EET 2017
WORLD: Received opcode CMSG_QUESTGIVER_STATUS_QUERY - for Player Tudja (Guid: 1$
WORLD: Sent SMSG_QUESTGIVER_STATUS for Creature (Entry: 40030 Guid: 160750)
WORLD: Received opcode CMSG_TIME_SYNC_RESP: counter 0, client ticks 177112950, $
 WORLD: Opcode CMSG_TIME_SYNC_RESP -- Our ticks: 177113295, diff 345, latency 0
zDiff = 0.000000
WORLD: Received opcode CMSG_ZONEUPDATE: newzone is 12
STORAGE: DestroyZoneLimitedItem in map 0 and area 12
WORLD: Received opcode CMSG_JOIN_CHANNEL (151, 0x97)
WORLD: Received opcode CMSG_JOIN_CHANNEL (151, 0x97)
WORLD: Received opcode CMSG_JOIN_CHANNEL (151, 0x97)
WORLD: Received opcode CMSG_JOIN_CHANNEL (151, 0x97)
WORLD: Received opcode CMSG_JOIN_CHANNEL (151, 0x97)
WORLD: Received opcode CMSG_GET_CHANNEL_MEMBER_COUNT (979, 0x3D3)
WORLD: Received opcode CMSG_GET_CHANNEL_MEMBER_COUNT (979, 0x3D3)
WORLD: Received opcode CMSG_GET_CHANNEL_MEMBER_COUNT (979, 0x3D3)
WORLD: Received opcode CMSG_GET_CHANNEL_MEMBER_COUNT (979, 0x3D3)
Player::UpdateItemDuration(1,0)
CHAT: packet received. type 1, lang 1
Command: kick tudja [Player: Darude (Account: 5) X: -9476.250000 Y: 60.263199 Z: 56.321499 Map: 0 Selected: None (Guid: 0)]

Wed Feb 22 01:33:12 EET 2017

**Comment by SilvioDoMine** [comment]
Confirmed this.

**Comment by DanielBallaSZTE** [comment]
Bump

**Comment by DanielBallaSZTE** [comment]
Okay, I fixed it
Worldsession.cpp

void WorldSession::KickPlayer()
{
    if (m_Socket && !m_Socket->IsClosed())
        m_Socket->Close();
}

**Comment by cyberium** [comment]
Should be fixed
