### ISSUE TITLE
[TBC] Lady Vashj and other Bosses should despawn on Evade with a reduced respawntime, resetting the encounters

### ISSUE THREAD

**Issue by Qingle** [cmangos/issues#1312]
Was researching Vashj fight mechanics and stumbled across this:

"If the whole raid stays on the stairs, Have a warlock pull out an eye, run up with it, Poke vashj in the eye with it, She will kill it, Then in +-3 seconds, Despawn, Everyone can get in position, and she will respawn about 30 seconds later."

[Source](http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/95377-guilds-stuck-lady-vashj-starting-her.html+&cd=17&hl=en&ct=clnk&gl=cz)

This is aimed @cyberium for charm interactions mainly.

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/blob/b2e0c5e6b54ba79cf41cc63f25c95b831a497789/src/game/AI/ScriptDevAI/scripts/outland/coilfang_reservoir/serpent_shrine/serpent_shrine.cpp#L200
