### ISSUE TITLE
[WOTLK] Unfinished?? sd2 & Acid 36 = ACTION_T_UPDATE_TEMPLATE:

### ISSUE THREAD

**Issue by Grz3s** [cmangos/issues#1313]
**Current behavior**: 
Hi all ... 
This one is serious issue:
Creatures after using sd2,ACID - action 36 UPDATE_TEMPLATE or even from spell -  after respawn stucks .. (wont do any waypoints or randomMovement)
Also you may see this neverending (spam) error:
```code
ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed!
ERROR:Map::GetReachableRandomPosition> Unsupported unit type is passed! 
```
**Expected behavior**: 
Creatures who ... were updated into another entry ones ... after respawn should go back to theirs waypoints or randomovement.

**Steps to reproduce**:
With WotlkDB Update [764] -- this one is for ACID
Use commands
```code
.go creature 74042
.damage 1
-- let him aggro you (he will transform into ghost) - this is our action
.die  (creature ofc;) )
.respawn (creature ofc)
-- see effect
```

We can check sd2 script for 'Nestlewood Owlkins' in Azuremyst Isle
more info here -- https://github.com/unified-db/Database/issues/251#issuecomment-249414622

Also we can check update comming from spell in Pyrewood Village
spell  - ID - 7671 Transformation
more info here: https://github.com/cmangos/wotlk-db/issues/4#issuecomment-253327960

**Client version**: 
Wotlk 3.3.5a

**Database version**: 
WoTLKDB - newest

**Operating system**: 
Win7 64bit

**Comment by AnonXS** [comment]
AI isnt initialised upon template change, hence the ai has to nested completely in the original entrys script.
I think its better this way, as a template change can occure e.g on aggro, in combat etc and reinitialising it then can lead to issues, its just easier to script a mob under one entry instead of making it reinitialise on template change.

**Comment by killerwife** [comment]
This should be fine, I reset entry on respawn now.
