### ISSUE TITLE
[TBC] Feign Death and Vanish Does Not Stop Enemy Casting

### ISSUE THREAD

**Issue by DanielBallaSZTE** [cmangos/issues#1314]
Hunter's Feign Death does not stop enemy casting. Also if a rogue vanishes, it doesn't stop it either.
I think it's a bug with cleared targets while casting.

**Comment by AnonXS** [comment]
Dublicate https://github.com/cmangos/issues/issues/1314

**Comment by jimmybrancaccio** [comment]
Closing as duplicate.

**Comment by DanielBallaSZTE** [comment]
@jimmybrancaccio 
Excuse me? 
You mark the issue as duplicated having it linked to the issue itself?

**Comment by jimmybrancaccio** [comment]
Apologies @DanielBallaSZTE Reopened!

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/blob/master/src/game/Entities/Unit.cpp#L11435
This code is responsible for this behaviour. That code I believe was added after this issue was resolved. @jimmybrancaccio please test it. The code is present in all cores.

**Comment by Pastew** [comment]
Hello,

I tested it. It looks it is fixed for both Feign Death and Vanish. Proof below.
![feigh_death](https://user-images.githubusercontent.com/5671416/54716656-7f81e280-4b56-11e9-8eee-a115a0507ffc.gif)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5671416/54716666-87418700-4b56-11e9-9a34-f7d295ee92bf.gif)
