### ISSUE TITLE
Documentation cmake path

### ISSUE THREAD

**Issue by JulianSchneider** [cmangos/issues#1319]
The [documentation](https://github.com/cmangos/issues/wiki/Installation-Instructions#compiling-cmangos-and-scriptdev2-nix) suggests having the directories in /home/mangos:

build, run and mangos

But -DCMAKE_INSTALL_PREFIX=\../mangos/run executed in /home/mangos/build will actually install into /home/mangos/mangos/run

Instead it should say -DCMAKE_INSTALL_PREFIX=\../run

Did I misread the instructions? If not it should be fixed to avoid confusion.

**Comment by cyberium** [comment]
duplicate with https://github.com/cmangos/issues/issues/1166
Yes we should look into this a bit more carefully
