### ISSUE TITLE
[CLASSIC] Possible Spell Hit Bug?

### ISSUE THREAD

**Issue by Gipsyjodler** [cmangos/issues#1320]
Hello, I think there is a bug within the current spell hit mechanic. I know that there had been some changes in the hit mechanic, but i dont know if this is an old problem or if it occurred with the last changes. Can you tell me if this is a possible bug? @Warlockbugs @killerwife
**Current behavior**: 
The additonal spell effect of spells can be resisted altough they hit. For Example, if you cast "Scorch" combined with the talent "Improved Scorch"(3/3), the debuff "Improved Scorch" can be resisted although "Scorch" hits the target. This behaviour can be also noticed with the talents "Ignite", "Shadow Vulnerability" of Warlocks and "Shadow Weaving"(5/5) of Priests.
**Expected behavior**: 
The additional debuff should always be added on the target when the spell hits. If the spell is resisted no debuff should be added. So if you cast a critical "Scorch" combined with the talents "Improved Scorch"(3/3)  and "Ignite" both debuffs from these talents should always be added on the target.
**Steps to reproduce**:

1. Cast "Scorch" combined with the talents "Improved Scorch"(3/3)  and "Ignite".
2. Cast a critical "Shadow Bolt" combined with the talent "Improved Shadow Bolt"
3. Cast a Shadow Spell combined with the talent "Shadow Weaving"

**Client version**: 
current
**Commit hash**: 

**Database version**: 

**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by dazidkk** [comment]
If i remember correctly, there's an issue with ignite stacking aswell. From the same player.

**Comment by killerwife** [comment]
You mean to say Fire Vulnerability spell ID 22959 gets resisted?

**Comment by cala** [comment]
I also noticed that the scorch debuff of my fire mage was more harder to bring to five stacks that it previously was but I did not dig the issue. Thanks for this report. Tagging @Warlockbugs on this.

**Comment by Warlockbugs** [comment]
This doesn't happen on TBC and these spells are identical between these two expansions. My guess is that classic core is behind on something related to target triggers.

**Comment by Warlockbugs** [comment]
Classic does die roll for target triggers, confirmed.
Target trigger cast starts here: https://github.com/cmangos/mangos-classic/blob/master/src/game/Spell.cpp#L6630 
TBC never does die roll for triggers. Any volunteers to diff execution path for these two cores inbetween Spell::ProcSpellAuraTriggers and Unit::MagicSpellHitResult ?

**Comment by robinsch** [comment]
I don't know if related but triggers should be handled on cast and not on hit (as mentioned in the issues).

**Comment by dagochen** [comment]
Hey,

maybe the die roll for triggers is correct? We should discuss it before someone wastes his time in finding the difference between TBC and Classic Cores.....

Found this discussion in the kronos bugtracker:
https://vanilla-twinhead.twinstar.cz/?issue=5770

At the end it says: 
>Scorch, Shadowbolt etc. are not binary, but the debuffs they inflict when they hit (or crit in the case of Imp SB) can be resisted seperately.

But the elitist jerks link is dead :(

**Comment by Gipsyjodler** [comment]
yes,my bad but i hope the proplem i pointed out is clear @killerwife
I have been testing it on a TBC server without any problems, Fire Vulnerability and Ignite is never resisted if the spell hits.

**Comment by Warlockbugs** [comment]
I've added physical school as a non-resistable marker (used as a component in Chaos school to make spell ignore magic resistances altogether) a few weeks ago, so that should work out of the box.

**Comment by Warlockbugs** [comment]
While the data needs additional verification, the point about core difference still stands however: for identical entires TBC core doesn't end up calling Unit::MagicSpellHitResult at all. This needs to be identified and somehow documented.

**Comment by killerwife** [comment]
classic core has plenty missing backports, something we have been diligently shoveling away in TBC. I even saw some places still using NULL macro instead of nullptr. This is the result of classic core not having a dedicated team.

**Comment by killerwife** [comment]
Should now be fine, all backports are in place.
