### ISSUE TITLE
[WOTLK] Auto-Cancel Auras When You Exit the Area

### ISSUE THREAD

**Issue by virusav** [cmangos/issues#1322]
There are auras that require presence in a particular area.
Example: 34630, the area 3873.
When you exit the area should be automatic removal of the aura.

Where this should be implemented in the core?
For the test checked in
```DIFF
void Aura::Update(uint32 diff)
```
works, but where correct positioning of the treatment?
Or is there already such a mechanism, but it does not work for all cases?

**Comment by Grz3s** [comment]
spell_area ??
https://github.com/cmangos/issues/wiki/spell_area

**Comment by virusav** [comment]
Aura (in this case SPELL_AURA_MOD_CHARM) superimposed on the NPC when the player uses an item.
Table spell_area added the entry indicating only the spell and the area, but the aura from the NPC was not removed.
Might need some more data to this table.

**Comment by Grz3s** [comment]
Allowed areas:
3873 - The Proving Grounds (Map: 530)
Yes... would be nice to control these things ... (almost all controled creatures have this "area" limit.)
Something like new condition - "Area" ?

**Comment by virusav** [comment]
CONDITION_AREAID&

**Comment by virusav** [comment]
Checking relevance.
