### ISSUE TITLE
[WOTLK] Dalaran, fishing

### ISSUE THREAD

**Issue by virusav** [cmangos/issues#1324]
```DIFF
void Spell::EffectTransmitted(SpellEffectIndex eff_idx)
...
if (!m_caster->GetTerrain()->IsInWater(fx, fy, m_caster->GetPositionZ() + 1.0f, &liqData))
```
In the zone of 4395 (Dalaran) it is impossible to fish due to "+ 1.0f".
If for the zone to write "- 1.0f", it is possible to fish in the fountain and other suitable water bodies.

In the sewer the values for the opportunity to fish also negative, but are dependent on the height of the object (above the water), on which stands a player.
Example: a player is on the object with a height of 5 above the water, so that the desired rate of fishing will be:
-1 - 5 = -6.0f

If not to take into account the object's height (above water) under the player, then allow to fish in Dalaran, you can:
```DIFF
            float fDelta = 1.f;
            if (m_caster->GetZoneId() == 4395) {
                fDelta = -fDelta;
            }
            if (!m_caster->GetTerrain()->IsInWater(fx, fy, m_caster->GetPositionZ() + fDelta, &liqData))
```
, but this is clearly a hack.

**This is a bug extractor cards?
Or is it a feature zone, located in "air"?**

**Comment by boxa** [comment]
fixed years ago...
https://github.com/mangosR2/mangos/commit/b793511e993b74898ce7a0eed65ee9132b6d00c9

IsAboveWater(...) now in cmangos core

**Comment by virusav** [comment]
Why in the zone Dalaran deviation of the Z coordinates is considered in the opposite direction?
Do you plan to fix fishing in Dalaran in cmangos?

**Comment by boxa** [comment]
this patch fixes fishing not only in dalaran
i can't remember exactly, but in shallow water also, such as ironforge, orgrimmar, etc
and you can normally catch fish standing waist-deep in water (like on offi)
try please this patch, maybe have details which i forgot

**Comment by virusav** [comment]
As I understand it, it is necessary to adapt the patch from mangosR2 for cmangos.
There is a list of "problem" zones where it is necessary to check the fishing with the patch?

**Comment by virusav** [comment]
If specified to apply the link patch (fully or partially receiving the coordinates Z), the fishing does not work correctly: float is not visible + not in all the places you can fish.

As a result of the tests I found an option in which you can fish even in shallow water.
You can fish, even standing in the water waist-deep or chest.

Patch:
```DIFF
diff --git a/src/game/SpellEffects.cpp b/src/game/SpellEffects.cpp
index fec2b0216..a8138f816 100644
--- a/src/game/SpellEffects.cpp
+++ b/src/game/SpellEffects.cpp
@@ -11337,7 +11337,7 @@ void Spell::EffectTransmitted(SpellEffectIndex eff_idx)
             m_caster->GetNearPoint2D(fx, fy, dis + m_caster->GetObjectBoundingRadius(), m_caster->GetOrientation() + angle_offset);
 
             GridMapLiquidData liqData;
-            if (!m_caster->GetTerrain()->IsInWater(fx, fy, m_caster->GetPositionZ() + 1.f, &liqData))
+            if (!m_caster->GetTerrain()->IsInWater(fx, fy, m_caster->GetPositionZ() + 1.f, &liqData) && !m_caster->GetTerrain()->IsAboveWater(fx, fy, m_caster->GetPositionZ() + 1.f))
             {
                 SendCastResult(SPELL_FAILED_NOT_FISHABLE);
                 SendChannelUpdate(0); 
```
The patch was checked in various water bodies in the areas of Dalaran, Stormwind, and in Stormwind near bodies of water.

What else should be checked?

**Comment by boxa** [comment]
i looked more closely and found that the code was changed later:
https://github.com/mangosR2/mangos/commit/9d6dc464f9e215c7d143be4a16e0118607f89baa
https://github.com/mangosR2/mangos/commit/7173a28b15c897dee15cab5276ec1e8ffd6970ff

so try this patch for current cmangos:
``` diff
diff --git a/src/game/SpellEffects.cpp b/src/game/SpellEffects.cpp
index fec2b02..ff459cc 100644
--- a/src/game/SpellEffects.cpp
+++ b/src/game/SpellEffects.cpp
@@ -11336,15 +11336,20 @@ void Spell::EffectTransmitted(SpellEffectIndex eff_idx)
             float angle_offset = max_angle * (rand_norm_f() - 0.5f);
             m_caster->GetNearPoint2D(fx, fy, dis + m_caster->GetObjectBoundingRadius(), m_caster->GetOrientation() + angle_offset);
 
-            GridMapLiquidData liqData;
-            if (!m_caster->GetTerrain()->IsInWater(fx, fy, m_caster->GetPositionZ() + 1.f, &liqData))
+            if (!m_caster->GetTerrain()->IsAboveWater(fx, fy, m_caster->GetPositionZ() + 1.5f, &fz))
             {
                 SendCastResult(SPELL_FAILED_NOT_FISHABLE);
                 SendChannelUpdate(0);
                 return;
             }
 
-            fz = liqData.level;
+            if (m_caster->GetPositionZ() < (fz - 1.0f))
+            {
+                SendCastResult(SPELL_FAILED_ONLY_ABOVEWATER);
+                SendChannelUpdate(0);
+                return;
+            }
+
             // finally, check LoS
             if (!m_caster->IsWithinLOS(fx, fy, fz))
             {
```

**Comment by virusav** [comment]
The results of the tests of your patch:
1. Error "You were not able to cast far enough".
![boxa_not_working1](https://cloud.githubusercontent.com/assets/323130/23698065/30029e2e-03fb-11e7-9e9d-28553a2d948b.jpg)
2. Error "Cannot be used in the water."
![boxa_not_working2](https://cloud.githubusercontent.com/assets/323130/23698066/3002ce12-03fb-11e7-864d-f1a452333fda.jpg)
3. Gnome can't fish where can draenei. :)
![boxa_not_working3](https://cloud.githubusercontent.com/assets/323130/23698064/30024bd6-03fb-11e7-8dbd-21b0513f9e3b.jpg)
4. Maximum player immersion, in which fishing is possible (draenei).
![boxa_working1](https://cloud.githubusercontent.com/assets/323130/23698067/300a824c-03fb-11e7-8b6e-6704cb09b8dc.jpg)
5. Maximum player immersion, in which fishing is possible (gnome).
![boxa_working2](https://cloud.githubusercontent.com/assets/323130/23698063/3001e3ee-03fb-11e7-97f9-83014d89ce7c.jpg)

Patch tested on the same areas as the previous one.
In General, the fishing works.
About depth of immersion to be able to fish I can say nothing, as it was on the official server.

**Comment by boxa** [comment]
thank you for testing!

the next my thought was to use the correct waist height so that there no calculating errors on high and low models (eg draenei and gnome)

here next generation patch =), try it please (i did not check, but everything should be clear)
``` diff
diff --git a/src/game/DBCStores.cpp b/src/game/DBCStores.cpp
index 6efcffb..449a5e8 100644
--- a/src/game/DBCStores.cpp
+++ b/src/game/DBCStores.cpp
@@ -966,6 +966,17 @@ uint32 GetCreatureModelRace(uint32 model_id)
     return extraEntry ? extraEntry->Race : 0;
 }
 
+// for creatures - mid point, for mounts - spine, for characters - waist line
+float GetModelMidpoint(uint32 modelId)
+{
+    if (CreatureDisplayInfoEntry const* displayInfo = sCreatureDisplayInfoStore.LookupEntry(modelId))
+    {
+        if (CreatureModelDataEntry const* modelData = sCreatureModelDataStore.LookupEntry(displayInfo->ModelId))
+            return modelData->MountHeight;
+    }
+    return 0.0f;
+}
+
 // script support functions
 MANGOS_DLL_SPEC DBCStorage <SoundEntriesEntry>  const* GetSoundEntriesStore()   { return &sSoundEntriesStore;   }
 MANGOS_DLL_SPEC DBCStorage <SpellRangeEntry>    const* GetSpellRangeStore()     { return &sSpellRangeStore;     }

diff --git a/src/game/SpellEffects.cpp b/src/game/SpellEffects.cpp
index fec2b02..6c0535e 100644
--- a/src/game/SpellEffects.cpp
+++ b/src/game/SpellEffects.cpp
@@ -11336,19 +11336,19 @@ void Spell::EffectTransmitted(SpellEffectIndex eff_idx)
             float angle_offset = max_angle * (rand_norm_f() - 0.5f);
             m_caster->GetNearPoint2D(fx, fy, dis + m_caster->GetObjectBoundingRadius(), m_caster->GetOrientation() + angle_offset);
 
-            GridMapLiquidData liqData;
-            if (!m_caster->GetTerrain()->IsInWater(fx, fy, m_caster->GetPositionZ() + 1.f, &liqData))
-            {
-                SendCastResult(SPELL_FAILED_NOT_FISHABLE);
-                SendChannelUpdate(0);
-                return;
-            }
+            SpellCastResult err = SPELL_FAILED_SUCCESS;
+            float waistHeight = GetModelMidpoint(m_caster->GetDisplayId()) * m_caster->GetObjectScale();
+
+            if (!m_caster->GetTerrain()->IsAboveWater(fx, fy, m_caster->GetPositionZ() + waistHeight + 0.5f, &fz))
+                err = SPELL_FAILED_NOT_FISHABLE;
+            else if (m_caster->GetPositionZ() < (fz - waistHeight))
+                err = SPELL_FAILED_ONLY_ABOVEWATER;
+            else if (!m_caster->IsWithinLOS(fx, fy, fz))
+                err = SPELL_FAILED_LINE_OF_SIGHT;
 
-            fz = liqData.level;
-            // finally, check LoS
-            if (!m_caster->IsWithinLOS(fx, fy, fz))
+            if (err != SPELL_FAILED_SUCCESS)
             {
-                SendCastResult(SPELL_FAILED_LINE_OF_SIGHT);
+                SendCastResult(err);
                 SendChannelUpdate(0);
                 return;
             }
```

**Comment by virusav** [comment]
Your patch is missing the function Declaration GetModelMidpoint in DBCStores.h:
```DIFF
float GetModelMidpoint(uint32 modelId);
```
With the patch the gnome will not drown while fishing.)
Draenei can go on the belt, and the gnome - a little below the belt.
![wowscrnshot_030817_185232](https://cloud.githubusercontent.com/assets/323130/23711897/3d6abdf8-0432-11e7-9cc9-d82b4bcd9fcc.jpg)
![wowscrnshot_030817_185348](https://cloud.githubusercontent.com/assets/323130/23711898/3d974774-0432-11e7-83ab-ae1095f50b13.jpg)

**Comment by virusav** [comment]
Whether fishing to work in Silvermoon City?
With the patch not working.
![wowscrnshot_030817_210944](https://cloud.githubusercontent.com/assets/323130/23717191/d578b99a-0443-11e7-82f5-85764834019d.jpg)

**Comment by boxa** [comment]
@virusav
thank you for testing!
i and the players tested too, no problems found, everything works clearly
so patch ready for commit

> Whether fishing to work in Silvermoon City?

here no water at all =) if you walk on this "water" there are no traces
TerrainInfo::getLiquidStatus() returns LIQUID_MAP_NO_WATER
