### ISSUE TITLE
Equipment System Extension

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#1329]
Current equipment system from database works as follows:
We are able to set one Equipment Template per spawn/template.

In the last few weeks when gathering data, we discovered that following extensions are needed:
We need to be able to change Equipment template at will on entering combat/changing phases in combat, preferably using an ID for equipment template.
Also, we need to be able to set RANDOM equipment templates. This is hinted by some item names from TBC.

I propose the following:
Creature_template and creature tables equip ID > 0 will use one static Equip template.
EquipID < 0 will use an entry from table Equip_template_group

What will Equip_template_group do?
Three columns: Equip template group ID, equip template ID, event type (this one is debatable, will explain at the end).
This way on spawn we would randomize between equip template IDs and pick one at random depending on the group.

Event type - with this we could possibly automatize changing weapons on entering combat, but its possible this is too much and instead we will offload it by using an EAI command.

Proposed EAI commands:
Change equipment template ID - this would enable mobs switching templates on phases/entering combat. Some mobs draw out different weapons on aggro. Its currently only possible to change it in SD2.
Reset Equipment template ID to OnSpawn one - If a mob has random on spawn IDs, we will reset to the one the randomization picked.

I would really like some feedback on my ideas, because current equipment handling from DB is quite limited.

These suggestions were gathered based on reports by @MantisLord @AnonXS @SaltGurka

@cala @cyberium @Tobschinski @grz3s I would like your feedback on this. If you guys can provide me some feedback I can have this implemented quite soon™.

**Comment by AnonXS** [comment]
I think any changing of weapons should be left to eai / dbscripts_on_x.
Npcs changing weapons is mostly on waypoint or part of their ai.

As we have extended pooling tables, i think we should try to keep this system. e.g. 

-`creature_equip_template`.`entry` links to `pool_creature_equip_template` (`id`, `equipentry1`, `equipentry2`, `equipentry3`);

We should want to keep it minimalistic as extra options in such a table could confuse and are unnecessary due to extended eai / dbscripts_on_x capabilities.

**Comment by Grz3s** [comment]
42 SCRIPT_COMMAND_SET_EQUIPMENT_SLOTS this command works preety well.. for scripts ;)

**Comment by Saltgurka** [comment]
Implementing an equivalent of SCRIPT_COMMAND_SET_EQUIPMENT_SLOTS in EventAI should be all we need here. Having pool tables for equipment templates seem unnecessary when we can update the modelid directly.

**Comment by AnonXS** [comment]
Pro ACID Implemenataion aka SET_ACTION_T_SET_EQUIPMENT_ENTRY.

**Comment by AnonXS** [comment]
# Cho'Rush the Observer

[Research different weapon combinations](https://vanilla-twinhead.twinstar.cz/?issue=13020) aka:
```
Mage form: Arcane Explosion, Fireball, Frost Nova
Mage weapon ID: Kindling stave (ID# 11750) OR Ogremage Staff (ID# 2226)

Priest form: Heal, Mind Blast, PW: Shield, fear
Preist weapon ID: Guiding Stave of Wisdom (ID #11932)

Shaman form: Healing Wave, Lightning bolt (this should be CHAIN LIGHTNING), Earthgrab totem
Shaman weapon ID: The one he has equipped on currently is correct.
```

**Comment by killerwife** [comment]
Non issue anymore. Can be done in EAI and dbscript.
