### ISSUE TITLE
[WOTLK] Spell 60445 - Dalaran Fountain Fishing

### ISSUE THREAD

**Issue by virusav** [cmangos/issues#1332]
Patch:
```DIFF
diff --git a/src/game/GameObject.cpp b/src/game/GameObject.cpp
index 824db3e66..d2d0051e1 100644
--- a/src/game/GameObject.cpp
+++ b/src/game/GameObject.cpp
@@ -1448,6 +1448,11 @@ void GameObject::Use(Unit* user)
                             loot = new Loot(player, this, success ? LOOT_FISHING : LOOT_FISHING_FAIL);
                             loot->ShowContentTo(player);
                         }
+                        // Dalaran: The Eventide
+                        if (subzone == 4568) {
+                            // Dalaran Fountain Fishing
+                            player->CastSpell(player, 60445, true, nullptr, nullptr, player->GetObjectGuid());
+                        }
                     }
                     else
                     { 
```

**Comment by boxa** [comment]
@virusav 
explain please why this is necessary? 
without any code fishing in Dalaran works normally

**Comment by virusav** [comment]
Early developers of cmangos said that if there is a spell for some purposes, it is necessary to use it.
The coin can be caught only in the fountain of Dalaran, is responsible for what spell 60445.

If the current policy cmangos does not require the use of such spells, the patch is not needed.

What then to focus when writing patches?
That will not be a hack?

**Comment by xfurry** [comment]
@cyberium any thoughts on this?

**Comment by cyberium** [comment]
Its more or less a hack. Sound like that spell need to be casted though.
So we have to found a better way to handle this and check if http://wowwiki.wikia.com/wiki/The_Coin_Master work.

**Comment by virusav** [comment]
If you find a more correct solution that is already working, the issue should be closed?

**Comment by killerwife** [comment]
I believe that spell is for testing purposes because fishing loot is fine as it is.
