### ISSUE TITLE
Adding more generic DBScripts to dbscripts_on_creature_movement

### ISSUE THREAD

**Issue by Saltgurka** [cmangos/issues#1333]
I will mostly be referring to tbc-db in this post, but it should apply to wotlk and classic too. 

I would like to add a lot more generic dbscripts_on_creature_movement scripts to prevent more duplicate scripts being created. Currently we only have 4. ("GENERIC - Despawn Self", "GENERIC - Disable Waypoint Movement", "Stratholme - Gargoyles - RUN ON" and "GENERIC - Run Mode Off").

- We have no generic scripts for emotes. My suggestion would be this:
The Emote ID's range from 1 to 423 (in tbc). I would like to create a dbscript for each emote and the dbscript ID should be the same as the emote ID. That way you will never have to search to find the correct one.

It would continue like this: 
![image](https://cloud.githubusercontent.com/assets/22568446/23827278/473f265e-06b0-11e7-8347-f58b755b691c.png)

This would make it very easy for us to finally scrap the emote column in creature_movement and replace it with dbscripts. 

We would then have to move the existing generic scripts (id 1,3,5,6) to a higher range.

Apart from emotes here's my suggestion for additional generic scripts:

```
1-476: Emotes (476 is the max in wotlk)
480-489: SCRIPT_COMMAND_STAND_STATE (all 10 UnitStandStateTypes)
500: GENERIC - Despawn Self
501: GENERIC - Run Mode On
502: GENERIC - Run Mode Off
503: GENERIC - Set Idle Movement
504: GENERIC - Set Random Movement
505: GENERIC - Pause Waypoints
506: GENERIC - Resume Waypoints
507: GENERIC - Set Active Object On
508: GENERIC - Set Active Object Off
509-514: GENERIC - Send AI Event X to Self
```
@AnonXS also suggested that we add generic scripts for SCRIPT_COMMAND_FLAG_SET and SCRIPT_COMMAND_FLAG_REMOVE, so that's something we should consider as well. 

Using the same system in all 3 databases would be benefitial, so if we can agree to a common way of doing this that would be great. :)

**Comment by AnonXS** [comment]
XXX: GENERIC - Visibilty OFF
XXX: GENERIC - Visibilty ON
Maybe other Visibilty Flags

XXX: GENERIC - Add UNIT_FLAG_UNKNOWN7
XXX: GENERIC - Add UNIT_FLAG_XXX ...

XXX: GENERIC - Remove UNIT_FLAG_UNKNOWN7
XXX: GENERIC - Remove UNIT_FLAG_XXX

Basicly find as many possible standard "GENERIC" scripts that could be used, maybe built compinations of most likely combinations.
