### ISSUE TITLE
[WOTLK] Spawn objects with a type=6 (linkedTrapId)

### ISSUE THREAD

**Issue by virusav** [cmangos/issues#1334]
At the moment linkedTrap objects are added to the database in the table gameobject.
If the underlying object is searched within a radius of linkedTrap and challenge Use.
When despawn the main object does not delete linkedTrap.

Suggestions:
1. To do the automatic adding linkedTrap in the game world when you download the main object (including events and pollow).
At the same time to record the received Guid/ObjectGuid/... GameObjectData.
2. When you use the/enable or despawn the main object is not to search linkedTrap, and take the one that was added to world in the point with the main object.
3. When you create a master object with a script/spell, etc. automatically add linkedTrap the same pattern.

In the end, all the excess population of objects from the database can be deleted, because linkedTrap spelled out in the templates of the main objects and should work as one.

Currently under testing to make spawn linkedTrap at the point of the main object.
The synchronization usage/activation and despawn.

**Does it make sense to continue working on the proposed direction?
Or such a decision would not even be considered?**

**Comment by Grz3s** [comment]
Hi @virusav . 100% agree with fact ..that when master object id despawned (trap should despawn with it)
But working on Stratholme i found this strange thing:
Pls look here:
https://github.com/cmangos/wotlk-db/issues/101

**Comment by virusav** [comment]
Need an example of this trap (entry).
It is possible that such objects should not be processed outside of the main object.
Are there any examples in sniffs when traps are in the world alone, but the main object is not at all?

**Comment by evil-at-wow** [comment]
Something similar as Grz3s' Stratholme example is present in Dire Maul: apparently the trap Warpwood Pods don't have their trap GOs spawned. See my findings in classicdb/database#711.

**Comment by Grz3s** [comment]
its complicated enough...
We all know objects with spawned traps without players help...
example can be Netherwing eggs and theirs traps (185600)...
and here it looks like we have objects with traps spawned only with players intervencion.

**Comment by virusav** [comment]
Does anyone know how to find in the core by the lowguid of the object, its ObjectGuid to complete the desired action?

**Comment by virusav** [comment]
Checking relevance.

**Comment by AnonXS** [comment]
Linked GoTrap Removal - Export pending

**Comment by killerwife** [comment]
Exported in https://github.com/cmangos/mangos-wotlk/commit/91abe1210db0371cbe7e7464cbd5f472daddf7fc
