### ISSUE TITLE
[WotLK] Fishing - All locations: "Did not land in Fishable Water"

### ISSUE THREAD

**Issue by Ubergeekking** [cmangos/issues#1335]
Updated the server on March 1, and now we are unable to fish anywhere. Every cast fails with "Cast did not land in fishable water." Tested with multiple accounts, in several zones. Affects existing and newly created accounts.

No steps to reproduce, beyond trying to fish normally.
Server: Ubuntu 14.04 64bit
Clients:  WotLK 3.3.5a (enGB) (Windows)

wotlk-DB is 12943 (up to update 764_Zone.sql) and Core 12952_01 

Tested on multiple pc's:  Windows 7, 8, and 10. all were 64-bit.

**Comment by Ubergeekking** [comment]
sorry. not sure what i fat-fingered but it submitted while i was typing the title

**Comment by Ubergeekking** [comment]
I updated core and db May 3, and it fishing no longer has any issue. Should I close the issue?

**Comment by xfurry** [comment]
> Should I close the issue?

Yes please (unless there are still recent issues)
