### ISSUE TITLE
[CATA] vmap_extractor cmake failure

### ISSUE THREAD

**Issue by alysher** [cmangos/issues#1336]
currently attempting to run cmake with -DBUILD_VMAP_EXTRACTOR=1 causes this error:

>CMake Error at contrib/vmap_extractor/vmapextract/CMakeLists.txt:15 (add_executable):
>  Cannot find source file:
>
>    mpq_libmpq.cpp
>
>  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
>  .hxx .in .txx

**Comment by cyberium** [comment]
CMaNGOS doesn't support anymore cata
