### ISSUE TITLE
[CATA] build fail on extractor

### ISSUE THREAD

**Issue by alysher** [cmangos/issues#1337]
running make with -DBUILD_EXTRACTOR=ON terminates with this error:

> In file included from /wow/mangos/4.3.4/source/contrib/extractor/loadlib/loadlib.cpp:3:0:
>/wow/mangos/4.3.4/source/contrib/extractor/loadlib/loadlib.h:8:22: fatal error: StormLib.h: No such file or directory
> #include "StormLib.h"
>                      ^
>compilation terminated.
>contrib/extractor/loadlib/CMakeFiles/loadlib.dir/build.make:54: recipe for target 'contrib/extractor/loadlib/CMakeFiles/loadlib.dir/loadlib.cpp.o' failed

**Comment by cyberium** [comment]
CMaNGOS doesn't support anymore cata
