### ISSUE TITLE
Legion - Use the Garrison buildings and set their scales to something else than 1

### ISSUE THREAD

**Issue by goclad** [cmangos/issues#1338]
Hello 
I'm trying to create an event which would shrink all the buildings and the players with them.
To do that I tried to create new objects in the gameobject_template by giving them the DisplayId of the Garrison buildings and change their scale to 0.1 so I could just set them up for the event.
But something goes wrong, probably because of their types.

I managed to shrink the objects of type 5 or 7, but I can't do that with the buildings.
I suppose the solution is to change the type of the buildings, but I can't simply do that.
Does anybody know what to do?

**Comment by OriginsDev** [comment]
I can only try answer this from a non-code point of view - however I believe the objects you are able to scale or M2 format and the one's you can't are WMO. WMO has never been scaleable.

**Comment by cyberium** [comment]
Legion, garrison?
