### ISSUE TITLE
[TBC]Quest Timer freezing client?

### ISSUE THREAD

**Issue by kesodev** [cmangos/issues#1340]
Starting "The Kessel Run" freezes player client completely.

http://www.wowhead.com/quest=9663/the-kessel-run

I have a feeling it has to do with the quest timer since I want to recall having this issue on other timed quests in the past.

Cant really give any detailed info since my client just freezes. No crash report. Nothing.

**Comment by MantisLord** [comment]
You use quest helper addon by any chance?

**Comment by kesodev** [comment]
@MantisLord correcto. Any way to solve this tho? Tons of players will complain about this if making a live server.

**Comment by MantisLord** [comment]
Yes, I believe the issue lies in not having the most up to date QuestHelper for 2.4.3.
@Warlockbugs knows more about this. From what I can remember, he also had a link to the correct version.

**Comment by Warlockbugs** [comment]
Quest Helper issue. I've lost a couple of hours debugging this head-scratcher in-game. On-screen objectives list update enters infinite cycle.
Latest fixed version compatible with 2.4.3 is [0.54](https://wow.curseforge.com/projects/quest-helper/files/140114).
