### ISSUE TITLE
Some Auras Are Not Removed on Creature Death

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1344]
**Current behavior**: 
Permanent auras with periodic effect are not removed on creature death.
For example, the four Emerald Dragons have a periodic aura 25041 added when they enter combat. This aura remains and still triggers its periodic effect even when they are dead.
Also, NPC Flameguard (11667) has a periodic aura 19626 added on spawn that triggers a hostile spell. Even after the NPC is killed, the aura still triggers, damaging nearby players.

I don't know if this is intended behaviour (meaning all creature scripts need to be updated) or if this is unexpected.
Tagging @Warlockbugs on this.

**Expected behavior**: 
These auras should be removed on creature death.

**Steps to reproduce**:

1. `.npc add 11667`
2. kill it with `.die`
3. go near its corpse to take the damage

**Client version**: 
Classic 1.12.1

**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/029748fbc9d86a62f6fdb396ea33f5e0722231e9

**Database version**: 
Classic DB 1.8

**Operating system**: 
Mac OS X 10.6.8

**Comment by virusav** [comment]
Classic:
```DIFF
void Unit::JustKilledCreature(Creature* victim, Player* responsiblePlayer)
	victim->SetDeathState(JUST_DIED); 
		void Creature::SetDeathState(DeathState s)
			Unit::SetDeathState(s);
				RemoveAllAurasOnDeath();
				// used just after dieing to remove all visible auras
				// and disable the mods for the passive ones
```
Spell 19626 -> TriggerSpell 19627

RemoveAllAurasOnDeath - does not remove this spell
RemoveAllAuras - this spell removes

Perhaps we need a more subtle treatment to RemoveAllAurasOnDeath (or change the parameters of these spells to the table spell_template).

**Comment by boxa** [comment]
interesting

the problem is that it's passive, permanent aura, and we don't know remove it on death or not. maybe it only visual aura?
another issue is that in theory it should not periodically triggered after death.

therefore, imho there are two ways:
1. delete at death the aura with the periodic trigger
2. not to delete, but not allow to trigger after death 

something like that...

**Comment by cala** [comment]
Thanks @boxa I'll test your code when I get the chance.

**Comment by cala** [comment]
Bump at myself.

**Comment by cala** [comment]
Hello @boxa sorry for taking so long to test your patch. Unfortunately, it does not fix the issue: the passive aura is still there and it still triggers the second spell.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/d8e07b2112c253ab7f7235e169618657ff9a6fd3
