### ISSUE TITLE
[TBC DB] Creature curhealth issue

### ISSUE THREAD

**Issue by henrikssonkevin** [cmangos/issues#1345]
Hi

Creatures does not seem to fetch/set curhealth propperly in creature table. All values in creature_template are correct but spawning the mob doesnt set HP after minhp/maxhp.

I tried spawning a Wrath Master which gives the following error in the DBErrors.log:

`2017-03-27 16:52:07 Table creature have creature (GUID: 160566 Entry: 19005) with creature_template.RegenerateStats & REGEN_FLAG_HEALTH and low current health (7181), creature_template.MinLevelHealth=143620.`

This problem popped up after applying all updates in TBCDB/Updates folder.

All multiplying options are correctly set to x1. Also tried changing min/maxhp in creature_template which gives no effect. Wrath Master still spawns with 7181 HP. Changing curhealth manually in creatures table also has no effect.

**Comment by cala** [comment]
By any chance, do you have changed the mangosd.conf file and modified those variables:
```
Rate.Creature.Normal.HP = 1
Rate.Creature.Elite.Elite.HP = 1
Rate.Creature.Elite.RAREELITE.HP = 1
Rate.Creature.Elite.WORLDBOSS.HP = 1
Rate.Creature.Elite.RARE.HP = 1
```
?

**Comment by kesodev** [comment]
Nope, only changed my DB auth and stuff. Everything else is default.

**Comment by kesodev** [comment]
I tried changing HP of creature_template to see if it was a multiplying issue and it's not. Changed hp to 120k instead of 140k and hp still stands at 7181.

**Comment by Tobschinski** [comment]
Isn't the total health hidden in vanilla and TBC?

**Comment by kesodev** [comment]
No it's not hidden in TBC and the mob does have 7k hp. He dies within seconds of getting attacked by other npc's.

**Comment by kesodev** [comment]
HP seems off on all NPC's. Thrallmar grunt has 3052 hp but should have 3500.

**Comment by kesodev** [comment]
DBError.log for Wrath master

2017-03-27 16:52:07 Table `creature` have creature (GUID: 160566 Entry: 19005) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (7181), `creature_template`.`MinLevelHealth`=143620.

**Comment by cala** [comment]
Indeed, it seems your creature table has wrong curhealth data (maybe curmana too). Can you try with a fresh install of TBC-DB?

**Comment by kesodev** [comment]
Yes @cala it does give some curmana errors aswell. This is about as fresh as it gets tho. Downloaded and installed about 3-4 days ago. Already done tons of stuff which is why I rather not just dropp it :D

**Comment by kesodev** [comment]
Tried repairing the DB with heidisql maintenance tool to check that the tables werent corrupt. No luck.

**Comment by kesodev** [comment]
Could it have something to do with:

```
2017-03-28 12:11:01 SQL: SELECT guid, respawntime, map, instance, difficulty, resettime, encountersMask FROM creature_respawn LEFT JOIN instance ON instance = id
2017-03-28 12:11:01 query ERROR: Unknown column 'encountersMask' in 'field list'
2017-03-28 12:11:01 SQL: SELECT guid, respawntime, map, instance, difficulty, resettime, encountersMask FROM gameobject_respawn LEFT JOIN instance ON instance = id
2017-03-28 12:11:01 query ERROR: Unknown column 'encountersMask' in 'field list'
```

**Comment by kesodev** [comment]
@cala any idea how I assign curhealth and curmana to fetch the propper field from creature_template?

**Comment by Muehe** [comment]
I have similar errors in the log on classic core: https://gist.github.com/Muehe/1092e607cecc46579e325611fce69722

**Comment by kesodev** [comment]
I tried a full re-install and can confirm that there's something wrong in the 50k + lines of SQL updates that is the TBCDB/updates folder. This issue only occurs after installing the updates.

**Comment by Tobschinski** [comment]
@Muehe Did https://github.com/cmangos/classic-db/blob/master/Updates/1634_the_dragonmurk.sql#L184 not fix this?

**Comment by Muehe** [comment]
Damn, I'm on commit 1633! :laughing:

**Comment by kesodev** [comment]
I tried executing the last SQL line on TBCDB. No luck tho. @Tobschinski

**Comment by kesodev** [comment]
I found this update in 840.sql.

`UPDATE creature a join creature_template b on a.id=b.entry SET a.curhealth=b.MinLevelHealth WHERE a.curhealth<b.MinLevelHealth AND b.RegenerateStats&1 AND a.id=b.entry;`

Doesnt look right to me. Also 998 gives tons of errors on updating a fresh install of TBCDB so it needs to be looked at.

**Comment by kesodev** [comment]
this code

`UPDATE creature a join creature_template b on a.id=b.entry SET a.curhealth=b.MinLevelHealth WHERE a.curhealth<b.MinLevelHealth AND b.RegenerateStats&1 AND a.id=b.entry;`

Seems to address this without effect. Located in 840.sql.

**Comment by kesodev** [comment]
Anyone?

**Comment by Muehe** [comment]
It might indicate something went wrong with the updates. Do you use the `InstallFullDB.sh` script?

**Comment by Grz3s** [comment]
to fix this error you need correct HelathMultiplier from sniff...
I'm sure i can find it ... but not now...
If im correct (99%) TBC has simmilar values to WoTLK for 19005.
UnitClass =1
EXpansion = 1
If yes than you know why you have hp = 7181
more info here:
https://github.com/cmangos/issues/wiki/creature_template#healthmultiplier

**Comment by kesodev** [comment]
@Grz3s well the sniff data was correct prior to updating the DB so it's safe to say there's an update on the `creature_template_classlevelstats` which is not compatible with TBCDB.

**Comment by Grz3s** [comment]
i dont have a TBC DB... tell me what values you have there for c.19005
creature: 19005 has:
HealthMultiplier = 20  <--- this is correct one
PowerMultiplier = 10  <--- this is correct one

**Comment by kesodev** [comment]
@Grz3s Thanks for the detailed description of the issue, much appreciated!

Altho I have to ask why use something like `creature_template_classlevel`? What are the benefits rather than using `creature_template` data?

**Comment by Grz3s** [comment]
```quote
Altho I have to ask why use something like  creature_template_classlevel ? What are the benefits rather than using  creature_template  data?
```
koz this is the way how official servs works. (in short ver)

```
I guess c_template data isnt 100% correct?
```
its hard to get (WoTLK - 43282 creatures) all data... 
But hey... we all working on that .. and every day we're closer .. ;)

```quote
Just seems like more effort to sniff multipliers.
```
CmangoS +  all databases (that uses it) bases on as closed data as its possible to get ;)

**Comment by kesodev** [comment]
Thanks a bunch @Grz3s for all the answers, much appreciated!

Since SQL isnt my strong side I might aswell ask how I after doing this:

```
SELECT entry,
       HealthMultiplier,
       PowerMultiplier,
       DamageMultiplier,
       DamageVariance,
       ArmorMultiplier,
       ExperienceMultiplier
FROM creature_template
WHERE entry BETWEEN 1 AND 29095;
```
Make all 30k rows format this way:

`UPDATE creature_template SET HealthMuliplier = "VALUE", PowerMultiplier = "VALUE", etc etc.. WHERE entry = 123;`

**Comment by kesodev** [comment]
@cala 

How do you guys do these massive backports from lets say WOTLK db?

Looking at 841_CLS.sql there are thousands of rows like:

`UPDATE `creature_template` SET `Expansion`=0 WHERE `Entry`=920;`

I need to get Multiplier values from the WOTLKDB to fix TBCDB issues.

**Comment by amaroc** [comment]
Omg guys, what you talking about? Import from WOTLK? It must be good by default on TBC database...  something was wrong on updates or core... and this problem exist as i see more then 1 moth - it`is terrible...

**Comment by killerwife** [comment]
We imported CLS in tbc-db as well. The thing is, this is part of a large scale research that needs to be done and noone has time for. Right now we are working in emergency mode ever since I exported 800 commits in december. I will deal with this in the coming months, when I have a break from my usual stuff. A lot of c++ is needed to fully fix this.

**Comment by joeyc83** [comment]
If it helps any, from my research I found that the bosses inside of raids (?? or skull) were 200 times less than what the DB was showing.  I increased the multiplier for world bosses (inside of mangosd.conf) to 200, and the health displayed correctly.  Inside of regular dungeons, named bosses (elite with levels showing) were 15 times lower the DB.  I haven't found a work around for that one yet.

**Comment by kesodev** [comment]
This issue is still present in the new "RiseOfThePhoenix" DB. This should probably be taken out until the C++ part is finnished.

**Comment by kotishe** [comment]
Damn, need fix it =(

**Comment by AnonXS** [comment]
For Starts someone could just export Multpliers from wotlk-db to tbc-db, this already solves alot of Health / Damage Value Issues. :)

**Comment by Saltgurka** [comment]
This should now be greatly improved with this commit: https://github.com/cmangos/tbc-db/commit/e6623c09f6fb43d400586c0d443ddbc16fea70e0

The issue can probably be closed

**Comment by jimmybrancaccio** [comment]
Closing this out per above comment. If you're continuing to still have any issues with this please don't hesitate to open a new issue (you may also reference #1345 if you do). Thanks!
