### ISSUE TITLE
[TBC] Critical - Chars losing skills, bags, itens.

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1347]
**Current behavior**:
When you die, and try to get your corpse back, you got DC, and when you log-in back, your character cannot speak, don't have professions, all bags is gone. But everything is on the database.

**Steps to reproduce**:

1. Die
2. Try to get your corpse back
3. Get DC
4. Watch your skills gone (including speaking ones), bags, etc.

**Database version**: 
Last TBC-DB

**Comment by SilvioDoMine** [comment]
@Warlockbugs

**Comment by Warlockbugs** [comment]
Looks like session duplication. Related to: https://github.com/cmangos/issues/issues/1177

**Comment by cyberium** [comment]
yes its related to double login i will close this.
