### ISSUE TITLE
[CLASSIC] - regression - mini-pet attack mode

### ISSUE THREAD

**Issue by RichardGe** [cmangos/issues#1350]
**Current behavior**: 
While attacking with a summoned mini-pet, the pet will have an "attack" behavior.
this is a recent **regression**: I didn't have this bug before 

**Expected behavior**: 
the pet should not react to combat .
by "pet", I mean the little inoffensive followers like cats,frogs...
I think it's the tag : MINI_PET in the source code

**Steps to reproduce**:
1) take a pet, for example :  
the Dark Whelpling :
http://db.vanillagaming.org/?item=10822
2) attack a mob
3) your little pet dragon will make attack noises each second.

**Client version**: 
1.12.1 - 5875

**Commit hash**: 
029748fbc9d86a62f6fdb396ea33f5e0722231e9

**Database version**: 
4a4d6ebf4866737128f3ae29942651dafb306fbe

**Operating system**: 
Windows 7

**Comment by RichardGe** [comment]
This is because in Guardian::UpdateAI
m_reacState is REACT_AGRESSIVE instead of PASSIVE

**Comment by Warlockbugs** [comment]
It kinda surprised me that we don't have a companion AI yet. GuardianAI seems to be an overkill for companions, mini-pets do absolutely nothing, except for following the master around.

**Comment by killerwife** [comment]
Mini pets are essentially Null AI with follow. But ur right. I will do something about it next month.

**Comment by cyberium** [comment]
Mini-pet are in bad situation currently, they are not considered as pet in some wrong case and they are in some other wrong case. We have to make some more work on them.
And yes if mini-pet got GuardianAI its wrong and have to be fixed.

**Comment by bdebaere** [comment]
Has this been fixed already? Currently for me companions go crazy attacking and returning to you when you are attacking an enemy at range.

**Comment by dagochen** [comment]
I heard someday, they should die through AOE? Anyone knows something about that?

**Comment by killerwife** [comment]
I am working on it with @Warlockbugs . Its undergoing testing and will propably be fixed when I have time to make first version for TBC.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/49252e28ee851b9171ef4a2d58699876ec599de5
