### ISSUE TITLE
[CLASSIC] Socket.cpp - out of array - bug only for Debug mode

### ISSUE THREAD

**Issue by RichardGe** [cmangos/issues#1351]
Doing that is maybe correct in Release mode, but in Debug, it will trigger an error crash

`

	std::vector<int> A;
	A.assign(10,1);
	std::vector<int> B;
	B.assign(10,0);
	std::copy(&A[0], &A[10], &B[0]);

`

this is exactly what is done here :

https://github.com/cmangos/mangos-classic/blob/master/src/shared/Network/Socket.cpp#L277

I'm having crash in debug because  m_secondOutBuffer->m_buffer  is pointing to bad last element in the second argument of std::copy

Commit hash:
029748fbc9d86a62f6fdb396ea33f5e0722231e9

**Comment by cyberium** [comment]
@namreeb we already encoutered that case (during a teamviewer session). Maybe its more clear now and you could do something about it?

**Comment by namreeb** [comment]
That's an interesting bug.  Visual Studio, when compiling in Debug mode, enables assertions making sure that you do not dereference a member past the end of the vector.  Those assertions are disabled in Release mode.  However std::copy does not copy the last element, so in this case it shouldn't exactly matter.

I'm not sure what the 'correct' way to do this is, but I would suggest changing the std::copy line to this:

`memcpy(&m_outBuffer->m_buffer[m_outBuffer->m_writePosition], &m_secondaryBuffer->m_buffer[0], &m_secondaryBuffer->m_buffer[m_secondaryBuffer->m_writePosition]);`

**Comment by RichardGe** [comment]
@namreeb ,
I do agree with you that in this particular case, we would need the good old memcpy.
In this case this is safe.
This is sad that we can't use std::copy, and that C++ standard didn't though of case like that. 
of course we can use 
`std::copy(A.begin(), A.end(), &B[0]);`
if we always want to copy everything.
imo, the best solution would be to do something like that :
`std::copy(&A[0], lastIndex == A.size() ? A.end() :  &A[lastIndex]   , &B[0]);`
but VS2015 will NOT be able to compile that  :(

note, maybe you should also update the  std::copy  of line 263 ?

**Comment by RichardGe** [comment]
if we use memcpy, this is how I see the changes :

`std::copy(&m_outBuffer->m_buffer[length], &m_outBuffer->m_buffer[m_outBuffer->m_writePosition], m_outBuffer->m_buffer.begin());`
to
`memcpy(
			&(m_outBuffer->m_buffer[0]),
			&(m_outBuffer->m_buffer[length]),
			(m_outBuffer->m_writePosition - length) * sizeof(m_outBuffer->m_buffer[0]) );`

and

`std::copy(&m_secondaryOutBuffer->m_buffer[0], &m_secondaryOutBuffer->m_buffer[m_secondaryOutBuffer->m_writePosition], &m_outBuffer->m_buffer[m_outBuffer->m_writePosition]);`

to 

`memcpy(
			&(m_outBuffer->m_buffer[m_outBuffer->m_writePosition]),
			&(m_secondaryOutBuffer->m_buffer[0]),
			(m_secondaryOutBuffer->m_writePosition) * sizeof(m_secondaryOutBuffer->m_buffer[0]) );`

**Comment by namreeb** [comment]
You actually can use std::copy but it's too annoying in my opinion
