### ISSUE TITLE
Database initialization problem with invalid date given

### ISSUE THREAD

**Issue by dvdvideo1234** [cmangos/issues#1354]
**Current behavior**: 
> Processing database updates ...
    Appending Updates/601_DB_Version.sql
    Appending Updates/602_spell_target.sql
    Appending Updates/603_grom_monument.sql
    Appending Updates/604_waypoints.sql
    Appending Updates/605_creature.sql
    Appending Updates/606_creature.sql
    Appending Updates/607_Quests_Test_Flight.sql
    Appending Updates/608_creature_equip_template.sql
    Appending Updates/609_quest_10861.sql
    Appending Updates/610_creature.sql
    Appending Updates/611_gameobject.sql
    Appending Updates/612_quest_14351.sql
    Appending Updates/613_quest_524.sql
    Appending Updates/614_import_corepatch_12944.sql
    Appending Updates/615_Draenei_pt4.sql
    Appending Updates/616_corepatch_12945.sql
    Appending Updates/617_corepatch_12946.sql
    Appending Updates/618_creature.sql
    Appending Updates/619_quest_1147.sql
    Appending Updates/620_quest_9467.sql
    Appending Updates/621_import_corepatch_12947.sql
ERROR 1292 (22007) at line 3: Incorrect datetime value: '0000-00-00 00:00:00' for column 'start_time' at row 12
ERROR: cannot apply Updates/621_import_corepatch_12947.sql
mangos@mangos-VB:~/Documents/setup/MaNGOS/wotlk/db$

**Expected behavior**:  Query to pass

**Steps to reproduce**: sudo ./InstallFullDB.sh
**Client version**: N/A

**Commit hash**: https://github.com/cmangos/wotlk-db/commit/f55827c5b6f9ddc7454b9cec012d82a94a0f298f

**Database version**:  1.0
**Operating system**: Ubuntu 16.04 LTS x64

**Comment by Grz3s** [comment]
https://github.com/cmangos/wotlk-db/issues/60
