### ISSUE TITLE
[CLASSIC] spawntimesecsmax` (...) value lower than `spawntimesecsmin` in log

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#1356]
**Current behavior**: 
on mangosd.exe start log now outputs;

about **60000** messages of;

2017-04-17 10:23:42 Table `creature` have creature (GUID: 17116 Entry: 2256) with `spawntimesecsmax` (120) value lower than `spawntimesecsmin` (300), it will be adjusted to 300.

and another **60000** or so of;

017-04-17 10:23:42 Table `gameobject` have gameobject (GUID: 3 Entry: 187653) with `spawntimesecsmax` (0) value lower than `spawntimesecsmin` (180), it will be adjusted to 180.

The GUID, Entry, min and max spawn times change for every log entry but its the same error message.

**Expected behavior**: 

Probably no error message *shrug*,  the sheer volume is a change from something recent.

**Steps to reproduce**:

1. start mangosd.exe

**Client version**: 

1.12.1

**Commit hash**: 

Latest mangos-classic
commit 5e4bd03efd4c74c82a688abcd28103cdb7c3bb2b

**Database version**: 

Latest Classic-db
commit b204b8286586854a5dfbb4c4863879166fa4bd25

**Operating system**: 

Windows 8.1

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Grz3s** [comment]
@cala you need to use this script:
https://github.com/cmangos/wotlk-db/commit/151a25f66f6fc0f69b2b7b50062264d8bfb4fbe3

**Comment by cala** [comment]
Thanks @Grz3s 

Closed by https://github.com/cmangos/classic-db/commit/c8634435c773b9ac98aaf7bb4cfd00c2ed15b86a
