### ISSUE TITLE
[TBC] WorldSocket::HandleAuthSession

### ISSUE THREAD

**Issue by zmmmspy** [cmangos/issues#1359]
When logging in to one account twice from the same computer the world will crash:

WorldSocket::HandleAuthSession: client build 8606, account TESTER, clientseed 15511501
WorldSocket::HandleAuthSession: (s,v) check s: D172BA101573A77D49C367F18806BA3****3EB0EE2AE2007129F4ABA8D2751BF v: 8745FCB5DE99C385F1ED039AD89****C3656E404165A8872B85F84132E6692A3
WorldSocket::HandleAuthSession: Client 'TESTER' authenticated successfully from **.*.**.**.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  close: Bad file descriptor
Aborted

**Comment by Warlockbugs** [comment]
Connected with https://github.com/cmangos/issues/issues/1177

**Comment by zmmmspy** [comment]
There seems to be no currently working fix then? Thank you for your time.

**Comment by Arnibou** [comment]
World Crash too when internet disconneted when i'm logged IG

**Comment by pkdetlefsen** [comment]
After applying [PR-225](https://github.com/cmangos/mangos-tbc/pull/225) I can only reproduce this issue by doing the following:

1. Start first wow client and log into account but stay at character selection screen.
2. Start second wow client and log into the same account.
3. Server crashes with the following error:

```
WorldSocket::HandleAuthSession: client build 5875, account TEST, clientseed AC0B1CBE
WorldSocket::HandleAuthSession: (s,v) check s: CFE5BB388AD495B4660CB2FAE0CB655915F9A21D16ACE1406422148E52AEA2F7 v: 3DCEB199F17B867276D66992FA60E21745AFEEBDD39D7B31C09A89AA0A69B81B
WorldSocket::HandleAuthSession: Client 'TEST' authenticated successfully from *.*.*.*.
Segmentation fault
```

It also crashes if you start logging into a character on client 1 and then log into the same account using client 2.

If the character is fully logged in on client 1 then the server won't crash when logging in using client 2 no matter if the character state changed or not.

System: Debian 9

**Comment by pkdetlefsen** [comment]
Turns out I was having this issue because I earlier had applied the fix mentioned by @Razfury [here](https://github.com/cmangos/issues/issues/1177#issuecomment-310931994). This caused the core to crash here:

```
void Player::SaveToDB()
{
    // we should assure this: ASSERT((m_nextSave != sWorld.getConfig(CONFIG_UINT32_INTERVAL_SAVE)));
    // delay auto save at any saves (manual, in code, or autosave)
    m_nextSave = sWorld.getConfig(CONFIG_UINT32_INTERVAL_SAVE); <----------
    ...
}
```

Once I removed the fix I could no longer reproduce this issue. Not sure if this helps anyone else having this issue?

**Comment by Thema89** [comment]
Uhm, @pkdetlefsen I didn't applied that fix, but I still can reproduce this issue using a clean cmangos version... did you applied anything else from these "chat hints" earlier to your solution in addition to that lines?

**Comment by SilvioDoMine** [comment]
Since is more dificult now to reproduce this issue, I'm pasting here a fresh core dump to help devs to look into it. https://gist.github.com/SilvioDoMine/76e6746afe9bb0c8d3f3d6bf4052cd8d

**Comment by CabrasDaPeste** [comment]
We need to figure it out a way to reproduce this 100% in order to solve it

**Comment by SilvioDoMine** [comment]
A simple git apply on this .diff can fix this issue. @cyberium said that he will push into the repo soon.

`diff --git a/src/shared/Network/Socket.cpp b/src/shared/Network/Socket.cpp
index b0964f3..37864fe 100644
--- a/src/shared/Network/Socket.cpp
+++ b/src/shared/Network/Socket.cpp
@@ -60,7 +60,8 @@ namespace MaNGOS
 
     void Socket::Close()
     {
-        assert(!IsClosed());
+		std::lock_guard<std::mutex> guard(m_closeMutex);
+		if (IsClosed()) return;
 
         boost::system::error_code ec;
         m_socket.shutdown(boost::asio::ip::tcp::socket::shutdown_both, ec);
diff --git a/src/shared/Network/Socket.hpp b/src/shared/Network/Socket.hpp
index cce351e..db04aeb 100644
--- a/src/shared/Network/Socket.hpp
+++ b/src/shared/Network/Socket.hpp
@@ -64,6 +64,7 @@ namespace MaNGOS
             std::unique_ptr<PacketBuffer> m_secondaryOutBuffer;
 
             std::mutex m_mutex;
+			std::mutex m_closeMutex;
             boost::asio::deadline_timer m_outBufferFlushTimer;
 
             void StartAsyncRead();
`
