### ISSUE TITLE
[CLASSIC][TBC][WOTLK] MySQL Error - ERROR 1046 (3D000) at line 15: No database selected

### ISSUE THREAD

**Issue by dvdvideo1234** [cmangos/issues#1360]
**Current behavior**:  Removing the mangos database gives the following error

**Expected behavior**:  Deleting the database to return success

**Steps to reproduce**:

1. mysql -uroot -p < mangos/sql/create/db_drop_mysql.sql
2. mysql -uroot -p -e "flush privileges;"

**Client version**:  N/A

**Commit hash**:  2e858f417c2c59e61ae26ccc5346464457e1c035 ( wotlk )

**Database version**: 647830bd284f20504cc9cd7de99694a2d599f2e3 ( wotlk )

**Operating system**: Ubuntu 16.04 LTS x64

**Fix suggestion**:  https://github.com/cmangos/mangos-wotlk/pull/219

**Comment by jimmybrancaccio** [comment]
I've attempted to replicate but cannot. All seems to be working fine. Please open a new issue if you're still experiencing problems. Thanks!

``` bash
$ mysql -uroot -e "flush privileges;"
$ mysql -uroot < mangos/sql/create/db_drop_mysql.sql
```

No errors we received during running of those commands. Tested with Classic.

- cmangos/cmangos-classic@b555cd3
- cmangos/classic-db@2c040f9
