### ISSUE TITLE
Mangos website is not working

### ISSUE THREAD

**Issue by dvdvideo1234** [cmangos/issues#1362]
**Current behavior**: N/A

**Expected behavior**: N/A

**Steps to reproduce**:

1. http://cmangos.net/

**Client version**:  N/A

**Commit hash**: N/A

**Database version**: N/A

**Operating system**: N/A

[![cloud_flare.jpg](https://s16.postimg.org/drd74ig11/cloud_flare.jpg)](https://postimg.org/image/qvirh782p/)

**Comment by dvdvideo1234** [comment]
It's kinda .. down again :dagger:

**Comment by cyberium** [comment]
fixed

**Comment by Flaires** [comment]
Again. Same error.

**Comment by EGSilver** [comment]
Still down
