### ISSUE TITLE
[CLASSIC] Mobs Stuck in Casting

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1363]
If a mob starts casting a ranged spell and its target gets out of its line of sight before it finishes the spell, then the mobs casting will not be interrupted properly. The spell orb effects will be stuck on the mob's hands even if it decides to melee afterwards.

https://webmshare.com/4MJ80

**Comment by katz1** [comment]
I made a fix for this, but I will test it for some time before making a PR. Here is the patch:

[0001-Fixed-units-stucking-in-casting-state.txt](https://github.com/cmangos/issues/files/980799/0001-Fixed-units-stucking-in-casting-state.txt)

Currently when a Spell::CheckCast fails right before casting the spell (after the cast bar is full), only Spell::finish(false) is called. This however does not seem to remove the casting orbs from the caster. My fix attempt uses in these cases Spell::cancel() instead of finish, when the spell state is PREPARING. Note that Spell::cancel() calls Spell::finish(false) in this spell state.

**Comment by katz1** [comment]
I found an issue with the fix I posted last week. If I fail a gathering due to not enough skill, the message 'Interrupted' is incorrectly displayed in the client along with the 'Failed attempt' one.

So calling cancel() is too much in every PREPARING case there. The relevant spells which stuck should be properly identified based on some common trait, and the others should not be interrupted.

**Comment by al3xc1985** [comment]
@killerwife this was fixed

**Comment by killerwife** [comment]
Fixed by sending proper packets on interrupt ages ago.
