### ISSUE TITLE
[Classic] Typo in Terenthis dialogue

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1364]
There is a minor typo in one of Terenthis's dialogue. He says: It sounded like a roar.!

![typo](https://cloud.githubusercontent.com/assets/18726138/25760162/c8858492-31d5-11e7-9619-0d3d8ba2f5fd.jpg)

**Comment by Grz3s** [comment]
yes
this is correct one:
```quote
What was that noise? It sounded like a roar.
```
