### ISSUE TITLE
[TBC] Thunder Bluff Zeppelin

### ISSUE THREAD

**Issue by zmmmspy** [cmangos/issues#1365]
![1](https://cloud.githubusercontent.com/assets/28284520/25770071/fdb7a9fa-31f9-11e7-952a-3bea8e47998b.jpg)
![2](https://cloud.githubusercontent.com/assets/28284520/25770072/fdba7fb8-31f9-11e7-9a17-956322d35e06.png)

**Current behavior**: 
Thunder Bluff guards say zeppelin exist.

**Expected behavior**: 
 Guards not mention Zeppelin exists. Wouldn't be a bad idea though.

**Comment by berserkingyadis** [comment]
Still happening.

![screenshot_5](https://user-images.githubusercontent.com/9959527/49333629-64e52700-f5c2-11e8-97bb-4a6a8455a9a9.png)

core commit: 28bb409e106bedba124d6f87dbfacb68abfee406
tbc-db commit: f686443ee9f8404b8479ceefee2224ddf471a820
OS: win 10

**Comment by MantisLord** [comment]
Thank you for confirming.
https://github.com/cmangos/tbc-db/commit/c01366c1ee8a958333e628e3e85d5e681d34d8e6
