### ISSUE TITLE
[TBC] Quest "A Dip in the Moonwell"

### ISSUE THREAD

**Issue by zmmmspy** [cmangos/issues#1366]
![1](https://cloud.githubusercontent.com/assets/28284520/25770975/a58493ac-3211-11e7-997f-37889d1bfd79.png)

**Current behavior**: 
Unable to collect the water as robot during this quest. This quest was known to have issues and was removed in the long run.

**Expected behavior**: 
Collect water. To make life easier just remove this quest. :)

**Comment by Qingle** [comment]
This quest wasn't removed til Cata I believe.

**Comment by killerwife** [comment]
I know a fix, there is a target type bug. Will fix in the future.

**Comment by zmmmspy** [comment]
TY! Build? or release date? Mark fixed?

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/commit/5260cf6977da2a210fcec059352e20dfbd381474 closes this issue
