### ISSUE TITLE
Why not delete session pointer when player is be kicked out because he load same account

### ISSUE THREAD

**Issue by q444781603** [cmangos/issues#1370]
sorry,.I am not good at English.

in old version:

World::AddSession_(WorldSession* s)  this function  will delete old session pointer.  like this：

{
        SessionMap::const_iterator old = m_sessions.find(s->GetAccountId());

        if (old != m_sessions.end())
        {
            // prevent decrease sessions count if session queued
            if (RemoveQueuedSession(old->second))
                decrease_session = false;
			// not remove replaced session form queue if listed
			delete old->second;// delete session pointer
        }
 }

but  now version donot delete session pointer,  i try it , i use same account to kick my online account, some bug come into being.

**Comment by cyberium** [comment]
related to https://github.com/cmangos/issues/issues/1177
