### ISSUE TITLE
[TBC] HandleMoveNotActiveMoverOpcode: Error check is incorrect?

### ISSUE THREAD

**Issue by Harha** [cmangos/issues#1371]
**Current behavior**: HandleMoveNotActiveMover: incorrect mover guid: mover is Player Adminn (Guid: 2) and should be Player Adminn (Guid: 2) instead of Player Adminn (Guid: 2)

**Expected behavior**: HandleMoveNotActiveMover: incorrect mover guid: mover is Player Adminn (Guid: 2) and should be Something SomethingElse (Guid: x) instead of Player Adminn (Guid: 2)

**Steps to reproduce**:

1. Fresh server db and core (28.05.2017)
2. Order flight from Stormwind to Wetlands triggered it for me

**Client version**: 2.4.3

**Commit hash**: 6f829080f8a33be45a09c372cf602357df7264f0

**Database version**: cef3c5967d88704c53cacfe1f8503708bc6ac908

**Operating system**: Windows 10 x64 Education

Just a very very minor thing.

**Comment by cyberium** [comment]
https://github.com/cmangos/issues/issues/880
