### ISSUE TITLE
Visual Studio 2017 Question

### ISSUE THREAD

**Issue by rmzV** [cmangos/issues#1372]
Hi there!
what is the minimum components requirments for compiling Cmangos VS 2017?
As i understand while package consists of around 70GBs.
Can someone point me with absolute minimum list of components?

https://docs.microsoft.com/en-us/visualstudio/install/media/vs2017-modify-workloads.png

**Comment by killerwife** [comment]
You only need Visual C++ and cmake support.

**Comment by rmzV** [comment]
Thank you for reply..
Early, i tryed cmake route, but without succes:(
Small tutorial will be realy helpfull^(

**Comment by Lillecarl** [comment]
https://github.com/cmangos/issues/wiki/Beginners-Guide-Home
https://github.com/cmangos/issues/wiki/Installation-Instructions

Not sure those are 100% up2date, but it's a start! :)

And you indeed don't need the full package, as @killerwife stated

**Comment by rmzV** [comment]
@Lillecarl , i already have working Cmangos system compiled with Visual Studio 2015 (but installation of this product contains a lot of not used staff). Now when Visual studio 2017 is out, i am thinking about "as small as possible setup"

If i understand correctly , what @killerwife said , i need only:
https://www.microsoft.com/en-us/download/details.aspx?id=53840
and
https://cmake.org/download/

in this case i dont need Visual studio programm at all?
currently :
https://github.com/cmangos/issues/wiki/Installation-Instructions 
contains only visual studio instruction, so small chapter with cmake rout will be really welcome.

**Comment by Fabi** [comment]
You need the build tools not the redist
https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017

and cmake installed of course. 

Or just Visual studio 2017 with C++ workload (which isn't that big...)

**Comment by rmzV** [comment]
@Fabi ,thank you, so i setup boost, build tools and cmake,
1) can i open and compile  mangosdVC150.sln  inside cmake now? or there is another steps required (under windows)?
2)so cmake is something like a shell, is there are any visual studio "shell version" to use with build tools?

**Comment by Fabi** [comment]
I bet there are two ways (for wotlk at least) right now.

1. You can configure cmake and generate project/solution files with it (easier with cmake gui).
2. Use the premade mangosdVC150 (141 would be the right name...) solution file.

To build a sln file from the command line you can use the following command:
`msbuild mangosdVC150.sln/OrSomeOtherFIle /p:configuration=Debug/Release /p:Platform=x64/Win32`

**Comment by oppahansi** [comment]
`mangos-classic / mangos-tbc` repositories currently only contain:

- `mangosdVC140.sln`

No other sln files. Only mangos-wotlk contains `mangosdVC150.sln`.
That is the part I am having problems with atm following the official installation instructions.

**Comment by cyberium** [comment]
https://github.com/cmangos/issues/wiki/Installation-Instructions

Its updated instruction with a couple of videos ;)
