### ISSUE TITLE
Provide missing premade mangosdVC150.sln files for mangos-classic and mangos-tbc.

### ISSUE THREAD

**Issue by oppahansi** [cmangos/issues#1373]
**Current behavior**: 
The repositories `mangos-classic` and `mangos-tbc` are missing the premade `mangosdVC150.sln` files for VS2017.

**Expected behavior**: 
The repositories `mangos-classic` and `mangos-tbc` should contain/provide the premade `mangosdVC150.sln` files for VS2017.
Those are referenced in the official **Installation Instructions** on the "**Compiling CMaNGOS and ScriptDev2 (Windows)**" section. 

**Additional Comment:**
`mangos-classic` can still be compiled using `mangosdVC140.sln for Visual Studio 2015`
Did not try `mangos-tbc`.

**Client version**: 
World of Warcraft Classic (1.12.x) for cmangos-classic
World of Warcraft TBC (2.4.3) for cmangos-tbc

**Comment by killerwife** [comment]
You can build them on your own with CMAKE. The idea is to remove all prebuilt .sln.

**Comment by Fabi** [comment]
I gave you some steps in the other issue how to use cmake-gui which should work fine

**Comment by oppahansi** [comment]
@Fabi Described steps in #1372 did not work for me.

I am going to stick to VS2015 until the Install Instructions are updated with instructions on how to build .sln files for VS2017 on windows.

I guess the issue can be closed then. Thank you for your comments.
