### ISSUE TITLE
[CLASSIC] Client Disconnects When Fighting With a RAID Boss

### ISSUE THREAD

**Issue by yushicsm** [cmangos/issues#1375]
**Current behavior**: 
When you are fighting with a BOSS who in a 40 players RAID TEAM（Molten Core）
when disconnect Network Connection
Log the same Account again
you will see your Characters in the The Stockade of Stormwind City and lost raid team

**Steps to reproduce**:

1. In a raid team
2. give your heath to 9999999 and fight with Onyxia or Lucifron in Molten Core
3. Kill the Client (Alt+F4 ）
4. Log the same Account again

**Client version**: 
1.12
**Commit hash**: 
latest
**Database version**: 
latest
**Operating system**: 
win7，win2012

**Comment by jimmybrancaccio** [comment]
Could this possibly be related to #1177?

**Comment by killerwife** [comment]
Should be fixed now. Had several causes.
