### ISSUE TITLE
[CLASSIC]Disconnect when loot

### ISSUE THREAD

**Issue by yushicsm** [cmangos/issues#1376]
**Steps to reproduce**:
1. at least two player in the team
2. looted only by leader
3. kill a boss
4. Loot the Corpse but not get the Item, you will see two names in the distribution list
5. Kill the Client of a player (Alt+F4)
6. Log the same account again
7. the leader won't see the player's name in the distribution list

**Client version**: 
1.12
Commit hash:
latest
Database version:
latest
Operating system:
win7，win2012

**Comment by cyberium** [comment]
Cannot reproduce. It might be fixed.
