### ISSUE TITLE
[CLASSIC] Rooted Melee Creatures Attack Priority

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1378]
**Current behavior**:

Rooted **melee** creatures do not attack the closest enemy when first threat target is out of range.

**Expected behavior**:

Rooted **melee** creatures should switch to the closest enemy when first threat target is out of range.

**Steps to reproduce**:

1. Attack a melee creature with two players
2. Root the melee creature
3. Second threat target moves in melee range
4. The melee creature will not attack second threat target

**Client version**: 
1.12.1

**Commit hash**: 

**Database version**: 
Classic DB version 1.8.5 "Below Blackrock Mountain". For core Classic z2697.

**Operating system**: 
Windows 10

**Comment by killerwife** [comment]
They now have closest priority when melee mob.
