### ISSUE TITLE
Gameobjects with negative spawntime are spawned by default

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1379]
**Current behavior**: Gameobjects which should not be spawned, but instead spawned by a script have a negative spawntime. These are still spawned by default.

**Expected behavior**: Gameobjects with negative spawntime should not be spawned by default.

**Steps to reproduce**:

1. .go 3286 -3670 155 0
2. See that the spawn is active by default
3. .go -6993 -1134 272 0
4. See that the spawn is active by default
5. Et cetera

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
Classic DB version 1.8.5 "Below Blackrock Mountain". For core Classic z2697.
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Did you do .gm off?

**Comment by bdebaere** [comment]
And I'm an idiot.

**Comment by Saltgurka** [comment]
We've all done this mistake at some point or another ;)
