### ISSUE TITLE
[CLASSIC]ResourceExtractor.sh

### ISSUE THREAD

**Issue by Razfury** [cmangos/issues#1382]
**Current behavior**: 
VmapsExtractor is called in the script
**Expected behavior**: 
Vmaps_Extractor should be the correct name in the script
**Steps to reproduce**:

1.  Bring the extractor to your classic 1.12.1 folder
2. open the tool and extract
3.  fails on vmaps extraction becuase vmaps_extractor isn't called right in the script

**Client version**: 
1.12.1
**Commit hash**: 
b44b2a9
**Database version**: 
cmangosDB latest
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Muehe** [comment]
Fix:

```diff
diff --git a/contrib/extractor_scripts/ExtractResources.sh b/contrib/extractor_scripts/ExtractResources.sh
index 06ada2e6e..225c6e32c 100644
--- a/contrib/extractor_scripts/ExtractResources.sh
+++ b/contrib/extractor_scripts/ExtractResources.sh
@@ -163,7 +163,7 @@ fi
 if [ "$USE_VMAPS" = "1" ]
 then
   echo "`date`: Start extraction of vmaps..." | tee -a $LOG_FILE
-  ./vmapExtractor | tee -a $DETAIL_LOG_FILE
+  ./vmap_extractor | tee -a $DETAIL_LOG_FILE
   echo "`date`: Extracting of vmaps finished" | tee -a $LOG_FILE
   mkdir vmaps
   echo "`date`: Start assembling of vmaps..." | tee -a $LOG_FILE
```

**Comment by Muehe** [comment]
@cyberium I have just done a fresh classic installation on Windows to test the new cmake process, and the extraction script is indeed broken. As far as I can tell from the file names in the releases, this issue concerns tbc/wotlk repos as well. Do you want me to PR the fix, or can you just commit it?

**Comment by cyberium** [comment]
Thank you i'll push your fix, no need to PR.
