### ISSUE TITLE
[Classic] Debug crash (calling abort()) on startup

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1383]
http://imgur.com/5zxDoE8
http://imgur.com/N0XjUQW

Win32 release and x64 release neither crashes on start-up and seem to run as expected.

Both Win32 and x64 debug versions call abort() as soon as they have finished starting up.

This issue is exclusive to the classic branch.

I am running windows 10, x64.

Classic in Debug seems to be broken altogether on windows?

**Comment by oppahansi** [comment]
**Confirming:**
mangos-classic **x64 debug** is crashing on startup.
mangos-classc **x64 release** no problems.

http://prntscr.com/fk4ojn - error (same for Win32 debug)

I am using VS 2015, Windows 10 x64

**Comment by Phatcat** [comment]
No longer relevant with the removal of provided solution files.
(debug works fine build using cmake)
