### ISSUE TITLE
[Classic] Hunter's Pet has wrong follow

### ISSUE THREAD

**Issue by Razfury** [cmangos/issues#1384]
**Current behavior**: 
The hunter's pet follows behind the player
**Expected behavior**: 
The hunter's pet should follow beside the player on the left side
**Steps to reproduce**:

1. create a hunter & get a pet
2. summon/call the pet
3. run a straight line and watch the pet follow behind you instead of beside you

**Client version**: 
1.12.1
**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/b44b2a95a6525ce66ba52ffabc0b96e377e5d733
**Database version**: 
https://github.com/cmangos/classic-db/commit/f1bb84e7788500eb23dab31e96fde4160ea208af
**Operating system**: 
Win 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Pet follow is now completely wrong, yes this can be fixed by adjusting Pet Follow angle, but it still wont work the way it worked on retail (encountering obstacles, direction change responsiveness and so on)

**Comment by Razfury** [comment]
ah okay, I mean it doesn't bother me at all I just thought i'd open an issue 💯

**Comment by Phatcat** [comment]
Related issue https://github.com/cmangos/issues/issues/1146

**Comment by Warlockbugs** [comment]
Angle is now adjusted, that should suffice for the time being.
