### ISSUE TITLE
[WOTLK] compiling issue on x64 with VC150

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1386]
Classic compiles both x64 and win32 fine with the vc140 solution and tbc as well, and wotlk compiles both x64 and Win32 with the vc140 solution... the vc150 solution for wotlk compiles Win32 fine, but x64 (both Debug and Release) throws this error;

![billede](https://user-images.githubusercontent.com/1907820/27161661-35ff00a4-517d-11e7-9fb1-3dcc8c442f91.png)

On windows 10 x64.

**Comment by Konctantin** [comment]
need add #include <intrin.h>

**Comment by xfurry** [comment]
This is probably my bad, because when I added support for VC150 I only tested win32 build.
Maybe someone can make a PR, so we can quickly fix this.
