### ISSUE TITLE
Creatures are affected by fire damage from nearby fires

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1387]
**Current behavior**: 
Creatures that are nearby fires are affected by fire damage.
**Expected behavior**: 
Creatures that are nearby fires should not be affected by fire damage. I have never seen this in my entire time playing WoW. At the very least the creatures in the example should definitely not be affected.
**Steps to reproduce**:

1. .go 1922 -4148 41 1
2. Look at the Kor'Kron Elites next to the steps going up to Thrall
3. Enjoy the show

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
Classic DB version 1.8.5 "Below Blackrock Mountain". For core Classic z2697.
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Muehe** [comment]
This is already tracked in #1159 and the other issues linked there.

**Comment by bdebaere** [comment]
Thank you, I searched but apparently not the right keywords.

**Comment by AnonXS** [comment]
Can be closed
