### ISSUE TITLE
Quest Deaths in the Family (354) should not require The Haunted Mills (362)

### ISSUE THREAD

**Issue by brotalnia** [cmangos/issues#1390]
The quest "Deaths in the Family" should not have a previous quest requirement. Currently it requires "The Haunted Mills".

Proof:
https://youtu.be/CVeijybDMN0?t=8m40s
https://youtu.be/8dNMBWh2wxY?t=9m27s

You can see in the videos that both quests are offered to the player simultaneously. That is impossible if one quest requires the other.

**Comment by Tobschinski** [comment]
Classic: https://github.com/cmangos/classic-db/commit/97dc0d956dd5f74e63eb5e07e9dc2c2d1fe1e2f8

**Comment by cala** [comment]
Thanks. 👍
