### ISSUE TITLE
[CLASSIC] J.D. Collie's Dialogue After Quest - Making Sense of It

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1392]
**Current behavior**: 
Completing the last quest J.D. Collie has to offer should trigger a dialogue of more than 3 lines  according to http://www.wowhead.com/quest=4321/making-sense-of-it#comments
"When you finish all of the dicover the pylon quests you accept a quest for the book. Make sure to stick around a few mins afterwards to completely finish the quest. I started to run out of the cave and notice that J.D. Collie was still talking so I went back."
**Expected behavior**: 
There's probably more dialogue, need to investigate with sniffs or something. I couldn't find anything online unfortunately. Maybe someone else will have more luck.
**Steps to reproduce**:

1. Get quest 4321
2. Hand in
3. See only 3 lines of text

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
Classic DB version 1.8.5 "Below Blackrock Mountain". For core Classic z2697.
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Have this script.
