### ISSUE TITLE
[WOTLK] Death Knight's Death Grip Spell Doesn't Pull the Targeted Creature

### ISSUE THREAD

**Issue by Vladskywolf** [cmangos/issues#1393]
**Current behavior**: 
Casting the Death Grip spell only aggros the mob despite seeing the correct spell animation effect. Once aggro'd, the creature runs towards the Death Knight or stays in position casting spells if it's a spell caster.

**Expected behavior**: 
Death Grip should 'force pull' the creature, causing it to fly through the air to within melee range of the Death Knight. See this vid for an example:
https://www.youtube.com/watch?v=BBHoq6oLYqo

**Commit hash**: 
dd29786c8282e7e8fbd791e7671724f77d3bfcf3

**Database version**: 
WoTLKDB v1.0 'Echoes of Northrend' for CMaNGOS-WOTLK 12943
updated to "required_13954_02_mangos_gameobjects"

**Operating system**: 
Server: Ubuntu 12.04
Client: Windows 7

**Further comment**
The Death Grip spell works correctly in my current 'live' build, commit hash "99846c574512da41e6fcaf489219ce280d97cc9f", db version "UDB 0.12.2 (408) for CMaNGOS-WOTLK" updated to "required_12938_01_mangos_scriptdev2_tables".

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Grz3s** [comment]
can confirm...
Funny thing ..that with GM ON... spell still works...(aggro breaks visual effect?)

**Comment by Vladskywolf** [comment]
Good catch, I wouldn't have thought being a GM could change spell behavior so significantly so I didn't even think to try.
But yeah, with 'gm on', it works as it's supposed to.

**Comment by Vladskywolf** [comment]
Having spent many hours compiling different commits, I have found where/when exactly this problem started occuring. Seems it was quite some time ago, I'm surprised no one else has opened an issue about it before. 

I will only list the relevant successive commits. All the others I tried either consistently worked before or didn't work afterwards. In every build where it didn't work, enabling GM mode caused the spell to work correctly.

Version: 12943
Commit: 23ead4a3bea3715bab9d2aa2837bef002e01c3fb
Author: Ono <warlockbugs@users.noreply.github.com>  2016-11-24 02:30:22
Committer: Ono <warlockbugs@users.noreply.github.com>  2016-11-24 02:30:22
Comment: Remove double resilience reduce on DoTs
Status: **DEATH GRIP WORKS AS INTENDED IN THIS BUILD**

Version: 12943
commit: 256c7c7f86fd137f64ae8081a5046f91f21602ad
Author: Cyberium <cybermomo@techemail.com>  2016-11-24 21:14:48
Committer: Cyberium <cybermomo@techemail.com>  2016-11-25 17:46:12
Comment: JustSummoned should be called when original caster is provided.
Status: DOES NOT COMPILE

Version: 12943
commit: fc3e046e4d04215b436d04e3ade87704099acffd
Author: Cyberium <cybermomo@techemail.com>  2016-11-25 17:56:33
Committer: Cyberium <cybermomo@techemail.com>  2016-11-25 17:58:06
Comment: remove more SystemConfig.h reference
Status: DOES NOT COMPILE

Version: 12943
commit: 8a2f4b6e92d3667aecc2734e88360720290264ca
Author: Cyberium <cybermomo@techemail.com>  2016-11-25 17:20:42
Committer: Cyberium <cybermomo@techemail.com>  2016-11-25 17:58:08
Comment: General charm/pet fix
Status: **DEATH GRIP DOES NOT WORK AS INTENDED IN THIS BUILD.**


Having some Java, lots of SQL, and very ancient ANSI C coding experience, I can generally follow well written code, as this is for the most part. In this case however, my lack of C++ skill and the number of files changed from the previous commit have proved to be a stumbling block, not to mention a lack of understanding of how everything ties together in cmangos. I ended up following dead ends because of this, never suspecting changes made for charm/pet would be where the problem was, so I finally decided on the 'brute force' method to track down the problem commit.

Anyway, my apologies, but this is as far as I could take it.

**Comment by cyberium** [comment]
no need to expose mail ;) Thank you for this detailed comment.

**Comment by Vladskywolf** [comment]
[face palm]

Sorry about that. I simply copied what was in the git log, completely forgetting about potential spammers getting the addresses from this page. Shameful I could forget such a thing...

Thanks for taking care of it. When I saw the email I immediately came here to edit them out.

**Comment by Trystanosaurus** [comment]
I'm not sure if this will help locate the problem or not but if you use Death Grip on a monster after you've aggro'd it it works correctly. So it's only broken when being used on a creature that isn't engaged.

You can test this by hitting a mob with Icy Touch then Death Gripping right after, it seems to pull them correctly then.

**Comment by xfurry** [comment]
It does help. Actually I now realized that this happens because of the MotionMaster execution priority.

If you first hit the creature and the apply the death grip, that means that first the creature will chase, then it will jump. Since the jump is the last instruction that will be executed.
However, if you grip a creature which isn't in combat, first the creature will receive the jump instruction, but since the spell will set the creature in combat that will override the jump and the creature will only chase.

I'm not sure how to make this work correctly. Maybe @cyberium  knows.

**Comment by Warlockbugs** [comment]
Motionmaster is being reworked by me, but this is a somewhat lengthy process.

**Comment by Phatcat** [comment]
> if you use Death Grip on a monster after you've aggro'd it it works correctly

This is not the case anymore, doing a death grip on an enemy, agrroed or not, does not make it jump towards you. Spell visual is happening but no actual effect.

**Comment by insunaa** [comment]
This was indeed fixed with https://github.com/cmangos/mangos-wotlk/commit/76f4a250659a5a8a054b7e3ec18fe8b3ba4d092c
closing
