### ISSUE TITLE
can't build wotlk with provided visual studio solutions.

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1394]
**Current behavior**:

![billede](https://user-images.githubusercontent.com/1907820/27260628-1283394a-5431-11e7-95c0-a62d9ae0d21f.png)

**Expected behavior**: 

Should look for the files according to the new folder structure with sub-folders inside 'game'.

**Steps to reproduce**:

Attempt building wotlk with any of the provided sln solution files. ( get this error trying to build any version using vc140 or vc150 - If the provided sln files are no longer supported... why are they still provided?

**Client version**:

Wotlk - the others don't seem to be affected

**Commit hash**:

8111a6c75ef476bdc7961c30c06f40cb325024f7

**Database version**: 

N/A

**Operating system**: 

Windows 10, x64

**Comment by Tobschinski** [comment]
They will be removed this week.

**Comment by Phatcat** [comment]
installation instructions should be updated to reflect these changes as the instructions rely on the provided sln files.

**Comment by Tobschinski** [comment]
My boy @Cyberium is recording some tutorial videos as we speak.

**Comment by Phatcat** [comment]
Wonderful.
