### ISSUE TITLE
Corpse.EmptyLootShow has no effect in group loot

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1395]
**Current behavior**: 
Corpse.EmptyLootShow has no effect in group loot: you cannot right click the corpse to loot and no sparkles. Normal loot untested.
**Expected behavior**: 
Corpse.EmptyLootShow should have the standard looting behaviour but without loot of course inside. Sparkles of normal loot should appear.
**Steps to reproduce**:

1. Set Corpse.EmptyLootShow to 1 in config
2. Make a party
3. Kill something with no loot
4. You won't be able to right click the corpse to loot

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
Classic DB version 1.8.5 "Below Blackrock Mountain". For core Classic z2697.
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Tobschinski** [comment]
That was done on purpose, as far as I remember. Having an empty loot window doesn't really have any benefits. But let's hear that from our loot-god @cyberium.

**Comment by bdebaere** [comment]
As far as I can remember it was implemented because it is blizzlike. But I could be wrong.

**Comment by cyberium** [comment]
Well we can argue about that more if you want but its not a real issue.
Someone want to see that empty loot windows implemented?
