### ISSUE TITLE
Taking a flypath with more than one flystop together

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1396]
**Current behavior**: 
Taking a flypath with your friend works and you fly together. Taking a flypath which consist out of more than one stop, for example Gadgetzan, Tanaris to Feathermoon, Feralas makes it look to your client like your friend stops at the first stop. And vice versa, your friend sees you stopping at the first stop.
**Expected behavior**: 
Taking a flypath together with your friend, he should follow you until the end together with all individual flystops.
**Steps to reproduce**:

1. Make a group (maybe not necessary)
2. Fly from Gadgetzan, Tanaris to Feathermoon, Feralas
3. Your friend stops at Thalanaar, Feralas instead of flying together after the first flystop

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
Classic DB version 1.8.5 "Below Blackrock Mountain". For core Classic z2697.
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cyberium** [comment]
Should be fixed

**Comment by bdebaere** [comment]
@cyberium Can you link the commit please?

**Comment by cyberium** [comment]
Why it doesn't work ingame?
https://github.com/cmangos/mangos-classic/commit/21096ecf853ed2c43a3d9ce3446cb0f89e5c016b
