### ISSUE TITLE
UNIT_FLAG_DISABLE_MOVE is not implemented for creatures

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1397]
**Current behavior**: 
Some units are chained or bound to their location by other means. They should not be allowed to move. Right now they can move.
**Expected behavior**: 
Units with UNIT_FLAG_DISABLE_MOVE should not be able to move, they should be able to do anything else like attack (in accordance with their flags of course). As far as I can tell it's not implemented in code anywhere that creatures with this flag are not allowed to move.

There are units which need this flag to work like they do on retail, when this is implemented I know a few I can add.

**Steps to reproduce**:

1. Find a unit with UNIT_FLAG_DISABLE_MOVE
SELECT
	`creature`.*
FROM
	`creature`
JOIN
	`creature_template` ON `creature`.`id` = `creature_template`.`Entry`
WHERE
	`creature_template`.`UnitFlags` & 4 = 4

2. Attack or aggro it
3. It will move to you

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
Classic DB version 1.8.5 "Below Blackrock Mountain". For core Classic z2697.
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
This flag is considered deprecated after original release. It is not seen on creatures and was replaced with control grant/removal for players. The meaning and usage of it are unknown and naming is likely wrong, that's why it is not implemented.

**Comment by bdebaere** [comment]
"...and was replaced with control grant/removal for players."
Replaced with what? I'm not following.

Thanks, I'll investigate other adjustments in the database to make it work as expected.

**Comment by Warlockbugs** [comment]
SMSG_CLIENT_CONTROL_UPDATE is what replaced for players.

You can't investigate the real name, usage and meaning without sniffs, don't waste your time: https://github.com/TrinityCore/TrinityCore/commit/b36da771857554c5bd652bf8ccc1386d4be607b0

AI and movement generators is what currently controls creature movement, including rooting in place.

**Comment by Warlockbugs** [comment]
The issue should be renamed to "Research the up-to-date naming and meaning of UNIT_FLAG_DISABLE_MOVE"
