### ISSUE TITLE
QuestLevel -1 not implemented

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1398]
**Current behavior**: 
Accepting a quest with QuestLevel -1 shows as grey in the quest log.
**Expected behavior**: 
Quests with QuestLevel -1 should adjust to the player's level as stated in the documentation.
**Steps to reproduce**:

1. .quest add 9029
2. Check your quest log
3. The quest is grey

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
Classic DB version 1.8.5 "Below Blackrock Mountain". For core Classic z2697.
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
It's quite possible that this feature is from TBC and onward.

**Comment by bdebaere** [comment]
If so then we must find what the actual level of the quests is that are now on -1. Need more sources.

**Comment by bdebaere** [comment]
http://wayback.archive.org/web/20060615235237/http://wow.allakhazam.com:80/db/qlookup.html?special=-22 makes no mention of quests adjusting to level. The table has levels set for each quest.
http://wayback.archive.org/web/20060626220252/http://wow.allakhazam.com:80/db/quest.html?wquest=9367 is marked as level 60
http://wayback.archive.org/web/20071009235112/http://www.wowhead.com:80/?quest=9367 is marked as level 60, but "requires level 59" for some reason.
http://wayback.archive.org/web/20071101072713/http://wow.allakhazam.com:80/db/quest.html?wquest=9029 is also marked as level 60, 8 months into BC release
http://wayback.archive.org/web/20071015074116/http://wowhead.com:80/?quest=9029 is marked as level 60

Is this enough evidence to update 9029, 9367, 9368 to 60?

**Comment by Warlockbugs** [comment]
Tagging @cala for this, since this is unique classicdb case.

**Comment by AnonXS** [comment]
Still think some open world pvp quests should use this in tbc.
