### ISSUE TITLE
SMSG_CAST_FAILED is not the correct string for that numerical value

### ISSUE THREAD

**Issue by namreeb** [cmangos/issues#1399]
`SMSG_CAST_FAILED` should actually be `SMSG_CAST_RESULT`.  The proof is in the alpha client:

In the alpha client, `SMSG_CAST_RESULT` has a numerical value of `0x123`.

From the 1.12.1 client:
Notice that these handlers do almost the same thing.  Also, logically, it makes no sense to send something called `SMSG_CAST_FAILED` after each and every spell.

**Comment by cyberium** [comment]
+1 its no sense to send 'SMSG_CAST_FAILED' with 'OK' status.

**Comment by killerwife** [comment]
I dont wanna be an ass, but isnt it dangerous to post this here?

**Comment by namreeb** [comment]
Dangerous how?  I don't understand.

**Comment by Warlockbugs** [comment]
The implication is that posting original symbols is somewhat darker shade of gray than posting own guessworks named by hand. I wouldn't do that personally.

**Comment by namreeb** [comment]
Seems like a drop of water in the ocean to me, but feel free to edit it.

**Comment by Warlockbugs** [comment]
I just shared an opinion, we don't have a consesus policy on this yet.

**Comment by cyberium** [comment]
We have, we have to be careful as all public project in grey zone so i'll edit it ;)
