### ISSUE TITLE
NPC Terenthis should not have a weapon.

### ISSUE THREAD

**Issue by brotalnia** [cmangos/issues#1403]
**Current behavior**: 
Terenthis has an axe.

**Expected behavior**: 
He should not have a weapon.

**Proof**: 
https://youtu.be/_S8TMimuYxU?t=2m
https://youtu.be/nSSOfjaTiTI?t=5m53s

You can see that he does not have a weapon in the retail videos.

http://www.wowhead.com/npc=3693/terenthis

**Comment by brotalnia** [comment]
Well i assumed it would be the same in all. The wowhead screenshot is from 2008 and he doesn't have a weapon there either.

http://www.wowhead.com/npc=3693/terenthis#screenshots:id=77946

**Comment by cala** [comment]
> Well i assumed it would be the same in all

Grz3s was probably meaning that you should mention in which version of the game/database you noticed the issue (Classic, TBC, WotLK).

Terenthis indeed wields a weapon in Classic, I'll fix this.
