### ISSUE TITLE
[Classic] Wrong packet structure for SMSG_QUESTGIVER_QUEST_DETAILS

### ISSUE THREAD

**Issue by brotalnia** [cmangos/issues#1404]
**Current behavior**: 
The structure of the SMSG_QUESTGIVER_QUEST_DETAILS packet is wrong. The emotes are not being sent at all.

**Expected behavior**: 
The DetailsEmotes should be included in the packet. They are played when the quest giver gives you the details of a quest. SendQuestGiverQuestDetails needs to be updated.

**Steps to reproduce**:

1. Talk to a quest giver.
2. Click a quest he is offering you. (It must have a DetailsEmote)

**More Information**: 

You can see that the emotes are commented out here: https://github.com/cmangos/mangos-classic/blob/39ab48e42ad8beacbb3b695c7ce88daca8b5b1cb/src/game/Entities/GossipDef.cpp#L416

If you want proof that these emotes exist in vanilla, here are some videos:
https://youtu.be/jTSyexUNN9E?t=1m21s
Kaltunk does a talk emote when offering the quest.
https://youtu.be/jTSyexUNN9E?t=27m47s
Gar'thok does a yell emote when offering the quest.
https://youtu.be/YcEqpVfrE7U?t=42m28s
Misha Tor'kren does a cry emote when offering the quest.

**Comment by Phatcat** [comment]
https://github.com/elysium-project/server/pull/995/commits/6d31e4d9770f3ba53b83ce319b2c3ea9967ed977

https://github.com/mangoszero/server/pull/23/files
