### ISSUE TITLE
[classic] Error compiling with playerbots enabled

### ISSUE THREAD

**Issue by durotar** [cmangos/issues#1407]
**Current behavior**:
As I said in the title, I have an error compiling the core with playerbots enabled. I use Visual Studio 2013. I have found the problem:
line:
https://github.com/cmangos/mangos-classic/blob/master/src/game/PlayerBot/Base/PlayerbotClassAI.cpp#L436

It says:
bool PlayerbotClassAI::PlayerbotClassAI::FleeFromPointIfCan(uint32 radius, Unit* pTarget, float x0, float y0, float z0, float forcedAngle /* = 0.0f */)

Must to be:
bool PlayerbotClassAI::FleeFromPointIfCan(uint32 radius, Unit* pTarget, float x0, float y0, float z0, float forcedAngle /* = 0.0f */)

As you can see: PlayerbotClassAI is duplicated.

**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/a0f6c74ded8b1302690241bba7403003c3584404

**Operating system**: 
windows 10 64bits

**Comment by Warlockbugs** [comment]
Please, keep in mind that MSVC++ 2013, however, is no longer officially supported. MSVC++ 2015 and newer is recommended.
