### ISSUE TITLE
When Using PlayerBot Some of Them Cannot Cast Spells

### ISSUE THREAD

**Issue by yushicsm** [cmangos/issues#1410]
Warrior : BLOODRAGE
SHAMAN : FLAMETONGUE_WEAPON , WINDFURY_WEAPON

last year ,the bot can cast these spells well
but this year maybe,
they suddenly can't cast them

**Comment by cala** [comment]
@cyberium could you please create a new label "playerbot" or something similar to tag issue that will likely be related to playerbot? Thanks!

**Comment by stfx** [comment]
@cala everyone with push access can edit labels here: https://github.com/cmangos/issues/labels

**Comment by cala** [comment]
Fixed in 
https://github.com/cmangos/mangos-classic/commit/4f24427a55b1148a9a56eac768d83663d321b7de

**Comment by yushicsm** [comment]
> 修正了
> [cmangos / mangos-classic @ 4f24427](https://github.com/cmangos/mangos-classic/commit/4f24427a55b1148a9a56eac768d83663d321b7de)

thanks
