### ISSUE TITLE
[CLASSIC] Seal of Righteousness Rank 1

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1412]
**Current behavior**: 
Two Seal of Righteousness spells with rank 1 are currently in the spellbook: 20154 (which does not mention the judgement effect) and 21084 (which mentions the judgement effect). Is this blizzlike? After all the ability which is on the action bar is spell 21084, so why is spell 20154 added anyway? The information comes from the SkillLineAbility.dbc which loads 20154 as the previous rank of spell 21084. During character creation spell 21084 is taught to the character and this function looks to the previous ranks and learns them as well, in this case spell 20154.

This looks weird **to me** in the spellbook, but I could be wrong:
![image](https://user-images.githubusercontent.com/1436449/27755859-daa3aaac-5df2-11e7-94b4-6735348d8a6d.png)

**Expected behavior**: 
I pose questions if the current behaviour is Blizzlike. Thoughts?

**Steps to reproduce**:

1. Make a new Paladin
2. Open spellbook on Holy page

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
Latest
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Grz3s** [comment]
hi ...
This may be useful here...
Look at this vid ... made in 2009 (wotlk) - BE Paladin
https://www.youtube.com/watch?v=7Whduw2cLEE (Pls look at 2:27)

You will see that Player has first ver of this spell from beginning... and second version (updated) you can buy. (Luckly for us ... player checked whats the dif. between spell he has already and new one.)

**Comment by bdebaere** [comment]
Could this mean that we have to adjust the playercreateinfo_spell table entry from 21084 to 20154?

**Comment by Grz3s** [comment]
I only can say about wotlk ... not sure how it was in vanilla/TBC

**Comment by Warlockbugs** [comment]
It appears that in Wrath they start with 20154 and then upgraded to 21084. 21084 in Classic / TBC is also the first "real" rank with judgment info in it. The question is where 20154 should go. One of procs (25741) is marked "Rank 1.5". It seems, that 21084 should overwrite 20154 and never show it again? I don't think our spell chains support that.

**Comment by Warlockbugs** [comment]
Update: it appears that 21084 is learned via spell 10321 along with Judgement and indeed is rank 1.5. However, its unclear how the our spell chain should look like within given limitations.

**Comment by bdebaere** [comment]
Perhaps the Blizzlike situation is this:
On character creation the spell 20154 and only 20154 is learned;
When the character learns Judgement the spell is upgraded with to 21084 with added Judgement info.

It makes sense because Judgement at this time is unknown to the player, reading the tooltip could lead to confusion and to avoid this Blizzard created this first rank without the effect. This would mean we have to change the playercreateinfo_spell from 21084 to 20154.
As to what actually remains in the spellbook after the upgrade, I would opt for only 21084 but I can't confirm if this is Blizzlike.

I seem to remember something similar like this scenario, but can't confirm.

**Comment by Warlockbugs** [comment]
We need 21084 to overwrite 20154 somehow then, this is not directly supported yet AFAIK. If we put them into the same chain, it will display both AFAIK.

**Comment by bdebaere** [comment]
Wrath of the Lich King video https://youtu.be/RMF2a7Rg1FA?t=29s has only one Seal of Righteousness in spellbook.

**Comment by Grz3s** [comment]
another place ..where same situation happens (second version - player has to buy)
https://youtu.be/oLy8hMW-e48?list=PLEePyUlZKyaSfeEe4T7BRIGFXUBb5uu0_&t=161

**Comment by Warlockbugs** [comment]
Before Wrath, it was Judgement training spell (10321), which taught both Judgement and upgraded version of SoR. Since Judgement spell was removed in Wrath and replaced with new spells, only upgraded version of SoR is left in the trainer's list.

**Comment by bdebaere** [comment]
I couldn't find any more videos with Paladins opening their spellbook. My best guess is what I have already said. This also seems the most logical.

On character creation the spell 20154 and only 20154 is learned;
When the character learns Judgement the spell is upgraded to 21084 with added Judgement info.
We will not add 21084 to NPC's trainable spells.

Do we add an exception in code for this one spell? Learning 21084 unlearns 20154?

**Comment by killerwife** [comment]
The one that does not work with judgement is taught due to ranks even if it is not in DB. That is because this is the only exception to our otherwise working rank system. Which means that the only way currently for it not to be in spellbook, is to remove the spell from spell_template alltogether. And thats hardly a proper solution.

**Comment by Trystanosaurus** [comment]
I've just noticed this issue playing the TBC core.

Trinity had the same issue, discussed here - https://github.com/TrinityCore/TrinityCore/issues/14239
Their solution was in this commit - https://github.com/TrinityCore/TrinityCore/commit/08fdac340c8af7d7426870d3ec51ab88c5dd77db

I don't know if that helps at all.

**Comment by Warlockbugs** [comment]
Fully fixed as of:
https://github.com/cmangos/mangos-classic/commit/4a2641a81cfd1e04bcaf8d947cb9a3d5c9815cc5
https://github.com/cmangos/mangos-tbc/commit/66562ea68dbd2b3d2331a83ada7891ee6256b947
https://github.com/cmangos/mangos-wotlk/commit/6b36025b638b1f6ac89539f598f05016cc9cacf7

Players start with a version without Judgment component; Judgment training replaces it with a similar rank suitable for Judgment; starter version is hidden once a better version is acquired.

It took some time to cook some important core changes which made it possible.
