### ISSUE TITLE
[WotLK] Death Knight's Death Gate spell doesn't return you to original location

### ISSUE THREAD

**Issue by Vladskywolf** [cmangos/issues#1414]
**Current behavior**: 
While at Ebon Hold, casting the Death Gate spell doesn't return you to the previous location

**Expected behavior**: 
From anywhere in the world, casting the Death Gate spell will allow the Death Knight to teleport to Ebon Hold. Casting it again at Ebon Hold should return the Death Knight to their original location.

**Commit hash**: 
315e48d7806e5a82cb585b9c2a664a8e4dbb68d5

Though it's been happening since at least commit hash 99846c574512da41e6fcaf489219ce280d97cc9f, dated September 23, 2015 (12938).

What I notice is that after teleporting to Ebon Hold, a message "Interrupted" is briefly displayed in red text.

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Dramacydal** [comment]
it's pandaria+ behaviour.
Same for Teleport: Moonglade

**Comment by killerwife** [comment]
I can confirm @Dramacydal remark, there was no return feature on moonglade or death gate on retail during wotlk.

**Comment by Vladskywolf** [comment]
Sorry for the false alarm. Having never played WotLK live (only TBC), I went by the description of this spell in Wowhead. Next time I'll make sure to check the changelog, where in this case it becomes apparent this feature was only added to the Death Gate ability in 5.4.0 build 17191.
