### ISSUE TITLE
[CATA] Compile problem and possible work-around

### ISSUE THREAD

**Issue by Vladskywolf** [cmangos/issues#1415]
First I'll start out by saying that I'm aware there is no longer official support for the Cata build. However my understanding (according to a recent forum post) is that Fabian still has some interest in it and may update it from time to time.

Having said that, I'm posting this possible work-around for those who wish to try out the Cata build for themselves but are unable to compile it.

I started by going back through each commit from the latest, but it was a bit time consuming so I checked Travis-ci history for the last successful build which is dated August 13, 2016 (6d44966f75b91d27d78eb14f2a0f5a112f88e855) and was able to compile that. Undeterred, I did a little bit more digging so I could build the latest commit.

Caveat: I only build on a Linux system, so this may or may not be applicable to builds on Windows or OSX.

Problem: Any attempts to compile recent Cata builds results in this message:

> In file included from /home/mangos/cmangos/cata/test/core/src/framework/Policies/ObjectLifeTime.cpp:20:0:
/home/mangos/cmangos/cata/test/core/src/framework/Policies/ObjectLifeTime.h:29:26: error: expected initializer before ‘at_exit’
     void MANGOS_DLL_SPEC at_exit(void (*func)());

I worked around this by removing all references to MANGOS_DLL_SPEC. Once I did that, it compiled fine. Here's how I did it:

- cd to base mangos source directory.

- edit file "src/framework/Platform/Define.h" and remove the following line (it was line 83) for me:
>  \#  define MANGOS_DLL_SPEC __declspec(dllexport)

- Execute the following shell command:
> find ./ -type f -exec sed -i 's/MANGOS_DLL_SPEC //g' {} \;

All this basically does is search through every file for string "MANGOS_DLL_SPEC " (note the space at the end) and removes it.

Might not be the most elegant solution but after the above steps it completed the build process.

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cyberium** [comment]
CMaNGOS doesn't support cata anymore
