### ISSUE TITLE
[CLASSIC] Melee Creatures Moving in Melee Range

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1417]
**Current behavior**: 
I have this unconfirmed feeling that creatures are easier to tank on retail. It happens often when backpedalling that the creature attacking you just walks through you, leading to you backpedalling again to have alle the enemies face you. Rinse and repeat.
This seemed easier on retail from what I remember from WotLK, but maybe someone from vanilla remembers it differently?
This is **not all the time**, but enough to be an annoyance for me that I wanted some opinions.
**Expected behavior**: 
I feel like when you backpedal creatures should never walk through you and start hitting you from behind.
**Steps to reproduce**:

1. Round up some enemies
2. Try and have all of them stay in front of you

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
Latest
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by BareRose** [comment]
Can confirm, enemies often walk through you, meaning you can't attack them with abilities that require you to face the target. Very irritating.

Assuming this is just an issue of values (and not something more complex in enemy AI), would there be any way to figure out the retail ones? We do have plenty of video footage of retail, which might allow for reconstruction, or even better some packet sniffs of an enemy moving up to the player, thus allowing an exact distance to the player to be calculated.

**Comment by cyberium** [comment]
Well i think its more harder than you think. Also can someone can confirm that on retail there is special mechanism to "replace correctly" the creature in front of the player? I mean you can see it adjust slightly itself its distance and position to face the player correctly.

**Comment by Tobschinski** [comment]
Yes.

**Comment by killerwife** [comment]
There are two components to this issue. Mobs should be far away from you based on combat reach if they melee. Second thing is that they should try to unstack (more mobs attacking you, they spread around you slightly)

The problem with this, is that invisible creatures take up "a spot". Empty model, unselectable, unattackable, you guys know the type. These cause jittery behaviour.

So to sum up - fix combat reach of given mob, fix find near point to ignore invisible creatures, tweak find near point so that the spreading out is more blizzlike (currently it isnt).

**Comment by cyberium** [comment]
i remember even some mob that doesn't have enough space to to be in front going in one side, then if there is more mob they even can be in back, in fact all around the player depending the space and the mob amount.
So well we just need to code that "replacement" feature that will be a good challenge. It should be a feasible with movement generator. Someone to take that challenge? ;)

**Comment by killerwife** [comment]
I am progressively fixing combat reach data with my team on TBC and I implemented extra flag that notifies this "stacking" logic to ignore them. Any better idea how to mark mobs to be ignored by this spreading out logic?

**Comment by cyberium** [comment]
I dont get your implementation but if you create a list of visible creature around you can check them via  -> IsVisibleForOrDetect.
I think there is already a searcher that return only visible units around a radius implemented in map. So invisible unit is not a real problem. The problem is how a creature will get assigned a position and keep it during the fight (or even replace itself if a creature in front die)

**Comment by killerwife** [comment]
They are not invisible, they are "invisible" like targeting dummies, empty model, not selectable, invisible to player, but not to client.

**Comment by cyberium** [comment]
killerwife something like float Unit::GetAttackAngle(PreferedPostion) that can be called by creature AI to select a disponible angle. That method will handle all attacker position and should be called in updateAI. Thats may be a way to envisage it.

Target dummies does not need placement and as its not an enemy it will be ignored even if the player enter in combat with it by an aoe (auto out of combat). Empty model should be invisible? not selectable should not be ignored by the placement so its ok. IsVisibleForOrDetect should handle 99% of the cases.

**Comment by killerwife** [comment]
IsVisibleForOrDetect cant handle anything..............................
Those mobs are visible, but they have empty model and you won't notice them without sniff. They are used for displaying visuals and whatnot. I have found no way to do it generically. EXTRA_FLAG_INVISIBLE can't be used, it hides the dummies from client and then you don't see spell visuals.

**Comment by killerwife** [comment]
void WorldObject::GetNearPoint(WorldObject const* searcher, float& x, float& y, float& z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater) const

This is what handles it atm.         MaNGOS::NearUsedPosDo u_do(*this, searcher, absAngle, selector); is what needs to ignore the "invisible" mobs (they are visible, they are sent to client, you just dont see them usually cos no model/cant be selected/attacked). I am asking about ideas how to ignore this search generically, I haven't been able to find one.

**Comment by BareRose** [comment]
Are dummy mobs for spell effects like that in retail? If not then cmangos implementation would be wrong altogether (or a hack anyway).

As for NearUsedPosDo, shouldn't these mobs have some flag or other property that clearly distinguishes them from non-dummy mobs?

**Comment by al3xc1985** [comment]
This was fixed. Prove is in symetry server

**Comment by killerwife** [comment]
Correct, this is fixed, even if in not a blizzlike way because mobs on retail do this on classic, but our system is always an approximation.
