### ISSUE TITLE
[CLASSIC] Taking Boat From Ratchet to Booty Bay and Back Without Getting Off Crashes Game Client

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1420]
![billede](https://user-images.githubusercontent.com/1907820/27744063-7565096c-5dbe-11e7-8f02-41d706ab0cde.png)

steps to recreate;

1. .tele ratchet
2. step on the boat and take it to booty bay
3. do not leave the boat in booty bay, stay on it
4. let the boat take you back to ratchet
5. game client crash on map change (server seems to continue running fine?)

Happens on classic running in debug on win10

Edit*:  @Namreeb
[2017-07-09 17.07.53 Crash.txt](https://github.com/Phatcat/mangos-classic/files/1150334/2017-07-09.17.07.53.Crash.txt)

**Comment by yushicsm** [comment]
The classic client crash very frequently after recent updates

**Comment by yushicsm** [comment]
Most client crash happened when loot the corpse

**Comment by cala** [comment]
@yushicsm could you please open a separate issue and post your crashlog in it, please? The crash you are reporting is unrelated to the one @Phatcat has reported. Thanks.

**Comment by namreeb** [comment]
@Phatcat can you post the full error txt file?  It will be in the Errors subdirectory of the main wow directory.

**Comment by Lillecarl** [comment]
@yushicsm You're saying it happens after recent updates, could you pinpoint which rev this starts at by checking out older revs?

**Comment by yushicsm** [comment]
After lot of tests
The client crash because I made some change on core....
Not the problem of CM classic

**Comment by jimmybrancaccio** [comment]
I've attempted to replicate this today using WotLK and could not. Is this still happening for anyone involved in this thread or may we close this one out?

I will attempt to allocate some time to see if I can replicate it with Classic.

**Comment by jimmybrancaccio** [comment]
I tested this tonight with cmangos/cmangos-classic@b555cd3 and cmangos/classic-db@2c040f9 and could not replicate the issue. If this is still a problem please open a new issue with full details so it can be investigated more.

Of note, I went back and forth between Ratchet and Booty Bay about 4-5 times, staying on the boat the entire time.

**Comment by Phatcat** [comment]
Tried this again and couldn't reproduce either. I found a new issue, though..
