### ISSUE TITLE
[WOTLK] Problem with Scarlet Enclave q.12698 "The Gift That Keeps on Giving"

### ISSUE THREAD

**Issue by Vladskywolf** [cmangos/issues#1423]
**Current behavior**: 
After returning the first ghoul, none are credited to the player nor are they thrown into the pit, they just keep following the player.

**Expected behavior**: 
Every returned ghoul should be credited to the player and thrown into the pit by Gothik the Harvester.

**Commit hash**: 
809fa326c3d74ccceab622842a8604bf3cf86b86

**Database Version**: 
267c480ec5ed39d60eca7415bb9f9264627a2475

**Additional Notes**: 
I have checked this in my (other) test build of 12943, hash 23ead4a3bea3715bab9d2aa2837bef002e01c3fb, and it shows the same problem. However, it works as expected on my live build 12938, hash fbdf049c1187ddf3297b174571db90a94de1bed2. 

Not sure if it helps, but a quick comparison of the npc_scarlet_ghoul section of the script file ebon_hold.cpp shows there are no significant changes, only a declared constant replacing an equivalent boolean value.

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Vladskywolf** [comment]
In the latest build I have tested, the returned ghouls are now being correctly credited to the player. The only issue, admittedly a relatively minor cosmetic one, is that the animation showing them being 'thrown' into the pit is not occurring - they are simply 'killed' by Gothik the Harvester where they're standing. 

**Commit hash**:
9b98854f15751d08aa65d32b96abf92eb8a683f1
(build 13973)

**Database version**:
WoTLKDB v1.1 'The Warsong' for CMaNGOS-WOTLK 13965
ACID 3.3.5a (Wrath of the Lich King) for CMaNGOS-WOTLK (3.3.5a Client)
hash: a9fedfaf62188a86f904b16389df284b82d60afd

**Comment by Grz3s** [comment]
retested 15/12/20 - works correct
