### ISSUE TITLE
[TBC] Bonechewer Raider doesn't despawn pet

### ISSUE THREAD

**Issue by Darexon** [cmangos/issues#1424]
**Current behavior**: 
Bonechewer Raider (16925) doesn't despawn their pet when they leave combat. This can result in many wolves being spawned.
**Expected behavior**: 
Wolf despawns when the Bonechewer Raider leaves combat.

**Steps to reproduce**:
1. Attack a Bonechewer Raider
2. Leave combat

**Client version**: 
2.4.3
**Commit hash**: 
83800aee37c689fbe5e3063e00b62cdf59affb38
**Database version**: 
bd4817518468e452766f05721c4f869c9f6dfc0c
**Operating system**: 
Linux x64

**Comment by AnonXS** [comment]
Summoning Spell 32723 has Duration: ID (21) -1, 0, -1

Resolved with:
```
-- Bonechewer Riding Wolf
('1870601','18706','9','0','100','1','0','5','10500','12500','11','16460','1','0','0','0','0','0','0','0','0','0','Bonechewer Riding Wolf - Cast Festering Bite'),
('1870602','18706','0','0','100','1','8000','8000','15000','15000','11','3149','0','0','0','0','0','0','0','0','0','0','Bonechewer Riding Wolf - Cast Furious Howl'),
('1870603','18706','7','0','100','6','0','0','0','0','41','0','0','0','18','33554432','0','0','0','0','0','0','Bleeding Hollow Riding Worg - Despawn on Evade'),
```

http://www.wowhead.com/npc=18706/bonechewer-riding-wolf#abilities

**Comment by Darexon** [comment]
The more blizzlike solution seems to be despawning on reached home position with Bonechewer Raider mounting according to http://www.wowhead.com/npc=16925/bonechewer-raider#comments and http://www.wowhead.com/npc=18706/bonechewer-riding-wolf#comments
