### ISSUE TITLE
[Player Bot] - Guide could be updated, to refeclect classic server only.

### ISSUE THREAD

**Issue by iWritei** [cmangos/issues#1425]
As far as I can tell player bot is only a core option available in [mangos-classic]. The following guides currently do not indicate that the other server versions do not have player bot core support.

https://github.com/cmangos/issues/wiki/PlayerBot-mod-inside-CMaNGOS-core
https://github.com/cmangos/issues/wiki/Guide-to-build-Playerbot

**Comment by cala** [comment]
We are in the process of porting also the TBC and WotLK branches but I don't have finished that yet. It should be done this week.
