### ISSUE TITLE
[TBC] Thrallmar Grunts and Thrallmar Marksmans not in the Thrallmar Faction

### ISSUE THREAD

**Issue by Darexon** [cmangos/issues#1426]
**Current behavior**: 
Thrallmar Grunts and Thrallmar Marksmans are not in the Thrallmar faction (there may be more NPCs missing that I didn't catch)
**Expected behavior**: 
Thrallmar Grunts and Thrallmar Marksmans should be in the Thrallmar faction 
**Steps to reproduce**:

1. Go to Thrallmar
2. See Thrallmar guards aren't in the Thrallmar faction. 

**Client version**: 
2.4.3
**Commit hash**: 
6e17525bc0ccf54707badb0d784987449c04bc85
**Database version**: 
3cc0a92507523d8195d054016bf413caa0622383
**Operating system**: 
Linux x64

http://www.wowhead.com/faction=947/thrallmar#members contains a full list of Thrallmar members.

**Comment by Saltgurka** [comment]
Thanks, solved in https://github.com/cmangos/tbc-db/commit/7bef58b66c89f6486beb95e8a19b999317197225
