### ISSUE TITLE
Wiki Accessibility

### ISSUE THREAD

**Issue by AnonXS** [cmangos/issues#1429]
Can we get the Wiki Sites on 

https://github.com/cmangos/classic-db/wiki
https://github.com/cmangos/tbc-db/wiki
https://github.com/cmangos/wotlk-db/wiki

https://github.com/cmangos/mangos-classic/wiki
https://github.com/cmangos/mangos-tbc/wiki
https://github.com/cmangos/mangos-wotlk/wiki

linking to

https://github.com/cmangos/issues/wiki ? I think alot of people dont know it even exists.

**Comment by killerwife** [comment]
@cala add a wiki redirect somewhere on classic-db and close this issue. wotlk-db is done, i will do tbc-db

**Comment by cala** [comment]
done
