### ISSUE TITLE
[TBC] Bonechewer Rot Lasts Too Long

### ISSUE THREAD

**Issue by cameronjphillips** [cmangos/issues#1430]
**Current behavior**: 
Bonechewer Rot lasts 30 minutes http://www.wowhead.com/spell=33951/bonechewer-rot
**Expected behavior**: 
Bonechewer Rot should last 30 seconds
**Steps to reproduce**:

1. Get attacked by a Bonechewer Scavenger or Bonechewer Mutant
2. See Bonechewer Rot lasts 30 minutes

**Client version**: 
2.4.3
**Commit hash**: 
6e17525bc0ccf54707badb0d784987449c04bc85
**Database version**: 
56f622f6e5e767aebd92228c7f2d3e3afb9efde4
**Operating system**: 
Linux x64

**Comment by AnonXS** [comment]
http://wowwiki.wikia.com/wiki/Bonechewer_Scavenger?direction=next&oldid=1519736
wotlk though.

**Comment by AnonXS** [comment]
```
ServerToClient: SMSG_AURA_UPDATE_ALL (0x0495) Length: 157 ConnectionIndex: 0 Time: 12/27/2008 05:08:54.000 Number: 586953
Spell ID: 33951
Flags: EffectIndex1, EffectIndex2, Duration, Negative (166)
Level: 59
Charges: 0
Caster GUID: Full: 0xF1300041EC469A62 Entry: 16876 UInt64: 17379391245159668322
Max Duration: 1800000
Duration: 1366951
```
