### ISSUE TITLE
Missing Training Dummies in Orgrimmar

### ISSUE THREAD

**Issue by Darexon** [cmangos/issues#1432]
**Current behavior**: 
There is no training dummies in the Valley of Honor
**Expected behavior**: 
There be training dummies near the Hunter trainers in the Valley of Honor https://www.youtube.com/watch?v=uWfTKzaDe3k
**Steps to reproduce**:

1. Go to Hunter trainers in Orgrimmar
2. See there is no training dummies

**Client version**: 
2.4.3
**Commit hash**: 
Mangos-TBC 6e17525bc0ccf54707badb0d784987449c04bc85
**Database version**: 
TBC-DB 56f622f6e5e767aebd92228c7f2d3e3afb9efde4
**Operating system**: 
Linux x64

**Comment by killerwife** [comment]
This is from wotlk onwards. TBC had no training dummies.

**Comment by AnonXS** [comment]
yes they were added prepatch with new 3.0.0 talent trees.
