### ISSUE TITLE
[Wiki] Dead Link for SQLyog

### ISSUE THREAD

**Issue by Saben65** [cmangos/issues#1433]
https://github.com/cmangos/issues/wiki/Installation-Instructions#software-requirements-windows

The link for SQLyog is dead. The project was moved to https://www.webyog.com/

Alernatively, it can be downloaded from github. https://github.com/webyog/sqlyog-community/wiki/Downloads

**Comment by AnonXS** [comment]
Wiki is editable, should be fine now. :)
