### ISSUE TITLE
[CLASSIC] Curing the Sick Weirdness

### ISSUE THREAD

**Issue by BareRose** [cmangos/issues#1434]
When curing a Sickly Gazelle using the Curative Animal Salve, the Gazelle not only dies (resulting in a "Cured Gazelle" corpse) but also counts as two cured Gazelles for the quest. IIRC quests are in the DB most of the time, so the second issue may just be a duplicate on some type of completion trigger, whereas the first one could be that the Cured Gazelle that replaces the Sickly Gazelle is falsely spawned with 0 health.

EDIT: Turns out the Gazelle doesn't spawn dead, it is simply hostile which causes it to instantly die to your thorns. Without thorns on it will simply attack you.

**Current behavior**:
Sickly Gazelle + Curative Animal Salve = Dead Cured Gazelle, +2 in objective counter

**Expected behavior**: 
Sickly Gazelle + Curative Animal Salve = Alive Cured Gazelle, +1 in objective counter

**Client version**: 
1.12.1

**Commit hash**: 
35dc3b68abb3b534a48553fdc34878bc10d8fde0 (mangos)
8d1abc479571fb9cfeb621d5715bb52abce891cb (classic-db)

**Operating system**:
Windows 7 64-bit

**Comment by Trystanosaurus** [comment]
This still seems to be happening. With thorns on the cured deer instantly attacks you and dies before you even notice it's there. I also got credit for two cures for each deer. It seems like using the salve counts for 1 and killing the cured deer counts for the second. This can be tested with thorns off.

**Comment by cala** [comment]
The main reason for this is that the healing salve spell puts the player in combat with the cured deer/gazelle. Now that critters flee from their enemies, they no longer attack the player, hence do not kill themselves on thorns and thus do not grant additional killing credit. The put in combat things still remains and should not occur but this is probably a more generic issue in targeting, IMHO.
