### ISSUE TITLE
DB merge: raw idea (Disscuss)

### ISSUE THREAD

**Issue by rmzV** [cmangos/issues#1435]
was thinking at late night today:

is it possible to merge vanilla+tbc+wotlk Db's in one?
lets say each item in db will have /vanilla triger/tbc triger/wotlk triger/ collumn
and then vanilla server will use items with "vanilla triger" etc etc...
or better: server will have vanilla set of rules or tbc set of rules

so we will have 1 server and 1 db.. with will reduce time on fixing and support ?

**Comment by ulfgebhardt** [comment]
+1

**Comment by rmzV** [comment]
or what if Wotlk DB  will consists of vanilla with vanilla mechanics. tbc with tbc mechanics and wotlk with wotlk mechanics with all of this parts db still will be blixx like.

**Comment by cala** [comment]
Hi,

Thanks for the suggestion, however this is not an "issue" strictly speaking, so please take the discussion to our forums where it is more suited. Thanks.
