### ISSUE TITLE
[WOTLK] In-Combat/Aggro Indicator Not Always Displaying Actual State

### ISSUE THREAD

**Issue by Vladskywolf** [cmangos/issues#1439]
**Current behavior**: 
There seems to be a problem with the in-combat indicator, meaning the red flashing around your character's UI frame in the upper left corner. Sometimes, if I aggro something while riding by on my mount and keep going instead of stopping to fight, the red flashing will stop but if I dismount and try to re-mount or try to equip something I get the message "You can't do that while in combat". I noticed this happening even if I rode what I considered to be a sufficient distance away, for example during a test run of the DK starting zone, riding up to Death's Breach to where the gryphons to Ebon Hold are, having come up the path on the other side. However it does seem to eventually time out.

**Expected behavior**: 
Your character's UI frame should always flash red while in a combat state and stop flashing when completely out of it.

**Commit hash**: 
eddeff7fe9ba49ee1dc2ae7df31c0b1fca4bf247

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
I can not reproduce this issue as of now. Closing this.
