### ISSUE TITLE
[WotLK] Noxxion and minions should only do nature damage

### ISSUE THREAD

**Issue by Saben65** [cmangos/issues#1440]
https://github.com/mangoszero/database/commit/114b8cb8a05ddf35bd4cbe04e21a50800661e53f

[Noxxion](http://www.wowhead.com/npc=13282/noxxion) and [his spawns](http://www.wowhead.com/npc=13456/noxxions-spawn) [should only do nature damage](http://www.wowhead.com/npc=13282/noxxion#comments:id=187580)  (currently they do physical). He [*may*](http://www.wowhead.com/npc=13282/noxxion#comments:id=12954) have been immune to frost at some point.

- [Patch 1.9 - Jan 2006](http://wowwiki.wikia.com/wiki/Patch_1.9.0#Raids_.26_Dungeons) says he had the correct immunities added. Doesn't go into specifics.
- [MMObase](https://www.mmobase.de/spiele/world-of-warcraft/tipps/279/) says he is immune to frost.
- [Video from 2006](https://www.youtube.com/watch?v=2VmNkbi_jP8) shows him being affected by [Ice Armor](http://db.vanillagaming.org/?spell=7302): not immune to frost?

[WoWWiki](http://wowwiki.wikia.com/wiki/Noxxion)

**Edit:** Was fixed in classic DB already here: https://github.com/cmangos/classic-db/commit/c593ed3eb8917782e88b822f377f28ab1ac90bb5. Just needs to be ported to TBC and WotLK from the looks of it.

**Comment by MantisLord** [comment]
Thanks, it's now fixed in TBC-DB here: 
https://github.com/cmangos/tbc-db/commit/b3b139fc42f6fd8eefb31a1713979d1c9befc5f0

**Comment by cala** [comment]
Poking @Grz3s, only WotLK-DB needs this now.

**Comment by Grz3s** [comment]
https://github.com/cmangos/wotlk-db/commit/5b7ca51e27363d7ac55146fccee5af156ef0fdc2
done thx

**Comment by cala** [comment]
Closed by https://github.com/cmangos/wotlk-db/commit/5b7ca51e27363d7ac55146fccee5af156ef0fdc2
