### ISSUE TITLE
[TBC] Playerbots won't take commands of any kind

### ISSUE THREAD

**Issue by dunjeon** [cmangos/issues#1441]
**Current behavior**: 
/t BOTNAME orders combat TANK or anything like it doesn't work. follow, summon, etc
/t orders does not yield a response

**Expected behavior**: 
/t BOTNAME orders combat TANK 
/t orders > TANK

**Steps to reproduce**:
1.  .bot add BOTNAME
2.  /invite BOTNAME
3.  /t BOTNAME orders combat TANK
4.  /t BOTNAME  orders

**Client version**: 
2.4.3

**Operating system**: 
Windows 10  x64

**Comment by cala** [comment]
Hi,

Do you get feedback when using a command to give bots orders ?
What happens when giving a non-existing command to a bot ?
Does giving orders through /p or /ra work ?

**Comment by dunjeon** [comment]
No feedback is received -- not even with debug whisper on.  The result of /t BOTNAME orders results in a echo of orders (as if you simply whispered the word orders to the player)).  All commands seem to be treated like non existing commands -- they all just echo the word back to the master.

**Comment by cala** [comment]
Thank you for your feedback, I have now a good idea of what is going on about the non-working commands. I should be able to fix that tonight.

**Comment by dunjeon** [comment]
Thumbs high, brother, love your work.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-tbc/commit/a57646491e460d557e7364ca0bba68450891b6cf and https://github.com/cmangos/mangos-wotlk/commit/6668fd0093e4584c5a04e927b182dab36bf2d7da
