### ISSUE TITLE
[WotLK] Compiling CMangos-wotlk with Playerbot fails on Ubuntu Linux

### ISSUE THREAD

**Issue by ssj17vegeta** [cmangos/issues#1443]
**Current behavior**: Does not compile during "make install" phase (strangely enough, I thought you were only linking during this phase, not compiling).

**Expected behavior**: Should compile.

**Steps to reproduce**:

1. In "build" directory, I compiled with cmake .. -DBUILD_PLAYERBOT=ON -DCMAKE_INSTALL_PREFIX=/opt/mangos -DDEBUG=0

2. Then, once finished, make install.

The following error occurs: 

`Building CXX object src/game/CMakeFiles/game.dir/PlayerBot/Base/PlayerbotMgr.cpp.o
/home/pierre/wow/mangos-wotlk/src/game/PlayerBot/Base/PlayerbotMgr.cpp: In member function ‘void PlayerbotMgr::HandleMasterIncomingPacket(const WorldPacket&)’:
/home/pierre/wow/mangos-wotlk/src/game/PlayerBot/Base/PlayerbotMgr.cpp:239:46: error: ‘class PlayerTaxi’ has no member named ‘GetTaxiDestination’
                 uint32 curDest = bot->m_taxi.GetTaxiDestination();

/home/pierre/wow/mangos-wotlk/src/game/PlayerBot/Base/PlayerbotMgr.cpp:256:99: error: invalid initialization of reference of type ‘const TaxiPathNodeEntry&’ from expression of type ‘const value_type {aka const TaxiPathNodeEntry* const}’
                         TaxiPathNodeEntry const& node = flight->GetPath()[flight->GetCurrentNode()];
                                                                                                   ^
^Csrc/game/CMakeFiles/game.dir/build.make:14659: recipe for target 'src/game/CMakeFiles/game.dir/PlayerBot/Base/PlayerbotMgr.cpp.o' failed`

**Client version**: Not relevant.

**Commit hash**: ca8051001c709f668a267fa670388a87adc93b90

**Database version**: Not relevant.

**Operating system**: Ubuntu Linux server edition. GCC version 5.2.1.

**Comment by Phatcat** [comment]
> error: ‘class PlayerTaxi’ has no member named ‘GetTaxiDestination’

https://github.com/cmangos/mangos-wotlk/commit/c1393a25acf2cf0c4b5faa79a57e4b3f04c7a68b

**Comment by NeatElves** [comment]
test
```patch
diff --git a/src/game/PlayerBot/Base/PlayerbotMgr.cpp b/src/game/PlayerBot/Base/PlayerbotMgr.cpp
index af226cf59..22a8fbb03 100644
--- a/src/game/PlayerBot/Base/PlayerbotMgr.cpp
+++ b/src/game/PlayerBot/Base/PlayerbotMgr.cpp
@@ -236,7 +236,7 @@ void PlayerbotMgr::HandleMasterIncomingPacket(const WorldPacket& packet)
                 // 1) end taxi path in far (multi-node) flight
                 // 2) switch from one map to other in case multi-map taxi path
                 // we need process only (1)
-                uint32 curDest = bot->m_taxi.GetTaxiDestination();
+                uint32 curDest = bot->m_taxi.GetNextTaxiDestination();
                 if (!curDest)
                     return;
 
@@ -253,10 +253,10 @@ void PlayerbotMgr::HandleMasterIncomingPacket(const WorldPacket& packet)
                         flight->Interrupt(*bot);                // will reset at map landing
 
                         flight->SetCurrentNodeAfterTeleport();
-                        TaxiPathNodeEntry const& node = flight->GetPath()[flight->GetCurrentNode()];
+                        TaxiPathNodeEntry const* node = flight->GetPath()[flight->GetCurrentNode()];
                         flight->SkipCurrentNode();
 
-                        bot->TeleportTo(curDestNode->map_id, node.x, node.y, node.z, bot->GetOrientation());
+                        bot->TeleportTo(curDestNode->map_id, node->x, node->y, node->z, bot->GetOrientation());
                     }
                     return;
                 }
```

**Comment by ssj17vegeta** [comment]
Seems to fix the compile issue. Thanks a bunch !

Out of pure curiosity, how come are we compiling things on the "make install" phase ? Wasn't it intended solely on linking ?

**Comment by ssj17vegeta** [comment]
Oh, sweet :)

**Comment by cala** [comment]
Fixed.

**Comment by ssj17vegeta** [comment]
Thanks a bunch man. Greatly appreciated. I think this issue can be closed ^^ (I'm afraid I can't do that :p)
