### ISSUE TITLE
Does prebuild release have Playerbot?

### ISSUE THREAD

**Issue by apo126** [cmangos/issues#1447]
Using latest wotlk prebuild release e786f45 and latest database adcbdc8. Server works well without any errors. But in wow, when typing ".bot add BOTNAME", it says there is no such command.

Does prebuild release have Playerbot?
If yes, how to make Playerbot work?
If no, do you plan to release a Playerbot version?

Thank you in advance for your help.

**Comment by cala** [comment]
> Does prebuild release have Playerbot?
If yes, how to make Playerbot work?
If no, do you plan to release a Playerbot version?

No, prebuild release does not have Playerbot. We plan to have two pre-releases: one without Playerbot and one with it (poke @cyberium). Unfortunately this is not currently supported by the Appveyor, so only the one without Playerbot mod is currently available.
