### ISSUE TITLE
[CLASSIC] Game Breaking OOC Health Regain Formulas

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1448]
https://github.com/cmangos/mangos-classic/blob/master/src/game/Entities/Player.cpp#L4892
all these formulas honestly look like... Also who came up with the bright idea of a negative constant? Did they happen to test what happens when you strip, oh, let's say.. a warrior, of all their gear... and give them ress sickness? I'll tell you. They stop regaining health altogether.

All the constants should ALL be positive, for obvious reasons. A constant is indeed supposed to be there on the formula for every single class (also the paladin), and it should be positive.

While they on wowwiki before tbc wasn't sure about the warrior, post tbc they figured it out for pre tbc (probably while figuring out the new formula for the warrior);

http://wowwiki.wikia.com/wiki/Health_regeneration?oldid=222101

    Warrior: Spirit * 0.80 + ?

http://wowwiki.wikia.com/wiki/Health_regeneration

    Warrior Pre-BC | Spirit * 0.80 + 6

As we can see, Spirit * 0.8 + 6 is a hell of a lot cleaner than... Spirit * 1.26 - 22.6 ... And it's also a positive constant...

here are some links to a discussion on the formulas and stuff...;

https://wow.gamepedia.com/Talk:Health_regeneration/Archive01
http://wowwiki.wikia.com/wiki/Talk:Health_regeneration

**Comment by GuybrushGit** [comment]
Dupe https://github.com/elysium-project/server/issues/2160

**Comment by dagochen** [comment]
Can someone say something about a "base crit chance for rogues and warriors"? In my experience there was a base spellcrit chance for any class of 5%, which would explain warrior crits with TF without extra buffs. With the current formulas warriors are at 0.01% chance to crit, which could also explain the crits in youtube videos, but the chance that a warrior had done a video of that particular crit is very low.... 

Maybe someone knows more about that part of the formulas? @Phatcat  you seem to have done some research on that?

**Comment by Phatcat** [comment]
http://wowwiki.wikia.com/wiki/Critical_strike?oldid=349108

**Comment by dagochen** [comment]
Considering your source ....the formulas in the core are wrong?

https://github.com/cmangos/mangos-classic/blob/4e00672d354bcda3d742669cb07fb5e61e5a9e67/src/game/Entities/Player.cpp#L4849

that formula does not return 0% for any level for any warrior/rogue/hunter....?

**Comment by Phatcat** [comment]
unless someone can provide proof which booth counters wow wiki and can defend what is already in the core then yes, those formulas are incorrect.

**Comment by Warlockbugs** [comment]
Honestly, it may be infinite times better if we just take the TBC data from 2.0.1 "Before the Storm" client, figure out possible constant key differencies using known vanilla stats snapshots, and just go from there. At least it will be based on something solid and legitimate and reproducible, rather than questionable guesswork.
But first, that would require DB override tables for TBC .dbcs scaling constants we are interested in.
Vanilla is not my focus interest, so also tagging @cala
