### ISSUE TITLE
[WotLK] Compiling errors on fresh Debian 9 (Stretch) System

### ISSUE THREAD

**Issue by Dainara82** [cmangos/issues#1449]
here is what happend

[ 93%] Built target game
Scanning dependencies of target mangosd
[ 93%] Building CXX object src/mangosd/CMakeFiles/mangosd.dir/CliRunnable.cpp.o
In file included from /home/mangos/wotlk/src/shared/Auth/AuthCrypt.h:23:0,
                 from /home/mangos/wotlk/src/game/Server/WorldSocket.h:29,
                 from /home/mangos/wotlk/src/game/Server/WorldSession.h:31,
                 from /home/mangos/wotlk/src/game/Server/Opcodes.h:32,
                 from /home/mangos/wotlk/src/game/Entities/Unit.h:31,
                 from /home/mangos/wotlk/src/game/Entities/Creature.h:23,
                 from /home/mangos/wotlk/src/game/Globals/ObjectMgr.h:25,
                 from /home/mangos/wotlk/src/mangosd/CliRunnable.cpp:27:
/home/mangos/wotlk/src/shared/Auth/SARC4.h:34:24: error: field ‘m_ctx’ has incomplete type ‘EVP_CIPHER_CTX {aka evp_cipher_ctx_st}’
         EVP_CIPHER_CTX m_ctx;
                        ^~~~~
In file included from /usr/include/openssl/evp.h:14:0,
                 from /home/mangos/wotlk/src/shared/Auth/SARC4.h:23,
                 from /home/mangos/wotlk/src/shared/Auth/AuthCrypt.h:23,
                 from /home/mangos/wotlk/src/game/Server/WorldSocket.h:29,
                 from /home/mangos/wotlk/src/game/Server/WorldSession.h:31,
                 from /home/mangos/wotlk/src/game/Server/Opcodes.h:32,
                 from /home/mangos/wotlk/src/game/Entities/Unit.h:31,
                 from /home/mangos/wotlk/src/game/Entities/Creature.h:23,
                 from /home/mangos/wotlk/src/game/Globals/ObjectMgr.h:25,
                 from /home/mangos/wotlk/src/mangosd/CliRunnable.cpp:27:
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^~~~~~~~~~~~~~~~~
src/mangosd/CMakeFiles/mangosd.dir/build.make:62: die Regel für Ziel „src/mangosd/CMakeFiles/mangosd.dir/CliRunnable.cpp.o“ scheiterte
make[2]: *** [src/mangosd/CMakeFiles/mangosd.dir/CliRunnable.cpp.o] Fehler 1
CMakeFiles/Makefile2:899: die Regel für Ziel „src/mangosd/CMakeFiles/mangosd.dir/all“ scheiterte
make[1]: *** [src/mangosd/CMakeFiles/mangosd.dir/all] Fehler 2
Makefile:127: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
dainara@Server:/home/mangos$

**Comment by Warlockbugs** [comment]
Debian has made the switch to OpenSSL 1.1. Its not backwards compatible with OpenSSL 1.0.
Please, check if you are still able to install [this package](https://packages.debian.org/source/stretch/openssl1.0) from the repo of your distribtuion.

**Comment by Dainara82** [comment]
Thanks for asnwer,
i can't install it couse it is not available in this debian 9 :( 
can i do anything else? is it possible  to change wotlk source files on my machine? if yes what exactly i need to change and how?

**Comment by Warlockbugs** [comment]
Current OpenSSL 1.0 branch is an LTS release, so cmangos chose to stay with it. However, some Linux distros (and some BSD flavors) went ahead with migration to 1.1 this year. Arch maintainers, for example, understand the problem and provide 1.0 package, while Debian maintainers for some reason chose to exclude 1.0.

From my understanding of last year's discussions, migrating cmangos to 1.1 requires some changes to source file that will make it no longer compatibile with OpenSSL 1.0, which is what absolute majority of other distros use, which is not acceptable at the moment. I didn't look into this issue myself, so don't quote me on that.

I am afraid i am unable to provide a solution at the moment, only Debian has issues with compatibility. I can only suggest exploring the ways to get that 1.0 package, either by third party repos or manually.

**Comment by Dainara82** [comment]
i compiled it but it don't work will try anything else tomorrow
but i think an downgrade is not possible :( 
everything else is running  cmangos classic too 
i hope spneone have a way that i can run wotlk  the old one bring me an error, the new one i can't compile :(

**Comment by Warlockbugs** [comment]
I've got a debian testing vm now, let us get a little bit more practical. :smile: 
Here are packages you need to play with:
You can have both of these:
libssl1.0.2
libssl1.1
You can have only one of these:
libssl-dev is 1.1.0
libssl1.0-dev is 1.0.2

Get packages libssl1.0.2, libssl1.1 and libssl1.0-dev and try again.

**Comment by Dainara82** [comment]
You are so great *kiss*

i only need to install
libssl1.0-dev
everything else i had

server running like a charm

**Comment by Warlockbugs** [comment]
Now we also have support for both 1.0 LTS and 1.1 branches out of the box, so the problem for cutting-edge distros should be resolved.
