### ISSUE TITLE
[Vanilla] Periodically dying at the destination flight path

### ISSUE THREAD

**Issue by linuxpng** [cmangos/issues#1450]
**Current behavior**: 
In mangos-classic, since commits past July 28th, taking a flight master seems to randomly cause you to die when hitting the destination.  It does not happen every time, but when it does this seems to be logged to the console:

Flight path finalized in non-final point. Investigate causes. Destination: 0. Player name: Meldran.

**Expected behavior**: 
Not dying when you land on the flight path

**Steps to reproduce**:

1. Taxi between nodes.  It is, seemingly, random

Client version:
1.12.1

Commit hash:
6d5565a1aad679ed10d61c52ceba4318654da829

Database version:
4d2f3c582b8a31895cd351fdc7c48ccb9313e07e

Operating system:
Ubuntu 16.04

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by D33rhunt3r** [comment]
This is also happening on the WOTLK build.

**Comment by Dainara82** [comment]
Can confirm the bug in Classic 1.12.1 , too.
A friend died on landing after me in Stormwind

**Comment by killerwife** [comment]
I need a way to reproduce this every time.

**Comment by Dainara82** [comment]
I will try to reproduce it, 
Ah there was something else, as we landing and my friend died we both flagged with PvP, don't know why
We flying from ironforge to stormwind with lvl 8
He was a little bit behind me
Maybe this informations helping too

**Comment by killerwife** [comment]
‎Oooooooh, I fixed that long ago and I missed it when porting :D
