### ISSUE TITLE
Gurubashi Axe Thrower

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1453]
Gurubashi Axe Throwers should sometimes walk out of close combat and resume combat from a distance of 10 yards (https://www.youtube.com/watch?v=UAuscPlh8yw, watch in 0.25 speed, can be seen all throughout the first third of the video - 1:02, 1:32, 1:57, 2:20, 2:22, 2:54, 2:59) - I have a feeling it's not only the axe throwers who should do this but also most other mobs who have all their power in their ranged abilities, which is most shooter/caster mobs... 

There is no way to sort this using the db in any way that won't seem really hacky, so it probably needs for eventAI to be upgraded further.

**Comment by AnonXS** [comment]
http://www.wowhead.com/npc=11350/gurubashi-axe-thrower#comments

probably linked to them chainstunning people making them back off and resume casting 22887 at range.

@killerwife is working on an ai prototype which might resolve this sort of behavior for npcs.

**Comment by Phatcat** [comment]
Well, I am fairly certain it's not just the axe thrower but a bunch of caster mobs who should attempt to get out of melee range. I am almost 100% sure I personally remember the necromancers of scholomance (those that summon those skeletons) wanting to get out of melee range as well..

So I'm personally not sure it has anything to do with stun. Also there's no direct correlation between if the players are stunned and if the axe thrower will leave close combat, just look throughout the video I linked. Just pay attention to the very first time I made a note of it, at 1.02, the mob runs out of range NOT after having done the axe flurry, but seemingly at random, and the player is not stunned when it happens either.

**Comment by cala** [comment]
Should be fixed with the new EventAI system now. :+1:

**Comment by AnonXS** [comment]
No it's not, their script was just converted to new format, distancing was not added to spell 16075

**Comment by cala** [comment]
Ok, I'll add it soon(tm).

**Comment by AnonXS** [comment]
```
-- Gurubashi Axe Thrower 11350
('1135001','11350','4','0','15','0','0','0','0','0','0','0','1','-229','0','0','0','0','0','0','0','0','0','0','Gurubashi Axe Thrower - Say on Aggro'),
('1135002','11350','4','0','100','0','0','0','0','0','0','0','57','2','25','0','0','0','0','0','0','0','0','0','Gurubashi Axe Thrower - Enable Range Mode on Aggro'),
('1135003','11350','2','0','20','1025','95','0','6000','8000','0','0','11','8269','0','33','0','0','0','0','0','0','0','0','Gurubashi Axe Thrower - Cast Enrage at 95% HP'),
('1135004','11350','0','0','100','1025','5000','15000','23000','28000','0','0','11','24018','0','0','0','0','0','0','0','0','0','0','Gurubashi Axe Thrower - Cast Axe Flurry'),
('1135005','11350','0','0','100','1025','1000','1000','8000','8000','0','0','11','16075','4','512','0','0','0','0','0','0','0','0','Gurubashi Axe Thrower - Cast Throw Axe'),
('1135006','11350','9','0','100','1025','5','30','1500','2000','0','0','11','22887','1','256','0','0','0','0','0','0','0','0','Gurubashi Axe Thrower - Cast Throw'),
```

('1135005','11350','0','0','100','1025','1000','1000','8000','8000','0','0','11','16075','4','**1536**','0','0','0','0','0','0','0','0','Gurubashi Axe Thrower - Cast Throw Axe'),
