### ISSUE TITLE
Does the playerbot has its own worldsession?

### ISSUE THREAD

**Issue by sw1young** [cmangos/issues#1454]
**Current behavior**: 
I guess the playerbot's behavior in the game would be handled in with player's session.
So when many bots in the world, the server will run slowly under less sessions.
**Expected behavior**: 
Creat its own session for each bot like a player.
**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 

**Commit hash**: 

**Database version**: 

**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cyberium** [comment]
You probably mean autonomous bot.
No nothing about that for now.
