### ISSUE TITLE
[CLASSIC][TBC][WOTLK] Deprecation of Database Tables

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#1456]
creature_movement creature_movement_template - tbc-db has removed last usage of the old deprecated fields. I want to remove them now @Grz3s @cala opinions?

Also, questgiver_greeting will soon be exported, it enables full npc_gossip deprecation, would be nice if CDB and WDB worked on removing all its data afterwards.

**Comment by cyberium** [comment]
didn't read the issue but knowing the author is enough for me to close this.

**Comment by killerwife** [comment]
Troll.

**Comment by Grz3s** [comment]
WoTLDB.. fixed old data from creature_movement creature_movement_template long time ago.
textid1 - textid5
emote
spell
model1 - model2 

About npc_gossip -- i dont think thats a good idea to remove it.. theyre lots of gossips that correct ids were never found.

**Comment by cala** [comment]
Clean-up was made also in Classic DB. So feel free to proceed on the removal of deprecated fields.

Regarding npc_gossip I agree with @Grz3s : either we let it untouched, either we move them to npc_text/gossip_menu but with using placeholder IDs.

**Comment by killerwife** [comment]
It already uses placeholder IDs, but not database-side, but core-side. @Mantislord already removed plenty on our end, and it just needs more research. The #1 reason i want to remove it is because many of them are supposed to be in questgiver_greeting and the rest should be in npc_text and gossip_menu. npc_gossip uses npc_text but only assigns it to ONE guid of given creature_template, which we know is wrong. As a result needs to be nuked asap because its not blizzlike.
