### ISSUE TITLE
[WOTLK] Server crash during potion use and exit combat.

### ISSUE THREAD

**Issue by hipejoe** [cmangos/issues#1457]
**Current behavior**: 
Player: UpdatePotionCooldown call sent from Unit: ClearInCombat passes no argument and assumes default of nullptr.

Spellentry lookup occurs but is not sent to AddCooldown, Instead default of nullptr is passed.

**Expected behavior**: 
spellentry lookup should pass to addcooldown instead of nullptr

**Steps to reproduce**:

1. start combat. 
2. take some damage.
3. use portion
4. kill target

**Client version**: 3.3.5a

Suggested fix: Pass spellentry to addcooldown.

if (spellEntry)
    {
        // start cooldowns at server side, if any
        AddCooldown(*spellEntry, itemProto);
    }

    m_lastPotionId = 0;

Sorry, not sure how to push a branch to github, yet. Otherwise I would just push as pull request.

**Comment by cyberium** [comment]
Thank you :)
