### ISSUE TITLE
WOTLK - Players Die when landing at destination flight path

### ISSUE THREAD

**Issue by D33rhunt3r** [cmangos/issues#1458]
Copied from #1450 as the problem seemed common to the WOTLK and Classic builds but only fixed and closed in the classic release.  I've modified the description and other details for this ticket.

Current behavior:
 In mangos-WOTLK, since commits as of 9/10/17, taking a flight master seems to randomly cause you to die when hitting the destination. It does not happen every time, but when it does this seems to be logged to the console:

Flight path finalized in non-final point. Investigate causes. Destination: 0. Player name: Meldran.

Expected behavior:
 Not dying when you land on the flight path

Steps to reproduce:
1.Taxi between nodes. It is, seemingly, random

Client version:
 3.3.5a

Commit hash:
 Don't know how to find this, I've cloned the repository as of 9/10.

Database version:
 Dunno either,  same clone of the repository on 9/10.

Operating system:
 windows server 2012 R2

**Comment by cyberium** [comment]
Thank you it should be fixed :) 👍
