### ISSUE TITLE
[TBC] Missing Quest Giver Greetings

### ISSUE THREAD

**Issue by brotalnia** [cmangos/issues#1459]
First good job on implementing quest giver greetings! I want to share with you some greetings i had found by watching videos. I commited them to Elysium, so you'll have to update the sql to match your db format (locales are in the same table there). The file contains links with exact timestamps to the video sources for the texts. I also found the German versions for some of the texts.

Link - https://github.com/elysium-project/server/blob/development/sql/migrations/20170805164518_world.sql#L25

Here is a list of the quest givers whose greetings it contains:

> Deputy Willem
> Remy "Two Times"
> Guard Thomas
> Farmer Furlbrow
> Gryan Stoutmantle
> Duthorian Rall
> Talin Keeneye
> Sentinel Glynda Nal'Shea
> Thundris Windweaver 
> Onu
> Shindrell Swiftfire
> Gaxim Rustfizzle
> Apothecary Zamah
> Verna Furlbrow
> Salma Saldean
> Apothecary Johaan
> Coleman Farthing
> Executor Zygand
> Magistrate Sevren
> Deathguard Linnea
> Master Gadrin
> Canaga Earthcaller
> Gar'Thok
> Kin'weelay
> Sergra Darkthorn
> Mountaineer Stormpike
> Mebok Mizzyrix
> Wharfmaster Dizzywig
> William Pestle

**Comment by killerwife** [comment]
‎Look in my repo commit in tbc-db where I have added some initial ones that were made by @Mantislord. We added a bunch of that were missing by both elysium and trinitycore                                                                                                                                                                                  ‎

**Comment by brotalnia** [comment]
That's great, you are only missing the greeting for 1 NPC from mine, and the German texts for some of the other NPCs.

253 - William Pestle

English
> Aha! Good day, good day, Master $C! Come, sit down and have a drink. You have an enterprising look in your eye, and I think you'll find speaking to me worth your time...

German
> Aha! Guten Tag, guten Tag, Meister $C! Kommt, setzt Euch und trinkt etwas. Ihr habt so ein Leuchten in den Augen, als wolltet ihr gern etwas tun. Ich denke, Ihr solltet ein paar Wörtchen mit mir wechseln, es lohnt sich bestimmt...

**Comment by brotalnia** [comment]
I found another greeting.

Martie Jainrose (342)
https://youtu.be/dtwK_FXCgNs?t=40s
> Hail, $n. Welcome to my humble garden. The weather has been perfect lately. Let us hope it holds steady for a ripe harvest.

**Comment by MantisLord** [comment]
Original link in this issue is now broken.
I think mostly everything @brotalnia mentioned here now has been added.

Please open new issue for any more missing texts.
