### ISSUE TITLE
Locales Npc-texts problem

### ISSUE THREAD

**Issue by RazzorX** [cmangos/issues#1460]
1) Sorry for my bad english...
2) For testing- and translation purpose, i have inserted [this](https://github.com/cmangos/tbc-db/commit/63126a1b3306253401d71d349b81fc662569e857#diff-c4b9bfeb5054dbf403b1017499185358R28) in my WotLK-DB
3) I'm using a german translation (.loc3)

After commit [40ae84a](https://github.com/cmangos/mangos-wotlk/commit/40ae84a4ac9634bd5734f8b0df9061de8aa2c5a4) it seems, that all Npc-texts ingame appears in english.
Only if i type ".reload locales_npc_text" and delete all client cache files, all Npc-texts are in german again.

Btw, translations in table "locales_questgiver_greeting" do not seem to be loaded "properly", texts are ingame in english only.

> 2017-09-13 13:42:53 Loading Questgiver Greetings...
2017-09-13 13:42:53 >> Loaded 0 questgiver greetings.

> 2017-09-13 13:42:54 >> Loaded 0 locales questgiver greetings.

(51 entries in questgiver_greeting and 6 entries in locales_questgiver_greeting)

**Comment by RazzorX** [comment]
With commit [206955f](https://github.com/cmangos/mangos-wotlk/commit/206955f6af192a801a63c811d55347bf7a2c8a60), translations for NPC texts are working again. Thanks!

Translations in Table "locales_questgiver_greeting" are... please look at the picture, i think it explain it...
![npc_text](https://user-images.githubusercontent.com/18652247/31176126-026624f6-a912-11e7-949b-fbfe9dfae3c9.png)

Once again : I'm using a german translation (.loc3) !

**Comment by killerwife** [comment]
Ok, ill look at it.

**Comment by killerwife** [comment]
Did you remove client cache?

**Comment by RazzorX** [comment]
Hi, yes several times, alway the same.

TEXT_LOC_1-8 entrys are only for testing purpose in the database.
Because i could not understand why the translation in Text_loc3 is not displayed.
It looks like it can only Text_loc1 be displayed, regardless other translations.

**Comment by killerwife** [comment]
The problem if it exists is in:
void Player::SendPreparedQuest(ObjectGuid guid) const
line
        sObjectMgr.GetQuestgiverGreetingLocales(guid.GetEntry(), type, loc_idx, &title);

I don't have a foreign client other than english, so I can't help with debugging this. If you can put a breakpoint and look there.

**Comment by RazzorX** [comment]
@killerwife  Thank you for trying to help!

Commit [8445563](https://github.com/cmangos/mangos-wotlk/commit/8445563bd78d0b21d5e4338dc36e037850e9e449) fix this issue. Thanks!
