### ISSUE TITLE
A debuff from a dead or out of combat NPC does not affect you

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1461]
**Current behavior**: 
If you are hit by a DoT and the creature dies or leaves combat, the spell will keep on missing.
**Expected behavior**: 
Creatures dying or leaving combat (evading) shouldn't have any effect on their debuffs on you.
**Steps to reproduce**:

1. Find a creature which casts a long lasting DoT on you
2. Fight it
3. Run / Kill it
4. Notice the DoT damage missing

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 

**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
I confirm this.

**Comment by killerwife** [comment]
‎I have a fix somewhere in the missing months of backports. I will see tomorrow morning what I can do about it.

**Comment by Phatcat** [comment]
Hmm... This issue must be 'somewhat recent'... Because this wasn't an issue a year ago; 

https://github.com/cmangos/issues/issues/1103
> Can be reproduced easily by going to the northern part of Felwood to the Toxic Horrors, then pull 2 or 3 into combat at the same time; notice how the dots don't seem to ever get a tick in on you, put gm mode on and leave the mobs; notice how the dots start ticking on you.

**Comment by killerwife** [comment]
Dealt with. https://github.com/cmangos/mangos-classic/commit/314a113f39a3f634f1d1d11f41e7fdf28c137372
