### ISSUE TITLE
[CLASSIC] Quest of Vision in Tauren Teaches Wrong Spell as Reward

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#1462]
**Current behavior**: 
"Quest of Vision" in Tauren starting area erroneously says it will teach you mark of the wild as quest reward

**Expected behavior**: 
Quest rewards without trying to teach a spell not applicable to my class

**Steps to reproduce**:

1. Level a tauren to 5 or 6 
2. Pick up "Quest of Vision"
3. Complete quest

**Client version**: 
1.212

**Commit hash**: 
git rev-parse --verify HEAD
731e39ad76d28d69cd7e04cad3246b748e79d060

**Database version**: 
$ git rev-parse --verify HEAD
8d369bdbe0222b17fea45d1c8dca6af940e2713c

**Operating system**: 
Linux/wine

**Comment by Saltgurka** [comment]
There is no quest named "Quest of Vision". Maybe you mean Rite of Vision? (http://db.vanillagaming.org/?quest=772)

**Comment by linuxpng** [comment]
Ah yes.  My apologies.  The quest turn in did not say "The following spell will be cast on you:"  I can't recall it exactly, but it implied it would be taught to you.  Just a wording issue.

**Comment by bdebaere** [comment]
Same issue for: http://db.vanillagaming.org/?quest=755
The text reads: "You will learn:". The client creates this text based on SMSG_QUESTGIVER_OFFER_REWARD.

**Comment by killerwife** [comment]
Both quests now work as intended.
