### ISSUE TITLE
IsSingleTargetSpell doesn't work

### ISSUE THREAD

**Issue by Komaeda91** [cmangos/issues#1464]
**Current behavior**: 
mage can Polymorph any numbers of creature
**Expected behavior**: 
mage can only Polymorph one creature at the same time
**Steps to reproduce**:

1. create one mage characters
2. choose one creature and cast Polymorph
3. choose another creature and cast Polymorph,you will find ,both of them are be Polymorphed

**Client version**: 
latest version
**Commit hash**: 
8e44ff736bf95796dcbf6fa260478ad0ed54e9b9
**Database version**: 
latest version
**Operating system**: 
windows 7 sp1

**Comment by user10001** [comment]
[CLASSIC] I can confirm that mage can polymorph multiple creatures at once. It affects all the ranks of  as well.

###This is what I have found so far:

IsSingleTargetSpell(SpellEntry const* spellInfo) definition is located in SpellMgr.h
struct SpellEntry definition is located in DBCStructure.h
struct ClassFamilyMask definition is located in DBCStructure.h
MECHANIC_POLYMORPH is in Mechanic enum located in SharedDefines.h

polymorph rank 4 entry is in spell_template table in mangos database with id=12826

SELECT SpellName, Rank,SpellFamilyFlags, SpellFamilyName, Mechanic FROM spell_template WHERE Id='12826';

gives that SpellFamilyFlags is 3238264832
SpellFamilyName is 3
Mechanic is 17

###Check this line:
https://github.com/cmangos/mangos-classic/blob/5557bf3cc688ff5940b637f5d86e0e7c6b71f9b5/src/game/Spells/Spell.cpp#L4081

**Comment by Warlockbugs** [comment]
Everything else works, this commit is the culprit: https://github.com/cmangos/mangos-classic/commit/b90abe9a0f450dafc619f2f9379c47104f35540b
