### ISSUE TITLE
[classic]some Boss can't be attacked

### ISSUE THREAD

**Issue by yushicsm** [cmangos/issues#1466]
**Current behavior**: 
Bloodlord Mandokir (11382) ,Witch Doctor Zum'rah (7271) can't be attacked，but they can attack the players.
**Steps to reproduce**:
Easy to test ,maybe more Boss have this problem

**Client version**: 
latest version
**Database version**: 
latest version
**Operating system**: 
windows 2012

**Comment by oppahansi** [comment]
@Phatcat and me will adress ZG bosses in near future.

**Comment by yushicsm** [comment]
not only in ZG
Witch Doctor Zum'rah (7271) in Zul'Farrak
Pyroguard Emberseer(9816) in Blackrock Spire
I only find these ,but there must be more.

**Comment by yushicsm** [comment]
in boss_mandokir.cpp 
''m_creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);''
when i change it to "m_creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PLAYER);"
Bloodlord Mandokir (11382) can be attacked again.

**Comment by cala** [comment]
Bloodlord Mandokir and Pyroguard Emberseer are working fine now. They were fixed a few weeks ago.
Can you tell if Witch Doctor Zum'rah is also OK ?

**Comment by AnonXS** [comment]
boss_zumrah might also be missing removeflag here:

https://github.com/cmangos/mangos-classic/blob/39ab48e42ad8beacbb3b695c7ce88daca8b5b1cb/src/game/AI/ScriptDevAI/scripts/kalimdor/zulfarrak/boss_zumrah.cpp#L103

**Comment by nekolepsy** [comment]
I've submitted a patch pull request to mangos-classic to fix Witch Doctor Zum'rah

**Comment by cala** [comment]
Fixed thank you.
