### ISSUE TITLE
[CLASSIC] Mage Tier 3 6-set Bonus Not Being Applied

### ISSUE THREAD

**Issue by Ginnerskov** [cmangos/issues#1467]
**Current behavior**: 
After casting spells on Patchwerk for 5 minutes straight, the buff were never applied to him.

**Expected behavior**: 
Having 6-set, should make the mage have a chance to apply the aura "Elemental Vulnerbility" http://db.vanillagaming.org/?spell=28771  to the target 

**Steps to reproduce**:

1.  Equip 6 piece T3 and test.
2. 
3. 

**Client version**: 
1.12.1

**Commit hash**: 
Don't know how to see this piece of info - Tested 25th of September 2017 around 2 am cest.

**Database version**: 
Don't know how to see this piece of info - Tested 25th of September 2017 around 2 am cest.

**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Tested set and managed to get proc. Both TBC and vanilla.
