### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Unholny** [cmangos/issues#1469]
**Current behavior**: 
I tried to compile cmangos-classic but it failed @ 71%.
I can see that travis-cli couldn't build the latest commit, what's up?

**Expected behavior**: 
It should've compiled successfully.

**Steps to reproduce**:

1. Follow the installation guide;
2. cmake
3. make

**Client version**: 

**Commit hash**: 9d0d662e8419ba234468484502c78babb1f4ad19

**Database version**: -

**Operating system**: Ubuntu 16.04 LTS

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)
https://gist.github.com/anonymous/11750a405c0790ac355e3e32f284c34f

**Comment by Warlockbugs** [comment]
Should be fixed.

**Comment by Unholny** [comment]
Thank you very much!
