### ISSUE TITLE
Random_templates in ACID

### ISSUE THREAD

**Issue by Saltgurka** [cmangos/issues#1470]
To prevent excessive scattering of files with the new random_templates system and ACTION_T_TEXT_NEW we should add this to the bottom of the ACID file in all 3 DBs (ofc classic should only have the classic templates etc): 

```sql
-- =======================================================
-- Random Templates used by ACID
-- =======================================================
-- Classic IDs 0 - 9999
REPLACE INTO dbscript_random_templates (id, type, target_id, chance, comments) VALUES
(6,0,-1559,0,'8506 - Random Spawn Texts'),
(6,0,-1560,0,'8506 - Random Spawn Texts'),
(6,0,-1561,0,'8506 - Random Spawn Texts'),
(6,0,-1562,0,'8506 - Random Spawn Texts'),
(6,0,-1563,0,'8506 - Random Spawn Texts'),
(6,0,-1564,0,'8506 - Random Spawn Texts'),
(6,0,-1565,0,'8506 - Random Spawn Texts'),
(6,0,-1566,0,'8506 - Random Spawn Texts'),
(6,0,-1567,0,'8506 - Random Spawn Texts'),
(6,0,-1568,0,'8506 - Random Spawn Texts');

-- TBC IDs 10000 - 19999
REPLACE INTO dbscript_random_templates (id, type, target_id, chance, comments) VALUES
(10011,0,-1543,0,'17918 - Random Despawn Texts'),
(10011,0,-1544,0,'17918 - Random Despawn Texts'),
(10011,0,-1545,0,'17918 - Random Despawn Texts'),
(10012,0,-1546,0,'17918 - Random Spawn Texts'),
(10012,0,-1547,0,'17918 - Random Spawn Texts'),
(10012,0,-1548,0,'17918 - Random Spawn Texts');

-- WOTLK IDs 20000+
REPLACE INTO dbscript_random_templates (id, type, target_id, chance, comments) VALUES
```

There we will add any random templates containing ACID texts. That way we don't have to create an extra file whenever we want to randomize texts in ACID with ACTION_T_TEXT_NEW. Templates used in dbscripts should still be kept in separate files and not in the ACID file.

Any objections or opinions on this? If not I will add it to TBC acid soon

@Grz3s @cala @Tobschinski

**Comment by killerwife** [comment]
👍

**Comment by MantisLord** [comment]
I think it's a good idea. This way we don't have to leave ACID file in order to determine which creature_ai_text IDs correspond to a creature.

**Comment by Grz3s** [comment]
I'm OK with it.

**Comment by Saltgurka** [comment]
Done in TBC: https://github.com/cmangos/tbc-db/commit/387cfcf649b49990342e6cee4fea541f1e053046

**Comment by Grz3s** [comment]
WoTLKDB also :)

**Comment by AnonXS** [comment]
can be closed
