### ISSUE TITLE
[WOTLK] NPC-Text Translation Bug

### ISSUE THREAD

**Issue by RazzorX** [cmangos/issues#1472]
-- Sorry for my bad english...
-- I'm using a german translation (GMDB)

This issues has nothing to do with #1460.
This must be an old bug, which I noticed many years ago.

**Current behavior**: 
If you talk with an NPC, which has several texts (text1_0, text2_0 etc in npc_text), then text3_0 and text3_1 are not translated (in my case, not in German).
The problem is, however, only when you talk with Female NPCs, in Male NPCs the text is translated normally!
All other texts (text1_0, text2_0 etc) do not have this problem. Other languages may also be affected. (not tested)

**Expected behavior**: 
All texts that have a translation in locales_npc_text , should always be displayed.

**Steps to reproduce**:
You must use a language other than English.
.go creature 57322 or 59443 and talk several times with a Female NPCs until Text3_0_locX or Text3_1_locX is displayed. (or not)

**Client version**: 
WotlK 3.3.5a (3.3.5.12340)

**Commit hash**: 
[e2407b9](https://github.com/cmangos/mangos-wotlk/commit/e2407b9927dede38f4922908039e71e351b82df6)

**Database version**: 
[f1301d9](https://github.com/cmangos/wotlk-db/commit/f1301d993cd03fc2e773e46d66d6ff69c1d09fe0)

**Operating system**: 
Windows 7 64bit

**Comment by RazzorX** [comment]
![Picture](https://user-images.githubusercontent.com/18652247/31277801-fe972388-aaa2-11e7-984a-49f3414e3a2c.png)

**Comment by Warlockbugs** [comment]
Fixed in:
https://github.com/cmangos/mangos-wotlk/commit/79f2b26f44fa25c8d1fce065b1fedbc9e76925dc
https://github.com/cmangos/mangos-tbc/commit/6b27f4c3985664751733dabd2e892ceeee98814d
https://github.com/cmangos/mangos-classic/commit/5ed81f92a55786402097e308944fbf6dbd8937bd
