### ISSUE TITLE
[WOTLK] Auctionhouse searching for unknown recipes not work correctly

### ISSUE THREAD

**Issue by Dainara82** [cmangos/issues#1473]
hi,
i found an issue in the auctionhouse,
when you looking for useable recipes you found all you can lern with skill but the knowes recieps it found too,

normaly the known recipes you don't find

**Comment by jimmybrancaccio** [comment]
Hello, thank you for taking the time to submit these issues. Please resubmit them if you're still having issues with them utilizing the bug reporting template (shown when you open a new issue).
