### ISSUE TITLE
[WotLK] Dungeonfinder don't work

### ISSUE THREAD

**Issue by Dainara82** [cmangos/issues#1474]
Dungonfindet don't work

i played last time on an other privat server WotLK too  and there work the Dungeonfinder

**Comment by Grz3s** [comment]
Yes if i remember correctly @kvipka had it working fine on his repo :o

**Comment by Dainara82** [comment]
when will it implement here?

**Comment by AnonXS** [comment]
Dublicate https://github.com/cmangos/issues/issues/841
