### ISSUE TITLE
[ALL] Character don't loging out

### ISSUE THREAD

**Issue by Dainara82** [cmangos/issues#1475]
I have this issue in Classic and Wotlk,
i think in BC is it too,
when i log in an character and log out or kick this character, it will stay in world until i restart the server 
this is i think 2 or 4 weeks befor i don't had this issue

**Comment by Dainara82** [comment]
OK i tried to look what happend, i found something out, but i don't know why it is so,
When someone go online with an character and go offline
in the Character.log  all ok  character logging in  and out

In "character" Database 
in the  "Online"  field from this character   it will don't change to 0
it stay 1   so the character don't log out from the Database!

I hope you understand what i try to telling you :)

this is in Classis  and WotLK.  if it is in BC i don't know

**Comment by ulfgebhardt** [comment]
#1177

**Comment by killerwife** [comment]
I found the cause. Will fix in coming days.

**Comment by Dainara82** [comment]
when you think you can fix this issue?

**Comment by ulfgebhardt** [comment]
This is an intentional bug.

**Comment by pkdetlefsen** [comment]
I'm no longer having this issue after merging changes from September 16th until now into my own fork. I couldn't find a commit mentioning fixing this issue, but I guess it has been fixed? :)
