### ISSUE TITLE
[CLASSIC][TBC][WOTLK] Missing NPC Movement in Stratholme

### ISSUE THREAD

**Issue by stan84** [cmangos/issues#1476]
Patchwork Horrors (id 10414),
Eye of Naxxramas (id 10411),
Rockwing Gargoyles (id 10408),
nerubians, 
scarlet crusaders are standing or does random movement.

As i can remember in old time some of them should patrol instance along certain path.

Found some missing data in YTDB database http://svn2.assembla.com/svn/ytdbase/Mangos/Wotlk/ 
Im did already already some backports on my test realm. Unfortunately the YTDB npc guids are different to UDB has, and needs some manual testing and adjutment.

Client version -classic, tbc, wotlk.

**Comment by cala** [comment]
Thanks for your report. I'm surprised: all of this was added to the Classic branch in version 1.7 of the database that was released last year. I've checked right now and patrols were working as they should. Can you confirm your report, please?

I can't tell for sure that TBC-DB and WotLK-DB had this ported, but they are usually only a few months behind Classic DB in terms of keeping up (and vise versa) so it should also be there.

**Comment by stan84** [comment]
just did fresh instalation of both databaseses ( classic and tbc), and after querrying for creaures with movement type 2, in map 329 mysql returns values:
TBC- DB: SELECT * FROM tbcdb.creature where MovementType=2 and map=329; -- responds 0 row(s) returned
Classic db look fine because:
SELECT * FROM classicdb.creature where MovementType=2 and map=329; -- 37 row(s) returned


![obraz](https://user-images.githubusercontent.com/3476555/31584374-705ce186-b1ad-11e7-82cb-ba02e293de9f.png)

**Comment by AnonXS** [comment]
Resolved in TBC. - 37 rows

**Comment by al3xc1985** [comment]
I guess ir ia fixed. You did export from like an year ago. Ehat do you think @killerwife ?
