### ISSUE TITLE
[CLASSIC][TBC][WOTLK] Collaboration Between Classic/TBC/WotLK for Instances

### ISSUE THREAD

**Issue by MantisLord** [cmangos/issues#1479]
This isn't so much an issue as it is an open discussion regarding collaboration and shared data.

The issue of guid conflicts between the three databases (CDB, TDB, WDB) has been discussed already multiple times in the past. The conclusion seems to be that everything is too complex at this point to warrant a full re-guid of all creatures/objects. This process would be prone to errors and could take too much effort.

Guid/id/entry mismatches add an inherent level of difficulty when it comes to porting fixes between DBs, and we only worsen the problem day by day.

@Saltgurka and I have been thinking about dungeons and raid content recently (specifically how much data is shared across expansions for various instances). Our current data in TBC-DB is out of sync with CDB for many of these instances, so it makes working on that vanilla content very hard for the TBC team (and I'm sure the WDB team) at times.

Because of this challenge, we'd like to propose creating and maintaining a file structure allowing for easier syncing of content fixes within these instanced maps. 

Here's what this could look like using Naxxramas as an example:
https://gist.github.com/MantisLord/c7cd61725c581ef53495f2a4a5682d7a
When I run this in TBC-DB, I get a complete picture of all the data ported from CDB for Naxx.

While creating this file, I followed a general template like this:
https://gist.github.com/MantisLord/f763655263dc67ba1e2104e150f9543d
-- copy paste outputs from helper script <-- Helper script is linked below
-- copy paste section for dungeon from acid_*.sql <-- This is just an idea we had to include ACID for the dungeon/instance in this file instead of confining everything to single ACID file. This makes sense to us because the ACID files are already split based on region/map.
There are some details surrounding that which we aren't sure about yet though, including how to handle shared creature_ai_text entries. 

Since none of these files are created currently, I also made a SQL script allowing for extraction and re-guiding of instance data which was used to generate the above Naxxramas example:
https://gist.github.com/MantisLord/56121289e0ec8803e2ea43dab8d4c512

The idea is all that you need to do to generate the data for the initial file for a map is to enter the mapID, choose a free guid range for objects/creatures, and include any misc dependencies like dbscripts and conditions.
We think that having a file per dungeon like this would really help promote collaboration between the DB teams and would allow us to easily see where we stand in regards to instanced content across all cores.

We are fully aware that sometimes content changes or is added between expansions. A good example is the extra spawns/scripts added for Brewfest event and ETC band in Blackrock Depths during the TBC era.
These entities would not be present in the blackrock_depths.sql CDB file, but they would be present in blackrock_depths_tbc.sql and blackrock_depths_wotlk.sql. The idea is that these differences will be very few and far between. It's also not unlike what we already have to handle in the ACID files with varying spell ids, scripts, and texts between expansions.

Another thought we had is that although these files might start out sort of ugly in a "dump-like" format, they could be improved over time to be more human readable - such as separating data into groups by room/area and adding additional comments. Please note also that the Naxx example is just a model and not necessarily representative of the final format we decide upon.

**Comment by AnonXS** [comment]
This has been adapted for the the most part.
