### ISSUE TITLE
Classic core crashes

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1480]
**Current behavior**: 
Core crashes when some NPC summons its pet. I did not manage to find which one, it happens on another active grid/map.

**Expected behavior**: 
Do I really need to describe the expected behaviour? ;-)

**Steps to reproduce**:

1. Load a character
2. .tele stormwind (place do not seem to matter, but this one is known to work)
3. wait a few minutes (3-4 max) to see the core crash

This is reproducible.

Crash log: https://pastebin.com/CgcrHerT

Console log right before the crash:
```
Sending SMSG_SPELL_START id=6920
Sending SMSG_SPELL_GO id=6920
Spell 6920 Effect0 : 6 Targets: Creature (Entry: 3821 Guid: 34923), -, -
Spell: Aura is: 16
Aura: construct Spellid : 6920, Aura : 16 Target : 1 Damage : 145
Holder of spell 6920 now is in use
Sending SMSG_SPELL_START id=6920
Sending SMSG_SPELL_GO id=6920
Spell 6920 Effect0 : 6 Targets: Creature (Entry: 3821 Guid: 34932), -, -
Spell: Aura is: 16
Aura: construct Spellid : 6920, Aura : 16 Target : 1 Damage : 140
Holder of spell 6920 now is in use
Sending SMSG_SPELL_START id=6920
Sending SMSG_SPELL_GO id=6920
Spell 6920 Effect0 : 6 Targets: Creature (Entry: 3821 Guid: 34933), -, -
Spell: Aura is: 16
Aura: construct Spellid : 6920, Aura : 16 Target : 1 Damage : 140
Holder of spell 6920 now is in use
Map::GetHitPosition vmaps corrects gained with static objects! new dest coords are X:6751.557617 Y:-1969.357910 Z:552.002991
Sending SMSG_SPELL_GO id=12746
Spell 12746 Effect0 : 56 Targets: Creature (Entry: 3771 Guid: 33232), -, -
Spell 18727 Effect0 : 6 Targets: Pet (Petnumber: 340 Guid: 1), -, -
Spell: Aura is: 79
Aura: construct Spellid : 18727, Aura : 79 Target : 1 Damage : 0
AURA MOD DAMAGE type:1 negative:0
Holder of spell 18727 now is in use
Spell 18735 Effect0 : 6 Targets: Pet (Petnumber: 340 Guid: 1), -, -
Spell: Aura is: 133
Aura: construct Spellid : 18735, Aura : 133 Target : 1 Damage : 0
Holder of spell 18735 now is in use
Spell 18742 Effect0 : 6 Targets: Pet (Petnumber: 340 Guid: 1), -, -
Spell: Aura is: 132
Aura: construct Spellid : 18742, Aura : 132 Target : 1 Damage : 0
Holder of spell 18742 now is in use
Pet (Petnumber: 340 Guid: 1) enters grid[37,26]
Segmentation fault
```

**Client version**: 
1.12.1

**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/632846867d259dc32f5262322a927738ee5c57e4

**Database version**: 
https://github.com/cmangos/classic-db/commit/e8d8082439b663d5ac9a2b4c21e61634022def6b

**Operating system**: 
Mac OS X 10.6

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
@cala 
    NewSummon->GetCharmInfo()->GetAI()->SetReactState(REACT_DEFENSIVE);
change into 
    NewSummon->AI()->SetReactState(REACT_DEFENSIVE);

**Comment by asavah** [comment]
Still crashes even with the suggested changes.

Login to char at elwynn forest, wait for 2-3 minutes, crashes.
Ubuntu 17.10, gcc 7.2.0, fresh VM

gdb backtrace https://pastebin.com/N5vu2dWX

```
#0  0x00005634e9285768 in CreatureAI::SetReactState (this=0x0, st=REACT_DEFENSIVE)
```
Seems to try to set a member variable of a null object.

**Comment by kotishe** [comment]
confirm

**Comment by killerwife** [comment]
Fixed in: https://github.com/cmangos/mangos-classic/commit/e2005e1c317b132fb8a9abfb7570025979eef419

**Comment by cala** [comment]
It does the trick very much, thanks @killerwife for fixing it that quick! :+1:
