### ISSUE TITLE
[CLASSIC] Campfire Game Objects on Top of Campfires Already in the World

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1481]
Sometimes a campfire game object is situated on top of an already existing campfire baked on the game map. Why is this? It's not for the fire damage, that can be done with an invisible fire damage game object.

This leads to the model glitching with the model it is laid over. Which is my main reason in starting this discussion. See picture (the object is selected but not everything lights up as it should):
![image](https://user-images.githubusercontent.com/1436449/31583365-9ba09440-b19a-11e7-8e8d-cb75d6f2da93.png)

If you mouse over the campfire, a display won't appear in the right bottom of the screen. But who can say this is not blizzlike?

**Comment by Grz3s** [comment]
various reasons.
- req for cooking
- added between expansions.. and in our DBs (not-needed object is still there)
- duplicates?
Theres no other option than checking every place where this happens...(difficult to find)..

Pls provide some details ..
- which DB's is used
- guids? (so we can find this object)

**Comment by bdebaere** [comment]
@Grz3s 
Classic db
.go 966 -1429 65 0

Cooking is a good remark. It is indeed required to have this object there for cooking. Though I am not sure how easily one could replace it by an invisible object which meets the same needs of enabling cooking.

**Comment by Grz3s** [comment]
just checked that place... (got only wotlkDB)
they're only 2 objects there
```code
('2061','6','0','Campfire','','','','14','0','0','1','0','0','0','0','0','0','0','1','2','7897','0','3','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','');
('185498','8','192','Campfire','','','','0','0','0','1.22','0','0','0','0','0','0','4','10','2061','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','');
```
'185498' guid 45322 - spellfocus - 8   
'2061'     guid 45323 - trap          - 6

@Cala can you pls check if any you guys have any duplicates there?

**Comment by bdebaere** [comment]
@Grz3s You will only notice two gameobjects. But there is one already on the world map.

**Comment by al3xc1985** [comment]
@cala can you check please in db for duplicates and if none exist, close this?

**Comment by AnonXS** [comment]
it's just the mouseover for interactable or otherwise needed gameobjects, no duplicate no nothing.

```
45322, Entry 185498 - [Campfire X:962.502991 Y:-1429.079956 Z:64.553299 MapId:0]
9000451, Entry 2061 - [Campfire X:962.502991 Y:-1429.079956 Z:64.553299 MapId:0]
Found near gameobjects (distance 10.000000): 2 
Object not found!
```

Normal fire go + the fire trap it spawns.
