### ISSUE TITLE
[TBC] Missing Movement and Text for Servo in Badlands 

### ISSUE THREAD

**Issue by stan84** [cmangos/issues#1483]
just another small issue:
servo an small mechanical npc in badlands is missing movement and txt.
Current behavior:  Servo ( npc#2922) is standing.

Expected behavior: should walk around and says like described http://wowwiki.wikia.com/wiki/Servo
http://rain01.free.fr/malvadeza/userpix/12_wowia_1.jpg

**Comment by AnonXS** [comment]
AI was fixed here: https://github.com/cmangos/tbc-db/commit/551d93a1058dc23163c0caf47296e5ec4dbae27a#diff-8882d83d44ad5da160640aa84df413a6R943

not sure about pathing, i think that also works on tbc at least.

**Comment by jimmybrancaccio** [comment]
@AnonXS Awesome, thank you! If anyone is able to test the pathing that would be excellent. Then we can consider this a case closed!

**Comment by AnonXS** [comment]
Doesnt have any movement, texts could be handled in dbscripts on movement though, but thats not really an improvement as he seems to not be reacting to anything.
