### ISSUE TITLE
[CLASSIC] Spell 6607 Disarms the Caster

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1486]
**Current behavior**: 
Spell 6607 disarms the caster instead of the target. A spell 6608 is triggered through mechanic SPELL_EFFECT_TRIGGER_SPELL with targets TARGET_CHAIN_DAMAGE, NO_TARGET. The spell 6608 itself has targets TARGET_SELF, NO_TARGET.
**Expected behavior**: 
At the very least in this case, the spell triggering should pick the target for the triggered spell which is TARGET_CHAIN_DAMAGE.
**Steps to reproduce**:

1. Go to Silithus
2. Find a Dredge Crusher
3. Let it hit on you
4. Notice how it disarms itself when casting Lash

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 

**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/commit/b169db77f2fdc4fc81fc198408bb940057e9eb10#diff-267e883184701d9dd4ecaf79808a9b4dR1839

Make a similar solution to this, except caster will be target and make a C++ PR. For now we need to research this.
