### ISSUE TITLE
[WOTLK] Hunter Bug Tracking - Can Enable Them All

### ISSUE THREAD

**Issue by Anime88** [cmangos/issues#1487]
**Current behavior**: 
Using the Tracking Spell (Beasts, Demons, Humanoids etc.) stacks, so you can use all of them at the same time.
**Expected behavior**: 
Just one of them is useable at the same time.

**Steps to reproduce**:

1.  Create a Hunter Char, level up and learn the Tracking Spells.
2.  Go to a City, cast Tracking Humanoids an watch the Minimap. You can see them now.
3.  Cast Tracking for Beasts, the humanoids shoud gone and Animals should be now on the minimap. But you can see also see the humanoids. 

**Client version**: 
WotLK Patch 3.3.5 (12340)

**Commit hash**: 
8ded0ae428f478e5ea66b02d3f0f10b2a2900c05, but also in older Versions.
**Database version**: 
Also last Version and older.

**Operating system**: 
Windows 7 x64 and Windows 10 x64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by al3xc1985** [comment]
@killerwife i remember you fixing this kind of  problems

**Comment by killerwife** [comment]
This needs review. In my infinite wisdom I am unable to guess if the wotlk version of this issue was fixed.

**Comment by al3xc1985** [comment]
Ok

**Comment by ekg98** [comment]
I can confirm i was atleast fixed for the hunter with beast vs humanoids. Not sure other modes or char types.

**Comment by killerwife** [comment]
Tested, works as intended now.
