### ISSUE TITLE
[WOTLK] Hunter Bug Multi-Shot

### ISSUE THREAD

**Issue by Anime88** [cmangos/issues#1488]
Current behavior:
Using the Multi-Shot on multiple targest in Range, the Multi-Shot shoots only one shot to one target.

Expected behavior:
Casting Multi-Shot with more then one target in range it fires 1 to 3 shots, one for each target.

Steps to reproduce:

    1. Create a Hunter Char, level up and learn the Multi-Shot Spell.
    2. Go to a area with some enemies, the enemie should be near together.
    3. Cast Multi-Shot and see ist fires just on Arrow to one traget instead fireing to 2 or 3 tragets.

Client version:
WotLK Patch 3.3.5 (12340)

Commit hash:
8ded0ae428f478e5ea66b02d3f0f10b2a2900c05, but also in older Versions.
Not sure but I think this works 2 Weeks ago, and now it don't.
Database version:
Also last Version and older.

Operating system:
Windows 7 x64 and Windows 10 x64

**Comment by killerwife** [comment]
Resolved some time ago.
