### ISSUE TITLE
[WoTLK] Unable to Update Core Database

### ISSUE THREAD

**Issue by jimmybrancaccio** [cmangos/issues#1489]
**Current behavior**: 

When running the `./InstallFullDB.sh` script it will error out since there is a missing field in the `spell_template` table.

**Expected behavior**: 

I expect the base SQL files to be able to be imported without issue.

**Steps to reproduce**:

1. Get commit cmangos/mangos-wotlk@60e8e3f (though I am pretty sure it was introduced in cmangos/mangos-wotlk@06ce23e so I believe either would work).
2. Compile as usual, and then attempt to run the './InstallFullDB.sh' script.
3. You should see an error that `/home/mangos/mangos/sql/base/dbc/cmangos_fixes/Spell.sql` failed to import.

**Client version**: 

N/A

**Commit hash**: 

cmangos/mangos-wotlk@06ce23e

**Database version**: 

v1.1 The Warsong

**Operating system**: 

Ubuntu 14.x

### Log From InstallFullDB.sh

``` bash
$ ./InstallFullDB.sh 

Welcome to the WoTLK-DB helper InstallFullDB.sh

ATTENTION: Your database mangos will be reset to WoTLK-DB!
Please bring your repositories up-to-date!
Press CTRL+C to exit
...........
> Processing WoTLK database v1.1 'The Warsong' ...
  v1.1 'The Warsong' is applied!


> Processing database updates ...
    Appending Updates/1160_DB_Version.sql
    Appending Updates/1161_razorgore_updates.sql
    Appending Updates/1162_q8730.sql
    Appending Updates/1163_Game_Events_Part2.sql
  4 DB updates applied successfully


> Trying to retrieve last core update packaged in database ...
  Found last core revision in DB is 13965


> Trying to apply additional core updates from path /home/mangos/mangos ...
  CORE UPDATE PROCESSED: 0
  CORE UPDATE FOUND BUT ALREADY IN DB: 29


> Trying to apply /home/mangos/mangos/sql/base/dbc/original_data ...
    Appending DBC file update DungeonEncounter.sql to database mangos
    Appending DBC file update Spell.sql to database mangos
  DBC datas successfully applied


> Trying to apply /home/mangos/mangos/sql/base/dbc/cmangos_fixes ...
    Appending CMaNGOS DBC file fixes Spell.sql to database mangos
ERROR 1054 (42S22) at line 262: Unknown column 'EffectBasePoints1' in 'field list'
ERROR: cannot apply /home/mangos/mangos/sql/base/dbc/cmangos_fixes/Spell.sql
```

**Comment by killerwife** [comment]
Fixed in latest commit.
