### ISSUE TITLE
[cmangos-classic] Filling 'mangos' database from mangos/sql/base/mangos.sql fails, ": Column count doesn't match value count"

### ISSUE THREAD

**Issue by berserkingyadis** [cmangos/issues#1491]
This is the failing command:

`sudo mysql -u root -p mangos < mangos/sql/base/mangos.sql `

**Current behavior**: 
mysql exits with the errors: 
1. ERROR 1136 (21S01) at line 1015: Column count doesn't match value count at row 1
2. ERROR 1136 (21S01) at line 1229: Column count doesn't match value count at row 1

After checking the file, it seems that the lines 1001, 1002 were added recently (https://github.com/cmangos/mangos-classic/commit/124614054770d9502f1bddf4a2cd2dcdda2fbc34) and cause this error. After deleting them the insert is working. The next error is in line 1229 with the same issue, the column count does not match the value count at row 1. Same goes with the lines 1165- 1170. Seems they were added and the inserts after that fail because there now are too many columns.

**Expected behavior**: 
The sql file goes through without error.

**Steps to reproduce**:

1. doing a fresh install 
2. sudo mysql -u root -p < mangos/sql/create/db_create_mysql.sql 
3. sudo mysql -u root -p mangos < mangos/sql/base/mangos.sql

**Client version**: 
-
**Commit hash**: 
d43eaefc88e4339ab4a7c0f45f9662ead589a38c
**Database version**: 
the sql files from the cmangos-classic sql folder
**Operating system**: 
ubuntu-16.04.3-desktop-amd64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cyberium** [comment]
Could you please retry with latest change?
