### ISSUE TITLE
Cenarion Beacon works outside of Felwood

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1494]
**Current behavior**: 
http://www.wowhead.com/item=11511/cenarion-beacon works outside of Felwood. Mining and collecting herb nodes in Eastern Plaguelands will yield the corrupted drops.

**Expected behavior**: 
Should it? I find very little info on this subject.

**Steps to reproduce**:

1. Get a Cenarion Beacon.
2. Go to Eastern Plaguelands.
3. Mine or herb.

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 

**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
Cenarion Beacon is supposed to only work in Felwood. I'll fix this.
