### ISSUE TITLE
[CLASSIC] How are we Doing In The Battle to Subvert the Cauldrons?

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1497]
**Current behavior**: 
Nothing happens when clicking "How are we doing in the battle to subvert the cauldrons?".

**Expected behavior**: 
High Priest MacDonnel and Shadow Priestess Vandis should respond with the current status.

**Steps to reproduce**:

1. Go to either High Priest MacDonnel or Shadow Priestess Vandis.
2. Click the gossip.
3. Nothing happens.

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 

**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
I had these on my personal ToDo list for a long time but I can't find any source about it:
- does it even applies to Classic ?
- what are the possible gossips ?
- on what criteria are gossips used ?
