### ISSUE TITLE
wotlk playerbot could not loot quest items

### ISSUE THREAD

**Issue by bowey** [cmangos/issues#1498]
**Current behavior**: 
after kill quest creature, playerbot does not loot quest items on the corpse, just standing on the corpse. 

**Expected behavior**: 
after kill quest creature, playerbot loot quest items. 

**Steps to reproduce**:
1.  .bot add  playerbot_name 
2.  /invite  playerbot_name 
3. kill quest creatures
4. wait playerbot loot quest item.

**Client version**: 
wow_3.3.5a

**Commit hash**: 
8ecd77a568b9f2601972cbaa4fa40acc2a84c57e

**Database version**: 
Mysql 5.7.19
**Operating system**: 
 ubuntu 16.04  (Ubuntu)

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Hermetica** [comment]
This problem is in PlayerBotAI.cpp  - when handling SMSG_LOOT_RESPONSE
you have:
if (lootslot_type != LOOT_SLOT_NORMAL) continue;

You also have to handle owned items kind of like:
if (lootslot_type != LOOT_SLOT_NORMAL && lootslot_type != LOOT_SLOT_OWNED) continue;

**Comment by derflongshanks** [comment]
I changed the above line to
 if (lootslot_type != LOOT_SLOT_NORMAL && lootslot_type != LOOT_SLOT_OWNER)
                    continue;
And that fixed it for me

**Comment by jimmybrancaccio** [comment]
I can confirm adjusting:

``` c++
if (lootslot_type != LOOT_SLOT_NORMAL)
    continue;
```

to

``` c++
if (lootslot_type != LOOT_SLOT_NORMAL && lootslot_type != LOOT_SLOT_OWNER)
    continue;
```

in `PlayerBotAI.cpp` allows the bot to collect quest items properly.

**Comment by cala** [comment]
Thanks! Fixed by: https://github.com/cmangos/mangos-wotlk/commit/cff9a21e99c80868d1c4118033a73bf14feff34f
