### ISSUE TITLE
Spell Line of Sight casting is broken

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1499]
**Current behavior**: 
When trying to cast a spell on a target that is behind a wall, the player casts the spell, GCD is activated and mana/reagents are consumed while target is not hit by spell (do not even enter combat if hostile target).
Spell casting when having the target in LoS is working as intended.

**Expected behavior**: 
Caster should receive an error message stating that target is not visible.

**Steps to reproduce**:

1. Have a druid with Faerie Fire
2. `.tele Blackrockspire` and enter the instance
3. Try to cast the spell Faerie Fire on the first NPC on the left after entering the instance while hiding behind the wall and while having the NPC in Line of Sight

**Client version**: 
1.12.1

**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/024e9e776b52643590de7cec1df991cc62ef90a9

**Database version**: 
Classic DB v.1.8.5

**Operating system**: 
Windows 7 Pro and Mac OS X 10.6

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by coolmodi** [comment]
IsSingleTargetSpell() in SpellMgr doesn't account for any spell without a mechanic, so basically most spells in the game, and returns false, resulting in none of the single target spell checks being done

**Comment by Warlockbugs** [comment]
Entire block of code seems to be faulty:

TBC Core:
```
    if (Unit* target = m_targets.getUnitTarget())
    {
```
Classic core:
```
    // following code block is supposed to be applied to single target spell
    // TODO: above assumption need to be verified
    Unit* singleTarget = m_targets.getUnitTarget();
    if (singleTarget && sSpellMgr.IsSingleTargetSpell(m_spellInfo))
    {
```
Completely incorrect usage of IsSingleTargetSpell introduced in https://github.com/cmangos/mangos-classic/commit/5b67e424f21b429f5a447c32df52e615c655f27c

**Comment by Warlockbugs** [comment]
Might be better to rename it into something like IsSingleTargetTrackingSpell to prevent this in the future.
