### ISSUE TITLE
[WotLK] Compiling Error

### ISSUE THREAD

**Issue by Dainara82** [cmangos/issues#1505]
Hi, have compiling error
`[  9%] Building CXX object src/shared/CMakeFiles/shared.dir/Auth/HMACSHA1.cpp.o
/home/mangos/wotlk/src/shared/Auth/HMACSHA1.cpp: In constructor ‘HMACSHA1::HMACSHA1(uint32, uint8*)’:
/home/mangos/wotlk/src/shared/Auth/HMACSHA1.cpp:24:13: error: ‘m_key’ was not declared in this scope
     memcpy(&m_key, seed, len);
             ^~~~~
src/shared/CMakeFiles/shared.dir/build.make:110: die Regel für Ziel „src/shared/CMakeFiles/shared.dir/Auth/HMACSHA1.cpp.o“ scheiterte
make[2]: *** [src/shared/CMakeFiles/shared.dir/Auth/HMACSHA1.cpp.o] Fehler 1
CMakeFiles/Makefile2:638: die Regel für Ziel „src/shared/CMakeFiles/shared.dir/all“ scheiterte
make[1]: *** [src/shared/CMakeFiles/shared.dir/all] Fehler 2
Makefile:127: die Regel für Ziel „all“ scheiterte
`
what can i do?

**Comment by berserkingyadis** [comment]
Which core version?

Which operating system?

**Comment by evil-at-wow** [comment]
I believe @killerwife has fixed this in the meantime with cmangos/mangos-wotlk@87ab52b05bc282080cd6313f49dd3235a280449f, so just update your repository and build again. Feel free to reopen this issue if the compile error isn't fixed after all.

**Comment by adellaci** [comment]
I have tested it and it compiles once again
