### ISSUE TITLE
[WOTLK] Character Partially Reverted to Previous State

### ISSUE THREAD

**Issue by Dainara82** [cmangos/issues#1507]
**Current behavior**: 
1 Player played from lvl 16 to lvl 25  learnd everything and left the game, after he logging in again he was lvl 16 again, all skills are learnd from lvl 25, but all clothes are lost the character was naked, all quests he can do again,
so the character have an halfe rollback 

**Steps to reproduce**: can't reproduce it

**Client version**:  3.3.5a

**Commit hash**:  fresh from yesterday

**Database version**: fresh DB from yesterday

**Operating system**:  server  Linux Debian 9 64Bit   CLient i think  Win10

**Comment by Warlockbugs** [comment]
I suspect its related to https://github.com/cmangos/issues/issues/1177

**Comment by al3xc1985** [comment]
@cyberium can we xlose it? We are not able to reproduce it. As worlockbugs mentioned, it might been fixed
