### ISSUE TITLE
[Vanilla] Startup errors

### ISSUE THREAD

**Issue by xion87** [cmangos/issues#1508]
**Current behavior**: 
Having these error at startup https://hastebin.com/ligicesiwa.coffeescript

**Expected behavior**: 

**Steps to reproduce**:

1. dunno
2. 
3. 

**Client version**: 
1.12.2

**Commit hash**: 
Latest of today

**Database version**: 
Latest of today

**Operating system**: 
Ubuntu 16

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
This is the same issue than https://github.com/cmangos/issues/issues/1412
So, I'm closing this one.
