### ISSUE TITLE
[WotLK] Quest 4901 SD2 problem

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#1509]
**Expected behavior**: 

NPC 10300 should walk to the caves and cast a spell while you light the torches.

**Current behavior**: 

NPC walks to first cave asks you to light  torch and then just stands there.

**Steps to reproduce**:

1. Take Quest 4901
2. Follow C10300 to cave
3. Thats it.,,:)

**Client version**: 
3.3.5
**Commit hash**: 
7831fb20603a7f626d042fef4d6ba8e5014ca99b
**Database version**: 
PSDB
**Operating system**: 
Windows 7 32 bit

**Edited**: Sorry had behaviors above backwards..

**Comment by Grz3s** [comment]
@xfurry WotlkDB has same problem with this...

**Comment by xfurry** [comment]
@Grz3s I have no idea why is this happening. I will need to run this in debug mode in order to understand why isn't the creature continuing the path.

Is this something that could be related to some EscortAI changes? Do the other escort quests work fine in general?

**Comment by Grz3s** [comment]
Tried to find smth that pauses npc...
1st: 
http://www.wowhead.com/quest=4121/precarious-predicament
- here you have to eliminate ambush to continue escort... -- did work fine
2nd:
http://www.wowhead.com/quest=9759/ending-their-world
- one of last escort that u made for me... npc stops to do small event etc... -- but then he continue his walk.. so no problem there also

**Comment by cala** [comment]
I did some changes (mostly visuals and texts) for this quest one (or two) year ago.
If I remember correctly, there is a timer in each cave and the NPC won't resume movement until the timer expires. Can you try to wait a few minutes (2 or 3 maybe) to see if the NPC starts moving to the next cave?
I just tested on Classic right now and aside from that timer, the quest and event work fine.

So maybe we need to force the timer to a lower value once the GO is used by the player (I don't know why I did not do it last time, there was maybe a good reason to it).

**Comment by Rog360** [comment]
@cala You hit it on the head! She waits 3 minutes before moving on. So this one is a time problem... :)

**Comment by Grz3s** [comment]
oh lol ... this also works for wotlkDB...
got this:
```quote
(wowhead)
By Random0076 (1,295 – 8·19)  on 2008/02/18 (Patch 2.3.3)   
This may take your health down some so when whe is channeling at the torches she will continue to until u right-click it. This is a good time to eat/drink.
```
So waaypoints should be unpaused after using object.

**Comment by Rog360** [comment]
I think so too. Tried with no success to find a video... :)

**Comment by Grz3s** [comment]
Quick update:
I managed to wait that long in each cave (5*3min = 15mins) :D ... to look on that final event...and unfortunately it stuck... after 2 ghosts apeared... (even after 6 mins nothing happened)
![test](https://user-images.githubusercontent.com/2374069/33783326-3dba1902-dc54-11e7-8130-c3ed8a649601.jpg)

**Comment by cala** [comment]
If you are not in a hurry, I will look into it in a few days when I get back access to my computer. I like this quest.

**Comment by cala** [comment]
I just had a quick look and:
- there is no wait time in the waypoints
- the escort is already paused/unpaused (with only a 2 sec timer) once the player uses the GO
So I don't know why the NPC waits 3 minutes (3 min & 2 secs mentioned above to be accurate)

My only guess would be `STOP_TIME_FOR_PLAYER` in WaypointMovementGenerator.cpp (that is defined to 3 minutes), but I don't see why other escort NPCs would not have the same issue...
Any wild guess @xfurry that I could investigate?

**Comment by cala** [comment]
> Quick update:
I managed to wait that long in each cave (5*3min = 15mins) :D ... to look on that final event...and unfortunately it stuck... after 2 ghosts apeared... (even after 6 mins nothing happened)

@Grz3s Unfortunately, I don't have this issue on Classic core. As the script is the same between Classic and WotLK, there might be a difference in the DB (possibly missing GOs).

**Comment by cala** [comment]
I finally found the tricky cause of the wait time and I have a fix. I also spotted two small issues with that quest. I shall fix everything in one single commit soon.

**Comment by xfurry** [comment]
I don't think that this issue is related to the quest itself.
I did some testing and I found out that if the creature is casting spell http://www.wowhead.com/spell=18953/ranshalla-waiting which has
```
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (1, 0) (TARGET_SELF, TARGET_NONE)
Aura Id 26 (SPELL_AURA_MOD_ROOT), value = 1, misc = 0 (0), miscB = 0, periodic = 0
```
then the escort movement will break.
I think it might be a generic issue with WP movement breaking on root / stun auras.
Poke @killerwife or @cyberium because they toyed with the movement recently.

**Comment by cala** [comment]
@xfurry that is exactly where the issue comes from. The root aura triggers in the movement generator an internal timer that prevents the waypoint movement to be resumed until the timer expires (3 min). This is the same timer used when a player opens a gossip menu with a wandering NPC, making it stop for a while.
There is a way to reset the timer by changing the current point of the path. To fix the quest, I set the next point to current point + 1 once the player used the GO. I should push the whole commit this evening once I'm back at home.

But you are right, I'm not sure the initial behaviour is correct in this case.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-wotlk/commit/a1ea2a01b3607ec72e860055b5446e0c96a487fd
