### ISSUE TITLE
z2716_01_realmd_totp.sql will not apply to realmd database with users that have not logged in

### ISSUE THREAD

**Issue by linuxpng** [cmangos/issues#1510]
**Current behavior**: 
Upgrading DB from z2678_01_realmd to z2716_01_realmd_totp will fail with strict date checking on mysql

**Expected behavior**: 
Apply the database update properly

**Steps to reproduce**:

1. Have realmd db version z2678_01
2. mysql -u root -p realmd < mangos/mangos/sql/updates/realmd/z2716_01_realmd_totp.sql

**Client version**: 
1.12.1

I was able to apply the update with these commands:
use database realmd;
select @@GLOBAL.SQL_MODE;
set sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

Several users administrator, gamemaster, moderator etc were never logged in but database entries remained from initial setup (with zero's for login dates).  I am not a database expert by any stretch, so I have no idea if the above is the appropriate resolution.  If so, the documentation will probably need to be updated.

**Comment by jimmybrancaccio** [comment]
Closing this as it does not appear these are default SQL modes:

```
MariaDB [(none)]> select @@GLOBAL.SQL_MODE;
+--------------------------------------------+
| @@GLOBAL.SQL_MODE                          |
+--------------------------------------------+
| NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+--------------------------------------------+
1 row in set (0.00 sec)
```
