### ISSUE TITLE
[Vanilla] compilation crash when building only extractors (Linux)

### ISSUE THREAD

**Issue by pboardman** [cmangos/issues#1511]
**Current behavior**:
Error when compiling only the extractors with:
```
cmake ../mangos -DCMAKE_INSTALL_PREFIX=\../run -DBUILD_EXTRACTORS=ON -DBUILD_GAME_SERVER=OFF -DBUILD_LOGIN_SERVER=OFF
make
```

```
[ 78%] Building CXX object contrib/vmap_extractor/vmapextract/CMakeFiles/vmap_extractor.dir/wdtfile.cpp.o
[ 79%] Building CXX object contrib/vmap_extractor/vmapextract/CMakeFiles/vmap_extractor.dir/wmo.cpp.o
[ 80%] Linking CXX executable vmap_extractor
[ 80%] Built target vmap_extractor
Scanning dependencies of target vmap_assembler
[ 81%] Building CXX object contrib/vmap_assembler/CMakeFiles/vmap_assembler.dir/__/__/src/game/vmap/BIH.cpp.o
In file included from /opt/mangos/src/game/vmap/BIH.cpp:19:0:
/opt/mangos/src/game/vmap/BIH.h:26:29: fatal error: Platform/Define.h: No such file or directory
compilation terminated.
```

**Expected behavior**: 
Extractors compilation should work

**Steps to reproduce**:

1. compile CMaNGOS with those cmake options: ` -DBUILD_EXTRACTORS=ON -DBUILD_GAME_SERVER=OFF -DBUILD_LOGIN_SERVER=OFF `

**Client version**: 
N/A
**Commit hash**: 
649050e
**Database version**: 
N/A

**Operating system**: 
Linux

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by berserkingyadis** [comment]
Can reproduce, newest core.

OS: Archlinux 64bit

**Comment by FiniteReality** [comment]
I can also reproduce this. However, it seems to work correctly when building the game server and login server, so I'm guessing it's something with the CMakeLists not setting an include path correctly when the flags are disabled.
