### ISSUE TITLE
[CLASSIC] Mangletooth - Blood Shard Quests - Spell Rewards

### ISSUE THREAD

**Issue by RichardGe** [cmangos/issues#1512]
For reward of quests 889 5042 5043 5044 5045 5046 the NPC 3430 "Mangletooth" is supposed to cast a spell :  16618  16612 17013  7764  10767 or  16610  on you .
But he casts the spells on himself instead.

I had a look in the quest_template database.  I don't see a way to change the RewSpell Target. Is the target hard-coded in source code - or is there a way to change it in database ?

note : my server is several months old 

related to  https://github.com/cmangos/issues/issues/1150

**Comment by bdebaere** [comment]
These spells all have TARGET_DUELVSPLAYER assigned to them. Meaning the caster will be reset to the quest giver in the for loop looping over every effect in Player.cpp.

```
// Find spell cast on spell reward if any, then find the appropriate caster and cast it
    uint32 spellId = pQuest->GetRewSpellCast();
    if (!spellId)
        spellId = pQuest->GetRewSpell();

    if (spellId)
    {
        if (SpellEntry const* spellProto = sSpellTemplate.LookupEntry<SpellEntry>(spellId))
        {
            Unit* caster = this;

            if (questGiver->GetTypeId() == TYPEID_UNIT)
            {
                for (uint8 i = 0; i < MAX_EFFECT_INDEX; ++i)
                {
                    if (spellProto->Effect[i] == SPELL_EFFECT_LEARN_SPELL ||
                        spellProto->Effect[i] == SPELL_EFFECT_CREATE_ITEM ||
                        spellProto->EffectImplicitTargetA[i] == TARGET_DUELVSPLAYER ||
                        spellProto->EffectImplicitTargetA[i] == TARGET_SINGLE_FRIEND)
                    {
                        caster = (Unit*)questGiver;
                        break;
                    }
                }
            }

            caster->CastSpell(this, spellProto, TRIGGERED_OLD_TRIGGERED);
        }
    }
```

**Comment by MrMarvin** [comment]
I dug a little into quest reward spell behavior and added a lengthy comment over in #1150, which also applies to the quests mentioned here. Also please note that I am currently working on the TBC version. Same issue. Can we please add the `Version: TBC` label here as well? Thanks!

**Comment by cala** [comment]
Tested today and closing now as Mangletooth's reward buffs are now correctly cast onto the player.
