### ISSUE TITLE
[PetAI] Consume Shadows/Suffering Causes Voidwalker to Attack

### ISSUE THREAD

**Issue by UnforgetaBill** [cmangos/issues#1513]
**Current behavior**: Casting consumer shadows (all ranks) causes combat to start.  Casting consume shadows with a mob targeted causes the voidwalker to attack the mob instead of casting the consume shadows buff , same with suffering spell.

**Expected behavior**:  Casting consume shadows gives the voidwalker a healing buff of the same name 

**Steps to reproduce**:

1.  Cast consume shadows
2.  Combat begins(similar to bloodrage), if a mob is targeted voidwalker will attack it.

**Client version**: 
1.12.1 (5875)

**Commit hash**: 
Sorry I don't know what this is, I downloaded the source from git on 4-Dec-2017.

**Database version**: 
Classic-DB 1.8.5

**Operating system**: 
Server running on Linux Mint 18.3 (Ubuntu 16.04)
Tested on client running Win 7 64 bit, and running on Linux with wine

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
Needs to be hacked in petAI or Spells have to be rechecked, why the pet is able to automatically break its own casting (which is true for alot of spells/ai situation with channelled or casted spell)

spells: (17854) (17767) (17850) (17851) (17853) (17852) (27272)

**Comment by cala** [comment]
On latest revision https://github.com/cmangos/mangos-classic/commit/8f0b95836ea2e7825b75c1444a5c0906bd351b05 this is partly fixed:
- Consume Shadows no longer puts players in combat
- however, casting Consume Shadows when a neutral or hostile NPC is targeted still makes the voidwalker move towards this target and attack it once Consume Shadows channel is over.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/6ef10bbe3567ec4fd7f59e272039c53ca7bcd35a
