### ISSUE TITLE
Command issue [WotLK]

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#1514]
**Current behavior**: 
Type a command and receive the following error in log.

> Table `command` have command '' that only used with some subcommand selection, it        can't have help or overwritten access level, skip.

**Expected behavior**: 
Type command with no error

**Steps to reproduce**:

1. Type any command
2. get error in DB log
3. 

**Client version**: 
3.3.5

**Commit hash**: 
de8e74c001ad2c8b33378a0fb3a4026cafe254de

**Database version**: 
PSDB

**Operating system**: 
Windows 7 x86

**Comment by jimmybrancaccio** [comment]
Hello, thank you for taking time to submit this issue. I have attempted to replicate it using the wotlk-db and was unable too. If you're still experiencing this issue please create a new case in GitHub.
