### ISSUE TITLE
Boost not found

### ISSUE THREAD

**Issue by dagochen** [cmangos/issues#1515]
Following your tutorial, Source does not compile.

Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	C1083	Datei (Include) kann nicht geöffnet werden: "boost/asio.hpp": No such file or directory (Quelldatei wird kompiliert ..\..\src\mangosd\Master.cpp)	mangosd	D:\Mangos\mangos\src\shared\Network\Socket.hpp	27	

Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	C1083	Datei (Include) kann nicht geöffnet werden: "boost/thread/tss.hpp": No such file or directory (Quelldatei wird kompiliert ..\..\src\mangosd\Main.cpp)	mangosd	D:\Mangos\mangos\src\shared\Database\Database.h	28

**Comment by dagochen** [comment]
https://github.com/cmangos/issues/issues/1016#issuecomment-237315605

fixed the problem.

BOOST_ROOT and BOOST_LIBRARYDIR didnt work!

**Comment by jimmybrancaccio** [comment]
Closing this out as resolved. Please connect with us on Discord if you're still having any issues. We'd be happy to lend a hand. Thanks!
