### ISSUE TITLE
Inconsistency between presents

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1516]
**Current behavior**: 
Some presents instantly show the quest to reward:
![image](https://user-images.githubusercontent.com/1436449/34074204-4d2d85e8-e2aa-11e7-8cd4-036518fcdf0f.png)

While others have a welcome screen first that appears where you can select the quest:
![image](https://user-images.githubusercontent.com/1436449/34074202-422a42c6-e2aa-11e7-8828-fb6258a2065f.png)

**Expected behavior**: 
I'm not sure so I would like to ask if anyone knows what the expected behavior is here since there is a discrepancy between all the available presents. Maybe this is even blizzlike, but I don't know how to confirm this. Maybe someone knows.

**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 

**Commit hash**: 

**Database version**: 

**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
This is related to tables gossip_menu, gossip_menu_option, questgiver_greeting, npc_text and quest_template. Since noone was ever really in-depth working on Winter's Veil, this stuff never got added. Looking through videos will propably provide quick evidence for fixes.

**Comment by bdebaere** [comment]
@killerwife I can't seem to find any vanilla videos of people opening the actual present during Winter Veil. Only others like this one: https://www.youtube.com/watch?v=2vxjkKuxBIg. So I'm not sure how much evidence this really is.

**Comment by killerwife** [comment]
The event was largely unchanged in TBC, only the gift was different. The texts can be extracted from that.

**Comment by bdebaere** [comment]
@killerwife It's not about the quest text. It's about the gameobject greeting you and you have to click the quest for some presents, while other presents show the quest immediately.

**Comment by bdebaere** [comment]
@cala I can't test at the moment but from the commit I'm assuming that gossips are added to the presents instead of removed. Is this really the solution here? A present cannot greet you, it's an inanimate object. Just a thought.
