### ISSUE TITLE
[TBC] The Blood Furnace Dungeon Error

### ISSUE THREAD

**Issue by valenciawow** [cmangos/issues#1517]
**Current behavior**: 

The Blood Furnace Dungeon
1. Entry: 17414
Creature's bomb is not broken.
2. Entry: 17380
The door of broggok is not opened.

**Comment by jimmybrancaccio** [comment]
Hello, thank you for taking the time to submit these issues. Please resubmit them if you're still having issues with them utilizing the bug reporting template (shown when you open a new issue).
