### ISSUE TITLE
[TBC] 2 Quest Errors - 8483 and 8488

### ISSUE THREAD

**Issue by valenciawow** [cmangos/issues#1519]
**Current behavior**: 

Quest

1. Quest: 8483
If you are having a conversation with Creature on The "Dwarven Spy", you will get an error message.
2. Quest: 8488
Creature of "Unexpected Results" has been summoned and has no response.
Apprentice Mirveda does not participate in the battle.

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/1af285f3c3a4a13bcef38364f1bdd3db36e308e0

**Comment by jimmybrancaccio** [comment]
We still need some replication for point 1 and testing to ensure point 2 is now resolved.

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/f35e5cb3aeda329842e194e97076d2313b9d5a72
