### ISSUE TITLE
[CLASSIC] The Use of the Mage Does Not See The Building Issues

### ISSUE THREAD

**Issue by bluehelp1989** [cmangos/issues#1520]
**Current behavior**: 
After the flashing of a wizard, a building can not be seen in a dark city or a copy, and it can pass through the door.
Request to fix the problem of the flash.

This problem appears in the 1.12 and 2.43

Mmaps, VMap, maps, DBC are all extracted, but still can't solve this problem, ask for help!

**Expected behavior**: 

**Steps to reproduce**:
See video and pictures

**Client version**: 
1.21

**Commit hash**: 
Newest

**Database version**: 
Newest

**Operating system**: 
windows 10 X64

video:
https://youtu.be/D-ofWa3CNmA

photo:
https://imgur.com/QNHjXtD 
https://imgur.com/btDqOhE 
https://imgur.com/DkRBWha

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/4403065d6996b53bd9a57de8bd87d04d4b545dd4
