### ISSUE TITLE
[WOTLK] [SPELL=20555] Regeneration (Racial Passive)

### ISSUE THREAD

**Issue by virusav** [cmangos/issues#1522]
This spell does not restore health during combat.

Health = 1272.
```
void Player::RegenerateHealth(uint32 diff)
{
    uint32 curValue = GetHealth();
    uint32 maxValue = GetMaxHealth();
LOG: curValue=1269, maxValue=1272, diff=2000

addvalue = OCTRegenHPPerSpirit() * HealthIncreaseRate;
LOG: addvalue=8.056819, OCTRegenHPPerSpirit()=8.056819, HealthIncreaseRate=1.000000

addvalue *= GetTotalAuraModifier(SPELL_AURA_MOD_REGEN_DURING_COMBAT) / 100.0f;
LOG: addvalue=0.805682, GetTotalAuraModifier(SPELL_AURA_MOD_REGEN_DURING_COMBAT)=10

addvalue += GetTotalAuraModifier(SPELL_AURA_MOD_HEALTH_REGEN_IN_COMBAT);
LOG: addvalue=0.805682

addvalue *= (float)diff / REGEN_TIME_FULL;
LOG: addvalue=0.805682

ModifyHealth(int32(addvalue));
LOG: int32(addvalue) = 0
```

I tried different value of health at different levels and different damage, but always the value of the heal was less than 1, so int32(addvalue) is always 0.
As a result, no restoration of health is not happening.

Does the amount of healing should not be considered as 10% of the total health?

**Comment by killerwife** [comment]
No. Spirit influences that. The wording is "10% of total Health regeneration may continue during combat." which means out of 8.056819 HP/s OOC you get 0.805682 HP/s in combat, which is exactly what it does.

**Comment by virusav** [comment]
The problem is that the recovery is not working as it is always int32(addvalue) = 0.

**Comment by killerwife** [comment]
Then try setting your spirit attribute to a ridiculously high number and then see whats what.

**Comment by virusav** [comment]
Checked on the official server:
1. The spell description hasn't changed.
2. Even on the lower levels of health regenerated during combat.

Is with version 335а this spell has changed so much?

**Comment by killerwife** [comment]
Afaik all regen was changed, both mana and HP. The spell wasn't changed though. Your gripe is with regen calculations, not this spell. You need to do you homework on that front.
