### ISSUE TITLE
[classic] - 1 Spirit Healer in South of the Barrens ?

### ISSUE THREAD

**Issue by RichardGe** [cmangos/issues#1523]
There is 1 Spirit Healer in the south of the Barrens, but no cemetery. So I would say it's useless ?
Is it an error in Database... or maybe it was in original wow vanilla ?
creature GUID : 5724

![asup_spirit](https://user-images.githubusercontent.com/2279126/34388970-23b58f40-eb37-11e7-8b30-35564b41b74a.jpg)

**Comment by killerwife** [comment]
I suggest checking against TBC. I think they added one later.

**Comment by cala** [comment]
More than probably one of those Spirit Healer linked to a graveyard added after Classic.

**Comment by Grz3s** [comment]
![sheal](https://user-images.githubusercontent.com/2374069/34425213-d66a13d2-ec21-11e7-8652-a20edf1763cf.jpg)
same place in WOTLK  ;)
