### ISSUE TITLE
[Classic] Image Projection not killing Spectral Projection's in Scholomance

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1524]
**Current behavior**: 
Currently in Scholomance, Spectral Tutors (https://db.vanillagaming.org/?npc=10498) cast Image Projection (https://db.vanillagaming.org/?spell=17651) as intended. They then disappear and reappear healed (as intended), however when they reappear the Spectral Projections (https://db.vanillagaming.org/?npc=11263) don't die.

**Expected behavior**: 
The Tutors should cast the spell, which summons Spectral Projections then go invisible. 5 seconds later the projections should be removed and the tutor comes back, healed.

All of this is working perfectly except that when the Tutor comes back any remaining projections aren't removed.

**Steps to reproduce**:

1. Got to scholomance and clear the first few rooms.
2. Engange a Spectral Tutor and wait for it to cast Image Projection
3. 

**Client version**: 1.12.1

**Commit hash**: 067dd86

**Database version**: Classic-DB 1.8.5 - de40a13

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
I will look at this.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/258bbf1709d0e27530dcaa3ee560b0c6f0de4cb9
Thank you. 👍
