### ISSUE TITLE
[Classic - Bots] SQL query error loading combat orders

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1526]
**Current behavior**: 
When you add a bot there's a SQL error loading the bots previous orders. This seems to be because the script expects a field in the database "auto_follow" that isn't there. The error log is below. Sometimes when I'm loading bots the game hangs for a while, I'm not sure if this is related or not.

2018-01-03 09:46:16 SQL: SELECT combat_order,primary_target,secondary_target,pname,sname,combat_delay,auto_follow FROM playerbot_saved_data WHERE guid = '7'
2018-01-03 09:46:16 query ERROR: Unknown column 'auto_follow' in 'field list'

**Expected behavior**: 
You add in the bot and it loads the combat orders it had when it logged out the last time.

**Steps to reproduce**:

1. Add a bot
2. Give it combat orders (e.g. /t botname orders combat tank)
3. Remove the bot
4. Add it back in

**Client version**: 1.12.1

**Commit hash**: 067dd86

**Database version**: Classic-DB 1.8.5 - de40a13

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
Thanks. I'll look into this.
