### ISSUE TITLE
Quest 12687 Into the Realm of Shadows

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#1528]
**Current behavior**: 
Dark Rider of Acherus [28768] spawning again and again after killing him. It was working correctly a while back. But, now no way to finish quest.
**Expected behavior**: 
Kill Dark Rider of Acherus, Mount Acherus Deathcharger [28782] 
**Steps to reproduce**:
1. Take Quest 12687
2. Kill Dark Rider of Acherus

**Client version**: 
3.3.5
**Commit hash**: 
d099270a5b2bd60ed0e423922d79ba02893a7be9
**Database version**: 
PSDB Latest Rev.
**Operating system**: 
Windows x86

**Comment by Grz3s** [comment]
does PSDB use wotlkDB scripts?

**Comment by Rog360** [comment]
Yes, We have the same death script and eventai as CmangosDB. We only use different scripts if they are not yet done in Cmangos db. So, This is working correctly in CDB?

**Comment by Grz3s** [comment]
i cant reproduce your error... in WotlkDB.

**Comment by Rog360** [comment]
Thanks Grz3s, Looks like the problem is on my side... :(

Thanks for your help.

**Comment by Rog360** [comment]
@Grz3s  Thought you might like to know it was a entry in vehicle_accessory that was causing the issue... :)
