### ISSUE TITLE
[Classic] Westfall Stew Quest (38) can't be handed in

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1529]
**Current behavior**: 
I've collected the needed ingredients (3 Stringy Vulture Meat (id 729), 3 Murloc Eyes (id 730), 3 Goretusk Snouts (id 731) and 3 Okra (id 732)). The quest is showing as completed in the quest log but I can't hand it in to Salma Sandean.

I've tried selling any excess items I had so I only had 3 of each but it still wouldn't hand in.

**Expected behavior**: 
You can hand in the quest after getting 3 of each of the items.

**Steps to reproduce**:

1.  Accept Westfall Stew from Salma Sandean (id 235). You might need to get the pre-requisite from Verna Furlbrow (id 238) first.
2.  Collect 3 of each item (id's 729, 730, 731 and 732)
3.  Attempt to hand in..

**Client version**: 1.12.1

**Commit hash**: 067dd86

**Database version**: Classic-DB 1.8.5 - de40a13

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Grz3s** [comment]
Can't reproduce this on WotlkDB 
let's @cala look on ClassicDB

**Comment by cala** [comment]
I cannot reproduce it either on Classic. However, what comes to my mind is that you need to make sure that you have enough free room in your bags before turning the quest in (4 slots) or it will fail because the 4x3 required items are not yet removed from the bag when the 4 rewards items are put in your bags.

**Comment by Trystanosaurus** [comment]
Ah, that might explain it. I'll close this issue now in that case.

Thanks for taking the time to look into it!
