### ISSUE TITLE
[Classic] Huldar (2057) has missing offhand

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1532]
**Current behavior**: 
Huldar in Loch Modan (coords 52.2, 69.3) has a missing offhand. It's just showing a blue and white checkered box.

![huldar](https://user-images.githubusercontent.com/25745474/34868334-b3813388-f783-11e7-9361-7454d9699ec4.jpg)

**Expected behavior**: 
Unfortunately I'm not sure, the vanilla wowhead just has photos of him with no equipment, presumably he should be holding a shield.

**Steps to reproduce**:

1. Go to Huldar in Loch Modan
2. 
3. 

**Client version**: 1.12.1

**Commit hash**: 067dd86

**Database version**: Classic-DB 1.8.5 - de40a13

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
http://de.wowhead.com/npc=2057/huldar#screenshots:id=36110
