### ISSUE TITLE
[Classic] Error after taxi exit and potential death

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1533]
**Current behavior**: 
If you're on a taxi path and disconnect (or Alt-F4 the client) when you reload you're still on the taxi path, which is great but when you land the server spits out an error message and sometimes you end up taking (fatal) falling damage.

When you do land after the disconnect there's an error message in the server log of "ERROR:Flight path finalized in non-final point. Investigate causes. Destination: 0. Player name: Shifty."

I think like issue #1061 the damage you take depends on the difference in height between the origin point and the destination. I tried Silithus to Un'goro on my level 60 warrior and he didn't take any falling damage though so I'm not sure. Stormwind to Darkshire however killed my level 5 mage. I'm not sure if in this case it's more to do with the characters height when you kill the client that determines the falling damage, though that is a bit of a guess.

I also get "ERROR:HandleMoveNotActiveMover: incorrect mover guid: mover is Player Shifty (Guid: 1) and should be Player Shifty (Guid: 1) instead of Player Shifty (Guid: 1)" errors in the server almost every time I take a taxi but I think that's unrelated.

**Expected behavior**: 
You shouldn't take any falling damage.

**Steps to reproduce**:

1.  Get a flight (Stormwind -> Darkshire seems to work).
2.  Kill the client with Alt-F4.
3.  Log back in and wait for landing.

**Client version**: 1.12.1

**Commit hash**: 067dd86

**Database version**: Classic-DB 1.8.5 - de40a13

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
Confirmed as of today. The damage are not taken 100% so a few tries might be required to have the full issue.

**Comment by Warlockbugs** [comment]
Cannot reproduce with new taxi system, so i think this should be considered as fixed.
