### ISSUE TITLE
Wrong Bind IP on AuthServer and WorldServer

### ISSUE THREAD

**Issue by Natsui31** [cmangos/issues#1539]
**Current behavior**: 

BindIP is always default IP which is 0.0.0.0

**Expected behavior**: 

BindIP should be taken from config file

**Steps to reproduce**:

1. Change BindIP
2. netstat -ano | findstr $PID_realmd

**Client version**: 
N/D
**Commit hash**: 
9ce621b3392da2d9a78e25d1fb2c0e7fcab5aef0
**Database version**: 
N/D
**Operating system**: 
Windows 10 build 16299

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
Should be fixed in:
https://github.com/cmangos/mangos-classic/commit/ab2f3f6725a5ad979c4641a9a8268da9bc537227
https://github.com/cmangos/mangos-tbc/commit/0651e93e625e33de4a5bb03281879d2c90a1ca79
https://github.com/cmangos/mangos-wotlk/commit/33665bce5d458354173ea111a7ab0aaa8bd3518d
