### ISSUE TITLE
[TBC] Kyle the friendly in bloodhoof village

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1540]
**Current behavior**: 
Kyle the friendly is permanently dancing just outside Bloodhoof Village in Mulgore. Kyle the frenzied is running around as he should be for his quest (which works correctly).

**Expected behavior**: 
He shouldn't be there. Kyle the friendly's creature_template id is 23622, there's a creature in the creature database (guid 24761) with that id. I think it should simply be removed.

**Steps to reproduce**:

1. Go to the entrance of Bloodhoof Village.
2. There he is.
3. 

**Client version**: 2.4.3

**Commit hash**: 9035dbf

**Database version**: 1.6 - Rise of the Phoenix - 7a9a564

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
So, when should the dog be dancing in the village? Is there some sort of Quest End Script missing? Or just a "dublicate" spawn which should not be there.

There are some spawns in the world, which simply pose as reminders that some sort of scripting is still missing from a npc/quest etc.

**Comment by Trystanosaurus** [comment]
I probably could have been clearer. It's a duplicate spawn that shouldn't be there.

The quest is Kyle's gone missing (11129):
1. There's a dog called "kyle the frenzied" who runs around the village.
2. You feed him plainstrider meat.
3. He stops, eats the meat and despawns.
4. "kyle the friendly" spawns in his place and dances for a a few seconds then despawns.
5. Then "kyle the frenzied" comes back and continues running around ready for the next person.

All of that is working perfectly. But as well as that there is a version of "kyle the friendly" permanently dancing at the entrance of the village and he should be removed.

My guess would be that he was dancing there when the zone was sniffed and he got imported by mistake, he should only appear for 5 seconds as a result of completing the quest.

**Comment by AnonXS** [comment]
^ this. good to know going to remove him

**Comment by Trystanosaurus** [comment]
Great thanks, I've tested cmangos/tbc-db@f7adde2 and the static spawn's gone and the quest still seems to work perfectly so I'll close this issue.

Thanks for taking the time to sort it out, I know it wasn't really the most game breaking issue!
