### ISSUE TITLE
[CLASSIC][TBC] AHBot Posting Too Many Items in Neutral Auction House

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1541]
**Current behavior**: 
I was noticing that my server became unstable sometimes for 5-10 minutes after first starting it up. I think it might have been something between the server and the SQL database and turning on SQL debug there were a lot of auctions being created and deleted. This was happening on both the Classic and TBC core, I've not tried WotLK.

Looking at the AHbot status with the server freshly started the balance was:
|            | Alliance |  Horde   | Neutral  |  Total   |
| Count      |      150 |       75 |    39040 |    39265 |

I left it going for 15 minutes and the balance became:
|            | Alliance |  Horde   | Neutral  |  Total   |
| Count      |     1650 |     1575 |    38786 |    42011 |

I don't think I've changed anything in the AHBot config which would cause this, the important bits are below:
AuctionHouseBot.Seller.Enabled = 1
AuctionHouseBot.DEBUG.Seller = 0

AuctionHouseBot.Alliance.Items.Amount.Ratio = 100
AuctionHouseBot.Horde.Items.Amount.Ratio = 100
AuctionHouseBot.Neutral.Items.Amount.Ratio = 100

AuctionHouseBot.MinTime = 1
AuctionHouseBot.MaxTime = 72

AuctionHouseBot.Items.Vendor = 0
AuctionHouseBot.Items.Loot = 1
AuctionHouseBot.Items.Misc = 0
AuctionHouseBot.Bind.No = 1
AuctionHouseBot.Bind.Pickup = 0
AuctionHouseBot.Bind.Equip = 1
AuctionHouseBot.Bind.Use = 1
AuctionHouseBot.Bind.Quest = 0
AuctionHouseBot.LockBox.Enabled = 0

AuctionHouseBot.ItemsPerCycle.Boost = 75
AuctionHouseBot.ItemsPerCycle.Normal = 20
AuctionHouseBot.BuyPrice.Seller = 1
AuctionHouseBot.Alliance.Price.Ratio = 200
AuctionHouseBot.Horde.Price.Ratio = 200
AuctionHouseBot.Neutral.Price.Ratio = 200

AuctionHouseBot.Items.ItemLevel.Min = 0
AuctionHouseBot.Items.ItemLevel.Max = 0
AuctionHouseBot.Items.ReqLevel.Min = 0
AuctionHouseBot.Items.ReqLevel.Max = 0
AuctionHouseBot.Items.ReqSkill.Min = 0
AuctionHouseBot.Items.ReqSkill.Max = 0

AuctionHouseBot.Items.Amount.Grey = 0
AuctionHouseBot.Items.Amount.White = 2000
AuctionHouseBot.Items.Amount.Green = 2500
AuctionHouseBot.Items.Amount.Blue = 1500
AuctionHouseBot.Items.Amount.Purple = 1000
AuctionHouseBot.Items.Amount.Orange = 0
AuctionHouseBot.Items.Amount.Yellow = 0

I do have cross faction auction houses turned on in the main server config, I don't know if that would make a difference.

In AuctionHouseBot.cpp (line 108) it does seem to have the neutral auction house as the default config, though I'm afraid I don't really know enough to know if that's a problem or not.

```
class AHB_Seller_Config
{
    public:
        AHB_Seller_Config() : LastMissedItem(0), m_houseType(AUCTION_HOUSE_NEUTRAL), m_minTime(0), m_maxTime(0)
        {
        }
```

**Expected behavior**: 
AHBot spreads auctions out evenly.

**Steps to reproduce**:

1. Activate the AHbot with default settings and wait
2. Check status with GM command ahbot status
3. 

**Client version**: 1.12.1 / 2.4.3

**Commit hash**: 9ce621b / 9035dbf

**Database version**: Below Blackrock Mountain 1.8.5 - 336b905 / Rise of the Phoenix 1.6 - 7a9a564

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Trystanosaurus** [comment]
Just to add to this. I've restarted my server now and the ahbot status is showing

```
==========================================================
|            | Alliance |  Horde   | Neutral  |  Total   |
|--------------------------------------------------------|
| Count      |      150 |      150 |    47620 |    47920 |
==========================================================
```

So I guess what's happening is each time the server is started up it thinks all auctions are neutral, it's then trying to fill the Alliance and Horde auction houses with even more items, so if the server gets restarted a lot the Neutral AH gets tons of items.

**Comment by cala** [comment]
@xfurry ported AH Bot to the core years ago, so I'm assigning this to him in case he has an idea.

**Comment by HerrTrigger** [comment]
(IIrc, @VladimirMangos added ahbot, as one of his last major commits to mangos.)

**Comment by Trystanosaurus** [comment]
Just coming back to this, I think what was causing the issue it that I had AllowTwoSide.Interaction.Auction set to 1.

I think what's happening is when the server restarts and the AHBot asks the server for auctions it uses "AuctionHouseObject* AuctionHouseMgr::GetAuctionsMap(AuctionHouseEntry const* house)" from line 51 of AuctionHouseMgr.cpp (for classic) which returns Neutral for all auctions if the two sided auctions is turned on.

I've since tried with the 2 sided auctions turned off and it behaves a lot better. It can still hang on startup though if the server has been off for a day or two and there area lot of auctions to remove/replace.

**Comment by killerwife** [comment]
Since AH bot got rewritten, closing this.
