### ISSUE TITLE
[TBC DB] Call to arms always on

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1542]
**Current behavior**: 
Currently all 4 call to arms events (entry 18 to 21 in the database) are always running.

In the database they have the same occurrence as length, so they're all always on. Length is 5760 (which is 4 days) so that's fine but occurrence should be 4 weeks (40320 - 4x7x24x60).

Also the start date for eye of the storm is wrong, it's 2010-01-07 02:00:00 which is a Thursday (so it'd run from early Thursday-Sunday instead of Friday-Monday), it should be 2011-01-07 02:00:00 which is a Friday, it then fits in with the dates for the other three events (2011-01-14 02:00:00, 2011-01-21 02:00:00 and 2011-01-28 02:00:00).

I'm afraid I know nothing about pull requests or proper formatting of SQL for this project but my fix is:

```
UPDATE `mangos`.`game_event` SET `occurence`='40320' WHERE  `entry`=18;
UPDATE `mangos`.`game_event` SET `occurence`='40320' WHERE  `entry`=19;
UPDATE `mangos`.`game_event` SET `occurence`='40320' WHERE  `entry`=20;
UPDATE `mangos`.`game_event` SET `start_time`='2011-01-07 02:00:00', `occurence`='40320' WHERE  `entry`=21;
```

**Expected behavior**: 
There should only be one running at a time, for 4 days around the weekends.

**Steps to reproduce**:

1. Go to any capital city and see the flags and call to arms NPCs overlapping
2. Or run event list from the console
3. 

**Client version**: 2.4.3

**Commit hash**: 9035dbf

**Database version**: Rise of the Phoenix 1.6 - 7a9a564

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Fixed in https://github.com/cmangos/tbc-db/commit/6efd76d7828d746f6f584ca24932c61208042f9c
