### ISSUE TITLE
[Classic] Triage Quest patients still loose health after being healed

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1543]
**Current behavior**: 
In the quest Triage you have to heal 15 patients before 6 die. While they're on the triage mats they gradually loose health. After you have used the quest item on them their health does regenerate but they still gradually loose health. For the patients that start off critically injured that means they tend to die after you've healed them causing you to fail the quest.

Their code seems to be in scripts\world\npcs_special.cpp

Their's a custom UpdateAI there that handles their health going down and a SpellHit that handles them healing on successful item use, but the SpellHit doesn't override their update so they do keep loosing health until they despawn.

**Expected behavior**: 
They stop loosing health when healed.

**Steps to reproduce**:

1. On a horde character get first aid 250 and be level 35 or more.
2. Go to Doctor Gregory Victor in Hammerfall (creature id 12920) and accept the triage quest.
3. Watch the critically injured patients shout how you've saved them, just before they die.

**Client version**: 1.12.1

**Commit hash**: 3f7e6c1

**Database version**: Below Blackrock Mountain 1.8.5 - c6ccbca

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
Your analyse of the issue is indeed correct. I'll fix it soon. Thank you.

**Comment by cala** [comment]
Could you retry doing the quest with latest revision, please ? The whole script seems to be broken for me and I can't tell if something changed recently or if my install is simply corrupted.

If it still works the same, I suggest the following update if you can also test it:
```diff
--- a/src/game/AI/ScriptDevAI/scripts/world/npcs_special.cpp
+++ b/src/game/AI/ScriptDevAI/scripts/world/npcs_special.cpp
@@ -262,10 +262,11 @@ struct npc_doctorAI : public ScriptedAI
 
 struct npc_injured_patientAI : public ScriptedAI
 {
-    npc_injured_patientAI(Creature* pCreature) : ScriptedAI(pCreature) {Reset();}
+    npc_injured_patientAI(Creature* pCreature) : ScriptedAI(pCreature), isSaved(false) {Reset();}
 
     ObjectGuid m_doctorGuid;
     Location* m_pCoord;
+    bool isSaved;
 
     void Reset() override
     {
@@ -325,6 +326,7 @@ struct npc_injured_patientAI : public ScriptedAI
             }
 
             m_creature->SetWalk(false);
+            isSaved = true;
 
             switch (m_creature->GetEntry())
             {
@@ -344,6 +346,10 @@ struct npc_injured_patientAI : public ScriptedAI
 
     void UpdateAI(const uint32 uiDiff) override
     {
+        // Don't reduce health if already healed
+        if (isSaved)
+            return;
+
         // lower HP on every world tick makes it a useful counter, not officlone though
         uint32 uiHPLose = uint32(0.05f * uiDiff);
         if (m_creature->isAlive() && m_creature->GetHealth() > 1 + uiHPLose)
```

**Comment by Trystanosaurus** [comment]
I've just tried it again now, I'm fairly sure I'm using commit 3f7e6c1 and it was still working the same as before. You heal them but they still loose life.

Then I tried your update (with no other changes to the core) and it seemed to work perfectly. As soon as the spell completed they stopped loosing life and I was able to complete the quest. I also had a quick look at the alliance version too and that one was working fine as well, so it seems to sort it!

There is one tiny thing, that sometimes the patients will appear on a mat with another patient, or where there's a corpse but I wouldn't be surprised if the same thing happened on live servers back in the day.

**Comment by cala** [comment]
Then its my local install that may be broken after all the recent tests and changes I made to it. Not a big issue.

Thank you for confirming that the fix works, I'll push it then. As for the corpse stacking, it also happened on retail if memory serves.
