### ISSUE TITLE
[WOTLK] Clearcasting Stays on After Spell Cast - Affects "Your Next Spell" Type Abilities

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1545]
**Current behavior**: 
As a mage, when I get the clearcasting buff from the arcane concentration talent the buff doesn't dissapear after the first spell I cast, so I get free spells for 15 seconds.

I had the same issue with the brain freeze talent (0 mana instant fireballs for 10 seconds) and netherwind focus, the 8 peice set bonus of the Netherwind Regalia (giving me all spell cast instantly for 10 seconds).

Spell id's from the dbc file are:
Clearcasting - 12536
Brain freeze - 57761
Netherwind focus - 22008

Presumably other similar affects may show the same behaviour. I tried it out on the classic core and it seemed to be working okay, at least clearcasting.

**Expected behavior**: 
After the first cast the buffs should end.

**Steps to reproduce**:

1. Get a mage high enough level to learn arcane concentration (lvl 20 should cap it).
2. Cast until you get the buff.
3. Enjoy free spells.

**Client version**: 3.3.5a

**Commit hash**: 17aa7cf

**Database version**: 7d1e818

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Should be resolved.
