### ISSUE TITLE
Quest Lunar Fireworks 

### ISSUE THREAD

**Issue by Evilkiiller** [cmangos/issues#1547]
**Current behavior**: 
Quest Does Not complete
**Expected behavior**: 
It's supposed to show up as 1/2 or 2/2 When you let the fireworks off. i have closed the quest and accepted it agian Multiple times to No end
**Steps to reproduce**:
1. Server wide event, Speak to a Lunar Festival Herald to Begin the quest. 

2. Complete the first Quest by speaking to a Lunar Festival Harbinger. Then Take the Second Quest Which Should be "LUNAR FIREWORKS" 
 
3. When you have the quest Your supposed to buy 8 Lunar fireworks and 2 Lunar Fireworks Clusters. When you let them off it should go  1/8 2/8 Ect.  

**Client version**: 
2.4.3
**Commit hash**: 
Unkown
**Database version**: 
TBC-DB 1.4.3 - 006 Pre-Release beta build for CMaNGOS-TBC

**Operating system**: 
Windows 2016

**Comment by cala** [comment]
Closed by https://github.com/cmangos/tbc-db/commit/2a0ae8ff47014b5ef640f116983c5ec4bc7fad09
You need to update to latest core version first.
