### ISSUE TITLE
TBC Spell Bug，Chain Damage

### ISSUE THREAD

**Issue by shinefield** [cmangos/issues#1548]
Version TBC 2.4.3

Warrior and Felguard
“Cleave” Cannot be used
The charge is not close enough.

Hunter
“Multiple Shot” Cannot be used
“Trap” Cannot be used

Shaman
“lightning chain” Cannot be used

summary
Chain Damage Spell Cannot be used
feel is cant find target

**Comment by evil-at-wow** [comment]
I didn't actually check, but I can make an educated guess what's going on here. I bet these spells are broken for a similar reason as I mentioned in cmangos/issues#1504.

**Comment by shinefield** [comment]
Thank you for your answer，Have you solved the problem?

**Comment by evil-at-wow** [comment]
No, I didn't spend any time on it because killerwife said he had it handled. For the time being I avoided the problem by not updating my server :wink:

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/64ebf44071ddc564e3476e3b38846b7b003a9894
