### ISSUE TITLE
[TBC] PlayerBot  findcommand BUG，Server crash

### ISSUE THREAD

**Issue by shinefield** [cmangos/issues#1549]
file: game/PlayerBot/Base/PlayerBotAI.cpp

void PlayerbotAI::_HandleCommandFind(std::string& text, Player& /*fromPlayer*/)
{
    ...
    m_lootTargets.pop_front();
    ...
}
two execute find Server crash

**Comment by cala** [comment]
Thank you for your report. Can you detail a bit more in which circumstances you were using the find command ? (syntax, actual target of the bot master, actual target of the bot...) and so on, please ?

**Comment by shinefield** [comment]
1.add bot
2.add party
3.execute find ok
4.execute find Server crash

Sorry，My English is poor
