### ISSUE TITLE
[Quest - 11878] Khu'nok Will Know

### ISSUE THREAD

**Issue by AliziaKaline** [cmangos/issues#1550]
**Current behavior**: 
The creature [Orphaned Mammoth Calf (ID 25861)](http://www.wowhead.com/npc=25861/orphaned-mammoth-calf) isn't summoned at the beginning of the quest [Khu'nok Will Know (ID 11878)](url).

**Expected behavior**: 
It must be summoned by the spell [Call Mammoth Orphan (ID 46232)](http://www.wowhead.com/spell=46232/call-mammoth-orphan).

**Steps to reproduce**:
1. .go xyz 3198.335 5282.036 47.1 571
2. Take the quest (previous quest : [Help Those That Cannot Help Themselves(ID 11876)](http://www.wowhead.com/quest=11876/help-those-that-cannot-help-themselves))

**Client version**: 
3.3.5a

**Commit hash**: 
ec4a5999f8e0573f172bfdf704849b4fd9db339f

**Database version**: 
WoTLKDB v1.1 'The Warsong' for CMaNGOS-WOTLK 13965, update 13972_01

**Operating system**: 
W10

**Fix suggestion** : 
```
INSERT INTO `mangos`.`dbscripts_on_quest_start` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `buddy_entry`, `search_radius`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`)
VALUES (11878, 0, 15, 46232, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 'Orphaned Mammoth Calf Spawn');

UPDATE `mangos`.`quest_template` SET `StartScript` = '11878' WHERE `entry` = '11878';
```

**Other issue** : 
Currently, the spell summon a critter but it must be a guardian. [(source)](https://youtu.be/31fb6QuUjhE?t=15s)

**Comment by Grz3s** [comment]
quest was fixed here...
https://github.com/cmangos/wotlk-db/commit/b88d0bb457de975b4809d41deaf34699971ed7ff
are u sure that you're using latest DB ? (we're 160commits ahead from 1.1 release)

**Comment by AliziaKaline** [comment]
My DB mustn't be updated. All is fine.
