### ISSUE TITLE
[WotLK] Flesh Eater (creature id 3) has only 1 health

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1553]
**Current behavior**: 
The Flesh Eaters in Duskwood (creature id  3) have only one health. I had a quick look in the database but things like health modifier (1.02) and min/max health (664/713) seemed okay.

**Expected behavior**: 
They should have more health, unfortunately I  haven't found a good source for how much.

**Steps to reproduce**:

1. Go to a flesh eater (.go creature id 3)
2. Check health
3. 

**Client version**:  3.3.5a

**Commit hash**: ec4a599

**Database version**: 500244f

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
Expansion -1 -> 0 ?

**Comment by Grz3s** [comment]
can be closed
