### ISSUE TITLE
[WotLK] Razegore fight, destroy egg targets already destroyed eggs

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1556]
**Current behavior**: 
When you are possessing Razegore in Blackwing Lair sometimes his destroy egg spell targets an already destroyed egg. This can make the encounter impossible to beat because you have to destroy them all and the eggs on the far platform are very close together.

When it does target a destroyed egg you get the console message "HandleGameObjectUseOpcode: CMSG_GAMEOBJ_USE for despawned GameObject (Entry 177807), didn't expect this to happen."

Also during this fight no adds seem to spawn, though the fight at least doesn't need the adds to be winnable.

**Expected behavior**: 
The spell only targets destroyed eggs.

**Steps to reproduce**:

1. Go to blackwing lair .tele blackwinglair
2. Kill the controller and use the orb (engage him before killing him or the fight doesn't start properly)
3. Take Razegore to the platform he starts on and try destroying some eggs.

**Client version**: 3.3.5a

**Commit hash**: ec4a599

**Database version**: 500244f

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
Fixed by one of the commits from the wall that was recently pushed.
