### ISSUE TITLE
[WOTLK] Playerbot Priest Casts Fortitude Repeatedly

### ISSUE THREAD

**Issue by Hermetica** [cmangos/issues#1557]
**Current behavior**: 
When playing with a Priest Bot, Bot casts Word of Fortitude repeatedly on party members with Toughness perk granted by Mining skill.
This probably occurs with any non-removable intrinsic buff which has the same effect as a caster buff.

**Expected behavior**: 
Priest Bot recognizes that Toughness can't be overridden and ignores it when checking for similar buffs.

**Additional Info**:
The PlayerBotAI.cpp file contains a Buff method which cycles through existing Auras looking for "compatible" auras, upon finding one, it compares the "value" of the current buff with the "expected value" of the new buff.  If it the new buff is higher, the Bot casts the buff.  In the above example, the spell grants +8 stamina (e.g.) the Toughness perk grants +3 stamina.  Because casting the buff does not override the toughness and toughness occupies the earliest slot, the code is executed on every AI cycle.

I fixed this in mine by cycling over all buffs and only casting if the buff is higher than "all" similar effects.  This is probably not optimal and will result in additional bugs.  It probably should just ignore the "non-removable" intrinsic buffs.

**Comment by derflongshanks** [comment]
I copied the check in playerbot classic, which is basically checking if there is a better aura there and if not then buffing. Rather than checking against each current buff to find if the buff is better than any existing one

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-wotlk/commit/e60bdb7b31f4b51e3412d4b9a761c6df24d4436b
Though WotLK would need an overhaul as it is wildly different (and in many points behind) Classic and TBC branches.
