### ISSUE TITLE
Hostile NPCs do not attack players

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1559]
**Current behavior**: 

Hostile NPCs do not attack players even when staying on top of them. Engaging them makes them evade instantly.

I noticed that this happened after the whole batch of commits from today. The NPCs were working fine when I pushed my Omen commits this morning.

**Expected behavior**: 

They should attack players

**Steps to reproduce**:

1. Log a player
2. Move to any creature with a red platename
3. Dance safely on its head...

**Client version**: 
1.12.1

**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/4e00672d354bcda3d742669cb07fb5e61e5a9e67

**Database version**: 
Classic DB v1.9

**Operating system**: 
Windows 7

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
I will make this a priority. Expect to hear from me today or tomorrow.

**Comment by killerwife** [comment]
Found cause, this is an issue specific to vanilla due to some missing backports unrelated to my code.

**Comment by cala** [comment]
Thank you for looking so quick into this. 👍

**Comment by killerwife** [comment]
Its np. I was prepared to do this. 82 commits just beg for mistakes like this.
