### ISSUE TITLE
[TBC] Pathfinder NormalizeZ

### ISSUE THREAD

**Issue by dunjeon** [cmangos/issues#1562]
**Current behavior**: 
Places mobs located in very shallow water below ground level.  This causes the mobs to be hidden or only displayed partially.

**Expected behavior**: 
Mobs should be on the ground proper so they can be seen.

**Steps to reproduce**:
mongosd.conf line #249:
PathFinder.NormalizeZ = 1

1. Find an area with very shallow water (ankle deep?) and mobs won't be displayed correctly
2. The "river" in WC is a great example
3. Set PathFinder.NormalizeZ = 0 and mobs are placed correctly

void PathFinder::NormalizePath()
Located in world.cpp line: 546

**Client version**: 
2.4.3
**Commit hash**: 

**Database version**: 
TBCDB_1.6.0_RiseOfThePhoenix.sql

**Operating system**: 
Win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
Poking @cyberium for he worked on NPC is shallow waters, recently.

**Comment by AnonXS** [comment]
easily tested with players present in black morass, if they stand in water and you teleport to them, you fall below map.

**Comment by al3xc1985** [comment]
Doble poking @cyberium . He is the great one! :P

**Comment by killerwife** [comment]
Will be fixed in next export.

**Comment by al3xc1985** [comment]
Eee, u are rhe greatest one

**Comment by Szymplo** [comment]
I'm not sure if it's correct to write this here. Currently i didn't notice problem with mobs in shallow water visualisation. But there is a problem with fighting them. They evade ranged attacks, heals as not in combat, suddenly run away from fight without any reason. I think it's connected with Z-axis problem. I'm not skilled programmer but it looks like they sometimes hiding in water even if it's knee deep.
I upgraded server yesterday. I found some piece of code " shallow water case for Unit::UpdateAllowedZ" and checked my build files. This files are up-to date (float minWaterDeep /*= DEFAULT_COLLISION_HEIGHT*) and so on, but problem still exist.
I tested in cave on the way to Wailing Caverns, mobz first shallow pound are hard healing,evading...

**Comment by cyberium** [comment]
This look like same issue related https://github.com/cmangos/mangos-tbc/commit/1db4c57b68f96760a52cd7fd583e6fa024ea5eda#commitcomment-39428139

I will in comming days take a look on it (will see if its fixable in reasonable amount of time). But its not related to this issue, thus this issue is fixed as you can confirm that creature are now correctly displayed in shallow water.

**Comment by Szymplo** [comment]
Thank you very much. This bug is one of most annoying in great Cmangos software. I Really appreciate your work. If it's not very difficult I'll be happy to see it fixed in future.
And yeah, it seems to be problem like "1db4c57"
