### ISSUE TITLE
Quest: Garments of the moon

### ISSUE THREAD

**Issue by mc2programmer** [cmangos/issues#1563]
Unable to heal and fortify Sentinel Shaya (possibly others)
in order to complete night elf priest quest Garments of the moon.

Should be able to cast lesser heal rank 2 and fortify on npc. Instead I get "invalid target"

I know this was working previously to updating database.

 

WOTLK 3.3.5a

**Commit hash**: 

DB Version 13965

Window 7

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by mc2programmer** [comment]
Not sure if this is correct but here is a fix

in world db under creature_template id 12429 the UnitFlags was set to 32768 (related to water.....)
I changed it to 4096 (UNIT_FLAG_PVP)

I guess here is the command that would work
UPDATE creature_template SET UnitFlags = '4096' WHERE creature_template.Entry =12429;
I think I remember her being invisible as well and she is not longer invisible. I have not verified this for other races, but I suspect they are not working either.

**Comment by cala** [comment]
Thank you for your report.
The script is the same in Classic, TBC and WotLK. As it is working fine in Classic (tested right now), I assume there is an error in WotLK DB. Poking @Grz3s

**Comment by Grz3s** [comment]
No... WotlkDB has the same values .. and all Garments quests, that using sd2 script, were working fine..... until something was changed in core.  (Invaild target - if we'll try cast)

Only diff i see there IS  in addon b2_1_pvp_state = 1 (classic has b2_1_pvp = 16)  .. 
if ill change that to 16 ..player will cast both spells on himself.

Both spells have this:
Targets (21, 0) (TARGET_SINGLE_FRIEND, NO_TARGET)  ...  <-- target damaged?

Anyway: this may be related to this issue also:
https://github.com/cmangos/wotlk-db/issues/208

Im sure that:
@Warlockbugs 
@killerwife 
Will know what happened...

**Comment by killerwife** [comment]
Spell ID?

**Comment by Grz3s** [comment]
SPELL_LESSER_HEAL_R2    = 2052,
    SPELL_FORTITUDE_R1      = 1243,

**Comment by killerwife** [comment]
That's strange. I should not have affected that target type in any way. Unless the guy has wrong flags, and CanAssist evaluates as false that is. I will try to look once I am home.

**Comment by Grz3s** [comment]
creature_template  for any npc from these quests .. is the same in classic and wotlk ... unitflags = 32768, extraflags  =2 (no diff if ill remove that also) etc...

**Comment by killerwife** [comment]
Check creature type flags.

**Comment by Grz3s** [comment]
creatureTypeFlags = 0
b2_1_pvp_state = 1  (classic has b2_1_flags = 16)  -- if ill set 16.. player willl cast that spell on himself only
Let me repeat that.. we did not change anything in (npcs) these quests  + quest that i gave link above...
But somehow they stopped working.
spells dont like friendly creatures anymore in wotlk ...

**Comment by killerwife** [comment]
Because most of the time you can heal creatures. The two exceptions are pvp NPCs (with ally / horde symbol) and ones with special creature type flags. Only then can a player heal a creature.

**Comment by Grz3s** [comment]
b2_1_pvp_state = 1 yes they have that... and "invaild target" shows up

**Comment by cala** [comment]
What is strange is that it does not affect Classic and WotLK equally (works for the former, not the second, did not try on TBC).  :/

**Comment by killerwife** [comment]
I have identified the issue and have delegated it to @Warlockbugs . Its related to the change of UNIT_FLAG_PVP. In vanilla and TBC it works 1:1, but in wotlk its different for some reason.

**Comment by Warlockbugs** [comment]
Should be fixed.
