### ISSUE TITLE
[CLASSIC][TBC][WOTLK] Auto-broadcasting System Implementation

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#1564]
**Current behavior**:  I would like to activate autobroadcast or request it

**Expected behavior**: have a autobroadcast config and table

**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: all

**Commit hash**: 

**Database version**: all

**Operating system**: ubuntu server

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
I am not quite sure as its already a long time ago, but i think retail servers had some sort of autobroadcast system too.

So i am pro the idea of implementing something like this.

**Comment by cavaclub** [comment]
and btw all other emulators have

**Comment by killerwife** [comment]
Closing due to vagueness and inactivity

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/pull/581
