### ISSUE TITLE
[TBC] spell Ritual of Summoning and  Meeting Stone Summon bug.

### ISSUE THREAD

**Issue by keyshuwen** [cmangos/issues#1565]
Current behavior:
Summoning target error.

Steps to reproduce:
A B C D

A  call D
B Click the transmission gate.
C Click the transmission gate.

Result, summon C.

It looks like a target call error.

cmangos/mangos-tbc@33444d4
Previous normal work.

Database version: required_s2369_01_mangos_spell_affect
Operating system: windos 10 (x64)

**Comment by killerwife** [comment]
Fixed in https://github.com/cmangos/mangos-tbc/commit/3af616f1cea3fce3fb4a8dae10ec3a613fa942ad
