### ISSUE TITLE
[WOTLK] Rogue Vanish Spell ID 1856 Multiple Ranks

### ISSUE THREAD

**Issue by mc2programmer** [cmangos/issues#1567]
Rogue Vanish tries to cast, but instantly breaks stealth.

Vanish should set invisible/stealth state for 10 secs + other effects
Allows the rogue to vanish from sight, entering an improved stealth mode for 10sec. Also breaks movement impairing effects. More effective than Vanish (Rank 1).

Just cast Rogue Vanish (Spell ID 1856, 1857) or any other rank (seems like other ranks are also have the same issue)

**Client version**:  WotLK 3.3.5a(12340)

**Commit hash**: 

**Database version**:  13965

Windows 7

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Vanish works as intended.
