### ISSUE TITLE
[WOTLK] Food Spell Buff Patch

### ISSUE THREAD

**Issue by NeatElves** [cmangos/issues#1570]
Event item no work final buff(10 sec)
1. Slow-Roasted Turkey
https://github.com/cmangos/wotlk-db/issues/197
http://www.wowhead.com/item=44838
http://www.wowhead.com/spell=65422
Attack power and Stamina - spell 65414
```sql
UPDATE  `spell_template` SET `EffectTriggerSpell3` = '65414' WHERE `Id` =65422;
```
2. Candied Sweet Potato
https://github.com/cmangos/wotlk-db/issues/196
http://www.wowhead.com/item=44839
http://www.wowhead.com/spell=65418
Haste rating and Stamina - spell 65410
```sql
UPDATE  `spell_template` SET `EffectTriggerSpell3` = '65410' WHERE `Id` =65418;
```
3. Cranberry Chutney
https://github.com/cmangos/wotlk-db/issues/195
http://www.wowhead.com/item=44840
http://www.wowhead.com/spell=65420
Spell power and Stamina - spell 65412
```sql
UPDATE  `spell_template` SET `EffectTriggerSpell3` = '65412' WHERE `Id` =65420;
```
4.  Pumpkin Pie
https://github.com/cmangos/wotlk-db/issues/180
http://www.wowhead.com/item=44836
http://www.wowhead.com/spell=65421
Spirit and Stamina - spell 65415
```sql
UPDATE  `spell_template` SET `EffectTriggerSpell3` = '65415' WHERE `Id` =65421;
```
5. Spice Bread Stuffing
https://github.com/cmangos/wotlk-db/issues/179
http://www.wowhead.com/item=44837
http://www.wowhead.com/spell=65416
Hit rating and Stamina - spell 65416
```sql
UPDATE  `spell_template` SET `EffectTriggerSpell3` = '65416' WHERE `Id` =65419;
```
~~6. Bread of the Dead, Bobbing Apple, Winter Veil Cookie
https://github.com/cmangos/wotlk-db/issues/178
http://www.wowhead.com/item=46691
http://www.wowhead.com/item=20516
http://www.wowhead.com/item=21254
http://www.wowhead.com/spell=24869
Stamina and Spirit for 15 min - spell 24870~~
```sql
UPDATE `spell_template` SET `Effect2` = '6', `EffectDieSides2` = '1', `EffectImplicitTargetA2` = '1', `EffectApplyAuraName2` = '23', `EffectAmplitude2` = '10000', `EffectTriggerSpell2` = '24870' WHERE `Id` =24869;
```

**Comment by cala** [comment]
Point six is fixed by https://github.com/cmangos/mangos-wotlk/commit/6f5130cf1590bea5aac8f3d13746c80221e5eb45

**Comment by Grz3s** [comment]
Fixed:
https://github.com/cmangos/mangos-wotlk/commit/ba3f1aa218f99663f13ab97625b2c6afe24613db
