### ISSUE TITLE
[WOTLK] Glyphs Do Not Work

### ISSUE THREAD

**Issue by SailorCamilleMoon** [cmangos/issues#1571]
**Current behavior**: 
Right click to use glyph, glyph does not appear in the menu and it will disappear from your backpack.

**Expected behavior**: 
Right click to use glyph, it will then appear in your menu.

**Steps to reproduce**:

1. Make or acquire any glyph for your class. 
2. Right click to use it.
3. It will disappear from your Backpack and won't appear in your glyph menu.

**Client version**: 
WoTLK
**Commit hash**: 
89fa2ccfccb6c5dfc867a56e4e53413808043899
**Database version**: 
wotlk-db
**Operating system**: 
Ubuntu 17.10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by hipejoe** [comment]
its not 100% right, but I returned back the final else logic in filltargetmap. seemed to be skipping the target map fill all together, 
ex: 
after:
    }
    tmpUnitLists[i].push_back(m_caster); // add caster so that we can cast dest only effects
}

ADD this:

else
{
   if (m_caster->GetObjectGuid().IsPet())
   {
       SetTargetMap(SpellEffectIndex(i), TARGET_SELF, tmpUnitLists[i /*==effToIndex[i]*/]);
   }   
   else
   {
        SetTargetMap(SpellEffectIndex(i), TARGET_EFFECT_SELECT, tmpUnitLists[i /*==effToIndex[i]*/]);
   }
}

**Comment by killerwife** [comment]
That fix is not in line with how targets should work though. Give a list of spells and target types which do not work.

**Comment by hipejoe** [comment]
right! I'll put some more time into the missing type information, instead of the bucket workaround.

**Comment by SailorCamilleMoon** [comment]
Tried a similar work around myself, but to no avail. Thank you for your help though =)

**Comment by killerwife** [comment]
This is already working as I fixed it long time ago.
