### ISSUE TITLE
Azuregos spells can not target players

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1572]
**Current behavior**: 
Fighting Azuregos (NPC 6109 with a faction of 7, neutral) results in a mostly melee combat. Azuregos casts his spells as expected but they never target players fighting him. However, his magic reflection shield works: a spell casted at him is reflected to original caster.
I assume this is related to his faction and the way his relation to players is evaluated because changing Azuregos faction to something that is hostile to players fixes the issue: the spells target players as they should. So, kindly poking @Warlockbugs 

This is a new issue: Azuregos encounter was working fine when I slightly reworked a few months ago.

I did not test, but all neutral NPCs should then have the same twisted behaviour.

**Expected behavior**: 
Azuregos spells should target players when they engage him.

**Steps to reproduce**:

1. .go creature Azuregos
2. attack him (or use the gossip menu to make him attack)
3. observe combat log and notice only melee damage from Azuregos

**Client version**: 
1.12.1

**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/cedd8df86767dcff6b17499ffbf444127d7c0dd8

**Database version**: 
Classic DB v1.9

**Operating system**: 
Mac OS X

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Faction 7 is a player faction.

**Comment by cala** [comment]
Are you sure ? According to the wiki, this is "Creature" and its masks do not match players.

**Comment by killerwife** [comment]
I might be wrong, but aren't there two Azuregos' in Azshara? One neutral not attackable and one hostile?

**Comment by cala** [comment]
Nearly. ;-)
There are two of them, both are neutral with gossip flag. One is attackable or can be engaged by gossip, the other one has flags UNIT_FLAG_IMMUNE_TO_PLAYER and UNIT_FLAG_IMMUNE_TO_NPC that are never removed.

I'm talking about the first one and I'm adamant it was working fine [last time](https://github.com/cmangos/mangos-classic/commit/e18d029250bc4665a3868c04edce1c10d4b8557c) I updated his script. I also tested the encounter during again first half of 2017 and it was still working so this is a "mostly" recent regression.

**Comment by cala** [comment]
Also, as I said, the issue is not about Azuregos himself, but neutral NPCs.

You can try NPC 10558 (Hearthsinger Forresten). His Shoot and Multishot spells work (16100 & 14443) hit players, but Demolarizing Shout (16244) never targets players.
Idem with NPC 7098 (Ironbeak Screecher) : its Defeaning Screech (3589) never hits.

You can pick whichever NPC in `SELECT * FROM creature_template WHERE factionalliance=7 and AIName="EventAI";`, half the spells are no longer targeting players.

**Comment by killerwife** [comment]
Ok. I will check this when I am at home where I have working classic setup.

**Comment by cala** [comment]
Great, thanks ! :+1:

**Comment by killerwife** [comment]
This was merely a "subject to research" thing. It was a port from the old system, it was just inconsistently used.
