### ISSUE TITLE
Improve revision.h Generation

### ISSUE THREAD

**Issue by jimmybrancaccio** [cmangos/issues#1573]
**Current behavior**: 

Currently when this file is generated, `src/tools/genrevision/genrevision.cpp` will check this file to fetch the git commit id:

`.git/FETCH_HEAD`

however this appears to show you the master commit id, which may not be the same as the branch you've created an are on.

**Expected behavior**: 

I would expect revision.h to list the git commit information of the branch I am presently on, wether that be master or another branch I've made on my own.

**Steps to reproduce**:

1. Pull latest code from any of the repos (classic, TBC, WotLK).
2. Create a new branch - `git checkout -b new_branch cff9a21`
3. Go into your build directory and run cmake. cmake should actually showing you the right commit in its output.
4. Run make. You probably don't need to wait until make is running to check `mangos/src/shared/revision.h`. It should list the master branches commit id instead of your branches commit id.

**Client version**: 

N/A

**Commit hash**: 

N/A - though for this I was using cmangos-wotlk (e9b4d5fac1f2e8b6a39782fcf9dd9755d873b419) and changed to (cff9a21e99c80868d1c4118033a73bf14feff34f)

**Database version**: 

N/A

**Operating system**: 

Linux - Ubuntu 14.04

**Notes**:

Of note, I was having issues with a lot of OnError: Connection Reset by Peer messages, and mangosd using 100% CPU usage in e9b4d5fac1f2e8b6a39782fcf9dd9755d873b419 of cmangos-wotlk so I wanted to move back to previous commits because it wasn't happening in those builds. I was going nuts because each time I started up ./realmd it would show the master build commit:

``` bash
[mangos@hostname ~/build/src/realmd]$ ./realmd -c /home/mangos/mangos/run/etc/realmd.conf
CMaNGOS/0.18 (2018-02-27 11:55:53 - e9b4d5fac1f2e8b6a39782fcf9dd9755d873b419) for Linux_x64 (little-endian) [realm-daemon]
```

even though it was building the code from my branch on the previous commits.

It would be a good idea for the code which generates revision.h to use another method to fetch which commit you're actually at. Perhaps it can check the branch and look at the refs file:

``` bash
$ head .git/refs/heads/allow-PlayerBot-to-pick-up-quest-items
cff9a21e99c80868d1c4118033a73bf14feff34f
```

**Comment by Muehe** [comment]
Discord log:

![genrevision](https://user-images.githubusercontent.com/8838573/37003475-6a0f289a-20cd-11e8-9b25-0bd3207cb78e.png)


Relevant git commands to get the actual commit, date and time:

```
user@machine:/mangos-classic$ git rev-parse HEAD
<commitID>
user@machine:/mangos-classic$ TZ=UTC git show --quiet --date=iso-strict-local --format="%ad" <commitID>
0000-00-00T00:00:00+00:00
```

The `TZ=UTC` is needed to get a timezone independent time. Otherwise the time might contain a timezone offset other than `+00:00`, based on which timezone the author was in.

```
user@machine:/mangos-classic$ git show --quiet --date=iso-strict-local --format="%ad" <commitID>
0000-00-00T01:00:00+01:00
```
