### ISSUE TITLE
[Classic][Regression] max Health issue for some creatures

### ISSUE THREAD

**Issue by RichardGe2** [cmangos/issues#1574]
My database & bin  are currently at latest revision.

I'm noticing max health issue on random creatures: They are very low compared to database archives and cmangos  creature_template.MaxLevelHealth.

all my Rate.Creature.*****   in the .conf are at 1.0  

I have several examples :   
Ironforge guard( 5595) has 2614 health in cmangos. archives report 5 K
Cenario Caretaker (4050)  has 610 health in cmangos. archives report 1.9 K
Fineous Darkvire (9056)   has 2K health in cmangos. archives report 29 K
Jaina ( 4968 ) has 2332 health  in cmangos. archives report 185 K  
Thrall ( 4949 ) has 2665 health  in cmangos. archives report 40 K  
King Magni ( 2784 )  has 3331 health  in cmangos. archives report 17 K  
( I didn't check the other world bosses, I think it's the same issue )

It seems critical, my concern is that this issue seems to affect a large number of creatures... or maybe it's me who is not lucky when I pick random NPCs ...

This seems to be related to the usage of creature_template_classlevelstats : you are using it instead of the creature_template.MaxLevelHealth.

I'm wondering why you don't use MaxLevelHealth anymore ?
What's your thoughts, do you think it's affecting a large number of creatures ?
Can't we have a script comparing the  creature_template_classlevelstats   versus   creature_template.MaxLevelHealth  and red flag all creatures where the difference is above a percentage ?
btw, I didn't check the damage, maybe they are low too ?

**Comment by cala** [comment]
Thank you for this very complete and clear report.

We are currently using two systems at the same time.

1. One that relies on `creature_template_classlevelstats` and various multipliers from `creature_template`
2. One that uses solely fields from `creature_template`, like `MaxLevelHealth`and ignores multipliers

A given creature can only use one of these systems and ideally, we would like to only use the former. Unfortunately, defining correct multipliers is a difficult task for a lot of creatures like triggers or dummy NPCs or creatures that were heavily changed across the various patches of the game. This is even harder for Classic as we have close to little reliable sources for those.

A few months ago, the two systems were coexisting only for health and mana stats and the switch from one to the other was determined by the sign of `creature_template.ArmorMultiplier`. If it was positive: the first system was used, if not then the creature was using the second one.

Recently, @killerwife extended the systems to also work with damage stats. That was a much welcome update and I asked then that DB developers were still able to use `creature_template.ArmorMultiplier` as a switch. If memory serves, he included that change.

I'm unfortunately busy as of now. Could you please check if the creatures you are reporting are using a positive or negative `creature_template.ArmorMultiplier` ? If positive, can you turn it to -1 ? If already negative, can you change the `creature_template.HealthMultiplier` to a negative value ?

**Comment by RichardGe2** [comment]
the 5 creatures have ArmorMultiplier=-1  and   HealthMultiplier=1
if I change HealthMultiplier to -1,  creatures  2784, 4050, 4968, 5595  will have only 1 point of life.
and creature 9056 will have an 3 billion of life (invalid number I assume)

**Comment by cala** [comment]
This confirm there is an issue with the switches from one system to the other. I will have a look at it when I can.

**Comment by cala** [comment]
@RichardGe2 could you test this patch and tell me if it fixes the issue, please ?
```diff
--- a/src/game/Entities/Creature.cpp
+++ b/src/game/Entities/Creature.cpp
@@ -1183,19 +1183,15 @@ void Creature::SelectLevel(uint32 forcedLevel /*= USE_DEFAULT_DATABASE_LEVEL*/)
         // Use Creature Stats to calculate stat values
 
         // health
-        if (cinfo->HealthMultiplier >= 0)
+        if (cinfo->ArmorMultiplier >= 0)
+        {
             health = cCLS->BaseHealth * cinfo->HealthMultiplier;
-
-        // mana
-        if (cinfo->PowerMultiplier >= 0)
             mana = cCLS->BaseMana * cinfo->PowerMultiplier;
-
-        // armor
-        if (cinfo->ArmorMultiplier >= 0)
             armor = cCLS->BaseArmor * cinfo->ArmorMultiplier;
+        }
 
         // damage
-        if (cinfo->DamageMultiplier >= 0)
+        if (cinfo->DamageMultiplier >= 0 && cinfo->ArmorMultiplier >= 0)
         {
             usedDamageMulti = true;
             mainMinDmg = ((cCLS->BaseDamage * cinfo->DamageVariance) + (cCLS->BaseMeleeAttackPower / 14.0f)) * (cinfo->MeleeBaseAttackTime / 1000.0f) * damageMulti;
@@ -1211,40 +1207,34 @@ void Creature::SelectLevel(uint32 forcedLevel /*= USE_DEFAULT_DATABASE_LEVEL*/)
         }
     }
 
-    if (!usedDamageMulti || health == -1 || mana == -1 || armor == -1.f) // some field needs to default to old db fields
+    if (!usedDamageMulti || armor == -1.f) // some field needs to default to old db fields
     {
         if (forcedLevel == USE_DEFAULT_DATABASE_LEVEL || (forcedLevel >= minlevel && forcedLevel <= maxlevel))
         {
             // Use old style to calculate stat values
             float rellevel = maxlevel == minlevel ? 0 : (float(level - minlevel)) / (maxlevel - minlevel);
 
-            // health
-            if (health == -1.f)
+            // health, mana and armor
+            if (armor == -1.f)
             {
                 uint32 minhealth = std::min(cinfo->MaxLevelHealth, cinfo->MinLevelHealth);
                 uint32 maxhealth = std::max(cinfo->MaxLevelHealth, cinfo->MinLevelHealth);
                 health = uint32(minhealth + uint32(rellevel * (maxhealth - minhealth)));
-            }
-
-            // mana
-            if (mana == -1.f)
-            {
+                
                 uint32 minmana = std::min(cinfo->MaxLevelMana, cinfo->MinLevelMana);
                 uint32 maxmana = std::max(cinfo->MaxLevelMana, cinfo->MinLevelMana);
                 mana = minmana + uint32(rellevel * (maxmana - minmana));
-            }
-
-            // armor
-            if (armor == -1.f)
+                
                 armor = cinfo->Armor;
+            }
 
             // damage
             if (!usedDamageMulti)
             {
                 mainMinDmg = cinfo->MinMeleeDmg * damageMulti;
                 mainMaxDmg = cinfo->MaxMeleeDmg * damageMulti;
-                offMinDmg = cinfo->MinMeleeDmg * damageMulti;
-                offMaxDmg = cinfo->MaxMeleeDmg * damageMulti;
+                offMinDmg = cinfo->MinMeleeDmg * damageMulti / 2.0f;
+                offMaxDmg = cinfo->MaxMeleeDmg * damageMulti / 2.0f;
                 minRangedDmg = cinfo->MinRangedDmg * damageMulti;
                 maxRangedDmg = cinfo->MaxRangedDmg * damageMulti;
 ```

**Comment by cala** [comment]
Poke @RichardGe2

**Comment by RichardGe2** [comment]
I'm going to test that shortly, stay tuned

**Comment by RichardGe2** [comment]
@cala ,

With this path it's now way better :)

Ironforge guard( 5595) has now  5 K - like archives
Cenario Caretaker (4050) has now 1.9 K - like archives
Fineous Darkvire (9056) has now 11 K  ( archives report 27~29 K ... but maybe wrong archives ?)
Jaina ( 4968 ) has now 185 K - like archives
Thrall ( 4949 ) has now 637 K - like archives
King Magni ( 2784 ) has now  17 K - like archives  (it's weak btw...)

**Comment by cala** [comment]
Thank you for this feedback. Fineous Darkvire had his stats reviewed last year, so this may explain the difference. I'll push my patch to the Classic branch soon. :+1:
