### ISSUE TITLE
[Regression] Master Loot makes quest items always available

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1576]
**Current behavior**: 

When having a group with Master Loot set, if the creature killed by the players has a quest item in its loot table (ChanceOrQuestChance < 0), then the item will be available for all players whenever they are on the quest or not. I did not managed to spot which commit caused that issue to appear recently.
Poking @killerwife and @cyberium who are the only ones to have work on the loot system in a not too far past, to my knowledge.

**Expected behavior**: 

Quest items should only be available to players that are on the quest.

**Steps to reproduce**:

1. log a player and invite a friend (works also with a bot), set loot to Master Loot
2. `.go creature azuregos`
3. kill a few stone giants in the vicinity: everyone should be able to see and pick up "Giant Silver Vein" items though they are quest items (drop rate is 80%)

**Client version**: 
1.12.1

**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/7542662e02a671667f2c363f89ab798e096c72a3
**Database version**: 
Classic DB v1.9

**Operating system**: 
Mac OS X and Windows 7

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
I will add it to the list of bugs. But this does sound awfully similar like my issue with horde seeing ally magtheridons head. And its propably the result of my recent fixes, where the items mentioned above were not being looted for when the person who opened the corpse didnt have the q.
