### ISSUE TITLE
Items with conditions cannot be looted from gameobjects

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1577]
**Current behavior**: 

When looting a gameobject (like herbs), items that require a condition to be fulfilled (like have 1 item XXX in inventory) do not display in loot window whenever the condition is fulfilled or not.

I noticed that when I was trying to fix cmangos/issues#1494
I thought at first that I was unable to reproduce the issue, but further testing proved that looting items from gameobjects (herbs) that have a condition (that was fulfilled) was no longer possible. Removing the condition_id for this item made it lootable again. Looting items with the same condition from a creature was still working however.
More than probably related to https://github.com/cmangos/mangos-classic/commit/50331cd8e8e56a7b4ee0d3c5ef91eb61a22c5429 so kindly poking @killerwife because reverting the commit fixes the issue.

**Expected behavior**:

Items looted from gameobjects that have a condition_id in the gameobject_loot_template should display when the condition is fulfilled and remain hidden otherwise.

**Steps to reproduce**:

1. log a character with high herbalism skills
2. `additem 11511`
3. `.tele felwood` and collect from herbs
4. notice that no 'Fel creep' is ever looted though it has a 50% drop chance when item 11511 is in inventory

**Client version**: 
1.12.1

**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/f51374e7368a270bfe2e8b9ab47d49403072af20

**Database version**: 
Classic DB v1.9

**Operating system**: 
Mac OS X and Windows 7

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
@cala I think I know why. Try to test the following: 
in
bool LootTemplate::PlayerOrGroupFulfilsCondition(const Loot& loot, Player const* lootOwner, uint16 conditionId)

change
if (ownerSet.size() == 1)
to
if (ownerSet.size() <= 1)

**Comment by cala** [comment]
This seems to fix the issue, indeed ! :+1:

**Comment by killerwife** [comment]
Well that was easy. I didn't take into account the fact that only creatures have owner set. I will commit it tomorrow to all cores.
