### ISSUE TITLE
[Regression] GAMEOBJECT_TYPE_TRAP with faction 0 do not trigger

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1578]
**Current behavior**: 

Trap GameObjects with faction 0 do not trigger when players enter trap radius (i.e. the spell is not cast).

Changing the GO faction to some hostile one makes the trap trigger. Changing the faction to a friendly one does not make the trap trigger. So I highly suspect something related to Relations. 

This breaks Onyxia encounter, Rookery in UBRS, Mazthoril teleporting runes in Winterspring, Engineering teleporters, Winter Veil Wondervolt and some other ones.

Thus poking @killerwife for this one. I'm sorry for harassing you during the last days, but I'm reviewing/checking/testing many things at the moment, so the probability for issue to be raised is far higher. :wink:  So offering you a drink : :beer: 

**Expected behavior**: 

Trap GOs with no faction set should trigger when players are coming near them (if radius is not zero, of course).

**Steps to reproduce**:

1. `.go object id 176164`
2. Step onto the rune on the floor, several times, back and forth
3. Notice the character is not teleported at the top of mountain as it should by spell 17159

**Client version**: 

1.12.1

**Commit hash**: 

https://github.com/cmangos/mangos-classic/commit/21174d3db7427a525bf35da7b6ae8ac3765e95f7

**Database version**: 

Classic DB v1.9

**Operating system**: 

Windows 7

**Comment by killerwife** [comment]
Looking into it. I am searching in sniffs for the GO.

**Comment by cala** [comment]
Thanks! :+1: 
Just for information, but I think you were already aware of it, those GOs were previously working.

**Comment by killerwife** [comment]
[2] UpdateType: CreateObject1
[2] GUID: Full: 0xF11002B0240012C1 Entry: 176164 UInt64: 17370386718309487297
[2] Object Type: GameObject (5)
[2] Update Flags: Unknown1, LowGuid, StationaryObject, GOPosition, GORotation (856)
[2] GO Position GUID: 0x0
[2] GO Position: X: 5893.286 Y: -4054.652 Z: 596.3094
[2] GO Transport Position: X: 5893.286 Y: -4054.652 Z: 596.3094
[2] GO Orientation: 2.268925
[2] Corpse Orientation: 0
[2] Unk Int32: 3741319168
[2] Low GUID: 603984577
[2] GO Rotation: X: 0 Y: 0 Z: 0.9063072 W: 0.4226195
[2] (0) OBJECT_FIELD_GUID: Full: 0xF51012F1 UInt64: 4111471345
[2] (2) OBJECT_FIELD_TYPE: (33) Object, GameObject
[2] (3) OBJECT_FIELD_ENTRY: 176164
[2] (4) OBJECT_FIELD_SCALE_X: 1
[2] (8) GAMEOBJECT_DISPLAYID: 1287
[2] (14) GAMEOBJECT_DYNAMIC: 4294901760
[2] (17) GAMEOBJECT_BYTES_1_1: 1
[2] (17) GAMEOBJECT_BYTES_1_2: 6
[2] (17) GAMEOBJECT_BYTES_1_3: 0
[2] (17) GAMEOBJECT_BYTES_1_4: 255

ServerToClient: SMSG_GAMEOBJECT_QUERY_RESPONSE (0x005F) Length: 163 ConnectionIndex: 0 Time: 09/24/2009 20:29:20.000 Number: 2659
Entry: 176164
Type: Trap (6)
Display ID: 1287
[0] Name: Rune of Mazthoril LT
[1] Name: 
[2] Name: 
[3] Name: 
Icon Name: 
Cast Caption: 
Unk String: 
[0] Data: 0
[1] Data: 0
[2] Data: 2
[3] Data: 17159
[4] Data: 0
[5] Data: 1
[6] Data: 0
[7] Data: 0
[8] Data: 0
[9] Data: 0
[10] Data: 0
[11] Data: 0
[12] Data: 0
[13] Data: 0
[14] Data: 0
[15] Data: 0
[16] Data: 0
[17] Data: 0
[18] Data: 0
[19] Data: 0
[20] Data: 0
[21] Data: 0
[22] Data: 0
[23] Data: 0
Size: 1
[0] Quest Item: 0
[1] Quest Item: 0
[2] Quest Item: 0
[3] Quest Item: 0
[4] Quest Item: 0
[5] Quest Item: 0

Answer: Set the trap extra flag. It can be used to target everyone.

**Comment by killerwife** [comment]
ctrl +f goInfo->trapCustom.triggerOn

**Comment by cala** [comment]
Good try, thank you... but no, using `gameobject_template.CustomData1` does not seem to do the trick.

- Default value (0 = unfriendly) no longer works: neither players nor NPCs trigger the trap GO (this is the issue reported here)
- Value 1 (target is friendly) does not work: neither players nor NPCs trigger the trap GO
- Value 2 (everyone) does work : players trigger the trap GO... **but** NPCs also trigger it, meaning they are teleported in the case of GO 176164 , in the Rookery, dragonkins trigger all the eggs they are walking by and so does Onyxia in her lair, making these encounters impossible to do

I still think that we are not handling faction 0 properly in regard of players/NPCs factions or at least that this case is not handled in `switch (goInfo->trapCustom.triggerOn)`.

**Comment by killerwife** [comment]
I was afraid of that NPC problem. Well that means this needs a custom check. Factions for GOs work the same way they work for NPCs, so it makes the trap neutral to everyone I think. Which means that this propably calls for a custom script to only target players.

**Comment by killerwife** [comment]
Elaboration:
This will be exported soon.
`                    if (std::function<bool(Unit*)>* functor = sScriptDevAIMgr.OnTrapSearch(this))
                    {
                        MaNGOS::AnyUnitFulfillingConditionInRangeCheck u_check(this, *functor, radius);
                        MaNGOS::UnitSearcher<MaNGOS::AnyUnitFulfillingConditionInRangeCheck> checker(target, u_check);
                        Cell::VisitAllObjects(this, checker, radius);
                    }`

**Comment by cala** [comment]
> Factions for GOs work the same way they work for NPCs, so it makes the trap neutral to everyone I think

Basically, you are saying that we were previously handling those GO (and anything with faction 0) wrong because they were acting neutral with NPCs while considering players as hostile. And now that the core has the proper behaviour (everything is neutral to faction O) we have to workaround it for the traps. Am I understanding it correctly?

**Comment by killerwife** [comment]
Well, I would not call it a workaround for a simple reason. Traps are not just traps, but basically spellcaster GOs. I have several cases of GOs which dont trigger on proximity, but cast a spell periodically like an NPC. With the addition of GO AI, the point is that one day this will be possible, just like it is possible for Units. For now, the only GO spellcasting features supported are Relations and Distance checks.

And yes, we were handling all sorts of stuff wrong in relation to (pun intended) GOs and their faction. I have had to correct several faction in TBC for it to work properly.

**Comment by cala** [comment]
> I have several cases of GOs which dont trigger on proximity, but cast a spell periodically like an NPC. With the addition of GO AI, the point is that one day this will be possible, just like it is possible for Units.

As you may have noticed, I already started using this much welcomed feature - in this very specific case, indeed - and have plan to use it more in a not so distant future. ;-)

Regarding GOs in general, I think we should have a talk about how they are handled in core when we can, because some things (at least) are wrong or incomplete, especially for TRAP or GOOBER types and I would like to improve them.

**Comment by killerwife** [comment]
@cala Underwater bubbles are the reason I added that trapCustom.triggerOn stuff. Though to be fair, those might have wrong faction.

**Comment by killerwife** [comment]
@cala Underwater bubbles are the reason I added that trapCustom.triggerOn stuff. Though to be fair, those might have wrong faction.

**Comment by cala** [comment]
It is possible we are not speaking of the same underwater bubbles but I'll have a look at those to be sure. ;-)

**Comment by cala** [comment]
Whatever, the two underwater bubbles required to complete the quest (at least not dying while doing it) are working as intended.

**Comment by cala** [comment]
Seems to be fixed by one of the commits from the recent wall that was pushed.

**Comment by killerwife** [comment]
It was? Huh? How.

**Comment by cala** [comment]
I'll recheck with a fully fresh install then.

**Comment by cala** [comment]
Done: those GOs work like they should again and like they previously did before the span of time when I made this report: they are triggered by player proximity and are not triggered by NPCs.

Some wild magic was probably at hand if you did not fix this on purpose.

**Comment by cala** [comment]
Reopening this issue as there indeed seems to be something amiss.
As a summary:

1. Sometime between December 2017 and February 2018, `GAMEOBJECT_TYPE_TRAP` with faction 0 stopped triggering when a player was within radius distance. Changing `gameobject_template.CustomData1` to force the trap to react to hostile or friendly targets did not work. Changing it to react to everyone did work for players... but also for NPCs, which should not be the case
2. After the batch of commits added in March 21, the behaviour of trap `GAMEOBJECT_TYPE_TRAP` with faction 0 was partly reintroduced as they started to trigger again when a player was within radius distance while ignoring NPCs. Hence the closure of this issue though I understand from above that this fix was not intended
3. I noticed last week that there is still an issue with `GAMEOBJECT_TYPE_TRAP` with faction 0. Though they are now triggered again by player, they still don't have the proper relation to players. An example is GO 180517 (Putrid Mushroom) used in Emeriss encounter. This GO is summoned as a wild object with `SPELL_EFFECT_SUMMON_OBJECT_WILD` by spell 24904. The trap is triggered by players and the trap spell 24871 is cast but it fails to target that same players through `(TARGET_EFFECT_SELECT, TARGET_ALL_ENEMY_IN_AREA_INSTANT)`. Players triggering the trap should suffer the negative effect of spell 24871, this is the whole purpose of this GO. Changing the GO's faction to one that is hostile to players enable the correct behaviour for the GO.

Thus, I see three possible explanations: 

1. The trap GO template does not have the proper faction. But this is doubtful as every database I checked has faction 0 for this GO.
2. Wild GO should inherit the faction of the original caster (Emeriss in this case). This is also doubtful as it would defeat the purpose of **wild** summoning if we need to introduce some link between the caster and the wild object...
3. `GAMEOBJECT_TYPE_TRAP` with faction 0 should be considered as kind of hostile to players, instead of pure neutral

Required SQL change to test this GO:
```SQL
UPDATE gameobject_template SET data2=5, ExtraFlags=1 WHERE entry=180517;
```
GO's sniffed faction is 0. Emeriss' faction is 50.

**Comment by killerwife** [comment]
TARGET_ALL_ENEMY_IN_AREA_INSTANT explicitly requires HOSTILES, so this is directly influenced by faction. @Warlockbugs this means IsEnemy is failing for the GO 180517. Are you sure you default to correct default inside ReputationRank GameObject::GetReactionTo(Unit const* unit) const?

@cala please show the packet for casting the spell in sniff (24871,24904), as well as the GO create object packet for 180517. Specifically I need to see if OBJECT_FIELD_CREATED_BY is set.

**Comment by cala** [comment]
@killerwife unfortunately, I don't have sniffs for Emeriss fight. My comment about the GO's faction was based on all DBs having the same value (especially Trinity DB that has this entry marked as verified).

If you are looking for another GO with the same faction/behaviour and that is also now broken, there is Kurinnaxx Sand Trap (GO 180647), that is still available in-game. It is summoned with the same logic, using spells (25648 / 26524) and triggers trap spell 25656. It is possible that @evil-at-wow or @Tobschinski already have data of that encounter.

**Comment by evil-at-wow** [comment]
The good thing about bosses in instances is that, unlike world bosses, you can still go annoy them even after they've been killed by another guild (*). And having spread chaos and destruction in AQ20 too, I'm pretty sure dear Kurinnaxx's unfortunate demise is in my archives somewhere. I'll have a look.

**Comment by killerwife** [comment]
Uff, thats a problem then. I uncovered a potential issue in one of my Tier 3 Relations functions. But I need data to verify it, since its not in client.

**Comment by Tobschinski** [comment]
Entry: 180647
GAMEOBJECT_FACTION: 14

I've never seen a wild trap with no faction, but I have seen lots of missing factions in go_template.

**Comment by evil-at-wow** [comment]
@Tobschinski Can you show the GO spawn data as well, or specifically the OBJECT_FIELD_CREATED_BY, as requested by killerwife? Then I don't have to dive in my archive any more :smile:

**Comment by evil-at-wow** [comment]
That also counts as showing it - it wasn't clear from your previous post those fields are not set.

**Comment by cala** [comment]
@Tobschinski so basically you are saying that all GO with faction=0 in our database**s** are in fact missing their correct faction value. That is very interesting and sheds a different light on this issue.

On a slightly related topic, could you provide data2 and data7 for Trap Sand / GO 180647, please ?

**Comment by Tobschinski** [comment]
I can't tell you, I've just never seen one (when it damages the player). But I also have to admit that I never really payed attention.

I have 0 and 0 for both, 2 and 7.

**Comment by cala** [comment]
Thank you. These are unexpected, but I'll deal with it.

**Comment by cala** [comment]
After some researches from the Great and Awesome @Tobschinski it seems that there are only a handful of GO traps with faction 0 and that they do not interact with players nor NPCs.

This means that most of the GO traps in our databases with faction = 0 are in fact missing their proper faction. @grz3s I'll fix some of them soon but we should investigate the proper faction every time we deal with such a GO.
