### ISSUE TITLE
[Classic] - regression - Voidwalker doesn't follow at the end of combat 

### ISSUE THREAD

**Issue by RichardGe2** [cmangos/issues#1579]
My Core is just ~2 weeks old - but I don't see related fix on that in git.

in most of the cases, at the end of Combat, my void walker doesn't follow me and stays near the creature's corps. This was not doing that before, I assume this is related to the new AI stuff.

Don't know if it's the best way to fix it, but on my server, I just added this 'else' inside PetAI::UpdateAI

```
if (owner->IsWithinDistInMap(m_unit, PET_FOLLOW_DIST))
{
m_unit->GetMotionMaster()->Clear(false);
m_unit->GetMotionMaster()->MoveIdle();
}
else//<---- I added this else
{
m_unit->GetMotionMaster()->MoveFollow(owner, PET_FOLLOW_DIST, PET_FOLLOW_ANGLE);
}
```

So this is forcing the follow as soon as the combat is ended

**Comment by killerwife** [comment]
@RichardGe2 The fix should be somewhere in PetAI::EnterEvadeMode, pet doesnt go into evade on going back to player, but its still the function where creature ends combat. I suggest you try to add it there.

**Comment by Warlockbugs** [comment]
Fixed in the latest revision.
