### ISSUE TITLE
The Damage During the Blizzard Decline Will Consume Clearcasting

### ISSUE THREAD

**Issue by keyshuwen** [cmangos/issues#1580]
**Current behavior**: 
Cast Blizzard spell = 10

**Expected behavior**: 
Blizzard In the process of descent, Clearcasting will be consumed.

**Steps to reproduce**:
1.  Cast Blizzard.
2.  Mage Click the talent Arcane Concentration.
3.  The damage during the blizzard decline will consume Clearcasting.

**Commit hash**:   new.

**Database version**:  new

**Operating system**:  win10 x64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by jimmybrancaccio** [comment]
@keyshuwen Can you confirm if this is an issue on the latest commits?

**Comment by yatzi888** [comment]
Can confirm this is still occuring - https://www.youtube.com/watch?v=JWCefN1etb8&feature=youtu.be Latest commits.

**Comment by jimmybrancaccio** [comment]
@yatzi888 Is this still a problem? If so please provide the commit ids.

**Comment by cocely** [comment]
Problem still exists

**Comment by killerwife** [comment]
Fixed as of https://github.com/cmangos/mangos-tbc/commit/731c0748e31c99174139f1871d3fb55eace85d33 on tbc branch.
