### ISSUE TITLE
[CLASSIC] Know Sap Talent Bug

### ISSUE THREAD

**Issue by Purownage** [cmangos/issues#1581]
Hello old schoolers,

I've noticed that since the tweak made for rogue improve sap talent when it should have restealth you (35% to 90% depend on stage.) it wipe aggro on mobs and so sap is evade by the mobs resulting to leave you unstealth and aggro mobs.

I know this seems to be a hard fix but I wonder why the skill isn't take in charge by the core?
https://classicdb.ch/?spell=14076  (Rank 1)
https://classicdb.ch/?spell=14094  (Rank 2)
https://classicdb.ch/?spell=14095  (Rank 3)
and
https://classicdb.ch/?spell=14093 (Stealth/Vanish)

thanks

**Comment by jimmybrancaccio** [comment]
@Purownage So that we may properly look into this issue, if it's still an issue can you open a new case with full details including steps for replication. Thank you.
