### ISSUE TITLE
[CLASSIC] Naxx Portal Issue

### ISSUE THREAD

**Issue by Purownage** [cmangos/issues#1582]
Hello,

When using Naxx portals at the end of wings pet stay locked into that boss room.
Pet should be teleport with player. But thats not all, if the hunter right click on pet then dismiss manually THEN immediatly log out when he relog he will be teleported to stormwind in an uninstanced version of the stockade. (in the version you cant access normally.) he can now wander in an instance with no mobs at all exactly like the stockade.

step to reproduce : 
clear naxx plague wing when you kill last boss take portal with your pet active.
Right click on your pet icon and select dismiss. (it will say not in line of sight but continue the process.)
log out.
relog.
you inside stormwind in uninstanced stockade.

thanks :)

**Comment by jimmybrancaccio** [comment]
@Purownage So that we may properly look into this issue, if it's still an issue can you open a new case with full details. Thank you.
