### ISSUE TITLE
[ALL VERSION] Flightpath exit position incorrect

### ISSUE THREAD

**Issue by Daribon** [cmangos/issues#1584]
**Current behavior**: 
Flight paths on every emulator currently uses taxinode.dbc to check if you can use a flight path in that area, then once you are onboard a flight path it will use taxipathnode.dbc until the end.
Which is incorrect, if a emulator only uses taxipathnode.dbc you will end up in the wrong position in the end, which is usually seen as you falling down to the ground once flight path is finished.
**Expected behavior**: 
What is supposed to happen after you reach last id of a pathid at your final destination is that the
server should read from taxinode.dbc and teleport you to the location stated inside of the .dbc.
So if you take a flight from Westfall to Stormwind, you should end up at the position .go xyz -8840.56 489.7 109.61 0 after teleportation, which is stated by taxinode.dbc under the name Stormwind, Elwynn".

Videos from vanilla displaying this:
https://www.youtube.com/watch?v=0Rx3xCa51IU
https://www.youtube.com/watch?v=jo-cfBB4BY8
This still exists on retail, so it's very easy to test.
**Steps to reproduce**:

1.  Take flightpath from any place to Stormwind, notice that you spawn on different location than where you spawned on retail when flight is over.

**Client version**: 
1.12.1, 5875

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Actually we have this fixed. https://github.com/cmangos/mangos-classic/blob/master/src/game/MotionGenerators/WaypointMovementGenerator.cpp#L407

So I am not sure you have tested cmangos.

**Comment by Daribon** [comment]
Oh ye, seems to have been fixed recently.
https://github.com/cmangos/mangos-classic/commit/e639d0bbd4067a2d871485b942a1d502499bd7ec#diff-d6cd676add41b04b916296ade8e51ff1
