### ISSUE TITLE
Duplicated Creatures

### ISSUE THREAD

**Issue by LewisPotato** [cmangos/issues#1586]
**Current behavior**: 
In Ghostlands, Tranquillien where the flight master is there are meant to be 2 Silvermoon Dragonhawk's standing by side of him but instead there are 2 by each side of him, there is only meant to be one on each side, I'm not sure which one is the original one because they're slightly out of place.

**Expected behavior**: 
Should only be one on each side.
**Steps to reproduce**:

1. Go to Ghostlands.
2. Or just teleport to Tranquillien
3. See it for yourself.

**Client version**: 
TBC 2.4.3
**Commit hash**: 
CMaNGOS TBC/0.18 (2018-03-19 16:29:18 - 9e0dd6f8010a3a3bc626bee0434d97bdadf745e5) for Win64 (little-endian)
**Database version**: 
Using World DB: TBC-DB 1.5.0 'PRE-RELEASE BUILD' for CMaNGOS-TBC
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Grz3s** [comment]
@cala 
WotlkDB has that place correct... no duplicates there ;)

**Comment by AnonXS** [comment]
dublicate due to rework, spawns are going to be removed soon.

**Comment by cala** [comment]
@Grz3s Tranquilien and Ghostlands have been added in TBC so I doubt I'll find any duplicate there in Classic DB. ;-)
