### ISSUE TITLE
Pet Movement

### ISSUE THREAD

**Issue by LewisPotato** [cmangos/issues#1588]
**Current behavior**: 
Warlock's pets won't return to you after they've killed something, resulting in you having to click Follow to get them to keep with you.
**Expected behavior**: 
After it has successfully killed the creature it should return to the owner and continue to follow the owner.
**Steps to reproduce**:

1. Create a warlock.
2. Let it automatically aggro and go off to attack that creature.
3. Notice it won't return to you afterwards without having to click Follow.

**Client version**: 
World of Warcraft Classic - 1.12.2
**Commit hash**: 
6b97d3c4dd7c7dee035ea1cc42fb07485c058926
**Database version**: 
Classic DB version 1.9 "The Black Dragonflight". For core Classic z2717.
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by RichardGe2** [comment]
duplicated with my report  :  
https://github.com/cmangos/issues/issues/1579
