### ISSUE TITLE
[TBC] Mobs Spawned by Jewelcraft Figurine's Are With Wrong Level

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1589]
**Current behavior**: 
When you use [Figurine - Seaspray Albatross], [Figurine - Shadowsong Panther] or [Figurine - Crimson Serpent] will spawn a little pet lvl 5.

**Expected behavior**: 
When you use one of this itens, they should spawn a mob with the same level as the caster.

**Steps to reproduce**:

1. Create a character and use .level 69 on yourself.
2. .additem 35700 (To add [Figurine - Crimson Serpent])
3. Use and see that mob level is only 5.

**Client version**: 
2.4.3 8606

**OBS**: 
You can hackfix changing the level of the mob on Database from 5 to 70, because those trinkets need at least lvl 70 to use, so, the mobs min level will aways be 70.

**Comment by AnonXS** [comment]
some spells provide the level the spawned npc should have, some should have the players level.
https://github.com/lh-server/core/commit/f283ef4dcab9d3cdf1b517bf9d45fa3194247bea
