### ISSUE TITLE
Quest Bug

### ISSUE THREAD

**Issue by LewisPotato** [cmangos/issues#1591]
**Current behavior**: 
In Tirisfal Glades, Deathknell as you walk out of Deathknell there is a quest you pick up from the NPC Galvin Montague and when you accept the quest A Rogue's Deal he will you the quest but it is saying it is complete (the complete quest button is lit) I click it and it triggers the quest complete noise but it doesn't complete.
**Expected behavior**: 
The quest should complete and give you the reward for it.
**Steps to reproduce**:

1. Make an undead or just use any horde character.
2. Go to Tirisfal Glades, Deathknell.
3. Accept the quest, then try and complete it.

**Client version**: 
World of Warcraft Classic - 1.12.2
**Commit hash**: 
6b97d3c4dd7c7dee035ea1cc42fb07485c058926
**Database version**: 
Classic DB version 1.9 "The Black Dragonflight". For core Classic z2717.
**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Grz3s** [comment]
You didnt remove item(by mistake or smth) he gave you to deliver for Inkeeper Renee? .. i see no reason why this quest would not work correctly...

**Comment by bdebaere** [comment]
Possibly related: https://github.com/cmangos/issues/issues/1405

**Comment by Levitanious** [comment]
Basically, the quest NPC's **flags** are set to make it _immune to players_ (thanks **AnonXS** for the hint!),
so the solution is just to temporarily remove this immunity.

It will get restored after Calvin-The-NPC will evade from combat.

**cmangos-tbc example**:
Add `m_creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PLAYER);` before the IF clause at [line 155](https://github.com/cmangos/mangos-tbc/blob/69f1ed1070b97def7265e18f09ef4dc903b32503/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/tirisfal_glades.cpp#L155).

Tested. Works. Here are the screens [1](https://media.discordapp.net/attachments/362206349339262978/434899825654497291/unknown.png) and [2](https://media.discordapp.net/attachments/362206349339262978/434899871175147533/unknown.png).

**Comment by cala** [comment]
One small question to @Warlockbugs : here, the involved NPC has `UNIT_FLAG_IMMUNE_TO_PLAYER` set in DB.
In SD2, we remove it with `SetImmuneToPlayer(false)` but then we have to manually readd it on reset.
I would have assumed that the flag would be restored automatically on reset.

Is this intended or is this due to the fact that the reset function for this NPC is also overridden in SD2?

**Comment by cala** [comment]
> Possibly related: #1405

@bdebaere unfortunately, it is not related.

**Comment by Warlockbugs** [comment]
Immune flags have specific script actions attached to them in B's system. My judgment on this would be reviewing all flags currently set in the database, then moving them into scripts and clearing the database. Then "re-adding" will occur in a more organic nature, through script returning to default sort of state.

**Comment by Levitanious** [comment]
I'm sorry i couldn't look deep enough into the structure of the scripting thing, not enough familiarity with the core. I absolutely love the elegant way of having flag set with it's own method. <3 Thanks for your time, @cala
