### ISSUE TITLE
[TBC] Quest 10451 Causes Core Crash

### ISSUE THREAD

**Issue by keyshuwen** [cmangos/issues#1593]
**Current behavior**: 
 In the process of escorting creature, Crash.
Possible updates:

https://github.com/cmangos/mangos-tbc/commit/18cb926cf9fda4f0cdae06010bcb49bb602cbda5

This line crash.  
spirit->GetMotionMaster()->Clear(false, true);  

@killerwife Can you give me some help? Thank you.

**Client version**:  tbc

**Commit hash**: new

**Database version**:  new

**Operating system**:  win10 x64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)
![qq 20180408200104](https://user-images.githubusercontent.com/4241825/38467218-9e3639b0-3b67-11e8-9984-5edfade9f01f.png)

**Comment by MagPurify** [comment]
@keyshuwen 
You can remove this line:
`spirit->GetMotionMaster()->Clear(false, true)`;
That NPC doesn't have motion generator, that's why is crashing it. Haven't created the PR because I am not sure if this is the correct fix for it.
