### ISSUE TITLE
[TBC] Meeting Stone and Summoning Ritual Error

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1594]
**Current behavior**: 
Meeting Stone and Summing Ritual doesn't summon anyone.

**Expected behavior**: 
The target player should receive a message that he is summoned.

**Steps to reproduce**:

1. A B C D
2. A summons D
3. B and C clicks A portal
4. No one gets summoned, and everyone who clicks starts channelling the portal.

**Client version**: 
2.4.3 8086

**Commit hash**: 
Last commit

**Database version**: 
Last TBC-DB

**Operating system**: 
Windows Server 2012 R2

**Comment by SilvioDoMine** [comment]
@killerwife aparrently cmangos/mangos-tbc@3af616f broke the actual summon somehow

**Comment by killerwife** [comment]
Fix:
void Spell::EffectTransmitted(SpellEffectIndex eff_idx)

        case GAMEOBJECT_TYPE_SUMMONING_RITUAL:
        {
            if (m_caster->GetTypeId() == TYPEID_PLAYER)
            {
                Player* player = (Player*) m_caster;
                pGameObj->AddUniqueUse(player);
                pGameObj->SetActionTarget(player->GetSelectionGuid());
                m_caster->AddGameObject(pGameObj);          // will removed at spell cancel
            }
            break;
        }

Busy IRL atm, will push it to cmangos sometime later.

**Comment by SilvioDoMine** [comment]
@killerwife which archive and line should I put this code? ty
