### ISSUE TITLE
[CLASSIC] Shadowglen Hunter Trainer Does Not Train

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1595]
Ayanna Everstride (3596) the hunter trainer in Shadowglen does not train appropriate skills for fresh nightelf hunters. The only skill she trains is Parry, wich is a level 8 spell and should not be trained by her. See:

SELECT * FROM mangos.npc_trainer WHERE entry = 3596;

Here is a picture with the hunter spells up to level 6. She should train these I believe:

![untitled](https://user-images.githubusercontent.com/18726138/38830273-08aaeb10-41bc-11e8-8baa-70bc51767503.png)

Sorry for being lazy and not making a fix myself.

**Comment by Brodyzera** [comment]
I've had the same issue with other starting area hunter trainers.  Do you have any sources for what skills the hunter trainer should offer for low levels?  I wasn't able to find any accurate sources, so I was wondering if you might know where to look.

**Comment by killerwife** [comment]
Luckily I started in that zone way too many times. All shadowglen trainers trained until lvl 6. I am absolutely sure of that. Only difference is that I did like 5 chars in TBC, not vanilla.

**Comment by cala** [comment]
All low level class trainers have the same list of spells. If all of hunter trainers are missing their spells, it is possible to take the list from a high level trainer and remove all spell above level 6.

**Comment by killerwife** [comment]
this was mentioned as fixed. closing
