### ISSUE TITLE
[WotLK] Dungeon Finder in 2018

### ISSUE THREAD

**Issue by Unholny** [cmangos/issues#1596]
Hello everyone!

Today, I decided to join the cMaNGOS community by setting up three realms - classic, tbc and wotlk, which I designed to stay behind the same realmd (loginserver). I have had experience with WoW Emulation in the early 2010s when I was playing around with TrinityCore but nothing that serious - mostly SmartAI scripting, SQL editing or creating missing items/npcs etc as well as small adjustments to the core as I am experienced in OOP.

I found out that the Dungeon Finder feature in WotLK is not working at all. I would be really happy to contribute to this awesome community by fixing / re-working from scratch the Dungeon Finder in order to make it work, but I will need to go through the basics and in the following weeks I will be playing around with the core as well as the database in order to get used to both.

Any collaborators interested in forming a squad and getting the Dungeon finder as well as other nice features working on cMaNGOS?

Peace,
Unholny a.k.a Holiman

**Comment by Unholny** [comment]
Why did you close it?

**Comment by stfx** [comment]
Closed due to 1. inactivity, 2. not being an actual issue report and 3. being a duplicate of #841
