### ISSUE TITLE
[cmangos-tbc] Rogue combo points clear on the target when combat ends.

### ISSUE THREAD

**Issue by rpilatm** [cmangos/issues#1598]
**Current behavior**: 
Rogue combo points clear on the target when the rogue leaves combat (tested on mobs and players.)
Oddly doesn't happen when the Rogue leaves combat through Vanish, only when leaving combat naturally - running away / stop attacking.
**Expected behavior**: 
Combo points should persist whether the rogue is in combat or not.
**Steps to reproduce**:

1. Build combo points up on a target as a Rogue.
2. Stop attacking / run away and wait for combat to stop.
3. Your combo points will disappear.

**Client version**: 
2.4.3
**Commit hash**: 
b8e2b9308fcf5b2266fc49da3ddc6ae2257e2b2b
**Database version**: 
tbc-db 2.4.3
**Operating system**: 
linux_x64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
WoW Icon 16x16.png Patch 1.12.0 (2006-08-22):
Fixed a bug that made Combo Points disappear from your target when using Vanish.

**Comment by rpilatm** [comment]
this is not when using Vanish, this is when leaving combat naturally.

**Comment by killerwife** [comment]
Yes, thats intended.

**Comment by rpilatm** [comment]
How is losing combo points on a target when leaving combat intended in 2.4.3? Sorry maybe I'm misinformed but the premise is just weird. Would you know how to make it not clear combo points on combat clear?

**Comment by killerwife** [comment]
Yes, on player combat leave i would just pass the same parameter as I did for vanish. But this is indeed blizzlike behaviour, on creature evade you lose combo points.

**Comment by rpilatm** [comment]
Sure I meant only player vs player combat. Thanks for help!

**Comment by rpilatm** [comment]
The only mention I found of dropping combo points on combat exit is here
from Unit.cpp
`void Unit::CombatStop(bool includingCast, bool includingCombo)
{
    if (GetTypeId() == TYPEID_PLAYER)
        ((Player*)this)->SendAttackSwingCancelAttack();     // melee and ranged forced attack cancel

    AttackStop(true, includingCast, includingCombo);
    RemoveAllAttackers();`

How would I go about making an exemption for PvP?
Thanks

**Comment by killerwife** [comment]
You need to first find mentions of it being true on retail 10 years ago. Changing it is the easy part.

**Comment by rpilatm** [comment]
Here's an example, even though it's a custom UI you can clearly see his combo points staying after he enters stealth normally after blinding the enemy player: https://youtu.be/xF4Rx1sQYQU?t=70
and one more from the same video:https://youtu.be/xF4Rx1sQYQU?t=286 
Notice how he says: "Sap, cheap shot, wait out DR and re-open" - that's solely for the purpose of building up combo points for later while dropping combat naturally (re-stealthing).
