### ISSUE TITLE
[CLASSIC] Dynamic Movement Action

### ISSUE THREAD

**Issue by Fuzedknight** [cmangos/issues#1600]
There appears to have been a new bug introduced with Dynamic Movement changes in the past 7 months. After taking a 7 month break from database development when using my old scripts that worked perfectly fine, I've noticed that activating dynamic movement will cause NPCs using it to get extremely close to a player before stopping when working with a turn off combat movement command. For example when using this script:
https://puu.sh/AhrRm/4613b40439.png

The NPC will stand at range and shoot as intended however they WILL NOT chase through LoS. Originally the fix was to enable Dynamic Movement with a script like this.
https://puu.sh/AhrSW/5837de7771.png

7 Months ago, this worked. Also attempting it on the Elysium DB which is 8 year old Mangos it works just fine. However with the most up to date version I've found that anything using this script will not stop at 30 or 40 yards but get to about 8 yards before stopping. Some NPCs that Shoot bows will just run right into melee range from their 30 yard pull distance even though the script demands them to stop at 30 yards. Therefore I conclude that something has been changed with Dynamic Movement recently that is causing this bug. Using the 1st script above without Dynamic movement still works perfectly fine, yet the original issue of the NPC not chasing through LoS returns.

**Comment by Grz3s** [comment]
try this (and let me know):

```sql
-- Illyanna Ravenoak
DELETE FROM creature_ai_scripts WHERE creature_id = 11488;
INSERT INTO creature_ai_scripts VALUES  
('1148801','11488','4','0','100','2','0','0','0','0','49','1','0','0','20','0','0','0','0','0','0','0','Illyanna Ravenoak - Enable Dynamic Movement and Prevent Melee on Aggro'),
('1148802','11488','9','0','100','3','5','30','1700','2000','11','20735','1','0','40','2','0','0','0','0','0','0','Illyanna Ravenoak - Cast Multi-Shot and Set Ranged Weapon Model'),
('1148803','11488','0','0','100','3','7200','12300','13100','19500','11','22914','4','1','40','2','0','0','0','0','0','0','Illyanna Ravenoak - Cast Concussive Shot and Set Ranged Weapon Model'),
('1148804','11488','0','0','100','3','22800','36200','60000','85500','11','22908','4','1','40','2','0','0','0','0','0','0','Illyanna Ravenoak - Cast Volley and Set Ranged Weapon Model'),
('1148805','11488','9','0','100','3','6','80','1000','1000','49','1','0','0','0','0','0','0','0','0','0','0','Illyanna Ravenoak - Enable Dynamic Movement at 6-80 Yards'),
('1148806','11488','9','0','100','3','0','5','1000','1000','49','0','0','0','20','1','0','0','40','1','0','0','Illyanna Ravenoak - Disable Dynamic Movement and Enable Melee and Set Melee Weapon Model at 0-5 Yards'),
('1148807','11488','0','0','100','3','9600','18100','20300','41200','11','22910','0','1','0','0','0','0','0','0','0','0','Illyanna Ravenoak - Cast Immolation Trap'),
('1148808','11488','7','0','100','2','0','0','0','0','40','1','0','0','0','0','0','0','0','0','0','0','Illyanna Ravenoak - Set Melee Weapon Model on Evade');

-- fix
DELETE FROM creature_template_addon WHERE entry = 11488;
UPDATE creature_template SET SpeedRun = 2.023 WHERE entry = 11488;
```

**Comment by Fuzedknight** [comment]
It's slightly better but she will still get closer than she should. When pulled from out of her range she will run to >20 yards. Won't run right into melee range but still not stopping at 30.
https://puu.sh/AhVx5/093de2b81a.png

If body pulled by running into her aggro range you're close enough that she won't stop at all and immediately run to melee range. If you range check her she will always run to >20 yards. LoS also is NOT working with this script.
https://puu.sh/AhVDW/7a200092cd.png

**Comment by Grz3s** [comment]
i also tried many diff options ... without positive result...
so probably you're correct ..that dynamic movement causes this verid issue...
Core devs may help here:
@killerwife @cyberium ...

**Comment by Fuzedknight** [comment]
So I've been experimenting pretty hard and I've discovered something I really can't explain. I was trying to troubleshoot the range problem (the NPC keeps getting too close even without dynamic movement involved which is another issue). After trying for multiple days and many different scripts I got very frustrated and decided to just increase the ranges of the prevent movement, start movement and Shoot scripts OVER the cap of the shoot spell on the original script that used to work. I figured what would happen was that the NPC would be out of range to shoot and therefore simply stand there. The result was rather shocking. When I use this script

> INSERT INTO `creature_ai_scripts` VALUES 
> (1285603, 12856, 11, 0, 100, 0, 0, 0, 0, 0, 21, 0, 0, 0, 20, 0, 0, 0, 23, 1, 0, 0, 'Prevent Combat Movement and Prevent Melee and Set Phase 1 on Spawn'), 
> (1285604, 12856, 9, 5, 100, 1, 5, 35, 2400, 2500, 11, 6660, 1, 0, 40, 2, 0, 0, 21, 0, 0, 0, 'Cast Shoot and Set Ranged Weapon Model (Phase 1)'), 
> (1285605, 12856, 9, 5, 100, 1, 35, 80, 3000, 3100, 21, 1, 1, 0, 20, 1, 0, 0, 0, 0, 0, 0, 'Start Combat Movement and Start Melee at 30 Yards (Phase 1)'), 
> (1285606, 12856, 9, 5, 100, 1, 0, 10, 0, 0, 21, 1, 0, 0, 40, 1, 0, 0, 20, 1, 0, 0, 'Start Combat Movement and Set Melee Weapon Model and Start Melee Below 10 Yards (Phase 1)'), 
> (1285607, 12856, 9, 5, 100, 1, 10, 34, 0, 0, 21, 0, 1, 0, 20, 0, 0, 0, 0, 0, 0, 0, 'Prevent Combat Movement and Prevent Melee at 30 Yards (Phase 1)'),  
> (1285608, 12856, 7, 0, 100, 0, 0, 0, 0, 0, 22, 1, 0, 0, 40, 1, 0, 0, 0, 0, 0, 0, 'Set Phase 1 and Set Melee Weapon Model on Evade');

These numbers are clearly 5 above the cap HOWEVER they work PERFECT. The mob is standing at maximum range tested by me using a similar shoot spell against them and backpedaling out of the shoot range. As soon as I lose the ability to hit them they move forward and begin shooting again. Yet the script itself it telling them to stop 5 yards beyond the max and so by all accounts should not work. Yet it does... I really can't explain why but it might also be key in solving the dynamic movement problem.

**Comment by AnonXS** [comment]
yea i used this way to simulate archer npcs on l4g, it's still not very sightful.
especially the (combat) movement stop on spellcast (shoot) is needed to make it look good but then again its just poluting the script with more and more movement informs for the unit.

**Comment by Fuzedknight** [comment]
I am actually rewriting all my fixes to work within the silly system, the way I have made my work is that it's portable between servers / old iterations of Mangos so imo just leave it the same and just let people know that they need to add range to prevent confusion hah. Or at least have it toggleable like the damage/health modifiers.

**Comment by AnonXS** [comment]
Dynamic Movement was nuked alltogether, can be closed.

**Comment by killerwife** [comment]
Kept in core until all is converted to new ranged AI. Thread is invalid anyhow.
