### ISSUE TITLE
classic Ritual of Summoning Can't use it

### ISSUE THREAD

**Issue by 127y** [cmangos/issues#1601]
**Current behavior**: 

**Expected behavior**: 

**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 

**Commit hash**: 

**Database version**: 

**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
Duplicate of https://github.com/cmangos/issues/issues/1594
You should also take the time to properly fill the issue you open if you want them to be fixed.
