### ISSUE TITLE
[TBC] AoE Effects Such as Frost Nova Don't Apply to Rogue's Vanish

### ISSUE THREAD

**Issue by rpilatm** [cmangos/issues#1608]
**Current behavior**: 
AoE effects such as Frost Nova don't apply on Rogue's Vanish - they bring him out of Stealth but don't freeze him in place.
Proof: https://www.twitch.tv/videos/261313181
**Expected behavior**: 
Rogue should be frozen in place after getting his vanish broken (works fine with Stealth)
**Steps to reproduce**:

1. Vanish as Rogue.
2. Have a Mage use Frost Nova near you.
3. You'll be taken out of Stealth but not frozen in place.

**Client version**: 
2.4.3
**Commit hash**: 
latest
**Database version**: 
latest
**Operating system**: 
linux_64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
.learn 1856 Vanish
.learn 122 Frost Nova
item=5140 Flash Powder

will work when more spell core dependencies are exported.

**Comment by rpilatm** [comment]
@AnonXS also Mage's Water Elemental Frost Nova

**Comment by Pastew** [comment]
I tried to reproduce, but every time it freezes the rogue like I shown below:

![frost_nova](https://user-images.githubusercontent.com/5671416/54090240-53a27800-4372-11e9-9c24-ced14d08f41a.gif)

**Comment by BenDol** [comment]
Tested and can confirm its fixed on the latest core/db.
