### ISSUE TITLE
Another ./InstallFullDB.sh Question

### ISSUE THREAD

**Issue by touchitcrusade** [cmangos/issues#1609]
Hello again, All,

Thanks so much for answering my last question.  You helped me move along to the next step. For the life of me, I cannot figure out why the following is happening now.  I have MySQL Server 8.0 and I am on Windows 10.

I am on the step, Git Bash Here and I type ./InstallFullDB.sh

It starts the process appropriately.

It appends all the updates until...

**Current behavior**: 
Appending Updates/797_q9720.sql
    Appending Updates/798_Zangarmarsh_PvP_Beam.sql
    Appending Updates/799_c.20109.sql
    Appending Updates/800_c19945_aura.sql
    Appending Updates/801_c_20210_20606_aura.sql
    Appending Updates/802_c20619_aura.sql
Appending Updates/803_c21267.sql
    Appending Updates/805_transpolyporter.sql
    Appending Updates/806_misc_fixes.sql
ERROR 1064 (42000) at line 396: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank, req_spell) VALUES

(38215,     0, 38215, 1, 0),
(38216, 38215, 38215, 2 ,0' at line 1
ERROR: cannot apply Updates/806_misc_fixes.sql

**Operating system**: 
Windows 10

Can anyone please help with this?  You guys were total life savers last time.  Thanks again, I really appreciate any assistance.

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by natiewow** [comment]
Could be related to MySQL 8, I guess? I get no syntax errors on 5.7.

**Comment by touchitcrusade** [comment]
Thanks.  I will reattempt with 5.7.  I will follow up and see if this was the cause.  Thank you!

**Comment by touchitcrusade** [comment]
I attempted with 5.7.  I did get further.  I was able to get to nearly the end of the walk through.  Now, however, I encounter this.


Appending Updates/966_black_morass_templates.sql
    Appending Updates/967_old_hillsbrad_teleport.sql
    Appending Updates/968_putrid_mushrooms.sql
    Appending Updates/972_CDB-1962_cenarion_beacon.sql
    Appending Updates/995_taxi_shortcuts_alliance_easternkingdoms_capitals.sql
ERROR 1146 (42S02) at line 1: Table 'mangos.taxi_shortcuts' doesn't exist
ERROR: cannot apply Updates/995_taxi_shortcuts_alliance_easternkingdoms_capitals.sql


This is after I did a complete wipe and a total restart from scratch.  I wanted to make sure I had a clean start from the get go with MySQL 5.7 Server.

I even went to the fetch updates area of the tutorial and followed those steps, then did ./InstallFullDB.sh

**Comment by cala** [comment]
This error is unrelated to your MySQL installation which seems to work fine now.

The error is due to SQL data being inserted before the required table is created. Once the DB devs of the repository have applied the required SQL update from CMaNGOS core, this error should disappear.

**Comment by natiewow** [comment]
The taxi_shortcuts table is being created by sql/base/mangos.sql during initial db creation (as seen [here](https://github.com/cmangos/mangos-tbc/commit/238ea76fbcd5d8d340bc06637550130756e17f3e#diff-19d5e01df7226bec976ff28e83a4bbefR16576)). I'm not sure why this error would appear if you started the whole process from scratch. It looks to me like you're using new base with older db...

If you drop your whole db and recreate it according to your guide (creation and initialisation) this error should not appear again.
