### ISSUE TITLE
[CLASSIC] Can Collect From gameobject Despite Having Collected All Quest Items

### ISSUE THREAD

**Issue by Muehe** [cmangos/issues#1610]
**Current behavior**: 
Being on a quest which requires the player to collect items from a gameobject, the player can still "loot" these objects, despite having collected all required items. No more items are added to the players inventory and the gameobject despawns.

When the gameobjects have been fake-looted and respawned, they can not be interacted with again. But all objects present when the quest requirement was finished can still be interacted with.

When the player relogs, he can not interact with any of the objects anymore.

**Expected behavior**: 
Once the player has finished collecting the quest items, he should no longer be able to interact with the gameobjects from which they can be looted.

**Steps to reproduce**:

1. Create Night Elf char
2. `.quest add 3521`
3. Collect "Moonpetal Lily"s on the ponds northwest of the big tree.

**Client version**: 
1.12.1
**Commit hash**: 
f51374e7368a270bfe2e8b9ab47d49403072af20
**Database version**: 
b9d6b66b1501410b1c4f046aee53008a5a6ed619
**Operating system**: 
Ubuntu 18.04

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Resolved some time ago. Remember to do .gm off
