### ISSUE TITLE
Setting PlayerbotAI.BotguyCost to a High Value Causes mangosd To Crash

### ISSUE THREAD

**Issue by jimmybrancaccio** [cmangos/issues#1611]
**Current behavior**: 

Setting the `PlayerbotAI.BotguyCost` configuration value in the playerbot.conf file to something quite high, ex., 99999999999, will cause mangosd to crash when speaking with an NPC.

**Expected behavior**: 

I would expect with this value set, it will just ignore it and use the highest maximum value, or prevent mangosd from starting.

**Steps to reproduce**:

1. Build latest core and include PlayerBot functionality, I tested on WotLK.
2. Edit the playerbot.conf file and set the PlayerbotAI.BotguyCost to 99999999999.
3. Open your client and login to the server. You may need to create a couple characters here, I already had a few on my server. I say this because I believe you'll need to have at least one other character created besides the one you're going to log into the world with so that the bot summon menu knows to generate in the UI.
4. Login with one of your characters to the world, and locate an NPC - someone who gives a quest is ideal. Speak with this NPC and you should experience the crash.

You can also refer to this video (which should be available for 30 days from today):

https://www.twitch.tv/videos/262257474

It appears when setting this value to an "out of bounds" value, it causes mangosd to crash.

**Client version**:

3.3.5a

**Commit hash**: 

b2d3ca56385049eb0b6ea07c68a1506774c1d12b

**Database version**: 

Not sure of the version, but the commit hash is (from wotlk-db)

41731bb4be7bb27a7ecbf8ba015a14f8a6b51e22

**Operating system**: 

Ubuntu 14.04

**Recommended Solution**:

Either we ignore any value that is higher then deemed acceptable/valid and change it to something that is valid on runtime, or mangosd should fail to start if the provided value is non-valid.

Regardless of what solution is done, we should update the notes around the PlayerbotAI.BotguyCost option in playerbot.conf to state what is being done.

**Comment by cala** [comment]
Hi,

I'll have a look at this, but tell me why on Earth, you need to set such an insane amount ?  I'm pretty sure that players cannot get that much money.

**Comment by jimmybrancaccio** [comment]
@cala That's the million dollar question 😝 It was my hacky attempt in getting the bot menu to not show up on NPCs. In Discord, I was advised using "-1" for the `PlayerbotAI.BotguyQuests` would be better. This may be another GitHub issue in itself where we propose an actual option to enable or disable the bot menu (0 - disabled, 1 - enabled).

We also discussed that we believed the limit on money was 2 billion.

**Comment by Lillecarl** [comment]
If you go close to 2147483648 copper you might have issues, that's where the int32 overflows and becomes a negative number close to -2147483648, and having negative amounts of money isn't very great.

It would be great getting a crashdump from the crash.

**Comment by cala** [comment]
Well, I think that requesting a way to disable the Bot Guy feature is better than using edge effect such as crazy amount of money. I'll have a look at that but don't expect high priority on that topic though. :wink: 

Thanks @Lillecarl for the explanation.

**Comment by Lillecarl** [comment]
@cala Considering money is an int32 i'd say make the configuration entry an int32 too, if it's < 0 then disable botguy.

Whoever botguy is 🤣

**Comment by cala** [comment]
Option for disabling botguy was added in https://github.com/cmangos/mangos-classic/commit/8c5be3b665b6a3f133261d2e675f19a47330c5dc

It does not fix the core crash as the same issue will occur every time someone overflows a integer config variable (the crash occurs when parsing config variables). But at some point, server admins should be careful about what they do.

**Comment by jimmybrancaccio** [comment]
> It does not fix the core crash as the same issue will occur every time someone overflows a integer config variable (the crash occurs when parsing config variables). But at some point, server admins should be careful about what they do.

I totally agree, and having the upper limit there now in the conf gives the server admin no reason to not read and follow that as a guide. Thanks @cala 👍
