### ISSUE TITLE
Not really an issue to report, just a question.

### ISSUE THREAD

**Issue by DonCDXX** [cmangos/issues#1612]
Sorry if this is the wrong place to post this question. Please point me to a better place if there is one. I figured this is the place to ask since people who know how to take the game apart are likely to come here.

Is it possible (and if so, how) to extract the heightmaps from WotLK? I've been hoping to take the very comfortably familiar world of pre-catacylsm WoW and use it in games.

**Comment by katz1** [comment]
I am not the best guy to answer this, but you should be able to do that with some investigation. The VMapExtractor program (contrib\vmap_extractor) is already parsing the MPQ files of the client to get 3D world information and build vmaps from them for visibility checks.
