### ISSUE TITLE
[TBC][WOTLK] My What Big Feet You Have - Wolf Pup Leaves BIG Footprints

### ISSUE THREAD

**Issue by alanman** [cmangos/issues#1615]
**Current behavior**: 
Wolf pup in Freewind Post in Thousand Needles leaves MASSIVE footprints.
![wowscrnshot_051318_161302](https://user-images.githubusercontent.com/4338585/40283213-d7826c2a-5c37-11e8-9192-843f4b1430c7.jpg)

**Expected behavior**: 
Should be much smaller.

**Steps to reproduce**:

1. Visit Freewind Post. (This may happen other places as well where animals leave footprints.)
2. Watch the wolf walk around.
3. 

**Client version**: 
2.4.3
**Commit hash**: 

**Database version**: 
TBC-DB 1.5.0, updated to u960
Mangos - required_s2369_01_mangos_spell_affect

**Operating system**: 
windows 7

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by BillytheOrc** [comment]
This looks like a client-side issue to me, not serverside. I could be wrong?

**Comment by EGSilver** [comment]
I'm having the same issue.

**Comment by berserkingyadis** [comment]
Still happening.

![screenshot_4](https://user-images.githubusercontent.com/9959527/49333535-e471f680-f5c0-11e8-8ea8-a4973bbc8d4f.png)

core commit: 28bb409e106bedba124d6f87dbfacb68abfee406
tbc-db commit: f686443ee9f8404b8479ceefee2224ddf471a820 
OS: win 10

**Comment by killerwife** [comment]
To be honest, this does seem like a clientside issue.

**Comment by AnonXS** [comment]
client issue due to model rescaling in tbc+.
