### ISSUE TITLE
[WOTLK] Scarlet Ghouls Do Not Follow Player, Quest 12698 "The Gift That Keeps On Giving"

### ISSUE THREAD

**Issue by Vladskywolf** [cmangos/issues#1616]
**Current behavior**: 
This quest (12698) requires you to use device 'Gift of the Harvester' (item: 39253) to spread plague amongst the Scarlet Miners (creature: 28819, 28822, 28841, 28891) until they turn into Scarlet Ghouls (creature: 28845, 28897) which will then follow you back to the quest giver for, um, processing. :)

What is happening is that if the Scarlet Ghoul is immediately aggro'd and starts to fight, it will no longer follow you after the fight is concluded. Unfortunately given the confines of the mine this is likely to happen quite often.

On one occasion I successfully brought a Scarlet Ghoul out without aggro'ing anything.

On another occasion as I was leaving the mine with a Scarlet Ghoul in tow, having not previously aggro'd anything, a Scarlet Miner spawned which we then had to fight. Afterwards the Ghoul continued to follow me, as it should.

I'm uncertain if there is a 'timing' issue, such that if it follows you unhindered for a certain length of time it will continue to follow after any subsequent fights. Numerous attempts to bring back Ghouls were failures since they almost immediately aggro'd other miners or defended me and subsequently did not follow me out.

**Expected behavior**: 
Scarlet Ghouls should continue to follow the player after any battles regardless of when they are aggro'd.

**Commit hash**: 
9b98854f15751d08aa65d32b96abf92eb8a683f1
(build 13973)

**Database version**: 
WoTLKDB v1.1 'The Warsong' for CMaNGOS-WOTLK 13965
ACID 3.3.5a (Wrath of the Lich King) for CMaNGOS-WOTLK (3.3.5a Client)
hash: a9fedfaf62188a86f904b16389df284b82d60afd

**Other notes**: 
Multiple id's showed up when I queried the database for the creature ids of the Miners and Ghouls so I listed them all above, being uncertain which one(s) are actually relevant to this quest.

Other players have reported the same issue which is what prompted me to test for this particular bug, though being grouped they were more easily able to complete this quest.

The last build I tested (13956) did not exhibit this particular problem.
hash: 809fa326c3d74ccceab622842a8604bf3cf86b86

This quest is part of the Death Knight starting area, The Scarlet Enclave.

**Comment by Grz3s** [comment]
this all been fixed some time ago
retested 15/12/20 - works correct
