### ISSUE TITLE
[TBC] Black Temple Illidan (Akama)

### ISSUE THREAD

**Issue by dunjeon** [cmangos/issues#1617]
**Current behavior**: 
After the intro dialogue between Illidan and Akama, Akama disappears and Illidan freezes in place.

**Expected behavior**: 
Illidan and Akama should fight each other. (Akama should not disappear).  the players should be able to fight Illidan.

Note: The encounter seems to work in the cManogs-wotlk build.

**Steps to reproduce**:
1. Navigate to Illidan's room in the Black Temple Raid  
2. Click on Akama's dialogue to start the Illidan  encounter   
3.  After Illidan   says "You are not prepared!" Akama will disappear and Illidan will freeze in place.  

**Client version**: 
2.4.3

*Commit hash**: 

**Database version**: 
Snapshot v1.6.2037

**Operating system**: 
Windows 10 and Linux tested

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by forever2019** [comment]
Request priority repair.
Thank you!

**Comment by AnonXS** [comment]
1. Kill Council with .damage command
2. Speak to Akama who enters the room
3. Do RP Walk with Akama
![grafik](https://user-images.githubusercontent.com/19734826/145727056-c017cc74-202a-4f4d-a387-0a1ea138c075.png)
4. Speak with Akama at Illidan Staircase
![grafik](https://user-images.githubusercontent.com/19734826/145727090-3a99f31c-e0a6-4941-af45-8667516a2d56.png)
5. Enjoy RP
![grafik](https://user-images.githubusercontent.com/19734826/145727110-7e26abb5-cde5-4c3d-af4d-6b0ed62f8899.png)
6. Defeat Illidan
