### ISSUE TITLE
[Classic]

### ISSUE THREAD

**Issue by 127y** [cmangos/issues#1618]
**Current behavior**: The Mage will use the flash method in the Undercity to enter the void and then die

**Expected behavior**: Flash can be used normally

**Steps to reproduce**:

1. 
![tim 20180527213603](https://user-images.githubusercontent.com/36727009/40586556-2a42ac5e-61f6-11e8-9733-2adf76a97c29.png)

2. 

![3333](https://user-images.githubusercontent.com/36727009/40586583-aae29ca2-61f6-11e8-9a24-7bbdee2de581.png)

3. 
![444](https://user-images.githubusercontent.com/36727009/40586584-b4c27990-61f6-11e8-9d17-ed47ae813e50.png)

**Client version**: [Classic]1.12.1-1.12.3

**Commit hash**: 1d662e3879caee889f63c87169b28959b8eb44e3

Database version: "required_z2716_01_realmd_totp"
Database version: "required_z2719_01_characters_taxi_system_update"
Database version: "required_z2719_01_mangos_taxi_system_update"

Operating system:win2008/win2012/win10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
Thank you for this documented report. This is a duplicate issue of https://github.com/cmangos/issues/issues/1520
