### ISSUE TITLE
[Classic]Hunter Warlock pet some BUG

### ISSUE THREAD

**Issue by 127y** [cmangos/issues#1620]
**Current behavior**: Hunter Warlock pet base property error 

**Expected behavior**: Hope to repair

**Steps to reproduce**:

1. Hunter pet base property error 
![tim 20180608104526](https://user-images.githubusercontent.com/36727009/41136596-8e27213e-6b09-11e8-93cf-d4ee84aba0c6.png)

2. Hunter Pet attack Owner does not enter the battle
![40543099-8118ae2c-6055-11e8-8aea-3a2cb26bb76e](https://user-images.githubusercontent.com/36727009/41136625-b2aec5e8-6b09-11e8-9fe3-4e7ef8d7dc17.png)

3. Pets kill monsters will not return to their owners
![tim 20180608105405](https://user-images.githubusercontent.com/36727009/41136805-80be54ee-6b0a-11e8-95b7-829e02f69ce2.png)
4. Warlock Pet BUG
![tim 20180608141130](https://user-images.githubusercontent.com/36727009/41141976-aa4eed84-6b26-11e8-950c-efef8232646c.png)
![tim 20180608141210](https://user-images.githubusercontent.com/36727009/41141980-b09e3546-6b26-11e8-8bb3-908e9e4161f9.png)
![tim 20180608141258](https://user-images.githubusercontent.com/36727009/41141983-b4d644dc-6b26-11e8-856b-339f16885f15.png)
![tim 20180608141351](https://user-images.githubusercontent.com/36727009/41141988-b81a3496-6b26-11e8-9d41-57acdbf28cfb.png)
![tim 20180608141517](https://user-images.githubusercontent.com/36727009/41141994-ba8320e4-6b26-11e8-9744-af5d76eceafb.png)

**Client version**: 1.12.x

**Commit hash**: 750eabe0227ced7fc8b5d9a77737042bf64d47cc

**Database version**: Using World DB: Classic DB version 1.9 "The Black Dragonflight". For core Classic z2717.
Using creature EventAI: ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

**Operating system**: win10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by timspiering** [comment]
I've debugged InitStatsForLevel and it returns the correct data from the database so it seems to be a visual error.

**Comment by Xinito** [comment]
I've debugged InitStatsForLevel and it returns the correct data from the database so it seems to be a visual error.

**Comment by ientium** [comment]
this Bug，Mee to 

for CMaNGOS-TBC (2.4.3 Client)

Operating system: win10
Hope to repair
thanks

**Comment by ientium** [comment]
this Bug，Me too

for CMaNGOS-TBC (2.4.3 Client)

Operating system: win10
Hope to repair
thanks

**Comment by SilvioDoMine** [comment]
I may have a bug to add on the pets too:

At least on CMaNGOS-TBC, when you train pet spells, doesn't spend Training Points, and you can train all spells with your pet.

@Warlockbugs

**Comment by Warlockbugs** [comment]
The issue is fixed.

@SilvioDoMine 
Please report anything that is different from the head post in separate issues for easier tracking/assignment.

**Comment by ientium** [comment]
@Warlockbugs this Hunter Warlock pet base property error isnot  fixed？

**Comment by AnonXS** [comment]
Seperate Issues into their own posts.
