### ISSUE TITLE
[CLASSIC] Investigate the Blue Recluse

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#1621]
The mobs needed to capture _(Rift Spawn 6492)_ does not spawn in quest _Investigate the Blue Recluse_ (1920).
You can use the _Cantation of Manifestation_ (7308) item in the Blue Recluse inn, but doing so does not 'reveal' any mobs you are supposed to capture.

https://vanilla-twinhead.twinstar.cz/?quest=1920

**Comment by RazzorX** [comment]
Same problems with "Investigate the Alchemist Shop" (id=1960) Horde-Quest

**Comment by cala** [comment]
Both quests are basically the same. You can complete the Horde one in Stormwind and the Alliance one in Undercity. So no surprise they share the same issue.

There is [an issue](https://github.com/classicdb/database/issues/695) about this opened in the old Classic DB repository and I had all the scripts required for a long time. The only reason I'm not pushing them is an issue in core related to the way invisibility is applied/removed: the spells used here do not seem to work properly. As the whole invisibility mechanics was changed from Classic to TBC, I need to take some time to investigate this a bit more.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/a4b14eca185a0817282a361cf2d77378a9d0a550

**Comment by aleigood** [comment]
Same problem in TBC and not fix yet.

**Comment by AnonXS** [comment]
This originated from tbcmangos, so if it is not fixed it has nothing to do with this commit as it came from tbcmangos, or was ported to tbcmangos.

if there is a new regression with this quest, please open a new issue instead of digging up old stuff.

https://github.com/cmangos/tbc-db/commit/f9f58a306192705f52839c068347f5e01559efcf
