### ISSUE TITLE
[Classic] Hunter pet problem

### ISSUE THREAD

**Issue by 127y** [cmangos/issues#1623]
**Current behavior**: There are still some problems with hunters' pets. When a pet goes to Daguai, it will run around.

**Expected behavior**: Hope to repair

**Steps to reproduce**:

1. There are still some problems with hunters' pets. When a pet goes to Daguai, it will run around.
2. Whether it can be added, LootsLogFile, LevelupLogFile, LogMoneyTrades, ChatLogFile

**Client version**: 1.12

**Commit hash**: fddb1b5a1e19897bea4fe2af596ba29515aed3cb

**Database version**: required_z2722_01_mangos_creature_waypoint_refurbishing

**Operating system**: win2012 - win10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
It should be fixed by https://github.com/cmangos/mangos-classic/commit/fddb1b5a1e19897bea4fe2af596ba29515aed3cb
Can you confirm?
