### ISSUE TITLE
[Classic] Error in spell_template table, probably sql file format was updated (there should be 147 fields in sql).

### ISSUE THREAD

**Issue by linuxpng** [cmangos/issues#1627]
**Current behavior**: 
After updating I am unable to start the mangos server after updating:

Loading spell_template...
Error in spell_template table, probably sql file format was updated (there should be 147 fields in sql).

**Expected behavior**: 
Mangosd starts

**Steps to reproduce**:

1. Updated mangos server and classic db

**Client version**: 
1.12.1

**Commit hash**: 
commit b400348f639dee177b4753228a821af47974dc0e

**Database version**: 
v.1.9.0

**Operating system**: 
ubuntu 16.04 lts

I did try dropping and recreating the mangos db, error persists.

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-classic/commit/fddb1b5a1e19897bea4fe2af596ba29515aed3cb

It was fixed here. Also need to update DB correctly using script and CORE_DIR value.

**Comment by linuxpng** [comment]
So defining "CORE_PATH" resolved the issue.  Thank you.  Two points:
1) I always use the script to update the db, because I don't know what I am doing in general.
2) Per the script:
"## Define the path to your core's folder (This is optional) <------
##   If set the core updates located under sql/updates from this mangos-directory will be added automatically"

The config file and installation instructions should probably be corrected.  I have not had to add the path in this file ever before.

**Comment by AnonXS** [comment]
The Wiki is freely editable.

**Comment by ezzo300** [comment]
2019-02-20 21:52:59 Loading spell_template...
2019-02-20 21:53:00 ERROR:Error in spell_template table, probably sql file format was updated (there should be 180 fields in sql).
 i have this problem can anyone help me and  tell me how to resolve it ?
using windownsx10
