### ISSUE TITLE
[CLASSIC][TBC] Scroll of Spirit Issue

### ISSUE THREAD

**Issue by 127y** [cmangos/issues#1630]
**Current behavior**: Scroll of Spirit BUG

**Expected behavior**: Hope to repair

**Steps to reproduce**:

1. Scroll of Spirit    Scroll of Spirit II   Scroll of Spirit III   Scroll of Spirit IV
Scroll of Stamina   Scroll of Stamina II  Scroll of Stamina III  Scroll of Stamina IV
Scroll of Strength  Scroll of Strength II  Scroll of Strength III  Scroll of Strength IV
Scroll of Intellect   Scroll of Intellect II  Scroll of Intellect III  Scroll of Intellect IV
Scroll of Agility     Scroll of Agility II   Scroll of Agility III  Scroll of Agility IV
2. 4 kinds of reel BUFF can exist at the same time
3. 
![111](https://user-images.githubusercontent.com/36727009/41808953-229ae908-7718-11e8-8091-0d56aadc3efc.png)
![33333](https://user-images.githubusercontent.com/36727009/41809068-df1980ca-7719-11e8-9b03-8dff59a54326.png)

**Client version**: 1.12 - 2.4.3

**Commit hash**: feb871923e618584a7db68ec38f57dd93c41f9e8

**Database version**: required_z2722_01_mangos_creature_waypoint_refurbishing

**Operating system**: win2008 - win10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
https://github.com/cmangos/issues/wiki/spell_chain

**Comment by 127y** [comment]
@AnonXS 
This method can be solved, but using the lower scrolls will cover the advanced effects.

**Comment by AnonXS** [comment]
You mean lower buffs will overwrite higher buffs?

**Comment by 127y** [comment]
@AnonXS
yes  lower buffs will overwrite higher buffs

**Comment by berserkingyadis** [comment]
Still happening.

core commit: 28bb409e106bedba124d6f87dbfacb68abfee406
tbc-db commit: f686443ee9f8404b8479ceefee2224ddf471a820
OS: win 10

**Comment by Warlockbugs** [comment]
Should be fixed in https://github.com/cmangos/mangos-tbc/commit/7b39a9c92279a91f3746b11f7ee98bb4ffa55d26.
