### ISSUE TITLE
query ERROR: Table 'mangos.faction_store' doesn't exist

### ISSUE THREAD

**Issue by EGSilver** [cmangos/issues#1633]
@killerwife when using the last repack i'm getting these errors when booting the server.
when i compile myself i am able to run. what am i missing here?

2018-06-25 22:42:36 
2018-06-25 22:42:36 Loading faction_store...
2018-06-25 22:42:36 ERROR:SQL: SELECT MAX(entry) FROM faction_store
2018-06-25 22:42:36 ERROR:query ERROR: Table 'mangos.faction_store' doesn't exist
2018-06-25 22:42:36 ERROR:Error loading faction_store table (not exist?)

**Comment by killerwife** [comment]
Rebuild DB. It gets auto added when a script is rerun.

**Comment by killerwife** [comment]
Also fyi, the table is in cmangos\mangos-tbc\sql\base\dbc\original_data FactionStore.sql

**Comment by EGSilver** [comment]
Cannot even find the sql file in that folder, might be blind but its not there.

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/tree/master/sql/base/dbc/original_data
It is there even in the repository.

**Comment by EGSilver** [comment]
Yeah, just figured that out as well, was looking on my desktop, sorry. it's quite early.

**Comment by EGSilver** [comment]
@killerwife have you try'd entering Karazhan with this repack, every other raid seems to work. but when i enter Karazhan the character seems to get stuck in limbo. are you having these issue's?
