### ISSUE TITLE
World PvP broken

### ISSUE THREAD

**Issue by EGSilver** [cmangos/issues#1634]
**Current behavior**: 
World PvP not working, cannot capture towers in Outland, havent try'd vanilla content.
Sliders not showing.
**Expected behavior**:
Sliders should be shown and player should be able to capture these towers.

**Steps to reproduce**:

1. Hellfire / Zangarmarsh
2. Try to capture a tower

2.4.3
Master 
Latest DB
W10

**Comment by killerwife** [comment]
Try the following:
.gm off
.gm fly off
.gm visible on

If those are set the other way, world pvp does not work.

**Comment by EGSilver** [comment]
Exactly, thanks! i noticed normal dungeon bosses do not drop blue loot either, is there a forum around for this stuff @killerwife ? the Cmangos website seems to be offline.
I could use some guidelines.

**Comment by killerwife** [comment]
No, sadly the website is offline, and there are no plans for reinstating it. There is a discord you can join.
