### ISSUE TITLE
[WOTLK] Some Mounts No Longer Summoned.

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#1635]
These are the ones I found so far.... :)

Invincibles Reins
Item 50818

Blazing Hippogryph
Item 54069

Magic Broom
Item 37011

**Current behavior**: 
Click to mount, Cast spell, But no mount summoned.

**Expected behavior**: 
Click to mount, Cast spell, & summon mount

**Steps to reproduce**:
1. Get item
2. Click it 

**Client version**: 
3.3.5

**Commit hash**: 
12d9f57251979e38e6e4651b270098cab20a8d6b
I Think it was working before commit "New taxi system: fix mount appearance precedence."

**Database version**: 
PSDB

**Operating system**: 
Mac OS X

**Comment by Rog360** [comment]
This issue seems to be fixed with this db revert... :)[https://github.com/cmangos/wotlk-db/commit/9b58af8af65a059beaaf47102013f4f6cd6b2225](url)

**Comment by AnonXS** [comment]
Info on why reopen

**Comment by Tobschinski** [comment]
no, you will never know why we do this

**Comment by Rog360** [comment]
I closed the issue because I thought it was fixed with a db commit. Then found the db commit only fixed some of them. So, reopened and edited my last post... :)

**Comment by Rog360** [comment]
Ok, Seems some more may have been fixed after https://github.com/cmangos/mangos-wotlk/commit/02b6f3cc731471512cd48f91f395304c69818313

I'll post back after I check a few more.... :)
