### ISSUE TITLE
[TBC] ad map extractor cannot open MPQ

### ISSUE THREAD

**Issue by TheGhostGroup** [cmangos/issues#1636]
**Current behavior**: 
when map extractor ad run from debian 9 it cannot open common.MPQ stating it cant find it even though its in the directory "Data" 

**Expected behavior**: 
No all maps extracted so world server does not launch.

**Steps to reproduce**:

1. run ad from game directory from debian 9 server wait till finished and scroll up
2. Error opening archive './Data/common.MPQ': Does file really exist?
3. 

**Client version**: 
2.4.3 8606
**Commit hash**: 
ff38fa684dc8630851281608030a74448dc99c95
**Database version**: 

**Operating system**: 
Debian 9

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by jimmybrancaccio** [comment]
Hello, thank you for taking time to submit your issue. We do not presently provide support for setting up CMaNGOS in GitHub. Please connect with us on Discord if you're still having any issues. We'd be happy to lend a hand. Thanks!
