### ISSUE TITLE
Empty Realm list - But with strange behavior...

### ISSUE THREAD

**Issue by Albanosdes** [cmangos/issues#1639]
**Client version**: Vanilla
**Operating system**: Debian 9.4 64bits

Hello there, I'm trying to setup my vanilla server, and i'm encountering an issue.
First of all, I had setup a server some months ago, and it did works, even If I've been on an issue for a while ([https://github.com/cmangos/issues/issues/1527#issuecomment-355622912]), we were 2 playing on it for the testing phase.

Now I made a new and clean server, and in order to not lose accounts/characters, I did a backup of the realmd and characters databases from the older server, and then I restored theses on the new server. And it was great, my friend and I got back our accounts and our characters.

But then comes the issue. And it is a weird one as I don't understand anything happening.
I created a new account, but when trying to log in my realm list was empty.
I created another test account, and then I managed to get directly to the character menu.
If I try to go back on the new account (not the test one), I also can reach the character menu directly (without passing by the realm list).
So I though "weird... but seems ok", so I removed the test account, trying to relog with the new one, and the empty realm list again.
I tried this on the same computer that I play on my account (which is working).

I asked to a friend of mine to try the new account but he gets stuck at the empty realm list menu.
I recreated the test account and asked him to log in, he log in, and when selecting the language and the server type, he cannot see the validate button.

And I honestly don't know what to do, and as a Linux Administrator it's frustrating !!!  I dont see anything in the logs either.
I'm thinking about trying it again this evening on another computer, but I would welcome any help.

Thanks for reading.

REALMD.conf 
[RealmdConf]
ConfVersion=2010062001
LoginDatabaseInfo = "127.0.0.1;3306;mangos;mangos;realmd"
LogsDir = "/var/log/mangos-wow/"
MaxPingTime = 30
RealmServerPort = 3724
BindIP = "0.0.0.0"
PidFile = ""
LogLevel = 0
LogTime = 0
LogFile = "/var/log/mangos-wow/Realmd.log"
LogTimestamp = 0
LogFileLevel = 0
LogColors = ""
UseProcessors = 0
ProcessPriority = 1
WaitAtStartupError = 0
RealmsStateUpdateDelay = 20
WrongPass.MaxCount = 0
WrongPass.BanTime = 600
WrongPass.BanType = 0

MANGOSD.conf :
RealmID = 1
DataDir = "/home/mangos/data/etc"
LogsDir = "/var/log/mangos-wow/"
LoginDatabaseInfo     = "127.0.0.1;3306;mangos;mangos;realmd"
WorldDatabaseInfo     = "127.0.0.1;3306;mangos;mangos;mangos"
CharacterDatabaseInfo = "127.0.0.1;3306;mangos;mangos;characters"
LoginDatabaseConnections = 1
WorldDatabaseConnections = 1
CharacterDatabaseConnections = 1
MaxPingTime = 30
WorldServerPort = 8085
BindIP = "0.0.0.0"

realmlist :
MariaDB [realmd]> select * from realmlist \G;
*************************** 1. row ***************************
                  id: 1
                name: Imperium
             address: wow.imperium-gaming.fr
                port: 8085
                icon: 1
          realmflags: 64
            timezone: 10
allowedSecurityLevel: 0
          population: 0.02
         realmbuilds: 5875 6005 6141 

MariaDB [realmd]> select * from account \G;
*************************** 5. row ***************************
             id: 5
       username: MyAccount
        gmlevel: 3
          email: NULL
        last_ip: my-ip
  failed_logins: 0
         locked: 0
active_realm_id: 0
      expansion: 0
       mutetime: 0
         locale: 2
          token: NULL
*************************** 6. row ***************************
             id: 6
       username: MyFriendWorkingAccount
        gmlevel: 3
          email: NULL
        last_ip: myfriendip
  failed_logins: 0
         locked: 0
active_realm_id: 0
      expansion: 0
       mutetime: 0
         locale: 2
          token: NULL
*************************** 7. row ***************************
             id: 21
       username: MyFriendNotWorkingAccount
          email: NULL
        last_ip: myfriendnotworkingip
  failed_logins: 0
         locked: 0
active_realm_id: 0
      expansion: 0
       mutetime: 0
         locale: 2
          token: NULL
*************************** 9. row ***************************
             id: 20
       username: TEST
         email: NULL
        last_ip: myfriendnotworkingip
  failed_logins: 0
         locked: 0
active_realm_id: 0
      expansion: 0
       mutetime: 0
         locale: 2
          token: NULL

*** EDIT ***
Well after some tries with my own account, I don't see any realm either. I'm forwarded directly to the realm because I have already characters on it.
But idk why my realm is not showing.

**Comment by Albanosdes** [comment]
Well I finally managed to find my problem. I'm in France, so I used the timezone code "10" (french) in the mangosd.conf and in the realmlist table in realmd dbb.
But, and I don't know why because I'm pretty sure my client is in French, the server doesn't seems to recognize my client as a French one.
So I updated mangosd.conf and realmlist to use timezone code "2" (US), and it worked...

I'm pretty sure there is a bug somewhere because after that, when I connect, I get asked the desired language and the realm style. But in the languages, the only proposal I got is "deutsch".

**Comment by evil-at-wow** [comment]
I don't know if that's a failsafe check, but check what folders you have in the 'Data' folder of your WoW installation. I have, apart from some MPQ files, a folder with 'enUS' in there (but it's a TBC client).

**Comment by jimmybrancaccio** [comment]
Hello, thank you for taking time to submit your issue. We do not presently provide support for setting up CMaNGOS in GitHub. Please connect with us on Discord if you're still having any issues. We'd be happy to lend a hand. Thanks!

**Comment by lenaing** [comment]
Hello there,

Just wanted to chime in, in case anyone get to this "issue".

I was trying to understand what was going on with another MaNGOS project. But the server is not the issue here.

It seems that the french client, or at least version `1.12.1.5875`, is actually reporting the client locale as `frFR` -> `2` to the server.

Here is an excerpt of my _realmd.log_ :

```
2025-12-19 22:32:21 [AuthChallenge] Account 'LENAIN' using IP 'A.B.C.D' is using 'frFR' locale (2)
```

The hint was provided by the `C:\Program Files (x86)\World of Warcraft\Documentation\ReadMe.html` file with the following quote (in french) :

> La première fois que vous vous connectez avec un nouveau compte, vous accédez à l'écran de sélection du royaume, où deux questions vous sont posées :
> 1. Votre zone de prédilection : si vous habitez aux USA, des tranches horaires sont proposées. En Europe, des pays sont proposés. 

I suppose that, in 2006, the client did not send the same locales ID than now and the french one was `2`, while US was `1`.

If you ever need to reset the last realm used on a client, just remove the `SET realmName "TheRealmName"` from the client `<Installation Path>/WTF/Config.wtf` file.

Hope this will prevent headaches from fellow WoW users ;)
