### ISSUE TITLE
[Classic] warlock BUG

### ISSUE THREAD

**Issue by 127y** [cmangos/issues#1641]
**Current behavior**: warlock BUG

**Expected behavior**: 

**Steps to reproduce**:

1. 
![-4](https://user-images.githubusercontent.com/36727009/42308119-39259486-8067-11e8-8540-9035f7a32d87.png)

2. 
3. 

**Client version**: 1.12

**Commit hash**: a01120d2415d3fc45ea0c306597f1b7f41fab010

**Database version**: 
Using World DB: Classic DB version 1.9 "The Black Dragonflight". For core Classic z2717.
Using creature EventAI: ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

**Operating system**: win10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by jimmybrancaccio** [comment]
Hello, thank you for taking the time to submit this bug. Unfortunately without clear steps for replication and what the exact issue is it will be too difficult to resolve this issue. Please re-submit your case with detailed information so the development team may further look into the issue. Each unique issue should have its own case in GitHub. Thank you.
