### ISSUE TITLE
[CLASSIC] Issues with Mage Spells

### ISSUE THREAD

**Issue by 127y** [cmangos/issues#1642]
**Current behavior**: mage BUG

**Expected behavior**: 

**Steps to reproduce**:Release to you rself

1. 
![tim 20180705173311](https://user-images.githubusercontent.com/36727009/42315380-e1f247b4-8079-11e8-95a9-289344328133.png)

2. 
3. 

**Client version**: 1.12

**Commit hash**:  a01120d2415d3fc45ea0c306597f1b7f41fab010

**Database version**: 
Using World DB: Classic DB version 1.9 "The Black Dragonflight". For core Classic z2717.
Using creature EventAI: ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

**Operating system**: win10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
Please. Make a proper description of the issue and how to reproduce it.
I'm sorry to be blunt but almost all of your reports are hardly understandable, hence the related issues will probably never be investigated.

**Comment by AnonXS** [comment]
Mage is not rooted by Frostbite Talent anymore
