### ISSUE TITLE
[TBC] Hunter Pet Issues (Training Points & Scale)

### ISSUE THREAD

**Issue by EGSilver** [cmangos/issues#1644]
Hunter pet training points do not go down when learning a new 'talent'.
also Pet scale's are incorrect

**Expected behavior**: 
Training points should be consumed when choosing a skill.
Pets should be bigger.

**Steps to reproduce**:

Create a hunter. 

**Client version**: 
2.4.3 TBC

**Database version**: 
Latest.

**Comment by killerwife** [comment]
Pets are bigger when they level up. And training points work now afaik.
