### ISSUE TITLE
[TBC] Life Tap Displays Miss on Player Frame

### ISSUE THREAD

**Issue by EGSilver** [cmangos/issues#1646]
**Current behavior**: 
When a warlock uses life tap a miss displays on the player frame.

**Expected behavior**: 
The spell works as it should but should not show a miss on the player frame.

**Steps to reproduce**:

1. Create Warlock
2. Use Lifetap
3. Miss

**Client version**: 
2.4.3

**Commit hash**: 

**Database version**: 
Latest. Rise of the phoenix

**Operating system**: 
W10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by zaphstar** [comment]
This is still an issue and I have replicated it, I think I know of the issue:

It casts life tap twice on each use of the spell.

The first one is cast at nobody
Second one is cast at yourself

The first spell of course is missing and causing this issue.
The spell should only cast on yourself and not cast twice.

![](https://cdn.discordapp.com/attachments/344344495254405131/748422522021871616/unknown.png)

**Comment by killerwife** [comment]
Solved some time ago.
