### ISSUE TITLE
[CLASSIC] Quel'Serrar Quest Chain - Quest 7507 (Foror's Compendium) Should Give Item 18513 (A Dull and Flat Elven Blade)

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1649]
**Current behavior**: 
When you hand in Foror's compendium you aren't given the dull sword that you need to take the follow up quest.

**Expected behavior**: 
After handing in quest 7507 you are given item 18513. As far as I can see it's not listed as a quest reward, it should be given to the player by casting a spell on them.

https://classicdb.ch/?quest=7507 - The first quest
http://classicdb.ch/?spell=22925 - The spell that should be cast on completing the first quest
https://classicdb.ch/?quest=7508 - The follow up quest you get from the sword.

**Steps to reproduce**:

You probably need to be a level 60 warrior to do these.
1. Give yourself Foror's Compendium of Dragon Slaying (.add 18401)
2. Accept the quest from the book
3. Go to Lorekeeper Lydros (.go creature id 14368)
4. Hand in the quest, no flat blade is given so the chain can't go further.

Client version: 1.12.1 (5875)

Commit hash: 16a2393

Database version: 1.9 - b5e2f39

Operating system: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by EGSilver** [comment]
This item is provided when starting the quest Neutral 15 [60] The Forging of Quel'Serrar which starts with Neutral 15 Lorekeeper Lydros in Dire Maul.
