### ISSUE TITLE
[TBC] Warlock Pet Bugs

### ISSUE THREAD

**Issue by BillytheOrc** [cmangos/issues#1651]
**Current behavior**: 
On dismissing warlock pets, their name is reset and their spells are all removed.

**Expected behavior**: 
Literally anything but the current behavior.

**Steps to reproduce**:

1. Use Grimoire of Sacrifice on a voidwalker. 
2. dismiss it.
3. summon it back.
4. it's all gone. and his name changed.

**Client version**: 
2.4.3 Build 8606

**Commit hash**: 
most recent as of 7/15/2018

**Database version**: 
most recent as of 7/15/2018

**Operating system**: 
Win10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by BillytheOrc** [comment]
Fixed in https://github.com/cmangos/mangos-tbc/commit/a9d3b20298e185c37fa7d75d5e2929e59be7c32f

**Comment by jimmybrancaccio** [comment]
Closing this one out per the above comment.
