### ISSUE TITLE
[WotLK] Guild Vaults not loading items.

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#1654]
**Current behavior**: 
Open the guild vault and most of the items don't load. I have over 600 items and it only shows a few with retrieving item info.Tabs also don't load correctly.

**Expected behavior**: 
Open vault see items and tabs work... :)

**Steps to reproduce**:

1. Open Guild Vault.
2. See a few items with retrieving item info.

**Client version**: 
3.3.5
**Commit hash**: 
cd8a683f5a74857c42d00b3759b12b36a7e762e5
**Database version**: 
PSDB
**Operating system**: 
Windows 7 64-bit

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
@Rog360 please try the following:

try reverting these two commits:
https://github.com/cmangos/mangos-wotlk/commit/35527066cb91bfcdd2032364c7acb0fc6dd0a302
https://github.com/cmangos/mangos-wotlk/commit/7a2c29c5a6e4b3e135c3a69b0be4039605022282
in this order

then try if it works now

if it works try two more usecases:
put an item with charges in the bank
put an item with 3 sockets socketed in the bank (leatherworking tbc item for example)
and let me know

**Comment by killerwife** [comment]
Also one more thing, which might be much faster.
I changed this line:
data << uint32(pItem->GetCount());                  // +12 ITEM_FIELD_STACK_COUNT
into
data << uint8(item->GetCount());                                                    // +12 ITEM_FIELD_STACK_COUNT
 by Mistake

Maybe doing this one change will fix it all without reverting. I am sorry I can't help atm but I am not at my wotlk-capable pc.

**Comment by Rog360** [comment]
You beat me to this one. Fixed in commit 88a49b083da391bbfc3db5ad2110df16777e9e34.
Thanks Killerwife... ;)
