### ISSUE TITLE
[CLASSIC][TBC][WOTLK] Fleeing Enemies Seek Assistance From Dead or Engaged Allies

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1658]
**Current behavior**: 
When you're fighting creatures that flee they will include already engaged or dead allies as possible targets to run to for help.

**Expected behavior**: 
They should exclude dead or engaged enemies from their list. I tried to look for the cause but didn't get too far. For classic I think it's in bool Unit::CanAssist(const Unit* unit, bool /*ignoreFlags*/) const, line 444 of Relations.cpp, there needs to be something there maybe to check that the unit to assist isn't dead or in combat.

**Steps to reproduce**:

1. Go to creatures that flee, I was using level 12/13 murlocs in Darkshore - .go creature id 2202
2. Get one to flee level while 2 are engaged or while standing near a corpse - .damage 210 (they seem to have around 220ish health.
3. 

**Client version**: 1.12.1

**Commit hash**: ca5ef78

**Database version**: b5e2f39

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Trystanosaurus** [comment]
This also seems to be happening on tbc too (tested on commit 387f363).

**Comment by cala** [comment]
The fleeing movement generator being the same across the three cores, this issue is probably also relevant for WotLK.
