### ISSUE TITLE
Shirrak the dead watcher

### ISSUE THREAD

**Issue by EGSilver** [cmangos/issues#1660]
**Current behavior**: 
When Shirrak uses his Focus fire ability (not sure if it is related) the map around the player disappears and the server stutters/hangs. You are unable to move and need to teleport out.

![shirrak](https://user-images.githubusercontent.com/40366529/43035499-5e9fba8e-8cf1-11e8-9621-b3f51cf78d9f.png)

**Steps to reproduce**:

1. Start the fight, stand still wait a while.

**Client version**: 
2.4.3

**Database version**: 
Latest.

**Operating system**: 
W10

**Comment by killerwife** [comment]
I did just that and this did not happen to me to be honest. I am reworking the focus fire very slightly but that should have no impact on this.

**Comment by EGSilver** [comment]
odd, restarted try'd again, same thing happened. could it be related to my maps?

**Comment by killerwife** [comment]
Clear client cache and turn off all addons. What then?

**Comment by EGSilver** [comment]
Well... It crashed the client now

**Comment by EGSilver** [comment]
No idea what is happening here, but my client crashes in the middle of the fight each time now.

**Comment by AnonXS** [comment]
Maybe also needs to be neutral

**Comment by EGSilver** [comment]
DB rebuild solved this.
