### ISSUE TITLE
Assertion in MaNGOS

### ISSUE THREAD

**Issue by madmax765** [cmangos/issues#1661]
**Current behavior**: 
It is displaying an error in the console after it loads. This error does not show up in 2.4.3 or 3.3.5, just only in 1.12.1

mangos-classic\src\shared\threading.cpp:131: Error: Assertion in MaNGOS::Thread::setPtiority failed: _OK
**Expected behavior**: 

![image](https://user-images.githubusercontent.com/29853/43043674-91302554-8d66-11e8-8804-bc3963f11a91.png)

should not show this error
**Steps to reproduce**:

1.  compiled on one pc running win 10 pro
2.  moved to another pc running windows server 2008 r2 standaed
3. executed 

**Client version**: 
1.12.1 -Villian
**Commit hash**: 
35f03b7b4a1fc188fc2117a5621d90b697025569
**Database version**: 
Classic DB version 1.9 "The Black Dragonflight". For core Classic z2717.
**Operating system**: 
Complied on win 10 pro
Ran on Windows server 2008 r2 standaed
[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
@cyberium if you can, look at this.

**Comment by 127y** [comment]
@madmax765 

Threading.cpp

        case Priority_Realtime: _ok = SetThreadPriority(handle, THREAD_PRIORITY_TIME_CRITICAL) == 0; break;
        case Priority_Highest : _ok = SetThreadPriority(handle, THREAD_PRIORITY_HIGHEST)       == 0; break;
        case Priority_High    : _ok = SetThreadPriority(handle, THREAD_PRIORITY_ABOVE_NORMAL)  == 0; break;
        case Priority_Normal  : _ok = SetThreadPriority(handle, THREAD_PRIORITY_NORMAL)        == 0; break;
        case Priority_Low     : _ok = SetThreadPriority(handle, THREAD_PRIORITY_BELOW_NORMAL)  == 0; break;
        case Priority_Lowest  : _ok = SetThreadPriority(handle, THREAD_PRIORITY_LOWEST)        == 0; break;
        case Priority_Idle    : _ok = SetThreadPriority(handle, THREAD_PRIORITY_IDLE)          == 0; break;
        
---------------------------------------------------------------------------------------------------------------------
        
        case Priority_Realtime: _ok = !!SetThreadPriority(handle, THREAD_PRIORITY_TIME_CRITICAL) ; break;
        case Priority_Highest : _ok = !!SetThreadPriority(handle, THREAD_PRIORITY_HIGHEST)       ; break;
        case Priority_High    : _ok = !!SetThreadPriority(handle, THREAD_PRIORITY_ABOVE_NORMAL)  ; break;
        case Priority_Normal  : _ok = !!SetThreadPriority(handle, THREAD_PRIORITY_NORMAL)        ; break;
        case Priority_Low     : _ok = !!SetThreadPriority(handle, THREAD_PRIORITY_BELOW_NORMAL)  ; break;
        case Priority_Lowest  : _ok = !!SetThreadPriority(handle, THREAD_PRIORITY_LOWEST)        ; break;
        case Priority_Idle    : _ok = !!SetThreadPriority(handle, THREAD_PRIORITY_IDLE)          ; break;

**Comment by madmax765** [comment]
Thank you, That seemed to fix it

https://prnt.sc/ka562d

**Comment by evil-at-wow** [comment]
The code was wrong to begin with. The Windows function SetThreadPriority returns a non-zero value on success, so just changing the comparison to != 0 should work as well (and it doesn't require that double-operator-!-to-convert-to-bool weirdness). Remarkably enough this seems to have been changed in the TBC core over two years ago, without being merged to Classic. Strange.

**Comment by stfx** [comment]
> changing the comparison to != 0 should work as well (and it doesn't require that double-operator-!-to-convert-to-bool weirdness).

I agree that all `!!` should be changed to `!= 0`
