### ISSUE TITLE
[WOTLK] Error With transportsystem.cpp

### ISSUE THREAD

**Issue by madmax765** [cmangos/issues#1662]
**Current behavior**: 
Can not close console  CMD window when trying to ext using CTRL+C
**Expected behavior**: 
To close and exit
**Steps to reproduce**:

1. startup server 3.3.5 
2. let it run for a few

3. Then try to ext it
![image](https://user-images.githubusercontent.com/29853/43112360-bc6ec97e-8ec3-11e8-8413-f4c2e43bec2f.png)
4. Can not close the window with task manager
5. It just locks up

**Client version**: 
3.3.5 WOTLK
**Commit hash**: 
b9632ec92cec3000f21270c5d62036dcc2a5da86
**Database version**: 
WoTLKDB v1.1 'The Warsong' for CMaNGOS-WOTLK 13965
**Operating system**: 
Winows server 2008 R2 standard

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Rog360** [comment]
I had this same error last night after running server for about 3 or 4 hours. I didn't have any problem with closing and restarting the server. I'm using Windows 7 ultimate x64 and commit 
b9632ec92cec3000f21270c5d62036dcc2a5da86... ;)

**Comment by killerwife** [comment]
I suggest loading up server in debug mode and acquiring more information. windows server 2008 is suspiciously old but that might just be me. I am currently away from my wotlk capable PC.

**Comment by Rog360** [comment]
I'm on it. I'll post back more info on this when it crashes under debug mode. Thanks for your work... :)

**Comment by Rog360** [comment]
I haven't been able to get any debug info for this. I've only had it do it once. When I properly shutdown the server with ".server shutdown 5". Most of the time I just close the window... :(

**Comment by jimmybrancaccio** [comment]
@Rog360 Is this still an issue? Can you confirm if it happens on an OS newer then 10 years old?

**Comment by jimmybrancaccio** [comment]
Thank you for the update @Rog360. I'm going to go ahead and close this one out then. If you're still seeing issues with it please open a new case with full details. Thanks!

**Comment by madmax765** [comment]
I update my OS from windows  server 2008 r2 to Windows server 2016 standard Did a fresh pull today Commits on Nov 25, 2018  e45254ea3b12437a73a77639407ae9f545283c4e 
And I am still getting this error.
