### ISSUE TITLE
[TBC] Quest 746 - Dwarven Digging Only Dropping 1 Prospector's Pick

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#1663]
**Current behavior**: 
The quest (in Mulgore) requires you to collect 5 Prospector's Picks (Item 4702) and break them at a forge to get 5 Broken Tools (item 4703).

Currently you can only get one Prospector's Pick at a time.

**Expected behavior**: 
You can get more than one prospector's pick. I'm not sure if the maximum should be 5 or if it should be unlimited though.

The problem seem to be that in the quest_template ReqSourcCount1 is set to 1, meaning you only get one pick to drop. In the vanilla database it's set to 5 and in the WotLK database it's set to 0.

I couldn't find any proof but I think the WotLK one is right, you can pick up as many as you like so I've fixed it on my core with the following database update..

`UPDATE `mangos-tbc`.`quest_template` SET `ReqSourceCount1`='0' WHERE  `entry`=746;`

**Steps to reproduce**:

1. Get the quest .quest add 746 (the mobs are level 7-9)
2. Go to the quest mobs .go creature id 2989
3. Farm and see if you can get more than one pick.

**Client version**: 2.4.3 (build 8606)

**Commit hash**: d1f8fa9

**Database version**: 1374c15

**Operating system**: Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
The accepted fix will be: UPDATE quest_template SET ReqSourceCount1=5 WHERE entry IN(746);
It will be dealt with after the big tbc-db release we are preparing.

**Comment by berserkingyadis** [comment]
Was this fixed by the mentioned tbc-db release? I

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/93ef06b2cf038bebfa5763e2907cf62d3fce2575
