### ISSUE TITLE
[WOTLK] AHBot: Boost Value Spam

### ISSUE THREAD

**Issue by madmax765** [cmangos/issues#1668]
**Current behavior**: 
AH Bot spamming CMS Window saying 
`AHBot: Boost value used to  fill AH! (If this happens often adjust both itemsPerCycle in ahbot.conf)`
repeating like once a minute
**Expected behavior**: 
should not see it
**Steps to reproduce**:

1. Just run cmangos 
2.  ran another copy of in debug mode same, but nothing in logs on it
3. setting in the ahbot
`AuctionHouseBot.ItemsPerCycle.Boost = 20
AuctionHouseBot.ItemsPerCycle.Normal = 20`

**Client version**: 
WOTLK 3.3.5
**Commit hash**: 
154e446e9aeb07f02eba09c819e551c7865fb50c
**Database version**: 
WoTLKDB v1.1 'The Warsong' for CMaNGOS-WOTLK 13965
**Operating system**: 
Windows server 2016 standard 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)
This does not show up in the crash log or in serves log

![image](https://user-images.githubusercontent.com/29853/43369340-4e03b83e-933a-11e8-94e1-65122a43e90a.png)

![image](https://user-images.githubusercontent.com/29853/43369342-5755668a-933a-11e8-9e76-3810348a302a.png)

**Comment by jimmybrancaccio** [comment]
This sounds more like a feature request as it appears the output is intended to be like this. Marking as such.

**Comment by madmax765** [comment]
seems to be ok now
