### ISSUE TITLE
[TBC] Arcane Torrent. Caster resists his racial ability

### ISSUE THREAD

**Issue by ungluck** [cmangos/issues#1673]
**Current behavior**: 
Blood Elf casts Arcane Torrent. Spell is begin resisted and set into cooldown. In such situation spell doesn't give energy or mana to caster.

**Expected behavior**: 
Spell shouldn't move to cooldown or should give resources.

**Steps to reproduce**:
1. Cast Arcane Torrent
2. Cast it again and again
3. Do 2, until see resist
![image](https://user-images.githubusercontent.com/40755598/43467803-380b26ea-94eb-11e8-8ed8-c9211879803e.png)

**Client version**: 
2.4.3

**Commit hash**: 
commit d1f8fa9d1d39467c7de2bbc602fb13150ee6f3a9
**Database version**: 
latest
**Operating system**: 
win32, win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
Havent tested it again, but @killerwife fixed the root issue recently, it was causaed by a pretty bad hack.
It will eventually be resolved in public when the related commit gets exported.

**Comment by ungluck** [comment]
Thanks for explain. First this was found near week ago, may be I has been fixed already. I'll recheck it again.

**Comment by ungluck** [comment]
Rechecked it again
![image](https://user-images.githubusercontent.com/40755598/43486437-85635350-951c-11e8-93a8-a7b8f6051671.png)

**Comment by ungluck** [comment]
Thanks, seems work now without resist
