### ISSUE TITLE
[Discussion] Ghamoo-ra armor value

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1675]
The NPC Ghamoo-ra (4887, https://classicdb.ch/?npc=4887) in Blackfathom Deeps has the highest armor value of any NPC in classic: 925,032. This seems a tad excessive for a level 25 boss, are we certain this is correct?

**Comment by Tobschinski** [comment]
Should be even higher. 925032 is its armor when it's lvl 23.

**Comment by offl** [comment]
http://www.wowhead.com/npc=4887/ghamoo-ra#comments:id=772435

**Comment by bdebaere** [comment]
@Tobschinski It's 925,032 for level 25 currently. See the database.

**Comment by Tobschinski** [comment]
Yeah that's wrong, the armor was taken from the Bestiary, but it's level 23 in there. Need to be 1000 x whatever the armor of a level 25 warrior is.

**Comment by cala** [comment]
@bdebaere you can trust @Tobschinski in here. I know he checks and double checks what he does and he is able to challenge the validity of sniffs or resources against old versions of the game, like Classic.

Regarding Ghamoo-ra, I have its stats corrected in a rework of Blackfathom Deeps I have on my disk.
Here:

```SQL
-- Ghamoo-ra
UPDATE creature_template SET HealthMultiplier=6, MinLevelHealth=4194, MaxLevelHealth=4194, ArmorMultiplier=1000, Armor=1026000, DamageMultiplier=1.7, MinMeleeDmg=36, MaxMeleeDmg=48, MinRangedDmg=24, MaxRangedDmg=36, MeleeAttackPower=86, RangedAttackPower=6, MeleeBaseAttackTime=2000, RangedBaseAttackTime=2000 WHERE entry=4887;
```
More than 1M armor. Good luck with that!

**Comment by bdebaere** [comment]
@cala Will you apply this fix?

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/0af9154b4e2d826838eb60e174c33f7cfab7ff08
