### ISSUE TITLE
Multithreading on extractors.

### ISSUE THREAD

**Issue by FALL1N1** [cmangos/issues#1676]
**Current behavior**: 
No multi threading support, causing the mmap generator to extract for 3-4 days straight.

**Expected behavior**: 
Implement a --threads (multi threading, trinity-like) support so we can build them within minutes (depending on core/thread count).

**Operating system**: 
any

----

Is there any multi threading support on the extractors because generating mmaps for 3 days on a (e.g) 24core cpu is just ridiculous, if there isn't please let me know so i can port trinity's code and make a PR.
Regards.

**Comment by FALL1N1** [comment]
http://prntscr.com/kdqhwe http://prntscr.com/kdqj8y it has been running on all 24 available threads but it utilizes only 4 (i think) and it has been running for almost over 2 days straight

**Comment by killerwife** [comment]
When using the script you have to specify core count. Also did you build extractors in Release build? Because in debug it will indeed take more than a day.

**Comment by FALL1N1** [comment]
ah.. it is in debug so that's must be it, thanks
