### ISSUE TITLE
[TBC] Arelion's Secret Quest Can Be Completed Only Once

### ISSUE THREAD

**Issue by ungluck** [cmangos/issues#1677]
**Current behavior**: 
Arelion's Secret quest (id = 10286) can be completed only once. The second time you or other player can not do it. Only after server restart you can do this quest again.

**Expected behavior**: 
Quest should be done many times. For every player.

**Steps to reproduce**:
1. do .quest add 10286
2. go to Magister Aledis (npc=20159) and start battle
3. fight with him until quest will be completed (25% of Aledis  hp).
4. wait for Magister Aledis will refresh and start battle again.
5. fight until he set to 25% hp again, and see that he will not stop combat. (only after server restart you can do it again)

locally I repair it with update EnterEvadeMode() function
I think m_bIsDefeated should be set to 'false' after Aledis eveid combat, so I add m_bIsDefeated = false;

        if (m_creature->isAlive())
        {
            if (!m_bIsDefeated)
            {
                m_creature->SetWalk(true);
                m_creature->GetMotionMaster()->MoveWaypoint();
            }
	    else
	    {
		m_creature->GetMotionMaster()->MoveIdle();
		m_bIsDefeated = false; // - this one was added for local quest repair
	    }
        }

**Client version**: 
2.4.3
**Commit hash**: 
Server version:
commit d1f8fa9d1d39467c7de2bbc602fb13150ee6f3a9
**Database version**: 
latest
**Operating system**: 
win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by stealthgun** [comment]
I have the same issue.
