### ISSUE TITLE
Paladin Cleanse dismisses buffs

### ISSUE THREAD

**Issue by Lankytim** [cmangos/issues#1681]
**Current behavior**: 
Paladin uses Cleanse on self to dispell Bonechewer Rot.
Bonechewer Rot is dispelled, but so are active buffs, eg: Blessing of Wisdom and Vengeance.

**Expected behavior**: 
Cleanse should only dispell applicable debuff, ie. Bonechewer Rot.

**Steps to reproduce**:
1. As lvl 65 paladin, cast Blessing of Wisdom on self.
2. Engage Bonechewer Scavenger in Hellfire Peninsula.
3. Once afflicted by Bonechewer Rot, cast Cleanse on self.

**Client version**: 
2.4.3

**Commit hash**: 
d3dec8fd2f6868b96c92e3985540a25aed41d6ee

**Database version**: 
1.7.0
a87e8c5fa8640a571827b768394c11b352683c6e

**Operating system**: 
Server: Debian 9 amd64
Client: Windows 7 x64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by ungluck** [comment]
Seems the same bug as
https://github.com/cmangos/issues/issues/1680
where pet dispel dispells his buff.

**Comment by Lankytim** [comment]
Thank you.  I will try to arrange a WotLK system for testing, or test it on TBC once the fix is hopefully ported to cmangos-tbc.
