### ISSUE TITLE
[CLASSIC] Fishing Pools Have Low Respawn Time

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1683]
**Current behavior**: 
Fishing pools, specifically the wreckage pools which grant you a chest e.g. https://www.wowhead.com/item=21150/iron-bound-trunk respawn too fast. There are some places like Ratchet and Stranglethorn Vale where you can simply farm all day moving from pool to pool because by the time you reach the third or fourth pool, the first one is already respawned again. I noticed in the db it said for some pools a 180 seconds respawn time, that's 3 minutes. That may be correct for some non-wreckage pools, but based on my experience with retail I doubt it is for wreckage pools.

**Expected behavior**: 
It seems to me like it should be a lot slower. Some use the pooling system, but not all of the fishing pools do. I'm unsure if this is intentional or not.

**Steps to reproduce**:

1. Go to Ratchet
2. Fish the wreckage pools
3. Notice you can farm this

**Comment by AnonXS** [comment]
I think what i observed when looking through the gos in stranglethorn vale is that they miss pooling, most fishing node pools consist of 2-4 different types of gos that can spawn in this place, so we probably are missing pooling in these locations making these gos 100% repeated spawns.

**Comment by AnonXS** [comment]
To add to this a little more, the respawntime in lowlevel zones was kept pretty low, as this was sort of confirmed to be the case for these zones as the trunks n stuff arent really worth that much compared to higher level trunks found in e.g STV or Desolace. Needs to be further monitored to see how it plays out in an actual production environment.
