### ISSUE TITLE
[CLASSIC] Onyxia Stands in the Air

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1685]
**Current behavior**: 
Onyxia stands in the air when she is done moving. This could also be affecting other creatures.
![image](https://user-images.githubusercontent.com/1436449/44300263-6f75fc00-a304-11e8-85d8-48adf5e22ac1.png)

**Expected behavior**: 
While in the air she needs to keep her flying animation even while standing still in the air.

**Steps to reproduce**:

1. .go creature Onyxia.
2. Start the fight.
3. Get to the whelp spawn phase, this is when Onyxia lifts in the air.
4. Notice when she is standing still she is standing on the air.

**Client version**: 
1.12.1
**Commit hash**: 
Latest
**Database version**: 
Latest
**Operating system**: 
Win10

**Comment by killerwife** [comment]
Try SetHover.

**Comment by AnonXS** [comment]
And spell animation for Spells Executed during Flying (fireball) can cause flying animation to not go off correctly during the casttime, but unrelated to that.

**Comment by al3xc1985** [comment]
After onixya remake by cala i think it can be closed. What do you think? @killerwife

**Comment by killerwife** [comment]
Actually should've been fixed on classic by cala and by me on tbc.

**Comment by al3xc1985** [comment]
Yes after your last export cala imolementes her flying by spell. I know that for sure

**Comment by al3xc1985** [comment]
@killerwife  can we close it?

**Comment by cala** [comment]
Yes. Can be closed. Thank you.
