### ISSUE TITLE
[CLASSIC] Mend Pet's Range Restriction is not Updated

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1686]
**Current behavior**: 
Mend Pet has a range of 20 yards. But you can be as far as you want from your pet and it will still allow you to cast the spell. However, it will not perform a heal, it will consume mana though. The range isn't updated client side or something. 

**Expected behavior**: 
Mend Pet should only be castable when in 20 yards of your pet. This way it will actually heal your pet when consuming mana. The client should be updated whether you are in range or not and a server side check to produce the message out of range needs to be added.

**Steps to reproduce**:

1. .learn 1515 (Tame Beast)
2. .learn 13544 (Mend Pet)
3. Tame something, put the pet on stay so it stays in place.
4. Try to cast Mend Pet from further than 20 yards. Your mana is consumed but your channeling is interrupted.

**Client version**: 
1.12.1
**Commit hash**: 
Latest
**Database version**: 
Latest
**Operating system**: 
Win10

**Comment by killerwife** [comment]
TARGET_PET is not checking for range in checkcast, There is a check in SetTargetMat, which I recently moved. This means an additional check for range has to be added to CheckCast. I wont be home until tomorrow, maybe ull beat me to it :D                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ‎
