### ISSUE TITLE
[CLASSIC] Tame Beast is Possible While Not Holding Aggro

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1687]
**Current behavior**: 
It's possible to tame a pet with someone else tanking it, completely trivializing the experience.

**Expected behavior**: 
I'm not sure what should happen but the end result should be that you can't tame a pet if someone else is had aggro for even a second.

**Steps to reproduce**:

1. .learn 1515 (Tame Beast)
2. Start taming
3. Have a friend or another character take aggro while you tame
4. Notice you will still end up with the pet

**Client version**: 
1.12.1
**Commit hash**: 
Latest
**Database version**: 
Latest
**Operating system**: 
Win10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
I am gonna need source on this. Fixing it is a 5 min thing, but I remember tanking for a friend.

**Comment by bdebaere** [comment]
@killerwife The spell description says "If you lose the beast's attention for any reason, the taming process will fail".

**Comment by killerwife** [comment]
https://www.youtube.com/watch?v=4XtynHRCNaw&feature=youtu.be @berserkingyadis you wanted something to work on ^^

**Comment by berserkingyadis** [comment]
Indeed, Ill take a look. Pointers on where to start are always welcomed

**Comment by killerwife** [comment]
Code that checks during execution of channeled spells, and utilize the "tame beast" spell attribute for the condition.

**Comment by berserkingyadis** [comment]
@killerwife I wont be able to to this, if this is a 5 min thing pls go ahead and fix, I shall learn from the diff.

**Comment by killerwife** [comment]
This is already implemented using SPELL_ATTR_EX2_TAME_BEAST in Spell::Update
