### ISSUE TITLE
[TBC] Demons and Humanoids Under Control Can Use Spells Without Cooldown

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1688]
**Current behavior**: 
Warlock can control demons from open world. And use a lot of them spellsand abilityes without cd, so warlock can kill bosses and elits using one button and spend for 10-15 secs.
**Expected behavior**: 
Spells should be used with cd.
**Steps to reproduce**:
1. Control demon, for example - one of demons from Mechanar
2. Go to combat and use his spell
3. Kill enemies spend 1-2 secs

There is only example - the same issue with cd exists with other demons - in nagrand or winterspring or other locations. I think, the same issue is with humans and priest's mind control, but I must check it.

I try to load video using radical. If you can not see it - answer please.
https://radikal.ru/video/ycrN1CZ8xGC

**Client version**: 
2.4.3
**Commit hash**: 
latest
**Database version**: 

**Operating system**: 
Win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Each such spell needs a cooldown added. Tech is there for it, but its a painstaking research. Please add a list of mobs that have issues with this for you.

**Comment by ungluck** [comment]
Ok, I'll add mobs from the warlock, that I've already found:
Mechanar
npc=19712 - spell=35047
npc=19712 - spell=35056
npc=19712 - spell=38923

Nagrand
npc=17152 - spell=32009

Winterspring
npc=7463 - spell=16856

Could you please explain: cooldown should be added in spell.dbc or in spell_template database? Or may be somewhere in core files?

**Comment by datchannin** [comment]
The Blood Furnace
Hellfire Familiar
npc=19016
npc=21646
spell=13341

Felguard Brute
npc=18894
npc=21645
spell=15615
spell=18072

shadowmoon-technician
npc=17414
npc=18618
spell=30846

**Comment by datchannin** [comment]
The Shattered Halls
Shadowmoon Acolyte
npc=16594
npc=20576
spell=15587 (15)
spell=31516 (15)
spell=15585 (12)
spell=35943 (12)
spell=36052 (20)
spell=35944 (20)

Shattered Hand Champion
npc=17671
npc=20584
spell=11972 (12)
spell=32588 (20)
spell=32587 (20)

Shattered Hand Brawler
npc=16593
npc=20582
spell=36033 (12)
spell=8876 (12)
spell=3391 (12)

shattered-hand-zealot
npc=17462
npc=20595
spell=30989

**Comment by datchannin** [comment]
The Slave Pens
coilfang-soothsayer
npc=17960
npc=19890
spell=15791
spell=15790

coilfang-scale-healer
npc=21126
npc=21842
spell=37669
spell=34944

**Comment by datchannin** [comment]
The Steamvault
coilfang-siren
npc=17801
npc=20623
spell=37856
spell=35106

coilfang-oracle
npc=17803
npc=20622
spell=8281

**Comment by datchannin** [comment]
Mana-Tombs
ethereal-scavenger
npc=18309
npc=20258
spell=34920
spell=33871

ethereal priest
npc=18317
npc=20257
spell=34944
spell=37669

ethereal-theurgist
npc=18315
npc=20261
spell=32316
spell=17145
spell=38064

ethereal-spellbinder
npc=18312
npc=20260
spell=32316

**Comment by datchannin** [comment]
Sethekk Halls
sethekk-shaman
npc=18326
npc=20699
spell=22885
spell=32663
spell=15501

**Comment by datchannin** [comment]
The Botanic
Bloodwarder Greenkeeper
npc=18419
npc=21546
spell=34797
spell=39120
spell=39121
spell=34798
spell=34800

**Comment by datchannin** [comment]
The Mechanar
Bloodwarder Physician
npc=20990
npc=21523
spell=36340
spell=38921

Bloodwarder Centurio
npc=19510
npc=21522
spell=35178

Sunseeker Netherbinder
npc=20059
npc=21541
spell=35261
spell=38936

Sunseeker Engineer
npc=20988
npc=21540
spell=36341
spell=36345
spell=36346
spell=39196

mechanar-driller
npc=21528
npc=19712
spell=35056
spell=38923
spell=35047

bloodwarder-slayer
npc=19167
npc=21524
spell=13736
spell=15708
spell=35189
spell=15589

**Comment by datchannin** [comment]
The Arcatraz
Ethereum Slayer
npc=20896
npc=21596
spell=36838
spell=38894

Spiteful Temptress
npc=20883
npc=21615
spell=36868
spell=38892

**Comment by datchannin** [comment]
OPEN WORLD
Felguard Elite
npc=8717
spell=16046 (20)
spell=13737 (20)

Hound of Culuthas
npc=20141
spell=36405

**Comment by bdebaere** [comment]
@killerwife From what source might we learn the cooldown? Wowhead says n/a for most of these.

**Comment by Saltgurka** [comment]
@bdebaere 
Spell IDs and their location on the action bar are from SMSG_PET_SPELLS_MESSAGE
Cooldowns are from SMSG_SPELL_COOLDOWN. Keep in mind though that many spells have random cooldown ranges and that will not be apparent from this packet. (you would have to cast it several times to get accurate values)

Me and Trugge has previously made quite a bit of progress on this topic and Slave Pens, Steamvaults, The Underbog, Hellfire Ramparts, Blood Furnace and Shattered Halls are already complete (Humanoids only so far). See wip file: https://gist.github.com/Saltgurka/5ef9a1c87635107310dbeed7c4a49132

There are two issues though:
* We have no way to set random cooldown ranges
* Different creatures can have different cooldowns for the same spell and we have no way to achieve that atm. (see Prayer of Healing s.15585 in gist above)

**Comment by Phatcat** [comment]
Some mobs are 'supposed' to be able to be mind controlled and use their abilities without cooldown;

https://www.youtube.com/watch?v=MasnehgAN8w
https://www.youtube.com/watch?v=1JOuLreyMtg
https://www.youtube.com/watch?v=W401_h4ADuY
https://www.youtube.com/watch?v=JfUOW1ZN_4k

All of those videos are from tbc era spanning 2007 - 2008, probably it was fixed before the release of wotlk, but was this sort of mechanic abuse available BEFORE the release of TBC though?

**Comment by killerwife** [comment]
Creature spell list system now supports sending these cooldowns for creatures which use it. TBC dungeons and raids already have all added. Closing this as its architecturally solved and need DB data.
