### ISSUE TITLE
[TBC] Priests Can Use Mind Control on NPCs That Are Level 62 and Above

### ISSUE THREAD

**Issue by ungluck** [cmangos/issues#1689]
**Current behavior**: 
There are 3 mind control spells
id=605 - lower than 32 level
id=10911 - lower than 47 level
id=10912 - lower than 62 level

I tryed all of them use to 69 level target, and 10912 can be used.
https://radikal.ru/video/WUTi7LrBeAr

**Expected behavior**: 
10912 can be used on 69 level target

**Steps to reproduce**:
Should be used not more than 62 level target

1. Target human npc 69 level and check using spell.
2. 
3. 

**Client version**: 
2.4.3
**Commit hash**: 
latest
**Database version**: 

**Operating system**: 
win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
https://www.wowhead.com/forums&topic=31069

**Comment by ungluck** [comment]
![image](https://user-images.githubusercontent.com/40755598/44567424-f8fd5200-a77a-11e8-998f-a6c06135342d.png)

If it is not a bug, priest should use mind control
id=605 - priest level + 2
id=10911 - priest level + 3
id=10912 - priest level + 4
If priest on 70 lvl, he should be able to control humanoid by first rank mind control - 72 level.
But on the video priest can not use first rank mind control on npc 69 level.

So the bug is in situation when priest can not use mind control first rank on npc 69 level?

**Comment by AnonXS** [comment]
https://wowwiki.fandom.com/wiki/Mind_Control?oldid=1589722
```
When learned, Mind Control actually lets a priest usurp the will of a player or mob higher the priest's level. It is not known if Rank 4 is harder to resist than Ranks 1 through 3, so it could be worth using the lower ranks to save mana if the target unit is within the priest's range. In general, however, MC is seldom used until endgame or PvP situations. 
```
So it seems that only last ranks "minlevel" is taken from players current level.

**Comment by killerwife** [comment]
It works differently. Max rank can be used on up to 70 in TBC.

```cpp
                    if (int32(expectedTarget->GetLevel()) > CalculateSpellEffectValue(SpellEffectIndex(i), expectedTarget))
                        return SPELL_FAILED_HIGHLEVEL;
````

The formula is BasePoints = 32 + Level * 1.00 up to spell max lvl which is 70 for spell 10912
