### ISSUE TITLE
[TBC][Crash] Alliance taxi path crashes core (through Ironforge and Stormwind). 

### ISSUE THREAD

**Issue by ungluck** [cmangos/issues#1690]
**Current behavior**: 
When player try to use taxi from Rebel camp to Refug Pointe - core crashes immediately after fly was pressed. The same crash when player try to fly from Menethil Harbr to Rebel Camp.
There is PrtScn of this path:
![image](https://user-images.githubusercontent.com/40755598/44656819-20665000-aa03-11e8-9c34-b47115a774be.png)

Path is 
Rebel camp - Stormwind - Ironforge - Refug Pointe.
Info from taxi_shortcuts table (database):
Rebel camp - Stormwind - path id = 752
Stormwind - Ironforge - doesn't have path in this table
Ironforge - Refug Pointe - path id = 31

Seems that crashe routes through Ironforge and Stormwind, in which the character is visually transplanted to the new Griffin. 

**Expected behavior**: 

**Steps to reproduce**:

1. Open fly points: Rebel camp - Stormwind - Ironforge - Refug Pointe.
2. Try to fly from Rebel camp to Refug Pointe

**Client version**: 
2.4.3 (rus locale)
**Commit hash**: 
latest
**Database version**: 

**Operating system**: 
win32, win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)
Sorry, now I don't have access to core and database to try compile in debug mode. This report is from verification team, and I see crashes from console as segmentation fails
![image](https://user-images.githubusercontent.com/40755598/44657057-29a3ec80-aa04-11e8-829a-9d05e8a07345.png)

**Comment by Warlockbugs** [comment]
Cannot reproduce.

**Comment by Warlockbugs** [comment]
You are missing a few database or core updates, which most likely means that this report is relevant to a private fork. Private forks of core and/or databases are not supported on the issue tracker.

**Comment by ungluck** [comment]
Thanks for answer, I can miss cmangos update, but I've never done any update myself, without github.com/cmangos. I'll check again all core and database update when have access to core.
