### ISSUE TITLE
[Regression] UnitFlag UNIT_FLAG_IMMUNE_TO_NPC is not properly removed when NPC is asked to engage combat

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1694]
**Current behavior**: 

A NPC with UnitFlag UNIT_FLAG_IMMUNE_TO_NPC will immediately reset when forced to engaged combat with another unit by script (as an attacker or as a target) or called upon by another unit. This was previously working.

I noticed this issue with Stitches event in Duskwood: Watcher Dodds is supposed to attack Stitches to prevent him from reaching Darkshire. The script I wrote years ago was working upon release as Watcher Dodds was engaging Stitches and calling for help of a nearby NPC (Watcher Paige).

I witnessed the event last week and Watcher Dodds no longer attacks Stitches and the DBScript throws an error stating that the NPC cannot attack (whenever I make Dodds attack Stitches or the opposite).

**Expected behavior**: 

A said in the [wiki](https://github.com/cmangos/issues/wiki/creature_template_classic#unitflags):
> UNIT_FLAG_IMMUNE_TO_NPC: makes you unable to attack everything. Almost identical to our “civilian”-term. Will ignore it’s surroundings and not engage in combat unless “called upon” or engaged by another unit.

A NPC with that flag should not engage or be engaged in combat by range or LoS. However, the flag should be removed (and automatically reapplied on evade/respawn) when another unit called for help or the NPC is attacked (or told to attack) by script.

**Steps to reproduce**:

1. `.go creature id 888`
2.  `.npc add 923`
3. Notice that Watcher Paige immediately attacks (she does not have UnitFlag UNIT_FLAG_IMMUNE_TO_NPC) and that Watcher Dodds turns towards NPC 923 because he is called for help by Watcher Paige, then he immediately resets and does not attack.

**Client version**: 
1.12.1

**Commit hash**: 

**Database version**: 
Classic DB v1.9

**Operating system**: 
Windows 7, macOS

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
It makes you unable to attack NPCs which is correct. You have to remove the flag in the script explicitly.

**Comment by AnonXS** [comment]
The descriptions for most of these flags are pretty outdated and for that one it is from a time where this unitflag wasnt even researched and implemented properly and i doubt due to scripting limitations that we will be able to handle this generically and we will eventually run into a rabbit hole again if we enforce a generic behavior.

We will have to do [this](https://github.com/lh-server/core/commit/ca0e90c56d27217e89a223d6abd7f6345ad1c448) everywhere like [here](https://github.com/cmangos/mangos-tbc/blob/master/src/game/AI/ScriptDevAI/scripts/kalimdor/zulfarrak/boss_zumrah.cpp#L80).

**Comment by killerwife** [comment]
The SetImmuneToPlayer vs the unitflag removal is due to pets. For players and NPCs which do have them, this is the intended way. Same with ToNPC. The removal is per script, it can be right on attacking, it can be on escort start (this is the most common one) or it can be completely off-pattern.

**Comment by cala** [comment]
Closed: see my comment [here](https://github.com/cmangos/issues/issues/1693#issuecomment-418381840)
