### ISSUE TITLE
[TBC] Bonus healing is not added, but bonus spell damage is added twice

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1696]
**Current behavior**: 
Bonus healing is not added from the items of character, but instead it spell damage is added twice.
For example:
item (144 damage bonus, 431 healing)
![image](https://user-images.githubusercontent.com/39913306/45045654-5303ee80-b07c-11e8-8628-118511638fc3.png)

Dru without item (0 damage bonus, 0 healing)
![image](https://user-images.githubusercontent.com/39913306/45045676-6616be80-b07c-11e8-894d-8c6e58b34044.png)

Dru with item (288 damage bonus, 0 healing)
![image](https://user-images.githubusercontent.com/39913306/45045695-74fd7100-b07c-11e8-8fbb-440cfea8acd2.png)

**Steps to reproduce**:

1. add item with spell damage and heal bonus
2. check bonuses without item
3. check bonuses with item
4. compare

**Client version**: 
2.4.3
**Commit hash**: 
latest
**Database version**: 

**Operating system**: 
win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cyberium** [comment]
Fixed on last revision
