### ISSUE TITLE
[WotLK] Remove olum & ragged_john from ScriptDev2 sql 

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#1697]
Their script was removed,But they are still assigned in SQL... :)
npc_spirit_of_olum
npc_ragged_john

**Steps to reproduce**:

1. Start Server
2. Stop Server
3. Read Errors in Server.... :)

**Client version**: 
3.3.5

**Commit hash**: 
78a07fc2947d06728a3c289f8442c43aafec19e1
**Database version**: 
PSDB

**Operating system**: 
Windows 7 x64

**Comment by Grz3s** [comment]
@xfurry  ;)

**Comment by Rog360** [comment]
Seems it's now removed... ;)
