### ISSUE TITLE
[TBC] Instant death using several buffs for paladin-protection

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1700]
**Current behavior**: 
I found some strange bug and tested it on the last core release
Binaries of commit a92b294
[s2378] Substantial EAI rework
Snapshot v0.18.1253

If paladin have several buffs, npc can kill him with 1634000000 physical damage.
Paladin should have improved righteous fury 3/3 and blessing of sanctuary buff
For my example he should have 10700 armor (50% damage reduce)

Then use improved righteous fury buff, use  blessing of sanctuary buff and npc will kill you instant.
For my opinion - if you have enough damage redution for reducing incoming damage to '1' , then may be improved right fury 3/3 is trying to additional reduce 6% damage at the end of calculations. 
(1 - 1*0.06) = 0.96 damage. So may be somewhere (damage-1) is converting to uint32 to overflow it? 
Please, look into video file, I tryed to save it to understand the paladin behaviour (damage is in log).

https://radikal.ru/video/3ULZCc5O7C6

P.S. Once I found the same bug with mage and his buff "Dampen Magic" that decrease spell damage. But for that time I didn't understand the issue. And only now I find how to rerun this bug with 100% death and save video.

**Steps to reproduce**:
1. have improved right fury 3/3 in talent
2. use blessing of sanctuary buff
3. use righteous fury buff
4. add 10700 armor (use set .additem 30123, 30124, 30125, 30126, 30127 and shield 1168)
5. go to npc=21661 for example
6. start battle and wait

**Client version**: 
2.4.3
**Commit hash**: 
latest
**Operating system**: 
win32

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
Another of these issues ended with the opener saying the russian wow client is at fault.

**Comment by datchannin** [comment]
Seems another is not connected with current. I don't have client crashes, and tryied only eng client. And my paladin is being killed with physical damage. I'm not sure, may be I should test it on russian client. I will try.

**Comment by datchannin** [comment]
I've just tested. The same on russian.
![image](https://user-images.githubusercontent.com/39913306/45570656-1dc18280-b86c-11e8-9174-28b4ccc1faa8.png)

**Comment by cyberium** [comment]
Fixed in the last revision ;) Thank you for this excellent bug report with all the information we need to reproduce.

**Comment by datchannin** [comment]
No problem, thanks for fix))
