### ISSUE TITLE
[TBC] Character freezes on dungeon zone in

### ISSUE THREAD

**Issue by Nolin7777** [cmangos/issues#1701]
**Current behavior**: 
It is not possible to enter Karazhan without getting stuck. Gameobjects and NPCs aren't loaded either.
Players reported this issue for UBRS too.

**Steps to reproduce**:

1. Enter Karazhan
2. Character freezes
3. Can't log off, move, use spells, etc..

**Client version**: 
2.4.3
**Commit hash**: 
latest
**Database version**: 
latest
**Operating system**: 
Debian 8

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
Set `Visibility.Distance.Instances     = 110` or lower.
