### ISSUE TITLE
[TBC] Rogue's SAP snares creatures when used followed by an spell

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1705]
**Current behavior**:
When a Rogue uses spell SAP on a creature, and then strike with a spell (Sinister Strike, Garrote, Backstab, Ambush), the creature will be snared on the ground, not following and attacking the player. 

If the sap is followed by an auto-attack, the crature will follow and attack the power normally.

**Expected behavior**: 
After the creature suffers from SAP, they should re-engage the player with the normal script.

**Steps to reproduce**:

**1.** .learn 1784
**2.** .learn 703
**3.** Use steath on a humanoid mob
**4.** Use garrote on stealthed mob
**5.** Walk away from the mob.

**Client version**: 
2.4.3 (8086)

**Commit hash**: 
Latest

**Database version**: 
Latest

**Operating system**: 
Debian 6

**Comment by ManoloZocco** [comment]
Same for me, i followed the same procedure.

**Client version:**
2.4.3 (8086)

**Commit hash**:
Latest

**Database version:**
Latest

**Operating system:**
win64

**Comment by Pooch11** [comment]
I am trying to work on this issue, and looking at other similar fixes involving CC to determine where to get started. It seems like any other bleed effects (Rupture) following Sap do not break this movement bug. Funny enough -  if you blind the target after the sequence above it will gain its movement again.
I have looked into similar closed issues to see if I can find any hints on where to get started. Right now I am honed in on. 
Unit::RemoveAurasWithInterruptFlags 
But could this be an incorrect entry into the spell_template instead?

Client version:
TBC 2.4.3 (8086)

Operating system:
win64

**Comment by SilvioDoMine** [comment]
@killerwife this issue back again. I could reproduce doing the follow: Sap with an rogue, and then another player use any spell.

Video proof: https://drive.google.com/file/d/1Wqgg4BIi9hDfksUHq_6ehhPe0mnc8cYn/view

**Comment by killerwife** [comment]
Tested, works as intended now.
