### ISSUE TITLE
[Discussion] Possible additional meaning of SPELL_ATTR_EX3_NO_INITIAL_AGGRO

### ISSUE THREAD

**Issue by ratkosrb** [cmangos/issues#1706]
I was reading old vanilla patch notes, and after comparing the spell data from client builds before and after that patch, it leads me to believe that the AttributesEx3 flag with value 0x00020000 (131072) means that the spell cannot proc effects on the victim.

> World of Warcraft Client Patch 1.11.0 (2006-06-20)
> - Pick Pocket: This ability will no longer trigger effects on your target.

![pick pocket](https://user-images.githubusercontent.com/35845488/45711258-a8b6bb80-bb91-11e8-907b-2f6b8f81e31d.png)

> World of Warcraft Client Patch 1.10.0 (2006-03-28)
> - Hunter's Mark - This spell no longer triggers procs on the spell
>   caster. This was being abused to land debuffs without getting on the
>   creature's hate list.

![hunters mark](https://user-images.githubusercontent.com/35845488/45711397-1d89f580-bb92-11e8-9a50-9bafd7556e74.png)

> World of Warcraft Client Patch 1.10.0 (2006-03-28)
> - Distract - This ability will no longer trigger a Shaman's Lightning
>   Shield (which caused the Rogue to lose stealth).

![distract](https://user-images.githubusercontent.com/35845488/45711613-d18b8080-bb92-11e8-9c01-89d7c827f3a5.png)

> World of Warcraft Client Patch 1.10.0 (2006-03-28)
> - Detect Magic - This spell no longer triggers procs on the spell
>   caster. This was being abused to land debuffs without getting on the
>   creature's hate list.

![detect magic](https://user-images.githubusercontent.com/35845488/45711832-74dc9580-bb93-11e8-9fdd-63afcae8c8fb.png)

It could be unrelated, but i wanted to share this just in case.

**Comment by Ve1vet** [comment]
@ratkosrb it means, what it means. When you cast spells with this attribute on creature, you not getting on the creature's hate list. Thats it. And this is right name for this attribute.
For triggering there is other attributes.

**Comment by ratkosrb** [comment]
The reason i brought it up was because in some of the examples i posted, this was the only attribute that changed in the spell data after the patch. Like in the 1.11 patch notes it says about Pick Pocket that "This ability will no longer trigger effects on your target.", and the only change for that spell in the 1.11 Spell.dbc compared to that of 1.10 is that attributesEx3 was set to 131072 which is the attribute SPELL_ATTR_EX3_NO_INITIAL_AGGRO, so i thought maybe it has another meaning too. All the other fields for this spell were the same.

I guess blizzard could have had other server side only fields or tables where this behavior is defined, which are not exported to the dbcs, so the fact that this attribute was added to the spell is unrelated.

**Comment by ratkosrb** [comment]
@Ve1vet I was proven right by the [enum names leak](https://wow.tools/dbc/?dbc=enumeratedstring&build=2.5.1.39640#page=1&search=2213) from TBC Classic.

And its now renamed to it's proper name.
https://github.com/cmangos/mangos-classic/blob/master/src/game/Spells/SpellDefines.h#L155
