### ISSUE TITLE
[Classic] missing mailbox in Orgrimmar ?

### ISSUE THREAD

**Issue by RichardGe2** [cmangos/issues#1707]
I'm suspecting there was a mailbox here during 1.12.

My sources are my memory, and Wow Cartographe 1.07 , released before TBC.

And it doesn't make sense to have 4 mailboxes inside IronForge and Stormwind, while only 1 in Orgrimmar.

![image](https://user-images.githubusercontent.com/26671163/45769066-c857ed80-bc3e-11e8-9333-47b0403693c2.png)

**Comment by RichardGe2** [comment]
Even in Wow Cartographe 1.05 - released before AQ & Naxramass, this mailbox is here.

**Comment by killerwife** [comment]
[11] Stationary Position: X: 1894.966 Y: -4553.875 Z: 29.15346, O: 2.155483
[11] Unk Int32: 2097
[11] Low GUID: 4027318272
[11] (0) OBJECT_FIELD_GUID: Full: 0xF00C0831 UInt64: 4027320369
[11] (2) OBJECT_FIELD_TYPE: (33) Object, GameObject
[11] (3) OBJECT_FIELD_ENTRY: 173047

The mailbox is in classic-db


  | 29100 | 173047 | 1 | 1894.97 | -4553.88 | 29.1535 | 2.15548 | 0 | 0 | 0.880891 | 0.473319 | 900 | 900 | 100 | 1
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by RichardGe2** [comment]
really? ok I need to double check why not in my server - I'll investigate and come back with explanation...

**Comment by cala** [comment]
@RichardGe2 : @killerwife provided data from sniffs for that particular mailbox so it can be added in Classic DB (and probably others) but you are right, it is currently missing. You can do a PR to add it from these data if you like.

**Comment by RichardGe2** [comment]
pull request ready - the mailbox was linked to event :  7 - Lunar Festival
