### ISSUE TITLE
[WotLK] Crash loading creature data.

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#1708]
**Current behavior**: 
On startup, Loads up to loading creature data
**Expected behavior**: 
Start up without crashing
**Steps to reproduce**:

1. Start server
2. Wait for creature data loading

**Client version**: 
3.3.5
**Commit hash**: 
commit 14f5c3fa52e171801d0e019e2fd62a1b0b1694a9
**Database version**: 
PSDB
**Operating system**: 
Windows 7 64bit

Source
mangosd.exe

Summary
Stopped working

Date
‎9/‎19/‎2018 1:20 PM

Status
Report sent

Description
Faulting Application Path:	C:\Program Files (x86)\WotLK 3.3.5\mangosd.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	mangosd.exe
Application Version:	0.0.0.0
Application Timestamp:	5ba284e3
Fault Module Name:	mangosd.exe
Fault Module Version:	0.0.0.0
Fault Module Timestamp:	5ba284e3
Exception Code:	c0000005
Exception Offset:	000000000018f520
OS Version:	6.1.7601.2.1.0.256.1
Locale ID:	1033
Additional Information 1:	285a
Additional Information 2:	285a26c24a109b78a9669694b6765e95
Additional Information 3:	b973
Additional Information 4:	b973c6f9650c339cb967ed674f63b82e

Extra information about the problem
Bucket ID:	2986041998

**Comment by cyberium** [comment]
Do you have it each time?

**Comment by Rog360** [comment]
Yes, Server won't start at all... :(

**Comment by cyberium** [comment]
visual studio 2015? Is it a crash or a lock? (nothing seems happening)

**Comment by Grz3s** [comment]
@cyberium  Server starts fine for me .... but smth strange happens here:
```code
2018-09-19 23:08:58 Loading Creature Data...
2018-09-19 23:08:59 ERROR:Error load map file: ./maps/5301920.map
2018-09-19 23:08:59 ERROR:Error load map file: ./maps/5305252.map
2018-09-19 23:09:00 ERROR:Error load map file: ./maps/0003955.map
```

**Comment by cyberium** [comment]
Yes i will do something to resilence them but i want to get more data about those errors. Why they happens, Bad creatures locations?

So there is nothing to worries here thoses errors exist since long time, i just unsilenced them.

**Comment by Grz3s** [comment]
good point... will track ... them ;)

**Comment by Rog360** [comment]
cyberium found the problem and it was on my db side. A few npc where spawned wrong and caused core to crash, So I'll close this issue and my give thanks to cyberium... ;)
