### ISSUE TITLE
[TBC] Can't deposit money on Guild Bank

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1710]
**Current behavior**: 
Deposit gold on Guild Vault doesn't work.

**Expected behavior**: 
It should remove your gold and put in Guild Vault.

**Steps to reproduce**:

1. Type .guild create YOURNAME "Testing"
2. Target yourself and type .mod money 100000
3. Go to any guild bank, and open it.
4. Try to Deposit any quantity of money
5. You can hear the money sound but no money is transfered.

**Client version**: 
2.4.3 (8606)

**Operating system**: 
Linux Debian 9

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by ManoloZocco** [comment]
I followed the procedure, in my case everything works correctly.

**Operating system:** Ubuntu 18.04

**Comment by SilvioDoMine** [comment]
Did you tried with a fresh compilation, @ManoloZocco?

**Comment by SilvioDoMine** [comment]
Everything works fine with commit 8acf1bb
