### ISSUE TITLE
[TBC] Paladin cleanse is also dispeling benefit buffs

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1711]
**Current behavior**: 
If have benefits buffs like Blessing of Might while you are using Cleanse to remove a Debuff, you will also lose 1 benefical buff.

**Expected behavior**: 
Should only dispell debuffs 

**Steps to reproduce**:

1. type .learn 29380 and  .learn 20217
2. Use Blessing of Kings on yourself
3. Type .cast self 41191 (To cast Deadly Poison on yourself)
4. While the debuff is on, use Cleanse on yourself.
5. Reproduced. The poison is gone, but also 1 benefical spell is gone too.

PS: This may also happen with Priest cleanse, and is probably related with shaman Purge spell problem #1702 

**Client version**: 
2.4.3 (8606)

**Commit hash**: 
b2fb23051013fb7400e169da052a7927da218478

**Database version**: 
Latest

**Operating system**: 
Linux Debian 9

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Lankytim** [comment]
I thought this sounded similar to #1681 which was fixed recently, so I tested #1681 again with b2fb230 and was NOT able to reproduce the previous issue.

Hopefully this information is helpful to someone.

**Comment by SilvioDoMine** [comment]
I tried now with lastest core rev and lastest tbc-db and still got this issue. You have discord to discuss, @Lankytim?

**Comment by SilvioDoMine** [comment]
This should be fixed by PR cmangos/mangos-tbc#249
