### ISSUE TITLE
[TBC] Grace periode time is crashing the server

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1713]
**Current behavior**: 
If a player ALT+F4 from the server, and not come back, the server will crash in 20 seconds.

**Expected behavior**: 
If the player don't log back in 20 seconds, he should be logged out.

**Steps to reproduce**:

1. Start the server
2. Loggin into a char
3. Alt + F4
4. Wait 20 seconds.

**Client version**: 
2.4.3 (8606)

**Commit hash**: 
8acf1bbc83b7239a24cc7872cdab31d889e60634

**Database version**: 
58aa53e81310595eb4b7703cf2672fa04b34270f

**Operating system**: 
Windows Server 2016 Database
&& Linux Debian 9

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)
Crash report: https://gist.github.com/SilvioDoMine/fa2f2c65fb1974bfea1e02ea960a5734

**Comment by Grz3s** [comment]
confirmed on [WoTLK]

**Comment by SilvioDoMine** [comment]
@Lillecarl checked out the crash report and figure out that this crash is related with https://github.com/cmangos/mangos-tbc/blob/master/src/game/Server/WorldSession.cpp#L489

Aparently is trying to get the IP of a disconnected session. Need to alter the string, or simple remove it will fix this crash.

**Comment by Lillecarl** [comment]
Ping @cyberium
