### ISSUE TITLE
[TBC] Creatures Mind Control (Charm) is Causing Character to Dodge Damage Forever

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1714]
**Current behavior**:
If you engage a creature that cast any type of mind control (charms) on you, and then you run to a place where the mob surely will flee (evade), he will get out of combat and your character will be immune to any kind of damage.

**Expected behavior**: 
After a mob cast any kind of mind control on you, he should keep in combat with you and re-engage afterwords.

**Steps to reproduce**:

This is slightly specific, so:

1. type .go xyz 4956.049805 -466.867004 319.248383 (On Map 1 - Kalimdor)
2. .die in every mob except Jadefire Trickster
3. Engage combat with him and run towards the top of the ramp
![image](https://user-images.githubusercontent.com/20645369/46450853-d2fba200-c769-11e8-968b-c5be687b107f.png)
4. Wait the mob uses the spell Cause Insanity on you.
5. He will evade towards his initial location, and when the debuff is vanished, you will be immune to every kind of damage.

**Extras**
- If you not go the ramp, the mob will evade, but you won't be immune.
- You can attack normally while dodging every damage.
- Can't be reproduced on pvp.
- This lasts untill you die or logout. 
- You can't buff yourself, and even If you use items such as food, the item will be used, but you won't get buffed.

If anyone need help to reproduce this, just ask me

**Client version**: 
2.4.3 (8606)

**Commit hash**: 
8acf1bbc83b7239a24cc7872cdab31d889e60634

**Database version**: 
58aa53e81310595eb4b7703cf2672fa04b34270f

**Operating system**: 
Linux Debian 9

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by SilvioDoMine** [comment]
@killerwife do you have an idea what may be causing this? Which part on the code should @LevelOneX and me look and give an attention.

**Comment by killerwife** [comment]
I do not, the first time I am hearing about this.

**Comment by MagPurify** [comment]
Possible related to this commit: https://github.com/cmangos/mangos-tbc/commit/d1aa52c863ff04957b9f44286a6f1bf31ebe0afd ... It fixed the problem, but sometimes I get a crash on that line of code, same as described on the commit https://github.com/cmangos/mangos-tbc/commit/d1aa52c863ff04957b9f44286a6f1bf31ebe0afd#r31948747

**Comment by KansasGremlin** [comment]
This has been reproduced many times.  Like posted, one of the main culprits are the Felwood Jadefire Tricksters.  Others include bosses who Mind Control, Silithus have bugs that are Slavemakers.  All can cause this to happen.  When a character gets mind controlled, without a second aggro target, the Trickster will try to reset to original position.  The Trickster's mind control can wear off and leave the afflicted person now in a state of EVADE.  You will not aggro any monster and if you hit the Trickster, he takes the damage, but immediately resets to full health.  So if you are in this state and hit a lvl1 squirrel, it will die.  But mostly you are now EVADE bugged until relog.  
In EVADE state, the character cannot even hit themself with a spell such as buff, food, and if they craft an item (for example smelt copper ore) the Copper ore is used but you evade the creating of Copper Bars.  Health potions will be consumed, but you Evade the heal.  Zoning does not fix the issue, only known solution is to relog.
There are a few monsters that do attack back an EVADED character, but they will never strike you in physical, spellcasts, or even auras.

**Comment by killerwife** [comment]
The evade fix and the crash fix are both alrdy in cmangos. This needs renewed reproduction. Best make a video on a clean cmangos.

**Comment by killerwife** [comment]
Closing this as spells have been adjusted in AI and no report about it.
