### ISSUE TITLE
Cannot start mangosd due to mysql query error

### ISSUE THREAD

**Issue by bobfajita** [cmangos/issues#1715]
**Steps to reproduce**:

1. Run InstallFullDB.sh
2. Try to start mangosd
3. The table `character_db_version` in your [CHARACTER] database indicates that this database is out of date!

  [A] You have: --> `z2719_01_characters_taxi_system_update.sql`

  [B] You need: --> `z2724_01_characters_taxi_system_format_update.sql`

4) Try to apply updates within sql/updates/characters until you eventually get to:

$ mysql -u root -p characters < mangos/sql/updates/characters/z2682_01_characters_pvpstats.sql 
Enter password: 
ERROR 1054 (42S22) at line 1: Unknown column 'required_z2679_03_characters_guild_member' in 'character_db_version'

**Client version**: 
1.12.1
**Commit hash**: 
commit a8823b892a1ac4b9d8fcea501ded3db5c74d2623

**Database version**: 
7e86ef101e3a5a1c176f394b8f055810b5595fef

**Operating system**: 
ubuntu 16.04 lts

**Comment by SilvioDoMine** [comment]
On InstallFullDB.config you should put the source directory in order to install the server sql update files. Such as https://github.com/cmangos/mangos-classic/tree/master/sql

**Comment by bobfajita** [comment]
Thanks for the reply.  I do have that set already.

## Define the path to your core's folder (This is optional)
##   If set the core updates located under sql/updates from this mangos-directory will be added automatically
CORE_PATH="/home/mangos/mangos/"

**Comment by Grz3s** [comment]
no ... 'characters' is not part of world database.
https://github.com/cmangos/issues/wiki/Installation-Instructions#initialize-characters-database

**Comment by bobfajita** [comment]
Thanks for the reply.  So it seems that Installfulldb.sh should not be a contributing factor to not being able to apply the characters db updates above, correct?

**Comment by Grz3s** [comment]
you missing the point...
this is not "repack' where by one click you got all prepared and ready...
CmangoS is a Core... where if set up correctly... you can start it...and should work fine with empty world (no creatures, objects etc) - 'characters Db' is part of it... and this has nothing to do with World DB.

All WorldDB .providers (classicDB, TBCTB, WotlkDB..etc....) provides you data to fill that world . with creatures, objects, quests, etc... . ACID(eventAI) and SD2(Scriptdev2) are part of it... thats why they're included. Also any core update for that world must be added "in right moment" if you know what i mean, thats why to avaoid conflicts etc.. ./installFULLDB.sh tool was created to simplify that proces....
Imagine that u have to add everything one by one.. (wotlDB has ~600 small updates already)

Remember ... this tool is 100% "World DB" and has nothing to do with Characters DB.

**Comment by bobfajita** [comment]
Thanks for the explanation.  I am not at all a mangos or mysql expert (obviously).  Do you have have suggestions how to resolve the initial issue?

Thanks

**Comment by bobfajita** [comment]
I am not sure what in the hour or two I did messing around fixed it, but I have the z2724_01_characters_taxi_system_format_update.sql update applied and server running.

**Comment by Grz3s** [comment]
thats the newest one...so you won that battle ;)

Anyway next time...
After fresh core compile all you need to do is:
1st: add  .../sql/base/characters.sql to your fresh characters database
2nd: check what is in your `character_db_version`  (if it shows that you have newest one - then you dont need to do anything there) if not do 3rd step.
3rd: add everything newer than yours from  /sql/updates/characters /...
**must be** from oldest to newest !!!
So z2682_01_characters_pvpstats.sql  first then ... z2686_01_characters_reset_talents.sql ...--->
and last one should be z2724_01_characters_taxi_system_format_update.sql

And now ... imagine that to update "world db" you will be adding one by one ...like above... (example 600 files) ... im sure you wouldnt be happy  :D ... thats why db providers have **installFulldb.sh** tool

**Comment by jimmybrancaccio** [comment]
Closing this as resolved. If you should have any further issues which are not bugs in the core or database, please don't hesitate to reach out to us on Discord (https://discord.gg/Dgzerzb) if you need further assistance.

Else if you've got a bug to report, go ahead and submit it here on GitHub. Thanks!
