### ISSUE TITLE
[TBC] Priest Mass Dispel removes _some_ beneficial buffs from friendly/self

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#1716]
**Current behavior**: 
Priest Mass Dispel removes _some_ beneficial buffs from friendly/self. Cast Mass dispel on multiple unfriendly NPC and it correctly removed their beneficial buffs, however Prayer of fortitude was removed from myself but Prayer of Shadow protection remained.

**Expected behavior**: 
remove unfriendly npc/player beneficial buffs and remove harmful ONLY from friendly and me.

**Steps to reproduce**:

1. Gather mobs and/or party members with buffs
2. as priest cast mass dispel
3.  observe buffs removed and remaining.

**Client version**: 
1.12.1
**Commit hash**: 
6d22c093d0028e647a215bb6bc8abae57e267049
**Database version**: 
9f2211c3d6725659369bcf70acad96f6ff92de9d
**Operating system**: 
Winows 8.1

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by SilvioDoMine** [comment]
Related to issue #1711

**Comment by SilvioDoMine** [comment]
Works perfectly as intended.

**Comment by SilvioDoMine** [comment]
@lduguid Works perfectly as intended.

**Comment by lduguid** [comment]
#249
