### ISSUE TITLE
[TBC] Ethereum Prison Does Not Give You Reputation

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1717]
**Current behavior**: 
If you open Ethereum Prison (object=184419) using key (item=29460), and if you restore friendly unit - reputation is not being given to you.
But I can see in log that spell that should give reputation was casted. If I learn spell by .learn command and try to cast it, spell give me reputation correctly.

At the scrins - 
1. - casting by npc
2. - casting by self
3. - rep was modify only by casting self.
![image](https://user-images.githubusercontent.com/39913306/46562452-cb243500-c904-11e8-8c6a-a0fac2b0b25d.png)
![image](https://user-images.githubusercontent.com/39913306/46562494-f73fb600-c904-11e8-910b-6924e704245b.png)
![image](https://user-images.githubusercontent.com/39913306/46562552-3d951500-c905-11e8-8fb1-0447b61b4ab9.png)

**Expected behavior**: 
Reputation should be given

**Steps to reproduce**:

1. use .additem 29460 50
2. use .tele Nether
3. fly to Ethereum Prison (object=184419)
4. start open prisons and see your reputation if npc will be friendly

5. try .learn 39331
6. use 39331 - it will work

**Client version**: 
2.4.3
**Commit hash**: 
from 04.10.18
**Database version**: 
from 04.10.18
**Operating system**: 
win 64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
Add Combat AI for hostile Versions!

**Comment by al3xc1985** [comment]
tested... and if you restore a friend it gives you reputation +500
@killerwife  can be closed
