### ISSUE TITLE
MySQL 8.0.2+ new keyword RANK

### ISSUE THREAD

**Issue by dsx75** [cmangos/issues#1719]
MySQL server 8.0.2 introduced a new reserved keyword RANK, which is now causing some issues with columns named rank (could be fixed by enclosing column names with ` ).

For example (tbc-db):
\sql\base\dbc\cmangos_fixes\Spell.sql

or in Server.log

ERROR:SQL: SELECT guildid,rank FROM guild_member WHERE guid = '1'

ERROR:SQL: SELECT spell_id, prev_spell, first_spell, rank, req_spell FROM spell_chain

ERROR:SQL: SELECT arena_team.arenateamid,name,captainguid,type,BackgroundColor,EmblemStyle,EmblemColor,BorderStyle,BorderColor, rating,games_week,wins_week,games_season,wins_season,rank FROM arena_team LEFT JOIN arena_team_stats ON arena_team.arenateamid = arena_team_stats.arenateamid ORDER BY arena_team.arenateamid ASC

It's no big deal, everything's working fine on older versions of MySQL server, just wanted to let you guys know, in case you didn't know already :)

**Comment by dsx75** [comment]
I've just noticed that this is actually mentioned in the installation instructions.

My bad, sorry. Delete this issue, please.

**Comment by Pooch11** [comment]
I didn't notice this in the installation instructions and made a fix for TBC version [here](https://github.com/cmangos/mangos-tbc/pull/250)
I think it would be pretty convenient for new people interested in the project

**Comment by Lillecarl** [comment]
@cyberium this is the MySQL weirdness I'm talking about
