### ISSUE TITLE
[TBC] PlayerBot - unknown column combat_order

### ISSUE THREAD

**Issue by dsx75** [cmangos/issues#1721]
**Current behavior**: 

**TBC** clean fresh installation, compiled with the **PlayerBot** support.

It seems that there is a conflict between database structure and the code.

The code [mangos-tbc] \src\game\PlayerBot\Base\PlayerbotAI.cpp refers (7 times) to the column **column_order** of the table **playerbot_saved_data** in the database **tbccharacters**.

The database structure [mangos-tbc] \sql\base\characters.sql doesn't contain such column though, only similar columns bot_primary_order and bot_secondary_order

**Expected behavior**: 

The source code should be consistent with the database structure (and vice versa).

**Steps to reproduce**:

1. Install the TBC version of the server (compile with the PlayerBots enabled)
2. Create 2 level 1 characters on the same account
3. Log into one of the character and add the other one as a bot
4. Assign a combat order to the bot
5. Do some combat
6. Check the Server.log for the errors (ERROR:SQL ERROR: Unknown column 'combat_order' in 'field list')

**Client version**: 
2.4.3 (8606)

**Commit hash**: 
6d22c093d0028e647a215bb6bc8abae57e267049

**Database version**: 
9f2211c3d6725659369bcf70acad96f6ff92de9d

The characters database up to the latest update s2376_01_characters_taxi_system_format_update.sql

**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by dsx75** [comment]
"Fixed" temporarily by manually adding the missing column:

`ALTER TABLE `playerbot_saved_data`
	ADD COLUMN `combat_order` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' AFTER `guid`;`

**Comment by cala** [comment]
Fixed. Thank you for reporting.
The fix also applies to WotLK core but it will have to wait for tomorrow.
