### ISSUE TITLE
Crash using postgresql during startup

### ISSUE THREAD

**Issue by Lillecarl** [cmangos/issues#1722]
If there are null values in column text in tables questgiver_greeting or trainer_greeting cmangos will crash. If you start it with PostgreSQL as a backend, tbc-db converted using pgloader.

I suggest we alter these tables so they can't hold null, but empty string instead, thoughts?

**Comment by cyberium** [comment]
I suggest not supporting PostgreSQL instead?

**Comment by Lillecarl** [comment]
Considering the psql wire protocol is being used for some really cool databases these days (see cockroach for example) I don't agree, but it's definitely a low priority issue. Why do we allow these tables to be null though? 

A personal opinion is that postgresql these days is way more attractive then MySQL considering all different MySQL versions (oracle, Mariadb 5, mariadb 10 which we're only part compatible with).
