### ISSUE TITLE
[Wiki] Installation instructions - missing info about playerbot.conf

### ISSUE THREAD

**Issue by dsx75** [cmangos/issues#1723]
1. The Wiki page **Installation instruction** in section **Install CMaNGOS binary files**

https://github.com/cmangos/issues/wiki/Installation-Instructions#install-cmangos-binary-files

should probably include also info about copying 

`C:\Mangos\mangos\src\game\PlayerBot\playerbot.conf.dist.in`

to

`C:\Mangos\run\playerbot.info`

(if PlayerBot functionality was enabled during the compilation).

2. And the section **(OPTIONAL) Update *.conf files**

https://github.com/cmangos/issues/wiki/Installation-Instructions#optional-update-conf-files

should probably mention the playerbot.conf file as well.

**Comment by berserkingyadis** [comment]
Im sure you can just edit that in
