### ISSUE TITLE
[TBC] Paladin: Crusader Strike Should Refresh Judgement Aura Duration From Other Paladins

### ISSUE THREAD

**Issue by ungluck** [cmangos/issues#1724]
Spell: 35395
Link from forum 2007 - description of this ability.
http://www.clanyawa.com/viewtopic.php?f=18&t=3363

Crusader Strike deals 110% of weapon damage(after 2.3.2). It is on a 6 second cooldown (roughly 10 PPM if used every time it's available). Its other, less well-known property is that it refreshes the duration of all Judgements on the target, **not just those cast by the Paladin himself**, making it ideal when grouped with another Paladin who can Judge Wisdom or Light (or even both, if you have enough Paladins)

![image](https://user-images.githubusercontent.com/40755598/46663286-613ab280-cbc6-11e8-88ab-e70eb85e1ea8.png)

**Current behavior**: 
Crusader strike refreshes Judgments, casted by himself. 

**Expected behavior**: 
Crusader strike should refresh Judgement aura duration from all paladins.

**Steps to reproduce**:

1. Play two paladins from two clients at the same time
2. Cast Judgement on target
3. Try to refresh Judgement duration from paladin B by using Crusader strike of Paladin A.

**Client version**: 
2.4.3
**Commit hash**: 
latest
**Database version**: 
~from 04 October
**Operating system**: 
win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by al3xc1985** [comment]
can be closed....working perfect @killerwife
