### ISSUE TITLE
[TBC] Paladin: Benediction talent should reduce mana cost of Judgement

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1725]
**Current behavior**: 
Benediction talent is not reduce mana cost of Judgement, only Seals
![image](https://user-images.githubusercontent.com/39913306/46695780-1eee9100-cc19-11e8-984d-5c72ff5fc3f1.png)

Without talent
![image](https://user-images.githubusercontent.com/39913306/46695849-4f362f80-cc19-11e8-8bc8-a49177275224.png)

With talent
![image](https://user-images.githubusercontent.com/39913306/46695873-6248ff80-cc19-11e8-9c6a-b750246a253b.png)

With or withount talent - cost is the same 147 mana

**Expected behavior**: 
Should reduce cost by 15% (5 points)

**Steps to reproduce**:

1. Learn Benediction

**Client version**: 
2.4.3
**Commit hash**: 
from 08.10.2018
**Database version**: 
from 04.10.2018
**Operating system**: 
Win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Please try the following SQL update.
UPDATE spell_affect SET SpellFamilyMask=0x0000000000800000 WHERE entry IN(20101);

**Comment by datchannin** [comment]
It works after using
_UPDATE spell_affect SET SpellFamilyMask=0x0000000000800000 WHERE entry IN(20101);_
![image](https://user-images.githubusercontent.com/39913306/46698916-f9658580-cc20-11e8-920b-f209ea0026b8.png)
Thanks

**Comment by killerwife** [comment]
Will commit it to the repo.
