### ISSUE TITLE
[TBC] Paladin: Seal of the Crusader Should Make Each Hit Deal Less Damage

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1726]
**Current behavior**: 
Now Seal of the Crusader gives 474 melee attack power
Now Seal of the Crusader gives 40% attack speed

But it also should reduce melee damage. 
From wow.gamepedia.com/Seal_of_the_Crusader:
Seal of the Crusader is NOT a good seal for DPS or tanking paladins. Although it increases your attack speed, it makes each hit deals less damage. So its real benefit in damage output is the additional attack power it provided.

![image](https://user-images.githubusercontent.com/39913306/46699221-c8398500-cc21-11e8-94d7-797a6f4084f8.png)

So it should increase attack speed by 40% and reduce melee damage by 40% -> profit should be only as 
melee attack power. But now it gives double profit - melee attack power and attack speed.

**Expected behavior**: 
should reduce melee damage (by 40%?)

Client version:
2.4.3
Commit hash:
from 08.10.2018
Database version:
from 04.10.2018
Operating system:
Win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by norcimoix** [comment]
I just checked cmangos/mangos-classic@95e49313 and the same seems to apply there. I suspect it's also true for the wotlk branch.

**Comment by Warlockbugs** [comment]
Fixed in:
https://github.com/cmangos/mangos-classic/commit/1f8ed44d1deae55560ac2277e5b1dae0154ec942
https://github.com/cmangos/mangos-tbc/commit/6c2ca55e5bdb8bf7faea1b4a126e7efac9de2744

**Comment by norcimoix** [comment]
@Warlockbugs I think your patch reduces the damage by too much. If you increase by 40% (multiply by 1.4) and then reduce by 40%  (multiply by 0.6) then you actually reduce the DPS by 16% instead of leaving it untouched (since x*1.4*0.6 = x*0.84).
