### ISSUE TITLE
[TBC] Paladin: Benediction talent, tested again after fix

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1727]
**Current behavior**: 
After update spell as:
_UPDATE spell_affect SET SpellFamilyMask=0x0000000000800000 WHERE entry IN(20101);_
in https://github.com/cmangos/issues/issues/1725
Talent reduces only Judgement, without Seals. 

**Expected behavior**: 
Should reduce mana cost of Judgement and Seals together

**Comment by killerwife** [comment]
UPDATE spell_affect SET SpellFamilyMask=0x000000000A800200 WHERE entry IN(20101);
Tested myself. Adding to tbc db.
