### ISSUE TITLE
[TBC] Reconnecting via Grace Period During Taxi Flight Causes Flight Movement Flag to Persist on a Character

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1728]
**Current behavior**: 
Strange issue - run wow in window mode, after - fly using taxi. Minimize window, when remind 1 minute before flying will be finished. Close window with game. After, log in one more time. And wait finishing of your flying. After it finish, you can fly without mount, only by press "space" key.

This is video, how do it. You can scroll time of flying, but look how to close game and start it again.
https://radikal.ru/video/BQ7FST24h7V

Character on the video is without Game Master access.

**Expected behavior**: 
Should not fly without mount and without GM access.

**Steps to reproduce**:

1. run wow in window mode
2. open taxi point in Morgan's Vigil
3. open taxi point in Thorium Point
4. start flying from Morgan's Vigil to Thorium Point
5. minimize window when 60-50 seconds before finish
6. close window
7. log in again and wait for finishing of flying
8. press space key after landing.

**Client version**: 
2.4.3
**Commit hash**: 
latest
**Database version**: 
~04 october
**Operating system**: 
win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
Caused by new grace period feature. Exact cause is unknown, but it has something to do with the way we sync splines (client thinks that flight flag is a permanent one instead temporary spline).

**Comment by SilvioDoMine** [comment]
@cyberium

**Comment by datchannin** [comment]
Found the same issue if player was summoned during taxi. Player can fly without mount after summon. (the latest release)

**Comment by Warlockbugs** [comment]
Fixed. More details in commit description.

If you notice any visual glitches with players who login mid-air (for example, relogging on a flying mount), let us know.
