### ISSUE TITLE
[Classic] Maraudon: Entrance to "Earth Song Falls" not working

### ISSUE THREAD

**Issue by a20eac1d** [cmangos/issues#1729]
**Current behavior**: 

The teleporter at (X: -1381 / Y: 2918 / Z: 74 / M: 1) does nothing. You can activate it, but nothing happens.

**Expected behavior**: 

Gain entry to Earth Song Falls.

**Steps to reproduce**:

1. Teleport to coordinates
2. Rightclick "Doodad_CentaurTeleporter01"
3. Nothing happens.

**Client version**: 

1.12.2

**Commit hash**: 

7036041e4836234b13b17a1548e8765d629b2ceb

**Database version**: 

23c2306dde3fe9740d1da9aaf4d066919e91b70b

**Operating system**: 

Windows 8.1 64-bit

**Comment by cala** [comment]
I cannot reproduce this.
You need to use item 17191 to activate the portal, not click on the GO itself (it is not supposed to be selectable unless you are on GM mode).

**Comment by a20eac1d** [comment]
You are right, my mistake. I was stupid.
