### ISSUE TITLE
[CLASSIC] Mob Portraits Show an Incorrect Health Value

### ISSUE THREAD

**Issue by a20eac1d** [cmangos/issues#1730]
**Current behavior**:
Sometimes, mobs portraits show an incorrect health value. This bug is only visual, the damage is still being calculated correctly. Addons are NOT the cause because none were installed at the time of recording (see below).

**Expected behavior**: 
Show the correct hp value

**Steps to reproduce**:
Unknown. See video: https://gfycat.com/SlowThirstyAmericanalligator

**Client version**: 
1.12.2

**Commit hash**: 
7036041e4836234b13b17a1548e8765d629b2ceb

**Database version**: 
23c2306dde3fe9740d1da9aaf4d066919e91b70b

**Operating system**: 
Windows 8.1 64-bit

**Comment by cala** [comment]
I confirm this one.

**Comment by killerwife** [comment]
Give me reproducible cases. I know the GM mode one.

**Comment by a20eac1d** [comment]
@killerwife I honestly have no clue how to reproduce it, but it happens all the time for me. With many types of creatures in many locations. I think it might be sending the percentage value of health instead of the absolute value?

So instead of sending:
I have 3847 of 5000 HP

It sends:
I have 76 / 5000 HP.

Because 3847 of 5000 is ~76%

**Comment by killerwife** [comment]
Yes, but you are not supposed to see values of mobs, unless in GM mode. Right now we are missing a broadcast of HP values when leaving GM mode (.gm off), other than that there seem to be cases, which I do not know how to reproduce.

**Comment by bdebaere** [comment]
So far I was able to reproduce it 100% of the time with Starving Mountain Lion.
.go creature Starving Mountain Lion

**Comment by a20eac1d** [comment]
@bdebaere It has nothing to do with specific mobs or types.

@killerwife I don't know how to help you, but in the coming days I will read the client's memory to see if the client ACTUALLY thinks that the mob has a low hp value or if the UI is rendering it the wrong way.

**Comment by killerwife** [comment]
Closing, as fog of war has been adjusted numerous times.
