### ISSUE TITLE
[TBC] Combat disappear while pvp if you don't attack for several seconds

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1731]
**Current behavior**: 
I'm not sure if it is a bug. But if you in pvp-combat and stop combat by pressing 'esc' - combat will disappear after several sec.

So if you are rogue, you can use stun for several seconds, and combat will fade faster then stun from your enemy. And you can use invisible while he is still in stun.

First video - rogue used stun, and after - invisible befire stun was finished.
https://radikal.ru/video/kLD64HF6Oxn

Second video - combat off after 4 seconds and rogue was stayed near enemy
https://radikal.ru/video/hA6i8AMdBwq

**Client version**: 
2.4.3
**Commit hash**: 
latest
**Database version**: 
~04-06 october
**Operating system**: 
win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
This is indeed not an issue, at least not in the cases you are describing.
