### ISSUE TITLE
[TBC] Undercity Guardian's Disease Cloud Hits Neutral Reputation Horde Players

### ISSUE THREAD

**Issue by Etherstream** [cmangos/issues#1733]
**Current behavior**: 
Undercity Guardian's Disease Cloud hits Horde players when at neutral reputation with Undercity. At friendly reputation and above this doesn't occur.

**Expected behavior**: 
I'm not 100% sure, but if I remember correctly, this shouldn't happen even at neutral reputation. Disease Cloud should only hit hostile players.

**Steps to reproduce**:
Stand near Undercity Guardian in Undercity with a Horde character that's neutral with Undercity.

**Client version**: 
2.4.3

**Commit hash**: 
aebe3cda118be49523c90dcf42f4a16bad9cc23c

**Database version**: 
961e84885c3b10eddd5fc5e3fa00e55c04a9b7a8

**Operating system**: 
Windows 10 Pro 64-bit

**Comment by AnonXS** [comment]
` Undercity Guardian 5624 - guard_undercity ` maybe do changes to the spell_template

**Comment by AnonXS** [comment]
s.12187 Disease Cloud - can not confirm the issue.

**Comment by Warlockbugs** [comment]
Its related to ineraction between faction templates and pvp flags in pre-WotLK versions of the game. Some NPCs see such players as neutral attackable from their PoV while player sees them as friendly helpful.

![Screenshot](https://i.imgur.com/iQ5tVyM.png)

**Comment by esno** [comment]
![Peek 2019-10-02 23-46](https://user-images.githubusercontent.com/16262833/66084374-c8d3d580-e56e-11e9-9c4b-664e2956a5a8.gif)
core: https://github.com/cmangos/mangos-tbc/commit/efa81ed55042c29d3c9b5b415b77fd85bf5bc604
database: https://github.com/cmangos/tbc-db/commit/69315e9cdb21632bb0cf0521bab6d86d09661124

> Undercity Guardian's Disease Cloud hits Gulayim for 21 Nature.
> Undercity Guardian's melee swing hits Gulayim for 675 Physical. (Crushing)

**Comment by Warlockbugs** [comment]
Should be fixed by:
https://github.com/cmangos/mangos-classic/commit/772c571c4cdba6340141c2ffb7ee2dd1c234ca12
https://github.com/cmangos/mangos-tbc/commit/b819ce0593de3156a2335c1f9bf4ecada3a899c5
https://github.com/cmangos/mangos-wotlk/commit/e39c357d60bdcd3a84fef77ae4df664624e6ce41

Those are to be improved further a bit later.
