### ISSUE TITLE
[CLASSIC][TBC] Jumping Down From Shadowfang Keep Instance Doesn't Teleport You Out of the Instance

### ISSUE THREAD

**Issue by Etherstream** [cmangos/issues#1734]
**Current behavior**: 
Nothing happens when you jump down from the wall of Shadowfang Keep to expected Silverpine Forest. You can just keep walking around the instanced Silverpine Forest.

**Expected behavior**: 
You should get teleported out of the instance when you jump off the wall of Shadowfang Keep to Silverpine Forest.

**Steps to reproduce**:

1. Get inside the instance of Shadowfang Keep
2. Make your way up to the wall where you can jump down to the Silverpine Forest
3. Jump down

**Client version**: 
2.4.3

**Commit hash**: 
aebe3cda118be49523c90dcf42f4a16bad9cc23c

**Database version**: 
961e84885c3b10eddd5fc5e3fa00e55c04a9b7a8

**Operating system**: 
Windows 10 Pro 64-bit

**Comment by cala** [comment]
Thank you for this report. This is now fixed in https://github.com/cmangos/classic-db/commit/ee3fde8995159a4b207706082ecb23abcbc65c3b
