### ISSUE TITLE
[TBC] Crash core while try to login-logout quickly while on ship moving

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1735]
**Current behavior**: 
Checked on latest release
![image](https://user-images.githubusercontent.com/39913306/47271910-74fef500-d586-11e8-8987-f29172190221.png)

While you are swimming on the ship from/to Booty Bay and use alt+f4 for log out + login again - server will crash.
Check my video:
https://radikal.ru/video/oYxNxeqnusl

**Expected behavior**: 
Should not crash

**Steps to reproduce**:

1. Go to ship
2. Wait for start moving
3. Use alt+f4 for logout
4. Log in and check console

**Client version**: 
2.4.3
**Commit hash**: 
latest
**Database version**: 
beginning of october
**Operating system**: 
win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Lankytim** [comment]
I was able to reproduce the crash.

Client version:
2.4.3
Commit hash:
6d22c093d0028e647a215bb6bc8abae57e267049
Database version:
1.7.0 commit 9f2211c3d6725659369bcf70acad96f6ff92de9d
Operating system:
Windows 7 64bit client; Linux Debian 9 server

**Comment by datchannin** [comment]
Seems this crash occurs not only while on ship. I've seen the same after disconnection while PVP, but I can't reproduce it again for create video. May be it has too complicate conditions. I can't understand dependence for reproduction.

**Comment by CabrasDaPeste** [comment]
Confirmed.

**Comment by SilvioDoMine** [comment]
@datchannin can you still confirm if this issue happen on the last commit?

**Comment by Lankytim** [comment]
I re-tested just now with mangos-tbc commit faec3d82b3febbe3485b7bdfae8ab140caa881c6.  Seems to be fixed for me.

**Comment by datchannin** [comment]
For me it was fixed with commit 7f9a0b560f7df193094711d1d2b0f50de8e005c1 (Resolve teleports before reconnect).
I still can not reproduce crash after disconnect while PVP, but may be it was fixed too.

**Comment by datchannin** [comment]
About crash while PVP: It was happen after my internet connection has been disappeared. May be it was problem?
