### ISSUE TITLE
[CLASSIC] Floating NPCs in Orgrimmar

### ISSUE THREAD

**Issue by bdebaere** [cmangos/issues#1738]
**Current behavior**: 
Two NPCs are floating for me in Orgrimmar. All other NPCs are ok.
https://www.youtube.com/watch?v=_0hrM2ra4XI
https://www.youtube.com/watch?v=GAeDe1RrvqY
**Expected behavior**: 
Not floating.
**Steps to reproduce**:

1. .go creature "Bounty Hunter Kolark"
2. .go 2029 -4723 26 1

**Client version**: 
1.12.1
**Commit hash**: 
DB 187c2f6f88c3aa8c73b33cdf7a89075b2cf216fa
Code 6f7d9f71d57cc489d34a9cc1a66b4a7383e61f29
**Database version**: 
required_z2727_01_mangos_event_ai
**Operating system**: 
Win10

**Comment by AnonXS** [comment]
Cant confirm in tbc which has same path. But his NpcFlags is 268435458 in classic-db.

**Comment by bdebaere** [comment]
@AnonXS 268435458 is QuestGiver + Guard. I updated the value to 2 like in TBC with sadly the same result.

**Comment by Grz3s** [comment]
i think its a mmap issue ... u can check 
`UPDATE creature_template SET ExtraFlags = ExtraFlags | 16384 WHERE entry IN (14182);`
this is not a fix (it will make him go through walls etc - if aggroed) ... but will show you where isuee lays.

**Comment by bdebaere** [comment]
@Grz3s Updating that to a disable works. So this points to a mmap issue. But why? I've used the extractors...

**Comment by AnonXS** [comment]
predefined extractor settings are not perfect

**Comment by bdebaere** [comment]
@AnonXS I never saw any options regarding ExtractResources.sh? What settings do I have to use and how can I set them?

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/blob/b4dcb0f4782babf0147f764a77e533eb375bb2fc/contrib/mmap/src/MapBuilder.cpp#L383

**Comment by cala** [comment]
Can no longer reproduce as off today. Z position was recently improved for spline movement and this probably fixed this issue.
