### ISSUE TITLE
[WOTLK] Elemental Focus' Clearcasting Charges Aren't Consumed When Using Damaging Spells

### ISSUE THREAD

**Issue by kartoffelsup** [cmangos/issues#1739]
**Current behavior**: 
When having chosen the Elemental Focus (id: 16164) Talent in the Elemental Tree as a Shaman, one will enter a Clearcasting (id: 16246) state with two charges after a landing a critical hit with a damaging spell which will reduce the mana cost of the next two damaging or healing spells by 40%.

The charges are consumed when casting a healing spell (i.e. Healing Wave), but are not consumed when casting a damaging spell (i.e. Lightning Bolt, the mana cost reduction is applied though).

I've narrowed it down to this [line](https://github.com/cmangos/mangos-wotlk/blob/ecf7799753ec864f1f4418e6e715c635ef5addc9/src/game/Spells/UnitAuraProcHandler.cpp#L596): 
`if (useCharges && execData.procExtra != PROC_EX_CAST_END && spellProcEvent->procEx == PROC_EX_NONE` in `src/game/Spells/UnitAuraProcHandler.cpp` 
But do not really know what is supposed to happen there.

**Expected behavior**: 
The charges of Clearcasting are consumed for both damaging and healing spells.

**Steps to reproduce**:

1. Create a shaman
2. .level 79
3. Spec into Elemental until Elemental Focus can be learned
4. Attack a creature with Lightning Bolt until a critical hit occurs and Clearcasting procs
5. Fire many Lightning Bolts and see that the Clearcasting charges are not consumed

**Client version**: 3.3.5 (12340)

**Commit hash**:  ecf7799753ec864f1f4418e6e715c635ef5addc9

**Database version**:  WoTLKDB v1.1 'The Warsong' for CMaNGOS-WOTLK 13965, required_13982_01_mangos_event_ai

**Operating system**: Manjaro Linux x64 wine-3.19 staging

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Resolved on spellmod rework.
