### ISSUE TITLE
DK - Deathgrip

### ISSUE THREAD

**Issue by tarwyn** [cmangos/issues#174]
http://www.hotwow.com/spell-53276.html

Neither the Pulleffect, nor the Fixate effect seem to work.

**Comment by Shaedia** [comment]
Still not working (database PSMDB_WOTLK installed in december 2014).
Spell ID 49576 (DK lvl 60)

**Comment by jimmybrancaccio** [comment]
Would like to get this tested again with latest code please.

**Comment by al3xc1985** [comment]
U just made Arthas Happy on any cmangos wotlk server, that his servants are now, Scorpion(Mortal Kombat) image :P
