### ISSUE TITLE
[WOTLK] Buff charges are not updated in the client

### ISSUE THREAD

**Issue by kartoffelsup** [cmangos/issues#1740]
**Current behavior**: 
Buffs with charges are not correctly displayed/updated in the client. For example, the Shaman's Water Shield has 3 charges. If you get hit by an opponent, a charge is removed and you restore a specific amount of mana. 

However, in the client, the Water Shield charges still show 3 - if you log out and back in it will show 2.

**Expected behavior**: 
Buff charges are updated in / propagated to the client.

**Steps to reproduce**:

1. Create a Shaman
2. Learn Water Shield
3. Get hit and see that you gained mana from the Water Shield charge
4. Client still displays all charges as available

**Client version**: 3.3.5 (12340)

**Commit hash**:  ecf7799753ec864f1f4418e6e715c635ef5addc9

**Database version**:  WoTLKDB v1.1 'The Warsong' for CMaNGOS-WOTLK 13965, required_13982_01_mangos_event_ai

**Operating system**: Manjaro Linux x64 wine-3.19 staging

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by alanman** [comment]
I can confirm this also happens with Lightning Shield.

**Comment by killerwife** [comment]
Tested, works now as intended.
