### ISSUE TITLE
[WOTLK] Improved Revenge Makes Revenge Hit Every Target Instead of Just 1 Additional One

### ISSUE THREAD

**Issue by kartoffelsup** [cmangos/issues#1741]
**Current behavior**: 
When [Improved Revenge](https://wow.gamepedia.com/Improved_Revenge_(warrior_talent)) has been talented, Warriors will hit every target in front of them with Revenge instead of just 2.

**Expected behavior**: 
When [Improved Revenge](https://wow.gamepedia.com/Improved_Revenge_(warrior_talent))  has been talented, Warriors hit their target and one additional target with Revenge.

**Steps to reproduce**:

1. Create a Warrior
2. Learn Defensive Stance
3. Learn Revenge
4. Talent into [Improved Revenge](https://wow.gamepedia.com/Improved_Revenge_(warrior_talent)) 
5. Find 3+ enemies and use revenge on them
6. Notice how you hit all of them

**Client version**: 3.3.5 (12340)

**Commit hash**:  ecf7799753ec864f1f4418e6e715c635ef5addc9

**Database version**:  WoTLKDB v1.1 'The Warsong' for CMaNGOS-WOTLK 13965, required_13982_01_mangos_event_ai

**Operating system**: Manjaro Linux x64 wine-3.19 staging

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Tested, works as intended.
