### ISSUE TITLE
[TBC] Crusader Aura Buffs Run Speed After Landing Off Gryphon

### ISSUE THREAD

**Issue by Lankytim** [cmangos/issues#1742]
**Current behavior**:
Paladin gains a buff to running speed after landing if he casts Crusader Aura while in flight on a transport.

**Expected behavior**:
Run speed upon landing should be like normal.

**Steps to reproduce**:

1. As paladin, activate Crusader Aura
2. Take a taxi flight
3. While in flight, dismiss Crusader Aura with right-click
4. While in flight, re-activate Crusader Aura
5. Upon landing, the run speed is faster

**Client version**: 2.4.3

**Commit hash**: mangos-tbc faec3d82b3febbe3485b7bdfae8ab140caa881c6

**Database version**: TBC-DB 641d4bceaed42694cd0ec1403843475b4294c827

**Operating system**: Win 7 client, Debian Linux 9 server

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by al3xc1985** [comment]
confirm

**Comment by killerwife** [comment]
Will be fixed in next export.
