### ISSUE TITLE
[WotLK] 2 invalid ACID Spells?

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#1743]
Using QSW 3.3.5 Application

Spell 30998 not in DBC. Did find Spell 30986
`('1769502','17695','1','0','50','6','1000','1000','0','0','0','0','11','30998','0','32','0','0','0','0','0','0','0','0','Shattered` Hand Assassin - Cast Cheap Shot `OOC'),`

Spell 36626 not in DBC. No luck finding spell for spawning creature 21335
`('2077502','20775','0','0','100','1025','3000','9000','10000','15000','0','0','11','36626','4','0','0','0','0','0','0','0','0','0','Markaru` - Cast Summon Mark''aru `Tentacle'),`

**Comment by AnonXS** [comment]
These just were not ported from tbc yet. they are missing "serverside" spells.

**Comment by Rog360** [comment]
Ok, Thanks AnonXS... :)

**Comment by Grz3s** [comment]
they will be added soon* ;)

**Comment by Rog360** [comment]
Thanks Grz3s. I'll close this one since it has been answered... ;)
