### ISSUE TITLE
[TBC] spell_bonus_data Table Adds 100% More Spell Bonus That Should Add

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1744]
**Current behavior**: 
I see that Seel of Command (paladin, spell=20424) have 100% + 29% of spell bonus. I've tryed to 
adjust spell_bonus using spell_bonus_data table and see this:

1. Spell_bonus_data = 0.29 (If > 0 Use this as new spell power coefficient.) 
![image](https://user-images.githubusercontent.com/39913306/48091968-62d6b500-e21c-11e8-9e53-69ba88921cc7.png)

2. Spell_bonus_data = 0 (If = 0 Don’t apply any spell power coefficient. (Don’t scale damage with spellpower))
![image](https://user-images.githubusercontent.com/39913306/48092014-7f72ed00-e21c-11e8-90ae-530c9f214f53.png)

3. Spell_bonus_data = -1 (If < 0 Calculate default spell power coefficient.)
![image](https://user-images.githubusercontent.com/39913306/48094463-4b4efa80-e223-11e8-9105-d4060b345446.png)

Seems 29% spell bonus is good, but this table doesn't turn off 100% of spell bonus. 
For first - 29% should be as spell bonus:
So 1.a and 1.c are good, but 1.b has 100% + 29% spell bonus. 100% is а bug?

For second - don't apply any spell coefficient.
So 2.a and 2.c are good, but 2.b has 100% more spell bonus Is it the same bug as 1.a?

For third - default spell power coefficient.
3.a, 3.b, 3.c are the same - 0 spell bonus coefficiet - seems good.

Why this table adds 100% spell bonus for f < 0 and f = 0? The same exists for other spell of paladin (Seal of Blood).

**Comment by yatzi888** [comment]
Does this mean any spell linked to the spell_bonus table has a 100% dmg increase or am I understanding this incorrectly?

**Comment by datchannin** [comment]
I don't know about "all" spells, because I can not test all from the table.
But it connected to Paladin spells. Seems paladin has some differences from other classes.

**Comment by yatzi888** [comment]
@datchannin Did you try removing the spells from the spell bonus table? I'm curious as to whether it's the table that's adding the extra 100% SP bonus

**Comment by datchannin** [comment]
@yatzi888 I didn't try remove spells. But if spells is removed from table, how can we adjust spell bonus percentage? 
Anyway, I think this issue should be re-checked on new core. Passed for 3 months after issue was reported.
As for me, I think issue affected classes that use damage from different sources, spell+physic. May be paladin and shaman.

**Comment by yatzi888** [comment]
Killerwife self-assign <3 <3 The king has arrived. I'll sit back on this one. :P

**Comment by killerwife** [comment]
Unit::MeleeDamageBonusDone this function is at fault, it ignores SP and adds it twice. I will look into it, but I need to figure out the correct approach.

**Comment by killerwife** [comment]
@yatzi888 and @datchannin how is Seal of Command/Seal of Blood supposed to interact with Attack Power?

**Comment by datchannin** [comment]
For Seal of Command (wowwikki - 2008)
![image](https://user-images.githubusercontent.com/39913306/52840403-34655180-310a-11e9-8589-66bcf14c1b0f.png)

So seems SoC doesn't interact with AP directly. But AP increases DPS, and SoC uses DPS for calculate proc damage.

**Comment by killerwife** [comment]
From that analysis, its also means that AP is being added twice as well. Please check that out.

**Comment by datchannin** [comment]
I don't have possibility now to run the latest core, but I checked on one of previous version:
iteration 1. White damage = 63, AP = 436. Proc = 43. 
iteration 2. White damage = 100, AP = 700. Proc = 70.
Seems Proc is = 70% from White Damage without using AP directy.

May be some one can check proc on the latest core?
1. Create pal
2. .level +69
3. .setskill 162 350
4. learn talent retro - Seal of Command
5. use SoC and then try autoattack unarmed - iteration 1
6. add buff AP
7. use SoC and then try autoattack unarmed - iteration 2

**Comment by killerwife** [comment]
If you mean the client display of min-max dmg, that one alrdy has AP baked into it.

**Comment by killerwife** [comment]
I believe I fixed this already.
