### ISSUE TITLE
[TBC] Hellfire quests 10129 & 10146 Mission: Gateways Murketh and Shaadraz

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1747]
**Current behavior**: 
When you use the provided item [Seaforium PU-36 Explosive Nether Modulator] on the gateways, you don't recieve the quest credit. Probably server-side spell related.

**Expected behavior**:
When you use the  [Seaforium PU-36 Explosive Nether Modulator], you should recieve the credit, in order to complete the quest.

**Steps to reproduce**:

1. Create and alliance, and level up to 60
2. .go creature 68897
3. .q add 10146
4. Speak with Wing Commander and fly
5. Use the items on the Gateways.

**Client version**: 
2.4.3
**Commit hash**: 
 e2daaea6c984f116559e4630c8e011acfbdae9fe
**Database version**: 
latest
**Operating system**: 
Debian 9

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by yatzi888** [comment]
Can confirm. I had to make the quest auto-complete to avoid confusion.

**Comment by KP580BM1** [comment]
### Try this
DELETE FROM `dbscripts_on_spell` WHERE `id`=33655;
INSERT INTO `dbscripts_on_spell` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `buddy_entry`, `search_radius`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`)
VALUES
	(33655, 1, 8, 19291, 1, 0, 19291, 100, 1, 0, 0, 0, 0, 0, 0, 0, 0, ''),
	(33655, 1, 8, 19292, 1, 0, 19292, 100, 1, 0, 0, 0, 0, 0, 0, 0, 0, ''),
	(33655, 1, 8, 19358, 1, 0, 19358, 100, 1, 0, 0, 0, 0, 0, 0, 0, 0, ''),
	(33655, 1, 8, 19359, 1, 0, 19359, 100, 1, 0, 0, 0, 0, 0, 0, 0, 0, '');

**Comment by yatzi888** [comment]
@KP580BM1 I'll try this tonight and report back. :)

**Comment by SilvioDoMine** [comment]
I can confirm that this work as intended @KP580BM1. Would be nice to any db dev push this to tbc-db and wotlk-db.

**Comment by AnonXS** [comment]
Sadly thats not the root of the issue.

**Comment by al3xc1985** [comment]
Can be closed, fixed by @grz3s long time ago @killerwife
