### ISSUE TITLE
[TBC] Hellfire Quest 9383 - An Ambicious Plan

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1749]
**Current behavior**: 
When you use the item [Sanctified Crystal] on a dying Uncontroled Voidwalker, nothing happens.

http://db.hellfire-tbc.com/?item=23417
http://db.hellfire-tbc.com/?spell=29364

**Expected behavior**:
When you use the item, should kill the Uncontroled Voidwalker, and summon an crystal object nearby his corpse, and you should loot the [Glowing Sanctified Crystal].

Probably missing core-side spell.

**Steps to reproduce**:

1. .quest add 9383
2. .go creature 59368
3. Attack the Uncontrolled Voidwalker until 15% HP
4. Use the [Sanctified Crystal]

**Client version**: 
2.4.3

**Commit hash**: 
 e2daaea6c984f116559e4630c8e011acfbdae9fe

**Database version**: 
Latest TBC-DB

**Operating system**: 
Debian 9

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
Cant reproduce

**Comment by IvanDanshin** [comment]
No target for spawn GObject in Spell.dbc
https://i.gyazo.com/bb4a15485defcfd5ac3f4a31242b30d6.png

Fix for this issue:
`UPDATE spell_template SET EffectImplicitTargetB1=38 WHERE Id=29364;`

**Comment by AnonXS** [comment]
@killerwife will probably resolve this when more spelltargeting changes get exported.

**Comment by berserkingyadis** [comment]
Were the said spelltargeting changes exported?

**Comment by killerwife** [comment]
Tested, works.
