### ISSUE TITLE
[TBC] Hellfire Quest 9545 - The Seer's Relic

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1750]
**Current behavior**: 
When you use the item [Seer's Relic] on near Sendai's corpse, nothing happens.

**Expected behavior**:
When used the item, should summon some ghosts npcs for some roleplay mini-event, and then complete the quest. Source: https://www.youtube.com/watch?v=Q5yGPTNfWsM

**Steps to reproduce**:

1. .q add 9545
2. .go creature 86002
3. Use [Seer's Relic]

**Client version**: 
2.4.3
**Commit hash**: 
 e2daaea6c984f116559e4630c8e011acfbdae9fe
**Database version**: 
TBC-DB Latest
**Operating system**: 
Debian 9

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
Could use a touchup, script plays wonky, but succeeds.

**Comment by Almightie** [comment]
Using item  23645 triggers spellId 30489.
This triggers eventId 10745 which is not defined in the 'dbscripts_on_events'.
Quick searched the tbc-db for any references to '10745' and a gossip containing 'unarmed or not!' but found no results. Is this script even implemented?

**Comment by killerwife** [comment]
Closing this since I implemented this script long time ago.
