### ISSUE TITLE
[BUG] Razormane Hunter (c. 3265)  summon more than one pet

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1751]
**Current behavior**: 
The mob Razormane Hunter summons more than one pet. Sometimes 2, sometimes 4.

![image](https://user-images.githubusercontent.com/20645369/48567145-86b48d80-e8e3-11e8-9f98-de1943dd6fdd.png)

**Expected behavior**: 
They should have only one pet.

**Steps to reproduce**:

1. .go creature 20303
2. Search for any Razormane Hunter

**Client version**: 
2.4.3
**Commit hash**: 
 e2daaea6c984f116559e4630c8e011acfbdae9fe
**Database version**: 
latest tbc-db
**Operating system**: 
debian 9

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Grz3s** [comment]
mothod not used by TBCDB but it fixes your issue..
```sql
-- Razormane Hunter 3265
Delete from `creature_ai_scripts` where creature_id = 3265;
Insert into `creature_ai_scripts` values
('326501','3265','1','0','100','0','1000','1000','0','0','0','0','56','0','0','0','0','0','0','0','0','0','0','0','Razormane Hunter - Despawn Guardians on OOC'),
('326502','3265','1','0','100','0','2000','2000','0','0','0','0','11','6479','0','0','0','0','0','0','0','0','0','0','Razormane Hunter - Cast Razormane Wolf OOC'),
('326503','3265','4','0','100','0','0','0','0','0','0','0','57','2','25','0','0','0','0','0','0','0','0','0','Razormane Hunter - Enable Hunter Mode on Aggro'),
('326504','3265','2','0','100','1024','15','0','0','0','0','0','25','0','0','0','1','-47','0','0','0','0','0','0','Razormane Hunter - Flee at 15% HP'),
('326505','3265','9','0','100','1025','5','25','2300','3900','0','0','11','6660','1','256','0','0','0','0','0','0','0','0','Razormane Hunter - Cast Shoot');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '3265';
```
