### ISSUE TITLE
[classice]unable connect to sever

### ISSUE THREAD

**Issue by the2ndface** [cmangos/issues#1752]
**Current behavior**: 
When I open wow.exe and login ,display"Disconnect from the server"，No verification account password，so I thick something wrong.
**Expected behavior**: 

**Steps to reproduce**:
I follow the installation instructions to install,and the server can be run. I can create account on mangosd window.
The configuration file is as follows：
**mangosd.conf:**
`RealmID = 1
DataDir = "../share"
LogsDir = "../log"
LoginDatabaseInfo     = "127.0.0.1;3306;mangos;mangos;classicrealmd"
WorldDatabaseInfo     = "127.0.0.1;3306;mangos;mangos;classicmangos"
CharacterDatabaseInfo = "127.0.0.1;3306;mangos;mangos;classiccharacters"
LoginDatabaseConnections = 1
WorldDatabaseConnections = 1
CharacterDatabaseConnections = 1
MaxPingTime = 30
WorldServerPort = 8085
BindIP = "127.0.0.1"
`

**the realmd.conf**
`LoginDatabaseInfo = "127.0.0.1;3306;mangos;mangos;classicrealmd"
LogsDir = "../log"
MaxPingTime = 30
RealmServerPort = 3724
BindIP = "127.0.0.1"
PidFile = ""
LogLevel = 0
LogTime = 0
LogFile = "Realmd.log"
LogTimestamp = 0
LogFileLevel = 0
LogColors = ""
UseProcessors = 0
ProcessPriority = 1
WaitAtStartupError = 0
RealmsStateUpdateDelay = 20
WrongPass.MaxCount = 0
WrongPass.BanTime = 600
WrongPass.BanType = 0
`
**and update mysql realmlist table**
server address: 154.123.*.* //hidden the last two
port :8085

**iptables**  
all accept

**Client version**: 
1.12.1  and  1.12.3
**Commit hash**: 

**Database version**: 
mysql 5.7
**Operating system**: 
server:ubuntu 16.04 64bit
client: win10 64bit

so I want to know ,is there any other config that  I shoud Configuration?

**Comment by SilvioDoMine** [comment]
@the2ndface you are having problems with configuration, and this isn't an issue with the emulator. You should seek for help in our Discord or Forum. visit: https://cmangos.net to get the links.

**Comment by jimmybrancaccio** [comment]
Hi @the2ndface! Thanks for taking the time to submit your issue. As noted by the other two, our GitHub is not for support of CMaNGOS but rather to report issues once you have it up and running. If you need assistance in getting it going please don't hesitate to join us on our Discord (
https://discord.gg/Dgzerz). We'd be happy to give you a hand in there.
