### ISSUE TITLE
[WOTLK] Raptor Captor - Cannot Capture Raptors

### ISSUE THREAD

**Issue by jimmybrancaccio** [cmangos/issues#1754]
**Current behavior**: 

When attempting to utilize the Sturdy Rope to capture raptors, it won't actually allow you to capture them. The animation shows as if you're trying to capture them, but nothing happens. I've attached a video of me attempting to capture the raptors:

https://youtu.be/0ryDeiLbcU4

**Expected behavior**: 

When using the sturdy rope it should allow you to capture the raptor. I've found this video on YouTube which depicts it working properly.

https://www.youtube.com/watch?v=0MvEE_WFcdE

**Steps to reproduce**:

1.  Get the quest Raptor Captor - https://www.wowhead.com/quest=27242/raptor-captor
2. Locate yourself some raptors, the Bloodfen Screechers should work fine.
3. Start attacking the raptor until you get the message that it "looks weak enough to capture".
4. Use the Sturdy Rope to capture it.
5. Note nothing happens.

**Client version**: 

3.3.5a

**Commit hash**: 

653dea9d892da7170afc33bf37ee6911ce8dc8b5

**Database version**: 

3aee4927d69b33aa5270b3d871d71cc727d02149

**Operating system**: 

14.04

**Comment by Grz3s** [comment]
quest 27242 was added in 4.0.3.13277
im sure you talking about.. q.11146 'Raptor Captor'
- fixed

**Comment by Grz3s** [comment]
update your db.. quest should work fine now

**Comment by jimmybrancaccio** [comment]
Oops, you're right @Grz3s! Looks like the correct Wowhead link is:

https://www.wowhead.com/quest=11146/deprecated-raptor-captor

Marking this one as resolved by cmangos/wotlk-db@ea7a4c2.
