### ISSUE TITLE
[WOTLK] Take Down Tethyr! - Cannot Use Cannons

### ISSUE THREAD

**Issue by jimmybrancaccio** [cmangos/issues#1755]
**Current behavior**: 

When you take the quest, you can see Tethyr appear, but are not able to use the cannons to shoot at him. I've attached a video to further display what is happening.

https://youtu.be/AdgP5lFMqxk

**Expected behavior**: 

Upon obtaining the quest there should be marksmen that run out to their post (this does not appear to happen, they just seem to "magically" appear. Then once Major Mills yells, "FIRE AT WILL!" you should be able to utilize the cannons to shoot at Tethyr. Here's a video I've found which seems to depict the correct behavior:

https://www.youtube.com/watch?v=9bouANygWgs

**Steps to reproduce**:

1. Obtain quest Take Down Tethyr - https://www.wowhead.com/quest=27222/take-down-tethyr
2.  Wait at the docs for Major Mills, he will eventually yell, "FIRE AT WILL!".
3.  Move to one of the cannons located around the docks and attempt to use it. You should not be able to actually use it (by right clicking on it).

**Client version**: 

3.3.5a

**Commit hash**: 

653dea9d892da7170afc33bf37ee6911ce8dc8b5

**Database version**: 

3aee4927d69b33aa5270b3d871d71cc727d02149

**Operating system**: 

Ubuntu 14.04

**Comment by stealthgun** [comment]
I have the same Issue for the TBC core.

Version & Environment

Client Version:
"2.4.3" (TBC)

Client Version: 2.4.3
CMaNGOS Repo & Commit Hash: cmangos/mangos-tbc@19d3644

Database Repo & Commit Hash: cmangos/tbc-db@2791ec8

Operating System: Win 2019

**Comment by insunaa** [comment]
Just tested this on TBC core and it works flawlessly over there at least.

**Comment by jimmybrancaccio** [comment]
I've confirmed this is working in WotLK (cmangos/mangos-wotlk@1903013 & cmangos/wotlk-db@66f7605). Closing as such.
