### ISSUE TITLE
[WOTLK] Winterfall Ritual Totem - Cannot Talk to Kernda

### ISSUE THREAD

**Issue by jimmybrancaccio** [cmangos/issues#1756]
**Current behavior**: 

After becoming Neutral with Timbermaw Hold speaking or attempting to speak to the NPC, Kernda nothing will happen. Here's a video of my attempt. Please note, I was Neutral before trying this but even tried manually adjusting my reputation with Timbermaw Hold to Friendly to see if that had any effect, it did not. I used the command:

`.modify rep 576 Friendly`

https://youtu.be/3kER8WIMEhI

**Expected behavior**: 

When you reach Neutral or above reputation with Timebermaw Hold you should be able to speak with the NPC, Kernda to complete the quest. I was unfortunately unable to find a YouTube video to depict this but the comments on the WowHead site confirms this:

https://www.wowhead.com/quest=8471/winterfall-ritual-totem

**Steps to reproduce**:

1. Obtain the quest Winterfall Ritual Totem - https://www.wowhead.com/quest=8471/winterfall-ritual-totem
2. Fight some furblogs - a good place to do this is at Felpaw Village. Do this until you get a neutral repuation with Timbermaw Hold. I believe there's also some necklaces you can obtain and turn in for rep points.
3. Once you're Neutral or above with Timbermaw Hold, go into the tunnels that connect Felwood and Winterspring and find Kernda. Attempt to speak with him (right click him) but note you cannot.

**Client version**: 

3.3.5a

**Commit hash**: 

653dea9d892da7170afc33bf37ee6911ce8dc8b5

**Database version**: 

3aee4927d69b33aa5270b3d871d71cc727d02149

**Operating system**: 

Ubuntu 14.04

**Comment by Grz3s** [comment]
it works fine...
check if you havent got "at war" selected with them
![fefef](https://user-images.githubusercontent.com/2374069/48655277-d80c6c00-ea0c-11e8-8847-05e901c05e86.jpg)

**Comment by jimmybrancaccio** [comment]
@Grz3s Looks like you're correct. I had 'At War' checked off. I wasn't aware of option in the UI that but that seems to have done the trick. Unchecking it allows me to talk to the NPC and complete the quest. 

We can consider this one closed. Thank you for taking a look into the issue. I'm surprised no one at WowHead had left that as a comment.

![2018-11-16 22_22_05-world of warcraft](https://user-images.githubusercontent.com/405585/48656798-67a32200-e9ef-11e8-8551-8893c31a7cd5.jpg)

**Comment by Warlockbugs** [comment]
Most likely, retail server did auto-untick on "At War" flag upon gaining certain reputation level, but that's just a guess.
