### ISSUE TITLE
[TBC] Kael'thas Sunstrider/Illidan Stormrage Boss Encounters Don't Start

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1758]
**Current behavior**: Running up to Kaelthas or Illidan triggers the RP text/voice for the beginning of the fights but instead of the [Kaelthas]first mob becoming attackable after the inital RP, the encounter resets and repeats the same thing as described or [Illidan]The boss goes back to kneel stance and the encounter doesn't start.

Both mobs start as unattackable, which makes me think this is part of the problem.

**Expected behavior**: [Kaelthas]The first mob should start attacking/be attackable and the boss encounter should ultimatly play out rather than resetting before any of the adds become attackable. [Illidan]Boss should become attackable and encounter should play out.

**Steps to reproduce**:

1. Kill all the mobs and bosses in The Eye asside from Kaelthas (may not need to kill all the mobs I did this for testing purposes)
2. Run up to Kaelthas
3. Enjoy the sweet sound of Kaelthas repeating himself until you lose your mind.

Same with Illidan.

**Client version**: 2.4.3

**Commit hash**: Not sure what to put here, compiled around a month ago

**Database version**: 1.7.0

**Operating system**: Windows Server 2012 R2

Edit 1:
I did .die all the mobs up to KT/BT but I wouldn't have thought it would have any effect on the Kaelthas script.

Edit 2: 
Temp Workaround:
Did some testing on Illidan and I managed to get the fight to start by changing the Unitflag value in the creature_template to 0 rather than 768. This means that Illidan is now attackable, waiting for Akuma to finish the RP gets the boss out of the kneel stance and he then proceeds to attack the nearest player. 

Haven't looked at kaelthas yet, but I assume it won't be as clean a work around.

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by MantisLord** [comment]
Full Kael rework by Killerwife is coming soon™ so please no one spend too much time on that one.

**Comment by yatzi888** [comment]
>           Full Kael rework by Killerwife is coming soon™ so please no one spend too much time on that one.

Sounds great looking forward to it 👍

**Comment by MantisLord** [comment]
Addressed here:
https://github.com/cmangos/mangos-tbc/commit/c1424618db9f259a7c9c024ff85c8842cb5855e0
