### ISSUE TITLE
[Classic] Rot Hide Graverobber in Trisfal Glades cast Curse of Thule (-2 Spirit) on themselves

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#1760]
**Current behavior**: 
Rot Hide Graverobber in Trisfal Glades cast Curse of Thule (-2 Spirit) on themselves

**Expected behavior**: 

Should cast curse on player the NPC is attacking.

**Steps to reproduce**:

1.  Initiate combat with a Rot Hide Graverobber in Trisfal Glades 
2.  attack until they cast curse.
3. 

**Client version**: 

1.12.1

**Commit hash**: 

commit b555cd3e53020ca21cdb4d0e1783ebd8b9ce4731

**Database version**: 

commit 2c040f9b78a1c2b3395b40a28fd3ae4f1163ff8f

**Operating system**: 

Windows 8.1

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/5cbfcb4aea3d5565a8b80e25f0530bab41f27bf9
