### ISSUE TITLE
Crashes on Object.h

### ISSUE THREAD

**Issue by CabrasDaPeste** [cmangos/issues#1763]
Don't know exatcly what cause them. But here's two core dumps.

**Client version**: 
2.4.3 (8606)

**Commit hash**: 
00666387394559dcc8ba5b589a305b3dfe033fb5

**Database version**: 
370151f3e6f07cf1ce625a10b94b8a0a8410d281

**Operating system**: 
Debian 9

https://gist.github.com/CabrasDaPeste/0359f946a89e85c1c7727c9b1cea5d82
&&
https://gist.github.com/SilvioDoMine/9e9459fbc6237382fe4c31a709215c5a

**Comment by jimmybrancaccio** [comment]
Hello @CabrasDaPeste Can you provide the database commit hash as well, you may update your original posting with that information. Thank you!

**Comment by BenDol** [comment]
Looking into this stack trace it seems like there might be custom code causing this? Looks like the enums used in `Unit::isInCombat` are exceeding the value count size?

**Comment by jimmybrancaccio** [comment]
@CabrasDaPeste Are you still having any issues with this. If not may we close out the issue?

**Comment by al3xc1985** [comment]
I think this can be closed

**Comment by killerwife** [comment]
I vaguely remember fixing a similar issue to this. The issue report is too vague anyway. As a result I am closing this as "fixed".

**Comment by al3xc1985** [comment]
I will do a cleaning in issues killer. And from all my test on symetry i will land all of those i know are fixed
