### ISSUE TITLE
Blade's Edge Mountain - Quest 10714 - On Spirit's Wings - Using Rexxar's Whistle Does Nothing

### ISSUE THREAD

**Issue by CabrasDaPeste** [cmangos/issues#1764]
**Current behavior**: 
When you use the provided item Rexxar's Whistle on the desired spot, nothing happens.

**Expected behavior**: 
When the item is used, should summon two ogres, and you could watch their conversation, and then the quest would be complete.

**Steps to reproduce**:

1. .quest add 10714
2. .go creature 77756
3. Use [Rexxar's Whistle] on both mobs.

**Client version**: 
2.4.3 (8086)

**Commit hash**:
00666387394559dcc8ba5b589a305b3dfe033fb5
**Database version**: 
370151f3e6f07cf1ce625a10b94b8a0a8410d281
**Operating system**: 
Debian 9

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by MantisLord** [comment]
Should be fixed as of:
https://github.com/cmangos/mangos-tbc/commit/26f20ede207d05f559ce8cd11278d788df5d74f0
Needs confirmation

**Comment by Pastew** [comment]
I can't confirm the bug. Quest item worked for me:
![image](https://user-images.githubusercontent.com/5671416/54089917-96fae780-436e-11e9-93e7-31ed4994658d.png)

**Commit hash:** 62971e092f2c0217b5b8550c5b001370ba6d5273)

**Comment by berserkingyadis** [comment]
Can also confirm that using the whistles' AOE on both mobs completes the quest and spawns an owl.
