### ISSUE TITLE
Blade's Edge Mountain - Quest 10911 - Fire At Will!

### ISSUE THREAD

**Issue by CabrasDaPeste** [cmangos/issues#1765]
**Current behavior**: 
When you use the provided item [Naturalized Ammunition] near by the fel cannon, they transform into your pet. They follow the character, you can send they to attack, etc; Also, the spell that should destroy the warps can be used, their animation is right, but doesn't give credits to the quest.

**Expected behavior**: 
When used the provided item near the fel cannon, they shouldn't move, can their spell should destroy the warp-portal.

**Steps to reproduce**:

1. .quest add 10911
2. .go creature 75436
3. kill nearby demons
4. Use [Naturalized Ammunition] near the Fel Cannon.

**Client version**: 
2.4.3 (8606)

**Commit hash**: 
00666387394559dcc8ba5b589a305b3dfe033fb5

**Database version**: 
370151f3e6f07cf1ce625a10b94b8a0a8410d281

**Operating system**: 
Debian 9

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/145729450-917b04c7-da97-4981-9a65-ba3ba4514930.png)

![grafik](https://user-images.githubusercontent.com/19734826/145729479-a15f5ab3-66a2-424d-99e4-71126a10228a.png)

/petfollow etc cant be used on it
