### ISSUE TITLE
Pilgrim's Bounty event

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#1766]
The event shows in the active event list, yet when i go outside the gates of Stormwind & Ironforge there is no event going on.

CMaNGOS/0.18 (2018-11-18T12:38:16+01:00 - 3c76d923a21b7b1a8c4aca24065a4511508e07ff) for Linux_x64 (little-endian)
Clean install of database.

**Comment by adellaci** [comment]
Another thing i noticed was that the update submitted ([WOTLK] Food Spell Buff Patch #1570) for the buff to this event where not added to the database. When i hand entered them into the DB they function as intended.

**Comment by jimmybrancaccio** [comment]
Hello, Please resubmit this using the template provided when creating the issue. Please ensure to include all requested details. Thanks.
