### ISSUE TITLE
Expert's Training Dummy Dies Upon Attacking

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#1767]
**Current behavior**: Upon attacking Expert's Training Dummy, dummy dies with one point of damage

**Expected behavior**: Expert's Training Dummy should never die

**Steps to reproduce**:

1. Go to any of the Training Dummies in a major city
2. Attack dummy
3. 

**Client version**: WotLK 3.3.5a

**Commit hash**:  3c76d923a21b7b1a8c4aca24065a4511508e07ff

**Database version**: WoTLKDB v1.1 'The Warsong' for CMaNGOS-WOTLK 13965
                                   3c101da2de04ba2975c241f3990c2198cce42fb8

**Operating system**: Server: Ubuntu 16.04 Server AMD64   
                                   Client: Window 7

**Comment by jimmybrancaccio** [comment]
Hello,

Please include the database commit hash as well. You may edit your original post to include this information.

Thanks,

**Comment by adellaci** [comment]
@jimmybrancaccio 
Where can i get the database commit hash?

**Comment by adellaci** [comment]
Thank you @jimmybrancaccio
