### ISSUE TITLE
Server Crash While Prospecting (Jewelcraft)

### ISSUE THREAD

**Issue by CabrasDaPeste** [cmangos/issues#1769]
**Current behavior**: 
If you use Prospect on a item stack, and don't loot all items and close the bag, and then try to prospect again, the server crashes.

Its calling this assert here:
`mangosd: /home/ptr/mangos/src/game/Entities/Item.cpp:1178: void Item::SetLootState(ItemLootUpdateState): Assertion `m_lootState == ITEM_LOOT_NONE' failed.
Aborted`

**Expected behavior**: 
I don't quite remember what should happen in this case. I think should be like Enchanting, the next time you prospect will show the remaining items.

**Steps to reproduce**:

1. .learn 28895
2. .learn 31252
3. .setskill 755 300
4. .add 10620 20
5. Use the spell Prospecting on the Thorium Ore
6. Loot the Thorium Powder and close the loot window.
7. Use prospect again on the same Thorium Ore stack.
8. Reproduced.

**Client version**: 
2.4.3 (8606)

**Commit hash**: 
00666387394559dcc8ba5b589a305b3dfe033fb5

**Database version**: 
370151f3e6f07cf1ce625a10b94b8a0a8410d281

**Operating system**: 
Debian 9

**Crash Log**:
https://gist.github.com/CabrasDaPeste/a639cc05870d4ccacaeadea80a569df8

**Comment by berserkingyadis** [comment]
No crashes here, gm or no. Only thing when gm is, that the ores dont get consumed.

core commit: 637aeb57f9358e156853d42c4d7c47a3b5aac14a
db commit: 6b03cb53bbcba01919817e0a111062db18e91990

op: archlinux

**Comment by cyberium** [comment]
Should be fixed
