### ISSUE TITLE
DK - Mind Freeze + Endless Winter Talent

### ISSUE THREAD

**Issue by tarwyn** [cmangos/issues#177]
http://www.hotwow.com/spell-47528.html

With Endless Winter r2 (http://www.hotwow.com/spell-49657.html) seems to lock your runepower until a new runepower gain is achieved. This problem does not occur when used without Endless Winter, thus penalizing Frost-DKs.

**Comment by killerwife** [comment]
I cannot reproduce this issue and as such I am closing it.
