### ISSUE TITLE
Disenchant Doesn't Destroy Items, You Can Reuse Disenchant Forever

### ISSUE THREAD

**Issue by CabrasDaPeste** [cmangos/issues#1771]
**Current behavior**: 
After you used disenchant, the item isn't destroyed. You can loggout, and loggin, and disenchant them again.

**Expected behavior**: 
The item should be destroyed after you disenchant them.

**Steps to reproduce**:

1. .learn 28029
2. .setskill 333 375
3. .add 25157
4. Use Disenchant on the [Serpentlord Claymore]
5. Loot the item
6. Logoff
7. Login
8. Notice that you can use Disenchant on the [Serpentlord Claymore] once again.
9. Reproduced.

**Client version**: 
2.4.3 (8606)

**Commit hash**: 
00666387394559dcc8ba5b589a305b3dfe033fb5

**Database version**: 
370151f3e6f07cf1ce625a10b94b8a0a8410d281

**Operating system**: 
Debian 9

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by berserkingyadis** [comment]
Cant reproduce. The item disappears

commt: 637aeb57f9358e156853d42c4d7c47a3b5aac14a

**Comment by jimmybrancaccio** [comment]
Closing as Can't Reproduce.

**Comment by berserkingyadis** [comment]
Technically you CAN reproduce when you are in gm, no?

**Comment by jimmybrancaccio** [comment]
@berserkingyadis If we can reproduce the issue using different parameters lets get a new issue open with full details and steps for replication.
