### ISSUE TITLE
Pilgrim's Bounty Event

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#1773]
**Current behavior**: No event going on outside of the major citys

**Expected behavior**: Pilgrim's Bounty happen outside the major citys

https://wowwiki-archive.fandom.com/wiki/Pilgrim%27s_Bounty?oldid=2387038

**Steps to reproduce**:

1. Go outside the gate of the major citys
2. 
3. 

**Client version**: WotLK 3.3.5a

**Commit hash**: 3c76d923a21b7b1a8c4aca24065a4511508e07ff

**Database version**:  WoTLKDB v1.1 'The Warsong' for CMaNGOS-WOTLK 13965
3c101da2de04ba2975c241f3990c2198cce42fb8

**Operating system**:  Server: Ubuntu 16.04 Server AMD64
Client: Window 7

When use the command ".event list" it shows that the event is active.

**Comment by jimmybrancaccio** [comment]
Hello, please also include your database commit hash. You may go into the directory of your database - e.g., `cd /home/mangos/wotlk-db` and run:

``` bash
git rev-parse HEAD
```

**Comment by adellaci** [comment]
This i believe has been corrected. It worked this last thanks giving
