### ISSUE TITLE
Support For More Than 28 Bag Slots

### ISSUE THREAD

**Issue by Ghaster** [cmangos/issues#1777]
CMaNGOS-Classic currently only support bags with up to 28 slots. However, the 1.12.1 client does actually support 36 slot bags, just like TBC and WotLK. The issue lies in UpdateFields in the core that are not correct for CONTAINER_END. 

To fix this, CONTAINER_END needs to be changed from:
`CONTAINER_END                              = ITEM_END + 0x3A`
to:
`CONTAINER_END                              = ITEM_END + 0x4A`
and change MAX_BAG_SIZE from:
`#define MAX_BAG_SIZE 28`
to:
`#define MAX_BAG_SIZE 36`

The updated CONTAINER_END is backed up by the following sources:
[https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/328263-wow-1-12-1-5875-info-dump-thread-4.html#post2716691](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/328263-wow-1-12-1-5875-info-dump-thread-4.html#post2716691)
[https://github.com/RomanRom2/WoWCore/blob/92b7646c2bafb22ad6dca0acc9496a35561292c4/05875_1.12.1/pas/sandbox/common/UpdateFields.pas#L39](https://github.com/RomanRom2/WoWCore/blob/92b7646c2bafb22ad6dca0acc9496a35561292c4/05875_1.12.1/pas/sandbox/common/UpdateFields.pas#L39)

**Comment by jimmybrancaccio** [comment]
@Ghaster Can you submit a diff or PR on this?

**Comment by Ghaster** [comment]
Submitted👍
