### ISSUE TITLE
Imp & Voidwalker Pets Have No Armor

### ISSUE THREAD

**Issue by Zooke** [cmangos/issues#1778]
**Current behavior**: 
Imp/Voidwalker have 0 armor
**Expected behavior**: 
Imp/Voidwalker should have armor
**Steps to reproduce**:

1. Summon pet, see armor value on pet tab is 0.
2. Send pet into battle, check combat log to see pet takes full damage.
3. Values appear to be in the database so core is failing to apply them. Hunter pets work fine so possibly an error just in Warlock pet code.

**Client version**: 
1.12
**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/fb86389881943d1d862b7aea283a2b6d35eb33ab
**Database version**: 
https://github.com/cmangos/classic-db/commit/7ef3336053a5aa293bc1ad30e0d916dc838dcb7b
**Operating system**: 
Win 10 1809 LTSC

**Comment by Patrick-Barry** [comment]
I found the issue with the voidwalker's armor. In the database it's armor multiplier is set at -1 instead of 1.
The following will correct the error:
UPDATE `classicmangos`.`creature_template` SET `ArmorMultiplier` = '1' WHERE (`Entry` = '1860');

**Comment by al3xc1985** [comment]
@killerwife i remember @AnonXS or @MantisLord  adding srats to this pets

Can be closed?

**Comment by killerwife** [comment]
Yes. This was a vanilla only issue I believe.
