### ISSUE TITLE
Vultros Model is Not Scaled Correctly

### ISSUE THREAD

**Issue by Zooke** [cmangos/issues#1779]
**Current behavior**: 
Vultros too small.
**Expected behavior**: 
Vultros is big like https://www.youtube.com/watch?v=uV-b6pgQmDU
**Steps to reproduce**:

1. Spawn Vultros
2. See he is not big like the video
3. Suggested Fix
UPDATE `mangos`.`creature_template` SET `Scale`='3' WHERE `Entry`='462';

**Client version**: 
1.12
**Commit hash**: 
latest
**Database version**: 
latest
**Operating system**: 
W10LTSC

**Comment by cala** [comment]
Scales from TBC-DB/WotLK-DB are not transposable to Classic-DB as it seems 3D models in DBC were rescaled (probably in patch 2.0.1). Basically, scale=0 means "use default model scale from DBC" for Classic DB. I'll push the fix soon.
