### ISSUE TITLE
Vultros Loot is Incorrect

### ISSUE THREAD

**Issue by Zooke** [cmangos/issues#1780]
**Current behavior**: 
Vultros drops the dagger 100%
**Expected behavior**: 
Vultros drops a cape most of the time and the dagger less often.
**Steps to reproduce**:

1. Spawn Vultros
2. Kill Vultros
3. Loot Vultros
I am guessing this came from https://github.com/cmangos/classic-db/commit/eb37cbe0f660d950f7766ed2e1e253d2c8d6bd48

Suggested fix
UPDATE `mangos`.`reference_loot_template` SET `ChanceOrQuestChance`='25' WHERE `entry`='65004' and`item`='4454';
INSERT INTO `mangos`.`reference_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`, `comments`) VALUES ('65004', '5971', '55', '1', '1', '1', '0', 'Feathered Cape');

Source
https://web.archive.org/web/20060114023456/http://wow.allakhazam.com:80/db/mob.html?wmob=462

**Client version**: 
1.12
**Commit hash**: 
Latest
**Database version**: 
Latest
**Operating system**: 
Win10LTSC

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by jimmybrancaccio** [comment]
@Zooke Please ensure to provide both the commit hashes for the core and database when submitting an issue. Thanks.

**Comment by Zooke** [comment]
Will do.

What is the difference between the reference loot template and the creature loot template ?

**Comment by Zooke** [comment]
AnonXS,
Currently rare loots in this table have some 'corrected' values such as 75/25 and some values taken directly from websites at the time like 70.24/21.38.
How do you want to handle this data ? Do we round the numbers to add to 100 or use the data verbatim.
Maybe there was always a % chance that no unique loot would be dropped.

**Comment by AnonXS** [comment]
Well i set chance for unique item to 85% due to your link and your rounding logic.
```
  | Talon of Vultros | 23.38% | (47 in 201) -> 25%
  | Feathered Cape | 57.21% | (115 in 201) -> 60%
```

**Comment by Zooke** [comment]
On reflection, I have to admit that I am uncomfortable with rounding figures even though I believe it would overall be more accurate and blizzlike.
The historic drop rates used in this project have clearly been meticulously researched and collated, whether they are correct or not is debateable but I feel the weight of history bearing down on what I see as a fundamental change to the project.

**Comment by Zooke** [comment]
Fixed in https://github.com/cmangos/classic-db/commit/34a04d26807fa4b6ca7b69063b6a75d19b207c00

**Comment by jimmybrancaccio** [comment]
Awesome, thanks for the update @Zooke Closing this one out as fixed!

**Comment by cala** [comment]
Oups, forgot to close it by myself when merging @Zooke's PR. Sorry.
