### ISSUE TITLE
Server Core Crashing in Ubuntu 16.04

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#1781]
**Current behavior**: Server crashes on "2018-11-25 19:33:24 ERROR:SESSION: received not allowed opcode CMSG_LFG_GET_STATUS (0x0296)"

**Expected behavior**: Not to crash

**Steps to reproduce**:

1. Start mangosd
2. Login with character
3. After short period of playing the server crashes

**Client version**: 3.3.5a

**Commit hash**: e9dfec78da25363609d034aa8b833d58d55ae151

**Database version**: 3c101da2de04ba2975c241f3990c2198cce42fb8

**Operating system**: Server Ubuntu 16.04 Server, Client Windows 7

This just started after doing a "git pull" and compiling this afternoon (11/24/2018). Had been playing all day before this with out an issue. Did do a "InstallFullDB".

Please advise on how get get further information if need 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by CabrasDaPeste** [comment]
@jimmybrancaccio this may be linked with #1774?

**Comment by jimmybrancaccio** [comment]
This is definitely possible @CabrasDaPeste! I don't believe the issue is with the message 'CMSG_LFG_GET_STATUS' as I reported this but I believe the answer I got from devs on this was just that the Looking For Group status wasn't implemented in a way to return something valid.

You're probably going to have to enable crash dumps @adellaci to get something useful out of this. And perhaps crank up your logging levels to 3.

**Comment by adellaci** [comment]
@jimmybrancaccio 
I have been running the server with "LoadAllGridsOnMaps = "DO"" up to and including the update i did on Friday to cmangos, & wotlk-db. I have a server large enough to have the whole world live and it has worked great. That is running weeks at a time, never had a crash.

Sunday i did a git pull on cmangos, which updated, and did a git pull on wotlk-db, which had NO updates. 

When i went to run the server it said that  the "maps" where not current i needed to re-extract. I performed "./ad -f 1", "./vmaps_extractor", "./vmap_assembler Buildings vmaps", &  "./MoveMapGen8Core.sh". Copied "dbc", "Cameras", "maps", "vmaps", & "mmaps" over to the server's "share" directory.  

When i started the server and got connected the server would crash with in 5 to 10 minutes. I changed "LoadAllGridsOnMaps = "DO"" to "LoadAllGridsOnMaps = """ the server stayed up for a couple of hours before it failed.

Tonight i will change the log level to 3 and run it, with "LoadAllGridsOnMaps = "DO"". and post the results.

**Comment by adellaci** [comment]
@jimmybrancaccio 
The log hit 87247596 and i shut it down. 
I'm going to change "LoadAllGridsOnMaps = "DO""  to "LoadAllGridsOnMaps = """ and see if i can come up a reasonably log.

**Comment by madmax765** [comment]
Same story here, the only difference I am running it on windows server 2016

**Comment by adellaci** [comment]
@madmax765 
Haven't seen you in a while! I'm debating on starting the server from scratch, just in case. My log level 1 crashed upon completion of loading.

**Comment by adellaci** [comment]
@jimmybrancaccio 

Here are all the logs at level one with out LoadAllGridsOnMaps = "DO"

I will run another with out "DO"

[DBErrors.log](https://github.com/cmangos/issues/files/2617972/DBErrors.log)
[EventAIErrors.log](https://github.com/cmangos/issues/files/2617973/EventAIErrors.log)
[Realmd_2018-11-26_20-30-29.log](https://github.com/cmangos/issues/files/2617975/Realmd_2018-11-26_20-30-29.log)
[Server_2018-11-26_20-30-49.log](https://github.com/cmangos/issues/files/2617976/Server_2018-11-26_20-30-49.log)

**Comment by adellaci** [comment]
@jimmybrancaccio 
I am running without "DO" and it server is still up, but i have to it the hay. I will leave the server up to see if it crashes.

**Comment by jimmybrancaccio** [comment]
@adellaci Thank you very much for your follow ups. Looking forward to seeing what else you come up with.

**Comment by jimmybrancaccio** [comment]
@brianmask We'll likely need a stack trace of the crash. I recommend reviewing my notes in #1774 on how to get that going. Thanks!

**Comment by jimmybrancaccio** [comment]
Alright, I'm getting more crashes now, seemingly unrelated to #1774. mangosd won't stay up for more then 15 minutes or so. I also have a crash log which is about 30MBs in size, but I trimmed it to this. If the full log is desired just let me know.

[mangosd-11272018.txt](https://github.com/cmangos/issues/files/2619916/mangosd-11272018.txt)

**Comment by Dramacydal** [comment]
Looks like some insane recursion in movement generator XD

**Comment by jimmybrancaccio** [comment]
@Dramacydal Yeah, looks like it's looping a whole lot and eventually just running out of resources and crashing - at least that was my understanding from @Laizerox's comment yesterday in Discord.

**Comment by Muehe** [comment]
[Backtrace](https://gist.github.com/Muehe/5254640aa9867e116c170d1a9c002159)

Repeating messages have been cut at ~ line 900.

**Comment by jimmybrancaccio** [comment]
This should be resolved now. 🎉  I've been running the latest commit for about an hour now without issue. Please give it a test and let us know!

**Comment by cyberium** [comment]
Yep its fixed
