### ISSUE TITLE
Instance Uldaman: Unknown Spell ID 24889 Lets One of the Keepers Focus on You 

### ISSUE THREAD

**Issue by ChrisRadi** [cmangos/issues#1782]
**Current behavior:**
We currently have a strange error in the pre-chamber before "The Hall of Crafters" with the ancient stone keepers. At the beginning all keepers are still dead and waiting for someone who triggers them with the table in the middle of the room. But there is a strange behavior when a Druid call the spell "Dire Bear Form" (Aura/Spell ID 9634), then one of the keepers gets just alive, but no one is able to focus him. Also the script is not running further and the doors just stay closed. 
The server debug is full of:
`ERROR:CastCustomSpell: unknown spell id 24899 by caster: Player xxxx (Guid: 7) triggered by aura 9634 (eff 0)` 

**Expected behavior:**
Normally all stone keepers should be immutable as long they're dead. 

**Steps to reproduce:**
Enter the instance Uldaman as or with a druid, do all sub-quests in the instance and go further to the "The Hall of Crafters". Stay next to the ancient stone keeper in the back, right corner, call the spell "Dire Bear Form" (Aura/Spell ID 9634) and see if the stone keeper is focusing you all the time.

**Client version:**
3.3.5a Client

**Commit hash:**
e45254ea3b12437a73a77639407ae9f545283c4e

**Database version:**
WoTLKDB v1.1 'The Warsong' for CMaNGOS-WOTLK 13965
ACID 3.3.5a (Wrath of the Lich King) for CMaNGOS-WOTLK (3.3.5a Client)
Database commit hash: 3c101da2de04ba2975c241f3990c2198cce42fb8

**Operating system:**
Linux (Debian 9.1)

I hope this helps. Anyone knows how to fix it or where to add the spell id when this is causing the error?

**Comment by jimmybrancaccio** [comment]
@ChrisRadi Please provide the full details as requested in the issue template so this can be further triaged and reviewed.

**Comment by jimmybrancaccio** [comment]
@ChrisRadi Thanks, can you also provide the database commit hash? You can go into your database directory and use `git rev-parse HEAD`. Thanks!

**Comment by ChrisRadi** [comment]
Updated

**Comment by killerwife** [comment]
Fixed druid error otherwise cant reproduce anymore
