### ISSUE TITLE
[Classic] Question concerning map extractor

### ISSUE THREAD

**Issue by RichardGe2** [cmangos/issues#1783]
Hi, it seems map extractor built from source code is currently not working for Classic ( only works for WOTLK ? ).
error on Classic : "Could not read dir_bin file" 
What's the status on that ?
I know we can take the bin from mangos-classic/releases ,
but where is the valid source code of this build then ?

**Comment by killerwife** [comment]
Tbc should be working as well. Maybe I did some sort of mistake. @cyberium will check it out when he has time. There might be a non-trivial difference between vanilla and tbc that I personally do not know about.

**Comment by cala** [comment]
@RichardGe2 we may need more details here. I built the extractors from sources yesterday evening and extracted all maps for Classic. I did that on mac OS (aka *NIX plateform). So at least the source code seems ok.

The only issue I had is that extrators shell scripts are not copied in the build directory, I had to pick them from `/contrib/extractor_scripts`.

**Comment by RichardGe2** [comment]
I tried again with my own build.. and I think you are right, it seems to work.
Don't know what happened the first time :)
