### ISSUE TITLE
Brack and Slark patrol too slowly

### ISSUE THREAD

**Issue by Zooke** [cmangos/issues#1784]
**Current behavior**: 
Brack and Slark patrol too slowly
**Expected behavior**: 
They run along the shore considerably faster than players.
**Steps to reproduce**:

1. Observe npc's along beach in Westfall
2. 
3. 

**Client version**: 
1.12
**Commit hash**: 
latest
**Database version**: 
latest
**Operating system**: 
W10LTSC

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
```
UPDATE `creature_movement` SET `script_id` = 5 WHERE `id` IN (90206,90207) AND `point` = 1;
```
Note that path 90206 is missing in classic-db.

**Comment by jimmybrancaccio** [comment]
@Zooke Please ensure to provide the commit hashes for the core and database when submitting issues. Thanks.
