### ISSUE TITLE
Extractor and Bad Camera Files

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#1785]
**Current behavior**: 
 On startup classic mangosd.exe logs that there are Errors with camera files 

> 2018-11-27 17:00:06 Using enUS DBC Locale as default. All available DBC locales: enUS 
2018-11-27 17:00:06 
2018-11-27 17:00:06 Loading cinematic...
2018-11-27 17:00:06 ERROR:Camera file ./Cameras/PalantirOfAzora.m2 is damaged. File is smaller than header size
2018-11-27 17:00:06 ERROR:Camera file ./Cameras/FlybyUndead.m2 is damaged. File is smaller than header size
2018-11-27 17:00:06 ERROR:Camera file ./Cameras/FlybyNightElf.m2 is damaged. File is smaller than header size
2018-11-27 17:00:06 ERROR:Camera file ./Cameras/FlyByGnome.m2 is damaged. File is smaller than header size
2018-11-27 17:00:06 ERROR:Camera file ./Cameras/FlyByTroll.m2 is damaged. File is smaller than header size
2018-11-27 17:00:06 ERROR:Camera file ./Cameras/FlyByTauren.m2 is damaged. File is smaller than header size
2018-11-27 17:00:06 ERROR:Camera file ./Cameras/Scry_cam.m2 is damaged. File is smaller than header size
2018-11-27 17:00:06 ERROR:Camera file ./Cameras/FlyByDwarf.m2 is damaged. File is smaller than header size
2018-11-27 17:00:06 ERROR:Camera file ./Cameras/FlybyOrc.m2 is damaged. File is smaller than header size
2018-11-27 17:00:06 >> Loaded 1 cinematic waypoint sets in 63 ms
2018-11-27 17:00:06 
2018-11-27 17:00:06 Loading Script Names...
2018-11-27 17:00:06 >> Loaded 359 Script Names
2018-11-27 17:00:06 

It erros on all the m2 files generated by the extractors except FlyByHuman.m2, which is 4K in size and seems OK. The error ones above are 0K in file size.

*Expected behavior**: 

No Camera file Error in log

**Steps to reproduce**:

1. run extractors and copy camera folders into running directory 
2. observer server.log
3. 

**Client version**: 

1.12.1

**Commit hash**: 

ef5ce19bd650d68523211045a1cd2c1d6a9fde49

**Database version**: 

7ef3336053a5aa293bc1ad30e0d916dc838dcb7b

**Operating system**: 

win 8.1
[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by jimmybrancaccio** [comment]
I don't seem to be able to replicate this. My file sizes are all above 0k. You may wish to try rerunning your extractors (I believe it's `ad` that does the camera file extraction - someone correct me if I'm wrong ).


``` bash
$ ls -lah /home/mangos/classic/data/Cameras/
total 52K
drwxrwxr-x 2 mangos mangos 4.0K Nov 27 12:22 .
drwxrwxr-x 7 mangos mangos 4.0K Nov 27 14:59 ..
-rw-rw-r-- 1 mangos mangos 4.0K Nov 27 12:22 FlyByDwarf.m2
-rw-rw-r-- 1 mangos mangos 3.9K Nov 27 12:22 FlyByGnome.m2
-rw-rw-r-- 1 mangos mangos 3.7K Nov 27 12:22 FlyByHuman.m2
-rw-rw-r-- 1 mangos mangos 4.8K Nov 27 12:22 FlybyNightElf.m2
-rw-rw-r-- 1 mangos mangos 3.8K Nov 27 12:22 FlybyOrc.m2
-rw-rw-r-- 1 mangos mangos 3.6K Nov 27 12:22 FlyByTauren.m2
-rw-rw-r-- 1 mangos mangos 3.8K Nov 27 12:22 FlyByTroll.m2
-rw-rw-r-- 1 mangos mangos 3.7K Nov 27 12:22 FlybyUndead.m2
-rw-rw-r-- 1 mangos mangos 2.6K Nov 27 12:22 PalantirOfAzora.m2
-rw-rw-r-- 1 mangos mangos 2.1K Nov 27 12:22 Scry_cam.m2
```

**Comment by cala** [comment]
> (I believe it's ad that does the camera file extraction - someone correct me if I'm wrong ).

Correct. The `ad` binary does the camera files extraction, right after extracting the various DBC files.

**Comment by lduguid** [comment]
Ran twice, same result. Windows, visual studio 2017 64bit release build of extractors. Everything else appears to extracted fine and more interesting one of the camera files appears good. 

Not overly relevant to classic but as a side note, 64bit release build of tbc extractors worked fine extracting tbc client on my machine.

Perhaps my wow classic client has some corruption... I am not at that computer atm but will report back later today and update status of this issue accordingly.

**Comment by lduguid** [comment]
I attempted twice with the Win x64 release extractors, once with original Wow client and again using a different Wow Client, same issue.  FlyByHuman.m2 is fine, other classic m2 fiels are 0 in size, which in turn produces the Error when referenced in the run.

However, as other do not seem to have this problem, my solution was to just grab the tbc (using only classic relevant ones) camera files which are all fine and use them with classic. seems to work.

**Comment by AnonXS** [comment]
:no_good_man: still needs to be resolved?

**Comment by lduguid** [comment]
>  still needs to be resolved?

It _may_ but for now I am putting it down to perhaps a local 'quirk', hence the closing of the issue.  Unless others also have it with the latest Classic extractors compiling on Windows Visual Studio 2017 x64 it is probably OK to close or someone else want to try it out.  I will try a release x86 build later to see if it is also an issue for me.

**Comment by cala** [comment]
I'm uneasy with this being closed as the issue seems to be repeatable, at least on your side. Thank you @lduguid for testing various configurations. We may need someone else to test this on a config similar to yours.

I'm reopening this. If no one else is having/reproducing the issue, we may assume this is some wrong config on your side.

(extracted on mac OS, I have slightly the same file sizes than @jimmybrancaccio )

**Comment by lduguid** [comment]
Mystery solved. It can be closed as it is me.  I am bamboozled how i have sourced two different Wow clients that seem to have the same patch.MPQ, missing all but one of the Cameras m2 files. The WoW clients were definitely sourced from two different CD copies of the game but perhaps i patched both of them using the same patch downloads from the internet to get it from my CD copy to the 1.12.1x build *shrug* 

Apologies for the miss-issue.

![image](https://user-images.githubusercontent.com/105060/49186996-ffbbd800-f31a-11e8-905a-1d862d29df0f.png)

**Comment by cala** [comment]
> I am bamboozled how i have sourced two different Wow clients that seem to have the same patch.MPQ, missing all but one of the Cameras m2 files.

![It's magic](https://media1.tenor.com/images/79a8babaaa65d030e4f23d4b77a08709/tenor.gif?itemid=9565411)
