### ISSUE TITLE
Prayer of Mending Never Expires, Causing Infinite Strong Heals

### ISSUE THREAD

**Issue by SilvioDoMine** [cmangos/issues#1786]
**Current behavior**: 
After using Prayer of Mending while grouped, and recieve damage, the heal spread to another player and the stack is changed from 5 to 4. After the player with 4 stacks recieve damage, the heal will spread to another player, and the stack is changed from 4 to 5 again. And the heal only gets stronger, and stronger, and don't expires.

**Expected behavior**:
The stack should be changed to 5, 4, 3, 2, 1, and then vanishes.

**Steps to reproduce**:

1. Loggin 2 accounts/chars
2. `.learn 33076` in one of them (Learn Prayer of Mending)
3. Party up with the characters
4. Use prayer of mending in one of the characters
5. use `.cast self 8921` to force hit the player with Prayer of Mending
6. Do this until the heal gets +9000000
7. Reproduced.

**Client version**: 
2.4.3 (8086)

**Commit hash**: 
 e10a6b07b00c920534bf4c61570ec3a8ea476652

**Database version**: 
ac016ca0643ae7d24441c6ada4f96b99ddce9e34

**Operating system**: 
Debian 9

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Working on it.

**Comment by killerwife** [comment]
Fixed in https://github.com/cmangos/mangos-tbc/commit/d9656ff75df6b60a81891f8eb5b1e42bf59a55c8
