### ISSUE TITLE
Fleeing Mobs Have Incorrect Dead Body Position Upon Dying

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#1789]
**Current behavior**: 

Feeling mobs dead body will 'drag' back to a position close to where the player is currently standing and/or where it started its flee position.

**Expected behavior**: 

NPC dead body will lay to rest in the location where it died.

**Steps to reproduce**:

1.  Go to Trisfal Glades with low'ish level warlock
2.  Using the Scarlet Zealot NPC's around castle just outside of the Ruins of Lordaeron.
3.  NOT using a pet to tank, apply dots to a Scarlet Zealot, so that it can get a chance to flee before dieing.
4. When it flee's at low health, run to a different location
5. Observer the NPC die and body fall to ground then 'drag' across ground to position close to where you are standing.

NOTE: This is relevant to both Classic and TBC cores, did not test WOTLK.

Maybe related to work done on [Reimplement Fleeing using new AIOrders system](https://github.com/cmangos/mangos-classic/commit/d8678a483e0a3aefba1d0644deaf0c82bc240d5e) (Classic)

**Client version**: 

1.12.x

**Commit hash**: 

c442bc0bef1e6e5b167e5026e6cd67e30d041e81 - Classic
d5f75302653b1581bdede1f32b964ce77e15662a - TBC

**Database version**: 

79707205b79110fbee7cc211287f85a7ee134867 - Classic
01c5747b1e2a1c52276806b034b44e9fd1e42ce1 - TBC

**Operating system**: 
win 8.1x

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Resolved. https://github.com/cmangos/mangos-classic/commit/c2b758eb36a8fd9e4c5a4b41ccce89c28fc49a67
