### ISSUE TITLE
Summoned Pet Aggro Issues

### ISSUE THREAD

**Issue by tarwyn** [cmangos/issues#179]
Rev #12429 (and prior)

NPC Summoned Pets do not follow the aggro rules that any NPC is subject to. The first creature or player to aggro a summoned pet stays on top of that pets aggro list until the summoned pet dies. It is NOT possible to taunt or by any other means change the aggro target of a summoned pet once it has aggroed on something. They also never enter evade if their aggro target tries to run away and can be dragged across entire zones in this fashion.

Correct behaviour of NPC summoned pets should be just like any other NPC: they should be susceptible to taunting and they should use the location where they were summoned as a means of establishing distance required to enter evade.

**Comment by cyberium** [comment]
This need to be reconfirmed so i can close the issue until then
