### ISSUE TITLE
When Closing Out mangosd There is a transportsystem.cpp Error

### ISSUE THREAD

**Issue by madmax765** [cmangos/issues#1790]
**Current behavior**: 
When  closing cmangos I get this error
**Expected behavior**: 
Should close with out error
**Steps to reproduce**:

1.  Run Cmangos
2.  Exit or ctrl+x 
3. 

**Client version**: 
 WOTLK
**Commit hash**: 
0aaed51e2067a6eb86f86de168c31bf3f700c3a3
**Database version**: 
PSMDB Rev. 409
**Operating system**: 
Windows server 2016 Standard
![image](https://user-images.githubusercontent.com/29853/49328720-61f72180-f543-11e8-8d1e-8bf8b8ad7f93.png)

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by berserkingyadis** [comment]
Did you run with a fresh config file for mangosd?

**Comment by madmax765** [comment]
Yes, And in the pic _D:\game cores\wow files_ is from where I compiled it at. from another pc Running windows 10 and running it on the server C:\AA\WOTLK

**Comment by jimmybrancaccio** [comment]
I have attempted to replicate this on cmangos/mangos-wotlk@0aaed51 and cannot (using Ubuntu 14.04). I do recall seeing this before though.

```
10:50:01 GameEvent 41 "Leader of Jin'Alai, Kutube'sa" removed.
10:50:01 GameEvent 42 "Leader of Jin'Alai, Gawanil" started.
10:50:01 Next game event check in 480 seconds.
server shutdown 10
Table `command` have command '' that only used with some subcommand selection, it can't have help or overwritten access level, skip.
10:50:51 mangos>10:51:03 Halting process...
$
```

**Comment by ekg98** [comment]
![transportbasecrash](https://user-images.githubusercontent.com/24751528/49348838-cd411080-f675-11e8-883f-c83886d6a8b5.JPG)

encountered by typing server shutdown 0
ubuntu server 16.04

**Comment by jimmybrancaccio** [comment]
Just got the error myself:

```
server shutdown 10
19:00:16 Table `command` have command '' that only used with some subcommand selection, it can't have help or overwritten access level, skip.
19:00:26 mangos>Non-grid object (TypeId: 0) in grid object removing list, ignored.
19:00:36 /home/mangos/mangos/src/game/Maps/TransportSystem.cpp:49: Error: Assertion in ~TransportBase failed: m_passengers.empty()/home/mangos/mangos/src/game/Maps/TransportSystem.cpp:49: Error: Assertion in ~TransportBase failed: m_passengers.empty()/home/mangos/mangos/src/game/Maps/TransportSystem.cpp:49: Error: Assertion in ~TransportBase failed: m_passengers.empty()/home/mangos/mangos/src/game/Maps/TransportSystem.cpp:49: Error: Assertion in ~TransportBase failed: m_passengers.empty()19:00:36 Halting process...
```

I just updated to cmangos/mangos-wotlk@28de995 so I will see if happens there as well.

**Comment by ekg98** [comment]
I still get it as of right now...

**Comment by Rog360** [comment]
I posted an issue report on this error and it was closed. Glad to see I'm not the only one getting this error.
https://github.com/cmangos/issues/issues/1514

**Comment by jimmybrancaccio** [comment]
I don't believe any commits have been made since the issue was reported to address this issue so it would be expected behavior that this still happens (unfortunately).

**Comment by ekg98** [comment]
I just had a interesting bug occur with classic.  it reflects about the table command has command red message above.  The console just slammed into full crazy mode.  Anything typed into the console is always followed by newline.  Its like something in the console is forcing it to append a newline to stdin.

I alt + f key to a different tty.  Keyboard is fine.  strange...

**Comment by jimmybrancaccio** [comment]
@ekg98 This does not appear to be related to this issue with the TransportSystem.cpp error. Please ensure that each unique problem has its own issue in GitHub.

**Comment by adellaci** [comment]
I'm testing that tonight. After everything is loaded i'm using 1756000 of mem + ot -

**Comment by xfurry** [comment]
I also remember that I saw this error, but not recently though.
I will try to investigate it again, as soon as I have the chance.

**Comment by adellaci** [comment]
i can log on to the Realm but i an stuck on connecting to the World.
When i started my mem was at 1756000 +/-, now that i can not enter into the World mem is at 1848636.

i can not get 'mangosd' to shutdown by 'server shutdown 0'. I have to use 'Ctrl-C' to get it to stop. Mem usage with server idle is 429000 +/-.

I did not get the 'transportsystem.cpp Error' message on close.

I'm rerunning the test with update to cmangos and wotlk-db from this morning.

**Comment by adellaci** [comment]
Ubuntu Server 16,04.
CMaNGOS : 005a7a98f50569817b2b0d5f1bf16bb012ffd704
WOTLK-DB : e41a5b54cbfbbcb80d34467d5286bc1fb189e4ae

Server idle with three terminals open for, one terminal has 'top running'
Memory Usage: 332000+/-

realmd started in terminal 2
Memory Usage: 342000+/-

mangosd started in terminal 3 w/ all maps loaded
Memory Usage: 1753000+/-

after 5 minutes of running, NO character logged in
Memory Usage: 1769000+/-

one character logged in 
Memory Usage: 1778000+/-

characters logged out, and running for 12 minutes
Memory Usage: 1781000+/-

I will report memory usage after an hour w/o any characters logging in any further.

**Comment by adellaci** [comment]
After one hour of running with no character logged in
Memory Usage: 1811000+/-

**Comment by madmax765** [comment]
> 
> 
> i can log on to the Realm but i an stuck on connecting to the World.
> When i started my mem was at 1756000 +/-, now that i can not enter into the World mem is at 1848636.
> 
> i can not get 'mangosd' to shutdown by 'server shutdown 0'. I have to use 'Ctrl-C' to get it to stop. Mem usage with server idle is 429000 +/-.
> 
> I did not get the 'transportsystem.cpp Error' message on close.
> 
> I'm rerunning the test with update to cmangos and wotlk-db from this morning.

same.. i could not shut down. and got no error that time too up time 3 hours 44 mins.. and its ok, but wont make it pass 24 hours

**Comment by adellaci** [comment]
2 hours 40 mins can still enter world,
after logging out
Memory Usage: 1822000+/-

**Comment by Lankytim** [comment]
In case this is related/helpful, I had a "transport-related" crash on my mangos-tbc today:

```...
GameEvent 57 "World's End Tavern - Perry Gatner Announce" removed.
Next game event check in 960 seconds.
GameEvent 24 "Stormwind City - Stockades Jail Break" started.
Next game event check in 600 seconds.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error>>'
  what():  remote_endpoint: Transport endpoint is not connected
Aborted```

That was with mangos-tbc commit 2508cbb76849b9a3501b2f0cbcd281edcf1b00c8 for Linux_x64.  I don't think there were any players logged in at the time.

**Comment by adellaci** [comment]
I got home and tried to log in, got hung enter world.

Memory Usage: 184000+/-
%cpu went from 71 to 105

**Comment by madmax765** [comment]
| Name | Value | Type
-- | -- | -- | --
▶ | this | 0x000001e83886e798 { size=15987178197214944733 } | std::list<Group *,std::allocator<Group *> > *

>	mangosd.exe!std::list<Group *,std::allocator<Group *> >::begin() Line 1007	C++

Unhandled exception at 0x00007FF7BB866F2B in mangosd.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

crash final in debug mode

http://www.crypthome.com/crash.png
![image](https://user-images.githubusercontent.com/29853/51085688-efb15980-170a-11e9-9ef1-6d76b214c554.png)

**Comment by xfurry** [comment]
@madmax765 this image points to something else. ```DungeonPersistentState: UnbindThisState()```. -> Poke @cyberium 

However, the other error regarding the transport still remains.
