### ISSUE TITLE
[WotLK] All inland water causes damage!

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#1791]
**Current behavior**: 
Enter water anywhere inland and you get damage like your in lava.

**Expected behavior**: 
enter water and no damage.

**Steps to reproduce**:
1. .tele stormwind
2. go jump in lake
3. damage

I extracted maps twice and tried cyberium's maps also.
Still get damage.

**Client version**: 
3.3.5
**Commit hash**: 
0aaed51e2067a6eb86f86de168c31bf3f700c3a3

**Database version**: 
PSDB

**Operating system**: 
Windows 7 x64

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-wotlk/commit/d97d322de5b5cb8a96128cd77b620054948f7393

**Comment by Rog360** [comment]
Thanks killerwife... :)

**Comment by cala** [comment]
Yes, global warming was introduced to Azeroth. We are *that* accurate when doing emulation.

**Comment by ddzzhen** [comment]
great,i have this problem too. Thanks a lot.

**Comment by Tobschinski** [comment]
I have lots of other problems, someone help me!
