### ISSUE TITLE
[TBC]Mana Tide Totem Crashing Server

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1792]
**Current behavior**: Since updating the Core, using the mana tide spell totem instantly puts mangossd in a not responding state crashing the server.

**Expected behavior**: Should restore mana to the player

**Steps to reproduce**:
Method 1:
1. .learn 16190 
2. use spell
3. F

Method 2:
1. .cast 16190 or .cast 16191

Totem id 10467 / mana tide effect is 39610

**Client version**: 2.4.3

**Commit hash**:  9d892e1f4908b7b8f3ac2a3ff2c51d30987d46d7

**Database version**: 5.7.21 

**Operating system**: Windows Server 2012 R2

https://imgur.com/a/0vt79Oh - Crash error. Sorry haven't got a crash report yet :S

**Discord Discussion:**
"LevelOneToday at 2:18 PM
Regarding the mana tide totem, reverting this commit will fix that problem: https://github.com/cmangos/mangos-tbc/commit/49e3b77a27de3604186b54a3d434496e2b0f15e5
GitHub
SPELL_AURA_PERIODIC_TRIGGER_SPELL select target logic applies to a...
…spells

Fixes 35951 being filled with target even though it shouldn't
Also this will propably break some things but its a step in the right
direction."

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Working on it.
