### ISSUE TITLE
SSC_LadyVashj Fight -  ENCHANTED_ELEMENTAL= 21958 Is To Slow

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1795]
**Current behavior**:  Elementals that spawn during the boss fight  [21958 - Enchanted Elemental] are to quick when running to the boss (with the intent to buff her) Explode timers seem correct for when they explode (buffing the boss),.

**Expected behavior**:  Elementals are meant to move slower, exploding as soon as they reach the boss, rather than move rapidly up to the boss and explode 5 seconds after reaching the boss.

**Setting the elementals to to have a speedrun of 1.0 rather than 2.14286 works great for me right now**

**Steps to reproduce**:

1. Start Lady Vashj fight
2. Get to the last phase where the elementals spawn

**Client version**: 2.4.3

**Commit hash**: 594ef7bc39c37c57267a4dbf531d1adb70538518

**Database version**: latest

**Operating system**: Win Serv 2012 r2

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
here is where it should be fixed: https://github.com/cmangos/mangos-tbc/blob/master/src/game/AI/ScriptDevAI/scripts/outland/coilfang_reservoir/serpent_shrine/boss_lady_vashj.cpp#L213
hint: run/walk

**Comment by AnonXS** [comment]
resolved here https://github.com/cmangos/mangos-tbc/commit/e328b3b4d36175e7919f3eabb396bf841f5d6868#diff-c1fe26f6338e975164c671a1f02e366dR561
