### ISSUE TITLE
The itemID 54811 and spellID 75614 are not working as expected

### ISSUE THREAD

**Issue by ddzzhen** [cmangos/issues#1796]
**Current behavior**: the item can`t use , it is a Mounts with the itemID  "54811" and spellID "75614", the only one depends on the area and skillrank.
i find the other spellIDs about the 星骓 include the "75617","75618","75619","75620" in the spell.dbc, and "76153" also is about "星骓".

but  spell(75614) can`t use from the item(54811) and spellid("75617","75618","75619","75620","76153") is ok.
**Expected behavior**: 
item can be used normally.

**Steps to reproduce**:

1. config the server
2. start the server
3. connect the server by client.

**Client version**: 
3.3.5a(12340)
**Commit hash**: 

d97d322de5b5cb8a96128cd77b620054948f7393

**Database version**: 

fca7acd9000fced979098734ac8de333e74c0c8f

**Operating system**: 
Ubuntu18.04

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by jimmybrancaccio** [comment]
@ddzzhen Please provide your core commit hash and database commit hashes.

**Comment by ddzzhen** [comment]
> @ddzzhen Please provide your core commit hash and database commit hashes.

sorry for that. i found how to find the hashes actually now.

mongos-woltk hash:d97d322de5b5cb8a96128cd77b620054948f7393
wotlk-db hash:fca7acd9000fced979098734ac8de333e74c0c8f

**Comment by killerwife** [comment]
I retested, it works as intended now.
