### ISSUE TITLE
AHBot is Missing Lower Level Cloth Items

### ISSUE THREAD

**Issue by ekg98** [cmangos/issues#1797]
I am running almost default ahbot config except for item levels adjusted.  I have increased everything a order of magnitude.  I have 93,000 items in my auction house.  I found that there is no silk, wool, or linen in the ah.  I only have two pages of cloth in the whole 93,000 items  I have to include the item number in the force include to make it appear at all.  I assume this is a filter issue.  

Populate AH with proper amount of cloth items.

**Steps to reproduce**:

1. configure ahbot
2. run ahbot
3. observe ah

**Client version**: TBC/WOTLK

**Commit hash**: 034be8 tbc / wotlk - c2d267

**Database version**: 1.7 tbc / 1.1 wotlk

Ubuntu CLI 16.04.5

**Comment by jimmybrancaccio** [comment]
@ekg98 Can you clarify what you mean by 'configure AH bot'? How are you configuring it, can you provide your configuration where you expect there to be these items?

**Comment by ekg98** [comment]
[ahbot.conf.txt](https://github.com/cmangos/issues/files/2664761/ahbot.conf.txt)

This is default except for quantities.

**Comment by jimmybrancaccio** [comment]
@ekg98 So it is my understanding that you expect that those items show up when using a default configuration file?

We'll have to investigate to see if that's the intended behavior or not.

**Comment by ekg98** [comment]
Indeed the tradegoods is set to priority 10 and the filter values are set both to 0 to allow all trade goods.  White is a large value.  This in default behavior spawns some cloths but they are only high level.  It doesnt seem to spawn any cloth below level 30 or maybe 40 or so.

**Comment by cyberium** [comment]
Could you please give me proper item id as exemple? I am not able to identify clearly the problem. I see btw that there is not much item of these type that are only droppable. They often are available on some vendor. So to maximise the chance to get White quality of cloth try enable vendor item.

**Comment by ekg98** [comment]
I believe you to be right cyberium.  I will try to enable it later but as far as I can tell there is one lady in silvermoon city that does sell these cloths as of 2.4.3.  I will see if I can verify later.

**Comment by ekg98** [comment]
Operator error.  Needed vendorable items enabled.
