### ISSUE TITLE
Some Bleeding Hollow Tormentor (dismounted ones) should use Fear s.33924 as RP

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#1798]
**Current behavior**: 
Bleeding hollow tormentor located at rethgor in hellfire peninsula will always fear his own summoned pet worg and/or another bleeding hollow tormentors pet. 

**Expected Behaviour**:

Fear player at least most of the time

**Steps to reproduce**:

1. Engage combat with bleeding hollow tormentor
2. Combat until he casts fear (do not kill his pet worg)
3. 

**Client version**: 
2.4.x

**Commit hash**: 

900051fb74749aa01cba95d04c4a5ef9dc05fbb3

**Database version**: 

4449a5bfd1f40ba391169ce03ed89d40b9767d5b

**Operating system**: 

8.1
[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
It seems friendly units are also placed in the Bleeding Hollow Tormentor threatlist.

('1942402','19424','0','0','100','1','9000','16000','12000','18000','0','0','11','33924','2','0','0','0','0','0','0','0','0','0','Bleeding Hollow Tormentor - Cast Fear'), -> Fear on Second in Aggrolist

**Comment by lduguid** [comment]
From very hazy memory, I thought I remembered it being a possibility in retail that he could fear his own worg, however, on killing many of them using my own hunter and pet, not once were I or my pet feared, always a friendly (to the npc) worg.

If this is datamined behavior I do not doubt that it is a correct setting in the database but could there be something else going on where regardless of actual threat, the tormentor worg is always incorrectly second on the combat threat list?  Is there a convient way to test if this is tha case?

**Comment by lduguid** [comment]
Some followup: 

Firstly I should clarify I was using a hunter with a pet out so there is always a second target for the NPC.

I tired to dig deeper on this by setting a breakpoint in;

`CreatureEventAI::GetTargetByType` in `CreatureEventAI.cpp` and stepping from there, I must admit that I quickly got out of my depth in trying to figure out why the creature **19424** would cast **33924** on its own worg.  Reading about creature_ai_scripts in the wiki, the enum of **TARGET_T_HOSTILE_SECOND_AGGRO** (**2**) for the target of the event action **ACTION_T_CAST** (**11**) does say _HOSTILE_, so I am assuming the creature has a threat list that should not include its own work as it is not hostile to it. Although the comment just states;, 

> Targets the unit with the second most threat in the threat list.

and that is unclear, to me at least, that it some what conflicts with the implied wording of **TARGET_T_HOSTILE_SECOND_AGGRO**, which suggests **hostile**, only versus the entire combat threat list.  

However, regardless if i get stepping with the debugger, it did appear that when the spell was cast it was getting a non worg target to work with but I could not follow from there why it was still choosing the worg past that point.

Another question, why is it the **33924** version of '**Fear**', did that come from sniff;s?  there seem to be a bunch of other '**Fear**' spell in spell_template, could another fear be a possible choice here?

**Comment by AnonXS** [comment]
I guess we are using the spell wrong as it has: 
```
Effect 0:
Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (38, 0) (TARGET_SCRIPT, TARGET_NONE)
Aura Id 7 (SPELL_AURA_MOD_FEAR), value = 0, misc = 0 (0), miscB = 0, periodic = 0
``` which implies a fixated entry this spell targets, maybe it was confused with the stable worg masters which cause their wolfs to be feared on certain event and the fearspell was just salvaged here.

I'll lookup the npc if it really uses **33924**.

**Comment by lduguid** [comment]
Where did you get that nice summary of spell info. about **33924** ? I might be blind but i could not correlate what you posted with what was available in the gazillion columns of info about it spell_template.

**Comment by AnonXS** [comment]
https://github.com/sidsukana/QSpellWork/releases

**Comment by lduguid** [comment]
Nice! Thank you for the link.

**Comment by AnonXS** [comment]
can someone reproduce this, i could not?

**Comment by lduguid** [comment]
It probably has to be tested with at least one other 'friendly' in combat as you and in range, with me as a  hunter and my pet out engaging in comabt  is what i was using.  At the time and it was pretty consistent with the NPC casting his 'fear' spell on his own worg instead of me and/or my pet.  I have not tested this since posting the issue but will test again tonight to see if I can still reproduce.

**Comment by AnonXS** [comment]
![unbenannt](https://user-images.githubusercontent.com/19734826/51853570-e938f980-2328-11e9-93eb-c7cffd5d2434.PNG)

yes reproduced with additonal unit in threatlist

**Comment by AnonXS** [comment]
**rp issue**:

```
should fear worg, but not summon worg 69475,69473,69472,69470
should not fear worg and not summon worg 69471
should not fear worg, but summon worg: 52275,52276,69474,69476,69477,69478,69479,69480,69481
```

we could add movement for 69475,69473,69472,69470 (they move random) making them cast s.33924 every 4 minutes + handle the emotes

```
-- Bleeding Hollow Tormentor 19424 - should probably only summon mount if mounted / only play rp if dismounted, edit scripts so only pathing versions set the phase where this is executed
('1942401','19424','0','X','100','1','240000','240000','240000','240000','0','0','5','36','0','0','11','33924','15','0','0','0','0','0','Bleeding Hollow Tormentor - OneShotAttack1H and Cast Fear OOC (Phase X)'),
('1942402','19424','0','X','100','1','241000','241000','240000','240000','0','0','5','11','0','0','0','0','0','0','0','0','0','0','Bleeding Hollow Tormentor - OneShotLaugh OOC (Phase X)'),
```

**Comment by killerwife** [comment]
I am closing this as it was removed and the other part isnt subject to this.
