### ISSUE TITLE
Importing mangos.sql fails due to duplicated faction column

### ISSUE THREAD

**Issue by joao-fidalgo** [cmangos/issues#1801]
`ERROR 1136 (21S01) at line 1355: Column count doesn't match value count at row 1`

**Current behavior**: Cannot import mangos.sql into database due to duplicated faction column.

**Expected behavior**: I should be able to import the script.

**Steps to reproduce**:

1. mysql -umangos -pmangos tbcmangos < mangos-tbc/sql/base/mangos.sql

**Client version**: 2.4.3

**Commit hash**: 900051fb74749aa01cba95d04c4a5ef9dc05fbb3

**Database version**: 4449a5bfd1f40ba391169ce03ed89d40b9767d5b

**Operating system**: Ubuntu 18.04

**Comment by joao-fidalgo** [comment]
I already have the fix ready for this, just dealing with GPG sign failing due to email privacy issues.

**Comment by AnonXS** [comment]
duplicate https://github.com/cmangos/issues/issues/1799
