### ISSUE TITLE
ERROR 1396 (HY000) at line 7: Operation CREATE USER failed for 'mangos'@'localhost'

### ISSUE THREAD

**Issue by dvdvideo1234** [cmangos/issues#1802]
**Current behavior**: 
`ERROR 1136 (21S01) at [line 1355](https://github.com/cmangos/mangos-tbc/blob/900051fb74749aa01cba95d04c4a5ef9dc05fbb3/sql/base/mangos.sql#L1355): Column count doesn't match value count at row 1`
**Expected behavior**: 
The query to be executed correctly
**Steps to reproduce**:
1. Install [latest TBC source](https://github.com/cmangos/mangos-tbc)
2. Execute the SQL file from the `sudo` command line
```
      mysql -f -uroot $mysqlpa tbcmangos < $scriptpath/$drtitle/mangos/sql/base/mangos.sql
```

**Client version**:  Lastest version of TBC db/server

**Commit hash**: Lastest [commit](https://github.com/cmangos/mangos-tbc/commit/0cb338cd7b20732c541691b3729fb3fe7da5865d#diff-19d5e01df7226bec976ff28e83a4bbef)

**Database version**:  Lastest TBC database

**Operating system**: 
```
mangos@mangos-VB:~/Documents/UbuntuBatches/MaNGOS$ uname -a
Linux mangos-VB 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
**Crash Log** None

**Comment by AnonXS** [comment]
duplicate https://github.com/cmangos/issues/issues/1799

remove `35,` factionalliance and factionhorde was merged into faction
