### ISSUE TITLE
[WotLK] Fix SD2 text for Four Horsemen

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#1803]
**Current behavior**: 
Says "youself"
(-1533044,'Defend youself!',8892,1,0,0,'blaumeux SAY_BLAU_AGGRO'),

**Expected behavior**: 
Should be "yourself"
(-1533044,'Defend yourself!',8892,1,0,0,'blaumeux SAY_BLAU_AGGRO'),

**Client version**: 
3.3.5

**Commit hash**: 
68f669bae1f5a4f5f28c98eacd84bf1ced0ccc3a

**Database version**: 
PSDB

**Operating system**: 
Windows 7 x64

**Comment by cala** [comment]
Seems that I missed this one on my previous check.

**Comment by Rog360** [comment]
I added a note on the commit you did. Just figured I'd post it here. so, it wasn't forgotten... :)
