### ISSUE TITLE
Bags dropped after upgrade to 32 slots

### ISSUE THREAD

**Issue by ekg98** [cmangos/issues#1804]
**Current behavior**: Bags are dropped after this commit and all items are moved to mailbox
https://github.com/cmangos/mangos-classic/commit/ac9a3bd7dab183f1f3fae6d16f4baa3a2993fc00?diff=unified

**Expected behavior**: Bags retained from previous commit

**Steps to reproduce**:

1. Upgrade from older mangos version than commit
2. run mangos

**Client version**: Classic

**Commit hash**: ac9a3bd
https://github.com/cmangos/mangos-classic/commit/ac9a3bd7dab183f1f3fae6d16f4baa3a2993fc00?diff=unified

**Database version**: 1.9.0

Ubuntu CLI 16.04 LTS

Conversion from 28 slot bags to 32 slot causes bags with the old item_instance data field to be dropped.

Needed sql update for characters db to go along with this commit

**Comment by cala** [comment]
Confirmed.

**Comment by cala** [comment]
To be more accurate : on first character login after https://github.com/cmangos/mangos-classic/commit/ac9a3bd7dab183f1f3fae6d16f4baa3a2993fc00, all bags are destroyed (except the main back pack). Thus, all(?) items previously contained in these bags are sent to the character by mail.

This only occurs to bags equipped before https://github.com/cmangos/mangos-classic/commit/ac9a3bd7dab183f1f3fae6d16f4baa3a2993fc00, all bags equipped and filled after this commit stay in player's inventory with their items.

By chance, my development and my production servers are respectively using revision after and before the related commit, so I can perform tests to help fix this issue.

**Comment by killerwife** [comment]
There are checks on item load, and container load, which I do not remember where they are, somewhere in Player::LoadFromDB. It needs to be debugged to see which condition fails.

**Comment by cala** [comment]
Thank you for your feedback. Notice is made in commit for other users.
