### ISSUE TITLE
[TBC] Druid talent learning adds point instead subtracks

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1806]
**Current behavior**: 
If you try to learn Primal Fury talent, first level will add you talent point, so you will have 63 points at the end instead of 61.

**Expected behavior**: 
It should subtrack point and maximum points should be 61.

**Steps to reproduce**:

1. Create Druid
2. .level +69
3. add 5 points to Feral Agression
4. add 5 points to Ferocity
5. add 3 points to Sharpened Claws and 2 to Feral Swiftness.
![image](https://user-images.githubusercontent.com/39913306/49901173-87ecc200-fe71-11e8-95cc-ecf22adfdb99.png)
you will have 15 spent points and 46 talent points, 15+46 = 61

6. add 1 point to Primal Fury

![image](https://user-images.githubusercontent.com/39913306/49901259-c1253200-fe71-11e8-91de-ae94d08470f0.png)
you will have 16 spent points and 47 talent points, 16+47 = 63 (2 new points were added)

Video how to do it: https://radikal.ru/video/QtVqd2saHs4

**Client version**: 
2.4.3, eng
**Commit hash**: 
latest
**Database version**: 
latest
**Operating system**: 
win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by SilvioDoMine** [comment]
This also cause talent reset when relogging

**Comment by datchannin** [comment]
Yes, talent will be reset if you spend all 63 points. May be because player should not have move than 61 talent points.

**Comment by datchannin** [comment]
I thought, that there are fields in spell_template or may be separate table for core to understand if this spell is talent and how many points it should cost. But I did't find such information. So don't know what part is responsible for talents/spell and points spending.
