### ISSUE TITLE
Putting on a Trinket Will Add Additional Cooldown Time to Spells

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1807]
**Current behavior**: 
If you put off trinket and then put on it - you will have addition CD to spell on it. Even if your CD have already finished.
For example:
you have PVP trinket with spell=42292 (5 min CD) that already was refreshed 5 min CD.
if you put on Trinket to character you will have 30 sec CD. But after it finish, you will not able to USE spell on trinket for addition 4.30 min.

And for addition I have such error on my console:
mangos>Player::AddCooldown> Spell(42292) try to add and already existing cooldown?

**Expected behavior**: 
If you put off and the put on trinket (with refreshed CD) you should have only 30 sec CD. 

**Steps to reproduce**:

1. create Warrior, use .additem 18854 to create trinket
2. put on it
3. wait for 30 sec CD
4. try to use trinket, but you will not be able to do it
5. put off it and put on again
you will have: Player::AddCooldown> Spell(42292) try to add and already existing cooldown?
in your console
![image](https://user-images.githubusercontent.com/39913306/49902379-d3ed3600-fe74-11e8-868c-6c8322180ca1.png)

**Client version**: 
2.4.3
**Commit hash**: 
91bcbfeb558141e30481899cc030d5d3747ffb3b

**Database version**: 
7acaa3054854b480b48df3baadb068eb3e099309

**Operating system**: 
win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by jimmybrancaccio** [comment]
Hello @datchannin Please provide the actual commit hashes. Saying 'latest' does not help unfortunately. Thanks!

**Comment by datchannin** [comment]
Hi @jimmybrancaccio ,

It was latest by 13 December.
So I believe it was: 
commit 91bcbfeb558141e30481899cc030d5d3747ffb3b - for core
and commit 7acaa3054854b480b48df3baadb068eb3e099309 - for database

**Comment by AnonXS** [comment]
fix pending - "Do not supply item for equip cooldown addition"

**Comment by berserkingyadis** [comment]
Not sure If replicated. 

What I did:

1. put on trinket: 30 sec cd 
2. wait 30 secs, item becomes ready
3. put off and on
4. item has 30 sec cooldown again

Fixed?

@datchannin @AnonXS 

core: https://github.com/cmangos/mangos-tbc/commit/1ee44bb75c87fb599f85d8d959dbf7d1933fb05a
db: https://github.com/cmangos/tbc-db/commit/8134aaac47ac3eb45a6acd42e1948f7c0b241d1c

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/bec5c1031dd1704248a7f7d775c92b7d994eacdc
