### ISSUE TITLE
[TBC] The Eye - 19514/Alar not entering Phase 2

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1810]
**Current behavior**: Phase 1 involves killing Alar whilst he switches platforms, including the adds he spawns whenever he does the switch. Right now killing Alar in phase 1 seems to end the fight, giving the players the boss loot.

**Expected behavior**: Alar is meant to die as part of Phase 1 but instead of the fight ending and loot being made available. Alar is meant to re-spawn in the middle of the boss room and start Phase 2.

**Steps to reproduce**:

1. .tele TK
2. Start the boss fight Alar
3. fight through Phase 1 killing Alar

**Client version**:  2.4.3 

**Commit hash**:  d5ea73003678f5000e578ee10e42a6d63b21d9a7

**Database version**:  954cde0d16104258c13976d1075e569ed658301e

**Operating system**:  Windows Server 2012 R2

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
Did you do .die by any chance?

**Comment by yatzi888** [comment]
@killerwife Unfortunately I tried everything to make sure it wasn't me missing the script triggers. I tried slowly taking him down with .damage and also using a boss spell which deals around the same damage as a normal group. I have changed the mobs health multiplayer to reduce the it's overall hp. Could this be having an effect?

**Comment by killerwife** [comment]
Try doing ".die 1". Thats how I test him.

**Comment by yatzi888** [comment]
I'll give it ago when I'm back from work! Thanks (The rest of the raid runs like a dream :D big props)

**Comment by yatzi888** [comment]
@killerwife Ye .die 1 worked. This can be closed, I guess I was being impatient with my dmg output on him, must of messed with the script! Sorry!
