### ISSUE TITLE
The Eye - 19514/Alar - 0% HP Immune beginning of phase 2

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1812]
**Current behavior**: Majority of the time when Alar goes into phase 2 (after killing him) he re-appears with 0% HP and is in an immune state.

**Expected behavior**: Boss should regen back to full HP and not be immune. 

Video showing the result - https://youtu.be/RnR_Wd66Akg

Apologies if this is another case of me testing in a dodgy manner. 

**Steps to reproduce**:

1. Take boss to 0% in first phase with a dot on him
2. Wait for him to reappear with 0% hp

Client version: 2.4.3

Commit hash: d5ea73003678f5000e578ee10e42a6d63b21d9a7

Database version: 954cde0d16104258c13976d1075e569ed658301e

Operating system: Windows Server 2012 R2

EDIT: Changed text to remove what I thought was the cause dots on the boss before transition into phase 2. Could not reproduce this and ultimatly can't find a specific trigger as to why the bug sometimes does't happen, or does.

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by yatzi888** [comment]
I have a feeling it's to do with the spell 34098 ClearAllDebuffs seemingly not working. Doesnt seem to clear any debuffs from my characters when using as a learnt spell and the boss uses it right before transitioning to the second phase

**Comment by killerwife** [comment]
That should not be possible, he does RemoveAllAurasOnDeath on his immunity.

**Comment by yatzi888** [comment]
I see, i did some more testing and it i take back the dot causing him to not regen hp. I can't seem to find a specific trigger now. Sometimes it works, sometimes it doesn't

**Comment by yatzi888** [comment]
@killerwife I made these changes which fixed it - but I'm 100% positive theres a better way to resolve it. I'm just playing around https://github.com/yatzi888/mangos-tbc/commit/5d1a1b03a4bed6775e43fe0a9984ed9f3ea37afd

**Comment by killerwife** [comment]
Sadly thats not how it shoould be fixed cos then its not blizzlike. I will try to resolve this in the future somehow.

**Comment by yatzi888** [comment]
@killerwife ye I figured :P I just wanted to get him working and was wondering if this would help in anyway. The HP change is ofc for my server specifcally as well where bosses have less hp. Look forward to the proper fix 👍

**Comment by AnonXS** [comment]
resolved
