### ISSUE TITLE
Wrong Models for Winter Revelers

### ISSUE THREAD

**Issue by splinecl** [cmangos/issues#1815]
**Current behavior**:
Models for Winter Revelers spawned by Winter Veil event are wrong.
 Looking at the two models standing under the mistletoe in near Innkeeper Allison in The Gilded Rose in Stomwind, the male model is all black with no textures, and the female model is not dressed in the expected christmas elf clothes. 

**Expected behavior**: 
The models should be a male and female model dressed in the winter veil gear.

**Steps to reproduce**:

1. Go to any inn and look at Winter Reveler models standing under the mistletoe
2. 
3. 

**Client version**: 
1.12.1

**Commit hash**: 
mangos-classic 08eb6b67a3df9e5d90e10c721a3f342b0b97ecc3
classic-db fb87a373aa253b59af536c2bbe6fa52d049d75ea

**Database version**: 

fb87a373aa253b59af536c2bbe6fa52d049d75ea

classic-db
Classic DB version 1.9 "The Black Dragonflight". For core Classic z2717.
required_z2729_01_mangos_creature_template_faction_removal
ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

**Operating system**: 
Windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by splinecl** [comment]
![image](https://user-images.githubusercontent.com/2018961/50520179-25c1cd00-0abf-11e9-8f79-24d2ff6a4cd1.png)

**Comment by splinecl** [comment]
Screenshot of expected behavior:

![image](https://user-images.githubusercontent.com/2018961/50520846-dbdae600-0ac2-11e9-9fa9-76eb770c02c6.png)

**Comment by splinecl** [comment]
classic-db fb87a373aa253b59af536c2bbe6fa52d049d75ea

**Comment by Tobschinski** [comment]
Entry: 15760
Name: Winter Reveler
[0] CreatureDisplayID: 15750
[1] CreatureDisplayID: 15752
[2] CreatureDisplayID: 0
[3] CreatureDisplayID: 0

**Comment by AnonXS** [comment]
they use spells to change entry which defines models, fucking game event npcs

**Comment by Tobschinski** [comment]
Makes sense, if there's no use of NPC 15760 without the spells. If yes, then the model looks like in the screenshots above.

**Comment by Tobschinski** [comment]
My favorite: 
![untitled](https://user-images.githubusercontent.com/4753528/50706346-d9960000-105d-11e9-8b2e-bace2af5aeb2.png)

**Comment by AnonXS** [comment]
strange is that it seems that displayids in SMSG_CREATURE_QUERY_RESPONSE also has changed, whats the timestamp of your paste?

**Comment by Tobschinski** [comment]
Far later, Cata, I wouldn't trust it myself then. Even if they are valid models.
