### ISSUE TITLE
 Can't compile on Windows 10 x64 with Visual Studio CE and boost 1.69.0 ?

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1820]
**Current behavior**: 

Can't compile any cmangos core due to errors;

"'_snprintf': is not a member of 'std' (compiling source file C:....)..."
"cannot open file '..\..\src\shared\Debug\shared.lib'"

There isn't even any debug folder in src\shared at all, so...

![image](https://user-images.githubusercontent.com/1907820/50573384-2dd97f80-0dd3-11e9-9fd9-3e014574f0d6.png)

**Expected behavior**: 

Able to compile the cmangos cores

**Steps to reproduce**:

1. Install newest cmake, newest visual studio and newest boost
2. configure cmake
3. open the project and try to build

---
Windows 10 x64
Visual Studio Community 2017
Boost 1.69.0

**Comment by AFrdn** [comment]
if you search for std::_snprintf you should find a single occurence of this in the code base. Deleting std:: fixes the build problem

**Comment by Phatcat** [comment]
Okay, so I tried searching for it, and I'm not finding it.

![image](https://user-images.githubusercontent.com/1907820/50573551-3bdccf80-0dd6-11e9-896f-138215f8a0f8.png)

https://github.com/cmangos/mangos-classic/search?q=std%3A%3A_snprintf&unscoped_q=std%3A%3A_snprintf

Am I misunderstanding something here, or have I perhaps set up something incorrectly?

**Comment by AFrdn** [comment]
I remembered I had the same issue 2 weeks ago, but I can't find back where I changed something in the end :(

**Comment by Phatcat** [comment]
It's all good, don't worry about it, it would arguably need a proper fix project-side anyways, but it would be nice getting to build right at this moment (I could just grab the pre-builds, but I ain't admitting defeat yet)

**Comment by AFrdn** [comment]
I remember I had issues from using the most recent version of boost instead of the one recommended in the installation instructions, that might be what was causing this

**Comment by cala** [comment]
@phatcat just a wild thought: are you building in debug mode ? If so, try release mode. I can't tell you sure as I don't use VS but I remember someone having similar issue as yours and he was building in debug mode with recent boost lib.

**Comment by Phatcat** [comment]
Well, I'd hate to have to give up debug, for troubleshooting purposes, but I'll give it a try, at least it should narrow down what actually needs to be ironed out for cmangos to build on the latest cmake.

**Comment by Phatcat** [comment]
Alright, I found a solution. It's a pretty messy one but it works.

If you look in my originally posted picture, you'll notice all those errors are coming from the same file;

system_category_win32.hpp

On line 52 it reads;

std::snprintf( buffer, len, "Unknown error (%d)", ev );

And doing as @AFrdn suggested, I replaced the std::snprintf with _snprintf and now it builds without error...

Hmmm... Hmm..

**Comment by cala** [comment]
Glad you found a solution, though I agree with you  it would be better if it builds out of the box. But I'm afraid I won't be of any kind of help regarding Win build.

By the way, happy new year to you and your dears ones. 🙂

**Comment by Phatcat** [comment]
Well thank you, and happy new year to you and yours as well =)

**Comment by AFrdn** [comment]
next hurdle I met was a problem with one of the creation scripts. I made a pull request to fix it, but in the mean time you can also fix it on your local version: https://github.com/cmangos/mangos-wotlk/pull/265

**Comment by Phatcat** [comment]
Hehe, looks like someone was in such a rush to push something that they didn't get around to to test nor even visually check the code ^^

**Comment by AFrdn** [comment]
It happens when you're tired after a day of work and want to push a bunch of changes to the open source project you work on after regular work, it's fixed now.

**Comment by Phatcat** [comment]
Alright so to get cmangos to build on boost 1.66 or later without modifying boost you have to remove this line;

#  define snprintf _snprintf

from the \src\shared\Common.h file

**Comment by Muehe** [comment]
```diff
diff --git a/src/shared/Common.h b/src/shared/Common.h
index 787f5ed77..f514667de 100644
--- a/src/shared/Common.h
+++ b/src/shared/Common.h
@@ -29,6 +29,7 @@
 #include <errno.h>
 #include <signal.h>
 #include <assert.h>
+#include <boost/version.hpp>
 
 #if defined(__sun__)
 #include <ieeefp.h> // finite() on Solaris
@@ -60,7 +61,9 @@ typedef std::chrono::time_point<std::chrono::system_clock, std::chrono::millisec
 
 #  define I32FMT "%08I32X"
 #  define I64FMT "%016I64X"
+#if ((BOOST_VERSION / 100) % 1000) < 66
 #  define snprintf _snprintf
+#endif
 #  define vsnprintf _vsnprintf
 #  define finite(X) _finite(X)
```

Can somebody test this patch with boost >= 1.66 please? Seems to work fine for 1.65.

**Comment by MantisLord** [comment]
Summoning @cyberium @killerwife @Warlockbugs 

Looks like a solution has been found here for supporting newer boost versions. Which route should we take? We could remove the line entirely depending on what version of VS we want to support. Or we could use solution like @Muehe has and define it based on either Boost or VS version.

**Comment by Warlockbugs** [comment]
The issue originates in dependencies, while Common.h is a part of the project source.
Arguably the correct semantics for this workaround would be adding a global CXX definition to CMake under MSVC condition upon detecting version of the boost dependency? Something like this:
`add_compile_definitions(snprintf=_snprintf)`

**Comment by Phatcat** [comment]
I found the solution of deleting the define by asking a bit around about what could be the cause and this is the answer I got;

![image](https://user-images.githubusercontent.com/1907820/50824500-0d5f7700-1337-11e9-9d09-6d02ef4e38cf.png)
