### ISSUE TITLE
Disconnecting on a flightpath lets you fly upon logging back in

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1821]
**Current behavior**: When you force diconnect or your connection drops whilst on a flightpath, when you log back your character will come back with fly on

**Expected behavior**: Upon logging back in  flightpath should continue where left off and player should be forced to the ground as normal when the fp is over.

**Steps to reproduce**: 
https://youtu.be/v_Y1LCsYi_w
1. take a fp
2. disconnect
3. log back in and finish the fp, fly around undetered

**Client version**: 
2.4.3
**Commit hash**: 
2508cbb76849b9a3501b2f0cbcd281edcf1b00c8
**Database version**: 
1ed52b7a85aaa47e91c100e28999a396935af7bb
**Operating system**: 
Windows Server 2012 r2

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by yatzi888** [comment]
I went back to a previous core not sure on the commit but it's probz a week old and the issue isn't appearing

**Comment by AnonXS** [comment]
dupliacte https://github.com/cmangos/issues/issues/1728
