### ISSUE TITLE
[TBC] - Two mages in same party cannot refresh each other same rank 1 polymorph

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#1822]
**Current behavior**: 

Two mages in same party, first mage polymorphs creature, before the polymorph expires, the second mage attempts to polymorphs creature again before original polymorph expires.  Errors with more powerful spell is already active.  In my case I was using rank 1 polymorph with both mages.

**Expected behavior**: 

Same rank polymorph should be allowed to be reapplied by friendly player on already polymorphed creature..

**Steps to reproduce**:

1.  create two level 10 mages with polymorph spell learnt on both 
2.  party up togeather
3.  1st mage apply polymorph rank 1 to creature
4. 2nd mage apply polymorh rank 1 to same creature before original polymorph expires.

**Client version**: 

2.4.x

**Commit hash**: 

commit 618b12de43508eca6fd50fcc7d2611a9f904ec7e

**Database version**: 

commit 717da67bd86f7e96b17c01f7ec6ca31180433f4f

**Operating system**: 

8.1

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
Fixed (sort of).
This is specific to my old incomplete rewrite of aura stacking present in Classic and TBC cores.
Polymorph should not be handled the way it was. Its tired to another system currently also incomplete (that being DR).
