### ISSUE TITLE
Enchanted Item in 'will not be traded' Slot of Trade Dialog Cannot be Completed

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#1823]
**Current behavior**: 

Trade an item in 'Will not be traded' slot of trade dialog with a player that has trade skill enchanting.  The enchanter enchants and trades and you can see the enchant in the dialog but it will silently not complete the trade.

**Expected behavior**: 

Trading with an enchanter will complete with the item returned to owner with enchant.

**Steps to reproduce**:

1.  Open trade with a player that has the trade skill enchanting
2.  Place enchant-able item in 'will not be traded' slot of trade dialog
3.  Press trade
4. have enchanter enchant item and confirm visually.
5. have enchanter press trade.
6. transaction stuck at this point and cannot complete, must cancel

**Client version**: 

2.4.x

**Commit hash**: 

commit 618b12de43508eca6fd50fcc7d2611a9f904ec7e

**Database version**: 

commit 717da67bd86f7e96b17c01f7ec6ca31180433f4f

**Operating system**: 

8.1

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by al3xc1985** [comment]
Tesred a few days ago. Working, can be closed

**Comment by al3xc1985** [comment]
@killerwife close it
