### ISSUE TITLE
Quest 6624 & Quest 6622 Triage Are Broken

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#1828]
**Current behavior**: 
Item 16991 is targeting player and not NPC [12923,12924,12925,12936,12937,12938]

**Expected behavior**: 
Use item 16991 on above NPCs and cure them. May also need SD2 checked too.

**Steps to reproduce**:
1. Take Quest Triage [Alliance or Horde]
2. Use item on NPC.

**Client version**: 
3.3.5
**Commit hash**: 
b932fdf4b22c37e3ee6127af9ae5e1a8de7860e3
**Database version**: 
PSDB
**Operating system**: 
Windows 7 64bit

**Comment by MantisLord** [comment]
Cannot reproduce.
