### ISSUE TITLE
[TBC] Undeads seem to be getting Draenei Racials

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1829]
**Current behavior**: Undeads seem to be getting Draenei Racials - Gem Cutting/28875 & Gift of the Naaru 28880

https://imgur.com/eJirUa9

**Expected behavior**:  Shouldn't recieve these racials.

**Steps to reproduce**:

1. Create undead character or log to already created undead

**Client version**:  2.4.3

**Commit hash**: 3671e06eaa46e1abe5750dd47d80e5566c64e5ce

**Database version**:  26279a8054f06f06c7d673a5b8c7325524c74af6

**Operating system**:  Windows OS 2012

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
@Warlockbugs you can close this when you are done. :)

**Comment by killerwife** [comment]
Apply this to your character DB and pull newest core:
DELETE a FROM character_skills as a WHERE skill IN(760) AND guid IN (select guid from characters b where race IN(5) and a.guid=b.guid);

**Comment by Warlockbugs** [comment]
Already fixed in last commits. New characters are cured already, but DB requires a cleanup, either a db revision patch or a core auto-cleanup solution of some kind.

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/e4bc8014a8d195f3783f08a25be148271b64b00c
