### ISSUE TITLE
Quality Control Against Let's Play WoW Deathknight [Part 2]

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1831]
https://www.youtube.com/watch?v=hnXA_Mhic-4
(watch in 0.75 or 0.5)

- [ ] 1:28 (1:33) - Both the death knight initiates we see him fighting go to their knees (looks like they are doing the beg) once they are defeated. All 5 initiates I fought on cmangos did nothing but despawn once they lost.
Also, the death knight initiates you challenge to a duel should stop their other actions and focus on the player. On cmangos they will casually turn around and continue their conversation, or if it was one of the initiates who is running about the area, then they will continue running about (until the duel starts, then they'll engage you obviously)

**Comment by bdebaere** [comment]
@Phatcat Here's another video. Definitely looks like a beg. They should also say a random text before the duel begins like "No potions." or "You don't stand a chance, $N". https://www.youtube.com/watch?v=b863yUtcCzM&feature=youtu.be&t=794

**Comment by Grz3s** [comment]
duel = sd2 script... anything else is db scripting...
and probably .. i need to fix all on db side... :)

**Comment by Phatcat** [comment]
> They should also say a random text before the duel begins like "No potions." or "You don't stand a chance, $N"

Pretty sure they already do this, say the text at least.
