### ISSUE TITLE
 Elemental Mastery Proccing on Previous Spell Cast Causing no Crit or Mana Reduction

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1833]
**Current behavior**:  When a player is spamming abilities and slots in the talent elemental mastery [https://vanilla-twinhead.twinstar.cz/?spell=16166] the aura drops when the previous cast hits the target, rather than proccing on the next cast. Losing the aura from the previous spell cast doesn't make that cast benefit from the 100% crit of mana reducton. Using it on an opener or after a small delay from the previous cast works as intended.

[Video showing bug - https://youtu.be/Ep4r5ZvOqmw?t=35 ]

**Expected behavior**: Elemental mastery should be spent on the cast following it's use.

**Steps to reproduce**:

1. Roll Shaman and talent into elemental mastery [https://vanilla-twinhead.twinstar.cz/?spell=16166]
2. Spam it whilst in the middle of a spell cast
3. Watch as the cast prior to element mastery, spends the elemental mastery aura and doesnt benefit from it.

Client version: 2.4.3

Commit hash: c559b36d4e99345002f59987161bb87591bc30d4

Database version: 8de43372a43d824a3f9e5688d1f6609ab71cb775

Operating system: Windows Server 2012 R2

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by MagPurify** [comment]
I want to take a look at this, but I still haven't find any clue of when the `Clearcasting` should be used. Is it when the spell hits the mob or when the player casts a skill ? Does any one have any tip ?

**Comment by EricksOliveira** [comment]
Normally Clearcasting is activated when the player casts a spell. Clearcasting is activated when the spell reaches the target.

**Comment by jimmybrancaccio** [comment]
I would like to have this one replicated again on the latest code please.

**Comment by Yatzii93** [comment]
I can check again but I'd bet the house it's still happening. It's always brought up by my playerbase.

**Comment by berserkingyadis** [comment]
Still happening. Activated Clearcasting while the spell was on the way and it got consumed while not having an effect.

https://gfycat.com/gregariousunevengalah

tbc core commit: 4a04c15feeb570b44dae9789ebd21abadbdfd1f5

**Comment by jimmybrancaccio** [comment]
Thank you @berserkingyadis.

**Comment by killerwife** [comment]
Fixed on tbc branch as of https://github.com/cmangos/mangos-tbc/commit/731c0748e31c99174139f1871d3fb55eace85d33 

Will port to other two branches in the coming weeks.
