### ISSUE TITLE
Wrong ID for Hammersmith Axesmith Swordsmith Learn Spells

### ISSUE THREAD

**Issue by RichardGe2** [cmangos/issues#1834]
You can learn blacksmith specialties from NPCs :  "Lilith the Lithe" "Kilram" and "Seril Scourgebane".
But in the current Vanilla, it doesn't work because spell IDs are wrong

#define S_LEARN_HAMMER          39099
#define S_LEARN_AXE             39098
#define S_LEARN_SWORD           39097

should be replaced by the good spell IDs : 

#define S_LEARN_HAMMER          17044
#define S_LEARN_AXE             17043
#define S_LEARN_SWORD           17042

Also note that the Unlearn feature doesn't seem to work too.

( I didn't test BC and WOTLK )

**Comment by Warlockbugs** [comment]
The specialization unlearning mechanics from newer xpacks does not fit vanilla, there is no SPELL_EFFECT_UNLEARN_SPECIALIZATION nor spells for it. I think it left untouched in the core until further information on the subject. It may be quite possible that unlearning was not possible as of 1.12.x.
Related: https://github.com/classicdb/database/issues/262

**Comment by Warlockbugs** [comment]
Tagging @cala on the subject again.

**Comment by killerwife** [comment]
From my recollection, unlearning was not possible.

**Comment by cala** [comment]
Profession specialisation could not be unlearned back in Classic days. You chose a specialisation and it was for ever.

I'm aware some clean-up is required in Classic DB/core regarding these, I just never took the time to look at it.

**Comment by ratkosrb** [comment]
That is true for early vanilla, but after 1.10 you could choose another specialization if you unlearned the whole profession. If you installed WoW from the disk and patched it yourself, you should have file called Patch.txt in your game folder that contains the full patch notes. If you look in it, you'll find this:

> World of Warcraft Client Patch 1.10.0 (2006-03-28)
> - Players that unlearn Engineering or Leatherworking may now
>   respecialize if they decide to relearn the professions.
