### ISSUE TITLE
Poisons skill showing incorrect values and not skilling up.

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1835]
**Current behavior**: Poisen skill is showing 3157/0 and does not increase when trying to skill up.

Image: https://imgur.com/a/g7oZDX1

**Expected behavior**: Poisens should be 0/75 (pretty sure on this)

**Steps to reproduce**:

1. .learn 2842
2. Open general tab in spellbook and click on Poisons

**Client version**: 2.4.3

**Commit hash**:  fec66a2b2907c74bb88acbfbfe8d52e3b8210408
Database version: 8de43372a43d824a3f9e5688d1f6609ab71cb775

Operating system: Windows Server 2012 R2

I'll do some testing to see if I can find a previous core where I'm not experiencing this bug.

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
Looks like uninitialized value. Will be investigated.

**Comment by Warlockbugs** [comment]
Should be fixed as of:
https://github.com/cmangos/mangos-classic/commit/b76575a146d09fb2d1a4249c3984a5324cfd7041
https://github.com/cmangos/mangos-tbc/commit/8e3355c3fa8dcac3647d1bb0846a7f9732a58022
https://github.com/cmangos/mangos-wotlk/commit/ee7d297a7919cebe1659a0caa6f7dee1ca83d31c
