### ISSUE TITLE
[WotLK] db-version out of date 13990_01*.sql / 13992_01*.sql

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#1836]
**Current behavior**: Using configuration file ../etc/mangosd.conf.
World Database total connections: 2
MySQL client library: 5.7.24
MySQL server ver: 5.7.24-0ubuntu0.16.04.1
MySQL client library: 5.7.24
MySQL server ver: 5.7.24-0ubuntu0.16.04.1
SQL: SELECT required_13992_01_mangos_weapon_skills_fix_wotlk FROM db_version LIMIT 1
query ERROR: Unknown column 'required_13992_01_mangos_weapon_skills_fix_wotlk' in 'field list'
The table `db_version` in your [WORLD] database indicates that this database is out of date!

  [A] You have: --> `13990_01_mangos_playercreate_skills_wotlk.sql`

  [B] You need: --> `13992_01_mangos_weapon_skills_fix_wotlk.sql`

**Expected behavior**: mangosd start without database error

**Steps to reproduce**:

1. start mangosd
2. 
3. 

**Client version**: 3.3.5 (12340)(Release)Jun 24 2010

**Commit hash**: 1a14777956eaf4d5ace190ee0285a2770ac9e340

**Database version**: 9bb20e062d1d5f450ca6b7830b5a0b47241af1d0

**Operating system**: Server: Distributor ID: Ubuntu 16.04.5 LTS Server
                                    Client: Window & Professional
the updates do not exist in './mangos-wotlk/sql/updates/mangos

**Comment by Grz3s** [comment]
https://github.com/cmangos/wotlk-db/commit/17a5aa0cfb32aacc706ad7240938c3898f6566e7

+ make sure you have newest core

**Comment by adellaci** [comment]
@Grz3s 
Thank you It works right now.
