### ISSUE TITLE
Tauren racial cultivation not applied when learning herbalism

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#1838]
**Current behavior**: 

Tauren racial cultivation not applied when learning herbalism. Herbalism skill starts at 1/75 as it does with all other races.

**Expected behavior**: 

Tauren racial cultivation (Herbalism skill increased by 15) will be applied when a tauren race learns herbalism.  When this happens the herbalism skill should start at 15 (or 16?)/75

**Steps to reproduce**:

1.  Create tauren
2.  Learn Herbalism (TB trainer is Komin Winterhoof)
3.  Open Spellbook and Abilities,  skill page and observe incorrect herbalism skill value

NOTE: This is not just a UI issue as trying to pick an earthroot will error with 'Earthroot requires herbalism 15) which you should have from the get go as a tauren.

**Client version**: 

2.4.x

**Commit hash**: 

commit 715a550959320c89dd5507a26f2cbbd26f9d5c6a

**Database version**: 

commit 526fc2198db46191a92208480213e04425264f66

**Operating system**: 

10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
The bonus works on freshly created character, but disappears on logout. Investigating.

**Comment by Warlockbugs** [comment]
Found it, a trickier one. Due to changes introduced into loading order, at the time Cultivation was loaded, Herbalism likely has not been loaded yet, so the bonus was never applied. Whether it happened or not entirely depended on the order of skills coming from database.

Character loading was tuned accordingly.
