### ISSUE TITLE
Mage - Missile Barrage Talent

### ISSUE THREAD

**Issue by tarwyn** [cmangos/issues#184]
Rev 12428 (and prior)

Spell 54490, 54489, 54488, 54486, 44404

The talent applies itself correctly, however when it does, the duration of Arcane Missiles is correctly reduced to half (2.5 seconds), but the missiles continue to fire in 1 second intervals, resulting in only 2 of 5 missiles being launched during Missile Barrage effect. This talent needs to not only reduce the duration of Magic Missile by half, but also the missile launch interval from 1 second to 0.5 seconds.

**Comment by killerwife** [comment]
Works as intended without any changes now.
