### ISSUE TITLE
Vazruden Does Not Work Properly

### ISSUE THREAD

**Issue by Hollands09** [cmangos/issues#1842]
**Current behavior**: 
Vazruden the final boss on Hellfire Ramparts does not work.  The wrong text "Vazruden the Herald descends from the sky" is shown upon entrance into the instance but this should be shown when Vazruden is at a 10% health.  When the last guard is killed it does not set the boss fight into action.  If Vazruden is killed with .die it does not spawn the loot.

**Expected behavior**: 
Kill the 2 guards are the bottom of the ramp leading to the encounter.  Upon the death of the last guard Nazan should fly down and drop Vazruden of for the first part of the fight.  At this point Nazan should start shooting fireballs into the encounter.  Once Vazruden is at 10% of health "Nazan descends from the sky" should emote and Nazan joins the fight.  Upon death the fel iron chest is spawned and lootable.

![vazruden](https://user-images.githubusercontent.com/46874978/51447606-d9e4fb00-1ced-11e9-986b-4a27e51a360f.png)

**Steps to reproduce**:

1. Enter Hellfire Ramparts on normal or heroic.
2. Notice the text upon entrance (says Vazruden should say Nazan and its at the wrong time).
3. Travel to last boss and kill 2 guards at the bottom of the ramp and observe that the encounter does not start.  

**Client version**
2.4.3
**Commit hash**
e55071159
**Database version**
mangos_tbc
**Operating system**
Windows 10
6 Core processor
DB-MySQL
CMake 3.13.2
VS2017

https://www.youtube.com/watch?v=LEvGcXDiIw8: shows 10% health for Vazruden for Nazan to descend.

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
https://youtu.be/LEvGcXDiIw8?t=40 40% hp, emote will be fixed soonishTM and not sure if we want to make the encounter ".die" able

**Comment by MagPurify** [comment]
Took a look at this very quickly. Looks like it's because when a player run into a fresh instance. The mobs are in some kind of evade state regenerating the HP from 1 to 100%.  Since the Boss is near the player entrance his script actives the second phase.

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/fdb7d24fe40fd3e6d5601fa6bfab4c06f0a07623#diff-bd11f7f23b053005393ff29963e69542

export for text on instance entry pending

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/940f5dcc7fef898778fc99906bcf40b1a4468477#diff-bd11f7f23b053005393ff29963e69542R224
