### ISSUE TITLE
Justine Demalier's Gender

### ISSUE THREAD

**Issue by enVias** [cmangos/issues#1843]
**Current behavior**:
Justine can spawn in as either male or female.

**Expected behavior**:
Justine should always be female. (https://wow.gamepedia.com/Justine_Demalier)

**Steps to reproduce**:
1. On a GM account, teleport to Stormwind using .tele stormwind
2. Look at Justine, who is standing next to you.
3. If female model is showing, .die and .respawn Justine until the gender changes.

**Client version**:
1.21.1, 2.4.3, 3.3.5a

**Commit hash**:
Classic:  3152fd8
TBC:  8ebc483
WotLK:  c069009

**Database version**:
Classic-DB:  v1.10 'Echoes of War'
TBC-DB:  v1.7.0 'A New Hope'
WotLK-DB:  v1.1 'The Warsong'

**Operating system**:
Windows 10

![justine](https://user-images.githubusercontent.com/1429438/51448014-6a195380-1d73-11e9-8f95-846952594b06.png)

**Comment by yatzi888** [comment]
https://i.ytimg.com/vi/m7E-NFJaAgk/maxresdefault.jpg

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/7250e1df900f180fa52446db5a5ba2f9274dd5bd
