### ISSUE TITLE
Undercity Blink Teleports to Wrong Locations

### ISSUE THREAD

**Issue by MagPurify** [cmangos/issues#1844]
Current behavior:
If a player uses blink in Undercity, it will teleport to wrong locations.

Expected behavior:
Blink should respect the PathFinder, and get a point that the player can actually go.

Steps to reproduce:

.t Undercity
.learn 1953
Blink, anywhere !

Video:
https://drive.google.com/file/d/1XmbD7zfI33k_eKQHzXMkFT1FkhxDbUYD/view?usp=sharing

Client version:
2.4.3 (8606)

Commit hash:
82d8fa6a6592195ff7391e721c06a6515a8a3305

Database version:
75a7e8f722024c42a2faef3ff2106655d59b556e

**Comment by darklordsqk** [comment]
@MagPurify 
If it urged you, you may locally fix this with the simple fix procedure in #1846

**Comment by MagPurify** [comment]
Resolved here: https://github.com/cmangos/issues/issues/1846
