### ISSUE TITLE
MoveChase or MapExtraction issue, NPC walking into unreachable location. 

### ISSUE THREAD

**Issue by MagPurify** [cmangos/issues#1845]
Current behavior:
Possible MoveChase or MapExtraction problem. NPC's when chasing player is picking up terrain in unreachable locations

Expected behavior:
NPC should respect the map and move in the correct position when running to the player.

Steps to reproduce:

This have been reported for me in a couple places, but I was able to reproduce it the video below.

Video:
https://drive.google.com/file/d/10GKzXuIhtp3X-mNaUjXbSlUnnNJONAcK/view?usp=sharing

Client version:
2.4.3 (8606)

Commit hash:
82d8fa6a6592195ff7391e721c06a6515a8a3305

Database version:
75a7e8f722024c42a2faef3ff2106655d59b556e

**Comment by AnonXS** [comment]
duplicate https://github.com/cmangos/issues/issues/1720

**Comment by MagPurify** [comment]
@AnonXS, as mentioned by Killerwife, he said that this might be a possible mmap extraction, that's why I created another issue, but if you like it, I can just post the evidences there.

**Comment by AnonXS** [comment]
It is, your wording was just poor. ` NPC's when walking or running away`

.go xyz 58.88, -4601.32, 50.71, 1

**Comment by cyberium** [comment]
On my side i can confirm navmesh problem on that place that need further investigation
![](https://i.imgur.com/Gq0Stme.jpg)

**Comment by bdebaere** [comment]
@cyberium What is that? Is that software specifically for wow emus?

**Comment by evil-at-wow** [comment]
That's the [Recast](https://github.com/recastnavigation/recastnavigation) demo application, or more likely a modified version of it that recently landed in the cmangos repositories (see the contrib/recastdemomod folder).

**Comment by AnonXS** [comment]
![unbenannt](https://user-images.githubusercontent.com/19734826/51861214-f6abaf00-233b-11e9-9438-431ee1a56141.PNG)

new maps, same place, no navmesh shadow, better path
