### ISSUE TITLE
Map::GetHeightInRange leak may cause z-coordinate calc error when specifying a nagetive value. 

### ISSUE THREAD

**Issue by darklordsqk** [cmangos/issues#1846]
Mage blink in the UnderCity may reproduce this error. 

**Current behavior**: 
When a mage cast blink at the bottom of the UnderCity (with z near -60.00), it will teleport on the surface of the ground(with z near +60.00). 

**Expected behavior**: 
The blink spell's dest z-coordinate can only be similar with its start point z-coordinate. 
Blink's targetMode is TARGET_LOCATION_CASTER_FRONT_LEAP. So trace it through. 

**Steps to reproduce**:
Just blink at the lowest place of the UnderCity. Use .gps command find a place with positive and negative z-coordinate at a very near absolute value. 
Because the surface ground-z of the UnderCity is about +59.xx , while the cavern ground-z is about -59.xx , which makes the condition in Map::GetHeightInRange() get an error calc. 
The result is player blink onto the surface of the map out of the UnderCity. 

**A simple fix (need further test)**:
// File: src/game/Maps/Map.cpp
// Line: 2156
// fix diff error, to get the diff of two value needn't to put an abs() on the original values. 
    float diffMaps = fabs(z - mapHeight);
    float diffVmaps = fabs(z - vmapHeight);

**Comment by darklordsqk** [comment]
Root cause of issue #1844

**Comment by MagPurify** [comment]
Yes, it worked for me as well. Should we create a PR for that or is to risky ? Maybe infer that question to someone with more knowledge on maps

**Comment by killerwife** [comment]
Guys test the commit I just pushed. This is one of those super old missed exports of mine (and technically its what was suggested here).

**Comment by MagPurify** [comment]
Worked the same way. I will close my issue. Thanks @killerwife
