### ISSUE TITLE
Shaman - Flametongue Weapon

### ISSUE THREAD

**Issue by Lsnickels** [cmangos/issues#1847]
**Current behavior**: Flametongue does very high damage (500-600 damage per swing with 1.8 speed weapon, no spell power at rank 7) in comparison to how hard it should be hitting. The ability also scales unexpectedly. With 930 spellpower, rank 7 flametongue hits for 1000 to 1400 damage per swing with a 1.8 speed dagger.

**Expected behavior**:  Typically flametongue hits for 50-60 damage per swing with a 1.8 speed weapon and no spell power at rank 7. It should also not scale as much as it does with spellpower (or perhaps it is just a multiplier on the base damage?)

**Steps to reproduce**:

1. Using level 70 shaman, apply Flametongue Weapon Rank 7 to your weapon (any speed).
2. Auto attack any monster.
3. Observe higher damage values.

**Client version**: 2.4.3

**Commit hash**: ea58208edb97ca294961ab2a2045cfda77860ec3

**Database version**: 5d467bd4dc3bb73a4a4b4ed8629050c8cf497309

**Operating system**: Windows Server 2016

**Comment by EricksOliveira** [comment]
I think there is something wrong, rank 7 is no longer TBC and yes LK. TBC only up to rank 5!

**Comment by MagPurify** [comment]
I was able to reproduce this issue, is this DB related ?

**Comment by bdebaere** [comment]
@MagPurify My best guess is it's related to faulty data in https://github.com/cmangos/issues/wiki/Spell_bonus_data.

**Comment by yatzi888** [comment]
I fixed this issue by changing the SpellFamilyFlags to 17179869184 in the db for `Id` IN ('16343', '16344', '25488') - Flametongue Weapon Proc

17179869184 is the flag used by the totem equilant that applies the buff to party members

It seems the previous flag 2097152 caused the spell to also deal the amount of Spell Power a player has

**Comment by killerwife** [comment]
if you mean spell_template, then thats not a valid change.

**Comment by yatzi888** [comment]
Valid enough for me xD otherwise you can run Spell Power FT Shaman and pull insane dps.

**Comment by Baynar** [comment]
spell_template is extracted from the game files so it should be correct.
There seem to be only 2 entries in Spell_bonus_data for Flametongue (8026, 10444) neither seem suspicious.

**Comment by AnonXS** [comment]
Just for reference, that this topic was researched. https://github.com/cmangos/mangos-tbc/commit/1948c17ac97c10cae8d605eb42cadf48eac5fb60
