### ISSUE TITLE
Boss Prince Malchezzar Infernals are not Working

### ISSUE THREAD

**Issue by LevelOneX** [cmangos/issues#1848]
**Current behavior**: 
During Malchezzar fight, infernal relays are not appearing even though he casts the spell and the animation appears. Model doesn't appear.

**Expected behavior**: 
Malchezzar should summon an infernal in a random location every X seconds, and the infernall should cast hellfire.

**Steps to reproduce**:

1. .t Karazhan
2. Go to Malchezzar
3. Start Boss Fight

**Client version**: 
2.4.3 (8606)

**Commit hash**: 
3ec3d51ad72a1b506e8d4c0e0125898547b19dba

**Database version**: 
98dbeeba6789772c422e7d7a21c795b98ea65075

**Comment by LevelOneX** [comment]
Yes, it has. Right now it's 4,098 in my DB. On code

(GetCreatureInfo()->ExtraFlags & CREATURE_EXTRA_FLAG_ACTIVE) values is 4096.
4096 | 0×00001000 | CREATURE_EXTRA_FLAG_ACTIVE

**Comment by killerwife** [comment]
Ok, right now I can't (be bothered) to debug it. If you want to beat me to it check out the following lines of code in the core using breakpoints in debug in this order.
boss_malchezaar.cpp
relayFar->CastSpell(relayClose, SPELL_INFERNAL_RELAY, TRIGGERED_NONE);
spelleffects.cpp
                case 30834:                                 // Infernal Relay
spell.cpp
case 30835:                                         // Infernal Relay - Malchezaar - must only hit unused infernals
spelleffects.cpp
                case 30835:                                 // Infernal Relay
same file
SPELL_EFFECT_SUMMON handler - EffectSummonType

and see which part isnt reached

**Comment by LevelOneX** [comment]
It's not reaching the last part:
SPELL_EFFECT_SUMMON handler - EffectSummonType

**Comment by killerwife** [comment]
Okay, does it reach case TARGET_LOCATION_CASTER_DEST: inside SetTargetMap function in spell.cpp,
if not check Spell::CheckCast( function or Spell::CheckTarget( function.

**Comment by LevelOneX** [comment]
So it reached out to that part, I managed to make it work. The unitTarger was being removed after SetTargetMap().

I went deep and figured out that this function was returning false. https://github.com/cmangos/mangos-tbc/blob/master/src/game/Spells/Spell.cpp#L7185-L7195

I added the following lines,
                m_spellInfo->EffectImplicitTargetA[eff] != TARGET_LOCATION_CASTER_DEST &&
                m_spellInfo->EffectImplicitTargetB[eff] != TARGET_LOCATION_CASTER_DEST &&

and it worked. I just need to double check with you, if this is acceptable so I can create the PR.

**Comment by killerwife** [comment]
Ok, here is the deal. Recently I finally redid the whole lot of targeting I have been promising for all of 2018. The code you are mentioning is not even hit for that particular spell anymore. The real "hack" here is to skip checktarget for all IsDestinationOnlyEffect spells. The code is still work in progress and I expect it to make it into cmangos around maybe March. If you wish for this to be fixed for now, make a PR which will skip the CheckTarget loop inside FillTargetMap for all IsDestinationOnlyEffect spells.

**Comment by LevelOneX** [comment]
Is this fine for the PR ?
```
for (UnitList::iterator itr = tmpUnitLists[effToIndex[i]].begin(); itr != tmpUnitLists[effToIndex[i]].end();)
{
    if (IsDestinationOnlyEffect(m_spellInfo, SpellEffectIndex(i)))
    {
        ++itr;
        continue;
    }
            
    if (!CheckTarget(*itr, SpellEffectIndex(i), effException[effToIndex[i]]))
        itr = tmpUnitLists[effToIndex[i]].erase(itr);
    else
        ++itr;
}
```

**Comment by yatzi888** [comment]
@LevelOneX Could you pass me your first fix. I'd love to test it on my server.

**Comment by LevelOneX** [comment]
@yatzi888 on Spell.cpp, fill target map. 

Wrap this block of code 
```
for (UnitList::iterator itr = tmpUnitLists[effToIndex[i]].begin(); itr != tmpUnitLists[effToIndex[i]].end();)
			{
				if (!CheckTarget(*itr, SpellEffectIndex(i), effException[effToIndex[i]]))
					itr = tmpUnitLists[effToIndex[i]].erase(itr);
				else
					++itr;
			}
```
```
if (!IsDestinationOnlyEffect(m_spellInfo, SpellEffectIndex(i))) 
		{
			for (UnitList::iterator itr = tmpUnitLists[effToIndex[i]].begin(); itr != tmpUnitLists[effToIndex[i]].end();)
			{
				if (!CheckTarget(*itr, SpellEffectIndex(i), effException[effToIndex[i]]))
					itr = tmpUnitLists[effToIndex[i]].erase(itr);
				else
					++itr;
			}
		}
```

**Comment by yatzi888** [comment]
@LevelOneX Works perfect. Tested on my server. Awesome stuff

**Comment by Hollands09** [comment]
I tested it today and it seems to work perfectly.  In phase 3 Prince Malchezaar's Axes id: 17650 do 1 damage though.

**Comment by AnonXS** [comment]
Which is on another plate, hence new issue, which awaits a pending fix for it.
