### ISSUE TITLE
Shade of Aran Blizzard Issues

### ISSUE THREAD

**Issue by MagPurify** [cmangos/issues#1849]
**Current behavior**: 
Aran's Blizzard is casted, animation appears for about 1 second. Doesn't do any damage.
**Expected behavior**: 
Aran's Blizzard is casted, animation appears for the duration of the spell in his outer area. Proc damage whoever is on top of it.

**Steps to reproduce**:

1. .t Karazhan
2. .go creature Shade of Aran
3. Start Fight and Wait Blizzard to get casted (alternative .cast self 29969)

**Client version**:
2.4.3 (8606)

**Commit hash**:
3ec3d51ad72a1b506e8d4c0e0125898547b19dba

**Database version:**
98dbeeba6789772c422e7d7a21c795b98ea65075

**Comment by EricksOliveira** [comment]
I fixed it. But I can not push.

**Comment by killerwife** [comment]
So post the code here.

**Comment by AnonXS** [comment]
or you push your "fix branch" to your remote fork of cmangos, then you can create a pullrequest.

**Comment by EricksOliveira** [comment]
I can not create Pullrequest either. post here

**Comment by AnonXS** [comment]
yes because you re trying to push to this repo.

create a fork of cmangos core repo
![unbenannt](https://user-images.githubusercontent.com/19734826/51761143-9236e880-20cc-11e9-8ad4-ed8a4a2d0cd1.PNG)

set your local repositorys remote to your fork and push the fix there, then you are able to create a Pull Request.

**Comment by EricksOliveira** [comment]
I already did the PR.

**Comment by MagPurify** [comment]
Actually @EricksOliveira you have to see why it's not casting in the Script C++ like Killerwife mentioned. You are just casting another skill instead. Digging into this issue I found out that might be related to the:
https://github.com/cmangos/issues/issues/1848, because it's getting removed at the same place 
```
if (!IsDestinationOnlyEffect(m_spellInfo, SpellEffectIndex(i))) 
		{
			for (UnitList::iterator itr = tmpUnitLists[effToIndex[i]].begin(); itr != tmpUnitLists[effToIndex[i]].end();)
			{
				if (!CheckTarget(*itr, SpellEffectIndex(i), effException[effToIndex[i]]))
					itr = tmpUnitLists[effToIndex[i]].erase(itr);
				else
					++itr;
			}
		}
```
When I commented the whole code out, the spell works. Do you have another hack for this @killerwife ?
