### ISSUE TITLE
Rage Winterchill - Death & Decay

### ISSUE THREAD

**Issue by EricksOliveira** [cmangos/issues#1850]
**Current behavior**: 

When casting the spell (Death & Decay = ID 31258) if the player moves the boss, the cast is cut and the spell is intercepted.

**Expected behavior**: 

When casting the spell (Death & Decay = ID 31258) even if the player or boss is moving, the spell cast must not be intercepted.

**Steps to reproduce**:

1. Stanza Hyjal Summit
2. Complete the wave to the boss Rage Winterchill
3. Wait for the Death & Decay cast and move on the stance.

**Client version**: 
2.4.3 (8606)
**Commit hash**: 
7f9963d30cd5c03db5ca1429fa9112ffb05f6a59
**Database version**: 
98dbeeba6789772c422e7d7a21c795b98ea65075

**Comment by AnonXS** [comment]
general issue with lots of npcs that channel a certain ability, when current topaggro leaves a certain radius they might interrupt themselves to start chasing.

**Comment by EricksOliveira** [comment]
But it does not even need to go away, if you just move the cast is cut

**Comment by EricksOliveira** [comment]
I'll take a look. As far as I know this spell there should be no interruption. Well all the mechanics I saw were like that.

**Comment by killerwife** [comment]
All of hyjal will be revamped in cmangos the way T5 was done in one big push. Sometime this year, no eta.

**Comment by berserkingyadis** [comment]
Was this fixed by the mentioned export in 2019?

**Comment by killerwife** [comment]
Resolved.
