### ISSUE TITLE
Unknown taxi error with PVP flight master in eastern plaguelands

### ISSUE THREAD

**Issue by cala** [cmangos/issues#1851]
**Current behavior**:

After capturing Plaguewood tower in the Eastern Plaguelands, players can speak with the Griffon master NPC 17209 (William Kielar) and ask him through gossip menu options to get a taxi flight to one of the three other towers. When selecting any of the three options, "Unspecifed taxi server error" is displayed and nothing happens. 

I'm poking @Warlockbugs on this as he is the most expert on taxis. Note that this error was already existing before the changes you made in the past months.

The error name is puzzling and I did not find what exactly causes this: scripts and DB content are similar to TBC-DB and WotLK-DB content and the taxis are working in TBC core. So, this is a Classic-only issue.

To properly test this, the following SQL needs to be applied first (the tower capture scripts are currently missing):
```SQL
-- Adds script spawning NPC when a tower is captured in Eastern Plaguelands
DELETE FROM dbscripts_on_event WHERE id IN (10691, 10692, 10700, 10701);
INSERT INTO dbscripts_on_event (id, delay, command, datalong, datalong2, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(10700, 0, 10, 17209, 0, 0, 0, 8, 0, 0, 0, 0, 2987.5, -3049.11, 120.126, 5.75959, 'Horde Plaguewood Tower progress event - summon William Kielar'),
(10701, 0, 10, 17209, 0, 0, 0, 8, 0, 0, 0, 0, 2987.5, -3049.11, 120.126, 5.75959, 'Alliance Plaguewood Tower progress event - summon William Kielar');
```

**Expected behavior**: 

When choosing one of the three gossip menu options, the player should mount the skeletal griffon and fly to the selected tower destination.

**Steps to reproduce**:

1. `.tele eastern` and then `.go 2987 -3042 120`
2. force activate PVP flag depending on server settings and wait for the tower to be captured and NPC 17209 to appear
3. Speak with him and pick any of the three gossip menu options available

**Client version**: 

1.12.1

**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/9f37df9bf43fdaa85ca0924a30cfdfa00b774b54

**Database version**: 
Classic DB v1.10

**Operating system**: 
mac OS and Win 7

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Warlockbugs** [comment]
The error was inherited because i preserved mount displayid check. Model seems to be missing here:

    // Can't add taxi path without mount display id unless specified otherwise
    uint32 displayId = sObjectMgr.GetTaxiMountDisplayId(entry->from, m_owner.GetTeam(), commercial);
    if (requireModel && !displayId)
        return false;

The taxi node has creature id 17660 defined, but we lack template for it later there:

    CreatureInfo const* mount_info = GetCreatureTemplate(mount_entry);
    if (!mount_info)
        return 0;

Proposed solution: db needs template for creature 17660. No core changes needed.

**Comment by killerwife** [comment]
@cala TBC has the entry. Also,
https://www.wowhead.com/npc=17660/skeletal-gryphon

**Comment by cala** [comment]
If it is that simple, I'll fix this very soon.

The error message being non-explicit I did try to track it in the code, but I did not go deep enough to find this was model related before I gave up at the node check part.

Thanks!
