### ISSUE TITLE
SSC - Leotheras the Blind - Boss Spell is Applying as a Buff Instead of a Debuff

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1852]
**Current behavior**: SPELL_CHAOS_BLAST = 37675 should put a fire debuff on the player but instead it's applying as a buff. This means the player can right click it off.

**Expected behavior**: SPELL_CHAOS_BLAST = 37675 aura should apply as a debuff 

**Steps to reproduce**:

1. target self
2. .aura 37675
3. 

**Client version**: 2.4.3

**Commit hash**: 4589c7b22866e86bfd29eb0ecd3c85aff45d42d1

**Database version**: c3ac98f8838b4318c3819485e3bae40f8e645052

**Operating system**:  Windows Server 2012 r2

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by yatzi888** [comment]
If someone could point me in the dirrection of what makes a aura friendly or not, I'd love to sort this out myself and any other cases I come accross. :) Need an expert for advice

**Comment by yatzi888** [comment]
@killerwife Is that as simple as adding 26 to the spell attribute colum (spell_template table)?

**Comment by killerwife** [comment]
UPDATE spell_template SET Attributes=Attributes|0x04000000 WHERE Id = 37675; -- Chaos Blast - Leotheras

Yes. I will export it, but not atm.

**Comment by yatzi888** [comment]
@killerwife Legend! Works a treat.

**Comment by killerwife** [comment]
Fixed a long time ago.
