### ISSUE TITLE
Cast Auto-Selection Buff to Low Level Player and the Original High Level Spell Won't Finish Properly

### ISSUE THREAD

**Issue by darklordsqk** [cmangos/issues#1860]
**Client version**: 
wow classic 1.12

**Current behavior**: 
High Lv buff spell will add a auto-selection buff of low Lv in spell chain well. But buff spell of original level on the client won't finish casting. you have to press Esc to stop casting manually, or else cast other spell will get busy 
now info. 

**Expected behavior**: 
The original spell of high level will finish casting automatically. 
The server may send all two either SPELL_FAILED_* or SPELL_CAST_OK to both high level spell and related auto-selected low level spell. 

**Steps to reproduce**:
Just pick a Lv60 Paladin and a Lv1 role. Then Buff Lv1 with a HIGH level blessing spell. 

The original high level spell on client won't receive SpellCastResult, 
So a maybe working fix I think is this: 

// File: src/game/Spells/SpellHandler.cpp
// Function: void WorldSession::HandleCastSpellOpcode(WorldPacket& recvPacket)
// Line: 375 - 385
        if (SpellEntry const* actualSpellInfo = sSpellMgr.SelectAuraRankForLevel(spellInfo, target->getLevel()))
        {
            // try SPELL_FAILED_DONT_REPORT to fix auto-selection buff on low level
            if (actualSpellInfo->Id != spellInfo->Id)
            {
                Spell* prevSpell = new Spell(_player, spellInfo, false);
                prevSpell->SendCastResult(SPELL_FAILED_DONT_REPORT);
            }
            spellInfo = actualSpellInfo;
        }

**Comment by jimmybrancaccio** [comment]
@darklordsqk Please provide the commit hash for your core and database.

**Comment by darklordsqk** [comment]
> @darklordsqk Please provide the commit hash for your core and database.

@jimmybrancaccio 
core version was a2ebef85b92f9acb3194d4dcd59c7d55f7634dfd
db version was dea8a314ad60968ab02d6b32fbf6d584c933cb62

**Comment by darklordsqk** [comment]
> This shouldn't happen on classic.

It did happen on classic. And I don't think this issue have any relationship with the database. 
It's all core's problem. the code in SpellHandler.cpp shows that a spell will check if there is an auto-select related spell before server send SMSG. And if it has, only the low level spell will triggered well. the original spell won't get a SpellResult from the server so that the client got stucked.

**Comment by Phatcat** [comment]
> It did happen on classic.

Yes it did. With macros. I already proved this earlier in the issue I linked;

![image](https://user-images.githubusercontent.com/1907820/52630534-c11ad000-2ebc-11e9-860c-9987b67d6d58.png)

**Comment by darklordsqk** [comment]
> I don't know if you're saying

I mean it did just happen on cmangos classic core. You know, there is NOT only a single version of wow client that can adapted on cmangos core. And I'm not sure if it's only happened on my client version. 

Btw, either I don't know if 
> With macros.
means that the auto-select spell was completed on the client side with a macro. If it dose, where can I find this macro. 
Or in other words, Did you mean this issue only happened with some modified version of 1.12 clients?

**Comment by Phatcat** [comment]
Once cmangos-classic behaves like it should and say that the target is too low level for the buff then yes you'll need a macro. the macro depends on which spell you wanna cast but I'm pretty sure someone has made a template... [or something](https://forum.nostalrius.org/viewtopic.php?f=44&t=25006#p188920).

But it has nothing to do with the player getting stuck in cast, that's something else.

**Comment by darklordsqk** [comment]
> But it has nothing to do with the player getting stuck in cast, that's something else.

I think player getting stuck in cast in this case DO have relationship with auto-selection implementation in cmangos core side. You could check the code in 
// File: src/game/Spells/SpellHandler.cpp 
// Function: void WorldSession::HandleCastSpellOpcode(WorldPacket& recvPacket) 
The original reason why player casting stuck happened is that the **spellInfo** is different from **actualSpellInfo** after called **sSpellMgr.SelectAuraRankForLevel()**. 
And only the new **actualSpellInfo** will go on **SpellStart()** proc, while the old **spellInfo** won't got any feedback from the server. 
If the original classic wow ought to feedback TARGET_LEVEL_TOO_LOW to client, why the **sSpellMgr.SelectAuraRankForLevel()** appeared in this code block. 
So when this happened, it just perform like your network jamed and the spell casting won't finish. 
In this case, it was NOT the spell can't receive **CastingResult** due to network lag, BUT the server ignored the original the triggered spell itself, which caused this stuck. 
Therefore, IMO, the easiest way to fix that on cmangos is just sending a SPELL_FAILED_DONT_REPORT for the original spell to the client. 

Still, to me, it's hard to determine where this unhandled spell result should belong to (server side or client side). 
Although I still have some confusion, I gonna locally fix this by checking whether the spell_id is different from before and after auto-select proc.

**Comment by bdebaere** [comment]
@darklordsqk You're assuming that that code is there for a valid reason, which is never a good assumption when dealing with code written over the span of decades by multiple people who have come and gone. Most likely this code was added for TBC purposes and was left in there for classic.
So, if @Phatcat is correct, instead of trying to automatically downrank and failing which in turn leads to casting being stuck it shouldn't even try to downrank. Which means this issue can be closed and the focus should instead be on returning an error message stating the target is too low level.

**Comment by darklordsqk** [comment]
@bdebaere Therefore, the discussion was posted in the issue section of c-mangos project but not in a PR section. I'm not a guy who knew the details of WoW well. All I can do is just point out the issue that I think is abnormal in game playing and explain why there might happen in my own view. The main purpose of this issue is to report to the dev team that the Buff Spells would get stuck while casting to a low-level target. 
An issue is an issue, dude~ It's about the phenomenon of the abnormal behavior of casting buff on low-levels. Of course there are NOT only ways to fix it in code level. And I'm not the guy to decide which way should be chosen to fix this issue. XD

**Comment by bdebaere** [comment]
@darklordsqk It's okay, my comment was not meant as a personal attack. It's merely how I view this issue and what should happen with it. I've seen some weird code in a lot of different companies. All I'm saying is, just because it's there doesn't mean it should be there.

**Comment by jimmybrancaccio** [comment]
Closing this issue out. If anyone is still having a problem, please open a new issue with full details.

**Comment by Phatcat** [comment]
Jimmy, you got to be joking. This issue is still very much present. Reopen this issue and stop messing around. This is ridiculous and damaging to the development progress of the project. You going around hiding issues. You thin it's funny or something?

**Comment by jimmybrancaccio** [comment]
@Phatcat You need to chill out. Be respectful.

Issue has been reopened, however I would like it to be replicated again on the latest code.

**Comment by al3xc1985** [comment]
on current state is working perfect... at least tested on tbc.. and I believe by exports it is working in classic 2
@killerwife  can we close it?
