### ISSUE TITLE
Target Dummy sharing cooldown with unrelated items

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1861]
**Current behavior**: 
Masterwork Target Dummy shares cooldown with Night Dragon's Breath/Whipper Root Tuber

**Expected behavior**:
They probably shouldn't? One is a healing item the other is a summon guardian item.

**Steps to reproduce**:
1. .Additem 16023
2. .Additem 11951
3. .Additem 11952
4. Use the whipper root or the night dragon and watch masterwork target dummy get put on cooldown

**Client version**: 
cmangos classic

**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/a2ebef85b92f9acb3194d4dcd59c7d55f7634dfd

**Database version**: 
https://github.com/cmangos/classic-db/commit/f050cb5eb898cabcdbab3bb8b79742bd6ccdfdd0

**Operating system**: 
Windows 10

**Comment by lduguid** [comment]
Take with a huge grain of salt as it is wowhead, however https://classic.wowhead.com/item=16023/masterwork-target-dummy#shared-cooldown

**Comment by Phatcat** [comment]
Hmm, well I got no evidence saying it shouldn't, so.
