### ISSUE TITLE
Units Can Not Leave Water After Aggro

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1862]
**Current behavior**: 
If you start combat, units can not leave water, only stay and doing nothing.
video:
https://radikal.ru/video/RNI1r6apE6N

**Expected behavior**: 
Units should move to player.

**Steps to reproduce**:
1. go to the blackfathom deeps
2. move to the first murloc as on video
3. aggro him
4. go out the water

**Client version**: 
2.4.3
**Commit hash**: 
e7a262d2c6b25ec3cae1dd66f83a0445cb0d4109
**Database version**: 
e85c8f0e307ed735adde9fea6e4b8627c7932ab6
**Operating system**: 
win64

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by AnonXS** [comment]
npc entry?

**Comment by datchannin** [comment]
npc=4818

**Comment by Grz3s** [comment]
also confirmed for wotlk.. 
strange that the same npc spawned outside water will chase you into lake ... and will get out of it with no issues...
only guids spawned inside water having this poroblems ...

**Comment by adellaci** [comment]
I have seen the same issue leaving starting area for Draenei, doing the fishing quest.

**Comment by CabrasDaPeste** [comment]
I've seen some mobs do the same in mangos-tbc in Zangarmarsh.

**Comment by Grz3s** [comment]
problem is not creature or its inhabittype....
Issue comes from MMAPS ...  with them turned OFF ... creatures will react correct...

**Comment by yatzi888** [comment]
@Grz3s THis can be tested right you can disable MMAP checks in db for a creature if I'm not mistaken

**Comment by bdebaere** [comment]
@yatzi888 https://github.com/cmangos/issues/wiki/creature_template#extraflags
UPDATE creature_template SET ExtraFlags = ExtraFlags | 16384 WHERE entry = 4818;

**Comment by al3xc1985** [comment]
confirm this bug,,,, @Grz3s  is right

**Comment by Auxil3300** [comment]
This is still a major issue with several instances where water exists, it appears to be working correctly in the out-world however.

**Comment by AnonXS** [comment]
Same as https://github.com/cmangos/issues/issues/2986
