### ISSUE TITLE
[TBC] Warlock Void's Spell "Consume Shadows" Target

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1863]
**Current behavior**: 
If you try to use Void's Spell Consume Shadows while you have a targer - void will start attack instead of use the spell. The same issue with him Suffering spell.
video: https://radikal.ru/video/GBkV8Ek74UV
**Expected behavior**: 
Void should use his spell if you press the spell button.

**Steps to reproduce**:
1. Target enemy
2. Use Consume Shadows 

**Client version**: 
2.4.3
**Commit hash**: 
e7a262d2c6b25ec3cae1dd66f83a0445cb0d4109
**Database version**: 
e85c8f0e307ed735adde9fea6e4b8627c7932ab6
**Operating system**: 
win64

**Comment by AnonXS** [comment]
duplicate https://github.com/cmangos/issues/issues/1513
