### ISSUE TITLE
Curse of Recklessness Using Give Unit Possibility to Evade all Attack

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1864]
**Current behavior**: 
If you use Curse of Recklessness and then make unit flee - he starts evade all attacks. And if you kill him using .die and resp him using .resp - he still will evade all your attacks. And unit will stop his auto-attacks too. He will use only his spells.
Video:
https://radikal.ru/video/xl6nYaFcbDZ

**Expected behavior**: 
Unit should work as usually
**Steps to reproduce**:
1. Use Curse of Recklessness on humanoid.
2. Reduce his health below 15%
3. Wait for his flee.
4. Try to damage him.

**Client version**: 
2.4.3
**Commit hash**: 
e7a262d2c6b25ec3cae1dd66f83a0445cb0d4109
**Database version**: 
e85c8f0e307ed735adde9fea6e4b8627c7932ab6
**Operating system**: 
win64

**Comment by BenDol** [comment]
Unable to reproduce this on the latest TBC core/db
