### ISSUE TITLE
Rogue Can Not Use Riposte Against Units Without Weapon

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1866]
**Current behavior**: 
Rogue Can Not Use Riposte Against Units Without Weapon. Spell become active, but use can not use it (invalid target). Seems it can not been used after disarm core patch.
Gamepedia says after 1.6.0 spell should deal damage
![image](https://user-images.githubusercontent.com/39913306/52304362-a4a20380-29a3-11e9-8f40-a23c3b73291f.png)

**Expected behavior**: 
Rogue should use riposte for damage, but disarm aura should not be applyed
**Steps to reproduce**:
1. Take Riposte talent
2. Wait proc after parry against enemy without weapon
3. Try to use

**Client version**: 
2.4.3
**Commit hash**: 
e7a262d2c6b25ec3cae1dd66f83a0445cb0d4109
**Database version**: 
e85c8f0e307ed735adde9fea6e4b8627c7932ab6
**Operating system**: 
win64

**Comment by AnonXS** [comment]
@Warlockbugs

**Comment by Phatcat** [comment]
Seems like we're having the same issue Blizzard did before patch 1.5.0 - lol look they said they fixed it in 1.4.0 as well but they can't have or they broke it again during 1.4.x xD

**Comment by Warlockbugs** [comment]
This is a known weakness of our (and i think almost every other emulator) spell system - lack of partial application. During spell preparation we need to evaluate each individual effect and after this decide which effects should be applied on per-target basis. Current nature of CheckCast abomination is "apply all or nothing" and its virtually impossible to change that without ripping it apart at this point.

**Comment by Phatcat** [comment]
> Current nature of CheckCast abomination is "apply all or nothing" and its virtually impossible to change that without ripping it apart at this point.

But abolish poison works even if the target is not poisoned? Is that one hackfixed?

**Comment by Warlockbugs** [comment]
It probably is, i'll look into it. Not much else can be done without remaking the system anyway.

**Comment by Phatcat** [comment]
https://github.com/cmangos/mangos-classic/commit/916e476f17c66fa218dd83727c6c334e3cc5f995

hmmm

**Comment by killerwife** [comment]
This has been resolved with partial application.
