### ISSUE TITLE
Crowd Control and Running Out of Range

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1867]
**Current behavior**: 
Use sap spell (rogue control). 
Start combat, but your target should be still under sap (you can do it if, for exampl,e use dagger throw with small skill of dagger throw).
Then run away from your enemy and wait several minutes. You will stay in combat until you mave back to your target. The same is for druide Hibernate spell. May be the same is for mage polymorph.
Video:
https://radikal.ru/video/zSlfWLVIkpM

**Expected behavior**: 
Enemy should drop threat after you move for 40 yards, may be after Sap aura expired.

**Steps to reproduce**:
1. Use sap.
2. Move away
3. Wait several minutes and check that you in combat

**Client version**: 
2.4.3
**Commit hash**: 
e7a262d2c6b25ec3cae1dd66f83a0445cb0d4109
**Database version**: 
e85c8f0e307ed735adde9fea6e4b8627c7932ab6
**Operating system**: 
win64

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/146690755-e0673ee4-90db-4a2c-99e0-1c3e82572fe1.png) player gets in combat with missed throw in sapped target

![grafik](https://user-images.githubusercontent.com/19734826/146690768-8a3a77e8-512b-48cd-81ff-77f6b5befd64.png) combat drops at about

![grafik](https://user-images.githubusercontent.com/19734826/146690873-2b10ec29-ff8c-468e-8fcd-765203cce569.png) npc stays sapped and in combat after player drops combat

if any step of this is still wrong, report in a new issue.

```
Expected behavior:
Enemy should drop threat after you move for 40 yards, may be after Sap aura expired.
``` is resolved "at ~50y"
