### ISSUE TITLE
Priest - Shadow Word: Death

### ISSUE THREAD

**Issue by Azelen** [cmangos/issues#187]
hello, priest's SW: D self-damage procs negative priest's talents (like shadow weaving and blackout) on self, this shouldn't happend.

**Comment by Warlockbugs** [comment]
Fixed in:
https://github.com/cmangos/mangos-tbc/commit/d99037131a31893920219fd7d7720a7c94d70c96
https://github.com/cmangos/mangos-wotlk/commit/21f2f0040f07879a2d6d2cb5449d389e75fac63c
