### ISSUE TITLE
Very shallow water dismounts players.

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1874]
## 🐛 Bugreport

https://youtu.be/ZjtfA9mkYkM - Cords - X: 2966.2 Y:5495 Z: 144 Area: 3951 Zone: 3522 Map: 530 - or the whole of Zangarmarsh which has now become a new form of the game 'the floor is lava' ^.^

Puddles dismount players since the recent changes : https://github.com/cmangos/mangos-tbc/commit/4a14e2fa36080e83e906eb7f18f1a53d39d0f970

### Expected behavior

As set before, players should be able to mount over puddles and not get dismounted

### Version & Environment
 
Client Version: [] 2.4.3

CMaNGOS Repo & Commit Hash:  []() https://github.com/cmangos/mangos-tbc/commit/7ee8c009e026034ed70693cd88e01c943d4f697f

Database Repo & Commit Hash: []() https://github.com/cmangos/tbc-db/commit/a97ab9423ded83e67a06d8a2a11a88b113df2f60

Operating System: []
Windows Server 2012 R2
### Steps to reproduce
1. Mount
2. Run over a puddle in the world
3. Cry as you dismount

### Crashlog

- [X] None

**Comment by Levitanious** [comment]
What the build options? Are mmaps used?

**Comment by yatzi888** [comment]
> 
> 
> What are the build options? Are mmaps used? Using pre-extracted resources or extracted them yourself?
> 
> Any screenshots?

Extracted myself. I have a video 2 secs.

**Comment by yatzi888** [comment]
https://youtu.be/ZjtfA9mkYkM

**Comment by Levitanious** [comment]
It's important to record `.gps` coordinates, thanks for the video, though.

**Comment by yatzi888** [comment]
Sorry! X: 2966.2 Y:5495 Z: 144 Area: 3951 Zone: 3522 Map: 530 - or the whole of Zangarmarsh which has now become a new form of the game 'the floor is lava' :D

**Comment by Levitanious** [comment]
I suggest you to edit your issue with new info to make it easier for others to help.

**Comment by yatzi888** [comment]
Wait I may need to do a more up to date map extraction. Let me give it a try.

**Comment by darklordsqk** [comment]
This issue happened since the MirrorTimer Update.

**Comment by CabrasDaPeste** [comment]
Confirmed.

**Comment by Levitanious** [comment]
Possibly related: https://github.com/cmangos/mangos-tbc/commit/4a14e2fa36080e83e906eb7f18f1a53d39d0f970#diff-045615fdac3a8bdfe4398682397a2d86R20463
(Thanks, @Phatcat)
