### ISSUE TITLE
Chicken Issues (CLUCK!)

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1875]
## 🐛 Bugreport
The chicken carries on it's business after it's been made friendly.
The player is the one laying the egg
The faction the chicken takes on is friendly even to horde players in classic and tbc.
~The emote that the chicken does on /cheer is incorrect~ fixed

### Expected behavior
- The spell that spawns the egg seems to be coming from the player and not the chicken making it seem like the player laid the egg.. obviously should be coming from the chicken
- The chicken when it is 'activated' needs to stay in place and not move until it resets
- ~The emote that the chicken does on /cheer is incorrect, should be the one that is currently not i use~ fixed
- In classic and tbc the chicken would become friendly only to alliance as per this comment (and many others from horde players saying they can't interact with it after they got the emote);
https://www.wowhead.com/quest=3861/cluck#comments:id=556749
>After maybe 40-50 repetitions, I got the message "Chicken looks up at you quizzically. Maybe you should inspect it?" (I'm actually copying this verbatim from my screen.)
>
>I got excited and turned towards the chicken to discover that it did NOT have the question mark over its head, nor did my cursor change to the gear when I hovered over it. The cursor remained a sword.
>
>Instead, the guard over at the town boundary RAN OVER AND KILLED THE CHICKEN!
>
>That has to have been the single funniest thing I've seen while playing this game. Apparently, activating the quest script got the chicken flagged as an Alliance chicken. Ha ha ha!

### Version & Environment
Client Version:
Any

CMaNGOS Repo & Commit Hash:
Classic (but applies to all) [185e72c04cc518064665fd66c7730aae69d6c468](https://github.com/cmangos/mangos-classic/commit/185e72c04cc518064665fd66c7730aae69d6c468)

Database Repo & Commit Hash: 
Classic (but applies to all) [51c204856d0dbaf59f06e56644874ea5e6fb4b92](https://github.com/cmangos/classic-db/commit/51c204856d0dbaf59f06e56644874ea5e6fb4b92)

Operating System:
Any

### Steps to reproduce
1. Make a level 1 alliance char
2. .tele westfall
3. get special chicken feed
4. find a chicken and do /chicken a bunch of times
5. accept the quest and feed the chicken

**Comment by Levitanious** [comment]
> The player is the one laying the egg

Please.

**Comment by Phatcat** [comment]
because the quest is alliance only in both classic and tbc so if you want to reproduce this on classic you'd have a hard time as a horde.

Also that is the issue, some quest reward spells are wrongfully cast by the player themselves when it should be the questgiver casting them, we already looked into this in the past but it seems things are more complex than implemented, this quest is one such quest, and so since it's the player casting the spell it's the player laying the egg. Just go try it out.

**Comment by Phatcat** [comment]
I already did a bit of work towards this, corrected the emotes;
https://github.com/cmangos/mangos-classic/pull/380
