### ISSUE TITLE
Tracking Feature is Not Working Properly

### ISSUE THREAD

**Issue by Nett118** [cmangos/issues#1876]
The tracking feature of the interface that enables players to track resource nodes, mobs, or NPCs on the mini-map is not acting correctly. The magnifying glass control on the border of the mini-map allows the player to choose which types of tracking to enable. Some forms of tracking are restricted to certain classes and professions. From what I can tell most of the professions are not changing when chosen and some do not initiate the tracking. Going to the players spell book is necessary for tracking of those professions… Find herbs/minerals, track beasts/demons…### Version & Environment

Client Version: [ "3.3.5a" (WOTLK)]

CMaNGOS Repo & Commit Hash: 
WOTLK(https://github.com/cmangos/mangos-wotlk/tree/b99e2a81042cfc517b6aac7cb95892c277d66ba7

Database Repo & Commit Hash: 
PSDB

Operating System: 
Windows 7 64-bit

### Steps to reproduce
1. Start server
2. Log in
3. Click Tracking Icon
4. ...Choose Find Herbs/minerals or other from profession

**Comment by al3xc1985** [comment]
I can confirm this bug

**Comment by ekg98** [comment]
I can confirm that hunters tracking spells can be stacked in the mini map.  I can have more than one running at a time.

I also confirm that the mining tracking icon doesn't appear on the mini map.  The little one that is supposed to be where the hour glass is.  I am not sure if any of the hunters tracking supposed to appear there aswell.

**Comment by killerwife** [comment]
@Warlockbugs

**Comment by Warlockbugs** [comment]
Fixed by https://github.com/cmangos/mangos-wotlk/commit/bfe21d4acdece9b7bbda275d5c60cc9ffa5fa067
