### ISSUE TITLE
Using playerbots - when bot Is commanded to 'repair all' the server loops

### ISSUE THREAD

**Issue by zslg01** [cmangos/issues#1878]
## 🐛 Bugreport
A playerbot needed repair. Went to Ironforge, got close to repair vendor, told bot to repair (/t nnn repair all).
### Expected behavior
Bot should repair then be ready to go
### Version & Environment
"3.3.5a" (WOTLK)

Client Version: 3.3.5a patch 12345

CMaNGOS Repo & Commit Hash[WTOLK] 37ba423ffec1254d417c469b87bc8b644006bc13

Database Repo & Commit Hash: WOTLK-DB a586dd82f1557f7dc9df926f94faf4a0171000d0

Operating System: MacOS

### Steps to reproduce
1. Logon, add bot, battle NPC
2. proceed to repair NPC
3. /t nnn repair all

### Crashlog

- [X] None

**Comment by zslg01** [comment]
Had to Ctrl-C server to get out. It was in a loop. I got a MacOS sample of execution stack if that helps.

**Comment by Baynar** [comment]
on TBC playerbots crash none-stop
Example attack a mob while using a player bot = server crashes when bot tries to cast a spell.

**Comment by cala** [comment]
@zslg01 As a notice, the server does not crash with Playerbot on Classic when using repair all. On the other hand, the command does not work and return an error as the package length seems to be wrong. I will investigate that.

@Baynar We would need a dedicated issue and more details because this is too vague a report.

**Comment by cala** [comment]
The bug in Classic with the repair command is fixed in 
https://github.com/cmangos/mangos-classic/commit/63cf163063416968a8aba85096c288b1a9d17b82
I'll take care of the TBC/WotLK issue when I'll port the various PlayerBot fixes along with this one.
