### ISSUE TITLE
Priest suddenly unable to use Shadowform 'Spell not ready' requires relogging to fix

### ISSUE THREAD

**Issue by yatzi888** [cmangos/issues#1879]
## 🐛 Bugreport

A priest specced into shadow something may find themselves in a situation where they can't click shadowform, they get a message saying the 'spell is not ready' and it seems the only fix is a relog.

### Expected behavior
Shadowform should be castable aslong as the priest has mana, it shouldn't randomly stop allowing the user to use the spell

Client Version: [] 2.4.3

CMaNGOS Repo & Commit Hash: [cmangos/mangos-tbc@7ee8c00](https://github.com/cmangos/mangos-tbc/commit/7ee8c009e026034ed70693cd88e01c943d4f697f)

Database Repo & Commit Hash: [cmangos/tbc-db@a97ab94](https://github.com/cmangos/tbc-db/commit/a97ab9423ded83e67a06d8a2a11a88b113df2f60)

### Steps to reproduce
At this time I can't seem to find a solid way to recreate the problem, all I know is it happens a fair amount and it can be frustrating for people who play this class. Will continue to investigate and update if find out more.
1. Use Shadowform as a priest whilst it's on GCD

### Crashlog

- [X] None

**Comment by darklordsqk** [comment]
Hmmm. Seems that the aura immune proc bugged. 

#1880 is the same **Spell Not Ready** issue I had found yesterday. 

Shadowform & Stealth are both some kind of **Shape Shift Mask** which provide by spell aura. 
While these kind of auras got immune by some reasons, the original spells got stuck. (replied with "Spell not ready") 

SO, I think these 2 issue may cause by a same root.

**Comment by yatzi888** [comment]
Confirming the fact that it seems to be a problem with clicking the form whilst it's on a GCD

**Comment by LevelOneX** [comment]
I have seen players reporting that, but not sure how to reproduce it 100%.

**Comment by al3xc1985** [comment]
maybe it shares the problem with the aura system? and it might be linked with https://github.com/cmangos/issues/issues/1876

**Comment by keyshuwen** [comment]
Do it in this way.
Quickly press the keyboard One Two Three.
It will cause such problems.
Repeat several times.

1. cast spell  Keyboard shortcut Three.
![1](https://user-images.githubusercontent.com/4241825/59158206-ac0c2180-8ae9-11e9-96c9-c2ed6b99179a.png)

2.Crazy Press of Shortcut Key in Foundry Process One two. 
![2](https://user-images.githubusercontent.com/4241825/59158265-07d6aa80-8aea-11e9-9d43-99049ffc8190.png)

3.There is a certain probability.
![3](https://user-images.githubusercontent.com/4241825/59158281-597f3500-8aea-11e9-96e9-79219393b8b2.png)

Sorry, my English is not very good.   :(

**Comment by berserkingyadis** [comment]
Definetly not easy to reproduce, I spend like 10 minutes straight and now with numb fingers I recommend writing a AutoHotkey script or something. 😛

**Comment by keyshuwen** [comment]
I think it's GCD.

Cast the last 10% , and press the shortcut key.

It should be easy to implement.
emmmm......

I don't understand why.
This problem has existed for more than a year.  :(

**Comment by ulfgebhardt** [comment]
@keyshuwen can you please submit an contribution for a fix? <3

**Comment by keyshuwen** [comment]
@ulfgebhardt 
I don't know how to fix it.
I don't understand why.
Everything is speculation.   :(

**Comment by keyshuwen** [comment]
@ulfgebhardt 

More testing is needed.   :(

    // check global cooldown
    if (strict && !m_IsTriggeredSpell && m_caster->HasGCD(m_spellInfo))
        return !m_spellInfo->HasAttribute(SPELL_ATTR_DISABLED_WHILE_ACTIVE) ? SPELL_FAILED_NOT_READY : SPELL_FAILED_DONT_REPORT;

**Comment by keyshuwen** [comment]
@BenDol   

Do you have any good suggestions?  :)

**Comment by BenDol** [comment]
Check the latest PR for the solution.

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/3c73168139b57a869847fdb44caa5111136ed462

**Comment by AHalici** [comment]
Dying fixes this
