### ISSUE TITLE
Faerie Fire based Spells & Items will cause Player cannot go into Stealth in some case. 

### ISSUE THREAD

**Issue by darklordsqk** [cmangos/issues#1880]
## 🐛 Bugreport
Trying to cast Stealth family spell while having Faerie Fire based debuff will make the Stealth spell become invalid permanently. (Neither go cooldown nor become available after Faerie Fire debuff disappeared.)
Unless you logout or cast some force stealth spell such as Vanish. 

### Expected behavior
The Stealth spell shall either go into CD while the stealth being immune
or 
Just become valid directly after the Faerie Fire faded.

### Some checks
I have checked the code but not fully understood yet. 
It seems that the unstealthable aura was implemented by some immune aura effect proc. The stealth spell will apply an aura which will be immune by some other auras. But the spell which provide stealth aura was NOT working properly while the stealth being immune. 

### Version & Environment
Client Version: [1.12.1]

CMaNGOS Repo & Commit Hash:  [mangos-classic](7091f09bbe3e6b41438975ebc9ba1cfbea549cff)

Database Repo & Commit Hash: [classic-db](b461795f08f36557be21fcbcaa039599df312f1d)

Operating System: [Win7 SP1]

### Steps to reproduce
1. Login a rogue and a druid account, both with level3 gmlevel. 
2. Start duel. 
3. The druid input .cast 770 with the rogue selected. 
4. Wait for the rogue out of combat. 
5. The rogue cast stealth before the Faerie Fire debuff fade. 
6. Wait for the Faerie Fire debuff disappear. 
7. Check the Stealth spell's state. 

### Crashlog
None

**Comment by darklordsqk** [comment]
###Further investigation
I think this problem is caused by the uncompleted proc of the Caster Aura Check. 

// File: src/game/Spells/Spell.cpp
// Function: SpellCastResult Spell::CheckCasterAuras() const;

Need someone knew the details well to solve this.

**Comment by darklordsqk** [comment]
I've added a very low efficient code block into Spell::CheckCasterAuras() to solve this issue locally. 

`
    // Fix Stealth & Invisibility check
    if (m_spellInfo->Dispel == DISPEL_STEALTH || m_spellInfo->Dispel == DISPEL_INVISIBILITY)
    {
        Unit::SpellAuraHolderMap const& auras = m_caster->GetSpellAuraHolderMap();
        for (const auto& itr : auras)
        {
            SpellAuraHolder* holder = itr.second;
            SpellEntry const* pEntry = holder->GetSpellProto();
            if (pEntry->HasAttribute(SPELL_ATTR_EX_DISPEL_AURAS_ON_IMMUNITY))
            {
                for (int i = 0; i < MAX_EFFECT_INDEX; ++i)
                {
                    if (pEntry->EffectApplyAuraName[i] == SPELL_AURA_DISPEL_IMMUNITY
                        && pEntry->EffectMiscValue[i] == m_spellInfo->Dispel)
                        return SPELL_FAILED_CASTER_AURASTATE;
                }
            }
        }
    }
`

**Comment by insunaa** [comment]
@killerwife was a fix for this ever merged? canidae seemed to think it would ~2 years ago

**Comment by killerwife** [comment]
No, I did a different fix I reversed from client https://github.com/cmangos/mangos-tbc/blob/master/src/game/Spells/Spell.cpp#L3931

**Comment by insunaa** [comment]
Then I'm closing this as fixed
