### ISSUE TITLE
Scarlet Monastery instances wrongly require level 35

### ISSUE THREAD

**Issue by Itzamnaaj** [cmangos/issues#1882]
## 🐛 Bugreport
When attempting to enter any Scarlet Monastery instance with a character under level 35, entry is denied with the message "You have to be at least level 35 to enter".

### Expected behavior
From memory, I knew this behaviour is not according to the original Blizzard servers. According to Vanilla WoW Wiki, the minimum level required to enter the Scarlet Monastery instances is 21: https://vanilla-wow.fandom.com/wiki/Scarlet_Monastery.

### Version & Environment

Client Version: [1.12.1]

CMaNGOS Repo & Commit Hash:  [CLASSIC](https://github.com/cmangos/mangos-classic/tree/7091f09bbe3e6b41438975ebc9ba1cfbea549cff)

Database Repo & Commit Hash: [CLASSIC](https://github.com/cmangos/classic-db/tree/81e30ba76549336c2fad8d5c0b5ab75a1689acc2)

Operating System: [Gentoo GNU/Linux]

### Steps to reproduce
1. Create or log into a character level <35
2. Issue command .tele scarletmonastery
3. Walk through any of the 4 instance portals

### Crashlog

- [ ] None

**Comment by Phatcat** [comment]
wowpedia says it's 20 for every entrance actually;
https://wow.gamepedia.com/index.php?title=World_of_Warcraft_instances_by_level&oldid=2490792

And so it was on wowwiki back in 2009 as well, apparently got added without a ref;
![image](https://user-images.githubusercontent.com/1907820/52963336-c89c1680-339f-11e9-90fd-14fd78a84395.png)
It was even altered and then alterred back.
![image](https://user-images.githubusercontent.com/1907820/52963916-5af0ea00-33a1-11e9-9108-a7713f1e543e.png)
![image](https://user-images.githubusercontent.com/1907820/52963841-2715c480-33a1-11e9-8b88-538508242ea6.png)



Seems like it was updated to 21 (for whatever reason) in preparations for cataclysm (probably in patch 4.0.3a.), reading the comment it could however have been changed all the way back with patch 3.3.0;
![image](https://user-images.githubusercontent.com/1907820/52963599-845d4600-33a0-11e9-9507-93b075c40011.png)

**Comment by Phatcat** [comment]
And here we have all the correct instance req and recommended levels from 2006 before the release of tbc pre-patch;
https://wow.gamepedia.com/index.php?title=Instances_by_level&oldid=295506

**Comment by Itzamnaaj** [comment]
Thanks for the prompt fix Phatcat, I can confirm it fixes the issue.

**Comment by cala** [comment]
Thanks, closed by https://github.com/cmangos/classic-db/commit/929bd010ffb4444b7636420bcbd39bfac6e80092
