### ISSUE TITLE
Alterac Valley capture points/banners  

### ISSUE THREAD

**Issue by martindev446** [cmangos/issues#1884]
## 🐛 Bugreport
(This might be a DB issue, I'm unsure.)
In Alterac Valley, each capture point in the battleground appears to have all 4(Horde Controlled, Alliance Controlled, Horde Contested, Alliance Contested) banners.
![wowscrnshot_021819_181334](https://user-images.githubusercontent.com/13082079/52987594-bcc54a00-33c9-11e9-8b1b-3aa7a7567ea3.jpg)

As a side effect I believe there are multiple lighting effects around each banner.
Another side effect is the giant mob packs attempting to guard each banner(but i suppose this could be in another bug report).
![wowscrnshot_021819_214339](https://user-images.githubusercontent.com/13082079/52987608-cbabfc80-33c9-11e9-83ea-4c36a4659987.jpg)

### Expected behavior
Each capture point should only display the banner of the faction that controls it.
Example of Horde contested point: https://youtu.be/a2HSKSnffLk?t=14
Example of Horde capture point and estimate of mob pack size: https://youtu.be/5Q4dx6FVLUk?t=69

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash:  [TBC](https://github.com/cmangos/mangos-tbc/tree/321040f8c18eb263cce118b31447c968ee056d79)

Database Repo & Commit Hash: [TBC](https://github.com/cmangos/tbc-db/tree/b46c70d3f14213699dd1a5f5fbb20f0d153cf043)

Operating System: [Win 10]

### Steps to reproduce
1. Use command ".debug bg" to enable solo player battlegrounds.
2. Enter Alterac Valley by talking to the respective alliance/horde NPC in Hillsbrad.
3. Visit any capture point on the map.

### Crashlog

- [X] None

**Comment by killerwife** [comment]
Figure out how the spawning of the mobs works. Make sure you do .gm off since then u also see despawned GOs or creatures. By default, all except the correct one should be despawned (I did the same on Halaa banners)

**Comment by martindev446** [comment]
Even with gm mode off, multiple banners are spawned on each point, along with the mobs. ill try to keep investigating

**Comment by Baynar** [comment]
Can confirm this.

**Comment by al3xc1985** [comment]
@killerwife this can be closed...tested and works perfect
