### ISSUE TITLE
Alterac Valley: Multiple copies of Captains/Bosses

### ISSUE THREAD

**Issue by martindev446** [cmangos/issues#1885]
## 🐛 Bugreport
(This might be a DB issue, I'm unsure. I might be posting in the wrong place)
In Alterac Valley, it appears that the following Captain/General mobs have been spawned in two places in each of their respective rooms:

Drek'Thar
![wowscrnshot_021819_181409](https://user-images.githubusercontent.com/13082079/52988600-ef714180-33cd-11e9-9e72-0669a2ebbd87.jpg)

Captain Galvangar
![wowscrnshot_021819_181524](https://user-images.githubusercontent.com/13082079/52988634-09128900-33ce-11e9-8914-8e40fd198828.jpg)

Captain Belinda Stonehearth
![wowscrnshot_021819_181556](https://user-images.githubusercontent.com/13082079/52988650-1596e180-33ce-11e9-86dc-60a2cb320f75.jpg)

Vanndar Stormpike
![wowscrnshot_021819_181641](https://user-images.githubusercontent.com/13082079/52988662-22b3d080-33ce-11e9-9235-0b5139093a74.jpg)

### Expected behavior
Most-likely correct spawn points:
Drek'Thar: https://youtu.be/AxxC8WW2Ozg?t=126 (hard to see)
Captain Galvangar: (need source)
Captain Belinda Stonehearth: https://youtu.be/cJaktAcZnvU?t=94
Vanndar Stormpike: https://youtu.be/oYGS8yWC1bg?t=31

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash:  [TBC](https://github.com/cmangos/mangos-tbc/tree/321040f8c18eb263cce118b31447c968ee056d79)

Database Repo & Commit Hash: [TBC](https://github.com/cmangos/tbc-db/tree/b46c70d3f14213699dd1a5f5fbb20f0d153cf043)

Operating System: [Win 10]

### Steps to reproduce
1. Use command ".debug bg" to enable solo player battlegrounds.
2. Enter Alterac Valley through Hillsbrad NPC
3. Visit the locations of the following NPCs: Drek'Thar, Captain Galvangar, Captain Belinda Stonehearth, and Vanndar Stormpike

### Crashlog

- [X] None

**Comment by killerwife** [comment]
Make a list of entries for creatures from creature_template (you can find Id on wowhead in URL) which are duplicate and need their proper spawns determined. We can datamine that from wotlk dataz.

**Comment by martindev446** [comment]
I bolded the entries which i believe are the correct spawn locations, but definitely needs double checking(Galvangar in particular is an odd one). 

Duplicate Generals/Captains 

Creature | creature_template _entry_ | creature _guid_ (1) | creature _guid_ (2)
--------- | ------------------------ | ----------------- | -----------------
Drek'Thar | 11946 | 51865 | __97135__
Galvangar | 11947 | 97137 | __51866__
Balinda Stonehearth | 11949 | 51868 | __97136__
Vanndar Stormpike | 11948 | 51867 | __97134__
