### ISSUE TITLE
[TBC] Pusillin Disappers In The Middle Of Event And Appers Inactive At The Start Point

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1887]
## 🐛 Bugreport
Pusillin event in the Dire Maul. Player should use gossip for start Pusillin move to the next point. After use gossip at the point near tunnel, he runs and disappers. If you try to return to Pusillin first point, he will be there but hungs and you will not be able to use gossip menu.
Interesting, that if you use Game Master speed and run near Pusillin, he will work without bug.
So seems he disappers at some distance from player.

### Expected behavior
He should'n disappear at distance, it is not an escort quest. 
As proof there are lots comments on wowhead that players able to kill him solo even on TBC at 61 level.
![image](https://user-images.githubusercontent.com/39913306/53194712-24c39c80-3625-11e9-9b10-eb38d68106b3.png)

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash:  [TBC](321040f8c18eb263cce118b31447c968ee056d79)
321040f8c18eb263cce118b31447c968ee056d79

Database Repo & Commit Hash: [TBC](f9965649e7b5a0b94a3c8f78f1ce15dc9521aa9a)
f9965649e7b5a0b94a3c8f78f1ce15dc9521aa9a

Operating System: [Win 64]

### Steps to reproduce
1. .tele Dire Maul
2. go inside and turn left, then move to Pusillin 
3. start event and try finish it without GM Speed.
4. restart event and try finish it with GM Speed.
5. ...
5. Profit

### Crashlog
- [X] None

**Comment by Grz3s** [comment]
active flag req. thats all

**Comment by datchannin** [comment]
@Grz3s 
thanks, I've fixed using this:
`UPDATE creature_template SET ExtraFlags = ExtraFlags|4096 WHERE Entry in (14354);`

**Comment by Grz3s** [comment]
I would not give him pernament flag.... 
i would set active flag .. on his waypoints (script) start
```sql
21 SCRIPT_COMMAND_SET_ACTIVEOBJECT 
```
and remove it stright after finish... 
I'll add it to my todo list .. and script will be updated soon ;)
