### ISSUE TITLE
Lunar Invitation Scroll Not Teleporting Player

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#1888]
## 🐛 Bugreport

Using the lunar festival invitation in the 'greater moonlight' in any horde capital city (tested UC and Org), the animation works and the spell appears to cast but when done the player remains in capital city and is not teleported to moonglade.

### Expected behavior

Teleport player to moonglade when done casting lunar festival invitation in capital city greater moonlight

### Version & Environment

Client Version: [2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash:  fa3788dcb961693c6b11d3de6abb8eba157b44fb

Database Repo & Commit Hash: f9965649e7b5a0b94a3c8f78f1ce15dc9521aa9a

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

### Crashlog

- [X] None

**Comment by AnonXS** [comment]
http://db.hellfire-tbc.com/?item=21711
http://db.hellfire-tbc.com/?spell=26373

**Comment by lduguid** [comment]
If it helps, all the database values appear to in place, using a reference to https://github.com/cmangos/tbc-db/commit/9e50619a88b17f35799e5af10c20bca462db55d1#diff-13b49da930d82006ce46b40e718b36c0 
( i assume this update is now rolled into TBCDB_1.7.0_ANewHope.sql)

except the targetentry of `spell_script_target` WHERE `entry` = 26373 which in the commit above is 300058 (which makes no sense to me) but in my database it is currently 180,867 which does make sense, so the db values look OK in my database.

**Comment by AnonXS** [comment]
Culprit was the data_flags for ```SELECT * FROM `dbscripts_on_go_template_use` WHERE `id` IN (180867) ORDER BY delay; ```
