### ISSUE TITLE
NPC Clear Their Aggro and Stop Combat In Instances if You Run From Them

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1889]
## 🐛 Bugreport
If you start combat inside instance and run away from mobs, they stop combat and return to their start position. They do it like mobs in the open world.

### Expected behavior
Npc shouldn't clear arggo if you only run from they.

### Version & Environment

Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: [TBC](321040f8c18eb263cce118b31447c968ee056d79)
321040f8c18eb263cce118b31447c968ee056d79

Database Repo & Commit Hash: [TBC](f9965649e7b5a0b94a3c8f78f1ce15dc9521aa9a)
f9965649e7b5a0b94a3c8f78f1ce15dc9521aa9a

Operating System: [Win 64]

### Steps to reproduce
1. .tele Hellfire
2. move to the middle of instance
3. aggro pack of mobs
4. move away
4. ...
5. Profit

### Crashlog
- [X] None

**Comment by datchannin** [comment]
Seems the same actual for bosses. I've tested on Gargolmar.

**Comment by cala** [comment]
Also true for Classic core (and probably WotLK).

This is game breaking for encounters  where bosses must be pulled far from their spawn point, like like Baron Geddon or Shazzrah in Molten Core.

**Comment by Muehe** [comment]
Related issue: #995

**Comment by AnonXS** [comment]
Hmm not really, the one is a legit mechanism, the other is a outright broken leash bug which is probably broken due to some missing exports.

**Comment by datchannin** [comment]
@Muehe ,
#995 from 2016 year, but instances aggro system worked correctly in the second part of 2018. 
It was broken a few months ago.

**Comment by cala** [comment]
I've investigated a bit this issue and as you guessed, this comes from the creature's leash (or to be more accurate the lack of real leashing).

`Unit::IsLeashingTarget(Unit* victim)` is called every time a unit checks if it has a combat target. If the target (the player, in our case) is too far away from the point where the unit was engaged, `IsLeashingTarget()` will return `true` and the unit will be forced to enter evade mode.

Code in `Unit::IsLeashingTarget(Unit* victim)` states that leash implementation is to be done, thus there is no real leashing and more importantly: no difference between outdoor world and dungeon creatures.

The best fix would be to implement a real leash system. I think @killerwife has this in his bags, but I don't know if this is a WIP or if this is just waiting to be exported.

In the meantime, there are some temporary workarounds that can be think of:
- bypass the `IsLeashingTarget()` if the unit is in a map that is a dungeon. On the downside: this will have no effect on NPCs located outdoor, like world bosses (Emerald Dragons for instance)
- make use of the currently unused DB field `creature_template.Leash`, for example by making it signed with -1 value meaning "leashing is disabled". This would allow to set at creature's level which one should leash or not. On the downside we are coding in DB a global behaviour (instance NPC never leash) and I think we should aim to a more clever design covering both global instance cases and local outdoor cases
- set config `CONFIG_FLOAT_THREAT_RADIUS` to an insanely high amount as it is used in the distance calculation. This will fix the issue in dungeons but will break current leashing outdoor (mobs will follow players forever)

**Comment by Yatzii93** [comment]
Can also just add expections-

[bool Unit::IsLeashingTarget(Unit* victim) const
{
	uint32 map = GetMapId();
	uint32 targetid = static_cast<Creature const*>(this)->GetGUIDLow();
	if (!(targetid == 5480040))
	{
		if (map == 548)
			return false;
	}](url)

**Comment by nullpointer010** [comment]
This is a fix that can do the job meanwhile:
```
const MapEntry* entry = sMapStore.LookupEntry(GetMapId());
if (IsLeashingTarget(target) && entry->map_type != MAP_RAID)
{
	AI()->EnterEvadeMode();
	return false;
}
```
A bypass if the unit is in a map of a raid.
But as @cala said, this will have no effect on bosses located outdoor.

**Comment by BenDol** [comment]
We could probably have the `entry->map_type != MAP_RAID` check and make use of the `creature_template.Leash` for world bosses?

**Comment by keyshuwen** [comment]
What seems to be missing.   entry->map_type != MAP_INSTANCE. 

`            const MapEntry* entry = sMapStore.LookupEntry(GetMapId());
            if (entry->map_type != MAP_RAID && entry->map_type != MAP_INSTANCE)
            {
                AI()->EnterEvadeMode();
                return false;
            }`

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/146687462-c4d86d1e-6b17-41fe-9bb0-b5415b97a2df.png)

resolved
