### ISSUE TITLE
Abolish Poison Spell Dispells Poison Only On The First Tick

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1892]
## 🐛 Bugreport
spell=2893, druid poison periodical dispel.
Should dispel poison on apply after cast, and add aura for every 2 sec poison dispel. Now works only dispel when poison is applyed. 

### Expected behavior
Should dispel poison every 2 sec.
![image](https://user-images.githubusercontent.com/39913306/53356616-d8d26980-393c-11e9-8635-38b8cf89e558.png)

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: [TBC](57b3a61bb117365b25c5e8d3f0c1b5c650ff551d)
57b3a61bb117365b25c5e8d3f0c1b5c650ff551d

Database Repo & Commit Hash: [TBC](f9965649e7b5a0b94a3c8f78f1ce15dc9521aa9a)
f9965649e7b5a0b94a3c8f78f1ce15dc9521aa9a

Operating System: [Win 64]
### Steps to reproduce
1. Cast Abolish Poison when some npc casts on you poison effect.
2. Can be used Daggerfen Muckdweller (npc=18115)
3. 
4. ...
5. Profit

### Crashlog
- [X] None

**Comment by adimeus** [comment]
Investigated this a little and I found out that in SpellAuras.cpp line 1838, the switch statement
`switch (triggeredSpellInfo->EffectImplicitTargetA[0])`
is defaulting and setting `triggerTarget` to a nullpointer.

This leads to  `SpellCastTargets targets` being empty and nontheless being passed to `spell->SpellStart(&targets, this);` introduced in this ([defe992](https://github.com/cmangos/mangos-tbc/commit/defe99293ac201b7d189601e211ecfefe9d9e768#diff-267e883184701d9dd4ecaf79808a9b4dR1956)) change.

Prevented this behaviour by not letting the switch default. Extended a case to the switch at line 1847 
```
 case TARGET_UNIT_CASTER:
 case TARGET_UNIT_FRIEND:   // +++ added ('Abolish Poison Effect' id 3137 has EffectImplicitTargetA1 '21' (TARGET_UNIT_FRIEND)
   triggerCaster = target;
   triggerTarget = target;
   break;
```
Resulting in the poison being cleansed ~ allthough it looks like it's happening faster than once every 2 seconds...
Not sure if this is a correct fix or not, as this is one of my first looks at the code, I'm just posting my findings.

**Comment by datchannin** [comment]
I see that shaman totem [8166], that cast spell [8168] correctly clears poison for every tick. And the target is (TARGET_CASTER_COORDINATES, TARGET_ALL_PARTY). Abolish poison is not clears and target is ((TARGET_SINGLE_FRIEND, TARGET_NONE))

And if this is TARGET_UNIT_FRIEND issue, cat it be connected with this report?
https://github.com/cmangos/issues/issues/1894

Because for example 
npc = 780, Skullsplitter Mystic. Cast Healing Wave on Friendly Missing HP.
The spell is [11986] and target is (TARGET_SINGLE_FRIEND, TARGET_NONE) the same as for Abolish Poison.

**Comment by Almightie** [comment]
Made a PR for this suggested solution
#https://github.com/cmangos/mangos-tbc/pull/271
Abolish poison (2893) triggers abolish poison effect (3137) which has an implicit target of UNIT_TARGET_FRIEND.

**Comment by cala** [comment]
Fixed in https://github.com/cmangos/mangos-tbc/commit/806077b4de36ec4ebb4e8d45aeb46b6bf9f5f391 by @Almightie
