### ISSUE TITLE
Player Can Swim On His Mount

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1893]
## 🐛 Bugreport
Player can swim under water using his mount. For example tauren on his codo.
![image](https://user-images.githubusercontent.com/39913306/53357072-07047900-393e-11e9-8ba8-aa3485ef2d17.png)
For use it he should jump to the water from the coast while ride the mount.
If player move to the water without jumping, he will be dismounted.

### Expected behavior
Player should be dismounted after appears on water.

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: [TBC](57b3a61bb117365b25c5e8d3f0c1b5c650ff551d)
57b3a61bb117365b25c5e8d3f0c1b5c650ff551d

Database Repo & Commit Hash: [TBC](f9965649e7b5a0b94a3c8f78f1ce15dc9521aa9a)
f9965649e7b5a0b94a3c8f78f1ce15dc9521aa9a

Operating System: [Win 64]

### Steps to reproduce
1. Use mount.
2. Go to the coast (for example near Orgrimmar).
3. Start moving
4. Press jump when you will be near water like here
![image](https://user-images.githubusercontent.com/39913306/53357291-990c8180-393e-11e9-9eba-c91aa019b252.png)
5. ...
6. Profit

### Crashlog

- [X] None

**Comment by RussianE39** [comment]
I can confirm that. Although, sometimes I've got proper dismount when heading into water.

**Comment by RussianE39** [comment]
--- a/src/game/Entities/Player.cpp
+++ b/src/game/Entities/Player.cpp
@@ -1104,6 +1104,7 @@ void Player::SetEnvironmentFlags(EnvironmentFlags flags, bool apply)
         // which can't swim and move guid back into ThreatList when
         // on surface.
         // TODO: exist also swimming mobs, and function must be symmetric to enter/leave water
+       RemoveAurasWithInterruptFlags(apply ? AURA_INTERRUPT_FLAG_NOT_ABOVEWATER : AURA_INTERRUPT_FLAG_NOT_UNDERWATER);
         getHostileRefManager().updateThreatTables();
     }
Yea. This patch will fix that issue, although, its not proper way.

**Comment by datchannin** [comment]
Seems this patch resumes this issue
https://github.com/cmangos/issues/issues/1874

**Comment by cala** [comment]
This issue also exists on Classic core.
