### ISSUE TITLE
Blink at a Certain Place in Undercity May Still Teleport to the Surface of Ground

### ISSUE THREAD

**Issue by darklordsqk** [cmangos/issues#1895]
## 🐛 Bugreport
When a mage cast blink above the water surface of the UnderCity while having falling flag on character. It will teleport character to the surface of the map ground. 

### Expected behavior
The blink spell's dest z-coordinate can only be similar with its start point z-coordinate.
Blink's targetMode is TARGET_LOCATION_CASTER_FRONT_LEAP in Spell.cpp. So trace it through.

### Version & Environment
Client Version: ["1.12.1"] (CLASSIC)

CMaNGOS Repo & Commit Hash:  [CLASSIC](https://github.com/cmangos/mangos-classic/commit/3806c2452c032ea3c58dd6b244ab8eb296394411)

Database Repo & Commit Hash: [CLASSIC](https://github.com/cmangos/classic-db/commit/929bd010ffb4444b7636420bcbd39bfac6e80092)

Operating System: [Win 7 SP 1]

### Steps to reproduce
1. .tele undercity
and
2. .go xyz 1572.15 239.37 -62
3. jump forwards to the water and cast blink while character is on falling status (important)
4. wait for the server to calc the final landing position.
or
2. .go xyz 1450.60 245.54 -62.75
3. jump forwards to the water and cast blink while character is on falling status (important)
4. wait for the server to calc the final landing position.

### Crashlog
- [X] None

**Comment by darklordsqk** [comment]
I'm pretty sure that the root cause of this problem is from the Map Class, but not from the Spell Class. Although, the representation seems have some relationship with falling status or water surface check etc. 

This issue is a side effect of issue #1846 & the related fix of 
Commit 4403065d6996b53bd9a57de8bd87d04d4b545dd4

imo, 
    float diffMaps = fabs(fabs(z) - fabs(mapHeight));
    float diffVmaps = fabs(fabs(z) - fabs(vmapHeight));
in Map::GetHeightInRange() 
doesn't have a distinct mathematical meaning. 
That is the root cause of so many weird representations. 

If mapHeight from GridMap is positive while the current search Z is negative, the diffMaps will absolutely NOT be the right distance from current search Z and the map height Z. 

The goal of Map::GetHeightInRange() is to find an height within a reasonable range of provided Z. 
so a reasonable procedure of GetHeightInRange is below:
1. Get the real distance from current search Z to both VMap Height Z and Map Height Z. 
    float diffMaps = fabs(z - mapHeight);
    float diffVmaps = fabs(z -(vmapHeight);
2. Compare both the diffMaps and diffVmaps to the maxSearchDist. 
3. If one of them less than maxSearchDist, that means we have found a reasonable landing place from either GridMap or VMap.
4. If none of them less than maxSearchDist, that means we cannot find a reasonable landing place from 
neither GridMap nor VMap. Then the function fail, and the original Z won't be changed.

**Comment by cala** [comment]
Could you retest with https://github.com/cmangos/mangos-classic/commit/7fa4124748e2f378e209c82bd7d0dea448482f02 ?

**Comment by darklordsqk** [comment]
> Could you retest with [cmangos/mangos-classic@7fa4124](https://github.com/cmangos/mangos-classic/commit/7fa4124748e2f378e209c82bd7d0dea448482f02) ?

OK, I will recompile it now.

**Comment by darklordsqk** [comment]
@cala I finished the test. 
![1](https://user-images.githubusercontent.com/4716232/53684816-4cb1af00-3d4d-11e9-8520-a701afda6f24.png)
![2](https://user-images.githubusercontent.com/4716232/53684818-50453600-3d4d-11e9-9c03-a29d95e3f587.png)
![3](https://user-images.githubusercontent.com/4716232/53684819-52a79000-3d4d-11e9-909a-fb8b087a03f1.png)
![4](https://user-images.githubusercontent.com/4716232/53684820-54715380-3d4d-11e9-9141-cb9d2a4acf19.png)

Seems like it isn't the liquid level cause this issue.

**Comment by darklordsqk** [comment]
Here is a little fix of this issue. 

![5](https://user-images.githubusercontent.com/4716232/53685013-ff830c80-3d4f-11e9-8dbc-3833a15140bc.png)

But I don't think it's a perfect one. 
So it needs further test.

**Comment by al3xc1985** [comment]
@killerwife I remember you fixed this 2
