### ISSUE TITLE
Lurker Below - Spout Spell Player in Liquid Check

### ISSUE THREAD

**Issue by 5man999** [cmangos/issues#1897]
## 🐛 Bugreport

Recent commits (https://github.com/cmangos/mangos-tbc/commit/7a23337bdce0d18cd3f4f6817bf5761f03e024a0) have caused Lurkers Spout spell to do no damage or knockback to people remaining on the platform.  [Probably the same issue is occuring with the other spell check changes in that commit]

Reverting the commits back works, however I've chose to do it slightly differnetly, instead checking whether the player is under the water rather than just checking for shallow water. This avoids cheesing the fight by standing in the puddles on the platform.

Not sure why the current code is failing in the sense that it must be applying true in any circumstance.

**My Changes:**
```
 2 src/game/Spells/Spell.cpp
case 37433:                                         // Spout (The Lurker Below), only players affected if its not in water
if (target->IsUnderwater())
return false;
```

### Expected behavior

Spell should hit anyone missing the water envirumental flag (anyone on Lurkers platform)

### Version & Environment

Client Version: [] "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash:  []() https://github.com/cmangos/mangos-tbc/commit/42a831b21fccfff63825ca4d85819f2f23ee8cf9

Database Repo & Commit Hash: []() https://github.com/cmangos/tbc-db/commit/5b5e775f82f2418a1920045322320aa945de3ac7

Operating System: [] Windows

### Steps to reproduce
1. Go into SSC
2. Start Lurker Fight
3. Wait for Spout Spell to trigger
4. stay on the platform and watch as you remain unaffected by the spells damage or knockback.
5. Profit

### Crashlog

- [X] None

-Yatzi888

**Comment by killerwife** [comment]
Should be fixed. Please retest.

**Comment by 5man999** [comment]
Works well. Great stuff killerwife!
