### ISSUE TITLE
playerbot freezes mangosd process, currently broken

### ISSUE THREAD

**Issue by cbrgm** [cmangos/issues#1898]
## 🐛 Bugreport

As soon as a player bot talks to an NPC, the server hangs up in an endless loop and does not react anymore until the restart.

If you look at the process load, it is ~100%. The mangosd process itself does not crash, but it seems to freeze itself.

```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command                 
 3259 1000       20   0 1550M  917M 18132 S 106. 23.8 14:42.62 /opt/mangos/bin/mangosd 
```
Unfortunately there are no more logs displayed, neither in the DBErrors.log nor on Stderr/Stdout.
Here is however an extract from DBErrors.log, even though I don't think this is the cause:

```
2019-03-07 22:51:11 ERROR:Table `command` have command '' that only used with some subcommand selection, it can't have help or overwritten access level, skip.
2019-03-07 22:52:27 ERROR:MoveSpline::init_spline: zero length spline, wrong input data?

```

### Expected behavior

The mangosd process should not freeze when a player bot talks to an NPC.

### Version & Environment

Client Version: [ "3.3.5a" (WOTLK)]

CMaNGOS Repo & Commit Hash:
[WOTLK] (https://github.com/cmangos/mangos-wotlk/tree/master)
Hash: 904bcb09e78b2ec7df184053d6ece2d31b3de7a3

Database Repo & Commit Hash:
[WOTLK] (https://github.com/cmangos/wotlk-db/tree/master)
hash: bc2e71aa160c3ed588d576b1309a977d218a6f62

Operating System: [Linux Ubuntu 18.04]
6xCPU Cores
16GB RAM
200 GB HDD

### Steps to reproduce
1. Create a dwarf and a human character
2. Login as dwarf and invite human character as playerbot
3. Complete the first quest
4. Command the playerbot to complete the quest  `quest end` or sell items
5. Server freezes

### Crashlog

- [X] None

**Comment by cbrgm** [comment]
@cala is this a duplicate of #1878?

I have seen that you have already made some [commits](https://github.com/cmangos/mangos-classic/commits/master)  for Classic regarding the playerbot issue, thank you very much! :-) 

Do the same changes also have to be merged into wotlk?

**Comment by cala** [comment]
Yes, this is probably a duplicate and the issue seems to rely in the way bots handle interaction with NPCs. 

A said in the other issue, I'll investigate this when I port the change from Classic branch to TBC et WotLK.

**Comment by cbrgm** [comment]
Thanks for your work @cala ! Great!

**Comment by cbrgm** [comment]
The issue still appears in a freshly compiled version two hours ago. I'm compiling a new version that includes the latest commits from some minutes ago at the moment and will give feedback.

**Comment by cala** [comment]
Based on the two cases described in the related issues, I can no longer reproduce the infinite loop since my fix and bot interactions with NPCs seem to work as intended. Could you provide a way to reproduce the freeze, please?

**Comment by cbrgm** [comment]
Do you have a 3.3.5a client available? I set up a testserver in a container on gcloud for you using the latest realmd and mangosd binaries compiled half an hour ago.

```
realmlist 116.203.121.99:3724
```
You can logon as GM using user `cmangos` and password `cmangos`.
To reproduce the freeze:

* Login as test
* Enter `.bot add bot` to add the bot char
* Accept the first quest at the quest npc in front of the church (so does the bot)
* Go inside the church, use `/w bot quest end`. Talk to the quest npc to complete the quest (so does the bot)
* server freezes as soon as the bot talks to the npc

When you try to login again, realmd still authenticates you, but mangosd won't respond.
Do you have any dev irc available? I'd like to provide as much support as i can.. :-)

**Comment by berserkingyadis** [comment]
You can join us in discord https://discord.gg/G3yN8G .

Are you sure you wanna expose that info that publicly?

**Comment by cbrgm** [comment]
Yes, don't worry I'm gonna purge the machine when you don't need it anymore

**Comment by cala** [comment]
> - Login as char (human)
> - Enter .bot add <bot> to add the bot char and invite bot to your party
> - Accept the first quest at the quest npc in front of the church (so does the bot)
> - Go inside the church, use /w <bot> quest end. Talk to the quest npc to complete the quest (so does the bot)
> - server freezes as soon as the bot talks to the npc

I did these exact steps on a fresh install on my machine and no freeze at all: bot says that quest is complete.
I do believe you that your server freezes using the same protocol, I'm trying to understand why.

**Comment by cbrgm** [comment]
I'm going to recompile the latest wotlk-master once more now. Maybe I messed up something. I'll give you feedback in a few minutes.

**Comment by cbrgm** [comment]
In the end, it was my fault. I packed cmangos into a docker image and used old cached image layers with outdated binaries to build the container. 

The bot works fine! Many thanks for the great work!
