### ISSUE TITLE
[crash] BIH::intersectRay [version-tbc]

### ISSUE THREAD

**Issue by digz6666** [cmangos/issues#190]
Server crashed with following log:
http://pastebin.com/Br3f2UyF

Revision: 1924 (version-tbc)

**Comment by Phatcat** [comment]
BIH::intersect has been reworked https://github.com/cmangos/mangos-tbc/commit/092bcc81b0ec3cf408aaf0b67de5a3bc0130510a and this crash dump is more than 3 years old now.
