### ISSUE TITLE
Crushridge Warmonger Doesn't Cast Frenzy on Friendly NPC Death

### ISSUE THREAD

**Issue by Pastew** [cmangos/issues#1902]
## 🐛 Bugreport
Crushridge Warmonger doesn't cast Frenzy on friendly npc death.
* NPC: [2287](https://www.wowhead.com/npc=2287/crushridge-warmonger)
* Frenzy: [8269](https://www.wowhead.com/spell=8269/frenzy)
* Vengeance: [8602](https://www.wowhead.com/spell=8602/vengeance)
* Original issue with similar problem: [#1894](https://github.com/cmangos/issues/issues/1894)  

All impacted creatures gathered with this query. (There might be more, I based on comment column which is not the best idea)
```sql
SELECT * FROM tbcmangos.creature_ai_scripts where comment like "%Friendly Death%"
```
```
2287, Crushridge Warmonger - Cast Frenzy and Text Emote on Friendly Death
258501, Stromgarde Vindicator - Cast Vengeance on Friendly Death
392502, Thistlefur Avenger - Cast Vengeance on Friendly Death
1188002, Twilight Avenger - Cast Vengeance on Friendly Death
```
triggerspell 8602

NOTE: Watch out while debugging with 11880, this creature has also 30% chance to cast Vengence at 30% HP, so don't get confused.

### Expected behavior
Crushridge Warmonger should cast Frenzy (and probably Text Emote) when friendly NPC dies.

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash:  [TBC](https://github.com/cmangos/mangos-tbc/tree/96cabc05dd5479552a8d5e9699633a4693cf0a78)

Database Repo & Commit Hash: [TBC](https://github.com/cmangos/tbc-db/tree/e44859d14ea22b6d4207c359221269db68e4497c)

Operating System: [Win 10 (64)]

### Steps to reproduce
1. .npc add 2287
2. .npc add 2287
3. Kill one of them
4. ...
5. Profit

### Crashlog
- [x] None

**Comment by Tobschinski** [comment]
Not the solution you guys are looking for but it's quite possible that the used hook is nonsense in these cases anyway. 

Spells like:
Id: 8603 - Name: Thistlefur Death
Id: 8655 - Name: Riverpaw Death
Id: 8894 - Name: Stromgarde Death
Id: 9144 - Name: Crushridge Death
exist.

**Comment by Pastew** [comment]
Thanks for pointing that out. I'm new to cmangos.
I found spell you mentioned on classic wowhead: [link](https://classic.wowhead.com/spell=9144/crushridge-death)

Standard wowhead returns
```
Spell #9144 (possibly named "Crushridge Death") doesn't exist. It may have been removed from the game.
```
So:
1. Should we use those deprecated spells?
2. If so, is there any example of usage similar spells in cmangos?

I'm new to cmangos, I don't have too much knowledge yet.

**Comment by Tobschinski** [comment]
We usually try to stay as close to Blizzard as it's possible (and reasonable). If they used the spell, we should do too. Of course, they for sure updated their script engine over the years, maybe the spell became deprecated at some point, we don't know. But if the spell is coming back with 1.13 ... then it's a good chance it's still good to use.

I was about to add these spells yesterday, but I still have unanswered questions. For example, when is it NOT going to happen. I assume the Warmonger has to be in combat ... does it happen again even if the Warmonger is already enraged ... stuff like that.

I don't know if you're familiar with C++, but the concept itself is used in Garr's script. Whenever a Firesworn dies [here](https://github.com/cmangos/mangos-classic/blob/master/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/molten_core/boss_garr.cpp#L145), it casts a spell that is picked up by Garr [here](https://github.com/cmangos/mangos-classic/blob/master/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/molten_core/boss_garr.cpp#L91).

**Comment by AnonXS** [comment]
My bet is that casting Vengeance at 30% is just a wrong implementation and should be the real low hp enrage ability, not the friendly death Vengeance one.
E.g the dummy effect ```
Dummy
Radius: 20 yards
Server-side script
``` triggers in ACID to -> `on dummy effect spellhit` cast Vengeance Spell. this way its unrelated to any hp threshold and therefore unfailable due to how it currently "works".

**Comment by Tobschinski** [comment]
What spell are you referring to here? Not like I really tried but I didn't find a spell for the Twilight Avengers yet. But that double Vengeance cast looks wrong for sure.

**Comment by Pastew** [comment]
However, I think using those spells won't work on TBC, therefore I'd like to fix it using current solution.

Please let me know if my understanding what's going on here is correct.

My query:
```sql
SELECT creature_id, event_chance, event_flags, event_param1, event_param2, action1_type, action1_param1, action1_param2, action1_param3, comment FROM tbcmangos.creature_ai_scripts where creature_id = 2287 and comment like "%Friendly Death%";
```
Result:
```
# creature_id, event_type, event_chance, event_flags, event_param1, event_param2, action1_type, action1_param1, action1_param2, action1_param3, comment
  2287,        14,         100,          0,           1395,         15,           11,           8269,           0,              2,              Crushridge Warmonger - Cast Frenzy and Text Emote on Friendly Death
```

I followed this doc: https://github.com/cmangos/mangos-wotlk/blob/master/doc/EventAI.txt
My understanding: The event will occur when NPC will lose 1395 HP.
It doesn't make sense to me, because losing 1395 != die.
Where did this value 1395 come from? based on [vanilla-twinhead](https://vanilla-twinhead.twinstar.cz/?npc=2287) this NPC has from 4377 to 4572 HP, so losing 1395 HP is not even close to 0. 

Please, enlighten me.

**Comment by Tobschinski** [comment]
The mob was elite status in vanilla and (correct me if I'm wrong, normal status in TBC+).  1395 is the default health of a  level 39 warrior. In vanilla, you need to multiply that with 3 (the default health multiplier)

The spells don't work because they most likely not exist yet, you would need to add them (didn't check, just my first guess). The client DBC of TBC and WotLK do not contain all spells, lots of triggers, server side spells were removed.

**Comment by Pastew** [comment]
OK, I will try to figure what's going on once I have some time. Thanks for explanation!

**Comment by AnonXS** [comment]
Yes, these "classic-db" spells are imported into sql/base/dbc/cmangos_fixes/Spell.sql in the wotlk and tbc core repos. Then these spells can be used for db scripting as they are now part of the respective spell_template re­per­toire.

So:
1. all these vengeance user: `NPC XY cast "XXX Death" on Death`
2. all vengeance user npcs: `NPC XY Cast Frenzy and Text Emote on Spellhit` (question here is if its only triggered in combat or in general)
3. pull request to one respective database

**Comment by Pastew** [comment]
I looked again at this issue and here's my observations that may be useful:

1. Description of EVENT_T_FRIENDLY_HP in [doc](https://raw.githubusercontent.com/cmangos/mangos-wotlk/master/doc/EventAI.txt) is inaccurate.  
It says: "Expires when a friendly unit in (Radius) has at least (Param1) HP points missing."  
So my understanding is if I will run:
```
.npc add 2287
.damage 1395
```
The event should be triggered. But it doesn't. I have to run .damage 1396 at least, so Description should be:  
"Expires when a friendly unit in (Radius) has at least (Param1 + 1) HP points missing."  

2. If I damage npc for more than it has Health Points, for example:
```
.npc add 2287
.damage 5000
```

It will not trigger the event. So friendly NPC thinks that NPC is dead when it's actually almost dead. So it makes this scenario possible: 
```
NPC has (npc_max_hp - 1395) HP. The event isn't triggered yet.
Player kills NPC with one hit. The event is not triggered also.
```

3. NPC triggers the event on himself (when there is only one NPC, no friends around). To reproduce:
```
.npc add 2287
.damage 1396
```
It doesn't make sense because besides he casts frenzy he also says:  
"Crushridge Warmonger calls for help!
Crushridge Warmonger goes into a rage after seeing a friend fall in battle!"

4. Given above @Tobschinski was right that this approach doesn't make sense here to be 100% correct. However, in my opinion it emulates expected behaviour well enough. Please let me know what do you think.

**Comment by AnonXS** [comment]
Id: 8603 - Name: Thistlefur Death
Id: 8655 - Name: Riverpaw Death
Id: 8894 - Name: Stromgarde Death
Id: 9144 - Name: Crushridge Death

should be used, not some custom solution with EVENT_T_FRIENDLY_HP

**Comment by Pastew** [comment]
@AnonXS but are those available on tbc? I think those spells are only on vanilla.

**Comment by AnonXS** [comment]
They will when they get ported, see above.

**Comment by Pastew** [comment]
Hmm, ok. Thanks for explanation.

**Comment by AnonXS** [comment]
```
ServerToClient: SMSG_SPELLLOGEXECUTE (0x024C) Length: 24 ConnectionIndex: 0 Time: 02/09/2008 08:36:13.000 Number: 8038
Caster GUID: Full: 0xF0090A180023BBF0 TypeMask: Object, Unit UInt64: 17296366942090935280
Spell ID: 8894
Count: 1
[0] Spell Effect: Dummy (3)
[0] Count: 0
``` this is indeed the way to go, atleast Stromgarde Defender 2584 cast it on Death. maybe more.

**Comment by KansasGremlin** [comment]
If I can add my Classic-Wow experience.  As I fought several dozen Crushridge Ogres, the one above that casts Frenzy was casting his 'buff' at various states of health.  He also cast this without any other Ogre dying around him, as I typically only had himself aggro'd.
If the spell only casts upon friendly death, he shouldn't have cast this.  And yes, I think the 30% health buff works consistently.  But some would not cast this even if I had a spellcaster Ogre die while also fighting the Warmonger.  
Hope I can just add that I do agree this is accurate description in the thread title.
