### ISSUE TITLE
PDUMP files will not load across spins of server

### ISSUE THREAD

**Issue by zslg01** [cmangos/issues#1905]
## 🐛 Bugreport

I did a dump of my 5 characters from the Feb2019 git version of the server. Tried loading them into the March2019 git download I did on the 12th. The pump load appears to work but the characters are not in the database.

### Expected behavior

The plump load should reload characters
### Version & Environment

Client Version: []
"3.3.5a" (WOTLK)

Database Repo & Commit Hash: []()
Again which one the dump or load version?

Operating System: 
Linux Mint 19.1

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

### Crashlog

- [X] None

**Comment by jimmybrancaccio** [comment]
@zslg01 You're missing the commit hash information for both the core and database, please update your issue to include this information as well as the exact steps we need to use to replicate this issue.

**Comment by evil-at-wow** [comment]
@zslg01 If possible, I would mention the commits from both server versions, that way it's easy enough for developers to check what has been changed in the core between these versions. You should be able to find these hashes in the output/logs of the world daemon. For example, here's the start of a random log I have here:

```
CMaNGOS TBC/0.18 (2018-12-15T12:45:00+03:00 - 8894854eb08dd59b4b5522f732cfb836ac7cbcab) for Linux_x64 (little-endian) [world-daemon]
<Ctrl-C> to stop.
...
```
As you can see, the commit hash should be in the first line (I didn't check, but I'm going to assume that's also the case on other platforms).

**Comment by zslg01** [comment]
<RANT>
The problem is since I updated I no longer have the old server .. so how am I to get the old hash? I am not going to rebuild the old server just to get a hash.
This sounds like the old IBM ploy — “ask them for more documentation and maybe they will go away”  … LOL
From now on I am going to dump out the database using SQL backup and then I will at least be able to rebuild - or just start over — it isn’t the payroll or my taxes.
Maybe I’ll document everything you need to dump to retain a character.
Of course if there were ANY documentation of the SQL layout and the functions of the various tables it might get easier … <shrug>
/<Rant>

**Comment by evil-at-wow** [comment]
No one is asking you to rebuild the old server, especially not for a commit hash - that's why I said 'if possible'. But in case you still had the old server (or logs from it), it was easy enough to get the hash, so I deemed it worth asking. The "feb 2019" gives us an idea about your starting point, so that's something at least.

Note that we have documentation about the SQL tables and purpose of many of the fields. You can find it [on the wiki](https://github.com/cmangos/issues/wiki/charactersdb_struct). That said, I'm not claiming it's a nice complete, detailed, perfect description, but it's a good start IMHO.

**Comment by zslg01** [comment]
Thanks I’ll check it out

**Comment by jimmybrancaccio** [comment]
@zslg01 Are you still having any problems are may we close this issue out?

**Comment by zslg01** [comment]
Close it out
