### ISSUE TITLE
Quest 25229 - A Few Good Gnomes is Broken

### ISSUE THREAD

**Issue by cbrgm** [cmangos/issues#1907]
## 🐛 Bugreport
Quest 25229 is broken. Motivating the gnomes using the "Motivate-a-Tron" quest item is not working. 

https://www.wowhead.com/quest=25229/a-few-good-gnomes

### Expected behavior
Using the "Motivate-a-Tron" on gnome citizens should motivate them.

### Version & Environment
Client Version: [ "3.3.5a" (WOTLK)]

[WOTLK](https://github.com/cmangos/mangos-wotlk/tree/master)

[WOTLK](https://github.com/cmangos/wotlk-db/tree/master)

Operating System: [Win10]

### Steps to reproduce

See: https://www.wowhead.com/quest=25229/a-few-good-gnomes

### Crashlog

- [X] None

**Comment by Grz3s** [comment]
https://github.com/unified-db/Database/issues/157#issuecomment-196002394

**Comment by adellaci** [comment]
Still not working
quest=25229
item=52566
npc=39253
npc=39623
