### ISSUE TITLE
Boss Blackheart the Inciter Disappears After Incite Chaos Phase is Done

### ISSUE THREAD

**Issue by ezzo300** [cmangos/issues#1908]
**Current behavior**: 
During Blackheart the Inciter ( Shadow Labyrinth ) fight and when the boss   cast spell Incite Chaos ( id 33676 :  Incites chaos in the minds of all enemies, causing them to randomly attack each other)  and when it end he dispear  when i put gm command on i found him dead
**Expected behavior**: 
Blackheart the Inciter should continue the fight after cast Incites chaos and not dispear and die
**Steps to reproduce**:

1. Shadow Labyrinth
2. go to Blackheart the Inciter
3. Start Boss Fight

**Client version**: 
2.4.3 (8606)
**Commit hash**: 
57b3a61bb117365b25c5e8d3f0c1b5c650ff551d
**Database version**: 
969e3722d75c5f7837197709e6b77dd2c0ae0fb5
**Operating system**: 
unix

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by jimmybrancaccio** [comment]
@ezzo300 Please submit your issues using the bug template. This case does not include any commit information which is required - please add this information.

**Comment by ezzo300** [comment]
thanks is it okey now ?

**Comment by ezzo300** [comment]
informations has been updated  i wish they could help me

**Comment by berserkingyadis** [comment]
I replicated this issue. After the phase where he was friendly he disappeared. After turning on GM mode hes lying dead in the room (lol).

https://gfycat.com/ellipticalwarpedjanenschia (he disappears at ~0:32)

core: 74e6f3a1766d56c2e56f3881bb26f1c98b4267b0
db: 53943cada35b81adf82d97d9fb40da84836edbac
os: Windows 10

**Comment by buenodart** [comment]
Replicated and I got the same problem here!

**Comment by killerwife** [comment]
Script has been reworked and now should not happen again.
