### ISSUE TITLE
Create Healthstone Consumes Soulshard Yet Fails

### ISSUE THREAD

**Issue by Ansem** [cmangos/issues#1910]
## 🐛 Bugreport

Version TBC 2.4.3, code compiled on 4 march 2019 from the mangos-TBC github.
Tested with Blood Elf Warlock:
Create healthstone when 1 is already present in the inventory results in the soulshard being consumed but no spell effect being done. (either not creating a new healthstone or replacing the existing one)

### Expected behavior

Each Create healthstone should make a new healthstone in the Burning Crusade, as per WOTLK patch 3.0.2 it has been limited to one. A soulshard should not be consumed when no healthstone is created.

Patch changes
Patch 6.0.2 (14-October-2014): Healthstone's cooldown will now not reset until the player leaves combat. Healing from this ability is now a flat amount (instead of a % of maximum health) and can no longer be a Critical Effect.
Patch 3.0.8 (2009-01-20): Attempting to create a healthstone when you already have one no longer consumes mana or triggers the cooldown of this ability.
Patch 3.0.2 (14-Oct-2008): Healthstones are globally unique, regardless of talents. You can only have 1.
Patch 2.1.0 (22-May-2007): These abilities will now be sorted in rank order in your spellbook.

### Version & Environment

Client Version: [2.4.3]

CMaNGOS Repo & Commit Hash:  [e271f0e290ec0df9f936eb1d45979f4ca5a75a7e
]()

Database Repo & Commit Hash: [22c8a2a ]()

Operating System: [Linux (CENTOS-7)]

### Steps to reproduce
1. Play Warlock
2. Create healthstone
3. Create second healthstone when one is present in inventory
4. Soulshard is consumed, no second healthstone.
5. Profit, except not.... you wasted precious healthstones and the game doesnt tell you it wont work :(

### Crashlog

- None

**Comment by jimmybrancaccio** [comment]
@Ansem Please include your database commit hash.

**Comment by Ansem** [comment]
How do I find out the database commit hash from the FAQ dump  that I used?

**Comment by jimmybrancaccio** [comment]
@Ansem I am not sure what you mean by 'FAQ dump', please clarify.

**Comment by Ansem** [comment]
I downloaded the world dump from: https://github.com/cmangos/tbc-db/releases on 4 march 2019

**Comment by jimmybrancaccio** [comment]
So it's 22c8a2a as noted on the release page.

**Comment by Ansem** [comment]
Updated the main comment, thank you!!!

**Comment by evil-at-wow** [comment]
> So it's 22c8a2a as noted on the release page.

Actually, it's not. That's the commit the release download was at the time you looked at the releases page, but that gets updated every time we create a build (we only keep one version around for download). And indeed, that commit hash doesn't match with Ansem's statement that he downloaded it on 4 March 2019.

I don't think we keep a reference to the commits in these release files, so unless someone takes note of the commit hashes when they download a release - but let's be honest, nobody does that and we can't expect people to do so - I don't think there's an easy way to figure out the commits it was created from...

Maybe this is something @cyberium can improve in the builds? Say add a text file in the downloaded archives with the commit hashes?

**Comment by jimmybrancaccio** [comment]
@Ansem Do you still have this problem with the latest code?

**Comment by BenDol** [comment]
I was able to reproduce and fixed it in a PR

**Comment by jimmybrancaccio** [comment]
@BenDol Awesome. We'll let the PR close the issue then. Thanks!! 😄

**Comment by Ansem** [comment]
Compiled with latest DB and core per 2-6-2019.
Problem still exists and is unsolved and unchanged.

**Comment by BenDol** [comment]
Did you compile my branch? Latest cmangos master core doesn't have the changes yet.

**Comment by Ansem** [comment]
I used the master branch and wasted all my soulshards, haha.
How do I access your branch, and at what time would this merge with the master branch?

**Comment by BenDol** [comment]
Can see the progress here https://github.com/cmangos/mangos-tbc/pull/288 and I have no idea, when ever the main devs decide to merge it.

**Comment by Ansem** [comment]
Confirmed it works!
Now just waiting until they merge it with the main one. Thanks!
