### ISSUE TITLE
Karazhan Chess Event All Pieces Have 1% HP

### ISSUE THREAD

**Issue by ezzo300** [cmangos/issues#1912]
**Current behavior**: 
When you start the Chess Event Game ,all  the pieces are 1% HP  , and when they start fight they die from the first strike.
**Expected behavior**: 
the pieces should be 100% health points 
**Steps to reproduce**:

1. go creature Echo of Medivh (or enter Karazhan and start the chess event.)
2. Take control of you faction king.
3. after fight start pieces found all on 1% hp

**Client version**: 
2.4.3 TBC
**Commit hash**: 
57b3a61bb117365b25c5e8d3f0c1b5c650ff551d
**Database version**: 
969e3722d75c5f7837197709e6b77dd2c0ae0fb5
**Operating system**: 
linux (ubuntu )

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by LevelOneX** [comment]
I can confirm this.

**Comment by ezzo300** [comment]
> I can confirm this on my side as well.

you mean u have the same issue ?  ))

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/32c14ba729e89f5c920c24a0a73158284937c58f
