### ISSUE TITLE
Rogue Spell Doesn't Stop Eating

### ISSUE THREAD

**Issue by kuramajssken001** [cmangos/issues#1914]
## 🐛 Bugreport

Rogue Sap spell can not cut short eating.
### Expected behavior

Stop eating immediately.
### Version & Environment

Client Version: [8606]

CMaNGOS Repo & Commit Hash:  []()
https://github.com/cmangos/mangos-tbc/commit/96cabc05dd5479552a8d5e9699633a4693cf0a78

Database Repo & Commit Hash: []()
https://github.com/cmangos/tbc-db/commit/06a95e7ed8ee2777a5d9d95436c3c868994d6748

Operating System: []
Win 2008 R2

**Comment by Pastew** [comment]
Confirmed on TBC. Proof below.
![sap_eating](https://user-images.githubusercontent.com/5671416/54717314-3337a200-4b58-11e9-8360-ea037dd78ad2.gif)

**Comment by berserkingyadis** [comment]
Can confirm that sapping does not cancel eating on latest DB and core.
