### ISSUE TITLE
Spam Summon Ekkorash in Netherstorm 

### ISSUE THREAD

**Issue by 5man999** [cmangos/issues#1915]
Using https://www.wowhead.com/item=29207/conjuring-powder a player can spam summon Ekkorash in relation to this quest https://www.wowhead.com/quest=10173/the-archmages-staff 

Both the spell and the item don't have any cooldowns. Ekkorash also doesn't have a duration time, resulting in her not despawning after a certian period of time.

**Expected behavior**

I have no idea what the blizzlike experience is meant to be for this quest, the only thing I do know that in the current state a player can continually spawn Ekkorash until the server performance starts to feel unwell.

Spellid - `Id` = '34992' Summon Ekkorash: I changed the duration index to '4' to be 2mins. 
Also itemid - `entry` = '29207' - Conjuring Powder: Spell_cooldown1 to '220000'

Edit: Changing the spell duration doesn't despawn Ekkorash, I've chosen to just do a AIscript

REPLACE INTO `creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES (1949303, 19493, 1, 0, 100, 0, 150000, 150000, 0, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Ekkorash the Inquisitor - Despawn OOC');

**Client Version:** [] "2.4.3" (TBC)

**CMaNGOS Repo & Commit Hash:** cmangos/mangos-tbc@4add5bc

**Database Repo & Commit Hash:** cmangos/tbc-db@5b5e775

**Operating System:** [] Windows
**Steps to reproduce**

-Go to ArklonRuins in Netherstorm
-Take the quest https://www.wowhead.com/quest=10173/the-archmages-staff or just give yourself https://www.wowhead.com/item=29207/conjuring-powder
-Use Conjuring Powder to continually summon Ekkorash at the brazier

Crashlog

    None

**Comment by AnonXS** [comment]
```
Effect 0:
Id: 61 (SPELL_EFFECT_SEND_EVENT)
BasePoints = 1
Targets (0, 0) (NO_TARGET, NO_TARGET)
EffectMiscValueA = 13008
```
Need to add Cancel Event if Creature is already summoned.

**Comment by Grz3s** [comment]
hello :cactus:

**Comment by 5man999** [comment]
Awesome! Much better approach
