### ISSUE TITLE
Find Minerals Spell Fades Imeddiatly when you activate it

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#1916]
## 🐛 Bugreport
Create a char and go to mining trainer. After you train mining, activate find minerals. You will see that it fades immidiatly and doesn't track minerals

The same thing si with find herbs and find treasure dwarf racial, or even sense undead

### Expected behavior
it should stay activated and show you on the minimap nearby minerals

### Version & Environment

Client Version: [3.3.5a]

CMaNGOS Repo & Commit Hash:  [https://github.com/cmangos/mangos-wotlk/tree/b7879823f27a353eecaff65bfa66cc5e8fae1247](https://github.com/cmangos/mangos-wotlk/tree/b7879823f27a353eecaff65bfa66cc5e8fae1247)
Database Repo & Commit Hash: [https://github.com/cmangos/wotlk-db/tree/bc2e71aa160c3ed588d576b1309a977d218a6f62](https://github.com/cmangos/wotlk-db/tree/bc2e71aa160c3ed588d576b1309a977d218a6f62)
Operating System: [Win 7]

### Steps to reproduce
1. Create any char
2. Learn mining from a trainer
3. Activate find minerals from the minimap
4. ...
5. Profit

### Crashlog

- None

**Comment by al3xc1985** [comment]
I forgot yo say that I use playerbots

**Comment by al3xc1985** [comment]
I tried with a clean core, without playerbot to exclude eventually problems, and the problem with find minerals is the same

**Comment by Rog360** [comment]
Also post in issues here --> https://github.com/cmangos/issues/issues/1876

**Comment by al3xc1985** [comment]
thank you very much , I will close this one
