### ISSUE TITLE
WOTLK borean tundra murlocks 

### ISSUE THREAD

**Issue by rmzV** [cmangos/issues#1917]
http://www.wowhead.com/quest=11560/oh-noes-the-tadpoles
On live saved murlocks running near you for some time 

video
https://www.youtube.com/watch?v=WxAaYVg6c3A

**Comment by jimmybrancaccio** [comment]
Hello,

Please use the bug template when filing issues. This allows us to collect all the necessary information to further investigate the issue.

Thanks,
