### ISSUE TITLE
Charm Effects / Mind control

### ISSUE THREAD

**Issue by talamortis** [cmangos/issues#1920]
## 🐛 Bugreport

Charm Effects / Mind control  has an issue is player is dueling/fighting another player and one of them get charmed if the aura runs out normally, the caster will still be channeling the effect.

Tested with @lillecarl.

https://cdn.discordapp.com/attachments/453301823034359809/562386889387278347/unknown.png

### Expected behavior

Upon the aura being removed from the charmed player the caster should stop channeling the effect.

### Version & Environment

Client Version: [] "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash:  [TBC](https://github.com/cmangos/mangos-tbc/commit/849e036f67d337a0bea85d10961be977faa8d220) 

Database Repo & Commit Hash: []()

Operating System: [] Windows 10

### Steps to reproduce
1. Make two characters priest and another of choice
2. Mind control the other player
3. let the aura effect run out correctly.
4. 
5. Profit

### Crashlog

- None

**Comment by Lillecarl** [comment]
@Warlockbugs Thoughts?

**Comment by killerwife** [comment]
this should be resolved now.
