### ISSUE TITLE
Black Temple: Akama and Shadow of Akama BUG (TBC 2.4.3)

### ISSUE THREAD

**Issue by Zettoo** [cmangos/issues#1921]
Current behavior: The NPCs can not attack Akama (and Akama does not attack anyone), the NPCs that launch the ray in the shadow of Akama are constantly throwing it and when you kill them the buff counter (the buff is generated by the beam that launch the NPCs in the shadow of akama) does not decrease, stays fixed at 7 (7 are the NPC's that throw the beam, as you go killing it should decrease the counter of the buff (7,6,5 ...), therefore, the shadow of akama is constantly stationary and never comes close to akama.

Expected behavior: That the NPC's can attack Akama (Akama does not have any flag that makes it immune, or not attackable), that as you kill the NPC's that control the shadow (specifically 7) of Akama, the The buff counter decreases until it reaches 0 (all dead NPC's). Then the shadow of Akama can move and get closer to Akama and as they begin to fight.

Client version: 2.4.3 Client

Core Hash:

6a6657326ff49a39cac0bef695d35b05f75b2c40

Database version: mysql 5.6.
Operating system: Windows 10

**Comment by AnonXS** [comment]
duplicate https://github.com/cmangos/issues/issues/1814
