### ISSUE TITLE
Wisps not spawning on Archimonde

### ISSUE THREAD

**Issue by Yatzii93** [cmangos/issues#1924]
## 🐛 Bugreport
 Wisps do not spawn on ending phase

### Expected behavior

Wisps should spawn periodically in random locations around the boss during last kill phase.

This fixed the problem for me - ( I can safely say that there is going to be way better ways to fix this, I just do what I can to get things working. I guess this is a start. ) 

                if (m_uiSummonWispTimer < uiDiff)
                {
                    float m_fAngle;
					float fX, fY, fZ;

					//m_creature->SummonCreature(NPC_ANCIENT_WISP, float(urand() % 40), float(0 % 40), 0, 0, TEMPSPAWN_TIMED_OOC_DESPAWN, 15000);
					m_creature->GetNearPoint(m_creature, fX, fY, fZ, 200, 75.0f, m_fAngle + frand(39.30f, M_PI_F * 2));
					m_creature->SummonCreature(NPC_ANCIENT_WISP, fX, fY, fZ, 0, TEMPSPAWN_TIMED_OOC_DESPAWN, 15000);
					m_uiSummonWispTimer = urand(1000, 1500);
                }
                else
                    m_uiSummonWispTimer -= uiDiff;

### Version & Environment

Client Version: [] 2.4.3

CMaNGOS Repo & Commit Hash:  []() https://github.com/cmangos/mangos-tbc/commit/2978d347c04000c9ed0ee2579b44a822a6e0d864

Database Repo & Commit Hash: []() https://github.com/cmangos/tbc-db/commit/b0f586fbd5c9d7332a90ac9ba5be9b44c159b0bf

Operating System: [] Win

### Steps to reproduce
1. Get Archimonde in hyjal to 10% to trigger ending phase

### Crashlog

- None

-Yatzi

**Comment by killerwife** [comment]
Non issue it seems.
