### ISSUE TITLE
Two Questions of Feedback

### ISSUE THREAD

**Issue by forever2019** [cmangos/issues#1927]
TBC 2.43 
OS: windows10

Illidan Stormrage does not physically attack, and invalid targets cannot attack it.
![image](https://user-images.githubusercontent.com/49540243/56004691-4b39b600-5cff-11e9-8d62-52261f2354e2.png)

Illidan Stormrage has no physical attack action, the core has been prompting the following information.
![image](https://user-images.githubusercontent.com/49540243/56004711-57be0e80-5cff-11e9-8ce6-f8c66407b511.png)

**Comment by AnonXS** [comment]
duplicate https://github.com/cmangos/issues/issues/1617
