### ISSUE TITLE
Stormchops can be applied to target and also procs to often

### ISSUE THREAD

**Issue by Yatzii93** [cmangos/issues#1929]
🐛 **Bug Report:**

Stormchops (http://db.excalibur.ws/?spell=43730) can be applied to target units and the proc also triggers on every recieved hit. The results are beutiful but definitly not intended.

**Expected behavior**
Stormchops shoud only be applied to self and shouldn't be procing from recieved damage (I think-based on tooltip and the results seemingly being to nutty to be blizzlike)

I fixed the problem where it applies to targets by changing the spells target to self in my db but as I have learnt recently this is not the way to go about it.

**Version & Environment**

**Client Version**: [] 2.4.3

**CMaNGOS Repo & Commit Hash:** cmangos/mangos-tbc@2978d34

**Database Repo & Commit Hash:** cmangos/tbc-db@b0f586f

**Operating System:** [] Win
**Steps to reproduce:**
1. Get stormchops .additem 33866
2. Target enermy creature, press stormchops
3. Attack creature (or multiple with applied debuff) 
4. Watch the lightshow!

Crashlog

    None

-Yatzi

**Comment by al3xc1985** [comment]
Also:
https://www.wowhead.com/item=33871/recipe-stormchops#comments
"At Blizzcon during the item panel, the dev's said that eating this and standing next to a critter or mob in the rain would have a "special" effect. Waiting to try this out as soon as I get the recipe."

**Comment by al3xc1985** [comment]
also Quite nice for a small amount of extra threat-generation. The ranged component can be particularly useful for Warriors and Bear-tanks. It'll allow them to generate a small level of AOE threat, similar to a Pally's Consecration.

It's only 53 to 67 damage. But it may also help change the mind of an undecided mob, who has just left melee range, and headed toward your healer.

**Comment by al3xc1985** [comment]
it has a lot of effects.. I just collected some, there might be more.. I let this info for devs to check the link and see all of them from comments of wowhead

**Comment by Yatzii93** [comment]
From hellground: - If you want a fix, it does involve changing the spell data though.
spellInfo->EffectTriggerSpell[0] = 43733;
                spellInfo->EffectTriggerSpell[1] = 43731;
                spellInfo->EffectImplicitTargetA[1] = 1;
                spellInfo->EffectImplicitTargetB[1] = 0;
                spellInfo->AttributesEx2 |= SPELL_ATTR_EX2_FOOD_BUFF;

**Comment by berserkingyadis** [comment]
Still zappy boi. https://gfycat.com/wideeyedbitesizedjohndory

Definitely not "occasionally"

**Comment by AnonXS** [comment]
Cant be applied to enemy anymore, procc rate adjusted.

https://github.com/cmangos/tbc-db/commit/ab512902982a02347e307deb4720d7800e1ff5c2
