### ISSUE TITLE
PlayerBot non-combat actions are only performed while moving

### ISSUE THREAD

**Issue by jasongdove** [cmangos/issues#1930]
## 🐛 Bugreport

PlayerBot will only perform non-combat actions while moving. This is a problem in itself because you have to pace bots around for them to apply buffs, etc, but this also prevents them from using items (like food/drink).

I believe this regression was introduced with this commit https://github.com/cmangos/mangos-wotlk/commit/18b9703681cfa3c5466047f8a08d05abfc1e8824

### Expected behavior

Bots should perform non-combat actions while master is idle/not moving.

### Version & Environment

Client Version: [3.3.5a]

CMaNGOS Repo & Commit Hash:  [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/74ff47b46d58d56b9476ba6f0b41e9a7f5168f64)

Database Repo & Commit Hash: [WOTLK](https://github.com/cmangos/wotlk-db/tree/9ff057287e913c39db34284fbe5c3e334adc4616)

### Steps to reproduce
1. Summon bot
2. Add water to bot's inventory
3. Without moving, force bot to cast spells until mana is low
4. Note that bot will not drink if master remains stationary
5. Move bot, and note that message is displayed that bot needs to drink, but this will also fail because of the movement. Therefore, the bot will never replenish its mana.

**Comment by cala** [comment]
Greetings,

I've also noticed this. Thank you for investigating further this issue: I'm fixing it right now.
