### ISSUE TITLE
Questions of Illidan and Akama

### ISSUE THREAD

**Issue by forever2019** [cmangos/issues#1931]
## 🐛 Bugreport
At present, Illidan has no attack action, and players can not attack Illidan, indicating invalid targets.

### Expected behavior
When the dialogue between Illidan and Akama is over and the battle begins, Illidan players can attack.
Illidan also had physical attacks.
Please give priority to repair.
Thank you!

### Version & Environment
  - "2.4.3" (TBC)

Compiled latest source code, latest database

![QQ截图20190416004715](https://user-images.githubusercontent.com/49540243/56151142-2e450180-5fe3-11e9-8750-152a4fa6d2a0.jpg)

When Illidan is not physically attacking, the core always prompts this information.

![QQ截图20190416010257](https://user-images.githubusercontent.com/49540243/56151229-63515400-5fe3-11e9-98fe-8d8188976aa7.jpg)

Please give priority to repair.
Thank you!

**Comment by AnonXS** [comment]
duplicate https://github.com/cmangos/issues/issues/1617
