### ISSUE TITLE
'shared' not building with boost 1.70

### ISSUE THREAD

**Issue by natiewow** [cmangos/issues#1932]
## 🐛 Bugreport
FreeBSD just got boost 1.70 in the ports tree and now building cmangos fails with the following:

```[  9%] Building CXX object src/shared/CMakeFiles/shared.dir/Util.cpp.o
In file included from /home/mangos/mangos-tbc/src/shared/Util.cpp:22:
/home/mangos/mangos-tbc/src/shared/TSS.h:64:37: error: no type named 'sp_dereference' in namespace 'boost::detail'
            typename boost::detail::sp_dereference< T >::type operator*() const
            ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/home/mangos/mangos-tbc/src/shared/TSS.h:64:51: error: expected member name or ';' after declaration specifiers
            typename boost::detail::sp_dereference< T >::type operator*() const
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
2 errors generated.
*** Error code 1
```

### Version & Environment

CMaNGOS Repo & Commit Hash:
https://github.com/cmangos/mangos-classic/tree/4d9755af3341ebcff08ca6bbeebd5b06cfddc8dd
https://github.com/cmangos/mangos-tbc/tree/fc792319768322ee4937f7dcf6d7c57fe56df0bd
https://github.com/cmangos/mangos-wotlk/tree/4f87375e834784ef72c1d7e320782b5dfd5fe76c

Operating System: FreeBSD 12.0-RELEASE-p3

**Comment by natiewow** [comment]
After some googling I think I fixed it by including `<boost/shared_ptr.hpp>` in TSS.h. It builds and seems to work Ok, but I have no idea if this is the correct way.

**Comment by evil-at-wow** [comment]
The ```boost/shared_ptr.hpp``` header is where the sp_dereference template is defined, so I'd say yes, that's a good way to fix it. 
Older boost versions - I checked with an older 1.62 I have here -apparently included that header themselves in ```boost/thread/tss.hpp```, so that's where TSS.h got it and why it has worked so far. Looks like boost 1.70 reorganized their headers a bit.

**Comment by MantisLord** [comment]
I can confirm I was having the same issue with 1.70 and this change fixed it for me.

**Comment by Warlockkaal** [comment]
This is the exact problem I'm having.  How do you "include" <boost/shared_ptr.hpp> in TSS.h?

**Comment by natiewow** [comment]
Just add the line

```#include <boost/shared_ptr.hpp>```

somewhere at the top of that file.
