### ISSUE TITLE
Player animation stuck running when afk for a period of time(on player zone-in)

### ISSUE THREAD

**Issue by Yatzii93** [cmangos/issues#1933]
## 🐛 Bugreport

Players who are afk for a period of time close to the time it takes to get an AFK flag, seem to run on the spot to a player who has zoned into the area. As soon as they move the player animation corrects itself and it seems to only happen when players are loaded in. If someone afks whos already present, they won't start moving.

I don't even know where to begin troubleshooting with this one.

### Expected behavior

Players afk should stand still if no movement action is preformed on their character, even so I can't think of a scenario where a player should do the running animation when still.
### Version & Environment

Client Version: [] 2.4.3

CMaNGOS Repo & Commit Hash:  []() https://github.com/cmangos/mangos-tbc/commit/fc792319768322ee4937f7dcf6d7c57fe56df0bd

Database Repo & Commit Hash: []() https://github.com/cmangos/tbc-db/commit/f4b89833b36c3d2a23265380ac2eeb4e20053a21

Operating System: [] Win Server 2012 R2

### Steps to reproduce
1. Haven't been able to reproduce in LAN, only tried a couple times though. Better to test with players connecting in externally.
2. Have a player go afk until the AFK flag shows
3. Have another player zone into the area where the AFK player resides 
4. Player will be running on the spot

Not sure if it happens everytime.

### Crashlog

- None

**Comment by Yatzii93** [comment]
Reference to this issue on alternative core -
Player Visual Bugs · Issue #367 · Looking4Group/L4G_Core

**Comment by Yatzii93** [comment]
After further investigation it seems to be the sitting animation that's causing problems - it must not be transmitting to other clients https://i.imgur.com/RgbI8RV.jpg

This was in LAN.

**Comment by Warlockbugs** [comment]
Please, take a look if this situation has improved after latest changes.

**Comment by Yatzii93** [comment]
You legend, will get back to you tonight.

**Comment by Yatzii93** [comment]
Still occurring unfortunatly.

**Comment by Yatzii93** [comment]
Hmmm still getting the issue after re-checking. @Warlockbugs

**Comment by Yatzii93** [comment]
@Warlockbugs Sorry to keep pining - I'm still gathering info. There is an improvement in the sense that sometimes I find it's working perfect, for example just now logging in I don't see 1 person running on the spot and afk flagged people are sitting. However there are time on zone in where the same bug reappears for everyone in the area. Maybe I can identify what is 100% working and what is a hit and miss. I'll let you know.

**Comment by Yatzii93** [comment]
Ok so I'm unsure what changed but this bug has been very minimal as of late. I did rebuild the AH if that has any correlation. I will continue to monitor and report back.

**Comment by Yatzii93** [comment]
Ignore my previous comments, this definitly seems like client to server communication problem.

Not sure if related but I've uncovered some very werid behaviour concerning how the core is handling player movement packets. I've implemented Lillecarls anticheat system and I noticed that sometimes players recieve movement information from other players. 1 way to replicate it easily is using druid flightform - https://youtu.be/KIDYfksq5W4.

This happens accross the board though, its just going in and out of flightform seems to be a guarenteed way to have it happen.

Basically all the anticheat does (explaining it very simplistically) is it registers a players cordinations on the map when they move, if they move suddenly too far from the set threshold it will trigger the anti-cheat, moving them back to their old co-ordinates. What you can see in the video (or what I assume is happening) is the software is applying the druids movement packets to the non druid character.

Could this be part of a larger problem that also ties into this raised issue.

Also I've had to disable the cheat in shattrath due the same reason, take this one example and x it by 100. People port around like crazy ontop of eachother. There must be something going wrong behind to scenes, otherwise the anti-cheat feature works fine.

**Comment by Yatzii93** [comment]
Could be closed with this change - https://github.com/cmangos/mangos-tbc/commit/38406bcbb3c098ec5cad6fa610b7308754c07629 

Would be nice to have 100% confirmation from someone else. On my core I've had this change in place for over a month, no reoccurance.

**Comment by Warlockbugs** [comment]
I have verified the patch above and it also solves a remaining lost case of client freeze. Due to different packet naming and lower chance of occurrence it was overlooked during movement freezes sanitation.
