### ISSUE TITLE
Shaman two-handed talent spell

### ISSUE THREAD

**Issue by Inifield** [cmangos/issues#1934]
## 🐛 Bugreport
Right now the talent doesn't "work", this has to do with the recent change made to UpdateSpellTrainedSkills()

### Expected behavior
It should add the skills to your character panel under skill tab

### Version & Environment

Client Version: [] 1.12.1

CMaNGOS Repo & Commit Hash:  []() https://github.com/cmangos/mangos-classic/tree/4d9755af3341ebcff08ca6bbeebd5b06cfddc8dd

Database Repo & Commit Hash: []()(https://github.com/cmangos/classic-db/tree/13992f3a57e7581421af6d9e7c3f79ad46745cbc

Operating System: [] Win10

### Steps to reproduce
1. Make a shaman and level it to 10+
2. Go to ench skill tree
3. Learn Two-handed axes & maces
4. Go to character panel & skill tab
5. Notice you don't have weapon skill two-handed axes & maces here

### Information
I've noticed that  [this line](https://github.com/cmangos/mangos-classic/blob/master/src/game/Entities/Player.cpp#L5586) is the problem, if you revert it to https://i.imgur.com/nhUJEYU.png everything works again, because since we aren't getting the skill it returns EQUIP_ERR_NO_REQUIRED_PROFICIENCY

### Crashlog

- None

**Comment by standujar** [comment]
Should we open a PR with your change ?

**Comment by emil19ro** [comment]
someone fixed this bug?

**Comment by standujar** [comment]
Didn't saw a fix on the PR :'(

**Comment by Inifield** [comment]
The "fix" in the imgur picture is basicly just a partial revert of someone's else commit, you can use it as a temporary solution until Warlockbugs does a proper fix

**Comment by standujar** [comment]
@emil19ro https://github.com/standujar/mangos-classic I did that temporary changes on a fork :) if you want to use it

**Comment by Warlockbugs** [comment]
Fixed in https://github.com/cmangos/mangos-classic/commit/485637e8793f3db1d271e1e52dc2c50a1c8aecbf
