### ISSUE TITLE
Player Moves Through Textures While Under Fear From NPC

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1935]
## 🐛 Bugreport
Player moves through textures when he is under fear. Then falls and dies. 
Video: https://radikal.ru/video/Bh5PUd8cGCz

### Expected behavior
Player shouldn't run throuth textures.

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: fc792319768322ee4937f7dcf6d7c57fe56df0bd
Database Repo & Commit Hash: a5d6c50ec4d99270b642ae3a30e2ee774cf8d3ec

Operating System: [Win 64]

### Steps to reproduce
1. Go to creature with fear (for example npc=9167)
2. Start combat
3. Wait until fear
4. ...
5. Do it several times and check movement of player.

### Crashlog
- None

**Comment by datchannin** [comment]
I've tested new release, how to fear and moving while the fear is working. And see that now player can also fly while fear, fly over the pits in the air. And still sometimes do it through textures. So if fear cancels while you move through textures you can fall and die.

Example:
https://radikal.ru/video/5KifcUapiuP

**Comment by Warlockbugs** [comment]
The patch was not related to this issue in particular, but buildings, that's why it remains open. The slope picking issue is still occurring on the open terrain and requires more attention.

**Comment by cyberium** [comment]
@jimmybrancaccio another exemple bad labeling ;) its obvious that this was replicated if you read the @Warlockbugs comment.

**Comment by jimmybrancaccio** [comment]
Ah my apologies @cyberium! Will be more careful in my reading and labelling.

**Comment by Warlockbugs** [comment]
All random movement generators now use unified point picking since:

https://github.com/cmangos/mangos-classic/commit/af22e480aade560f8ceab000a7052cda9e6ea5fe
https://github.com/cmangos/mangos-tbc/commit/8fd1742bc7c0543668cbe9942409f4159faa14af
https://github.com/cmangos/mangos-wotlk/commit/e962fb0a25220abd63d41360e34a8b90bcb64c3c

Running on top of the vertical cliff should no longer be the case.
