### ISSUE TITLE
Shaman The Same Totems Stack If They Have Different Level

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1938]
## 🐛 Bugreport
If you use the same shaman totems different level in one group, you will recieve bonus from two (three, four) the same totems.
This works for Strength of Earth Totem for example, and the same type of totem.
Several totems stack only visual as buff plate, but not give you multi-bonus.
![image](https://user-images.githubusercontent.com/39913306/57167522-c118d500-6e06-11e9-888f-90250464e8e5.png)

![image](https://user-images.githubusercontent.com/39913306/57167555-e0176700-6e06-11e9-8cc5-0849f764de90.png)

### Expected behavior
Totems should not stacking. 
This is list of all stackable totem from november 2007:
http://www.twentytotems.com/2007/11/stackable-totems-guide_27.html

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: 5722e638bdf1aa6cdee9abf63a7b2940df1417df
Database Repo & Commit Hash: a5d6c50ec4d99270b642ae3a30e2ee774cf8d3ec

Operating System: [Win 64]

### Steps to reproduce
1. Create two shamans
2. Invite them to group
3. Use one of totem with stats (and multilevel) different levels
4. ...
5. Profit

### Crashlog
- None

**Comment by Warlockbugs** [comment]
Fixed in https://github.com/cmangos/mangos-tbc/commit/7b39a9c92279a91f3746b11f7ee98bb4ffa55d26.
