### ISSUE TITLE
Spell errors on mangosd Startup

### ISSUE THREAD

**Issue by Warlockkaal** [cmangos/issues#1939]
mangosWOTLK:d8184bd9bbe9f0743a72210bd5a5a1be0a46ff08
WOTLKdb: ff2d31ba2520f67af8c677b3ad6ae8b10a5f2807
Win7

I was able to build the solution in Cmake 3.14.3 and VS2019.
I have Mysql server 5.7 and followed the detailed tutorial.

Everything seemed ok until I tried to start mangosd.

It had lots of errors and ended in segmentation fault
[Server.log](https://github.com/cmangos/issues/files/3163877/Server.log)
[EventAIErrors.log](https://github.com/cmangos/issues/files/3163878/EventAIErrors.log)

Realmd started without issue.

**Comment by Grz3s** [comment]
```quote
2019-05-09 13:03:25 Loading spell_template...
2019-05-09 13:03:25 ERROR:spell_template table is empty!
```
reason for all your errors

Use ./installFulldb.sh    for correct instalation process
Make sure this part is SET UP correctly!
```code
## Define the path to your core's folder
## Core updates located under sql/updates from this mangos-directory will be added automatically
CORE_PATH=""
```

**Comment by Warlockkaal** [comment]
I should have mentioned that part.

It ran Ymiron 1.2 and it didn't seem like it did very much compared to TBC.

![image](https://user-images.githubusercontent.com/50396647/57485824-90e79100-7261-11e9-8d5f-5042b8868186.png)

![image](https://user-images.githubusercontent.com/50396647/57485855-9f35ad00-7261-11e9-8d34-edb4e1166ffb.png)

**Comment by Warlockkaal** [comment]
Wait I think I found what you meant.
![image](https://user-images.githubusercontent.com/50396647/57486040-0fdcc980-7262-11e9-8b59-b300320ec9b5.png)

**Comment by Warlockkaal** [comment]
Days and days of hitting my head against a wall, at least this time it was my fault and not the boost header.

Thanks for your help Grz3s:
![image](https://user-images.githubusercontent.com/50396647/57486286-a7dab300-7262-11e9-807d-ddda83d98bfa.png)

**Comment by DexHonsa** [comment]
What did you change in the InstallFullDB.sh file in order to make this work?  I have the exact same error log. plz help!

**Comment by ekg98** [comment]
You must point corepath to your cores location. It needs access to files that are installed with the core only.
