### ISSUE TITLE
Troll Racial Berseking Ability Adds Random Melee Speed Bonus

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1940]
## 🐛 Bugreport
If you use Troll Racial Berseking Ability, it adds you random melee speed bonus. (But fixed bonus for cast speed). See screens below. For check I used several times Berserking. Melee bonuses are different, but casting bonuses all time are 10%. (I checked with 100% hp, so it should be 10% for melee and cast).
![image](https://user-images.githubusercontent.com/39913306/57733079-5178d480-76a7-11e9-80b1-bae630025a90.png)

### Expected behavior
Speed bonus should be the same for the same hp percent of caster.

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: 879a2740b6f7367b52141cdd2f341df6a274d095
Database Repo & Commit Hash: a5d6c50ec4d99270b642ae3a30e2ee774cf8d3ec

Operating System: [Win 64]

### Steps to reproduce
1. Create troll.
2. Cast Bercerking with 100% hp
3. Check your melee speed attack (should be 1.8 every time)
4. Do 2-3 several times
5. ...
6. Profit

### Crashlog
- None

**Comment by berserkingyadis** [comment]
**Berserking**yadis can confirm. The buff modifies the atk speed from 2.0 to a range ~[1.54-1.82].

**Comment by killerwife** [comment]
Tested, seems to work as intended. Tested a priest
