### ISSUE TITLE
Npc Pet and Master Never Evade Combat

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1941]
## 🐛 Bugreport
If you aggro npc with his pet and run away from them, they will not evade combat.
If master evades - pet attacks you and master starts attack again. 
If pet evades - master attacks you and pet starts attack again.
They can evade only if do it together, but chances of this are very small.

Check the video
https://radikal.ru/video/SOwjCVNaLgm
0:34-0:36 - mage tries run OOC, but after pet attacks, he starts combat again.
0:15-0:18 - the same

### Expected behavior
Pet and master should evade combat on not throw each other to the combat again.

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: 879a2740b6f7367b52141cdd2f341df6a274d095
Database Repo & Commit Hash: a5d6c50ec4d99270b642ae3a30e2ee774cf8d3ec

Operating System: [Win 64]

### Steps to reproduce
1. Go to npc with pet (for example .go creature id 5617)
2. Start combat.
3. Try to go out of combat by run from them (try several timers)
4. ...
5. Profit

### Crashlog
- None

**Comment by BenDol** [comment]
This one has been a tough one to debug. If anyone has any suggestions to why this is happening that would help me in my debugging that would be great.

Hints I have so far:
`bool Unit::SelectHostileTarget()`
```
 if (target)
    {
        if (IsLeashingTarget(target))
        {
            AI()->EnterEvadeMode();
            return false;
        }
```
This is where it goes when evading initially, but we need to remove all the creatures from the server and spawn in a test case or its almost impossible to debug. Any help on this would be appreciated, I'll come back to this later. Going to work on something else for now.

**Comment by BenDol** [comment]
Another note is this only happens on the second evade attempt on the same mob.

**Comment by BenDol** [comment]
So you cant reproduce this properly if you aren't being attacked by the guardian (pet) consistently (i.e high speed where you just evade quickly) it only happens when you are always bring attacked by the pet and the master evades.

**Comment by BenDol** [comment]
So I've narrowed this down to the `bool Unit::IsLeashingTarget(Unit* victim) const` method. This for what ever reason is returning false for the pet which means it will forever attack you.

The call to `victim->IsWithinDist3d(x, y, z, ThreatRadius > AttackDist ? ThreatRadius : AttackDist);` on line [9215](https://github.com/cmangos/mangos-tbc/blob/master/src/game/Entities/Unit.cpp#L9215) of `Unit.cpp` results in `true`.

It checks distsq < maxdist * maxdist, example: `distsq(3719.35376) < (maxdist * maxdist)(10061.293636)` this means its still well within radius. My guess is that the pets `m_combatStartPos` resets to where it initially evaded so you have to run even further.

**Comment by al3xc1985** [comment]
tested on actual tbc and bug is fixed @killerwife  I believe it can be closed
