### ISSUE TITLE
Druid Moonkin Aura Is Stacked From Several Druids

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1942]
## 🐛 Bugreport
If you add to group several druids and use double Moonkin Form, you will have double +5% moonkin aura for druid, who second used shapeshift (first used shapeshift druid have only one copy of aura).
![image](https://user-images.githubusercontent.com/39913306/57738335-b2a8a400-76b7-11e9-9b9d-4c58b16718ee.png)

### Expected behavior
Druid aura should not stacking

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: 879a2740b6f7367b52141cdd2f341df6a274d095
Database Repo & Commit Hash: a5d6c50ec4d99270b642ae3a30e2ee774cf8d3ec

Operating System: [Win 64]

### Steps to reproduce
1. Create two druids, add talent to boonkin form
2. Create group of druids
3. Use shapeshift for first druid (check critical chance and aura)
4. Use shapeshift for second druid (check critical chance and aura)
4. ...
5. Profit

### Crashlog

- None

**Comment by datchannin** [comment]
It can be connected with aura stacking rewrite, I've never seen this before
https://github.com/cmangos/mangos-tbc/commit/7b39a9c92279a91f3746b11f7ee98bb4ffa55d26

**Comment by Warlockbugs** [comment]
This is actually a correct behavior (albeit visually) if one of two druids uses the class quest idol to add bonus rating to the moonkin aura: what shouldn't stack in this case is 5% crit. I'll look into it sometime soon.

**Comment by datchannin** [comment]
I've tested without idol. Today I've rechecked cat/bear aura and it is not stacked from several cats in group. So it may be only Moonkin issue.

**Comment by Warlockbugs** [comment]
Should be fixed as of https://github.com/cmangos/mangos-tbc/commit/6aeccd321db704e1a390d71da05c68716c9a305b.
