### ISSUE TITLE
Drums Of War Stacking From Several Players

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1943]
## 🐛 Bugreport
If you uses several drums of war while in group - effects will stack. So you can have several the same buffs.
![image](https://user-images.githubusercontent.com/39913306/57811990-62434c00-7774-11e9-9ebd-3dc04b58008f.png)

### Expected behavior
They shouldn't stack with the same drums.
![image](https://user-images.githubusercontent.com/39913306/57812059-9880cb80-7774-11e9-8e61-e9377cfb39f2.png)

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: 879a2740b6f7367b52141cdd2f341df6a274d095
Database Repo & Commit Hash: a5d6c50ec4d99270b642ae3a30e2ee774cf8d3ec

Operating System: [Win 64]

### Steps to reproduce
1. Create two characters.
2. Learn leatherworking and do it 350+
3. .add item 29528
4. creater group
5. use drums from the first character and the second
6. ...
7. Profit

### Crashlog
- None

**Comment by BenDol** [comment]
.learn all_crafts
.setskill 165 350
.additem 29528 5

**Comment by Warlockbugs** [comment]
Reopened due to a revert. Needs more work.

**Comment by Warlockbugs** [comment]
Should be fixed as of https://github.com/cmangos/mangos-tbc/commit/6aeccd321db704e1a390d71da05c68716c9a305b.

**Comment by BenDol** [comment]
Nice work! Will test it out asap
