### ISSUE TITLE
[classic] Blackrock spire - Client stuck

### ISSUE THREAD

**Issue by RichardGe2** [cmangos/issues#1944]
## 🐛 Bugreport
I have 2 players connected to my server, outside Blackrock Spire - everything ok.
1st player enters inside Blackrock Spire - everything ok.
The 2nd player enters in the same Blackrock Spire instance, and here I have an issue :  
On the Client side of the 2nd player, he can move his character but in an empty instance : no NPCs, he can't see the 1st player. he can't see his '/say', he can't logout.... 
On the Client side of the 1st player, everything is working, he can see the 2nd player moving talking... he can also see the NPCs attacking the 2nd player ( but 2nd player himself can't see he is under attack )  

Looks like a hard bug to investigate. because it seems random. I'm wondering if I'm the only one to report this issue. Or if it's a known one. I can also debug source code and investigate, but first I would like have some clues from you of where the issue could be.
For me, it looks like the client of 2nd player is not receiving any data from server. but why? and how can I check that?

Don't know if related, but sometimes on server I see the message : 
"check existing of map file maps ./maps/2293132.map : not exist"
I confirm I don't have this map, and it's not generated by the extractor

### Version & Environment
wow classic 1.12.1
windows 10
database : ee3fde8995159a4b207706082ecb23abcbc65c3b
core : 05e8b71997263ad05a00ebbb6bd97891b5e736ea
( roughly the latests at this time )

**Comment by cala** [comment]
Could you try to reduce visibility range and such in mangosd.conf and retry, please? This reminds me of something similar.

**Comment by RichardGe** [comment]
oh really, yes I increased visibility range some months ago to 300 I think remember  .. I'll try ...

**Comment by RichardGe2** [comment]
oh really, yes I increased visibility range some months ago to 300 I think remember .. I'll try ...

**Comment by RichardGe2** [comment]
your workaround is working.

As I was in an instance, I thought it was Visibility.Distance.Instances that needed to be reduced. but actually it's Visibility.Distance.Continents. I lowered it from 300 to 250.

Thank you !

closing the ticket. I don't think you guys want to fix that as I'm using non-default values.

**Comment by evil-at-wow** [comment]
> As I was in an instance, I thought it was Visibility.Distance.Instances that needed to be reduced. but actually it's Visibility.Distance.Continents.

I'm as confused as you are now. Inside an instance I would expect Visibility.Distance.Instances to count, just like you. It's even documented like that... 

For future reference: if you ever want to check that (certain) packets are sent to players, you can edit the 'WorldLogFile' setting in your mangosd.conf. The core then basically makes a text file with that name and uses it as a packet log file. In your case, with just a few players, there won't be any issue, but needless to say this file can become pretty large if your server has a lot of traffic.
