### ISSUE TITLE
Quest Dry Times crashes core when clicking quest reward 'A Bulging Coin Purse'

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#1947]
## 🐛 Bugreport

Complete quest 'Dry times' (**entry 116** of **tbcmangos.quest_template**). After receiving rewards 'Finely Woven Cloak and A Bulging Coin Purse', click on the Bulging Coin Purse to open it and collect coins. core crashes.

### Expected behavior
Click quest reward should award coins without core crash.

### Version & Environment
  Client Version - "2.4.3" (TBC)
  
  Commit Hash - TBC  - 878873cf924ac94c42fd224048e6b3240012a28d
 
  Database Version - TBC  - cd169fc6f2d3a8bf1a5a1d32f5d3cf3a5b32b692
  
Operating System - Windows 10
  
### Steps to reproduce
1. See above.
2.
3.
4. ...
5. Profit

### Crashlog
 Last lines in server.log is;
 2019-05-27 18:56:10 ERROR:Table '**item_loot_template**' loot id #**10456** used but it doesn't have records.

### Notes 
It should be noted that it does not appear that there is a **10456** entry or item number in **item_loot_template** but there is a entry of **10456** in **item_template**, where 10456 in item_template is 'The Bulging Coin Purse'

**Comment by lduguid** [comment]
![image](https://user-images.githubusercontent.com/105060/58518153-dca3a100-8162-11e9-9ca1-866c6e7a4c50.png)

**Comment by BenDol** [comment]
Why was this closed?

**Comment by lduguid** [comment]
void Loot::ForceLootAnimationCLientUpdate() const
{
    if (!m_lootTarget)
        return;
...

It appears that by the time ForceLootAnimationCLientUpdate is this case

**Comment by BenDol** [comment]
Just tested this now and for me the variable `m_objectTypeId` was the issue. Calling GetTypeId() fails.

**Comment by BenDol** [comment]
Oddly enough it doesn't crash if you receive the item then logout and login, then open it.

**Comment by BenDol** [comment]
.quest add 116
.quest complete 116
.go creature "Barkeep Daniels"

**Comment by lduguid** [comment]
> Just tested this now and for me the variable `m_objectTypeId` was the issue. Calling GetTypeId() fails.
> 
> But yeah m_lootTarget is invalid.

I agree, as seen in the stack screenshot, ..->GetTypeId() is the point of crash, I am assuming (perhaps incorrectly :P) that it would not have had a chance to call GetTypeId() if ForceLootAnimationCLientUpdate() had of bailed early with m_lootTarget set to null.

**Comment by lduguid** [comment]
> Oddly enough it doesn't crash if you receive the item then logout and login, then open it.

I will try that and report back.

**Comment by BenDol** [comment]
I have added the fix, will submit a PR. I need to look into if it the correct approach though.
