### ISSUE TITLE
Do we Need This Old Windows XP-era Hack?

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#1950]
### # Story so far:

We have an old-ass gimmick to work around some old XP-specific things. `<shakes his head in disapproval>`

Do we still need this stuff?

### # The Stuff:

TBC:
https://github.com/cmangos/mangos-tbc/blame/487c06c9721e1b4585a0bbc50655f32d7422f699/src/mangosd/Master.cpp#L273-L306

Classic:
https://github.com/cmangos/mangos-classic/blame/0272fdf7187ae03883eb63c84527fed256152021/src/mangosd/Master.cpp#L273-L306

WotLK:
https://github.com/cmangos/mangos-wotlk/blame/243ccc4a684878c03c79cefd73d51139a13ee1e8/src/mangosd/Master.cpp#L273-L306

All it does is punching some keycodes on win32 platforms to avoid some esoteric bug in Windows XP.

**Comment by killerwife** [comment]
@cyberium this is way too dank and before my time. Any idea what to do here?
