### ISSUE TITLE
Mount and Dismount Will Heal Warlock Pets to Full HP

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1953]
## 🐛 Bugreport
If you have injured Warlock pet (for example Void), you can use your mount and after this you can use dismount. Your pet will disappear after mount. And after dismount it will appear again but with full HP bar.

### Expected behavior
Pet shouldn't be healed after Warlock dismount.

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: 2bd07043438cbae4b64352e9d14d35cf49c109b4
Database Repo & Commit Hash: c8569c4265b62678a574a8c3951a871ef5662843

Operating System: [Win 64]

### Steps to reproduce
1. Create warlock
2. .add 6265 (add shard)
3. summon Void
4. damage him using .damage 1000
5. use your mount
6. dismount
7. check HP of your Void
8. Profit

### Crashlog
- None

**Comment by killerwife** [comment]
Non issue. Retested and works as intended. Only watch out for blood pact.
