### ISSUE TITLE
Friendly Units Don't Attack You If You Start Attack Them

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1955]
## 🐛 Bugreport
If you want to attack friendly units to change your reputation. They will not start attack you after your hit, if you have reputation more than friendly.

### Expected behavior
Units should attack you if you start attack them

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: 2bd07043438cbae4b64352e9d14d35cf49c109b4
Database Repo & Commit Hash: c8569c4265b62678a574a8c3951a871ef5662843

Operating System: [Win 64]

### Steps to reproduce
1. .tele Booty Bay
2. .modify rep 21 10000
3. add "At war" option
![image](https://user-images.githubusercontent.com/39913306/58836184-bc8f4880-8660-11e9-99aa-92dcc5be37ec.png)
4. Start attack enemy (friendly) unit
5. Check his reaction
6. Profit

### Crashlog
- None

**Comment by berserkingyadis** [comment]
Did the listed steps, Booty bay NPCs get attackable and react by chasing you in combat stance, but they dont attack. Don't know about how it was back in the day tho.

![image](https://user-images.githubusercontent.com/9959527/74230547-e0f9f500-4cc4-11ea-86fc-46d300dbd364.png)

core: https://github.com/cmangos/mangos-tbc/commit/1ee44bb75c87fb599f85d8d959dbf7d1933fb05a
db: https://github.com/cmangos/tbc-db/commit/8134aaac47ac3eb45a6acd42e1948f7c0b241d1c

**Comment by killerwife** [comment]
At war has been adjusted twice since this. Resolved.
