### ISSUE TITLE
Connection Was Forcibly Closed by Remote Host

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1958]
## 💬 Support Question
Hi, may be someone faced with the same issue: while core run and players are in the world, host (or database, or core, or something else) disconnects players. Then player can see only frozen client, should kill it using ctrl+alt+del and reconnect to server. 
This happens every day, without time reference. 
I googled the issue and read a lot of different cases with different places - cores, web-servers, database-servers, 1C, and so on. And some developers say this is may me host issue, others say - database...

May be someone faced such problem and knows where to find the solution.
This is console while issue is active:
![image](https://user-images.githubusercontent.com/39913306/59196009-2eeab600-8b96-11e9-8484-b28a364f37af.png)
![image](https://user-images.githubusercontent.com/39913306/59196082-56da1980-8b96-11e9-9943-37ea45274474.png)

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: 4a04c15feeb570b44dae9789ebd21abadbdfd1f5
Database Repo & Commit Hash: fc8cf015e0c47607d018253d23d37d194395a2ce

Operating System: [Win 64]

### Steps to reproduce
I don't have any steps. And can't reproduce it with 100% probability. But I see this every day.

**Comment by Levitanious** [comment]
@datchannin If it's possible, can you run the thing in a debugger? Break at socket error, snapshot the process state -- so we can trace the thing back.

Recently added ReleaseWithDebugSymbols build type will help.

**Comment by berserkingyadis** [comment]
Whats the scenario here? Are you running the server while being connected to router via WiFi?

 How many players are playing on your server? Are they in another network/country?

**Comment by datchannin** [comment]
Thanks for pointing, I'll update repository hashes.
As I know, host uses cable connection, not WiFi.
I've already asked help from host owner, they said: "there are not any problem from our side".

Last time I was able to see this issue in real time. Checked connection to host. There are not connection issues with RDP, and I didn't see any issues with web-servers.

I have near 70-90 average players on the server (peak is 115). They are from different countries. Mainly Belarus, Ukraine, Russia. And disconnections are not connected with countries, players from every countries were disconnected.

Can be errors of such type are mainly related only to the host? I thought it can be related to SQL connection. For example limitation of clients allowed, or something near that?

**Comment by evil-at-wow** [comment]
I would exclude database connections for now. The server has a fixed number of connections to the databases, and typically the database will run on a server in the same network (or even on the same server). Clients (read: players) don't have any connection to the databases; they only connect to realmd and, after successful authentication, to mangosd.

These logs look more like clients closing the connection, because of something the server itself does. What's the time span of the log you're showing? A client disconnecting every now and then (like several minutes between tem)? Or is this more several clients disconnecting in a short period of time and then nothing for a while?

**Comment by datchannin** [comment]
For time: I see pack of disconnects once per 1.5-3 hours. Something like 50-60 players are disconnected simultaneously. This is parse of my server.log. I highlight such packs of disconnect:
![image](https://user-images.githubusercontent.com/39913306/59310125-0c4bc080-8cae-11e9-83f5-36017acf53f6.png)

**Comment by jimmybrancaccio** [comment]
Is this still an problem or may we close out this issue?

**Comment by datchannin** [comment]
This issue is still exist, but you can close this report: players could not play with such disconnects every several hours, so I closed the server.
Thanks everyone who tried to help.

**Comment by jimmybrancaccio** [comment]
Sounds good, thanks for the update @datchannin. Don't hesitate to hit us up in Discord if you still see any issues. Or if you come up with a good way to replicate don't hesitate to reopen the issue here!

**Comment by Warlockbugs** [comment]
Suspected cause is the recent wave of attacks against emulated servers using invalid UTF-8 sequences in chat channel names which caused connected player clients to freeze. A protective measure against UTF-8 shenanigans was just deployed.

**Comment by Yatzii93** [comment]
@Warlockbugs <3
