### ISSUE TITLE
Spell Temporal Phase Modulator Hungs or Crash Core

### ISSUE THREAD

**Issue by datchannin** [cmangos/issues#1959]
## 🐛 Bugreport
If you use Spell Temporal Phase Modulator several times on the same target, core hungs forever. You only can restart it.

Video link: https://radikal.ru/video/YXluczLlb5N

### Expected behavior
Core should not hungs.

### Version & Environment
Client Version: ["2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash: 4a04c15feeb570b44dae9789ebd21abadbdfd1f5
Database Repo & Commit Hash: c84631b0cc6b68f01a42b182c19d972d2ff47cae

Operating System: [Win 64]

### Steps to reproduce
1. .tele Blade
2. .quest add 10609
3. fly to egg and open it
4. use Temporal Phase Modulator several times
5. Profit

### Crashlog
- None

**Comment by datchannin** [comment]
Sometimes core crash without hung.
May be this can help (this occures after crash in debug mode):
![image](https://user-images.githubusercontent.com/39913306/59302919-bc64fd80-8c9d-11e9-8c48-5a389459da88.png)

**Comment by datchannin** [comment]
If revert this one - crash will disapper.
https://github.com/cmangos/mangos-tbc/commit/56acbbd006b0c5d30929a0d3fe1ded114d632bca

**Comment by BenDol** [comment]
Can you see if you're able to reproduce this using https://github.com/cmangos/mangos-tbc/pull/285 instead?

**Comment by BenDol** [comment]
Confirmed this isnt happening with my changes only

**Comment by killerwife** [comment]
Can you guys give me a full stack trace?

**Comment by datchannin** [comment]
What does it mean "stack trace"? Steps to reproduce? Or crash log?
If about log - I run core on Windows, and core does not produce logs for Win in case of crash. Or may be I don't know where I should search for logs.

**Comment by killerwife** [comment]
I consider this resolved. I removed duplicate script.
https://github.com/cmangos/mangos-tbc/commit/74e6f3a1766d56c2e56f3881bb26f1c98b4267b0
If issues persist in a different script, I will gladly go put out that fire again.
