### ISSUE TITLE
Config is Installed as .conf.dist

### ISSUE THREAD

**Issue by seirl** [cmangos/issues#1963]
I get why it's useful to install the config as .conf.dist files, but for packages it's very bad practice to not have the config installed properly by default. Most package managers already have a way to handle conflicts to avoid overriding user config when installing (e.g `.new` files in Pacman). Right now I have to manually move the files like this after the package creation:

      mv "${pkgdir}/etc/realmd.conf.dist" "${pkgdir}/etc/realmd.conf"

  It would be good to have a configure flag that allows to directly install the files as .conf instead of .conf.dist.

**Comment by jimmybrancaccio** [comment]
Hello,

If you wish to track this information on the CMaNGOS repositories please update your original post (or create a new issue) so that it conforms to our issue templates. If you have any questions please do not hesitate to reach out.

Thanks,

**Comment by Muehe** [comment]
@seirl Would this be solved by copying to `.conf` when there is no pre-existing file and copying to `.conf.dist` if there is one already?

**Comment by seirl** [comment]
Yes. I think the "standard" way to do that is to use `install --backup` for configuration files.

**Comment by esno** [comment]
that's not cmake syntax. cmake's `install` (https://cmake.org/cmake/help/v3.13/command/install.html) does not provide a backup flag. A workaround could be something like this:
```
 install(CODE "
  if (NOT EXISTS \"${destination}/myfile.txt\")
        file(INSTALL \"${source}/myfile.txt\" DESTINATION \"${destination}\")
    endif()
 ") 
```
from my point of view the good pattern is to rename the files in your PKGBUILD and let your package manager deal with file conflicts.

**Comment by seirl** [comment]
> from my point of view the good pattern is to rename the files in your PKGBUILD and let your package manager deal with file conflicts.

Alright!
