### ISSUE TITLE
🚀 [Feature Request] Use of __FILE__ Prevents Reproducible Builds

### ISSUE THREAD

**Issue by seirl** [cmangos/issues#1966]
## 🚀 Feature

Right now, the use of the `__FILE__` macro makes it so that some of the paths that were used at build time are included as strings in the binaries. This makes builds non-reproducible, can be a privacy issue and make package managers not happy, with errors like "==> WARNING: Package contains reference to $srcdir". I'm not sure what a proper fix would be, maybe the usage of `__FILE__` could simply be removed. There's also apparently a -ffile-prefix-map that could be used to solve this problem:

> -ffile-prefix-map=old=new  
> When compiling files residing in directory old, record any references to them in the result of the compilation as if the files resided in directory new instead.

### Benefits & Purpose

Reproducible builds: https://reproducible-builds.org/

**Comment by jimmybrancaccio** [comment]
Hello,

If you wish to track this information on the CMaNGOS repositories please update your original post (or create a new issue) so that it conforms to our issue templates. If you have any questions please do not hesitate to reach out.

Thanks,

**Comment by seirl** [comment]
@jimmybrancaccio done, please reopen

**Comment by killerwife** [comment]
I am not closing this as its still relevant, I reviewed the FILE usages and this stackoverflow is the solution for it. https://stackoverflow.com/a/40947954 I do not care enough to invest time into it but someone might.

**Comment by insunaa** [comment]
Looking back into this due to the packaging stuff, the *only* occurrence of `__FILE__` in a Release Build with `-DNDEBUG` is
https://github.com/cmangos/mangos-tbc/blob/b2e0c5e6b54ba79cf41cc63f25c95b831a497789/src/shared/Errors.h#L44
where for some reason we insist on not dropping asserts.

Instead of
```cpp
#define WPError(CONDITION) \
if (!(CONDITION)) \
{ \
    printf("%s:%i: Error: Assertion in %s failed: %s", \
        __FILE__, __LINE__, __FUNCTION__, STRINGIZE(CONDITION)); \
    assert(STRINGIZE(CONDITION) && 0); \
}
```
we could also just do or something along those lines.
```cpp
#ifndef NDEBUG
#define WPError(CONDITION) \
if (!(CONDITION)) \
{ \
    printf("%s:%i: Error: Assertion in %s failed: %s", \
        __FILE__, __LINE__, __FUNCTION__, STRINGIZE(CONDITION)); \
    assert(STRINGIZE(CONDITION) && 0); \
}
#else
#define WPError(CONDITION)
#endif
```

all other occurrences of `__FILE__` are already deactivated in the preprocessor by NDEBUG or by default
