### ISSUE TITLE
🚀 [Feature Request] Disable Installation of run-mangosd

### ISSUE THREAD

**Issue by seirl** [cmangos/issues#1967]
## 🚀 Feature
We should disable the installation of `run-mangosd`.

### Visualisation
None

### Benefits & Purpose
Most distributions use systemd nowadays, making scripts like run-mangosd useless. There should be a configure switch to not install this script, or the script should be removed completely.

**Comment by jimmybrancaccio** [comment]
Hello,

If you wish to track this information on the CMaNGOS repositories please update your original post (or create a new issue) so that it conforms to our issue templates. If you have any questions please do not hesitate to reach out.

Thanks,

**Comment by Muehe** [comment]
That file has last been touched 11 years ago and I'm not sure anyone is even using it anymore. It can probably just be removed completely.

**Comment by jimmybrancaccio** [comment]
This issue is being closed out. I would however recommend submitting a new issue using our feature request template if this is something you'd like to see in future versions of CMaNGOS.

**Comment by seirl** [comment]
@jimmybrancaccio you closed a lot of my issues after saying that they didn't match the feature request template, however I wonder if you read the issues in the first place, as the issue template in that case didn't add any information seeing as they are purely technical and do not require any screenshots or anything. This one for instance is removing some parts of the code. It feels silly to rewrite it to match an issue template, as you can see. There is no need for "additional information".

Anyway, I rewrote it so that it now conforms to your template, could you please repoen this issue?

**Comment by killerwife** [comment]
I adjusted the script for our use on vengeance, we are using it for certain. Its obviously optional for those who wish to run it from startup. Closing this as its rendered moot.
