### ISSUE TITLE
No Daemon Mode For mangosd

### ISSUE THREAD

**Issue by seirl** [cmangos/issues#1968]
Right now if you immediately close STDIN after running mangosd, the daemon will shut down. This requires bad hacks when you're trying to make mangosd play nice with the init system. For instance, I had to do something like this in my systemd service:

    StandardInput=tty-force
    TTYPath=/dev/tty4

There should either be a way to run mangosd in daemon mode so that it doesn't stop when STDIN is closed (like realmd does), or use `isatty(3)` to check whether a closed STDIN means that the user wants the daemon to stop.

**Comment by evil-at-wow** [comment]
I'm going to make a semi-educated guess: you have ```Console.Enable = 1``` in your mangosd configuration? :smile:

**Comment by seirl** [comment]
Ah, yes, I forgot this was a thing. So why is this a setting instead of just a call to `isatty(3)`? Seems to me like there's no reason to have it at 1 when stdin is not a tty, and no reason to have it at 0 when stdin is a tty?

**Comment by evil-at-wow** [comment]
I can't answer why it's a setting. It's been like this for as long as I remember (and I've been around for a long time). The simple explanation is often correct, so maybe that just happened to be the first thing the developer came up with, and it was easy to implement and it worked... and no one ever felt the need to change is afterwards until now? :smile:

I agree with you that there's little to no point in having the console enabled if you don't have a tty. The other way around is at least more sensible from a technical point of view: if you run it in a terminal, you perhaps don't want the console to be enabled. But even there it's hard to come up with a compelling reason to disable it, I agree.

**Comment by jimmybrancaccio** [comment]
Hello,

If you wish to track this information on the CMaNGOS repositories please update your original post (or create a new issue) so that it conforms to our issue templates. If you have any questions please do not hesitate to reach out.

Thanks,

**Comment by seirl** [comment]
I think I'll close this since there's a workaround so the issue isn't really accurate.
