### ISSUE TITLE
TBC Priest - Mind Flay/Shadow weaving

### ISSUE THREAD

**Issue by Azelen** [cmangos/issues#197]
Mind Flay will apply stack of shadow weaving only 1 time @ last tick, and only if cast wasnt delayed by damage. it should apply 1 stack of shadow weaving @ every tick.

**Comment by Evolvee** [comment]
https://youtu.be/jD7R0WZiV0U?t=410
i dont think so

**Comment by jimmybrancaccio** [comment]
@Azelen Can you confirm if this is still an issue in the latest commits.

**Comment by killerwife** [comment]
This is no longer an issue. Shadow Weaving was fixed, so that its now applied on channel start like its intended to be.

**Comment by Evolvee** [comment]
Its not intended to be applied on channel start.
