### ISSUE TITLE
Dun Morogh 'Airstrip'

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#1974]
Currently massively underpopulated compared to vanilla (through wotlk) retail;
0 -4789 -1691 504

https://youtu.be/6dYVpMqRPAY?t=4m25s
https://youtu.be/LvUyDD0rnsE?t=4m16s
https://youtu.be/oBdwTbgG9os?t=9m14s
There should be a pet trainer located there named Peria Lamenur, she should be clapping at a dwarf dancing, whilst a gnome in warrior gear next to her should be cheering on.
Some gnome girls playing with knives should once in a while pass them by, like, very close

https://youtu.be/6dYVpMqRPAY?t=4m42s
https://youtu.be/LvUyDD0rnsE?t=4m29s
https://youtu.be/oBdwTbgG9os?t=8m54s
There should be fighting going on with trolls, and you should be able to take part of it; they should also be lootable.

https://youtu.be/oBdwTbgG9os?t=9m21s
https://youtu.be/LvUyDD0rnsE?t=2m44s
https://youtu.be/N1WLkpXHahA?t=1m18s
A dwarven scout of some sorts should be waving at players flying by - just constantly waving.
Not as bad as the other guy in the back who looks to be chopping up the bonfire with his bare hands.
There should also be several other npcs there.

https://youtu.be/LvUyDD0rnsE?t=2m57s
https://youtu.be/oBdwTbgG9os?t=9m12s
npcs by the light missing on cmangos

https://youtu.be/oBdwTbgG9os?t=9m9s
https://youtu.be/LvUyDD0rnsE?t=3m25s
there should be two npcs next to the flight that is ready to take off

https://youtu.be/LvUyDD0rnsE?t=3m3s
Missing npcs 'inside' the building, guarding the entrance

https://youtu.be/LvUyDD0rnsE?t=3m8s
Missing bonfire and npcs around it

https://youtu.be/LvUyDD0rnsE?t=3m11s
there should be an engineer at each of the standby planes

https://youtu.be/LvUyDD0rnsE?t=3m37s
there should be 2 guards next to the bogus 'entrance'

https://youtu.be/LvUyDD0rnsE?t=3m56s
should be 2 npcs in the area outisde as well

https://youtu.be/6dYVpMqRPAY?t=3m48s
https://youtu.be/LvUyDD0rnsE?t=3m25s
There should be npcs running around like there's chaos going on, all the while npcs on rams should be patrolling the populated area

(https://www.youtube.com/results?search_query=ironforge+airstrip - for further studying :+1:)

**Comment by Swater96** [comment]
I tried to upload the pictures to an imgur album but that wasn't working so here goes...

These pictures are from the classic beta and should help to get the cmangos version more accurate to the retail classic


![WoWScrnShot_062119_123523](https://user-images.githubusercontent.com/540552/59942043-5ce8b980-9424-11e9-992e-3ae80cc1c19a.jpg)
![WoWScrnShot_062119_123525](https://user-images.githubusercontent.com/540552/59942044-5ce8b980-9424-11e9-8155-7f886684b787.jpg)
![WoWScrnShot_062119_123801](https://user-images.githubusercontent.com/540552/59942045-5ce8b980-9424-11e9-8d0d-9e75dbe01ca3.jpg)
![WoWScrnShot_062119_123805](https://user-images.githubusercontent.com/540552/59942046-5ce8b980-9424-11e9-94bd-1234b16669ec.jpg)
![WoWScrnShot_062119_123810](https://user-images.githubusercontent.com/540552/59942047-5d815000-9424-11e9-8b02-e2c8718aba51.jpg)
![WoWScrnShot_062119_123817](https://user-images.githubusercontent.com/540552/59942048-5d815000-9424-11e9-8156-8ad8d763a999.jpg)
![WoWScrnShot_062119_123819](https://user-images.githubusercontent.com/540552/59942049-5d815000-9424-11e9-8273-04b787ead163.jpg)
![WoWScrnShot_062119_123834](https://user-images.githubusercontent.com/540552/59942050-5d815000-9424-11e9-8118-06931ea38c57.jpg)
![WoWScrnShot_062119_123904](https://user-images.githubusercontent.com/540552/59942051-5d815000-9424-11e9-9688-a81306d09cf4.jpg)
![WoWScrnShot_062119_123914](https://user-images.githubusercontent.com/540552/59942052-5d815000-9424-11e9-8186-dff3ab1ee67a.jpg)
![WoWScrnShot_062119_123924](https://user-images.githubusercontent.com/540552/59942053-5d815000-9424-11e9-9561-be7c8240af45.jpg)
![WoWScrnShot_062119_123934](https://user-images.githubusercontent.com/540552/59942054-5d815000-9424-11e9-9ab1-11bc6efb22de.jpg)
![WoWScrnShot_062119_123941](https://user-images.githubusercontent.com/540552/59942056-5e19e680-9424-11e9-9232-eca1ecc34982.jpg)
![WoWScrnShot_062119_123956](https://user-images.githubusercontent.com/540552/59942057-5e19e680-9424-11e9-95ea-119d792c9797.jpg)
![WoWScrnShot_062119_124010](https://user-images.githubusercontent.com/540552/59942058-5e19e680-9424-11e9-9fe4-c0752faeb04d.jpg)
![WoWScrnShot_062119_124016](https://user-images.githubusercontent.com/540552/59942059-5e19e680-9424-11e9-9b8a-5d4cdd5aa982.jpg)
![WoWScrnShot_062119_124024](https://user-images.githubusercontent.com/540552/59942061-5e19e680-9424-11e9-976b-e0777776dedb.jpg)
![WoWScrnShot_062119_124042](https://user-images.githubusercontent.com/540552/59942062-5e19e680-9424-11e9-9134-e886389085d2.jpg)
![WoWScrnShot_062119_124048](https://user-images.githubusercontent.com/540552/59942064-5e19e680-9424-11e9-8193-627ba54bb324.jpg)
![WoWScrnShot_062119_124056](https://user-images.githubusercontent.com/540552/59942065-5eb27d00-9424-11e9-8691-ade5ece648d4.jpg)
![WoWScrnShot_062119_124112](https://user-images.githubusercontent.com/540552/59942066-5eb27d00-9424-11e9-8081-8a4cd559610b.jpg)
![WoWScrnShot_062119_124119](https://user-images.githubusercontent.com/540552/59942067-5eb27d00-9424-11e9-94a9-dd491a80764b.jpg)
![WoWScrnShot_062119_124201](https://user-images.githubusercontent.com/540552/59942068-5eb27d00-9424-11e9-8fca-828fb248d655.jpg)
![WoWScrnShot_062119_124207](https://user-images.githubusercontent.com/540552/59942069-5f4b1380-9424-11e9-9d49-817d0d6a1cf6.jpg)
![WoWScrnShot_062119_124210](https://user-images.githubusercontent.com/540552/59942070-5f4b1380-9424-11e9-9b6f-1db34d83e3f7.jpg)
![WoWScrnShot_062119_124219](https://user-images.githubusercontent.com/540552/59942071-5f4b1380-9424-11e9-851b-791e6847cc02.jpg)
![WoWScrnShot_062119_124236](https://user-images.githubusercontent.com/540552/59942072-5f4b1380-9424-11e9-9a7c-c78898efd9fe.jpg)
![WoWScrnShot_062119_124238](https://user-images.githubusercontent.com/540552/59942073-5f4b1380-9424-11e9-92ce-c4c693c88095.jpg)
![WoWScrnShot_062119_124244](https://user-images.githubusercontent.com/540552/59942074-5f4b1380-9424-11e9-8d20-de540c78495a.jpg)
![WoWScrnShot_062119_124255](https://user-images.githubusercontent.com/540552/59942075-5f4b1380-9424-11e9-95d4-89cbcce40023.jpg)
![WoWScrnShot_062119_124300](https://user-images.githubusercontent.com/540552/59942076-5f4b1380-9424-11e9-9f04-5234fdcc6480.jpg)
![WoWScrnShot_062119_124306](https://user-images.githubusercontent.com/540552/59942077-5fe3aa00-9424-11e9-8cff-8c8d3dfe86fe.jpg)
![WoWScrnShot_062119_124314](https://user-images.githubusercontent.com/540552/59942078-5fe3aa00-9424-11e9-8408-01d722152e66.jpg)
![WoWScrnShot_062119_124317](https://user-images.githubusercontent.com/540552/59942079-5fe3aa00-9424-11e9-9e01-834a013cd732.jpg)
![WoWScrnShot_062119_124322](https://user-images.githubusercontent.com/540552/59942080-5fe3aa00-9424-11e9-8753-ab4f27f1b80f.jpg)
![WoWScrnShot_062119_124329](https://user-images.githubusercontent.com/540552/59942081-5fe3aa00-9424-11e9-85fc-1f4cf5b6a541.jpg)
![WoWScrnShot_062119_124343](https://user-images.githubusercontent.com/540552/59942082-5fe3aa00-9424-11e9-82f0-8e5b375f17dc.jpg)
![WoWScrnShot_062119_124406](https://user-images.githubusercontent.com/540552/59942083-5fe3aa00-9424-11e9-9e06-660b4cec14e6.jpg)

**Comment by Swater96** [comment]
@cala https://gist.github.com/Swater96/726277419ab02687f5e31862340ac600
All emotes implemented, only thing left is the Frostmane spawns (which is above my paygrade) <3

**Comment by cala** [comment]
Thank you @Swater96 and it's nice to see you around.
I will look at this soon.
