### ISSUE TITLE
Windtalker's Wristguards

### ISSUE THREAD

**Issue by Purownage** [cmangos/issues#1984]
Hi,

Windtalker's Wristguards and all other pvp rep item lvl 60 is bugger only silverwing faction is allow to buy so Hordies doesnt have access too any of theres pieces of gears. It should detect player faction and ask for proper rep! tyvm :)

**Comment by MantisLord** [comment]
@Warlockbugs appears to be correct... For Classic-DB, this item has RequiredReputationFaction 890 and RequiredReputationRank 7 in item_template (Silverwing Sentinels, Exalted). This data probably isn't accurate. TBC-DB already has 0 for both of these fields.

I'm not sure if this is actually the proper rank all three versions of the bracer should be restricted to, or if there are other items impacted as the reporter of this issue originally suggested, but we can easily work around this by using conditions associated with the corresponding vendor templates:

```sql
-- Windtalker's Wristguards - no template level faction requirement
UPDATE `item_template` SET `RequiredReputationFaction`=0, `RequiredReputationRank`=0 WHERE `entry` IN (19582,19583,19584);

DELETE FROM `conditions` WHERE `condition_entry` IN (1529,1530);
INSERT INTO `conditions` (`condition_entry`, `type`, `value1`, `value2`, `comments`) VALUES
(1529, 5, 890, 7, 'Has Minimum Rank Exalted With Faction ID: 890'), -- Silverwing Sentinels
(1530, 5, 889, 7, 'Has Minimum Rank Exalted With Faction ID: 889'); -- Warsong Outriders
UPDATE `npc_vendor` SET `condition_id`=1529 WHERE `entry`=14753 AND `item` IN (19582,19583,19584);
UPDATE `npc_vendor` SET `condition_id`=1530 WHERE `entry`=14754 AND `item` IN (19582,19583,19584);
```

**Comment by killerwife** [comment]
Afaik no, these items should all always show up, and just not be purchasable. The conditions will hide them, no?

**Comment by MantisLord** [comment]
Hmm yes you have a point there... seems we may need to gather some research.

The conditions I made would indeed hide them from the vendor list. If it turns out they're supposed to be as you suspect - visible, but not purchasable, we'll need an alternate solution.

**Comment by killerwife** [comment]
AV and WSG vendors were released before reputation restriction on items was added. The vendors should only show what you can currently buy. AB however is supposed to show everything and have reputation restrictions in place. Bandages are supposed to be seen on all vendors with reputation condition at all times.

**Comment by AnonXS** [comment]
Linked to https://github.com/cmangos/issues/issues/2935 - classic issue
