### ISSUE TITLE
The Perfect Stout Quest

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#1985]
"hmmm, anyone know how Perfect Brew dwarven quest should work?
or Perfect Stout rather
The wiki says that it require Rejold's New Brew to start
https://classicdb.ch/?quest=315
and that how it works
but
the Rejold's New Brew says "remeber that weed you brought me"
and that was from the Perfect Stout, implying it should be earlier quest" 
This is his quotes on discord

Quest should require completition of 315 not 415

`UPDATE quest_template SET PrevQuestId = 0 WHERE entry = 315;
UPDATE quest_template SET PrevQuestId = 315, NextQestId = 0 WHERE entry = 415;`

Credits Lord Phoenix

I put this here because I understood that he has some trouble with his old firefox vs github

**Comment by AnonXS** [comment]
Some additional Information, but classic beta has shown that some of the quest trees are incomplete.

https://www.wowhead.com/quest=413/shimmer-stout#comments:id=190688

```

This quest can be done without doing the first quest of the chain

```

---

https://www.wowhead.com/quest=415/rejolds-new-brew#comments:id=190337

```

This quest becomes undoable if you finish Shimmer Stout (q.413) quest first. The second part of this quest chain can be done at the cost of skipping this quest (the first part)

Funnily enough, immediately after turning in The Perfect Stout (q.315), you can grab Shimmer Stout (q.413) from the very same NPC.

In order to do this intermediate step, you need to turn down Rejold when he offers you Shimmer Stout (q.413).

Run back to Kharanos, talk to one of the dwarves at Steelgrill's Depot for Rejold's New Brew (q.415), then return to Rejold to turn it in and then do Shimmer Stout.

```

https://www.wowhead.com/quest=315/the-perfect-stout

**Comment by Muehe** [comment]
Yeah this pretty much confirms it is working correctly, thanks for the research. FYI the classic version of Wowhead has Allakhazam and Thottbot comments included now, which say the same thing: https://classic.wowhead.com/quest=415/rejolds-new-brew#comments:id=2794174

**Comment by Muehe** [comment]
Ah I see what's going on here, this is not a Classic bug.

Classic:

![Screenshot_20190621_045544](https://user-images.githubusercontent.com/8838573/59894458-fc845880-93e0-11e9-88eb-828982e6f658.png)

TBC and WotLK:

![Screenshot_20190621_045621](https://user-images.githubusercontent.com/8838573/59894460-0017df80-93e1-11e9-9d81-877abcc4cae8.png)

Fix @cala :

```sql
UPDATE `quest_template` SET `PrevQuestId`='0', `NextQuestInChain`='413' WHERE `entry`='315';
UPDATE `quest_template` SET `PrevQuestId`='315' WHERE `entry`='413';
UPDATE `quest_template` SET `PrevQuestId`='315', `NextQuestId`='0' WHERE `entry`='415';
```

**Comment by MantisLord** [comment]
@Muehe so just to be clear, you're saying that Classic-DB data is correct and TBC-DB/WotLK-DB data is wrong in this case?

Your SQL fix implies to me that Version: TBC and Version: WotLK versions are appropriate here and that Version: Classic should be removed.

**Comment by Muehe** [comment]
Yes, precisely. Was a bit confused about who to tag for TBC/Wotlk DBs so I just picked cala, since I think he has commit rights on all the DBs.

**Comment by cala** [comment]
Bump to myself to port this to WotLK.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/wotlk-db/commit/453bcbec62ec2839cbd2f98fc1ee2d6681166680
