### ISSUE TITLE
[TBC] Can't compile Playerbot on latest core.

### ISSUE THREAD

**Issue by berserkingyadis** [cmangos/issues#1986]
## 🐛 Bugreport

I am getting this error when trying to compile the latest tbc-core with Playerbot option.
```
1>PlayerbotAI.cpp
1>E:\Dev\github\others\cmangos\mangos-tbc\src\game\PlayerBot\Base\PlayerbotAI.cpp(4066): error C2065: 'TARGET_FLAG_OBJECT': undeclared identifier
1>E:\Dev\github\others\cmangos\mangos-tbc\src\game\PlayerBot\Base\PlayerbotAI.cpp(4146): error C2065: 'TARGET_FLAG_OBJECT': undeclared identifier
1>E:\Dev\github\others\cmangos\mangos-tbc\src\game\PlayerBot\Base\PlayerbotAI.cpp(4163): error C2065: 'TARGET_FLAG_OBJECT': undeclared identifier
1>E:\Dev\github\others\cmangos\mangos-tbc\src\game\PlayerBot\Base\PlayerbotAI.cpp(5564): error C2065: 'TARGET_FLAG_OBJECT': undeclared identifier
1>E:\Dev\github\others\cmangos\mangos-tbc\src\game\PlayerBot\Base\PlayerbotAI.cpp(5584): error C2065: 'TARGET_FLAG_OBJECT': undeclared identifier
1>E:\Dev\github\others\cmangos\mangos-tbc\src\game\PlayerBot\Base\PlayerbotAI.cpp(7181): error C2065: 'TARGET_FLAG_OBJECT': undeclared identifier
1>E:\Dev\github\others\cmangos\mangos-tbc\src\game\PlayerBot\Base\PlayerbotAI.cpp(9731): error C2065: 'TARGET_FLAG_OBJECT': undeclared identifier
1>Done building project "game.vcxproj" -- FAILED.
```
Code: https://github.com/cmangos/mangos-tbc/blob/7d8b57c48f50502f901f7db696292b535c9eaedb/src/game/PlayerBot/Base/PlayerbotAI.cpp#L4066
### Expected behavior

Compile without problems
### Version & Environment

Client Version: [TBC 2.4.3]

CMaNGOS Repo & Commit Hash:  https://github.com/cmangos/mangos-tbc/tree/7d8b57c48f50502f901f7db696292b535c9eaedb

Operating System: [Win 10]

### Steps to reproduce
1. Pull latest mangos-tbc code
2. Compile with Playerbot enabled
3. ...
4. Profit

### Crashlog
![image](https://user-images.githubusercontent.com/9959527/59859262-b72e3f80-937c-11e9-9a40-17fee1392a38.png)

**Comment by lduguid** [comment]
replace references of TARGET_FLAG_OBJECT to TARGET_FLAG_GAMEOBJECT should  be enough
