### ISSUE TITLE
Level 2 Class Quests for Night Elves Require The Balance of Nature (457) When It Should Require The Balance of Nature (456)

### ISSUE THREAD

**Issue by DarkPhoenixxy** [cmangos/issues#1987]
Starting class quests for Night Elves in Shadowglen should trigger right after first quest, when player attains level 2, just like for other races. Fix:

UPDATE quest_template SET PrevQuestId = 456 WHERE entry = 3116 OR entry = 3117 OR entry = 3118 OR entry = 3119 OR entry = 3120;

**Comment by cala** [comment]
Closing this: the WotLK part will be fixed in the next backport process.
