### ISSUE TITLE
Creature targeting home cause core into infinite loop. 

### ISSUE THREAD

**Issue by darklordsqk** [cmangos/issues#1989]
## 🐛 Bugreport
When a mob(guard) killed another mob and return home, the core stuck. 

### Expected behavior
Should not stuck. 

### Version & Environment
Client Version: "1.12.1" (CLASSIC)
CMaNGOS Repo & Commit Hash:  [CLASSIC](https://github.com/cmangos/mangos-classic/commit/e0dbba39cd8bc12980049ba9a2865d0b7297214b)
Database Repo & Commit Hash: [CLASSIC](https://github.com/cmangos/classic-db/commit/ae3d4525918a87399a95f8d12be9563eedf7362a)
Operating System: [Linux Ubuntu 14]

### Steps to reproduce
1. login
2. tele southshore
3. wait for southshore guard killing graybear.

### Crashlog
- None ('Cuz it's not typical crash.)

![2](https://user-images.githubusercontent.com/4716232/59891918-b1cb0680-9409-11e9-83d5-13456babcf87.png)

![1](https://user-images.githubusercontent.com/4716232/59891926-b7285100-9409-11e9-8ded-e9e5a9424ba5.png)

**Comment by BenDol** [comment]
This is a duplicate isn't it? https://github.com/cmangos/issues/issues/1971

**Comment by darklordsqk** [comment]
@BenDol I've tried again. It's the same issue. Thanks.

**Comment by darklordsqk** [comment]
Duplicated with https://github.com/cmangos/issues/issues/1971

**Comment by BenDol** [comment]
Thanks for the report none the less
