### ISSUE TITLE
Intermittent TBC core crash

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#1990]
## 🐛 Bugreport

Race, class, zone, combat type, mob type does not seem to matter,  playing for approx. 30 minutes on average (sometimes shorter/sometimes longer) the core will crash.  There does not seem to be a consistent pattern of player behavior involved.  Similar crashes with multiple characters of various level have occurred  Change causing crash is recent, within the last few days.  Appears to be a recursive overflow of the stack.

No relevant hints to cause in any of the logs.

![image](https://user-images.githubusercontent.com/105060/59959089-883fc880-9465-11e9-9f36-783fdf22f746.png)

### Expected behavior

No crash

### Version & Environment

  Client Version - "2.4.3" (TBC)

  Commit Hash - https://github.com/cmangos/mangos-tbc/commit/cc5b93316b9207689cbcb429e3f7e2a0187702d9

Database Repo & Commit Hash: []() https://github.com/cmangos/tbc-db/commit/422fc12a99589ad41dc8844fb674eafb2a600b5b

Operating System: 10

### Steps to reproduce
1. Play TBC with any character/race of any level for about 30 minutes.
2.
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by BenDol** [comment]
Duplicate https://github.com/cmangos/issues/issues/1971

**Comment by lduguid** [comment]
https://github.com/cmangos/mangos-tbc/commit/96d39e00420fd3b9252cf3dd50c8ccc8234be41c appears to fix this.  Tested for crash for many hours this morning with multiple toons/level/zones etc., no crash so far. ..
