### ISSUE TITLE
Janalai Summon Amani'shi Hatcher is Broken

### ISSUE THREAD

**Issue by Yatzii93** [cmangos/issues#1995]
## 🐛 Bugreport

Hatchers do not spawn during the boss encounter. Spell ids -  43962,45340

### Expected behavior

Hatchers are meant to spawn and go to egg spawning location.

### Version & Environment

Client Version: [] "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash:  []() https://github.com/cmangos/mangos-tbc/commit/5171dcff86bed141ace0ef41989fa05f0cb00dc0

Database Repo & Commit Hash: []() https://github.com/cmangos/mangos-tbc/commit/5171dcff86bed141ace0ef41989fa05f0cb00dc0

Operating System: []  Win 

### Steps to reproduce
1. Enter ZA and engage Janalai

### Crashlog

- None

**Comment by Yatzii93** [comment]
Actually might be wrong about Repentance. Going to double check everything.

**Comment by MantisLord** [comment]
Fixed with https://github.com/cmangos/mangos-tbc/commit/6ff0ec15f2931d92cb6d15c5e9a7548a0caf645f
