### ISSUE TITLE
mysql80-server sql error in cmangos_fixes/Spell.sql

### ISSUE THREAD

**Issue by metacreo** [cmangos/issues#1999]
## 🐛 Bugreport
`mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1064 (42000) at line 68: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Rank, Rank2, Rank3, Rank4, Rank5, Rank6, Rank7, Rank8, Rank9, Rank10, Rank11, Ra' `

sql errors in base/dbc/cmangos_fixes/Spell.sql
 queries WITHOUT brackets Rank, Rank2, Rank3, Rank4, Rank5..... 
by adding `` sql import ok 
mysql80-server on freebsd

**Comment by metacreo** [comment]
wotlk

**Comment by metacreo** [comment]
Hi all
I made a little changes to core and sql.
Now mangos work with mysql 8.0 freebsd (+fixed extractors build)
1. fixed invalid queries who I known and who see in DBErrors.log
2. fixed build on freebsd with mysql80-server
3. fixed extractors build on freebsd 
Here is my diff http://newestvision.com/public/diff.diff

**Comment by jimmybrancaccio** [comment]
Hey @metacreo Can you please go back and fill out all the requested information in the bug report? You should be able to edit your original entry and then fill out all the missing information.

Thanks.

**Comment by metacreo** [comment]
Sorry, I close this. I start create pull request with fixes for freebsd and starting compatability to much faster mysql 8.0.
