### ISSUE TITLE
Auchenai Crypts "Shirrak the Dead Watcher" AI Crash...

### ISSUE THREAD

**Issue by keyshuwen** [cmangos/issues#2000]
## 🐛 Bugreport

Auchenai Crypts "Shirrak the Dead Watcher" AI Crash..

### Expected behavior

Attacking creature  Until Crash....
npc Entry = 18371.
emmm... My English is not good.  :(

### Version & Environment

Client Version: [ "2.4.3" (TBC)]

CMaNGOS Repo & Commit Hash:  []()

https://github.com/cmangos/mangos-tbc/commit/5286fde5d5fdea58ff66090c3edb1211001ada96
Database Repo & Commit Hash: []()
https://github.com/cmangos/tbc-db/commit/71d680357dc241242cec752eb7857e0b02ce35bd

Operating System: [Win10 x64]

### Steps to reproduce
1.  in Auchenai Crypts
2.  Attacking creature (Entry = 18371)
3.  Crash

### Crashlog

- None

**Comment by jimmybrancaccio** [comment]
Hi @keyshuwen Please go back and fill out all of the requested information for the bug report. You can edit your original entry and then fill out all the missing information.

Thanks,

**Comment by keyshuwen** [comment]
@jimmybrancaccio  Ok.

Looks like a spell error.
https://github.com/cmangos/mangos-tbc/blob/master/src/game/Entities/DynamicObject.cpp#L222

**Comment by Thar3l** [comment]
After the debugging it turned out that the object that casts the spell is a **DynamicObject**, so **GetAffectiveCasterObject()** returns null. To fix this, just let it return this type of object.

`if (m_originalCasterGUID.IsDynamicObject() && m_caster->IsInWorld())
        return m_caster->GetMap()->GetDynamicObject(m_originalCasterGUID);`

**Comment by killerwife** [comment]
Try removing ", nullptr, nullptr, GetObjectGuid()" from owner->CastSpell(nullptr, 32301, TRIGGERED_OLD_TRIGGERED, nullptr, nullptr, GetObjectGuid());
And it should be fine.

**Comment by albeecode** [comment]
I'm also experiencing this issue on a WOTLK server.  I created a new issue for this just a minute ago.  Should have searched first.  Is there anything I can do to assist in resolution?  I asked in my issue how to enable full debug logging so that I can re-produce and upload as much info as possible.

Thanks for all you guys do!!
- Albeecode

**Comment by albeecode** [comment]
NPC Creature ID: 18371 GUID: 5580001

**Comment by AnonXS** [comment]
maybe temporary moving it back to 

```
void Aura::HandleAuraDummy(bool apply, bool Real)

            case 32286:                                     // Focus Target Visual
            {
                if (m_removeMode == AURA_REMOVE_BY_EXPIRE)
                    target->CastSpell(target, 32301, TRIGGERED_OLD_TRIGGERED, nullptr, this);

                return;
            }

``` resolves it

**Comment by buenodart** [comment]
Hi, guys!

Wich solution should I use?

**Comment by Xadras** [comment]
Removing the last three parameters as suggested by killerwife fixed it just fine for me

**Comment by buenodart** [comment]
> Removing the last three parameters as suggested by killerwife fixed it just fine for me

OHHHH!! Thank You @Xadras 

I'll try =D
