### ISSUE TITLE
SQL table setup for creature_template broken

### ISSUE THREAD

**Issue by h42dev** [cmangos/issues#2001]
### Expected behavior

Running sql/base/mangos.sql should work without errors

### Version & Environment

Client Version: [1.12.1]

CMaNGOS Repo & Commit Hash:  [CLASSIC](https://github.com/cmangos/mangos-classic/tree/498765a7ea48241b66d1d62aa171014d6ef3db6a)

Database Repo & Commit Hash: N/A

Operating System: Arch/Manjaro

### Steps to reproduce
1. During database initialization, the following command currently fails:
`mysql -uroot -p classicmangos < mangos/sql/base/mangos.sql`

2. This is due to the added column to the creature_templote table in [this commit](https://github.com/cmangos/mangos-classic/commit/498765a7ea48241b66d1d62aa171014d6ef3db6a)
3. While the commit handles update scripts for existing dbs, it seems to have missed updating the initial sql files.
4. Easily fixed by adding a '0' default value for the column towards the end of [line 1279](https://github.com/cmangos/mangos-classic/blob/34416ec80c61e18b4ef802e959be4bcbf54ffed5/sql/base/mangos.sql#L1279) in mangos.sql

### Crashlog

- None

**Comment by esno** [comment]
https://github.com/cmangos/mangos-classic/pull/396
