### ISSUE TITLE
Playerbot duel with melee character and master causes server to crash.

### ISSUE THREAD

**Issue by kelbren** [cmangos/issues#2005]
## 🐛 Bugreport

Playerbot duel with melee character and master causes server to crash.

### Expected behavior
Client Version:  [2.4.3]

CMaNGOS Repo & Commit Hash:  [TBC] (https://github.com/cmangos/mangos-tbc/tree/61e466b1a3f46964e9a9fc2cb6b69747e69a1626)

Operating System:  Linux Ubuntu 18.04 server

### Steps to reproduce
1.   Create warrior character A
2.  Create caster character B
3.  Login with character B
4.  .bot add character A
5.  Start a duel, after the countdown finishes and combat begins, the server crashes

### Crashlog
- None

**Comment by berserkingyadis** [comment]
Just reproduced, still happening.

core: https://github.com/cmangos/mangos-tbc/commit/1ee44bb75c87fb599f85d8d959dbf7d1933fb05a
db: https://github.com/cmangos/tbc-db/commit/8134aaac47ac3eb45a6acd42e1948f7c0b241d1c

**Comment by cala** [comment]
Closed by the recent changes I made in Playerbot code: in some places, targets where assumed to be creatures, leading to a crash when they were in fact players.

Tell me if you encounter this crash again, but I wasn't able to reproduce it after the last changes.
