### ISSUE TITLE
🐛 [Bug Report] Issues with a fresh Install

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/issues#2010]
### Issues with a fresh Install

I installed the tbc version of cmangos in oder to test some PRs. The following things occured when installing:

#### Install instructions
- install instructions should be in readme or linked in the readme. The wiki is linked, but it is not referenced how to install (i used the wiki https://github.com/cmangos/issues/wiki/Installation-Instructions)
- install instructions in the wiki are only for classic & tbc, i did not check the wotlk repo, but i assume they are missing

#### Error in `mangos-tbc/sql/base/mangos.sql`
<details>
  <summary>Resolved in #2008 ✔️ </summary>

```mysql -uUSER -pPW mangos_tbc < mangos-tbc/sql/base/mangos.sql```
Results in:
```ERROR 1136 (21S01) at line 1376: Column count doesn't match value count at row 1```
I commented out the coresponding lines to solve it for now:
```
LOCK TABLES `creature_template` WRITE;
/*!40000 ALTER TABLE `creature_template` DISABLE KEYS */;
-- INSERT INTO `creature_template` VALUES
-- (1,'Waypoint (Only GM can see it)','Visual',NULL,1,1,0,10045,0,0,0,35,1,8,8,1,1,0,0,4096,0,130,5242886,0.91,1.14286,20,0,0,0,0,0,0,-1,1,1,1,1,1,1,8,8,0,0,7,7,1.76,2.42,0,3,100,2000,2200,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'','');
/*!40000 ALTER TABLE `creature_template` ENABLE KEYS */;
UNLOCK TABLES;
```
-> This error can be detected by an automatic build test
</details>

#### DBC sql install
- The install instructions contain instructions for the DBC-SQL files -> the first commands are for windows. But thats not mentioned there (tho one can guess ofc)
`mysql -uUSER -pPW mangos_tbc < mangos-tbc/sql/base/dbc/*.sql`
Results in (debian):
`-bash: mangos-tbc/sql/base/dbc/*.sql: No such file or directory`

<details>
  <summary>Resolved ✔️ </summary>

- The command for nix results in a console error (think it has no negative effect tho):
```for sql_file in ls mangos-tbc/sql/base/dbc/original_data/*.sql; do mysql -uUSER -pPW --database=mangos_tbc < $sql_file ; done```
Results in (debian):
```-bash: ls: No such file or directory```
Same applies for the second command

</details>

#### Map extractors
```
Ever since extractors are no longer in repository, you will need to compile them yourself. The extraction process should work identically to Windows, since the scripts are portable.

If you followed this guide the file can be found in:

Executables: /home/mangos/mangos/run/bin/tools

Scripts: /home/mangos/mangos/contrib/extractor_scripts
```

I am running under windows, my server is linux. On windows i do not have the tools to compile.
But the windows binaries are available in the Pre-Releases. That should be noted in install instructions.

### Version & Environment

Client Version: -

CMaNGOS Repo & Commit Hash:  https://github.com/cmangos/mangos-tbc/tree/398fd89c70db847df7e83a1ff1ee1304cb889a49

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/c5e6e41ecb739a779aa1cc8ec68b8d470d3cd42f

Operating System: Debian

**Comment by esno** [comment]
I changed the backticks to `$(ls mangos-tbc/sql/base/dbc/original_data/*.sql)` to prevent github markdown parsing them as inline codeblocks.

**Comment by ulfgebhardt** [comment]
@esno Marked the corresponding section as resolved ty!

**Comment by jimmybrancaccio** [comment]
Ideally each unique issue should have it's own issue in GitHub (for the future).

**Comment by ulfgebhardt** [comment]
@jimmybrancaccio I will seperate this issue

**Comment by ulfgebhardt** [comment]
Closing in favor of:
- https://github.com/cmangos/issues/issues/2025
- https://github.com/cmangos/issues/issues/2026
- https://github.com/cmangos/issues/issues/2027
- https://github.com/cmangos/issues/issues/2028

Thanks to everyone who already have fixed problems of this issue <3. You are the best!
