### ISSUE TITLE
🐛 [Bug Report] TBC-DB errors on fresh install

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/issues#2011]
### TBC-DB errors on fresh install

On a fresh install of `mangos-tbc` & `tbc-db` there is a number of errors on startup:

#### At Startup

![image](https://user-images.githubusercontent.com/1238238/60909703-38dc0380-a27f-11e9-8e55-91634ecf9381.png)

![image](https://user-images.githubusercontent.com/1238238/60909822-82c4e980-a27f-11e9-9cf7-b8954bf68d6f.png)

![image](https://user-images.githubusercontent.com/1238238/60909847-940df600-a27f-11e9-80bd-f737bd016a91.png)

![image](https://user-images.githubusercontent.com/1238238/60909902-ac7e1080-a27f-11e9-896b-8243b700eb70.png)

![image](https://user-images.githubusercontent.com/1238238/60909923-b99aff80-a27f-11e9-843f-36fe3df941b9.png)

![image](https://user-images.githubusercontent.com/1238238/60909962-d46d7400-a27f-11e9-91d5-49486ad7a6a4.png)

![image](https://user-images.githubusercontent.com/1238238/60910000-ecdd8e80-a27f-11e9-8fb4-e226a442a31b.png)

#### At runtime

![image](https://user-images.githubusercontent.com/1238238/60910086-27472b80-a280-11e9-8ff2-b51b24bc5c16.png)

### Expected behavior

No Database errors

### Version & Environment

Client Version: 2.4.3 (TBC)

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/tree/398fd89c70db847df7e83a1ff1ee1304cb889a49

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/c5e6e41ecb739a779aa1cc8ec68b8d470d3cd42f

Operating System: debian 9.9

### Steps to reproduce
1. install tbc (mangos & database)
2. startup
3. see errors
4. ...
5. Profit

### Additional Info

When DB and core are coupled those errors can let a build test fail and therefore prevent to ever happen on a stable branch

**Comment by AnonXS** [comment]
outdated errors, next time plain text, no screenshots for copy paste purpose.
