### ISSUE TITLE
🐛 [Bug Report] Aura Proc Trigger Spell's in talents seem to not be working

### ISSUE THREAD

**Issue by Yatzii93** [cmangos/issues#2012]
## 🐛 Bugreport

Ever since I took in the target rework updates and the ones following up until the latest commits (https://github.com/cmangos/mangos-tbc/commits/master?after=6ff0ec15f2931d92cb6d15c5e9a7548a0caf645f+419) I've been having an issue with some aura proc trigger spells learnt from talents. They don't seem to show up under a players auralist when talented into and adding them manually doesn't seem to work to make them proc either (will show up in auralist until relogging). Example spells are Improved Wingclip (http://db.excalibur.ws/?spell=19233), Entrapment(http://db.excalibur.ws/?spell=19388) and the Improved Hamstring(http://db.excalibur.ws/?spell=23695).

To be sure it wasnt my end I tested on a Pre-build I had straight from the main repo. date 29/06/2019 and the problem was also apparent in that core. I haven't tested the very latest but I can only assume it's still the case as nothing new commit wise addresses this issue. (or atleast as far as I am aware)

It doesnt seem to be all spells learnt through talents though. Illumination an aura proc spell learnt from the holy paladin tree seems to apply and function fine.

### Expected behavior

These talents should auto learn the relevant spell to the player be, then in the case of Improved Wingclip, a mob should on chance be rooted for 4 seconds.

### Version & Environment

Client Version: 

CMaNGOS Repo & Commit Hash:  https://github.com/cmangos/mangos-tbc/commit/696ae998ae044c33eaad9d000a66a00815f61571

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/commit/8f9dc7c4c0dcbe54b7cf3340f57ab8b13d04b876

Operating System: Win

### Steps to reproduce
1. Create a hunter, talent into Improved Wing Clip
2. Check to see if it shows on aura list .aura list
3. Spam wingclip on a mob to see if they have a chance to be rooted instead of just slowed
4. ...
5. Profit

### Crashlog

- None

**Comment by AnonXS** [comment]
Seems to me the aura passive is never applied to the player, did it for you? Only with .aura 19233 it seems to apply.

**Comment by Yatzii93** [comment]
Yep! it applies it for it still doesn't proc for me which is werid.

**Comment by Yatzii93** [comment]
http://db.excalibur.ws/?spell=20215 for instance applied automatically and works perfectly, definitely makes it confusing, atleast from my perspective as it doesn't seem to be a blanket problem.

**Comment by AnonXS** [comment]
Well Illumination is hardcoded the other one is dependent on spell subsystems to work. :)

**Comment by Yatzii93** [comment]
ooo a clue! I'll go digging for treasure.

**Comment by Yatzii93** [comment]
Similar to this fix - https://github.com/cmangos/mangos-tbc/commit/ef69703867689c37537d250646fb205e408a9d58 
It's the same thing here, if you change it to target the self the aura will apply and work properly. I guess this isn't the fix considering it's affecting a number of spells. Maybe the targeting system needs to be reworked to accomodate these spells rather than manually changing all the spells that have stopped working.

**Comment by Yatzii93** [comment]
I know it's probably not ideal but I have a custom function in my core to edit spells in memory on server start-up. Adding checks like this 

`case SPELLFAMILY_PALADIN:
            {
                if (spellInfo->Effect[0] == 6 && spellInfo->EffectApplyAuraName[0] == 42 && spellInfo->EffectImplicitTargetA[0] == 6)
                    spellInfo->EffectImplicitTargetA[0] = 1;`

seems to act as a overarching fix. I looked in the targeting rework stuff and couldn't find any noticable changes to Target_unit_enemy (6). It all looked pretty exact to the old code. Probably something I'm missing.

**Comment by AnonXS** [comment]
And now its time for @killerwife :)

**Comment by Yatzii93** [comment]
Definitely! xD

**Comment by Yatzii93** [comment]
@killerwife There's more spells that are effected. This is the way to go about it for them all?

**Comment by killerwife** [comment]
Sadly yes. I hate blizzard.

**Comment by Yatzii93** [comment]
Add improved Hamstring to the list
http://db.excalibur.ws/?search=improved+hamst
Maybe http://db.excalibur.ws/?search=entrapment?
It seems to now show in my test chars aura list now but doesnt proc, might need to check the flags in the db.

**Comment by killerwife** [comment]
Alrdy done. Will export it sometime later.

**Comment by Yatzii93** [comment]
thanks @killerwife
