### ISSUE TITLE
🐛 [Bug Report] Lady Vashj distance movement

### ISSUE THREAD

**Issue by Yatzii93** [cmangos/issues#2013]
Recent change to how mobs distance themself from their target seems to have causes a slight issue on Lady Vashj. Basically her in melee range check is to quick after the distance yourself function is called. The result causes her to move back for a split second then go back to meleeing, rather than staying at range and using her bow.

My hack fix is:- This makes sure theres a 3 second buffer before the melee check can be successfully called. I imagine there's a better way to do this maybe concerning the base distance yourself function?

https://gist.github.com/Yatzii93/4e63488390d9983cbcdf5c29cf0551ff

Client Version:

CMaNGOS Repo & Commit Hash: cmangos/mangos-tbc@696ae99

Database Repo & Commit Hash: cmangos/tbc-db@8f9dc7c

Operating System: Win
Steps to reproduce

-Fight lady vashj until she stuns you and trys to distance herself

Crashlog

    None

**Comment by AnonXS** [comment]
Probably the same issues alot of npcs currently have with overreactive movechase and domeleeattack calls. they interrupt their own spells/ongoing actions to chase or to melee when they can sometimes.

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/145730076-262c4df4-78e9-44d4-90a9-d870514061a8.png)

seems resolved, again.
