### ISSUE TITLE
🐛 [Bug Report] Zu'Aman chest event loot mix up

### ISSUE THREAD

**Issue by Yatzii93** [cmangos/issues#2014]
ZA chest event loot seems to bug out at times, offering the bear for chest 3 instead of 4. I've been unable to reproduce the problem myself but it happens fairly often for my players. I'm going to look into this deeper, just thought I'd leave this issue here to make notes on.

Client Version:

CMaNGOS Repo & Commit Hash: cmangos/mangos-tbc@696ae99

Database Repo & Commit Hash: cmangos/tbc-db@8f9dc7c

Operating System: Win
Steps to reproduce
Cannot reproduce myself atm. Will update with more info later. The normal events are
-kill a ZA boss within the timer
-loot the chest to get extra gear.

Crashlog

    None

**Comment by killerwife** [comment]
Closing this as it has been a long time and many changes.
