### ISSUE TITLE
🐛 [Bug Report]Bot as Priest Stop Buffing My Main Character Shaman with Power Word: Fortitude

### ISSUE THREAD

**Issue by Denza755** [cmangos/issues#2018]
## 🐛 Bugreport

Bot as priest stop buffing my main char shaman with Power Word: Fortitude
But other bots he buffs with Power Word: Fortitude
### Version & Environment

Client Version: 

CMaNGOS Repo & Commit Hash: 

Database Repo & Commit Hash: 

Operating System: 

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by jimmybrancaccio** [comment]
@Denza755 Please provide **all** of the information requested in the bug form.

**Comment by jimmybrancaccio** [comment]
Closing this out as we have heard no response. We will consider reopening it if the requested information can be provided.
