### ISSUE TITLE
🐛 [Bug Report] Pooling System - Randomized Respawn Broken

### ISSUE THREAD

**Issue by AnonXS** [cmangos/issues#2019]
## 🐛 Bugreport

Randomized respawn only works once, then never again.

.go c id 10559
.kill 10559
.respawn
.go c id 10559
.kill
.respawn
.kill
.respawn
.kill
.respawn
.kill
.respawn

Same thing with gos
.go o id 154357

### Expected behavior

Should randomize like it works in dungeons/instanced maps seems to only be broken in open world.

Should randomize location as it did befor pooling system was reworked by @cyberium

**Comment by AnonXS** [comment]
voa issue only

**Comment by cyberium** [comment]
https://youtu.be/LCFVEEga1_c
