### ISSUE TITLE
🐛 [Bug Report] Error when you run do_create_mysql on TBC.

### ISSUE THREAD

**Issue by oromancer** [cmangos/issues#2020]
Hello, I just tried install databases with your scripts and there is one problem.

First error appeared when I executed InstallFullDB.sh
```
> Processing TBC database v1.7 'A New Hope' ...
ERROR 1045 (28000): Access denied for user 'mangos'@'localhost' (using password: YES)
ERROR: cannot apply Full_DB/TBCDB_1.7.0_ANewHope.sql
```
Next step I find out this user is created by do_create_mysql.sql.
When this simple command is called: 
```
mysql>CREATE USER `mangos`@`localhost` IDENTIFIED BY `mangos`; 
ERROR 1819 (HY000): Your password does not satisfy the current policy requirements;

```
The problem is new versions of mysql have password validator.

```
mysql> SHOW VARIABLES LIKE 'validate_password%';

+--------------------------------------+--------+
| Variable_name                        | Value  |
+--------------------------------------+--------+
| validate_password_check_user_name    | OFF    |
| validate_password_dictionary_file    |        |
| validate_password_length             | 8      |
| validate_password_mixed_case_count   | 1      |
| validate_password_number_count       | 1      |
| validate_password_policy             | MEDIUM |
| validate_password_special_char_count | 1      |
+--------------------------------------+--------+
```
Solutions:
1) Change the password to a given format for validation.
2) Change policy requirements:
```
SET GLOBAL validate_password_length = 6;
SET GLOBAL validate_password_number_count = 0;
SET GLOBAL validate_password_special_char_count = 0;
SET GLOBAL validate_password_mixed_case_count = 0;
```
3) Turn off validator:
`SET GLOBAL validate_password_policy = 0;`

### Expected behavior
I would expect running this script would update the database without any issues or errors.

### Version & Environment
Client Version: "2.4.3 (TBC)"
CMaNGOS Repo & Commit Hash:bade77f0bf01c099152a819c06f474788b554653
Database Repo & Commit Hash: 1ce049ba1ffb6ce34f280ce419cebd9acd200106
Operating System: Linux Ubuntu 18.10
Mysql: 5.7.26

### Steps to reproduce
1. Fetch given commits of classic and the classic database.
2. Make sure you've run the base SQL Stuff to get the DB structure going.
3. Setup and run the do_create_mysql.sql and look to users in database or continue to run InstallFullDB.sh script.
4. Observe the error about the routine.

### Crashlog
- None

**Comment by killerwife** [comment]
Closing this, since if you want to have a secure setup you should not use the default password and after setting up mysql on 4+ machines since this post, never had this issue.
