### ISSUE TITLE
🐛 [Bug Report] Seal of Righteousness Damage is Incorrect

### ISSUE THREAD

**Issue by DramatimeWoW** [cmangos/issues#2022]
### 🐛 Bugreport - Seal of Righteousness damage is incorrect
Seal of Righteousness damage is way off. The spell coefficient from spell damage is wrong. The base damage calculation also appears to be wrong. In the calculation for spell damage, its being passed the dummySpell which causes the spell damage coefficient to be calculated at ~38% because it defaults to the default coefficient calculation, then another ~10% gets added (from the db) to that from the actual damage proc spell when the spell is cast. Seal of Righteousness' spell damage coefficients are special because the coefficient is based on the base weapon speed that you are wielding so both of these calculations is wrong. When looking at the spell damage being used in the calculation for the actual damage proc, it doesn't appear to be taking into account all the spell damage from gear/talents. It appears its missing spell power from talents (specifically Holy Guidance). Improved seal of righteousness talent also doesn't appear to be adding 15% Seal of Righteousness damage after spell damage/talents correctly as well. 

### Expected behavior
Here is a wiki link from 2.4.3 from June 2008, slightly before the 2.4.3 patch date but Seal of Righteousness nor the talents in discussion here were changed for this patch. 
https://wowwiki.fandom.com/wiki/Seal_of_Righteousness_(old)?oldid=1432433

As you can see the spell coefficient from spell damage should be:

9.2% per 1.0 weapon speed, One-handed Seal of Righteousness
10.8% per 1.0 weapon speed, Two-handed Seal of Righteousness

The base damage calculation should be:

Added Holy damage for a one-handed weapon
= 0.85 * (seal damage coeff * MWS / 100) + 0.03 * (MW + mw) / 2 - 1

Added Holy damage for a two-handed weapon
= 1.2 * (seal damage coeff * MWS / 100) + 0.03 * (MW + mw) / 2 + 1

Where:
spell damage coeff = coefficient as per tooltip
MWS = main weapon speed
MW = maximum weapon damage
mw = minimum weapon damage

The seal damage coefficient is dependent on the rank of the seal which you can see on the table in the link above.

The damage done by the Seal can be increased by up to 15% with the talent Improved Seal of Righteousness (3% over 5 ranks). This damage is added after additional damage is calculated from +spell damage gear.

source(https://wowwiki.fandom.com/wiki/Seal_of_Righteousness_(old)?oldid=1432433)

### Version & Environment
Client Version: 2.4.3 (TBC)

CMaNGOS Repo & Commit Hash:  https://github.com/cmangos/mangos-tbc/tree/a440e856392dd55ed41b6d3a9eba80e79492187c

Database Repo & Commit Hash:    https://github.com/cmangos/tbc-db/tree/ad1f6281d31b09bb5eea08d36681d296f9de00da

### Steps to reproduce
1. Cast Seal of Righteousness
2. Auto attack a mob
3. See the absurd damage its doing
4. Run a calculation to verify the damage is off. 
5. ???
6. Profit

**Comment by Yatzii93** [comment]
@DramatimeWoW has a fixed this and confirmed working my end. Waiting for him to PR it ... *taps watch* ;)
