### ISSUE TITLE
🐛 [Bug Report] Issues with a fresh Install - Readme

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/issues#2025]
### Issues with a fresh Install - Readme

install instructions should be in readme or linked in the readme. The wiki is linked, but it is not referenced how to install (i used the wiki https://github.com/cmangos/issues/wiki/Installation-Instructions)

### Version & Environment

Client Version: -

CMaNGOS Repo & Commit Hash:  https://github.com/cmangos/mangos-tbc/tree/398fd89c70db847df7e83a1ff1ee1304cb889a49

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/c5e6e41ecb739a779aa1cc8ec68b8d470d3cd42f

Operating System: Debian

**Comment by killerwife** [comment]
Readme notes wiki has installation instructions. Closing.
