### ISSUE TITLE
🐛 [Bug Report] Issues with a fresh Install - Missing WOTLK instructions

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/issues#2026]
### Issues with a fresh Install - Missing WOTLK instructions

install instructions in the wiki are only for classic & tbc, i did not check the wotlk repo, but i assume they are missing (i used the wiki https://github.com/cmangos/issues/wiki/Installation-Instructions)

### Version & Environment

Client Version: -

CMaNGOS Repo & Commit Hash:  https://github.com/cmangos/mangos-tbc/tree/398fd89c70db847df7e83a1ff1ee1304cb889a49

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/c5e6e41ecb739a779aa1cc8ec68b8d470d3cd42f

Operating System: Debian

**Comment by adellaci** [comment]
This covers clasic, tbc, & wotlk.
https://github.com/cmangos/issues/wiki/Installation-Instructions

**Comment by ulfgebhardt** [comment]
I refere to stuff like this:

https://github.com/cmangos/issues/wiki/Installation-Instructions#initialize-mangos-database
![image](https://user-images.githubusercontent.com/1238238/63023147-bf9a8680-bea4-11e9-892e-97213087d98f.png)

I am sure its not a major problem - and I see there have been some unifications regarding directory namings etc.

Feel free to close this issue if you do not plan or see the requirement to improve the install instructions to cover the WOTLK branch in a more explicit way.

**Comment by killerwife** [comment]
No longer an issue
