### ISSUE TITLE
🐛 [Bug Report] Issues with a fresh Install - DBC sql Install

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/issues#2027]
### Issues with a fresh Install - DBC sql Install

- The install instructions contain instructions for the DBC-SQL files -> the first commands are for windows. But thats not mentioned there (tho one can guess ofc)
`mysql -uUSER -pPW mangos_tbc < mangos-tbc/sql/base/dbc/*.sql`
Results in (debian):
`-bash: mangos-tbc/sql/base/dbc/*.sql: No such file or directory`

### Version & Environment

Client Version: -

CMaNGOS Repo & Commit Hash:  https://github.com/cmangos/mangos-tbc/tree/398fd89c70db847df7e83a1ff1ee1304cb889a49

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/c5e6e41ecb739a779aa1cc8ec68b8d470d3cd42f

Operating System: Debian

**Comment by cyberium** [comment]
New install instruction doesn't containt that anymore.
