### ISSUE TITLE
🐛 [Bug Report] Issues with a fresh Install - Map extractors

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/issues#2028]
### Issues with a fresh Install - Map extractors

```
Ever since extractors are no longer in repository, you will need to compile them yourself. The extraction process should work identically to Windows, since the scripts are portable.

If you followed this guide the file can be found in:

Executables: /home/mangos/mangos/run/bin/tools

Scripts: /home/mangos/mangos/contrib/extractor_scripts
```

I ~~am~~ was running under windows, my server is linux. On windows i do not have the tools to compile.
But the windows binaries are available in the Pre-Releases. That should be noted in install instructions. Since knowing this you do not need to upload the client files to the server nor is it required to install the build tools under windows.

### Version & Environment

Client Version: -

CMaNGOS Repo & Commit Hash:  https://github.com/cmangos/mangos-tbc/tree/398fd89c70db847df7e83a1ff1ee1304cb889a49

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/c5e6e41ecb739a779aa1cc8ec68b8d470d3cd42f

Operating System: Debian

**Comment by ulfgebhardt** [comment]
seems to specific to justify an issue

**Comment by Muehe** [comment]
@ulfgebhardt The Wiki can be edited by any Github user, so when you find something outdated (of which there is quite a lot sadly) feel free to correct it.
