### ISSUE TITLE
🚀 [Feature Request] DBC.Locale Can you support multiple languages?

### ISSUE THREAD

**Issue by scc172fly** [cmangos/issues#2030]
DBC.Locale
#        DBC Language Settings
#        0 = English; 1 = Korean; 2 = French; 3 = German; 4 = Chinese; 5 = Taiwanese; 6 = Spanish;
#        255 = Auto Detect (Default)

**Comment by ReyDonovan** [comment]
can you write me I will give localization for 8 languages)

**Comment by ReyDonovan** [comment]
[mangos_locale.zip](https://github.com/cmangos/issues/files/4019235/mangos_locale.zip)

**Comment by jimmybrancaccio** [comment]
Closing this out as it seems resolved. Thank you @ReyDonovan 🎉

**Comment by killerwife** [comment]
You can always ask on discord. We do not support them officially for being a tad more under the radar of a known entity.

**Comment by laniidae** [comment]
> [mangos_locale.zip](https://github.com/cmangos/issues/files/4019235/mangos_locale.zip)

sorry for the silly question, but how do i use this?
