### ISSUE TITLE
🐛 [Bug Report]Too high default range for Say and TextEmote

### ISSUE THREAD

**Issue by RazzorX** [cmangos/issues#2033]
## 🐛 Bugreport
You can "hear" NPCs from too far away. Up to 40 yards can not be right.

In the old days there was already an [attempt](https://github.com/cmangos/mangos-svn/commit/0df6a26d0a9d846cb61d8585a5ae4ec9e7fa4b40) to change that, but it was [later](https://github.com/cmangos/mangos-wotlk/commit/f7173d6fc39e1b4e303bab380ecd0f295526d18f) reverted, i think because they thought the values in the core would not match the values in the config. 25 yards sounds more realistic for me.

### Expected behavior
You shouldn't hear NPCs that are too far away.

### Version & Environment

Client Version:  "3.3.5a" (WOTLK) - it effects all versions

CMaNGOS Repo & Commit Hash: [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/ac93cdab16e7dd72278f679d771c9a93586d9f9a)

Database Repo & Commit Hash: [WOTLK](https://github.com/cmangos/wotlk-db/tree/af4560e573150dd910db9bf57592045562d33741)

Operating System: Win7

### Steps to reproduce
1. Find a loud talking NPC
2. Walk ~40yards away from him / her
3. You can "hear" him / her
4. ...
5. Profit

### Crashlog

- None

### Additional
Are there any addons (for Live-Server) that can show the distance between the player and an NPC? To find out a more fitting distance value. I guess Blizz has not changed the values over the years.

-- Sorry for my english...

**Comment by AnonXS** [comment]
And often times, especially on aggro texts are not displayed correctly at all in sniff they mostly happen shortly after creature is called into combat, so there might be some sort of artificial delay so client can display it correctly.

**Comment by domgho** [comment]
The first commit didn't change the default hardcoded values in core where the values are read from the config (in case of invalid or non existing config values) so due to the discrepancy we assumed the ones in the core are right instead of in the config (probably didn't find the first commit).

Please make a PR that reverts the second commit and changes the hardcoded default config values to those in the core.

**Comment by cyberium** [comment]
25 seem to low to me. Do any of you can confirm that 25 is right?

**Comment by al3xc1985** [comment]
@killerwife u fixed this 2

**Comment by AnonXS** [comment]
Set to 25 from 40.
