### ISSUE TITLE
💬 [Support Request] Can't get CMake configured by following official instruction. 

### ISSUE THREAD

**Issue by hisntfmajesty** [cmangos/issues#2038]
Hi. 
I just wanted to play WoW singleplayer. Big dream. Too poor to afford a subscription. 
Did what detailed instruction ( https://github.com/cmangos/issues/wiki/Detailed-installation-guide-for-Microsoft-Windows#cmake) said, step by step.
Then CMake gone like "The C compiler identification is unknown..." and bang, nothing works fine. Logs are attached below. I don't know what features to enable in Visual Studio, or else. 
I wish you'll feel thyself helpful.

More detailed error text: 

> Selecting Windows SDK version  to target Windows 10.0.17134.
> The C compiler identification is unknown
> The CXX compiler identification is unknown
> CMake Error at CMakeLists.txt:28 (project):
>   No CMAKE_C_COMPILER could be found.

[CMakeError.log](https://github.com/cmangos/issues/files/3567280/CMakeError.log)
[CMakeOutput.log](https://github.com/cmangos/issues/files/3567281/CMakeOutput.log)

**Comment by alanman** [comment]
> D:\Python\2019\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(434,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [D:\GA\WOW cManGOS\GitBashHere\mangos-classic\bin\BuildDir\CMakeFiles\3.15.2\CompilerIdC\CompilerIdC.vcxproj]

It looks like what is potentially your C compiler is from a Python install?  That's not part of the "official instruction".  I would recommend downloading Visual Studio if possible.  If not, there may be some custom settings you need to do to make python talk to cmake properly.  Or maybe you just need to add your C compiler path to your environment variables?

**Comment by berserkingyadis** [comment]
@hisntfmajesty did you manage to get it working with the suggestion of installing Visual Studio?

**Comment by jimmybrancaccio** [comment]
@hisntfmajesty We're just following up one more time to see if you were able to get this resolved. Please let us know 😄

**Comment by al3xc1985** [comment]
I believe this can be closed. I oersonally configuree cmake lately and it is working by wiki instructions
