### ISSUE TITLE
Client Error on Characters Created In Zones They Don't Have Required Proficiency For

### ISSUE THREAD

**Issue by Lillecarl** [cmangos/issues#204]
If you happen to have changed the spawn location of characters to EX outland and didnt change the startlevel, then characters logging in will get wowerror for some reason. Possibly related to

https://github.com/cmangos/mangos-tbc/commit/73e253c4d418e1981f21917d3e744cfbeeaa200c
https://github.com/cmangos/mangos-tbc/commit/66624b866050f10a500c7f5743545f48f1d05e73

**Comment by al3xc1985** [comment]
I don't think is valid @killerwife

**Comment by killerwife** [comment]
This might still be an issue but I am wondering if this should be considered since its something downright custom and the author didnt deal with it himself :D

**Comment by Lillecarl** [comment]
@killerwife It's not really an issue for us, but might be something hard for someone using cmangos for making their own fun project if they don't share the same understanding of cmangos as we do.
