### ISSUE TITLE
🐛 Magenta Cap Clusters

### ISSUE THREAD

**Issue by Tobschinski** [cmangos/issues#2040]
contain 1-6 Magenta Fungus Cap, (in up to 3 stacks)

maybe like this:
1 100%
2 66%
3 33% 
?

% unclear

**Comment by AnonXS** [comment]
https://classic.wowhead.com/item=8047/magenta-fungus-cap

https://github.com/cmangos/tbc-db/commit/00201ccb585ebcd7f5b84a6b38eefa66119f39d9#diff-36aacf86200a9261b3aad012717d17c457a4b3259c54e1f05aea5769797650edR5

maybe can be improved further.
