### ISSUE TITLE
🐛 [Bug Report] boss_shirrak cast spell causes mangosd crash

### ISSUE THREAD

**Issue by yukozh** [cmangos/issues#2044]
### Expected behavior
Should add a global catch to catch all of the script AI exceptions. If error happens, close the instance and log erros, not crash the whole process.

### Version & Environment
Client Version: 2.4.3" (TBC)
CMaNGOS Repo & Commit Hash:  TBC
Operating System: WIN10

### Steps to reproduce
1. attack the boss shirrak
2. after the boss focuses on someone, the mangosd get crashed

### Others
Got the dump from the crash process, it crashed at 

```c++
template<class T>
inline void Cell::VisitGridObjects(const WorldObject* center_obj, T& visitor, float radius, bool dont_load)
{
    CellPair p(MaNGOS::ComputeCellPair(center_obj->GetPositionX(), center_obj->GetPositionY()));
    Cell cell(p);
    if (dont_load)
        cell.SetNoCreate();
    TypeContainerVisitor<T, GridTypeMapContainer > gnotifier(visitor);
    cell.Visit(p, gnotifier, *center_obj->GetMap(), *center_obj, radius);
}
```

because the center_obj is null, a workaround is adding a null check in this method:

```c++
if (!center_obj)
    return;
```

The boss is casting spell #32301, but I did not find this ID in script boss_shirrak. Also, dunno after adding this workaround, which phase will be impacted.

**Comment by Warlockbugs** [comment]
Possibly related: https://github.com/cmangos/issues/issues/2057

**Comment by cala** [comment]
Fixed in https://github.com/cmangos/mangos-tbc/commit/78d4860c3c13411b500f467accb56e8610b625aa
Thank you.
