### ISSUE TITLE
🐛 Torloth the Magnificent despawns

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#2047]
## 🐛 Bugreport
When doing Q10781 [Battle of the Crimson Watch] After he spawns, He says his text and despawns. Seems something in SD2 is amiss.

### Expected behavior
Should say text and attack.

### Version & Environment
Client Version: 
3.3.5a" (WOTLK)

### CMaNGOS Repo & Commit Hash: 
[WOTLK](https://github.com/cmangos/mangos-wotlk/tree/e0770c55a64235f6f4a67f4a0c819c3f8efde502)

### Database Repo & Commit Hash: 
Project-Silvermoon Rev 411

### Operating System: 
Windows 7
### Steps to reproduce
1.  .add quest 10793
2. .go creature 25983 [CDB guid]
3. complete quest and take next one
4. kill mobs until Torloth the Magnificent spawns.

### Crashlog
None

**Comment by killerwife** [comment]
Script was reworked in 2020 completely
