### ISSUE TITLE
💬 [Support Request] Way to disable cooldowns for character spells

### ISSUE THREAD

**Issue by siewert87** [cmangos/issues#2048]
## 💬 Support Request

Is there any way to disable cooldowns for character spells? I tried _.cheat cooldown off_ but it's saying _No such comand_.

### Version & Environment

Client Version: 1.12.1

CMaNGOS Repo & Commit Hash: CLASSIC (bd8b2a3b4c459ff49fc1a4edb1de4425c8678996)

Database Repo & Commit Hash: Classic (c012683f52afa57a8e1705d9f9adfccf7d197519)

Operating System: Linux Flavor

**Comment by killerwife** [comment]
No. There is no such custom feature. Feel free to tinker with spell_template on your own time and clear it there from all player spells.

**Comment by siewert87** [comment]
I'll take a look, thank you anyway.
