### ISSUE TITLE
🐛 [Bug Report] Charge in water

### ISSUE THREAD

**Issue by yukozh** [cmangos/issues#2049]
TBC 2.4.3

if charge in water, the system always makes your dest to be the surface of water. Expected: the dest should be underwater nearby the creature.

Cast the charge:

![image](https://user-images.githubusercontent.com/2216750/67622005-33172780-f848-11e9-89b8-1203f2708a24.png)

The dest is wrong:

![image](https://user-images.githubusercontent.com/2216750/67622093-2e06a800-f849-11e9-8a59-48abba0b21ab.png)

**Comment by yukozh** [comment]
I saw the mangos only handle the charge in here: https://github.com/cmangos/mangos-tbc/blob/master/src/game/Spells/Spell.cpp#L5122

So I want to know how does the spell work? Is the real charge path computed in client side?

**Comment by Warlockbugs** [comment]
Should be fixed as of:
https://github.com/cmangos/mangos-classic/commit/8f59074bb6b93630103e9082f6e695f6d9e5e50c
https://github.com/cmangos/mangos-tbc/commit/d91eac113fa905aae801058f6a636922a8684998
https://github.com/cmangos/mangos-wotlk/commit/925fbba3f3b52921d5846d37cbafb7fc04861bd5
