### ISSUE TITLE
🐛 [Bug Report] AoE Damage Cap

### ISSUE THREAD

**Issue by miraco** [cmangos/issues#2054]
## 🐛 Bugreport
 Since patch 2.2.0, most area effect damage effects have an 'area damage cap' which limits the potency of the spell if used against a large number of targets simultaneously.

As always blizzard never mentioned directly in a patchnote that this system was added but they mentioned it for specific spells. 

Patch 2.2.0:
Druid:
- Hurricane: This spell is now affected by area damage caps. Its bonus damage coefficients have also been increased.
Hunters
- Volley: This spell is now affected by area damage caps. Its bonus damage coefficients have also been increased. It also correctly consumes charges of Misdirection.
Mages:

-  Blizzard: This spell is now affected by area damage caps. Its bonus damage coefficients have also been increased.
-  Frost Nova: This spell is now affected correctly by area damage caps.

Warlocks:
- Rain of Fire: This spell is now affected by area damage caps. Its bonus damage coefficients have also been increased.
- Seed of Corruption: Dead targets will no longer be erroneously counted toward the damage cap on this spell.

Patch 2.4.0:
Mages:

- [Arcane Explosion]: The damage cap for area of effect damage on this spell has been increased by approximately 50%.
A theoretical example of Arcane Explosion; 1000 damage cap, 500 hit per mob: (Taken out of an old elitistjerks thread) [[](https://web.archive.org/web/20081023033855/http://elitistjerks.com/f47/t25902-aoe_spell_cap_mechanics/)

 One Mob:
```
[Player]'s Arcane Explosion damages [Mob1] for 500.
500 damage done total
```
Two Mobs:
```
[Player]'s Arcane Explosion damages [Mob1] for 500.
[Player]'s Arcane Explosion damages [Mob2] for 500.
1000 damage done total.
```
Three Mobs:```

[Player]'s Arcane Explosion damages [Mob1] for 333.
[Player]'s Arcane Explosion damages [Mob2] for 333.
[Player]'s Arcane Explosion damages [Mob3] for 334.
1000 damage done total
```
 The three-mob encounter does 333 damage to each mob (the 334 is from the decimals), which is because of the 1000 damage cap. Because I deal 500 damage per mob, it took me two mobs to reach the cap; when I add a third, I exceed the cap, so my damage must be modified to re-equal the cap. The theoretical cap is 1000, so the equation to solve for damage is: 1000 / 3, or 333.3 damage to each mob.
 
Another example is below, involving one critical strike; 1000 theoretical cap; 500 base, normal damage; 750 unmodified critical strike:

One Mob:
```
[Player]'s Arcane Explosion damages [Mob1] for 750 critically.
750 damage done total

```
Two Mobs:
```
[Player]'s Arcane Explosion damages [Mob1] for 500.
[Player]'s Arcane Explosion damages [Mob2] for 750 critically.
1250 damage done total; 1000 damage is counted towards the cap, and 250 is extra damage
```
Three Mobs:
```
[Player]'s Arcane Explosion damages [Mob1] for 333.
[Player]'s Arcane Explosion damages [Mob2] for 333.
[Player]'s Arcane Explosion damages [Mob3] for 500 critically.
1167 damage total; 1000 is counted towards the cap, and 167 is extra damage from the critical.

```
Also, because CoE and such damage-increasing debuffs "avoid" the cap, a situation can be true: 
With a cap of 1000; a base, normal hit of 500; and two mobs:

No mobs with CoE:
```
[Player]'s Arcane Explosion damages [Mob1] for 500.
[Player]'s Arcane Explosion damages [Mob2] for 500.
1000 damage done total.
```
One Mob with CoE:
```
[Player]'s Arcane Explosion damages [Mob1] for 550.
[Player]'s Arcane Explosion damages [Mob2] for 500.
1050 damage done total; 50 extra damage.
```

Two Mobs with CoE:
```
[Player]'s Arcane Explosion damages [Mob1] for 550.
[Player]'s Arcane Explosion damages [Mob2] for 550.
1100 damage done total; 100 extra damage.
```

### Expected behavior
Known damage caps: (Source: [](http://web.archive.org/web/20081023033855/http://elitistjerks.com/f47/t25902-aoe_spell_cap_mechanics/))

Mage
https://i.gyazo.com/7febf6ad8f7096ed660c833e8bbc5867.png

Warlock
https://i.gyazo.com/95d40d837b06c972ff98b36b773fab5c.png
Rain of Fire: 6710
Hellfire: 5200
Source: [](https://web.archive.org/web/20080811092840/http://elitistjerks.com/f31/t17008-warlock_pve_raiding_compendium/)

> Aoe cap: if your seed of corruption detonates for more than 13580 on all targets combined, it will do less damage. When this happens, the detonation damage will be scaled down so that the total is 13580. This reduction is done after calculating +damage gear, talents and buffs so it is the same for every gear and spec. 
> 
> Example, if you hit 10 targets with SoC detonation, you will hit each for 1358. 
> 
> Some multipliers (crits, CoS, etc) are not affected and will allow you to hit individual targets for more.
> 
> Example: SoC hitting 10 targets will hit each for 1358, but crits will be 1358x1.5.
> 
> For completeness: Hellfire caps at 5200 per tic, and RoF at 6710 per tic. You hit this at around 10 targets.

Priest
https://i.gyazo.com/072baac9f7926ac3dd43d8b5aa9ddd24.png

Shaman:
https://i.gyazo.com/80bbb353b4debcbaad7357a3efa854ee.png

So far used and found sources:
http://web.archive.org/web/20090107184759/http://forums.worldofwarcraft.com/thread.html?topicId=443123919&sid=1
http://web.archive.org/web/20081023033855/http://elitistjerks.com/f47/t25902-aoe_spell_cap_mechanics/
http://wowwiki.wikia.com/wiki/Patch_2.2.0
https://wow.gamepedia.com/Area_of_Effect
http://classic-wow.wikia.com/wiki/Area_damage_caps
http://web.archive.org/web/20080811092840/http://elitistjerks.com/f31/t17008-warlock_pve_raiding_compendium/
http://web.archive.org/web/20081023033855/http://elitistjerks.com/f47/t25902-aoe_spell_cap_mechanics/
https://www.back2basics-wow.eu/community/index.php?page=Thread&threadID=16751&pageNo=1 (sadly on german tho but they also discussed it with a few sources ive linked here)

I haven't found any sources yet for other aoe spells than the already posted ones. 
It seems like consecration is not affected by any caps. There are plenty of people talking about that and as you can see in this video it doesnt matter how many adds hes tanking, the damage done remains the same:

This Bugreport was taken from
https://forum.excalibur.ws/bugtracker/excalibur-tbc/classes/mage/aoe-damage-cap-r7160/?tab=comments#comment-27652

### Version & Environment
<!--
  Client Version - is required
  Valid values are:
  - "1.12.1" (CLASSIC)
  - "2.4.3" (TBC)
  - "3.3.5a" (WOTLK)
-->
Client Version:  2.4.3 TBC

<!--
  Commit Hash - is required
  Valid values are:
  - [CLASSIC](https://github.com/cmangos/mangos-classic/tree/XXXX)
  - [TBC](https://github.com/cmangos/mangos-tbc/tree/XXXX)
  - [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/XXXX)

  To find XXXX use "git log -1 --format=%H" in your local CMaNGOS repo
-->
CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-tbc 
67b3fcc

**Comment by Yatzii93** [comment]
Im also interested in this, seed of corrupt does insane damage due to what I believe is a lack of a cap. I just not well versed on this subject to really comment.

**Comment by killerwife** [comment]
The report is mostly correct. The feature is missing because it requires heavy refactor of spell damage processing. Also a completely different system is needed in wotlk, which is again completely different and doesnt need this refactor. Atm it is a very low priority for me, but anyone can pick this up if they want.

**Comment by killerwife** [comment]
I made a recent change to damage calculation and all I need is a huge Excel spreadsheet with the data. Once someone makes it, compares it to 2.1 and 2.2 patch notes, I will implement the system.

**Comment by miraco** [comment]
Thats not completet, thats all i found so far.
Arcane Explosion is pre 2.4 for example cant find post 2.4

**Comment by miraco** [comment]
Fixed i guess https://github.com/cmangos/mangos-tbc/commit/915379869506f263baac6b44ebee1e8dd2db945c
