### ISSUE TITLE
🐛 [Bug Report] Can't access to the Molten core with Lothos Riftwaker

### ISSUE THREAD

**Issue by CedricThomas** [cmangos/issues#2055]
## 🐛 Bugreport
Can't access to the **Molten core** with **Lothos Riftwaker** (in gm mode or with the **Attunement core**). 
The portal access is still working.

### Expected behavior
Lothos Riftwaker need to teleport the player in the molten core

### Version & Environment

Client Version: 
  - "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/mangos-classic/tree/9805f3642ddf3cd2eb54c99d3d3958269dc5874c)

Database Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/classic-db/tree/d9faa0dfd4f666e2de97a22066c8d8b0f4f3a8ee)

Operating System: 
  - Linux Flavor (Debian)

### Steps to reproduce
1. Create a new character with GM account
2. Use the command `.tele Molten Core`

GM version :
3.a. Use the command `.gm on`
4.a. Speak with Lothos Riftwaker to get teleported to the Molten Core

Player version:

3.b. Use the command `.levelup 60` with you character selected
4.b. Accept Lothos Riftwaker quest
4.b.  Use the command `.additem 18412` with you character selected
5.b.  Resolve  Lothos Riftwaker quest
6.b. Speak with Lothos Riftwaker to get teleported to the Molten Core

### Crashlog
- None

**Comment by cala** [comment]
Thank you for opening this issue.
I confirm the teleport through Lothos gossip no longer work. I investigated very quickly this issue and it seems that spell 25139 (Teleport to Molten Core DND) is no longer working even with the target position set in the DB. We need to investigate this.

**Comment by Yatzii93** [comment]
The spell targeting needs to be changed. I fixed this a little while ago. It's to do with it's targets in the db I'm pretty sure. Although might not be the ideal fix.

**Comment by Yatzii93** [comment]
I think it's just the teleport spells tbh, we saw the samething with the quel teleport orb/spells. I also had to change my custom portals a while ago after the targeting rework. I remember Killer saying he added some cheat checks (if I remember correctly) the ones that affected afew talents, it seems to be the same thing. Tbh though, it's only the teleport spells I've had issues with + the talents that we've resolved.

**Comment by cala** [comment]
I confirm this is unrelated to data_flags in this case, this is the spell itself that is not working. I did not investigate further to see if this is a wider issue, though.

**Comment by Yatzii93** [comment]
Pretty sure you just have to remove 17 from EffectImplicitTargetB1 in the DB similar to the other few teleport spells that broke. Killer did the same to resolve a couple orbs in Quel and I did the same for my custom portals and I pretty sure I did it for this spell too.

**Comment by killerwife** [comment]
TARGET_FLAG_UNIT_UNK means that the spell has to go like "lothos -> player" and then it should work in theory

**Comment by cala** [comment]
Seems to be fixed as of today (just tested successfully right now). I guess @killerwife did his magic in the past export! 👍 

@CedricThomas peux-tu tester et confirmer s'il te plaît ?

**Comment by CedricThomas** [comment]
I will try asap !

**Comment by killerwife** [comment]
Correct. This should be ok now.
