### ISSUE TITLE
🐛 [Bug Report]Characters Losing spells

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#2056]
## 🐛 Bugreport
Character are losing spells shoot,throw,dual weild & possibly more. You can relearn them on level up. But, when you log out and log back in. They are missing again.

### Expected behavior
Shouldn't lose spells

### Version & Environment
Client Version:"3.3.5a" (WOTLK)
VS 2015

### Commit Hash
 [WOTLK]https://github.com/cmangos/mangos-wotlk/commit/2eb0eb85ac290addb3c73523003d6e4640e47e2a)

### Database Repo: 
PSDB 411

### Operating System: 
Windows 7 64x

### Steps to reproduce
1.Look at char spells
2.Notice missing throw,shoot,ect...
5. Profit

**Comment by ekg98** [comment]
i am missing shoot on all my characters that have guns.  Even my hunter that has skills higher than 1.

**Comment by Rog360** [comment]
Glad to see it wasn't just me. I hope this is fixed asap. as this is a game killer... :(

**Comment by ekg98** [comment]
Yes. I noticed for the characters with gun skill at 1. The guns are red in the npc vendor. Also when mousing over stats. It shows the item type “gun” in red.

**Comment by killerwife** [comment]
No worries. Tomorrow I am on this.

**Comment by Rog360** [comment]
Nice! Thanks for your work Killerwife... :)

**Comment by ekg98** [comment]
Yeah i believe i loose the skill. Was playing my rogue and could have sworn i bought stuff like guns and crossbows etc. login and they disappear too. Not sure if related.

**Comment by AnonXS** [comment]
https://forum.cmangos.net/t/strange-talent-problem/183

**Comment by killerwife** [comment]
Okay, I did the following:
Setup clean mangos-wotlk, fresh world db, fresh char db, fresh realmd
I created a new druid, levelled him up, saved, relogged multiple times, worked fine.
Created a new rogue, learned dual weild, maxed weapon skills, worked fine.
Created a new hunter, on first login, auto shot was there.

I need help from you guys disagnosing this.

**Comment by ekg98** [comment]
![267F03D1-4441-4580-9AD7-A0C996587052](https://user-images.githubusercontent.com/24751528/69833391-7e36a880-1201-11ea-988f-e79843050252.jpeg)

Appeared at ding to level 11. Logout and disappeared

**Comment by cyberium** [comment]
- created a rogue and leveled normaly (doing quest and killing mobs) until level 11
- getting killed multiple time from different creatures
- logout while alive/ghost

no way to reproduce.

Maybe its time to enable sql log in conf file and search any error that can help us for that problem.
It may be related to something not correct in the core or in your specific db (one update didn't made what is supposed to do?)

**Comment by ekg98** [comment]
Rog are you able to replicate?

**Comment by Rog360** [comment]
Not @ home for holidays. But, I can help check, when I return in a few days. I'm not ruling out sql problem. Will check logs then. Thank you all for your work... :)

**Comment by Orcman2019** [comment]
It isn't that hard, 

Create an orc warrior,
hit level 20
teleport to UC/TB/SM and learn weapon skills, they work when you first learn them, I was using the heirloom gun to pull mobs
Die to something, skills will be gone when you rez and learned weapon types will show red text. Repurchasing the throw/crossbow/gun skills will not restore shoot/throw.
Server log shows what I put in the forum, it pulls them off the toolbars as something that isn't known.

**Comment by Orcman2019** [comment]
Blood elf Paladin did the same thing, learn a skill like polearms and die and it will be unlearned again.

**Comment by ekg98** [comment]
> It isn't that hard,
> 
> Create an orc warrior,
> hit level 20
> teleport to UC/TB/SM and learn weapon skills, they work when you first learn them, I was using the heirloom gun to pull mobs
> Die to something, skills will be gone when you rez and learned weapon types will show red text. Repurchasing the throw/crossbow/gun skills will not restore shoot/throw.
> Server log shows what I put in the forum, it pulls them off the toolbars as something that isn't known.

Cyberium nor killerwife can replicate it with a new core or db.

**Comment by cyberium** [comment]
Replicated today i'll work on it

**Comment by cyberium** [comment]
Please try to reproduce it now.

**Comment by Orcman2019** [comment]
Seems to be working, tested out and the skills seem to be staying now.

**Comment by Rog360** [comment]
Working on mine too. Thank you cyberium... ;)

**Comment by Rog360** [comment]
Fixed! So this one is closed... :)
