### ISSUE TITLE
🐛 [Bug Report] Shadow Labyrinth Boss blackheart bug

### ISSUE THREAD

**Issue by yukozh** [cmangos/issues#2060]
TBC 2.4.3

After the boss casted `INCITE_CHAOS`, the each party member will get the buff that they were controlled by boss, however, when the control expired, boss will stop combat and disappeared. The expected behavior should be the boss continue combat with party members.

**Comment by jimmybrancaccio** [comment]
@yukozh Please provide **all** of the information quested in the bug report.

**Comment by cala** [comment]
Thanks for this report.
However, closing as duplicate of https://github.com/cmangos/issues/issues/1908
