### ISSUE TITLE
[Bug Report]  Creature Group moving

### ISSUE THREAD

**Issue by miraco** [cmangos/issues#2062]
##  Bugreport
While researching for the stair of desteny event i found that we are missing a way to set creatures angle distance and turn points for follow movement.

And we are missing a way in AI scripts that spawned creatures can set to a group to follow. Somethink like:
ACTION_T_FOLLOW, Distance, Angle, Creature
### Visualisation
We have groups like this:
![fel soldier group](https://user-images.githubusercontent.com/6261245/68292794-ec69ce80-008c-11ea-8250-def9da573e19.jpg)

Walking in a straight line
![ss+(2019-11-06+at+12 01 17)](https://user-images.githubusercontent.com/6261245/68292928-2cc94c80-008d-11ea-99e4-659d9ba30721.png)

But can also have groups that walk a bit behind them.
![ss+(2019-11-06+at+11 17 36)](https://user-images.githubusercontent.com/6261245/68292797-f095ec00-008c-11ea-9243-aeec0e6f2e66.jpg)

![followangle2 png](https://user-images.githubusercontent.com/6261245/68292810-f7246380-008c-11ea-80a9-9af230ec94a3.jpg)

Groups that turn around after a specific point should also not crossover. 

### Benefits & Purpose
Can manualy set follow angle and dist for groups.

**Preventing Cross Over**
[Current behavior on cmangos](https://www.youtube.com/watch?v=WZV9rDSi7fI&feature=youtu.be)

[Behavior on retail](https://youtu.be/PdpHB50_nrg?t=53)

[Another retail video](https://www.youtube.com/watch?v=1cKLzPZx9LA&feature=youtu.be)

**Comment by miraco** [comment]
I added some videos where you can see the crossover (cmangos) and how it should work. (retail)

**Comment by miraco** [comment]
After looking a bit more about the moving on retail i think the complete system about creaturegroups moving could get a rewrite and this should probably get its own movement generator.

`// Calculate distance and time it will take to reach for leader
    float dist = leader->GetDistance(wp.x, wp.y, wp.z) +
                 leader->GetObjectBoundingRadius();
    float speed;
    if (wp.run)
        speed = leader->GetSpeedRate(MOVE_RUN);
    else
        speed = leader->GetSpeedRate(MOVE_WALK);

    if (speed <= 0.0f)
        speed = 1.0f;

    float time = dist / speed;

    if (time <= 1.0f)
        time = 1.0f;

    // Make everyone else walk towards their adjusted waypoint in a speed that
    // gives the same travel time as the leader`

**Comment by Ve1vet** [comment]
@miraco yes it should( should be movement generator for linked groups to keep them in sync ). Also when groups turns, mobs with smaller turn radius moves slowly & mobs with bigger turn radius moves faster.
And in Sunwell Plateau, as i remember, groups have script for turn around in sync( there is more complex turn around than in Black Temple or other places ).

**Comment by jimmybrancaccio** [comment]
@miraco Is this really a feature request? It sounds more like a bug to me - as it sounds like something is not working the way it should?

**Comment by killerwife** [comment]
This is correctly a feature request since this not only requires movement but also group AI behaviour to work in unison.

**Comment by miraco** [comment]
I think its a bit of both. The movement part is indeed a bug.

The part with angle and distance handling is more of a feature request.

**Comment by cyberium** [comment]
Its about our lack of support of creature group and creature formations. We have to do it someday or another. Hoping someone will comme up with a good db table structure to represent them, maybe @Tobschinski ? (he know everything about that matter). Then we'll have to handle creature group in the core and create a new formation generator.

**Comment by cala** [comment]
:smiling_imp:

**Comment by miraco** [comment]
https://github.com/TrinityCore/TrinityCore/commit/0e2342c1698d9e2dc8a8c9d559f232cbb83707cb#diff-30f3be0c1f09a63767f7837f8b203362

https://github.com/TrinityCore/TrinityCore/commit/0e2342c1698d9e2dc8a8c9d559f232cbb83707cb#commitcomment-38299651

**Comment by killerwife** [comment]
Resolved by cyberiums formations.
