### ISSUE TITLE
🐛 [Bug Report] Casting npcs not going back to target after being feared

### ISSUE THREAD

**Issue by Yatzii93** [cmangos/issues#2063]
## 🐛 Bugreport

Casting npcs not going back to target after being feared
### Expected behavior

Once the mob stops fleeing it should be able to move again freely. Right now it seems to be stunned in place.
### Version & Environment

Client Version: 
  - "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-tbc/commit/29906c91a7925581dc910ae15c79e4d0d9f6acd2

Database Repo & Commit Hash: 
https://github.com/cmangos/tbc-db/commit/088e92c93377906b3fafabe7591fd8eaa6169650

Operating System: 
 - Win XX
### Steps to reproduce
1. .learn 34322 (Phychic scream)
2. run through a load of casting mobs you can fear - Zul'farrak is a good dungeon. fear as you run through.
3. the casting mobs will get stuck in place at times.

It seems to be if you fear a mob and then go out of range of it's casting ability.
https://i.imgur.com/lSp9iGm.jpg <---image of occurance

### Crashlog

- None

**Comment by Yatzii93** [comment]
Re-implementing this code - https://github.com/cmangos/mangos-tbc/commit/c07bbdfbc1360e15aedb72e2aedfa506a29d0c74
Seems to have solved the issue:

  // Non-client controlled unit with an AI should have target restored (if exists)
    else if (owner.AI() && !owner.HasFlag(UNIT_FIELD_FLAGS, (UNIT_FLAG_CONFUSED | 

> UNIT_FLAG_FLEEING | UNIT_FLAG_STUNNED)))
>     {
>         if (Unit* victim = owner.getVictim())
>         {
>             owner.SetTarget(victim);
>             owner.AI()->HandleMovementOnAttackStart(victim);
>         }
>     }

@killerwife Does this make sense, it was an educated guess to revert it going back through the commits. I cannot reproduce the problem now whereas I could cause it reliably before.

**Comment by Warlockbugs** [comment]
Reproducing as level 70 player in Zul'Farrak:
1.  Spot a group of Sandfury Shadowcasters.
2.  Move close enough for them to be affected by your AOE fear (8 yd Psychic Scream), but not aggro on you yet.
3.  Initiate combat by AOE fear: `.cast 10890 triggered`
4.  Move about 20 yd away to get reliably out of range of their spellcasts.
5.  When fleeing effect expires, observe Shadowcasters being stuck on "Idle" movement while targeting player.
6.  Shadowcasters will resume chasing if player moves within the range of their spellcast.

Unrelated issue(s):
- Mobs drop combat if player simply outruns their visibility range in Zul'Farrak. This should not happen inside the dungeon.
