### ISSUE TITLE
🐛 [Bug Report]warrior Charge spell    No automatic attack

### ISSUE THREAD

**Issue by yh20100** [cmangos/issues#2065]
## 🐛 Bugreport
left click a target, use Charge spell, After the charge，No automatic attack
But if right click a target,use Charge spell, After the charge，automatic attack

**Comment by Warlockbugs** [comment]
Should be fixed as a consequence of fixing global case of abilities triggering auto-attack:
https://github.com/cmangos/mangos-classic/commit/d5be8e46c3d0cce69129f20dabfc2e4dc5de63f8
https://github.com/cmangos/mangos-tbc/commit/0d7bb2b4a702a3f4eba372e3ff6c26c0ab316dff
https://github.com/cmangos/mangos-wotlk/commit/f3c87cefd9be0bb1763570def9a5b01ca6acf979
