### ISSUE TITLE
🐛 [Bug Report] Yetimus doesn't exist 

### ISSUE THREAD

**Issue by Orcman2019** [cmangos/issues#2067]
## 🐛 Bugreport

Doesn't seem to exist in the database, no quest either.
https://www.wowhead.com/npc=47484/yetimus-the-yeti-lord
https://www.wowhead.com/quest=28485/yetimus-the-yeti-lord

### Expected behavior
Normally wanders between the waypoints and killed for related quest.

### Version & Environment
3.3.5.a
WOTLK
5ae8fcd3b7166305dcdb281c21f315491b614a88

Operating System: 
Linux Mint 19.2

### Steps to reproduce
1. tele to tarren mill
2. go west near the yeti cave, should be walking around there.

**Comment by Grz3s** [comment]
Both npc and quest ...Added in patch 4.0.1.12984
Should be closed.

**Comment by Orcman2019** [comment]
Oh wow, I swear it was in there prior to that but I guess that was 2010 it got added.

**Comment by Ve1vet** [comment]
@Orcman2019  Patch 4.0.3 (**15-Nov-2010**): Added.

https://wowwiki.fandom.com/wiki/Quest:Yetimus_the_Yeti_Lord
