### ISSUE TITLE
🐛 [Bug Report] Cyclonean summons twice

### ISSUE THREAD

**Issue by Orcman2019** [cmangos/issues#2068]
## 🐛 Bugreport
Part of warrior quests, when summoned there are 2 of them instead of one.
https://classic.wowhead.com/quest=1713/the-summoning
https://classic.wowhead.com/npc=6239/cyclonian

### Version & Environment
Client Version: 
3.3.5a
WOTLK
5ae8fcd3b7166305dcdb281c21f315491b614a88

Operating System: 
Linux Mint 19.2

### Steps to reproduce
1. Start quest
2. Wait for summoning
3. 
4. ...
5. Profit

**Comment by Orcman2019** [comment]
![cyclonian_a](https://user-images.githubusercontent.com/58348159/72036268-800b7700-3257-11ea-88d4-73bad1cc759c.jpg)
![cyclonian_b](https://user-images.githubusercontent.com/58348159/72036269-800b7700-3257-11ea-8f15-94bc193e2eb1.jpg)
![cyclonian_c](https://user-images.githubusercontent.com/58348159/72036270-80a40d80-3257-11ea-8aa7-90c3b8a6157e.jpg)
![cyclonian_d](https://user-images.githubusercontent.com/58348159/72036271-80a40d80-3257-11ea-97b3-89c2ea0b5df9.jpg)
![cyclonian_e](https://user-images.githubusercontent.com/58348159/72036267-800b7700-3257-11ea-8fd0-a6547b96bb41.jpg)

**Comment by Orcman2019** [comment]
Looks like it's working, location is same instead of where the video shows...

![cyclonian_f](https://user-images.githubusercontent.com/58348159/72121822-6599d200-3319-11ea-88a7-27824826d644.jpg)

**Comment by AnonXS** [comment]
Change for another time as i didnt have sniff coords on hand.
