### ISSUE TITLE
🐛 [Bug Report][classic-db]

### ISSUE THREAD

**Issue by raodan218** [cmangos/issues#2069]
## 🐛 Bugreport
classic db data incorrect, when import classic db by running InstallFullDB.sh, it reports error:

> Trying to apply ACID/acid_classic.sql ...
ERROR 1264 (22003) at line 17109: Out of range value for column 'action2_type' at row 268
ERROR: cannot apply ACID/acid_classic.sql

I check 'acid_classic.sql' and found that the line with id 1534106 is something wrong:
('1534106','15341','0','0','100','1025','600000','600000','120000','120000','0','0','11','8269','0','1','-106','0','0','0','0','0','0','0','General Rajaxx - Cast Frenzy after 10 Minutes')

'action2_type' column which type is tinyint has value -106.

I change this value to 1 and the data import can be completed successfully.

### Expected behavior
The wrong value need to be corrected.

### Version & Environment

Client Version:  "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: 

Database Repo & Commit Hash:  ttps://github.com/cmangos/classic-db/master

Operating System:  Windows 10

### Steps to reproduce
1. Run InstallFullDB.sh

### Crashlog

- None

**Comment by cala** [comment]
I did not yet do all the usual cleaning I regularly do to ACID, so it is possible that mistakes exist though this one does not appear on my system. What DB engine do you use?

**Comment by raodan218** [comment]
My DB version is MySQL 5.7.26  which is part of WAMP, and all databases and tables are created from SQL scripts without any modification.

>mysqld.exe --version
mysqld.exe  Ver 5.7.26 for Win64 on x86_64 (MySQL Community Server (GPL))

**Comment by AnonXS** [comment]
Introduced here: https://github.com/cmangos/classic-db/commit/c3301b56a20dbe9169d053c7f71e65280b859d2f
