### ISSUE TITLE
🐛 [Bug Report] Base agility does not change melee crit

### ISSUE THREAD

**Issue by henrikssonkevin** [cmangos/issues#2071]
## 🐛 Bugreport
Base agility not scaling melee crit correctly.

### Expected behavior
Base agility should scale melee crit correctly.

### Steps to reproduce
1. Make a rogue
2. Gradually level up using `.levelup 5` while keeping an eye on melee crit
3. Once you hit 25 the crit will be almost 0%.

### Version & Environment
Client Version: "2.4.3" (TBC)

Database Repo: https://github.com/cmangos/tbc-db
Database Version: TBC-DB 1.7.0 'A New Hope' for CMaNGOS-TBC
Database Update: required_s2396_01_mangos_game_event_split

Operating System: Windows 10 x64

Screenshot is of a level 31 rogue only wearing pants with +14 agil.
![critagil](https://user-images.githubusercontent.com/23076488/71310083-38d85600-2410-11ea-91d9-1adc404bd1fd.PNG)

**Comment by al3xc1985** [comment]
I believe that crit is reduce to zero because your skill weapon compared with level is gradually reduced dramatically

**Comment by henrikssonkevin** [comment]
@al3xc1985 wow silly me, you are completely right. Thank you!
