### ISSUE TITLE
🐛 [Bug Report] [WotLK] Fishing not possible

### ISSUE THREAD

**Issue by Dainara82** [cmangos/issues#2072]
## 🐛 Bugreport
  - "3.3.5a" (WOTLK)
-->
Client Version:  3.3.5a
CMaNGOS Repo & Commit Hash:  f3c87cefd9be0bb1763570def9a5b01ca6acf979
Database Repo & Commit Hash: 5ae8fcd3b7166305dcdb281c21f315491b614a88
- Linux Debian 9 Server

Fishing not possible, tested in several zones
Every cast fails with "Cast did not land in fishable water."

**Comment by killerwife** [comment]
@cyberium I am gonna ask u for aid here because I have honestly not a clue :/

**Comment by ekg98** [comment]
Theres another post about this issue. It shows a video with the error.

**Comment by AnonXS** [comment]
yea in an issue called "Multiple problems with latest build compilation and DB" ~,~

Here is the info:

I can confirm fishing does not work for me at all. Astuffedtiger has compiled a video here. This works in some water and others not.
https://youtu.be/Rri7qKAqZ7k

**Comment by hipejoe** [comment]
Fix for those who like to fish:
In Spell.cpp @ case TARGET_LOCATION_CASTER_FISHING_SPOT:

Change: 
if (!m_caster->GetTerrain()->IsInWater(x, y, m_caster->GetPositionZ() + 1.f, &liqData))

To:
if (!m_caster->GetTerrain()->IsInWater(x, y, m_caster->GetTerrain()->GetWaterLevel(x, y, m_caster->GetPositionZ()) - 1.0f, &liqData))

Hope this helps!
