### ISSUE TITLE
🐛 [Bug Report] Fishing from pools with group loot results in "trying to open a loot without credential"

### ISSUE THREAD

**Issue by codestothestars** [cmangos/issues#2074]
## 🐛 Bugreport
Fishing from a pool (e.g. Oily Blackmouth School or Floating Debris) while in a group with group loot turned on fails when it is another player's turn for loot. The fishing cast simply ends without showing a loot window and play otherwise proceeds as usual. The server console logs the error `Loot::ShowContentTo()> Player X (Guid: Y) is trying to open a loot without credential`. The failure advances the group loot turn, so for example in a group of 2, every other fish will fail. It also consumes one "tick" of the pool.

Fishing outside of pools appears to be unaffected.

### Expected behavior
Fishing pools should neither affect nor be affected by group loot.

### Version & Environment

Client Version: 
1.12.1

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-classic/tree/f40070f6309d41d07d48a074dcacb2c33642ab2c

Database Repo & Commit Hash: 
https://github.com/cmangos/classic-db/tree/97b49fadbac513cbe1274199618ebe86be41786d

Operating System: 
Windows 10.0.18363

### Steps to reproduce
1. Join a group.
2. Ensure group loot is on.
3. Attempt to fish from a pool more than once.

### Crashlog

- None

**Comment by TarasHots** [comment]
@codestothestars I wasn't able to reproduce with current latest changes. Added to group with group loot and just fishing in those fishing pools. Looks to be fixed. Or maybe there are some details?

**Comment by codestothestars** [comment]
I was just able to reproduce it on the latest commit.

```
Using commit hash(fa7fd131d88906a2abacae1a32d6f54329021093) committed on 2020-05-11T23:52:38+02:00
```

Perhaps it is only certain pools, but I'm fishing from the one in Auberdine at `.go xyz 6514.420898 816.962830 7.057332 1`. To be clear on the group loot thing, the party member must be within range to get a turn at loot.

**Comment by TarasHots** [comment]
@codestothestars thank you for details. Reproduced in Ratchet

**Comment by cyberium** [comment]
Should be fixed with the PR above.
