### ISSUE TITLE
[Bug Report] Battered Chest loot

### ISSUE THREAD

**Issue by schell244** [cmangos/issues#2076]
Loots tables of "Battered Chest" are incorrect, according to https://classic.wowhead.com/object=2843/battered-chest

Object-ID: 2843
Loot-Entry: 2265

**Client version**: 
1.12.1

**Commit hash**: 
CMaNGOS Repo & Commit Hash: Classic, Latest

**Database version**: 
CMaNGOS Repo & Commit Hash: Classic DB, Latest

**Operating system**: 
Win 10

**Comment by schell244** [comment]
To be more precise: 
There are 2 types of "Battered Chests" objects:

object=2843 (level 1-5 loot) 
https://classic.wowhead.com/object=2843/battered-chest

object=106318 (level 5-10 loot)
 https://classic.wowhead.com/object=106318/battered-chest#contains:50-19+1

Currently, object=2843 holds wrong loot (level 5-10 loot), while object=106318 has no loot items set at all.

TODO:
1) Change loot tabels from object=2843 to hold only low level loot.
2) Implement loot for object=106318

**Comment by jimmybrancaccio** [comment]
@schell244 Please provide **all** of the requested information in the bug report template.

**Comment by schell244** [comment]
Issue is closed with:
https://github.com/cmangos/classic-db/commit/474fb08e60359c0a6909fc3249d778e9b68d5bd9
