### ISSUE TITLE
🐛 [Bug Report] - Battered Chest - spawn points

### ISSUE THREAD

**Issue by schell244** [cmangos/issues#2077]
## 🐛 Bugreport

Missing spawns of Battered Chest, objectID: 2843

Current Battered Chest spawn points don't cover all points mentioned at:
https://classic.wowhead.com/object=2843/battered-chest#screenshots

TODO:
Implement more spawn points and add spawns to pooling system.
(My suggestion would be maximum of 2 spawns at the same time in each start area,
one spawn in a cave, the other spawn somwhere outside)

Client Version: 
1.12.1

CMaNGOS Repo & Commit Hash: Classic, Latest

Operating System: 
Win10

**Comment by schell244** [comment]
There are two types of "Battered Chests"
object=2843 -> level 1-5
object=106318 -> level 5-10 
spawns should be set according to:
https://classic.wowhead.com/object=2843/battered-chest
https://classic.wowhead.com/object=106318/battered-chest#contains:50-19+1

**Comment by jimmybrancaccio** [comment]
@schell244 Please provide **all** of the requested information in the bug report template.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/2230752558dba612cfaeef72cb0f4f202114f7d7
