### ISSUE TITLE
🐛 [Bug Report] Can not share quests with party members

### ISSUE THREAD

**Issue by kelbren** [cmangos/issues#2079]
### Expected behavior
Share quest with group

### Version & Environment
 "2.4.3" (TBC)

Client Version: 
  - [TBC]

cMaNGOS Repo & Commit Hash: 
Safeguard CMSG_PUSHQUESTTOPARTY by checking that the player has the quest

### Steps to reproduce
1. group 
2. try to share quest.
3. no response.
### Crashlog
- None

**Comment by killerwife** [comment]
Will fix later this week along with other export issues. If not, vigorously ping me to oblivion on discord.

**Comment by killerwife** [comment]
This should be already addressed.
