### ISSUE TITLE
🐛 [Bug Report] mangos-tbc new installation Table 'tbcmangos.db_script_string' doesn't exist

### ISSUE THREAD

**Issue by left3721** [cmangos/issues#2080]
OS: Ubunt18.04
Database: Mysql** 5.7.28

mysql -uroot -p tbcmangos < mangos.sql 

ERROR 1146 (42S02) at line 1506: Table 'tbcmangos.db_script_string' doesn't exist

**Comment by Valkirie** [comment]
There is indeed an issue with the mangos.sql file. It contains several errors:
- db_script_string table is called differently across the file (dbscript_string)
- DROP TABLE IF EXISTS `game_event_time`; instruction is missing.
- `option_broadcast_text` INT(11) NOT NULL DEFAULT '0' is missing a comma
- `box_broadcast_text` INT(11) NOT NULL is missing a comma
- INSERT INTO `gossip_menu_option` VALUES is missing two columns

**Comment by berserkingyadis** [comment]
Still an issue, just replicated. This is currently blocking people from using this core :(

**Comment by left3721** [comment]
I use heidsql to import mangos.sql, and then use installfulldb.sh under TBC dB, installfulldb.config to configure core_path = ".. / mangos", and start mangos TBC

**Comment by killerwife** [comment]
The reason why I technically miss these is that if you use tbc-db install script properly, they do not hinder you at all. Nonetheless, I am fixing it.
