### ISSUE TITLE
🐛 [Bug Report] Downranked spell auras still return incorrect actualDamage

### ISSUE THREAD

**Issue by Valkirie** [cmangos/issues#2081]
## 🐛 Bugreport
When downranked, spell auras will keep the original actualDamage value (m_modifier.m_baseAmount). While ingame tooltip shows the proper spell applied to lower level character, damage/value dealt by that spell remains similar to original casted spell rank.

[See picture](https://i.ibb.co/0KJPwfY/Sans-titre.png)

### Expected behavior
actualDamage value has to be downranked similarly to actualBasePoints.

### Version & Environment
"2.4.3" (TBC)
Client Version: 2.4.3 (8606)

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/tree/d5cb3780b2e06a5a6ca3d6eb5793ffa9abd61710

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/476329b388f6a33b9ec7d475f5af3f536752fda9

### Steps to reproduce
1. Level 70 character to cast Retribution Aura Rank 6 on level 10 party member (gets Rank 1 applied).
2. Level 10 character to be hit by a creature.
3. See the "Does 5 Holy damage" downranked tooltip displayed.
4. See the 39 damage dealt to the creature.

### Crashlog
- None

**Comment by killerwife** [comment]
You see, those tooltips, we do not influence them in any way. Client calculates it all on its own.

**Comment by Valkirie** [comment]
`// recalculate basepoints for lower rank (all AreaAura spell not use custom basepoints?)
if (actualSpellInfo != GetSpellProto())
actualBasePoints = actualDamage = actualSpellInfo->CalculateSimpleValue(m_effIndex);`

Fixed it. But dunno if proper...

**Comment by killerwife** [comment]
No, but very close. Pushing fix :)

**Comment by Valkirie** [comment]
Great. Looking forward to your fix to figure out what should have been the proper approach.
