### ISSUE TITLE
🐛 [Bug Report] Fight for Warsong Gulch - double trouble

### ISSUE THREAD

**Issue by Daedalus-code** [cmangos/issues#2082]
## 🐛 Bugreport
Darnassus Alliance Brigadier General has the same quest twice with different reward.

![Screen Shot 2020-01-09 at 6 15 25 PM](https://user-images.githubusercontent.com/59256533/72089502-72fc8f80-330c-11ea-893a-02da32a56d60.png)

Different reward also:

![Screen Shot 2020-01-09 at 6 15 22 PM](https://user-images.githubusercontent.com/59256533/72089606-a63f1e80-330c-11ea-96d9-6bebad079541.png)
![Screen Shot 2020-01-09 at 6 15 18 PM](https://user-images.githubusercontent.com/59256533/72089631-accd9600-330c-11ea-9389-165b8c0082ae.png)

### Expected behavior

Should not be double trouble I suppose.

### Version & Environment

Client Version: 
  - "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: 

- [CLASSIC](https://github.com/cmangos/mangos-classic/tree/0f8571da4c1a7b8dd9f68a6f659373a3669000c5)

Database Repo & Commit Hash: 

- [CLASSIC](https://github.com/cmangos/classic-db/tree/e8d26b0e7dcf8608844641e6e8ea18d9517b5bb0)

Operating System: 

  - Linux Flavor

### Steps to reproduce
1. Go to Darnassus and talk to Alliance Brigadier General.
2. Be amazed.
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by Orcman2019** [comment]
https://classic.wowhead.com/npc=15351/alliance-brigadier-general#starts

Looks like each tier is supposed to have 2 quests until 60

**Comment by Daedalus-code** [comment]
I stand corrected, thanks.

**Comment by Orcman2019** [comment]
I think it is doing similar near Hammerfall for the Arathi Basin quests, seems like depending on level the same quest is showing up with different rewards?

![ab_a](https://user-images.githubusercontent.com/58348159/72308074-41036a00-3639-11ea-9ba6-68a2fd6dff4c.jpg)
![ab_b](https://user-images.githubusercontent.com/58348159/72308075-41036a00-3639-11ea-8524-809d00f2cea3.jpg)
![ab_c](https://user-images.githubusercontent.com/58348159/72308077-41036a00-3639-11ea-8acd-dc7742b932c4.jpg)
![ab_d](https://user-images.githubusercontent.com/58348159/72308080-41036a00-3639-11ea-8854-c394ea7aff98.jpg)

**Comment by Daedalus-code** [comment]
Double trouble not correct? 👀🤔

**Comment by Tobschinski** [comment]
Nope, needs to be fixed.

**Comment by Daedalus-code** [comment]
![morethanddoubletroubleOO](https://user-images.githubusercontent.com/59256533/72690009-15d8b900-3b18-11ea-9736-320a161ef82d.png)
