### ISSUE TITLE
🐛 [Bug Report] Orb of Translocation in Silvermoon teleports to Twisting Nether outside Stair of Destiny

### ISSUE THREAD

**Issue by Orcman2019** [cmangos/issues#2083]
## 🐛 Bugreport
Should normally be able to teleport between UC and Silvermoon with the orbs.

Orb of Translocation in Undercity works normally
Orb of Translocation in Silvermoon leads to 'Twisting Nether' by the Stair of Destiny (fall to death)

### Version & Environment
3.3.5a (WOTLK)
Server Build: [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/68d7959b52c785d2dc52dd3ab8d3737778a6303e
DB: [WOTLK](https://github.com/cmangos/wotlk-db/tree/29b9b88a487f78f19b45b51c110a3a63bf608818 (applied some of the changes today but not all of them)
OS Linux Mint 19.2

## Steps to Reproduce:
1. Create Undead (or anything Horde)
2. .tele to UC
3. Use Orb of Translocation to get to Silvermoon, works fine :)
4. Use Orb of Translocation in Silvermoon to end up in empty space (aauugh dead).

![translocate_a](https://user-images.githubusercontent.com/58348159/72122229-697a2400-331a-11ea-965a-8dc14e7a0332.jpg)

![translocate_b](https://user-images.githubusercontent.com/58348159/72122227-697a2400-331a-11ea-9d08-6362334f6978.jpg)

![translocate_c](https://user-images.githubusercontent.com/58348159/72122230-697a2400-331a-11ea-8c27-6eefb8c3cc01.jpg)

![translocate_d](https://user-images.githubusercontent.com/58348159/72122225-697a2400-331a-11ea-8779-f415f9a6aa3c.jpg)

**Comment by killerwife** [comment]
Fixed by https://github.com/cmangos/mangos-wotlk/commit/f4097f6b5b51bea96eea72838166f1124759c560
