### ISSUE TITLE
🐛 [Bug Report]Lordaeron Citizen should be invisible

### ISSUE THREAD

**Issue by Orcman2019** [cmangos/issues#2084]
## 🐛 Bugreport
In UC courtyard there are a bunch of Lordaeron Citizen ghosts that should only show up with warlock's detect invisibility ability or paladin's sense undead ability.

https://classic.wowhead.com/npc=3617/lordaeron-citizen#comments

### Version & Environment
3.3.5a (WOTLK)
server f4097f6b5b51bea96eea72838166f1124759c560
db ec97e726cd9babf8a83b93eb347dd4296b131fb4
Linux Mint 19.2

### Steps to reproduce
1. UC courtyard

![ghosts](https://user-images.githubusercontent.com/58348159/72192413-e4971500-33c2-11ea-99cc-00359c4944fa.jpg)

**Comment by Grz3s** [comment]
wotlk DB issues pls report: (creatures/objects/quests/events/waypoints etc)
https://github.com/cmangos/wotlk-db/issues
