### ISSUE TITLE
💬 [Support Request] [A] You have: --> z2746 - [B] You need: --> `z2745 ?

### ISSUE THREAD

**Issue by Daedalus-code** [cmangos/issues#2087]
## 💬 Support Request

I tried to apply updates from folder sql/updates - nothing, complains about duplicates.
There are several threads about this common issue.
I still don't grasp anything with this issue tho, confusing.

### Version & Environment

Client Version: 
  - "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash:  
  - [CLASSIC](https://github.com/cmangos/mangos-classic/tree/992e0902a6cfe35b6b7162523740cad886183c09)

Database Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/classic-db/tree/71d750dad5c0fd930ea9627d8346aefa14f3d356)

Operating System: 
  - Linux Flavor
### Steps to reproduce
1. git pull latest from db and core
2. apply updates
3. " I need to downgrade ? "
4. ...
5. No gaming, just debugging..

```
2020-01-14 13:11:30 ERROR:query ERROR: Unknown column 'required_z2745_01_mangos_game_event_split' in 'field list'
2020-01-14 13:11:30 ERROR:The table `db_version` in your [WORLD] database indicates that this database is out of date!
2020-01-14 13:11:30 ERROR:
2020-01-14 13:11:30 ERROR:  [A] You have: --> `z2746_01_mangos_world_safe_locs_facing.sql`
2020-01-14 13:11:30 ERROR:
2020-01-14 13:11:30 ERROR:  [B] You need: --> `z2745_01_mangos_game_event_split.sql`
2020-01-14 13:11:30 ERROR:
2020-01-14 13:11:30 ERROR:You must apply all updates after [A] to [B] to use mangos with this database.
2020-01-14 13:11:30 ERROR:These updates are included in the sql/updates folder.
2020-01-14 13:11:30 ERROR:Please read the included [README] in sql/updates for instructions on updating.
```

**Comment by Daedalus-code** [comment]
README from update folders tells me nothing really.

```
This folder contains SQL files which will apply required updates to your MySQL
database, whenever the CMaNGOS database structure has been changed or extended.

After applying an update the DB is compatible with the CMaNGOS revision of this sql update.
SQL updates include special protection against multiple and wrong order of update application.
```
Found this "explanation" : 

ERROR: [A] You have: --> [your current version]
ERROR: [B] You need: --> [the most recent version]

Still at loss here.

**Comment by Daedalus-code** [comment]
/base/mangos.sql

ERROR 1136 (21S01) at line 324: Column count doesn't match value count at row 1

**Comment by cala** [comment]
Looks like you updated your database without updating your core to latest version.

**Comment by Daedalus-code** [comment]
Yeah it tells me that but I did compile new core and update database.
Did a fresh install of classic-db with git clone but still same.
Compiled the core.

Not sure why this is a thing...

**Comment by Daedalus-code** [comment]
[A] You have: --> `z2746_01

[B] You need: --> `z2745_01

The core is lagging?

There must be a better way updating this, why this common failure is a thing and not fixed is mind boggling .

**Comment by Daedalus-code** [comment]
[the most recent version]" is below [your current version] ?

Not sure whats going on.

**Comment by cala** [comment]
> [A] You have: --> `z2746_01
>
> [B] You need: --> `z2745_01

This means:
- your database has revision: z2746 which is the actual code revision supported by the database since commit https://github.com/cmangos/classic-db/commit/14e169b98d5608e09eb16beca1aab57b911eba28
- your core has revision z2745 which is outdated because our core is revision z2746 since commit https://github.com/cmangos/mangos-classic/commit/2e82f8a9b7e2884d7bbcbf13acdccd0e9259a28b

I can start without error a core compiled from latest sources using latest DB, so they seem to be in sync. Which suggests that your core is probably outdated. There might be another reason, but this one looks the most probable.

> I tried to apply updates from folder sql/updates - nothing, complains about duplicates.

You should not apply sql updates by yourself unless you know what you are doing. DB install script takes care of this for you once you've provided it with the path to your core source directory.

**Comment by Daedalus-code** [comment]
Me trying to apply "updates" are after everything is installed clean.

**Comment by Daedalus-code** [comment]
**Initialize Mangos database**

mysql -uroot -p classicmangos < mangos/sql/base/mangos.sql = ERROR 1136

**Comment by Daedalus-code** [comment]
My bad, all of it !

So sorry.
Everything got installed directly into the /run directory not in /home/ubuntu/wow/mangos-classic/run  
Was able to see that with the virtualbox - ubuntu when the folder was never made after make install.

Im running a bash script, my bad and Im so sorry again.

```
sudo find / -name offmesh.txt
```
Showed me where it was installed wrong...so I moved those to mangos-classic/run and it runs now.
