### ISSUE TITLE
looting locked chests

### ISSUE THREAD

**Issue by Azelen** [cmangos/issues#209]
hi, there is a problem with looting chests that require a key to open, when open it - no loot window will appear, it will immediately close instead. they can be looted only with autoloot option.

**Comment by cyberium** [comment]
must be fixed

**Comment by Arnibou** [comment]
On the last rev. TBC with DB TBC, it still doesn't work even with the new loot system. In the log, the server sending out the loot to the player but the window doesn't open and the trunk  closes as soon.
