### ISSUE TITLE
🐛 [Bug Report] Not able to kill 'sickly deer' anymore but my pet can kill them.

### ISSUE THREAD

**Issue by Daedalus-code** [cmangos/issues#2092]
## 🐛 Bugreport

I was able to kill them before, I remember I 'Arcane Shot' them all the time.
![Screen Shot 2020-01-18 at 12 54 43 AM](https://user-images.githubusercontent.com/59256533/72653883-5fe16380-398d-11ea-93b0-921e4700b1d2.png)
Now my hunter is just animating shots with sounds (not sure if arrows disappears tho)
![Screen Shot 2020-01-18 at 12 54 56 AM](https://user-images.githubusercontent.com/59256533/72653944-a59e2c00-398d-11ea-9874-6ef86b17242e.png)
My pet takes them down first hit, while I still shoot at it.
![Screen Shot 2020-01-18 at 12 55 13 AM](https://user-images.githubusercontent.com/59256533/72653966-bc448300-398d-11ea-9ae3-dd03152d6c5c.png)

### Expected behavior

They should fall down dead by my arrows (skinning them works when they dead) 
### Version & Environment

Client Version: 
  - "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/mangos-classic/tree/68556568285cc90ac6897e236365d286bb6bff87)

Database Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/classic-db/tree/65c04d32cfb86a937138313f0d622f1ef20d9b70)

Operating System: 
  - Linux Flavor
### Steps to reproduce
1. Log in
2. Try to kill a sickly deer around Darkshore
3. demand my pet do the job..
4. ...skinning wondering if I need sleep..
5. Profit

### Crashlog

- None

**Comment by killerwife** [comment]
There was some code that was related to this and wasn't making much sense and I kept it inside cos I do not know all the nuances. I might check it out if someone doesnt beat me to it.

**Comment by Daedalus-code** [comment]
![Screen Shot 2020-01-18 at 1 06 10 AM](https://user-images.githubusercontent.com/59256533/72654209-dcc10d00-398e-11ea-9842-ce693aaea7e0.png)

other server I was able to kill it melee , maybe it's ranged will test more

**Comment by Daedalus-code** [comment]
Damn you fast.

**Comment by killerwife** [comment]
I realized where the issue was and I fixed it. Do recheck though.

**Comment by Daedalus-code** [comment]
Thank you so much (: 

![Screen Shot 2020-01-18 at 1 23 32 AM](https://user-images.githubusercontent.com/59256533/72654759-3cb8b300-3991-11ea-854a-9db6f72a47c6.png)
