### ISSUE TITLE
🐛 [Bug Report] WotLK Is Segfaulting @ 1497cc1

### ISSUE THREAD

**Issue by jimmybrancaccio** [cmangos/issues#2096]
## 🐛 Bugreport

I've compiled a fresh build on the WotLK today but it seems to segfault:

https://paste.linuxbox.ninja/paste/58

### Expected behavior

No segfaults please.

### Version & Environment

Client Version: 3.3.5a

CMaNGOS Repo & Commit Hash: 1497cc1d82516a39904b0762b7a709310d91210f

Database Repo & Commit Hash: 6f9374206ac7d78e15335964fe29f67f3e8f49a0

Operating System: Ubuntu 19.10

### Steps to reproduce

1. Fetch the code at the above commit id.
2. I use this as my cmake - `cmake ../mangos -DCMAKE_INSTALL_PREFIX=\../mangos/run -DPCH=1 -DDEBUG=1 -DBUILD_PLAYERBOT=ON -DBUILD_EXTRACTORS=ON`
3. `make && make install`
4. One installed, run `./mangosd`. You may need to wait a little. It seemed to happen within 5-10 minutes for me. Of note, no players are on the realm. I actually only have `mangosd` running, not even `realmd`.
5. Profit

### Crashlog

- https://paste.linuxbox.ninja/paste/58

```
(gdb) info threads
  Id   Target Id                                   Frame 
  1    Thread 0x7ffff6ffc740 (LWP 24704) "mangosd" 0x00007ffff7faf9f5 in __GI___nanosleep (requested_time=0x7fffffffe630, 
    remaining=0x7fffffffe630) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  2    Thread 0x7ffff6f7b700 (LWP 24720) "mangosd" 0x00007ffff7faf9f5 in __GI___nanosleep (requested_time=0x7ffff6f7ad30, 
    remaining=0x7ffff6f7ad30) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  3    Thread 0x7ffff677a700 (LWP 24721) "mangosd" 0x00007ffff7faf9f5 in __GI___nanosleep (requested_time=0x7ffff6779d30, 
    remaining=0x7ffff6779d30) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  4    Thread 0x7ffff5f79700 (LWP 24723) "mangosd" 0x00007ffff7faf9f5 in __GI___nanosleep (requested_time=0x7ffff5f78d30, 
    remaining=0x7ffff5f78d30) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
* 9    Thread 0x7fffe2585700 (LWP 24736) "mangosd" 0x000055555612c619 in std::__cxx11::list<Aura*, std::allocator<Aura*> >::begin (
    this=0x2048) at /usr/include/c++/9/bits/stl_list.h:951
  10   Thread 0x7fffe2d86700 (LWP 24737) "mangosd" 0x00007ffff7faf9f5 in __GI___nanosleep (requested_time=0x7fffe2d85bc0, 
    remaining=0x7fffe2d85bc0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  11   Thread 0x7fffe3587700 (LWP 24739) "mangosd" 0x00007ffff71bb65e in epoll_wait (epfd=19, events=0x7fffe3586670, maxevents=128, 
    timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  12   Thread 0x7ffff5564700 (LWP 24740) "mangosd" 0x00007ffff71bb65e in epoll_wait (epfd=15, events=0x7ffff5563660, maxevents=128, 
    timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
```

**Comment by Orcman2019** [comment]
Seeing the same thing, nothing unusual in the logs before it is crashing.

**Comment by Orcman2019** [comment]
> Grz3s commented 3 hours ago 
> can you pls check with this?:
> UPDATE creature_template SET extraFlags=extraFlags&~4096;
> you may receive some errors ...but thats not important ... just check if server still crashes

Ran it about 2 hours now, no crashing.

**Comment by killerwife** [comment]
Should be now fixed.
