### ISSUE TITLE
🐛 [Bug Report] ERROR WorldSocket ProcessIncomingData client sent malformed packet size

### ISSUE THREAD

**Issue by Daedalus-code** [cmangos/issues#2098]
## 🐛 Bugreport

Not sure what this is, can't remember seeing this.  

2020-01-21 17:08:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
**2020-01-21 17:17:23 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 1025 , cmd = 2109479168**
2020-01-21 17:28:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.
2020-01-21 17:38:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
2020-01-21 19:01:01 GameEvent 1024 "Hourly Bells" removed.
2020-01-21 19:08:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
**2020-01-21 19:15:23 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18245 , cmd = 539959380**  

2020-01-22 02:01:01 GameEvent 1024 "Hourly Bells" removed.
2020-01-22 02:08:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
2020-01-22 02:15:33 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18245 , cmd = 539959380
**2020-01-22 02:15:37 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 5635 , cmd = 16777729**
2020-01-22 02:28:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.
2020-01-22 02:38:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.  

2020-01-22 15:28:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.
2020-01-22 15:38:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
**2020-01-22 15:55:59 ERROR:Socket::Open() failed to get remote address.  Error: remote_endpoint: Transport endpoint is not connected
2020-01-22 15:55:59 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18501 , cmd = 790643777**

### Expected behavior

Error is Error.

### Version & Environment

Client Version: 
  - "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/mangos-classic/tree/9d7b13a0c0a8fc3678a6e6f2c5cecf37575b85d2)

Database Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/classic-db/tree/4a299e914100f9ff118e86802bd4775abb2c5cab)

Operating System: 
  - Linux Flavor - Raspberry Pi 4 - Ubuntu 19.10 Server
### Steps to reproduce
1. Start server yesterday.
2. Check logs today.
3. hm
4. ...
5. Profit

### Crashlog

- None
Server still running.

**Comment by Daedalus-code** [comment]
Joined the server and killed some sickly ones and this was the only new logs that showed up.

```
2020-01-22 18:08:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
2020-01-22 18:22:19 ERROR:Subcommand 'note' of command 'ban' have less access level (2) that parent (3)
2020-01-22 18:22:19 ERROR:Subcommand 'warn' of command 'ban' have less access level (2) that parent (3)
2020-01-22 18:22:19 ERROR:Table `command` have command '' that only used with some subcommand selection, it can't have help or overwritten access level, skip.
2020-01-22 18:22:19 ERROR:Table `command` have nonexistent command 'movegens', skip.
```

**Comment by killerwife** [comment]
Second problem is just related to wrong data in chat tables in core. Its not critical and I will fix it eventually. The first problem however is serious and I do not know where to start. Does it happen every time?

**Comment by Daedalus-code** [comment]
[Server.log](https://github.com/cmangos/issues/files/4099113/Server.log)

I will restart server and look now

**Comment by Daedalus-code** [comment]
Reboot and looking at it now...time will tell 👀 

```
2020-01-22 19:52:37 Loading WorldState
2020-01-22 19:52:37 
2020-01-22 19:52:37 ---------------------------------------
2020-01-22 19:52:37       CMANGOS: World initialized       
2020-01-22 19:52:37 ---------------------------------------
2020-01-22 19:52:37 
2020-01-22 19:52:37 SERVER STARTUP TIME: 0 minutes 38 seconds
2020-01-22 19:52:37 
2020-01-22 19:52:37 
2020-01-22 19:52:37 Starting up anti-freeze thread (10 seconds max stuck time)...
```

**Comment by Daedalus-code** [comment]
No WorldSocket but joined with the < GM > and took a boat.


2020-01-22 23:38:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
2020-01-22 23:58:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.
2020-01-22 23:59:53 ERROR:Subcommand 'note' of command 'ban' have less access level (2) that parent (3)
2020-01-22 23:59:53 ERROR:Subcommand 'warn' of command 'ban' have less access level (2) that parent (3)
2020-01-22 23:59:53 ERROR:Table `command` have command '' that only used with some subcommand selection, it can't have help or overwritten access level, skip.
2020-01-22 23:59:53 ERROR:Table `command` have nonexistent command 'movegens', skip.
2020-01-23 00:00:01 GameEvent 16 "Gurubashi Arena Booty Run" started.
2020-01-23 00:00:01 GameEvent 31 "Edge of Madness, Renataki" removed.
2020-01-23 00:00:01 GameEvent 1024 "Hourly Bells" started.
**2020-01-23 00:00:20 ERROR:Delayed Zone Update: Client sent invalid zoneId for X,Y & MAP Coordinates. GUID: 16 zoneId: 1537 Expected 1, Coords: -5026.169434 -833.473083 495.319305**
2020-01-23 00:01:01 GameEvent 1024 "Hourly Bells" removed.


Not seen Delayed Zone Update before either.

```
ERROR:Delayed Zone Update: Client sent invalid zoneId for X,Y & MAP Coordinates. GUID: 16 zoneId: 1537 Expected 1, Coords: -5026.169434 -833.473083 495.319305
2020-01-23 00:01:01 
```

Im not falling off the boat anymore tho, thats kewl.

**Comment by Daedalus-code** [comment]
It came back 👀 
[Server.log](https://github.com/cmangos/issues/files/4101136/Server.log)



2020-01-23 01:08:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
2020-01-23 01:28:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.
2020-01-23 01:38:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
2020-01-23 01:58:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.
2020-01-23 02:00:01 GameEvent 16 "Gurubashi Arena Booty Run" removed.
2020-01-23 02:00:01 GameEvent 1024 "Hourly Bells" started.
2020-01-23 02:01:01 GameEvent 1024 "Hourly Bells" removed.
2020-01-23 02:08:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
2020-01-23 02:28:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.
2020-01-23 02:38:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
2020-01-23 02:58:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.
2020-01-23 03:00:01 GameEvent 16 "Gurubashi Arena Booty Run" started.
2020-01-23 03:00:01 GameEvent 1024 "Hourly Bells" started.
2020-01-23 03:01:01 GameEvent 1024 "Hourly Bells" removed.
2020-01-23 03:08:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
2020-01-23 03:28:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.
2020-01-23 03:38:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
**2020-01-23 03:46:22 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18245 , cmd = 539959380
2020-01-23 03:46:23 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18245 , cmd = 539959380**
2020-01-23 03:58:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.
2020-01-23 04:00:01 GameEvent 1024 "Hourly Bells" started.
2020-01-23 04:01:01 GameEvent 1024 "Hourly Bells" removed.
2020-01-23 04:08:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.

**Comment by Daedalus-code** [comment]
10 hours later, nothing. hm

**Comment by Daedalus-code** [comment]
2020-01-23 13:28:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.
2020-01-23 13:36:10 ERROR:Socket::Open() failed to get remote address.  Error: remote_endpoint: Transport endp>
**2020-01-23 13:36:11 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18501 , cmd = >**
2020-01-23 13:38:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
2020-01-23 13:58:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.


I see this when Im working on the Raspberry that runs mangos and realmd ..
I do parse a lot of txt back and forth through terminal to debug my cmangos-script.
It occurs around that time when I do this, could be or it could just be me..

Not sure what else it could be... my VirtualBox ssh died on me (wrong pw regardless,host+clients...) so thats why my Pi4 is getting abused while it runs the server.

**Comment by cyberium** [comment]
@killerwife iam not sure this is related with recent multithread changes.
I encoutered them already under some specific case.
I was not able to identify exactly the cause but its related to the socket not able to handle received data correctly when cpu is in heavy use.
It might be related to socket unable to separate each opcode datas (more than one is processed at a time)
Our current implementation of boost asio is not perfect. I wonder if its not a good idea to sync our code with trinity if its better (didn't look at it yet)

**Comment by Daedalus-code** [comment]
Finally got logged back into my Ubuntu 64bit server through host.. logs looks clean after 10hours:27minutes..

I have only seen this error in my Pi4 logs so far

**Comment by killerwife** [comment]
@cyberium the netcode part you are talking about is thread safe from what I know

**Comment by cyberium** [comment]
Yes i think so too. It doesn't mean it work as it should in those case ;)

**Comment by Laizerox** [comment]
I will give my input on this issue. When client gets disconnected from a server (crash or network loss) it will cache all outgoing packets. When server comes back online or network restores it will try to send its cached buffer after login to server.

I'm not sure if my theory is right, but this is when I have noticed it to occur. Its purely client related and we cannot do anything about it.

**Comment by evil-at-wow** [comment]
You seem to have it ever now and then @Daedalus-code. Could you try with ```MapUpdate.Threads``` set to 1 in your config? If that doesn't help then we can at least rule out the recent multi-threading changes Cyberium was referring to.

I'm aware of a similar problem that's been introduced when we moved to asio, but that is on the sending side, not the incoming side (so we can send the client malformed packets). I discovered it last year and I've slowly started working on a fix after my multi-threading fixes part 1 PR cmangos/mangos-tbc#333 (I admit Classic has been a distraction). 

That issue is basically data races because packet processing code that's not thread-safe is being used from multiple threads anyway (I can't explain the gory details in just a few lines, so I'll not do that here). So just maybe there's something else lurking there as well?

**Comment by Daedalus-code** [comment]
Done, restarting now.

**Comment by Yatzii93** [comment]
I have experiencing issues with the map multi-threading which lead me to revert. I didn't report it considering I was missing this commit https://github.com/cmangos/mangos-tbc/commit/e540632823e3c56d074c43bd85cb6bf41509311d

Basically what was happening is people were going into a map that I assume wasn't loaded in memory and the result was their client not recieveing updates or sending them (not quite sure). Client side they could run around but nothing new would load like npcs appearing etc or being able to cast spells. Server-side they would just be standing still. Required them to relog. Restarting the client without logging out properly from the world didn't seem to fix the issue.

But ye I wanted to test again with the config setting inplace to see if it made a difference.

**Comment by Daedalus-code** [comment]
I have not seen that error since I turned threads down to 1 from 3.

Still looking

**Comment by Daedalus-code** [comment]
I had also a old mangos.conf file from 2019, does that do anything to make it unstable?
I took the new one and edited my info and overwrite the old config file, started the server and totally forgot about the 3 threads setting and it is still running with no errors 👀 

The old mangos.conf I just added the new changes when I saw them.

**Comment by Daedalus-code** [comment]
```
2020-01-25 07:38:21 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18245 , cmd = 791617620
```

yeah it's back.
Turning it off.

**Comment by Daedalus-code** [comment]
```
2020-01-26 07:58:47 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18245 , cmd = 791617620
```  
with:
```
MapUpdate.Threads = 1 
```

**Comment by Daedalus-code** [comment]
I have not seen the error since the change into:
```
MapUpdate.Threads = -1
```

From mangosd.conf:  

"Don't put more thread then your number of CPU " **threads -1** " for this to work stable."

**Comment by Yatzii93** [comment]
How many cores does your CPU have? Including virtual. @Daedalus-code

**Comment by Daedalus-code** [comment]
CPU – Broadcom BCM2711, Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.5GHz.

**Comment by Yatzii93** [comment]
ok definitly more than one 😆

**Comment by Daedalus-code** [comment]
"MapUpdate.Threads = 3" 
Would be fun? :D hehe

**Comment by Yatzii93** [comment]
I want to try again with the config but I'm in conflict with the fact that I never really go above 20% CPU power on my VM and I don't want to cause issue for my players. Been having a bit of a meh with client crashes lately.

**Comment by Daedalus-code** [comment]
I run two servers: one legit with few restarts/updates etc..

and one I stress test with... but the ERROR came from the legit server... xP

**Comment by Yatzii93** [comment]
DId you notice any ingame issues though? As I said before I was getting werid issues when people were zoning in maps. Like at one point the whole of the eastern kingdoms was kinda of bugged out. Going through a portal to SW would either do nothing, or you'd zone in and not get any client updates until doing a proper relog. (client updates as in, nothing would load in like npcs and server side you'd be standing still)

**Comment by Daedalus-code** [comment]
I will look into that and post if I see any.
Checked the logs while this is happening?

**Comment by Yatzii93** [comment]
No unfortunatly my live envirument doesnt have much active logging, only crash logging. Dont have the luxary of SSD's so I keep the disk writing as minimal as possible so it's clear for the database writes.

**Comment by Daedalus-code** [comment]
These do pop up on a clean build and a restart.

![CanCrashClient](https://user-images.githubusercontent.com/59256533/73276414-f103d600-41e8-11ea-8ac1-8c4bfcdeb917.png)

**Comment by Yatzii93** [comment]
I havent seen that warning specifically, but can easily fix that in the db.

**Comment by Daedalus-code** [comment]
Am no db expert so not sure what I need todo 🙈

**Comment by Daedalus-code** [comment]
```
2020-01-29 23:08:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
2020-01-29 23:24:34 ERROR:Socket::Open() failed to get remote address.  Error: remote_endpoint: Transport endpoint is not connected
2020-01-29 23:24:35 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18501 , cmd = 790643777
2020-01-29 23:28:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.
```
With " MapUpdate.Threads = -1  " 

latest:  
mangos-classic  
classic-db

Raspberry pi4

**Comment by Yatzii93** [comment]
Tbh I see though error warnings from time to time even without the multi-threading map. I'd wager they aren't related.

**Comment by Daedalus-code** [comment]
Could it be a faulty Pi ?

Not sure where to look 👀

**Comment by Laizerox** [comment]
> Could it be a faulty Pi ?
> 
> Not sure where to look 👀

I already posted where the issues potentially originates, please read again https://github.com/cmangos/issues/issues/2098#issuecomment-577813086

**Comment by Daedalus-code** [comment]
When no clients have played at all and it occurs?

**Comment by cyberium** [comment]
no client doesn't mean server socket didn't received something. Verify that there is not something on your network trying to use server port.
As my knowledge ProcessIncomingData have no way to be triggered without communication with server port.

**Comment by Daedalus-code** [comment]
Two servers at the same network using some port?

**Comment by Laizerox** [comment]
> Two servers at the same network using some port?

No it can be some arbitary client connecting to same port and sending data. It doesn't have to be specifically wow client. It can be ANYTHING.

**Comment by Daedalus-code** [comment]
```
2020-02-03 15:40:38 ERROR:MapUpdate.Threads (-1) can't be negative. Using 3 instead.
```

fascinating

**Comment by Daedalus-code** [comment]
```
│2020-02-12 09:00:01 GameEvent 16 "Gurubashi Arena Booty Run" started.                                                                           │
│2020-02-12 09:00:01 GameEvent 1024 "Hourly Bells" started.                                                                                      │
│2020-02-12 09:01:01 GameEvent 1024 "Hourly Bells" removed.                                                                                      │
│2020-02-12 09:08:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.                                                               │
│2020-02-12 09:22:49 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18245 , cmd = 539959380                         │
│2020-02-12 09:28:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.                                                               │
│2020-02-12 09:38:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.                                                               │
│2020-02-12 09:58:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started. 
```

The other realm has another port now (8086), but it still happened on the Pi that has port (8085)

**Comment by Warlockbugs** [comment]
Could it be a port scanner by someone or something similar?

**Comment by Daedalus-code** [comment]
```
│2020-02-16 08:00:01 GameEvent 1024 "Hourly Bells" started.                                                                                 │
│2020-02-16 08:01:01 GameEvent 1024 "Hourly Bells" removed.                                                                                 │
│2020-02-16 08:08:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.                                                          │
│2020-02-16 08:28:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.                                                          │
│2020-02-16 08:37:38 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18245 , cmd = 539959380                    │
│2020-02-16 08:38:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.                                                          │
│2020-02-16 08:58:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.                                                          │
│2020-02-16 09:00:01 GameEvent 16 "Gurubashi Arena Booty Run" started.
```  

Not sure why it is still happening, everyone is moving out and the internet is used rarely, no people here that even knows what a port scanner is.

My Pi is still spewing out malformed error.

**Comment by Daedalus-code** [comment]
```
2020-02-16 17:08:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
2020-02-16 17:17:16 ERROR:Socket::Open() failed to get remote address.  Error: remote_endpoint: Transport endpoint is not connected
2020-02-16 17:17:16 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18501 , cmd = 790643777
2020-02-16 17:28:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.
```

People are moving out of where I live, maybe it's the internet/intranet being disconnecting etc .. 
Only happens on the Raspberry Pi4.....I should compile on the Pi2 also...to see if I can replicate.

**Comment by Daedalus-code** [comment]
```
│2020-02-17 09:00:01 GameEvent 16 "Gurubashi Arena Booty Run" started.                                                                      │
│2020-02-17 09:00:01 GameEvent 1024 "Hourly Bells" started.                                                                                 │
│2020-02-17 09:01:01 GameEvent 1024 "Hourly Bells" removed.                                                                                 │
│2020-02-17 09:08:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.                                                          │
│2020-02-17 09:08:28 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18245 , cmd = 539959380                    │
│2020-02-17 09:08:29 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18245 , cmd = 1848582228                   │
│2020-02-17 09:08:29 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 19026 , cmd = 33573197                     │
│2020-02-17 09:08:35 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 20304 , cmd = 1313818964                   │
│2020-02-17 09:08:35 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 20304 , cmd = 1313818964                   │
│2020-02-17 09:08:35 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 32768 , cmd = 4268894208                   │
│2020-02-17 09:08:36 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 30 , cmd = 67072                           │
│2020-02-17 09:08:36 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 12 , cmd = 1048576                         │
│2020-02-17 09:08:36 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18501 , cmd = 168644684                    │
│2020-02-17 09:08:37 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 5635 , cmd = 22216704                      │
│2020-02-17 09:08:37 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 768 , cmd = 3760531968                     │
│2020-02-17 09:08:37 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 5635 , cmd = 23658496                      │
│2020-02-17 09:08:38 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 0 , cmd = 2171236608                       │
│2020-02-17 09:08:38 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 0 , cmd = 1409262592                       │
│2020-02-17 09:08:38 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 27648 , cmd = 11                           │
│2020-02-17 09:08:39 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 356 , cmd = 1969317477                     │
│2020-02-17 09:08:39 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 12420 , cmd = 754974720                    │
│2020-02-17 09:08:39 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 12300 , cmd = 1610678530                   │
│2020-02-17 09:08:40 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 20304 , cmd = 1313818964                   │
│2020-02-17 09:08:40 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 21582 , cmd = 282701                       │
│2020-02-17 09:08:41 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 768 , cmd = 3758492416                     │
│2020-02-17 09:08:41 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 17517 , cmd = 21604                        │
│2020-02-17 09:08:41 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 14848 , cmd = 3080192                      │
│2020-02-17 09:08:42 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 256 , cmd = 4207869184                     │
│2020-02-17 09:08:42 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 90 , cmd = 65536                           │
│2020-02-17 09:08:42 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 4609 , cmd = 13312                         │
│2020-02-17 09:08:43 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 3 , cmd = 256                              │
│2020-02-17 09:08:43 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 18249 , cmd = 86095                        │
│2020-02-17 09:08:43 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 20560 , cmd = 556418                       │
│2020-02-17 09:08:44 ERROR:WorldSocket::ProcessIncomingData: client sent malformed packet size = 32768 , cmd = 2400856064                   │
│2020-02-17 09:28:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.                                                          │
│2020-02-17 09:38:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.                                                          │
│2020-02-17 09:58:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.   
```

Big one 👀

**Comment by al3xc1985** [comment]
I believe this is a more of a hardware lumitation or bad configration of the sistem networking.

For examole we see ine limitation that occurs from that to time without disconnecting the server, but it has a 3-4/percent data loss.
https://www.raspberrypi.org/forums/viewtopic.php?t=229578

**Comment by al3xc1985** [comment]
You can also check your sistem error log to see what happends in the same moment with server segfault

**Comment by HerrTrigger** [comment]
Not sure if this contributes as info, but the 'client sent malformed ...' is an issue older then/running for over 10 years. Not sure if it was there when BC was still master, but surely when Wotlk became master I started noticing it. Was some info about it on the old forums - should these still be accessible somehow (?). It's very random though, and I have no idea how to exactly reproduce on the fly. I've never had a crash as a direct result though I think.

**Comment by Daedalus-code** [comment]
I have not seen this error for a long time, closing it.. for the time being.
Thanks for the responses (: 👍🏻
