### ISSUE TITLE
TBC Mage - Water Elemental cannot use 'Freeze' while casting 'Waterbolt'

### ISSUE THREAD

**Issue by cpinkus** [cmangos/issues#210]
Right now in cmangos-tbc the Water Elemental is unable to cast the ranged frost nova spell (Freeze) while casting the Waterbolt spell. The Freeze should be able to be cast by the Water Elemental while the Elemental is casting Waterbolts.

**Comment by Phatcat** [comment]
https://github.com/cmangos/mangos-tbc/commit/975cd80366dc8dfe7d58338aeecdfa8173a8110b
https://github.com/cmangos/mangos-wotlk/commit/8f4738e3d1b26ab46a4dbdd3c189f9263ee13b0d

**Comment by Phatcat** [comment]
Commits reverted, re-opening. Once again sorry. Most of all for the bloat and the notifications spam associated.

**Comment by cyberium** [comment]
should be ok now
