### ISSUE TITLE
[Bug Report] Zul' Farrak Instance

### ISSUE THREAD

**Issue by Orcman2019** [cmangos/issues#2101]
**Current behavior**: 
1. Gahz'rilla should require a quest item Mallet of Zul'Farrak to activate the gong, and he should then be attackable.
1.1 Something seems wrong with entry for Mallet of Zul'Farrak (image) it shows as a blue item with stats instead of a quest item.
1.2 Gong is usable even without the mallet, and either way Gahz'rilla is not attackable.

2. Sergeant Bly has dialog options after event but neither do anything (they show up but clicking does nothing), should turn hostile and drop quest item (Divino-matic Rod).

https://classic.wowhead.com/item=9240/mallet-of-zulfarrak#comments
https://classic.wowhead.com/npc=7273/gahzrilla
https://classic.wowhead.com/npc=7604/sergeant-bly

**Expected behavior**: 

1. Mallet should summon Gahz'rilla who can be attacked.

2. Sergeant Bly should turn hostile with dialog option asking about Divino-matic Rod.

**Steps to reproduce**:

1. Zul'Farrak instance
2. 

**Client version**: 
WOTLK3.35a
**Commit hash**: 
0f25acc14be82ba267e74ae69b58b4de41f52849
**Database version**: 
531621c6e1e310aa36d00c7692f6e3b8a564e9f6
**Operating system**: 
Linux Mint 19.2

![zf_a](https://user-images.githubusercontent.com/58348159/73129871-7c435880-3faa-11ea-80f4-607f88d840fe.jpg)
![zf_b](https://user-images.githubusercontent.com/58348159/73129872-7c435880-3faa-11ea-983e-94c62e91f697.jpg)

**Comment by shagu** [comment]
Regarding 1)
Not a bug. This looks like as it is supposed to be for Wotlk.

> Prior to patch 3.0.8, the Mallet of Zul'Farrak was not able to be equipped, and was useful only to summon Gahz'rilla. The Mallet is no longer required to summon Gahz'rilla and the dungeon can be completed without it - but it makes a useful weapon for enhancement shaman, and is easy to get at an early level with help. This item cannot be sold or disenchanted. 
[Source](https://wowwiki.fandom.com/wiki/Mallet_of_Zul%27Farrak)

**Comment by Grz3s** [comment]
fixed

**Comment by Orcman2019** [comment]
Strange I looked on wowhead at both the mallet and the mob and neither has any comments about it changing, and when you search for mallet there is no blue mallet match either, even as a removed item (?).

**Comment by Grz3s** [comment]
and you're not checking on "Classic Wowhead"? ... that would be strange to check 3.3.5 in classic....
anyway here pic from wowhead...
![lol](https://user-images.githubusercontent.com/2374069/73139719-d1de3a80-4068-11ea-8ee1-77acac209e62.jpg)

**Comment by Orcman2019** [comment]
Strange, if I go to wowhead directly and click it auto redirects to classic and the green item.. If its manually switched in the corner back it shows the blue item comments..

**Comment by Grz3s** [comment]
because in current ver ,,, item is not available anymore

**Comment by Orcman2019** [comment]
Tested it out, I can kill Gahz'rilla now, the quest/dialog for Sergeant Bly is still not doing anything.

![zf_e](https://user-images.githubusercontent.com/58348159/73419208-81224800-42db-11ea-953b-dcd4d29ff979.jpg)
![zf_f](https://user-images.githubusercontent.com/58348159/73419209-81224800-42db-11ea-860c-55ab99c7d23b.jpg)

**Comment by Grz3s** [comment]
@Orcman2019 thx again for report...
this should be fixed:
https://github.com/cmangos/wotlk-db/commit/20eb4347dae235396a776a16048e61b80dabc696

**Comment by Orcman2019** [comment]
Sweet looks like its working like a charm now.

![zf_g](https://user-images.githubusercontent.com/58348159/73512357-8c8e7580-43a6-11ea-9358-f55ad752c071.jpg)
