### ISSUE TITLE
🐛 [Classic] Lunar Festival Invitation won't teleport player to Moonglade

### ISSUE THREAD

**Issue by canidae** [cmangos/issues#2102]
## 🐛 Bugreport
Activating Lunar Festival Invitation (item ID 21711) within the Greater Moonlight will not teleport the player to Moonglade (from Stormwind).

### Expected behavior
Teleport player to Moonglade.

### Version & Environment
  - Client: "1.12.1" (CLASSIC)
  - Server: [CLASSIC](https://github.com/cmangos/mangos-classic/tree/3b3df96c90e06691ae6324cfb0b3341180d2e414)
  - Database: [CLASSIC](https://github.com/cmangos/classic-db/tree/e15ef1e135943f59961746cb1fbfae974e8cb16e)
  - OS: Linux Arch

### Steps to reproduce
1. Pick up quest "The Lunar Festival" near mailbox in Stormwind, complete it.
2. Pick up follow up quest "Lunar Fireworks", complete it.
3. Enter Greater Moonlight and use item "Lunar Festival Invitation".
4. Profit.

**Comment by Daedalus-code** [comment]
Yes, nothing happens after completing the quest and clicking the "Lunar Festival Invitation"

**Comment by killerwife** [comment]
Link item please.

**Comment by AnonXS** [comment]
https://tbcdb.com/?spell=26373

**Comment by Daedalus-code** [comment]
https://classic.wowhead.com/item=21711/lunar-festival-invitation

**Comment by killerwife** [comment]
Seems like a missing script based on my check. Sadly I do not have data for a quick fix.

**Comment by cala** [comment]
Hmm. Should be working in Classic (except for the Thunderbluff one). I wrote all the scripts some times ago. I'll see what happened soon (mind full with Gothic rework at the moment).

**Comment by AnonXS** [comment]
Maybe linked to 

https://github.com/cmangos/tbc-db/commit/07bceeaa9336ca0c5196e4c4934a39a8eb0f2d5b
https://github.com/cmangos/tbc-db/commit/e36a73b33d47e92a861b4bd50224355f987e5490

**Comment by cala** [comment]
Possible, though I remember having tested these. But I may have missed a thing.

**Comment by Daedalus-code** [comment]
```
2020-01-26 22:28:01 GameEvent 61 "Stormwind City - Stockades Jail Break" started.
2020-01-26 22:38:01 GameEvent 61 "Stormwind City - Stockades Jail Break" removed.
2020-01-26 22:54:48 ERROR: DB-SCRIPTS: Process table `dbscripts_on_go_template_use` id 180867, command 15 has buddy 15891 not found in range 10 of searcher Gameobject (Entry: 180867 Guid: 121699) (data-flags 3), skipping.
2020-01-26 22:54:48 ERROR: DB-SCRIPTS: Process table `dbscripts_on_go_template_use` id 180867, command 15 has buddy 15694 not found in range 10 of searcher Gameobject (Entry: 180867 Guid: 121699) (data-flags 5), skipping.
2020-01-26 22:54:48 ERROR: DB-SCRIPTS: Process table `dbscripts_on_go_template_use` id 180867, command 15 has buddy 15906 not found in range 10 of searcher Gameobject (Entry: 180867 Guid: 121699) (data-flags 5), skipping.
2020-01-26 22:54:48 ERROR: DB-SCRIPTS: Process table `dbscripts_on_go_template_use` id 180867, command 15 has buddy 15905 not found in range 10 of searcher Gameobject (Entry: 180867 Guid: 121699) (data-flags 5), skipping.
2020-01-26 22:54:48 ERROR: DB-SCRIPTS: Process table `dbscripts_on_go_template_use` id 180867, command 15 has buddy 15908 not found in range 10 of searcher Gameobject (Entry: 180867 Guid: 121699) (data-flags 5), skipping.
2020-01-26 22:54:48 ERROR: DB-SCRIPTS: Process table `dbscripts_on_go_template_use` id 180867, command 15 has buddy 15907 not found in range 10 of searcher Gameobject (Entry: 180867 Guid: 121699) (data-flags 5), skipping.
2020-01-26 22:54:48 ERROR: DB-SCRIPTS: Process table `dbscripts_on_go_template_use` id 180867, command 15 has buddy 15719 not found in range 10 of searcher Gameobject (Entry: 180867 Guid: 121699) (data-flags 5), skipping.
```

when I try this in sw

**Comment by AnonXS** [comment]
`.event start 7` ?

**Comment by cala** [comment]
The errors are not surprising as there is one spell for all the cities back and forth, meaning eight different targets (6 cities + Moonglade from Alliance and Moonglage from Horde). Hence, every cast should failed to find 7 targets, which is the case here. And you have no error for NPC target 15892 who is the one used for Alliance teleport (which is logical as you were in Stormwind).

This seems to indicates that the script did find a buddy target for spell 26448 but that the cast failed. This really remembers me the teleport issue with MC gossip menu from Lothos or BWL orb of Translocation that I have scheduled to fix when I'm done with Naxx or at least once Kel'Thuzad is the only one remaining, while I do my research about him.

**Comment by cala** [comment]
Hmm… I am not able to reproduce this issue. Using a Lunar Invitation does teleport the player to Moonglade or one of the Capital Cities.

However, there is a new issue: players can teleport from Moonglade to a city of the opposite faction though it was not possible when I reworked Lunar Festival and implemented those teleports.

**Comment by cala** [comment]
More tests done: player has to target himself/herself in order to have the spell casting properly. It silently fails otherwise. Definitely a targeting issue here.

**Comment by Daedalus-code** [comment]
Tried to target myself and do the scroll again but nothing happened. hm

**Comment by canidae** [comment]
Same here, targeted myself, used the scroll, nothing.

**Comment by killerwife** [comment]
@cala whats actual spell ids are used by this and where is the script? I could not find it when I looked. If it has TARGET_UNIT then the dbscript (im guessing here) needs to self target.

**Comment by AnonXS** [comment]
item spell <https://classic.wowhead.com/spell=26373>
```
(180867, 0, 15, 26450, 0, 0, 15905, 7, 5, 0, 0, 0, 0, 0, 0, 0, 0, 'Lunar Festival - Teleports Darnassus'), -- Holiday - Lunar Teleport: Darnassus at Darnassus Reveler
(180867, 0, 15, 26452, 0, 0, 15906, 7, 5, 0, 0, 0, 0, 0, 0, 0, 0, 'Lunar Festival - Teleports Ironforge'), -- Holiday - Lunar Teleport: Ironforge at Ironforge Reveler
(180867, 0, 15, 26448, 0, 0, 15892, 7, 3, 0, 0, 0, 0, 0, 0, 0, 0, 'Lunar Festival - Teleports Moonglade - Alliance'), -- Holiday - Teleport: Moonglade at Lunar Festival Emissary [Entry 15892]
(180867, 0, 15, 26448, 0, 0, 15891, 7, 3, 0, 0, 0, 0, 0, 0, 0, 0, 'Lunar Festival - Teleports Moonglade - Horde'), -- Holiday - Teleport: Moonglade at Lunar Festival Herald [Entry 15891]
(180867, 0, 15, 26453, 0, 0, 15908, 7, 5, 0, 0, 0, 0, 0, 0, 0, 0, 'Lunar Festival - Teleports Orgrimmar'), -- Holiday - Lunar Teleport: Orgrimmar at Orgrimmar Reveler
(180867, 0, 15, 26454, 0, 0, 15694, 7, 5, 0, 0, 0, 0, 0, 0, 0, 0, 'Lunar Festival - Teleports Storwimnd'), -- Holiday - Lunar Teleport: Stormwind at Stormwind Reveler
(180867, 0, 15, 26455, 0, 0, 15719, 7, 5, 0, 0, 0, 0, 0, 0, 0, 0, 'Lunar Festival - Teleports Thunderbluff'), -- Holiday - Lunar Teleport: Thunderbluff at Thunder Bluff Reveler
(180867, 0, 15, 26456, 0, 0, 15907, 7, 5, 0, 0, 0, 0, 0, 0, 0, 0, 'Lunar Festival - Teleports Undercity'); -- Holiday - Lunar Teleport: Undercity at Undercity Reveler
```

**Comment by killerwife** [comment]
Id: 15907
Name: Increased 2H Axe
Description: Increases two-handed axes skill rating by $s1.
