### ISSUE TITLE
🐛 [Classic] Druid talent "Blood Frenzy" and Rogue talent "Seal Fate" does not give extra combo points

### ISSUE THREAD

**Issue by canidae** [cmangos/issues#2103]
## 🐛 Bugreport
Druid talent "Blood Frenzy" (Feral Combat talent tree, 4th row, 3rd column) will not give the druid an extra combo point for critical strikes from Cat form abilities. The similar "Primal Fury" talent for (Dire) Bear form works.
Rogue Assassination talent "Seal Fate" neither gives extra combo point upon critical strike from abilities that gives combo points.

### Expected behavior
Critical strikes from Cat form abilities should give extra combo point when player has points in talent "Blood Frenzy".
Critical strikes from rogue abilities that gives combo points should give extra combo point when player has points in talent "Seal Fate".

### Version & Environment
  - Client: "1.12.1" (CLASSIC)
  - Server: [CLASSIC](https://github.com/cmangos/mangos-classic/tree/3b3df96c90e06691ae6324cfb0b3341180d2e414)
  - Database: [CLASSIC](https://github.com/cmangos/classic-db/tree/e15ef1e135943f59961746cb1fbfae974e8cb16e)
  - OS: Linux Arch

### Steps to reproduce
1. Fight any monster with a druid character in cat form having 2 points in talent "Blood Frenzy".
2. Use Cat form ability like "Claw".
3. Observe that critical strikes from Claw won't give extra combo point.
4. Profit

**Comment by killerwife** [comment]
Should be fixed.

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-classic/commit/69a8718d5903ed8917a482a2da5f68bc130e7877
