### ISSUE TITLE
🐛 [Bug Report] Can't click mailbox in Thunder Bluff

### ISSUE THREAD

**Issue by Daedalus-code** [cmangos/issues#2105]
## 🐛 Bugreport

Mu mail :O
![Screen Shot 2020-01-26 at 10 58 32 PM](https://user-images.githubusercontent.com/59256533/73142532-23e68680-4090-11ea-8995-26274df5e3b3.png)

### Expected behavior

I should be able to click it and see a mail icon also.
### Version & Environment

Client Version: 
  - "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/mangos-classic/tree/3b3df96c90e06691ae6324cfb0b3341180d2e414)

Database Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/classic-db/tree/e15ef1e135943f59961746cb1fbfae974e8cb16e)

Operating System: 
  - Linux Flavor - Raspberry Pi 4 Ubuntu 19.10 Server
### Steps to reproduce
1. Thunder Bluff
2. Mail around Auction House
3. No mail and not able to click
4. ...
5. Profit?

### Crashlog

- None

**Comment by cala** [comment]
Cannot reproduce. Try with a Horde NPC, maybe ?

**Comment by Daedalus-code** [comment]
< GM > on each side, got it xD 🙈 

![Mail](https://user-images.githubusercontent.com/59256533/73143278-8b083900-4098-11ea-95a6-aada139d26ae.jpg)
