### ISSUE TITLE
🐛 [Bug Report] WotLK Fails to Compile @ 11c0f0e

### ISSUE THREAD

**Issue by jimmybrancaccio** [cmangos/issues#2106]
## 🐛 Bugreport
Attempting to compile WotLK fails at https://github.com/cmangos/mangos-wotlk/commit/11c0f0e55d2c6736598bdd3777e3b39c50a83ff1

### Expected behavior
It should compile without errors or failure.

### Version & Environment
Client Version: 3.3.5a
CMaNGOS Repo & Commit Hash:  `11c0f0e55d2c6736598bdd3777e3b39c50a83ff1`
Database Repo & Commit Hash: `f92f559df64c83c8e29cf61a7dec3e91a5753058`
Operating System: Ubuntu 19.10

### Steps to reproduce
1. Pull `11c0f0e55d2c6736598bdd3777e3b39c50a83ff1`
2. Attempt to compile.
3. Note error about 19% of the way in.
4. ...
5. Profit

### Crashlog

```
[ 19%] Building CXX object src/game/CMakeFiles/game.dir/AI/CreatureAISelector.cpp.o
/home/mangos/wotlk/mangos/src/game/AI/CreatureAISelector.cpp: In function ‘UnitAI* FactorySelector::GetSpecificAI(Unit*, const string&)’:
/home/mangos/wotlk/mangos/src/game/AI/CreatureAISelector.cpp:101:83: error: invalid static_cast from type ‘Unit*’ to type ‘Player*’
  101 |             return GetClassAI(Classes(unit->getClass()), static_cast<Player*>(unit));
      |                                                                                   ^
In file included from /home/mangos/wotlk/mangos/src/game/Entities/Object.h:27,
                 from /home/mangos/wotlk/mangos/src/game/Entities/Unit.h:30,
                 from /home/mangos/wotlk/mangos/src/game/Entities/Creature.h:23,
                 from /home/mangos/wotlk/mangos/src/game/AI/CreatureAISelector.cpp:20:
/home/mangos/wotlk/mangos/src/game/Entities/EntitiesMgr.h:35:7: note: class type ‘Player’ is incomplete
   35 | class Player;
      |       ^~~~~~
[ 19%] Building CXX object src/game/CMakeFiles/game.dir/AI/EventAI/CreatureEventAI.cpp.o
[ 19%] Building CXX object src/game/CMakeFiles/game.dir/AI/EventAI/CreatureEventAIMgr.cpp.o
[ 19%] Building CXX object src/game/CMakeFiles/game.dir/AI/PlayerAI/CharmAI.cpp.o
make[2]: *** [src/game/CMakeFiles/game.dir/build.make:224: src/game/CMakeFiles/game.dir/AI/CreatureAISelector.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:697: src/game/CMakeFiles/game.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by Orcman2019** [comment]
[ 12%] Building CXX object src/game/CMakeFiles/game.dir/AI/CreatureAISelector.cpp.o
/home/cmangos/mangostemp/src/game/AI/CreatureAISelector.cpp: In function ‘UnitAI* FactorySelector::GetSpecificAI(Unit*, const string&)’:
/home/cmangos/mangostemp/src/game/AI/CreatureAISelector.cpp:101:83: error: invalid static_cast from type ‘Unit*’ to type ‘Player*’
             return GetClassAI(Classes(unit->getClass()), static_cast<Player*>(unit));
                                                                                   ^
src/game/CMakeFiles/game.dir/build.make:333: recipe for target 'src/game/CMakeFiles/game.dir/AI/CreatureAISelector.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/AI/CreatureAISelector.cpp.o] Error 1
CMakeFiles/Makefile2:546: recipe for target 'src/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Warlockbugs** [comment]
Should be fixed in https://github.com/cmangos/mangos-wotlk/commit/4318fc2725cfd8e51edf42320c018b0ec082bdb4
