### ISSUE TITLE
🐛 [Bug Report]Skinnable shouldn't be showing unless character has skinning skill?

### ISSUE THREAD

**Issue by Orcman2019** [cmangos/issues#2108]
## 🐛 Bugreport
Blizzlike is that this only shows up if the character has the skinning ability.

![zf_e](https://user-images.githubusercontent.com/58348159/73419479-816f1300-42dc-11ea-8832-c814b3ad6a39.jpg)

### Expected behavior
Shouldn't see Skinnable tag unless the character happens to have trained that as a profession.

### Version & Environment
3.3.5a" (WOTLK)
[WOTLK](https://github.com/cmangos/mangos-wotlk/tree/50f629cb06c492eab25f28c6794126c53ff274fa)
[WOTLK](https://github.com/cmangos/wotlk-db/tree/f39c4a1d5d949c1873b32c47758b4ea0f776bab1)
Operating System: 
Linux Mint 19.2

**Comment by Warlockbugs** [comment]
Should be fixed in:
https://github.com/cmangos/mangos-classic/commit/9be9e74c5b6926543f4d9529ebeae2e2310120b7
https://github.com/cmangos/mangos-tbc/commit/f6db2be21650c5fd1af84a9950ac6f1d152ee543
https://github.com/cmangos/mangos-wotlk/commit/d48e11544bae0629af60b49a8a00d761f43c8289
