### ISSUE TITLE
🐛 [Bug Report] Direct fire spells not accounting for partial resists.

### ISSUE THREAD

**Issue by Yatzii93** [cmangos/issues#2109]
## 🐛 Bugreport

Direct Fire Spells seem to not be affected by partial spell resistance. Fire damage dots do, so for instance fireball will not have any partial resists but the fireball dot does. Other schools seem to be working fine.

Fire Spell - 
![image](https://user-images.githubusercontent.com/47720837/73464650-2a6a4c00-4377-11ea-9003-15c12e1ee6cf.png)
![image](https://user-images.githubusercontent.com/47720837/73465039-afedfc00-4377-11ea-8d6a-1c1d76950833.png)

Arcane - 
![image](https://user-images.githubusercontent.com/47720837/73464827-64d3e900-4377-11ea-97e8-b1be5abe227a.png)

### Expected behavior

Fire spells should also partial resist just like the other schools. There is no reason it should be excluded.
### Version & Environment

Client Version:
2.3.4

CMaNGOS Repo & Commit Hash:
cmangos/mangos-tbc@650e49b

Database Repo & Commit Hash:
cmangos/tbc-db@78435bb

Operating System:
Win

### Steps to reproduce
1. Cast direct firespells on a boss level mob. I used Fireball for this example.

### Crashlog

- None

**Comment by Warlockbugs** [comment]
Cannot reproduce.
![Screenshot](https://i.imgur.com/QF7gTOv.png)

**Comment by Yatzii93** [comment]
Werid! Ty for testing. It seems to only be an issue with Fireball and Pyroblast my end. I'll have to dig around to see if I can figure out why.

**Comment by DramatimeWoW** [comment]
I am also not getting partial resists on the following commit: https://github.com/cmangos/mangos-tbc/tree/a440e856392dd55ed41b6d3a9eba80e79492187c

**Comment by Yatzii93** [comment]
hmmmm 🤔 I don't think theres been anything recently to do with partial resists. This issues been in my core since @Warlockbugs did his resistance rework. I've checked over all the code and recent commits and I can't see anything off. I still need to do a good debug session.

**Comment by Yatzii93** [comment]
So I found where it's going wrong and there is no difference in the code from my core to repo.

Fireball is returning true here 
https://github.com/cmangos/mangos-tbc/blob/master/src/game/Spells/SpellMgr.h#L643

> inline bool IsBinarySpell(SpellEntry const& spellInfo, uint8 effectMask = EFFECT_MASK_ALL)

The result is !binary causing this code to fail and ultimately leading to a 0 chance of a partial resist.
https://github.com/cmangos/mangos-tbc/blob/master/src/game/Entities/Unit.cpp#L3973

@Warlockbugs Did you use repo code/DB or VoA code/DB?

**Comment by Yatzii93** [comment]
Fireball has an auramask of 1 due to the aura being applied after the direct damage. Rather than frost bolt where the aura is applied before.

Fireball:
![image](https://user-images.githubusercontent.com/47720837/73812764-dc6da200-47d5-11ea-96f5-b575214f7e3f.png)

**Comment by Warlockbugs** [comment]
I am using repo code. The question is, where did direct damage effect go from the mask? Something is very off. If this is a regression, its not related to any of my code. IsBinarySpell being fed with incorrect info about effects applied.

**Comment by Warlockbugs** [comment]
I'll try to investigate this evening.

**Comment by Yatzii93** [comment]
hmmm maybe I'm looking in the wrong tbh. I forced binary to false for fireball and it now produces a chance to resist but even then I'm not getting resists ingames. If you've used repo code and it's fine I'm not against you not re-testing anything. I just wanted to double check. I'll keep looking.

**Comment by Yatzii93** [comment]
If @DramatimeWoW can reproduce it a older version and you can't now then the only explanation is I'm missing something. I'll have to go through the call stack and see if all the code alligns.

**Comment by Yatzii93** [comment]
@berserkingyadis tested and it's partial resisiting in that test so there must of been something that fixed it. I'll keep looking.
