### ISSUE TITLE
🐛 [Bug Report] Food crates, Barrels "Invalid target"

### ISSUE THREAD

**Issue by Daedalus-code** [cmangos/issues#2111]
## 🐛 Bugreport

![Food](https://user-images.githubusercontent.com/59256533/73478601-ac1da200-4396-11ea-9cb5-cf1df1c7d339.jpg)

### Expected behavior

Get food?
### Version & Environment

Client Version: 
  - "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/mangos-classic/tree/9be9e74c5b6926543f4d9529ebeae2e2310120b7)

Database Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/classic-db/tree/c90d0fb1c9828a9163d5bab1cd4e2ab28bf3c2e9)

Operating System: 
  - Linux Flavor
### Steps to reproduce
1. Look for crates at beach.
2. Try to open
3. Invalid target
4. ...
5. Profit

### Crashlog

- None

**Comment by Daedalus-code** [comment]
![Milk](https://user-images.githubusercontent.com/59256533/73479307-0834f600-4398-11ea-971f-3ab2bc12d41b.jpg)
 Barrel of Milk also 👀

**Comment by Tobschinski** [comment]
![image](https://user-images.githubusercontent.com/4753528/103381419-fe59cc80-4aeb-11eb-845f-aa266e825220.png)

looks fixed

**Comment by Daedalus-code** [comment]
![barrels](https://user-images.githubusercontent.com/59256533/103457454-c75c0480-4cff-11eb-878e-aa15c79c6748.jpg)

No my barrels?! 👀 🦖

**Comment by killerwife** [comment]
Either provide additional information on a server, or idk. Tobi tested on a clean mangos-classic.

**Comment by Daedalus-code** [comment]
Not latest obviously 👀😨 I will come back to you, building latest now.

**Comment by Grz3s** [comment]
![zzzz](https://user-images.githubusercontent.com/2374069/103457998-c1642480-4cfb-11eb-8b6c-ef657aeb4595.jpg)

Same place...
I suggest to check it on clean install (using no repacks, no 3rd party instalation tools, and remove additional addons)
Use ./installfullDB.sh tool
then we can go from there

**Comment by Daedalus-code** [comment]
Compiled, updated database, installfulldb went through with no errors:
![core_db](https://user-images.githubusercontent.com/59256533/103463662-49fbb880-4d2e-11eb-8a99-d6fc231721b0.png)

Still it is invalid 👀 
![hmm](https://user-images.githubusercontent.com/59256533/103463589-c93cbc80-4d2d-11eb-8c47-e22d9b074b5b.jpg)
![poly](https://user-images.githubusercontent.com/59256533/103463602-de195000-4d2d-11eb-9619-7a6601a4d0ea.png)
Still invalid, found a chest, that worked, I have not modded the world database at all, never.
No mods, edits at all.. other than configs I guess, my pet died and I tried to resurrect it but got text on screen telling me pet not dead, I could summon on him instantly.

**Comment by Grz3s** [comment]
@Tobschinski @cala   - can you guys check it pls?
`.go -3047.70 -985.94 7.95 0`  
`Barrel of Melon Juice`

**Comment by Daedalus-code** [comment]
Gonna try a fresh install...

**Comment by Daedalus-code** [comment]
Still invalid 🤔 
![hmmmm](https://user-images.githubusercontent.com/59256533/103464206-276b9e80-4d32-11eb-9859-54f9c9bc67d6.jpg)
The poly error not there now, letting the server run and will see if it pops up.

**Comment by Daedalus-code** [comment]
The mechanics behind this is inside **classicmangos database** (world)?
This issue is on both of my realms, both run with default **classicmangos database** (world).

**Comment by killerwife** [comment]
Make sure all parties included 1. clear cache from client 2. gm off when using the barrel.

**Comment by Daedalus-code** [comment]
![cacheoO](https://user-images.githubusercontent.com/59256533/103791574-e54ca080-5042-11eb-82fc-0b70e4959356.jpg)
Great! GM was on, I was able to open it with off and on.
The cache, was that the WDB directory? 👀 I deleted those files, and it seems like it fixed it. Thank you! 😃
