### ISSUE TITLE
🐛 [Bug Report] Hunter Pet, Feed Function not Working

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2112]
## 🐛 Bugreport
Hunter; I feed pet, the food does not get removed from bag, and the pet mood does not improve

### Expected behavior
Feed pet a food item, item disappears from bag, pet eats, and mood inproves
### Version & Environment

Client Version: 3.3.5a

CMaNGOS Repo & Commit Hash: 

Database Repo: e6de748a70e958a50ff2a67a66e8da4eced75a2b
Commit Hash: a32de86566cd994788d3dbb5cec42106c8832354

Operating System: 
Server: Ubuntu 16.04 4.15.0-76-generic 
Client: Windows 7

### Steps to reproduce
1.Log in with hunter
2.Feed pet
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by adellaci** [comment]
As of this morning i am still having this issue. Am i the only one?

**Comment by SuperSmelly** [comment]
I also have this issue. And I cannot abandon the pet either

**Comment by alanman** [comment]
Yeah, problem is still there.  Here's my workaround for it:

Edit Pet.cpp. goto line 691 and comment out "LooseHappiness();"
![image](https://user-images.githubusercontent.com/4338585/78316205-58594180-751c-11ea-982b-2889e5e43ab0.png)

That will stop the happiness from decreasing.  Next, you'll have to manually increase the happiness rating in the database. Basically, happiness over 1 million is considered happy. Execute this line in your sql database to bump all hunter pets over a million happiness:
```UPDATE character_pet SET curhappiness = curhappiness+1000000 WHERE curhappiness < 1000000 AND PetType = 1;```

**Comment by adellaci** [comment]
I haven't test it yet, but is someone working on it?

**Comment by Grz3s** [comment]
fixed
can be closed.

**Comment by cala** [comment]
👍🏻

**Comment by adellaci** [comment]
@alanman @cala @Grz3s 

Gentlemen, Thank you very much
