### ISSUE TITLE
🐛 [Classic] Druid Nature's Grace is triggered by all criticals, not just spells

### ISSUE THREAD

**Issue by canidae** [cmangos/issues#2113]
## 🐛 Bugreport
Nature's Grace:
> All spell criticals grace you with a blessing of nature, reducing the casting time of your next spell by 0.5 sec.

This talent procs on all ability criticals, not just spells. For example, a Cat Form druid with this talent will get proc on this talent for all crits from e.g. Shred, Claw, etc.

### Expected behavior
Only spell criticals should grant Nature's Grace.

### Version & Environment
  - Client: "1.12.1" (CLASSIC)
  - Server: [CLASSIC](https://github.com/cmangos/mangos-classic/tree/df16cbaae6c7f5e3a594315ce3746ef852b8ad6b)
  - Database: [CLASSIC](https://github.com/cmangos/classic-db/tree/c90d0fb1c9828a9163d5bab1cd4e2ab28bf3c2e9)
  - OS: Linux Arch

### Steps to reproduce
1. Create a Druid with all talents.
2. Give Druid decent gear.
3. Attack target in Cat Form with Claw.
4. Observe Nature's Grace buff appearing on critical hits.
5. Profit

**Comment by Daedalus-code** [comment]
Like this?
![Claw](https://user-images.githubusercontent.com/59256533/73609401-8b8b5d00-45cd-11ea-910e-0ba51a2d6a6c.jpg)

**Comment by nate123456** [comment]
I tested this on the current build, and the issue no longer occurs. After taking Nature's Grasp, when a crit occurred in Cat Form with Claw no Nature's Grasp proc occurred as per the combat log, whereas with a Crit heal the effect did occur. 

The issue can be closed.
