### ISSUE TITLE
🐛 [Bug Report] Kaja won't help me out in Orgrimmar

### ISSUE THREAD

**Issue by Daedalus-code** [cmangos/issues#2115]
## 🐛 Bugreport

Need my stuff repaired and she refuses to help out ☕️ 
![NormalToon](https://user-images.githubusercontent.com/59256533/73610374-b0380280-45d6-11ea-91a6-a224f072acee.jpg)
GM (.gm off) won't work
![GM_with_gmOFF](https://user-images.githubusercontent.com/59256533/73610383-cc3ba400-45d6-11ea-8875-42bd9f75faea.jpg)
GM (.gm on) works 👀 
![GM_with_gmON](https://user-images.githubusercontent.com/59256533/73610387-dd84b080-45d6-11ea-9f42-80f0e139766e.jpg)

### Expected behavior

Repair my stuff woman! 🙈 
### Version & Environment

Client Version: 
  - "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/mangos-classic/tree/df16cbaae6c7f5e3a594315ce3746ef852b8ad6b)

Database Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/classic-db/tree/c90d0fb1c9828a9163d5bab1cd4e2ab28bf3c2e9)

Operating System: 
  - Linux Flavor
### Steps to reproduce
1. Walk to Orgrimmar.
2. Talk to Kaja.
3.
4. ...
5. Profit (not for her)

### Crashlog

- None

**Comment by Orcman2019** [comment]
Weird it works on Wrath:

![WoWScrnShot_020220_145535](https://user-images.githubusercontent.com/58348159/73616090-4b77aa80-45cc-11ea-858a-3631080b05d6.jpg)

**Comment by Orcman2019** [comment]
https://classic.wowhead.com/npc=3322/kaja

**Comment by Daedalus-code** [comment]
![still_crying](https://user-images.githubusercontent.com/59256533/73755450-56fed900-4766-11ea-87fa-e479353459a1.png)

She hates my illegal name or what ? 👀

**Comment by MantisLord** [comment]
Also works in TBC (it goes straight to the vendor window as I think it should).
I suspect some shenanigans related to Love is in the Air?

**Comment by cala** [comment]
I look at this.

**Comment by Daedalus-code** [comment]
Thank you!

![Kaja_working](https://user-images.githubusercontent.com/59256533/78827286-24ca5b80-79e3-11ea-94d6-c9307002bd2d.jpg)
