### ISSUE TITLE
🐛 [Bug Report]The Endless Hunger

### ISSUE THREAD

**Issue by Orcman2019** [cmangos/issues#2116]
## 🐛 Bugreport
DK Quest The Endless Hunger can't be completed.

Key is received, should unlock the soul prison, doesn't do anything.

### Expected behavior
https://www.wowhead.com/npc=29519/unworthy-initiate
https://www.wowhead.com/quest=12848/the-endless-hunger
https://www.wowhead.com/item=40732/acherus-shackle-key

### Version & Environment
"3.3.5a" (WOTLK)
https://github.com/cmangos/mangos-wotlk/tree/a32de86566cd994788d3dbb5cec42106c8832354
https://github.com/cmangos/wotlk-db/tree/e6de748a70e958a50ff2a67a66e8da4eced75a2b
Operating System: 
Linux Mint 19.2

### Steps to reproduce
1. Create DK
2. Do the first 3 quests in the chain

![eh_a](https://user-images.githubusercontent.com/58348159/73615612-ab6b5280-45c6-11ea-86d0-4b3c5361f24b.jpg)
![eh_b](https://user-images.githubusercontent.com/58348159/73615613-ab6b5280-45c6-11ea-8151-11af11712cd2.jpg)
![eh_c](https://user-images.githubusercontent.com/58348159/73615614-ab6b5280-45c6-11ea-87ad-138b54fdfdbd.jpg)
![eh_d](https://user-images.githubusercontent.com/58348159/73615616-ab6b5280-45c6-11ea-9c3b-2b14e395f9d0.jpg)

**Comment by chz8494** [comment]
did same request and having same trouble, tried to touch and unchain all `Unworthy Initiate`, nothing happens after. can't finish mission

**Comment by chz8494** [comment]
The mission after it called "Death Comes From On High" doesn't work as well. character stucks after activating Acheus Eye.

**Comment by Grz3s** [comment]
yes both quests were damaged by core updates....some time ago...
"The Endless Hunger" -- i'll fix it as soon as ill find time... 
Death Comes From On High - this one is more difficult ... because ..spell that is used to control "eye of acherus"  is broken (again somewhere in core) ... and kicks player stright out from its possesed after player touche any button creature... another reason may be few missing server side spells .. that were not used  by original script... and they may be req now,,,

**Comment by chz8494** [comment]
so how can a player leave Acheus newbie place if they can't complete "Death Comes From On High"?

**Comment by Grz3s** [comment]
**he can't** ... I know that both quests a crucial for dk starting zone... Belive me i spent few months to redo whole dk zone + help ppl like @xfurry etc... we made it almost perfect... from A to Z... and its painfull to see stuff that once worked fine ..doesnt anymore... 
at the moment i see no other option than make them autocomplete in your local repo.. [https://github.com/cmangos/issues/wiki/Quest_template#method](url) .. and wait until fixed..
Sory. I hope that nothing else is broken there also :/

**Comment by chz8494** [comment]
@Grz3s tried change method to 0, doesn't seem to work, i'd expect to see quest available and finished right after acceptance? but what I actually see now is that nothing changed when [12484]"The Endless Hunger" method=0

**Comment by Grz3s** [comment]
if you have .gm rights ..you can always use command:
**.q c 12484**

**Comment by Grz3s** [comment]
-- fix for this quest
-- Chained Peasant - These spells need to ignore LOS
UPDATE spell_template SET AttributesEx2 = AttributesEx2|4 WHERE id IN (54612, 54613);

**Comment by Orcman2019** [comment]
The above changes fixed this quest, the eye of Acherus quest still seems to be bugged though, the eye spawns and any attempt to control it boots you out but the eye doesn't despawn.

![eh_1](https://user-images.githubusercontent.com/58348159/79941197-f6a43d00-8420-11ea-8b27-4921c9f695bc.jpg)
![eh_2](https://user-images.githubusercontent.com/58348159/79941196-f60ba680-8420-11ea-8a20-2e4ff9533062.jpg)

**Comment by Grz3s** [comment]
added here:
https://github.com/cmangos/mangos-wotlk/commit/b43c4a24a2db3c35a60a4bf705cf84019d31d126
