### ISSUE TITLE
🐛 [Bug Report]No exp after hitting 60 (Wotlk server)

### ISSUE THREAD

**Issue by Orcman2019** [cmangos/issues#2117]
## 🐛 Bugreport
Leveled from 59 to 60, exp bar went away and not getting more exp from quests or mobs.

### Expected behavior
Should keep going to level 80.

### Version & Environment
"3.3.5a" (WOTLK)
[WOTLK](https://github.com/cmangos/mangos-wotlk/tree/a32de86566cd994788d3dbb5cec42106c8832354)
[WOTLK](https://github.com/cmangos/wotlk-db/tree/e6de748a70e958a50ff2a67a66e8da4eced75a2b)
Operating System: 
Linux mint 19.2
### Steps to reproduce
1. Leveled from 59 to 60
2.

![60_a](https://user-images.githubusercontent.com/58348159/73618560-c8fbe480-45e5-11ea-9348-dd6c58e3fbb0.jpg)
![60_b](https://user-images.githubusercontent.com/58348159/73618561-c8fbe480-45e5-11ea-9469-7b1096dca75f.jpg)

**Comment by MantisLord** [comment]
Did you remember to set expansion of the account you're using?...
`.account set addon [username] 2`
1 = tbc, 2 = wotlk

**Comment by Orcman2019** [comment]
Yeah, just retried it and no difference.

.account set addon death 2
Subcommand 'note' of command 'ban' have less access level (2) that parent (3)
Subcommand 'warn' of command 'ban' have less access level (2) that parent (3)
Table `command` have command '' that only used with some subcommand selection, it can't have help or overwritten access level, skip.
Table `command` have nonexistent command 'movegens', skip.
Account DEATH (Id: 5) has been granted 2 expansion rights.

**Comment by Orcman2019** [comment]
Teleported to borean tundra and walking around fine, no exp with discovering new area either.

![WoWScrnShot_020220_190710](https://user-images.githubusercontent.com/58348159/73620526-9bb43400-45ef-11ea-9ffc-85874fd768a2.jpg)

**Comment by Rog360** [comment]
Yes, I'm having same problem with all char. over 60... :)

**Comment by killerwife** [comment]
Okay.
4 things to check -
1. mangosd.conf - Expansion = 2
2. table world_state - ID - 3 - check if its set to 2
3. account addon level needs to be set to 2
4. File WorldSocket.cpp - 
`    uint8 maxServerExpansion = sWorld.getConfig(CONFIG_UINT32_EXPANSION);
    uint8 currentServerExpansion = sWorldState.GetExpansion();
    uint8 playerAddonLevel = fields[7].GetUInt8();
    uint8 expansion;
    if (security >= SEC_GAMEMASTER)
        expansion = std::min(playerAddonLevel, maxServerExpansion);
    else
        expansion = std::min(playerAddonLevel, currentServerExpansion);`
needs to evaluate as 2

**Comment by Orcman2019** [comment]
1)
GameType = 0
RealmZone = 2
Expansion = 2
DBC.Locale = 255
2) 
mysql kept saying unknown table, not sure exactly what command I need to find it but nothing seemed to work to find it.
3)
Already verified that above
4)
src/game/Server/WorldSocket.cpp contains:
uint8 maxServerExpansion = sWorld.getConfig(CONFIG_UINT32_EXPANSION);
uint8 currentServerExpansion = sWorldState.GetExpansion();
uint8 playerAddonLevel = fields[7].GetUInt8();
uint8 expansion;
if (security >= SEC_GAMEMASTER)
    expansion = std::min(playerAddonLevel, maxServerExpansion);
else
    expansion = std::min(playerAddonLevel, currentServerExpansion);

**Comment by killerwife** [comment]
Its in character DB and if it doesnt exist, then you havent setup your server properly.

**Comment by Rog360** [comment]
I have this in world state. Is this correct?
id=0	Data=0 0 14887 14890 14889 14888

**Comment by Orcman2019** [comment]
mysql> select * from world_state;
+----+-----------------------------+
| Id | Data                        |
+----+-----------------------------+
|  0 | 0 0 14889 14890 14887 14888 |
+----+-----------------------------+
1 row in set (0.00 sec)

mysql>

**Comment by Rog360** [comment]
Your last commit fixed this for me. Thanks for your work... :)
