### ISSUE TITLE
🐛 [Bug Report]Table locales_areatrigger_teleport not created

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2118]
## 🐛 Bugreport
After run the ./InstallFullDB.sh script the locales_areatrigger_teleport table not created correctly.
### Expected behavior
The table should be created correctly.
### Version & Environment

Client Version: 
"1.12.1" (CLASSIC)
CMaNGOS Repo & Commit Hash: 
[CLASSIC](https://github.com/cmangos/tbc-db.git/)

Database Repo & Commit Hash: 
https://github.com/cmangos/classic-db.git
c90d0fb1c9828a9163d5bab1cd4e2ab28bf3c2e9

Operating System: 
CentOS 7
### Steps to reproduce
1.CREATE DATABASE `classic_world`;
2.mysql -uroot -p classic_world < sql/base/mangos.sql
3.for sql_file in $(ls sql/base/dbc/original_data/*.sql); do mysql -uroot -p --database=classic_world < $sql_file ; done
for sql_file in $(ls sql/base/dbc/cmangos_fixes/*.sql); do mysql -uroot -p --database=classic_world < $sql_file ; done
4. ./InstallFullDB.sh 

### Crashlog
- None

**Comment by biosfree** [comment]
Paying attention. The corresponding [update](https://github.com/cmangos/mangos-classic/blob/master/sql/updates/mangos/z2711_01_mangos_area_trigger_locales.sql) for mangos-classic has existed for a long time but has not been included in the main database.

And this despite the fact that running **mangosd** every time complains about the lack of the locales_areatrigger_teleport table
