### ISSUE TITLE
[Classic]&[TBC]Formula RemoveSpellbyDamageTaken

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#212]
> void Unit::RemoveSpellbyDamageTaken(AuraType auraType, uint32 damage)
> {
>    if (!HasAuraType(auraType))
>        return;
>    // The chance to dispel an aura depends on the damage taken with respect to the casters level.
>    uint32 max_dmg = getLevel() > 8 ? 25 \* getLevel() - 150 : 50;
>    float chance = float(damage) / max_dmg \* 100.0f;
>    if (roll_chance_f(chance))
>        RemoveSpellsCausingAura(auraType);
> }

Its seems "ok", but <strong>DoTs have less chance to break fear</strong> than direct damage spells or 
melee attacks! (alike 10%dots 30%direct/melee)

Its affects fear and etc effects in Classic&TBC, who know where is new formula in Wotlk&Cata?

proof: http://www.wowwiki.com/Fear?oldid=242361

> However, DoTs have less chance to break fear than direct damage spells or melee attacks. Even loaded up with DoTs a mob can be feared for the full duration with some frequency, but it can also break nearly instantly, depending on luck.

ps. sorry for my bad eng.

**Comment by cyberium** [comment]
@killerwife @Warlockbugs ?

**Comment by killerwife** [comment]
This is Heartbeat Resist, something @Warlockbugs is preparing for heavily. Afaik he has 2/3 preparations done. Since the thread is completely wrong you can close this.
