### ISSUE TITLE
🐛 [Bug Report]The common Gossip menu options text can not read the locales value

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2121]
## 🐛 Bugreport
The common Gossip menu options text can not read the value of table: "locales_gossip_menu_option" from menu_id=0 and id=0 to menu_id=0 and id=16.

### Expected behavior
Should display the values of table locales_gossip_menu_option, if exist.
### Version & Environment
  - "1.12.1" (CLASSIC)
  - "2.4.3" (TBC)

Client Version: 
1.12
2.4.3

CMaNGOS Repo & Commit Hash: 
90fb50ca6324997e21ee7b9756641b3497b341f5

Database Repo & Commit Hash: 
298b6f874cf0967f3fd7978ca1196b209ce35787

Operating System: 
CentOS
### Steps to reproduce
1. Insert locale value to table locales_gossip_menu_option from menu_id=0 and id=0 to menu_id=0 and id=16.
2. Client can not display the value of localized value.
3. Update table gossip_menu_option with locales text directly.
4. Client can display correctly.

**Comment by novicewu** [comment]
i got the same issue. Has anybody got the solution?

**Comment by MantisLord** [comment]
The `locales_gossip_menu_option` table is now deprecated and will soon be dropped.

Instead assign an `option_broadcast_text` in `gossip_menu_option`. This will ensure the appropriate blizzlike text is displayed from the `broadcast_text` table (along with any localized values present in `broadcast_text_locale`).
