### ISSUE TITLE
🐛 [Bug Report][TBC]Druid talent issues - Additional details

### ISSUE THREAD

**Issue by yhmark** [cmangos/issues#2125]
### Expected behavior

Affected by spell "Improved Leader of the Pack"(Druid's talent, id:34299,34297,34300), 
the actual effect of spell "Unleashed Rage"(Shaman's talent, id:30802-30811) is greatly improved.
Similar to hunter talent "Ferocious Inspiration"

### Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 

Database Repo & Commit Hash: 

Operating System: Linux Flavor

### Steps to reproduce
1.Druid lean talent "Improved Leader of the Pack"
2.Shaman lean talent "Unleashed Rage"
3.Druid and Shaman join the same group
4. Druid becomes bear or cheetah
5. Then once the talent "Unleashed Rage" is triggered, you can see that the attack power is abnormal from the properties panel

### Crashlog

- None

**Comment by Yatzii93** [comment]
With leader and Unleash:
![image](https://user-images.githubusercontent.com/47720837/74719407-de028580-522b-11ea-9870-685978b1c694.png)

Without:
![image](https://user-images.githubusercontent.com/47720837/74719441-ef4b9200-522b-11ea-8f14-a90e57059c0f.png)

Not seeing an issue on my end unless it's from a recent change.

**Comment by yhmark** [comment]
Here is the battle record for 2/18/2020（I updated the version of core and db on 1/16/2020）
<img width="862" alt="无标题" src="https://user-images.githubusercontent.com/11365520/74749363-02e70f00-52a5-11ea-8397-4c94704c2db7.png">
<img width="862" alt="无标题1" src="https://user-images.githubusercontent.com/11365520/74750016-fe6f2600-52a5-11ea-9b05-4660e13b7788.png">

I try to update to the latest version to see if there are still problems

**Comment by yhmark** [comment]
Hi Yatzii93

I updated to the latest version today, unfortunately, the problem persists
<img width="858" alt="无标题2" src="https://user-images.githubusercontent.com/11365520/74800619-01523100-530f-11ea-96a3-88eb5f7bddb8.png">
<img width="861" alt="无标题3" src="https://user-images.githubusercontent.com/11365520/74800631-08793f00-530f-11ea-942a-195f720e2568.png">
<img width="858" alt="无标题4" src="https://user-images.githubusercontent.com/11365520/74801121-a28db700-5310-11ea-8c49-29fbbcd2bfec.png">
<img width="859" alt="无标题5" src="https://user-images.githubusercontent.com/11365520/74801128-a8839800-5310-11ea-828e-26333ab1c85d.png">

**Comment by yhmark** [comment]
In addition, I tested and found that if the Druid landed in bear form, this bug would not be triggered, and he must change from human form to bear or cheetah form.
May be caused by deformation.

**Comment by yhmark** [comment]
And the battle record for 2/19/2020

Normal state:
<img width="859" alt="22222" src="https://user-images.githubusercontent.com/11365520/74858038-94c34a80-537f-11ea-9fe5-1586037b77c3.png">

"Ferocious Inspiration" + "Improved Leader of the Pack":
The damage of the panel!!!
<img width="860" alt="111111" src="https://user-images.githubusercontent.com/11365520/74858751-cd175880-5380-11ea-8d63-cf76feb2bb19.png">

"Ferocious Inspiration" + "Improved Leader of the Pack" + "Unleashed Rage":
The damage and attack power!!!
<img width="859" alt="33333" src="https://user-images.githubusercontent.com/11365520/74858842-f2a46200-5380-11ea-8f43-23a5a420bc6c.png">

**Comment by yhmark** [comment]
It ’s important to learn the "**Improved** Leader of the Pack" talent, not just the "Leader of the Pack"
