### ISSUE TITLE
🐛 [Classic] Talent reset on shaman also resets skill for two-handed axes and maces

### ISSUE THREAD

**Issue by canidae** [cmangos/issues#2129]
## 🐛 Bugreport
A Shaman resetting talents also cause weapon skill level in Two-Handed Axes and Two-Handed Maces to be forgotten. This was correct behavior prior to patch 1.11, but that patch changed the behavior to remember skill level of these two weapon proficiencies upon talent reset (https://wowwiki.fandom.com/wiki/Patch_1.11.0). 

### Expected behavior
Skill level of Two-Handed Axes and Two-Handed Maces should not be reset when resetting talents.

### Version & Environment
  - Client: "1.12.1" (CLASSIC)
  - Server: [CLASSIC](https://github.com/cmangos/mangos-classic/tree/0d1fcbaa95479554c1a64977df160c2e4dcd8544)
  - Database: [CLASSIC](https://github.com/cmangos/classic-db/tree/e15ef1e135943f59961746cb1fbfae974e8cb16e)
  - OS: Linux Arch

### Steps to reproduce
1. Learn Shaman enhancement talent Two-Handed Axes and Maces.
2. Level up weapon skill for Two-Handed Axes and Maces.
3. Reset talents.
4. Learn Shaman enhancement talent Two-Handed Axes and Maces.
5. Observe that weapon skill level of Two-Handed Axes and Maces is not remembered.
6. Profit

**Comment by killerwife** [comment]
@Warlockbugs

**Comment by Warlockbugs** [comment]
I've compared 1.11.0 and 1.10.1 skills entries, 1.11.0 added a very specific flag bit, which is currently unknown and not implemented.  I am certain that it is what we are looking to implement. I will get to it when i can.

**Comment by nate123456** [comment]
I learned the `Two-Handed Axes and Maces` talent, then leveled up the skill to 100, then reset my talents, then relearned the `Two-Handed Axes and Maces`, and the skill is back to 1. 

It seems that this is the expected behavior at some point in classic wow's history, but it was patched <= `.1.12.1`, so I'd say it's still a bug. 

The `Needs Replication` tag can be removed.
