### ISSUE TITLE
🐛 [Bug Report] Pet movement path needs to be improved

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2130]
Pets always move more than players, which is often be found by creature and enter combat before player. 
In addition, when the player retreats, the pet will move forward a certain distance.

video:
https://streamable.com/400zr

Client version:
2.4.3

Commit hash:
Newest

Database version:
Newest

Operating system:
centos

**Comment by Warlockbugs** [comment]
Pet should move a bit ahead of player due prediction ticks, but not when player is backpedaling. This was fixed.

https://github.com/cmangos/mangos-classic/commit/cca90ad72fa39e5e024ae2476d9e0164ba41d389
https://github.com/cmangos/mangos-tbc/commit/5b2f88b86db66eb774ff39fa93b6b72531382117
https://github.com/cmangos/mangos-wotlk/commit/b61c3135e65299833e0a444fe8496d917493b583

**Comment by aleigood** [comment]
When the player goes left or right, the pet will still run a distance forward.
