### ISSUE TITLE
🐛 [Bug Report] Part of the hunter's pet model is too small

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2131]
## 🐛 Bugreport
The hunter's tamed dragon Hawk is the same size as the purchased non combat pet.
![image](https://user-images.githubusercontent.com/3367999/74906251-5a8f9280-53eb-11ea-8ad7-08b0f02e3684.png)

Client version:
2.4.3

Commit hash:
Newest

Database version:
Newest

Operating system:
centos

**Comment by AnonXS** [comment]
Pets increase with happiness, but i think thats to small to begin with, maybe add what npc you tamed.

**Comment by jimmybrancaccio** [comment]
@aleigood Please provide _all_ information as requested in the bug report template.

**Comment by jimmybrancaccio** [comment]
Closing this as issue has not been updated with complete information. If this is still an issue please create a new issue in GitHub with the full details as requested by the bug reporting template. Thank you.
