### ISSUE TITLE
🐛 [Bug Report] The problem of quest "Taming the Beast"

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2132]
## 🐛 Bugreport

1. When during  using the tamer stick, even if the interruption can successfully tame the beast.
2. The beast will not follow the player after being tamed.

Client version:
2.4.3，1.12

Commit hash:
Newest

Database version:
Newest

Operating system:
centos

**Comment by jimmybrancaccio** [comment]
@aleigood Please provide _all_ of the information as requested in the bug report template.

**Comment by jimmybrancaccio** [comment]
Closing this as issue has not been updated with complete information. If this is still an issue please create a new issue in GitHub with the full details as requested by the bug reporting template. Thank you.
