### ISSUE TITLE
🐛 [Bug Report] The problem of quest "Escape from the Catacombs"

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2133]
## 🐛 Bugreport

The problem of quest "Escape from the Catacombs"
In the quest: 9212 "Escape from the Catacombs" creature:16295 don't help players to attack monsters.

Client version:
2.4.3

Commit hash:
Newest

Database version:
Newest

Operating system:
centos

**Comment by al3xc1985** [comment]
I think thia is a general problem for most or all wuest with such thing. The escorted npc/creature doesn't assist you whe. You are attacked

**Comment by killerwife** [comment]
@AnonXS I checked the NPC for  the escort and it has correct data. Can you check surrounding mobs if they maybe have wrong faction?

**Comment by AnonXS** [comment]
```
(11681, 16342, 1643, 0, 16, 17, 268959744, 0, 0, 0, 0),
(11682, 16343, 1643, 0, 15, 16, 268959744, 0, 0, 0, 0),
```
Faction 1643 seems correct as is.

**Comment by jimmybrancaccio** [comment]
@aleigood Please provide _all_ of the information as requested in the bug report template.
