### ISSUE TITLE
🐛 [Bug Report] The gossip menu option of "Spark" Overgrind

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2134]
## 🐛 Bugreport

The gossip menu option (menu_id:7426,id:0) of npc Engineer "Spark" Overgrind (entry:17243) should display after player accept the quest "Show Gnomercy(entry=9537)". Now it's always display.

Client version:
2.4.3

Commit hash:
Newest

Database version:
Newest

Operating system:
centos

**Comment by jimmybrancaccio** [comment]
@aleigood Please provide _all_ of the information as requested in the bug report template.

**Comment by Grz3s** [comment]
`.gm off`

**Comment by jimmybrancaccio** [comment]
Closing this as issue has not been updated with complete information. If this is still an issue please create a new issue in GitHub with the full details as requested by the bug reporting template. Thank you.
