### ISSUE TITLE
🐛 [Bug Report] Game crash during Moroes encounter

### ISSUE THREAD

**Issue by Valkirie** [cmangos/issues#2138]
## 🐛 Bugreport
When doing the Karazhan Moroes encounter, the server will crash. The Call Stack goes from Unit::TriggerAggroLinkingEvent() to CreatureLinkingHolder::ProcessSlaveGuidList().

### Version & Environment
Client Version: 2.4.3

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/tree/d2586ab3a5a0c3c3a6775b871a9ac3fcb4f522de

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/b8b623e4f23ec8b9f5c2d5e5d50529f71e796032

Operating System: Win 10

### Steps to reproduce
1. Go to Karazhan
2. Start encounter with Moroes
3. Crash the server

### Crashlog

- None
![Screenshot_2](https://user-images.githubusercontent.com/934757/75231864-7f528400-57b6-11ea-8163-fac7b6472452.png)

**Comment by Dromadoros** [comment]
Hey, did you find any solution ? Same issue for me

**Comment by Valkirie** [comment]
I know what caused this (fixed it as it was caused by some local server modifications).

**You absolutely need** to have those four adds **InWorld** by the time you trigger the fight otherwise the server will crash.

**Comment by tonymontoya** [comment]
This should probably be closed.  As mentioned - the issue was caused by a local server config.  I tested this whole raid on the latest build from this wek (June 22, 2020) and the could not reproduce the issue.  I was running on an Ubuntu 18.04 server backend however.
