### ISSUE TITLE
🐛 [Bug Report] Player Resilience not affecting Pets

### ISSUE THREAD

**Issue by Yatzii93** [cmangos/issues#2139]
## 🐛 Bugreport
 Has no affect at the moment.

### Expected behavior

Player resisilience should be affecting player pets the same as it does to the player.
https://wowwiki.fandom.com/wiki/Resilience - "Resilience is a character attribute that reduces all damage taken from players and their pets or minions."
### Version & Environment
**Client Version:** 
2.4.3

**CMaNGOS Repo & Commit Hash:**
cmangos/mangos-tbc@3e650fd

**Database Repo & Commit Hash:**
latest

**Operating System:**
Win

**Steps to reproduce:**
-Test damage on pet with master having Resilience gear and then without.

**Comment by Warlockbugs** [comment]
Inaccurate for TBC. Player's resilience was shared with pets late in WotLK expansion.

https://wow.gamepedia.com/Patch_3.3.0#Classes:_General
> Pet Resilience: All player pets now get 100% of their master's resilience.
