### ISSUE TITLE
🐛 [Bug Report][TBC]Shaman Chain Heal Issue

### ISSUE THREAD

**Issue by yhmark** [cmangos/issues#2143]
### Expected behavior

Shaman Chain Healing do not select the character's current target as the first target, and it will heal more than 3 targets.

My level is 60, Chain Healing level is 3.

### Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 5b6e8a7d618974ae9ab2e3439922e6e4a6e7ace7

Database Repo & Commit Hash: 45ce1e50bb8bea4bf5e72818e0ae5aa3796954d9

Operating System: Linux Flavor

### Steps to reproduce
1. 100% trigger

### Crashlog

- None

**Comment by yhmark** [comment]
It is verified that in the code, the current target is not added to the final target list.

**Comment by Dromadoros** [comment]
Hey,

I see that we erase unitTarget from our list but not added anymore. I'm debugging and hope to find a solution but still new in C++ ...

If someone has a solution for that, I will be curious :)

**Comment by duduch123** [comment]
I have the same problem @yhmark have you find a solution ?

**Comment by yhmark** [comment]
![治疗链](https://user-images.githubusercontent.com/11365520/79441633-11824600-800a-11ea-81ca-bb709c01e342.png)

**Comment by killerwife** [comment]
Closed in https://github.com/cmangos/mangos-tbc/commit/8e4b378905543685b0ab7c39c77d0bfc9848ba0a
