### ISSUE TITLE
🐛 [Bug Report][TBC] Crash while fight with Blackheart the Inciter in Shadow Labyrinth

### ISSUE THREAD

**Issue by ykslol** [cmangos/issues#2147]
## 🐛 Bugreport
In fight with [Blackheart the Inciter](https://www.wowhead.com/npc=18667/blackheart-the-inciter)  in Shadow Labyrinth

### Expected behavior
It must not to crassh the server.

### Version & Environment
 -  [Commit Hash](https://github.com/cmangos/mangos-tbc/tree/e5d065)
 - [Database Version](https://github.com/cmangos/tbc-db/tree/320eb)
 - Boost: 1.62.0 
 - OpenSSL: 1.1.0l  
 - gcc (GCC) 7.3.0
 - mysql  Ver 15.1 Distrib 10.1.44-MariaDB, using readline 5.2
 - build line:
       /usr/local/cmake/bin/cmake ../../ \
           -DCMAKE_INSTALL_PREFIX=/server \
           -DBUILD_GAME_SERVER=1 \
           -DBUILD_LOGIN_SERVER=0 \
           -DBUILD_EXTRACTORS=0 \
           -DPCH=0 \
           -DBUILD_PLAYERBOT=0 \
           -DDEBUG=1 \

- Client version: "2.4.3" (TBC)
- runing under docker image ubuntu:18.04 - kernel 4.4.0-174-generic

### Steps to reproduce
1. Get 70 lvl
2. Get [Shadow Labyrinth Key](https://www.wowhead.com/item=27991/shadow-labyrinth-key)
3. Go [Shadow Labyrinth](https://www.wowhead.com/shadow-labyrinth)
4. Go to [Blackheart the Inciter](https://www.wowhead.com/npc=18667/blackheart-the-inciter)
5. Start fight with him
6. Wait first cast of [War Stomp](https://www.wowhead.com/spell=33707/war-stomp)
7. crash in near 5 secs

### Crashlog
https://gist.github.com/ykslol/c5af578f36719c7564bc4cd9a219365c
![Screenshot from 2020-03-12 02-07-32](https://user-images.githubusercontent.com/20792687/76527190-de371f00-647f-11ea-8129-4c1ed53db66f.png)

**Comment by Booggmz** [comment]
got in in debian:stretch with latest build (today, now) and gdb
[log2020-03-13-19-34-02.log](https://github.com/cmangos/issues/files/4331351/log2020-03-13-19-34-02.log)

**Comment by hkshawn** [comment]
win10 64x reproduce

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-tbc/commit/7c50c57e374ba75a36a5101cfdb369b63a92c5c8
