### ISSUE TITLE
missing command: .list auras

### ISSUE THREAD

**Issue by Azelen** [cmangos/issues#215]
i've noticed that chat command .list auras exist in code but isnt listed in 'command' DB table which makes it not accessable ingame. (its missing at least in mangos.sql file for cmangos-tbc and cmangos-wotlk).

**Comment by AnonXS** [comment]
not missing anymore https://github.com/cmangos/mangos-tbc/commit/c9e84974a34b4a868f4e6329ef5d9735add78f8f
