### ISSUE TITLE
🐛 [Bug Report] clams in wotlk do not contain loot

### ISSUE THREAD

**Issue by ekg98** [cmangos/issues#2150]
## 🐛 Bugreport
Clams looted off mirlocs do not give any loot

### Expected behavior
clams should open and provide loot

### Version & Environment
win 10 wotlk 3.3.5a
Client Version: 3.3.5a

CMaNGOS Repo & Commit Hash: 7ae8e4763f9da934f4e430854a64f7595990de45

Database Repo & Commit Hash: 48ab22acf166560d731cb5d19646ba38b0382c2e

### Steps to reproduce
1. loot clam
2. open clam

**Comment by Grz3s** [comment]
theyre controled by spells like this one:
`Id: 58165
Name: Big-Mouth Clam
Description: Open the clam!

Effect 0:
Id: 59 (SPELL_EFFECT_CREATE_RANDOM_ITEM)
BasePoints: 1
Targets: (1, 0) (TARGET_UNIT_CASTER, TARGET_NONE)
EffectMiscValueA: 5092`

with loot inside `spell_loot_template` 
We do have all data there... and it used to work correct before  .. one of core updates broke it...
