### ISSUE TITLE
🐛 [Bug Report][TBC]The solution to the bug #2142

### ISSUE THREAD

**Issue by yhmark** [cmangos/issues#2152]
### Expected behavior

see here
https://github.com/cmangos/issues/issues/2142

The Possible solution:

![强化兽群领袖解决](https://user-images.githubusercontent.com/11365520/76856319-fea31700-688d-11ea-8ddb-9e34a7215453.png)

Details:
1. process "Improved Leader of the Pack", and the basepoint set to be the amount of health
2. process "Unleashed Rage", and use the health as basepoint to calculate the attack power

### Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 5b6e8a7d618974ae9ab2e3439922e6e4a6e7ace7

Database Repo & Commit Hash: 45ce1e50bb8bea4bf5e72818e0ae5aa3796954d9

Operating System: Linux Flavor

### Crashlog

- None

**Comment by jimmybrancaccio** [comment]
@yhmark Please add this information to the case your referenced. There's no need to open a new case 😄
