### ISSUE TITLE
🐛 [Bug Report] Shaman Flametongue Totem Bug

### ISSUE THREAD

**Issue by yhmark** [cmangos/issues#2153]
### Expected behavior

The fire damage attached to the weapon is too high!
See the code below:
![火舌图腾bug](https://user-images.githubusercontent.com/11365520/76857566-acafc080-6890-11ea-8ea7-7094955598c5.png)

line 3395 is the output of line 3398 in Server.log
line 3397 Is the original code, the result is: 1492 * 0.01 * 1.9 * (12 + 100) = 3174
I think it would be fine without the 100

### Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 5b6e8a7d618974ae9ab2e3439922e6e4a6e7ace7

Database Repo & Commit Hash: 45ce1e50bb8bea4bf5e72818e0ae5aa3796954d9

Operating System: Linux Flavor

### Crashlog

- None

**Comment by buenodart** [comment]
Hey, good night

This solution worked for you?

Im having the same problem! My flametongue totem is givin a lot of bonus damage!!!

**Comment by Dromadoros** [comment]
It worked for me :)

**Comment by killerwife** [comment]
```cpp
                    int32 totalDamage = (damage * 0.01f * weaponSpeed * (m_CastItem->GetEnchantmentModifier() + 100.f) / 100.f);
                    m_caster->CastCustomSpell(unitTarget, 16368, &totalDamage, nullptr, nullptr, TRIGGERED_OLD_TRIGGERED, m_CastItem);
```

**Comment by buenodart** [comment]
Ohhhh, ok!!! Thank you, guys!! For real!! ;)

I Appreciate!!

**Comment by canidae** [comment]
It looks like this is resolved?
https://github.com/cmangos/mangos-classic/commit/f6fc4ffc37d5aea802f6c82ad2c4741a5e89c6ec
https://github.com/cmangos/mangos-tbc/commit/fdf26b5e866b65aa04b3095157b93c3d98dd1848
