### ISSUE TITLE
💬 [Support Request]

### ISSUE THREAD

**Issue by FfKB** [cmangos/issues#2154]
CMaNGOS

### Version & Environment

Client Version: "3.3.5a" (WOTLK)

 
CMaNGOS Repo & Commit Hash:  [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/XXXX)

Database Repo & Commit Hash: 9fd5477d54d40abca29b314581816cef0ee2992a

Operating System: Linux Ubuntu 19.10

### Steps to reproduce
1. I was following that Faq: https://www.osrsbox.com/blog/2019/04/13/installing-a-wow-vanilla-server-on-ubuntu-linux/ when I got that error and I cannot solve that.
2. I can run the realm.conf: /home/wow/mangos-wotlk/run/bin/realmd -c /home/wow/mangos-wotlk/run/etc/realmd.conf
[CMaNGOS Auth server v0.18] port(3724)

       _____     __  __       _   _  _____  ____   _____ 
      / ____|   |  \/  |     | \ | |/ ____|/ __ \ / ____|
     | |        | \  / |     |  \| | |  __  |  | | (___  
     | |ontinued| |\/| | __ _| . ` | | |_ | |  | |\___ \ 
     | |____    | |  | |/ _` | |\  | |__| | |__| |____) |
      \_____|   |_|  |_| (_| |_| \_|\_____|\____/ \____/ 
      http://cmangos.net\__,_|     Doing things right!

Built on Mar 15 2020 at 14:14:37
Built for Linux_x64 (little-endian)
Using commit hash(9fd5477d54d40abca29b314581816cef0ee2992a) committed on 2020-03-14T18:07:15+03:00
Using configuration file /home/wow/mangos-wotlk/run/etc/realmd.conf.

<Ctrl-C> to stop.
Login Database total connections: 2
MySQL client library: 8.0.19
MySQL server ver: 8.0.19-0ubuntu0.19.10.3 
MySQL client library: 8.0.19
MySQL server ver: 8.0.19-0ubuntu0.19.10.3 
Added realm id 1, name 'MaNGOS'
3. But the mangos, I got that problem: /home/wow/mangos-wotlk/run/bin/mangosd -c /home/wow/mangos-wotlk/run/etc/mangosd.conf -a /home/wow/mangos-wotlk/run/etc/playerbot.conf
[CMaNGOS World server v0.18] id(1) port(8085)

       _____     __  __       _   _  _____  ____   _____ 
      / ____|   |  \/  |     | \ | |/ ____|/ __ \ / ____|
     | |        | \  / |     |  \| | |  __  |  | | (___  
     | |ontinued| |\/| | __ _| . ` | | |_ | |  | |\___ \ 
     | |____    | |  | |/ _` | |\  | |__| | |__| |____) |
      \_____|   |_|  |_| (_| |_| \_|\_____|\____/ \____/ 
      http://cmangos.net\__,_|     Doing things right!

Built on Mar 15 2020 at 14:14:16
Built for Linux_x64 (little-endian)
Using commit hash(9fd5477d54d40abca29b314581816cef0ee2992a) committed on 2020-03-14T18:07:15+03:00
Using configuration file /home/wow/mangos-wotlk/run/etc/mangosd.conf.

<Ctrl-C> to stop.
World Database total connections: 2
MySQL client library: 8.0.19
MySQL server ver: 8.0.19-0ubuntu0.19.10.3 
MySQL client library: 8.0.19
MySQL server ver: 8.0.19-0ubuntu0.19.10.3 
SQL: SELECT required_14010_01_mangos_static_custom_chat FROM db_version LIMIT 1
query ERROR: Unknown column 'required_14010_01_mangos_static_custom_chat' in 'field list'
The table `db_version` in your [WORLD] database indicates that this database is out of date!

  [A] You have: --> `14007_01_mangos_new_ticket_system.sql`

  [B] You need: --> `14010_01_mangos_static_custom_chat.sql`

You must apply all updates after [A] to [B] to use mangos with this database.
These updates are included in the sql/updates folder.
Please read the included [README] in sql/updates for instructions on updating.
4. Please could you help me with that, I am very noob with mysql
5. Profit

**Comment by al3xc1985** [comment]
in wotlk-db you have a file called InstallFullDB.sh
use it

**Comment by FfKB** [comment]
Thank you it worked!
But right now I have 

Loading CreatureEventAI Scripts...
Event 3001 Action 1 uses nonexistent SpellID 11959.
Event 3601 Action 1 uses nonexistent SpellID 8014.
Event 4002 Action 1 uses nonexistent SpellID 6016.
Event 4301 Action 1 uses nonexistent SpellID 11959.
Event 4601 Action 1 uses nonexistent SpellID 3368.
Event 4801 Action 1 uses nonexistent SpellID 7165.
Event 4802 Action 1 uses nonexistent SpellID 9080.
Event 6001 Action 1 uses nonexistent SpellID 12024.
Event 6002 Action 1 uses nonexistent SpellID 6016.
Event 6102 Action 1 uses nonexistent SpellID 7159.
Event 7902 Action 1 uses nonexistent SpellID 9128.
Event 9401 Action 1 uses nonexistent SpellID 53.
Event 9504 Action 1 uses nonexistent SpellID 53.
Event 9505 Action 1 uses nonexistent SpellID 10277.
Event 9802 Action 1 uses nonexistent SpellID 3229.
Event 9901 Action 1 uses nonexistent SpellID 11959.
Event 9902 Action 1 uses nonexistent SpellID 1776.
Event 9903 Action 1 uses nonexistent SpellID 53.
Event 10001 Action 1 uses nonexistent SpellID 8876.
Event 10301 Action 1 uses nonexistent SpellID 7164.
Event 11301 Action 1 uses nonexistent SpellID 6268.
Event 11501 Action 1 uses nonexistent SpellID 7342.
Event 11602 Action 1 uses nonexistent SpellID 8646.
Event 11901 Action 1 uses nonexistent SpellID 6268.
Event 12102 Action 1 uses nonexistent SpellID 53.
Event 12103 Action 1 uses nonexistent SpellID 11972.
Event 12202 Action 1 uses nonexistent SpellID 53.
Event 12302 Action 1 uses nonexistent SpellID 8016.
Event 12402 Action 1 uses nonexistent SpellID 13730.
Event 12601 Action 1 uses nonexistent SpellID 7357.
Event 12701 Action 1 uses nonexistent SpellID 3616.
Event 12702 Action 1 uses nonexistent SpellID 11831.
Event 15401 Action 1 uses nonexistent SpellID 12166.
Event 15701 Action 1 uses nonexistent SpellID 6268.
Event 20201 Action 1 uses nonexistent SpellID 7399.
Creature 203 has nonexistent SpellID(12544) defined in event 20302.
Event 20303 Action 1 uses nonexistent SpellID 20792.
Event 20501 Action 1 uses nonexistent SpellID 6595.
Event 20601 Action 1 uses nonexistent SpellID 3427.
Event 21001 Action 1 uses nonexistent SpellID 26047.
Event 21002 Action 1 uses nonexistent SpellID 6016.
Event 21202 Action 1 uses nonexistent SpellID 5242.
Event 21501 Action 1 uses nonexistent SpellID 22766.
Event 21502 Action 1 uses nonexistent SpellID 2589.
Event 21701 Action 1 uses nonexistent SpellID 7276.
Event 21702 Action 1 uses nonexistent SpellID 745.
Event 30001 Action 1 uses nonexistent SpellID 8716.
Event 31403 Action 1 uses nonexistent SpellID 3107.
Event 31404 Action 1 uses nonexistent SpellID 11831.
Event 31405 Action 1 uses nonexistent SpellID 20819.
Event 31502 Action 1 uses nonexistent SpellID 3105.
Event 32790 Action 1 uses nonexistent SpellID 61722.
Event 33001 Action 1 uses nonexistent SpellID 6268.
Event 33401 Action 1 uses nonexistent SpellID 7164.
Event 33402 Action 1 uses nonexistent SpellID 3427.
Event 33403 Action 1 uses nonexistent SpellID 11792.
Event 33502 Action 1 uses nonexistent SpellID 12468.
Event 33503 Action 1 uses nonexistent SpellID 13375.
Event 34501 Action 1 uses nonexistent SpellID 5568.
Event 34502 Action 1 uses nonexistent SpellID 6268.
Event 34701 Action 1 uses nonexistent SpellID 15284.
Event 34702 Action 1 uses nonexistent SpellID 16856.
Event 34703 Action 1 uses nonexistent SpellID 13736.
Event 34704 Action 1 uses nonexistent SpellID 19134.
Event 35201 Action 1 uses nonexistent SpellID 14313.
Event 39001 Action 1 uses nonexistent SpellID 6268.
Event 39101 Action 1 uses nonexistent SpellID 3584.
Creature 397 has nonexistent SpellID(13787) defined in event 39702.
Event 39703 Action 1 uses nonexistent SpellID 3611.
Event 39704 Action 1 uses nonexistent SpellID 20811.
Event 41201 Action 1 uses nonexistent SpellID 3106.
Event 42201 Action 1 uses nonexistent SpellID 3393.
Event 42404 Action 1 uses nonexistent SpellID 6660.
Event 42801 Action 1 uses nonexistent SpellID 5708.
Event 42903 Action 1 uses nonexistent SpellID 9613.
Event 43004 Action 1 uses nonexistent SpellID 547.
Segmentation fault (core dumped)

**Comment by Grz3s** [comment]
make sure that this is set up corectly

> Define the path to your core's folder
> Core updates located under sql/updates from this mangos-directory will be added automatically
> CORE_PATH=

**Comment by FfKB** [comment]
Thank you
