### ISSUE TITLE
No skills, No Language and No GM

### ISSUE THREAD

**Issue by FfKB** [cmangos/issues#2155]
### Version & Environment

Client Version: "3.3.5a" (WOTLK)

CMaNGOS Repo & Commit Hash:  [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/XXXX)

Database Repo & Commit Hash: 9fd5477d54d40abca29b314581816cef0ee2992a

Operating System: Unix 19.10

### Steps to reproduce
1. Dear People Yesterday I got help and I must say thank you, but there are few new troubles in WOTLK mangos. Everything is running but: When I created a character. The character cannot talk (no language skill), The Character is created without skills in the skill list and all GM command does not work.
2. Profit

**Comment by al3xc1985** [comment]
This is like you have no world data in db. It happend to me to  ot imporr all worls data in db. U need to delete the db and import it with the tool

**Comment by al3xc1985** [comment]
Ofcours2 create it first

**Comment by FfKB** [comment]
> This is like you have no world data in db

Ok I will study Sql to do this... I am afraid like always with SQL.
Thank you I will give you a feedback soon
Thank you

**Comment by FfKB** [comment]
> Ofcours2 create it first

I got that error first:

Trying to retrieve last core update packaged in database ...
 Found last core revision in DB is 14010
Path to core provided, but directory not found! /home/wow/mangos-wotlk/mangos

I just created that directory and  repeat that.

Then I got that error now:
Trying to retrieve last core update packaged in database ...
Found last core revision in DB is 14010

Trying to apply additional core updates from path /home/wow/mangos-wotlk/mangos ...
./InstallFullDB.sh: line 259: [: : integer expression expected
CORE UPDATE PROCESSED: 0
CORE UPDATE FOUND BUT ALREADY IN DB: 1

Trying to apply /home/wow/mangos-wotlk/mangos/sql/base/dbc/original_data ...
Appending DBC file update *.sql to database wotlkmangos
./InstallFullDB.sh: line 284: /home/wow/mangos-wotlk/mangos/sql/base/dbc/original_data/*.sql: No such file or directory
ERROR: cannot apply /home/wow/mangos-wotlk/mangos/sql/base/dbc/original_data/*.sql

**Comment by Grz3s** [comment]
wrong path to your sources -- thats why nothing is imported
for example ive got sources cloned to: E:\WoWServ\mangos-wotlk

so path will be:

> Define the path to your core's folder
> Core updates located under sql/updates from this mangos-directory will be added automatically
> CORE_PATH="E:\WoWServ\mangos-wotlk"

**Comment by FfKB** [comment]
> wrong path to your sources -- thats why nothing is imported
> for example ive got sources cloned to: E:\WoWServ\mangos-wotlk
> 
> so path will be:
> 
> > Define the path to your core's folder
> > Core updates located under sql/updates from this mangos-directory will be added automatically
> > CORE_PATH="E:\WoWServ\mangos-wotlk"

I GOT IT
