### ISSUE TITLE
🐛 [Bug Report] Custom item continues having red question mark.

### ISSUE THREAD

**Issue by dvdvideo1234** [cmangos/issues#2156]
## 🐛 Bugreport
Follow the given tutorial provided by a user at MMOwned. [Here is a MD version][1].

### Expected behavior
The custom item still has question mark in-game an it is not consumable by pets.

### Version & Environment

Client Version: 3.3.5a" (WOTLK) [12340 enUS]

CMaNGOS Repo & Commit Hash: [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/ac93cdab16e7dd72278f679d771c9a93586d9f9a)
Revision: ac93cdab16e7dd72278f679d771c9a93586d9f9a
Author: killerwife <killerwife@gmail.com>
Date: 2019-08-22 12:50:34
Message:
Add script for go_unadorned_spike to safeguard warchiefs blessing

Database Repo & Commit Hash: [WOTLK](https://github.com/cmangos/wotlk-db/tree/cfc6954c7a1436c86363cd746f8eea2a843ae142)
commit cfc6954c7a1436c86363cd746f8eea2a843ae142 (HEAD -> master, tag: wotlk-db_PreBuild, origin/master, origin/HEAD)
Author: cala <cala@users.noreply.github.com>
Date:   Wed Oct 3 15:28:15 2018 +0200

    [TDB][1928][ACID] Cleanup: revert text IDs back to Classic ones
    
    * Revert texts to Classic IDs from TBC after rangeMode AI update
    * Add some missing texts
    * Move some random texts to dbscripts_random_template
    
    (cherry picked from commit https://github.com/cmangos/tbc-db/commit/58aa53e81310595eb4b7703cf2672fa04b34270f

Operating System:
```
Linux mangos-vb 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Steps to reproduce
1. On a fully working server edit Item.dbc and [add the custom item using DBCUtil][2].
2. On the client 3.3.5a (12340). [Add the new item as MPQ in `WoW/Data/patch-Z.MPQ`][3]
3. In both places add custom consumable entry with item level 250 for pets
```
Item.DBC
entry	class	subclass	unk0	material	displayid	inventorytype	sheath
100000	0	5	-1	4	25466	0	0
```

4. Start [`mangos` and `realm` demons][4] and enter game 
5. The item has red question mark.

### Crashlog

- None

[4]: https://github.com/dvdvideo1234/UbuntuBatches/blob/master/MaNGOS/config.sh#L81
[3]: https://github.com/dvdvideo1234/Tools/tree/master/MPQEditor%203.5.0.733
[2]: https://github.com/dvdvideo1234/Tools/tree/master/DBCUtil%201.3.2
[1]: https://github.com/dvdvideo1234/UbuntuBatches/blob/master/MaNGOS/fix-item-icons.md

**Comment by Grz3s** [comment]
cmangos is not a place for random stuff ...

**Comment by dvdvideo1234** [comment]
@Grz3s Ok, but am I missing a configuration of some sort. In theory it must work, but it doesn't

**Comment by al3xc1985** [comment]
On rhe cmangos/wiki you will fi d all db  info. Check that section and make that item consumable. You will find all tables with what they do,and what option to change for it to work

**Comment by dvdvideo1234** [comment]
@al3xc1985 

Yes, that is correct for these that are not `*.dbc`. I just duplicated a consumable meat item.

**Comment by al3xc1985** [comment]
Did you solved your problem? Can this issue be closed?

**Comment by RazzorX** [comment]
I've tested it myself and it worked great. It sounds banal, but have you ever cleared the WoW-cache? Even a small thing like this has a big impact.

**Comment by adellaci** [comment]
How do you clear the WOW-cache?

**Comment by al3xc1985** [comment]
delete cache folder from wow client

**Comment by al3xc1985** [comment]
Please close this

**Comment by dvdvideo1234** [comment]
> I've tested it myself and it worked great. It sounds banal, but have you ever cleared the WoW-cache? Even a small thing like this has a big impact.

Yep, clearded it just now

**Comment by dvdvideo1234** [comment]
> I've tested it myself and it worked great. It sounds banal, but have you ever cleared the WoW-cache? Even a small thing like this has a big impact.

Yep cleared it before starting the game..

**Comment by dvdvideo1234** [comment]
> I've tested it myself and it worked great. It sounds banal, but have you ever cleared the WoW-cache? Even a small thing like this has a big impact.

@RazzorX  What internal structure did you use for the MPQ?

I am having

```
[2] err=0 text=SFileReadFile - DBFilesClient\Item.dbc - Data\patch-Z.MPQ
[1] err=0 text=LoadSectorTable failed
[0] err=0 text=LoadSectorTable failed
```

**Comment by dvdvideo1234** [comment]
@adellaci  @al3xc1985 

I delete the cache every time using a `*.bat ` file:
```bat
cd Cache
rd /S /Q WDB
cd ..

WoW.exe

exit 0
```

**Comment by dvdvideo1234** [comment]
@RazzorX 

Using the [lastest version x64](https://www.hiveworkshop.com/threads/ladiks-mpq-editor-32bit.249562/) I get all of the items as red question marks. How do you use the MPQ and what operations apply in the application internally ?

**Comment by dvdvideo1234** [comment]
Using the [WDBX editor](https://github.com/WowDevTools/WDBXEditor/releases/tag/1.1.9.a) I get all other items as question marks and the custom item with desired icon:
![image](https://user-images.githubusercontent.com/9112662/78672343-2f082f00-78e9-11ea-8c36-5f3f2a43289d.png)

![image](https://user-images.githubusercontent.com/9112662/78672385-3a5b5a80-78e9-11ea-867a-0fa597376a77.png)

**Comment by dvdvideo1234** [comment]
@RazzorX Strangely, when I export all the data from the client `Item.dbc` and update the one row with my item, convert it to MPQ, all items appear without question mark. Weird that Blizzard's MPQ system needs all the items to be stored, rather just keeping the deltas between the patches.

**Comment by RazzorX** [comment]
Nice to see that your items have icons now. :)
I can confirm that feeding a pet is broken. Must be a Core/Spell issue i think...
Can you make an issues report here?
