### ISSUE TITLE
🐛 [Bug Report] x64_Release folder

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2157]
## 🐛 Bugreport
There is a problem introduced recently in ALL cores. The visual studio 2019 doesn't create the folder x64_Release, instead it creates a file that doesn't have an extension with that name and you get an error in compiler that a file or folder with x64_Release allready exist and the compile fails.

If you delete rhat newlt created file and create a folder x64_Release, all will compile perfect

### Expected behavior
Create corectlly x64_Release folder

### Version & Environment

Client Version: 
ALL on windows 7
<!--
  Commit Hash - is required
  Valid values are:
  Latest from 24.03.2020 on windows 7

 ### Operating system

Windows 7

**Comment by al3xc1985** [comment]
@cyberium any ideea?

**Comment by cyberium** [comment]
Hey, yes its confirmed.

Can you please try to modify [that line](https://github.com/cmangos/mangos-classic/blob/master/src/shared/CMakeLists.txt#L211) onto
`COMMAND xcopy /Y \"${LibFolder}\\*.dll\" \"${DEV_BIN_DIR}\\*.dll\")`

And report here the result?

**Comment by Rog360** [comment]
Replacing

     COMMAND xcopy /Y \"${LibFolder}\\*.dll\" \"${DEV_BIN_DIR}\\*.dll\")

with

     COMMAND xcopy /Y \"${LibFolder}\\*.dll\" \"$(OutDir)\\*.dll\")
Fixes the compile problem. Just doesn't move dll to release folder... :)

**Comment by cyberium** [comment]
@Rog360 try with the command i gave i think you missunderstood.
current code is :
`COMMAND copy \"${LibFolder}\\*.dll\" \"${DEV_BIN_DIR}\")`
should be replaced by
`COMMAND xcopy /Y \"${LibFolder}\\*.dll\" \"${DEV_BIN_DIR}\\*.dll\")`

Copy should work. It work here for me and i still want someone to confirm it fix the issue before pushing the fix.

Delete folders  (in bin folder and cmake cache) or rename it as described in the issue then generate new project file, launch visual studio clean the solution and rebuild it in debug mode and in release mode.

If it work i'll push the fix.

**Comment by Rog360** [comment]
LoL! Sorry about that. Being isolated must be getting to me..
I can confirm that it compiles with no errors with your fix. Thanks for your work... ;)
