### ISSUE TITLE
🐛 [Bug Report] Customize Quest Only Pick Up But Can't Turn In

### ISSUE THREAD

**Issue by lfself-code** [cmangos/issues#2158]
## 🐛 Bugreport
customize quest only pick up but can't turn in

### Version & Environment

Client Version: 

CMaNGOS Repo & Commit Hash: 

Database Repo & Commit Hash: 

Operating System: 

### Steps to reproduce
1.cteature_template.npcflag=2
2.new creature_questrelation.id=cteature_template.entry
3.new creature_questrelation.quest=quest_template.entry

### Crashlog

- None

**Comment by RazzorX** [comment]
creature_questrelation table is for a quest giver and
creature_involvedrelation table is for a quest ender

**Comment by al3xc1985** [comment]
1 create quest in quest_template
2 use what @RazzorX  said and voila works perfect

**Comment by jimmybrancaccio** [comment]
Hi @lfself-code Please clarify the purpose of this case.

**Comment by jimmybrancaccio** [comment]
Closing this out as we have not heard back from you. If this is still an issue please create a new GitHub issue with the full details as required by the bug reporting template. Thank you.
