### ISSUE TITLE
Did you tried to use Zerotier and cMangos?

### ISSUE THREAD

**Issue by FfKB** [cmangos/issues#2160]
### Version & Environment

Client Version: "3.3.5a" (WOTLK)

CMaNGOS Repo & Commit Hash:  (https://github.com/cmangos/wotlk-db/tree/XXXX)

Database Repo & Commit Hash: 9fd5477d54d40abca29b314581816cef0ee2992a

Operating System: Unix 19.10

### Steps to reproduce
1. Hello Guy, I had finally install and run cMangos perfectly, right now I am working in use Zerotier and Mangos in a Lan connection. But I have several troubles with that, did you guy have tried Zerotier before? Is it applicable?

**Comment by Muehe** [comment]
Sorry, but we do not provide support for third party applications, so I'll close this. I have taken a look at their website and it sounds like Zerotier is just a P2P VPN software, so it will probably work.
