### ISSUE TITLE
💬 [Support Request]

### ISSUE THREAD

**Issue by FfKB** [cmangos/issues#2161]
### Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash:  [TBC](https://github.com/cmangos/mangos-tbc/tree/XXXX)

Database Repo & Commit Hash: b57eef772aeb43cc9d003c56faead3cfa3da8840

Operating System: Linux 19

### Steps to reproduce
1. Hello Guys I had have experienced the WOTLK server then I decided to create a TBC. I have done it, but when I run the game with wine. the background screen is black and after loading the game (after login) All objects is not displayed ? do you know what happened?

**Comment by Muehe** [comment]
This sounds like a problem with your wine version, a missing library in wine, or a broken WoW client. Either of those things are out of scope for a support request here, so I'll be closing this issue. You can keep posting more questions here or on our Discord server though. However I can't promise they will be answered.

I'd recommend starting the game from the console (`wine WoW.exe`) and seeing if there is an error message that might explain your problem.

Just FYI, people got all three WoW-clients used for CMaNGOS to work under wine, so it's definitely possible.
