### ISSUE TITLE
🐛 [Bug Report] Invoc totems from Shaman -> Crash

### ISSUE THREAD

**Issue by Dromadoros** [cmangos/issues#2165]
## 🐛 Bugreport
Some shamans on server pop totems and crash the server. The tricky thing is that some players played long time on the server with this class and never crashed it but some of them spam crash with their totems.

![totem-bug](https://user-images.githubusercontent.com/11585507/79073052-9efd2780-7ce4-11ea-8bf2-6e230ee1d352.gif)

I didn't see any problems when trying to debug it, `Spell::cast` finished correctly without errors. And I can't see any errors on logs.

### Expected behavior
Totem needs to pop without crashing server

### Version & Environment
Client Version:  "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 591c5b159e061847781bb91823175505af2bb65b
Database Repo & Commit Hash: 19e079b92d2afe2915df77734beb27a22fc3dd98
Operating System: Ubuntu 16.04

### Steps to reproduce
1. Create a draenei shaman
2. .level 59 and .tele gm
3. Learn all spells from class
4. Spam invoc totems (you can choose any totem you want)
5. In some cases, server crash

### Crashlog

```
2020-04-12 15:12:52 WORLD: CMSG_CAST_SPELL, spellId - 10408, cast_count: 0 data length = 9
2020-04-12 15:12:52 Sending SMSG_SPELL_START id=10408
2020-04-12 15:12:52 Sending SMSG_SPELL_GO id=10408
2020-04-12 15:12:52 Spell 10408 Effect0 : 28 Targets: -, -, -
2020-04-12 15:12:52 Creature 9000684 used AI is TotemAI.
2020-04-12 15:12:52 Sending SMSG_SPELL_GO id=10405
2020-04-12 15:12:52 Spell 10405 Effect0 : 35 Targets: Creature (Entry: 7368 Guid: 9000684), -, -
2020-04-12 15:12:52 Aura: construct Spellid : 10405, Aura : 125 Target : 1 Damage : -30
2020-04-12 15:12:52 Holder of spell 10405 now is in use
```

**Comment by Dromadoros** [comment]
Hey,

I found the source of this issue, I got the T0 (https://classic.wowhead.com/item-set=187/the-elements) on my shaman. The core crash when `furious storm` procs (https://classic.wowhead.com/spell=27774/the-furious-storm) from the itemset on invoking totem.

I think the proc was fired by the totem and try to fire the spell from it -> crash. Just need to find where this logic is :)

**Comment by duduch123** [comment]
Have you find a solution ?

**Comment by Dromadoros** [comment]
To avoid crashes I did a dirty fix : on ProcDamageAndSpellFor I check if spell is totem, if yes -> do not continue the proc

`            if (execData.procSpell && execData.procSpell->TotemCategory[0] != 0) return;`

_File: UnitAuraProcHandler.cpp
Line: 548_

It's not the right solution but works for now

**Comment by killerwife** [comment]
Fixed proccing on vanilla and no longer crashes.
