### ISSUE TITLE
🐛 [Bug Report] NPC vendor bug Gorzeeki Wildeyes

### ISSUE THREAD

**Issue by mikemenasi** [cmangos/issues#2166]
## 🐛 Bugreport
Gorzeeki Wildeyes should not sell the items Xorothian Glyphs, Black Lodestone and J'eevee's Jar until the questl Imp Delivery is completed and you are on the Dreadsteed of Xoroth quest . Also he should only sell to warlocks. see https://classicdb.ch/?npc=14437#comments

### Version & Environment
- "1.12.1" (CLASSIC)

Client Version: 
- [CLASSIC](https://github.com/cmangos/mangos-classic/tree/XXXX)

**Comment by jimmybrancaccio** [comment]
@mikemenasi  Please provide _all_ of the information as requested in the bug report template.

**Comment by jimmybrancaccio** [comment]
Closing this as issue has not been updated with complete information. If this is still an issue please create a new issue in GitHub with the full details as requested by the bug reporting template. Thank you.
