### ISSUE TITLE
🐛 [Bug Report] MoveSpline:init_spline zero length spline, wrong input data?

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2171]
## 🐛 Bugreport
MoveSpline:init_spline zero leght spline, wrong input data?
that is the error I get with a fresh cmangos wotlk install after you start the server after a while it will give me this

### Expected behavior
No error

### Version & Environment
"3.3.5a" (WOTLK)

Client Version: 
[WOTLK](https://github.com/cmangos/mangos-wotlk/tree/85f28893813825bd922aca99a63830dddd857429

CMaNGOS Repo & Commit Hash: 
[WOTLK](https://github.com/cmangos/wotlk-db/tree/fd0727d778ea4a36bd5d465b2a12799705685804

Database Repo & Commit Hash: 
Win 7

Operating System: 

### Steps to reproduce
1. create fresh install server
2. wiat a few minutes
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by Grz3s** [comment]
it comes from.. active 'Kvadir invasion' event in borean tundra.. 
it happens when passengers are unboarded from vehicles... (error only happens when player is not arround) ... 
Its not game breaking error or smth (more anoying stuff)
Got some idea how to fix it. (and will jump on it soon)

**Comment by al3xc1985** [comment]
ok, perfect.. I do my best to report them all

**Comment by cyberium** [comment]
Do you still encounter this?

**Comment by al3xc1985** [comment]
hmm...dunno...I will let this one as notification on my git...and I after I am done with testing all spells and talents.,..I shall see... I might check it during my test and also come back with info

**Comment by al3xc1985** [comment]
ok...tried to look in logs for a while...and nothing seems to appear ..I guess it's fixed..closing this
