### ISSUE TITLE
wrong quests in log after update 💬 [Support Request]

### ISSUE THREAD

**Issue by rmzV** [cmangos/issues#2173]
### Version & Environment

  - "3.3.5a" (WOTLK)
after updating to last one relise version i get some old quest in quest log .. with was completed earlier... instead of having some new ones((
img:
https://dropmefiles.com/XG0Su

**Comment by rmzV** [comment]
came from [MangosdConf]
ConfVersion=2018092101

**Comment by rmzV** [comment]
cleared cache and wtf wirh no success

**Comment by Grz3s** [comment]
if u closed (pressed X )your server before log off your char.. it could roll back to point where you started last login... I'm using this often to work on scripts :)

**Comment by rmzV** [comment]
no. i always log out and then close server apk
anyways this quests was done like 3 yearsback(

where actually quest log quests are stored?
how they can be corrupted?

**Comment by rmzV** [comment]
may be it helpfuk: i downloaded and upgrade my wotlk db and used compiled server.. no new maps etc extractions was redone

**Comment by rmzV** [comment]
old quests looks like
https://dropmefiles.com/Vn5Y1

**Comment by rmzV** [comment]
its interesting
https://classic.wowhead.com/quest=8627/avengers-breastplate
i have 8627 completed and normal quests in 
character_queststatus
https://dropmefiles.com/KJRsZ

**Comment by rmzV** [comment]
reextracted data and this doesnot help(

**Comment by Grz3s** [comment]
theres not much that can be done... this is not db or core mechanicks issue... its more like u did revert smth by mistake ...
All i can sugest is to auto finish quests u already finished before:
use command:
`.q c 8627`   - must have it in quest log .. and then do the same for every quest u think u've done before... `.q c X`

**Comment by rmzV** [comment]
well i loaded old Db  and server version from back up.. and quests  was in place.. clean update and have the same issue

**Comment by rmzV** [comment]
i have only one coustume fix in db.. butdont think it affected this issue
UPDATE item_template SET StatsCount = 5, stat_type1 = 3, stat_value1 = 30000, stat_type2 = 4, stat_value2 = 30000, stat_type3 = 5, stat_value3 = 30000, stat_type4 = 6, stat_value4 = 30000, stat_type5 = 7, stat_value5 = 30000 WHERE entry = 38090;

**Comment by rmzV** [comment]
in db 8627 marked as completed
https://dropmefiles.com/f6NHG
can i check quest id inside game from quest log... may be some id confusion?

**Comment by rmzV** [comment]
i pulled new character_queststatus to the older one db and quest log is perfectly fine.. so the problem not in this table((

**Comment by rmzV** [comment]
okey. i removed this quests log out-login and old ones are in place J__J
