### ISSUE TITLE
🐛 [Bug Report] Illusions of Jandice Barov have incorrect damage multiplier

### ISSUE THREAD

**Issue by albeecode** [cmangos/issues#2176]
## 🐛 Bugreport
The Jandice Barov encounter in Scholomance spawns many illusions of Jandice Barov that hit for like 500+ damage on average which is scaled way to high.  Comparing the WOTLK database to the WOW Classic database reveals the following differences:

Classic:
```
SELECT Name, MinMeleeDmg, MaxMeleeDmg, DamageMultiplier FROM classicmangos.creature_template WHERE Name like '%jandice barov%';
```
Classic Output:
```
Name, MinMeleeDmg, MaxMeleeDmg, DamageMultiplier
'Jandice Barov', '99', '130', '5'
'Illusion of Jandice Barov', '106', '140', '**0.25**'
```

WOTLK:
```
SELECT Name, MinMeleeDmg, MaxMeleeDmg, DamageMultiplier FROM wotlkmangos.creature_template WHERE Name like '%jandice barov%';
```
WOTLK Output:
```
Name, MinMeleeDmg, MaxMeleeDmg, DamageMultiplier
'Jandice Barov', '152', '210', '3.5'
'Illusion of Jandice Barov', '159', '221', '**7.5**'
```

### Expected behavior
Damage should be more realistic.

### Version & Environment
Client Version: "3.3.5a" (WOTLK)

CMaNGOS Repo & Commit Hash: ac55f5cfc0cc804651c352b3ccf950ce9a01ae00
Database Repo & Commit Hash: 1a3337ce0377faa4e4c57447b2323bba7656d998

Operating System: Ubuntu 18.04.4 LTS

### Steps to reproduce
1. Enter scholomance and get to the Jandice Barov boss.
2. DPS her down until she spawns illusions
4. ...
5. Profit

### Proposed Solution
Add following SQL update script:
```
UPDATE wotlkmangos.creature_template
SET 
    DamageMultiplier = 0.25
WHERE Entry = 11439;
```

**Comment by esno** [comment]
fixed in https://github.com/cmangos/wotlk-db/commit/01b5aaca1becdca9bfc1f45d88e98696a983774a
