### ISSUE TITLE
TBC - Rogue Stealth breaks immediately when entering combat

### ISSUE THREAD

**Issue by cpinkus** [cmangos/issues#218]
Stealth is not supposed to immediately break upon entering combat. Combat should prevent stealth from being initiated, but it should not unstealth until damage is dealt to the rogue. This can become problematic in a number of situations.

**Comment by Phatcat** [comment]
@cpinkus seeing you havn't been active in more than a year this is wishful thinking but... could you check if the issue has been solved?

**Comment by cyberium** [comment]
Should be fixed
