### ISSUE TITLE
💬 [Support Request] mangosd.conf & realmd.conf

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2180]
## 💬 Support Request

I would suggest tot implement mangosd.conf and realmd.conf as trinitycore has it... it is very easy the way they do it is very easy to be read and write.. For instance, any new persson has to go up to read the list and find the right line to change it's value, and go back. and it is a go back and fort action.... instead you can have the configuration under each description.

for example:

```
#    TradeSkill.GMIgnore.Level
#        GM level starting from trade skill level requirement ignored.
#        Default: 4 (Console as noneone)
#

TradeSkill.GMIgnore.Level = 4

#    TradeSkill.GMIgnore.Skill
#        GM level starting from trade skill skill requirement ignored.
#        Default: 4 (Console as noneone)
#

TradeSkill.GMIgnore.Skill = 4

#    MinPetitionSigns
#        Min signatures count to creating guild (0..9).
#        Default: 9

MinPetitionSigns = 9
```

### Version & Environment
ALL

Client Version: 
ALL

CMaNGOS Repo & Commit Hash:  
ALL

Database Repo & Commit Hash: 
ALL

Operating System: 

### Steps to reproduce
1. edit mangosd.conf and realmd.conf
2.
3.
4. ...
5. Profit

**Comment by jimmybrancaccio** [comment]
@al3xc1985 Did you still need help/support with this issue? Is the problem still occurring for you?

**Comment by AnonXS** [comment]
Open a issue composing what "features" you post in this issue you want to have as config option, "MinPetitionSigns" or whatever.

you're not showcasing what makes Tcore config better then what we currently use.

**Comment by al3xc1985** [comment]
@AnonXS u missunderstood my ticket. It's about how we arrange settings in conf files.
Currently we have a part with full explain of every configuration and in the end we have all of them listed up.
```

#    TradeSkill.GMIgnore.Level
#        GM level starting from trade skill level requirement ignored.
#        Default: 4 (Console as noneone)
#
#    TradeSkill.GMIgnore.Skill
#        GM level starting from trade skill skill requirement ignored.
#        Default: 4 (Console as noneone)
#
#    MinPetitionSigns
#        Min signatures count to creating guild (0..9).
#        Default: 9
TradeSkill.GMIgnore.Level = 4
TradeSkill.GMIgnore.Skill = 4
MinPetitionSigns = 9
```

I am suggesting as the example above, to have the explainaition above each command sepparete. 
```
#    TradeSkill.GMIgnore.Level
#        GM level starting from trade skill level requirement ignored.
#        Default: 4 (Console as noneone)
#

TradeSkill.GMIgnore.Level = 4

#    TradeSkill.GMIgnore.Skill
#        GM level starting from trade skill skill requirement ignored.
#        Default: 4 (Console as noneone)
#

TradeSkill.GMIgnore.Skill = 4

#    MinPetitionSigns
#        Min signatures count to creating guild (0..9).
#        Default: 9

MinPetitionSigns = 9
```

**Comment by AnonXS** [comment]
Search function?

**Comment by al3xc1985** [comment]
that is not the point of my request, is for having the file organized and easy to acces the information about each config what it does in a easier way. It's easier to see the description of config on top of each configuration setting, than having all description above and u allways have to scroll up to see which option what it does.

From your point it's easy cause u work with them everyday, but thinlk of it from a newby perspective.

Anyways, if u think is worth the investment in such arangement it;s ok, if not it;s also ok with me.
