### ISSUE TITLE
🐛 [Bug Report] Shade of Akama - Spawn loop

### ISSUE THREAD

**Issue by Valkirie** [cmangos/issues#2183]
## 🐛 Bugreport
During the Black Temple, Shade of Akama encounter, npc_creature_generatorAI::UpdateAI() will be triggered on Akama channeling and TrySummoning() function will be called, spawning adds at every tick. Flooding the area with hundreds of creatures.

### Expected behavior
TrySummoning() should be called every ~35 seconds.

### Version & Environment
Client Version: 2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/tree/master

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/master

Operating System: Win 10

### Steps to reproduce
1. Start Shade of Akama Encounter
2. Wait for Akama to start channeling the Shade.

![image](https://user-images.githubusercontent.com/934757/80315909-f201cf00-87fa-11ea-9bb9-1e675dab6edf.png)

**Comment by Valkirie** [comment]
`
if (m_spawn)
{
	if (m_uiSpawnTimer < diff)
	{
		TrySummoning();
		m_uiSpawnTimer = 35000;
	}
	else
		m_uiSpawnTimer -= diff;
}
`

**Comment by al3xc1985** [comment]
@killerwife you pretty overhaul this fight and including this, didn't u?
