### ISSUE TITLE
🐛 [Bug Report] Creature missing Buff

### ISSUE THREAD

**Issue by miraco** [cmangos/issues#2185]
## 🐛 Bugreport
Creatures with EVENT_T_FRIENDLY_MISSING_BUFF only Buff creatures when they are in Combat.

### Expected behavior
NPCs like Shadowmoon Acolyte should also Buff NPCs when they are not in Combat.

### Version & Environment

Client Version: 
2.5.3

CMaNGOS Repo & Commit Hash: 

Database Repo & Commit Hash: 

Operating System: 
Win XX
### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by miraco** [comment]
A solution would be removing this line:
https://github.com/cmangos/mangos-tbc/blob/master/src/game/AI/EventAI/CreatureEventAI.cpp#L448

But i am not sure this behavier is working at every npc.

**Comment by AnonXS** [comment]
16 = EVENT_T_FRIENDLY_MISSING_BUFF:
Parameter 5: InCombat  - 0 - Only in combat. 1 - Anytime. 2 - Only out of combat.
