### ISSUE TITLE
Rogue: Distract Does Not Work Properly on Pathing NPC's

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#219]
It seems that when an npc is NOT stationary, Distract will not cause them to face the proper direction (center of the area effect). Distract works properly on stationary npc's. This could be a problem with npc orientation while pathing, or it could be a problem with Distract itself. This is tested on a newly-updated cmangos-tbc.

**Comment by AnonXS** [comment]
Linked to https://github.com/cmangos/issues/issues/981?
https://github.com/cmangos/mangos-tbc/commit/d23d2f805acbd2073507f473f37e8938d18cb575

**Comment by jimmybrancaccio** [comment]
@AnonXS Do you know if this is still an issue which needs to be fixed?
