### ISSUE TITLE
🐛 [Bug Report] Warlock Talent Backdraft increases cast time not reduces

### ISSUE THREAD

**Issue by albeecode** [cmangos/issues#2191]
## 🐛 Bugreport
When Backdraft proc is active casting time is increase not decreased.  It seems to be about 3 times longer cast time.  I'm wondering if a value is 30 instead of .30

### Expected behavior
Talent tooltip:
![image](https://user-images.githubusercontent.com/32618169/81022146-e6398c80-8e3a-11ea-821b-258e785109b4.png)

### Version & Environment

Client Version: 3.3.5a (WOTLK)

CMaNGOS Repo & Commit Hash: ac55f5cfc0cc804651c352b3ccf950ce9a01ae00

Database Repo & Commit Hash: 1a3337ce0377faa4e4c57447b2323bba7656d998

Operating System: Ubuntu 18.04

### Steps to reproduce
1. Put 3 points into Backdraft talent
2. Cast Conflagrate to trigger
3. Witness increased cast time of Chaos Bolt
4. ...
5. Profit

### Crashlog

- None

**Comment by albeecode** [comment]
It appears this may be related to when Backlash procs at the same time.  I'm still testing to figure out 100% exactly what causes it.  but it appears to be when both procs occur together, then Backdraft will increase cast time unless dispelled.

**Comment by killerwife** [comment]
Seems to be fixed after testing
