### ISSUE TITLE
🐛 [Bug Report] Fire Nova Totem of level 7

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2193]
## 🐛 Bugreport
Totem does not properly cast spells, only Fire Nova Totem of level 7 has this problem.
Log print: 2020-05-05 22:51:25 ERROR:CastSpell: unknown spell id 0 by caster: Creature (Entry: 15483 Guid: 9000837)

![bug1](https://user-images.githubusercontent.com/3367999/81081728-e31acb00-8f24-11ea-9af2-b2851132301f.gif)

Client version:
2.4.3

Commit hash:
Newest

Database version:
Newest

Operating system:
centos

**Comment by ckj777** [comment]
how can I fix it? 
I have the same bug.

**Comment by jimmybrancaccio** [comment]
@aleigood Please provide _all_ of the information as requested in the bug report template.

**Comment by jimmybrancaccio** [comment]
Closing this as issue has not been updated with complete information. If this is still an issue please create a new issue in GitHub with the full details as requested by the bug reporting template. Thank you.
