### ISSUE TITLE
🐛 [Bug Report] The sentry totem is too far away from the caster.

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2194]
## 🐛 Bugreport
Sentry totem cannot be used correctly, too far away from the caster. Even if the totem is cancelled, the countdown buff still exists.

Client version:
2.4.3, 3.3.5

Commit hash:
Newest

Database version:
Newest

Operating system:
CentOS

**Comment by jimmybrancaccio** [comment]
@aleigood Please provide _all_ of the information as requested in the bug report template.

**Comment by jimmybrancaccio** [comment]
Closing this as issue has not been updated with complete information. If this is still an issue please create a new issue in GitHub with the full details as requested by the bug reporting template. Thank you.
