### ISSUE TITLE
🐛 [Bug Report] Stone Guard Zarg has incorrect title at Hall of Legends, Orgrimmar

### ISSUE THREAD

**Issue by TarasHots** [cmangos/issues#2195]
## 🐛 Bugreport
Stone Guard Zarg <Food and Drink>, looks like he should not be at Hall of Legends, Orgrimmar.

### Expected behavior
https://classic.wowhead.com/npc=12794/stone-guard-zarg

### Version & Environment
Client Version:  "1.12.1" (CLASSIC)
CMaNGOS Repo & Commit Hash: [CLASSIC](https://github.com/cmangos/mangos-classic/tree/4e1f3a0bbeee48f28fe034630f2e0ce875e724d3)
Database Repo & Commit Hash: [CLASSIC](https://github.com/cmangos/classic-db/tree/24c1198b61ea295242d1b9d5c1d343a12bf7df26)
Operating System: Linux Flavor (Mint 19)

### Steps to reproduce
1. Enter Hall of Legends in Orgrimmar
2. Go to the left
3. See `Stone Guard Zarg <Food and Drink>` is chilling
4. Talk to him and wonder why there are no food and drinks (he is selling weapons)
5. Profit

### Crashlog

- None

### Screenshot
![image](https://user-images.githubusercontent.com/2003618/81446011-55381d80-917a-11ea-85bd-6f0e71125e0b.png)

**Comment by cala** [comment]
Thank you for this report.

**Comment by TarasHots** [comment]
@cala I guess I can try to fix this. As far as I know there's one creature template with unique id. Later npc can be placed several times in world and each of them can be differentiated by guid. The question is: can we change second name for one of the copies, or we need new creature template?

**Comment by cala** [comment]
From what I see, this NPC is in the wrong place (it was moved in Hall of Legends in patch 2.0.1) and thus sells the wrong items.

He should then be moved to its correct location in Alterac Valley, this means update his entry in `creature` table for map and positions (though correct values are unkown to me).
Also, its `npc_vendor` entry should be updated (depending on how his vendor item list is set).

**Comment by Tobschinski** [comment]
He is in the correct spot, just the vendor list is wrong. (and the weapon)
