### ISSUE TITLE
🐛 [Bug Report] You're Able to Obtain Unobtainable Quests

### ISSUE THREAD

**Issue by RazzorX** [cmangos/issues#2197]
## 🐛 Bugreport
You can obtain unobtainable quests to your quest book.

### Expected behavior
You can only turn-in certain types of quests but not received.

### Version & Environment
Client Version: "3.3.5a" (WOTLK)

CMaNGOS Repo & Commit Hash: 
  - [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/79f2b26f44fa25c8d1fce065b1fedbc9e76925dc)

Database Repo & Commit Hash: 
  - [WOTLK-DB](https://github.com/cmangos/wotlk-db/tree/8e9a27c18114fb8b65ec86568c582e712ba96a12)

Operating System: 
Win 7 64bit

### Steps to reproduce
1. You need a Lv12 Char or higher
2. You need 60 or more wool in your bag
3. Teleport to Creature Mistina (Alliance) or Rashona (Horde)
4. Click on "A Donation of Wool" and then on Continue but NOT on Complete Quest
5. Press ESC and Log Out then Log In
6. You will now have this Quest in your Questbook...

### Misc
- Classic / TBC can also be affected
- It seems that (all?) quests with Method = 0 + OfferRewardText + RequestItemsText have this issue.
- Quests with Method = 0 + OfferRewardText (without RequestItemsText) like Hallow's End quests Candy Bucket, don't have this issue

- Sorry for my english, if you have any questions, please ask.

**Comment by nate123456** [comment]
After giving my character 60 wool, then selecting the quest, pressing continue, but not complete, then logging out then logging back in the quest is in my quest log despite that fact that it should not be acceptable as OP indicated.

The `Needs Replication` tag can be removed.

**Comment by killerwife** [comment]
For brevity, I tested this on TBC and i could not for the love of god reproduce. Moving on to wotlk

**Comment by RazzorX** [comment]
I ran some tests after your commit, but couldn't reproduce this issue anymore.
Thanks for the fix!
