### ISSUE TITLE
🐛 [Bug Report] World's End Tavern - L70ETC Concert Can be Heard Outside of of the World's End Tavern

### ISSUE THREAD

**Issue by jimmybrancaccio** [cmangos/issues#2198]
## 🐛 Bugreport

When the event "World's End Tavern - L70ETC Concert" starts you can move yourself outside of the World's End Tavern (I've made it to the Tuurem) and you can still hear the band playing. 

https://www.youtube.com/watch?v=1ST8glysvEQ

### Expected behavior

I would expect that you can only hear the song while you're inside the World's End Tavern.

### Version & Environment

Client Version: 3.3.5a

CMaNGOS Repo & Commit Hash: `2034df3ab5c495ad012f19fb6b03710eb09965ab`

Database Repo & Commit Hash:  `92e80ed33dc33da94ac401b49b8ddadb003f4a7c`

Operating System:  Ubuntu 19.10

### Steps to reproduce
1. Go to the World's End Tavern every 3 hours (00:00, 03:00, 06:00, 09:00, 12:00, 15:00, 18:00, and 21:00).
2.  The event should start, move yourself outside of the World's End Tavern. Go as far away as you can get, by foot or by mount.
3.  Note that you can continue to hear the band play the song.
4. ...
5. Profit 💸 

Of note, I had to manually start the event using `.event start 60` but the issue can still be replicated if you let the event start organically.

### Crashlog

- None

**Comment by Grz3s** [comment]
because sound is played by player not by source...  so u can go everywhere u like and still you will hear it ;)
This can be fixed by smth like this:
```sql
UPDATE `creature_ai_scripts` SET `action1_type` = 53, `action1_param1` = 19999 WHERE `id` = 2383001 AND `event_param1` = 9400 AND `event_param2` = 9400;
DELETE FROM dbscripts_on_relay WHERE id IN (19999);
INSERT INTO dbscripts_on_relay (id, delay, command, datalong, datalong2, datalong3, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(19999,0,16,11803,2,0,0,0,0,0,0,0,0,0,0,0,0,'Part of L70ETC - Power of the Horde Concert: play Sound');
```
try it.. and let me know...

**Comment by jimmybrancaccio** [comment]
@Grz3s That's MUCH better! I would consider this resolved using that SQL.

**Comment by esno** [comment]
fixed in https://github.com/cmangos/wotlk-db/commit/63db780ddbd7dfd5ef493cfdd68a934cd3a6feca
