### ISSUE TITLE
🐛 [Bug Report] World's End Tavern - L70ETC Concert Does Not Start Every 3 Hours As Expected

### ISSUE THREAD

**Issue by jimmybrancaccio** [cmangos/issues#2199]
## 🐛 Bugreport

I would expect this event to start at 00:00, 03:00, 06:00, 09:00, 12:00, 15:00, 18:00, and 21:00. However according to my server logs from today:

```
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 00:48:01 GameEvent 59 "World's End Tavern - L70ETC Concert Announce" started.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 01:00:01 GameEvent 60 "World's End Tavern - L70ETC Concert" started.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 01:05:01 GameEvent 60 "World's End Tavern - L70ETC Concert" removed.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 01:12:01 GameEvent 59 "World's End Tavern - L70ETC Concert Announce" removed.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 03:48:01 GameEvent 59 "World's End Tavern - L70ETC Concert Announce" started.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 04:00:01 GameEvent 60 "World's End Tavern - L70ETC Concert" started.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 04:05:01 GameEvent 60 "World's End Tavern - L70ETC Concert" removed.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 04:12:01 GameEvent 59 "World's End Tavern - L70ETC Concert Announce" removed.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 06:48:01 GameEvent 59 "World's End Tavern - L70ETC Concert Announce" started.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 07:00:01 GameEvent 60 "World's End Tavern - L70ETC Concert" started.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 07:05:01 GameEvent 60 "World's End Tavern - L70ETC Concert" removed.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 07:12:01 GameEvent 59 "World's End Tavern - L70ETC Concert Announce" removed.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 09:48:01 GameEvent 59 "World's End Tavern - L70ETC Concert Announce" started.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 10:00:01 GameEvent 60 "World's End Tavern - L70ETC Concert" started.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 10:05:01 GameEvent 60 "World's End Tavern - L70ETC Concert" removed.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 10:12:01 GameEvent 59 "World's End Tavern - L70ETC Concert Announce" removed.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 12:08:13 GameEvent 60 "World's End Tavern - L70ETC Concert" started.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 12:08:34 GameEvent 60 "World's End Tavern - L70ETC Concert" removed.
Frostwolf_2020-05-07_10-17-44.log:2020-05-09 12:13:50 GameEvent 60 "World's End Tavern - L70ETC Concert" started.
```

Here's the date output from my server:

```
$ date
Sat 09 May 2020 12:39:30 PM CDT
```

**EDIT:** 

And here's another log snippet and screenshot. It looks like the announce event started at 12:48,and sure enough the band started at 13:00 which is an hour late.

```
12:48:01 GameEvent 59 "World's End Tavern - L70ETC Concert Announce" started.
```
![Screen Shot 2020-05-09 12 52 31](https://user-images.githubusercontent.com/405585/81481249-3d9d7b00-91f4-11ea-9d0d-7a7706c78075.png)

![Screen Shot 2020-05-09 12 56 11](https://user-images.githubusercontent.com/405585/81481282-7c333580-91f4-11ea-9869-4d1a6afcea3e.png)

![Screen Shot 2020-05-09 12 57 34](https://user-images.githubusercontent.com/405585/81481308-ae449780-91f4-11ea-9596-276d7968b0a3.png)

![Screen Shot 2020-05-09 13 00 03](https://user-images.githubusercontent.com/405585/81481348-08ddf380-91f5-11ea-811a-b790b9fee465.png)

### Expected behavior

It should start these events every 3 hours, which I would expect to be 00:00, 03:00, 06:00, 09:00, 12:00, 15:00, 18:00, and 21:00.

> Since patch 2.4.3, The Artists Formerly Known as Level 80 Elite Tauren Chieftain perform in the World's End Tavern every three hours on the hour, eight shows per day. They play "Power of the Horde".

- From [WoWWiki](https://wowwiki.fandom.com/wiki/World%27s_End_Tavern#The_Artists_Formerly_Known_as_Level_80_Elite_Tauren_Chieftain)

### Version & Environment

Client Version:  3.3.5a

CMaNGOS Repo & Commit Hash:  `2034df3ab5c495ad012f19fb6b03710eb09965ab`

Database Repo & Commit Hash:  `92e80ed33dc33da94ac401b49b8ddadb003f4a7c`

Operating System:  Ubuntu 19.10

### Steps to reproduce
1. Go to the World's End Tavern at one of the following times - 00:00, 03:00, 06:00, 09:00, 12:00, 15:00, 18:00, and 21:00. I went at 12:00.
2. Note that the band does not come on stage to play. In fact I ended up seeing Perry Gatner instead.
3. Cry because your favorite band didn't come and play at the right time.
4. ...
5. Profit

### Crashlog

- None

**Comment by Grz3s** [comment]
fixed
