### ISSUE TITLE
🐛 [Bug Report] Compilation error when compiling with -DPOSTGRESQL=1

### ISSUE THREAD

**Issue by seirl** [cmangos/issues#2200]
## 🐛 Bugreport

CMangos doesn't compile with `-DPOSTGRESQL=1`:

```
In file included from /home/.../mangos-wotlk/src/shared/Database/DatabaseEnv.h:30,
                 from /home/.../mangos-wotlk/src/shared/pchdef.h:34,
                 from /home/.../mangos-wotlk/build/src/shared/CMakeFiles/shared.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/.../mangos-wotlk/src/shared/Database/QueryResultPostgre.h:85:14: error: ‘void QueryResultPostgre::EndQuery()’ marked ‘override’, but does not override
   85 |         void EndQuery() override;
      |              ^~~~~~~~
In file included from /home/.../mangos-wotlk/src/shared/Database/DatabaseEnv.h:32,
                 from /home/.../mangos-wotlk/src/shared/pchdef.h:34,
                 from /home/.../src/mangos-wotlk/build/src/shared/CMakeFiles/shared.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/.../mangos-wotlk/src/shared/Database/DatabasePostgre.h:55:14: error: ‘bool PostgreSQLConnection::_Query(const char*, PGresult**, uint64*, uint32*)’ marked ‘override’, but does not override
   55 |         bool _Query(const char* sql, PGresult** pResult, uint64* pRowCount, uint32* pFieldCount) override;
      |              ^~~~~~
```

### Expected behavior

CMangos should compile.

### Version & Environment

Client Version: not using any client

CMaNGOS Repo & Commit Hash: mangos-wotlk 347ef6dae82511cb83b4c5b6f192b65f7fc3167b

Database Repo & Commit Hash: not using any database

Operating System: ArchLinux

### Steps to reproduce

1. `cmake .. -DPOSTGRESQL=1`
2. `make`

### Crashlog

- None

**Comment by jimmybrancaccio** [comment]
@seirl Please provide more information, especially regarding your PostgreSQL environment and installed packages.

**Comment by seirl** [comment]
I'm struggling to see what the PostgreSQL environment has to do with this error, it's a compilation error from mangos internal code. I'm pretty sure the relevant thing here is my compiler version? (clang version 10.0.1)

**Comment by jimmybrancaccio** [comment]
Hello, please provide the requested information. Thank you.

**Comment by seirl** [comment]
Look, I'm not gonna waste time on arbitrary bureaucracy that is unneeded to reproduce the issue. There is a very obvious issue in internal code that takes two minutes to reproduce, and I gave you the commands to reproduce it.

It's a bug in purely internal code. You have one class which overrides a method from another base class, but the method from the original base class doesn't exist anymore. It has nothing to do with my PostgreSQL version whatsoever. I have a lot of respect for the project maintainers' time, but honestly I find it a bit disrespectful that you ask arbitrary info that is clearly unneeded if you look at what the error message says.

**Comment by jimmybrancaccio** [comment]
Closing as I was unable to replicate this. Worked fine on my end.

**Comment by seirl** [comment]
Have you tried with a more recent compiler? This error only happens for recent compiler versions (for GCC it's > 7.2.0).

Again, the error is easy to see here. The code is indeed overriding a method that doesn't exist in the base class.

**Comment by jimmybrancaccio** [comment]
After further discussion in Discord the development team will be removing the PostgreSQL build flag for the time being in the near future.
