### ISSUE TITLE
🐛 [Bug Report] 2nd Group Shattered Halls

### ISSUE THREAD

**Issue by miraco** [cmangos/issues#2204]
## 🐛 Bugreport
This is a list with Bugs of the second Legionnaire Group in Shattered Halls.

Spawns:
This are groups with 2 NPCs
- [x] On normal 1 Savage or Heaven + 1 Darkcaster/Acolyte/Brawler
- [x] ON Heroic 1 Heaven + 1 Darkcaster/Acolyte/Brawler
- [ ] The Savage/Heaven can stand left or right
![Spawn](https://user-images.githubusercontent.com/6261245/81391356-3fe0d600-911d-11ea-9152-4486c49dd010.png)

AI:
- [x] on Death every creature of  a legionnaire group "throw" a custom event to legionnaire. Currently every legionnaire in range gets this event. Just the leading legionnaire should get it
- [x] Legionnaire should spawn a new mob when a friendly creature dies, based on their position
- [x]  Acolytes buff friendly creatures with shadow resist, this should also get buffed OOC 
- [x] Acolytes should have caster AI.
- [x] Darkcaster should have caster AI.

- [x] Caster NPCs that get silenced should also have their spellschool locked. 

### Version & Environment

Client Version: 
2.4.3

I finaly found some time to work at shattered halls again. This group handling is so complexe thats why all of this is in one pull request.

**Comment by miraco** [comment]
https://github.com/cmangos/mangos-tbc/pull/391
https://github.com/cmangos/tbc-db/pull/778

**Comment by jimmybrancaccio** [comment]
Hello @miraco Please create a new unique issue for each individual bug. I'll leave this open for a week or so and will then close this issue out.

**Comment by miraco** [comment]
Since corona kinda hit me hard i stoped working at this. Maybe i will find some time to continue this in the future.
