### ISSUE TITLE
🚀 [Feature Request] UPDATED documentation

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2206]
## 🚀 Feature

As I try and strugel to learn to code in sql based on stuff that I find on vids, wowhead (not yet wow account) and to propose this fixes, I came to a wall of incomplete documentation.

MOREOVER the tools made in past like eventAi and any other db editors are REALLY REALLY out of date...
We need that if we want more devs... ppl would ask less question, and disturb devs less.

I took a lookt trinity core smartAI editor..OMG is super updated ,,but ours? NONE

Ty and I am somehow sorry that I am not a coder to help in C++ way.. I am trying to learn to code in sql

**Comment by jimmybrancaccio** [comment]
Closing this out as feature requests are meant for core/code. Anyone is welcome (and encouraged) to update and add to the documentation of CMaNGOS.
