### ISSUE TITLE
🐛 [Bug Report] Dispel Mechanics on Debuffs With Stacks

### ISSUE THREAD

**Issue by SuddenDeath** [cmangos/issues#2208]
## 🐛 Bugreport
Currently if target has 5 stacks of wound poison up and 1 crippling poison, it'll count as each stack as an individual debuff when casting cure/abolish poison...
Meaning 1/6 chance to remove crippling poison.

### Expected behavior
dispel rolls shouldn't account for debuff stacks, in this case it should be 1/2 chance to remove crippling poison.

Same goes for magic effects such as winter's chill debuffs etc, goes for all debuffs.

### Version & Environment
Client Version: 
  - "2.4.3" (TBC)
  - "3.3.5a" (WOTLK)

### Proof
http://web.archive.org/web/20190801065402/http://www.arenajunkies.com/topic/32697-why-does-devour-always-get-the-sheep

http://web.archive.org/web/20190801065403/http://www.arenajunkies.com/topic/140581-blizzard-winters-chill-5-stacks-at-once/page-4#entry2097447

http://web.archive.org/web/20190801065400/http://www.arenajunkies.com/topic/114054-do-you-stack-winters-chill-vs-warlocks/

Obviously any video evidence of this would always suffer from the rng factor and wouldn't be reliable.

**Comment by jimmybrancaccio** [comment]
@SuddenDeath Please provide _all_ of the information as requested in the bug report template.

**Comment by jimmybrancaccio** [comment]
Closing this as issue has not been updated with complete information. If this is still an issue please create a new issue in GitHub with the full details as requested by the bug reporting template. Thank you.
