### ISSUE TITLE
🐛 [Classic] Group loot rules are not used for most chests

### ISSUE THREAD

**Issue by canidae** [cmangos/issues#2210]
## 🐛 Bugreport
When looting chests while in a party, group loot rules are not applied, thus players will not be able to roll for items.

### Expected behavior
Group loot rules should apply to most chests.

### Version & Environment
Client Version: 1.12.1
CMaNGOS Repo & Commit Hash: [CLASSIC](https://github.com/cmangos/mangos-classic/tree/70320ce824107ea15de6625c6c67085d1507ad00)
Database Repo & Commit Hash: [CLASSIC](https://github.com/cmangos/classic-db/tree/f162c49cec1f369a2c4a6129cba59adecbb7884f)
Operating System: Ubuntu Linux (server), Arch Linux (client)

### Steps to reproduce
1. Create party, leave group loot rules to default settings.
2. Teleport party to a common chest (there's one just outside Stormwind which may contain good or better items). Or spawn a chest, however you do that.
3. Have one player loot chest.
4. Observe that green or better items will not be rolled for (if no green or better item in chest, try another chest).
5. Profit (for the player that looted the chest, but nobody else).

### Crashlog
- None

**Comment by canidae** [comment]
According to the wiki for [gameobject_template](https://github.com/cmangos/issues/wiki/gameobject_template) the field data15 determines whether group loot should be applied to chests. For most chests this value is set to 0.
I executed the following query on my database, and that gives group loot on the most common chests:
`UPDATE gameobject_template SET data15 = 1 WHERE name IN ("Battered Chest", "Large Battered Chest", "Large Iron Bound Chest", "Large Mithril Bound Chest", "Large Solid Chest", "Solid Chest");`
This is however not a perfect solution. It may include chests that shouldn't have group loot rules, and there's likely several other chests it doesn't include that should have group loot rules.

**Comment by Warlockbugs** [comment]
One of The Burning Crusade changes is addition of group loot to random chests found in the world. The correct vanilla group gameplay policy for chests is rolling for chests manually by typing `/roll`.
