### ISSUE TITLE
🐛 [Bug Report] [TBC] Grouping issue, causing de-syncs

### ISSUE THREAD

**Issue by stealthgun** [cmangos/issues#2213]
## 🐛 Bugreport
We have an issue where if someone forms a group larger then 3 players one player always de-syncs and in the end needing to disconnect. 

The server produces no logs from this, even running on purely internal clients the issues still happens the moment the 4th player is invited.

It starts by the chat not updating for you, but other players still see you talk, then your abilities stop working and then nothing works anymore and you need to force quit the game.

Have looked into the Router settings but nothing seems to work, so the assumption is that its a core issue. 

### Expected behavior
Be able to form groups larger then 3 players without de-syncing

### Version & Environment
  - "2.4.3" (TBC)

Client Version: 2.4.3
CMaNGOS Repo & Commit Hash: cmangos/mangos-tbc@19d3644

Database Repo & Commit Hash: cmangos/tbc-db@2791ec8

Operating System: Win 2019

### Steps to reproduce
1. Form a group
2. Invite 3-4 other players

### Crashlog
- None

**Comment by stealthgun** [comment]
After more testing, the problem lies in the "Server -> Client" communication. I've had one client disconnect/desync but when I ran around you can still see the character run around on the other clients. But the desynced client did not see anything update. But when I clicked exit game (or logout) on the client the server saw him as not on the server anymore, so the character would leave the group as normal. 

But the client does nothing (you can still run around) and needs a forced exit to exit the game.

**Comment by SilvioDoMine** [comment]
Thanks for the detailed report, @stealthgun. Could you provide us some video or animated gif showing this issue? Would be even more helpful to the devs look into

**Comment by stealthgun** [comment]
> Thanks for the detailed report, @stealthgun. Could you provide us some video or animated gif showing this issue? Would be even more helpful to the devs look into

Will try and replicate it and then share a video link

**Comment by stealthgun** [comment]
Ive replicated it.

So the server shows now errors (the last error is unrelated) 
![desync](https://user-images.githubusercontent.com/129263/83193929-1ae9ec80-a138-11ea-9fa6-cc96ccf3ac90.png)

I got an error crash on one client that might be related
[2020-05-28 22.50.52 Crash.txt](https://github.com/cmangos/issues/files/4698281/2020-05-28.22.50.52.Crash.txt)

Here is the video, the first part is the connected client running in front of the descync (Admintest) client (you can see that there is no update on the descync client).
After that I swith the input and you can clearly see that the (desync) character is moving on the connected client.
(url is incomming)

**Comment by atahual** [comment]
Had the same thing happen on cmangos vanilla running on a Raspberry Pi 4 with a Party size of just 2 Players.
Maybe its Hardware dependent? Will try to look further into it.

Interesting note, my friend tried to learn a Skill as it happened and after relaunching the client he had the Skill already learned which matches with the desynced Player still moving in the Video.
So basically the Client is still sending information to the Server but is presumably not getting anything from the Server.

**Comment by Yatzii93** [comment]
I have a feeling it's related to the multi-threading. It seemed to occur once it was implemented. How about trying to set the MapUpdate.Threads to 0 in the mangosd config file.

MapUpdate.Threads = 0

See if it's still an issue then.

**Comment by stealthgun** [comment]
@Yatzii93 Will try that with the server reboot tonight, will have an update on it soon.

**Comment by canidae** [comment]
This sounds very much like an issue we've experienced in classic core as well. Some clients seemingly stop receiving data from the server. They often can't even log out, they have to kill the client from the OS. Logging in again fixes the issue.
This _seems_ to happen more frequently when anyone enters/exits an instance, but I don't know if it's related. Once all party members were within the same instance, there were no such issues.
I'll also try setting MapUpdate.Threads to 0.

**Comment by SilvioDoMine** [comment]
Anyone has any response if this is multithreading related? The MapUpdate.Threads = 0 did anything?

**Comment by stealthgun** [comment]
@SilvioDoMine For me it did not, when I used .tele kara on a GM account mutiple times I got the descync issue. And I've seen it happening when questing aswell all since the MapUpdate.Threads = 0 has been enabled.

**Comment by canidae** [comment]
Not very helpful, but I unsuccessfully tried to replicate the issue while running a server instance within Valgrind/GDB. No luck, but I only tested for about an hour.

**Comment by Warlockbugs** [comment]
Not related to groups, its update size issue. Should be fixed with split reintroduction.
