### ISSUE TITLE
🐛 [Bug Report] Mmap Shallow Water Makes Creatures Evade

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2214]
## 🐛 Bugreport
If you go into shallow watters and aggro a creature the creature will evade. If you activate NormalizeZ option the creature will come to margin of the land, doesn;t enter the water, and will evade very soon

It was also disccused here:
https://github.com/cmangos/mangos-tbc/commit/1db4c57b68f96760a52cd7fd583e6fa024ea5eda

### Expected behavior

The creature should be able enter shallow water and attack you
### Version & Environment

ALL
Client Version: 
All client versions but tested on 2.4.3

CMaNGOS Repo & Commit Hash: 
c88567bb53fc7ba630e7950c7bab592e8ab0c5ad

Database Repo & Commit Hash: 
f45eebdc9ec24c5b6eca447d713cf579a5163ee2

Operating System: 

### Steps to reproduce
1. create a troll or orc or anythig..
2. tele in senjin vinllage in durotar and head east to zalzane pre islands
3. when you exit senjin village you will head towards zalzane... on the way you shall find very very small islands with tiger and raptors on them
4. ...aggro them while standing on shallow water win NormalizeZ = 0
4b. aggro them while standing on shallow water win NormalizeZ = 1
5. Profit

### Crashlog

- None

**Comment by BlackBoar101** [comment]
have this bug too.

**Comment by aleigood** [comment]
There's the same problem with Darkshore Thresher on the Darkshore in WotLK.

**Comment by Grz3s** [comment]
fixed:
https://github.com/cmangos/mangos-wotlk/commit/1ecf38129af4a39959d3d061b8b89ff3e7380f2d
