### ISSUE TITLE
🐛 [Bug Report] Quest Morbent Fel item Morbent Bane not working

### ISSUE THREAD

**Issue by stealthgun** [cmangos/issues#2215]
## 🐛 Bugreport
For the quest Morbent Fel (id 55) the Item Morbent's bane (id 7297) does not affect the npc.
And there for the quest cannot be completed.

![WoWScrnShot_052920_145939](https://user-images.githubusercontent.com/129263/83258600-d3567580-a1b6-11ea-9959-10c3a776f17c.jpg)

### Expected behavior
Morbent's bane should cast a weakness buff on the npc and make him non elite, if you kill him the quest shoul be completed.

https://classic.wowhead.com/quest=55/morbent-fel

### Version & Environment
  Client Version - is required
  Valid values are:
  - "2.4.3" (TBC)
Client Version: 8606

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/commit/60dfabf281510a0980379c0bc1ade04dd301857e

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/commit/2791ec86dea22c1c72fdbebaacffa8f8a76dc5b9

Operating System: Win 2019

### Steps to reproduce
1. Accept quest 55
2. Use item on NPC
3. Kill npc

**Comment by stealthgun** [comment]
The Aura does get removed, wanted to add that. But after you kill him the quest does not update, there are no server errors created.

**Comment by stealthgun** [comment]
@kelbren Thanks will check out of it helps for me aswell.

**Comment by stealthgun** [comment]
Just tested it and it works! this seems to solve the issue.

**Comment by Grz3s** [comment]
db issue ... fixed here: https://github.com/cmangos/wotlk-db/commit/bddcd11a1e1a24b347d9364fcc6f3d2e79d6ca9b
