### ISSUE TITLE
🐛 [Bug Report] Quest The Escape does not finish correctly

### ISSUE THREAD

**Issue by stealthgun** [cmangos/issues#2216]
## 🐛 Bugreport
The Escort quest The Escape (id 863) does not finish correctly, in the end the NPC should blow up and finish the quest but this does not happen The Npc stand in the final position for a a while and just disappears not completing the quest.

![Screenshot from 2020-05-29 00-23-42](https://user-images.githubusercontent.com/129263/83259097-be2e1680-a1b7-11ea-8932-06322bcfc7db.png)
![Screenshot from 2020-05-29 00-23-55](https://user-images.githubusercontent.com/129263/83259103-bff7da00-a1b7-11ea-9478-0d27478b8adb.png)

### Expected behavior
After you escorted the NPC to the final position the NPC should blow up and finish the quest.
**https://classic.wowhead.com/quest=863/the-escape**

### Version & Environment
Client Version: 2.4.3" (TBC)

CMaNGOS Repo & Commit Hash:  https://github.com/cmangos/mangos-tbc/commit/60dfabf281510a0980379c0bc1ade04dd301857e

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/commit/2791ec86dea22c1c72fdbebaacffa8f8a76dc5b9

Operating System: Win 2019

### Steps to reproduce
1. Accept quest 863
2. Escort the NPC
3. Wait

**Comment by stealthgun** [comment]
Adding an extra row in the database seems to solve the issue.

INSERT INTO tbcmangos.script_waypoint (entry, pathId, pointid, position_x, position_y, position_z, orientation, waittime, script_id, comment) VALUES('3439', '0', '26', '1091.97', '-2985.92', '91.73', '0', '40000', '0', '-Fix for the script to fire correctly');

**Comment by cala** [comment]
Some of the scripts are still not working as intended after the WP updates. It seems this is one of those. I'll check it along the other ones.

**Comment by cala** [comment]
@stealthgun could you check again this escort quest with the latest revision of the core, without the extra row for the database: just fresh install, please ?

**Comment by stealthgun** [comment]
Its fixed with the latest commit.

**Comment by cala** [comment]
Great, thank you!
