### ISSUE TITLE
🐛 [Bug Report] Quest A Dip In The Moonwell not working

### ISSUE THREAD

**Issue by stealthgun** [cmangos/issues#2217]
## 🐛 Bugreport
The Quest A Dip In The Moonwell (id: 9433) does not work, when you use then quest item (id: 23675) message appears in the client "invalid target" the Robotron 3000 spawns, but you do not take control over it, so you cannot complete the quest.

![Screenshot from 2020-06-01 18-23-54](https://user-images.githubusercontent.com/129263/83430391-e88d0780-a435-11ea-990f-fb08951d0dde.png)

### Expected behavior
When you use the quest item you should control the Robotron 3000 and be able to do the quest.
https://tbcdb.com/?quest=9433

### Version & Environment
Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: cmangos/mangos-tbc@19d3644

Database Repo & Commit Hash: cmangos/tbc-db@2791ec8

Operating System: Win 2019

### Steps to reproduce
1. Accept quest 9433
2. Activate the quest item near the "Concealed Control Panel"

### Crashlog
- None

**Comment by jaondayko** [comment]
I was able to replicate the quest bug:
`.quest add 9433`
`.tele thalanaar`
then turn around and find the quest point, using the item given will not do anything but spawn the Robotron 3000. Reusing the item will spawn another Robotron 3000.

**Comment by Crypticaz** [comment]
confirmed

**Comment by buenodart** [comment]
Confirmed

**Comment by danielcopetti** [comment]
Confirmed

**Comment by shagu** [comment]
[Confirmed](https://youtu.be/Sp74wabQaoE) on TBC (latest core & db)
