### ISSUE TITLE
🐛 xcopy' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#2220]
## 🐛 Bugreport
Getting error below on build.

6>shared.vcxproj -> C:\Users\Rog360\Documents\On Desktop\sources\Git Folder\cmangos-wotlk\bin\BuildDir\src\shared\Release\shared.lib
6>'xcopy' is not recognized as an internal or external command,
6>operable program or batch file.
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: The command "setlocal
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: xcopy /Y "C:\Users\Rog360\Documents\On Desktop\sources\Git Folder\cmangos-wotlk\dep\lib\x64_Release\*.dll" "C:/Users/Rog360/Documents/On Desktop/sources/Git Folder/cmangos-wotlk/bin/x64_Release\*.dll"
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmEnd
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmErrorLevel
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: exit /b %1
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmDone
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :VCEnd" exited with code 9009.
6>Done building project "shared.vcxproj" -- FAILED.

### Expected behavior
Build with no errors.

### Version & Environment
"3.3.5a" (WOTLK)

Client Version: 
[WOTLK](https://github.com/cmangos/mangos-wotlk/tree/4cb9cb8db25a467fa7ef474acdcebb00b659bd70)

CMaNGOS Repo & Commit Hash: 4cb9cb8db25a467fa7ef474acdcebb00b659bd70

  Operating System
  Win 7 & VS2017

**Comment by Saben65** [comment]
When you just type _path_ into cmd prompt, what does it return?

**Comment by Rog360** [comment]
it has "C:\Program Files\TortoiseSVN\bin".... ?

**Comment by Rog360** [comment]
I think TortoiseSVN messed it up. I added like "C:\Program Files\TortoiseSVN\bin;C:\Windows\System32" and it fixed the problem... :)
Thanks Saben65.
