### ISSUE TITLE
🐛 [Bug Report] - TBC Client Crashes when entering Karazhan

### ISSUE THREAD

**Issue by tonymontoya** [cmangos/issues#2223]
## 🐛 Bugreport
The issue is that when you attempt to zone into Karazhan - the game client freezes and eventually crashes after a few minutes. 

### Expected behavior
Any level 70 character, in a raid group with the Master's Key (attunement) should be able to zone into the Karazhan raid instance.

### Version & Environment

Client Version: "2.4.3" (TBC)
CMaNGOS Repo & Commit Hash:  https://github.com/cmangos/mangos-tbc/tree/aa971d7
Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/f6d1e
Operating System:  Ubuntu 18.04 LTS

### Steps to reproduce
1.  Create a level 70 character.
2.  Assign that character the Master's Key (.add 24490)
3.  Join a group with another character & convert it to a raid.
4. Teleport to Karazhan (.tele group karazhan)
5. Attempt to zone in after unlocking the front door with The Master's Key.

NOTE:  One thing I noted was that a second character on a second test account was able to zone into Karazhan without issue.  But when the first character crashed, and the second character re-zoned - his client crashed as well.  It seems that this may only be affecting the first character to zone in?

### Crashlog

==============================================================================
World of WarCraft (build 8606)

Exe:      <REMOVED>
Time:     Jun 20, 2020  4:24:27.959 PM
User:     <REMOVED>
Computer: <REMOVED>
------------------------------------------------------------------------------

This application has encountered a critical error:

ERROR #132 (0x85100084) Fatal Exception
Program:	C:\Games\WoW TBC\Wow.exe
Exception:	0xC0000005 (ACCESS_VIOLATION) at 0023:59434901

The instruction at "0x59434901" referenced memory at "0x59434901".
The memory could not be "written".

WoWBuild: 8606
Realm: Sunwell [<REMOVED>:8085]
Local Zone: Karazhan
Local Player: Carneasada, 0000000000000001, (-11101.8,-1998.31,49.8927)
------------------------------------------------------------------------------

----------------------------------------
    x86 Registers
----------------------------------------

EAX=59434901  EBX=0019FDC0  ECX=33FD0F00  EDX=ABA9ABA8  ESI=0E05C008
EDI=00006801  EBP=0019FDAC  ESP=0019FD8C  EIP=59434901  FLG=00010202
CS =0023      DS =002B      ES =002B      SS =002B      FS =0053      GS =002B

----------------------------------------
    Stack Trace (Manual)
----------------------------------------

Address  Frame    Logical addr  Module

Showing 50/50 threads...

--- Thread ID: 4488 [Current Thread] ---
59434901 0019FDAC 0000:00000000 C:\Games\WoW TBC\Wow.exe
0055F9F5 0019FDD8 0001:0015E9F5 C:\Games\WoW TBC\Wow.exe
0055FF41 0019FE00 0001:0015EF41 C:\Games\WoW TBC\Wow.exe
0041C873 0019FE44 0001:0001B873 C:\Games\WoW TBC\Wow.exe
0042883C 0019FEBC 0001:0002783C C:\Games\WoW TBC\Wow.exe
00429D61 0019FED4 0001:00028D61 C:\Games\WoW TBC\Wow.exe
00406898 0019FF70 0001:00005898 C:\Games\WoW TBC\Wow.exe
74C46359 0019FF80 0001:00006359 C:\Windows\System32\KERNEL32.DLL
770E7C24 0019FFDC 0001:00066C24 C:\Windows\SYSTEM32\ntdll.dll
770E7BF4 0019FFEC 0001:00066BF4 C:\Windows\SYSTEM32\ntdll.dll

--- Thread ID: 8836 ---
74C46359 02BDFF80 0001:00006359 C:\Windows\System32\KERNEL32.DLL
770E7C24 02BDFFDC 0001:00066C24 C:\Windows\SYSTEM32\ntdll.dll
770E7BF4 02BDFFEC 0001:00066BF4 C:\Windows\SYSTEM32\ntdll.dll

--- Thread ID: 8716 ---
74C46359 02DBFF80 0001:00006359 C:\Windows\System32\KERNEL32.DLL
770E7C24 02DBFFDC 0001:00066C24 C:\Windows\SYSTEM32\ntdll.dll
770E7BF4 02DBFFEC 0001:00066BF4 C:\Windows\SYSTEM32\ntdll.dll

--- Thread ID: 10772 ---
74C46359 02EBFF80 0001:00006359 C:\Windows\System32\KERNEL32.DLL
770E7C24 02EBFFDC 0001:00066C24 C:\Windows\SYSTEM32\ntdll.dll
770E7BF4 02EBFFEC 0001:00066BF4 C:\Windows\SYSTEM32\ntdll.dll

--- Thread ID: 7572 ---
7511F59F 0407FF0C 0001:0010E59F C:\Windows\System32\KERNELBASE.dll
0065EF34 0407FF68 0001:0025DF34 C:\Games\WoW TBC\Wow.exe
0075FDD4 0407FF80 0001:0035EDD4 C:\Games\WoW TBC\Wow.exe

**Comment by Warlockbugs** [comment]
Please, try again with latest master.

**Comment by tonymontoya** [comment]
@Warlockbugs  - the latest commit to master seems to have resolved the problem.  Tested on commit tag `1331cff`
