### ISSUE TITLE
💬 [Support Request] Stuck Building Core @ 92%

### ISSUE THREAD

**Issue by Irwin0812** [cmangos/issues#2225]
## 💬 Support Request

All is in the screenshot

![1](https://user-images.githubusercontent.com/67503938/85920276-b0c98200-b872-11ea-8fa9-0d34935f27ca.jpg)

### Version & Environment

Client Version: 1.12.1

CMaNGOS Repo & Commit Hash:  CLASSIC

Database Repo & Commit Hash: MariaDB 10.3

Operating System: Linux Ubuntu 20.04

### Steps to reproduce
1. 
2.
3.
4. ...
5. Profit

**Comment by jimmybrancaccio** [comment]
Hi @Irwin0812 Is this still an issue for you? Of note it looks like you're missing your MySQL libraries.

**Comment by al3xc1985** [comment]
@killerwife I guess it can be closed
