### ISSUE TITLE
🐛 [Bug Report] WOTLK Death Knight quest # 12641 fails - can not finish Death Knight start area.

### ISSUE THREAD

**Issue by kelbren** [cmangos/issues#2227]
## 🐛 Bugreport

Death Knight quest "Death from Above" # 12641  is not allowing control over the spawned Eye of Acherus.
if you try and move it resets and leaves your char in a state that you can not move. a re-log does clear the frozen player.
There does not seem to be any way to progress past this point as the purple portal behind the Lich King does not transport player to lower level.

Client Version:    - "3.3.5a" (WOTLK)
Commit Hash - [WOTLK] fd314f7 

### Steps to reproduce
1. build fresh server
2. create death knight.
3. .quest add 12641
4. Click on Eye of Acherus control mechanism
5. sadness

**Comment by Orcman2019** [comment]
I ran into the same thing but didn't want to make another issue.

The Eye of Acherus quest can be skipped but the teleport area is broken, more than likely more DK starting area quests broken after that.

**Comment by TarasHots** [comment]
Can confirm as well, also here is the error message, but I think this is the result, not cause of this issue:

`HandleSetActiveMoverOpcode: incorrect mover guid: mover is Creature (Entry: 28511 Guid: 9000766) and should be Player Nostop (Guid: 1)`

**Comment by kelbren** [comment]
With latest commit, teleport behind Lich King now works again. The Eye of Acherus is still not working. it only works if you have gm mode on. not able to move the eye to complete the quest.

**Comment by Grz3s** [comment]
fixed
