### ISSUE TITLE
New Feature - creature_spawn_data_template

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#2229]
```
CREATE TABLE creature_spawn_data_template(
Entry INT UNSIGNED NOT NULL COMMENT 'ID of template',
UnitFlags BIGINT NOT NULL DEFAULT '-1',
ModelId MEDIUMINT UNSIGNED NOT NULL DEFAULT '0',
EquipmentId MEDIUMINT NOT NULL DEFAULT '0',
CurHealth INT UNSIGNED NOT NULL DEFAULT '1',
CurMana INT UNSIGNED NOT NULL DEFAULT '0',
SpawnFlags INT UNSIGNED NOT NULL DEFAULT '0',
PRIMARY KEY(Id,UnitFlags,ModelId,EquipmentId,CurHealth,CurMana,SpawnFlags)
);
```

```
CREATE TABLE creature_spawn_data(
Guid INT UNSIGNED NOT NULL COMMENT 'guid of creature',
Id INT UNSIGNED NOT NULL COMMENT 'ID of template',
PRIMARY KEY(Guid)
);
```

Primary goal - offload creature table off of data that is needed in more places, namely in core and in dbscripts spawning, also complemented by database normalization.
Required because of cyclic flight splines - SpawnFlags are needed for that purpose and it needs to be a setting per-spawn that cannot be done with dbscripts due to architectural reasons. ID would be used in creature table and in dbscripts or any SummonCreature utilizer.

2 things: Think what might also be needed. Dbscripts need Unitflags per spawn very frequently (currently unable to do some stuff with it for that reason)
Think why this might be bad.

Example of SpawnFlags : RUN_BY_DEFAULT - common problem, we use dbscript for this with delay which is not blizzlike and cannot be used by cyclic spline

Linking all important people @cala @Tobschinski @Grz3s @cyberium

**Comment by AnonXS** [comment]
Nuke CurHealth , CurMana, currentwaypoint, deathstate and also maybe modelid, equipment_id from `creature`

**Comment by al3xc1985** [comment]
@killerwife implemented
