### ISSUE TITLE
💬 [Support Request] Lot of Errors During Server Startup

### ISSUE THREAD

**Issue by mnemonic-re** [cmangos/issues#2231]
Hello.

First I compiled the core and created the dbs myself and I got errors during server startup.
Then I downloaded prebuild world db and core executables and still the same thing.

I tried everything to fix it but to no avail.

If anyone can help me resolve this, please. Here is the log: https://pastebin.com/WH0N14xG

Thanks.

### Version & Environment
Client Version: 

"2.4.3" (TBC)

CMaNGOS Repo & Commit Hash:  

[TBC](https://github.com/cmangos/mangos-tbc/tree/82e851cfee73fc24f1f4ed2ff5592397c88305b4

Database Repo & Commit Hash: 

[TBC](https://github.com/cmangos/tbc-db/tree/3ff738d98e479850209d79ffadbb40d2fb9b68de

Operating System: 

Windows 7 x64

### Steps to reproduce
1. Compile the core myself or download prebuild && populate the DB myself or download prebuild
2. Configure everything
3. Run realmd.exe - fine
4. Run mangosd.exe - errors
5. Not Profit :(

**Comment by AnonXS** [comment]
fastly reduced to the point where they pop from time to time, some are even false positives

```
2021-12-12 21:41:57 Spell 21084 listed in `spell_threat` as custom rank has same data as Rank 1, so redundant
```
should be the only error to pop as false positive at the moment.
