### ISSUE TITLE
🐛 [Bug Report] Auchenai Crypts - First Boss

### ISSUE THREAD

**Issue by buenodart** [cmangos/issues#2234]
## 🐛 Bugreport

Go to Auchenai Crypts, First boss.
Start the fight, and when they cast "Shirrak the Dead Watcher focuses on 'new target'.

### Expected behavior

No dump. Boss cast his spell, and the action keep goin! Kill boss and keep going the DG

### Version & Environment

Client Version: 2.4.3(TBC)

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/tree/82e851cfee73fc24f1f4ed2ff5592397c88305b4
Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/934e21037ee7b68605f58971deb5d1442f9d904f
Operating System: Ubuntu 18.04LTS Windows Subsystem

### Steps to reproduce
Steps to reproduce
1. Open realmd
2. Open mangosd
3. Server on
4. Go to Auchenai Crypts. With, party, alone, anything. Start the Boss Fight
5. Wait the boss sent: Shirrak The Dead Watcher focuses on "new target"
6. Server get Dumped
7. Profit

Crashlog
Core Crash

### Crashlog
- mangos > Segmentation fault (core dumped)
![Shirrak - Boss](https://user-images.githubusercontent.com/31133800/87881102-75cbf180-c9cd-11ea-9eae-d59692f645ea.png)
![CoreDumped](https://user-images.githubusercontent.com/31133800/87881105-78c6e200-c9cd-11ea-9ebb-60de3b93bed6.PNG)

**Comment by Crypticaz** [comment]
Can confirm

**Comment by buenodart** [comment]
Fixed!
