### ISSUE TITLE
🐛 [Bug Report] Retribution aura does not work. Reflects Shadow damage instead of damaging with Holy

### ISSUE THREAD

**Issue by TarasHots** [cmangos/issues#2235]
## 🐛 Bugreport

![image](https://user-images.githubusercontent.com/2003618/88476038-4d944380-cf35-11ea-82fe-010eb6161d1a.png)

See the combat log, there is weird info about `You reflect 7294 Shadow damage`. This happens when paladin is hit with Retribution aura toggled on. It does not do anything to the enemy, but this aura does not work as intended. 

P.S.: looks like 7294 damage is an actual spell id of Retribution Aura 🤔 

### Expected behavior

It should cause X holy damage on every hit, depends from rank (only from rank? or maybe holy spell damage too?).
[See spell description](https://classic.wowhead.com/spell=7294/retribution-aura)

### Version & Environment

Client Version: 
"1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: [CLASSIC](https://github.com/cmangos/mangos-classic/tree/8f5891748962cc5bbc128c9a3a22ec363484ac04)

Database Repo & Commit Hash: [CLASSIC](https://github.com/cmangos/classic-db/tree/85df86dc552744e3d4aeb0bb56f99db9c4f71f5c)

Operating System: Linux Mint

### Steps to reproduce
1. Learn Rank 1 - Retribution Aura as paladin
2. Toggle aura and attack someone hostile
3. See that aura reflecting Shadow damage instead of doing Holy damage to your enemy
4. Profit

### Crashlog

- None

**Comment by FrankenFaust** [comment]
https://github.com/cmangos/mangos-classic/pull/420/commits/be68549af95fa08ab656f37b2eb38b56cd7fbfbf for classic, havent checked the behavior in tbc or wotlk.

**Comment by TarasHots** [comment]
@FrankenFaust thank you, will check this probably today

**Comment by TarasHots** [comment]
@FrankenFaust works good! I'm just wondering about the wording used in combat log. It says it `reflected` some amount of holy damage

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/pull/420
Thanks @FrankenFaust
