### ISSUE TITLE
🐛 [Bug Report] Galen's Escape EscortAI

### ISSUE THREAD

**Issue by Crypticaz** [cmangos/issues#2236]
## 🐛 Bugreport

The quest Galen's Escape (https://classic.wowhead.com/quest=1393/galens-escape) works properly up until the point he reaches his last wp. Upon reaching last wp, he runs back to original wp and the escort starts over (quest is completed on the first escort) and is repeated until player runs far enough, or on restart. 

Not sure exactly why he's running back to first wp, as I've compared other escort quests and this one and other one's look similar. Nothing seems to stick out as to why he runs back. The solution I have works, but I don't believe it's the proper fix for it.

m_creature->ForceDespawn();

This works if you create a case for his 22nd wp, but he despawns as he tries to run back to his first wp.
To add, Galen doesn't face you upon completing the quest, regardless of
m_creature->SetFacingToObject(pPlayer);
being scripted in.

### Expected behavior

Galen should run to the last wp and despawn
https://www.youtube.com/watch?v=57_CgmmO-hI

### Version & Environment

Client Version: 
2.4.3 (TBC)

CMaNGOS Repo & Commit Hash: [TBC] https://github.com/cmangos/mangos-tbc/tree/981507ae1c46f367510b8b0a4bf261fd0fb63b77

Database Repo & Commit Hash: [TBC] https://github.com/cmangos/tbc-db/tree/0e901539481a16b73efefaf2d798a41eac38532a

Operating System: 
Windows 10
### Steps to reproduce
1. Accept quest 5391 from Galen Goodward
2. Let Escort Playthrough
3. As he reaches last wp, watch him run back to original escort

### Crashlog

- None

**Comment by cala** [comment]
Thank you for this report.

After looking at the code, I made some minor updates to the quest, but the main issue here is that the escort NPC moves back to the initial point of its paths when he is asked to run through the dedicated SD2 method `EscortAI::SetRun()`.

Making him run with the `creature::SetWalk(false)` also makes him run back to the first point. At least client-side as it seems that Galen does reach the following points on his path server-side (to be confirmed).

Poking @cyberium because he recently worked on this code.

**Comment by Olion17** [comment]
In the npc_escortAI, the finishing escort magic is done at the last WP. Here the player gets the quest completed at the 21th WP, not at the 22th. At the WP 21-22 path segment the NPC is not a part of an escort anymore. I believe it gets a different EscortState while waiting 15 sec at the WP 21 (player for escort is checked every 1 sec). Anyway no despawn magic happens, we get the usual evade instead with MoveTargetedHome().

The simplest way is manual despawning the NPC at the last WP (22th) from the same WaypointReached() method. Another one may be completing the quest at the last WP, to keep the 21-22 segment within the escort path.
