### ISSUE TITLE
🐛 [Bug Report] Centipaar Tunneler Evade

### ISSUE THREAD

**Issue by Crypticaz** [cmangos/issues#2237]
## 🐛 Bugreport

For the quest Gadgetzan Water Survey, upon using Untapped Dowsing Widget, it will spawn Cenipaar Tunnelers. When trying to attack them, they enter evade mode. I believe if you try and pull them away from spawn a bit, they no longer enter evade mode and can be killed. However, I believe they're not supposed to be evading upon attack them. When they spawn in, they're not in evade mode, but only once you enter combat and start attacking them.

### Expected behavior

https://www.youtube.com/watch?v=DAEvjSDhYoI

### Version & Environment

Client Version:  2.4.3 TBC

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/commit/930cc967fe521446f33ffdb0100e57bee405cf17

Database Repo & Commit Hash: [TBC] https://github.com/cmangos/tbc-db/commit/7cb9fda52c6711a58a1d5221231438c7f8396ed4

Operating System: Windows 10

### Steps to reproduce
1. Accept/Add quest Gadgetzan Water Survey (992)
2. Use untapped dowsing widget in Sandsorrow Watch pool
3. Let creatures spawn and attack them
4. Profit

### Crashlog

- None

**Comment by AnonXS** [comment]
Linked to https://github.com/cmangos/issues/issues/2986, they spawn in shallow water, cant path out of it, so they go into evade mode. (try adding inhabittype|2)

**Comment by AnonXS** [comment]
InhabitType fix for shallow water.
