### ISSUE TITLE
Bugs experienced by players who have warlock minions and hunter pets (not blizzlike)

### ISSUE THREAD

**Issue by Neotmiren** [cmangos/issues#224]
If we have a player who has hunter "Call Pet" and warlock summon spells simultaneously, pet/minion system works incorrectly.

These problems can be easily fixed in pet.cpp

1) When Hunter calls pet one of warlock minions may come instead / Pet::LoadPetFromDB()

        result = CharacterDatabase.PQuery("SELECT id, entry, owner, modelid, level, exp, Reactstate, loyaltypoints, loyalty, trainpoint, slot, name, renamed, curhealth, curmana, curhappiness, abdata, TeachSpelldata, savetime, resettalents_cost, resettalents_time, CreatedBySpell, PetType "
                                          "FROM character_pet WHERE owner = '%u' AND (slot = '%u' OR slot > '%u') ",
                                          ownerid, PET_SAVE_AS_CURRENT, PET_SAVE_LAST_STABLE_SLOT);

This can be fixed by adding AND PetType=1 to WHERE condition

2) When Hunter pet is saved to DB it erases personalities of all warlock minions - not only their names, but also all their trained abilities / Pet::SavePetToDB()

            //stmt = CharacterDatabase.CreateStatement(del, "DELETE FROM character_pet WHERE owner = ? AND (slot = ? OR slot > ?)");
            stmt.PExecute(ownerLow, uint32(PET_SAVE_AS_CURRENT), uint32(PET_SAVE_LAST_STABLE_SLOT));

This can be fixed by adding AND PetType=1 to WHERE condition

**Comment by Phatcat** [comment]
This is not really an issue; players are not supposed to have both, and our system is really not fit for it in our current state anyways; a lot of areas regarding summons rely on the player class to be correct.

I'm not saying it's a bad idea to be able to handle this, but it's not an issue, more of a feature request, which is more fitting for the forum. Closing.
