### ISSUE TITLE
🐛 [Bug Report] Ikiss : Arcane Explosion through walls 

### ISSUE THREAD

**Issue by Dromadoros** [cmangos/issues#2240]
## 🐛 Bugreport
Sometimes when Ikiss cast Arcane Explosion and players are not in LOS, they received damage. Also players can cast through walls

![ikiss_bug](https://user-images.githubusercontent.com/11585507/89838527-bef60800-db6b-11ea-8411-b7ce5c5f0ae0.gif)

### Expected behavior
Players do not take damage when not in LOS and cannot cast behind wall

### Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 0a25260fc40306b29162d3af8e46c744949fbbb8

Operating System: Linux Flavor

### Steps to reproduce
1. Create a hunt, up 70 and .tele seth
2. Go to last boss -> Ikiss
3. Aggro, wait till he casts Arcane explosion
4. Hide behind one of four pole
5. Try to cast behind the pole and receive damage

### Crashlog
- None

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/146687981-5e01043e-a153-4759-bb66-88110d8f13d5.png)

![grafik](https://user-images.githubusercontent.com/19734826/146687994-4a4e16fb-7913-49f4-acb5-78cb869ff310.png)

![grafik](https://user-images.githubusercontent.com/19734826/146688002-392271d2-3d6e-4bbc-ba25-7adcae53129f.png)

![grafik](https://user-images.githubusercontent.com/19734826/146688028-f91d3d2e-1cc4-419d-930b-4b4ef6fd5d44.png)
