### ISSUE TITLE
🐛 [Bug Report] Mage's polymorph to sheep doesn't work in WOTLK

### ISSUE THREAD

**Issue by playfcode** [cmangos/issues#2241]
## 🐛 Bugreport
Hi, I deployed cmangos WOTLK last month in Ubuntu 16.4, and database is Mysql 5.7, client version is 3.3.5a,  but I found Mage's polymorphs  have bug, after I release a polymorph to a human creature, the creatrue can't be transfomed to sheep , and I can't kill it anyway. its energy will continue to increase .
I have already tested in different clients in same version, and get the same result, could you help check this? thanks.

**Comment by kelbren** [comment]
I can confirm. 
Polymorph does not work, there is a small visual flash and no sheep transformation, the creatures health increases until the duration of the Polymorph aura would normally end.

**Comment by darkpoetry** [comment]
Confirm this also happens with animals. Creature model does not change and instead creature suddenly gets a regen rate that makes it very difficult to kill.

**Comment by darkpoetry** [comment]
Has anyone found a workaround?

**Comment by kelbren** [comment]
I have been looking for the cause, but it's hard to trace, or I am not sure how. It seems its not setting the pacify aura and it stays agro. at this point I have no idea where to look for see what the problem is.  Pretty much make the mage useless with crowd control.

**Comment by xfurry** [comment]
CC @killerwife

**Comment by darkpoetry** [comment]
I haven't found any similar bugs filed in Trinity or anywhere else for this, does it also happen in BC or vanilla?

**Comment by kelbren** [comment]
I have not tried vanilla, my TBC install works fine. It only seems to be an issue in WotLK

**Comment by kelbren** [comment]
Applied the change.. Polymorph now works as expected. Thank you!

**Comment by playfcode** [comment]
@kelbren  Why the issue still exist in my wotlk after I did the git pull?

**Comment by Grz3s** [comment]
fixed

**Comment by darkpoetry** [comment]
Confirmed working on the latest pull thanks a bunch!

**Comment by playfcode** [comment]
Still  doesn't work in my wotlk after the lastest pull and restart server.

**Comment by Grz3s** [comment]
Pls make sure you running latest compile...
Pls check if sources contain:
\\src\game\Spells\SpellMgr.cpp
line: 2050
![sss](https://user-images.githubusercontent.com/2374069/95004039-003fec80-05de-11eb-9588-0134f2fab42c.jpg)

**Comment by playfcode** [comment]
I uploaded the video of the issue : https://youtu.be/K6LuUbWnPDk

**Comment by playfcode** [comment]
@Grz3s Thanks, but I checked the code is the lastest.
![image](https://user-images.githubusercontent.com/69490311/95004061-e8398e80-0618-11eb-852e-9dca77f307d6.png)

**Comment by kelbren** [comment]
I tested latest pull, as of an hour ago. works as expected in my test. make sure you replace your binary, and restart server.

**Comment by playfcode** [comment]
@Grz3s @kelbren  Thanks, it works as expected now.
