### ISSUE TITLE
🐛 [Bug Report] Mechano-Lord Capacitus - Mechanar Boss - Core Freezes when the boss is about to die

### ISSUE THREAD

**Issue by buenodart** [cmangos/issues#2242]
## 🐛 Bugreport

In Mechanar Dungeon, first boss, Mechano-Lord Capacitus.
The boss don't die.
You start the fight and when he gets like 350 HP, almost dying, the core just Freeze.
No errors report, no message in core about errors, and the core don't crash.

Just a core freeze happens and its necessary to force it to close (like 'kill the task').

### Expected behavior

Start the fight and kill the boss -> profit.

### Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: [TBC](https://github.com/cmangos/mangos-tbc/tree/6edb858f19c8c8c4de6fd15a37867b5bb44e7239)

Database Repo & Commit Hash: [TBC](https://github.com/cmangos/tbc-db/tree/d579c2b1e20aaaff3b7135916aea988dd18ef4a4)

Operating System: Ubuntu 18.04.4 LTS

### Steps to reproduce
1. Get any character (GM or Normal char with party)
2. Go to Mechanar DG
3. Start the Fight with the boss.
4. Use spells and try to kill it
5. Server Freeze

### Crashlog
- None

**Comment by danielcopetti** [comment]
Replicated. Bug confirmed. Here it went to 1 life point and froze.

**Comment by rnorden** [comment]
As far as I analyzed this it's not about Mechanolord per se but about the netherbombs he spawns.

I think there's a call cycle when he dies that goes like this:
1. Mechanolord dies
2. Triggers force despawn of all netherbombs
3. Triggers finalizing the movement path of a bomb
4. Triggers [boss_mechano_lord_capacitusAI::SummonedMovementInform](https://github.com/cmangos/mangos-tbc/blob/8439884cbf69543b26a5054c0157ee691b57392e/src/game/AI/ScriptDevAI/scripts/outland/tempest_keep/the_mechanar/boss_mechano_lord_capacitus.cpp#L119)
5. ...which sends the bomb to a random point again?

I tried wrapping it like follows but that didn't change anything.
```cpp
    void SummonedMovementInform(Creature* summoned, uint32 /*uiMotionType*/, uint32 /*uiData*/) override
    {
        if (summoned->IsAlive())
            MoveToRandomPoint(summoned);
    }
```

I didn't have the chance to dig deeper into why the `IsAlive()` check doesn't work as I expected.

@killerwife Do you have a hint to this?

**Comment by rnorden** [comment]
![callgraph](https://user-images.githubusercontent.com/14040199/93708936-94b84280-fb3a-11ea-9118-862d5baa1b87.png)

Here's a callgraph, sampled with valgrind's callgrind and started just before I aggroed the boss and then ran for about 3 minutes while the core was spinning around itself.

**Comment by AnonXS** [comment]
Resolved
