### ISSUE TITLE
🐛 [Bug Report] Opera Event - Wizard of Oz - Crash

### ISSUE THREAD

**Issue by berlingm** [cmangos/issues#2245]
**Current behavior**: 
After killing the Dorothee, Roar, Strawman and Tinhead, the Crone (the Witch) spawn.
Straight after her laughter sequence, the server crashes.

**Expected behavior**: 
That the event could be completed without crashing the server.

**Steps to reproduce**:
1. Spawn the Crone using .npc add 18168
2. As soon as the NPC starts spawning tornadoes, the server crashes

**Client version**: 
2.4.3

**Commit hash**: 
commit dc0ed4aa7d0a54c379e083f7c443c57ee7308f12 (HEAD -> master, tag: Last_mangos-tbc_PreBuild, origin/master, origin/HEAD)
commit 65184071621be88a22b5100fb3e51f9db3b0360c (HEAD -> master, tag: tbc-db_PreBuild, origin/master, origin/HEAD)

**Database version**: 
commit 65184071621be88a22b5100fb3e51f9db3b0360c (HEAD -> master, tag: tbc-db_PreBuild, origin/master, origin/HEAD)

**Operating system**: 
Windows 10 x64

After debugging, I have identified that it is indeed the tornadoes that crash the server, due to its waypoint being 0.
Below only the symptom is described, not the root cause of the tornadoes crashing the server, besides their waypoint being 0.

WaypointMovementGenerator::LoadPath: Creature (Entry: 18412 Guid: 9000517) doesn't have waypoint path 0
void WaypointMovementGenerator<Creature>::InitializeWaypointPath> unable to intialize path for Creature (Entry: 18412 Guid: 9000517)

The crash occur in the following code, because the waypoint is 0 (NULL):
WaypointNode const* nextNode = &m_currentWaypointNode->second;
In function :
void WaypointMovementGenerator<Creature>::SendNextWayPointPath(Creature& creature)
In file : 
WaypointMovementGenerator.cpp

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by rnorden** [comment]
Submitted a pull request for this issue, see https://github.com/cmangos/mangos-tbc/pull/403

**Comment by Lillecarl** [comment]
Related to #2244

**Comment by killerwife** [comment]
This has been resolved.
