### ISSUE TITLE
🐛 [Bug Report][WotLK][AHBot] - No longer post items in auction house

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2248]
## 🐛 Bugreport
AHBot no longer post any thing in the Auction House, and not see ahbot initialization  during system startup in the log.

### Expected behavior
if ahbot is setup in ahbot.conf, ahbot should post items to the auction house.

### Version & Environment

Client Version: "3.3.5a" (WOTLK)

CMaNGOS Repo & Commit Hash: 775484c1f521847531cf6320e02382c169b2bd8c

Database Repo & Commit Hash: 79371e9297e3c22bd665bfcf470a630c4166e9c9

Operating System: Server: Ubuntu 18.04.5 LTS 4.15.0-108-generic
                             Client: Windows 7 Pro

### Steps to reproduce
1. start server
2. log into game
3. go to AH
4. list items for sale
5. 

### Server log
ERROR:Table  "command" have nonexistent command 'ahbot', skip

**Comment by rnorden** [comment]
You probably didn't run cmake with the flag BUILD_AHBOT=ON.
You can check that in the file build/CMakeCache.txt.

```
> grep "BUILD_AHBOT" build/CMakeCache.txt
$ BUILD_AHBOT:BOOL=OFF
```

**Comment by adellaci** [comment]
That is correct and i see a few other options have been add to the cmake command, but is not covered in the "wiki". Where can i go to find out what the other options do?

**Comment by rnorden** [comment]
Which options do you think of?
check https://github.com/cmangos/mangos-tbc/blob/master/cmake/options.cmake

**Comment by adellaci** [comment]
Thank you @rnorden. All is good now.
