### ISSUE TITLE
🐛 [Bug Report] combo points works abnormally. After use  Eviscerate, combo point still exist in target.

### ISSUE THREAD

**Issue by ckj777** [cmangos/issues#2249]
## 🐛 Bugreport

Eviscerate or any other skill that spend combo point 
I've test code. I think combo points works abnormally.
After use Eviscerate and any other skill that spend bubble, combo point still exist in target.
Details in youtube link below..
### Version & Environment

Client Version: 2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: Commit Hash: latest

Database Repo & Commit Hash: Commit Hash: latest

Operating System: Windows 10

### Steps to reproduce
1.  https://www.youtube.com/watch?v=jWtz2mIhEzI
2.
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by rnorden** [comment]
I can't read your UI's language but  I guess it says "You need to have combo points for this action" or similar.
Something fundamental says you don't have combo points but your Unit Frames show you combo points, therefore I think your Unit Frame Addon (Perl?) is wrong here.
