### ISSUE TITLE
🐛 [Bug Report] Spell Travel Time/Interrupt Bug

### ISSUE THREAD

**Issue by arowjet** [cmangos/issues#2250]
## 🐛 Bugreport

Hi all, got a bug to report with the spell system, if two people spam an instant at each other, ice lance on one char, and counterspell on another char, if the ice lance spell is traveling through the air the caster will receive a full 8 second interrupt on that spell class.
but you are not supposed to be able to "spell school lock" on instant spells or on any spell traveling...even if they DO have a travel time. Once the spell is done casting or if the spell is instant, it shouldn't be interrupted.

thank you for reading, anyone know how to fix possibly? thanks all

btw this was reported by a 10 yr pvp frost mage and I tested it myself on him with a clean core
### Expected behavior

When a spell is done casting and traveling, or when an instant spell is traveling, a spell lock or interrupt should not interrupt or lock that class of spell.
### Version & Environment

2.4.3
Client Version: 
8606

CMaNGOS Repo & Commit Hash: 
d54ea8f8aa98ca9b38e5f925c1d971c4d1789803

Database Repo & Commit Hash: 

Operating System: 
ubuntu 18
### Steps to reproduce
1. Make 2 mages
2. start duel and one icelances
3. while ice lance is traveling, Counterspell
4. ...
5. Profit

### Crashlog

- None

**Comment by jimmybrancaccio** [comment]
Please see #2251 for a potential fix. I am leaving this one open as it appears to have much more of the bug reporting template filled out than the other case.

**Comment by killerwife** [comment]
Has been resolved
