### ISSUE TITLE
🐛 [Bug Report] Eating Animation Doesn't Work

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#2253]
## 🐛 Bugreport

Eating anim doesnt play when consuming food. Water anim works fine though.
### Expected behavior

You should see an animation when eating food.
### Version & Environment

Client Version: 
3.3.5a

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-wotlk/commit/95925d05964e5413cd74a0942515e3c27e5b4f0d

Database Repo & Commit Hash: 
https://github.com/cmangos/wotlk-db/commit/b6dfda5d984ce62dbe5a5b99a8a725cea42fc742

Operating System: 
Windows 10
### Steps to reproduce
1. Buy something to eat
2. Eat it
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by MantisLord** [comment]
Related? https://github.com/TrinityCore/TrinityCore/pull/21280

**Comment by al3xc1985** [comment]
@killerwife wasn't this fixed by @MantisLord patch?

**Comment by killerwife** [comment]
Fixed.
