### ISSUE TITLE
🐛 [Bug Report]Profession Locations are shining

### ISSUE THREAD

**Issue by craftorix** [cmangos/issues#2254]
## 🐛 Bugreport

Locations of the Professions (e.g. like an Oven you use for Cooking. I dont know how to call it) are always shining like this.
![WoWScrnShot_091320_100751](https://user-images.githubusercontent.com/70746948/93013494-48ed2280-f5a9-11ea-8b6f-70b226a9111f.jpg)
![WoWScrnShot_091320_101328](https://user-images.githubusercontent.com/70746948/93013553-ca44b500-f5a9-11ea-8ed4-6b36f547b266.jpg)

This includes every single profession location

### Expected behavior

This shouldnt be shining with those stars and such.

### Version & Environment

Client Version: 
3.3.5a

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-wotlk/commit/95925d05964e5413cd74a0942515e3c27e5b4f0d

Database Repo & Commit Hash: 
https://github.com/cmangos/wotlk-db/commit/b6dfda5d984ce62dbe5a5b99a8a725cea42fc742

Operating System: 
Windows 10
### Steps to reproduce
1. Just go to any Location where you can process your Profession (e.g. Oven or Anvil or whatever)
2.
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by craftorix** [comment]
Only happens aswell in GM Mode ON. (Normal behaviour though?)

**Comment by Grz3s** [comment]
.gm mode OFF... 
also if object is req. for quest in your questlog will make that effect..
This is not a bug...
