### ISSUE TITLE
🐛 [Bug Report]Valiance Keep Sound bugs

### ISSUE THREAD

**Issue by craftorix** [cmangos/issues#2257]
## 🐛 Bugreport

There are 3 Footmen Rob (ID: 25258) Chuck (ID: 25261) and George (ID: 25259) who are laying on the ground dead before their script starts. (They will also do random dying sounds when laying dead on the ground here:)

![WoWScrnShot_091320_105020](https://user-images.githubusercontent.com/70746948/93014424-41317c00-f5b1-11ea-91a7-b11d1ab9200c.jpg)

They will revive themselves after some time and do their script which is working fine but when they are about to disappear, Footman Mitch (ID: 25260) is running from behind towards the others. When Mitch has reached them they will all disappear and do a "Dying" sound.

You can also hear random "dying" sounds from various invisible character model when standing here in front of the Inn of Valiance Keep.

![WoWScrnShot_091320_111048](https://user-images.githubusercontent.com/70746948/93014490-c87eef80-f5b1-11ea-81e7-d46dcb4ba411.jpg)

### Expected behavior

There shouldnt be random "dying" sounds at all.

### Version & Environment

Client Version: 
3,3.5a

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-wotlk/commit/95925d05964e5413cd74a0942515e3c27e5b4f0d

Database Repo & Commit Hash: 
https://github.com/cmangos/wotlk-db/commit/b6dfda5d984ce62dbe5a5b99a8a725cea42fc742

Operating System: 
Windows 10
### Steps to reproduce
1. .tel ValianceKeep
2. Go in front of the inn like in 2nd Screenshot above.
3. Wait for a "dying sound" to appear

1. Go around the inn where the Gryphons are
2. You can see the Footmen laying dead on the ground
3. Wait a bit for them to resurrect themselves and do their script
4. Wait until the end of the script when Footman Mitch appears
5. Script ends. All 3 do a "dying" sound and will start laying dead on the ground again.

### Crashlog

- None

**Comment by Grz3s** [comment]
because you're on GM mode
`.gm OFF`  and you wont see them

**Comment by craftorix** [comment]
Well I am rarted :D but is it normal behaviour to hear those Dying sounds when they disappear?

**Comment by Grz3s** [comment]
on gm mode yes.. this is normal behaviour for gm to see how command 18 - despawn works .. dev when working on stuff can see if they despawned and are in spawn area... 
Player (not gm) will never see that or hear anything. 
BTW:  all three soldiers there are part of small event .. I made it some time ago...
recorded: https://www.youtube.com/watch?v=TlFdS3GH2EQ&feature=youtu.be&list=PLQWa1A2Qh_1XH_dyeGPZE1D9hwPw801e1&t=72
