### ISSUE TITLE
Performance vmaps on TBC/ classic

### ISSUE THREAD

**Issue by Schmoozerd** [cmangos/issues#226]
Hi guys,

with the recent changesto vmap extraction, there is now much more collision data stored in the vmaps.

Are there now performance issues?
Also if somebody is interesting to dig into the code, it is most likely reasonable to crop trees and similar (as done in wotlk)

(This is a forward of cmangos/issues#189 to get things handled more streamlined)

**Comment by cala** [comment]
From my point of view, I have no performance issues with vmaps enable for Classic core.

**Comment by Tobschinski** [comment]
@Cala What about the upper Blackrockspire, no more issues there?

**Comment by cala** [comment]
Well, the only UBRS performances issues I had were with a bad ACID script that was causing some infinite loop (NPC throwing events to each others).
I can believe other issues exist (or existed) but I can't report them since I don't have them. Hence my bump on this issue to gather more feedback. :)

**Comment by Tobschinski** [comment]
Hm, I am still stuck in UBRS if I set my distance to something greater than 250.

**Comment by cala** [comment]
I'll try with such value and tell you if I have errors.

**Comment by Tobschinski** [comment]
I would be surprised if not, because you were the one telling me about this issue :)

**Comment by cala** [comment]
Ah.
In this case, I should probably stop drinking, it seems to do me no good. :P

**Comment by cyberium** [comment]
@Schmoozerd no there is no performance issue thank you. But dont forget to come back one day.
