### ISSUE TITLE
🐛 [Bug Report][Quest]The Endless Hunger not working

### ISSUE THREAD

**Issue by craftorix** [cmangos/issues#2260]
## 🐛 Bugreport

Quest "The Endless Hunger" (ID: 12848 is not working properly. Prisoners wont trigger.

### Expected behavior

With should get into a fight with a prisoner when you unlocked their "cage"

### Version & Environment

Client Version: 
3.3.5a

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-wotlk/commit/c507b881d47c9d2e9907bc070f200c51c7504e00

Database Repo & Commit Hash: 
https://github.com/cmangos/wotlk-db/commit/d2d2bf1aba90a0ee84328813c93171540f309ffd

Operating System: 
Windows 10
### Steps to reproduce
1. Create a death knight
2. Do the quests until you have reached this quest
3. See the demise
4. ...
5. Profit

### Crashlog

- None

**Comment by Grz3s** [comment]
just tested it now ..and works correct:
![ccc](https://user-images.githubusercontent.com/2374069/93122133-e174c700-f6bd-11ea-94de-d54361fb9232.jpg)

only thing i can sugest is to check if all core updates are added correctly... 

PLS check in `spell_template` spells 54612 & 54613 if `AttributesEx2` = 4 ?
IF its  = 0 .. then:

make sure that `InstallFullDB.config` has this set up correctly: 
```code
## Define the path to your core's folder
## Core updates located under sql/updates from this mangos-directory will be added automatically
CORE_PATH="........."
```

**Comment by craftorix** [comment]
Okay dokey.

I will test when I come home from work. Thanks for this information!
