### ISSUE TITLE
🐛 [Bug Report] Hunter Pet on Ramp in Darnassus Causes Server Hang (Not Crash)

### ISSUE THREAD

**Issue by linuxthat** [cmangos/issues#2262]
## 🐛 Bugreport
Hunter class with a pet companion in Darnassus causes the server to not crash but hang on all commands and actions if the pet touches the ramp in the Cenarian enclave which the ramp that leads to Arch Druid Thandrel Staghelm.

Was able to replicate issue. Having the pet put away results in no issues.

### Expected behavior
Server should not hang but continue.

### Version & Environment

Client Version: 1.12.1

CMaNGOS Repo & Commit Hash: 2e21377ecfe9ddbb165bd485e41e1eeab72d7ba3

Database Repo & Commit Hash: c264d8283ad26837d6efd77fcd33bd76db82da82

Operating System:

LXD Container
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

### Steps to reproduce
1. Go to the Cenarian Enclave with a hunter. Have your pet out.
2. Try to go up the ramp that leads to the arch druid with your pet out.
3. The server will hang.

### Crashlog

- There is no crash, just a hang - Infinite loop.

**Comment by jimmybrancaccio** [comment]
@linuxthat Please provide a subject/title for the bug report.

**Comment by linuxthat** [comment]
Missed that, @jimmybrancaccio - Whoops. Updated.

**Comment by jimmybrancaccio** [comment]
Awesome, thanks @linuxthat!

**Comment by cala** [comment]
Can you provide a more detailed way to reproduce the issue, please ? I tried to reproduce it myself with a hunter and a pet and did not have any issue : my character went, talked to the arch druid and went down.

**Comment by ckj777** [comment]
https://www.youtube.com/watch?v=v6ovMqhMIpg

**Comment by canidae** [comment]
I'm also unable to reproduce this, although it's the same kind of desync I've seen on my server when 4 or more people are in a party, but in different zones (see https://github.com/cmangos/issues/issues/2325). I'm not sure if they're related somehow, but there's definitively something going on here.

**Comment by canidae** [comment]
There has been some recent changes that fixed a similar issue (#2325). You should update your core and see if this still is an issue.

**Comment by jimmybrancaccio** [comment]
@linuxthat Are you still experiencing this issue?

**Comment by nate123456** [comment]
I walked up the Ramp in the Cenarion Enclave as a hunter with the pet out up the Arch Druid in classic and did not experience a server hang- the server remained responsive. I'd say the issue can't currently be replicated, although it'd be good to hear from the OP to be sure they are good to go before the issue is closed. 

The `Can't be Replicated` tag could be used in the meantime.

**Comment by MantisLord** [comment]
While it's not perfect, the pet can traverse the entire ramp for me and there's no hang. I tested with Classic and TBC cores both to be sure.
Can't reproduce.
