### ISSUE TITLE
🐛 [Bug Report][Quest]Resupplying the Excavation

### ISSUE THREAD

**Issue by craftorix** [cmangos/issues#2264]
## 🐛 Bugreport

ID: 273

First of all. The quest script itself is working just fine and you can complete it but there is one bug.

When you reach the range where your quest objective turns to (Complete) you should see some text from the creatures but instead there is instant fighting without any text.

AND when there is the fight going on you shouldnt see the yellow quest marker above Huldars (ID: 2057) Head. Only when the last creature is dead.

### Expected behavior

https://youtu.be/9SkWWi4is_k?t=100

### Version & Environment

Client Version: 
3.3.5a

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-wotlk/commit/c507b881d47c9d2e9907bc070f200c51c7504e00

Database Repo & Commit Hash: 
https://github.com/cmangos/wotlk-db/commit/a859d04af27a2fa15abb36edc283b9e38704279d

Operating System: 
Windows 10
### Steps to reproduce
1. .q add 273
2. Make sure you are not the visibility range of the quest creatures.
3. Walk toward the map marker
4. ...
5. Profit

### Crashlog

- None

**Comment by craftorix** [comment]
Found out that in "broadcast_text" is the ID 494 which should broadcast the text from Miran but it doesnt. So there is a link missing or a quest condition.

Couldnt find out though why the yellow quest mark is still showing above Huldars Head while the attack is going on.

**Comment by Grz3s** [comment]
Fixed:
https://github.com/cmangos/mangos-wotlk/commit/8e36138cf631965c2b9c8a2084981beeb1f9f226
