### ISSUE TITLE
🐛 [Bug Report] [TBC] Crash - Shadowmoon Valley - Path of Conquest - Kor'kron Wind Rider

### ISSUE THREAD

**Issue by rnorden** [cmangos/issues#2265]
## 🐛 Bugreport
Kor'kron Wind Riders crash the server when they're called in hostile area. When hostile units exist/spawn next to him, the rider will move towards them and return to his spawn position when they're dead. 
The server crashes because there is probably something wrong with its movement path.

### Expected behavior
Ther server should not crash.

### Version & Environment
Client Version: 
  - "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 
  - [TBC](https://github.com/cmangos/mangos-tbc/tree/d54ea8f8aa98ca9b38e5f925c1d971c4d1789803)

Database Repo & Commit Hash: 
- [TBC](https://github.com/cmangos/tbc-db/tree/65184071621be88a22b5100fb3e51f9db3b0360c)

Operating System: 
  - Linux Flavor

### Steps to reproduce
1. .additem 31108
2. .go zonexy 51.15 63.13 3520
3. ...wait for a hostile mob to move into aggro range
4. Crash

### Crashlog
```
#0  0x00000000011877db in WaypointMovementGenerator<Creature>::SendNextWayPointPath (this=0x7fde74dfeac0, creature=...)
    at /home/mangos/mangos-tbc/src/game/MotionGenerators/WaypointMovementGenerator.cpp:425
#1  0x0000000001186a2c in WaypointMovementGenerator<Creature>::Reset (this=0x7fde74dfeac0, creature=...) at /home/mangos/mangos-tbc/src/game/MotionGenerators/WaypointMovementGenerator.cpp:155
#2  0x0000000001159c3f in MovementGeneratorMedium<Creature, WaypointMovementGenerator<Creature> >::Reset (this=0x7fde74dfeac0, u=...)
    at /home/mangos/mangos-tbc/src/game/MotionGenerators/MovementGenerator.h:89
#3  0x0000000001152e9c in MotionMaster::DirectExpire (this=0x7fde758080d0, reset=true) at /home/mangos/mangos-tbc/src/game/MotionGenerators/MotionMaster.cpp:198
#4  0x0000000000e607cd in MotionMaster::MovementExpired (this=0x7fde758080d0, reset=true) at /home/mangos/mangos-tbc/src/game/MotionGenerators/MotionMaster.h:124
#5  0x000000000115285e in MotionMaster::UpdateMotion (this=0x7fde758080d0, diff=100) at /home/mangos/mangos-tbc/src/game/MotionGenerators/MotionMaster.cpp:92
#6  0x0000000000fc659a in Unit::Update (this=0x7fde75805ea0, diff=100) at /home/mangos/mangos-tbc/src/game/Entities/Unit.cpp:478
#7  0x0000000000ebf612 in Creature::Update (this=0x7fde75805ea0, diff=100) at /home/mangos/mangos-tbc/src/game/Entities/Creature.cpp:696
```

**Comment by Lillecarl** [comment]
Related to #2244

**Comment by AnonXS** [comment]
I think the commits above resolved this, there was also some issue with it being "spamable" as it was not implemented correctly.
