### ISSUE TITLE
🐛 [Bug Report] [TBC] Mechanolord Capacitus causes infinite loop

### ISSUE THREAD

**Issue by rnorden** [cmangos/issues#2266]
## 🐛 Bugreport
While fighting Mechanolord Capacitus in Non-Heroic Mechanar, the server becomes unresponsive but does **not** crash.
CPU usage is getting maxed out, the game doesn't get updated, logging into the game server is stuck at "Connected".

I think the behavior might be connected to the bosses' reflective shields.

### Expected behavior
The server should not become unresponsive.

### Version & Environment
Client Version: 
  - "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 
  - [TBC](https://github.com/cmangos/mangos-tbc/tree/d54ea8f8aa98ca9b38e5f925c1d971c4d1789803)

Database Repo & Commit Hash: 
- [TBC](https://github.com/cmangos/tbc-db/tree/65184071621be88a22b5100fb3e51f9db3b0360c)

Operating System: 
  - Linux Flavor

### Steps to reproduce
1. .tele Mechanar
2. .gm on
3. Run towards Mechanolord, stay in the corner with the wall made of mana boxes
4. .gm off
5. Aggro Mechanolord, do nothing. Watch your health, Headcrack reset your max health.
6. When activating either Melee or Spell Reflective Shields the server may become unresponsive.

**Comment by linuxthat** [comment]
Duplicate of: https://github.com/cmangos/issues/issues/2242

**Comment by rnorden** [comment]
Indeed, thank you.
