### ISSUE TITLE
🐛 [Bug Report][DB]Several Errors

### ISSUE THREAD

**Issue by craftorix** [cmangos/issues#2267]
## 🐛 Bugreport

There are some several custom DB erros appearing in mangosd.exe console.

These would be:

ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2325201, command 1 call for non-unit, skipping.
ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2325201, command 15 call for non-unit, skipping.
ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2325201, command 28 call for non-creature, skipping.

ERROR: DB-SCRIPTS: Process table `dbscripts_on_relay` id 10103, command 0 has buddy 19425 by guid 69482 but buddy is dead, skipping.
ERROR: DB-SCRIPTS: Process table `dbscripts_on_relay` id 10103, command 0 has buddy 19425 by guid 69484 but buddy is dead, skipping.

ERROR: DB-SCRIPTS: Process table `dbscripts_on_relay` id 10103, command 0 has buddy 19425 by guid 69482 but buddy is dead, skipping.
ERROR: DB-SCRIPTS: Process table `dbscripts_on_relay` id 10103, command 0 has buddy 19425 by guid 69484 but buddy is dead, skipping.

ERROR: DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 3804, command 1 has buddy 38 by guid 80189 but buddy is dead, skipping.

### Expected behavior

I guess these errors aint the normal behaviour.

### Version & Environment

Client Version: 
3.3.5a

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-wotlk/commit/c507b881d47c9d2e9907bc070f200c51c7504e00

Database Repo & Commit Hash: 
https://github.com/cmangos/wotlk-db/commit/a859d04af27a2fa15abb36edc283b9e38704279d

Operating System: 
Windows 10
### Steps to reproduce
1. Just start mangosd.exe and play around
2. What I have done is I created a new character and played normally and leveled up normally.
3. ...
4. Profit

### Crashlog

- None

**Comment by craftorix** [comment]
https://github.com/cmangos/wotlk-db/commit/6d1cd5fb99efd521271bf6e595b4088b1f56ae09

Commit fixed it! Thanks 👍

**Comment by Grz3s** [comment]
commit fixed only 1 of them... 
other are TBC backports ... will be fixed another time
