### ISSUE TITLE
🐛 [Bug Report] Mountaineer Stenn

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#2269]
## 🐛 Bugreport

Mountaineer Stenn (ID: 1278) in Loch Modan doesnt have waypoints and is just standing there.

### Expected behavior

He should be walking around in Loch Modan specifically around the area of Thelsamar.

https://classic.wowhead.com/npc=1278/mountaineer-stenn

So from this point to this point:

![WoWScrnShot_091720_065024](https://user-images.githubusercontent.com/70746948/93421657-3bd67900-f8b2-11ea-898a-ca2fa1131003.jpg)
![WoWScrnShot_091720_065101](https://user-images.githubusercontent.com/70746948/93421659-3da03c80-f8b2-11ea-8742-f2ade173a2ec.jpg)

### Version & Environment

Client Version: 
3.3.5a

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-wotlk/commit/e7f3af84e0d0141b15d101c08d8e19214df2c407

Database Repo & Commit Hash: 
https://github.com/cmangos/wotlk-db/commit/d793a4b0385eb87846db0f596fce5af0edad24f6

Operating System: 
Windows 10
### Steps to reproduce
1. .tel Thelsamar
2. You should find him northeast of Thelsmar just standing there
3. He should be patrolling on the east side road of Thelsmar from the points you have seen in the screenshot
4. ...
5. Profit

### Crashlog

- None

**Comment by cala** [comment]
Waypoints are available in Classic for this NPC.

**Comment by AnonXS** [comment]
pretty sure we have this in classic/tbc-db

**Comment by al3xc1985** [comment]
@killerwife this was implemented by @Grz3s

**Comment by al3xc1985** [comment]
@AnonXS I remember u ported fix for this from wotlk
