### ISSUE TITLE
🐛 [Bug Report][Quest]Resupplying the Excavation

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#2273]
## 🐛 Bugreport

The latest commit to this quest has added the missing part but not in a correct way. The yellow quest marker is yet available over Huldars Head during the fight and Mirans Yell is not appearing as a text field only in chat you can see his yell.

### Expected behavior

Yellow Quest Marker shouldnt be visible during the fight and Mirans Yell should also be viewable in the world as a text field. (Red letters)

### Version & Environment

Client Version: 
3.3.5a

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-wotlk/commit/304670f61256f9c743379a5168c868d28b8c45d7

Database Repo & Commit Hash: 
https://github.com/cmangos/wotlk-db/commit/581f826dd7db7279aa095b674e1ace504125e6c8

Operating System: 
Windows 10
### Steps to reproduce
1. .q add 273
2. Walk towards the map marker
3. ...
4. Profit

### Crashlog

- None

**Comment by Grz3s** [comment]
Reason why you dont see Yell above npcs head is distance between you and him... and before you'll get close enough text bubble is already gone. (btw: theres no option to display by npc X text (say or yell).. that wont show up above his head... 
`he yellow quest marker is yet available over Huldars Head during the fight` -- will be corrected (thx for report)
