### ISSUE TITLE
🐛 [Bug Report] Account Create Command Doesn't Work From Console

### ISSUE THREAD

**Issue by schell244** [cmangos/issues#2274]
**Current behavior**: 
account create command from console does not work anymore (only tested on windows 10):

`account create test test
Account created: test
mangos>SQL: INSERT INTO account(username,v,s,joindate) VALUES('TEST','3A613E757A8CF7F79E587CA04211038EB73F59E5F3772E67519248278B628235','ECBC3CAC5749D4D366F8A668D2A634E6F409A3350508B6E1D2A7E2213F4F7761',NOW())
SQL ERROR: Incorrect datetime value: '0000-00-00 00:00:00' for column 'last_login' at row 1`

MySQL server ver: 5.7.30

**Commit hash**: 
8a7115f

**Operating system**: 
Windows 10

**Comment by jimmybrancaccio** [comment]
@schell244 Please provide _all_ of the information as requested in the bug report template.

**Comment by schell244** [comment]
Issue is no longer reproducible with latest core version 279fe2f
