### ISSUE TITLE
💬 [Support Request] Large Creature Out of Sight

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2275]
## 💬 Support Request

Large creature out of sight in cave, because they are too large, some must be reduced by half to return in line of sight.
Creature can't attack and player can't cast spell because target not in line of sight

### Version & Environment   

Client Version: "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: 8c5ae1b39a69c0d7af00feef393df1c7dfa458ec

### Steps to reproduce

1.Create a hero level 60 class=mage
2.Go to firegute brute .go creature 4610
3.cast fireball
4.reduce creature .mod scale 1
5.creature can attack and player can cast spell

### Crashlog
None

**Comment by Daedalus-code** [comment]
![NotInLine](https://user-images.githubusercontent.com/59256533/94160925-74afb880-fe85-11ea-90e4-e7486c110ae2.jpg)

Damn brute 😅

**Comment by adellaci** [comment]
Map issue?Sent from my smartphone
-------- Original message --------From: Daedalus-code <notifications@github.com> Date: 9/24/20  10:47 AM  (GMT-05:00) To: cmangos/issues <issues@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [cmangos/issues] 💬 [Support Request]Large creature out of sight (#2275) 



Damn brute 😅

**Comment by killerwife** [comment]
The function responsible for this is called GetCollisionHeight()
What is of note however is that in vanilla model scale works differently. While the code is still appropriate, maybe the DBC data is in a different state. @cala you know how vanilla model scale works. Can you please look at it whether it makes sense? CreatureModelData.dbc is I believe the dbc that contains model height and that is used by the function above.

**Comment by AnonXS** [comment]
As far as i can tell, this is a general issue we have at the moment

**Comment by fatalieror** [comment]
So if you can modify the Height in the DBC and it would fix the problem?

**Comment by al3xc1985** [comment]
@cyberium would you dbc patch help to make it easier for cases like this? I poke cyberium in here, maybe his dbc patch can be mandatory for many cases like this one
