### ISSUE TITLE
🐛 [Bug Report] [TBC] cMangos Make Error

### ISSUE THREAD

**Issue by anybodykilla** [cmangos/issues#2276]
## 🐛 Bugreport
Downloaded the git repos for TBC.  Created build folder in mangos-tbc folder and ran following cmake command
`cmake .. -DCMAKE_INSTALL_PREFIX=\../run -DBUILD_EXTRACTORS=ON -DPCH=1 -DDEBUG=0`
After I ran `make -j6`.  During the build it errors out and references my_bool as not been declared.

Scanning dependencies of target shared
[  4%] Building CXX object src/shared/CMakeFiles/shared.dir/cmake_pch.hxx.gch
[  5%] Building CXX object dep/recastnavigation/Detour/CMakeFiles/detour.dir/Source/DetourNavMeshBuilder.cpp.o
[  5%] Building CXX object dep/g3dlite/CMakeFiles/g3dlite.dir/BinaryInput.cpp.o
[  5%] Building CXX object dep/recastnavigation/Detour/CMakeFiles/detour.dir/Source/DetourNavMeshQuery.cpp.o
[  5%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/recast.dir/Source/RecastFilter.cpp.o
[  5%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/recast.dir/Source/RecastLayers.cpp.o
[  5%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/recast.dir/Source/RecastMesh.cpp.o
[  5%] Building CXX object dep/recastnavigation/Detour/CMakeFiles/detour.dir/Source/DetourNode.cpp.o
In file included from /wow/cmake-test/mangos-tbc/src/shared/Database/DatabaseEnv.h:41,
                 from /wow/cmake-test/mangos-tbc/src/shared/pchdef.h:34,
                 from /wow/cmake-test/mangos-tbc/build/src/shared/CMakeFiles/shared.dir/cmake_pch.hxx:5,
                 from <command-line>:
/wow/cmake-test/mangos-tbc/src/shared/Database/DatabaseMysql.h:50:75: error: ‘my_bool’ has not been declared
   50 |         static enum_field_types ToMySQLType(const SqlStmtFieldData& data, my_bool& bUnsigned);

Editing this /wow/cmake-test/mangos-tbc/src/shared/Database/DatabaseMysql.h file at 50:75 by changing my_bool to bool enables you to get further, but it errors out again.

Scanning dependencies of target mmaplib
[ 16%] Building CXX object contrib/mmap/CMakeFiles/mmaplib.dir/src/IntermediateValues.cpp.o
[ 16%] Building CXX object contrib/mmap/CMakeFiles/mmaplib.dir/src/TerrainBuilder.cpp.o
[ 16%] Building CXX object contrib/mmap/CMakeFiles/mmaplib.dir/src/VMapExtensions.cpp.o
[ 16%] Building CXX object contrib/mmap/CMakeFiles/mmaplib.dir/src/MapBuilder.cpp.o
[ 16%] Building CXX object src/shared/CMakeFiles/shared.dir/Auth/AuthCrypt.cpp.o
[ 17%] Building CXX object src/shared/CMakeFiles/shared.dir/Auth/Sha1.cpp.o
[ 17%] Building CXX object src/shared/CMakeFiles/shared.dir/Auth/HMACSHA1.cpp.o
[ 17%] Building CXX object src/shared/CMakeFiles/shared.dir/Auth/BigNumber.cpp.o
[ 17%] Building CXX object src/shared/CMakeFiles/shared.dir/Auth/base32.cpp.o
[ 17%] Building CXX object src/shared/CMakeFiles/shared.dir/Config/Config.cpp.o
[ 17%] Building CXX object src/shared/CMakeFiles/shared.dir/Database/Database.cpp.o
[ 17%] Building CXX object src/shared/CMakeFiles/shared.dir/Database/DatabaseMysql.cpp.o
[ 17%] Building CXX object src/shared/CMakeFiles/shared.dir/Database/DatabasePostgre.cpp.o
/wow/cmake-test/mangos-tbc/src/shared/Database/DatabaseMysql.cpp: In member function ‘void MySqlPreparedStatement::addParam(unsigned int, const SqlStmtFieldData&)’:
/wow/cmake-test/mangos-tbc/src/shared/Database/DatabaseMysql.cpp:420:5: error: ‘my_bool’ was not declared in this scope; did you mean ‘bool’?
  420 |     my_bool bUnsigned = 0;
      |     ^~~~~~~
      |     bool
/wow/cmake-test/mangos-tbc/src/shared/Database/DatabaseMysql.cpp:421:51: error: ‘bUnsigned’ was not declared in this scope; did you mean ‘unsigned’?
  421 |     enum_field_types dataType = ToMySQLType(data, bUnsigned);
      |                                                   ^~~~~~~~~
      |                                                   unsigned
/wow/cmake-test/mangos-tbc/src/shared/Database/DatabaseMysql.cpp: At global scope:
/wow/cmake-test/mangos-tbc/src/shared/Database/DatabaseMysql.cpp:465:84: error: ‘my_bool’ has not been declared
  465 | enum_field_types MySqlPreparedStatement::ToMySQLType(const SqlStmtFieldData& data, my_bool& bUnsigned)
      |                                                                                    ^~~~~~~
/wow/cmake-test/mangos-tbc/src/shared/Database/DatabaseMysql.cpp:465:18: error: no declaration matches ‘enum_field_types MySqlPreparedStatement::ToMySQLType(const SqlStmtFieldData&, int&)’
  465 | enum_field_types MySqlPreparedStatement::ToMySQLType(const SqlStmtFieldData& data, my_bool& bUnsigned)
      |                  ^~~~~~~~~~~~~~~~~~~~~~
In file included from /wow/cmake-test/mangos-tbc/src/shared/Database/DatabaseEnv.h:41,
                 from /wow/cmake-test/mangos-tbc/src/shared/pchdef.h:34,
                 from /wow/cmake-test/mangos-tbc/build/src/shared/CMakeFiles/shared.dir/cmake_pch.hxx:5,
                 from <command-line>:
/wow/cmake-test/mangos-tbc/src/shared/Database/DatabaseMysql.h:50:33: note: candidate is: ‘static enum_field_types MySqlPreparedStatement::ToMySQLType(const SqlStmtFieldData&, bool&)’
   50 |         static enum_field_types ToMySQLType(const SqlStmtFieldData& data, bool& bUnsigned);
      |                                 ^~~~~~~~~~~
/wow/cmake-test/mangos-tbc/src/shared/Database/DatabaseMysql.h:31:7: note: ‘class MySqlPreparedStatement’ defined here
   31 | class MySqlPreparedStatement : public SqlPreparedStatement
      |       ^~~~~~~~~~~~~~~~~~~~~~
[ 17%] Building CXX object src/shared/CMakeFiles/shared.dir/Database/Field.cpp.o
make[2]: *** [src/shared/CMakeFiles/shared.dir/build.make:184: src/shared/CMakeFiles/shared.dir/Database/DatabaseMysql.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 17%] Linking CXX static library libmmaplib.a
[ 17%] Built target mmaplib

Editing this file /wow/cmake-test/mangos-tbc/src/shared/Database/DatabaseMysql.cpp at 421:51and 465:18 by changing my_bool to bool removes all erros and make completes.  This is the first time I am using cmake and make, so I am unsure why this works.  I only attempted it when I stumbled across this post https://bugs.mysql.com/bug.php?id=85131.

### Expected behavior
After the above edits, make succeeds
[ 99%] Building CXX object src/mangosd/CMakeFiles/mangosd.dir/soapC.cpp.o
[100%] Building CXX object src/mangosd/CMakeFiles/mangosd.dir/soapServer.cpp.o
[100%] Linking CXX executable mangosd
[100%] Built target mangosd

### Version & Environment
Client Version: "2.4.3" (TBC) (not needed since this is before server is configured)
CMaNGOS Repo & Commit Hash: [TBC](https://github.com/cmangos/mangos-tbc/tree/75ec8e9ea32235fd1bef794c6b2dca043603637b)
Database Repo & Commit Hash: [TBC](https://github.com/cmangos/tbc-db/tree/f591765ca68d87c96010057aeacb5caf2902a239)
Operating System - Ubuntu Server 20.04

### Steps to reproduce
1. Install unbuntu server 20.04 in hyper-v on windows 10 using this iso ubuntu-20.04.1-live-server-amd64.iso (6 virtual processors, 10240MB ram, 150GB hard drive on ssd, secure boot DISABLED)
2. After updating server follow install unstructions here https://github.com/cmangos/issues/wiki/Installation-Instructions (be sure to set root password after installing prereqs)
3. After cmake commands, run "make -j6" and wait for error.
4. Make the change of my_bool to bool in both files, run "make -j6"
5. Profit

### Crashlog
- None

If this needs to be posted somewhere else, let me know.  Also not sure if this is a bug, but it may help someone with the same issue.

**Comment by linuxthat** [comment]
I've been able to replicate this as well on multiple installs - I'm not sure why this is the default but updating the files gets a clean compile every time.

**Comment by evil-at-wow** [comment]
You're seeing this error because you're using a MySQL 8 (or later) API to compile the core, but the core does not support the API of MySQL 8 (or later) yet. MariaDB seems to still have the old my_bool type. See the comments in #2285.

I suggest we continue any discussion in #2285 instead of keeping multiple issues open for the same core issue.
