### ISSUE TITLE
🚀 [Feature Request] Casters and Structures LOS Check

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2277]
## 🚀 Feature
 The problem is that if u fight with a caster and have mmap enabled and vmap also enabled casters can still cast through buildings

even with this settings:
vmap.enableLOS = 1
vmap.enableHeight = 1
vmap.ignoreSpellIds = "7720"
vmap.enableIndoorCheck = 1
DetectPosCollision = 1
mmap.enabled = 1

### Benefits & Purpose

The benefits are a VERY better gameplay!

**Comment by al3xc1985** [comment]
I want to add that mobs see me through trees for example and aggro! it is a game breake

**Comment by al3xc1985** [comment]
after a small talk with @AnonXS he gave me a link with this 
https://github.com/TrinityCore/TrinityCore/issues/3495

but 
![WoWScrnShot_092520_224059](https://user-images.githubusercontent.com/6240049/94309525-e587cb00-ff80-11ea-85f5-0edddd496619.jpg)

**Comment by al3xc1985** [comment]
ok
I tested out with the same npc Defias Rogue Wizard on a big building in goldshire and it is working perfect

my questions is... building like those should be included in vmaps system? should be extracted?

and judging by the link provided by @AnonXS trees are not included... u guys judge if this is tottally correct and what is correct

ty for your great effor and work

**Comment by jimmybrancaccio** [comment]
@al3xc1985 Please provide _all_ of the information as requested in the bug report template.

**Comment by AnonXS** [comment]
WMO case

**Comment by killerwife** [comment]
Recently I changed it so that even GO m2 are ignored so I am guessing this is blizzlike.
