### ISSUE TITLE
🐛 [Bug Report] error compiling

### ISSUE THREAD

**Issue by stan84** [cmangos/issues#2279]
/home/classicrealm/mangos-classic/src/game/BattleGround/BattleGroundWS.cpp: In member function ‘virtual void BattleGroundWS::EventPlayerClickedOnFlag(Player*, GameObject*)’:
/home/classicrealm/mangos-classic/src/game/BattleGround/BattleGroundWS.cpp:419:61: error: ‘class GameObject’ has no member named ‘IsAtInteractDistance’; did you mean ‘GetInteractionDistance’?
     else if (state == BG_WS_FLAG_STATE_ON_GROUND && target->IsAtInteractDistance(player) && GroundFlagInteraction(player, target) == BG_WS_FLAG_ACTION_NONE)
                                                             ^~~~~~~~~~~~~~~~~~~~
                                                             GetInteractionDistance
src/game/CMakeFiles/game.dir/build.make:5342: recipe for target 'src/game/CMakeFiles/game.dir/BattleGround/BattleGroundWS.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/BattleGround/BattleGroundWS.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:622: recipe for target 'src/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

  - "1.12.1" (CLASSIC)

**Comment by berserkingyadis** [comment]
setting reminder to test and close this after https://github.com/cmangos/issues/issues/2280 has been fixed

**Comment by adellaci** [comment]
I had no issue with compiling as of 09/27/20 pull 10:30 EST

**Comment by jimmybrancaccio** [comment]
@stan84 Please provide _all_ of the information as requested in the bug report template.

**Comment by jimmybrancaccio** [comment]
Closing this as issue has not been updated with complete information. If this is still an issue please create a new issue in GitHub with the full details as requested by the bug reporting template. Thank you.
