### ISSUE TITLE
🐛 [Bug Report]The  mobs which has waypoints in the dungeon, start to falling underground just after GridCleanUpDelay time(5min).

### ISSUE THREAD

**Issue by ckj777** [cmangos/issues#2281]
## 🐛 Bugreport

The  mobs which has waypoints in the dungeon, start to falling underground just after GridCleanUpDelay time(5min).
(mob list below)
Thay are stucked and disappeared when I come close to it. After that Client sometimes crashed and became unstable.

Here is mob list ( guid [entry] )

Shattered Hall
5400302 [17695] Shattered Hand Assassin
5400169 [17465] Shattered Hand Centurion
5400170 [17465] Shattered Hand Centurion
5400062 [16700] Shattered Hand Legionnaire
5400264 [16700] Shattered Hand Legionnaire
5400268 [17670] Shattered Hand Houndmaster
5400171 [17465] Shattered Hand Centurion
5400172 [17465] Shattered Hand Centurion
5400283 [17670] Shattered Hand Houndmaster
5400286 [17695] Shattered Hand Assassin
5400287 [17695] Shattered Hand Assassin
5400288 [17695] Shattered Hand Assassin
5400289 [17695] Shattered Hand Assassin
5400290 [17695] Shattered Hand Assassin
5400271 [17670] Shattered Hand Houndmaster

Bot
5530001 [17975] High Botanist Freywinn
5530002 [17976] Commander Sarannis
5530061 [18421] Sunseeker Researcher

I think every mob which was not defeated within GridCleanUpDelay(5min) can be the candidate of this symptom.

Details in youtube link below..

### Version & Environment

Client Version:  2.4.3" (TBC)

CMaNGOS Repo & Commit Hash:  latest

Database Repo & Commit Hash:  latest

Operating System:  Windows 10 x64

### Steps to reproduce
1.  https://www.youtube.com/watch?v=bXlUpjPQFms
2. 
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by AnonXS** [comment]
i can not replicate this issue.

![grafik](https://user-images.githubusercontent.com/19734826/219362106-23ed1080-f553-4d77-b133-75f22e17418b.png)

**Comment by Grz3s** [comment]
i also stood i exact same place where avi was recorded for good 10 mins.. and nothing wrong happened.
Not confirmed.
