### ISSUE TITLE
Life tap of Warlocks doesn't work in WOTLK

### ISSUE THREAD

**Issue by playfcode** [cmangos/issues#2283]
Life tap of Warlocks doesn't work in WOTLK, but it was normal a few days ago.
I have uploaded the video of the issue:
https://youtu.be/Xio8_wVnr0U

**Comment by D3thw0lf** [comment]
Can confirm that it also not working on TBC.

**Proof:**
https://youtu.be/BmsJNK36zYw

**Core Rev:** 584a5169367d707f8a0ff6e09f2e59bd8d94ba30
**DB Rev:** f90625a730f4771de8fca1cd2a2ee28ea137ed09
**Version:** 2.4.3

**Comment by xfurry** [comment]
CC @killerwife  again

**Comment by jimmybrancaccio** [comment]
@playfcode Please provide _all_ of the information as requested in the bug report template.

**Comment by yitugege** [comment]
yes,it is true that not woking on tbc

**Comment by killerwife** [comment]
Retested, seems to be working again.
