### ISSUE TITLE
🐛 [Bug Report] Complie error under MySQL 8.xx.xx

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2285]
## 🐛 Bugreport
Another error compiling. I'm porviding more information, because i change to Ubuntu 20.04.1 Server LTS, incase there is a version issue

GNU Make 4.2.1
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
cmake version 3.16.9
mysql  Ver 8.0.21-0ubuntu0.20.04.4 for Linux on x86_64 ((Ubuntu))
libboost-dev version (1.71.0.0ubuntu2)

-- CMaNGOS-Core revision : 0e2f0e018c49b6eaf6e6764ef764022142bacd29

cmake ~/mangos/mangos-wotlk -DCMAKE_INSTALL_PREFIX=~/wow-servers/mangos-server-wotlk -DBUILD_EXTRACTORS=ON -DBUILD_AHBOT=ON -DBUILD_PLAYERBOT=ON -DPCH=1 -DDEBUG=0 -DBUILD_RECASTDEMOMOD=ON ; make -j12

-- Detected 64-bit platform
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- GCC: SFMT enabled, SSE2 flags forced
-- cotire 1.7.6 loaded.
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- CMaNGOS-Core revision : 0e2f0e018c49b6eaf6e6764ef764022142bacd29
-- Revision time stamp   : "2020-09-15T21:15:07+02:00"
-- Install server to     : /home/mangos/wow-servers/mangos-server-wotlk
-- Use PCH               : Yes (default)
-- Build in debug-mode   : No  (default)
-- Build game server     : Yes (default)
-- Build login server    : Yes (default)
-- Build ScriptDev       : Yes (default)
-- Build AHBot           : Yes
-- Build Playerbot       : Yes
-- Build extractors      : Yes
-- Build RecastDemoMod   : Yes
-- Build git_id          : No  (default)
-- Build documentation   : No  (default)

[  7%] Building CXX object dep/g3dlite/CMakeFiles/g3dlite.dir/Ray.cpp.o
In file included from /home/mangos/mangos/mangos-wotlk/src/shared/Database/DatabaseEnv.h:41,
                 from /home/mangos/mangos/mangos-wotlk/src/shared/pchdef.h:34,
                 from /home/mangos/build-wotlk/src/shared/CMakeFiles/shared.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/mangos/mangos/mangos-wotlk/src/shared/Database/DatabaseMysql.h:50:75: error: ‘my_bool’ has not been declared
   50 |         static enum_field_types ToMySQLType(const SqlStmtFieldData& data, my_bool& bUnsigned);
      |                                                                           ^~~~~~~
make[2]: *** [src/shared/CMakeFiles/shared.dir/build.make:67: src/shared/CMakeFiles/shared.dir/cmake_pch.hxx.gch] Error 1
make[1]: *** [CMakeFiles/Makefile2:823: src/shared/CMakeFiles/shared.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by evil-at-wow** [comment]
The reason is that you're compiling against a newer MySQL now. The my_bool type was removed from the MySQP API with MySQL 8, but we still build against MySQL 5.7.

I'm pretty sure I've seen a PR or issue that changes the code, but I can't find it right now. I've also been wondering if we shouldn't update that and start supporting newer MySQL (or MariaDB) versions.

**Comment by adellaci** [comment]
@evil-at-wow  Thank you. I'll look into what i can do to fix it. If you do come across that info please forward on to me.

**Comment by adellaci** [comment]
@evil-at-wow it is safe to assume that it will be the same issue under Classic, & TBC

**Comment by adellaci** [comment]
Here is what found from the MySQL doc page:
```
my_bool

A boolean type, for values that are true (nonzero) or false (zero). The my_bool type was used before MySQL 8.0. As of MySQL 8.0, use the bool or int C type instead.
Note

The change from my_bool to bool means that the mysql.h header file requires a C++ or C99 compiler to compile.
```

**Comment by adellaci** [comment]
I found this article to install version 5.7 for both server and client side, for Ubuntu 20.04, and it looks like it may work for 18.04 also
[](https://computingforgeeks.com/how-to-install-mysql-on-ubuntu-focal/)

**Comment by evil-at-wow** [comment]
Yes, you'll have the same issue in all cores (Classic / TBC / WotLK).

A code change to make the cores build against MySQL 8 (or similar in MariaDB) is rather trivial, I'm just not sure if it then still works with MySQL 5.7 and earlier (the MySQL release notes mark it as an incompatible change, which I could understand seeing the different types involved), and if not, whether we want to drop support for those older versions then.

Using MySQL 5.7 on Ubuntu 18.04 is certainly possible (but I don't know how), because that's what we get in our TravisCI environment by default (the default Ubuntu 20.04 image in TravisCI comes with MySQL 8). And alternative to getting MySQL 5.7 on Ubuntu could be trying to get MariaDB instead, because as far as I'm aware, MariaDB still uses my_bool, also in recent versions.

**Comment by adellaci** [comment]
I am going to attempt a downgrade. I'll let you know how it turns out.

**Comment by adellaci** [comment]
@evil-at-wow the downgrade did not go so well. Rebuilding server from scratch.

**Comment by jimmybrancaccio** [comment]
Side note here - I've been building against MariaDB 10.4.x for a while now - no issues.

**Comment by killerwife** [comment]
I use 8 on both my machines and it works perfectly. All cores.

**Comment by adellaci** [comment]
How did you get over the compile error for boolean type

**Comment by adellaci** [comment]
Well i just rebuild my Server from scratch and installed MySQL 5.7. I have another server that i just got. i'll set it up with MariaBD to try it. 
I'm getting ready to set up DB for classic, tbc, & wotlk. 
The goal is to be able to run all three version at the same time with a Dell R210 Server that is going to manage realms, and my Dell PowerEdge 2900 manage worlds

**Comment by adellaci** [comment]
WotLK Build
CMaNGOS-Core revision : 72b1964bc8159ecd692955711a05d97d9bcf494c
Generated this, but completed the build:
```
[[ 78%] Building CXX object src/game/CMakeFiles/game.dir/BattleGround/BattleGroundHandler.cpp.o
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGround.cpp: In member function ‘virtual void BattleGround::RemovePlayerAtLeave(ObjectGuid, bool, bool)’:
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGround.cpp:1273:49: warning: enumeral mismatch in conditional expression: ‘ArenaSpells’ vs ‘BattleGroundSpells’ [-Wenum-compare]
         player->RemoveAurasDueToSpell(IsArena() ? SPELL_ARENA_DAMPENING : SPELL_BATTLEGROUND_DAMPENING);
                                       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 78%] Building CXX object src/game/CMakeFiles/game.dir/BattleGround/BattleGroundIC.cpp.o
[ 78%] Building CXX object src/game/CMakeFiles/game.dir/BattleGround/BattleGroundMgr.cpp.o
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGroundAB.cpp: In member function ‘virtual void BattleGroundAB::HandlePlayerClickedOnFlag(Player*, GameObject*)’:
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGroundAB.cpp:298:31: warning: comparison between ‘enum ABNodeStatus’ and ‘enum ABNodeType’ [-Wenum-compare]
     if (m_nodeStatus[node] == BG_AB_NODE_TYPE_NEUTRAL)
                               ^~~~~~~~~~~~~~~~~~~~~~~
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGroundAB.cpp:319:38: warning: comparison between ‘enum ABNodeStatus’ and ‘enum ABNodeType’ [-Wenum-compare]
         if (m_prevNodeStatus[node] < BG_AB_NODE_TYPE_OCCUPIED)
                                      ^~~~~~~~~~~~~~~~~~~~~~~~
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGroundAV.cpp: In member function ‘virtual void BattleGroundAV::Update(uint32)’:
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGroundAV.cpp:269:58: warning: comparison between ‘enum AVNodeIds’ and ‘enum AVGenericVariables’ [-Wenum-compare]
     for (AVNodeIds i = BG_AV_NODES_FIRSTAID_STATION; i < BG_AV_MAX_NODES; ++i)
                                                          ^~~~~~~~~~~~~~~
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGroundAV.cpp: In member function ‘virtual void BattleGroundAV::EndBattleGround(Team)’:
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGroundAV.cpp:319:58: warning: comparison between ‘enum AVNodeIds’ and ‘enum AVGenericVariables’ [-Wenum-compare]
     for (AVNodeIds i = BG_AV_NODES_FIRSTAID_STATION; i < BG_AV_MAX_NODES; ++i)
                                                          ^~~~~~~~~~~~~~~
[ 78%] Building CXX object src/game/CMakeFiles/game.dir/BattleGround/BattleGroundNA.cpp.o
[ 78%] Building CXX object src/game/CMakeFiles/game.dir/BattleGround/BattleGroundRB.cpp.o
[ 78%] Building CXX object src/game/CMakeFiles/game.dir/BattleGround/BattleGroundRL.cpp.o
[ 78%] Building CXX object src/game/CMakeFiles/game.dir/BattleGround/BattleGroundRV.cpp.o
In file included from /home/mangos/cmangos/wotlk/src/shared/Database/DatabaseEnv.h:23:0,
                 from /home/mangos/cmangos/wotlk/src/game/Entities/Player.h:27,
                 from /home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGroundEY.cpp:20:
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGroundEY.cpp: In member function ‘virtual void BattleGroundEY::HandlePlayerClickedOnFlag(Player*, GameObject*)’:
/home/mangos/cmangos/wotlk/src/shared/Log.h:260:38: warning: too many arguments for format [-Wformat-extra-args]
             sLog.outDebug(__VA_ARGS__);                 \
                                      ^
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGroundEY.cpp:479:5: note: in expansion of macro ‘DEBUG_LOG’
     DEBUG_LOG("BattleGroundEY: Team %u has taken the flag, gameobject entry.", source->GetTeam(), go->GetEntry());
     ^
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGroundAV.cpp: In member function ‘virtual void BattleGroundAV::FillInitialWorldStates(WorldPacket&, uint32&)’:
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGroundAV.cpp:641:107: warning: iteration 1 invokes undefined behavior [-Waggressive-loop-optimizations]
             FillInitialWorldState(data, count, avMineWorldStates[i][GetWorldStateType(j, TEAM_INDEX_HORDE)], m_nodes[i].owner == TEAM_INDEX_HORDE && stateok);
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGroundAV.cpp:637:29: note: within this loop
         for (uint8 j = 0; j < BG_AV_MAX_STATES; ++j)
                           ~~^~~~~~~~~~~~~~~~~~
[ 78%] Building CXX object src/game/CMakeFiles/game.dir/BattleGround/BattleGroundSA.cpp.o
```
Classic build
CMaNGOS-Core revision : 97ac726ca38828b1b7af7d35d109e518b6059f2c
Generated this, but completed the build;
```
[ 66%] Building CXX object src/game/CMakeFiles/game.dir/Chat/ChannelHandler.cpp.o
/home/mangos/cmangos/classic/src/game/BattleGround/BattleGroundAB.cpp: In member function ‘virtual void BattleGroundAB::HandlePlayerClickedOnFlag(Player*, GameObject*)’:
/home/mangos/cmangos/classic/src/game/BattleGround/BattleGroundAB.cpp:288:31: warning: comparison between ‘enum ABNodeStatus’ and ‘enum ABNodeType’ [-Wenum-compare]
     if (m_nodeStatus[node] == BG_AB_NODE_TYPE_NEUTRAL)
                               ^~~~~~~~~~~~~~~~~~~~~~~
/home/mangos/cmangos/classic/src/game/BattleGround/BattleGroundAB.cpp:306:38: warning: comparison between ‘enum ABNodeStatus’ and ‘enum ABNodeType’ [-Wenum-compare]
         if (m_prevNodeStatus[node] < BG_AB_NODE_TYPE_OCCUPIED)
                                      ^~~~~~~~~~~~~~~~~~~~~~~~
[ 67%] Building CXX object src/game/CMakeFiles/game.dir/Chat/ChannelMgr.cpp.o
/home/mangos/cmangos/classic/src/game/BattleGround/BattleGroundAV.cpp: In member function ‘virtual void BattleGroundAV::Update(uint32)’:
/home/mangos/cmangos/classic/src/game/BattleGround/BattleGroundAV.cpp:269:58: warning: comparison between ‘enum AVNodeIds’ and ‘enum AVGenericVariables’ [-Wenum-compare]
     for (AVNodeIds i = BG_AV_NODES_FIRSTAID_STATION; i < BG_AV_MAX_NODES; ++i)
                                                          ^~~~~~~~~~~~~~~
/home/mangos/cmangos/classic/src/game/BattleGround/BattleGroundAV.cpp: In member function ‘virtual void BattleGroundAV::EndBattleGround(Team)’:
/home/mangos/cmangos/classic/src/game/BattleGround/BattleGroundAV.cpp:316:58: warning: comparison between ‘enum AVNodeIds’ and ‘enum AVGenericVariables’ [-Wenum-compare]
     for (AVNodeIds i = BG_AV_NODES_FIRSTAID_STATION; i < BG_AV_MAX_NODES; ++i)
                                                          ^~~~~~~~~~~~~~~
[ 67%] Building CXX object src/game/CMakeFiles/game.dir/Chat/Chat.cpp.o
/home/mangos/cmangos/classic/src/game/BattleGround/BattleGroundAV.cpp: In member function ‘virtual void BattleGroundAV::FillInitialWorldStates(WorldPacket&, uint32&)’:
/home/mangos/cmangos/classic/src/game/BattleGround/BattleGroundAV.cpp:638:107: warning: iteration 1 invokes undefined behavior [-Waggressive-loop-optimizations]
             FillInitialWorldState(data, count, avMineWorldStates[i][GetWorldStateType(j, TEAM_INDEX_HORDE)], m_nodes[i].owner == TEAM_INDEX_HORDE && stateok);
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/mangos/cmangos/classic/src/game/BattleGround/BattleGroundAV.cpp:634:29: note: within this loop
         for (uint8 j = 0; j < BG_AV_MAX_STATES; ++j)
                           ~~^~~~~~~~~~~~~~~~~~
[ 67%] Building CXX object src/game/CMakeFiles/game.dir/Chat/ChatHandler.cpp.o
```
TBC build 
CMaNGOS-Core revision : 27c44a2c57f0a0a6ca873995b30093a6da8429c6
Generated this, but completed the build;
```
[ 75%] Building CXX object src/game/CMakeFiles/game.dir/BattleGround/BattleGroundWS.cpp.o
/home/mangos/cmangos/tbc/src/game/BattleGround/BattleGroundAV.cpp: In member function ‘virtual void BattleGroundAV::Update(uint32)’:
/home/mangos/cmangos/tbc/src/game/BattleGround/BattleGroundAV.cpp:269:58: warning: comparison between ‘enum AVNodeIds’ and ‘enum AVGenericVariables’ [-Wenum-compare]
     for (AVNodeIds i = BG_AV_NODES_FIRSTAID_STATION; i < BG_AV_MAX_NODES; ++i)
                                                          ^~~~~~~~~~~~~~~
/home/mangos/cmangos/tbc/src/game/BattleGround/BattleGroundAV.cpp: In member function ‘virtual void BattleGroundAV::EndBattleGround(Team)’:
/home/mangos/cmangos/tbc/src/game/BattleGround/BattleGroundAV.cpp:316:58: warning: comparison between ‘enum AVNodeIds’ and ‘enum AVGenericVariables’ [-Wenum-compare]
     for (AVNodeIds i = BG_AV_NODES_FIRSTAID_STATION; i < BG_AV_MAX_NODES; ++i)
                                                          ^~~~~~~~~~~~~~~
/home/mangos/cmangos/tbc/src/game/BattleGround/BattleGroundAB.cpp: In member function ‘virtual void BattleGroundAB::HandlePlayerClickedOnFlag(Player*, GameObject*)’:
/home/mangos/cmangos/tbc/src/game/BattleGround/BattleGroundAB.cpp:288:31: warning: comparison between ‘enum ABNodeStatus’ and ‘enum ABNodeType’ [-Wenum-compare]
     if (m_nodeStatus[node] == BG_AB_NODE_TYPE_NEUTRAL)
                               ^~~~~~~~~~~~~~~~~~~~~~~
/home/mangos/cmangos/tbc/src/game/BattleGround/BattleGroundAB.cpp:306:38: warning: comparison between ‘enum ABNodeStatus’ and ‘enum ABNodeType’ [-Wenum-compare]
         if (m_prevNodeStatus[node] < BG_AB_NODE_TYPE_OCCUPIED)
                                      ^~~~~~~~~~~~~~~~~~~~~~~~
[ 75%] Building CXX object src/game/CMakeFiles/game.dir/Chat/Channel.cpp.o
In file included from /home/mangos/cmangos/tbc/src/shared/Database/DatabaseEnv.h:23:0,
                 from /home/mangos/cmangos/tbc/src/game/Entities/Player.h:27,
                 from /home/mangos/cmangos/tbc/src/game/BattleGround/BattleGroundEY.cpp:20:
/home/mangos/cmangos/tbc/src/game/BattleGround/BattleGroundEY.cpp: In member function ‘virtual void BattleGroundEY::HandlePlayerClickedOnFlag(Player*, GameObject*)’:
/home/mangos/cmangos/tbc/src/shared/Log.h:259:38: warning: too many arguments for format [-Wformat-extra-args]
             sLog.outDebug(__VA_ARGS__);                 \
                                      ^
/home/mangos/cmangos/tbc/src/game/BattleGround/BattleGroundEY.cpp:453:5: note: in expansion of macro ‘DEBUG_LOG’
     DEBUG_LOG("BattleGroundEY: Team %u has taken the flag, gameobject entry.", source->GetTeam(), go->GetEntry());
     ^
[ 75%] Building CXX object src/game/CMakeFiles/game.dir/Chat/ChannelHandler.cpp.o
[ 76%] Building CXX object src/game/CMakeFiles/game.dir/Chat/ChannelMgr.cpp.o
/home/mangos/cmangos/tbc/src/game/BattleGround/BattleGroundAV.cpp: In member function ‘virtual void BattleGroundAV::FillInitialWorldStates(WorldPacket&, uint32&)’:
/home/mangos/cmangos/tbc/src/game/BattleGround/BattleGroundAV.cpp:638:107: warning: iteration 1 invokes undefined behavior [-Waggressive-loop-optimizations]
             FillInitialWorldState(data, count, avMineWorldStates[i][GetWorldStateType(j, TEAM_INDEX_HORDE)], m_nodes[i].owner == TEAM_INDEX_HORDE && stateok);
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/mangos/cmangos/tbc/src/game/BattleGround/BattleGroundAV.cpp:634:29: note: within this loop
         for (uint8 j = 0; j < BG_AV_MAX_STATES; ++j)
                           ~~^~~~~~~~~~~~~~~~~~
[ 76%] Building CXX object src/game/CMakeFiles/game.dir/Chat/Chat.cpp.o
```

**Comment by alexeijd** [comment]
something like this might work to fix missing my_bool:
`#if !defined(MARIADB_BASE_VERSION) && !defined(MARIADB_VERSION_ID) && \
  MYSQL_VERSION_ID >= 80001 && MYSQL_VERSION_ID != 80002
typedef bool my_bool;
#endif`

**Comment by killerwife** [comment]
I do have mysql 8 on my windows and it works fine huh.

**Comment by evil-at-wow** [comment]
It's not the version that's running that's important (MySQL 8 works fine then). It's rather the API you compile the core with. 
On Windows, we're building with the headers in dep/lib/include/mysql so these are still good, but on other platforms we're typically using the API installed on the system instead. And that's not always pre MySQL 8 or MariaDB.

**Comment by metacreo** [comment]
--- mangos/src/shared/Database/DatabaseMysql.cpp	2019-07-09 13:47:15.449152000 +0300
+++ mangos/src/shared/Database/DatabaseMysql.cpp	2019-07-09 14:28:33.000000000 +0300
@@ -416,7 +416,7 @@
 
     MYSQL_BIND& pData = m_pInputArgs[nIndex];
 
-    my_bool bUnsigned = 0;
+    bool bUnsigned = 0;
     enum_field_types dataType = ToMySQLType(data, bUnsigned);
 
     // setup MYSQL_BIND structure
@@ -461,7 +461,7 @@
     return true;
 }
 
-enum_field_types MySqlPreparedStatement::ToMySQLType(const SqlStmtFieldData& data, my_bool& bUnsigned)
+enum_field_types MySqlPreparedStatement::ToMySQLType(const SqlStmtFieldData& data, bool& bUnsigned)
 {
     bUnsigned = 0;
     enum_field_types dataType = MYSQL_TYPE_NULL;

--- mangos/src/shared/Database/DatabaseMysql.h	2019-07-09 13:47:15.449198000 +0300
+++ mangos/src/shared/Database/DatabaseMysql.h	2019-07-09 14:28:46.000000000 +0300
@@ -51,7 +51,7 @@
         // bind parameters
         void addParam(unsigned int nIndex, const SqlStmtFieldData& data);
 
-        static enum_field_types ToMySQLType(const SqlStmtFieldData& data, my_bool& bUnsigned);
+        static enum_field_types ToMySQLType(const SqlStmtFieldData& data, bool& bUnsigned);
 
     private:
         void RemoveBinds();

**Comment by jimmybrancaccio** [comment]
@metacreo Is this something that allows not only 8.x but other versions of MySQL and MariaDB to work? If so why not create a PR?

Thanks!

**Comment by adellaci** [comment]
@killerwife  @evil-at-wow  @AnonXS 
Folks could this be closed out now?

**Comment by adellaci** [comment]
This is working now
