### ISSUE TITLE
🐛 [Bug Report] Objects related to Quests are no longer loot/clickable

### ISSUE THREAD

**Issue by D3thw0lf** [cmangos/issues#2287]
## 🐛 Bugreport
Since some commits (tested at least TBC and LK, but my main is TBC so look here for commit hash) after [this commit](https://github.com/cmangos/mangos-tbc/commit/0b3ebc585f58f955f6d31131eaa425601749b985) the Objects, related to Quests, are no longer lootable except if you do .gm on!

I first thought I broke something so I checked db, installed fresh etc. etc. but after reverting back to named hash I (and players) are once again able to loot said objects. So there must be something in the commits above named hash/commit that breaks them.

I've also checked LK and it's there, too.

### Expected behavior
Accept Quest with looting x of object and being able to do so...

### Version & Environment
Client Versions: 2.4.3 (TBC) & 3.3.5a (WOTLK)

CMaNGOS Repo & Commit Hash:
_Last (tested) commits where everything is as expected!_
[TBC](https://github.com/cmangos/mangos-tbc/commit/0b3ebc585f58f955f6d31131eaa425601749b985)
[WOTLK](https://github.com/cmangos/mangos-wotlk/commit/2ffa511727e2a3db754e5d47cb744ed51ae94f74)

Database Repo & Commit Hash: 
Not related as I've tested A LOT of stuff to finally find out that it must be something in core...

Operating System: 
Linux

### Steps to reproduce
1. Pull latest changes and compile
2. Login with a new character (e.g. Horde, Orc)
3. Accept Quest ".q add 4402"
4. ...
5. Profit

### Crashlog
- None

**Comment by killerwife** [comment]
@xfurry perhaps this is your thing?

**Comment by xfurry** [comment]
Since when does this happen?

**Comment by xfurry** [comment]
This could be the only change that might impact loot:
https://github.com/cmangos/mangos-wotlk/commit/1508c3b771b9cf8b3ab67c9750554e58c17ce7b8#diff-ea9456fe07807485d5cd91e79c49dcfdR1523

Can anyone chance that if we remove the condition highlighted above, it will fix the problem

**Comment by xfurry** [comment]
@D3thw0lf I reverted the commit that could have caused the problems: https://github.com/cmangos/mangos-wotlk/commit/57c6d153a3b6f33a22f263ffa9c063a15cdab272

If this issue still happens, that it's probably something else that we need to fix.

**Comment by D3thw0lf** [comment]
I'll try that out in a minute. Thanks so far :)

**Comment by D3thw0lf** [comment]
![WoWScrnShot_100920_173953](https://user-images.githubusercontent.com/895448/95603414-8765e800-0a56-11eb-9480-53a8b1cf9ed0.jpg)

Nope still not working. Tested with Q 5041

**Comment by xfurry** [comment]
Fixed in https://github.com/cmangos/mangos-wotlk/commit/8bbb55dd31d34e6846ac73d8d069ad8552656edf
Thanks!
