### ISSUE TITLE
🐛 [Bug Report] Adding bot will cause server dump

### ISSUE THREAD

**Issue by playfcode** [cmangos/issues#2288]
## 🐛 Bugreport

After I added a mage bot to assist a warlock in WOTLK, sometimes the server  dump, Similar problems have occurred before in TBC, but they are caused by addon, But this time I remove all the addons ,will still have the same problem.

![image](https://user-images.githubusercontent.com/69490311/95648422-85109600-0b09-11eb-9cc1-f26ddb4e4d74.png)

**Comment by jimmybrancaccio** [comment]
@playfcode Please provide _all_ of the information as requested in the bug report template.

**Comment by jimmybrancaccio** [comment]
Closing this as issue has not been updated with complete information. If this is still an issue please create a new issue in GitHub with the full details as requested by the bug reporting template. Thank you.
