### ISSUE TITLE
🐛 [Bug Report] Failure to compile game.lib for Classic

### ISSUE THREAD

**Issue by Patrick-Barry** [cmangos/issues#2291]
## 🐛 Bugreport
Using a fresh install and compiling using Visual Studio 2019 produced the following errors:
C:\cmangos-classic\mangos\src\game\Entities\Unit.cpp(7495,55): error C2661: 'WorldObject::GetPosition': no overloaded function takes 0 arguments
C:\cmangos-classic\mangos\src\game\Entities\Unit.cpp(10512,93): error C2661: 'WorldObject::GetPosition': no overloaded function takes 0 arguments
C:\cmangos-classic\mangos\src\game\Entities\Unit.cpp(10649,91): error C2661: 'WorldObject::GetPosition': no overloaded function takes 0 arguments

### Expected behavior
Should compile without error.

### Version & Environment
Client Version: 1.12.1
CMaNGOS Repo & Commit Hash: d752899a0a4efadc12ff4fa904978b5bf6f91025
Database Repo & Commit Hash:  8963338e86d65fc658a242550fe9e79400ff3482

Operating System: Windows 10

### Steps to reproduce
1. Make a clean install of cmangos
2. Compile with Visual Studio 2019

### Crashlog
- None

**Comment by killerwife** [comment]
Fixed in https://github.com/cmangos/mangos-classic/commit/bd761a61fb5482868c8b031903d76e3ed927d3a0
