### ISSUE TITLE
🐛 [Bug Report][WOTLK] All escort quests are not working

### ISSUE THREAD

**Issue by GPinkie** [cmangos/issues#2292]
## 🐛 Bugreport
All escort quests i have come across in both eastern kingdom and kalimdor are currently not working. You can accept the quest, but when the quest is taken the npc does not move and you are unable to complete the quest. A few examples are.

- (Protect Kaya) https://classic.wowhead.com/quest=6523/protect-kaya

- (The Escape) https://classic.wowhead.com/quest=863/the-escape

- (Free From The Hold) https://classic.wowhead.com/quest=898/free-from-the-hold

- (The Defias Brotherhood) https://classic.wowhead.com/quest=155/the-defias-brotherhood

### Expected behavior
Npc's with escort quests should move when the quest is taken.

### Version & Environment

Client Version: "3.3.5a" (WOTLK)

CMaNGOS Repo & Commit Hash: 1024cebb954349e893cbdf8a7fdfb1ebd0c8146d

Database Repo & Commit Hash: 90d7420f41659d9f14adf27aea321b077b2aa586

Operating System: Win 10

### Steps to reproduce
1. Install database using ./installfulldb.sh
2. Go to any npc with an escort quest listed above
3. Take the quest
4. ...
5. Profit

### Crashlog

- None

**Comment by Grz3s** [comment]
just tested first one:
![escort](https://user-images.githubusercontent.com/2374069/96641625-e8c26c80-131c-11eb-95ad-2bf91c12f543.jpg)

all works correct

Pls check if sd2 scripts are loaded correctly ...
`SD2: Loading C++ scripts`
`Loaded 1246 C++ Scripts.`

**Comment by GPinkie** [comment]
Initializing Scripting Library...
  _____           _       _   _____
 / ____|         (_)     | | |  __ \
| (___   ___ _ __ _ _ __ | |_| |  | | _____   __
 \___ \ / __| '__| | '_ \| __| |  | |/ _ \ \ / /
 ____) | (__| |  | | |_) | |_| |__| |  __/\ V /
|_____/ \___|_|  |_| .__/ \__|_____/ \___| \_/
                   | |
                   |_| http://www.cmangos.net
SD2: Loading Script Texts...
Loading texts from script_texts, with additional data
>> Loaded 4663 text templates from script_texts

SD2: Loading Custom Texts...
Loading texts from custom_texts, with additional data

>> Loaded 0 string templates. DB table `custom_texts` is empty.
SD2: Loading Gossip Texts...
Loading texts from gossip_texts
>> Loaded 146 string templates from gossip_texts

SD2: Loading Script Waypoints for 125 creature(s)...
SD2: DB table `script_waypoint` has invalid point 0 for entry 467 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 1840 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 1842 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 1978 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 2713 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 2768 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 2917 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 3439 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 3465 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 3584 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 3678 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 3849 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 3850 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 4484 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 4500 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 4508 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 4880 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 4962 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 4983 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 5391 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 6182 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 6575 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 7780 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 7784 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 7806 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 7807 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 8284 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 9502 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 9503 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 9537 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 9598 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 9623 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 10096 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 10427 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 10638 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 10646 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 11016 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 11832 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 11856 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 12126 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 12423 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 12427 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 12428 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 12429 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 12430 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 12580 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 12717 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 12818 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 12858 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 15420 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 16295 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 16812 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 16993 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 17077 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 17225 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 17238 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 17312 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 17804 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 17876 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 17877 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 17969 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 17982 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 18209 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 18210 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 18887 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 19671 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 19685 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 20129 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 20281 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 20415 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 20763 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 20802 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 21027 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 22377 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 22458 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 22861 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 22863 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 22864 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 22916 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 23002 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 23340 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 23342 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 23344 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 23345 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 23346 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 23348 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 23383 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 23784 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 23790 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 23790 in path 1. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 23999 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 23999 in path 1. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 24001 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 24001 in path 1. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 24024 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 24175 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 24358 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 25208 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 25589 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 26499 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 26588 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 26814 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 28070 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 28217 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 29173 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 29434 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 30658 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 31279 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 31737 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 31833 in path 0. Skipping.
SD2: DB table `script_waypoint` has invalid point 0 for entry 32800 in path 0. Skipping.

>> Loaded 4399 Script Waypoint nodes.
SD2: Loading C++ scripts

Script registering but ScriptName boss_highlord_kruul is not assigned in database. Script will not be used.
Script registering but ScriptName npc_infernal_hound is not assigned in database. Script will not be used.
Script registering but ScriptName npc_war_effort is not assigned in database. Script will not be used.
Script registering but ScriptName go_portal_to_orgrimmar is not assigned in database. Script will not be used.
Script registering but ScriptName go_portal_to_undercity is not assigned in database. Script will not be used.
Script registering but ScriptName go_infernaling_summoner_portal_hound is not assigned in database. Script will not be used.
Script registering but ScriptName npc_agent_proudwell is not assigned in database. Script will not be used.
Script registering but ScriptName npc_blackwood_warrior is not assigned in database. Script will not be used.
Script registering but ScriptName npc_blackwood_totemic is not assigned in database. Script will not be used.
Script registering but ScriptName event_purify_food is not assigned in database. Script will not be used.
Script registering but ScriptName go_furbolg_food is not assigned in database. Script will not be used.
Script registering but ScriptName npc_captured_sprite_darter is not assigned in database. Script will not be used.
Script registering but ScriptName npc_kindal_moonweaver is not assigned in database. Script will not be used.
Script registering but ScriptName go_cage_door is not assigned in database. Script will not be used.
Script registering but ScriptName go_kaliri_nest is not assigned in database. Script will not be used.
>> Loaded 1231 C++ Scripts

sd2 is loading But with a few errors. And not 1246 C++ Scripts as you have.

**Comment by Grz3s** [comment]
smth is not right with your sources... (out of date?)
1st: ... non ef these errors shows up on clean compile

```
> 2020-10-20 21:33:59 SD2: Loading Script Texts...
> 2020-10-20 21:33:59 Loading texts from script_texts, with additional data
> 2020-10-20 21:33:59 >> Loaded 4700 text templates from script_texts
> 2020-10-20 21:33:59 
> 2020-10-20 21:33:59 SD2: Loading Custom Texts...
> 2020-10-20 21:33:59 Loading texts from custom_texts, with additional data
> 2020-10-20 21:33:59 
> 2020-10-20 21:33:59 >> Loaded 0 string templates. DB table `custom_texts` is empty.
> 2020-10-20 21:33:59 SD2: Loading Gossip Texts...
> 2020-10-20 21:33:59 Loading texts from gossip_texts
> 2020-10-20 21:33:59 >> Loaded 146 string templates from gossip_texts
> 2020-10-20 21:33:59 
> 2020-10-20 21:33:59 SD2: Loading Script Waypoints for 126 creature(s)...
> 2020-10-20 21:33:59 
> >> Loaded 4447 Script Waypoint nodes.
> 2020-10-20 21:33:59 SD2: Loading C++ scripts
> 2020-10-20 21:33:59 >> Loaded 1246 C++ Scripts.
```
2nd: why most of number are diff?
example: yours `Loaded 4663 text templates from script_texts`
ours `Loaded 4700 text templates from script_texts` ... etc...

What i can sugest... is to update your core and DB to latest version... compile again and recheck...

**Comment by GPinkie** [comment]
Hi thank you for the help. The error was on my part. After realizing that ./instalfulldb.sh was not installing the scriptdev2 sql or any other updates in the core. I remembered i moved the server location and forgot to update the config file for its new location.

I fixed it, reinstalled db, and the escort quests are now working again.
You can close this bugreport.
