### ISSUE TITLE
🐛 [Bug Report] - Wrong boss move (Moroes) - [karazhan]

### ISSUE THREAD

**Issue by diluh** [cmangos/issues#2299]
## 🐛 Bugreport

The movement of the moroes boss in Karazhan is not correct, after recent updates I think have broken his movement, I will leave a video showing the bug.

https://streamable.com/5juv1i

### Version & Environment

Client Version:   - "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 

https://github.com/cmangos/mangos-tbc/tree/a5ecd9b26e716fc048dd5a107f7cbf6e06b8f009

Database Repo & Commit Hash: 

https://github.com/cmangos/tbc-db/tree/ceade452c9951104c6cbe99aa49272c817e74087

Operating System:   - Linux Debian 9

### Steps to reproduce
1. .tele karazhan
2. go straight to the Moroes chief in Karazhan
3. Start the battle and see the wrong move.

**Comment by diluh** [comment]
@killerwife

**Comment by auroralima** [comment]
Any news about the bug?

**Comment by jimmybrancaccio** [comment]
@auroralima When there's any news or updates to this issue they will be posted here.

**Comment by diluh** [comment]
Fix https://github.com/cmangos/mangos-tbc/commit/08c3dad4e71f1053414018317908f0901a35651c

@killerwife  Close
