### ISSUE TITLE
Fear Movement Buggy

### ISSUE THREAD

**Issue by whitegear** [cmangos/issues#230]
Mangos Zero :  REVISION_NR "2066"

Fear movement and the fleeing target frequently becomes out of sync with the client...  
- NPC's that are slain while generating fleeing movement will (more often than not) generate a corpse that slides across the world.  Also, the npc will continue to move towards the player and even through the player until it quickly snaps back after roughly 1.5 seconds (to its correct location).  Before snapping back, the mob is not in the correct location (and is nearly impossible to target with spells requiring facing) though it is moving the whole time in a straight line.
- Players that are feared (duels / pvp) will appear to keep running to the horrizon when the duration runs out, however their actual location has not changed.  When the feared player moves and thus updates the models true location, the client will display their actual location (making the player appear out of thin air).  This happens variably when the feared player target is stationary or moving (but more so when stationary)

**Comment by cala** [comment]
A small update on this: I did not had the issue described above since the movement/vmaps/mmaps changes done by @cyberium last summer.

Unless someone confirm the issue still exist, I will close it soon(tm).

**Comment by al3xc1985** [comment]
This should be added to wotlk too
