### ISSUE TITLE
🐛 [Bug Report] Nightbane Boss - doesn't work - [Karazhan]

### ISSUE THREAD

**Issue by diluh** [cmangos/issues#2300]
## 🐛 Bugreport

**Boss - Nightbane [karazhan]** does not start, when we use the item [**Blackened Urn] itemiD = 24140** to start the event the boss is standing on the mountain and nothing happens making it impossible to kill the Boss.

Video showing bug - https://streamable.com/odpaz1

### Version & Environment

Client Version:    - "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 

https://github.com/cmangos/mangos-tbc/tree/a5ecd9b26e716fc048dd5a107f7cbf6e06b8f009

Database Repo & Commit Hash: 

https://github.com/cmangos/tbc-db/tree/ceade452c9951104c6cbe99aa49272c817e74087

Operating System:   - Linux Debian 9

### Steps to reproduce
1. .tele karazhan
2. Get to Boss Nightbane.
3. use itemID = 24140 to call the boss.

**Comment by diluh** [comment]
@killerwife

**Comment by diluh** [comment]
Do you have any plans to correct this Boss?

**Comment by jimmybrancaccio** [comment]
@diluh There are probably plans to correct this behavior as the issue is not closed. This issue should first be replicated by someone else so we can mark it as replicated and needs development. Thank you.

**Comment by diluh** [comment]
after the updates is working!  you can close @killerwife
