### ISSUE TITLE
🐛 [Bug Report] Rogue/Druid stealth ability becomes "locked" if used when Faerie Fired

### ISSUE THREAD

**Issue by canidae** [cmangos/issues#2305]
## 🐛 Bugreport
If a Rogue or Druid attempt to stealth when affected by Faerie Fire (from NPC Winter Pathfinder in west Winterspring), the ability gets "locked" (even after Faerie Fire debuff is gone) and player needs to relog to be able to use stealth again.

### Expected behavior
Stealth ability should not be permanently locked when used while having debuff Faerie Fire.

### Version & Environment
  - "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/mangos-classic/tree/af9b841aaabd0d6639fe8ae793f12a21c211a8eb)

Database Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/classic-db/tree/cb3029d7c0ccfe78ac8338c716288168c676bf33)

Operating System: 
- Ubuntu Linux (focal)

### Steps to reproduce
1. As a Rogue/Druid, find a Winterfall Pathfinder NPC in west Winterspring, engage NPC.
2. Attempt to stealth while having debuff Faerie Fire (fails).
3. Attempt to stealth again once debuff is gone (fails).
4. Profit

### Crashlog
- None

**Comment by Yatzii93** [comment]
Seems to be an issue with the TBC core too. I can't replicate it personally so maybe it's a latency/lag issue. 
Heres a clip where a players ghost wolf locks up after casting. My core is up to date, it has the recent "shadowform lockup" fix.
https://www.twitch.tv/videos/791888693?t=00h07m42s

**Comment by ClassicW** [comment]
Exactly the same problem with druid's Faerie Fire

**Comment by darklordsqk** [comment]
Old issue anyway.

**Comment by darklordsqk** [comment]
> Old issue anyway.
Duplicate of #1880

**Comment by canidae** [comment]
Closing. Duplicate as mentioned by @darklordsqk: https://github.com/cmangos/issues/issues/1880
