### ISSUE TITLE
🐛 [Bug Report] Improved Wing Clip Doesn't Work

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2307]
## 🐛 Bugreport         

The spell Improved Wing Clip doesn't work correctly,     
miss proc spell Improved Wing Clip ID=19229    
          
### Expected behavior                      

He must have a chance to proc the spell  Improved Wing Clip                      

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash: cb3029d7c0ccfe78ac8338c716288168c676bf33          

### Steps to reproduce                      

1. create hero Hunter level 60           
2. up Improved Wing Clip in survival talent   
3. go near enemy and use Improved Wing Clip               

### Crashlog     

- None

**Comment by nate123456** [comment]
I wing clipped an enemy 20 times with the Improved Wing Clip talent taken and no immobilization occurred. I can confirm that the talent does not have the intended effect. The `Needs Replication` tag can be removed.

**Comment by killerwife** [comment]
Again, check tbc please. Will make it easier to find out where the issue is, i feel like there might be a common problem when I ported some code down to vanilla.
