### ISSUE TITLE
🐛 [Bug Report] Entrapment Doesn't Work

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2308]
## 🐛 Bugreport         

The spell Entrapment doesn't work correctly, miss proc spell Entrapment ID= 19185          
          
### Expected behavior                      

the traps must have a chance to proc the spell Entrapment                 

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash: cb3029d7c0ccfe78ac8338c716288168c676bf33          

### Steps to reproduce                      

1. create hero Hunter level 60            
2. up Entrapment in survival talent        
3. go near enemy and use Immolation Trap                   

### Crashlog     

- None

**Comment by nate123456** [comment]
I took the Entrapment talent, then had mobs run over an Immolation Trap, Frost Trap, and Explosive Trap 15 times each (those are the traps that are supposed to have the proc chance as per the tooltip). There was no proc on any attempt.

Should be clear to remove the `Needs Replication` tag.

**Comment by killerwife** [comment]
Check if it works on tbc, since the spells are identical, and if it does, let me know.
