### ISSUE TITLE
🐛 [Bug Report] Illumination Works Only With Holy Shock

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2309]
## 🐛 Bugreport        

The spell illumination doesn't work correctly, work only with Holy Shock but doesn't work with holy light and flash light   

![holy](https://user-images.githubusercontent.com/71378304/98580733-c343d580-22c0-11eb-8f10-a5772b27e6d1.jpg)       
                  
### Expected behavior                      

It should work every time a spell like Holy Shock, holy light and flash light  hits a critical                              

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash: cb3029d7c0ccfe78ac8338c716288168c676bf33          

### Steps to reproduce                      

1. create hero paladin level 60            
2. up illumination, divine favor and holy shock in holy talent
3. use divine favor for 100% critic
4. use holy shock, holy light and flash light                         

### Crashlog     

- None

**Comment by killerwife** [comment]
table spell_affect needs better mask for 20210, that includes all 3 spells

**Comment by nate123456** [comment]
Does this issue need to be replicated? It looks like the issue has been identified. If not, could the `Needs Replication` tag be removed?

**Comment by killerwife** [comment]
Please compare tbc and vanilla, if they both dont work etc. The spells are identical and maybe thats where the issue stems from. I would like to help but I need some pointers.
