### ISSUE TITLE
🐛 [Bug Report] Preparation Doesn't Reset the Cooldowns of all Spells

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2310]
## 🐛 Bugreport        

The spell Preparation reset only vanish, Evasion and sprint       

                  
### Expected behavior                      

He must reset all rogue spells in vanilla version like Premeditation, blade flurry, adrenaline rush, Blind, ghostly strike, gouge, cold blood, kidney shot, distact and kick       

![prep](https://user-images.githubusercontent.com/71378304/98594087-6eaa5580-22d4-11eb-8e25-30842244ee48.jpg)        
![prep](https://user-images.githubusercontent.com/71378304/98594261-b335f100-22d4-11eb-90d7-00a9a6b06835.jpg)   
                 

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash: cb3029d7c0ccfe78ac8338c716288168c676bf33          

### Steps to reproduce                      

1. create hero rogue level 60              
2. up premeditation in subtley talent      
3. use Premeditation, blade flurry, adrenaline rush, Blind, ghostly strike, gouge, cold blood, kidney shot, distact, kick, vanish, Evasion and sprint       
4. use premeditation                                

### Crashlog     

- None

**Comment by AnonXS** [comment]
Evasion, Sprint, Vanish, Cold Blood, Shadowstep and Premeditation

**Comment by kepo123** [comment]
Confirmed on TBC 2.4.3!

Rev: https://github.com/cmangos/mangos-tbc/commit/140b42662e87d8217e09ddd25c95e76e3db21aa2
DB: https://github.com/cmangos/tbc-db/commit/b7be096f3331b1a68d0a6b401a363213b75cc45e

This one was reported by a player:
![image](https://user-images.githubusercontent.com/17118210/118308002-19a20300-b4f4-11eb-9f39-b9496d35f548.png)

**Comment by killerwife** [comment]
I just tested a clean TBC core and it worked perfectly fine. Are you sure your spell_scripts table is filled properly from core?

**Comment by kepo123** [comment]
> I just tested a clean TBC core and it worked perfectly fine. Are you sure your spell_scripts table is filled properly from core?

Now it doesn't work only for Vanish.

**Comment by killerwife** [comment]
I hate to say this, but it works for vanish on my end as well, I did my due diligence and just now I tested specifically vanish, are you sure you are not using a creature-based vanish spell or smth?
struct spell_preparation -> 0x0000026000000860 contains 0x800 mask for vanish right here.

**Comment by nate123456** [comment]
Could this issue's tags be updated to be `Version TBC` and `Can't Replicate`?

**Comment by killerwife** [comment]
Adrenaline rush is ignored because its not a valid combination in tbc. So yes, Cant replicate.
