### ISSUE TITLE
💬 [Support Request] warning compilation under linux with ABNodeType and ABNodeStatus

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2312]
## 💬 Support Request              
src/game/BattleGround/BattleGroundAB.cpp: In member function 'virtual void BattleGroundAB::HandlePlayerClickedOnFlag(Player, GameObject)':
src/game/BattleGround/BattleGroundAB.cpp:291:31: warning: comparison between 'enum ABNodeStatus' and 'enum ABNodeType' [-Wenum-compare]
     if (m_nodeStatus[node] == BG_AB_NODE_TYPE_NEUTRAL)
                               ^~~~~~~
src/game/BattleGround/BattleGroundAB.cpp:309:38: warning: comparison between 'enum ABNodeStatus' and 'enum ABNodeType' [-Wenum-compare]
         if (m_prevNodeStatus[node] < BG_AB_NODE_TYPE_OCCUPIED)     

### Version & Environment   

gcc version 8.3.0 (Debian 8.3.0-6)

**Comment by killerwife** [comment]
Fixed in latest commit.
