### ISSUE TITLE
🐛 [Bug Report] realmd.sql error?

### ISSUE THREAD

**Issue by bibibi-bug** [cmangos/issues#2315]
ERROR 1136 (21S01) at line 72: Column count doesn't match value count at row 1

create table account 17 column,insert into account 16 column
Is it wrong?

**Comment by Patrick-Barry** [comment]
I'm getting the same error when creating the realmd database for classic (mangos commit 94b88b4abeddad88136711cc6f3f692a257e48a7)

**Comment by darklordsqk** [comment]
Confirmed: 
The column `locale` varchar(4) NOT NULL DEFAULT '' 
 was not initialized on the INSERT
