### ISSUE TITLE
💬 [Support Request]

### ISSUE THREAD

**Issue by txpeaceofficer09** [cmangos/issues#2316]
## 💬 Support Request

I did a git clone of the wotlk server repo, but the latest database has a different version number my server says it requires 14023, but the latest database is 14026. I think I have something out of date and I have lots of in-game issues and errors.  I tried doing another clone, but everything that I clone now fails to compile.  The server version I pulled was only like a week or two ago.  It crashes a lot and I have lots of errors with stuff like NPCs that should escort and says their way points are invalid.

### Version & Environment

Client Version: 3.3.5a

CMaNGOS Repo & Commit Hash:  
I deleted the installer once I built it successfully.

Database Repo & Commit Hash: b8593aef437a59a9191f85e4bebe2b7aa89fc039

Operating System: Ubuntu 18.04

### Steps to reproduce
1. build from source
2. run mangosd binary
3. tail Server.log
4. ...
5. Profit

**Comment by Grz3s** [comment]
looks like your core is out of date... 
Source: https://github.com/cmangos/mangos-wotlk/tree/master/sql/updates/mangos

You probably didnt follow instalation tutorial... 
- make sure you have latest core cloned and compiled.. 
- then use `./installFullDB.sh` for FULL DB instalation process.. 
**This part must be also set: in `InstallFullDB.config`   -> 
`Define the path to your core's folder
Core updates located under sql/updates from this mangos-directory will be added automatically`

and then everything should go without any issue....
GL

**Comment by txpeaceofficer09** [comment]
I followed the cmangos guide.

git clone git://github.com/cmangos/mangos-wotlk.git mangos

Then created build folder and did cmake, make, make install.

The one I have successfully built, but the core is out of date. If I run
those steps now on the same server, the cmake succeeds, but make fails.


*James McCaughey*
Senior Network Analyst

jmccaughey@lamar.edu
Phone: 409.880.7997
www.lamar.edu





On Nov 16, 2020 at 5:14 PM, Grz3s <notifications@github.com> wrote:

looks like your core is out of date...
Source:
https://github.com/cmangos/mangos-wotlk/tree/master/sql/updates/mangos

You probably didnt follow instalation tutorial...

   - make sure you have latest core cloned and compiled..
   - then use ./installFullDB.sh for FULL DB instalation process..
   **This part must be also set: in InstallFullDB.config ->
   Define the path to your core's folder Core updates located under
   sql/updates from this mangos-directory will be added automatically

and then everything should go without any issue....
GL

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cmangos/issues/issues/2316#issuecomment-728386592>, or
unsubscribe

**Comment by txpeaceofficer09** [comment]
I did:

sudo -i mangos
git clone git://github.com/cmangos/mangos-wotlk.git
cd mangos-wotlk
cmake ../ -DCMAKE_INSTALL_PREFIX=/opt/mangos/wotlk/bin -DCONF_DIR=/opt/mangos/wotlk/etc
make && make install

and got:

[ 11%] Linking CXX static library libshared.a
[ 11%] Built target shared
Scanning dependencies of target game
[ 11%] Building CXX object src/game/CMakeFiles/game.dir/AI/BaseAI/CreatureAI.cpp.o
In file included from /home/mangos/mangos-wotlk/src/game/AI/BaseAI/CreatureAI.h:22:0,
                 from /home/mangos/mangos-wotlk/src/game/AI/BaseAI/CreatureAI.cpp:19:
/home/mangos/mangos-wotlk/src/game/AI/BaseAI/UnitAI.h:462:39: error: ‘std::function’ has not been declared
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                       ^~~~~~~~
/home/mangos/mangos-wotlk/src/game/AI/BaseAI/UnitAI.h:462:47: error: expected ‘,’ or ‘...’ before ‘<’ token
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                               ^
src/game/CMakeFiles/game.dir/build.make:62: recipe for target 'src/game/CMakeFiles/game.dir/AI/BaseAI/CreatureAI.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/AI/BaseAI/CreatureAI.cpp.o] Error 1
CMakeFiles/Makefile2:506: recipe for target 'src/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by evil-at-wow** [comment]
We got the same issue in the TBC core, see #2304. I've fixed it there in cmangos/mangos-tbc@c4cf8d1191 but the most recent block of commits in the TBC core hasn't been ported to WotLK yet. I think Killerwife is doing that these days.

**Comment by txpeaceofficer09** [comment]
Thanks, @evil-at-wow, that did the trick.  I went and put in the includes you added and everything compiled fine.  Now things are working a lot better.  The only bad thing is that I had to update the character database structure which screwed with all the inventory.
