### ISSUE TITLE
🐛 [Bug Report] Compilation error: 'error: ‘LocaleConstant’ does not name a type', ‘LocaleConstant’ has not been declared'

### ISSUE THREAD

**Issue by Szymplo** [cmangos/issues#2318]
## 🐛 Bugreport
Can't compile cmangos tbc server

### Expected behavior
Compile without errors

### Version & Environment

Client Version: 
  - "2.4.3" (TBC)

Commit Hash:
https://github.com/cmangos/mangos-tbc/tree/279fe2fe09a522338b15098f91dbaa285eb90cf5

Database Version - is required
https://github.com/cmangos/tbc-db/tree/47072f1900724edee2705d345cfd96f85aeeebcd

Operating System:
Linux Debian10 with MariaDB

### Steps to reproduce

git clone mangos-tbc and tbc-db
mkdir build cd build
cmake .. -DCMAKE_INSTALL_PREFIX=../run -DBUILD_EXTRACTORS=ON -DPCH=1 -DDEBUG=1 -DBUILD-PLAYERBOT=OFF -DBUILD-AHBOT=OFF
make

### Crashlog
[compile_error.log](https://github.com/cmangos/issues/files/5556354/compile_error.log)

**Comment by evil-at-wow** [comment]
This should be fixed with cmangos/mangos-tbc@ad119f1b9b.
