### ISSUE TITLE
🐛Rather Solution Ask: Problem with importing characters after database changed...

### ISSUE THREAD

**Issue by Szymplo** [cmangos/issues#2319]
## 🐛 Bugreport
I have a serious problem with importing characters to new version of server after database changed.
I know it's not strict bug report, rather question about any tool or fast way to do that...

### Expected behavior
Importing tbccharacters and tbcrealmd without manually reconstructing tables which this time i found to hard to do myself

### Version & Environment

 "2.4.3" (TBC)
  
  Commit Hashes old server version
  https://github.com/cmangos/mangos-tbc/tree/0b177955099622b57157e9f80844414ef44e6a22
  https://github.com/cmangos/tbc-db/tree/b29f5229b6d378271bf83562092e0ecb2c552ff9

  Commit Hashes of new server version
  https://github.com/cmangos/mangos-tbc/tree/059c8618b70e0b3d4e1626e855526da853d7c4e7
  https://github.com/cmangos/tbc-db/tree/422522c5ee0e3bde494267cf3e7ee51bf23d509a

### Additional info

   I'll attach my characters and realmd dump. If you find it hard to do please give me a small advice how to do it fastest way.
   I'll even accept methods like generating all the items for players again but i just want to know the most efficient way
   to help my few, but devoted players. So workaround will also be greatly appreciated.

   BTW u guys doin fine job with that project..
[characters_realmd_dump.tar.gz](https://github.com/cmangos/issues/files/5566328/characters_realmd_dump.tar.gz)

Best regards Szymplo

**Comment by evil-at-wow** [comment]
I'm not entirely sure if this is about importing individual characters or an entire character database (as you typically would when restoring say a backup), but I'm going to assume it's the full database here. 

And in that case I've answered a similar question earlier this year, so I'm going to point you to my response in cmangos/issues#2091 for more details to understand how this works.

The short summary for the characters database however is this:
* Import the old database (a backup, from a different server, whatever) as it is.
* Check the columns of the table character_db_version after the import. This table contains a field that's named after the current revision (for example "required_s2395_01_characters_WorldState").
* Apply core updates from sql/updates/characters to the characters database, **in order**, starting with the update **after** what you found in step 2, and **up to and including** the one the core expects. This last one is typically the last update you find in sql/updates/characters in your source tree (unless your source tree contains different commits or edits that are not in the built server yet).

**Comment by Szymplo** [comment]
OK it seems i tried to do it a bit "backwards" I deployed new version of server then imported tbcrealmd and tbcmangosd databases, and then manually tried fix database differences between tables i imported and pure ones from new version . I was "almost there" but stuck with huge problem with character-items connected to new thing called "item_instance". 
Thanks, I'll check your solution.

Best Regards
Szymplo

**Comment by Szymplo** [comment]
Did it right way and it works fine.

Thank you evil-at-wow.
