### ISSUE TITLE
🐛 [Bug Report] Compile Error @ 04fe9f8

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2322]
## 🐛 Bugreport
Compile Error

### Build 
-- CMaNGOS-Core revision : 04fe9f8c741995da3c24904cd3d44dfa1855285e
-- Revision time stamp   : "2020-11-21T14:26:18+01:00"

### Expected behavior
`[ 19%] Linking CXX executable realmd
In file included from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/PetAI.h:22:0,
                 from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/PetAI.cpp:19:
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:39: error: ‘std::function’ has not been declared
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                       ^~~~~~~~
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:47: error: expected ‘,’ or ‘...’ before ‘<’ token
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                               ^
In file included from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/CreatureAI.h:22:0,
                 from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/CritterAI.h:22,
                 from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/CritterAI.cpp:19:
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:39: error: ‘std::function’ has not been declared
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                       ^~~~~~~~
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:47: error: expected ‘,’ or ‘...’ before ‘<’ token
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                               ^
[ 20%] Building CXX object src/game/CMakeFiles/game.dir/AI/CreatureAIRegistry.cpp.o
In file included from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/CreatureAI.h:22:0,
                 from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/CreatureAI.cpp:19:
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:39: error: ‘std::function’ has not been declared
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                       ^~~~~~~~
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:47: error: expected ‘,’ or ‘...’ before ‘<’ token
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                               ^
In file included from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/CreatureAI.h:22:0,
                 from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/GuardAI.h:22,
                 from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/GuardAI.cpp:19:
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:39: error: ‘std::function’ has not been declared
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                       ^~~~~~~~
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:47: error: expected ‘,’ or ‘...’ before ‘<’ token
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                               ^
In file included from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/CreatureAI.h:22:0,
                 from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/NullCreatureAI.h:22,
                 from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/NullCreatureAI.cpp:19:
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:39: error: ‘std::function’ has not been declared
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                       ^~~~~~~~
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:47: error: expected ‘,’ or ‘...’ before ‘<’ token
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                               ^
In file included from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp:19:0:
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:39: error: ‘std::function’ has not been declared
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                       ^~~~~~~~
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:47: error: expected ‘,’ or ‘...’ before ‘<’ token
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                               ^
In file included from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/PetAI.h:22:0,
                 from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/GuardianAI.h:22,
                 from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/GuardianAI.cpp:19:
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:39: error: ‘std::function’ has not been declared
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                       ^~~~~~~~
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:47: error: expected ‘,’ or ‘...’ before ‘<’ token
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                               ^
In file included from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/CreatureAI.h:22:0,
                 from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/TotemAI.h:22,
                 from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/TotemAI.cpp:19:
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:39: error: ‘std::function’ has not been declared
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                       ^~~~~~~~
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:47: error: expected ‘,’ or ‘...’ before ‘<’ token
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                               ^
[ 20%] Built target realmd
[ 20%] Building CXX object src/game/CMakeFiles/game.dir/AI/CreatureAISelector.cpp.o
In file included from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/CreatureAI.h:22:0,
                 from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/NullCreatureAI.h:22,
                 from /home/mangos/cmangos/wotlk/src/game/AI/CreatureAIRegistry.cpp:19:
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:39: error: ‘std::function’ has not been declared
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                       ^~~~~~~~
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:47: error: expected ‘,’ or ‘...’ before ‘<’ token
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                               ^
[ 20%] Building CXX object src/game/CMakeFiles/game.dir/AI/EventAI/CreatureEventAI.cpp.o
src/game/CMakeFiles/game.dir/build.make:182: recipe for target 'src/game/CMakeFiles/game.dir/AI/BaseAI/NullCreatureAI.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/AI/BaseAI/NullCreatureAI.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/game/CMakeFiles/game.dir/build.make:86: recipe for target 'src/game/CMakeFiles/game.dir/AI/BaseAI/CritterAI.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/AI/BaseAI/CritterAI.cpp.o] Error 1
[ 20%] Linking CXX static library libmmaplib.a
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp:682:6: error: prototype for ‘void UnitAI::AttackSpecificEnemy(std::function<void(Unit*, Unit*&)>)’ does not match any in class ‘UnitAI’
 void UnitAI::AttackSpecificEnemy(std::function<void(Unit*, Unit*&)> check)
      ^~~~~~
In file included from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp:19:0:
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:14: error: candidate is: void UnitAI::AttackSpecificEnemy(int)
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
              ^~~~~~~~~~~~~~~~~~~
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp: In member function ‘virtual void UnitAI::AttackClosestEnemy()’:
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp:707:6: error: no matching function for call to ‘UnitAI::AttackSpecificEnemy(UnitAI::AttackClosestEnemy()::<lambda(Unit*, Unit*&)>)’
     });
      ^
In file included from /home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.cpp:19:0:
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:14: note: candidate: void UnitAI::AttackSpecificEnemy(int)
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
              ^~~~~~~~~~~~~~~~~~~
/home/mangos/cmangos/wotlk/src/game/AI/BaseAI/UnitAI.h:462:14: note:   no known conversion for argument 1 from ‘UnitAI::AttackClosestEnemy()::<lambda(Unit*, Unit*&)>’ to ‘int’
[ 20%] Built target mmaplib
Scanning dependencies of target MoveMapGen
[ 20%] Building CXX object contrib/mmap/CMakeFiles/MoveMapGen.dir/src/generator.cpp.o
src/game/CMakeFiles/game.dir/build.make:134: recipe for target 'src/game/CMakeFiles/game.dir/AI/BaseAI/GuardAI.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/AI/BaseAI/GuardAI.cpp.o] Error 1
src/game/CMakeFiles/game.dir/build.make:278: recipe for target 'src/game/CMakeFiles/game.dir/AI/CreatureAIRegistry.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/AI/CreatureAIRegistry.cpp.o] Error 1
src/game/CMakeFiles/game.dir/build.make:62: recipe for target 'src/game/CMakeFiles/game.dir/AI/BaseAI/CreatureAI.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/AI/BaseAI/CreatureAI.cpp.o] Error 1
src/game/CMakeFiles/game.dir/build.make:206: recipe for target 'src/game/CMakeFiles/game.dir/AI/BaseAI/PetAI.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/AI/BaseAI/PetAI.cpp.o] Error 1
src/game/CMakeFiles/game.dir/build.make:230: recipe for target 'src/game/CMakeFiles/game.dir/AI/BaseAI/TotemAI.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/AI/BaseAI/TotemAI.cpp.o] Error 1
src/game/CMakeFiles/game.dir/build.make:158: recipe for target 'src/game/CMakeFiles/game.dir/AI/BaseAI/GuardianAI.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/AI/BaseAI/GuardianAI.cpp.o] Error 1
src/game/CMakeFiles/game.dir/build.make:254: recipe for target 'src/game/CMakeFiles/game.dir/AI/BaseAI/UnitAI.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/AI/BaseAI/UnitAI.cpp.o] Error 1
[ 20%] Linking CXX executable MoveMapGen
[ 20%] Built target MoveMapGen
CMakeFiles/Makefile2:800: recipe for target 'src/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by evil-at-wow** [comment]
We got the same issue in the TBC core, see #2304. I've fixed it there in cmangos/mangos-tbc@c4cf8d1 but it looks like killerwife skipped my commits when porting the most recent block of commits in the TBC core to WotLK...

**Comment by adellaci** [comment]
Thank you @evil-at-wow

**Comment by killerwife** [comment]
F***

Will push it immediately. Recently I noticed I also forgot one of my commits......

**Comment by adellaci** [comment]
Thank you @killerwife 

I'll keep checking and test it right away

**Comment by adellaci** [comment]
@killerwife 

-- CMaNGOS-Core revision : b1ad3bb4e616537a167b9abd191a3a55499d7b50
-- Revision time stamp   : "2020-10-25T19:22:06+01:00"

I did another pull and it compile with two warming. Are these a problem

`[ 77%] Building CXX object src/game/CMakeFiles/game.dir/BattleGround/BattleGroundMgr.cpp.o
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGround.cpp: In member function ‘virtual void BattleGround::RemovePlayerAtLeave(ObjectGuid, bool, bool)’:
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGround.cpp:1305:49: warning: enumeral mismatch in conditional expression: ‘ArenaSpells’ vs ‘BattleGroundSpells’ [-Wenum-compare]
         player->RemoveAurasDueToSpell(IsArena() ? SPELL_ARENA_DAMPENING : SPELL_BATTLEGROUND_DAMPENING);
                                       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 78%] Building CXX object src/game/CMakeFiles/game.dir/BattleGround/BattleGroundNA.cpp.o
`
`[100%] Building CXX object src/mangosd/CMakeFiles/mangosd.dir/WorldRunnable.cpp.o
/home/mangos/cmangos/wotlk/src/mangosd/CliRunnable.cpp: In member function ‘bool ChatHandler::GetDeletedCharacterInfoList(ChatHandler::DeletedInfoList&, std::__cxx11::string)’:
/home/mangos/cmangos/wotlk/src/mangosd/CliRunnable.cpp:138:94: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘uint64 {aka long unsigned int}’ [-Wformat=]
             PSendSysMessage("Too many results %u. Narrow it down.", resultChar->GetRowCount());
                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~^
[100%] Linking CXX executable mangosd
`

**Comment by jimmybrancaccio** [comment]
As you noted these are just warnings. I'm going to close this GitHub issue out for now, but please don't hesitate to open a new issue if you'd like these warnings to be looked into. I'd like to keep each unique issue/question/problem in their own unique GitHub issues please.

**Comment by adellaci** [comment]
That good thank youSent from my smartphone
-------- Original message --------From: "Jimmy B." <notifications@github.com> Date: 11/22/20  1:21 PM  (GMT-05:00) To: cmangos/issues <issues@noreply.github.com> Cc: Anthony <adellaci@sacoriver.net>, Author <author@noreply.github.com> Subject: Re: [cmangos/issues] 🐛 [Bug Report] Compile Error @ 04fe9f8 (#2322) 
As you noted these are just warnings. I'm going to close this GitHub issue out for now, but please don't hesitate to open a new issue if you'd like these warnings to be looked into. I'd like to keep each unique issue/question/problem in their own unique GitHub issues please.
