### ISSUE TITLE
💬 [Support Request] Open world leash mechanics

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#2323]
## 💬 Support Request
I am trying to better understand the open world leashing system.  Currently I 'testing' with tbc, however, I believe it is applicable to all cores.

I found this comment in CombatManager.cpp

> /*
>     Creature Evade Timer & Leash range
> 
>     1) Leash timer 15 sec if creature can reach you
>     - Timer will be reset upon if player deals damage or if creature does damage to player
>     - Only direct damage will reset damage
> 
>     2) There is no timer for creature that cannot reach you
>     - Creature appears to be evading while it cannot reach you so player cannot deal any damage
>     - After 90yd it will drop combat because player is too far.
> 
>     3) Special creatures have leash range and timer
>     - No way to find out range as of now on WoD
> */

Focusing on the comment;
>     - Leash timer 15 sec if creature can reach you
>     - Timer will be reset upon if player deals damage or if creature does damage to player
>     - Only direct damage will reset damage

During testing I can try round up a number of mobs, I am close enough to pull multiple mobs and engage combat with them that I am not moving a distance far enough that it deviates from their normal pat. range. ie. where I am standing by point of combat, it would have been in aggro range of the mobs regardless.  What I am stressing here is that I am not pulling them any distance from a location that aggro of these multiple mobs would have been possible just using distance to them. 
 
Now I will focus on 1 mob to burn its health down, perhaps putting dots (if available) on the other two. Now after about 15 seconds give or take the other two mobs (which may or may not have had a dot on them initially), they will leash back although they were still in combat and melee hitting me.  This seems to contradicts this part of the comment -> Timer will be reset upon if player deals damage or **if creature does damage to player**. Yes,  if I am hitting them they will stay but if they are hitting me, two (or more) of the mobs still seem to reset on the 15 sec (give or take) timer  Is there a bug in this logic, or am I misunderstanding?  If it is working as intended, which is not blizz like IMHO, is it due to limitations in the current impl. and if so what are the challenges making it behave as above and not closer to blizz like leashing in the open world.

  You should be able to reproduce this with most open world mobs, particularly where multiple mobs are close togeather.

  This is not a criticism etc. or even a bug report, I am just trying to better understand how it should work etc.
Cheers,

### Version & Environment
N/A

### Steps to reproduce
Reading the description above also describes a way to reproduce.

**Comment by killerwife** [comment]
If creature does damage to the player it does not reset the timer. It resets the timer if it is dealing damage to an NPC, i.e. NPC to NPC combat.

**Comment by lduguid** [comment]
Thank you for the response.  

 Perhaps the comment should be updated from '... or creature does damage to player' to something  like '... or creature does damage to another creature'. 

  On that note, in a scenario where a player enters combat with multiple mobs and is in location close to where both mobs are standing (e.g. body pull both) and then proceeds to melee one of the mob, while both mobs are hitting and inflicting damage from both creatures, i.e. creature one being hit by the user and is being focused on until dead, while creature two is in combat and hitting the player, then after x seconds, is removed from combat and returns to its original pat. position, would you consider that something the current logic should be doing ?  I guess where I am going with this, is it generally considered that the current leashing in the open world is working as intended or it requires more refinement in the future?

Cheers,

**Comment by killerwife** [comment]
I am not sure if my adjustment is exported yet, I am sure you noticed that I exporting high volumes of changes. With the way it stands, after the export it should be as blizzlike as I know how to make it. We even now have going home through terrain after going too far from combat start position.

**Comment by lduguid** [comment]
Sounds good.  I believe I am running a clean latest as of today and it still seems a bit off (as described above) but will keep an eye on future exports and will test this particular scenario on each new update that seems it could be related etc.  

I was going to have a go at making some modifications to it myself but just wanted to get a sense of where it was at and if there are going to be changes to it soon. I will hold off as it sounds like it should be working as intended soon. Cheers.
