### ISSUE TITLE
🐛 [Bug Report] Nightbane from Karazhan is not working.

### ISSUE THREAD

**Issue by nobre027** [cmangos/issues#2326]
Boss - Nightbane from karazhan is not working, when we use the item to summon the boss =>[Blackened Urn] itemiD = 24140 and start the event the boss keep standing on the mountain don't come to fight letting impossible to kill.

Video showing bug - https://streamable.com/odpaz1

Expected behavior - https://www.youtube.com/watch?v=ROunfhm95qE&ab_channel=lajmie exemple of how is to be.

Version & Environment
Client Version: - "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash:

https://github.com/cmangos/mangos-tbc/tree/a5ecd9b26e716fc048dd5a107f7cbf6e06b8f009

Database Repo & Commit Hash:

https://github.com/cmangos/tbc-db/tree/ceade452c9951104c6cbe99aa49272c817e74087

Operating System: - Linux Debian 9

Steps to reproduce
.tele karazhan
Get to Boss Nightbane.
use itemID = 24140 to call the boss.

**Comment by diluh** [comment]
after the updates is working!  you can close
@killerwife
