### ISSUE TITLE
🐛 [Bug Report] [Playerbot] `/t BOTNAME quest report` returns list of completed and incompleted quests

### ISSUE THREAD

**Issue by christiansiewert** [cmangos/issues#2327]
## 🐛 Bugreport

According to [command-docs](https://github.com/cmangos/mangos-classic/blob/master/doc/PlayerBot/commands.txt#L64) `/t BOTNAME quest report` or `/p quest report` should give us a list of 

> all items, creatures or gameobjects needed to finish quests.

Instead, the commands return a list of completed and incompleted quests (Check attached image).

### Expected behavior

- Like described in the docs (all items, creatures or gameobjects needed to finish quests)

### Version & Environment

Client Version: "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: 6b345e0d3dabc57ea2c3d7a151df23174d29a796

Database Repo & Commit Hash: d8df9dc490711f622dd9447f6ba83d58f6048314

Operating System: Linux Flavor

### Steps to reproduce
1. Checkout classic-mangos and classic-db
2. Build with Playerbot enabled
3. Add some bots and do some quests
4. Check output of `/t BOTNAME quest report` or `/p quest report`
5. Profit

### Images ###
![image](https://user-images.githubusercontent.com/33094503/100468449-bc94cb00-30d4-11eb-8d17-1032e9367186.png)

**Comment by cala** [comment]
I think in this case the documentation is wrong. The purpose of said command has clearly been for years to give a completion status report on bots quests.

**Comment by christiansiewert** [comment]
I don't have an overview of the TBC and WOTLK repositories right now, but Classic lacks a corresponding implementation of the `report` subcommand:

https://github.com/cmangos/mangos-classic/blob/master/src/game/PlayerBot/Base/PlayerbotAI.cpp#L7411

This then causes `quest report` to jump to the final else branch, where the list of completed and incompleted quests is generated:

```cpp
...
else
    {
        bool hasIncompleteQuests = false;
        std::ostringstream incomout;
        incomout << "my incomplete quests are:";
...
```

If this is really the desired behaviour of `quest report`, we should formulate a feature request, because a corresponding subcommand like the one described in the documentation would be really nice if you're playing with bots.

**Example**

```
/t BOTNAME quest report

BOTNAME: 
    QUEST: I need NUM of GAMEOBJECT to finish. 
```

**Comment by jimmybrancaccio** [comment]
@christiansiewert Would you be able to create a feature request if this is something you'd like to see in a future version of playerbots?

**Comment by christiansiewert** [comment]
> @christiansiewert Would you be able to create a feature request

Sure, but we should create a template for feature requests first. I opened [christiansiewert/mangos-classic/issues/2](https://github.com/christiansiewert/mangos-classic/issues/2) for this.

Feel free to comment.

**Comment by jimmybrancaccio** [comment]
Hi @christiansiewert We do have a future request template (https://github.com/cmangos/issues/issues/new/choose). You'll want to make sure the issue is opened in our issues repository and not your own personal repository as we won't see it there.

Thanks!

**Comment by christiansiewert** [comment]
Thank you, it is here: https://github.com/cmangos/issues/issues/2334

**Comment by jimmybrancaccio** [comment]
Awesome thanks!

**Comment by christiansiewert** [comment]
If we want to handle that as a feature and not as a bug, we can close this. 

Thank you.
