### ISSUE TITLE
🐛[Bug Report] make Command Has Error

### ISSUE THREAD

**Issue by playfcode** [cmangos/issues#2328]
## 🐛 Bugreport
make commend can't be executed successfully when server initialization

### Expected behavior
![image](https://user-images.githubusercontent.com/69490311/100603819-9b381700-3340-11eb-8533-458c643044b1.png)

### Version & Environment

Operating System:

**Comment by jimmybrancaccio** [comment]
@playfcode Please provide _all_ of the requested information from the bug reporting template.

**Comment by cyberium** [comment]
No reproducible and/or not enough data provieded
