### ISSUE TITLE
🐛 [Bug Report] Relog cause lose of mithril bars after using >1 stack of mithril to transmute truesilver.

### ISSUE THREAD

**Issue by Szymplo** [cmangos/issues#2329]
### 🐛 Bugreport
There is a problem with transmute mithril to truesilver. If I use stack of > 1 mithril bars to transmute one of them to truesilver everything looks fine. But after relogging the rest of mithril bars left after transmutation (stack of 19 mithril bars) were gone from inventory, didnt found them also in bank or in post-mail. This stack dissapeared from server. I checked it two times. First I transmuted stack od 20 mithril bars and lost 19 mithril bars after relog. Second time i transmuted stack od 2 mithril bars into truesilver so i received one mithril bar and one truesilver bar. After relog the one mithril bar was gone. 

### Expected behavior

Transmuting > 1 mithril bars to truesilver doesn't make rest of mithril stack dissapear after relog.

### Version & Environment

  - "2.4.3" (TBC)

  Commit Hash:

  - https://github.com/cmangos/mangos-tbc/tree/059c8618b70e0b3d4e1626e855526da853d7c4e7

  Database Version:

   - https://github.com/cmangos/tbc-db/tree/422522c5ee0e3bde494267cf3e7ee51bf23d509a

   Operating System
       Server: Debian 10 Buster
       Client: Windows 7 

### Steps to reproduce
1. Use stack of >1 mithril bars to transmute truesilver
2. Logout and log in again
3. Check inventory and realise that u just lost some precious mithril bars.

**Comment by MantisLord** [comment]
Make sure you're applied the latest char DB updates and see if it still happens.

The core just had another update related to this just yesterday.

https://github.com/cmangos/mangos-tbc/commit/553211071970bc02956ef6fac74c31d2f461b7e9

**Comment by jimmybrancaccio** [comment]
@Szymplo Are you still having this issue?

**Comment by Szymplo** [comment]
Still having a problem after upgrading to:
https://github.com/cmangos/mangos-tbc/tree/8638574cde7341e585a2ada071a7171310fc1abc
https://github.com/cmangos/tbc-db/tree/dcd689a945e18b7dc4e4a3811bde0a400dfddf4d

I made test like that:
Gathered some mithril, then smelted it into mithril bars, gave 2 mithril bars to another char from other account.
Transmuted one Mithril Bar to truesilver and reloged with char which transmuted.
After reloging in inventory I didnt find truesilver bar (dissapeared, it was visible after transmutation before relogging) and same problem with Mithril bar. So after relogging 1 Truesilver bar and 1 Mithril bar vanished.

**Comment by Szymplo** [comment]
Ok. It looks like i had a problem with MariaDB database. Currently after database restart it works fine. I'll try to make some deep search to find a source of problem.
I'm closing this - it looks like that's my problem not yours.
