### ISSUE TITLE
🐛 [Bug Report] Failed to Compile on GossipDef

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2330]
## 🐛 Bugreport
Failed to compile on the following
`[ 82%] Building CXX object src/game/CMakeFiles/game.dir/Entities/ItemEnchantmentMgr.cpp.o
In file included from /home/mangos/cmangos/wotlk/src/game/Entities/GossipDef.h:23:0,
                 from /home/mangos/cmangos/wotlk/src/game/Entities/GossipDef.cpp:19:
/home/mangos/cmangos/wotlk/src/game/Quests/QuestDef.h:280:28: error: ‘Difficulty’ has not been declared
         bool   IsRaidQuest(Difficulty difficulty) const;
                            ^~~~~~~~~~
[ 82%] Building CXX object src/game/CMakeFiles/game.dir/Entities/ItemHandler.cpp.o
[ 82%] Building CXX object src/game/CMakeFiles/game.dir/Entities/MiscHandler.cpp.o
[ 82%] Building CXX object src/game/CMakeFiles/game.dir/Entities/NPCHandler.cpp.o
[ 83%] Building CXX object src/game/CMakeFiles/game.dir/Entities/Object.cpp.o
[ 83%] Building CXX object src/game/CMakeFiles/game.dir/Entities/ObjectGuid.cpp.o
[ 83%] Building CXX object src/game/CMakeFiles/game.dir/Entities/ObjectVisibility.cpp.o
[ 83%] Building CXX object src/game/CMakeFiles/game.dir/Entities/Pet.cpp.o
src/game/CMakeFiles/game.dir/build.make:13310: recipe for target 'src/game/CMakeFiles/game.dir/Entities/GossipDef.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/Entities/GossipDef.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:800: recipe for target 'src/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

### Expected behavior
To complete compiling

### Version & Environment
- "3.3.5a" (WOTLK)

Client Version: 

CMaNGOS Repo & Commit Hash: 

  Operating System - optional
Operating System: Ubuntu 18.04.5 Server LTS

### Steps to reproduce
1.Compile
2.
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by jimmybrancaccio** [comment]
I tempted to close this out for not including all the information as well as I couldn't replicate the issue using `d9e5ba681627a52e66247c7361952614298c0370`. I recommend getting at least this commit and trying again.

**Comment by adellaci** [comment]
i will try the lasted pull tomorrow night. If it compiles i'll close the issue

**Comment by darkpoetry** [comment]
Metoo, Debian 10, latest git as of about an hour before this post.

[ 82%] Building CXX object src/game/CMakeFiles/game.dir/Entities/GossipDef.cpp.o
In file included from /home/mangos/mangos/src/game/Entities/GossipDef.h:23,
                 from /home/mangos/mangos/src/game/Entities/GossipDef.cpp:19:
/home/mangos/mangos/src/game/Quests/QuestDef.h:280:28: error: ‘Difficulty’ has not been declared
         bool   IsRaidQuest(Difficulty difficulty) const;
                            ^~~~~~~~~~

**Comment by jimmybrancaccio** [comment]
I have still been unable to replicate this. As all the information from the template was not included I am closing this out. If you're still experiencing this please create a new issue.

**Comment by christiansiewert** [comment]
@ulfgebhardt Take a look here please: https://github.com/cmangos/issues/issues/2336#issuecomment-740709621
