### ISSUE TITLE
🐛 [Bug Report] The Emerald Dreamcatcher - question mark

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/issues#2333]
## 🐛 Bugreport

Having the quest `The Emerald Dreamcatcher` completed will result in a blue question mark

![image](https://user-images.githubusercontent.com/1238238/101297684-87058580-382a-11eb-9509-9dde6eadec43.png)

This is the case while `Twisted Hatred` is not complted

![image](https://user-images.githubusercontent.com/1238238/101297733-caf88a80-382a-11eb-8631-0bba505e29da.png)

### Expected behavior

Having the quest `The Emerald Dreamcatcher` completed should have a yellow questionmark, since its not a repeatable.

### Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: [TBC](https://github.com/cmangos/mangos-tbc/tree/daf52413)

Database Repo & Commit Hash: [TBC](https://github.com/cmangos/tbc-db/tree/96d6b19b)

Operating System: Linux Debian

**Comment by jimmybrancaccio** [comment]
@ulfgebhardt Please provide _all_ of the information requested by the bug reporting template.

**Comment by ulfgebhardt** [comment]
@jimmybrancaccio 

## Steps
- Ally Character
- `.go creature tallonkai`
-  accept quest from npc (2438)
- `.quest complete 2438`
- see blue questionmark
- ....
- Profit

![image](https://user-images.githubusercontent.com/1238238/101471783-00df6100-3948-11eb-9222-c8a64fa1e130.png)

**Comment by killerwife** [comment]
The quest is repeatable :D Its a weekly quest. Only one in all of vanilla :D :D

**Comment by ulfgebhardt** [comment]
ok I did not know that - thank you @killerwife for taking care
