### ISSUE TITLE
🐛 [Bug Report][WotLK] GossipDef.cpp fails to compile

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2340]
## 🐛 Bugreport
Fails to compile 

### Expected behavior
complete compile without error

### Version & Environment
Ubuntu 18.04 Server LTS  
mysql  Ver 14.14 Distrib 5.7.32, for Linux (x86_64) using  EditLine wrapper
- "3.3.5a" (WOTLK)

-- CMaNGOS-Core revision : 455b25ced8288d39e345a7fb7513b268d535e5e2
-- Revision time stamp   : "2020-12-12T13:56:32+01:00"

`[ 82%] Building CXX object src/game/CMakeFiles/game.dir/Entities/GossipDef.cpp.o
In file included from /home/mangos/cmangos/wotlk/src/game/Entities/GossipDef.h:23:0,
                 from /home/mangos/cmangos/wotlk/src/game/Entities/GossipDef.cpp:19:
/home/mangos/cmangos/wotlk/src/game/Quests/QuestDef.h:280:28: error: ‘Difficulty’ has not been declared
         bool   IsRaidQuest(Difficulty difficulty) const;
                            ^~~~~~~~~~
[ 82%] Building CXX object src/game/CMakeFiles/game.dir/Entities/Item.cpp.o
[ 82%] Building CXX object src/game/CMakeFiles/game.dir/Entities/ItemEnchantmentMgr.cpp.o
[ 82%] Building CXX object src/game/CMakeFiles/game.dir/Entities/ItemHandler.cpp.o
[ 82%] Building CXX object src/game/CMakeFiles/game.dir/Entities/MiscHandler.cpp.o
/home/mangos/cmangos/wotlk/src/game/Entities/GameObject.cpp: In member function ‘virtual bool GameObject::isVisibleForInState(const Player*, const WorldObject*, bool) const’:
/home/mangos/cmangos/wotlk/src/game/Entities/GameObject.cpp:1079:18: warning: zero-length gnu_printf format string [-Wformat-zero-length]
         printf("");
                  ^
[ 82%] Building CXX object src/game/CMakeFiles/game.dir/Entities/NPCHandler.cpp.o
[ 82%] Building CXX object src/game/CMakeFiles/game.dir/Entities/Object.cpp.o
[ 83%] Building CXX object src/game/CMakeFiles/game.dir/Entities/ObjectGuid.cpp.o
[ 83%] Building CXX object src/game/CMakeFiles/game.dir/Entities/ObjectVisibility.cpp.o
[ 83%] Building CXX object src/game/CMakeFiles/game.dir/Entities/Pet.cpp.o
src/game/CMakeFiles/game.dir/build.make:13310: recipe for target 'src/game/CMakeFiles/game.dir/Entities/GossipDef.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/Entities/GossipDef.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:800: recipe for target 'src/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by christiansiewert** [comment]
Is this still up to date? I just recompiled a clean pull of WOTLK and the error seems to be fixed between https://github.com/cmangos/mangos-wotlk/compare/25d2e8c223f8caacfa180e2ac70f581011c260d7..40cc038cc9f9fc7b569d231c38a2ee5165990f75.
