### ISSUE TITLE
🐛 [Bug Report]WoW Classic Mounts Work like retail WOW

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2342]
The mount system in classic, work the reverse of wow current.             
Currently you have to buy the riding apprentice spell=33388 **cost 90po**at level 40 and buy riding companion spell=3339 **cost 900 po**at level 60                        
Then each mount costs **10Po** and **100 Po** for level 40 and 60                        

**Expected behavior**           

Normally this should be reversed, you will have to learn one riding skill per race at **20 po**                    
spell=824/horse-riding        
spell=825/wolf-riding                                       
spell=826/ram-riding           
spell=828/tiger-riding              
spell=10861/raptor-riding            
spell=10906/undead-horsemanship               
spell=10907/mechanostrider-piloting                  
spell=18995/kodo-riding                          

And then you have to buy the mount at full price,                         
Rare | +60% | 40 | 80 PO                              
Épique | +100% | 60 | 1 000 PO        

As explained previously, in WoW Classic the mounts are extremely expensive and the skill costs only a handful of gold coins, unlike Battle for Azeroth where it is rather the opposite (at the level of racial mounts at least) .                  

Link wowhead for help     
https://fr.classic.wowhead.com/guides/mounts-classic-wow

**Version & Environment**                    

Client Version: "1.12.1" (CLASSIC)                    

CMaNGOS Repo & Commit Hash: 22085416a5d5fa3e1b178487b86c4595c399d42                       

**Steps to reproduce**                     
            
1. create hero human level 60             
2. go to .go xyz -9447.55 -1383.3 47.13            
3. check PNJ mount              

**Crashlog**      

None

**Comment by Tobschinski** [comment]
I think this was changed with the last patch made for vanilla wow, [patch 1.12.1](https://wowwiki.fandom.com/wiki/Patch_1.12.1)

**Comment by killerwife** [comment]
Tobi is correct. It was changed in the last patches of vanilla.
