### ISSUE TITLE
transport problem: no zepplin from ogri to undersity. Please help!

### ISSUE THREAD

**Issue by VitekUgarov** [cmangos/issues#2346]
**Current behavior**: 
 no zepplin from ogri to undersity. Please help!
![изображение](https://user-images.githubusercontent.com/58750201/102577400-0c314a00-4109-11eb-8b48-9d2eabe7c934.png)
**Expected behavior**: 
worked zepplin from ogri to undersity. Please help!
**Steps to reproduce**:

1. go to the zeppelin station near Ogrimmar or Undersity
2. wait
3. no zeppelin here

**Client version**: 
3.3.5.a
**Commit hash**: 
Using commit hash(d6fc0734a471a23ab86754245204936c738563d0) committed on 2020-12-17T20:26:02+01:00

**Database version**: 
Using World DB: WoTLKDB v1.4+ 'WrathGate' for CMaNGOS-WOTLK 14029
**Operating system**: 
Win 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Muehe** [comment]
@VitekUgarov There have been a few transport related commits to the DB and core after you made this issue, please retest after updating.

**Comment by VitekUgarov** [comment]
i updated to commit hash(9ca7b1ca1172d1cd19fd195b97d45f54906101db) committed on 2020-12-18T11:54:02+01:00

and up my db with this 3110_transport_data_corrections.sql

steel have no luck with zeppelin to Undersity

![изображение](https://user-images.githubusercontent.com/58750201/102628123-4aa32500-415a-11eb-8505-e01b7c5446d9.png)

**Comment by VitekUgarov** [comment]
when i login and appear at the platform near arrived zeppelin i see it and can use it
https://www.youtube.com/watch?v=vr2pZifHSnc

in other case i cant see zeppelin and cant use it

**Comment by Grz3s** [comment]
fixed with latest core updates

**Comment by VitekUgarov** [comment]
Work pretty well now.
Thx a lot !!!
