### ISSUE TITLE
🐛 [Bug Report] mangos-classic requires #include <functional> in UnitAI.h be added manually

### ISSUE THREAD

**Issue by bitbytenybble110** [cmangos/issues#2348]
## 🐛 Bugreport
mangos-classic fails to build at 19% in clean build directory with ```error: ‘std::function’ has not been declared``` in `UnitAI.h`

Attached cmake.log and make.log
[cmake.log](https://github.com/cmangos/issues/files/5721053/cmake.log)
[make.log](https://github.com/cmangos/issues/files/5721054/make.log)

### Expected behavior
mangos-classic binaries should build successfully

### Version & Environment

Client Version:  1.12.1

CMaNGOS Repo & Commit Hash:  https://github.com/cmangos/mangos-classic/tree/b1e413b302d1933812758ed25f90885008bd4a89

Database Repo & Commit Hash:  https://github.com/cmangos/classic-db/tree/8680c487b17ff4610b6796e1aedf00f98b927c90

Operating System: Ubuntu 18.04.5 LTS Kernel 4.15.0-128-generic x86_64

### Steps to reproduce
1.  Pull classic-mangos
2.  In build directory run `cmake ../mangos/ -DCMAKE_INSTALL_PREFIX=\../run -DPCH=1 -DDEBUG=0 -DBUILD_AHBOT=ON -DBUILD_PLAYERBOT=ON -DBUILD_EXTRACTORS=ON`
3.  In build directory run `make`

### Crashlog
- None

**Comment by bitbytenybble110** [comment]
```
In file included from /home/mangos/mangos-classic/mangos/src/game/AI/BaseAI/CreatureAI.h:22:0,
                 from /home/mangos/mangos-classic/mangos/src/game/AI/BaseAI/CreatureAI.cpp:19:
/home/mangos/mangos-classic/mangos/src/game/AI/BaseAI/UnitAI.h:463:39: error: ‘std::function’ has not been declared
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                       ^~~~~~~~
/home/mangos/mangos-classic/mangos/src/game/AI/BaseAI/UnitAI.h:463:47: error: expected ‘,’ or ‘...’ before ‘<’ token
         void AttackSpecificEnemy(std::function<void(Unit*,Unit*&)> check);
                                               ^
make[2]: *** [src/game/CMakeFiles/game.dir/AI/BaseAI/CreatureAI.cpp.o] Error 1
src/game/CMakeFiles/game.dir/build.make:62: recipe for target 'src/game/CMakeFiles/game.dir/AI/BaseAI/CreatureAI.cpp.o' failed
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
CMakeFiles/Makefile2:622: recipe for target 'src/game/CMakeFiles/game.dir/all' failed
make: *** [all] Error 2
Makefile:129: recipe for target 'all' failed
```
Appending additional compiler output missing from `make.log`

**Comment by christiansiewert** [comment]
It seems that your GCC compiler is too old, because `std::function` is not part of `std` on versions earlier than `g++-4.7` which includes `C++11`.

Try adding `#include <functional>` in `/home/mangos/mangos-classic/mangos/src/game/AI/BaseAI/UnitAI.h` and give it another try **or** upgrade your GCC compiler and pass `-std=c++11` argument during compilation.

![image](https://user-images.githubusercontent.com/33094503/102718906-1b6fed80-42eb-11eb-9463-990934b8b957.png)

**Comment by bitbytenybble110** [comment]
I'll try your recommendation but the GCC version installed is 7.5.0.  The default that is included in the Ubuntu 18.04 LTS.

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
```

**Comment by christiansiewert** [comment]
> I'll try your recommendation but the GCC version installed is 7.5.0.

Will you try the hint regarding `#include <functional>` and then can you please give feedback when you are done with it? 

I am interested in why this error is occurring and would like to know what is going on here. It could also be a misconfiguration in [cmangos/mangos-classic](https://github.com/cmangos/mangos-classic) CMake buildsystem generator.

**Comment by bitbytenybble110** [comment]
Inserting the `#include <functional>` line into the file `UnitAI.h` did allow me to compile mangos-classic without issue!

**Comment by christiansiewert** [comment]
> Inserting the `#include <functional>` line into the file `UnitAI.h` did allow me to compile mangos-classic without issue!

Ok, it would make sense to adapt the title of this issue. Would you be so kind?

**Comment by cala** [comment]
The missing include was added in January. Thanks for the report.
