### ISSUE TITLE
WoW 1.12 Classic client freezes sometimes with mmaps enabled

### ISSUE THREAD

**Issue by Neotmiren** [cmangos/issues#235]
With mmaps enabled client sometimes (rarely and unpredictably in general) freezes. Not completely, but FPS slows to 0.5 fps or lesser. I searched and found (in google cache) some messages from now not-functioning Mangos forum that described kind of the same issue:
# 

blueboy:
I have noticed that there does appear to be an annoying 'lag' that freezes the server (does not cause a crash). I would be interested to hear from you on the matter.
# 

blueboy:
Reply # 34 on: January 14, 2013, 01:51:40 PM >
Hi cala,

I've spent the weekend trying to track down the cause for this 'lag' issue. There is no apparent lagging with core code up to commit (z1898). Several commits after this involve the inclusion of the movemaps code. I built a server using code for commit (z1913) and everything ground to a halt after a few minutes. To prove that the problem is with the movemaps code, I disabled this feature in mangosd.conf and the lag went away. I know that playerbot code works fine with the movemap implementation for 'mangos-wotlk', so there is no reason why they shouldn't work together here too.

The path taken by bots returning to the player is very elongated, and this has already been commented on by xfurry here, with reference to npcs;

I have posted here to ask you and anyone else interested in testing the playerbot code to confirm (or not) this issue. I'm sure if this issue effects the playerbot code, it will also cause problems elsewhere.

I will work on a port for the 'mangos-tbc' code to check that this issue does not occur here too.
# 

As far as I can undertstand, this issue has not been resolved during past months.

Somehow I managed to find method of reproducing this bug. It always happens when you arrive to Theramore, just after a while. After short observation of creatures movements, it became clear that client freeze happens when "Theramore Guard" (Entry 4979, Guid 30639) walks up to the entrance of Jaina Proudmoore's Tower, reaches last step of staircase, turns round... and seems to disappear (if mmaps enabled he is not visible from "frozen mode"). If this Guard is killed using .die command the client freeze never happens.

**Comment by ryancheung** [comment]
In battleground, there is a very high chance of client freeze, especially have no client cache(WDB is empty). 

The client freeze also cause a fear movement bug: If the fearing target had a client freeze, other players saw him moving away. But, when the freeze is over, other players saw the fearing target immediately move back to a location with a very high speed.

**Comment by cyberium** [comment]
Closing this freeze are highly improved.
