### ISSUE TITLE
🐛 [Bug Report] NPC should run, not walk

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2351]
## 🐛 Bugreport
NPC should run to the designated place instead of walking slowly. The buff of players has disappeared on the way.

### Expected behavior
NPC should run, not walk

### Version & Environment
"2.4.3" (TBC)

Client Version: 
2.4.3

Database Repo & Commit Hash: 
dcd689a945e18b7dc4e4a3811bde0a400dfddf4d

Operating System: 
CentOS

### Steps to reproduce
1..character level 10
2..go xyz -4636.209961 -13069.5 -14.61 530
3..quest add 9541

**Comment by Grz3s** [comment]
and where you got that info from?
every avi from these times i saw summoned npc walks.
https://youtu.be/f00kCEI8t60?list=PL26B1F0F238B47030&t=119

**Comment by aleigood** [comment]
> and where you got that info from?
> every avi from these times i saw summoned npc walks.
> https://youtu.be/f00kCEI8t60?list=PL26B1F0F238B47030&t=119
> 
> Even person who does that q says that (...) he walks to slowly...

You may be right, I'm not sure, but the buff of the player will disappear when the NPC is halfway there.

**Comment by Grz3s** [comment]
pls do not post issue if u are not sure...

**Comment by aleigood** [comment]
I'm just not sure what the official version, but I'm sure that NPC ran in previous cmangos versions.

**Comment by Grz3s** [comment]
even avis from later expansions 2016 etc shows him walking

**Comment by aleigood** [comment]
https://www.youtube.com/watch?v=WkUpuaOb0Ek

**Comment by insunaa** [comment]
I think the misunderstanding here is that the furbolg walks all the time, ***until*** the furbolg transforms himself and the player into a panther, at which point the furbolg will run. This is visible both in the video of aleigood as well as the video by Grz3s

https://youtu.be/f00kCEI8t60?t=172

**Comment by Grz3s** [comment]
```code
Steps to reproduce
1..character level 10
2..go xyz -4636.209961 -13069.5 -14.61 530
3..quest add 9541
```
this is diff quest... but now i see what the problem is...

**Comment by aleigood** [comment]
In fact, what I want to say is that NPC started to run after becoming a cat, but now it's walking.

**Comment by Grz3s** [comment]
quest have been redone using correct data... 
However ... running still wont work...  its a core issue with how creatures a handled when summoned in water...

**Comment by Grz3s** [comment]
fixed:
https://github.com/cmangos/mangos-wotlk/commit/bfa848231feaae78856a2a0d2e9201a85e924bf7
