### ISSUE TITLE
🐛 [Bug Report]Miss Flypath in Moonglade

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2352]
## 🐛 Bugreport         

In moonglade, the flightmaster for druids only doesnt offer a return in their capital.                  
          
### Expected behavior                      

Normally, druids can return to their capital for free, tell the flight master of moonglade.          
NPC ID=11800 for alliance
NPC ID=11798 for horde                    

https://www.youtube.com/watch?v=7KuaM9JAKgU&ab_channel=GamersandEarners

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:8680c487b17ff4610b6796e1aedf00f98b927c90             

### Steps to reproduce                           

1. create hero druid level 10              
2. teleport to moonglade       
3. go to master fly .go xyz 7794.78 -2406.7 488.85           
4. see            

### Crashlog       

- None

**Comment by cala** [comment]
Tested right now and cannot reproduce. Could you provide more details on how to reproduce, please?

**Comment by ClassicW** [comment]
![image](https://user-images.githubusercontent.com/71378304/120383606-60ca2980-c325-11eb-9097-54acaebfc9e4.png)

create hero druid level 10
go to master fly .go xyz 7794.78 -2406.7 488.85

**Comment by cala** [comment]
![image](https://user-images.githubusercontent.com/1459044/120394368-98d86900-c333-11eb-8fcf-5a301d3d78ee.png)
The conditions for this gossip option to appear are: be Horde player AND have class mask 1024 (druid)
The various IDs for this gossip seem to be correctly set in the database. The only explanation that comes to mind is that your locale texts are missing the translation for this one.

Could you try:
```SQL
UPDATE gossip_menu_option SET option_broadcast_text=0 WHERE menu_id=4042;
```
Reboot your server and report back, please?

**Comment by QUADEMU** [comment]
Error found..... PR send on DB side, all informations there.
See u soon cMangos

**Comment by ClassicW** [comment]
thx you quademu, I thought the problem was mine. I was able to fix it.
![image](https://user-images.githubusercontent.com/71378304/123871319-e1377680-d933-11eb-876f-a9d9eb81854c.png)
![image](https://user-images.githubusercontent.com/71378304/123875010-40e45080-d939-11eb-8096-8e2ecc636237.png)
I was able to debug other fly world pvp at the same time
![image](https://user-images.githubusercontent.com/71378304/123875236-9b7dac80-d939-11eb-9a0c-46629b0c4331.png)
