### ISSUE TITLE
🐛 [Bug Report] Multiple players in group, player 2 randomly disconnected from server at arbitrary times.

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#2354]
## 🐛 Bugreport

Two players in group, tauren warrior and tauren shaman, level 8. questing in Mulgore. Every 5 minutes or so, player 2 is disconnected, player 1 (first to login) has never been disconnected.  Not clear weather it is some interaction with player 2 and npc/world etc. or it happens after some arbitrary time. It is not a hard disconnect, client still thinks player 2 is connected until timeout...

Internal LAN.

Same characters were working fine about 2 weeks ago (no idea on build at that time)

```
Socket::OnError.  The semaphore timeout period has expired.  Connection closed.
DoCastSpellIfCan by Creature (Entry: 18972 Guid: 86072) attempt to cast spell 20545 but spell failed due to unknown result 25.
DoCastSpellIfCan by Creature (Entry: 18972 Guid: 86072) attempt to cast spell 20545 but spell failed due to unknown result 25.
DoCastSpellIfCan by Creature (Entry: 18972 Guid: 86072) attempt to cast spell 20545 but spell failed due to unknown result 25.
DoCastSpellIfCan by Creature (Entry: 18972 Guid: 86071) attempt to cast spell 20545 but spell failed due to unknown result 25.
GameEvent 24 "Stormwind City - Stockades Jail Break" removed.
Next game event check in 600 seconds.
 DB-SCRIPTS: Process table `dbscripts_on_spell` id 37277, command 22 has buddy 21419 not found in range 30 of searcher Creature (Entry: 21417 Guid: 140459) (data-flags 0), skipping.
 DB-SCRIPTS: Process table `dbscripts_on_spell` id 37277, command 20 has buddy 21419 not found in range 30 of searcher Creature (Entry: 21417 Guid: 140459) (data-flags 2), skipping.
 DB-SCRIPTS: Process table `dbscripts_on_spell` id 37277, command 23 has buddy 21419 not found in range 30 of searcher Creature (Entry: 21417 Guid: 140459) (data-flags 8), skipping.
SESSION: received unexpected opcode CMSG_CANCEL_TRADE (0x011C) the player has not logged in yet and not recently logout
SESSION: received unexpected opcode CMSG_CANCEL_TRADE (0x011C) the player has not logged in yet and not recently logout
SESSION: received unexpected opcode CMSG_SET_SELECTION (0x013D) the player has not logged in yet
SESSION: received unexpected opcode CMSG_CANCEL_TRADE (0x011C) the player has not logged in yet and not recently logout
DoCastSpellIfCan by Creature (Entry: 21720 Guid: 75796) attempt to cast spell 12550 but spell failed due to unknown result 25.
DoCastSpellIfCan by Creature (Entry: 21720 Guid: 75800) attempt to cast spell 12550 but spell failed due to unknown result 25.
DoCastSpellIfCan by Creature (Entry: 21720 Guid: 75797) attempt to cast spell 12550 but spell failed due to unknown result 25.
DoCastSpellIfCan by Creature (Entry: 21720 Guid: 75803) attempt to cast spell 12550 but spell failed due to unknown result 25.

```
### Expected behavior

Server should not 'randomly' boot player 2.

### Version & Environment

Client Version:  2.4.3 (TBC)

CMaNGOS Repo & Commit Hash: 8384ef6cfbd27977ebf883708b8110c34007ab2b

Database Repo & Commit Hash: e0199d4469f039e274f874104d05d2feef51009e

Operating System:  Win 10

### Steps to reproduce
1. log in player 1
2. log in player 2
3. quest/interact with npcs/world for 10 - 15 mins
4. player 2 will server side disconnect and eventually timeout on client.

### Crashlog

- None

**Comment by Novivy** [comment]
I have regularly the same issue happening to random players at random time (in group but also alone) but almost every time it's in combat when casting a spell.

@lduguid why did you close it? found anything?

**Comment by lduguid** [comment]
Hmmm, this was sometime ago ( over a couple years), there has been many commits since then. From hazy memory, this was an issue after I updated but it was never determined what the cause could be at the time, some months after reporting it and more commits/updates later, it went away, at least on my server, hence the closing of the ticket.

Sorry its not helpful for your particular problem.
