### ISSUE TITLE
🐛 [Bug Report] ERROR 1064 (42000) at line 74: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(15268,'spell_blackout')

### ISSUE THREAD

**Issue by Daedalus-code** [cmangos/issues#2357]
```
> Trying to apply /home/ubuntu/wow/mangos-classic/sql/scriptdev2 ...
Appending SD2 file update scriptdev2.sql to database classicmangos_normal
Appending SD2 file update spell.sql to database classicmangos_normal
ERROR 1064 (42000) at line 74: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near (15268,spell_blackout),
(15323,spell_blackout),
(15324,spell_blackout),... at line 3
ERROR: cannot apply /home/ubuntu/wow/mangos-classic/sql/scriptdev2/spell.sql
```

Version: 
  - "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/mangos-classic/tree/c203e93249e8016297bf38d3df4131d8db077cf1)

Database Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/classic-db/tree/d5eee6ae4f7a77d88adbe333edf36478056950e1)

Operating System: 
Linux Ubuntu, Raspberry Pi4
```Linux ubuntu 5.4.0-1025-raspi #28-Ubuntu SMP PREEMPT aarch64 aarch64 aarch64 GNU/Linux```  

### Steps to reproduce
1. Update latest
2. InstallFullDB
3. 👀 
4. ...
5. Profit

**Comment by Grz3s** [comment]
fixed
