### ISSUE TITLE
🐛 [Bug Report]NPC falls out of the air

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2359]
## 🐛 Bugreport

The NPC came down from the sky:

![18695](https://user-images.githubusercontent.com/3367999/103654260-9a7a4c80-4fa0-11eb-9ec3-ee1f8c3de0de.jpg)

### Version & Environment
"2.4.3" (TBC)

Client Version: 
2.4.3

CMaNGOS Repo & Commit Hash: 
958a310001bb8e555bf024e27c46648761611f8f

Database Repo & Commit Hash: 
34d55bcca66a242f4b5003fefdeffb4bdc7321a6

Operating System: 
CentOS 7

### Steps to reproduce
.go cr id 18695 (When NPC appear in Dragonmaw fortress)

**Comment by killerwife** [comment]
Retested tbc, wotlk and voa. All seem fine now.
