### ISSUE TITLE
TBC - Shaman Windfury Totem extra attack offset

### ISSUE THREAD

**Issue by Cromisa** [cmangos/issues#236]
The Shaman's Windfury totem effect is being applied to the next attack rather than the current.
By that I mean, the graphic indicates that you've gained the Windfury proc, you also gain a buff saying you have the windfury proc (not sure this is needed? Pretty sure I didn't ever see it in the live server), but it doesn't apply until the next hit.
The next hit does generate and additional hit.
In addition, the free hit doesn't appear to increase the attack power of the attack, and also doesn't seem to proc all/any weapon enhancements (Seal of Righteousness, Firey Weapon enchant etc) - It seems to apply 1 of the effects, not both.

Example:
Paladin hitting for roughly 100ish white damage, with Seal Of Righteous adding another 20 damage, total 120ish.
Paladin gains the windfury totem proc(graphic runs, buff gets added) and does a normal hit (this attack should be the double hit)
The Paladins next hit does a double white hit for 100ish (should be more like 110ish with the AP bonus) and only adds one lot of 20 damage from Seal of Righteousness (should be two lots of 20 as it's another attack) - hope that makes sense?

The Windfury weapon(not totem) on the Shaman himself works fine (double attack with additional attack power in sync with the graphic and buff), it's just the totem when applied to other players has issues. As I'm typing this I realise I haven't tested if the Windfury totem works okay with the Shaman or not...I will confirm.

**Comment by jimmybrancaccio** [comment]
@Cromisa Can you confirm if this is still an issue with the latest commits?

**Comment by killerwife** [comment]
Fixed just like the other issue that reported this.
