### ISSUE TITLE
💬 [Support Request]alot of errors while compiling mangos-wotlk

### ISSUE THREAD

**Issue by rmzV** [cmangos/issues#2360]
## 💬 Support Request

Severity	Code	Description	Project	File	Line
Error	C2893	Failed to specialize function template 'unknown-type std::begin(_Container &)'	MoveMapGen	C:\mangos\dep\json\json.hpp	4290
Error	C1083	Cannot open include file: 'boost/stacktrace.hpp': No such file or directory	Shared	C:\mangos\src\shared\Log.cpp	32
Error	C2440	'return': cannot convert from 'initializer list' to 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>'	mmaplib	C:\mangos\contrib\mmap\src\MapBuilder.cpp	1182
Error	C4579	'nlohmann::detail::static_const<nlohmann::detail::from_json_fn>::value': in-class initialization for type 'const T' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported	mmaplib	C:\mangos\dep\json\json.hpp	2235
Error	C2131	expression did not evaluate to a constant (compiling source file C:\mangos\contrib\mmap\src\MapBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	2235
Error	C4579	'nlohmann::detail::static_const<nlohmann::detail::to_json_fn>::value': in-class initialization for type 'const T' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported	mmaplib	C:\mangos\dep\json\json.hpp	2235
Error	C4579	'nlohmann::detail::static_const<nlohmann::detail::from_json_fn>::value': in-class initialization for type 'const T' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported	mmaplib	C:\mangos\dep\json\json.hpp	2235
Error	C2131	expression did not evaluate to a constant (compiling source file C:\mangos\contrib\mmap\src\TerrainBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	2235
Error	C4579	'nlohmann::detail::static_const<nlohmann::detail::to_json_fn>::value': in-class initialization for type 'const T' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported	mmaplib	C:\mangos\dep\json\json.hpp	2235
Error	C2780	'unknown-type nlohmann::adl_serializer<T,void>::from_json(BasicJsonType &&,ValueType &) noexcept(<expr>)': expects 2 arguments - 1 provided	mmaplib	C:\mangos\dep\json\json.hpp	2513
Error	C2780	'unknown-type nlohmann::adl_serializer<T,void>::from_json(BasicJsonType &&,ValueType &) noexcept(<expr>)': expects 2 arguments - 1 provided	mmaplib	C:\mangos\dep\json\json.hpp	2513
Error	C2780	'unknown-type nlohmann::adl_serializer<T,void>::from_json(BasicJsonType &&,ValueType &) noexcept(<expr>)': expects 2 arguments - 1 provided	mmaplib	C:\mangos\dep\json\json.hpp	2513
Error	C2780	'unknown-type nlohmann::adl_serializer<T,void>::from_json(BasicJsonType &&,ValueType &) noexcept(<expr>)': expects 2 arguments - 1 provided	mmaplib	C:\mangos\dep\json\json.hpp	2513
Error	C2784	'const _Ty *std::begin(const std::valarray<_Ty> &)': could not deduce template argument for 'const std::valarray<_Ty> &' from 'add_rvalue_reference<const ContiguousContainer>::type' (compiling source file C:\mangos\contrib\mmap\src\MapBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2784	'_Ty *std::begin(std::valarray<_Ty> &)': could not deduce template argument for 'std::valarray<_Ty> &' from 'add_rvalue_reference<const ContiguousContainer>::type' (compiling source file C:\mangos\contrib\mmap\src\MapBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2784	'_Ty *std::begin(_Ty (&)[_Size]) noexcept': could not deduce template argument for '_Ty (&)[_Size]' from 'add_rvalue_reference<const ContiguousContainer>::type' (compiling source file C:\mangos\contrib\mmap\src\MapBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2893	Failed to specialize function template 'unknown-type std::begin(const _Container &)' (compiling source file C:\mangos\contrib\mmap\src\MapBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2893	Failed to specialize function template 'unknown-type std::begin(_Container &)' (compiling source file C:\mangos\contrib\mmap\src\MapBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2784	'const _Elem *std::begin(std::initializer_list<_Elem>) noexcept': could not deduce template argument for 'std::initializer_list<_Elem>' from 'add_rvalue_reference<const ContiguousContainer>::type' (compiling source file C:\mangos\contrib\mmap\src\MapBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2039	'iterator_category': is not a member of 'nlohmann::detail::iterator_traits<unknown-type,void>' (compiling source file C:\mangos\contrib\mmap\src\MapBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2146	syntax error: missing '>' before identifier 'iterator_category' (compiling source file C:\mangos\contrib\mmap\src\MapBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2784	'const _Ty *std::begin(const std::valarray<_Ty> &)': could not deduce template argument for 'const std::valarray<_Ty> &' from 'add_rvalue_reference<const ContiguousContainer>::type' (compiling source file C:\mangos\contrib\mmap\src\TerrainBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2784	'_Ty *std::begin(std::valarray<_Ty> &)': could not deduce template argument for 'std::valarray<_Ty> &' from 'add_rvalue_reference<const ContiguousContainer>::type' (compiling source file C:\mangos\contrib\mmap\src\TerrainBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2784	'_Ty *std::begin(_Ty (&)[_Size]) noexcept': could not deduce template argument for '_Ty (&)[_Size]' from 'add_rvalue_reference<const ContiguousContainer>::type' (compiling source file C:\mangos\contrib\mmap\src\TerrainBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2893	Failed to specialize function template 'unknown-type std::begin(const _Container &)' (compiling source file C:\mangos\contrib\mmap\src\TerrainBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2893	Failed to specialize function template 'unknown-type std::begin(_Container &)' (compiling source file C:\mangos\contrib\mmap\src\TerrainBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2784	'const _Elem *std::begin(std::initializer_list<_Elem>) noexcept': could not deduce template argument for 'std::initializer_list<_Elem>' from 'add_rvalue_reference<const ContiguousContainer>::type' (compiling source file C:\mangos\contrib\mmap\src\TerrainBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2039	'iterator_category': is not a member of 'nlohmann::detail::iterator_traits<unknown-type,void>' (compiling source file C:\mangos\contrib\mmap\src\TerrainBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	C2146	syntax error: missing '>' before identifier 'iterator_category' (compiling source file C:\mangos\contrib\mmap\src\TerrainBuilder.cpp)	mmaplib	C:\mangos\dep\json\json.hpp	4290
Error	LNK1181	cannot open input file '..\shared\Release\shared.lib'	AuthServer	C:\mangos\mangos\bin\buildir\src\realmd\LINK	1
Error	C4579	'nlohmann::detail::static_const<nlohmann::detail::from_json_fn>::value': in-class initialization for type 'const T' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported	MoveMapGen	C:\mangos\dep\json\json.hpp	2235
Error	C2131	expression did not evaluate to a constant	MoveMapGen	C:\mangos\dep\json\json.hpp	2235
Error	C4579	'nlohmann::detail::static_const<nlohmann::detail::to_json_fn>::value': in-class initialization for type 'const T' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported	MoveMapGen	C:\mangos\dep\json\json.hpp	2235
Error	C2784	'const _Ty *std::begin(const std::valarray<_Ty> &)': could not deduce template argument for 'const std::valarray<_Ty> &' from 'add_rvalue_reference<const ContiguousContainer>::type'	MoveMapGen	C:\mangos\dep\json\json.hpp	4290
Error	C2784	'_Ty *std::begin(std::valarray<_Ty> &)': could not deduce template argument for 'std::valarray<_Ty> &' from 'add_rvalue_reference<const ContiguousContainer>::type'	MoveMapGen	C:\mangos\dep\json\json.hpp	4290
Error	C2784	'_Ty *std::begin(_Ty (&)[_Size]) noexcept': could not deduce template argument for '_Ty (&)[_Size]' from 'add_rvalue_reference<const ContiguousContainer>::type'	MoveMapGen	C:\mangos\dep\json\json.hpp	4290
Error	C2893	Failed to specialize function template 'unknown-type std::begin(const _Container &)'	MoveMapGen	C:\mangos\dep\json\json.hpp	4290
Error	C2784	'const _Elem *std::begin(std::initializer_list<_Elem>) noexcept': could not deduce template argument for 'std::initializer_list<_Elem>' from 'add_rvalue_reference<const ContiguousContainer>::type'	MoveMapGen	C:\mangos\dep\json\json.hpp	4290
Error	C2039	'iterator_category': is not a member of 'nlohmann::detail::iterator_traits<unknown-type,void>'	MoveMapGen	C:\mangos\dep\json\json.hpp	4290
Error	C2146	syntax error: missing '>' before identifier 'iterator_category'	MoveMapGen	C:\mangos\dep\json\json.hpp	4290
Error	LNK1181	cannot open input file '..\..\src\shared\Release\shared.lib'	VMapAssembler	C:\mangos\mangos\bin\buildir\contrib\vmap_assembler\LINK	1
Error	LNK1181	cannot open input file '..\shared\Release\shared.lib'	WorldServer	C:\mangos\mangos\bin\buildir\src\mangosd\LINK	1

### Version & Environment

  Client Version - "3.3.5a" (WOTLK)

Client Version: 
  Commit Hash - is required

  - [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/XXXX)
  To find XXXX use "git log -1 --format=%H" in your local CMaNGOS repo
f64bbe823a4d0e06e5c8775125230af770220057

CMaNGOS Repo & Commit Hash:  
  - [WOTLK](https://github.com/cmangos/wotlk-db/tree/XXXX)
  To find XXXX use "git log -1 --format=%H" in your local Database repo
78c0f1d71920bc658402a3ea877a0635d3b61cad

**Comment by rmzV** [comment]
siims like \shared\Release\shared.lib missed, how can i fix it?

**Comment by al3xc1985** [comment]
Wasn't vs2015support  removed ?

**Comment by al3xc1985** [comment]
@cyberium can u poke in pls?

**Comment by rmzV** [comment]
https://github.com/cmangos/issues/wiki/Installation-Instructions
"Visual C++ 2015 or newer: Visual Studio Downloads (Visual Studio Community 2015 is recommended, but Express 2015 for Desktop will also do the job and is free, it is however not as good a choice for open source development as CE (Community Edition)."

at least instructions say that vs2015 is acceptable

**Comment by cyberium** [comment]
Yes VS2015 is removed. We generally support only one earlier version than current one. Microsoft VS2019 is current version so you should at least use VS2017. But i encourage you to always use latest version. CE version is free and can build the core.

For your issue you have to use newer version of boost. Your version is too old.

**Comment by rmzV** [comment]
@cyberium so vs2015 unsupported, but may work?  (and updating boost doesnot resolve issue?)

i am on non supported os atm and making some researches about modding vs_setup.exe (c++ app) to remove os restrictions but without luck. may be as c+ developer you can point a proper direction for my research?

**Comment by cyberium** [comment]
Iam not sure it can work. Iam just sure that you have old version boost too because its missing stacktrace.cpp.
I can't help you more than that unfortunately. Please try to use more recent version.
I will close this as its not supported.

**Comment by RazzorX** [comment]
Only for information:

I'am using Win7, VS2015 and Boost 1_71_0 and compiling of current mangos-wotlk core and extractors is always successfully.

**Comment by rmzV** [comment]
@RazzorX hehe, thanks, will try)

**Comment by rmzV** [comment]
@cyberium
@RazzorX

okey, just compiled with 1_71_0 boost... when you choose compile extractors, you get same numbers of errors... but compiling only server is fine.

i read this article
http://www.manchesterdeveloper.com/blog/post/compiling-code-without-visual-studio/

what do you think: is it possible to compile mangos without vs studio?
