### ISSUE TITLE
🐛 [Bug Report] Pet are disappeared whenever I enter or quit instance dungeons.

### ISSUE THREAD

**Issue by ckj777** [cmangos/issues#2364]
## 🐛 Bugreport

Pet are disappeared whenever I enter or quit instance dungeons

Details in youtube link below..
### Version & Environment

Client Version: 2.4.3" (TBC)

CMaNGOS Repo & Commit Hash:  latest

Database Repo & Commit Hash:  latest

Operating System: Windows 10 x64

### Steps to reproduce
1. https://www.youtube.com/watch?v=qvtpxC5cwIU
2.
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by Daedalus-code** [comment]
![classic](https://user-images.githubusercontent.com/59256533/105165952-41b9c080-5b17-11eb-8095-565901ed892e.jpg)
My pet ``Gucci`` "vanished" after entering dungeon and it changed it's name back to original npc name, pet is active but not around.

Client Version: 
  - "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/mangos-classic/tree/09bd8086b04431c685294f753a5a60bae31bd5d2)

Database Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/classic-db/tree/c1a0b3ac5fcfc895446d5d442b3da200d0b5f03c)

**Comment by BlackBoar101** [comment]
i have this bug also in 2.43 tbc.

**Comment by insunaa** [comment]
If you teleport after this happens (you entered the instance and your pet is gone) for example with `.go creature whatever`, even if that creature is within the same instance, your pet will also re-appear.

**Comment by insunaa** [comment]
Should be fixed as of https://github.com/cmangos/mangos-tbc/commit/ceb5c0e7aea9dff6d099c0a275f2541f3da511b6
https://github.com/cmangos/mangos-classic/commit/8f8714c0cf1638cd38419767dfa4c087bff12dd8
