### ISSUE TITLE
🐛 [Bug Report]Command "ban account" doesn't kick player 

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2366]
## 🐛 Bugreport         

The .ban account command doesn't completely disconnect the player and he ends up on the character list, so he can reconnect.     
the .kick command too         
          
### Expected behavior                      

When we ban a player, he should end up on the account connection and not on character list.      

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:c1d0cc769b644eeb65088c68b77cdd6d84311b5a                        

### Steps to reproduce                           

1. create hero                
2. connect ingame          
3. ban account with command .ban account            
4. try to reconnect ingame                

### Crashlog       

- None

**Comment by kepo123** [comment]
I confirm! The same problem exist on 2.4.3. Quite uncomfortable for live servers, because when there are hackers and some of the gms bans them, the hacker stays online and continues to use hacks.

**Comment by ClassicW** [comment]
that commit don't concern that one ? #8f9d1853

**Comment by killerwife** [comment]
This should no longer be an issue.
