### ISSUE TITLE
Problems after server running

### ISSUE THREAD

**Issue by tangko5290** [cmangos/issues#2368]
## 🐛 Bugreport

![20210116212701](https://user-images.githubusercontent.com/77279936/104813255-f8c9e980-5842-11eb-86ea-c437360bd1c0.png)

### Version & Environment

Operating System: 

### Steps to reproduce
1.mangosd.exe
2.DoCastSpellIfCan by Creature (Entry: 18972 Guid: 86070) attempt to cast spell 20545 but spell failed due to unknown result 25
3.There should be no "unknown result 25"
4. ...
5. uncommercially

### Crashlog

- None

**Comment by d3rrial** [comment]
This is *probably* caused by the shamans at the dark portal casting Lightning Shield on either themselves or others which already have a lightning shield active. As long as the target has an active shaman shield of the same kind, the spell will fail because "a more powerful version of this spell is already active"

```cpp
if (result != SPELL_CAST_OK)
            {
                switch (result) // temporary adapter
                {
                    case SPELL_FAILED_OUT_OF_RANGE:
                        return CAST_FAIL_TOO_FAR;
                    case SPELL_FAILED_TOO_CLOSE:
                        return CAST_FAIL_TOO_CLOSE;
                    case SPELL_FAILED_LINE_OF_SIGHT:
                        return CAST_FAIL_NOT_IN_LOS;
                    case SPELL_FAILED_PACIFIED:
                    case SPELL_FAILED_SILENCED:
                        return CAST_FAIL_STATE;
                    case SPELL_FAILED_NOT_READY:
                        return CAST_FAIL_COOLDOWN;
                    case SPELL_FAILED_NO_POWER:
                        return CAST_FAIL_POWER;
                    case SPELL_FAILED_CASTER_AURASTATE: // valid - doesnt need logging
                    case SPELL_FAILED_BAD_TARGETS:
                        return CAST_FAIL_OTHER;
                }
                sLog.outBasic("DoCastSpellIfCan by %s attempt to cast spell %u but spell failed due to unknown result %u.", m_unit->GetObjectGuid().GetString().c_str(), spellId, result);
                return CAST_FAIL_OTHER;
            }
```
doesn't account for that kind of result, so you get the unknown result log output
it doesn't affect your server performance at all, you can just ignore it.

**Comment by killerwife** [comment]
Closed through unported commit from wotlk.

**Comment by tangko5290** [comment]
Thank you for answering for me！
