### ISSUE TITLE
🐛 [Bug Report] Unable to use mount in cities

### ISSUE THREAD

**Issue by canidae** [cmangos/issues#2370]
## 🐛 Bugreport
Players cannot mount up in cities. Some places work (next to the canal in Stormwind), other's don't (Ironforge, town square between bank and auction house in Stormwind).

### Expected behavior
Players should be able to mount up in cities.

### Version & Environment
  - Client: "3.3.5a" (WOTLK)
  - Core: [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/7f545134946e72e5ebd913c866e8ff9d239c7978)
  - Database: [WOTLK](https://github.com/cmangos/wotlk-db/tree/36a1333587ab1e0eb7d0f3cbfd138cffd00f3a91)

### Steps to reproduce
1. Attempt to mount up between bank and auction house in Ironforge.
2. Profit

**Comment by kelbren** [comment]
Can confirm, mounts not allowed in major cities. They should be allowed.

**Comment by canidae** [comment]
This seems to have been fixed with this commit: https://github.com/cmangos/mangos-wotlk/commit/2204e5e45df4020f0480de14b07cb247346d48b7
