### ISSUE TITLE
🐛 [Bug Report] Elevator to Aldor Rise rises a bit too far

### ISSUE THREAD

**Issue by canidae** [cmangos/issues#2371]
## 🐛 Bugreport
The elevator to Aldor Rise starts at the top, then ascends even further up.
![aldor_rise_even_more2](https://user-images.githubusercontent.com/33864/104949081-a8779680-59be-11eb-8266-dc872f0753e3.png)

### Expected behavior
Elevator should go from the Terrace of Light to Aldor Rise, not from Aldor Rise to heaven.

### Version & Environment
  - Client: "3.3.5a" (WOTLK)
  - Core: [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/7f545134946e72e5ebd913c866e8ff9d239c7978)
  - Database: [WOTLK](https://github.com/cmangos/wotlk-db/tree/36a1333587ab1e0eb7d0f3cbfd138cffd00f3a91)

### Steps to reproduce
1. Observe elevator near Aldor Rise in Shattrath.
2. Profit

**Comment by Grz3s** [comment]
Fresh core with fresh DB..  and cant reproduce this issue:
heres vid:
https://youtu.be/yXOgj4Rjg8k

No idea what u did but.. pls check of fresh db. 

Can anyone else confirm it?

**Comment by kelbren** [comment]
Saw the same issue, re-extracted the mmap files and seems ok now. Perhaps the added GO were not extracted?

**Comment by canidae** [comment]
This is from a fairly fresh database, with one gotcha (which I really doubt should affect this): I've migrated (some) character data from a classic database using the following queries:
```
insert into wotlkcharacters.character_action select guid, 0, button, action, type from classiccharacters.character_action;
insert into wotlkcharacters.character_homebind select * from classiccharacters.character_homebind;
insert into wotlkcharacters.character_inventory select * from classiccharacters.character_inventory;
insert into wotlkcharacters.character_pet select id, entry, owner, modelid, createdbyspell, pettype, level, exp, reactstate, name, renamed, slot, curhealth, curmana, curhappiness, savetime, resettalents_cost, resettalents_time, abdata from classiccharacters.character_pet;
insert into wotlkcharacters.character_queststatus select guid, quest, status, rewarded, explored, timer, mobcount1, mobcount2, mobcount3, mobcount4, itemcount1, itemcount2, itemcount3, itemcount4, 0, 0 from classiccharacters.character_queststatus;
insert into wotlkcharacters.character_reputation select * from classiccharacters.character_reputation;
insert into wotlkcharacters.character_skills select * from classiccharacters.character_skills;
insert into wotlkcharacters.character_social select guid, friend, flags, "" from classiccharacters.character_social;
insert into wotlkcharacters.characters select guid, account, name, race, class, gender, level, xp, money, playerbytes, playerbytes2, playerflags, position_x, position_y, position_z, map, 0, orientation, taximask, online, cinematic, totaltime, leveltime, logout_time, is_logout_resting, rest_bonus, resettalents_cost, resettalents_time, trans_x, trans_y, trans_z, trans_o, transguid, extra_flags, stable_slots, 6, zone, death_expire_time, taxi_path, 0, 0, 0, 0, 0, 0, 0, 0, 0, watchedfaction, drunk, health, power1, power2, power3, power4, power5, 0, 0, 1, 0, concat(exploredzones, repeat(" 0", 64)), equipmentcache, ammoid, null, actionbars, deleteinfos_account, deleteinfos_name, deletedate from classiccharacters.characters;
insert into wotlkcharacters.guild select guildid, name, leaderguid, emblemstyle, emblemcolor, borderstyle, bordercolor, backgroundcolor, info, motd, createdate, 0 from classiccharacters.guild;
insert into wotlkcharacters.guild_eventlog select * from classiccharacters.guild_eventlog;
insert into wotlkcharacters.guild_member select guildid, guid, rank, pnote, offnote, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 from classiccharacters.guild_member;
insert into wotlkcharacters.guild_rank select guildid, rid, rname, rights, 0 from classiccharacters.guild_rank;
insert into wotlkcharacters.item_instance select guid, owner_guid, itementry, creatorguid, giftcreatorguid, count, duration, charges, flags, enchantments, randompropertyid, durability, 0, null from classiccharacters.item_instance;
insert into wotlkcharacters.pet_spell select * from classiccharacters.pet_spell;
delete from wotlkrealmd.account;
insert into wotlkrealmd.account select * from classicrealmd.account;
```

My current setup is that I actually drop database wotlkmangos and recreate it (InstallFullDB.sh) each time I start the server, leaving wotlkcharacters and wotlkrealmd untouched.
I could try restarting the server (later), see if that makes any difference.

**Comment by canidae** [comment]
Restarting the server fixed the position of the elevator.
It does indeed look like this error happen sporadically.

**Comment by canidae** [comment]
Returning to Shattrath after several hours (without restarting server) and the elevator is ascending to the heavens again.
Don't know if it's a zone loading issue or it just happens after a certain time.

**Comment by killerwife** [comment]
Need to recheck stationary position of elevator on wotlk. It will not manifest on spawn but later on. Its being sent out in Object.cpp in case someone wants to have a go at it.

**Comment by canidae** [comment]
Elevator seems to be working correctly now. I'm guessing this was the fix? https://github.com/cmangos/mangos-wotlk/commit/334f9f699ae338c23b66afb2ecef22c7f17a587e

**Comment by kelbren** [comment]
Server running for over 24 hours no issues with elevators. reboot server multiple times, still seems to be working properly.

**Comment by killerwife** [comment]
Yes that was the intented fix.
