### ISSUE TITLE
🐛 [Bug Report] TBC.spells.common.Melee attack angle too big.

### ISSUE THREAD

**Issue by BlackBoar101** [cmangos/issues#2372]
## 🐛 Bugreport when moving,attack range is too long.

https://user-images.githubusercontent.com/77557058/104978494-d7f7c480-59f9-11eb-9803-abbcdd198bfb.mp4
stand still
![IMG_20210121_152248](https://user-images.githubusercontent.com/77557058/105317108-bc3b1c80-5bb9-11eb-9eef-82118a82279a.JPG)
moving and attack
![IMG_20210121_152309](https://user-images.githubusercontent.com/77557058/105317133-c5c48480-5bb9-11eb-84b4-a482fc5a96ff.JPG)
normal attack angle
![-70a245c5d19dc545](https://user-images.githubusercontent.com/77557058/105317165-ceb55600-5bb9-11eb-8dc4-86eb80bebe5c.jpg)
cm2.43 angle
![7625a45be241106e](https://user-images.githubusercontent.com/77557058/105317182-d412a080-5bb9-11eb-9b9b-632e26cef215.jpg)

When moving the melee attack range is not right.too long hand than melee.
also,the attack angle is wrong too.180 not 120
when stand still the range bug is gone.but the angle bug remain

### Expected behavior

fix it
### Version & Environment

Client Version: 
2.4.3 TBC

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-tbc/tree/1b990c3

Database Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/tree/1b990c3

Operating System: 
win7
### Steps to reproduce
1.use hamstring
2.run around the mob
3.or face one arm toward the mob and run away from the mob
4. you,ll see warrior,s butt toward the mob and swing his axe too long away!
5.please leave comment if you want more information about this bug.

### Crashlog

- None

**Comment by BlackBoar101** [comment]
the latest playable code.2021.1.18

**Comment by insunaa** [comment]
Isn't this basic leeway kiting?

**Comment by BlackBoar101** [comment]
sorry.hard for me to open youtube.

**Comment by BlackBoar101** [comment]
@insunaa no.this is no flying kite.

**Comment by insunaa** [comment]
@BlackBoar101 As far as I can tell what you've shown and described is an intended mechanic of the game. It's called melee leeway and it increases the size of the hitbox of moving players and npcs. While it's undesirable to many players, it's definitely blizzlike

**Comment by BlackBoar101** [comment]
@insunaa
please check it out.
if this is the range motion buffer, the value is too big.it makes some class even unplayable now. and it feels ridicuous.

**Comment by insunaa** [comment]
I get what you're saying, *maybe* you're right. This is what I recorded literally just now in the official client on an official server: https://www.youtube.com/watch?v=sk25_2_Q9Y8

The attack angle does seem off in your example, but the distance seems to be accurate.

![image](https://user-images.githubusercontent.com/3718129/105320688-c283c580-5bc6-11eb-80e8-b108c05d290d.png)
^screenshot of the distance
![image](https://user-images.githubusercontent.com/3718129/105320741-d0d1e180-5bc6-11eb-8eae-7034fe7c5718.png)

**Comment by BlackBoar101** [comment]
what is ths client version? classic60 or the latestest lv100+ ？

**Comment by BlackBoar101** [comment]
and this one.watch where the warrior start to swing his sword.

https://user-images.githubusercontent.com/77557058/105328231-bcdaaf80-5bc7-11eb-97be-64e3727b6d54.mp4

**Comment by BlackBoar101** [comment]
@insunaa can you teach me how to add label to the bug?im a newbee here😲

**Comment by MantisLord** [comment]
@killerwife reminder for later

 https://www.youtube.com/watch?v=uokbqCLghbs

cbef22d6dc2880f7580d9938f168826dd76ac2ea

https://gitlab.com/lights-vengeance/issues/-/issues/1323

**Comment by BlackBoar101** [comment]
@MantisLord cool, i love you guys' golden shining code~

**Comment by BlackBoar101** [comment]
@mantislord 
please check the angle too.it should be 120 instead of 180.just a value but it affect a lot

**Comment by BlackBoar101** [comment]
@mantislord 
does this fix contain when moving attack range too long?i can see you fix the angle.

**Comment by BlackBoar101** [comment]
@mantislord
this is the normal mob max attack range when he chase you
![截屏_20210123_103938](https://user-images.githubusercontent.com/77557058/105566517-82d2f000-5d24-11eb-98b2-9036ca3e1709.jpg)
this is the mob max attack range in cm2.43.while the mob is out of the screen he can still attack you.
![截屏_20210123_103942](https://user-images.githubusercontent.com/77557058/105566552-b7df4280-5d24-11eb-847f-dbb10f6116a1.jpg)

**Comment by BlackBoar101** [comment]
@mantislord
the same thing happens in player's melee attack. it affect GREAT in pvp or any raid require position run.

**Comment by BlackBoar101** [comment]
@insunaa
check my latest screenshot please.

**Comment by BlackBoar101** [comment]
@mantislord 
hit the mob and fly it like kite,youll soon feel the range difference.

**Comment by BlackBoar101** [comment]
@killerwife
sorry to bother you.
there are two reasons cause normal attack looks so weird. 
first is attack angle.mantislord said it was confimed above.
second is the leeway value work on normal attack. to make it clear i opened#2402.
after your first check i upload anther several evidences.
hope these can make the issue clear.

**Comment by killerwife** [comment]
This has been resolved.

**Comment by AnonXS** [comment]
Duuplicate https://github.com/cmangos/issues/issues/2402
