### ISSUE TITLE
🐛 [Bug Report] Classic Fishing

### ISSUE THREAD

**Issue by Daedalus-code** [cmangos/issues#2377]
## 🐛 Bugreport

Start fishing where you can, to skill up.
Stuff keeps adding up, the player gets skills when nothing is caught also.
"The fish got away!" notification don't appear when that happens but it does appear when it really happens.

![Fishing0](https://user-images.githubusercontent.com/59256533/105633611-e90d5f00-5e59-11eb-8dd6-1c18a4dbc5a2.jpg)

After a while it will be less room to fish on if you don't move.
![Fishing1](https://user-images.githubusercontent.com/59256533/105633674-41446100-5e5a-11eb-9d02-7d4209be61e7.jpg)

Feels like I cheated when those extra skills popped up when nothing was caught sometimes.
![Skills](https://user-images.githubusercontent.com/59256533/105633721-941e1880-5e5a-11eb-91dc-2d2699f7a9aa.png)

Finally maxed out and leaving a mess 👀 🙈 
![Fishing3](https://user-images.githubusercontent.com/59256533/105633679-4e615000-5e5a-11eb-8644-01fc0f43f030.jpg)

### Expected behavior

The "bobber" Should disappear after the fishing round is completed, not stay. (some do disappear tho)
Could be related to the + skill I get and no fish is caught or no notification other than blue chat text with new skill acquired.

### Version & Environment

Client Version: 

CMaNGOS Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/mangos-classic/tree/cca21fff1fec16a22adeeda5f585902fee6021f3)

Database Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/classic-db/tree/3028bd7eb53b4351d71c0018587f875f154cde63)

Operating System: 
  - Linux Flavor
### Steps to reproduce
1. Start fishing
2. Continue fishing
3. Continuing
4. ...
5. Profit

### Crashlog

This popped up a lot at the end, from when I started to fish until I maxed out and logged out:
``15:07:51 ERROR:Loot::ShowContentTo()> Player Loading (Guid: 21) is trying to open a loot without credential
15:26:46 ERROR:Loot::ShowContentTo()> Player Loading (Guid: 21) is trying to open a loot without credential``

``
15:34:34 ERROR:Delete Gameobject (Entry: 35591 Guid: 9002630) with SpellId 7620 LinkedGO 0 that lost references to owner Player Loading (Guid: 21) GO list. Crash possible later.``
The server did not crash, still running.

**Comment by Daedalus-code** [comment]
**Went fishing in Baradin Bay.**
![Fishing_baradin_bay](https://user-images.githubusercontent.com/59256533/107873817-a3224480-6eb5-11eb-957e-b0145f9a9873.jpg)
That went fine, was there also another day fishing and no problems, at all.

Was at Astranaar real quick and fished some there, no errors, no pictures.

**Went back to Auberdine next to Gubber Blump.**
![Fishing_Auberdine](https://user-images.githubusercontent.com/59256533/107873861-e977a380-6eb5-11eb-836f-e2edfbeb884c.jpg)
These errors also came up again.
![mangos_log](https://user-images.githubusercontent.com/59256533/107873898-13c96100-6eb6-11eb-97f7-853833dcfe9d.png)
Went cooking with my caught fish, came back and they still there.
![Fishing_auberdine2](https://user-images.githubusercontent.com/59256533/107873888-0ad88f80-6eb6-11eb-8a63-c24573b640e6.jpg)
![bopper](https://user-images.githubusercontent.com/59256533/107873795-8128c200-6eb5-11eb-8892-efd8d884a330.png)

**Comment by aleigood** [comment]
The same problem occurred in WotLK.
