### ISSUE TITLE
🐛 [Bug Report] Death Knight rune consumption is not reflected in client

### ISSUE THREAD

**Issue by canidae** [cmangos/issues#2378]
## 🐛 Bugreport
Whenever Death Knights use powers that require runes the client is not updated to reflect that a rune was used.
This is similar to a previous bug (in Classic core) where energy users combo points did not disappear upon using finishing moves: https://github.com/cmangos/mangos-classic/commit/0f1f0ab000cb86f63fabdb9c6d8e5734e54285f5#diff-7a7fbb6e4a167c3e559c60a76a100a7172b3f84610925405f71b19df055b5aa6

### Expected behavior
Client should reflect that runes where consumed.

### Version & Environment
  - "3.3.5a" (WOTLK)
  - [WOTLK Core](https://github.com/cmangos/mangos-wotlk/tree/09729a5ab3f5ded2a1fd2c9352b50a42d6afb189)
  - [WOTLK DB](https://github.com/cmangos/wotlk-db/tree/3ccbb4341fa1e00f1cd2bc0446f61a05e8fcc136)
  - Ubuntu Focal

### Steps to reproduce
1. Use Death Knight ability that consumes a rune (for example Blood Boil).
2. Profit

### Crashlog
- None

**Comment by Mightylink** [comment]
I can confirm this is still happening in the latest build (3e8859b). The server is not sending rune cooldown information to the client and not showing the proper cooldown timers on spell abilities either giving you errors when trying to cast them.

Screenshot attached.
![WoWScrnShot_080121_131255](https://user-images.githubusercontent.com/10459893/127784929-006ee579-a182-439f-b479-2afc80c5f957.jpg)

**Comment by killerwife** [comment]
Resolved two weeks ago.
