### ISSUE TITLE
🐛 [Bug Report] Client crash when in Hellfire Peninsula

### ISSUE THREAD

**Issue by canidae** [cmangos/issues#2380]
## 🐛 Bugreport
Client frequently crash for players residing in Hellfire Peninsula. Client does not seem to crash in other zones like Terokkar Forest.
The crashes appear to happen both in and out of party.

There's some discussion on a commit I mistakenly thought was related to the issue. Adding it for reference: https://github.com/cmangos/mangos-wotlk/commit/f8cf6ed9e601f2d862203f40a4da83e934f2f88b

### Expected behavior
Client should not crash (usually infinite loop, process must be killed, sometimes client crash gives stack trace).

### Version & Environment
  - "3.3.5a" (WOTLK)
  - [WOTLK Core](https://github.com/cmangos/mangos-wotlk/tree/09729a5ab3f5ded2a1fd2c9352b50a42d6afb189)
  - [WOTLK DB](https://github.com/cmangos/wotlk-db/tree/3ccbb4341fa1e00f1cd2bc0446f61a05e8fcc136)
  - Ubuntu Focal

### Steps to reproduce
1. Let a server run for several days, it seems to crash more frequently after being up for some time.
2. Enter Hellfire Peninsula. Combat may or may not provoke client crash.
3. Client will eventually crash.

### Crashlog
- None

**Comment by killerwife** [comment]
Will look at this. Have a few clues as to why.

**Comment by canidae** [comment]
After updating to commit 83463453a2a6d2e81a7c46dbe596257896a593dd we've not experienced the client crashing in HFP. Not sure why, and I haven't studied the commits between when I reported this error and said commit, but a quick glance I couldn't see anything that was intended to fix this issue.
I'll keep the issue open for a bit longer, but if we still can't reproduce the error the next few days I'll close it.

**Comment by canidae** [comment]
No longer able to reproduce issue, closing.
