### ISSUE TITLE
🐛 [Bug Report] Mac build failing

### ISSUE THREAD

**Issue by tylercasper** [cmangos/issues#2385]
## 🐛 Bugreport
MacOS build is failing

### Expected behavior
The build should pass

### Version & Environment
"3.3.5a" (WOTLK)

Client Version: 
  [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/7f35a16c335de2374832486c7052df68483a3eac)

Operating System:
  Valid values are:
  - MacOS 11.1

### Steps to reproduce
1. Use a mac
2. Build

**Comment by metacreo** [comment]
What error from make ? "Boost.Stacktrace" ?

**Comment by insunaa** [comment]
It means you're using a version of Boost that is too old.
Boost/Stacktrace requires at least Boost version 1.65.0.
Mac Builds are confirmed to work with Boost 1.75.0 so I recommend you use this version of boost instead.

**Comment by metacreo** [comment]
@insunaa NO! it NOT related to boost.
@tylercasper try add  "add_compile_definitions(_GNU_SOURCE)" at end of file mangos/src/shared/CMakeLists.txt

**Comment by cala** [comment]
I'm unsure how someone can have an old version of boost installed on a Mac running the latest version of macOS : we are speaking of BigSur here, which have deprecated a lot of softwares.

**Comment by insunaa** [comment]
You literally said Boost.Stacktrace, how is it not related?
Maybe we need a Big Sur CI pipeline the, I think jimmy has something in the works for that, but at least on High Sierra the build works fine https://travis-ci.org/github/cmangos/mangos-wotlk/jobs/763487661

**Comment by metacreo** [comment]
just if(APPLAE) not work in CMakeLists

**Comment by cala** [comment]
I think @metacreo is refering to an issue that is supposed to be fixed in [this commit](https://github.com/cmangos/mangos-classic/commit/65712a1f421631009d41c334f450727edaab8387) and that was indeed a bug in Boost which was clearly marked by the development team as "won't fix", hence the workaround we had in the aformentioned commit.

**Comment by cala** [comment]
Regarding the original post of this issue, I simply believe that a good bunch of the libraries/tools used in CMaNGOS are simply not yet ported to macOS BigSur but without more output from OP, it will be hard to tell.

**Comment by metacreo** [comment]
# pkg info | grep boost
boost-all-1.72.0               The "meta-port" for boost libraries
boost-docs-1.72.0              Documentation for libraries from boost.org
boost-jam-1.72.0               Build tool from the boost.org
boost-libs-1.72.0_3            Free portable C++ libraries (without Boost.Python)

**Comment by cyberium** [comment]
Please provide full cmake output and also precise your hardware. Is it by any chance new M1 processor?

**Comment by metacreo** [comment]
everything is very simple. by mangos cmake config: linux,mac, freebsd... its UNIX and if(APPLE or if(FreeBSD not work
I no have new cpu or new hardware
Now I tried on freebsd manually add "add_compile_definitions(_GNU_SOURCE)" at end src/shared/CMakeLists.txt
No errors.
[CMakeOutput.log](https://github.com/cmangos/issues/files/6171046/CMakeOutput.log)

**Comment by metacreo** [comment]
Sorry...
Just now... on Catalina 10.15.7 cmake 3.19.7 boost 1.75.0.2
Build successful without any src modification.
Little later I try to build on bigsur.

**Comment by cyberium** [comment]
Should be fixed
