### ISSUE TITLE
🐛 [Bug Report] Naxxramas NPCs are too large

### ISSUE THREAD

**Issue by insunaa** [cmangos/issues#2386]
## 🐛 Bugreport

Many trash mobs in Naxxramas are way too large.

### Expected behavior

Trash mobs in Naxxramas should not be that large.

Spider Quarter Trash mobs:
https://youtu.be/3uIfEIGebt0
Abomination Quarter Trash mobs:
https://youtu.be/3uIfEIGebt0?t=569
Military Quarter Trash mobs:
https://youtu.be/3uIfEIGebt0?t=1852

### Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash:
mangos-tbc with commit: 8a2610f4ed253d4b8e7d2a4824f4221302752288

Database Repo & Commit Hash: 
tbc-db with commit: ea679ee148f7556515c89e77daaacd4ed4662ccb

Operating System: Linux hostname 5.10.5-arch1-1 #1 SMP PREEMPT Thu, 07 Jan 2021 09:50:43 +0000 x86_64 GNU/Linux

### Steps to reproduce
1. Create char
2. Go to Naxxramas
3. Look into the military quarter and the abomination quarter
4. ...
5. Profit

### Crashlog

- None

### Potential Fix:
Incorrect scale is probably caused by a "0" entry in the scale field of the creature_template table.

```
update creature_template set Scale=1 where entry=16145;
update creature_template set Scale=1 where entry=16146;
update creature_template set Scale=1 where entry=16165;
update creature_template set Scale=1 where entry=16164;
update creature_template set Scale=1 where entry=16163;
update creature_template set Scale=1 where entry=16861;
update creature_template set Scale=1 where entry=16449;
update creature_template set Scale=1 where entry=16368;
update creature_template set Scale=1 where entry=16446;
update creature_template set Scale=1 where entry=16451;
update creature_template set Scale=1 where entry=16017;
update creature_template set Scale=1 where entry=16029;
update creature_template set Scale=1 where entry=15939;
update creature_template set Scale=1 where entry=16452;
update creature_template set Scale=1 where entry=15976;
update creature_template set Scale=1 where entry=15975;
```

**Comment by AnonXS** [comment]
Adding to this
```
SELECT entry,name,scale FROM `creature_template` WHERE `scale` = 0;
```
are probably all wrong for tbc+
