### ISSUE TITLE
🐛 [Bug Report] Naxxramas Bosses don't reset when leaving fighting area

### ISSUE THREAD

**Issue by insunaa** [cmangos/issues#2388]
## 🐛 Bugreport

Bosses in Naxxramas never leash, they will always keep following the players.

### Expected behavior

Bosses should leash once players pull the boss outside of the fight area. For Razuvious for example it is up the staircase, for 4HM it is the doorframe, etc.
I'll add a more complete list and a Pull Request once I've implemented the leashes.

### Version & Environment

Client Version: Client Version: 
"2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 

mangos-tbc with commit: 8a2610f4ed253d4b8e7d2a4824f4221302752288

Database Repo & Commit Hash: 
tbc-db with commit: ea679ee148f7556515c89e77daaacd4ed4662ccb

Operating System: 

Linux hostname 5.10.5-arch1-1 #1 SMP PREEMPT Thu, 07 Jan 2021 09:50:43 +0000 x86_64 GNU/Linux

### Steps to reproduce
1. Create Character, Set level to 60
2. Port Character to Naxxramas and Pull Bosses
3. Run away really really fast and watch them chase you down, slowly but surely
4. ...
5. Profit

**Comment by insunaa** [comment]
Theoretically fixed with https://github.com/insunaa/mangos-tbc/commit/7f2e4eb5a255e669bace100abfc045aa2e3b32fc but haven't tested it yet because it's late at night and I need to sleep. Feel free to take a look at it @anybody reading this.

**Comment by killerwife** [comment]
The function in question in that commit will be removed in next few months. The new approach uses:
`
        m_creature->GetCombatManager().SetLeashingCheck([](Unit* /*unit*/, float /*x*/, float y, float /*z*/)
        {
            return y < 762 || y > 1076;
        });
`
style of checks. Just a headsup.
