### ISSUE TITLE
Mobs Backstab you even if you are facing them

### ISSUE THREAD

**Issue by scotty0100** [cmangos/issues#239]
Mobs Backstab you even if you are facing them

To test, .go creature Syndicate_Rogue

**Comment by cala** [comment]
I've open a PR that allows to handle this case in the NPC AI scripts rather than hardcoding exception for spells that are missing (on purpose?) spells attributes preventing them to be used in front of target.
https://github.com/cmangos/mangos-classic/pull/314

**Comment by cala** [comment]
Fixed in https://github.com/cmangos/mangos-classic/commit/211465ee4e3bf03009ad07cf41dee9efa42cf0ea. This is now up to DB devs to update the database.
