### ISSUE TITLE
🐛 [Bug Report] TK: Alar spawn with  hp 1 during Phase 2

### ISSUE THREAD

**Issue by ckj777** [cmangos/issues#2390]
## 🐛 Bugreport

Alar, the first boss of THE EYE,  has only 'hp 1' when its 2nd phase start.

### Version & Environment

Client Version: 2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: latest

Database Repo & Commit Hash: latest

Operating System: Windows 10 64x
                                  MySql 5.29
### Steps to reproduce
1. https://www.youtube.com/watch?v=-z3hmlP-c_0
2.
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by insunaa** [comment]
Can't reproduce on Linux with commit 3d4c0e3285ae5952b8da2808ad2f1d369f3f23eb
The entire encounter works exactly as expected.
