### ISSUE TITLE
🐛 [Bug Report] Server Crash on Player state change; Aura::UpdateAuraScaling() 

### ISSUE THREAD

**Issue by solo0755** [cmangos/issues#2391]
## 🐛 Bugreport

After running for a while, it crashes，dump a corefile 
useing： gdb ./mangos corefile
find a crashlog like this.
All the null-pointer problems I have judged in method (Aura::UpdateAuraScaling() ) and still have problems.

### Version & Environment

  - "2.4.3" (TBC)

Client Version: 

243
CMaNGOS Repo & Commit Hash: 
eb902887ed98d7677c2a72b73645b33a93a9e477

Database Repo & Commit Hash: 

  - Linux  Ubuntu18

Operating System: 

### Steps to reproduce
After running for a while, it crashes，dump a corefile 
useing： gdb ./mangos corefile
find a crashlog like this.
### Crashlog

#0  0x000056434588b65f in Aura::UpdateAuraScaling() ()
#1  0x00005643456ab98d in Unit::UpdateScalingAuras() ()
#2  0x000056434568fcc5 in Player::UpdateStats(Stats) ()
#3  0x00005643456acb42 in Unit::HandleStatModifier(UnitMods, UnitModifierType, float, bool) ()
#4  0x00005643456366d4 in Player::_ApplyItemBonuses(ItemPrototype const*, unsigned char, bool) [clone .part.432] ()
#5  0x0000564345637ac2 in Player::_ApplyItemMods(Item*, unsigned char, bool) ()
#6  0x000056434564548d in Player::EquipItem(unsigned short, Item*, bool) ()
#7  0x00005643459e8668 in WorldSession::HandleAutoEquipItemOpcode(WorldPacket&) ()
#8  0x00005643458423e8 in WorldSession::ExecuteOpcode(OpcodeHandler const&, WorldPacket&) ()
#9  0x000056434584a576 in WorldSession::Update(unsigned int) ()
#10 0x0000564345903b63 in World::UpdateSessions(unsigned int) ()
#11 0x00005643459076d6 in World::Update(unsigned int) ()
#12 0x00005643454f0717 in WorldRunnable::run() ()

- None

**Comment by solo0755** [comment]
i'will try this,tks all.
https://github.com/cmangos/mangos-tbc/commit/8a2610f4ed253d4b8e7d2a4824f4221302752288

**Comment by al3xc1985** [comment]
@solo0755 any crash?

**Comment by killerwife** [comment]
Should be resolved now.
