### ISSUE TITLE
🐛 [Bug Report] Improved Blizzard‘s chill effect working incorrectly

### ISSUE THREAD

**Issue by Gornaut** [cmangos/issues#2394]
[chilled] area effect (ingame spell ID: 12486) that is applied when Improved blizzard (ingame spell ID: 12488) talent is chosen in the frost tree working not as intended. Currently [chilled] effect is applied after 1-st blizzard damage tick and only reapplied after 4.5 seconds.

The [chilled] effect should be reapplied on targets every Blizzard tick (i.e every second)
so targets are slowed throughout the whole blizzard duration.

Proofs are:
1. https://www.youtube.com/watch?v=beyRXulvycI (from 1:55-2:00).
2. Classic Reference Client.
It also worked properly in earlier builds.

Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/tree/master/src/game/Spells

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/master/Full_DB

The most recently compiled version.

Operating System: Win 10

### Steps to reproduce

1. Log in onto any account;
2. Make a lvl 70 mage;
3. Choose Improved blizzard rank 3 in the frost tree;
4. Find mob/group of mobs;
5. Cast Blizzard spell of any rank on mob/group of mobs;
6. Look at the chilled debuff on one of the targets you casting blizzard on;
7. Make sure that chilled effect is only reapplied after previous one fades (4.5 sec).

### Crashlog
- None

**Comment by tangko5290** [comment]
Correct the owner of the post :
It's not the blizzard spell that went wrong!It's talent - Frost - enhanced blizzard(Spell code:11185-Lv1,12487-Lv2,12488-Lv3)

**Comment by killerwife** [comment]
Retested on mangos-tbc, the slow from improved blizzard is reapplied every blizzard tick as intended.
