### ISSUE TITLE
🐛 [Bug Report] NPC overlap in The Shattered Halls

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2399]
## 🐛 Bugreport

.go xyz 82.682137 76.32 -13.222322 540

![snipaste_20210215_185540](https://user-images.githubusercontent.com/3367999/107938097-cfc28300-6fbf-11eb-8d39-118e86122380.jpg)

### Version & Environment

Client Version: 
"2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 
6221743f48b4ca1d8b37a5527f58f1046ae629ec

Database Repo & Commit Hash: 
ab512902982a02347e307deb4720d7800e1ff5c2

Operating System: 
Linux 

### Steps to reproduce
1. .go xyz 82.682137 76.32 -13.222322 540

**Comment by miraco** [comment]
https://github.com/cmangos/mangos-tbc/commit/9bfb4b578a4e381dc0b3ddd9a8a02f16c6496fc0

1 of them shouldnt spawn cause of spawnMask.
Savage or Heathen for normal, heathen only on heroic.

**Comment by insunaa** [comment]
Does the issue also exist if you enter the instance via the dungeon portal, so that it's properly initialized with difficulty and stuff?

**Comment by AnonXS** [comment]
It seems the spawnmasks in your pullrequest where messed up @miraco

**Comment by AnonXS** [comment]
lets improve from here: https://github.com/cmangos/tbc-db/commit/801cf303eefd4d4670114cfa02d8bd299ecb6e4a

**Comment by miraco** [comment]
Im 90% sure it worked right after the core fix. And looking over the spawn Masks/pooling i couldnt find an error DB wise.
