### ISSUE TITLE
[TBC] Everybody Passed (Loot)

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#240]
I think I found a bug when using Group Loot or Need Before Greed.

The loot window will appear giving the players options to need, greed, pass. Sometimes it pops up quick and then disappears and says "Everybody Passed". I think it has to do when the loot roll window counting down, and then another player loots the same corpse. Once that happens it stops and says the above.

MaNGOS One/ (* * Revision 2040 - *) for Linux_x64 (little-endian)
ScriptDev2 (for CMaNGOS s2036+) Revision [s2747] (*) * * (Unix)

Don't have ACID version off the top of my head. But its the latest from their repo as of this post.

As a side note I believe this has only happened to me in dungeons.
Also, when in Group Loot or Need Before Greed, the leader shows the bag icon that I though was supposed to show for Loot Master only?

**Comment by cyberium** [comment]
fixed
