### ISSUE TITLE
🐛 [Bug Report] Ironforge Weapon Master's gossip menu is not available

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2400]
## 🐛 Bugreport
Ironforge Weapon Master's gossip menu is not available, and clicking "I'd like some weapon training" after clicking the gossip menu has no response.

![snipaste_20210215_193234](https://user-images.githubusercontent.com/3367999/107941731-1e265080-6fc5-11eb-9350-20d6cfcbc03e.jpg)
![snipaste_20210215_193218](https://user-images.githubusercontent.com/3367999/107941738-2088aa80-6fc5-11eb-8af5-bf6aebae5ba1.jpg)

### Expected behavior
The gossip menu is available.

### Version & Environment

Client Version: 
"2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 
b402c1d0ac0019967b62f33271839cb1487d2644

Database Repo & Commit Hash: 
145967aa2f009fcecce09453c1fa151ad8f6de19

Operating System: 
Linux

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/af66da8d8816d692e3997fdf172e386fa8878ca0
