### ISSUE TITLE
🐛 [Bug Report] TBC.spells.warrior.id_78.Heroic strike delete next normal attack.

### ISSUE THREAD

**Issue by BlackBoar101** [cmangos/issues#2403]
## 🐛 Bugreport

https://user-images.githubusercontent.com/77557058/108138917-d5e75b00-70b6-11eb-8c8b-78343826049d.mp4
https://user-images.githubusercontent.com/77557058/108031709-392aac00-7029-11eb-9174-d55de01b9e66.mp4

First video is a normal heroic strike.
Second video is cm2.43.
youll notice normal attack&rage got deleted in the second video

After active heroic strike.
other spell cast make rage not enough for next heroic strike will cancel heroic strike and delete the normal attack.
when rage is not enough the normal attack SHOULD NOT BE DELETED.
all the spells cast condition "need next weapon swing" have the same bug.
example "cleave"
it,s a heavy bug for fury and defence warrior.
### Expected behavior

@AnonXS AnonXS commented 6 hours ago
http://wowwiki.wikia.com/wiki/Patch_1.11.0

If Heroic Strike or Raptor Strike fails, your combat swing will do normal damage.
### Version & Environment

Client Version: 
2.4.3

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-tbc/tree/1b990c3

Database Repo & Commit Hash: 
https://github.com/cmangos/mangos-tbc/tree/1b990c3

Operating System: 
win7
### Steps to reproduce
1.active heroic strike
2.use other rage cost spell make rage lower than heroic strike
3.heroic strike fail and normal attack deleted
4. ...
5. Profit

### Crashlog

- None
 
### AnonXS edit

export of commit 7daaf7c223a5f7915e67580ead0225598cb280a9 - Spell: Let swing go through if next swing spell fails  will resolve this.

**Comment by BlackBoar101** [comment]
https://github.com/cmangos/issues/issues/2405#issuecomment-781007280

**Comment by wdenejko** [comment]
Hello, 

Any info regarding a potential fix for this issue?

**Comment by BlackBoar101** [comment]
If Heroic Strike or Raptor Strike fails, your combat swing will do normal damage.

**Comment by AnonXS** [comment]
@killerwife

**Comment by killerwife** [comment]
Solved already.

**Comment by BlackBoar101** [comment]
nice.i will test it later.
