### ISSUE TITLE
🐛 [Bug Report] TBC.spells.warrior.id_845.Cleave delete next normal attack.

### ISSUE THREAD

**Issue by BlackBoar101** [cmangos/issues#2404]
## 🐛 Bugreport

Active cleave 
Use other rage cost spell, make rage not enough for coming cleave.
Cleave will be canceled and delete the coming normal attack.
The normal attack should not be deleted.

need more information please look at bug_2403,i think they are a same bug.
https://github.com/cmangos/issues/issues/2403#issue-809067389
### Version & Environment

Client Version: 
2.43

CMaNGOS Repo & Commit Hash: 

Database Repo & Commit Hash: 

Operating System: 
win7
### Crashlog

- None

**Comment by BlackBoar101** [comment]
video explain at bug_2403

**Comment by BlackBoar101** [comment]
@insunaa
excuseme, can you teach me a cmake method. really sorry to contact you here, cause i dont konw other ways to talk to you.
i want to compile latest version server so i can report more bugs rightly.   this is the error below

![捕获](https://user-images.githubusercontent.com/77557058/111862712-05c59f00-8992-11eb-8d82-6fb8e59d267a.PNG)

**Comment by insunaa** [comment]
Sorry, can't help you with windows.

**Comment by BlackBoar101** [comment]
@insunaa 
thank you all the same~

**Comment by AnonXS** [comment]
@killerwife

**Comment by killerwife** [comment]
Solved already.
