### ISSUE TITLE
🐛 [Bug Report] [TBC] Zul'aman Invisible attacker 

### ISSUE THREAD

**Issue by d3athbl0w** [cmangos/issues#2406]
## 🐛 Bugreport

https://youtu.be/sGLP-RFqOAA

### Expected behavior

I'm not sure how this should work, but the most logical thing is that if it is a Mob it would be good if it can be attacked

### Version & Environment

Client Version: 
  - "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-tbc/commit/4c3e72b315c827a96489ac5802d1c7cd96ad5793

Database Repo & Commit Hash: 
https://github.com/cmangos/tbc-db/commit/45a132888bf46a18b12ac70ef1c1397bbbc5a223

Operating System: 
Windows 10
### Steps to reproduce
1. Go to zul'aman.
2. Go to the boss Akil'zon.
3. From the beginning there are unbeatable mobs hitting all the players.

### Crashlog

- None

**Comment by insunaa** [comment]
The enemy who is attacking you is this trigger NPC
![image](https://user-images.githubusercontent.com/3718129/108601645-e2610180-739d-11eb-82f4-270f0a73d02f.png)

**Comment by AnonXS** [comment]
[npc_eagle_trash_aggro_trigger](https://github.com/cmangos/mangos-tbc/commit/2e8fe69150e11e7fa83ac0144b4733f8bf5d4c59)
