### ISSUE TITLE
🐛 [Bug Report] Blackheart the Inciter script bug (Heroic)

### ISSUE THREAD

**Issue by Gornaut** [cmangos/issues#2407]
## 🐛 Bugreport
Blackheart the inciter the second boss in Shadow Labyrinth does not use mind control on players during casting his “Incite chaos” ability (spell ID: 33684) in heroic mode dungeon. Script itself seems to be partly working as Text script works fine same as movement but ability is not casted.

### Expected behavior
Players in party should be mind controlled and be hostile to each over for the duration of the spell.
Video proof of mechanic: https://www.youtube.com/watch?v=vX95Z5nqI0c&t=93s (watch from 0:45-0:55)

### Version & Environment

Client Version: "2.4.3" (TBC)
CMaNGOS Repo & Commit Hash: 2f7b26ef674091bd69b5f68f6c429c5fa7cc94b7

Database Repo & Commit Hash: 19dfd0943f54605994c40b46bcd62867d761be0b

Operating System: Win 10

### Steps to reproduce
1. Log in game;
2. Spawn 1-4 player bots;
3. Give every spawned player bot Shadow Labyrinth Heroic key by typing .additem 27991;
4. Change dungeon mode to heroic;
5. Type .tele SL;
6. Enter dungeon;
7. type .go creature Blackheart
8. Start the encounter with Blakcheart the Inciter;
9. Wait until he casts Incite Chaos.
10. profit

### Crashlog
- None

**Comment by AnonXS** [comment]
@killerwife
