### ISSUE TITLE
🐛 [Bug Report] sunwell plateau - kalecgos

### ISSUE THREAD

**Issue by Sladana** [cmangos/issues#2408]
## 🐛 Bugreport

https://i.gyazo.com/5ae578cad8e3d681a409f67cb84bb994.jpg
https://i.gyazo.com/b62d0f57d877db9fc735c04afeededfa.jpg

- "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-tbc/tree/master
  Database Version - is required
  Valid values are:
https://github.com/cmangos/tbc-db/tree/master

 

### Steps to reproduce
When Sathrovarr the Corruptor falls below 10% 
should Kalecgos(Dragon) and Sathrovarr the Corruptor Crazed Rage ( https://www.wowhead.com/spell=44806 )
Kalecgos(Human) but shouldn't get it.
All NPCs(Trash/Boss), and Player in Sunwell will be affected by the buff / debuff

**Comment by Sladana** [comment]
If you use the spell 44807 as a GM, all npcs in the area get this buff.

is it maybe a sql error? Attributes AttributesEx3 in the Spell Template ?

Because the c++ script looks clean.

**Comment by killerwife** [comment]
The script is a major work in progress for me on vengeance server. Anything SWP is like from 2015 with minor rewrites and needs fixing up. It will be in ports sometime this year when I finish Muru and Kiljaeden. Sadly its the only major TBC instance which isnt working atm in cmangos. (however all the other ones should work)

**Comment by solo0755** [comment]
All NPCs(Trash/Boss), and Player in Sunwell will be affected by the buff / debuff；
It's the same on my side;  
How to fix it? modify spell_template？

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/73747118c1f781cb34ace3dbdc935dc254f22524
