### ISSUE TITLE
🐛 [Bug Report] - TBC - Priest [Shadowfiend] does not regenerate mana

### ISSUE THREAD

**Issue by diluh** [cmangos/issues#2409]
## 🐛 Bugreport

Mana regen part does not work now

### Expected behavior

How should it work : Creates a shadowy fiend to attack the target. Caster receives 3% mana when the Shadowfiend attacks. Damage taken by area of effect attacks is reduced. Lasts 15 sec.

### Version & Environment

Client Version: 

  - "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 

https://github.com/cmangos/mangos-tbc/tree/4610107a04025c56b36fd9d5bc1016b1118dc150

Database Repo & Commit Hash: 

https://github.com/cmangos/tbc-db/tree/f1baa3ecbebbdcd934c3be6831ec3de5489d5ee1

Operating System: 
Ubuntu 18.04 LS

### Steps to reproduce
1. Use Shadowfiend
2.
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by diluh** [comment]
Someone if possible can give attention this error is critical

**Comment by insunaa** [comment]
The bug occurs because the pet is summoned *after* the spell aura is trying to apply to the pet. It doesn't find a pet => No mana leech aura applied to it.
