### ISSUE TITLE
[TBC] Spellprocc( like ignite,impact etc) castingtimebar disapears

### ISSUE THREAD

**Issue by AlexHjelm** [cmangos/issues#241]
Bug found! when my spells procc ( like ignite,impact etc) my casting time bar on my casting time spells disapears

**Comment by jimmybrancaccio** [comment]
Hello, I am closing this out due to an incomplete report. If this is still an issue please open a new case with full details so we can further investigate.

**Comment by killerwife** [comment]
This is also fixed already.
