### ISSUE TITLE
🐛 [Bug Report] [wotlk] Can't attack creatures in the water

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2411]
## 🐛 Bugreport
You can only hit once. If you attack again, creature will dodge and cannot be attack again.

### Expected behavior
should not be dodged.

### Version & Environment
Client Version: 
"3.3.5a" (WOTLK)

CMaNGOS Repo & Commit Hash: 
6b64356f3a3ca65e0c534eee74eb8ce7b6d3e977

Database Repo & Commit Hash: 
ae2f901214d19b27b818f167e10b41db74448974

Operating System: 
Linux

### Steps to reproduce
1. .go 5997.698242 664.057678 -8.271814 1
2. attack creature Darkshore Thresher (2185)

**Comment by aleigood** [comment]
ad95793c0de42da599e3eb6a8b42e5eae5078bd0

Update to above commit, he problem remains (wotlk).

**Comment by Grz3s** [comment]
should be fixed with:
https://github.com/cmangos/mangos-wotlk/commit/485e85200369715f15c78d5a2af92107ded2e550

**Comment by aleigood** [comment]
Tested and fixed.
