### ISSUE TITLE
💬 [Support Request]Why no dmp Callback log after the crash

### ISSUE THREAD

**Issue by cbcs** [cmangos/issues#2412]
## 💬 Support Request
How to make mangosd generate dmp after crash

### Version & Environment
Client Version: 
 "2.4.3" (TBC)

Windows 7 

CMaNGOS Repo & Commit Hash:  
Last repo

Database Repo & Commit Hash: 
Last Database repo

Operating System: 
Win 7

### Steps to reproduce
I just want to know why I am not generating dmp logs after the program reads and writes errors and crashes.
For example, I deliberately miswritten some loading logic code. Why is there no dmp generated?
How to enable dmp?

It seems that the WheatyUnhandledExceptionFilter of WheatyExceptionReport.cpp is not working.

Sry my bad english. 
Sincerely thank you for help me .

**Comment by insunaa** [comment]
Wheaty Exception stuff is literally decades old, I would have to look into this some more, but it might be that Wheaty just doesn't work anymore.

**Comment by cbcs** [comment]
> Wheaty Exception stuff is literally decades old, I would have to look into this some more, but it might be that Wheaty just doesn't work anymore.
Thank you for your reply. How can dmp or crash logs be generated?

**Comment by insunaa** [comment]
You could try it with this: https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps
But it might be even tho Wheaty is generally unfunctional, that it interferes with this, so ymmv.

**Comment by cbcs** [comment]
thx.
