### ISSUE TITLE
🐛 [Bug Report] Old Hillsbrand Foothills

### ISSUE THREAD

**Issue by Sladana** [cmangos/issues#2413]
## 🐛 Bugreport
CMaNGOS TBC/0.18 (2021-03-09T21:40:03+01:00 - 7e083a56458a1c247c85deeaa2d6c5b2a666e5da) for Linux_x64 (little-endian) 
Using World DB: TBC-DB 1.8.0 'Vengeance Strikes Back' for CMaNGOS-TBC 
Using creature EventAI: ACID 2.4.3 (The Burning Crusades) for CMaNGOS-TBC (2.4.3 Client) 

5er Dungeon => Old Hillsbrand Foothills 2nd Boss Captain Skarloc cannot be attacked, Event Stucked.

**Comment by al3xc1985** [comment]
@cyberium this was fixed I remember. Can it be closed?
