### ISSUE TITLE
🐛 [Bug Report] Rogue does not detect [Hunters' traps]

### ISSUE THREAD

**Issue by diluh** [cmangos/issues#2421]
## 🐛 Bugreport

Rogue Doesn't Detect Hunters' Traps - Leaving your skill useless
### Expected behavior

Rogue can detect Hunters' traps from a distance and can disarm
### Version & Environment

Client Version: 
  - "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-tbc/tree/633de2b8fa3eb73c9bcc19f287cf5260d12aa311

Database Repo & Commit Hash: 
https://github.com/cmangos/tbc-db/tree/d95bf93648a542b45056be9bedb76cdd370393b3

Operating System: 
- Linux Ubuntu 18.04
### Steps to reproduce
1. Start a duel between **Rogue x Hunter**
2. With the Hunter throw the traps to the ground
3. With Rogue you will not detect traps being unable to disarm
4. ...
5. Profit

### Crashlog

- None

**Comment by insunaa** [comment]
Can you post a video of how it's supposed to be vs. how it is? In my tests I could see the trap just fine for ~10 seconds until it became invisible, but I don't know if that is intended behavior or not.

**Comment by diluh** [comment]
@insunaa I made this video below see in the link
See that in the first trap the rogue sees it perfectly, in the second ice trap the rogue does not see it takes a while to be able to see.

https://streamable.com/s3zi5h

Is this behavior in the video correct?
@MantisLord @killerwife  Some information about this problem?

**Comment by insunaa** [comment]
The trap detection doesn't have infinite range. It's normal for the rogue to not see it from far away

**Comment by diluh** [comment]
@cyberium Fixed may close
