### ISSUE TITLE
🐛 [Bug Report] Morogrim Tidewalker / Colifang Fangs kill the Watery Grave Players

### ISSUE THREAD

**Issue by Sladana** [cmangos/issues#2425]
## 🐛 Bugreport
CMaNGOS TBC/0.18 (2021-03-19T13:38:55+01:00 - 5fe0793ccf6c70672e797a84d67efc86357bea72) for Linux_x64 (little-endian) 
Using World DB: TBC-DB 1.8.0 'Vengeance Strikes Back' for CMaNGOS-TBC 
Using creature EventAI: ACID 2.4.3 (The Burning Crusades) for CMaNGOS-TBC (2.4.3 Client) 

  
### Steps to reproduce
1. Pulling Morogrim Tidewalker
2. Watery Grave =>  Teleport 4 players under the waterfalls. ~6000 damage after 6 seconds, and some (about 1.5k) falling damage. ~50 Yard Range from Morogrim Tidewalker. ~ 30 sec cooldown. People close to the watery grave target will also take damage.
3. Colifang Fangs kill the Watery Grave Players
5. Profit

=> Method TBC Vid => https://www.youtube.com/watch?v=mWDOkWp952Q&t=366s  => No Colifang Fangs spawn.

**Comment by Sladana** [comment]
If Lurker is still alive, the fish spawn should be normal. It is not normal for the fish to follow players and fly after them.
normally they despawn

**Comment by insunaa** [comment]
Seems like the opposite problem of https://github.com/cmangos/issues/issues/2411 now

**Comment by AnonXS** [comment]
no its an issue with shallow water detection and in these small puddles small fish never spawn to my knowledge. so somebody has to add a missing z level condition to their spawn script.

**Comment by insunaa** [comment]
https://github.com/insunaa/mangos-tbc/tree/frenzy_fix should make them not spawn during the morogrim encounter

**Comment by AnonXS** [comment]
problem is they also spawn in vashj area befor and during the fight

**Comment by insunaa** [comment]
@AnonXS updated

**Comment by AnonXS** [comment]
vashj is swimable water though.

**Comment by insunaa** [comment]
@AnonXS updated again

**Comment by AnonXS** [comment]
we already have the check at spell s.37025 but ~20y seems fine, i commited something similar recently as the water checks are not super reliable yet.

**Comment by insunaa** [comment]
I'll open a PR if that's fine with you?

**Comment by AnonXS** [comment]
sure^^

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/61dde8f34776d807a436a990f8b7b74889dff273
