### ISSUE TITLE
🐛 [Bug Report]

### ISSUE THREAD

**Issue by filipbekic01** [cmangos/issues#2427]
I'm getting next error while building on Ubuntu 20.04:

[ 16%] Building CXX object src/game/CMakeFiles/game.dir/AI/ScriptDevAI/scripts/eastern_kingdoms/sunken_temple/instance_sunken_temple.cpp.o
/home/filip/mangos/mangos-tbc/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/shadowfang_keep/shadowfang_keep.cpp:171:21: error: ‘override’ does not name a type
  171 |     void Reset() {} override

**Comment by insunaa** [comment]
Try changing this file
https://github.com/insunaa/mangos-tbc/commit/3c1ea3f874629897a63d7c59f4ec2b78194f1fbf or rather applying this patch
https://github.com/insunaa/mangos-tbc/commit/3c1ea3f874629897a63d7c59f4ec2b78194f1fbf.patch

**Comment by cala** [comment]
I'm on it. =)

**Comment by filipbekic01** [comment]
Yeah I move one commit back and compilation works, I think last commit broke it :) Thanks @cala !

**Comment by cala** [comment]
There are two issues in my last commit that don't compile on GCC (Clang builds without problem though).
I'm waiting for Travis CI to confirm that everything is fine with my fix and I shall push it to master in a few minutes.

**Comment by insunaa** [comment]
Travis already confirmed that gcc on Linux is working now. Verdict on Clang on MacOS is still out, but Clang on Linux also builds :)

**Comment by cala** [comment]
I'm building on macOS with Clang, so there should be no surprise (and that's why I did not see the issues before pushing to master), but let be sure.

**Comment by filipbekic01** [comment]
Are you sure you're using latest GCC 9.3.0 (at the moment of writing)?

**Comment by insunaa** [comment]
build should be fixed, try with the latest commit

**Comment by aleigood** [comment]
fixed in wotlk

**Comment by cala** [comment]
@filipbekic01 could you confirm that this issue is fixed with the latest commits, please?

**Comment by filipbekic01** [comment]
Yes, build is passing.
