### ISSUE TITLE
🐛 [Bug Report] NPC triggered by quest always display

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2428]
## 🐛 Bugreport

.go -10826.94 -830.086 55.570 0

![snipaste_20210324_224746](https://user-images.githubusercontent.com/3367999/112330441-01cbb100-8cf3-11eb-8f3e-d86a8756b810.jpg)

### Version & Environment

Client Version: 
"3.3.5a" (WOTLK)

CMaNGOS Repo & Commit Hash: 
da01cc70f59434b4ddf4e311bd639bf94d3638f6

Database Repo & Commit Hash: 
a207315b101e9ee1c259f92ca9ba07f196e7d9da

Operating System: 
Linux

### Steps to reproduce
1. .go -10826.94 -830.086 55.570 0

**Comment by aleigood** [comment]
Looks like the script is broken. The part I expected 'DARKSHIRE...I HUNGER!!' did not appear after quest is done.

**Comment by cala** [comment]
> The part I expected 'DARKSHIRE...I HUNGER!!' did not appear after quest is done.

1. This text is not always played, this is one of a few options for the event amongst other texts
2. This text is played at one of the steps of the event, almost 10 minutes after the event is started, not right after quest completion
3. Successfully tested right now


I'm closing the issue.
