### ISSUE TITLE
[classic] Confuse and fleeing

### ISSUE THREAD

**Issue by zwisus** [cmangos/issues#243]
case 1
when a creature has aura(19503 or 118),it can add threat and follow the healer.
only follow the healer ,can not attcak.

spell:
19503= Scatter Shot
118= Polymorph

case 2
If  hunter has a pet.
hunter and his pet in creature‘s Aggro.
hunter cast Scatter Shot to creature, at the same time cast Feign Death)
 when the Scatter Shot's aura remove from the creature,
the creature will stop attack,only to follow the pet,only follow,can not attcak.
Not only Scatter Shot(confuse), Polymorph and Fear too.

**Comment by trimken** [comment]
UP problem still exist on TBC too.

**Comment by cala** [comment]
It's probably relevant for all cores to be honest.
The movement system is on the verge of being reworked. This could impact this issue (or at least post-poned its resolution).

**Comment by Warlockbugs** [comment]
Please, verify if this still happens after https://github.com/cmangos/mangos-classic/commit/47664238b4e0e82ad0a6762beefcbf5e33c6b462.

**Comment by cyberium** [comment]
This should be fixed
