### ISSUE TITLE
🐛 [Bug Report] [Spell] 3436 Wandering Plague

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2430]
## 🐛 Bugreport

Spell Wandering Plague (3436)
1. Can restore cat form energy.
2. It can infect itself.

![bug1](https://user-images.githubusercontent.com/3367999/112500560-740bc680-8dc3-11eb-8c34-2e2310de7b85.gif)

### Version & Environment

Client Version: 
"3.3.5a" (WOTLK)

CMaNGOS Repo & Commit Hash: 
da01cc70f59434b4ddf4e311bd639bf94d3638f6

Database Repo & Commit Hash: 
a207315b101e9ee1c259f92ca9ba07f196e7d9da

Operating System: 
Linux

### Steps to reproduce
1. .go cr 5125
2. Use Druid cat form to attack creatures.

**Comment by cala** [comment]
Thanks for your report. Fixed by https://github.com/cmangos/mangos-classic/commit/83369a3e3244475f383fcce599b39d0520150546
