### ISSUE TITLE
💬 [Support Request] How to keep database up-to-date?

### ISSUE THREAD

**Issue by filipbekic01** [cmangos/issues#2431]
When I want to get latest server version, I pull files and re-compile the project. 

But, how to keep my database up-to-date?

**Comment by Grz3s** [comment]
./installfulldb.sh 
and then reaply your custom stuff if theres any

**Comment by filipbekic01** [comment]
So what's gonna happen with NPCs for example? The one you add with `.npc add ID` command?

Its written in DB but full installation again may override it.

**Comment by insunaa** [comment]
They are overridden. If you have the option in your mangosd.conf activated, all custom-sql commands you're executing, like spawning creatures or gameobjects are saved as .sql files into the folder where your server binaries are (by default at least).
If you check them for errors and completeness you can use them to add the specific changes you did back to the database.

**Comment by filipbekic01** [comment]
That makes sense @insunaa. I believe full install will override only server (mangos) database? It will not override realm and characters tables? I went through script and it seems like that. Am I right? 

The main question is, I'm safe to run that script on production server?

**Comment by insunaa** [comment]
It will not override realm and character tables, yes.
Depending how old your server version is, it still comes with dangers tho, as in November 2020 there was a patch with how items are saved in the database (which is the characters database). This update requires you to run a script that will convert the old item_instance table to the new format.

Try to take a look if your version is older or newer than that.

It never hurts to have a backup of your database before running the script, but generally it is safe to run on a production server. (Tho I still advise testing it first, and again definitely having a backup)

**Comment by filipbekic01** [comment]
I've just started - a week ago. I'm still investigating the structure and community itself. My server is actually online and this is my first server ever to be honest. I compiled everything successfully on my Linux thanks for installation guide - it's golden.

However, database is a bit tricky because base SQL files are in server repository and, database seeds are in another repository. That makes sense at some point but I think base could be moved to database repository.

Maybe adding one more bash script named for example "UpdateDB.sh" wouldn't hurt I believe. Therefore, installation and update would be almost same probably (would read root file) but for example UpdateDB.sh would have some extra checks like the one you mentioned above.

**Comment by insunaa** [comment]
The difference there is pretty much semantic only. `InstallFullDB.sh` is intended both for filling an empty database, as well as updating an existing Database. Custom changes to the Database are generally "unsupported", but work via the `dev` directory in the database repository. When you add all your custom sql changes as .sql files to that directory and enable dev_updates in the `InstallFullDB.config` your custom sql will be applied after all the regular database updates are done.

As for SQL currently being split between core and db repo, that's being worked on

**Comment by filipbekic01** [comment]
Thanks for information, I really appreciate it!
