### ISSUE TITLE
🐛 [Bug Report]Sheep don't regen enemy

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2432]
## 🐛 Bugreport   

Sheep don't  regen   

![image](https://user-images.githubusercontent.com/71378304/112664784-a1578380-8e5a-11eb-98c9-73e5f34df1a7.png)      
 
### Expected behavior                      

when you are under the effect of sheep, your life should go up quickly   

### Version & Environment                     

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:c5f62c24deb587697dc571e76e5c20cada743190                            

### Steps to reproduce                           

1. create mage hero                  
2. go learn spell sheep           
3. damage enemy and use sheep        
4. see...                  

### Crashlog       

- None

**Comment by killerwife** [comment]
Check in core why 12939 spell id isnt being applied.

**Comment by ClassicW** [comment]
it is applied, but aura 12939 does not regen. I need someone to confirm this to me.

**Comment by MilkmanMHOC** [comment]
Sheep do not regen health on my server.  I thought perhaps i mis-remembered how sheep worked back in classic, but then i saw this, so guess its a bug?

**Comment by AnonXS** [comment]
try cutting this line

```UPDATE creature, creature_template SET creature.curhealth=creature_template.MinLevelHealth, creature.curmana=creature_template.MinLevelMana WHERE creature.id=creature_template.Entry AND RegenerateStats&1;```

from classic-db\utilities\world_cleanup.sql

**Comment by cala** [comment]
`world_cleanup.sql` is not part of the install process, so the first step is likely to have no effect. 😉

**Comment by cala** [comment]
Thank you for this report. Fixed by https://github.com/cmangos/mangos-classic/commit/999ebfd1f83d2b699921d8a3c9ef96a5b39d23b3
