### ISSUE TITLE
💬 [Support Request] 

### ISSUE THREAD

**Issue by Urthel** [cmangos/issues#2433]
## 💬 Support Request

Hi, currently working on putting together a 2.4.3 TBC cMangos server and it is coming along fine except that have hit a temporary snag when 'Installing Databases'.  (Am following the instructions as per https://github.com/cmangos/issues/wiki/Installation-Instructions link).  The guide is great and it is easy to follow though Mysql is something I've never had to dabble in before but it isnt all that difficult .  What I wanted to find out is how do I link the Bin file to mysql under linux?  (or is that step of the guide for the windows users only?)  

Tried to use the following console commands: 
mysql -uroot -p < mangos/sql/create/db_create_mysql.sql (but when I checked the 'create' folder that .sql file is already listed and contains the data to make the mangos user and mangos password already).  Am guessing that I still need to link that .sql file to the mysql database, right?  How is that done on linux?

The error that I get when I enter that command is:
bash: mangos/sql/create/db_create_mysql.sql: No such file or directory
(Even used with and without sudo at start of the above console command but same error message come up.  Am I right in thinking that it is all cause of the BIN file not being linked?)

(This is prob an easy solution for some but I am just not one of those lucky peeps yet lol)

### Version & Environment
NAME='Linux Mint'
VERSION="19.3" (Tricia)
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME='Linux Mint 19.3"
VERSION_ID="19.3"
HOME_URL='https://www.linuxmint.com/"
SUPPORT_URL='https://forums.linuxmint.com/"
BUT_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxming.com/"
VERSION_CODENAME=tricia
UBUNTU_CODENAME=bionic

  Client Version - "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash:  git clone git://github.com/cmangos/mangos-tbc.git mangos
Database Version - git clone git://github.com/cmangos/tbc-db.git

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

**Comment by insunaa** [comment]
Depends on your directory structure...

The problem seems to be that you're executing that command in the wrong directory.

**Comment by Urthel** [comment]
Thank you.  Will try this now.

**Comment by Urthel** [comment]
Worked out what went wrong and you was as you said...  that command line used folder 'mangos' but in my directory the way it was set it also had a main folder with same name.  I have bypassed that error message but for some reason Mysql wont grant access.  ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES).  Have gone into Mysql and just changed the root user password but still same error after the change...

**Comment by Urthel** [comment]
I think i got it.  It is a port issue apparently.

**Comment by insunaa** [comment]
yeah, the first one, the one which sets up the mangos user account etc., has to be done\* with the root user, so you actually have to use `sudo mysql ...` for subsequent ones you should be able to use the `mangos` user

\* technically it doesn't *have* to be done as root, but in this specific case it doesn't do harm as far as I can tell and it's the easiest way.
After that you should no longer need to use sudo or root user for any more commands

**Comment by Urthel** [comment]
Legend, thank you.
