### ISSUE TITLE
💬 [Support Request] End-Game Vendors

### ISSUE THREAD

**Issue by filipbekic01** [cmangos/issues#2435]
## 💬 Support Request
Does anybody know a good SQL script for vendors? I'm creating fun server and creating new vendors would take much time, I need some bootstrap at least.

If there is not ready-to-go script, maybe an idea how to make it quickly? I want to cover almost all end-game items, PvP and PvE.

Thanks for report in advance.

### Version & Environment
  - "2.4.3" (TBC)

**Comment by insunaa** [comment]
Not officially supported, but check out https://github.com/milestorme/CmanGOS_Mall

**Comment by filipbekic01** [comment]
Exactlly what I needed, just wanted to make sure with someone from community that mall is compatible with this cmangos version.

Thanks a ton!
