### ISSUE TITLE
🐛 [Bug Report] Razormane Stalker use wrong stealth spell.

### ISSUE THREAD

**Issue by Tobschinski** [cmangos/issues#2436]
Razormane Stalker use an incorrect spell to stealth. 

use spells 7939 & 22766 instead

DB 3812f8a95ec84fc89453bb5ba8d24d4b5ab90aca

**Comment by cala** [comment]
@Tobschinski if you do not fix this one by yourself, I assume there is some trick in here with these two spells that can't be fixed solely from the database ?

**Comment by Tobschinski** [comment]
never even looked at it

**Comment by cala** [comment]
Do your sniffs hint that spell 7939 triggers spell 22766?
