### ISSUE TITLE
💬 [Support Request] Player commands through CPP

### ISSUE THREAD

**Issue by filipbekic01** [cmangos/issues#2437]
## 💬 Support Request
What would be the easiest way to add item to Player inventory from CPP script? Can I invoke .additem command against player through CPP?

### Version & Environment
  - "2.4.3" (TBC)

**Comment by filipbekic01** [comment]
I believe I can add item in RAM, so after .save command or once interval fires, it will be saved in database too.

**Comment by insunaa** [comment]
Look at 
```cpp
StoreNewItemInBestSlots()
```

**Comment by filipbekic01** [comment]
That's perfect. I tried calculating slot on my own, I was sure there is a better way.
