### ISSUE TITLE
🐛 [Bug Report] Auction House Chest / Robe Bug

### ISSUE THREAD

**Issue by filipbekic01** [cmangos/issues#2441]
## 🐛 Bugreport
Auction house does not show items with inventory type `ROBE = 20` when category is selected. For example, if you add item [Wyrmhide Robe] to auction house and you navigate to Armor > Leather > Chest, the item will not appear. I can fix the issue but I just need approval from somebody that I'm right about this bug.

### Expected behavior
Auction house listing should return items with inventory type 20 or 5 for Chests.

### Version & Environment
Client Version: 2.4.3 TBC 

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/tree/124264045fe9fdcb99a1f003e1afc209e43bf44d

P.S. It's forked.

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/91bbc38fdc7763dfdaabd304f0bb09be712878f6

Operating System: Linux Ubuntu 20.04

### Steps to reproduce
1. Add [Wyrmhide Robe] to auction house
2. Open Armor > Leather > Chest
3. You can't see the item in that category

### Crashlog
- None

**Comment by filipbekic01** [comment]
Feel free to assign this issue to me.

**Comment by al3xc1985** [comment]
Nice, ty

**Comment by cyberium** [comment]
Fixed by https://github.com/cmangos/mangos-tbc/commit/216e00f52003b8f1e2e3ca1be5daee03a71b4a0e
