### ISSUE TITLE
🐛 [Bug Report] If the player is defeated by "Slim", his partner will always be by his side and will not disappear.

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2445]
If the player is defeated by "Slim", his partner will always be by his side and will not disappear.

Expected behavior
The partner  he summoned should disappear.

Version & Environment
Client Version:
"3.3.5a" (WOTLK)

CMaNGOS Repo & Commit Hash:
eeeb560413b8282c9e996deb1c6b0c108b2224e3

Database Repo & Commit Hash:
fa30e3d2eba4671eb413e966defeed72d1a25381

Operating System:
Linux

Steps to reproduce

**Comment by Grz3s** [comment]
and you expect that everyone will know who "slim" is .. right?
`npc entry` or `quest id` ....
![IQqvUNZtSCaxUQdG0d0-HQ](https://user-images.githubusercontent.com/2374069/113340696-20016480-9324-11eb-850c-f04063f37969.jpg)

**Comment by insunaa** [comment]
I'm guessing its the dude in the inn in Menethil

**Comment by Grz3s** [comment]
i know that and ..prob lots of ppl also... but this is a lesson .. to make correct tickets... not part of info..
