### ISSUE TITLE
🐛 [Bug Report]Priest Resurrecting Crashs Server

### ISSUE THREAD

**Issue by MilkmanMHOC** [cmangos/issues#2448]
## 🐛 Bugreport
Priest resurrecting crashes server if dead player in group has released. Server crashes if a priest tries to rez someone that has released. 

### Expected behavior
Priest should be able to resurrect after player has released but before returning to body without server crashing.

### Version & Environment
"1.12.1" (CLASSIC)

This same issues seems to have been reported and fixed for WotLK back in 2014.  See issues https://github.com/cmangos/issues/issues/478

Issues is reproducible at will.  Have party member die and release.  When priest resurrects dead character, the server cashes.

**Comment by canidae** [comment]
I think this is the same issue as https://github.com/cmangos/issues/issues/2397, which also happens in WotLK core.
