### ISSUE TITLE
Swift Hand of Justice / Discerning Eye of The Beast

### ISSUE THREAD

**Issue by tarwyn** [cmangos/issues#245]
These trinkets have a secondary effect that is supposed to restore mana or HP respectively on a kill that yields experience or honor. This is not currently working, no mana or HP are restored.

**Comment by jimmybrancaccio** [comment]
@tarwyn Can you confirm if this is still an issue on the latest commits?

**Comment by killerwife** [comment]
That was really long time ago. Needs to be manually rechecked. 99% this already works.

**Comment by Phatcat** [comment]
These still do not work as described, no.
