### ISSUE TITLE
🐛 [Bug Report] - Hunter - [Aspect of the Viper] Spell does not work mana regeneration

### ISSUE THREAD

**Issue by diluh** [cmangos/issues#2451]
## 🐛 Bugreport

I received some error report on the spell [Aspect of the Viper] ID 34074 - the spell is not regenerating the mana of the hunters they do not see any difference with magic activated.
### Expected behavior

When using magic the Hunter must regenerate their mana frequently as described in the spell
### Version & Environment

Client Version: 
  - "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-tbc/tree/74e1f760faa91fadfb15fa19ba76f21d60e10c89

Database Repo & Commit Hash: 
https://github.com/cmangos/tbc-db/tree/441a5466ddf37025c4d38e9c18f621029440c533

Operating System: 
- Linux Ubuntu 18.04
### Steps to reproduce
1. Spend the hunter's mana without the magic [Aspect of the Viper] and see mana regeneration
2. Now turn on [Aspect of the Viper] and notice that mana regeneration has virtually no difference with or without magic enabled.
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by diluh** [comment]
@cyberium @killerwife @MantisLord 
If possible could give a priority in this Bug thank you in advance

**Comment by nate123456** [comment]
The tag `Version: TBC` should be added to this issue for clarification.

**Comment by killerwife** [comment]
Can confirm aspect of the viper working, but it does not show up in combat log because of an attribute that is clientside.
