### ISSUE TITLE
🐛 [Bug Report] [Kil'jaeden/Sunwell Plateau]

### ISSUE THREAD

**Issue by d3athbl0w** [cmangos/issues#2452]
## 🐛 Bugreport

1.  First of all there are the NPCs that have to be when the encounter with kil'jaeden ends.
2.  Second these 3 mobs: https://www.wowhead.com/npc=25588/hand-of-the-deceiver When killing them kil'jaeden exits normally but ... it is not targetable.

### Version & Environment

Client Version: 

"2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-tbc/tree/74e1f760faa91fadfb15fa19ba76f21d60e10c89

Database Repo & Commit Hash: 
https://github.com/cmangos/tbc-db/tree/441a5466ddf37025c4d38e9c18f621029440c533

Operating System: 

Windows 10

### Steps to reproduce
1. Go to sunwell plateau and go to the area where kil'jaeden is.

### Crashlog

- None

**Comment by nate123456** [comment]
This issue should have the tag `Version: TBC` added to it for clarification.

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/73747118c1f781cb34ace3dbdc935dc254f22524
