### ISSUE TITLE
🐛 [Bug Report] Hunter's pet back to stay place with a very low speed

### ISSUE THREAD

**Issue by kaneha59** [cmangos/issues#2453]
## 🐛 Bugreport
![pet_walk](https://user-images.githubusercontent.com/33512405/115549366-28bdd880-a2db-11eb-925e-e497513488db.png)

### Expected behavior
pet should **_run_** back to place A,not walk.

### Steps to reproduce
1.order pet to stay at place A.
2.order pet to attack a monster.
3.switch pet mode to passive mode.
4. then pet will walk back to place A slowly.
### Version & Environment
Client Version: 
"2.4.3" (TBC)

CMaNGOS Repo & Commit Hash:
8853d361c64445e6c67fc04e253d30dd4f128003

Database Repo & Commit Hash:
bb12637676b39aefddc8b00f879a8a51516a366d

Operating System: 
Ubuntu20

### Crashlog
- None

**Comment by Warlockbugs** [comment]
Fixed.
