### ISSUE TITLE
🐛 [Bug Report] - Raid - Serpentshrine Cavern - Boss (The Lurker Below) - Phase SPOUT

### ISSUE THREAD

**Issue by diluh** [cmangos/issues#2454]
## 🐛 Bugreport

`case LURKER_SPOUT` with error

Currently the boss does not do the 360 degree turning over the BUG-showing platform in the video below
                  👇
https://streamable.com/odoi73

Another note when the boss throws players far away from the platform the creatures Coilfang Frenzy ID = 21508 are appearing in a lot of this way players die before climbing on the platform

### Expected behavior

In the SPOUT phase, the boss must drop the magic by turning the platform as in the video below 

https://youtu.be/JhWuAKAwTaw?t=37

### Version & Environment

Client Version: 
  - "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 
https://github.com/cmangos/mangos-tbc/tree/1fd6cbf383ecab031dd76223055aaaf57dbf8dd6

Database Repo & Commit Hash: 
https://github.com/cmangos/tbc-db/tree/2777eb0fcb4cc779e3c1121397a676be339fa39d

Operating System: 
  - Linux Ubuntu 18.04
### Steps to reproduce
1. Start Fight with Boss and wait for the SPOUT phase
2.
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by nate123456** [comment]
This issue should have the `Version: TBC` tag added to it for clarification.

**Comment by killerwife** [comment]
This has been resolved by altering the duration of the action I believe.
