### ISSUE TITLE
🐛 [CLASSIC] Duplicate page in item Jordan's Weapon Notes

### ISSUE THREAD

**Issue by vdeschuyf** [cmangos/issues#2457]
## 🐛 Bugreport
Duplicate page in item Jordan's Weapon Notes

### Version & Environment

Client Version: 1.12.1

CMaNGOS Repo & Commit Hash: e5d1b76fa1e642fec7f1f134f88c921b305d4c1d

Database Repo & Commit Hash: 1cff0972538ff44d078d48c54963cb25e6b775cf

### Steps to reproduce
1. Add item Jordan's Weapon Notes.
2. Notice that there is a duplicate page.

Proposed fix: https://github.com/cmangos/classic-db/pull/263/commits/6ff3850caaa67781cccb7176d2021dad07c19e8e

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/c3711ecb6b2350ed8bca0412471cb5c67df6db79
