### ISSUE TITLE
what's wrong with mangosd

### ISSUE THREAD

**Issue by libxengine** [cmangos/issues#2458]
i am try run mangosd:
ubuntu 20.04 x64   wlk3.3.5

[CMaNGOS World server v0.18] id(1) port(8085)

       _____     __  __       _   _  _____  ____   _____ 
      / ____|   |  \/  |     | \ | |/ ____|/ __ \ / ____|
     | |        | \  / |     |  \| | |  __  |  | | (___  
     | |ontinued| |\/| | __ _| . ` | | |_ | |  | |\___ \ 
     | |____    | |  | |/ _` | |\  | |__| | |__| |____) |
      \_____|   |_|  |_| (_| |_| \_|\_____|\____/ \____/ 
      http://cmangos.net\__,_|     Doing emulation right!

Built on May  9 2021 at 18:51:06
Built for Linux_x64 (little-endian)
Using commit hash(Git repository not found) committed on 0000-00-00T00:00:00+00:00
Using configuration file ../etc/mangosd.conf.

<Ctrl-C> to stop.
World Database total connections: 2
MySQL client library: 8.0.23
MySQL server ver: 8.0.23-0ubuntu0.20.04.1 
MySQL client library: 8.0.23
MySQL server ver: 8.0.23-0ubuntu0.20.04.1 
SQL: SELECT required_14033_01_mangos_command FROM db_version LIMIT 1
query ERROR: Unknown column 'required_14033_01_mangos_command' in 'field list'
The table `db_version` in your [WORLD] database indicates that this database is out of date!

  [A] You have: --> `14034_01_mangos_column_fix.sql`

  [B] You need: --> `14033_01_mangos_command.sql`

You must apply all updates after [A] to [B] to use mangos with this database.
These updates are included in the sql/updates folder.
Please read the included [README] in sql/updates for instructions on updating.

**Comment by insunaa** [comment]
Seems like your Database Version is out of sync with your server binary version. Pull the latest of both from github and apply `InstallFullDB.sh` again

**Comment by libxengine** [comment]
for sql_file in $(ls sql/base/dbc/original_data/*.sql); do mysql -uroot -p --database=wotlkmangos < $sql_file ; done

tips:
ERROR 1146 (42S02) at line 29: Table 'wotlkmangos.broadcast_text_locale' doesn't exist

it's does matter?

MoveMapGen.sh: line 98: ./MoveMapGen: cannot execute binary file: Exec format error
what's mean with this error ?

**Comment by libxengine** [comment]
can't ExtractResources,i dont know why...

Welcome to helper script to extract required dataz for MaNGOS!
Should all dataz (dbc, maps, vmaps and mmaps be extracted? (y/n)
y 
How many CPUs should be used for extracting mmaps? (1, 2, 4, 8)
4

MMap extraction can be started delayed
If you do _not_ want MMap Extraction to start delayed, just press return
Else enter number followed by s for seconds, m for minutes, h for hours
Example: "3h" - will start mmap extraction in 3 hours

MMap Extraction Delay (leave blank for direct extraction):


Would you like the extraction of maps to be high-resolution? (y/n)
y

Would you like the extraction of vmaps to be high-resolution? (y/n)
y

Current Settings:
Extract DBCs/maps: 1, Extract vmaps: 1, Extract mmaps: 1, Processes for mmaps: 4
maps extraction will be high-resolution
vmaps extraction will be high-resolution

Press (Enter) to continue, or interrupt with (CTRL+C)

2021年 05月 13日 星期四 20:48:14 CST: Start extracting dataz for MaNGOS
DBC and map files will be extracted
Vmaps will be extracted
Mmaps will be extracted with 4 processes

2021年 05月 13日 星期四 20:48:14 CST: Start extracting dataz for MaNGOS, DBCs/maps 1, vmaps 1, mmaps 1 on 4 processes

2021年 05月 13日 星期四 20:48:14 CST: Start extraction of DBCs and map files...
Map & DBC Extractor
===================

Detected locale: zhCN
Opening ./Data/zhCN/locale-zhCN.MPQ
Opening ./Data/zhCN/patch-zhCN.MPQ
Opening ./Data/zhCN/patch-zhCN-2.MPQ
Detected client build: 13507
Extracting dbc files...
Extracted 245 DBC files

Using locale: zhCN
Opening ./Data/zhCN/locale-zhCN.MPQ
Opening ./Data/zhCN/patch-zhCN.MPQ
Opening ./Data/zhCN/patch-zhCN-2.MPQ
Opening ./Data/common.MPQ
Opening ./Data/common-2.MPQ
Opening ./Data/lichking.MPQ
Opening ./Data/expansion.MPQ
Opening ./Data/patch.MPQ
Opening ./Data/patch-2.MPQ
Extracting camera files...
Extracted 0 camera files
Using locale: zhCN
Opening ./Data/zhCN/locale-zhCN.MPQ
Opening ./Data/zhCN/patch-zhCN.MPQ
Opening ./Data/zhCN/patch-zhCN-2.MPQ
Opening ./Data/common.MPQ
Opening ./Data/common-2.MPQ
Opening ./Data/lichking.MPQ
Opening ./Data/expansion.MPQ
Opening ./Data/patch.MPQ
Opening ./Data/patch-2.MPQ
Extracting maps...
Read Map.dbc file... Fatal error: Invalid Map.dbc file format!
2021年 05月 13日 星期四 20:48:15 CST: Extracting of DBCs and map files finished


2021年 05月 13日 星期四 20:48:15 CST: Start extraction of vmaps...
Extract for VMAPs05. Beginning work ....

Game path: Data/
Found locale 'zhCN'

Adding data files from locale directories.
Scanning patch levels from data directory.
Scanning patch levels from locale directories.
Locale: zhCN

Opening Data/zhCN/locale-zhCN.MPQ
Opening Data/zhCN/expansion-locale-zhCN.MPQ
Opening Data/zhCN/lichking-locale-zhCN.MPQ
Opening Data/common.MPQ
Opening Data/common-2.MPQ
Opening Data/expansion.MPQ
Opening Data/lichking.MPQ
Opening Data/patch.MPQ
Opening Data/patch-2.MPQ
Opening Data/zhCN/patch-zhCN.MPQ
Opening Data/zhCN/patch-zhCN-2.MPQ
Read LiquidType.dbc file...Done! (26 LiqTypes loaded)
Extracting World\wmo\Azeroth\Buildings\OilPlatform\Oilplatform.wmo
Extracting World\wmo\Azeroth\Buildings\Prison_Camp\Prisonhq_New.wmo
Extracting World\wmo\Azeroth\Buildings\Prison_Camp\Prisonlonghouse_New.wmo
Extracting World\wmo\Dungeon\Azjol_Lowercity\Azjol_Lowercity.wmo
Extracting World\wmo\Dungeon\BoreanMagnataurMicro\Boreanmagnataurmicro03.wmo
Extracting World\wmo\Dungeon\CavernsOfTime\Cavernsoftime.wmo
Extracting World\wmo\Dungeon\DrakTharon\Draktharon.wmo
Extracting World\wmo\Dungeon\IceCrown_dungeon\Icecrown_Dungeon.wmo
Extracting World\wmo\Dungeon\IceCrown_dungeon\Icecrown_Dungeon_Exteriormicro.wmo
Segmentation fault (core dumped)
2021年 05月 13日 星期四 20:48:15 CST: Extracting of vmaps finished
mkdir: 无法创建目录 “vmaps”: 文件已存在
2021年 05月 13日 星期四 20:48:15 CST: Start assembling of vmaps...
using Buildings as source directory and writing output to vmaps
Could not read dir_bin file!
exit with errors
2021年 05月 13日 星期四 20:48:15 CST: Assembling of vmaps finished


2021年 05月 13日 星期四 20:48:15 CST: Start creating MoveMaps
Used params: --silent --configInputPath config.json --offMeshInput offmesh.txt
Detailed log can be found in MaNGOSExtractor_detailed.log
Start creating MoveMaps

Be PATIENT - This will take a long time and might also have gaps between visible changes on the console.
WAIT until you are informed that 'creating MoveMaps' is 'finished'!
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 571
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 1
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 0
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 530
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 169
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 619
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 607
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 603
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 531
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 628
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 533
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 631
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 409
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 723
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 509
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 574
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 543
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 545
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 609
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 564
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 30
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 37
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 600
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 560
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 532
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 534
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 604
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 269
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 595
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 650
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 542
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 602
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 553
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 44
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 209
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 309
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 43
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 568
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 554
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 109
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 585
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 529
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 34
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 566
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 389
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 573
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 594
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 469
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 565
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 572
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 658
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 25
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 450
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 615
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 617
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 369
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 616
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 562
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 47
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 230
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 592
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 649
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 349
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 329
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 576
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 582
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 229
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 289
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 489
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 547
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 546
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 724
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 555
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 189
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 559
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 48
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 599
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 552
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 668
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 540
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 35
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 90
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 598
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 129
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 556
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 558
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 550
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 557
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 249
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 70
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 632
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 449
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 601
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 588
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 624
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 544
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 618
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 586
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 608
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 593
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 590
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 591
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 584
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 548
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 42
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 589
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 33
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 578
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 451
'vmaps' directory is empty or does not exist
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 575
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 587
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 596
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 580
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 429
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 36
'vmaps' directory is empty or does not exist
2021年 05月 13日 星期四 20:48:15 CST: (Re)created map 13


2021年 05月 13日 星期四 20:48:15 CST: Finished creating MoveMaps
