### ISSUE TITLE
🐛 [Bug Report] Kodos idle at spawn point

### ISSUE THREAD

**Issue by orygg** [cmangos/issues#2459]
## 🐛 Bugreport

At least one group of kodos remains stationary at its spawn location.

The following query shows, why this is the case:

select id, MovementType from creature where id in (2972, 2973, 2974);

### Expected behavior

The group of kodos should roam (probably along a circular path).

For proof, log into WoW Classic, or look at the maps on wowhead, that indicate circular movement patterns for all three kodo types:

https://classic.wowhead.com/npc=2972/kodo-calf#map
https://classic.wowhead.com/npc=2973/kodo-bull#map
https://classic.wowhead.com/npc=2974/kodo-bull#map

### Version & Environment

Client Version:  3.3.5a
CMaNGOS Repo & Commit Hash: WOTLK 43bddd0fc38d68540bd1c63986c352bc7fef8941
Database Repo & Commit Hash: WOTLK 142e3caf8eaf1d4290b033d90183bda3cb4e07e3

### Steps to reproduce

1. Travel to Mulgore to about -1330, -902.
2. See multiple Kodos idling.

**Comment by Tobschinski** [comment]
![image](https://user-images.githubusercontent.com/4753528/153869998-7a7414fc-d321-4ca8-b947-f29f061d6f01.png)

good chance this one does not spawn during darkmoon faire events

**Comment by al3xc1985** [comment]
Nice...ty
