### ISSUE TITLE
🐛 [Bug Report] Demon Scarred Cloak does not vanish from inventory after quest hand in

### ISSUE THREAD

**Issue by orygg** [cmangos/issues#2461]
## 🐛 Bugreport

Demon Scarred Cloak does not vanish from inventory, when the quest 'The Demon Scarred Cloak' gets finished.

### Expected behavior

Demon Scarred Cloak should vanish from inventory, when the quest 'The Demon Scarred Cloak' gets finished.

### Version & Environment

Client Version: 3.3.5a
CMaNGOS Repo & Commit Hash: WOTLK 43bddd0fc38d68540bd1c63986c352bc7fef8941
Database Repo & Commit Hash: WOTLK 142e3caf8eaf1d4290b033d90183bda3cb4e07e3

### Steps to reproduce

1. Get Demon Scarred Cloak from Ghost Howl with character that did not do the quest yet.
2. Start quest from item.
3. Hand in quest.
4. Notice, that the quest item did not disappear and allows you to open the quest proposition dialog again.

**Comment by nate123456** [comment]
I accepted the quest, completed the objectives, obtained the cloak, turned in the quest, and the cloak does not get removed from the inventory. When right clicking on the item, it states that you cannot take the quest as you already have it.

The `Needs Replication` tag can be removed.

**Comment by killerwife** [comment]
Incorrect, the item is a cloak and stays in inventory on classic so you can keep using it :) Non issue
