### ISSUE TITLE
Paladin "Improved Judgements" talent does not decrease cooldown

### ISSUE THREAD

**Issue by john-redd** [cmangos/issues#2465]
**Current behavior**: 
Judgement cooldowns remain 10 seconds, even with 1 (or 2) points in the "Improved Judgements" talent.

**Expected behavior**: 
Judgement cooldown should be decreased by 1 second for every point put into "Improved Judgements" talent.

**Steps to reproduce**:

1. Put 1 (or 2) points in "Improved Judgements" talent.
2. Cast Judgement spell
3. Attempt recast of Judgement spell right as it is coming off of cooldown.
4. Does not allow recast until the normal 10 second cooldown (instead of the either 8 or 9 second cooldown it should be based on points allocated in "Improved Judgements".

**Client version**: 
3.3.5a

**Commit hash**: 

**Database version**: 
wotlkmangos.db_version.version = WoTLKDB v1.4+ 'WrathGate' for CMaNGOS-WOTLK 14029

**Operating system**: 
Server: Ubuntu 20.04
Client: Windows 10

I know that it is annoying to have new issues opened with no PR, so I've done some poking around trying to get myself familiar with the codebase to see if I could figure it out, but not sure where exactly to look because I am still trying to wrap my head around how the game server/game database/character database interact with each other in regards to talents.

**Comment by killerwife** [comment]
Does it show a decrease in client?
Which judgements, all of them or a specific one you tested.

**Comment by john-redd** [comment]
Judgement of Light and Judgement of Wisdom are the only two I have tested, but I can test others as well if needed.

In the tooltip in the bottom right hand corner it shows the correct cooldown, and the shading timer
 of the ability matches what is displayed on the tooltip, but it remains uncastable (giving the "Spell is not ready yet" message at the center of the screen.)

![Screenshot (2)](https://user-images.githubusercontent.com/54959255/119563339-a2c30080-bd64-11eb-8697-d465d50f1e72.png)
![Screenshot (6)](https://user-images.githubusercontent.com/54959255/119563603-fcc3c600-bd64-11eb-82fe-7d77cbeb6e39.png)
