### ISSUE TITLE
💬 [Support Request]

### ISSUE THREAD

**Issue by lbrock11** [cmangos/issues#2466]
Hey,

I am running through your Detailed instructions, every seems to go fine, except when I Complile with VS (using 2019) I get 2 errors: both are Link1104 errors "Cannot open File 'libboost_date_time-vc142-mt-x64-1_76lib'" and "Cannot open file 'libboost_thread-vc142-mt-x64-1_76.lib". 

I tried moving forward twice but later when it come to running my "mangosd.exe" and Mangosd.conf and realmd.exe and realm.conf files are not in the locations they should and the .exe files haven't been created. 

Could this compilation error be the cause for it? 

  - "3.3.5a" (WOTLK)

If so, how do I get that working correctly?

**Comment by Muehe** [comment]
Hi. This usually happens when you pick the wrong MSVC version for you Visual Studio. According to the errors this is the one you need: https://sourceforge.net/projects/boost/files/boost-binaries/1.76.0/boost_1_76_0-msvc-14.2-64.exe/download

If this doesn't help try using an earlier boost version (but still MSVC 14.2). New version are sometimes a bit buggy.

**Comment by lbrock11** [comment]
I updated to that version but am now getting this error on the Cmake step: 

CMake Error at C:/Users/NAME/Documents/Personal/Samsung/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR system program_options
  thread regex serialization)
Call Stack (most recent call first):
  C:/Users/NAME/Documents/Personal/Samsung/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Users/NAME/Documents/Personal/Samsung/CMake/share/cmake-3.20/Modules/FindBoost.cmake:2344 (find_package_handle_standard_args)
  CMakeLists.txt:215 (find_package)

**Comment by Zelg4dis** [comment]
Hello, did you added the BOOST_ROOT environment variable? 
![Screenshot_1](https://user-images.githubusercontent.com/53647728/120067352-71db1800-c051-11eb-954c-9fbb757557e7.png)

also you can check the CMake to Boost compatibility table here: https://github.com/cmangos/issues/wiki/CMake-to-Boost-Version-Compatibility-Table

also for Boost you have to select a version number not ending in _bX (those are beta versions), and files with MSVC-14.1 in their name is for Visual Studio 2017 and MSVC-14.2 Visual Studio 2019

**Comment by lbrock11** [comment]
Hey,

Yes, I had done that. 

I finally got past that step and figured it out. 

However, I am now to the end. I have got the realmd.exe and mangosd.exe running, did my account creation and am confused by the next step. 

The instructions say:  
After successfully entering these commands you are ready to start the client and log in to the server. Make sure the realmlist.wtf file in the client directory only contains set realmlist 127.0.0.1 before starting. If you want to save addresses of other servers, you can prefix their lines with //, like:

set realmlist 127.0.0.1
//set realmlist someRealmd.somewhere

I do not have a "realmlist.wtf" file. Nor do I have a client to start. Where do I find these? 

![Capture](https://user-images.githubusercontent.com/84997788/120090527-96220d80-c0c0-11eb-8cd6-c5b610c11c01.PNG)

**Comment by nate123456** [comment]
You'd need to download a client through one of the sources out there on the web. A quick search online should do the job. Make sure to search for the right version- 1.12.1 (for classic). The `realmlist.wtf` file will come as part of the client (it's how you point your client to your custom server), it will be in the root of the client folder one you install/extract the client.
