### ISSUE TITLE
🐛 [Bug Report] Corrupted Ashbringer Event not fully working

### ISSUE THREAD

**Issue by bennaber** [cmangos/issues#2467]
## 🐛 Bugreport
With the ongoing Ashbringer Event while a player has equipt the Corrupted Ashbringer, entering the Scarlet Monasery and reaching Scarlet Commander Mograine, the main Event will not be triggert.

### Expected behavior
Normaly a  event should be start where Scarlet Commander starts kneels down and talking to the player:

Scarlet Commander: "You hold my father\'s blade, $N. My soldiers are yours to control, my $g Lord:Lady;. Take them... Lead them... The impure must be purged. They must be cleansed of their taint."

Afther this context, Highlord Mograine walks also into the cathedral and start a conversation with Scarlet Commander Mograine.

Highlord Mograine: "Renault..."
Scarlet Commander Mograine: "Father... But... How?"
Highlord Mograine: "Did you think that your betrayal would be forgotten? Lost in the carefully planned cover up of my death? Blood of my blood, the blade felt your cruelty long after my heart had stopped beating. And in death, I knew what you had done. But now, the chains of Kel\'Thuzad hold me no more. I come to serve justice. I AM ASHBRINGER."
Scarlet Commander Mograine: "Forgive me, father! Please..."

Then Highlord Mograine kills his son by a flash and speaks a last sentance:

Highlord Mograine: "You are forgiven..."

And Highlord Mograine finaly dissapears.

The Database shows the conversation entrys in the following tables:

broadcast_text:
(12473,'You are forgiven...','',0,0,0,1,0,0,0,0,0,0,0,0,31882),
(12472,'Forgive me, father! Please...','',0,0,0,1,0,0,0,0,0,0,0,0,31882),
(12471,'Did you think that your betrayal would be forgotten? Lost in the carefully planned cover up of my death? Blood of my blood, the blade felt your cruelty long after my heart had stopped beating. And in death, I knew what you had done. But now, the chains of Kel\'Thuzad hold me no more. I come to serve justice. I AM ASHBRINGER.\n','',0,0,0,1,0,0,0,0,0,0,0,0,31882),
(12470,'Father... But... How?','',0,0,0,1,0,0,0,0,0,0,0,0,31882),
(12469,'Renault...','',0,0,0,1,0,0,0,0,0,0,0,0,31882)
(12390,'You hold my father\'s blade, $N. My soldiers are yours to control, my $g Lord:Lady;. Take them... Lead them... The impure must be purged. They must be cleansed of their taint.','',0,0,0,1,0,0,0,0,0,0,0,0,31882)

dbscript_string:

(2000005981,'Renault...',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,25,0,'Highlord Mograine - Ashbringer Event Say 1'),
(2000005982,'Father... But... How?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,6,0,'Scarlet Commander Mograine - Ashbringer Event Say 2'),
(2000005983,'Did you think that your betrayal would be forgotten? Lost in the carefully planned cover up of my death? Blood of my blood, the blade felt your cruelty long after my heart had stopped beating. And in death, I knew what you had done. But now, the chains of Kel\'Thuzad hold me no more. I come to serve justice. I AM ASHBRINGER.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,6,0,'Highlord Mograine - Ashbringer Event Say 2'),
(2000005984,'Forgive me, father! Please...',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,20,0,'Scarlet Commander Mograine - Ashbringer Event Say 3'),
(2000005985,'You are forgiven...',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,'Highlord Mograine - Ashbringer Event Say 3')
(2000005980,'You hold my father\'s blade, $n. My soldiers are yours to control, my $g Lord:Lady;. Take them... Lead them... The impure must be purged. They must be cleansed of their taint.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,1,0,'Scarlet Commander Mograine - Ashbringer Event Say 1')

For reference how it should be, see also: 

https://www.youtube.com/watch?v=cp-jhDgbR08 starts @ 1:35

Client Version: 1.12.1

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-classic/tree/df0cfe42872f5c959c8ed079748ec2c8b0f1f429

Database Repo & Commit Hash:https://github.com/cmangos/classic-db/tree/89357fd36b174808e7ca372a13939802b91647e5

Operating System: Client = Windows 10, mangos-classic = debian 10

### Steps to reproduce
1. Equip the Corruptet Ashbringer
2. Walkt into the Cathedral of the Scalert Monasery
3. Reach Scarlet Commander Mograine
4. And nothing happens

**Comment by Grz3s** [comment]
Event works fine in WoTLK ... (sword must be hold in hand before enter instance portal)
CDB & TDB req checking.. if ` Scarlet Commander Mograine` respond on swords aura.

**Comment by bennaber** [comment]
https://coders-area.s3.eu-central-1.amazonaws.com/download/ashbringer-event-stuck.mp4

here you can see what iam talking about.

**Comment by cala** [comment]
Thank you for this report. Fixed by https://github.com/cmangos/classic-db/commit/54cf2b703b263bbbcd8053bb2298384a1ba1788b
