### ISSUE TITLE
🐛 [Bug Report] Some issue of world data.

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2468]
## 🐛 Bugreport
Location problems, falling underground or stuck：

Entry     GUID

- [x]  15274   54934         Falling underground
- [x]  2732     6910           Falling underground
- [x]  2732     6926           Falling underground
- [x]  4692     27980         Falling underground
- [x]  2252     17345         Standing on the fence
- [x]  5405     9530           Incorrect position
- wrong ❌   6272     9002813     Incorrect position (NPC on board, do not use .go cr command, it will crash client) -- we have no 6272 on any transport

Missing patrol paths：

Entry     GUID
- [x]  1907     2630  
- [x]  730       1342 
- [x]  696       2516 -> added in tbc-db from vmangos (cherry-pick)
- [ ]  784       4624 -> Burning Steps (Blackrock Soldier, Area 46)
- [x]  2553     140697 
- [x]  4260      2401 

Other:

Entry     GUID

- [x]  1713     2496     Swimming on land
- [x]  2731     6892     Swimming on land
- [x]  5617     23532   When a creature is killed, the summoned creature will not disappear.

Object: 
- [x]  2560 (loot list Incorrect )

Update 06/05
Game Object :
- wrong ❌   GUID:88296 48637 48639 48793  entry:86492 Incorrect position height -- guids not used in WoTLK
- wrong ❌   GUID:14890 entry:3659 Incorrect position height -- guids not used in WoTLK

### Version & Environment
TBC, WOTLK

CMaNGOS Repo & Commit Hash: 
faef4c1a3f430c48f628b19019c9a84d58c530a2

**Comment by Grz3s** [comment]
`6272     9002813     Incorrect position (NPC on board, do not use .go cr command, it will crash client)`
more info about this one pls... i do not see her spawned anywhere on transports...

**Comment by Grz3s** [comment]
`5617     23532   When a creature is killed, the summoned creature will not disappear.`
he is reseted on his master respawn

**Comment by aleigood** [comment]
> `6272 9002813 Incorrect position (NPC on board, do not use .go cr command, it will crash client)`
> more info about this one pls... i do not see her spawned anywhere on transports...
> ❌ - incorrect - we have only one spawn of 6272....


Entry: 25010    GUID: 9109860 
Entry: 25016    GUID: 9109964

correct position：
![snipaste_20210318_233240](https://user-images.githubusercontent.com/3367999/120886839-8fe0e380-c622-11eb-9476-d0819df4384a.jpg)
![snipaste_20210318_233441](https://user-images.githubusercontent.com/3367999/120886848-97a08800-c622-11eb-8675-a1de91fc0437.jpg)

**Comment by Grz3s** [comment]
youre wrong in both 
(we have sniffed both xyz)
- Entry: 25010
Wowhead:
`By 472214 on 2009/11/17 (Patch 3.2.2)
In the server Velen, he's stuck in a chair. -_-`
check other comments
- Ill correct it only - because this is blizz mistake and it was fixed in later expansions

- Entry: 25016
this one has waypoints .. and we have him sniffed in the middle of it... not static...
will try to find complete patch...

**Comment by Grz3s** [comment]
@aleigood  ... guids (very often) are not the same for TBC and WOTLK...  so some of your reports may ne ok bot one but not for sec DB...
You need to specify which DB youre checking ... otherwise you'll get issues like here:
```code
❌ GUID:88296 48637 48639 48793 entry:86492 Incorrect position height -- guids not used in WoTLK
❌ GUID:14890 entry:3659 Incorrect position height -- guids not used in WoTLK
```
non of these is correct for WoTLKDB

**Comment by AnonXS** [comment]
As there is no clear evidence supporting guid 4624 to be a waypoint path npc, i'll resolve this issue for now as it fixed enough issues.
It's clear to me though that a future rework of "The Pillar of Ash" region of burning steps could be a welcome future project, maybe even involving some spawn_groups/creature_spawn_entry
