### ISSUE TITLE
🐛 [Bug Report] Event Triggers are visible to non-GM Accounts

### ISSUE THREAD

**Issue by shagu** [cmangos/issues#2469]
## 🐛 Bugreport
Event triggers are visible to player accounts:
![cmangos-triggers](https://user-images.githubusercontent.com/11586807/120796157-c5aa9d00-c53a-11eb-8946-f214e34b4a1c.png)

### Expected behavior
Event triggers should be invisible to players.

### Version & Environment
Client:
  - "2.4.3" (TBC) [Fresh client, clean WDB folder]

CMaNGOS Repo & Commit Hash: 
  - https://github.com/cmangos/mangos-tbc/commit/ee05ec5a40afcdac9c912cb647add9ee3ce92a9a

Database Repo & Commit Hash: 
  - https://github.com/cmangos/tbc-db/commit/3c882f4692db938d45a702cd3f3d85965b4280d1

Operating System: 
  - Linux
 
### Steps to reproduce
1. Create non-GM account
2. Move to Zul'Farrak
3. See Area Triggers
4. ...
5. Profit

**Comment by killerwife** [comment]
Please go near them in gm mode and try to check if .gobject nearspawned - command gives any results and paste them here or go near them in gm mode and check what creature they are. Get back to me and i can explain how its possible to fix them :)

**Comment by shagu** [comment]
![image](https://user-images.githubusercontent.com/11586807/120907202-f3d5cd00-c65f-11eb-9589-10dc9b112ac6.png)

```
9000234, Entry 128972 - [Shallow Grave TRAP X:1887.939941 Y:1029.079956 Z:9.147750 MapId:209]
2090034, Entry 128403 - [Shallow Grave X:1887.939941 Y:1029.079956 Z:9.147750 MapId:209]
9000239, Entry 128972 - [Shallow Grave TRAP X:1881.989990 Y:1034.680054 Z:8.876790 MapId:209]
2090037, Entry 128403 - [Shallow Grave X:1881.989990 Y:1034.680054 Z:8.876790 MapId:209]
9000238, Entry 128972 - [Shallow Grave TRAP X:1888.359985 Y:1037.000000 Z:8.921030 MapId:209]
2090036, Entry 128403 - [Shallow Grave X:1888.359985 Y:1037.000000 Z:8.921030 MapId:209]
Found near gameobjects (distance 10.000000): 6 
```

**Comment by killerwife** [comment]
Try this: UPDATE gameobject_template SET data8=1 WHERE entry IN(128972);

**Comment by shagu** [comment]
> Try this: UPDATE gameobject_template SET data8=1 WHERE entry IN(128972);

Thanks, this did the trick. I've opened a PR for it.
