### ISSUE TITLE
Quest spell bug: Death Comes From On High

### ISSUE THREAD

**Issue by firewallzer0** [cmangos/issues#2470]
**Current behavior**: 
While controlling the eye of Acherus if you cancel the spell after the eye has launched your character's new base speed will become the speed of the eye of Acherus. Even using .modify speed 1 does not reset your base speed.

Speed can be reset by taking control of the eye again (.cast 51852) and then clicking the recall button.

[Video](https://youtu.be/ji2FT1M2y38)

**Expected behavior**: 
Character's base speed should remain unchanged when cancelling the spell.

**Steps to reproduce**:

1. Using the cast command: .cast 51852
2. Once the eye is launched cancel the spell by right clicking the spell in the upper right hand corner or by clicking the cancel button above the action bar.

Or

1.  Start quest "Death Comes From On High"
2.  Take control of the eye of Acherus using the control mechanism
3. Wait for the eye to be launched and then cancel the spell.

**Client version**: 
3.3.5 (12340) (Release)

**Commit hash**: 
Commit 4299c4c9b1a2b918f3d49264c1681d0107166f4a

**Database version**: 
World DB:
WoTLKDB v1.5+ 'Arugal's Fate' for CMaNGOS-WOTLK 14034
required_14034_01_mangos_column_fix
Commit 0137436e8c4082af63fd28d3e9fa4bb2884114f8

Character DB:
required_14030_01_characters_item_instance_duration_default

**Operating system**: 
CentOS 7.9 
Kernel: 3.10.0-1160.6.1.el7.x86_64
centos-release-7-9.2009.1.el7.centos.x86_64
Compiled with devtoolset-9 and cmake version 3.17.3

**Comment by Grz3s** [comment]
fixed
