### ISSUE TITLE
🐛 [Bug Report] Hunter Pet flys up in the air after boarding transports

### ISSUE THREAD

**Issue by kelbren** [cmangos/issues#2471]
## 🐛 Bugreport  Pet flys up when boarding transports.

When boarding a ship or Zeplin with a hunter pet, (or playerbot)  it will fly up in the sky and stay there.

### Expected behavior
Pet should stay on the deck.

### Version & Environment
"3.3.5a" (WOTLK)

Operating System - optional
Ubuntu 20.04

### Steps to reproduce
1.  Hunter pet and walk on to ship 
2. After the pet is summoned onto the transport, it will fly up and stay there.

**Comment by kelbren** [comment]
Any ideas on this? Anyone?

**Comment by killerwife** [comment]
I will resolve this after next round of ports to wotlk. I assume this happens only on wotlk?

**Comment by kelbren** [comment]
Yes, in my testing it only happens on wotlk.
Thanks

**Comment by kelbren** [comment]
Fixed
