### ISSUE TITLE
🐛 [Bug Report] - Shaman Spell Nature's Swiftness 

### ISSUE THREAD

**Issue by firewallzer0** [cmangos/issues#2473]
## 🐛 Bugreport
While playing with a Restoration Shaman, I found an issue with the "Nature's  Swiftness" talent point/spell (Spell ID: 16188 for the cast, Spell ID 17116 for the effect). As the spell reads the next spell nature spell cast with a base cast time less than 10 seconds becomes instant. However this effect does not wear off after casting a nature spell and instead stays active until dismissed making almost every nature spell the shaman casts instant. [Demo of bug](https://youtu.be/0VJ3fJZDTEU)

### Expected behavior
After casting nature's swiftness, only the next nature spell should be instant cast per the description of the spell. Then the effect should be dismissed. 

### Version & Environment

Client Version: 
WOTLK - 3.3.5a

CMaNGOS Repo & Commit Hash: 
[WOTLK](https://github.com/cmangos/mangos-wotlk/tree/4299c4c9b1a2b918f3d49264c1681d0107166f4a)

Database Repo & Commit Hash: 
[WOTLK](https://github.com/cmangos/wotlk-db/tree/0137436e8c4082af63fd28d3e9fa4bb2884114f8)

Operating System: 
Linux CentOS 7.9

### Steps to reproduce
1.  Setup a CMaNGOS - WotLK server using the build information above
2. Create a shaman and level them up to at least level 32 spending talent points only in Restoration until you can get the nature's swiftness Talent point.
3. Add the nature's swiftness spell from your restoration spellbook to your hot bar 
4. Cast nature's swiftness spell, followed by any nature spell such as Healing wave
5. Find Bug

### Crashlog

- None

### Additional information:
I originally saw this bug in Feb 2020 and reported it in a longer thread: https://github.com/cmangos/issues/issues/2053
It seems like there are too many bugs reported in that issue so I thought I'd pull one out and I will update the issue with this issues information.

Here is some information from the original post: 

Commit Hash: 3283560886a9dd1aba63d8db49d0fa4fc30dd67a
CMaNGOS Version: CMaNGOS/0.18 (0000-00-00T00:00:00+00:00 - 3283560886a9dd1aba63d8db49d0fa4fc30dd67a) for Linux_x64 (little-endian) Boost version 10.53.0
OS: CentOS 7
CMake Flags: PCH=0 BUILD_PLAYERBOT=1 BUILD_EXTRACTORS=1
Datebase: 5.6.45 MySQL Community Server

**Comment by MantisLord** [comment]
It's being consumed properly on TBC core, so this is a WotLK specific issue.

**Comment by killerwife** [comment]
Happy to report its working correctly after spellmod rework last year on wotlk
