### ISSUE TITLE
🐛 [Bug Report]wands do not work on viscidus and viscidus can't die

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2476]
## 🐛 Bugreport         

![image](https://user-images.githubusercontent.com/71378304/122994620-f0a14780-d3a8-11eb-8701-42ca0a389adf.png) 
only frost spells do viscidus phase. wands should normally do it too. by the way, viscidu does not die once all the Glob of Viscidus are dead.

          
### Expected behavior                      

All frost damage of any kind should work on viscidus, frost wand included, and when the Glob of Viscidus are all dead, viscidus must die immediately.

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:89357fd36b174808e7ca372a13939802b91647e5                      

### Steps to reproduce                           

1. create mage level 60             
2. teleport to AQ 40 
3. add item .add 7514
4. add ranged speed fast .m rangehaste 5000
5. go to .go creature 87938
6. start boss with wand
6. see          
 
### Crashlog       

- None

**Comment by cala** [comment]
Frost wands issue fixed by https://github.com/cmangos/mangos-classic/commit/6a8649ab8c2401ea782a590375f1bbe7485e02c6
