### ISSUE TITLE
🐛 [Bug Report] Mobs in King of the Foulweald event do not attack

### ISSUE THREAD

**Issue by orygg** [cmangos/issues#2480]
## 🐛 Bugreport

The mobs in the King of the Foulweald event do spawn after placing the banner, but do not attack the banner. The quest is still completable (just pull Chief Murgut when he spawns) but not working as it should.

### Expected behavior

The event mobs should attack the banner after spawning.

### Version & Environment

Client Version: 3.3.5a
CMaNGOS Repo & Commit Hash: WOTLK 43bddd0fc38d68540bd1c63986c352bc7fef8941
Database Repo & Commit Hash: WOTLK 142e3caf8eaf1d4290b033d90183bda3cb4e07e3

### Steps to reproduce

1. Get Quest 'King of the Foulweald'
2. Place Banner on Mound
3. Watch spawning mobs not attack
4. ...
5. Profit

**Comment by Nogemard** [comment]
Tbc has same issue

**Comment by AnonXS** [comment]
Closing in favor of old issue with link to more data. https://github.com/cmangos/issues/issues/1980
