### ISSUE TITLE
🚀 [Feature Request] custom script

### ISSUE THREAD

**Issue by firelook** [cmangos/issues#2482]
## 🚀 Feature
replicate the way to do custom script as it is implement in trinitycore

### Visualisation
implement a custom_script_loader.cpp files in which you have : 
`/*
 * This file is part of the TrinityCore Project. See AUTHORS file for Copyright information
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

// This is where scripts' loading functions should be declared:
void AddSC_announce_login();
void AddSC_XpWeekend();
void AddSC_WhoLoggedScripts();
void AddSC_Death_Announcer();
void AddSC_FireWorksOnLevelUp();
void AddSC_CongratsOnLevelScripts();
void AddSC_Boss_Announcer();

// The name of this function should match:
// void Add${NameOfDirectory}Scripts()
void AddCustomScripts()
{
	    AddSC_announce_login();
		AddSC_XpWeekend();
		AddSC_WhoLoggedScripts();
		AddSC_Death_Announcer();
		AddSC_FireWorksOnLevelUp();	
		AddSC_CongratsOnLevelScripts();	
		AddSC_Boss_Announcer();
}
`

### Benefits & Purpose
do not touch the code and grant people to have their own functionality

**Comment by al3xc1985** [comment]
This would be nice cause we can implement external scripts much easier like azeroth core if I am corrext.

What do you think @killerwife ?

**Comment by insunaa** [comment]
Why do you think https://github.com/cmangos/mangos-tbc/blob/master/src/game/AI/ScriptDevAI/system/ScriptLoader.cpp is insufficient for this?

**Comment by al3xc1985** [comment]
So let me understand please, we canbimplemwnt external scrips like azeroth core with that @insunaa ?

**Comment by Niam5** [comment]
Yes. There are comment sections in that file where you define the custome scripts to load, line 10 and line 373. You can make a folder called custom under the ScriptDevAI folder and place the files there then define them in the file mentioned above. You will need to rerun Cmake after you add them so they get picked up.

**Comment by al3xc1985** [comment]
Ty. I guess @killerwife this can be closed. What do you think?

**Comment by killerwife** [comment]
Anyone can add this on their own. I have done this on vengeance, some code is even on my and mantislords personal repos. I do not believe holding peoples hands with custom features is the goal of cmangos.
