### ISSUE TITLE
🐛 [Bug Report]Ribbon Dancing for Midsummer Fire Festival does not work

### ISSUE THREAD

**Issue by MilkmanMHOC** [cmangos/issues#2484]
## 🐛 Bugreport
The Midsummer Fire Festival ribbon dance does not function.  While the pole is present, and your cursor does change to a 'gear' interact symbol, clicking on it does nothing.  It is my understanding(so i have been told) that the script for this has not yet been written for the classic event.

### Expected behavior
The player should be able to click on the pole, and a 'ribbon' will connect them to it.  Once at least 2 players are connected and they 'dance' (actually just running around the pole for a few seconds) they will earn a +30 fire resistance buff that lasts for an hour.  

Some examples of ribbon dance from original 2006 event site
[Ribbon Dance in Stormwind](https://web.archive.org/web/20070627062113mp_/http://www.worldofwarcraft.com/imageviewer.html?/info/events/midsummer/,images/,4,7,http://www.worldofwarcraft.com/info/events/midsummer/)

[Ribbon Dance outside of Darnassus ](https://web.archive.org/web/20070627061920mp_/http://www.worldofwarcraft.com/imageviewer.html?/info/events/midsummer/,images/,7,7,http://www.worldofwarcraft.com/info/events/midsummer/)

[2006 Event Discription fo event](https://web.archive.org/web/20060703092722/http://www.worldofwarcraft.com/info/events/midsummer/)

### Version & Environment
  Client Version -   - "1.12.1" (CLASSIC)
  
Issues seems to be in all recent versions of Classic code base and DB
  
### Steps to reproduce
1. Find ribbon pole at summer festival location
2. Click on pole
3. Nothing happens
4. ...

Extra note, current "Live" classic seems to work/look the same as it did in 2006 if more examples are needed.  TBC changed the the fire festival alot, which is why i assume it has not yet been scripted in classic.

**Comment by killerwife** [comment]
@cala this issue can be resolved by porting the ribbon dance down from tbc. The tbc one has a lot more visuals but the essential idea is the same and it also uses many vanilla spells. One day when you decide to make midsummer work in vanilla, just look at the tbc version for ribbon dance.

**Comment by cala** [comment]
@killerwife to be quite honest, I was sure that ribbon dance was a TBC thing and from my understanding, only the cleansing part of the fire buff spell was missing from Classic. But if you say that more things than that are missing, I will have a look at it, sure.

**Comment by killerwife** [comment]
:D 
![image](https://user-images.githubusercontent.com/7995382/153681053-082c8032-6bdb-4586-9d6f-38c5e1bdbd9f.png)

**Comment by AnonXS** [comment]
Ribbon dance now works
