### ISSUE TITLE
🐛 [Bug Report]Thaddius  won't start

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2486]
## 🐛 Bugreport         
  
once you kill stalag and feugen, the boss thadius does not start and remains unselectable and does not move  

![image](https://user-images.githubusercontent.com/71378304/123495094-90b5d580-d622-11eb-8393-2e7331cf5e2b.png)

          
### Expected behavior                       

normally, once the first two bosses are killed (stalag and feugen) thadius should wake up after 15 seconds   

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:89357fd36b174808e7ca372a13939802b91647e5                       

### Steps to reproduce                           

1. create hero level 60             
2. teleport to naxxramas
3. go to .go creature 88481
4. kill stalagg and feugen  
5. see          
 
### Crashlog       

- None

**Comment by ratkosrb** [comment]
Were you on a GM account and did you use any commands? Because I know that everyone who claimed it does not work in the past was using gm commands which break the encounter. It should work with a proper raid of people on normal accounts.

**Comment by insunaa** [comment]
Thaddius works, I tested it a while ago. You must not kill Stalagg or Feugen with `.die` or excessive damage

**Comment by ClassicW** [comment]
As I said before, I never test a boss by doing a .die, I hit it with a dps that a raid can do. thaddius must become selectable 15 seconds after the 2 bosses are dead. this is not the situation.

**Comment by insunaa** [comment]
The Spell `trigger teslas` only has a 100yd range. If Stalagg and Feugen die further than that, the tesla coils that activate Thaddius will not activate and the fight will be stuck

**Comment by ClassicW** [comment]
I killed it slowly and next to the coil, thaddius has just changed color but is still not selected 
![image](https://user-images.githubusercontent.com/71378304/123560867-3c872e80-d7a5-11eb-88a0-ccb34f4a64bd.png)

**Comment by insunaa** [comment]
try changing the indicated line in the screenshot to what you see in the screenshot. recompile the server and see if it still doesn't work
![image](https://user-images.githubusercontent.com/3718129/123560963-e5358e00-d7a5-11eb-9a50-395a90c01eca.png)

**Comment by ClassicW** [comment]
we have the deploy in pending, after test i return u an feedback about that change.
