### ISSUE TITLE
[Bug Report]maexxna does not launch cocoons

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2490]
## 🐛 Bugreport         
 
maexxna does not cast its "cocoons" spell which should throw some players against the wall and force the distance dps to release them
          
### Expected behavior                       

Ranged damage dealers are of utmost importance during this boss encounter, as they are responsible for killing any cocoons around the edge of the room.
![image](https://user-images.githubusercontent.com/71378304/123545346-cad4c380-d757-11eb-9093-7855b793943d.png)

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:8b930912f749c5272aedf94e140a36844a195a4f                      

### Steps to reproduce                           

1. create hero level 60
2. go to naxxramas
3. go to boss .go creature 88483
4. start boss with another player
5. see
        
 
 
### Crashlog       

- None

**Comment by insunaa** [comment]
Maexxna never casts this on the tank. Did you try this with other players?

**Comment by ClassicW** [comment]
yes, i start boss with another player

**Comment by insunaa** [comment]
I checked SD2 and everything seems to be in order. Either the spell ID for the WEB_WRAP init spell is incorrect, or the database scripting for it is incorrect, but I couldn't find other issues

**Comment by ClassicW** [comment]
not to be confused with this spell
![maexxna](https://user-images.githubusercontent.com/71378304/123651918-25d7ea80-d82c-11eb-9b5c-e3de53b8a611.jpg)

**Comment by insunaa** [comment]
obviously
