### ISSUE TITLE
🐛 [Bug Report]no access to naxxramas via area trigger

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2491]
## 🐛 Bugreport         
 
area trigger to acces naxxramas and acces saphiron. the area trigger is linked to an obsolete quest
![image](https://user-images.githubusercontent.com/71378304/123545929-e7bec600-d75a-11eb-9325-e2b000cca951.png)
                 

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:8b930912f749c5272aedf94e140a36844a195a4f                      

### Steps to reproduce                           

1. create hero level 60
2. go to naxxramas
3. go to 4 end boss 
.go creature 88483 (for maexxna)
.go creature 88480 (for thadduis) 
.go creature 88755 (for 4 horseman) 
and .go creature 88226 (for horreb)
4. kill them all
5. try to access saphiron
        
 
### Crashlog       

- None

**Comment by insunaa** [comment]
The teleport area trigger should be scripted in the Database... Can you look for an areatrigger with this ID in the database and tell me what the query says? (if you end the SQL query in `\G` instead of `;` the query gets printed in a more readable format)

4156 <= area trigger id

**Comment by QUADEMU** [comment]
That quest 9378 is not validated by the effect of spell 28006, in RewardSpellCast for the series of quest 9121||9122||9123.
