### ISSUE TITLE
🐛 [Bug Report]Testing the Vessel quest bug

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2494]
## 🐛 Bugreport         
 
When you want to use the item of quest on a corpse of Muisek, it says invalid target
![image](https://user-images.githubusercontent.com/71378304/123825333-1c6b8280-d8ff-11eb-83e0-4921e1c198ec.png)              
  
### Expected behavior    

 you use the Muisek correctly, it should look like an Arcane Explosion from a mage. All you need to do is ge tclose to the mob, target it (while it's dead) and then Click the Muisek which has a 30 second cooldown.            

### Version & Environment    

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:8b930912f749c5272aedf94e140a36844a195a4f                      

### Steps to reproduce                           

1. create hero level 60
2. add quest 3123
3. go to Hinterlands
4. kill owlbeasts 
5. see
        
 
### Crashlog       

- None

**Comment by MantisLord** [comment]
Tested on latest Classic/TBC cores and it's working.
