### ISSUE TITLE
🐛 [Bug Report]too much distance from the melee.

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2495]
## 🐛 Bugreport   

some creatures like magmadar can reach players in close combat and inversely from much too far. Here the melée distance is 40 meters.   
![magmadar](https://user-images.githubusercontent.com/71378304/124197158-3909e500-dace-11eb-8f16-d87c10269591.png)  

          
### Expected behavior                       

The distance of magmadar in melee should be 10 instead of 40   

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:8b930912f749c5272aedf94e140a36844a195a4f                       

### Steps to reproduce                           

1. create hero level 60  
2. go to molten core  
3. add quest 10193   
4. attack to 40 meter distance  
5. see   
        
 
 
### Crashlog       

- None

**Comment by ClassicW** [comment]
![image](https://user-images.githubusercontent.com/71378304/124367417-44d4e300-dc57-11eb-9e6c-1ea9cb1cd16d.png)

**Comment by QUADEMU** [comment]
Hello, what is your current radius aggro def in conf ?

**Comment by fatalieror** [comment]
+confirm
Also for "The Beast" in UBRS; npc=10430
Hakkar in ZG; npc=14834

The melee range can be fixed by reducing the value of COMBAT_REACH in CREATURE_MODEL_INFO
-> but that doesnt fix that Hunters have to move way back in order for not being "too close"

**Comment by AnonXS** [comment]
Either related to https://github.com/cmangos/issues/issues/2402 or just creature issue

**Comment by killerwife** [comment]
Seems to be resolved ever since I resolved vanilla scaling issues.
