### ISSUE TITLE
🐛 [Bug Report] mangos-wotlk : fishing from 75 up to125 not proposed

### ISSUE THREAD

**Issue by firelook** [cmangos/issues#2498]
## 🐛 Bugreport
I am doing fishing, I am at Stormwind and level 75, I go to see "Arnold Leland" but he has nothing to teach me from 75 to 125 which is next proposition .
![2021-07-06_18-08-07](https://user-images.githubusercontent.com/3873193/124701264-8e8b2b00-deee-11eb-84c5-2d1e1e55cbe2.png)
P.S. Pêcher means Fishing
P.S.2 I have give  "Arnold Leland" but it is the same for other trainers in the allaiance that I have tested

### Expected behavior
should propose this option in the list

### Version & Environment
  - "3.3.5a" (WOTLK)

Client Version: 

  - [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/93c4e78 commit 93c4e784ed035dae35ca9d922fafc78b431eae85)

  - [WOTLK](https://github.com/cmangos/wotlk-db/tree/91f7fc5 commit 91f7fc5dab994dd9390ea5c88e67835a174e96f7)

**Comment by QUADEMU** [comment]
Hello frenchie, can you check if the SQL Command "SELECT 1 FROM npc_trainer WHERE entry=5493 AND spell=7734;" return you 1 for result.

**Comment by firelook** [comment]
N/a is the answer but I have the same if I take entry=5493 or spell=7734

**Comment by QUADEMU** [comment]
it's normal the entry is missing, under 1.1.2 the record exist, so exclusion to any mod between the extensions, you can consider to apply that one:
 `INSERT INTO `npc_trainer` (`entry`, `spell`, `spellcost`, `reqskill`, `reqskillvalue`, `reqlevel`, `condition_id`) VALUES (5493, 7734, 500, 356, 50, 0, 0);
` & restart

**Comment by firelook** [comment]
something else is missing, because the trainer doesn't do anything else

**Comment by QUADEMU** [comment]
Initially what did you have at entry 5493 for spell definition in npc_trainer?

**Comment by aleigood** [comment]
May be relevant: https://github.com/cmangos/issues/issues/2438

**Comment by firelook** [comment]
I am using official DB for mangos 3.3.5

**Comment by QUADEMU** [comment]
> I am using official DB for mangos 3.3.5
> So like everybody (I hope)
> ![2021-07-08_17-25-28](https://user-images.githubusercontent.com/3873193/124949170-9db6c980-e011-11eb-867e-d145ba6fbeda.png)
That one is the result of the REPLACE request wrote previously, 
> N/a is the answer but I have the same if I take "only" entry=5493 or spell=7734

Anyway after restart you still don't find the journeyman fishing in the NPC Arnold ?

**Comment by firelook** [comment]
I should have the same db like everybody, I am using the standard one, so anybody has not the same problem like me?

**Comment by firelook** [comment]
I look at the sql table and try to compare with mangos thrre , and it seems it is the same data, so I suspect it is linked to the code who do not provide the next training at level 50 of skill

**Comment by firelook** [comment]
and it is linked I suppose to "May be relevant: #[2438](https://github.com/cmangos/issues/issues/2438)"
We should not have 2 professions but one
![2021-07-12_09-00-44](https://user-images.githubusercontent.com/3873193/125244618-d398ce00-e2ef-11eb-8a2e-d754407ec965.png)

**Comment by AnonXS** [comment]
```
-- vanilla
SELECT * FROM npc_trainer WHERE entry=5493;

-- tbc
SELECT * FROM npc_trainer_template WHERE entry=1120;

-- wotlk
SELECT * FROM npc_trainer_template WHERE entry=2000;
```

**Comment by firelook** [comment]
I do not think it is linked to the sql , because you have 2 icons, but below the answer 
![2021-07-12_12-50-07](https://user-images.githubusercontent.com/3873193/125275790-be339c00-e30f-11eb-85c2-d169e9ad05b9.png)

**Comment by CorzaHorizon** [comment]
same issue

I learned Journeyman Fishing from the trainer npc.
The fishing skill max point does not expand to 150.

**Comment by killerwife** [comment]
Retested learning, seems to have been fixed by the recent fishing stacking fix.
