### ISSUE TITLE
🐛 [Bug Report]Stitches don't spawn

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2502]
## 🐛 Bugreport   

when you finish the Translate Abercrombie's Note quest, Stitches does not spawn and only the npc text appears

### Expected behavior                       

when you finish the Translate Abercrombie's Note quest, Stitches must spawn and attack darkshire.
![image](https://user-images.githubusercontent.com/71378304/125450593-48c70f8b-ed2f-4ae0-9bd9-b853f5a299e3.png)
### Version & Environment                  
 
Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:57de26dc7ee98066e1f28ddc31d5a8068c6430f6                   

### Steps to reproduce                           

1. create hero level 30
2. go to darkshire
3. take quest=251/translate-abercrombies-note and complete it
4. see  
        
 
### Crashlog       

- None

**Comment by cala** [comment]
Unfortunately, you are wrong. You have to progress further in the quest line before Stitches is summoned and I've tested this right now: this is working.
Closing this issue then.
