### ISSUE TITLE
🐛 [Bug Report] Database - Missing Pooling for Balgaras the Foul 1364 - 3 spawn locations minimum

### ISSUE THREAD

**Issue by AnonXS** [cmangos/issues#2504]
## 🐛 Bugreport

Missing Pooling for Balgaras the Foul 1364 - 3 spawn locations minimum

https://classic.wowhead.com/npc=1364/balgaras-the-foul#comments

spawnloc(s) in dun modr missing - i suspect one in pretty much every house from memory

spawnloc 2 in direforge hill <https://youtu.be/YQKCVlv5T-0?t=271>

spawnloc 1 in direforge hill (existant, with slight movement)
[15] Position: X: -2931.105, -2973.809, 30.6708, 5.282537

[7] Position: X: -2931.6973, -2973.4238, 30.670797, 2.682606935501098632

[13] Position: X: -2931.9473, -2973.8027, 30.670797, 4.179512977600097656

Client Version: 
All

Database Repo & Commit Hash: hash(720b20c213950f660be8d71e9af267ae45180a95)

### Steps to reproduce
1. .go c id 1364
2. there is only guid 10043
3. should be more
4. look at sniff and dont find the other locations...
5. @Tobschinski pretty please

**Comment by Tobschinski** [comment]
Never been to that place, so I could not sniff it and I don't have a working one right now so...

**Comment by Tobschinski** [comment]
Can't seem to get him spawn in any of the other places in TBC, maybe this is classic-only.

**Comment by killerwife** [comment]
Been hunting the guy on SoM. So far I saw rightmost camp and middle camp spawn. I will report as I find out more, once I have an idea where he can be ill try to sniff or at least approximate. He had random movement.

![image](https://user-images.githubusercontent.com/7995382/153609562-002d8a94-5a0b-454a-b683-8f911a9cc9d3.png)

**Comment by Tobschinski** [comment]
Think I have 2 spawns in the keep itself somewhere..
