### ISSUE TITLE
🐛 [Bug Report]Chest spawn in use

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2507]
## 🐛 Bugreport   

Sometimes, some chest appears in use when nobody is using it.
![image](https://user-images.githubusercontent.com/71378304/127934973-8f967107-5655-4079-a34f-40804d4580b1.png)

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:57de26dc7ee98066e1f28ddc31d5a8068c6430f6             

### Steps to reproduce                           

1. create hero  
2. go to chest position (exemple =.go -10104.99 -2334.62 29.39)
3. see  
        
### Crashlog       

- None

**Comment by AnonXS** [comment]
duplicate https://github.com/cmangos/issues/issues/2576
