### ISSUE TITLE
🐛 [Bug Report] [Classic] Paladin spell Divine Protection can be cast when Forbearance is active

### ISSUE THREAD

**Issue by vdeschuy** [cmangos/issues#2509]
## 🐛 Bugreport 
Paladin spell Divine Protection can be cast when Forbearance is active. Spell has no effect but costs mana and cooldown starts running.

### Expected behavior
Using Divine Protection, Divine Shield, Hand of Protection or Lay on Hands will afflict the protected character with the Forbearance debuff, which prevents any four of those abilities from being used again while it is active.
You should get an error message when trying to cast Divine Protection when Forbearance is active.

### Version & Environment
Client Version: 1.12.1 (CLASSIC)

CMaNGOS Repo & Commit Hash:   
https://github.com/cmangos/mangos-classic/tree/669a90188cb587a80807d611dea25ffa947c405c

Database Repo & Commit Hash: 
https://github.com/cmangos/classic-db/tree/31fca2e6e6a116927fe3edd79350aad8d64c7345

Operating System: Windows 10

### Steps to reproduce
1. Create a paladin of at least level 10.
2. Learn Divine Protection and Blessing of Protection.
3. First cast Blessing of Protection, then immediately cast Divine Protection.
4. Profit

**Comment by AnonXS** [comment]
Can't reproduce in tbc.

**Comment by vdeschuy** [comment]
> Can't reproduce in tbc.

Yes, tested this is in TBC as well and there it works as intended. Found out it is bugged on classic though.

**Comment by killerwife** [comment]
Pushed commit that should resolve this, retest.

**Comment by vdeschuy** [comment]
> Pushed commit that should resolve this, retest.

Works for me on classic now! Thanks! 👍
