### ISSUE TITLE
🐛 [Bug Report] warlock summoning Voidwalker when you are from the horde

### ISSUE THREAD

**Issue by firelook** [cmangos/issues#2510]
## 🐛 Bugreport
doing the quest Horde Voidwalker Quest Walkthroughs
=> going to the purple circle and using Runes of Summoning
=> it sayed incorrect target

### Expected behavior
generating a voidlwalkers

### Version & Environment

Client Version: 
 latest

P.S.
and it is the same for succubus (horde side)

**Comment by killerwife** [comment]
Please specify which patch this is on :)

**Comment by ssj17vegeta** [comment]
Can confirm the same behaviour on latest WOTLK Cmangos.

**Comment by ssj17vegeta** [comment]
Not sure if related, but spell 34387 shows the exact same behaviour (detonating portal in Hellfire peninsula quest 10208 "Disrupt Their Reinforcements") :

- Spell starts casting.
- Once cast bar is completely filled, "incorrect target".

**Comment by AnonXS** [comment]
no other quest, and related to gameobject as target, it works though if you click the cube i think its some LOS issue or something

**Comment by AnonXS** [comment]
https://github.com/cmangos/wotlk-db/commit/f78fbb1f1123a5851ea3556895e65fce5bc52caa
