### ISSUE TITLE
🐛 [Bug Report] TBC database install error

### ISSUE THREAD

**Issue by Patrick-Barry** [cmangos/issues#2512]
## 🐛 Bugreport
When building the TBC database I get the following error: 
ERROR 1062 (23000) at line 2146: Duplicate entry '15127' for key 'spell_template.PRIMARY'
ERROR: cannot apply ../mangos/sql/base/dbc/cmangos_fixes/Spell.sql

I got this error both when updating the database as well as freshly creating it.

### Expected behavior
Database should install correctly

### Version & Environment
Client Version:  2.4.3

CMaNGOS Repo & Commit Hash: TBC 3b74a513b0156bfaa41e5ae16232b1945e40f2bb
Database Repo & Commit Hash: TBC DB 4adadc0b3bbf703f86a8aaaf39500fe1f86374a6

Operating System:  Windows 10

### Steps to reproduce
1. Run  ./InstallFullDB.sh from  tbc-db directory
2. Profit

### Crashlog

- None

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/blob/master/sql/base/dbc/cmangos_fixes/Spell.sql#L2111

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/21e19d66cf48db0e891e0031c2d8ff27bd9ff5f9
