### ISSUE TITLE
🐛 [Bug Report][Classic] Creature Greater Fleshripper has 100% dropchance for Blindweed

### ISSUE THREAD

**Issue by vdeschuy** [cmangos/issues#2515]
## 🐛 Bugreport

Creature Greater Fleshripper has 100% dropchance for Blindweed.

### Expected behavior

Greater Fleshripper should not be dropping Blindweed.

### Version & Environment

Client Version: "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: 
[CLASSIC](https://github.com/cmangos/mangos-classic/tree/e65398a62f11ed9ac19adebf25d6a0708a4508f3)

Database Repo & Commit Hash: 
[CLASSIC](https://github.com/cmangos/classic-db/commit/60bca95630f0d66e6359f7a35d6328173fef3f24)

Operating System: Windows 10

### Steps to reproduce

1. Kill creature Greater Fleshripper
2. Observe 100% dropchance for Blindweed

**Comment by vdeschuy** [comment]
Suggested fix: https://github.com/cmangos/classic-db/pull/267

**Comment by cala** [comment]
FIxed in https://github.com/cmangos/classic-db/commit/89808a4a49262fdcf7f912c8e9ccfeda44cf4097.
Thank you.
