### ISSUE TITLE
🐛 [Bug Report] Crash when walking into campfires

### ISSUE THREAD

**Issue by vanillawowexplore** [cmangos/issues#2535]
## 🐛 Bugreport
Just walk into a campfire, any should work. Example, there is one by the vendors at sentinel hill.

### Expected behavior
Should take fire damage.

### Version & Environment
Client Version:  "1.12.1" (CLASSIC)

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-classic/tree/f13a81b7b940869abe62ab3a441796a9e9f04c2e

Database Repo & Commit Hash: https://github.com/cmangos/classic-db/tree/60bca95630f0d66e6359f7a35d6328173fef3f24

Operating System: Win 10

### Steps to reproduce
1. Find a campfire, Example, the one by the vendors at sentinel hill.
2. Dive in.
3.
4. ...
5. Profit

### Crashlog
- I'm unsure about the crash log, but I was able to debug enough to find the line it crashed on: https://github.com/cmangos/mangos-classic/blob/master/src/game/Spells/Spell.cpp#L268

### Potential fix:
- I looked at the same line in TBC and it looks like a fix was applied recently that seems to fix this issue in vanilla: https://github.com/cmangos/mangos-tbc/commit/98dd18f788315b0cf1690f2a860e9defe5970997

**Comment by killerwife** [comment]
Tested and seems fixed now.
