### ISSUE TITLE
controlled by spell(46427)，server crash again

### ISSUE THREAD

**Issue by solo0755** [cmangos/issues#2536]
## 🐛 Bugreport
When I killed  boss_felmyst，server crash

### Expected behavior
just killed  boss_felmyst，server crash

### Version & Environment
Client Version:  "2.4.3" (TBC)

  Commit Hash -   CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/tree/2c41a12ce73eea622ed8f6b50961517dbc44ea5e

WIN10

Operating System: 

### Steps to reproduce
just killed  boss_felmyst，server crash

### Crashlog
debug point is at "void SpawnManager::RespawnCreature": line 63
Exception:"vector erase iterator outside range"
- None

**Comment by killerwife** [comment]
In order to help, I need a full stack trace if possible.

**Comment by killerwife** [comment]
Try latest commmit. Should be resolved.

**Comment by insunaa** [comment]
Can confirm is fixed with the latest commit. The waypoints for Kalecgos after defeating Felmyst seem a bit off, tho. He flies through the building and lands below ground and then casts his ice breath

**Comment by solo0755** [comment]
Good job！！！，but another issue，the same problem，the same debug point。
Through the long corridor，keep moveing to kill the creature，When I was  controlled by spell （id：46427），server crash again。
“Exception:"vector erase iterator outside range"

there is the full stack：

 	ucrtbased.dll!00007ffad38f7fbc()	
 	ucrtbased.dll!00007ffad38f7ef4()	
 	ucrtbased.dll!00007ffad38f7d90()	
 	mangosd.exe!std::vector<SpawnInfo,std::allocator<SpawnInfo>>::erase(std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<SpawnInfo>>> _Where) line 1347	C++
>	mangosd.exe!SpawnManager::RespawnCreature(unsigned int dbguid, unsigned int respawnDelay) line 63	C++
 	mangosd.exe!CreatureLinkingHolder::DoCreatureLinkingEvent(CreatureLinkingEvent eventType, Creature * pSource, Unit * pEnemy) line 484	C++
 	mangosd.exe!Unit::TriggerEvadeEvents() line 558	C++
 	mangosd.exe!UnitAI::EnterEvadeMode() line 107	C++
 	mangosd.exe!CreatureEventAI::EnterEvadeMode() line 1495	C++
 	mangosd.exe!Unit::SelectHostileTarget() line 9152	C++
 	mangosd.exe!CreatureEventAI::UpdateAI(const unsigned int diff) line 1700	C++
 	mangosd.exe!Unit::Update(const unsigned int diff) line 533	C++
 	mangosd.exe!Creature::Update(const unsigned int diff) line 771	C++
 	mangosd.exe!Map::Update(const unsigned int & t_diff) line 786	C++
 	mangosd.exe!DungeonMap::Update(const unsigned int & t_diff) line 1705	C++
 	mangosd.exe!MapUpdateWorker::execute() line 53	C++
 	mangosd.exe!MapUpdater::WorkerThread() line 98	C++

**Comment by solo0755** [comment]
> Try latest commmit. Should be resolved.

by the way . i just

**Comment by solo0755** [comment]
fix by commit  e7e46555cc51e07a460693df5c92c50cdee54bf0
