### ISSUE TITLE
🐛 [Bug Report] Wotlk Database creation error

### ISSUE THREAD

**Issue by Patrick-Barry** [cmangos/issues#2538]
## 🐛 Bugreport
When creating a fresh Wotlk database using the mangos.sql in the sql/base directory the following error is given:

ERROR 1136 (21S01) at line 1457: Column count doesn't match value count at row 1

### Expected behavior
Database should be created without errors.

### Version & Environment

Client Version: 3.3.5a 

CMaNGOS Repo & Commit Hash: Wotlk 1d8a6861c7b44888379c8148c79b6d23b1865908
Database Repo & Commit Hash: Wotlk 98c05a08c02dd5aef8ec12e679e5553762cd3303
Operating System:  Win 10

### Steps to reproduce
1. Create the empty database
2. Try to run the sql/base/mangos.sql to populate it

### Crashlog

- None

**Comment by AnonXS** [comment]
@killerwife

**Comment by killerwife** [comment]
This should now be solved.
