### ISSUE TITLE
🐛 [Bug Report] Quest 'A Lesson in Fear' not working

### ISSUE THREAD

**Issue by SuperSmelly** [cmangos/issues#2540]
## 🐛 Bugreport
When planting the flag in the corpses of the 3 mobs, no credit is given for the quest 'A lesson in Fear' Howling Fjord

### Expected behavior
Quest credit should be given once the banner is planted in the corpse.

There are entries in creature_ai_scripts for the three mobs (24016,24161,24162) that should work based on what i can see in the wiki for that table. but it doe snot seem to

### Version & Environment

Client Version: 

  - [WOTLK](https://github.com/cmangos/mangos-wotlk/tree/1d8a6861c7b44888379c8148c79b6d23b1865908

-->
CMaNGOS Repo & Commit Hash: 

  - [WOTLK](https://github.com/cmangos/wotlk-db/tree/354cf37f3efd80cc6bf962135517b58428b0c430

-->
Database Repo & Commit Hash: 

Operating System: 

### Steps to reproduce
1. - Take the quest from Sergeant Gorth                                                                                      
2. -  Kill mobs until named mobs appear then kill them
3. - Plant the banner
4. ... No quest credit
5. Profit

### Crashlog

- None

**Comment by MantisLord** [comment]
It seems to be fixed now. Credit for the quest is awarded properly. You do have to target the corpses when using the Forsaken Banner for it to work.
Also, there aren't really enough Winterskorn Defenders to guarantee you get all 3 hero quest objectives to spawn, but I think this is normal/blizzlike.
