### ISSUE TITLE
🐛 [Bug Report] Enable Anticheat will crash server

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2542]
## 🐛 Bugreport

Set "enable = 1"  in the file "antichat.conf", the server will crash and restart as soon as player login to the server

### Version & Environment
"2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 
11415335582aab8e357b5d199947f804247cd617

Database Repo & Commit Hash: 
f60e5eb95db6dde2e8201cb0363d95e7c6b20046

Operating System: 
CentOS 7.6

### Steps to reproduce
1. clean compile and reset database
2. rename anticheat.conf.dist to anticheat.conf
3. modify enable=1
4. run server
5. Profit

**Comment by ckj777** [comment]
Copy the "warden_modules" folder to your server directory

**Comment by insunaa** [comment]
https://github.com/cmangos/mangos-tbc/pull/480
