### ISSUE TITLE
🐛 [Bug Report] Wotlk - Mage spell "Mirror Image" creates clones that are only level 1

### ISSUE THREAD

**Issue by Patrick-Barry** [cmangos/issues#2545]
## 🐛 Bugreport
When using the mage spell "Mirror Image" the clones created are only level 1 with 13 hp.  Deathknight blood worms talent also suffer from this issue so it may be related.

### Expected behavior

From what I can recall the level of the copies should be the same as your character.

Client Version: 3.3.5a

CMaNGOS Repo & Commit Hash: Wotlk 67d01de4c04bc69a81c1a462b2f49a90eb86abae
Database Repo & Commit Hash: Wotlk b2e13071fa13a6704516c8da79941885338199ab

Operating System: Windows 10

### Steps to reproduce
1. Take a level 80 mage and cast Mirror Image.

### Crashlog

- None

**Comment by killerwife** [comment]
Resolved
