### ISSUE TITLE
🐛 [Bug Report] NPCs does not have/show their equipment

### ISSUE THREAD

**Issue by cala** [cmangos/issues#2549]
## 🐛 Bugreport
NPCs with (supposely) unsheathed weapons/objects are displayed as barehand in game. When engaging combat, they are still fighting as barehand.

### Expected behavior
Equipment set in database should be displayed accordingly to the sheath status of each NPC and used/displayed when fighting.

### Version & Environment
  Client Version 
  - "1.12.1" (CLASSIC)

Client Version: 
- Mac Client v 1.12.1

CMaNGOS Repo & Commit Hash: 
  - [CLASSIC](https://github.com/cmangos/mangos-classic/commit/db94046d27c8d2283a4b4d87291b53e5184c7b24)

  Database Version
  - [CLASSIC](https://github.com/cmangos/classic-db/commit/89808a4a49262fdcf7f912c8e9ccfeda44cf4097)
 
  Operating System
  - macOS
 
### Steps to reproduce
1. With a horde character : `.tele stormwind`
2. Attack any guard
3. See they are fighting barehand instead of with sword and shield

### Crashlog
- None

**Comment by killerwife** [comment]
classic official
![image](https://user-images.githubusercontent.com/7995382/132957670-c4d258eb-351d-49fa-a324-fc8c0940c86b.png)
tbc core
![image](https://user-images.githubusercontent.com/7995382/132957700-4b6e3f9f-13ec-4a1b-aed3-f496b6bdc3e7.png)
vanilla core
![image](https://user-images.githubusercontent.com/7995382/132957703-4eb09246-7077-4086-81fe-eab25509a4d6.png)

**Comment by killerwife** [comment]
![image](https://user-images.githubusercontent.com/7995382/132957971-1610193c-2ac6-4ec5-bb1e-32b129aede03.png)
fixed
