### ISSUE TITLE
remove check for PREFIX in CMakeLists.txt

### ISSUE THREAD

**Issue by DasBlub** [cmangos/issues#255]
since https://github.com/cmangos/mangos-wotlk/commit/d489531fa028b5da09879fe738cf33ebe10d5d50 we have a check in place to inform users that they can no longer use the PREFIX parameter and instead should use CMAKE_INSTALL_PREFIX. this check should be removed sometimes in 2014. it should stay in there until then to make sure that everyone gets the message but it should be removed at some point to get rid of this legacy code.

this issue is just here as a reminder that this has to be done at some point.

**Comment by cyberium** [comment]
Ok got it.
