### ISSUE TITLE
🐛 [Bug Report] Area 52, Spotlight Spell triggered on false position [TBC-core]

### ISSUE THREAD

**Issue by Lhalyna** [cmangos/issues#2551]
## 🐛 Bugreport - Area 52, Spotlight Spell triggered on false position [TBC-core]

the area 52 spotlight spell triggered on false position, it must triggered in the middle of the entrance on any side. not before or behind

actual:
![WoWScrnShot_091121_213035](https://user-images.githubusercontent.com/26441174/132959359-1a2c6f03-40d9-49af-b74e-cfb916c77689.jpg)

right:
![WoWScrnShot_091121_213051](https://user-images.githubusercontent.com/26441174/132959371-9a87653c-c31a-4ba4-86d6-e1d2fc42c5ae.jpg)

**Comment by killerwife** [comment]
Closed in https://github.com/cmangos/mangos-tbc/commit/11184023b8ad1763d5a7215c49b92296fe342cca
