### ISSUE TITLE
🐛 [Bug Report] - Draenei - Visible Skill: Heroic Presence 6562 [TBC-core]

### ISSUE THREAD

**Issue by SabriynaVermillion** [cmangos/issues#2552]
## 🐛 Bugreport - Draenei - Skill - Heroic Presence 6562 [TBC-core]

passive skill heroic presence displayed incorrectly, skill not needs to be visible

**cmangos actual:**
![WoWScrnShot_091221_012017](https://user-images.githubusercontent.com/26441174/132965902-c38763de-8a2a-44e8-a150-51b2e2838007.jpg)

**Official World of Warcraft - Classic - TBC:**
![WoWScrnShot_091221_012128](https://user-images.githubusercontent.com/26441174/132965917-1d1f036c-909a-4ea2-8fa7-a7e3b6833629.jpg)

**Comment by AnonXS** [comment]
commit: `Make SPELL_EFFECT_APPLY_AREA_AURA_PARTY show up to unit casters even when passive`

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/ea94ab0ef9710f43643e87e282fbef77757c3b4f
