### ISSUE TITLE
🐛 [Bug Report] quest cleansing-the-scar

### ISSUE THREAD

**Issue by firelook** [cmangos/issues#2554]
## 🐛 Bugreport
casting power word on the 6 ranges does nothing for the quest [cleansing-the-scar](https://tbc.wowhead.com/quest=9489/cleansing-the-scar)

**Comment by kelbren** [comment]
Tested with WotLK and works correctly. I did not test with TBC

**Comment by firelook** [comment]
Quite strange, priest from the horde at the position 50.50, and I on each of the 6 fellows and the counter did not increase at all

**Comment by MantisLord** [comment]
Tested on both TBC and WotLK and it's working for me. Please reopen if issue persists on latest core and you can provide more info.

**Comment by skelUA** [comment]
Not working on 3.3.5. When cast on creature - nothing happened
