### ISSUE TITLE
🐛 [Bug Report]Paladin born spell 'Seal of Righteousness' is wrong and spell 'Judgement' required level is wrong

### ISSUE THREAD

**Issue by Cnzjs** [cmangos/issues#2555]
the spellid shold be 21084,not 20154.
the spell 20154 can not use 'Judgement' to unleash.

the paladin trainer require 'Judgement' at level 10,this should be level 4.

### Version & Environment
Client Version: 
TBC
CMaNGOS Repo & Commit Hash: 
Newest
Database Repo & Commit Hash: 
Newest

**Comment by killerwife** [comment]
There are two different spells. One is learned on lvl 1 and one is gained through a quest and replaces the first spell. @Warlockbugs

**Comment by Cnzjs** [comment]
Oh,OK,sorry I never played a paladin didn't know this,sorry.

**Comment by killerwife** [comment]
Closing this.
