### ISSUE TITLE
🐛 [Bug Report] equipement unmovable

### ISSUE THREAD

**Issue by firelook** [cmangos/issues#2558]
## 🐛 Bugreport
latest version https://github.com/cmangos/mangos-tbc/commit/d04257ad4bed268338e3d1d4d9323b1ea108c315
can not unequip  items => it sayed you are stuned

**Comment by Salaciaa** [comment]
i have this bug too it seems to happen after you open game client and login but also affects equipping items and i think using the flight masters too it says your busy. 

A work around i found to work is clicking logout then enter game again seems to temporally fix issue

**Comment by insunaa** [comment]
Apparently the hunter spell Misdirect is also affected, I'll have to investigate that one further

**Comment by firelook** [comment]
any progress please ?

**Comment by firelook** [comment]
Also I suspect you have the same problem with trading : 
below a way to easily create this glitch:
1/ a Fellow A do a research on the Auction House
2/ a Fellow B try to trade with him => refused obvsiouly due to the fact a trade is allready happening
3/ Fellow A leave the Auction House
4/ Fellow B try to trade with Fellow A and now you have an error
Fellow B can not trade any more with nobody
