### ISSUE TITLE
🐛 [Bug Report]Lady Jaina shoudn't be talkable after BOSS Azgalor in Hyjal.

### ISSUE THREAD

**Issue by Cnzjs** [cmangos/issues#2562]
## 🐛 Bugreport
After you kill BOSS Azgalor and talk to Thrall.Jaina will spawn and do a mass teleport spell.
Now you can talk to her and there is a gossip menu option to click(of course nothing happens when you click).
This is wrong I think.
Either she is untalkable or there should be none gossip menu option may be right.
Sorry for my poor English.

![WoWScrnShot_092821_160704_看图王_看图王](https://user-images.githubusercontent.com/34866054/135050958-b73e2fd0-289e-47a4-ba27-f2d9b8b41f1a.jpg)

### Version & Environment
2.4.3
Client Version: 
2.4.3
CMaNGOS Repo & Commit Hash: 

Database Repo & Commit Hash: 
newest

**Comment by Cnzjs** [comment]
I figured how to fix this:
\src\game\AI\ScriptDevAI\scripts\kalimdor\caverns_of_time\hyjal\hyjal.cpp
search for:
`                thrall->SummonCreature(NPC_JAINA, 5486.305f, -2777.72f, 1496.687f, 1.082104f, TEMPSPAWN_TIMED_OR_DEAD_DESPAWN, 120000, true, false, 2);
                thrall->SummonCreature(NPC_ALLIANCE_KNIGHT, 5489.709f, -2781.63f, 1497.728f, 1.32645f, TEMPSPAWN_TIMED_OR_DEAD_DESPAWN, 120000);
                thrall->SummonCreature(NPC_ALLIANCE_KNIGHT, 5480.393f, -2778.908f, 1497.069f, 1.047198f, TEMPSPAWN_TIMED_OR_DEAD_DESPAWN, 120000);
`
add these 2 lines after:
`				Creature* jaina = GetSingleCreatureFromStorage(NPC_JAINA);
				jaina->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
`

**Comment by MantisLord** [comment]
I believe it's correct for both Jaina and Thrall to retain their gossip flags during the mass teleport as weird as it seems - this is what happens on retail.

**Comment by AnonXS** [comment]
```
ClientToServer: CMSG_GOSSIP_SELECT_OPTION (0x3493) Length: 23 ConnIdx: 25 Time: 08/26/2017 18:54:13.754 Number: 32400
GossipUnit: Full: 0x2016F442C0115B00006A07000021A7A0 Creature/0 R1469/S27143 Map: 534 Entry: 17772 Low: 2205600
GossipID: 7552
GossipIndex: 2
PromotionCode: 

ClientToServer: CMSG_CLOSE_INTERACTION (0x3492) Length: 14 ConnIdx: 16 Time: 08/26/2017 18:54:14.035 Number: 32461
Guid: Full: 0x2016F442C0115B00006A07000021A7A0 Creature/0 R1469/S27143 Map: 534 Entry: 17772 Low: 2205600
```
No change in gossip flags.
