### ISSUE TITLE
Hunter and Warlock pets stamina bug

### ISSUE THREAD

**Issue by Erikbmd** [cmangos/issues#2566]
After the level up the pets will get huge stamina boost. If you dismiss them stamina goes back to normal.

**Comment by Erikbmd** [comment]
Since i couldn't upload the video here i did upload it on youtube to give the most information and how to replicate https://www.youtube.com/watch?v=z7XD57SSdpk

**Comment by AnonXS** [comment]
https://github.com/cmangos/issues/issues/2567
