### ISSUE TITLE
🐛 [Bug Report] Hunter and Warlock Pets Stamina Stacking

### ISSUE THREAD

**Issue by Erikbmd** [cmangos/issues#2567]
## 🐛 Bugreport Hunter and Warlock pets level up bug
When pet will level up he will get a huge stamina boost. If you dismiss pet stamina goes back to normal.

### Expected behavior
 Pets shouldn't be getting so much stamina after level up. https://www.youtube.com/watch?v=z7XD57SSdpk

### Version & Environment
 
Client Version: 2.4.3

CMaNGOS Repo & Commit Hash: 770df545955b9b4d55bfdec4cd7534fbc15be316

Database Repo & Commit Hash: 6853bbca8ef5fc9e47dd00c614e6e59afe1f8afb

Operating System: Win 10

### Steps to reproduce
1. lf you're a warlock or a hunter get a pet
2. Level up pet multiple times (.levelup)
3. Pet stamina will get multiple times higher than is should
4. Dismiss your pet and stamina goes back to normal again
5. Profit

### Crashlog

- None

**Comment by killerwife** [comment]
Resolved. Was unintentionally adding multiple scaling auras on lvlup
