### ISSUE TITLE
🐛 [Bug Report] realmd does not seem to detect client locale

### ISSUE THREAD

**Issue by Fra298** [cmangos/issues#2571]
## 🐛 Bugreport
    When connecting using a french client, in game UI is in french, but quest texts, creature names and most of the rest is in english. Loc_2 is installed in database.
I tried to set locale to 2 in realmd account table for my account, but after a successfull login, locale is set back to 0

### Expected behavior
Locale texts should be displayed

### Version & Environment
Client Version:  "3.3.5a" (WOTLK)

CMaNGOS Repo & Commit Hash: [WOTLK] ](https://github.com/cmangos/mangos-wotlk/tree/28b0e37e7afe8dff1674a9c1ecbc00875e743921)

Database Repo & Commit Hash: [WOTLK](https://github.com/cmangos/wotlk-db/tree/7fd11dd034f33b33251138d6b8457267e5d7e1d6)

Operating System: Win 10

### Steps to reproduce
1. Connect a realm with a client other than english
2. 
3.
4. ...
5. Profit

### Crashlog

- None

**Comment by aveolona** [comment]
Check **mangosd.conf**.

If you want multilocale:
`DBC.Locale = 255`

If French only:
`DBC.Locale = 2`

If it doesn't work, make sure your core and database are at the latest revision, because values at realmd account table must be "enUS", "deDE", "frFR", not "2", "9", "10".

**Comment by Fra298** [comment]
Everything was set correctly and up to date.
So far, problem is now solved locale field in account table was still as tinyint and don't know why as realmd database was up to date.
Thanks for the tip, I changed field to varchar(4) and everything is ok now 👍
