### ISSUE TITLE
🐛 [Bug Report] Quest "The Tome of Divinity" broke again

### ISSUE THREAD

**Issue by aveolona** [cmangos/issues#2572]
## 🐛 Bugreport
I'm not sure, but after commit [df5ed99](https://github.com/cmangos/mangos-classic/commit/df5ed99ef1c51b1c430cc22d318e4a32cc432071), quest "[The Tome of Divinity](https://classic.wowhead.com/quest=1783/the-tome-of-divinity)" (1783) is stopped working. 

Previously, after using the [Symbol of Life](https://classic.wowhead.com/item=6866/symbol-of-life) (6866) [Narm Faulk](https://classic.wowhead.com/npc=6177/narm-faulk) (6177) would get up and we can talk to him. After this current quest is completed and we can get a [new one](https://classic.wowhead.com/quest=1784/the-tome-of-divinity) (1784) from him. 

But now he just lies dead, although the resurrection action counts.

https://user-images.githubusercontent.com/1635791/141874585-99c6ed5d-259f-4b3b-8b36-cda44e498845.mp4

### Version & Environment
**Client Version:** 1.12.1 (CLASSIC) 5875 (enGB)

**CMaNGOS Repo & Commit Hash:** https://github.com/cmangos/mangos-classic & 153d18d
_Compiled 2 days ago._

**Database Repo & Commit Hash:** https://github.com/cmangos/classic-db & fcd7f4c
_Loaded 2 days ago._

**Operating System:** Debian 9.13 (stretch)

**Comment by aveolona** [comment]
Maybe execute part of this [SQL](https://github.com/cmangos/tbc-db/blob/ebfdc4e2e0833dd8987adbc05d24cd61def2624d/Updates/0945_remove_usage_of_deathstate.sql) from TBC-DB to Classic-DB? I could be wrong, only guessing.

**Comment by aveolona** [comment]
> Maybe execute part of this [SQL](https://github.com/cmangos/tbc-db/blob/ebfdc4e2e0833dd8987adbc05d24cd61def2624d/Updates/0945_remove_usage_of_deathstate.sql) from TBC-DB to Classic-DB? I could be wrong, only guessing.

No... It's not working. I'm do it and have not any results.

https://user-images.githubusercontent.com/1635791/142040854-bdb0e151-c21e-4bc1-8dbd-6950217d1ab3.mp4

**Comment by AnonXS** [comment]
doesnt look like you removed the deathstate hack in classic-db?

**Comment by aveolona** [comment]
> UPDATE `creature` SET `DeathState` = 0 WHERE `id` IN (6177,6172);

This is it?

**Comment by aveolona** [comment]
> doesnt look like you removed the deathstate hack in classic-db?
> 
> ![grafik](https://user-images.githubusercontent.com/19734826/142041955-53db40c9-81bd-4b67-9265-3bc2ba0c430d.png)
> 
> green name shows the deathhack is not present anymore. classic might use other guid for this npc some db data is probably different and i'm not even sure this commit shouldve been ported 1:1 to classic as it has tbc data in it.

Maybe you right, but commit [df5ed99](https://github.com/cmangos/mangos-classic/commit/df5ed99ef1c51b1c430cc22d318e4a32cc432071) for Classic, TBC and WotLK. I'm checked it. Hence my assumptions.

**Comment by AnonXS** [comment]
That spell was already in use befor https://github.com/cmangos/mangos-classic/commit/df5ed99ef1c51b1c430cc22d318e4a32cc432071, so i doubt it. And thats just this visual "rezz" animation nothing that should hinder the script much i think.

**Comment by aveolona** [comment]
> That spell was already in use befor [cmangos/mangos-classic@df5ed99#diff-e9724b2255faa59043c726bf7f2f2f9298e56e1f38ed10d729505e06a70d5058R822](https://github.com/cmangos/mangos-classic/commit/df5ed99ef1c51b1c430cc22d318e4a32cc432071#diff-e9724b2255faa59043c726bf7f2f2f9298e56e1f38ed10d729505e06a70d5058R822), so i doubt it. And thats just this visual "rezz" animation nothing that should hinder the script much i think.
> 
> ```
> SpellEffects.cpp
>                 case 32343:                                 // Revive Self
>                 {
>                     if (!unitTarget)
>                         return;
> 
>                     unitTarget->SetHealth(unitTarget->GetMaxHealth());
>                     return;
>                 }
> ```
> 
> And i'm wrong. wth however it even works in classic then, was it even working befor? But then again, the npc has maxhealth now all the time.....
> 
> Try this but it wont change anything really:
> 
> ```
> INSERT INTO `spell_template` (`Id`, `School`, `Category`, `CastUI`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `Stances`, `StancesNot`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `CasterAuraState`, `TargetAuraState`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaxLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerlevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectBaseDice1`, `EffectBaseDice2`, `EffectBaseDice3`, `EffectDicePerLevel1`, `EffectDicePerLevel2`, `EffectDicePerLevel3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `SpellVisual`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName`, `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `Rank1`, `Rank2`, `Rank3`, `Rank4`, `Rank5`, `Rank6`, `Rank7`, `Rank8`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaxTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `MaxAffectedTargets`, `DmgClass`, `PreventionType`, `StanceBarOrder`, `DmgMultiplier1`, `DmgMultiplier2`, `DmgMultiplier3`, `MinFactionId`, `MinReputation`, `RequiredAuraVision`, `IsServerSide`, `AttributesServerside`) VALUES (32343, 1, 0, 0, 0, 0, 8388608, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 41, 121, 0, 0, 'Revive Self', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0);
> ```

Yes, you're right... Nothing changes. [Henze Faulk](https://classic.wowhead.com/npc=6172/henze-faulk) in Elwynn Forest is not working too: quest "[The Tome of Divinity](https://classic.wowhead.com/quest=1786/the-tome-of-divinity)" (1786).

**Comment by cala** [comment]
Assigning myself on this. :)

**Comment by killerwife** [comment]
I sniffed this quest in my classic ventures, should you want a sniff of this dude and his script, pop by discord.

**Comment by cala** [comment]
The issue was in targeting. The spell was requesting targets to be corpses while they are feigning death.

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/ea2d94bef7b4b7a46a1d6df71ad457a872f41fea#diff-c2ee685b56ac6f7d6e23367411bdff2fc43e5f4a5bfde9f708364b854aa237e1R16

**Comment by cala** [comment]
I'm afraid the whole commit went under my radar when I did the October backports...
