### ISSUE TITLE
🐛 [Bug Report] [WoTLK] Processing wotlk-mangos/sql/base/mangos.sql file error

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2574]
### Bug Details

When running "/sql/base/mangos.sql" from i get a fault of "ERROR 1050 (42S01) at line 1580: Table 'creature_immunities' already exists"
Suggested Workaround proposed below would make it consistent with the other table entries

### Steps to Reproduce

1. cd wotlk-mangos/sql/base
2. mysql -umangos -pmangos wotlkmangos < mangos.sql
3.
4.

### Expected behavior

process through without error

### Suggested Workaround

```
1580: + DROP TABLE IF EXISTS `creature_immunities`;
1581: CREATE TABLE creature_immunities(
1582: `Entry` INT UNSIGNED NOT NULL COMMENT 'creature_template entry',
1583: `SetId` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'immunity set ID',
1584: `Type` TINYINT UNSIGNED NOT NULL COMMENT 'enum SpellImmunity',
1585: `Value` INT UNSIGNED NOT NULL COMMENT 'value depending on type',
1586: PRIMARY KEY(`Entry`,`SetId`,`Type`,`Value`)
1587: );
```

### Crash Log

N/A

### Core SHA1 Commit Hash

de5d4e09dc7fb93739b6bcf794312f720d03fb36

### Database SHA1 Commit Hash

7fd11dd034f33b33251138d6b8457267e5d7e1d6

### Operating System

Ubuntu 20.04.3 Server LTS

### Client Version(s)

- [ ] 1.1.12 (Classic)
- [ ] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by adellaci** [comment]
After make the Suggest Workaround this was the next error "ERROR 1050 (42S01) at line 12247: Table 'playercreateinfo_skills' already exists"

Make it consistent with other tables

Suggest Workaround (after applying the one above)

12247:  + DROP TABLE IF EXISTS `playercreateinfo_skills`;
12248:   CREATE TABLE `playercreateinfo_skills` (
12249:  `raceMask` int unsigned NOT NULL,
12250:  `classMask` int unsigned NOT NULL,
12251:  `skill` smallint(5) unsigned NOT NULL,
12252:  `step` smallint(5) unsigned NOT NULL DEFAULT '0',
12253:  `note` varchar(255) DEFAULT NULL,
12254:   PRIMARY KEY (`raceMask`,`classMask`,`skill`)
12255: ) ENGINE=MyISAM DEFAULT CHARSET=utf8;

**Comment by adellaci** [comment]
After making those two changes there was no further ERRORs

**Comment by adellaci** [comment]
Could or would someone process this through for me?

**Comment by cala** [comment]
Thank you for this report and fix. This is closed by https://github.com/cmangos/mangos-wotlk/commit/262291978c49455f3134f347e309536fb8774c9e
