### ISSUE TITLE
🐛 [Bug Report] [WoTLK] VMaps 000.vmtree is missing or point to wrong version vmap file

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2575]
### Bug Details

I reran the latest extraction tool move folders dbc. map, vmap, & mmap to the share folder in the server directory. I started mangosd and got this error;
2021-11-29 23:23:07 ERROR:VMap file '../share/vmaps/000.vmtree' is missing or point to wrong version vmap file, redo vmaps with latest vmap_assembler.exe program
2021-11-29 23:23:07 ERROR:Correct *.map files not found in path '../share/maps' or *.vmtree/*.vmtile files in '../share/vmaps'. Please place *.map and vmap files in appropriate directories or correct the DataDir value in the mangosd.conf file.

DataDir is pointed to the right folder. The 000.vmtree file 2.7MB in size and the header in the file shows "VMAP_7.0NODE"

### Steps to Reproduce

1. Run ExtractResources.sh
2. Move dbc, maps, vmaps, mmaps to DataDir defined in mangosd.conf file
3. Run mangosd
4.

### Expected behavior

To get pass loading maps

### Suggested Workaround

Have none

### Core SHA1 Commit Hash

de5d4e09dc7fb93739b6bcf794312f720d03fb36

### Database SHA1 Commit Hash

7fd11dd034f33b33251138d6b8457267e5d7e1d6

### Operating System

Ubuntu 20.04.3 Server LTS

### Client Version(s)

- [ ] 1.1.12 (Classic)
- [ ] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by adellaci** [comment]
@Muehe; I setup a TBC server the way i did the WoTLK server. The map files have not issues in TBC. I have three different copy's of the WoTLK game files. I extracted from all three and get the same error. The game file is 3.3.5a version. I am setting up a classic server now to see if that has an issue or not. I have been wanting to have all three server, since i wrote the step by step instruction for a Ubuntu Server from the ground up, back on the old cmangos web site in the forum section.

**Comment by adellaci** [comment]
Tested latest classic and no error in the '000.vmtree' file. Going to grab the map extraction tools from TBC and run them on WoTLK and see if it works

**Comment by adellaci** [comment]
Can not use the extract tools from tbc on wotlk, fails to create any vmaps

**Comment by adellaci** [comment]
Recompiled, and extracted maps again. It has gotten past that error, but new error.

Closing this as it is resolved

**Comment by adellaci** [comment]
CMangos Version 745653db2d3b6f640b0d63f84c8255e4a3952732
Database Version e2d0a712afb6ccf2ab2d0b1d9661580e90238430


Issue is back
-

**Comment by insunaa** [comment]
You need to extract the map files again with the latest version of the extractors.

**Comment by adellaci** [comment]
I am trying again............... steps using......... let you know in a bit

Pull Lastest as of 2 hours ago
Recompiled
ran 'make install"
copied files from 'bin/tools' to 'wowdata' folder
chmod +x ExtractResources.sh
./ExtractResources.sh

Current Settings:
Extract DBCs/maps: 1, Extract vmaps: 1, Extract mmaps: 1, Processes for mmaps: all
maps extraction will be high-resolution
vmaps extraction will be high-resolution

**Comment by adellaci** [comment]
Extracting GameObject models...
Extracting World\Wmo\Band\Final_Stage.wmo
No such file World\Wmo\Band\Final_Stage.wmo.
Couldn't open RootWmo!!!
Warning: Some models could not be extracted, see below
Could not find file of model World\Detail\Drkbus02.m2
Could not find file of model World\Detail\Drkbus04.m2
Could not find file of model World\Dreaming\Passivedoodads\Flowers\Dreambellflower02.m2
Could not find file of model World\Dreaming\Passivedoodads\Flowers\Dreampurpleflower03.m2
Could not find file of model World\Dreaming\Passivedoodads\Flowers\Dreamspinningflower01.m2
Could not find file of model World\Expansion01\Doodads\Coilfang\Activedoodads\Energytower\Coilfang_Towers_E_Particle.m2
Could not find file of model World\Expansion01\Doodads\Hellfirecitadel\Demonwing\Passivedoodads\Summon_Door\Hellfire_Dw_Summondoor.m2
A few of these warnings are expected to happen, so be not alarmed!
Done!

Extract for VMAPs05. Work complete. No errors.
./ExtractResources.sh: 255: Bad substitution

**Comment by insunaa** [comment]
use `bash ./ExtractResources.sh`

**Comment by adellaci** [comment]
Thank you will try that now

**Comment by adellaci** [comment]
@insunaa 
That was the issue not running it in bash. Thank you.
