### ISSUE TITLE
💬 [Support Request] server update problems

### ISSUE THREAD

**Issue by rmzV** [cmangos/issues#2577]
### Core Version

mangos-wotlk

### Support Request Details

return to testing WOtlk server and have multiple problems at updating (seems a lot has changed after last update)
i ll downloand this package, "mangos-wotlk-with-ahbot-18b5072f"
questions:
1) what is "warden_modules" folder? do i absolutely need it to run new version?
2) at archive name "with_ahbot" but inside there is no ahbot.conf config file... does it moved?

ill updated server.... and started to update DB.. there was an error that i required "wotlklogs"
using software shell i created "wotlklogs"  with settings "utf8 -- UTF-8 Unicode" - character set and "utf8_general_ci" -collation... and later execute sql file in this Db "logs.sql"
Now i get this error:
"2021-12-04 12:45:40 MySQL client library: 8.0.23
2021-12-04 12:45:40 MySQL server ver: 5.7.14 
2021-12-04 12:45:40 Logs Database total connections: 2
2021-12-04 12:45:40 ERROR:Could not connect to MySQL database at 127.0.0.1: Access denied for user 'mangos'@'localhost' to database 'wotlklogs'

2021-12-04 12:45:40 ERROR:Cannot connect to logs database 127.0.0.1;3306;mangos;mangos;wotlklogs"

what i must do now?

Thank you!

### Steps to Reproduce

1.Update old server version to last one
2.
3.
4.

### Core SHA1 Commit Hash

18b5072f084939cf7ccfef5cf40e6c871be3575e

### Database SHA1 Commit Hash

b2707d740b6784e48db65ad1747ce136ea6915fc

### Server Operating System

windows 8

### Client Version

3.3.5a (Wrath of the Lich King)

### Client Operating System

windows 8

**Comment by adellaci** [comment]
@rmzV enter in to mysql from command line a 'root' and issue the following statement; 

GRANT INSERT ON wotlklogs.* TO 'mangos'@'localhost';
FLUSH PRIVILEGES;
exit;
This should fix user 'mangos' access to the database and tables. I believe i have the same issue.

**Comment by rmzV** [comment]
@adellaci 
i created sql file with following^
"GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES, CREATE TEMPORARY TABLES ON `wotlklogs`.* TO 'mangos'@'localhost';
FLUSH PRIVILEGES;
exit;
"
then i select inside db "wotlklogs" group and push execute sql file... and i have an error
[Err] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'exit' at line 1
[Err] GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES, CREATE TEMPORARY TABLES ON `wotlklogs`.* TO 'mangos'@'localhost';
FLUSH PRIVILEGES;
exit;
[Msg] Finished - Unsuccessfully

**Comment by adellaci** [comment]
MySQL or MariaDB and witch version? I am using MySQL 8.0.27

**Comment by adellaci** [comment]
Oh i see it no ';' after exit

**Comment by rmzV** [comment]
well, i ll complete removed exit and its do the job. Thank you
"GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, LOCK TABLES, CREATE TEMPORARY TABLES ON `wotlklogs`.* TO 'mangos'@'localhost';
FLUSH PRIVILEGES;"

may be you can help me to enable ahh bot?

**Comment by adellaci** [comment]
Have you enable ahbot in the compiling?

**Comment by rmzV** [comment]
well i always enabling it, when i was compling by myself.. but today i used already compiled eddition, from here:
https://github.com/cmangos/mangos-wotlk/releases
mangos-wotlk-with-ahbot-18b5072f.zip

so i belive it must have ahbot included:/

**Comment by adellaci** [comment]
Do you have a ahbot.conf in your 'wotlk/etc' folder?

**Comment by rmzV** [comment]
i have ahbot.conf from previvious instalation... in root folder near "mangosd.exe"

**Comment by adellaci** [comment]
Is that where you have your relmd.conf file and your mangosd.conf file?

**Comment by adellaci** [comment]
I believe all the .conf file are suppose to be in the /etc/ folder

**Comment by rmzV** [comment]
its looks like 
https://dropmefiles.com/c9beN

**Comment by adellaci** [comment]
Your ahbot.conf file should look like this;
https://github.com/cmangos/mangos-wotlk/blob/master/src/game/AuctionHouseBot/ahbot.conf.dist.in

Your start up command should look like this or a windows version of this;
./mangosd -c ./mangosd.conf -a ./ahbot.conf

**Comment by rmzV** [comment]
i ll created bat file with "mangosd.exe ./mangosd -c ./mangosd.conf -a ./ahbot.conf" and this worked.
do i absolute need this part " -c ./mangosd.conf " or it takes mangosd.conf by default?

**Comment by adellaci** [comment]
I am not sure in windows. From what i see in the installation wiki page you do not need it. but try both ways, it will give you your answer

**Comment by rmzV** [comment]
okey thank you.
i will close this ticket couse it mostly answered.. exept for "warden_modules" folder. what this thing do, and  do i absolutely need it to run new version?

**Comment by adellaci** [comment]
I do not know i haven't looked into it yet

**Comment by al3xc1985** [comment]
U need it. Put the folder along side maps,vmaps,etc and activate it from mango.conf. this is just for cheaters.

**Comment by AnonXS** [comment]
> 

closing
