### ISSUE TITLE
💬 [Support Request] CMaNGOS get stuck on Added realm id 1

### ISSUE THREAD

**Issue by elch01** [cmangos/issues#2579]
### Core Version

mangos-wotlk

### Support Request Details

Im trying to run the server but it always get stuck on "Added realm id 1, name 'MaNGOS' ", ive tried enabling Log level 3 but it only but it outputs nothing of use.

I've followed the installation guide three times and it always ends up stuck.

### Steps to Reproduce

1. Follow installation guide
2. run /home/mangos/mangos/run/bin/realmd -c /home/mangos/mangos/run/etc/realmd.conf
3. Stuck

### Crash Log

Not a crash log but here's what it outputs:

Built on Dec 11 2021 at 11:34:28
Built for Linux_x64 (little-endian)
Using commit hash(a04b62519413c376d67bfce72a7a87728d4055fc) committed on 2021-12-08T00:30:44+01:00
Using configuration file /home/mangos/mangos/run/etc/realmd.conf.
OpenSSL 1.1.1k  25 Mar 2021 (Library: OpenSSL 1.1.1k  25 Mar 2021)

<Ctrl-C> to stop.
Login Database total connections: 2
Connected to MySQL database mangos@127.0.0.1:3306/wotlkrealmd
MySQL client library: 10.5.12
MySQL server ver: 10.5.12-MariaDB-0+deb11u1 
AUTOCOMMIT SUCCESSFULLY SET TO 1
Connected to MySQL database mangos@127.0.0.1:3306/wotlkrealmd
MySQL client library: 10.5.12
MySQL server ver: 10.5.12-MariaDB-0+deb11u1 
AUTOCOMMIT SUCCESSFULLY SET TO 1
Updating Realm List...
Added realm id 1, name 'MaNGOS'

Gets stuck here^

### Core SHA1 Commit Hash

a04b62519413c376d67bfce72a7a87728d4055fc

### Database SHA1 Commit Hash

b2707d740b6784e48db65ad1747ce136ea6915fc

### Server Operating System

Linux debian 5.10.0-9-amd64 | Debian 11

### Client Version

3.3.5a (Wrath of the Lich King)

### Client Operating System

Arch Linux 5.15.7-arch1-1

**Comment by insunaa** [comment]
Have you tried starting the `mangosd` binary after starting the `realmd` binary? Because you need both

**Comment by elch01** [comment]
Yes! but i get a "Check existing of map file './maps/0004331.map': not exist!"

Even though : 
```
find -name "0004331.map"
```
Resluts in:
```
./mangos/run/bin/maps/0004331.map
```

**Comment by insunaa** [comment]
Nope, that means there's probably an error in your extracted maps. try re-extracting the maps and then do it again.
`realmd` and `mangosd` should be running in parallel. `realmd` is the daemon that handles login stuff and `mangosd` is the actual game server. `realmd` will not show you anything different until people try to log in, `mangosd` will give you an "admin" console once `mangosd` is fully and correctly started.

Another thing: check file permissions for the map files. I see it sometimes that people extract and copy these files as root and then they might not be accessible to the user which runs the `mangosd` binary

**Comment by elch01** [comment]
Seems like a broken file

`-rwxrwxrwx 1 mangos root /home/mangos/mangos/run/bin/maps/0004331.map`

`Check existing of map file './maps/0004331.map': not exist!`

Thanks for the help!
