### ISSUE TITLE
🐛 [Bug Report] Server Exits after a few second after load

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2582]
### Bug Details

I have updated the TBC Server with latest 20.12.2021 uptes. Fresh install for server and fresh install for db.
But the server crashes after a few sec, after it is completetly loaded and it gives me no errors in logs even if I changed the loglevel to 3

@killerwife this is strange cause on server updated until 10.12.2021 it didn't exit at all

### Steps to Reproduce

1.Download source
2.compile
3.run fresh install
4.after a few seconds server exit with no info
5.Profit

### Expected behavior

to not crash

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version(s)

- [ ] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [ ] 3.3.5a (Wrath of the Lich King)

**Comment by vertx66** [comment]
Also happening with an existing version I've attempted to upgrade (Using commit hash(2e0d29f67174ee6cdd5ecded228093e69a2c333a) committed on 2021-12-10T21:32:55+01:00)
Run mangosd.exe for about 4 seconds, then the crash is occurring as OP mentioned. 

Only notable error prior to the crash is. 


mangos>Invalid poly ref in BuildPolyPath. polyLength: 2, pathStartIndex: 0, startPos: (11646.7, -7099.96, 9.06421), endPos: (11657.5, -7109.43, 10.9703), mapId: 530

Thanks! Have a good one.

**Comment by al3xc1985** [comment]
Also I did a think. I downgraded to 10.12.2021 and all works fine until that date

**Comment by insunaa** [comment]
![image](https://user-images.githubusercontent.com/3718129/146759958-f2d9d267-5c16-40a4-a5fe-27718351806f.png)
it segfaults in vmap code. I'm guessing invalid vmaps are sent or something

**Comment by insunaa** [comment]
ok traced it back a bit more. it's once again these guys who are breaking cmangos-tbc: https://tbc.wowhead.com/npc=21736/wildhammer-defender

the horde version too, probably
I'm not sure if the vmaps are incorrect or if the movegen of these folks sends them to invalid places, but something is wrong with them.

**Comment by insunaa** [comment]
ooofff.. it's just a division by 0
```cpp
	// If point lies inside the triangle, return interpolated ycoord.
	if (u >= 0.0f && v >= 0.0f && (u + v) <= denom) {
		h = a[1] + (v0[1] * u + v1[1] * v) / denom;
		return true;
	}
	return false;
```
denom is 0 in the case shown above

**Comment by fatalieror** [comment]
I have the exact same problem if i set my "PathFinder.NormalizeZ = 1" . if its turned of the server doesnt crash.
