### ISSUE TITLE
🐛 [Bug Report] TBC quest "the blackwood corrupted" causing server crash

### ISSUE THREAD

**Issue by suhgurim** [cmangos/issues#2584]
### Bug Details

using the "blackwood fruit stores" or "blackwood nut stores" world item as part of the quest "the blackwood corrupted" in mid northwest darkshore causes the cmangos server to freeze then crash
![image](https://user-images.githubusercontent.com/67372138/147842672-263b38f8-8a12-463b-9f61-c0b90b2e5767.png)

### Steps to Reproduce

1.
2.
3.
4.

### Suggested Workaround

gm command to complete quest

### Crash Log

[Server.log](https://github.com/cmangos/issues/files/7797308/Server.log)

### Core SHA1 Commit Hash

c27ef1c19c75d7545e4259d371e34cb092913640

### Database SHA1 Commit Hash

227bd1c0d0ae1e0505e1d90314be0a505f6792c3

### Operating System

ubuntu 20.04

### Client Version(s)

- [ ] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [ ] 3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
Presumed fixed in [#495](https://github.com/cmangos/mangos-tbc/pull/495) because we couldn't replicate the crash, but there was some code that could theoretically lead to a crash which we corrected. please test this again :)
