### ISSUE TITLE
🐛 [Bug Report][WoTLK][Database]  Updates/3670_TDB-0945_remove_usage_of_deathstate.sql error

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2586]
### Bug Details

```
Appending Updates/3670_TDB-0945_remove_usage_of_deathstate.sql
ERROR 1364 (HY000) at line 91: Field 'RelayId' doesn't have a default value
ERROR: cannot apply Updates/3670_TDB-0945_remove_usage_of_deathstate.sql
```

### Steps to Reproduce

1.Run InstallFullDB.sh
2.
3.
4.

### Expected behavior

Process all the updates

### Core SHA1 Commit Hash

N/A

### Database SHA1 Commit Hash

2a305a2e4fdd087c71044f87311a14dc766b8cac

### Operating System

Ubuntu 20.04.3 Server LTS

### Client Version(s)

- [ ] 1.1.12 (Classic)
- [ ] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by adellaci** [comment]
By changing '3670_TDB-0945_remove_usage_of_deathstate.sql' corrects the statement
```
-- Black Temple Npcs that are dead have special unitflags
DELETE FROM `creature_spawn_data_template` WHERE `entry` IN (10001,10002); -- 10000+ tbc range
INSERT INTO `creature_spawn_data_template` (`entry`, `UnitFlags`, `RelayID`) VALUES
(10001, 33587200, 0),
(10002, 33587264, 0);
```
Then the following errors for the same reason
```
    Appending Updates/3675_brd_brewfest.sql
ERROR 1364 (HY000) at line 1: Field 'RelayId' doesn't have a default value
ERROR: cannot apply Updates/3675_brd_brewfest.sql
```

**Comment by adellaci** [comment]
Changed file '3675_brd_brewfest.sql' corrects the error
```
REPLACE INTO creature_spawn_data_template(entry,UnitFlags,Faction,RelayID) VALUES
(10000,54,32768,0);
```

**Comment by AnonXS** [comment]
https://github.com/cmangos/wotlk-db/commit/2c3f54f17129557864789cb577c0edfee8ce79c7

**Comment by adellaci** [comment]
I'll test it now

Jan 2, 2022 1:52:08 PM AnonXS ***@***.***>:

**Comment by adellaci** [comment]
Looks good....Thank you @AnonXS
