### ISSUE TITLE
🚀 [Feature Request] /way command

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2588]
### Feature Details

Is this an old command or it is introduced in the recent wow?

### Visualizations

https://tbc.wowhead.com/guides/first-aid-profession-burning-crusade-classic

### Benefits and Purpose

I believe it creates an auto going to that specific point just by one command

### Core Versions

- [X] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by MantisLord** [comment]
Sorry I'm not sure I understand what you're talking about here :)

"/way" is a command you can use with the TomTom addon from what I remember. Your link doesn't show anything related.
