### ISSUE TITLE
Client Freezes When Vehicle Gets Into Visible Range

### ISSUE THREAD

**Issue by xfurry** [cmangos/issues#260]
Client is freezing when a vehicle which is in combat and has one or many accessories gets into visible range. Both the vehicle and the accessories are in combat.

The easy way to test this is the following scenario:
- Get a vehicle which has at least one accessory, for example move a Salvaged \* Siege Engine in Ulduar near the hostile targets, and leave it there to fight the npcs alone.
- Make sure that the vehicle and the accessories are in combat.
- Run outside of the visible range of the vehicle, until you won't be able to see it
- Run back to the vehicle. At the point when the vehicle should get into visible range, the client will freeze.

**Comment by xfurry** [comment]
It's pretty disappointing that nobody wants to contribute to fix this.
I spent the last few days trying to dig out a solution, but I'm not expert in spline movement, so I have no idea how to fix it.

I only know that if I delete or comment this line (or set of lines) https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Vehicle.cpp#L234 the crash won't happen.
However it's impossible to tell why is the client crashing when vehicle accessories are loaded.

I still hope that someone will at least share some ideas on this topic...

**Comment by tarwyn** [comment]
Did you try:
~~~
    Movement::MoveSplineInit init(*passenger);
    init.MoveTo(seatEntry->m_attachmentOffsetX, seatEntry->m_attachmentOffsetY, seatEntry->m_attachmentOffsetZ, false, true); 
    init.SetFacing(0.0f);                                   
    init.SetBoardVehicle();
    init.Launch();
~~~
Maybe it needs the local coordinates of the seat to work right.

**Comment by Exxenoz** [comment]
@tarwyn: This would be still not fully correct. We need a table for the real seat offsets (extracted from client data) and send them, including attachment offsets from dbc.

@xfurry: The outgoing server packets must be logged/sniffed and examined (compare it to sniffs from blizzard) to detect wrong or missing packet data.

**Comment by tarwyn** [comment]
@Exxenoz The data I suggest actually comes from sVehicleSeatStore which is loaded with client data out of "VehicleSeat.dbc", so I am not really sure what other data you would want us to use here.

**Comment by Exxenoz** [comment]
@tarwyn: The attachment offset data in "VehicleSeat.dbc" is not the real seat offset. The real seat offset is hidden somewhere in client model files.

**Comment by Exxenoz** [comment]
If it would be that easy to get these offsets, I had already implemented it long time ago. :)

**Comment by tarwyn** [comment]
@Exxenoz What are you basing your statements on?  Even Trinity is using the DBC data for the offset. 

In any case, it's something to try out. If it makes a difference, great, if not, it could be down to something else, for example packet sequence, as you mention.

**Comment by xfurry** [comment]
@tarwyn offsets don't help. I tried that already. I know that Trinity uses them, but even @shauren commented that they are using them in the wrong way.
@Exxenoz I don't have sniffer for 3.5.5a. Maybe someone can help here.

I tried testing on the DK zone map with all npcs cleaned out except for 28782 with movement as idle and the client still crashed.
I think there is clearly some disconnect between some movement packages and this only happens when there are vehicles with passengers on the map.

**Comment by Exxenoz** [comment]
@tarwyn: The real seat offsets are only needed for proper spell target selection (e.g. AOE effects) and other mechanics that need the exact position of a unit to work correctly. I better won't comment the "Even Trinity is using" sentence. ;)

**Comment by Exxenoz** [comment]
@xfurry: I do not have a 335a sniffer either, but wouldn't it be possible to call an output method inside the constructor of WorldPacket ("Create packet with opcode X") and additionally call this output method also in ByteBuffer (e.g. "Add int32 value: X") to at least get any information about what is currently going on?

**Comment by Shauren** [comment]
The offsets found in VehicleSeat.dbc are m2 bone attachment points -  you can extract this data from the client (you don't need to sniff them) and store it in database for example

**Comment by Schmoozerd** [comment]
@xfurry 
The local coordinates of the seat are not the war-winners here.
(Having them badly "only" results in the boarded npc being boarded at wrong positions and with wrong orientation)

@topic
I had some difficulties to reproduce the behaviour in a controlled way.

As you describe behaviour related to incombat/ out-of-combat I suggest the old issue that a boarded npc tries to move (which he never should be able to) - in this case here in some form of entering combat or evading.

So expect a more or less high-level (AI) issue.

At least this has been a similar issue in the past: a boarded npc attempts to move - results in a client-freeze (due to unexpected packages)

If this was the case, you need not to track the packages, but any movement change of the rider and prevent this.

**Comment by Grz3s** [comment]
```quote
As you describe behaviour related to incombat/ out-of-combat I suggest the old issue that a boarded npc tries to move (which he never should be able to) - in this case here in some form of entering combat or evading.
```
In this case: https://github.com/unified-db/Database/issues/87
DarkRider should controll vehicle ..
using this spell:
``` code
ServerToClient: SMSG_AURA_UPDATE (0x091C) 
UpdateAll: True
UnitGUID: Full: 0x2039244C201C1B8000000300005E2027 Vehicle/0 R3657/S3 Map: 609 Entry: 28782 Low: 6168615
AurasCount: 1
[0] Slot: 0
[0] HasAura: True
[0] SpellID: 46598 (46598)
[0] Flags: Positive (2)
[0] ActiveFlags: 1
[0] CastLevel: 55
[0] Applications: 0
[0] Int56 Count: 0
[0] Effect Count: 0
[0] HasCastUnit: True
[0] HasDuration: False
[0] HasRemaining: False
[0] CastUnit: Full: 0x1C39244C201C180000000300005E2027 Creature/0 R3657/S3 Map: 609 Entry: 28768 Low: 6168615

ServerToClient: SMSG_AURA_UPDATE (0x091C) 
UpdateAll: True
UnitGUID: Full: 0x1C39244C201C180000000300035AF695 Creature/0 R3657/S3 Map: 609 Entry: 28768 Low: 56293013
AurasCount: 2
[0] Slot: 0
[0] HasAura: True
[0] SpellID: 46598 (46598)
[0] Flags: NoCaster, Positive (3)
[0] ActiveFlags: 2
[0] CastLevel: 55
[0] Applications: 0
[0] Int56 Count: 0
[0] Effect Count: 0
[0] HasCastUnit: False
[0] HasDuration: False
[0] HasRemaining: False
[1] Slot: 1
[1] HasAura: True
[1] SpellID: 52370 (52370)
[1] Flags: NoCaster, Positive (3)
[1] ActiveFlags: 1
[1] CastLevel: 55
[1] Applications: 0
[1] Int56 Count: 0
[1] Effect Count: 0
[1] HasCastUnit: False
[1] HasDuration: False
[1] HasRemaining: False
```

**Comment by Schmoozerd** [comment]
A few more notes:
horse:
SELECT * FROM creature_Template WHERE entry=28782;
rider: (boarded via vehicle_accessory)
SELECT * FROM creature_template WHERE entry=28768;

horse has SD2 AI
rider has EventAI (without combat movement settings)
=> If there is a glitch in any of the mmgens the rider might be inclined to walk/ move.

**Comment by Schmoozerd** [comment]
Related to evading, you can look out for
DEBUG_FILTER_LOG(LOG_FILTER_AI_AND_MOVEGENSS, "%s follow to %s", m_owner->GetGuidStr().c_str(), target->GetGuidStr().c_str());
(Rider attempting to follow horse --> error in evade system --> AI error with vehicle riders)

**Comment by xfurry** [comment]
@Schmoozerd 
The problem is quite tricky.
As I said, I tried to test this on map 609 (DK area) and only with npc 28782 spawned on the whole map (many spawns)
I set all the creatures to movement idle (vehicle and summoned accessory) and the freeze still happened sometimes. Both creatures are same faction so no combat or other things could happen.

The only thing which prevented this from happening was to cancel the accessory boarding movement.
So I think that is the real problem. It usually happens when the creature is loaded on the map or the creature is re-synced with the client after getting out of range.
There is no specific opcode that is sent when the crash is happening. I think it's just the usual transport position update that is done here: https://github.com/cmangos/mangos-wotlk/blob/master/src/game/TransportSystem.cpp#L54 or something else related to movement.

PS.
Also on EnterEvadeMode we should use
```
if (m_creature->isAlive() && !m_creature->IsBoarded())
```
before sending the creature home.

**Comment by xfurry** [comment]
> Might help a little (untested) -- but be aware: This is all rather messy and the state/mmgen system requires a proper rework to be in itself clear and straight forward.

This doesn't fix the issue.
I'm not sure if it helps or not, but client still freezes.

**Comment by jimmybrancaccio** [comment]
@xfurry or @Grz3s Do we know if this is still an issue?

**Comment by Grz3s** [comment]
this issue is still valid.. and as i have been told will be hard to fix

**Comment by xfurry** [comment]
@Grz3s is the issue still occurring after https://github.com/cmangos/mangos-wotlk/commit/a995163eb3c8e9d93046b18afe549d0ac8ac6f6c?

**Comment by cyberium** [comment]
Yes it is. To fix this we should fix update_object. Wich is a garbage actualy regarding vehicle or transport in general.

**Comment by insunaa** [comment]
I can't reproduce this anymore. Can someone else test this again?

**Comment by al3xc1985** [comment]
I believe it's fixed
