### ISSUE TITLE
🚀 [Feature Request] Rename Database fields to PascalCase

### ISSUE THREAD

**Issue by cyberium** [cmangos/issues#2601]
### Feature Details

Renaming some table seem to be necessary to get a minimum consitancy over our database.

Obviously its not possible to rename all the db at once thus i want you to write what should be done for you in priority.

The new table "waypoint_path" seem to not make a consensus as it is.

Its main role is to store a path(selection of node) with an unique id
That id should not be tied to anything but some rule to clearly identify wich core it is.
We have to move creature_movement_template and creature_movement data in it. That can be quickly done as it require only to find a way to store a new pathId somewhere for all moving creatures.
Issue with it is only to figure the new id for each creatures.

Thats said back to field that need to be renamed
Following one are proposed by me and AnonXS as a priority.

```sql
ALTER TABLE `creature_movement` RENAME COLUMN `id` TO `Id`;
ALTER TABLE `creature_movement` RENAME COLUMN `point` TO `Point`;
ALTER TABLE `creature_movement` RENAME COLUMN `position_x` TO `PositionX`;
ALTER TABLE `creature_movement` RENAME COLUMN `position_y` TO `PositionY`;
ALTER TABLE `creature_movement` RENAME COLUMN `position_z` TO `PositionZ`;
ALTER TABLE `creature_movement` RENAME COLUMN `orientation` TO `Orientation`;
ALTER TABLE `creature_movement` RENAME COLUMN `waittime` TO `WaitTime`;
ALTER TABLE `creature_movement` RENAME COLUMN `script_id` TO `ScriptId`;
ALTER TABLE `creature_movement` RENAME COLUMN `comment` TO `Comment`;

ALTER TABLE `creature_movement_template` RENAME COLUMN `entry` TO `Entry`;
ALTER TABLE `creature_movement_template` RENAME COLUMN `pathId` TO `PathId`;
ALTER TABLE `creature_movement_template` RENAME COLUMN `point` TO `Point`;
ALTER TABLE `creature_movement_template` RENAME COLUMN `position_x` TO `PositionX`;
ALTER TABLE `creature_movement_template` RENAME COLUMN `position_y` TO `PositionY`;
ALTER TABLE `creature_movement_template` RENAME COLUMN `position_z` TO `PositionZ`;
ALTER TABLE `creature_movement_template` RENAME COLUMN `orientation` TO `Orientation`;
ALTER TABLE `creature_movement_template` RENAME COLUMN `waittime` TO `WaitTime`;
ALTER TABLE `creature_movement_template` RENAME COLUMN `script_id` TO `ScriptId`;
ALTER TABLE `creature_movement_template` RENAME COLUMN `comment` TO `Comment`;

ALTER TABLE `script_waypoint` RENAME COLUMN `entry` TO `Entry`;
ALTER TABLE `script_waypoint` RENAME COLUMN `pathId` TO `PathId`;
ALTER TABLE `script_waypoint` RENAME COLUMN `pointid` TO `Point`;
ALTER TABLE `script_waypoint` RENAME COLUMN `position_x` TO `PositionX`;
ALTER TABLE `script_waypoint` RENAME COLUMN `position_y` TO `PositionY`;
ALTER TABLE `script_waypoint` RENAME COLUMN `position_z` TO `PositionZ`;
ALTER TABLE `script_waypoint` RENAME COLUMN `orientation` TO `Orientation`;
ALTER TABLE `script_waypoint` RENAME COLUMN `waittime` TO `WaitTime`;
ALTER TABLE `script_waypoint` RENAME COLUMN `script_id` TO `ScriptId`;
ALTER TABLE `script_waypoint` RENAME COLUMN `comment` TO `Comment`;

UPDATE `waypoint_path` SET `pathId` = `entry`;
ALTER TABLE `waypoint_path` DROP COLUMN `entry`;
ALTER TABLE `waypoint_path` RENAME COLUMN `pathId` TO `Id`; -- PathId in spawn_group_formation
ALTER TABLE `waypoint_path` RENAME COLUMN `point` TO `Point`;
ALTER TABLE `waypoint_path` RENAME COLUMN `position_x` TO `PositionX`;
ALTER TABLE `waypoint_path` RENAME COLUMN `position_y` TO `PositionY`;
ALTER TABLE `waypoint_path` RENAME COLUMN `position_z` TO `PositionZ`;
ALTER TABLE `waypoint_path` RENAME COLUMN `orientation` TO `Orientation`;
ALTER TABLE `waypoint_path` RENAME COLUMN `waittime` TO `WaitTime`;
ALTER TABLE `waypoint_path` RENAME COLUMN `script_id` TO `ScriptId`;
ALTER TABLE `waypoint_path` RENAME COLUMN `comment` TO `Comment`;
ALTER TABLE `waypoint_path` DROP PRIMARY KEY;
ALTER TABLE `waypoint_path` ADD PRIMARY KEY (`PathId`, `Point`);
```

Those are obvious and my point by opening this issue is to gather more of them that you think they should be renamed by this batch of renaming.

### Visualizations

Nothing to show

### Benefits and Purpose

Make our live better

### Core Versions

- [X] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by cyberium** [comment]
@Grz3s @cala

**Comment by rnorden** [comment]
* Should we collect information about case sensitivity for different database object types (tables, columns, ...) for mainstream dbms?
E.g. could we break compatibility with Postgres because it handles case sensitivity differently to MySQL?

* If column names are case-sensitive, do queries have to abide the cases?

* At the moment the cases in database columns look like follows:

description | CASING | count(*) | example
|---|---|---|---|
| no underscores, all upper | ALL_UPPER | 1 | "ID"
| no underscores, starts with lower, has also upper | LOWER_PASCAL | 122 | "attackPower"
| has underscore, has both cases | MIXED_SNAKE | 256 | "Text_lang"
| has underscore, all lower | LOWER_SNAKE | 573 | "max_amount"
| no underscores, starts with upper, has also lower | UPPER_PASCAL | 738 | "AccountId"
| no underscores, all lower | ALL_LOWER | 1028 | "id"

**Comment by cyberium** [comment]
More renaming will be done in the futur but that one is done
