### ISSUE TITLE
Static Creature in spawn_group

### ISSUE THREAD

**Issue by miraco** [cmangos/issues#2602]
### Feature Details

When using spawn_group with rnd picked spawn_group_entry all spawns in the group get picked random.

Groups like the Destroyer + Darkcaster/archer in ramparts use 1 static npc (destroyer) that should always be on his position and get rnd adds (archer or darkcaster) behind him. 

My suggestion would be to only pick random entry for creatures that have id 0 in creature table. (Just like creature_spawn_entry).

### Benefits and Purpose

![148385129-cb1fcbca-1e9c-4efe-a329-d48497bfe9ff](https://user-images.githubusercontent.com/6261245/148640781-6547183c-aa2e-4324-86bd-2bb20daba8f3.png)
Scripting Groups like this.

### Core Versions

- [x] 1.1.12 (Classic)
- [x] 2.4.3 (The Burning Crusade)
- [x] 3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
That was actually discussed and i plan to do that.

**Comment by miraco** [comment]
yeah just wanted to have it in here so we dont forget it someday :)
