### ISSUE TITLE
🚀 [Feature Request] spawn_group with only 1 moving creature

### ISSUE THREAD

**Issue by miraco** [cmangos/issues#2603]
### Feature Details

We need something to let only one creature of an spawn_group move, without having the others following.

fox example:

![Wow_vhYZxqb5QY](https://user-images.githubusercontent.com/6261245/148642371-17c968b9-3a80-468a-af70-401ad0ef3813.png)
This is 1 group with 4 static staying mobs and the one on the right side using waypoints.

Here you can see that these group gets puleld together:

https://www.youtube.com/watch?v=n3iwah8Ppfo

Or this is from SL tested right now

https://www.youtube.com/watch?v=EPf_29bvlJg

### Benefits and Purpose

Maybe there are other groups that will have different waypoints too. For now its only this group i know.

### Core Versions

- [X] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
I mean, if you do not define a formation, this should already work if you define movement in creature table.

**Comment by miraco** [comment]
Other groups that would benefit from this:

Bota:
![Wow_U0dSRH9xyC](https://user-images.githubusercontent.com/6261245/148664584-ca954cc9-5e0e-413f-882e-5197f1c31d2f.png)

Shattered Halls:
![Wow_7OOTPP1kHe](https://user-images.githubusercontent.com/6261245/148664585-2feb2f4a-1c96-4376-ab9a-e1569af42ebf.png)
![Wow_g2QgByvrEB](https://user-images.githubusercontent.com/6261245/148664586-e55ba077-7fe1-44da-bf81-c1d53492f19f.png)

Maybe mecha (not sure its a group tho)
![Wow_vXGvQOoRiQ](https://user-images.githubusercontent.com/6261245/148664587-d4e60600-80a4-43e4-a6ce-ff80b3217eb1.png)


last time i tryed it, it didnt work but i will try it again maybe i made something wrong

**Comment by killerwife** [comment]
@miraco supply me with SQL and i will resolve this.

**Comment by miraco** [comment]
`SET @CGUID := 5430000; -- creatures
SET @SGGUID := 54300; -- spawn_groups

DELETE FROM waypoint_path WHERE PathID = @CGUID+17;
INSERT INTO waypoint_path (PathId, Point, PositionX, PositionY, PositionZ, Orientation, WaitTime, ScriptId) VALUES
(@CGUID+17, 1, -1276.92, 1640.51, 91.6726, 2.69188, 22000, 1173),
(@CGUID+17, 2, -1276.52, 1638.6, 91.6777, 4.62397, 0, 0),
(@CGUID+17, 3, -1278.69, 1636.47, 91.6955, 3.85742, 0, 0),
(@CGUID+17, 4, -1282.16, 1637.86, 91.706, 2.761, 0, 0),
(@CGUID+17, 5, -1282.55, 1639.29, 91.7032, 1.84051, 0, 0),
(@CGUID+17, 6, -1282.15, 1640.54, 91.6982, 1.23026, 26000, 1173),
(@CGUID+17, 7, -1283.46, 1638.84, 91.7092, 4.3852, 0, 0),
(@CGUID+17, 8, -1281.31, 1635.72, 91.7092, 5.35595, 0, 0),
(@CGUID+17, 9, -1277.05, 1636.46, 91.6883, 0.177039, 0, 0),
(@CGUID+17, 10, -1276.07, 1639.22, 91.6735, 1.16271, 0, 0);

DELETE FROM `spawn_group` WHERE Id = @SGGUID+26;
INSERT INTO `spawn_group`(`Id`, `Name`, `Type`, `MaxCount`, `WorldState`, `Flags`) VALUES 
(@SGGUID+26, 'Helfire Ramparts - Group 26', 0, 0, 0, 3);

DELETE FROM `spawn_group_spawn` WHERE Id = @SGGUID+26;
INSERT INTO `spawn_group_spawn`(`Id`, `Guid`, `SlotId`) VALUES 
(@SGGUID+26, @CGUID+17, 0), -- Bonechewer Hungerer (Moving)
(@SGGUID+26, @CGUID+28, 1), -- Bleeding Hollow Darkcaster
(@SGGUID+26, @CGUID+29, 2), -- Bleeding Hollow Darkcaster
(@SGGUID+26, @CGUID+66, 3), -- Shattered Hand Warhound
(@SGGUID+26, @CGUID+77, 4); -- Shattered Hand Warhound

DELETE FROM `spawn_group_formation` WHERE Id = @SGGUID+26;
INSERT INTO `spawn_group_formation`(`Id`, `FormationType`, `FormationSpread`, `FormationOptions`, `PathID`, `MovementType`, `Comment`) VALUES 
(@SGGUID+26, 0, 0, 1, @CGUID+19, 2, 'Bonechewer Ravener');

DELETE FROM creature WHERE guid IN (@CGUID+17, @CGUID+28, @CGUID+29, @CGUID+66, @CGUID+77);
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecsmin`, `spawntimesecsmax`, `spawndist`, `currentwaypoint`, `DeathState`, `MovementType`) VALUES
(@CGUID+17, 17259, 543, 3, -1276.92, 1640.51, 91.6726, 2.69189, 7200, 7200, 0, 0, 0, 2), -- Bonechewer Hungerer
(@CGUID+28, 17269, 543, 3, -1298.65, 1638.98, 91.8292, 3.9968, 7200, 7200, 0, 0, 0, 0), -- Bleeding Hollow Darkcaster
(@CGUID+29, 17269, 543, 3, -1288.11, 1637.25, 91.816, 4.95674, 7200, 7200, 0, 0, 0, 0), -- Bleeding Hollow Darkcaster
(@CGUID+66, 17280, 543, 3, -1296.52, 1636.16, 91.8307, 0.506145, 7200, 7200, 0, 0, 0, 0), -- Shattered Hand Warhoud
(@CGUID+77, 17280, 543, 3, -1292.4, 1637.55, 91.7452, 4.7732, 7200, 7200, 0, 0, 0, 0); -- Shattered Hand Warhound
`


This should work for the group in ramparts.

**Comment by killerwife** [comment]
@miraco this works already:

```sql
SET @CGUID := 5430000; -- creatures
SET @sgguid := 54300; -- spawn_groups

DELETE FROM creature_movement WHERE Id = @CGUID+17;
INSERT INTO creature_movement (Id, Point, PositionX, PositionY, PositionZ, Orientation, WaitTime, ScriptId) VALUES
(@CGUID+17, 1, -1276.92, 1640.51, 91.6726, 2.69188, 22000, 1173),
(@CGUID+17, 2, -1276.52, 1638.6, 91.6777, 4.62397, 0, 0),
(@CGUID+17, 3, -1278.69, 1636.47, 91.6955, 3.85742, 0, 0),
(@CGUID+17, 4, -1282.16, 1637.86, 91.706, 2.761, 0, 0),
(@CGUID+17, 5, -1282.55, 1639.29, 91.7032, 1.84051, 0, 0),
(@CGUID+17, 6, -1282.15, 1640.54, 91.6982, 1.23026, 26000, 1173),
(@CGUID+17, 7, -1283.46, 1638.84, 91.7092, 4.3852, 0, 0),
(@CGUID+17, 8, -1281.31, 1635.72, 91.7092, 5.35595, 0, 0),
(@CGUID+17, 9, -1277.05, 1636.46, 91.6883, 0.177039, 0, 0),
(@CGUID+17, 10, -1276.07, 1639.22, 91.6735, 1.16271, 0, 0);

DELETE FROM spawn_group WHERE Id = @sgguid+26;
INSERT INTO spawn_group(Id, Name, Type, MaxCount, WorldState, Flags) VALUES
(@sgguid+26, 'Helfire Ramparts - Group 26', 0, 0, 0, 3);

DELETE FROM spawn_group_spawn WHERE Id = @sgguid+26;
INSERT INTO spawn_group_spawn(Id, Guid, SlotId) VALUES
(@sgguid+26, @CGUID+17, 0), -- Bonechewer Hungerer (Moving)
(@sgguid+26, @CGUID+28, 1), -- Bleeding Hollow Darkcaster
(@sgguid+26, @CGUID+29, 2), -- Bleeding Hollow Darkcaster
(@sgguid+26, @CGUID+66, 3), -- Shattered Hand Warhound
(@sgguid+26, @CGUID+77, 4); -- Shattered Hand Warhound

DELETE FROM creature WHERE guid IN (@CGUID+17, @CGUID+28, @CGUID+29, @CGUID+66, @CGUID+77);
INSERT INTO creature (guid, id, map, spawnMask, position_x, position_y, position_z, orientation, spawntimesecsmin, spawntimesecsmax, spawndist, currentwaypoint, DeathState, MovementType) VALUES
(@CGUID+17, 17259, 543, 3, -1276.92, 1640.51, 91.6726, 2.69189, 7200, 7200, 0, 0, 0, 2), -- Bonechewer Hungerer
(@CGUID+28, 17269, 543, 3, -1298.65, 1638.98, 91.8292, 3.9968, 7200, 7200, 0, 0, 0, 0), -- Bleeding Hollow Darkcaster
(@CGUID+29, 17269, 543, 3, -1288.11, 1637.25, 91.816, 4.95674, 7200, 7200, 0, 0, 0, 0), -- Bleeding Hollow Darkcaster
(@CGUID+66, 17280, 543, 3, -1296.52, 1636.16, 91.8307, 0.506145, 7200, 7200, 0, 0, 0, 0), -- Shattered Hand Warhoud
(@CGUID+77, 17280, 543, 3, -1292.4, 1637.55, 91.7452, 4.7732, 7200, 7200, 0, 0, 0, 0); -- Shattered Hand Warhound
```

**Comment by miraco** [comment]
Yeah it works.
