### ISSUE TITLE
Segmentation fault after clean install

### ISSUE THREAD

**Issue by opiums9** [cmangos/issues#2607]
### Core Version

mangos-tbc

### Support Request Details

After a clean install of mangos according to [this instruction](https://github.com/cmangos/issues/wiki/Installation-Instructions), I am unable to start my server. The server is assembled in debug, logs are attached.

### Steps to Reproduce

1. git clone git://github.com/cmangos/tbc-db.git
2. cd mangos
3. make build
4. cmake ../ -DCMAKE_BUILD_TYPE=Debug -DBUILD_EXTRACTORS=ON -DPCH=1
5. make -j $(nproc) install

- extract maps (the log is attached)
- successful install databases
- update *.conf files & realmd.realmlist

- run realmd & mangosd
- get Segmentation fault :(

### Crash Log

[1641869708.crash](https://gist.github.com/opiums9/808326184db8c56f5d194ad34cda4e8b)
[Server.log](https://gist.github.com/opiums9/89effb82d31da455399ff6da9b07daa1)
[MaNGOSExtractor_detailed.log](https://gist.github.com/opiums9/dff196f60174e05e115dcdecadb771ac)

### Core SHA1 Commit Hash

 f0e9931c5a8b1a8e5876ba7140c9f54df2f82ff4

### Database SHA1 Commit Hash

 f0e9931c5a8b1a8e5876ba7140c9f54df2f82ff4

### Server Operating System

Debian 10.11

### Client Version

2.4.3 (The Burning Crusade)

### Client Operating System

Windows 7 x64

**Comment by cyberium** [comment]
You probably didn't provided core_path in InstallFullDB.config
All the error in server log are telling you that there is no spell in your spell_template table.

**Comment by opiums9** [comment]
Oh this is really so, I thought this parameter is not necessary, thanks more

**Comment by cyberium** [comment]
Now its mandatory we will add this as a requirement to the script
