### ISSUE TITLE
4.3.4: Implement XP Reward on Using Some Professions

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#261]
We need to implement the XP Rewards for Mining/Herbalism and a few others.

Here is the information:

http://www.wowwiki.com/Formulas:Gather_XP

Currently there is no XP Reward. This was a new system put in place in 4.0.1 rewarding extra XP when doing profession activities.

**Comment by cyberium** [comment]
CMaNGOS officially stop cata development.
