### ISSUE TITLE
🐛 [Bug Report] [WoTLK] Profession - Fishing - Journeymen

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2610]
### Bug Details

I created a character (leveled him to 19) and picked up fishing as a profession. I level the skill to 70, went to trainer and got my Journeymen training. When i open my skills, it show fishing skill max 75. I verified in my spell book that i have the journeymen training but will not raise my max skill.

### Steps to Reproduce

1.Pickup fishing apprentice 
2.Level character skill to 50 or above. 
3.Go to trainer and get Journeymen training
4.

### Expected behavior

Receive level max to 150

### Suggested Workaround

N/A

### Crash Log

N/A

### Core SHA1 Commit Hash

dee360ab0e1c11c882488501a4d6c85bb97cd036

### Database SHA1 Commit Hash

e6e2c6a6b763a04409b0998d3bb69ec9944c6e7a

### Operating System

Ubuntu 20.04.3 Server LTS

### Client Version(s)

- [ ] 1.1.12 (Classic)
- [ ] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Which particular trainer did you use

**Comment by adellaci** [comment]
Warg Deepwater npc=1683 Loch Modan

**Comment by adellaci** [comment]
Even if i use ".learn 7734" my potential skill level does not raise up 150 as it should

**Comment by virusav** [comment]
Core commit: MySQL 5.5/5.7 Support (fe71e7b378d87913aa8d6d6f2175f393c5840c25)
Wotlk-db commit: [TDB][3676] Script for q.9718 As the Crow Flies (697ea3ddbec5512391b9f276da0f9008f8e2107a)

Research:
```
.unlearn 7620 all
.cast self 7733 (+Apprentice)
.setskill 356 50
.cast self 7734 (+Journeyman, +Apprentice) - ?

max skill is still 75

.unlearn 7731 (-Apprentice)
.cast self 7734 (+Journeyman)

max skill 150

**Comment by killerwife** [comment]
I will check this out over the weekend guys.

**Comment by adellaci** [comment]
After rebuilding my server from scratch, and a few commits, it seem to be working. I will leave it open till this weekend for comments, if nothing comes up I'll close it.

**Comment by adellaci** [comment]
No further comments closing
