### ISSUE TITLE
🐛 [Bug Report] Creatures visible Ressource?

### ISSUE THREAD

**Issue by SabriynaVermillion** [cmangos/issues#2613]
### Bug Details

**I've discovered something that makes me wonder why that is.
Is there perhaps a reason why it is like this on a c-mangos server?**

**Original WoW:**
![ResourceQuestion2](https://user-images.githubusercontent.com/26441174/149632757-4b510f17-17a3-4117-93bd-3cfe9edec19c.png)

**C-Mangos-Server:**
![ResourceQuestion](https://user-images.githubusercontent.com/26441174/149632771-1d367b5e-7184-4d59-89c7-49433ab20c95.png)

**The bar under the health shows a resource I don't know about.
It's only on a c-mangos Server.**

### Steps to Reproduce

**1. Login in with your character to a c-mangos tbc server
2. Click on a creature that doesn't use rage, energy, or mana as a resource.**

### Expected behavior

**No resource should be displayed on the mentioned bar.**

### Core SHA1 Commit Hash

625c59468ce8433c2badf7cb915f07f1f13fdbc1

### Database SHA1 Commit Hash

cdb88c7736c3b87581ad946147903aaf4d3830de

### Operating System

Windows 10

### Client Version(s)

- [ ] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [ ] 3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
There is a config option for it. By default in vanilla and tbc you did not
see hp. Check fog of war in config.

**Comment by insunaa** [comment]
@killerwife they didn't mean the HP bar, they meant below that the resource bar (rage/mana/energy) which in this screenshot is 0/100 but should be invisible

**Comment by killerwife** [comment]
Oh, then we are just setting something wrongly to 100 in creature :D

**Comment by Warlockbugs** [comment]
Probably worth checking power type fields being broadcasted. If the first screenshot from modern remastered Classic client, it could be a difference between versions of UI and how they handle power values

**Comment by Darkynight** [comment]
This is correct. The ressource under the health bar must be invisible. It must not be displayed when you make the health visible in the configuration, nor when you move the mouse over the portrait in this area.

**Comment by berserkingyadis** [comment]
reproduced on core https://github.com/cmangos/mangos-tbc/commit/ce65ebca5c17cb0087ace7638907910b175a0955 db https://github.com/cmangos/tbc-db/commit/50d8fbad49e1c044b2f43fb45f32f359b7868eba commits
