### ISSUE TITLE
🐛 [Bug Report] [WoTLK] Core compile fails if Playerbots enabled

### ISSUE THREAD

**Issue by Niam5** [cmangos/issues#2614]
### Bug Details

Wrath core fails to compile with playerbots enabled.

### Steps to Reproduce

1. Clone repo
2. Configure using CMake to enable playerbots
3. Compile
4. Get error

### Expected behavior

Should compile with no issues

### Suggested Workaround

I have found the missed flag rename and fixed it on my fork but due to all the Eluna work it wants to pull all of it if I make a pull request and making a branch is meh. Commit that fixes it can be found here https://github.com/Niam5/mangos-wotlk/commit/e5106c656e15c72a6fb192e684c5223aaa1878ba

### Core SHA1 Commit Hash

e5106c656e15c72a6fb192e684c5223aaa1878ba

### Database SHA1 Commit Hash

e6e2c6a6b763a04409b0998d3bb69ec9944c6e7a

### Operating System

Windows Server 2016

### Client Version(s)

- [ ] 1.1.12 (Classic)
- [ ] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-wotlk/commit/04e8940e7f2d4df0d94069da98d4522e81db74cb

**Comment by killerwife** [comment]
Appreciate the quick fix cala while I was asleep :D
