### ISSUE TITLE
🐛 [Bug Report] [WoTLK][Quest] Galaen's Fate quest=9579 Amulet, no or very low drop

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2616]
### Bug Details

I have gone around The Cryo-Core 4 times kill every Sunhawk Reclaimer, and have fail to get the drop Galaen's Amulet. Everywhere i have looked the drop rate should be between 4 - 5%.

Researching the 'creature_loot_template ', the `ChanceOrQuestChance` is -4.53. With a negative, would it fail to drop?
 
Galaen's Fate quest=9579

Galaen's Amulet item=23873

Sunhawk Reclaimer npc=17606

Bloodmyst Isle - The Cryo-Core

### Steps to Reproduce

1. Pick up quest Galaen's Fate quest=9579 at The Cryo-Core
2. Farm Sunhawk Reclaimer npc=17606
3.
4.

### Expected behavior

Galaen's Amulet item=23873 to drop 

### Suggested Workaround

UPDATE `creature_loot_template` SET ChanceOrQuestChance = 4.53 WHERE entry = 17606 AND Item = 23873;

### Core SHA1 Commit Hash

e202f81cea4820fba2dd5fa31b095b9f635d9dcc

### Database SHA1 Commit Hash

e6e2c6a6b763a04409b0998d3bb69ec9944c6e7a

### Operating System

Ubuntu 20.04.3 Server LTS, WIndows 7 Client

### Client Version(s)

- [ ] 1.1.12 (Classic)
- [ ] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by adellaci** [comment]
With the suggested workaround, three trips completely around farming, and i got it. Seems reasonable.

**Comment by virusav** [comment]
The quest works and does not require any edits.
https://github.com/cmangos/issues/wiki/Loot_template#chanceorquestchance (Quest drop).

The chance of drop is small, but things fall on the quest, as it should be.
The first taking the quest - from 23 npc, the second - from 17.

**Comment by Grz3s** [comment]
```Researching the 'creature_loot_template ', the ChanceOrQuestChance is -4.53. With a negative, would it fail to drop?```
negative = quest drop
source wiki:
```ChanceOrQuestChance < 0, mincountOrRef > 0
Just as for plain entries absolute value of ChanceOrQuestChance signifies the percent chance
 that the item has to drop. But in addition negative ChanceOrQuestChance informs 
the core that the item should be shown only to characters having appropriate quest. 
This means that even if item is dropped, in order to see it in the loot the player must 
have at least one quest that has the item ID in its ReqItemIdN fields or in its ReqSourceIdN fields. 
The player must also have less copies of the item than ReqItemCountN or ReqSourceCountN.```

**Comment by adellaci** [comment]
@Grz3s glad to see you back. Read my original issue I went completely around four times and I didn't get the drop

**Comment by adellaci** [comment]
I did not test after I changed it to a positive value if I would get the drop after I had completed the quest I guess I need to go back and do that

**Comment by adellaci** [comment]
I am not discounting that I have an issue with my install because I have some other issues which are not making sense

**Comment by Grz3s** [comment]
4,5 is very small % that you will get it... ( 96% that u wont) ... so patience.
BTW:
I wouldnt be surprised if blizz .. have machanic that longer u farming (quest item)  = drop chance goes up... so ventualy you must get it...

**Comment by al3xc1985** [comment]
when I played blizz during wotlk time, that kind of behaviour didn't exist to increase drom chance when longer u farm. and believe me I quested a lot. I love questing

**Comment by adellaci** [comment]
Core: Using commit hash(99649bf079bc6503afba0a895d5b3177b0c53922)
Database: Using commit hash(06e7e55d472bb2e6e9728e8f01c34d6b76e7d374)

While go i redid my system from top to bottom, have just got around to testing this again. @Grz3s & @al3xc1985 was right it work just finish.
