### ISSUE TITLE
🐛 [Bug Report] [WoTLK] [Quest] They're Alive! Maybe... quest=9670

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2618]
### Bug Details

When freeing Expedition Researcher npc=17681 you are not given credit. Need 5 freed to complete quest.

### Steps to Reproduce

1. Pick up quest They're Alive! Maybe...  quest=9670
2. Attack Webbed Creature npc=17680
3. If you free a Expedition Researcher npc=17681
4.

### Expected behavior

Get credit if there is a Expedition Researcher from the Webbed Creature

### Suggested Workaround

N/A

### Crash Log

N/A

### Core SHA1 Commit Hash

c4fdc02fd18d3758d59a81cddc75cb9350afc3c7

### Database SHA1 Commit Hash

e6e2c6a6b763a04409b0998d3bb69ec9944c6e7a

### Operating System

Ubuntu 20.04.3 Server LTS, Client Windows 7

### Client Version(s)

- [ ] 1.1.12 (Classic)
- [ ] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by adellaci** [comment]
Trying to research it further the problem, i ran out to the area to test again, i had turn '.gm on' when i got to the first Webbed Creature, '.gm off' and attacked a Expedition Researcher came out and i got credit. Went thru a few more before i got a Expedition Researcher, but i did not get credit, so i did a few more and still did not get credit. I then started turning gm on, go to the Webbed Creature, turn gm off, attack, and if a Expedition Researcher come out i get credit.

**Comment by virusav** [comment]
Core commit: MySQL 5.5/5.7 Support (fe71e7b378d87913aa8d6d6f2175f393c5840c25)
Wotlk-db commit: [TDB][3676] Script for q.9718 As the Crow Flies (697ea3ddbec5512391b9f276da0f9008f8e2107a)

```
create a new character
.gm off
.level 16
.list creature 17686
.go creature 63445
get quest "They're Alive! Maybe..."
kill cocoons: if the right npc appears, then we get a killcredit +1
complete the quest
```

Everything is working.

**Comment by adellaci** [comment]
@virusav  I am deleting the DB and starting again to see if it changes

**Comment by virusav** [comment]
I always start the game through a bat-file:
```
rd /S /Q Cache
start wow.exe
```
Deleting the cache solves some of the problems.

**Comment by adellaci** [comment]
No i still have the issue. I am going to try with another character. I has something show up weird in the server log. I posted it but no one seem to know what it was. After that error as a warlock i have no control of my pets. All of there control buttons are grayed out.

If it is related to this toon I will have to back and check the other quest to see if they are not issues with other toon.

**Comment by adellaci** [comment]
I rebuilt server from scratch and now the these quest works.
