### ISSUE TITLE
💬 [Support Request] 

### ISSUE THREAD

**Issue by Nayr3456** [cmangos/issues#2621]
### Core Version

mangos-wotlk

### Support Request Details

I'm trying to run the WoTLK server. I have been running the TBC server for a while. When trying to launch the world server it crashes with no error. I am not running them at the same time on the same PC.

### Steps to Reproduce

1.
2.
3.
4.

### Crash Log

[Server.log](https://github.com/cmangos/issues/files/7917613/Server.log)

### Core SHA1 Commit Hash

fe71e7b378d87913aa8d6d6f2175f393c5840c25

### Database SHA1 Commit Hash

697ea3ddbec5512391b9f276da0f9008f8e2107a

### Server Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

### Client Operating System

Windows 10

**Comment by Nayr3456** [comment]
Start money was set too high.

**Comment by virusav** [comment]
mangosd.conf: `LogFileLevel = 3`
Start the server and check the log.
