### ISSUE TITLE
💬 [Support Request] 

### ISSUE THREAD

**Issue by Nayr3456** [cmangos/issues#2623]
### Core Version

mangos-wotlk

### Support Request Details

NPCs do not aggro players and players are invisible to each other. I am using all default configs.

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

fe71e7b378d87913aa8d6d6f2175f393c5840c25

### Database SHA1 Commit Hash

697ea3ddbec5512391b9f276da0f9008f8e2107a

### Server Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

### Client Operating System

Windows 10

**Comment by Niam5** [comment]
This may have been fixed by recent change https://github.com/cmangos/mangos-wotlk/pull/351 can you git pull the latest and try again?

**Comment by Nayr3456** [comment]
That did it
