### ISSUE TITLE
🐛 [Bug Report] Greater Plainstriders looting bug

### ISSUE THREAD

**Issue by MilkmanMHOC** [cmangos/issues#2625]
### Bug Details

When killing Greater Plainstriders near Crossroads, players found they almost never dropped loot and were not skinnable.  However, they seemed to drop loot when killed quickly (1 shot)

At low health, the Plainstrider will attempt to "run away in fear".  Once that happens, the drop rate seems to be zero, or very close to zero.  If they die before they are able to attempt to flee they are skinnable and loot drops seem to follow normal drop rates.  

### Steps to Reproduce

1. Attack Greater Plainstriders slowly dealing dmg until they flee, then kill.
2. Note they are not lootable or skinnable
3. Attack Greater Plainstrider and kill quickly before they flee
4. Note they are now lootable and skinnable.

### Expected behavior

Plainstriders should be skinnable after kill, and drop loot according to set droprates.

### Core SHA1 Commit Hash

9ba55ca03f8ad6376e003f79c788e54d8a4949de

### Database SHA1 Commit Hash

ba1d50c3b9049ad54b129ee56749232503ae91d0

### Operating System

Windows 7

### Client Version

1.1.12 (Classic)

**Comment by MilkmanMHOC** [comment]
Just to add, as more testing is being done it appears to apply to multiple types of plainstriders?  New Tauren characters are having difficulties with the starting zone quest to do no drops/ability to loot.

**Comment by MilkmanMHOC** [comment]
Just some more information on this.  I updated again today to the newest version, still did not work(worth a try).  In reading through the history i saw changes made to the flee mechanic on Dec 19th.  SO, i rolled back to Dec 18th and im happy to report i can now loot and skin the plainstriders.  I do not know if that specific change on the 19th is the issue or any of the numerous ones after that, but its a place to start.  

I also have some additional info on their fleeing in the current build.  IF they are not killed after fleeing they turn non-hostile and regen their health.  I do not believe this is correct, and in the dec 18th build after fleeing they eventually come back and finish attacking.  This may be a clue to the issue?

I will continue to test as i have time to fine more specifics about the issue.

**Comment by killerwife** [comment]
The mobs leash. If you do not attack them for 10-15 seconds, even during their flee, they will go back to do their thing.

**Comment by Trystanosaurus** [comment]
I've had the same problem with a new Tauren character. If the Plainstriders for the first quest start fleeing they leave no loot. However if you kill them without triggering the flee emote they are lootable as normal.

**Comment by Nytanath** [comment]
Can confirm, if you kill them while they're fleeing they appear untapped (their unitframe and icon has a gray background) which means you lack the rights to loot it.

**Comment by Nytanath** [comment]
Oh I see, thanks! I'm going to test this behavior for critters, but I think it's wrong for creatures, as they should go back to attacking players after evade. The FACTION_TEMPLATE_FLEE_FROM_CALL_FOR_HELP is correct for those creatures, they should call for help (a lot of creatures do), so it can't be that. It should have no bearing on whether or not they evade when the panic ends.
