### ISSUE TITLE
4.3.4: Implement HITINFO_FAKE_DAMAGE

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#263]
Looking at sniffs it appears there is a hit type (that also existed in 3.3.5a) that has never been implemented.

This is used for some NPC's who are actually in combat but at some point (around 80%) they quit taking damage and just continue in this fake fighting forever. If the NPC is healed to 100% they will take damage again down to approx 80% and again will remain there.

Here is some sniff data:

HitInfo: HITINFO_AFFECTS_VICTIM, HITINFO_UNK10, HITINFO_UNK11, HITINFO_UNK12, HITINFO_RAGE_GAIN, **\* HITINFO_FAKE_DAMAGE **\* (25172994)

ServerToClient: SMSG_ATTACKERSTATEUPDATE (0x0B25) Length: 53 Time: 08/22/2012 06:07:08.574 Number: 21175
HitInfo: HITINFO_AFFECTS_VICTIM, HITINFO_UNK10, HITINFO_UNK11, HITINFO_UNK12, HITINFO_RAGE_GAIN, HITINFO_FAKE_DAMAGE (25172994)
AttackerGUID: Full: 0xF130C2CD00003CD2 Type: Unit Entry: 49869 Low: 15570
TargetGUID: Full: 0xF130C2CF0009966C Type: Unit Entry: 49871 Low: 628332
Damage: 0
OverDamage: -1
Count: 1
[0] SchoolMask: 1
[0] Float Damage: 0
[0] Int Damage: 0
VictimState: VICTIMSTATE_NORMAL (1)
Unk Attacker State 0: -1
Melee Spell ID : 0
Rage Gained: 71

ServerToClient: SMSG_ATTACKERSTATEUPDATE (0x0B25) Length: 53 Time: 08/22/2012 06:07:08.574 Number: 21176
HitInfo: HITINFO_AFFECTS_VICTIM, HITINFO_UNK10, HITINFO_UNK11, HITINFO_UNK12, HITINFO_RAGE_GAIN, HITINFO_FAKE_DAMAGE (25172994)
AttackerGUID: Full: 0xF130C2CF0009966C Type: Unit Entry: 49871 Low: 628332
TargetGUID: Full: 0xF130C2CD00003CD2 Type: Unit Entry: 49869 Low: 15570
Damage: 0
OverDamage: -1
Count: 1
[0] SchoolMask: 1
[0] Float Damage: 0
[0] Int Damage: 0
VictimState: VICTIMSTATE_NORMAL (1)
Unk Attacker State 0: 0
Melee Spell ID : 0
Rage Gained: 65

I hope this helps.

**Comment by cyberium** [comment]
@Grz3s do you think we need that on wotlk?

**Comment by Grz3s** [comment]
i wont give you 100% answer for this:
If im correct first time i saw this in 4.x.x
Places like training grounds in Borean Tundra (or older Shadowmoon Valley) where this could be used...
Blizz.. was always using same method to avoid dmg:
- Emotes :D (all sniffed and confirmed)..
Example:
```sql
    EMOTE_ONESHOT_ATTACKUNARMED         = 35,
    EMOTE_ONESHOT_ATTACK1H                      = 36,
    EMOTE_ONESHOT_ATTACK2HTIGHT            = 37,
    EMOTE_ONESHOT_ATTACK2HLOOSE           = 38,
    EMOTE_ONESHOT_PARRYUNARMED           = 39,
    EMOTE_ONESHOT_PARRYSHIELD                 = 43,
    EMOTE_ONESHOT_READYUNARMED           = 44,
    EMOTE_ONESHOT_READY1H                        = 45,
```

**Comment by cyberium** [comment]
Thank you so i think we can close this for now
