### ISSUE TITLE
🚀 [Feature Request] Make CMaNGOS compatible with Ninja

### ISSUE THREAD

**Issue by insunaa** [cmangos/issues#2636]
### Feature Details

Currently CMake Configuration of CMaNGOS is incompatible with Ninja. I would like CMaNGOS to be buildable by Ninja.
(PRs for this to follow)

### Benefits and Purpose

Possibly faster build times. Wider compatibility with other build systems.
(Build on a 5950X, same CMake parameters, with `make clean` and `ninja clean` run beforehand)
![image](https://user-images.githubusercontent.com/3718129/152663391-35742c61-58fc-4c8f-9303-51ed2cb068ea.png)

### Core Versions

- [X] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
I have no idea what this means outside of slight speed improvement. I will let @cyberium test this one since he likes these things :D

**Comment by insunaa** [comment]
I think he said he doesn't really see a point either, but there's also no point to *not* support Ninja for Clang. It's already supported for GCC, just some dodgy code is keeping it from working with clang.
And given that it *does* result in a ~10% improvement for build times I don't see how it has any downsides

**Comment by killerwife** [comment]
Did you test the build on windows and on gcc with the cmake change?

**Comment by insunaa** [comment]
I don't have a windows system to build things on, but I can point you to these CI builds:
https://github.com/insunaa/mangos-tbc/actions/runs/1799113914
https://github.com/insunaa/mangos-tbc/actions/runs/1799113915
https://github.com/insunaa/mangos-tbc/actions/runs/1799113917

At the very least it doesn't make any difference to how things are built traditionally. Since only Clang is affected I don't see why it would, either. CLion being the premiere IDE to compile with clang on windows is also getting improved support through this, because it uses the Ninja Generator by default

**Comment by cyberium** [comment]
Yes no reason to not support it, just need to confirm nothing is badly impacted.

**Comment by insunaa** [comment]
The one thing it could have an impact on is XCode, but I'm unable to test that. As you can see in the github actions thing, it still compiles completely fine with the Xcode compiler, but I'm not sure how the GUI handles it. I don't see how it could negatively impact it, but I also can't test it unfortunately.

**Comment by cyberium** [comment]
Better don't create PR for all repos when its same change.
And i am sorry just realized that i forgot to change author. Sorry about that @insunaa

**Comment by insunaa** [comment]
Don't worry about it! I created PRs for all repos so that it'd be easier to just use the github UI to merge the PRs, but I'll stick to one repo in the future! :)
