### ISSUE TITLE
💬 [Support Request] 

### ISSUE THREAD

**Issue by maxsl89** [cmangos/issues#2637]
### Core Version

mangos-wotlk

### Support Request Details

When I log in, it shows that I was authorized successfully, but the server is not selected, nothing happens when I click it.

### Steps to Reproduce

1. Installed the server (DO Droplet) according to the [guide](https://github.com/cmangos/issues/wiki/Installation-Instructions).
2. Launched in separate screens mangosd and realmd.
3. In the realm list of the client specified the ip of the droplet.
4. Created an account using the command **account create MyNewAccount MyPassword**
So, when I log in client, it shows that I was authorized successfully, shows the mangos server, but nothing happens when I click it.

### Core SHA1 Commit Hash

5fefe5c0a15115f57258cd9dda8d250bfc0780b5

### Database SHA1 Commit Hash

99b0f4b96aa84854c50433a8b6aba01c3ca5e486

### Server Operating System

ubuntu 18.04

### Client Version

3.3.5a (Wrath of the Lich King)

### Client Operating System

ubuntu 20.04

**Comment by insunaa** [comment]
Did you open the required ports in your firewall? 3724 and 8085

**Comment by maxsl89** [comment]
@insunaa thanks for your answer!
**Did you open the required ports in your firewall? 3724 and 8085**
ufw status verbose
Status: inactive
**Also did you adjust the address field in the realmd.realmlist table?**
no, what should I do?

**Comment by maxsl89** [comment]
DELETE FROM realmlist WHERE id=1;
INSERT INTO realmlist (id, name, address, port, icon, realmflags, timezone, allowedSecurityLevel)
VALUES ('1', 'MaNGOS', '**MY SERVER IP**', '8085', '1', '0', '1', '0');
am I correct?

**Comment by insunaa** [comment]
That would work, yep
Alterntively 
```mysql
UPDATE realmd.realmlist SET address='YourServerAddress' WHERE id=1;
```

**Comment by maxsl89** [comment]
Thank you! everything ok now

**Comment by insunaa** [comment]
You're welcome!
Closing the issue now :)
