### ISSUE TITLE
🐛 [Bug Report] This revision of mangos requires a database updated to: `z2778_01_logs_anticheat.sql`

### ISSUE THREAD

**Issue by novicewu** [cmangos/issues#2638]
### Bug Details

Built on Feb  6 2022 at 10:10:48
Built for Linux_x64 (little-endian)
Using commit hash(670868b8c77cc7dd7bad3ff413cd735133e02cbd) committed on 2022-02-06T01:09:46+03:00
Using configuration file /home/mangos/mangos/run/etc/mangosd.conf.

<Ctrl-C> to stop.
World Database total connections: 2
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
Character Database total connections: 2
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
Login Database total connections: 2
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
Logs Database total connections: 2
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
SQL: SELECT required_z2778_01_logs_anticheat FROM logs_db_version LIMIT 1
query ERROR: Table 'classiclogs.logs_db_version' doesn't exist
SQL: SELECT * FROM logs_db_version LIMIT 1
query ERROR: Table 'classiclogs.logs_db_version' doesn't exist
The table `logs_db_version` in your [UNKNOWN] database is missing or corrupt.
MaNGOS cannot find the version info needed to check that the db is up to date.

This revision of mangos requires a database updated to:
`z2778_01_logs_anticheat.sql`

Reinstall your [UNKNOWN] database with the included sql file in the sql folder.

### Steps to Reproduce

1. Environment: ubuntu 20.04
2. wow CMANGOS 1.12
3. install per wiki https://github.com/cmangos/issues/wiki/Installation-Instructions
4. the error shows when coming to the step:"Running your Server", and running the command: /home/mangos/mangos/run/bin/mangosd -c /home/mangos/mangos/run/etc/mangosd.conf -a /home/mangos/mangos/run/etc/ahbot.conf
5. but no error when running the command: /home/mangos/mangos/run/bin/realmd -c /home/mangos/mangos/run/etc/realmd.conf

### Crash Log

Built on Feb  6 2022 at 10:10:48
Built for Linux_x64 (little-endian)
Using commit hash(670868b8c77cc7dd7bad3ff413cd735133e02cbd) committed on 2022-02-06T01:09:46+03:00
Using configuration file /home/mangos/mangos/run/etc/mangosd.conf.

<Ctrl-C> to stop.
World Database total connections: 2
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
Character Database total connections: 2
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
Login Database total connections: 2
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
Logs Database total connections: 2
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
MySQL client library: 8.0.28
MySQL server ver: 8.0.28-0ubuntu0.20.04.3 
SQL: SELECT required_z2778_01_logs_anticheat FROM logs_db_version LIMIT 1
query ERROR: Table 'classiclogs.logs_db_version' doesn't exist
SQL: SELECT * FROM logs_db_version LIMIT 1
query ERROR: Table 'classiclogs.logs_db_version' doesn't exist
The table `logs_db_version` in your [UNKNOWN] database is missing or corrupt.
MaNGOS cannot find the version info needed to check that the db is up to date.

This revision of mangos requires a database updated to:
`z2778_01_logs_anticheat.sql`

Reinstall your [UNKNOWN] database with the included sql file in the sql folder.

### Core SHA1 Commit Hash

idk

### Database SHA1 Commit Hash

idk

### Operating System

ubuntu 20.04

### Client Version

1.1.12 (Classic)

**Comment by insunaa** [comment]
You seem to have missed quite a few steps in the setup process.
Take another look at https://github.com/cmangos/issues/wiki/Installation-Instructions#install-databases

**Comment by novicewu** [comment]
> You seem to have missed quite a few steps in the setup process. Take another look at https://github.com/cmangos/issues/wiki/Installation-Instructions#install-databases

yea, indeed. thank you.

now i encounter another problem:
When login my character, there is no NPC and monster in the world. How to fix that?

**Comment by insunaa** [comment]
Did you install the Database?
https://github.com/cmangos/classic-db
-> `InstallFullDB.sh`

**Comment by novicewu** [comment]
yea, i forgot the 2nd step:
-> bash ./InstallFullDB.sh

Now it's working.
Thank you so much!

**Comment by insunaa** [comment]
You're welcome! :)
