### ISSUE TITLE
🐛 [WOTLK]  Crypt Fever + Ebon Plaguebringer ~Dk Talents~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2640]
### Bug Details

Spells:

Talents:

- [ ] Crypt Fever - Not working, it is not applaying the debuff that it says in description
- [ ]  + Ebon Plaguebringer - can not be tested cause Crypt Fever is not working

### Steps to Reproduce

1.create dk
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
@killerwife is this a good way to report classes spells/talents bugs? if not tell me how is good to do it ,pls

**Comment by al3xc1985** [comment]
Also if u want I can separate them all

**Comment by killerwife** [comment]
I prefer when they are one by one, makes it easier to show progress.

**Comment by al3xc1985** [comment]
ok, I will try my best to do so, from now on, and I will split them all

**Comment by killerwife** [comment]
Retest pls. Implemented it. This one was tricky.

**Comment by al3xc1985** [comment]
well not working

**Comment by killerwife** [comment]
Resolved it.

**Comment by al3xc1985** [comment]
https://www.youtube.com/watch?v=cV3dmzvGsno
I found this video from 2012... and I see that the totem can be selected...but I don;t know if this is on official or private

**Comment by killerwife** [comment]
I have checked offical 3.3.5 data

**Comment by al3xc1985** [comment]
ok. nice, ty very much... just to let you know I have tested all until this moment, and all are working just perfect
