### ISSUE TITLE
🐛 [Wotlk] Arcane Empowerment (Mage Talent)

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2643]
### Bug Details

What is working?
The buff for party

What is not working?
The bonus for arcane missile and arcane barrage

### Steps to Reproduce

1.create mage
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
I can confirm this is working. This is bonus spell damage from gear, not actual base damage.
