### ISSUE TITLE
🐛 [WOTLK] Netherwind Presence ~ Mage Talent ~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2644]
### Bug Details

The talent does not increase spell haste by 6%

### Steps to Reproduce

1.create mage
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Before:
![image](https://user-images.githubusercontent.com/7995382/153671197-e71badfc-ad00-4d74-a723-63d50945b312.png)
After:
![image](https://user-images.githubusercontent.com/7995382/153671231-647580c5-cb99-4eb1-866d-9e6f08046395.png)

Works as intended. Keep in mind this is spell haste, not haste rating.

**Comment by al3xc1985** [comment]
yes u are right, my mistake was exactly where u pointed
