### ISSUE TITLE
🐛 [Wotlk] Spell Power    Mage Talent

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2645]
### Bug Details

The talent should increase critical strike dmg bonus by 50% and it is not working, it doesn't increase

### Steps to Reproduce

1.create mage
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
I can confirm this also works. My hit did 1060, by default a crit would do 1060*1.5, but with the talent it did 1060*1.75
