### ISSUE TITLE
🐛 [WOTLK ] Anti Magic Zone ~DK Spell~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2650]
### Bug Details

U can still see the blue fire of the totem, and if u click on the the fire, u select the totem

### Steps to Reproduce

1.create dk
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Resolved by not making it clickable https://github.com/cmangos/wotlk-db/commit/f696741f2e6572af3835e47b1d4f410b26653591
