### ISSUE TITLE
🐛 [WOTLK] Bloodworm ~Dk Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2652]
### Bug Details

 as I can check I can say that he creates worms on attacking the target, but , the worms do not attack your target at all, they just wonder around

### Steps to Reproduce

1.
2.
3.create dk
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Resolved through several commits.
