### ISSUE TITLE
🐛 [Wotlk] Talent Judgement of the Wise

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2664]
### Bug Details

The talent should "Your damaging Judgement spells have a 33% chance to grant the Replenishment effect to up to 10 party or raid members mana regeneration equal to 1% of their maximum mana per 5 sec for 15sec, and to immediately grant you 25% of your base mana."

Also rank2 &3 need the same spell learn visual , If I am not wrong
Also the chance must be checked based on rank

I jeep this for refference

### Steps to Reproduce

1.pala
2.
3.
4.

### Core SHA1 Commit Hash

8276263

### Database SHA1 Commit Hash

83737278

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
Also I need to add here extract thing about it.

Through this talent it will also restore 25% of your base mana, beside the replenishment buff

**Comment by killerwife** [comment]
What exactly doesnt work about this? I already made the replenishment work.

**Comment by al3xc1985** [comment]
well it is not working...
I recloned the whole core and db... deleted my cache....reimplement all the dbs.... 

I create a pala...lvl it up to 60 for example...learn all spells from trainer...use seal of command...and use some mana with holy light.... I want to judge an enemy and:
1. Restore instantly 25% of my base mana
2. Apply the Replenishment buff to restore additional over time mana

BUT

Nothing is working

**Comment by al3xc1985** [comment]
in the mage case u added 
-- Enduring Winter - Mage talent - Frostbolt mask
UPDATE spell_template SET EffectSpellClassMask2_1=0x00000020 WHERE Id IN(44557,44560,44561);

but not in paladin case in both fixes.... are u sure u didn't forget to add this info for paladin with the proper spells? cause it is not working... the mage spell is perfect working with the changes...the paladin ones do not work

**Comment by al3xc1985** [comment]
that is more like it...working super cool...nice
