### ISSUE TITLE
🐛 [Bug Report] CANT finish  installation in windows.

### ISSUE THREAD

**Issue by BlackBoar101** [cmangos/issues#2666]
### Bug Details

![QQ截图20220212173946](https://user-images.githubusercontent.com/77557058/153706163-395b5b08-6540-4d74-8056-7588bc029703.png)
![QQ截图20220212173959](https://user-images.githubusercontent.com/77557058/153706165-dcc63cca-1c96-4a3a-955a-83fa06bdf73b.png)

### Steps to Reproduce

1.VS 2017 
2.cmake cmake-3.23.0-rc1-windows-x86_64
3.boost_1_72_0_b1-msvc-14.1-64.exe
4.cant install new CMTBC ,but can install last year version.

### Expected behavior

CAN some one give me some instructions ?So i can report more bugs in gameplay in new CMTBC.

### Core SHA1 Commit Hash

2022

### Database SHA1 Commit Hash

2022

### Operating System

win7

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
CMaNGOS TBC compiles fine on Windows (https://github.com/cmangos/mangos-tbc/actions/runs/1832964713)
There most be a problem on your system. Try re-running cmake or looking up the error codes in a search engine

**Comment by BlackBoar101** [comment]
@insunaa im not a coder. my system is win7 with vs2017. i tried many times tried many cmake version and boost version but still facing the same end.  it works fine with 2021 source code. i cant generate map extrator fully. a programmer looked into my computer he told me i must use VS 2019! another told me i need TBB .really hard for me...

**Comment by BlackBoar101** [comment]
@insunaa oh my god! this is really helpful. this is a beautiful new world with sunshine and soft wind!

**Comment by dunjeon** [comment]
Can't confim. Compiled on Windows 10

**Comment by insunaa** [comment]
I'll close the issue for now. If there is more to say on it feel free to reply and if it's relevant I'll re-open the issue

**Comment by BlackBoar101** [comment]
@dunjeon Does that mean new source code wont support win7 anymore? one coder did told me to try win10 enviroment.

**Comment by BlackBoar101** [comment]
@insunaa Not sure whether other win7 user face the same problem.

**Comment by BlackBoar101** [comment]
@MilkmanMHOC Thank you. This information is helpful, maybe VS2019 will help my build.

**Comment by BlackBoar101** [comment]
Compiled successfuly after installed VS 2019.

**Comment by BlackBoar101** [comment]
@insunaa do we have released server in pair?

**Comment by insunaa** [comment]
development build is rebuilt daily to be up to date.
if you want specific versions you will have to compile your own

**Comment by insunaa** [comment]
you don't have to compile the database. just download it and install it

**Comment by BlackBoar101** [comment]
i see thank you~

**Comment by BlackBoar101** [comment]
@insunaa What version of mysql should i use? Or can i download a green one just easy to in install database?

**Comment by BlackBoar101** [comment]
@insunaa there are too much problem i have to overcome to use mysql.

**Comment by BlackBoar101** [comment]
![图片](https://user-images.githubusercontent.com/77557058/154841668-8e4c6c1e-e811-4132-b4dc-ebc2faeecd35.png)
I cant finish install db. 
My InstallFullDB.sh just skip the .dbc files. I followed the install instruction step by step.
What should i do , can you give me some guide?
![图片](https://user-images.githubusercontent.com/77557058/154841737-59c7b45c-7060-4c65-a8ee-65000e5dc225.png)

**Comment by insunaa** [comment]
You need to follow the installation instructions: https://github.com/cmangos/issues/wiki/Installation-Instructions

Some Databases need to be initialized manually

**Comment by BlackBoar101** [comment]
@insunaa thank you. my server can running now.
https://github.com/cmangos/issues/wiki/Installation-Instructions   BUT does this guide missing *dbc .sql step?

**Comment by Nytanath** [comment]
The dbc sqls are imported from the core's source.

This step here in the guide:

> With the default configuration, you only need to change CORE_PATH to:

The installer imports it automatically when CORE_PATH is configured.

**Comment by BlackBoar101** [comment]
@Nytanath 
my core_path
![图片](https://user-images.githubusercontent.com/77557058/154875092-007c1ab1-b48e-4535-bf12-6aa338ca6be4.png)
my config
![图片](https://user-images.githubusercontent.com/77557058/154875275-e1bfaa6c-faa7-45ff-a837-f7de3ce84b1a.png)
I found InstallFullDB.sh act with no difference wether i do the config or not. it just dont do his dbc job in the core....
Whats my problem~~

**Comment by BlackBoar101** [comment]
Im stuck here for 3 days now...old database with new core cant report bug precisely.

**Comment by MilkmanMHOC** [comment]
Just looking at it, hard to tell but is there a space in your path before the first / ?

**Comment by BlackBoar101** [comment]
![图片](https://user-images.githubusercontent.com/77557058/154886604-1e76b0be-ef11-40df-9d25-c1db04d7eb3a.png)
I tried this servel times also

**Comment by BlackBoar101** [comment]
![QQ截图20220221120226](https://user-images.githubusercontent.com/77557058/154887183-3e78087f-f5c0-4510-b260-ac7d5a2d50e0.png)
![QQ截图20220221120235](https://user-images.githubusercontent.com/77557058/154887190-247accfb-8338-498e-96db-9aac286e80d2.png)
![QQ截图20220221120259](https://user-images.githubusercontent.com/77557058/154887192-52a02dd5-545a-4fd5-9f31-2ea09ef39837.png)
This is all  InstallFullDB.sh did for me.

**Comment by ckj777** [comment]
Simple full DB installation
https://www.youtube.com/watch?v=2CqWKSU3X2w

**Comment by BlackBoar101** [comment]
Thank you all! I finally solved my problem by reinstalling my win7.
