### ISSUE TITLE
🐛 [Bug Report] TBC.map.mob visual position does not match real position.

### ISSUE THREAD

**Issue by BlackBoar101** [cmangos/issues#2667]
### Bug Details

![WoWScrnShot_021222_190558](https://user-images.githubusercontent.com/77557058/153710864-716a9f6d-2c74-412e-bf0d-4b52c7626013.jpg)
the yellow guys  position should be the blue dot. but after you kill it , it will spawn some where VISUALLY AWAY! but its real position still at the blue dot. any spell cast on the guy will feed back too far away.
there are more mobs i come across have the same problem.

### Steps to Reproduce

1. use .go creature 58226
2. kill the mob. to see the problem faster, better kill the four in a row .
3. wait them to respawn
4. the visual position will be off the real position

### Expected behavior

visual positon should be the same as the real position.

### Core SHA1 Commit Hash

Development Build(2022-02-12)

### Database SHA1 Commit Hash

Development Build(2022-02-12)

### Operating System

win7

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Please, the next time it happens, try these two chat commands at the target.

.debug visibility isvisible
.debug visibility atclient

**Comment by BlackBoar101** [comment]
@killerwife
![WoWScrnShot_021322_100846](https://user-images.githubusercontent.com/77557058/153735241-43c2af5f-b715-44ea-ae72-e28c0d27de8c.jpg)

**Comment by BlackBoar101** [comment]
@killerwife
After i restart the server. they are back to the right position.
![WoWScrnShot_021322_101314](https://user-images.githubusercontent.com/77557058/153735400-6befffee-6a2a-4e75-a5b5-57de0e3a8193.jpg)

**Comment by killerwife** [comment]
I am definitely keeping a close on this one. Will let you know if I figure out something more.

**Comment by BlackBoar101** [comment]
![WoWScrnShot_021822_174022](https://user-images.githubusercontent.com/77557058/154683453-1f02df56-5f89-48dc-b675-73b4efa73a35.jpg)
This guy was hitting me miles away this afternoon. After you new commits this doesnt happen again.
hitting by invisible foes maybe because the model of the mob is miles away out of my screen.

**Comment by wackyliu** [comment]
have the same problem

**Comment by al3xc1985** [comment]
Why close is it fixed?

**Comment by BlackBoar101** [comment]
> Why close is it fixed?

Yes. I test it on the latest version.This bug doesnt occur anymore.
