### ISSUE TITLE
🐛 [Bug Report] error: 'GetSpellSchoolMask' was not declared in this scope

### ISSUE THREAD

**Issue by novicewu** [cmangos/issues#2673]
### Bug Details

[ 88%] Building CXX object src/game/CMakeFiles/game.dir/Spells/Scripts/Scripting/ClassScripts/Warlock.cpp.o
[ 89%] Building CXX object src/game/CMakeFiles/game.dir/Spells/Scripts/Scripting/ClassScripts/Warrior.cpp.o
/home/mangos/mangos/src/game/Spells/Scripts/Scripting/ClassScripts/Warrior.cpp: In member function 'virtual void Devastate::OnEffectExecute(Spell*, SpellEffectIndex) const':
/home/mangos/mangos/src/game/Spells/Scripts/Scripting/ClassScripts/Warrior.cpp:84:84: error: 'GetSpellSchoolMask' was not declared in this scope
             unitTarget->AddThreat(caster, 14.0f * sunder->GetStackAmount(), false, GetSpellSchoolMask(spell->m_spellInfo), spell->m_spellInfo);
                                                                                    ^~~~~~~~~~~~~~~~~~
/home/mangos/mangos/src/game/Spells/Scripts/Scripting/ClassScripts/Warrior.cpp:84:84: note: suggested alternative: 'SpellSchoolMask'
             unitTarget->AddThreat(caster, 14.0f * sunder->GetStackAmount(), false, GetSpellSchoolMask(spell->m_spellInfo), spell->m_spellInfo);
                                                                                    ^~~~~~~~~~~~~~~~~~
                                                                                    SpellSchoolMask
make[2]: *** [src/game/CMakeFiles/game.dir/build.make:7265: src/game/CMakeFiles/game.dir/Spells/Scripts/Scripting/ClassScripts/Warrior.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:628: src/game/CMakeFiles/game.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

### Steps to Reproduce

1. install per instruction from https://github.com/cmangos/issues/wiki/Installation-Instructions
2. when coming to step "make", it stopped at 89%
3. error: 'GetSpellSchoolMask' was not declared in this scope
4. details please check the crush log

### Crash Log

[ 88%] Building CXX object src/game/CMakeFiles/game.dir/Spells/Scripts/Scripting/ClassScripts/Warlock.cpp.o
[ 89%] Building CXX object src/game/CMakeFiles/game.dir/Spells/Scripts/Scripting/ClassScripts/Warrior.cpp.o
/home/mangos/mangos/src/game/Spells/Scripts/Scripting/ClassScripts/Warrior.cpp: In member function 'virtual void Devastate::OnEffectExecute(Spell*, SpellEffectIndex) const':
/home/mangos/mangos/src/game/Spells/Scripts/Scripting/ClassScripts/Warrior.cpp:84:84: error: 'GetSpellSchoolMask' was not declared in this scope
             unitTarget->AddThreat(caster, 14.0f * sunder->GetStackAmount(), false, GetSpellSchoolMask(spell->m_spellInfo), spell->m_spellInfo);
                                                                                    ^~~~~~~~~~~~~~~~~~
/home/mangos/mangos/src/game/Spells/Scripts/Scripting/ClassScripts/Warrior.cpp:84:84: note: suggested alternative: 'SpellSchoolMask'
             unitTarget->AddThreat(caster, 14.0f * sunder->GetStackAmount(), false, GetSpellSchoolMask(spell->m_spellInfo), spell->m_spellInfo);
                                                                                    ^~~~~~~~~~~~~~~~~~
                                                                                    SpellSchoolMask
make[2]: *** [src/game/CMakeFiles/game.dir/build.make:7265: src/game/CMakeFiles/game.dir/Spells/Scripts/Scripting/ClassScripts/Warrior.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:628: src/game/CMakeFiles/game.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

### Core SHA1 Commit Hash

n/a

### Database SHA1 Commit Hash

n/a

### Operating System

debian 10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
This might be caused by the lack of PCH.
To solve it add the following line beneath the other includes in the `Warrior.cpp` file:
```cpp
#include "Spells/SpellMgr.h"
```
