### ISSUE TITLE
🐛 [WOTLK] Army of Dead ~Dk Spell~ Behaviour

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2674]
### Bug Details

https://www.youtube.com/watch?v=e1coU7-Gn6k

The differences:
1. The ghouls spawn and stay in same place of summon until aggroed or put in combat with player (currently they spawn and come beside u like your ghoul and all stay in same place) . As u can see they have some sort of special behaviour
2. The channel on the video is like 10 sec (currently I count like 8 sec)

What do u think @killerwife ?

### Steps to Reproduce

1.dk unholy
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Video is from early wotlk, likely BETA. It changed a lot over wotlk. And on the topic of follow read this: https://www.wowhead.com/spell=42650/army-of-the-dead#comments:id=714121 I believe we do not have it like this, but they definitely can follow

**Comment by al3xc1985** [comment]
I am 100% sure that they should follow...but I am not sure that they should follow u from the moment they are summoned

second, the duration on spell is 10 sec... and a little bit down it says 500 sec... but I believe is that kind of 9,5 - 10 sec cast... we currently (I believe) it is like 8 sec... or please tell me if I count wrong

**Comment by killerwife** [comment]
The duration in 3.3.5 is 4 seconds for the channel which seems to correspond to what gamepedia says.

**Comment by al3xc1985** [comment]
And what about the moment after summoning? Îs there a small delay untill they follow?

**Comment by al3xc1985** [comment]
Than I will let it for refference

**Comment by al3xc1985** [comment]
@cyberium poke in here for just some info please...

**Comment by Nytanath** [comment]
It is possible that the ghouls should stay still during their spawning animation, but they definitely follow the player afterwards if not in combat.

I could only find [this video](https://youtu.be/zC_GdPSHNnk?t=21), it's a bit hard to see covered by the text, but on the right a ghoul spawns and does not move to attack the boss until his spawning animation is over.

**Comment by killerwife** [comment]
Oh yeah, I noticed that the taunt aura is placed on them after several seconds, which likely accounts for the spawning animation.

**Comment by al3xc1985** [comment]
exactly, this is the missing part

**Comment by killerwife** [comment]
Resolved it by disabling follow movement for 5 seconds until after the taunt is started.
