### ISSUE TITLE
🐛 [WOTLK] Improve Shields ~Shaman Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2676]
### Bug Details

I didn't know how to name this report.
So the talent works PERFECT

One thing I noticed and I believe is GENERAL in some cases.. The buff tooltip on the right corner near the minimap does not change with the values modified by the talent

### Steps to Reproduce

1.enhancement shaman
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
I believe this is non issue. I do not know of any way how to send it. It was fixed in Cataclysm by spell attribute 8 Aura Points On Client
