### ISSUE TITLE
🐛 [Bug Report] Corrupted Ashbringer is missing Ashbringer buff/aura [Classic/TBC]

### ISSUE THREAD

**Issue by Retrias** [cmangos/issues#2689]
### Bug Details

Corrupted Ashbringer is missing Ashbringer buff/aura when sword is equipped by player it should have a buff and player will become darker similar to priest shadowform this bug is present both on classic and tbc cmangos core I'm using latest compiled version of cmangos and also using the latest version of SSP bug is present in both link to the spell on wowhead. https://classic.wowhead.com/spell=28282/ashbringer

### Steps to Reproduce

1.Just equipe sword and will see nothing happens

### Core SHA1 Commit Hash

0f90b49385d7daa2d2468221cd70b0e6c6128566

### Database SHA1 Commit Hash

0f90b49385d7daa2d2468221cd70b0e6c6128566

### Operating System

Win 10

### Client Version

1.1.12 (Classic)

**Comment by killerwife** [comment]
@MantisLord check this one out

**Comment by celguar** [comment]
@MantisLord vmangos uses this approach instead of hackfix/remove hackfix. I checked and it worked in both vanilla/tbc. Would you be so kind to check it out, I don't want to make PR as it's not my code and I don't know the background of how it works. Maybe you do so you can decide :)

**Comment by celguar** [comment]
Hm, I guess if db was an issue for that specific aura then maybe all other things should be okay. Nvm then 😊

**Comment by MantisLord** [comment]
> Hm, I guess if db was an issue for that specific aura then maybe all other things should be okay. Nvm then 😊

Yeah that's right. It seems a couple years ago, some custom attributes were added for Ashbringer aura 28282 which caused this bug.
Can't remember even why these attributes were added in the first place - it was probably to patch some other issue which is no longer present. Removing this custom change seems safe now after a bit of testing on latest core.

**Comment by Nytanath** [comment]
> Yeah that's right. It seems a couple years ago, some custom attributes were added for Ashbringer aura 28282 which caused this bug.

Wild shot in the dark, but maybe it was to avoid nearby creatures entering and exiting combat instantly with the wielder, even if friendly? I seem to recall a bug like that ages ago.

**Comment by MantisLord** [comment]
> Wild shot in the dark, but maybe it was to avoid nearby creatures entering and exiting combat instantly with the wielder, even if friendly? I seem to recall a bug like that ages ago.

Yep exactly, that was one issue that used to exist in older core or with older version of the spell script.

I also removed that hack as part of the fix:

UPDATE spell_template SET AttributesEx=32, AttributesEx3=131072 WHERE id=28441; -- AB Effect 000, critters/neutral no longer attack

I tested it and it doesn't appear to happen anymore, so probably no longer needed.

**Comment by killerwife** [comment]
Simple answer guys, tbc enumeratedstrings leak. I changed meaning of some attributes and now it works out of the box.
