### ISSUE TITLE
🐛 [WOTLK] Toughness ~Shaman Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2690]
### Bug Details

The talent does not do increase the armor...

### Steps to Reproduce

1.
2.
3.
4.hunter

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Id: 16252
Name: Toughness (Rank 1)
Description: Increases your Stamina by $s1%, and reduces the duration of movement slowing effects on you by $s2%.

I do not see a mention of armor.

**Comment by al3xc1985** [comment]
@killerwife gosh my mistake.. I Guess I was too tired
