### ISSUE TITLE
🐛 [WOTLK] Mirror Image ~Mage Talent & Spell~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2691]
### Bug Details

Mirror have 14 health..

the mirrors should cast differently depending on your talent build as far as I remember...they have special behaviour

### Steps to Reproduce

1.mage2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
There is no evidence in either sniff or in trinitycore or anywhere the spells should change based on spec. I am happily gonna change that opinion when I see a video from wotlk with it.

**Comment by Nytanath** [comment]
[This comment](https://www.wowhead.com/spell=55342/mirror-image#comments:id=1102659) says it should always cast Frostbolt and Fireblast. A glyph to make them cast Arcane Blast was added in Cataclysm, so it's safe to say it doesn't depend on spec.

**Comment by al3xc1985** [comment]
U are right guys. I remember that when I player câtă. Ty
