### ISSUE TITLE
🐛 [WOTLK] Dual Welding ~Shaman Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2693]
### Bug Details

@killerwife I don't see Dual Weilding Talent working, because even thou I have allreay 3% chance to hit... + 6%this talent, on a simple 80 elite (and I am 80 ofcourse) ... I miss a lot with Lava Lash

### Steps to Reproduce

1.
2.
3.
4.
shaman

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Nytanath** [comment]
I can confirm this is not a bug: I tested against a level 80 training dummy, with this debug change:

```diff
diff --git a/src/game/Entities/Unit.cpp b/src/game/Entities/Unit.cpp
index afd4dd5b4..4e9b9e85c 100644
--- a/src/game/Entities/Unit.cpp
+++ b/src/game/Entities/Unit.cpp
@@ -3111,6 +3111,10 @@ MeleeHitOutcome Unit::RollMeleeOutcomeAgainst(const Unit* pVictim, WeaponAttackT
 
     Die<UnitCombatDieSide, UNIT_COMBAT_DIE_HIT, NUM_UNIT_COMBAT_DIE_SIDES> die;
     die.set(UNIT_COMBAT_DIE_MISS, CalculateEffectiveMissChance(pVictim, attType));
+
+    if (IsPlayer())
+        printf("Chance to miss with attType %u: %f\n", attType, CalculateEffectiveMissChance(pVictim, attType));
+
     if (pVictim->GetTypeId() == TYPEID_PLAYER && !pVictim->IsStandState() && CanCrit(attType))
     {
         die.chance[UNIT_COMBAT_DIE_CRIT] = 10000;
```

Results:

Dual wielding as a Tauren (so no +1% hit chance from Draenei racial), without talents:
```
Chance to miss with attType 0: 23.237572
Chance to miss with attType 1: 23.237572
```

1/3 Dual Wielding Specialization:
```
Chance to miss with attType 0: 21.237572
Chance to miss with attType 1: 21.237572
```

2/3:
```
Chance to miss with attType 0: 19.237572
Chance to miss with attType 1: 19.237572
```

3/3:
```
Chance to miss with attType 1: 17.237572
Chance to miss with attType 0: 17.237572
```

Dual Wielding gives a really big miss chance, even against targets at the same level - even with 3% hit from gear and 6% from this talent, it's still a 14% chance of missing each attack!

**Comment by al3xc1985** [comment]
Ok, ty
