### ISSUE TITLE
🐛 [WOLTK] Sentry Totem~Shaman Spell~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2694]
### Bug Details

U just place it down, but u can right click on the buff icon...and nothing

### Steps to Reproduce

1.
2.
3.
4.
shaman

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Closed by https://github.com/cmangos/mangos-wotlk/commit/d1114f540a7cb00944954866f53b43d9fd15a9c0
