### ISSUE TITLE
🐛 [WOTLK] Ancestral Aweykaning ~Shaman Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2695]
### Bug Details

Just a question...The talents works great...

Should a spirit or any entity spawn and do the heal? cause currently no create and anything is spawning...and the spell says that it should

### Steps to Reproduce

1.
2.
3.
4.
shaman

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Yes this is working correctly.
