### ISSUE TITLE
🐛 [Bug Report] [Classic] Protection Paladin Talent Reckoning is not working

### ISSUE THREAD

**Issue by Retrias** [cmangos/issues#2696]
### Bug Details

Protection Paladin talent Reckoning is not working I have done extensive testing with 1/2/3/4/5 talent points assign to it and does not give or store any extra attacks it should be able to store up to 4 extra attacks indefinitely until used after being the victim of a critical strike making your next melee hit 5 times 4 reckoning stacks + 1 white hit, using latest compiled build this talent has not worked to my knowledge since I started using cmangos last year, link to wowhead spell https://classic.wowhead.com/spell=20182/reckoning

### Steps to Reproduce

1.assign talent points to the Reckoning talent

### Expected behavior

you should be able to store up to 4 extra melee attacks indefinitely until used after being the victim of a critical strike

### Core SHA1 Commit Hash

ecc1fe2561622a7ab8e64abb6d82ecebc1d813fd

### Database SHA1 Commit Hash

7671516bd29e5716e3ddda49b582f389a3329240

### Operating System

Windows 10

### Client Version

1.1.12 (Classic)

**Comment by killerwife** [comment]
Duplicate of https://github.com/cmangos/issues/issues/2696
