### ISSUE TITLE
🐛 [WOTLK] Mirror Image ~Mage Spell~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2697]
### Bug Details

The mirrors do not enter comabt with u, when u summon them

### Steps to Reproduce

1.
2.
3.
4.
mage

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Closed by https://github.com/cmangos/mangos-wotlk/commit/4e331b2de3f41f93a44fb7f85f58678b81251052
