### ISSUE TITLE
🐛 [WOTLK] Focused Power ~Priest Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2700]
### Bug Details

The part with increase dmg and healing is not working

### Steps to Reproduce

1.
2.
3.
4.
priest

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Can confirm its working but its easy to miss the 4% increase

**Comment by al3xc1985** [comment]
Ok, ty
