### ISSUE TITLE
🐛 [Bug Report] [TBC] Quel'Serrar Quest Chain Unfired Ancient Blade not turning into Heated Ancient Blade after being hit with Onyxia's Flame Breath

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#2702]
### Bug Details

When you place the unfired blade (https://classic.wowhead.com/item=18489/unfired-ancient-blade) in front of Onyxia and she does her flame breath attack (https://classic.wowhead.com/spell=22904/heated-blade-dnd) on it, it should turn into the heated ancient blade (https://classic.wowhead.com/item=18488/heated-ancient-blade), this isn't working the server throws an error:

Spell entry 22904, effect 0 has EffectImplicitTargetA/EffectImplicitTargetB = TARGET_LOCATION_SCRIPT_NEAR_CASTER, but gameobject or creature are not defined in `spell_script_target`
Spell entry 22904, effect 1 has EffectImplicitTargetA/EffectImplicitTargetB = TARGET_GAMEOBJECT_SCRIPT_NEAR_CASTER, but gameobject are not defined in `spell_script_target`

The next step is to use the heated blade on her when she's dead to get the treated blade (https://classic.wowhead.com/item=18492/treated-ancient-blade), this bit works perfectly.

### Steps to Reproduce

1. Give yourself the unfired blade (.item add .18489)
2. Go to onyxia (.tele onyxia'slair)
3. Engage her and use the item to put it in front of her
4. Wait for her Flame Breath attack

### Expected behavior

The flame breath turns the unfired blade into the heated blade (https://classic.wowhead.com/object=179562/ancient-heated-blade) which you can then loot to get to the next bit of the quest.

### Suggested Workaround

The only way to work around for now is to skip a step and give yourself the heated blade via gm commands.

### Core SHA1 Commit Hash

b4d248d74fe9428608ddf3cff1fd1ba1ccf3b0a1

### Database SHA1 Commit Hash

d2a012ccb54c61a13ee0c153ac77cfaf43fe2b2c

### Operating System

Windows 10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/c8d625edd7521003525335bbf7eea241240219a1
