### ISSUE TITLE
🐛 [WOTLK] Spirit of Redemption ~Priest Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2704]
### Bug Details

Does not work at all. It should transfomr you into a spirit

### Steps to Reproduce

1.
2.
3.
4.
priest

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
I pushed a very small commit that should not do anything.

I tested spirit of redemption by:

speccing into talent on a priest
doing .die 1 on self

and it worked

**Comment by al3xc1985** [comment]
![WoWScrnShot_021822_090045](https://user-images.githubusercontent.com/6240049/154634154-2428c6a1-5749-42e3-a319-1f8ea36f55a7.jpg)

So I redoanloaded core/db ... delete cache...create new db...and still this...
more than that...even in this state...I can't even cast heal spells

**Comment by al3xc1985** [comment]
ok...so I thought that it might bug out with doing it very fast...and than I tried different way.. I leveled a char with .level 39...learned the talent...and all works great...

I believe that something is going wrong..when I level 80 immediatly the server might glich me up with the visual rtansformation because of my computer... ALL WORKS FINE.,,ty
