### ISSUE TITLE
🐛 [WOTLK] Shadowfiend ~Priest Spell~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2708]
### Bug Details

The shadowfiend is not dismised if it is killed by a mob ...it stays on the bar as your current death pet like in hunter case

### Steps to Reproduce

1.
2.
3.
4.
priest

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Gave him 5 second decay timer.

**Comment by killerwife** [comment]
https://github.com/cmangos/wotlk-db/commit/a04c01bc0a062a6fc9218b204d531a697c0b659d
