### ISSUE TITLE
🐛 [WOTLK] Shadow Affinity ~Priest Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2709]
### Bug Details

The part with the 15% mana regen after shadowfiend death is not working...the other part I could not test it with the threat reduction

### Steps to Reproduce

1.
2.
3.
4.
[riest

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
There is no shadowfiend part?

Description: Reduces the threat generated by your Shadow spells by $s1%, and you receive $s2% of your base mana when your Shadow Word: Pain or Vampiric Touch spells are dispelled.

**Comment by al3xc1985** [comment]
where in the world did I read that stupidity that I wrote?...gosh I work too much 14 hours a day

**Comment by al3xc1985** [comment]
closing this...as u did some fixes to shadow affinity the real thing
