### ISSUE TITLE
Q9440 and Cages [Line of Sight]

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#271]
I have a line of sight issue on Quest 9440 and GO 181625 & 181624. Seems you can't use Item 23659 on npcs because of a line of sight issue. If I delete the cages it works. Thanks for any help on this... :)

I tried adding [vmap.ignoreSpellIds = "7720,29917"] in config and it will cast the spell, But, Doesn't give credit.

**Comment by Rog360** [comment]
I thought I had a fix for this by adding spell to cmangos config like below.

     vmap.ignoreSpellIds = "7720,29917"

But, it will let you cast the spell but blocks quest credit. When casting on non-caged npc no credit problem... :(

**Comment by xfurry** [comment]
Which client version? 3.x or 4.x?

**Comment by Grz3s** [comment]
hi... it happens also for 3.x.x
first i removed reqspellcast in quest template (hack)
then i made a script:
```sql
-- Captured Jaguar
Delete from `creature_ai_scripts` where `creature_id`=17111;
Insert into `creature_ai_scripts` values 
('1711101','17111','8','0','100','1','29917','-1','0','0','33','17111','6','6','11','29918','0','4','0','0','0','0','Captured Jaguar - Quest Credit on Spellhit (Quest: 9440)');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '17111';
```
also i added thre spells into vmap.ignoreSpellIds = "7720,29916,29917,29918"

and same problem:
if creature is inside cage... credit is not given.
if creature is outside ... credit will be given to player

this is difficult one. 
Gl @xfurry

**Comment by xfurry** [comment]
Well, this is kind of an impossible one.

The spell doesn't offer any special attribute to avoid LoS and the GOs are type 5 (181624, 181625).

**Comment by Rog360** [comment]
I got it to work as a work around. But changes WDB data... :)

     UPDATE gameobject_template SET type=0 WHERE entry IN(181624,181625);

**Comment by xfurry** [comment]
Do we have any sniff to see which is the correct info about this?

**Comment by ulfgebhardt** [comment]
Fixable with db: https://github.com/cmangos/tbc-db/issues/24

**Comment by killerwife** [comment]
There are spells which fail when NPC is in a cage, there should simply ignore LOS by default. We can now set it inside IsIgnoreLOSSpell helper function in core. @robinsch found out that there are many spells like this especially for questgivers who are in cages. I think it would be safe to add these 3-4 spells to that helper function. The DB core is a hack, until a sniff is provided, because we do not alter gameobject_template without sniffed data. (and if we do, its not because of LOS issues)

**Comment by ulfgebhardt** [comment]
This Quest cant be sniffed anymore http://www.wowhead.com/quest=9440/deprecated-little-morsels

`This quest was marked obsolete by Blizzard and cannot be obtained or completed.`

And the Cage has an opening Animation. I think its save to assume that back then the Cages could be opened, but later sniffs have that ability removed due the fact the Quest was removed.

**Comment by robinsch** [comment]
Just check out Joanas leveling videos. The cage could be opened, but it's not required in order to receive the buffs. https://youtu.be/OAA86_GuQ7E?t=1h19m30s

**Comment by cyberium** [comment]
Should be fixed
