### ISSUE TITLE
🐛 [WOTLK] Shadowform ~Priest Spell~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2711]
### Bug Details

Shadow form cooldown it's getting bugged after u exit shadowform and cast heal spell

### Steps to Reproduce

1.
2.
3.
4.
priest

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Which heal spell. I tried flash heal and it works fine.

**Comment by al3xc1985** [comment]
with heal spell I tried...but at that moment...even clones and dk ghouls..were not working...so after I downloaded and reinstalled everything... it is all clear...ty
