### ISSUE TITLE
🐛 [WOTLK] Tactical Mastery ~Warrior Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2715]
### Bug Details

1.There should be a rage consumtion when u change stances...and this talent should retain.
2.The talent does not retain
3.The stances does not consume rage
4.I don't know if threat part is working

### Steps to Reproduce

1.
2.
3.
4.
warrior

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Please retest, should all be working now.

**Comment by al3xc1985** [comment]
works..perfect
