### ISSUE TITLE
🐛 [WOTLK] Poleaxe Specialization ~Warrior Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2718]
### Bug Details

Shoudln\t the crit and dmg be applied on the stas when u press C? I mean with all points in it, I don't see any change.]

More than that..even tested on white dmg I don;t see any crit or dmg increase

### Steps to Reproduce

1.
2.
3.
4.
warrior

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
I think we talked about a similar issue where the % dmg mod wasnt being shown when it only applied to a specific weapon and we compared on classic. I would assume a similar thing here (that it should not show). That being said, I will test it in debug mode that we apply it properly during calculations

**Comment by killerwife** [comment]
I tested it, and it updates for me when I have a polearm equipped. When I dont, nothing changes.
