### ISSUE TITLE
🐛 [WOTLK] Improve Mortal Strike ~Warrior Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2719]
### Bug Details

@killerwife can u help me with this one...I tried a lot of hits with mortal strike,..and I can't see the increase of dmg

### Steps to Reproduce

1.
2.
3.
4.
warrior

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Checked it, the 10% applies as intended
