### ISSUE TITLE
🐛 [WOTLK] Juggernaut ~Warrior Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2720]
### Bug Details

Does not work beside the duration increase

### Steps to Reproduce

1.
2.
3.
4.
warrior

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-wotlk/commit/e53f7281515724b6a8923bb9352d6222a1474e46 Fixed by and also a db commit https://github.com/cmangos/wotlk-db/commit/c21ef7c678ddb74d270cd448e1d9023824a1b273
