### ISSUE TITLE
🐛 [WOTLK] Unbridled Wrath ~Warrior Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2724]
### Bug Details

Currently at max rank 5 it only gives u +1 Rage.... it should give u more based on rank

### Steps to Reproduce

1.
2.
3.
4.
war

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Incorrect.


Id: 13002
Name: Unbridled Wrath (Rank 5)
Description: Gives you a chance to generate an additional rage point when you deal melee damage with a weapon. Effect occurs more often than Unbridled Wrath (Rank 4).

Only the procchance changes.

**Comment by al3xc1985** [comment]
I understande. Ok.ty
