### ISSUE TITLE
🐛 [WOTLK] Bloodrage ~Warrior Spell~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2725]
### Bug Details

The bloodrage should generate 15 rage talented over time...currently it does only 10

### Steps to Reproduce

1.
2.
3.
4.
war

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
I have rechecked this, first I used bloodrage without talents, which does 20 and 10 respectively, and then I talented it, It gave me 30 and 15, which seems to be what it should be.

![image](https://user-images.githubusercontent.com/7995382/154804814-f64c56cd-7558-4445-9545-d40fa58b26ac.png)

This is talented tooltip.

**Comment by al3xc1985** [comment]
@killerwife check If it gives 15 rage in 10 sec. It will not gives 15. Îinnstead IT gives only 10

**Comment by killerwife** [comment]
It gave me 15 locally.

**Comment by al3xc1985** [comment]
ok.. I counted 10...but I might be wrong..ty
