### ISSUE TITLE
🐛 [WOTLK] Vigilance ~Warrior Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2727]
### Bug Details

Can u check if this talents works somehow from the code? I don't have a group to test it

### Steps to Reproduce

1.
2.
3.
4.
war

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Fixed in https://github.com/cmangos/mangos-wotlk/commit/f3755e7e5d4d4aad57a906a1dcaa7d941007180e
