### ISSUE TITLE
🐛 [Wotlk] Critical Block ~warrior talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2729]
### Bug Details

it doesn't proc or it doesn't  double the dmg blocked at all...and I didn't saw to increase the crit of shield slam..
I am not sure about the second part cause it's a thing of numbers and 15% is not much...but first thing with block it doesn't do it

### Steps to Reproduce

1.
2.
3.
4.
war

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Fixed by https://github.com/cmangos/mangos-wotlk/commit/4bcc2b5db18ce0451671a1a6b46324887c0c8ff5
It already worked for autoattacks
