### ISSUE TITLE
🐛 [Wotlk] Curse of Doom ~warlock Spell~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2730]
### Bug Details

![WoWScrnShot_021922_095530](https://user-images.githubusercontent.com/6240049/154792372-f8def96f-4b75-486a-a104-f83e67785ab0.jpg)

1.Target dies by the spell...look how many are spawned at once ::)))))
2.Second thing is that... I believe that it should be under my command
3.They despawn very fast...they should be under your command for a period of time...not like 5 seconds in my case

### Steps to Reproduce

1.
2.
3.
4.
warlock

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
should u use enslave demon to enslave this demon? ... 
of course that it should be summoned only one... but just asking

**Comment by killerwife** [comment]
Fixed this yday to only spawn one and to spawn it on the target. Yes, you need to enslave it after yourself, I checked official 3.3.5 data
