### ISSUE TITLE
🐛 [WOTLK] Malediction ~Warlock Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2733]
### Bug Details

It should increase Spell dmg by 3% but it doesn't 

### Steps to Reproduce

1.
2.
3.
4.
warlock

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Ok I rechecked it, we send correct field update to client but I dont know where its supposed to be shown for SPELL_AURA_MOD_DAMAGE_PERCENT_DONE or if at all. We also add correct 3% during calculations. So working as intended but maybe im visually missing smth.

**Comment by al3xc1985** [comment]
Ok ty
