### ISSUE TITLE
🐛 [Bug Report] Mechanar Map Bug [TBC]

### ISSUE THREAD

**Issue by ckj777** [cmangos/issues#2734]
### Bug Details

Mobs in Mechanar "Nethermancer Sepethrea" area do not move due to map bug

https://www.youtube.com/watch?v=0pqaOYOkEfM

### Steps to Reproduce

1.
2.
3.
4.

### Crash Log

No response

### Core SHA1 Commit Hash

6da3d6fbb1333724062055243c414c5446e9f9ca

### Database SHA1 Commit Hash

89ade75e47d1a03d2f8c7a861c6e0a51915282b3

### Operating System

Windows 10 x64

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Linked a commit, reextract mmaps with the linked commit and should be fixed.
