### ISSUE TITLE
🐛 [Bug Report] [WoTLK] Mangos database update version '14049_01_mangos_unitflags2'

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2735]
### Bug Details

database/wotlk/Updates/3709_unitflags2.sql increments wotlkmangos db_version to `14049_01_mangos_unitflags2` yet mangos is still looking for `14048_01_mangos_waypoint_pathl`

### Steps to Reproduce

1.start mangosd
2.
3.
4.

### Expected behavior

mangosd and database to be at same version

### Suggested Workaround

remove statement from database/wotlk/Updates/3709_unitflags2.sql 
~~~
1 - ALTER TABLE db_version CHANGE COLUMN required_14048_01_mangos_waypoint_path required_14049_01_mangos_unitflags2 bit;
~~~
or update mangosd version 'cmangos/wotlk/sql/shared/revision_sql.h
~~~
1     #ifndef __REVISION_SQL_H__
2     #define __REVISION_SQL_H__
3     #define REVISION_DB_REALMD "required_14039_01_realmd_anticheat"
4     #define REVISION_DB_LOGS "required_14039_01_logs_anticheat"
5     #define REVISION_DB_CHARACTERS "required_14044_01_characters_extend_state"
6  -  #define REVISION_DB_MANGOS "required_14048_01_mangos_waypoint_path"
6  +  #define REVISION_DB_MANGOS "required_14049_01_mangos_unitflags2"
7     #endif // __REVISION_SQL_H__
~~~

### Crash Log

~~~
SQL: SELECT required_14048_01_mangos_waypoint_path FROM db_version LIMIT 1
query ERROR: Unknown column 'required_14048_01_mangos_waypoint_path' in 'field list'
The table `db_version` in your [WORLD] database indicates that this database is out of date!

  [A] You have: --> `14049_01_mangos_unitflags2.sql`

  [B] You need: --> `14048_01_mangos_waypoint_path.sql`

You must apply all updates after [A] to [B] to use mangos with this database.
These updates are included in the sql/updates folder.
Please read the included [README] in sql/updates for instructions on updating.
~~~

### Core SHA1 Commit Hash

Using commit hash(1376d26a1b6180e77f087e82d36c953e31a6f079)

### Database SHA1 Commit Hash

Using commit hash(a04c01bc0a062a6fc9218b204d531a697c0b659d)

### Operating System

Ubuntu 20.04.3 Server LTS, WIndows 7 Client

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by adellaci** [comment]
When i apply either fix mangod starts coming but end up with and errror @ `Loading Creature templates...`
~~~
Error in creature_template table, probably sql file format was updated (there should be 93 fields in sql).

terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
~~~

**Comment by killerwife** [comment]
It sounds like you did not recompile.

**Comment by adellaci** [comment]
I did recompile. I'll wipe my folders and clone fresh

**Comment by killerwife** [comment]
Cos I am working on the core right now and everything is working perfectly with that update

**Comment by adellaci** [comment]
Okay i delete the database and wotlk, cloned again and processed. Everything works right. That is odd that i pulled this morning and it didn't update correctly. Non the less it's all good
