### ISSUE TITLE
Nonworking spells invoked by Quest Items with  EffectImplicitTargetA=TARGET_SCRIPT and EffectImplicitTargetB=TARGET_SELF [Classic]

### ISSUE THREAD

**Issue by Neotmiren** [cmangos/issues#274]
There are 4 spells in SPELL.DBC with stated combination of parameters. Because of supposedly incorrect processing in Mangos Core the corresponding quests cannot be completed.

Tested two of these quests:
http://www.wowwiki.com/Quest:The_Only_Cure_is_More_Green_Glow  (remains opened issue in TC https://github.com/TrinityCore/TrinityCore/issues/1723 from 2011)
http://www.wowwiki.com/Quest:A_Taste_of_Flame_(3)

The resulting items 
http://www.wowwiki.com/High_Potency_Radioactive_Fallout
http://www.wowwiki.com/Encased_Fiery_Essence

cannot be obtained.

It is worthy of note that similar spells with swapped parameters EffectImplicitTargetA=TARGET_SELF and EffectImplicitTargetB=TARGET_SCRIPT work correctly. And strangely enough there are few places of coded in  Spell.cpp and SpellMgr.cpp with asymmetic conditonal tests like

if (spellInfo->Effect[j] && (spellInfo->EffectImplicitTargetA[j] == TARGET_SCRIPT || spellInfo->EffectImplicitTargetA[j] != TARGET_SELF && spellInfo->EffectImplicitTargetB[j] == TARGET_SCRIPT)))

After 3 places of code in  Spell.cpp and SpellMgr.cpp  are symmetrized by adding
&& m_spellInfo->EffectImplicitTargetB[j] != TARGET_SELF
to the first TARGET_SCRIPT test, the two aforementioned quests become fully working.

**Comment by cala** [comment]
Bump to myself to test this patch.

**Comment by Schmoozerd** [comment]
Hmm, i think the logic with this target-combination is:
1) use TARGET_SCRIPT as check if one is at proper position
2) use SELF as actual target.

Hence i suggest the following fix based on xfurry's patch: http://paste2.org/BLz0IVgz
