### ISSUE TITLE
🐛 [Bug Report][Server Log] "Invalid poly ref in BuildPolyPath"

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2740]
### Bug Details

Once the server was up and running i received an error in the BuildPolyPath. Every so often the error repeats

### Steps to Reproduce

1. start mangosd
2. wait a few second after server is completely up
3.
4.

### Expected behavior

no error in map

### World Server Log

```
Invalid poly ref in BuildPolyPath. polyLength: 2, pathStartIndex: 0, startPos: (1600.3, -6236.03, 5.8181), endPos: (1612.45, -6237.42, 6.65087), mapId: 571
Invalid poly ref in BuildPolyPath. polyLength: 2, pathStartIndex: 0, startPos: (11651, -7093.27, 10.3509), endPos: (11677.3, -7099.76, 14.3882), mapId: 530
Invalid poly ref in BuildPolyPath. polyLength: 2, pathStartIndex: 0, startPos: (11852.3, -7082.48, 28.6983), endPos: (11852, -7095.88, 28.7391), mapId: 530
Invalid poly ref in BuildPolyPath. polyLength: 2, pathStartIndex: 0, startPos: (2018.7, -4511.15, 74.703), endPos: (2008.06, -4529.09, 73.6226), mapId: 0
Invalid poly ref in BuildPolyPath. polyLength: 2, pathStartIndex: 0, startPos: (3256.17, -3392.97, 141.138), endPos: (3258.14, -3375.89, 143.759), mapId: 0
```

### Core SHA1 Commit Hash

Using commit hash(3b56de2a145a3b0c36a37e29b34d1883f07687f5)

### Database SHA1 Commit Hash

Using commit hash(a04c01bc0a062a6fc9218b204d531a697c0b659d)

### Operating System

Ubuntu 20.04.3 Server LTS, WIndows 7 Client

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
Mostly meaningless output, as often times nothing is going wrong when you teleport to these locations, started happening with Detour Updates.

**Comment by adellaci** [comment]
This error did not show up when started server 1/13/2024
CMaNGOS-Core revision : 27999d818ce8b308e30a24526b7705335d5b3dbc
WoTLK-Database revision : b276c0f5b99b0daaca23edd4117eac5c1f73c960
