### ISSUE TITLE
🐛 [Bug Report] Classic void PathFinder::BuildPolyPath bug

### ISSUE THREAD

**Issue by cbcs** [cmangos/issues#2742]
### Bug Details

worldserver print

Invalid poly ref in BuildPolyPath. polyLength: 2, pathStartIndex: 0, startPos: (2018.7, -4511.15, 74.703), endPos: (2008.06, -4529.09, 73.6226), mapId: 0
Invalid poly ref in BuildPolyPath. polyLength: 2, pathStartIndex: 0, startPos: (3256.17, -3392.97, 141.138), endPos: (3258.14, -3375.89, 143.759), mapId: 0

after running the server 

### Steps to Reproduce

1.start server
2.In a few minutes

### Core SHA1 Commit Hash

https://github.com/cmangos/mangos-classic/commit/1884a75d5ed8d31305a751777267e2bd2e9443bd

### Database SHA1 Commit Hash

Last DB

### Operating System

Win10

### Client Version

1.1.12 (Classic)

**Comment by al3xc1985** [comment]
there are some of those in wotlk db too

**Comment by al3xc1985** [comment]
# # #2740
