### ISSUE TITLE
🐛 [Bug Report] [WoTLK] Error, Loading Gameobject Data

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2743]
### Bug Details

Error when server starting up with one entry in Gameobject

### Steps to Reproduce

1. start mangosd
2. wait till loading gamobject data
3.
4.

### Expected behavior

Load Gameobject Data without error

### Suggested Workaround

N/A

### Crash Log

~~~
2022-02-19 13:43:55 Loading Gameobject Data...
2022-02-19 13:43:56 ERROR:Table `gameobject` has gameobject (GUID: 2300116) with non existing gameobject entry 181074, skipped.
2022-02-19 13:43:56 >> Loaded 103537 gameobjects
~~~

### Core SHA1 Commit Hash

Using commit hash(3b56de2a145a3b0c36a37e29b34d1883f07687f5)

### Database SHA1 Commit Hash

Using commit hash(a04c01bc0a062a6fc9218b204d531a697c0b659d)

### Operating System

Ubuntu 20.04.3 Server LTS, WIndows 7 Client

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Is there any video of Gurubashi Arena from wotlk? This is the chest for gurubashi if I am correct.

**Comment by adellaci** [comment]
According to wowhead classsic/tbc/retail Gurubashi Arena Chest should be object=179697/arena-treasure-chest. I'm still looking around

**Comment by AnonXS** [comment]
It's dungeon set chest in BRD <https://tbc.wowhead.com/object=181074/arena-spoils>

**Comment by killerwife** [comment]
Oh, nice one. Push it to WDB if you can anon. And close this. The rest of the updates can wait but atm we have many startup errors in wotlk so need to maintain it a bit before grz3s comes back.

**Comment by killerwife** [comment]
https://github.com/cmangos/wotlk-db/commit/06e7e55d472bb2e6e9728e8f01c34d6b76e7d374 fixed one

https://github.com/cmangos/wotlk-db/commit/f43187f406f48f567704e68be94bd9a134d511fb fixed other, closing
