### ISSUE TITLE
🐛 [Bug Report] Current implementation for breadcrumb quests is wrong

### ISSUE THREAD

**Issue by Nytanath** [cmangos/issues#2745]
### Bug Details

Breadcrumb quests are quests that lead you to other quests. They are optional - if you accept one, you can complete it and take the next step. Or you can take the next step already, and the breadcrumb becomes unavailable.

An example is [Rude Awakening](https://classic.wowhead.com/quest=363/rude-awakening) and [The Mindless Ones](https://classic.wowhead.com/quest=364/the-mindless-ones). Nothing should stop you from skipping the first undead NPC you meet and taking The Mindless Ones from the next quest giver. But then you can't do Rude Awakening. Not ideal, but an option nonetheless.

Right now on CMaNGOS breadcrumbs are instead treated as normal quests: you can't take the next step unless you do the breadcrumb first.

This could be fixed by a bunch of conditions for each breadcrumb quest, but a more general system might be better considering this is a widely understood aspect of the quest system.

More info:
https://github.com/TrinityCore/TrinityCore/issues/22264
https://github.com/TrinityCore/TrinityCore/issues/20452

How it was fixed in TC:
https://github.com/TrinityCore/TrinityCore/commit/5ed77113b637c49e99a610b00f385c51da67c3bf

List of breadcrumb quests in Classic, made by a Reddit user: https://www.reddit.com/r/classicwow/comments/cukd01/list_of_breadcrumbs_quests/

### Steps to Reproduce

1. Create an Undead character.
2. .go creature id 1569
3. Try to take the quest The Mindless Ones, notice you can't because it has a breadcrumb quest.
4. Compare this behavior to retail, where you can grab The Mindless Ones regardless.

### Expected behavior

Breadcrumbs are optional, not required.

### Core SHA1 Commit Hash

cbaf1b9cdacbcf61cbb1fa84e3a3620695127c8d

### Database SHA1 Commit Hash

127231a5413902c196e6a976a7a6082c8554674d

### Operating System

Windows 10, x64

### Client Version

1.1.12 (Classic)

**Comment by killerwife** [comment]
I am not opposed to this solution. As we do not have quest_template_addon, just make a PR and add it to quest_template after ExclusiveGroup. The guest code between TC and cmangos is largely identical with same functions.

**Comment by AnonXS** [comment]
This was implemented, now the actual data has to be adjusted.

https://tbc.wowhead.com/quest=11036/out-of-this-world-produce#comments:id=5238803

```
 the breadcrumb quests for Shadowmoon Valley, the breadcrumbs for 
Netherstorm are mutually exclusive. These breadcrumb quests are as 
follows:<br><br><a href="https://tbc.wowhead.com/quest=11037/a-strange-vision">A Strange Vision</a> from <a href="https://tbc.wowhead.com/npc=23265/seer-nakha">Seer Nakha</a> in Nagrand<br><a href="https://tbc.wowhead.com/quest=11036/out-of-this-world-produce">Out of This World Produce</a> from <a href="https://tbc.wowhead.com/npc=19471/old-orok">Old Orok</a> in Balde's Edge Mountains<br><br><a href="https://tbc.wowhead.com/quest=11039/report-to-spymaster-thalodien">Report to Spymaster Thalodien</a> from <a href="https://tbc.wowhead.com/npc=23273/arcanist-raestan">Arcanist Raestan</a> or <a href="https://tbc.wowhead.com/npc=23272/arcanist-savan">Arcanist Savan</a> in Shattrath<br><a href="https://www.wowhead.com/quest=11038/assist-exarch-orelis">Assist Exarch Orelis</a> from <a href="https://www.wowhead.com/npc=23270/vindicator-aeus">Vindicator Aeus</a> and <a href="https://www.wowhead.com/npc=23271/vindicator-kaan">Vindicator Kaan</a> at Shattrath<br><br><a href="https://tbc.wowhead.com/quest=10183/off-to-area-52">Off to Area 52</a> from <a href="https://tbc.wowhead.com/npc=19569/netherologist-coppernickels">Netherologist Coppernickles</a> in Netherstorm<br><br>Please note that <i>Report to Spymaster Thalodien</i> is a Scryer's quest, and may not be available for Aldar. For Scryers, this means it also rewards 10 reputation. Likewise, <i>Assist Exarch Orelis</i> is an Aldar quest with the same conditions.<br><br>Please also note that <i>Off to Area 52</i>
 rewards 2g 83s compared to the 69s of the other breadcrumbs. Although 
this quest is technically in Netherstorm, it's actually on the 
Gyro-plank bridge to Netherstorm from Blade's Edge.<br><br>Fun Fact: <i>Off to Area 52</i> used to award 1g and had <a href="https://tbc.wowhead.com/quest=10260/netherologist-coppernickels">it's own breadcrumb</a> that awarded 1g 86s but that quest never made it out of beta.</div><!--EndFragment-->
</body>
</html>By [Wyr3d](https://tbc.wowhead.com/user=Wyr3d) [on 2021/08/18](https://tbc.wowhead.com/quest=11036/out-of-this-world-produce#comments:id=5238803) (Burning Crusade)		
Like the breadcrumb quests for Shadowmoon Valley, the breadcrumbs for Netherstorm are mutually exclusive. These breadcrumb quests are as follows:

[A Strange Vision](https://tbc.wowhead.com/quest=11037/a-strange-vision) from [Seer Nakha](https://tbc.wowhead.com/npc=23265/seer-nakha) in Nagrand
[Out of This World Produce](https://tbc.wowhead.com/quest=11036/out-of-this-world-produce) from [Old Orok](https://tbc.wowhead.com/npc=19471/old-orok) in Balde's Edge Mountains

[Report to Spymaster Thalodien](https://tbc.wowhead.com/quest=11039/report-to-spymaster-thalodien) from [Arcanist Raestan](https://tbc.wowhead.com/npc=23273/arcanist-raestan) or [Arcanist Savan](https://tbc.wowhead.com/npc=23272/arcanist-savan) in Shattrath
[Assist Exarch Orelis](https://www.wowhead.com/quest=11038/assist-exarch-orelis) from [Vindicator Aeus](https://www.wowhead.com/npc=23270/vindicator-aeus) and [Vindicator Kaan](https://www.wowhead.com/npc=23271/vindicator-kaan) at Shattrath

[Off to Area 52](https://tbc.wowhead.com/quest=10183/off-to-area-52) from [Netherologist Coppernickles](https://tbc.wowhead.com/npc=19569/netherologist-coppernickels) in Netherstorm

Please note that Report to Spymaster Thalodien is a Scryer's quest, and may not be available for Aldar. For Scryers, this means it also rewards 10 reputation. Likewise, Assist Exarch Orelis is an Aldar quest with the same conditions.

Please also note that Off to Area 52 rewards 2g 83s compared to the 69s of the other breadcrumbs. Although this quest is technically in Netherstorm, it's actually on the Gyro-plank bridge to Netherstorm from Blade's Edge.

Fun Fact: Off to Area 52 used to award 1g and had [it's own breadcrumb](https://tbc.wowhead.com/quest=10260/netherologist-coppernickels) that awarded 1g 86s but that quest never made it out of beta.
```

**Comment by AnonXS** [comment]
Was merged with https://github.com/cmangos/mangos-tbc/commit/ed29981c2fb645132fed47e97156d58ecd56b1e1 - now up to db devs to fix more issues, maybe even port from TC.
