### ISSUE TITLE
🐛 [WOTLK] Inferno ~Warlock Spell~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2748]
### Bug Details

The inferno spell when u cast it , it summons 100 infernals under your command...anything is oneshotted...

also, it must stun and have fire dmg aura as far as I know also...currently it doesn't have anything..and should be only 1

### Steps to Reproduce

1.
2.
3.
4.
warlock

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
3 separate issues all resolved.
