### ISSUE TITLE
🐛 [WOTLK] Poisons ~Rogue Spell~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2749]
### Bug Details

The spell that opens a new system for rogues do not work

### Steps to Reproduce

1.
2.
3.
4.
rogue

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
can't test the reset of assasination talent tree without this one...the other 2 are allready tested

**Comment by killerwife** [comment]
[Patch 3.0.2](https://wowpedia.fandom.com/wiki/Patch_3.0.2) (2008-10-14): Damaging poisons now scale with attack power. Poisons skill removed. All finished poisons are available on vendors rather than created by the rogue. ?

**Comment by al3xc1985** [comment]
Ok, retesting

**Comment by al3xc1985** [comment]
found...testing
