### ISSUE TITLE
Priest Dismounts around Aspect of the Pack

### ISSUE THREAD

**Issue by Nett118** [cmangos/issues#275]
When hunters approach with aspect of the pack buff on them while my priest is mounted I am immediately dismounted. I watched other members of the group to see if they were effected by it and it seems that only priests are, however, I am not sure of warlocks or mages as we do not have these characters.

**Comment by Nett118** [comment]
I'm not saying it should be applied to mounted players, only that it dismounts players that are mounted on cats, like this one: http://www.wowhead.com/spell=42777; but does not dismount nearby horse mounted players. 
Buffs such as levitate dismounts all players and I believe aspect should as well.
Thank you so much for everything thus far.

**Comment by Warlockbugs** [comment]
Aura stacking is under major rewrite at the moment and this issue is already fixed in upcoming update.

**Comment by Warlockbugs** [comment]
"Same icon" stuff is no longer the case as of:
https://github.com/cmangos/mangos-tbc/commit/f14a867aa666df8869f9cf8d37ae654389d35ba9
https://github.com/cmangos/mangos-classic/commit/0206d01e4c31ae1a0795c191f60615bb25829277
