### ISSUE TITLE
🐛 [WOTLK] Shadow Dance ~Rogue Spell~ 

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2751]
### Bug Details

All works fine except one thing... when u have this spell... it is automatically added near stealth spell above the actionbar, and u won;t be able to use stealth again, after u use it once or twice...

### Steps to Reproduce

1.
2.
3.
4.
rogue

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
I linked a commit with which I reproduced it, but without that, i cant reproduce it anymore. Let me know.

**Comment by al3xc1985** [comment]
perfect working
