### ISSUE TITLE
🐛 [WOTLK]  Prey on the Weak ~Rgue Talent~

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2755]
### Bug Details

This needs a special case

### Steps to Reproduce

1.
2.
3.
4.
rogue

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Note, the buff is invisible and not seen anywhere in UI. I tested manually and debugged that it works as intended.

**Comment by al3xc1985** [comment]
will retest
