### ISSUE TITLE
🐛 [Bug Report] Warlock Succubus pet stats are a little off

### ISSUE THREAD

**Issue by Nytanath** [cmangos/issues#2756]
### Bug Details

I made a Warlock on the Classic PTR and created one in CMaNGOS with the exact same equip. Then checked the stats for the Succubus. Those are the results:

Retail:
![WoWScrnShot_022022_182722](https://user-images.githubusercontent.com/99603810/154855863-b7b65759-d3ea-44ab-b259-79957f8b303a.jpg)

![WoWScrnShot_022022_182735](https://user-images.githubusercontent.com/99603810/154855866-9e9b73e1-456e-4ff2-9f8c-a903fb90108a.jpg)

CMaNGOS:

![WoWScrnShot_022022_182725](https://user-images.githubusercontent.com/99603810/154855939-c9919666-4bce-437d-832a-a42d63ccf544.jpg)

![WoWScrnShot_022022_182729](https://user-images.githubusercontent.com/99603810/154855943-b2d4f9c3-d43a-496e-a96d-c223253ec058.jpg)

The only difference from the CMaNGOS player paperdoll is the ranged attack, that shows as "1 - 1 + 227" which is a graphical bug but unrelated to this issue.

Compared to my Retail's Succubus, my CMaNGOS Succubus has:
+1 Strength
+2 Agility
-2 Stamina
+36 Intellect
-52 Spirit
+2 Attack Power
-279‬ Armor

Her health and mana values are wildly wrong, too.
Retail has: 1814 Health, 1874 Mana.
CMaNGOS has: 1196 Health, 1442 Mana.

The equipment used is as follows:
.additem 16808
.additem 13141
.additem 16807
.additem 12968
.additem 16809
.additem 16804
.additem 16805
.additem 16806
.additem 16810
.additem 16803
.additem 13345
.additem 13096
.additem 12930
.additem 11832
.additem 18842
.additem 13396

No talents, no enchants, no buffs aside from the Demonic Ally buff that the Succubus has from the tier set bonus.

If you're testing on an Undead like me you'll need to .learn 227 to use staves.

.learn 712 to learn Succubus
.additem 6265 to get a Soul Shard

If there's some more testing required, let me know.

### Steps to Reproduce

Create an Undead Warlock, equip the items mentioned above, check the difference from Retail

### Core SHA1 Commit Hash

cbaf1b9cdacbcf61cbb1fa84e3a3620695127c8d

### Database SHA1 Commit Hash

127231a5413902c196e6a976a7a6082c8554674d

### Operating System

Windows 10, x64

### Client Version

1.1.12 (Classic)

**Comment by killerwife** [comment]
As vanilla doesnt have pet scaling, I would guess pet_levelstats is largely wrong.

**Comment by Nytanath** [comment]
> vanilla doesnt have pet scaling

Oh nice, I didn't know that. Makes it easier to test it then.

I checked pet_levelstats, the str/agi/stam/int/spirit can be easily adjusted; but I see hp and mana have the correct values (1709 hp and 1874 mana). While in-game they're roughly 3/4 of what the table says.

**Comment by killerwife** [comment]
Amalgamation of passing down from wotlk or tbc. I fixed up shadowfiend on tbc some time ago from sniffs but it was an insane endeavour and only like 61-70 and there is a ton of other pets :D

Question is why they are off ingame

**Comment by Nytanath** [comment]
The issue is here: https://github.com/cmangos/mangos-classic/blob/master/src/game/Entities/Pet.cpp#L1367

It only excludes hunter pets from using creature_template's multipliers, and I guess those values for Warlock pets are sniffed from pets summoned by creatures? Excluding SUMMON_PET from that calculation fixes values for player-summoned demons, but I'm not sure how it should work for creature-summoned ones.

**Comment by killerwife** [comment]
SUMMON_PET is only set for player pets :) So ur safe.

**Comment by Nytanath** [comment]
Oh nice, thanks :D
