### ISSUE TITLE
4.3.4: All Profession Trainers (Limit Trainer List To Specific Professions)

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#276]
in 4.x a new type of NPC was introduced. It is an all profession trainer. They teach more then 1 profession based on the gossip you select for a specific profession. When you then go to that trainer list it should only display spells for that profession.

Currently it just always show ALL spells for all professions without any kind of filter.

I am requesting an additional support of some kind from gossip to trainer list to be able to limit to specific professions.

Thank You.

**Comment by cyberium** [comment]
CMaNGOS officially stop cata development.
