### ISSUE TITLE
🐛 [Bug Report] In Classic, Warlock pets should be unsummoned when trying to summon another demon

### ISSUE THREAD

**Issue by Nytanath** [cmangos/issues#2762]
### Bug Details

When you try to summon a Demon while having another one out, your current demon should be despawned and it should not refund a Soul Shard. Right now the old demon is despawned only after the other demon's summon spell finishes.

In TBC doing this gives a 5 second stun on the demon, but in Classic it should despawn outright.

### Steps to Reproduce

1. Create a Warlock.
2. Summon a pet.
3. Try to summon another pet.

### Core SHA1 Commit Hash

cbaf1b9cdacbcf61cbb1fa84e3a3620695127c8d

### Database SHA1 Commit Hash

127231a5413902c196e6a976a7a6082c8554674d

### Operating System

Windows 10, x64

### Client Version

1.1.12 (Classic)

**Comment by killerwife** [comment]
Vanilla can be fixed by moving SPELL_ATTR_EX_DISMISS_PET implementation in Spell::Cast to Spell::Prepare, TBC stun needs to be scripted. After the 5 second stun it despawns? What if spellcast for summon in tbc is 10 seconds long as by default.

**Comment by killerwife** [comment]
Also confirmed in vanilla the spell attr is on prepare.

[Patch 1.1.1](https://wowpedia.fandom.com/wiki/Patch_1.1.1) (2004-11-17): Now dismisses your pet before casting to allow the Infernal to start Enslaved. Usable outdoors only.

https://wowpedia.fandom.com/wiki/Inferno_(warlock_ability)

As usual, feel free to throw down a PR for all of this.

**Comment by Nytanath** [comment]
[This is the spell](https://tbc.wowhead.com/spell=32752/summoning-disorientation). Just checked on TBC Classic, the duration is indeed 5 seconds and the pet does not get despawned at the end. You can still use the old pet's spells from when the stun expires to when you finish summoning the new pet.

I don't understand what's the point but that's how it is :P thanks for finding the patch notes for it, I'll make a PR.
