### ISSUE TITLE
🐛 [Bug Report] [TBC] Stillpine Ancestor Yor invalid model

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#2763]
### Bug Details

When doing the quest Totem of Vark (https://tbc.wowhead.com/quest=9542/totem-of-vark) in Azuremyst isle the ancestor of Yor starts out as a seal, goes out of the water and turns into a furbolg (this all works correctly). 

He then casts Shadow of the Forest (https://tbc.wowhead.com/spell=30448/shadow-of-the-forest) and should turn into a nightsaber and lead you the next totem. However he's just becoming a chequered cube instead.

![Yor](https://user-images.githubusercontent.com/25745474/154865558-dd7dd10c-b453-41fd-93cc-db6c57fd2bef.jpg)

### Steps to Reproduce

1. Get a level 8+ alliance char and go to Cryptographer Aurren (https://tbc.wowhead.com/npc=17232/cryptographer-aurren) at Azure Watch
2. Accept Learning the Language and follow the chain to The totem of Vark Stage
3. Keep an eye on Yor
4.

### Expected behavior

He should become a nightsaber, Shadow of the Forest says it uses Shadowmaw Alpha Transform (https://tbc.wowhead.com/npc=17411/shadowmaw-alpha-transform)

### Core SHA1 Commit Hash

71acc0a775b227bc2992a1ef4c04b92119c395d1

### Database SHA1 Commit Hash

82a41911d3880a73949f3dc12c602b54bb9aa298

### Operating System

Windows 10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by al3xc1985** [comment]
I think it îs a probleme in packets @killerwife . I encountered this boxy probleme in Wotlk but with the char. Something gets messy in there

**Comment by al3xc1985** [comment]
Can u plecase retest with lătrat cote?

**Comment by Trystanosaurus** [comment]
Still the same with TBC commit 87d6304b22bbc0b1cc70db987a1773f57e2a86c6

![WoWScrnShot_030122_083651](https://user-images.githubusercontent.com/25745474/156125587-8935c7ce-bb2c-484f-ae53-727521e76b6c.jpg)

From comments you should both be turned into cat form (at the moment the player does get the ghostly view and speed buff but no shape change) https://tbc.wowhead.com/quest=9542/totem-of-vark

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/219801302-099c15e7-16da-4adb-847c-87e8cb93922c.png)

![grafik](https://user-images.githubusercontent.com/19734826/219801320-27695360-8744-47fb-8fb6-77e00adbe191.png)

![grafik](https://user-images.githubusercontent.com/19734826/219801406-9b65c26c-8da8-4696-8733-beb3a8a13885.png)
