### ISSUE TITLE
💬 [Support Request] 

### ISSUE THREAD

**Issue by opiums9** [cmangos/issues#2764]
### Core Version

mangos-tbc

### Support Request Details

My server got 3 crashes at night

### Steps to Reproduce

1.
2.
3.
4.

### Crash Log

https://gist.github.com/opiums9/6d0e2374ee4ec8a50d2dbe5eeb7b2578
https://gist.github.com/opiums9/146d272746a969b6f8698d8918eeaaac
https://gist.github.com/opiums9/280771457c0e8a72293fc50d04140395

### Core SHA1 Commit Hash

f0e9931c5a8b1a8e5876ba7140c9f54df2f82ff4

### Database SHA1 Commit Hash

f0e9931c5a8b1a8e5876ba7140c9f54df2f82ff4

### Server Operating System

Debian 10

### Client Version

2.4.3 (The Burning Crusade)

### Client Operating System

Windows

**Comment by killerwife** [comment]
Closed by https://github.com/cmangos/mangos-tbc/commit/95aa150924b14aa6e8ee6cf89a1ff9e7f65152c7
