### ISSUE TITLE
🐛 [Bug Report] HandleCreatureQueryOpcode will Crash Server

### ISSUE THREAD

**Issue by cbcs** [cmangos/issues#2765]
### Bug Details

I don't know how to reproduce.
just entered the instance to kill.. and then go out and enter again.
Look the dmp

### Steps to Reproduce

1.HandleCreatureQueryOpcode 
2.maybe m_objectsStore is Null.

### Crash Log

[_mangosd.exe_[21-2_14-49-42].zip](https://github.com/cmangos/issues/files/8107830/_mangosd.exe_.21-2_14-49-42.zip)

### Core SHA1 Commit Hash

https://github.com/cmangos/mangos-classic/commit/1884a75d5ed8d31305a751777267e2bd2e9443bd

### Database SHA1 Commit Hash

the last db

### Operating System

Win10

### Client Version

1.1.12 (Classic)

**Comment by killerwife** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/b3b1592cfaf4459d1c5eef2705924314f0b68884
