### ISSUE TITLE
🐛 [Bug Report] Gauging the Resonant Frequency Crashe Server

### ISSUE THREAD

**Issue by ReyDonovan** [cmangos/issues#2767]
### Bug Details

quest Gauging the Resonant Frequency https://tbc.wowhead.com/quest=10594/gauging-the-resonant-frequency
when using the Oscillating Frequency Scanners item, the server crashes in the summon function

### Steps to Reproduce

1. quest add 10594
2. use Oscillating Frequency Scanners
3. crashe server
4.

### Core SHA1 Commit Hash

1562a7ff15673f4cc41e6db4bcd01d24305062dd

### Database SHA1 Commit Hash

86326375bc248bf0307735234c178be8dececd9d

### Operating System

Debian 11 Win10Pro

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Was fixed yesterday by https://github.com/cmangos/mangos-tbc/commit/95aa150924b14aa6e8ee6cf89a1ff9e7f65152c7

**Comment by ReyDonovan** [comment]
@killerwife  god emu wow
