### ISSUE TITLE
🐛 [Bug Report] Mobs should move backwards when backpedaling

### ISSUE THREAD

**Issue by Nytanath** [cmangos/issues#2768]
### Bug Details

Currently, when mobs "backpedal" because the player is too close, they turn around, move forward and turn around again.

https://user-images.githubusercontent.com/99603810/155182997-48b44b93-38ba-4d7f-af5d-5bb85d8bc6f8.mp4

On retail, they backpedal without changing their own orientation:

https://user-images.githubusercontent.com/99603810/155183132-4e1ca899-70ce-43d5-a54f-25340914dbcb.mp4

I checked various mob models in the Vanilla client, and they all have animations for backward movement, so I don't think this is something that was introduced in TBC or WotLK.

### Steps to Reproduce

1. Attack a mob.
2. Get close to it.
3. Wait until it backpedals.

### Expected behavior

Mob should not change orientation when backpedaling.

### Core SHA1 Commit Hash

cbaf1b9cdacbcf61cbb1fa84e3a3620695127c8d

### Database SHA1 Commit Hash

127231a5413902c196e6a976a7a6082c8554674d

### Operating System

Windows 10, x64

### Client Version

1.1.12 (Classic)

**Comment by killerwife** [comment]
Incorrect :) This is actually inaccurate on classic and it was even reported to classic devs. They are meant to turn back.

**Comment by Nytanath** [comment]
Ok managed to find a classic forum thread about it. I was wrong about it being on Vanilla, whoops :P thanks for correcting me.

Is the behavior valid for TBC and WotLK too?

**Comment by killerwife** [comment]
Yep, perfectly valid as we have it. You can even backstab during it as intended.

**Comment by Nytanath** [comment]
Alright, thanks! Sorry for the bogus issue.
