### ISSUE TITLE
4.3.4: Spell 102882 Needs To Prevent Self Target If Closest Target in Spell_Script_Target

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#277]
For Spell:

http://www.wowhead.com/spell=102882

as per sniff data the 2 npc (each with own creature_template entry) should cast at each other as targets (Juggle fire).

right now if I add single spell_script_target entry it will throw it properly from one to the other. But if I add a second target for the other one at same time to throw back at original npc then there is a problem. The spell will then target closest target for the spell and that is self.

So we need way for this spell to ignore self target so then the npc will search and find next closest target (the proper target). This would then allow each of the to toss to the other at same time.

**Comment by cyberium** [comment]
Seem's related to cata
