### ISSUE TITLE
🐛Classic Mage fireball damage applies too early [Bug Report] 

### ISSUE THREAD

**Issue by BrenMan99** [cmangos/issues#2770]
### Bug Details

Mage's fireball spells takes effect immediately not when they are struck by the fireball since [bb17f91]

### Steps to Reproduce

1. Shoot at enemy with a mages fireball spell.
2. The spell's casting delay occurs normally.
3. However the target takes damage immediately and the target starts moving towards the mage,
4. The fireball spell animation then occurs with the ball moving to and hitting the target,

### Expected behavior

The fireball should move from the mage to the target and then the target takes damage upon impact.

### Core SHA1 Commit Hash

8d9df167111b7c797558f58689142bae970e16d5

### Database SHA1 Commit Hash

49bb5f94c97950d3782ccdbdfcf39dfec92ea613

### Operating System

Linux Ubuntu

### Client Version

1.1.12 (Classic)

**Comment by killerwife** [comment]
Fixed
