### ISSUE TITLE
🐛 [Bug Report] [TBC] Can't autorun into houses in Elwyn Forest

### ISSUE THREAD

**Issue by Trystanosaurus** [cmangos/issues#2771]
### Bug Details

If you try to run into most of the houses in Elywn Forest (and presumably elsewhere) you bounce off a few times before getting in. I don't recall this being quite so bad on live (though I may be mis-remembering).

### Steps to Reproduce

1. Go to Sara Timberlain at Eastvale Logging camp (.go creature id 278)
2. Line square up with her house and try to run in
3. Most of the time you'll bounce back 2 to 5 times before getting into the house
4.

### Expected behavior

You should go into the house without bouncing off

### Suggested Workaround

You can simply jump over the threshold so it's just a cosmetic user experience issue

### Core SHA1 Commit Hash

d41af145f5e3ce150bb0130b695f4a7030e214b5

### Database SHA1 Commit Hash

f7f7e8183aec241a08f7a639aa274d84000a9582

### Operating System

Windows 10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Autorun is purely clientside. We do nothing with this. Terrain is also fully clientside. So this is non-issue.
