### ISSUE TITLE
🚀 [Feature Request] send information to discord

### ISSUE THREAD

**Issue by firelook** [cmangos/issues#2777]
### Feature Details

Be able like ashamanecore to send some information through "chat' or... to discord

### Benefits and Purpose

sharing with people some information

### Core Versions

- [ ] 1.1.12 (Classic)
- [ ] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
We recently closed an issue related to this and I will write the same here and close it. We will gladly accept a component that someone will pull request to each core, however we will not dedicate our time to it because there are more important things. Both me and cyberium agreed on this.
