### ISSUE TITLE
🐛 [WOTLK] DeathKnight Creation

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2786]
### Bug Details

U should not be able to create dk if u don't have a char lvl 55... currently something is wrong in code cause u can create dk with fresh db

### Steps to Reproduce

1.
2.
3.
4.
fresh db

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by RaenaLoa** [comment]
If set to gmlevel 2, you can create a DK without a pre-existing level 55 character. See screenshots:

gmlevel 0
![GMLevel0](https://user-images.githubusercontent.com/100370139/156245306-93abaa36-6520-4145-b291-b740086401b4.PNG)

gmlevel 2
![GMLevel2](https://user-images.githubusercontent.com/100370139/156245314-62d17349-1dad-46e8-815d-67e388a3676e.PNG)

**Comment by al3xc1985** [comment]
u are right... I am an idiot

**Comment by RaenaLoa** [comment]
No worries! Glad you got it figured out :)
