### ISSUE TITLE
wotlk the Binding quest 1795,  warlock felhunter class quest summon felhunter fails🐛 (with a suggested fix) [Bug Report] 

### ISSUE THREAD

**Issue by Eriumango** [cmangos/issues#2787]
### Bug Details

Location ratchet at the summoning circle
when doing the quest 1795, you use the item the tome of the cabal (item 6999) to summon a felhunter to defeat it in order to gain the felhunter summon spell.

The spell fails with an invalid target message.
This can be fixed by an SQL update to spell_template for the underlying spell the item uses which is spell id 8712.
The SQL update I used on my server for database wotlkmangos is:
` update spell_template set Effect2 = 0, Effect3 = 0, EffectImplicitTargetA2 = 0, EffectImplicitTargetA3 = 0 where id = 8712;`

### Steps to Reproduce

1. create a lock, level to 30
2. .tele to Ratchet, go up the hill to the summoning circle behind the flight master
3. .learn spell 8712
4. try to cast it near the summoning circle in the hut with the npcs standing around it.
5.it should fail with invalid target as a message
6. update the SQL as I have done for spell_template for spell id 8712 and database wotlkmangos:
` update spell_template set Effect2 = 0, Effect3 = 0, EffectImplicitTargetA2 = 0, EffectImplicitTargetA3 = 0 where id = 8712;`
7. then restart the server and retry the spell, the felhunter will now be summoned and the quest if you have it will be able to be completed

### Expected behavior

the felhunter should be summoned in the circle 

### Suggested Workaround

see steps to reproduce above
fix I have confirmed is an sql update in wotlkmangos database
` update spell_template set Effect2 = 0, Effect3 = 0, EffectImplicitTargetA2 = 0, EffectImplicitTargetA3 = 0 where id = 8712;`

### Core SHA1 Commit Hash

56f5cbf46046f6cece2c1f3ca2a07f540561cb08

### Database SHA1 Commit Hash

8b341a7d658ff4b362ddb142fde099039833793f

### Operating System

ubuntu 20.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Try this:

```
INSERT INTO spell_script_target VALUES
('8712', '0', '92252', '0'),
('8712', '0', '92388', '0');
```

**Comment by Eriumango** [comment]
Many thanks will do tomorrow

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Eriumango** [comment]
Hi killerwife, yes that works the felhunter can be summoned
many thanks

**Comment by Eriumango** [comment]
also seem to have a similar issue on the infernal quest where the Fel fire item doesnt pick up Kroshius remains

**Comment by Eriumango** [comment]
solved the infernal quest issue, a gameobject 179677 Kroshius remains  is required to be in the same position as the npc kroshius for the spell 23054 to work. It wasnt. so I updated table gameobject to match the position from table creature
this then allowed the npc to be revived and the quest to be completed.
@killerwife can you include these fixes in your next db commit please, your one above for the felhunter class quest and this one below for the infernal class quest.
thanks!
`update gameobject set position_x = 5800.89, position_y = -985.82, position_z = 409.78 where id = 179677;`
