### ISSUE TITLE
🐛 [Bug Report] [TBC] Will not destory enchant item while enchanting for other player

### ISSUE THREAD

**Issue by wackyliu** [cmangos/issues#2789]
### Bug Details

Will not destory enchant when enchanted for other player, I think other enchant will be same.

### Steps to Reproduce

![01](https://user-images.githubusercontent.com/39901380/156760695-b7f6a8c5-1b0d-4467-b150-e554c6ee5cfa.png)
![02](https://user-images.githubusercontent.com/39901380/156760725-408f661a-1448-4b20-a271-6bda7da289c3.png)

### Core SHA1 Commit Hash

ed55ecdd557479da091f635eb0e73719948134cf

### Database SHA1 Commit Hash

a8f2653193d417f70292c28a26de2f654d1c802c

### Operating System

WIN

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Fixed in https://github.com/cmangos/mangos-tbc/commit/706a0e8062da73995a48bd7d8a84e47bb236d568

**Comment by MilkmanMHOC** [comment]
This is also an issue on classic, hopefully this is on a back port list?  If not can it be added to the list?
