### ISSUE TITLE
🐛 [Bug Report] WheatyExceptionReport does not work inside the shared library alone

### ISSUE THREAD

**Issue by Nytanath** [cmangos/issues#2790]
### Bug Details

WheatyExceptionReport needs to be included in the executable that runs it, not into a shared library, for it to work properly and generate crash dumps on Windows.

Right now it is compiled in the shared library, which does not allow it to work.

I've tested it with [this quick and dirty fix](https://github.com/Nytanath/mangos-classic/commit/aa7855a839c509c978473505a502602b9ba9da76) and it properly generates a crash log. I don't know enough about CMake to submit a proper solution, however. Ideally it would be included in every compiled executable and not only mangosd.

Related to #2412.

### Steps to Reproduce

1. Cherrypick commit linked above, type  ".go creature" in chat to force a crash. Look at the generated crash dump in bin/Crashes.

### Core SHA1 Commit Hash

9062b5f69fc5a364fcec54e33b0d202fd1a817ff

### Database SHA1 Commit Hash

3974e3222ddb6e67067f66ee16a53f1e117045f2

### Operating System

Windows 10, x64

### Client Version

1.1.12 (Classic)

**Comment by cyberium** [comment]
Thank you, should be fixed
