### ISSUE TITLE
🐛 [Bug Report] Sprok in Gnomeregan missing txt

### ISSUE THREAD

**Issue by MilkmanMHOC** [cmangos/issues#2792]
### Bug Details

When talking to Sprok on the Gnomeregan side of the transporter from Booty Bay it just says "Missing US text".

Im not sure WHAT its supposed to say, but its not that. 

 
![sprok](https://user-images.githubusercontent.com/80412574/156904832-08c672bc-6f5a-4458-86e5-789320fab692.jpg)

### Steps to Reproduce

1.Try to talk to him
2.
3.
4.

### Core SHA1 Commit Hash

9062b5f69fc5a364fcec54e33b0d202fd1a817ff

### Database SHA1 Commit Hash

3974e3222ddb6e67067fee16a53f1e117045f2

### Operating System

WIn7

### Client Version

1.1.12 (Classic)

**Comment by miraco** [comment]
I guess you could test it with us client on retail classic
