### ISSUE TITLE
🐛 [Bug Report] Pets enter combat mode when interacting with some game objects.

### ISSUE THREAD

**Issue by MilkmanMHOC** [cmangos/issues#2793]
### Bug Details

If you, or a party member, have a pet out and near a mining node or chest and attempt to mine/open it, the pet seems to enter combat mode.  It moves next to it and faces it while making its combat noises.  It dose not appear to attack the object, but will not exit combat or move from that spot even after the object disappears.  

The only way to get the pet to move again is either dismiss the pet, or give it a new target to attack.

I have confirmed this with both hunter and warlock pets.

### Steps to Reproduce

1. Have a pet out
2. Mine a node or open a treasure chest
3.
4.

### Expected behavior

The pets should not react at all to using a mining node or chest.

### Core SHA1 Commit Hash

9062b5f69fc5a364fcec54e33b0d202fd1a817ff

### Database SHA1 Commit Hash

3974e3222ddb6e67067fee16a53f1e117045f2

### Operating System

Win7

### Client Version

1.1.12 (Classic)

**Comment by woodsman808** [comment]
Having the same issue with combat pets,it has cropped up once or twice while trying to pick up a quest item using the gear icon. Always happens with treasure chests.
Putting pet on passive doesn't change anything.
 A possible related bug,try to pick up food crates and milk or melon barrels, 
and you get "Invalid Target".

**Comment by Nytanath** [comment]
> A possible related bug,any class trying to pick up food crates and milk or melon barrels,
and you get "Invalid Target".

I have noticed this too, but with the Gurubashi Arena chest.

**Comment by korhaldragonir** [comment]
Having the same issue in version:
Core Version: 3ad31c4d2bd1b9e21273d1735da42b03ea5d3e75
DB Version: d743b53dd42bb415359dbe682fe858cf3e2b07ad

And since this is on the WotLK branch it seems not to be pinned to an expansion.

**Comment by AnonXS** [comment]
due to this being reworked now in 4 commits, refer to newest issue https://github.com/cmangos/issues/issues/3217
