### ISSUE TITLE
🐛 [Bug Report] [Classic] ERROR 1136 (21S01) at line 1340

### ISSUE THREAD

**Issue by novicewu** [cmangos/issues#2794]
### Bug Details

Error found when Initializing world database "mysql -uroot -p classicmangos < mangos/sql/base/mangos.sql"

Error Details:
```
# mysql -uroot -p classicmangos < mangos/sql/base/mangos.sql
Enter password: 
ERROR 1136 (21S01) at line 1340: Column count doesn't match value count at row 1
```
### Steps to Reproduce

1. install classic mangos per wiki [https://github.com/cmangos/issues/wiki/Installation-Instructions](https://github.com/cmangos/issues/wiki/Installation-Instructions)
2. When coming to the step "Initialize world database:" error found
3. 
4.
5.

### Core SHA1 Commit Hash

n/a

### Database SHA1 Commit Hash

n/a

### Operating System

debian 10

### Client Version

1.1.12 (Classic)

**Comment by al3xc1985** [comment]
Your mysql îs not registered. U need to find a Google Guise for IT. This îs not related to cmangos

**Comment by AnonXS** [comment]
outdated
