### ISSUE TITLE
Screenshot (7 mar 2022 5:58:53 PM)

### ISSUE THREAD

**Issue by Marcin7770** [cmangos/issues#2799]

**Comment by Marcin7770** [comment]
>

**Comment by al3xc1985** [comment]
@killerwife please close this

**Comment by cyberium** [comment]
Dont ping please any moderator can close this.

**Comment by al3xc1985** [comment]
Ok. The reason îs killerwife îs more active. And in past months he checked the issues very frewuently. I am no moderator, and don't know who that might be for cmangos  But anyways ty
