### ISSUE TITLE
🐛 [Bug Report] [WoTLK] Compile Warning, AchievementMgr.cpp

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2801]
### Bug Details

Warning during compile. Ubuntu 20.04 had an update to gcc & g++ today and my be the cause of the warning 
g++ (Ubuntu 9.4.0-1ubuntu1\~20.04) 9.4.0
gcc (Ubuntu 9.4.0-1ubuntu1\~20.04) 9.4.0

### Steps to Reproduce

1. Compile WoTLK cmake ~/cmangos/wotlk -DCMAKE_INSTALL_PREFIX=\~/wow-servers/wotlk -DBUILD_EXTRACTORS=On -DBUILD_AHBOT=ON -DBUILD_PLAYERBOT=ON -DPCH=0 -DDEBUG=0 -DBUILD_RECASTDEMOMOD=OFF -DBUILD_GIT_ID=0 ; make -j6

2.
3.
4.

### Expected behavior

No warnings

### Suggested Workaround

N/A

### Crash Log

~~~
/home/mangos/cmangos/wotlk/src/game/Achievements/AchievementMgr.cpp: In member function ‘bool AchievementCriteriaRequirement::IsValid(const AchievementCriteriaEntry*) const’:
/home/mangos/cmangos/wotlk/src/game/Achievements/AchievementMgr.cpp:289:1: warning: control reaches end of non-void function [-Wreturn-type]
  289 | }
      | ^
~~~

### Core SHA1 Commit Hash

CMaNGOS-Core revision : 38fef98a83150e41304450e0fec8ad9466e914bd

### Database SHA1 Commit Hash

N/A

### Operating System

Ubuntu 20.04.3 Server LTS

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by adellaci** [comment]
Compiled CMaNGOS-Core revision : 7823fe038c239de9a014a6ef17a3bf539f4ca66c this morning and this warning has been corrected

**Comment by adellaci** [comment]
Sorry it was not corrected

**Comment by dunjeon** [comment]
Can Confirm
