### ISSUE TITLE
🐛 [Bug Report] [WoTLK] [Quest] Murloc Poacher 

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2804]
### Bug Details

I picked up quest 'Murloc Poacher' (Quest 150) in Redridge, with many others. After killing several Murlocs and completing a couple of quest, ran back to Lakeshire to turn in quests. Dockmaster Baren (npc 381) show that i could turn in the quest. I needed 8 Murloc Fin (item 1468) but only had 5 fins. He would not let me complete it, which is correct but he should no show that i can turn it in.

### Steps to Reproduce

1. Go to Lakeshire in Redridge
2. Pick up quest 'Murloc Poacher' for Dockmaster Baren
3. Kill a few Murlocs and collect a couple of fins
4. Return to Lakshire and quest giver shows you can turn it in

### Expected behavior

Should not show you can turn it in until you have collected all 8 Murloc Fins

### Suggested Workaround

N/A

### Crash Log

N/A

### Core SHA1 Commit Hash

38fef98a83150e41304450e0fec8ad9466e914bd

### Database SHA1 Commit Hash

fe631a8aaf3d6f42162a7c4830df3017d7bcbdd6

### Operating System

Ubuntu 20.04.3 Server LTS, Client Windows 7

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Nytanath** [comment]
I tried this, but cannot reproduce:

![WoWScrnShot_030822_141140](https://user-images.githubusercontent.com/99603810/157244747-3e445499-b0de-4c09-9127-23f63ded9052.jpg)

**Comment by adellaci** [comment]
I have to do more research. When i went back, dropped the quest, re pick it up it worked correctly, but the first time i had picked up both quest he had and completed [Selling Fish] quest=127 when it happen. I need to go back and set the same scenario up and try it again.

**Comment by adellaci** [comment]
@Nytanath, you were correct i did have 4 fins in the bank.
Started everything from the beginning, that included getting the quest [Selling Fish] again. Went back and killed Murlocs, got all the Fins and Fishes, went back to quest giver, he excepted the Fins to complete [Murloc Poaching]. Even thou he showed i could turning the quest [Selling Fish], he would not except it. I did have all the Fish in my bag
