### ISSUE TITLE
WOTLK BloodFurnace Fel Orc Neophyte sometimes have gordok ogre model (with fix)🐛 [Bug Report] 

### ISSUE THREAD

**Issue by Eriumango** [cmangos/issues#2806]
### Bug Details

In the Blood furnace the Fel orc neophytes sometimes appear as gordok ogres.
These are creature 17429 which has a model id of 16332
Table creature_model_info has modelid_other_gender 12471 for modelid = 16332.
12471 is the modelid for creature 11440	Gordok Enforcer
easy fix update the modelid_other_gender to 0  (will match the tbc database then)

### Steps to Reproduce

1. go to blood furnace and wonder why some ogres are there. after first boss 
2.
3.
4.

### Expected behavior

orcs not ogres

### Suggested Workaround

fix the dbase entry with this sql please
`Update creature_model_info set modelid_other_gender = 0 where modelid = 16332;`

### Core SHA1 Commit Hash

56f5cbf46046f6cece2c1f3ca2a07f540561cb08

### Database SHA1 Commit Hash

8b341a7d658ff4b362ddb142fde099039833793f 

### Operating System

ubuntu 20.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
Was resolved with some export.

![grafik](https://user-images.githubusercontent.com/19734826/174918967-2ef9a67b-7551-4f27-8b57-1a480043f435.png)
