### ISSUE TITLE
[CLASSIC] Paladin +Healing

### ISSUE THREAD

**Issue by scotty0100** [cmangos/issues#281]
Paladin spell Holy Light seems to not be effected by +healing gear.

Flash of Light did seem to be effected, but not by much.

I added a GM char with about +200 healing using the top rank Holy Light spell and it didn't seem to budge much at all.

Whereas, using the same items on a priest healer increased his heal tremendously.

Also with Holy Light, I noticed there's about a 1-2 second delay before the heal actually heals your target. I don't remember this being in classic, however I didn't play a paladin. Is this a bug or not?

**Comment by al3xc1985** [comment]
@killerwife close it.... tested and working perfect even with talents
