### ISSUE TITLE
🚀 [Feature Request] 

### ISSUE THREAD

**Issue by rmzV** [cmangos/issues#2812]
### Feature Details

In current instructions, (cloning git repository sections), git commands still looks like:
git clone **git://github.com**/cmangos/mangos-wotlk.git mangos

but there was something about security protocol etc, and the propper (working) command must looks like:

git clone **https://github.com**/cmangos/mangos-wotlk.git mangos

### Benefits and Purpose

Fix for supporting github changes

### Core Versions

- [X] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by rmzV** [comment]
okey
$ git clone https://github.com /cmangos/wotlk-db.git
fatal: could not create leading directories of 'C:/Program Files/Git/cmangos/wotlk-db.git': Permission denied

fixed command working on mangos-wotlk and doesnot works on wotlk-db ((

**Comment by Nytanath** [comment]
You added a space between https://github.com and /cmangos/wotlk-db.git, that's why it doesn't work :P

**Comment by killerwife** [comment]
The actual command should look like git clone git@github.com:cmangos/mangos-wotlk.git

Github removed https authorization so if you want to do anything except pulling, you need to have it set up like this anyway.

**Comment by killerwife** [comment]
I have edited the installation instructions and closing this issue as resolved.
