### ISSUE TITLE
🐛 [Bug Report] AOE Spell No damage.

### ISSUE THREAD

**Issue by cbcs** [cmangos/issues#2813]
### Bug Details

1. In the case of multiple targets, when the knight casts Consecration, there will be no damage.
2. Hunter, when multiple shots + random shots are continuously cast, the random shots will cause no damage.
3. Mage, talent [Enhanced Blizzard], Blizzard has no damage

### Steps to Reproduce

1. .go -16.4 -383.07 61.78 36
2. Attract at least 5 enemies to attack you.
3. cast Blizzard ..the spell no damage...

### Crash Log

Maybe that's the problem in GirdNotifiersLmpl.h

if (!spellInfo->HasAttribute(SPELL_ATTR_EX2_IGNORE_LOS) && !i_dynobject.IsWithinLOSInMap(target))
   return;

The spell was interrupted here

### Core SHA1 Commit Hash

https://github.com/cmangos/mangos-classic/commit/6ddd9a7eaa25fd7eca1d5d35214f919a1f5fc5af

### Database SHA1 Commit Hash

Last DB

### Operating System

Win10

### Client Version

1.1.12 (Classic)

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-classic/commit/ebb497a9b75e269bc45a835814392c44ef23faa1
