### ISSUE TITLE
💬 [Support Request] Unable to clone

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#2814]
### Core Version

mangos-wotlk

### Support Request Details

git clone git@github.com:cmangos/mangos-wotlk.git cmangos/wotlk
Cloning into 'cmangos/wotlk'...
Warning: Permanently added the ECDSA host key for IP address '140.82.112.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

### Steps to Reproduce

1.git clone git@github.com:cmangos/mangos-wotlk.git cmangos/wotlk
2.
3.
4.

### Crash Log

n/A

### Core SHA1 Commit Hash

N/A

### Database SHA1 Commit Hash

N/A

### Server Operating System

Ubuntu 20.04.3 Server LTS

### Client Version

3.3.5a (Wrath of the Lich King)

### Client Operating System

N/A

**Comment by insunaa** [comment]
You can only use the git protocol if you have an account registered on github, where you have supplied your own SSH public key.

If you don't want to do that, clone it via https

`git clone https://github.com/cmangos/mangos-wotlk.git`

**Comment by adellaci** [comment]
thank you for the link.. followed instruction...all good
