### ISSUE TITLE
🚀 [Feature Request] add support for sql8

### ISSUE THREAD

**Issue by Eriumango** [cmangos/issues#2815]
### Feature Details

Hi in wotlkcharacters we have table groups, in MySQL 8 this is  now a reserved keyword , so table updates etc. are not working correctly for groups and parties can be hard to form as a result in the game with players and bots not getting the invites.

I have tested a fix by renaming the table to groupsb and changing all *.CPP references to groups I could find from groups to groupsb.
I found references in 
Group.cpp
MapPersistentStateMgr.cpp
ObjectMgr.cpp
this seems to work ok so far , I can now form parties and invite bots etc. with no issues.

 

### Benefits and Purpose

latest version mysql support

### Core Versions

- [X] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Thats unnecessary, they just need to be enclosed in ``. If you find a query thats causing trouble, post the place. `group` is fine, group by itself is not.

**Comment by Eriumango** [comment]
ok thanks will do,

**Comment by AnonXS** [comment]
mysql 8 is supported by now.
