### ISSUE TITLE
Quest 9853 Gurok The Usurper, warmaul skull drop restricted to 1 with FIX 🐛 [Bug Report] WOTLK

### ISSUE THREAD

**Issue by Eriumango** [cmangos/issues#2817]
### Bug Details

in the quest you have to get 7 warmaul skulls, (item 24502)
however you will only be able to get one in WOTLk.
this is because the table in quest_template for entry = 9853 has ReqSourceId2 = 24502 and ReqSourceCount2 = 1
in TBC the count  = 20. so you can get up to 20.
The sql needs a simple update
Update quest_template SET ReqSourceCount2 = 20 WHERE entry = 9853;

### Steps to Reproduce

1.get quest 9853 in wotlk
2. go to warmaul hill and kill ogres, see if item 24502 drops more than once..
3.
4.

### Expected behavior

the item drops more than once

### Suggested Workaround

sql update for the wotlk-mangos databases

`Update quest_template SET ReqSourceCount2 = 20 WHERE entry = 9853;`

### Core SHA1 Commit Hash

56f5cbf46046f6cece2c1f3ca2a07f540561cb08

### Database SHA1 Commit Hash

8b341a7d658ff4b362ddb142fde099039833793f

### Operating System

ubuntu 20.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
https://github.com/cmangos/wotlk-db/commit/c0f0207eecf2fb3edd39bf9a2467bccf0f4b3fca
