### ISSUE TITLE
🐛 [Bug Report] ”DB Error of Game_Event"/TBC

### ISSUE THREAD

**Issue by yuyu-lovegelin111333** [cmangos/issues#2821]
### Bug Details

DB Error alarm showed : 
2022-03-30 22:04:24 `game_event` game event id (7) has game_event_time but is not date scheduled - ignoring
2022-03-30 22:04:24 `game_event` game event id (28) has game_event_time but is not date scheduled - ignoring

### Steps to Reproduce

1.Run newest comm code server.exe
2. No more operate need .
3. Waiting seconds , goto read DB Error logs . Will see the alarms .
4. Game_Event entry 7 and 28 .

### Expected behavior

Should no this kind of alarms !

### Suggested Workaround

Suggest to sheck code beolow also and the DB date.
`            if (gameEvent.scheduleType != GAME_EVENT_SCHEDULE_DATE && gameEvent.scheduleType != GAME_EVENT_SCHEDULE_YEARLY)
            {
                sLog.outErrorDb("`game_event` game event id (%i) has game_event_time but is not date scheduled - ignoring", event_id);
                continue;
            }`

Base DB date : scheduleType =12 used by Event 7 ; scheduleType =13 used by Event 28 ; 

<a href="https://sm.ms/image/k1A286jZV9bnBIH" target="_blank"><img src="https://s2.loli.net/2022/03/31/k1A286jZV9bnBIH.png" /></a>
<a href="https://sm.ms/image/yFLfxoAqp91eMCs" target="_blank"><img src="https://s2.loli.net/2022/03/31/yFLfxoAqp91eMCs.png" /></a>
<a href="https://sm.ms/image/PReYg3vToKzhNrd" target="_blank"><img src="https://s2.loli.net/2022/03/31/PReYg3vToKzhNrd.png" /></a>
<a href="https://sm.ms/image/QSZ9d1m3WAytVXc" target="_blank"><img src="https://s2.loli.net/2022/03/31/QSZ9d1m3WAytVXc.png" /></a>

### Core SHA1 Commit Hash

1b419c0fa3d9d7818251d4903dbb62ed88d35b3b

### Database SHA1 Commit Hash

b4e525fd2d48779b975f1840ef1413fe117a7a3c

### Operating System

WIN10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by cyberium** [comment]
Probably some missing export from @killerwife here

**Comment by MilkmanMHOC** [comment]
This is an issue in classic also.  I changed the schedule_type to 11 instead of 13 to allow nobelgarden to start on the server... but unsure what affects, if any, that will have on the event to run properly.

**Comment by yuyu-lovegelin111333** [comment]
> Has some delete ,today. below: 

[https://github.com/cmangos/tbc-db/commit/9e5de05f1de78fe574fdb29cec440f6e21942583](url)

**Comment by yuyu-lovegelin111333** [comment]
Back to 0 alarms . 
In : [https://github.com/cmangos/tbc-db/commit/9e5de05f1de78fe574fdb29cec440f6e21942583](url)
