### ISSUE TITLE
🐛 [Bug Report] WotLK - Aeranas NPC in Hellfire, no conversation option for hand-in of quest Avruu's Orb

### ISSUE THREAD

**Issue by Cromisa** [cmangos/issues#2823]
### Bug Details

As title, the quest can't complete as the NPC doesn't have ability to be talked to.

### Steps to Reproduce

1. Get quest for Avruu's Orb in Hellfire
2. Can't talk to Aeranas to hand in quest.
3.
4.

### Expected behavior

! above Aeranas to hand in quest

### Suggested Workaround

Hacky work around is to remove the rest(); call in the constructor as it flags him as un-talkable - doubt this is the best option however :)
npc_aeranasAI(Creature* pCreature) : ScriptedAI(pCreature) {  } //removed call to Reset(); in constructor - this removed questgiver flag and blocked completion

### Core SHA1 Commit Hash

n/a

### Database SHA1 Commit Hash

n/a

### Operating System

Win 10 pro

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by onero** [comment]
I can confirm that this is currently not working
