### ISSUE TITLE
🐛 [Bug Report] WotLK - DeathKnight Ghoul stats missing from Database

### ISSUE THREAD

**Issue by Cromisa** [cmangos/issues#2826]
### Bug Details

Death Knight Ghoul is missing stats so is created as 1 health and 1 mana

### Steps to Reproduce

1. Create a Death Knight
2. Learn summon Ghoul
3. Summon a Ghoul, check the stats of the Ghoul - 1 health, 1 mana, 1 AP, 1 - 1 damage

### Expected behavior

Ghoul should have stats akin to hunter pet etc.

### Suggested Workaround

Add the following into the Database scripts
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '1', '1707', '800', '1693', '20', '16', '13', '20', '8');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '2', '1728', '810', '1714', '22', '17', '14', '21', '9');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '3', '1750', '820', '1735', '24', '18', '15', '22', '10');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '4', '1772', '830', '1757', '26', '19', '16', '23', '11');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '5', '1794', '840', '1779', '28', '20', '17', '24', '12');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '6', '1816', '851', '1801', '30', '21', '18', '25', '13');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '7', '1839', '862', '1824', '32', '22', '19', '26', '14');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '8', '1862', '873', '1847', '34', '23', '20', '27', '15');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '9', '1885', '884', '1870', '36', '24', '21', '28', '16');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '10', '1909', '895', '1893', '38', '25', '22', '29', '17');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '11', '1933', '906', '1917', '40', '26', '23', '30', '18');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '12', '1957', '917', '1941', '42', '27', '24', '31', '19');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '13', '1981', '928', '1965', '44', '28', '25', '32', '20');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '14', '2006', '940', '1990', '46', '29', '26', '33', '21');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '15', '2031', '952', '2015', '48', '30', '27', '34', '22');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '16', '2056', '964', '2040', '50', '31', '28', '35', '23');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '17', '2082', '976', '2065', '52', '32', '29', '36', '24');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '18', '2108', '988', '2091', '54', '33', '30', '37', '25');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '19', '2134', '1000', '2117', '56', '34', '31', '38', '26');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '20', '2161', '1013', '2143', '58', '35', '32', '39', '27');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '21', '2188', '1026', '2170', '60', '36', '33', '40', '28');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '22', '2215', '1039', '2197', '62', '37', '34', '41', '29');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '23', '2243', '1052', '2224', '64', '38', '35', '42', '30');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '24', '2271', '1065', '2252', '66', '39', '36', '43', '31');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '25', '2299', '1078', '2280', '68', '40', '37', '44', '32');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '26', '2328', '1091', '2309', '70', '41', '38', '45', '33');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '27', '2357', '1105', '2338', '72', '42', '39', '46', '34');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '28', '2386', '1119', '2367', '74', '43', '40', '47', '35');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '29', '2416', '1133', '2397', '76', '44', '41', '48', '36');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '30', '2446', '1147', '2427', '78', '45', '42', '49', '37');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '31', '2477', '1161', '2457', '80', '46', '43', '50', '38');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '32', '2508', '1176', '2488', '82', '47', '44', '51', '39');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '33', '2539', '1191', '2519', '84', '48', '45', '52', '40');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '34', '2571', '1206', '2550', '86', '49', '46', '53', '41');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '35', '2603', '1221', '2582', '88', '50', '47', '54', '42');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '36', '2636', '1236', '2614', '90', '51', '48', '55', '43');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '37', '2669', '1251', '2647', '92', '52', '49', '56', '44');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '38', '2702', '1267', '2680', '94', '53', '50', '57', '45');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '39', '2736', '1283', '2713', '96', '54', '51', '58', '46');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '40', '2770', '1299', '2747', '98', '55', '52', '59', '47');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '41', '2805', '1315', '2781', '100', '56', '53', '60', '48');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '42', '2840', '1331', '2816', '102', '57', '54', '61', '49');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '43', '2875', '1348', '2851', '104', '58', '55', '62', '50');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '44', '2911', '1365', '2887', '106', '59', '56', '63', '51');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '45', '2947', '1382', '2923', '108', '60', '57', '64', '52');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '46', '2984', '1399', '2960', '110', '61', '58', '65', '53');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '47', '3021', '1416', '2997', '112', '62', '59', '66', '54');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '48', '3059', '1434', '3034', '114', '63', '60', '67', '55');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '49', '3097', '1452', '3072', '116', '64', '61', '68', '56');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '50', '3136', '1470', '3110', '118', '65', '62', '69', '57');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '51', '3175', '1488', '3149', '120', '66', '63', '70', '58');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '52', '3215', '1507', '3188', '122', '67', '64', '71', '59');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '53', '3255', '1526', '3228', '124', '68', '65', '72', '60');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '54', '3296', '1545', '3268', '126', '69', '66', '73', '61');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '55', '3337', '1564', '3309', '128', '70', '67', '74', '62');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '56', '3379', '1584', '3350', '130', '71', '68', '75', '63');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '57', '3421', '1604', '3392', '132', '72', '69', '76', '64');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '58', '3464', '1624', '3434', '134', '73', '70', '77', '65');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '59', '3507', '1644', '3477', '136', '74', '71', '78', '66');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '60', '3551', '1665', '3520', '138', '75', '72', '79', '67');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '61', '3595', '1686', '3564', '140', '76', '73', '80', '68');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '62', '3640', '1707', '3609', '142', '77', '74', '81', '69');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '63', '3685', '1728', '3654', '144', '78', '75', '82', '70');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '64', '3731', '1750', '3700', '146', '79', '76', '83', '71');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '65', '3778', '1772', '3746', '148', '80', '77', '84', '72');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '66', '3825', '1794', '3793', '150', '81', '78', '85', '73');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '67', '3873', '1816', '3840', '152', '82', '79', '86', '74');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '68', '3921', '1839', '3888', '154', '83', '80', '87', '75');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '69', '3970', '1862', '3937', '156', '84', '81', '88', '76');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '70', '4020', '1885', '3986', '158', '85', '82', '89', '77');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '71', '4070', '1909', '4036', '160', '86', '83', '90', '78');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '72', '4121', '1933', '4086', '162', '87', '84', '91', '79');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '73', '4173', '1957', '4137', '164', '88', '85', '92', '80');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '74', '4225', '1981', '4189', '166', '89', '86', '93', '81');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '75', '4278', '2006', '4241', '168', '90', '87', '94', '82');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '76', '4331', '2031', '4294', '170', '91', '88', '95', '83');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '77', '4385', '2056', '4348', '172', '92', '89', '96', '84');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '78', '4440', '2082', '4402', '174', '93', '90', '97', '85');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '79', '4495', '2108', '4457', '176', '94', '91', '98', '86');
INSERT INTO wotlkmangos.pet_levelstats VALUES('26125', '80', '4551', '2134', '4513', '178', '95', '92', '99', '87');

The values I used were based on level 80 Ghoul hitpoints, armour etc.
I used a complete guess at working them backwards. Essentially I used a formula that reduced on 1.25% per level
Couldn't find any source of truth out there sorry :(

### Core SHA1 Commit Hash

n/a

### Database SHA1 Commit Hash

n/a

### Operating System

Win 10 pro

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
Currently summoned Ghouls have the appropriate stats for their level. Can anybody test this at different levels to see if this issue is still relevant?

**Comment by AnonXS** [comment]
Was resolved by https://github.com/cmangos/wotlk-db/commit/a9095cd2338c8e38a075a8669ac31d2260c4025a
These petlevelstats are totally different from what we currently have for level 1-80 entry 26125.
