### ISSUE TITLE
🐛 [Bug Report] Majordomo doesnt spawn (Molten Core bug)

### ISSUE THREAD

**Issue by kokutek** [cmangos/issues#2832]
### Bug Details

After killing every elite and boss in the molten core, Majordomo the Executus doesnt spawn on his place (either his elites doesnt spawn)

### Steps to Reproduce

1. .go xyz 1082.04 -474.59 -107.77 409
2. kill all bosses in the molten core
3. check the spawn location for majordomo ( .go xyz 707.66 -1191.92 -118.98 409)
4. thats it

### Expected behavior

After doing these steps, you should see a spawned Majordomo the Executus with couple of elites.

### Core SHA1 Commit Hash

ad047ad6c28fc83491f3f2570cf67c557a811a5b

### Database SHA1 Commit Hash

a11fd08c2b8139d27d9d4a33327cba710f9687af

### Operating System

Ubuntu 20.04 LTS x64

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Have you used the item to summon him? Dousing the runes.

**Comment by celguar** [comment]
According to WoWPedia, before patch 3.0.8 you have to use Aqual or Eternal Quintessence to douse all the runes before Majordomo appears

**Comment by kokutek** [comment]
Wait you need to do something like that? My apologies then, sorry for bothering, first time I see this.
