### ISSUE TITLE
🐛 [Bug Report] Mutanus the Devourer, Naralex, Disciple of Naralex, Instance [Wailing Caverns] Final Creature Script AI , No Perfect

### ISSUE THREAD

**Issue by yuyu-lovegelin111333** [cmangos/issues#2833]
### Bug Details

In the Instance Wailing Caverns , the entre Loc‘ NPC has Script AI after all the BOSSx7  has been killed  .
 [move to the depths of the cave to awaken his host ] ,Player need protect and escort him . 

Bug Below :  
the depths ' pool has 1st wave attack ( in code // First set of mobs ：MOCCASIN ID 5762  ) ， doesn't come out from water pool , and doesn't attack NPC or Players , and after timer counter 20000ms later , the 5762 disappeared , instead of by 2nd Mob do SpawnMob 5763 , and 5763 will attack NPC positivetly  , after 5763 dead , Final Boss can not DoSpawnMob  .  

Script AI Failed !

### Steps to Reproduce

1. Go to Instance Map 43 [Wailing Caverns].
2. Kill all other 7 boss.
3. Go back to Instance  entre .
4. Talk to NPC's GoIp Select .
5. NPC Start this Script AI. 
6. Follow NPC and protect him to depth's caves . 
7. In final case position near the Pool . Waiting 2 waves of attack by CR 5762 & 5763 .
8. When Creature 5762 MOCCASIN Summoned , do not attack it ,waiting 20seconds  ,waiting 2nd wave Mob summoned .
9. After killed 2nd wave Mob summoned , Final Boss will not summon by Script AI . 
10. Failed !

### Expected behavior

In code script , 1st set of mobs Creature Moccasin should come out from water and attack NPC !

`case 3:
                                // First set of mobs
                                for (uint8 i = 0; i < 3; ++i)
                                    DoSpawnMob(NPC_DEVIATE_MOCCASIN, aSummonPositions[3][0], aSummonPositions[3][1] + M_PI_F / 3 * i);
                                m_uiEventTimer = 20000;
                                ++m_uiSubeventPhase;
                                break;`

### Suggested Workaround

` void JustSummoned(Creature* pSummoned) override
    {
        // Attack the disciple
        pSummoned->AI()->AttackStart(m_creature);
        ++m_uiSummonedAlive;
    }`

### Crash Log

Video or photos record will update later soon !

### Core SHA1 Commit Hash

7062e90cc3a74d04d15ed1d42a543ee8bd22c26a

### Database SHA1 Commit Hash

2115d1edf090bbb9498743d085956f7875a9fb4f

### Operating System

WIN10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by yuyu-lovegelin111333** [comment]
@killerwife @cyberium  .Hi friend , can you help on this ? 

I do tested on exchange the creature type of 1st Mob and 2nd Mob in the database ,but test result are same . 
Do not know the code here in core , why 2nd mob can attack NPC automatictely , and 1st mob can not attack positivetly !

**Comment by ssj17vegeta** [comment]
WOTLK version is also affected in the very same way as OP described.

**Comment by yyhhrr** [comment]
classic version is the same issue

**Comment by AnonXS** [comment]
It's a regression as the last one to touch this was KW.

**Comment by whipowill** [comment]
Confirm this issue on WOTLK, just experienced it.

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/b36e0428eb8300a9b976770c46d4692e28903ee8

**Comment by yyhhrr** [comment]
can anyone port this to classic?

**Comment by AnonXS** [comment]
did you retest?

https://github.com/cmangos/mangos-classic/commit/bda9a9a29d377ce9ff553bd5c7d3c866f586929b
https://github.com/cmangos/classic-db/commit/82ec36fbb9a440cee92e344908e812f4cc395536 - 9d ago

**Comment by yyhhrr** [comment]
😀my bad,didn't see it yet
