### ISSUE TITLE
🐛 [Bug Report] WotLK - Locale not applied to broadcast texts.

### ISSUE THREAD

**Issue by ssj17vegeta** [cmangos/issues#2834]
### Bug Details

On a non-english (french) CMangos-wotlk server, broadcast texts appear in English although : 

1. The broadcast_text_locale table is populated, and the IDs between it and broadcast_text do match perfectly.
The following query, as expected, gives 0 rows returned:
```
SELECT Text, Text_lang FROM broadcast_text_locale
RIGHT JOIN broadcast_text ON broadcast_text.Id = broadcast_text_locale.id
WHERE (Text_lang = '' OR Text_lang IS NULL) AND Text <> '' AND Locale = 'frFR';
```
2. Other translations (locales_***** tables) work fine too.
3. DBC.locale set to 2, Server realmzone set to 10 in mangosd.conf.
4. WoW client's locale is french.

### Steps to Reproduce

1. Have french client + other settings mentioned in bug details. 
2. Face any instance boss (final boss in Gundrak, or talk to disciple of Naralex in wailing caverns after 4 bosses have been downed)... or any easier NPC using a broadcast text and make him/her talk.
3. Despair as you know your users don't master Shakespeare's language very well :laughing: 

### Expected behavior

Broadcast text should appear in the right language.

### Core SHA1 Commit Hash

fcdc506f0f37b2f1d7d86a8ca9e9f43b60252de8

### Database SHA1 Commit Hash

ca9ed3384dbff3591b7b14b64414cca671cf6625

### Operating System

Ubuntu Server Edition 21.10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
The wotlk-db install script has option:

LOCALES="NO"  

Make sure its on YES. its on NO by default because it slows db build and core start significantly.

**Comment by ssj17vegeta** [comment]
@killerwife just double-checked, it is set to YES in InstallFullDB.config.

As I said, everything else is translated properly, and broadcast_text / locale tables do contain the needed data (apart from very few things).

```SELECT COUNT(*) FROM broadcast_text ;```
73039

```SELECT COUNT(*) FROM broadcast_text_locale WHERE locale = 'frFR' ;```
72979

**Comment by ssj17vegeta** [comment]
So, it seems my test was incomplete. I've seen SOME texts included in broadcast_text_locale appear.

I checked a bit more, and it seems wrong numbers remain in the script for the boss I tested :

in boss_galdarah.cpp :
```SAY_AGGRO                  = -1604019,```

Where the proper id in broadcast_text_locale is 32534.

Is it because those scripts haven't been updated for the new mechanism yet, or am I missing something ?

**Comment by ssj17vegeta** [comment]
(Partially) solved by doing this : 

```UPDATE script_texts
INNER JOIN broadcast_text ON REPLACE(script_texts.content_default, '....', '...') = REPLACE(broadcast_text.Text, '....', '...')
SET broadcast_text_id = broadcast_text.Id
WHERE broadcast_text_id = 0 AND broadcast_text.`Text` IS NOT NULL;

I will submit a PR that fixes the missing links in the script_texts table :)

**Comment by ssj17vegeta** [comment]
Will be solved by https://github.com/cmangos/wotlk-db/pull/412
