### ISSUE TITLE
🐛 [Bug Report] 【TBC】Item : The Horseman's Reins has BUG

### ISSUE THREAD

**Issue by yuyu-lovegelin111333** [cmangos/issues#2835]
### Bug Details

The Horseman's Reins 
Player 's Riding Skill Level temporary Changed and Confused ! Onceif player use the item "Horseman's Reins " ID 37012 .

### Steps to Reproduce

1.Get Player's level to 40lv .
2.Go to any Riding trainer you know to learn Riding skill (primary one=75) .
3. Add item in your bag （"The Horseman's Reins " ID 37012）
4. Use this item ,and ride on this Mount.
5. ON this Mounting Model , Leveling up your Player to 41 or any other normal leveler .
6. You will see your character skill status bar auto increase to 225 （Riding skill medium =225）

### Expected behavior

No matter it was In Azeroth or Outland , the Horseman's Rein should no impact to Players' skill status .

### Suggested Workaround

<a href="https://sm.ms/image/ur2H7foEXxtjelk" target="_blank"><img src="https://s2.loli.net/2022/04/14/ur2H7foEXxtjelk.png" /></a>
<a href="https://sm.ms/image/8y4mwFvpiRBd2GX" target="_blank"><img src="https://s2.loli.net/2022/04/14/8y4mwFvpiRBd2GX.png" /></a>

### Core SHA1 Commit Hash

Newest in 2022-4-13

### Database SHA1 Commit Hash

Newest in 2022-4-13

### Operating System

WIN10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by yuyu-lovegelin111333** [comment]
@AnonXS @killerwife  . Sir， may you help on this ?

**Comment by yuyu-lovegelin111333** [comment]
woo. i 'am so sorry , i doesn't realised this effect . I will not ping them in future. Thanks for your mention .




















在 2022-04-15 02:05:40，"insuna" ***@***.***> 写道：

Please don't ping the devs when creating issues. They will get to it when they get to it and they see the issue as soon as it's posted, whether you ping them or not.

**Comment by AnonXS** [comment]
D - https://github.com/cmangos/issues/issues/2925
