### ISSUE TITLE
🐛 [Bug Report] The npc lying down can also turn around.

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2837]
### Bug Details

![动画](https://user-images.githubusercontent.com/3367999/163718283-349015a4-e3e4-4810-b11c-846dd1d0f7d8.gif)

### Steps to Reproduce

1. .go cr id 19882
2. Talk to NPC when they lie down.
3.
4.

### Core SHA1 Commit Hash

09bc8ec3ae47d3d681c77c1b122491d21bd2f588

### Database SHA1 Commit Hash

47984e93df92b42ea0a311dd2355ce38e6895979

### Operating System

Ubuntu 20

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
@aleigood , please retest this.

**Comment by killerwife** [comment]
In my defense, I did retest :D
