### ISSUE TITLE
🐛 [Bug Report] wlk mangosd crash

### ISSUE THREAD

**Issue by ximaiye** [cmangos/issues#2838]
### Bug Details

Characters can't go to Northrend. All channels will cause downtime 

### Steps to Reproduce

1.Thieves use hearthstone and the server goes down
2.The character goes to Northrend by boat. The character gets stuck and the server goes down
3.If the character goes to Northrend by any means, the server will be down
4.

### Crash Log

![图片](https://user-images.githubusercontent.com/103891456/163720074-46818b48-1367-4cdd-8936-f6a614ade7d6.png)

### Core SHA1 Commit Hash

7823fe038c239de9a014a6ef17a3bf539f4ca66c

### Database SHA1 Commit Hash

f5e6e30e859fa7b521707b2d06ffa2dcde37e405

### Operating System

linux

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
More information is required.

**Comment by insunaa** [comment]
Issue was abandoned and no further information was provided. Closing until there is more information
