### ISSUE TITLE
🐛 [Bug Report] Skill problem of death knight evil talent

### ISSUE THREAD

**Issue by ximaiye** [cmangos/issues#2841]
### Bug Details

The undead recovery under the evil talent of the death knight cannot summon ghouls。

### Steps to Reproduce

1.Press the undead recovery button under the evil talent of the death knight
2.The ghoul didn't come out
3.CD will appear
4.

![dk](https://user-images.githubusercontent.com/103891456/163909636-ba918188-e5f1-47ae-8405-d1dd9f810751.jpg)
![dk](https://user-images.githubusercontent.com/103891456/163909845-175f209f-e5f8-43dc-ab53-4ed07b8ff674.jpg)

### Core SHA1 Commit Hash

n/a

### Database SHA1 Commit Hash

n/a

### Operating System

linux

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
Fixed in https://github.com/cmangos/mangos-wotlk/commit/95c98331406a6718f6b96fb4c78a4ffa4c86c958
