### ISSUE TITLE
🐛 [Bug Report] quest

### ISSUE THREAD

**Issue by ximaiye** [cmangos/issues#2842]
### Bug Details

id 11270 is not complete

### Steps to Reproduce

1.the fire is not to burn corpse
2.id 11270 is not complete
3.
4.
![任务bug](https://user-images.githubusercontent.com/103891456/163918295-a23100ef-5fdc-48f2-be61-7e80b90f7099.jpg)

### Core SHA1 Commit Hash

n/a

### Database SHA1 Commit Hash

n/a

### Operating System

linux

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Grz3s** [comment]
Fixed by https://github.com/cmangos/mangos-wotlk/commit/38be9fb9ed6084e4875f0ee0ed6680ca6c5f1b1b
