### ISSUE TITLE
To catch a thistlehead quest 10570 WOTLK with suggested FIX🐛 [Bug Report] 

### ISSUE THREAD

**Issue by Eriumango** [cmangos/issues#2843]
### Bug Details

In this quest you hide whilst waiting for the NPC 21409 Envoy Icarius to go and pick up a bundle of bloodthistle. He is spawned with a unit flag which makes him non attackable (defined in creature_template)
There is no bit of the event ai which makes him attackable so you cant complete the quest by killing him when the quest giver tells you to attack him
I have included a new line to be added into dbscripts_on_event which removes the non attackable unit flag just before the quest give tells you to attack him
this works ok for me.

### Steps to Reproduce

1. get quest 10570 in shadowmoon valley
2. wait for the NPC icarius to spawn after planting the thistle
3. try and attack him when told to
4.
5.
6.

### Expected behavior

he should be killable when told to attack him

### Suggested Workaround

Update dbscripts_on_event with
```
insert  into `dbscripts_on_event`(`id`,`delay`,`priority`,`command`,`datalong`,`datalong2`,`datalong3`,`buddy_entry`,`search_radius`,`data_flags`,`dataint`,`dataint2`,`dataint3`,`dataint4`,`x`,`y`,`z`,`o`,`condition_id`,`comments`) values 
(13888,72000,0,48,256,0,0,21409,100,0,0,0,0,0,0,0,0,0,0,'icarius fix');

```
here the script entry fires on 72000 delay (just before the whisper on 73000) and removes the non attackable unit flag (256) for the creature 21409 (icarius)

### Core SHA1 Commit Hash

56f5cbf46046f6cece2c1f3ca2a07f540561cb08

### Database SHA1 Commit Hash

8b341a7d658ff4b362ddb142fde099039833793f

### Operating System

ubuntu 20.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Tbc-db should have a fix for a long time now on this @Grz3s check that maybe

**Comment by Grz3s** [comment]
pls be patient .. im doing tbc backports...
