### ISSUE TITLE
🐛 [Bug Report] Test Issue - Please Ignore

### ISSUE THREAD

**Issue by jimmybrancaccio** [cmangos/issues#2844]
### Bug Details

Hello world!

### Steps to Reproduce

1. Build
2. Deploy
3. Rejoice
4. $$$

### Core SHA1 Commit Hash

1234567890

### Database SHA1 Commit Hash

1234567890

### Operating System

macOS

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by jimmybrancaccio** [comment]
This is a test comment.

**Comment by jimmybrancaccio** [comment]
Test comment 2.

**Comment by jimmybrancaccio** [comment]
Test comment 3.

**Comment by jimmybrancaccio** [comment]
Please work!

**Comment by AnonXS** [comment]
closing for now as its assigned to you anyways.
