### ISSUE TITLE
[TBC] OOC after multiple misses while in Combat

### ISSUE THREAD

**Issue by RigaDev** [cmangos/issues#285]
How the bug is produced:

Variables: Player A, Player B.

Condition: Both players (A & B) are out ooc initially.

From test 1:
- A attacks B but every hit misses.
- A finally blows a hit on B but misses multiple times again (From tests it seems to be 2-3 times, >5 seconds) and both players get OOC.

From test 2:
- A attacks B and hits every time.
- A misses one hit and both players get OOC.

Conclusion: From the looks of it, it seems like the combat timer is the issues, it's not checking attackers status to know whether he's attacking still or not. I'm not sure if this is the issue, so my bad if it's not.

**Comment by cyberium** [comment]
Should be fixed
