### ISSUE TITLE
[Quest] King of the Foulweald

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2870]
The quest is found in Ashenvale... 
You can put the banner on the proper spot... the mobs will appear but they don;t come to attack the banner..
they should spawn in waves and coming to attack the banner, and after the last weave king m... should come 2...moment when you pick his totem after he is killed...
you get your quest item by killing the king, but the part with weaves is not working at all..

mobs only get;s spawned around the place, at the proper place from where they should come,, but they just stand there

https://tbc.wowhead.com/quest=6621/king-of-the-foulweald

**Comment by AnonXS** [comment]
Closing in favor of old issue with link to more data. https://github.com/cmangos/issues/issues/1980
