### ISSUE TITLE
[TBC] - Rogue Sap

### ISSUE THREAD

**Issue by ScullyNY** [cmangos/issues#288]
Hi,

if you use Sap you are automatically visible 
generally when one is discovered in stealth to get out

Youtube Link:

http://youtu.be/Dsfq_QmfEVQ

Part 2 (Duell)

http://youtu.be/Wb8ValaSCcE

**Comment by killerwife** [comment]
Checked issue recently, on my new TBC core, it works flawlessly. You can close the issue.

**Comment by cyberium** [comment]
Thank @killerwife
