### ISSUE TITLE
Quest 455 - The Algaz Gauntlet - missing startscript

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#2884]

**Comment by miraco** [comment]
I think that can get closed, there is nothing happening when accepting the quest.

https://youtu.be/j-EAi2TfLA8?t=30

**Comment by killerwife** [comment]
This one was wrongly written up, the actual thing is an orc intercepting u when u walk along the road and doing a yell on los, it might not be tied to quest but it does happen when you walk there as ur intended on this q.
