### ISSUE TITLE
Quest 4763 - The Blackwood Corrupted - recheck heavy script

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#2887]

**Comment by insunaa** [comment]
I've reworked the script a few months ago https://github.com/cmangos/mangos-tbc/blob/6e17b8159839b0e493aaaadd9c604b0ddf3f7bf4/src/game/AI/ScriptDevAI/scripts/kalimdor/darkshore.cpp#L772

There is one thing that's unclean imo and that is that the `bowlCoords` variable is global(ish)

I could probably put it into a custom function that I call for each furbolg? I'm open to suggestions. Other than that the scripting for this quest works flawlessly, as far as I can tell.

**Comment by killerwife** [comment]
The only major major flaw you are correct. That being said, here https://github.com/cmangos/mangos-tbc/blob/6e17b8159839b0e493aaaadd9c604b0ddf3f7bf4/src/game/AI/ScriptDevAI/scripts/kalimdor/darkshore.cpp#L1007 you can pass the position to the function instead and set it there :)

Next u can remove these https://github.com/cmangos/mangos-tbc/blob/6e17b8159839b0e493aaaadd9c604b0ddf3f7bf4/src/game/AI/ScriptDevAI/scripts/kalimdor/darkshore.cpp#L937 with GetNewAIInstance

And since you are using TimerManager, you should completely remove void UpdateAI(const uint32 diff) override usage through CombatAI. You can easily add additional combat actions in the child classes. // Flee at 15% HP can be done with a timerless action just search for AddTimerlessAction examples.

**Comment by insunaa** [comment]
Alright, I'll update the script!
