### ISSUE TITLE
Quest 403 - Guarded Thunderbrew Barrel - afterscript

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#2903]
Starts a big sequence where barrel state changes and guy runs up to get a beer and an RP and then returns back down.

**Comment by miraco** [comment]
I couldnt accept [Guarded Thunderbrew Barrel (ID 403)](https://classic.wowhead.com/quest=403/guarded-thunderbrew-barrel) on tbc ptr, but i think i saw the rp event you mean.

What basicly happens: after accepting Quest [Bitter Rivals (ID 310)](https://classic.wowhead.com/quest=310/bitter-rivals) you go to the barrel. 
You can then accept and complete quest [Distracting Jarvan (ID 308)](https://classic.wowhead.com/quest=308/distracting-jarven)
On Completion the npc moves away from the barrel and the barrel changes state so you can finish Quest [Bitter Rivals (ID 310)](https://classic.wowhead.com/quest=310/bitter-rivals) 

Have to research when this should be acceptable
