### ISSUE TITLE
Object 184640 - Magtheridon's Head

### ISSUE THREAD

**Issue by SabriynaVermillion** [cmangos/issues#2915]
object is visible, but should only be visible to everyone when the event begins

https://youtu.be/yNfZEO_fReo?t=38

**Comment by AnonXS** [comment]
Currently they are also not changing state when the quest is turned in, regression since animprogress/state change @killerwife 

![grafik](https://user-images.githubusercontent.com/19734826/233786404-5c6e8010-8e94-4013-8d38-97b4a15e6081.png)

```
alliance

.tele honorhold
.add 32385
turn in
.tele honorhold
```

Same bug supposedly with onyxia/nefarian heads.

**Comment by miraco** [comment]
This got fixed a while ago, cant find the commit atm. Pls open a new one if its not working for you

**Comment by killerwife** [comment]
Can confirm i have my hands in fixing this one.
