### ISSUE TITLE
Quest 331 - Report to Doren - missing startscript

### ISSUE THREAD

**Issue by AnonXS** [cmangos/issues#2918]
Somewhere between turning in q.330- 331, rather start of 331

Private Merle entry:1421 turns (neutral)

shouts at the player and runs out of the camp towards duskwood, where he is killed of by 3? script spawned

https://tbc.wowhead.com/quest=330/patrol-schedules#comments:id=106124
https://tbc.wowhead.com/quest=331/report-to-doren#comments:id=210306
https://tbc.wowhead.com/quest=331/report-to-doren#comments:id=146067:reply=14464

https://tbc.wowhead.com/quest=331/report-to-doren#comments:id=2932964
https://tbc.wowhead.com/quest=331/report-to-doren#comments:id=2771587 - Rebel Watchman?

**Comment by miraco** [comment]
https://github.com/cmangos/tbc-db/commit/2a81460ff5ce1f153d224ffd07382e787e014b92
