### ISSUE TITLE
💬 respawn delay? [Support Request] 

### ISSUE THREAD

**Issue by rmzV** [cmangos/issues#2929]
### Core Version

mangos-wotlk

### Support Request Details

Hello!
Respawn time on some creatures way to fast.(((
I looked at mangos config file. and could not figure out how to fix it(

### Steps to Reproduce

1.Killing mobs and they are already repawned((
2. 
3.
4.

### Core SHA1 Commit Hash

18b5072f084939cf7ccfef5cf40e6c871be3575e

### Database SHA1 Commit Hash

b2707d740b6784e48db65ad1747ce136ea6915fc

### Server Operating System

win 8

### Client Version

3.3.5a (Wrath of the Lich King)

### Client Operating System

win8

**Comment by rmzV** [comment]
@Grz3s 
Hello. i am asking about tweaking config file help) 
i think respawn time is a blizz like, but they respawn way too fast for solo gaming.((
examples: trolls near zul'aman (ghostlands) and Scarlet wariors near Agamand Mill (tirisfal glades)

**Comment by AnonXS** [comment]
There are no spawns at 73 57 in either tbc-db nor wotlk-db. `.go zonexy 73 57`, `57 73` has them at 5mins, same with tirisfal glades, not sure why you need more then 5mins time to clear this, even in sologame.

**Comment by rmzV** [comment]
@AnonXS if you has same lvl as npcs and have agroed 2 or 3 of them (depends on class) you will die.
example [Nissa Agamand](https://www.wowhead.com/npc=1655/nissa-agamand) 
get killed on her multiple times, running back and forth from graveyard takes more then 5 min.((

is that parameter (5 min) can be changed via config file?

**Comment by rmzV** [comment]
@AnonXS if you has same lvl as npcs and have agroed 2 or 3 of them (depends on class) you will die.
example [Nissa Agamand](https://www.wowhead.com/npc=1655/nissa-agamand) 
get killed on her multiple times, running back and forth from graveyard takes more then 5 min.((

is that parameter (5 min) can be changed via config file?

**Comment by AnonXS** [comment]
Not in our core, just do `Rate.Creature.Normal.Damage = 0.5` or something then you have no issues. else report the mobs, `.guid` command and report their entrys / id here so we can see if some respawn is too fast, 300secs aka 5mins is normal.

**Comment by AnonXS** [comment]
With no further evidence and both places having 5mins flat respawn timer, i'm closing this as it holds no purpose. we're not a 5min project that indends to make all content perfectly playable for soloplayers.

you should be able to kill a few mobs in a few minutes if you are playing seriously. if you are getting cornered by patrols & respawn and die, thats your fault, not the respawn.

if you come up with locations that actually suffer from too fast respawn (3 to 5mins), open a new issue.

**Comment by rmzV** [comment]
@AnonXS 
i just asked if it possible to change in config file=)
