### ISSUE TITLE
[TBC] Debuff limit

### ISSUE THREAD

**Issue by overy** [cmangos/issues#293]
Max debuff limit for TBC is 40. I dont understand how it is work in core, but in SpellAuraHolder::_AddSpellAuraHolder are 

else                                                // empty negative slot
        {
            for (uint8 i = MAX_POSITIVE_AURAS; i < MAX_AURAS; i++)
            {
                if (m_target->GetUInt32Value((uint16)(UNIT_FIELD_AURA + i)) == 0)
                {
                    slot = i;
                    break;
                }
            }
        }

So we are can have 16 debuffs? (MAX_POSITIVE_AURAS is 40 and MAX_AURAS is 56) but correct is 40 debuffs.

**Comment by killerwife** [comment]
The only mention I found of this thingy is this 
http://wowwiki.wikia.com/wiki/API_UnitAura 
http://wowwiki.wikia.com/wiki/API_UnitDebuff
http://wowwiki.wikia.com/wiki/API_UnitBuff
Debuff had maximum index of 40, but the maximum index for buff was unlimited. Can be tested by writing own addon and using a higher index for HELPFUL than 16 maybe?

**Comment by VladimirMangos** [comment]
We can't send to client more 16 debuffs data in TBC. I notsure at 100% how this work in TBC days at official servers.  Maybe possible have more debuffs but only first 16 show to client. But this must create problems with diff debuff affected values that show client by self...

**Comment by killerwife** [comment]
So then the code snippet is correct, and working properly, or whats the issue here?

**Comment by VladimirMangos** [comment]
It's correct in  data sending to client (visible from client debufffs [CD]). I  not sure abour server side (really applied to unit debuffs [RD]). Currently CD == RD This is correct if no confirmations in existance hiddent server side debufs in TBC time. So you sure that more 16 debufs applied but its not show all client.

**Comment by cyberium** [comment]
Not an issue

**Comment by killerwife** [comment]
It is an issue ^^ Should have solution in cmangos within next 1-2 months. Keeping it open till then.

**Comment by cyberium** [comment]
Ok so it will be closed in 2 month 👍

**Comment by dagochen** [comment]
half a year later .... ;) @killerwife  @cyberium

**Comment by killerwife** [comment]
Believe it or not, most of it is already out. I exported all the packet implementation. Only the smallest last part is missing. Expect it on next export spree next month. (you know I do these periodically)

**Comment by jimmybrancaccio** [comment]
@killerwife Just touching base on this one since it's been a while 😁

**Comment by killerwife** [comment]
Done a few months ago.
