### ISSUE TITLE
🐛 [Bug Report] q.2381 'Plundering the Plunderers' doesn't work

### ISSUE THREAD

**Issue by yyhhrr** [cmangos/issues#2931]
### Bug Details

https://github.com/cmangos/classic-db/commit/4a058641808cebe37f11d4a11513e1f8c495f2f7
gossip_menu_option condition_id=218 was wrong.(condition_id 218=Has Minimum Rank Exalted With Faction ID: 69)I don't think so.I think correct id was 1091(Quest ID 2381 Taken).poor english sorry.

### Steps to Reproduce

1.Get the quest
2.no gossip_menu_option show 
3.
4.

### Core SHA1 Commit Hash

6bdbad07e5447c42356a80d91d1172032a24c438

### Database SHA1 Commit Hash

2ed629eb754754ca696e84ed665e7738ed9a6535

### Operating System

win 10

### Client Version

1.1.12 (Classic)

**Comment by Grz3s** [comment]
@cala forgot to check if condition is the same between both db's
wotlk `218`,`9`,`2381`. `Quest ID 2381 Taken`;

**Comment by yordangrigorov97** [comment]
Replicated on commit 2ed629eb754754ca696e84ed665e7738ed9a6535 Solution suggested @yyhhrr fixes the bug
