### ISSUE TITLE
🐛 [Bug Report] Quest 11169 can not be complete

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2933]
### Bug Details

https://www.wowhead.com/tbc/quest=11169/the-grimtotem-weapon

Quest targets cannot be counted correctly.

### Steps to Reproduce

1. .quest add 11169
2. .go xyz -3870.99 -3039.53 33.251499 1
3. Release the totem and kill the crocodile
4.

### Core SHA1 Commit Hash

033194d32b4781d73b2be27facf22612dbc5fe20

### Database SHA1 Commit Hash

82042c4693226662be565ff663814a5be1639ef1

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
completeable again.

![grafik](https://user-images.githubusercontent.com/19734826/219802954-4415b1bb-15f7-4ce0-a79d-337a27d1b5fe.png)
