### ISSUE TITLE
🐛 [Bug Report]  Database update error using ./InstallFullDB.sh  option 3

### ISSUE THREAD

**Issue by Logandros** [cmangos/issues#2934]
### Bug Details

As per the WIKI and updating the Classic DB:

https://github.com/cmangos/issues/wiki/Detailed-installation-guide-for-Microsoft-Windows#database-update

Choosing option 3 to update (a clean existing unmodified install) now gives an error after the latest db contributions. This error was not present in earlier versions when following the WIKI procedure.

https://pastebin.com/Fmnwp6m5

### Steps to Reproduce

1. git fetch
2. git pull
3. ./InstallFullDB.sh
4. Choose Option 3

### Expected behavior

Database should update provided there have been no user modified tables.

### Suggested Workaround

n/a

### Crash Log

All previous changes will be lost. Type 'Install' if you are sure : Install
 
> Processing main Classic-DB release file "Melting Pot" ...
  - Applying ClassicDB_1_12_z2793.sql ... SUCCESS
 
 
> Trying to process Classic-DB updates
  - Applying Updates/3891_1_z2794_01_mangos_spawn_group_chanced_spawns.sql ... SUCCESS
  - Applying Updates/3891_2_ashenvale_legion_hounds.sql ... SUCCESS
  - Applying Updates/3892_ashenvale_bonfire.sql ... SUCCESS
  - Applying Updates/3893_ashenvale_mannoroc_lasher.sql ... SUCCESS
  - Applying Updates/3894_ashenvale_diathorus_the_seeker.sql ... SUCCESS
  - Applying Updates/3895_ashenvale_dirt_mound.sql ... SUCCESS
  - Applying Updates/3896_ashenvale_demon_ridge_cave.sql ... SUCCESS
  - Applying Updates/3899_razorfen_downs_goldthorn.sql ... SUCCESS
  - Applying Updates/3900_razorfen_downs_arthas_tear.sql ... SUCCESS
  - Applying Updates/3901_razorfen_downs_grave_moss.sql ... SUCCESS
  - Applying Updates/3902_zzarc_vul_spawn.sql ... SUCCESS
  - Applying Updates/3903_gurubashi_arena_tele.sql ... SUCCESS
  - Applying Updates/3904_forsaken_disease.sql ... SUCCESS
  - Applying Updates/3905_carnivous_the_breaker_loot.sql ... SUCCESS
  14 successfully added.
 
> Trying to set last content update version in db
  - Applying version changes ... FAILED!
>>> ERROR 1091 (42000) at line 1: Can't DROP 'content_z2778_01_logs_anticheat'; check that column/key exists
>>> Failed to update content version!
Press space to continue...

### Core SHA1 Commit Hash

6bdbad07e5447c42356a80d91d1172032a24c438

### Database SHA1 Commit Hash

e4a6f692ec7c8ee092f0abad161118fd36dc483b

### Operating System

Windows 11

### Client Version

1.1.12 (Classic)

**Comment by ale10bb** [comment]
line 1494 should be:
DB_LAST_CONTENT_VERSION_UPDATE=$(echo -n "${DB_LAST_CONTENT_VERSION_UPDATE//content_}") # remove "content_"
but not:
DB_LAST_CONTENT_VERSION_UPDATE=$(echo -n "${CURRENT_DB_VERSION//content_}") # remove "content_"
$CURRENT_DB_VERSION will normally point to "logs_db_version" during checking database "classiclogs" at line 869.

**Comment by ale10bb** [comment]
line 1494 should be:
DB_LAST_CONTENT_VERSION_UPDATE=$(echo -n "${DB_LAST_CONTENT_VERSION_UPDATE//content_}") # remove "content_"
but not:
DB_LAST_CONTENT_VERSION_UPDATE=$(echo -n "${CURRENT_DB_VERSION//content_}") # remove "content_"
$CURRENT_DB_VERSION will normally point to "logs_db_version" during checking database "classiclogs" at line 869.
(maybe 1494 copied from line 774 without modifying variable)

**Comment by Logandros** [comment]
I can confirm this issue was resolved as of [3907](https://github.com/cmangos/classic-db/commit/10ea0a0eac8d0860d1b682951eff86662cd7f4a0)
