### ISSUE TITLE
🐛 [Bug Report] Classic: rune of duty item 21568 show wrong reputation in vendor menu

### ISSUE THREAD

**Issue by yyhhrr** [cmangos/issues#2935]
### Bug Details

rune of duty item 21568 show wrong reputation,Use a horde character, but it shows that  needs alliance reputation.There are other battlefield equipment is also showing the wrong reputation requirements

### Steps to Reproduce

1.just buy the item
2.
3.
4.

### Core SHA1 Commit Hash

6bdbad07e5447c42356a80d91d1172032a24c438

### Database SHA1 Commit Hash

e4a6f692ec7c8ee092f0abad161118fd36dc483b

### Operating System

win 10

### Client Version

1.1.12 (Classic)

**Comment by insunaa** [comment]
Can you write a more detailed report on this? Maybe include screenshots to show what you're saying?

**Comment by AnonXS** [comment]
He's trying to tell us that our vendor is missing 2 items.

**Comment by yyhhrr** [comment]
There is screenshots
![image](https://user-images.githubusercontent.com/3608322/167108064-39949f00-ff1a-42b2-9ece-167b2f5183ec.png)

**Comment by AnonXS** [comment]
Ah okay, so its an classic-db only issue (with item_template). though i found something interesting out of this. seems horde vendor does not sell the Rune of Perfection for horde, also confirmed this with classic tbc data but wowhead shows it is sold.

**Comment by AnonXS** [comment]
https://classic.wowhead.com/npc=14754/kelm-hargunth#comments:id=3169109

so the items should not have the Rep Requirement, but the Items in the Vendor Lists should. Same with the Quests they offer at friendly.
You shouldnt be able to buy from them befor you reach friendly rep with faction 890 (alliance),889 (horde)

**Comment by yyhhrr** [comment]
I think it is correct that you need a friendly reputation to buy things from NPCs.But I don't think it's right to remove the rep requirement for item。Like https://classic.wowhead.com/npc=14754/kelm-hargunth#comments:id=3169109 ,this link said friendly for  Food/Bandages Honored for Rare Armor Revered for Rare Weapons
Exalted for Epic Bracers.

**Comment by AnonXS** [comment]
where does it say that?

**Comment by insunaa** [comment]
Yes, you need to have specific ranks of reputation to even see the items they sell I believe. At the very least I can confirm without a doubt that you need to have varying levels of reputation there. Source: 19s PvP
This goes for all PvP vendors in 1.12.x
They removed the rep requirements with tbc

**Comment by AnonXS** [comment]
but you get that one quest when you reach friendly, are all items behind rep requiremnt which made the vendor list empty or not showing?

**Comment by insunaa** [comment]
I'll have to check, it's been a while.
I remember having to grind for weeks to get the required rep to buy the ring and necklace for my 19s PvP character...

**Comment by AnonXS** [comment]
Ok, no you're right the gossip was removed.
