### ISSUE TITLE
🐛 [Bug Report] pathfinding wotlk

### ISSUE THREAD

**Issue by jokerlfm** [cmangos/issues#2938]
### Bug Details

pathfinding in wotlk is not working.
build path, find tiles always return empty.

### Steps to Reproduce

1. check logs or try to engage with a mob which need to find path to get to player.

### Core SHA1 Commit Hash

e5e96e756b18e51519acdd6f244504dfb8993a4f

### Database SHA1 Commit Hash

e5e96e756b18e51519acdd6f244504dfb8993a4f

### Operating System

Windows server 2019

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by jokerlfm** [comment]
I tried the version before 4/19. commit  eadf3f5 - "MMAP: Implement pathfinding for alternate tiles with GameObjects"
Everything going well.
So maybe the commit and new version of mmaps is the cause.

**Comment by kelbren** [comment]
I can confirm and agree with Jokerlfm, prior to 4/19 path-finding worked as expected. Mobs and pets, bots etc, all ignore path-finding, and jump in a more or less straight line towards their target. ignoring objects and such.

**Comment by killerwife** [comment]
I will check this out :)

**Comment by killerwife** [comment]
Okay so, I extracted all my mmaps on 24th of April and pathfinding indeed works. I did a simple test .go creature 12364, stood around the stairs and aggroed someone from the inside.

So I will need more information :)

**Comment by killerwife** [comment]
https://youtu.be/Ff21OIRC4To Hopefully I managed not to reveal any personal information on this one :D 

Anyway, working as intended on my end.

**Comment by aleigood** [comment]
April 30, I found the pathfinding problem and the map data was extracted on March 31, 2021. So I use the core and extractor tool with build on the lastest source code and extracted all mmaps, but the problem remains.

**Comment by killerwife** [comment]
Perhaps showcase your config, make sure to remove all passwords tho. gist.github.com

**Comment by aleigood** [comment]
Only two changes have been made, the other is the database and localization settings.

![image](https://user-images.githubusercontent.com/3367999/167620825-791c040b-4020-4170-9df0-761123694ddd.png)

**Comment by killerwife** [comment]
Reproduced, NormalizeZ is the issue. I will resolve the issue asap.

**Comment by kelbren** [comment]
I am not getting path finding to work at all in wotlk, (mobs run in a straight line, jumping over objects, and flying through the air)  I have pulled a current version and build everything including the extractors. When running the extract process, it segfaults during mmap generation.  I removed the --extractGameObjects option, and it completes without crashing.  I placed the fresh extracted files in the data folder for the server. and updated the binaries to latest.
still no path finding. NormalizeZ = 0 or 1 no change. 
Using Ubuntu 18.04 for everything.

**Comment by killerwife** [comment]
So my investigation shows several problems.

Easiest problem was this:

https://github.com/cmangos/wotlk-db/commit/55e71150e1fd8bdf0f2dc5ffe48137100dda6d77

Next, Oceans pathfinding meshes were only added recently and are still generally wonky so around oceans it will be a bit of an issue for the foreseeable future until we figure it out.

Lastly, there is no --extractGameObjects, only --buildGameObjects. I just tested that one and found the crash and fixed the crash.

**Comment by kelbren** [comment]
oops, I meant --buildGameObjects,  and thanks for this, I will re-build the extractors and test.
Thanks for the quick response, fixes and all the efforts, we all appreciate it.

**Comment by blitzi** [comment]
Hey ho, I guess the filepath is wrong here https://github.com/cmangos/mangos-wotlk/blob/547e159679e6d6ddd219898ed81c2c0b7be65c53/src/game/MotionGenerators/MoveMap.cpp#L232

it should be  std::string filePath = sWorld.GetDataPath() + std::string("mmaps/") + fileName;

and just to make sure the path length is not exploding we could either calculate the path length or just set the fileName buffer size to 256 instead of 100

After this change it worked on my fork

**Comment by kelbren** [comment]
Adding the sWorld.GetDataPath  has path finding working for me now.
Thank you.

**Comment by killerwife** [comment]
Changed that and linked the commit here. Caused by me when I added some big recent features.

**Comment by AnonXS** [comment]
You also learned the pirates to swim, so if they "can" go into water and out they will not have anymore issues.

https://github.com/cmangos/tbc-db/commit/e64630e354e80534936f94502706634df4686b49
