### ISSUE TITLE
Spell 52150 resurrect dead does not work for a death knight

### ISSUE THREAD

**Issue by LeXXyrus** [cmangos/issues#2942]
### Core Version

mangos-wotlk

### Support Request Details

The death knight spell does not work raise the dead (52150). If the specified conditions are met, the icon remains gray, the action does not occur, the update timer does not start. When re-entering the game client, the icon is again ready for a null action without a cooldown.

### Steps to Reproduce

1.
![ScreenShot_051222_192354](https://user-images.githubusercontent.com/95984364/168124918-81fd3dd8-62f3-4ddb-874f-191424cfb63a.jpeg)

2.
3.
4.

### Core SHA1 Commit Hash

5788aa22ae12f3d416f520972295bc34dcdda068

### Database SHA1 Commit Hash

b5d13e747da1c5ba6701c7bbae129eb7e29e985c

### Server Operating System

ubuntu 18.04 x64

### Client Version

3.3.5a (Wrath of the Lich King)

### Client Operating System

Windows 10 x64

**Comment by LeXXyrus** [comment]
https://user-images.githubusercontent.com/95984364/172455231-9c1ce9db-ae89-482b-a33b-7a3724c56f84.mp4   I am attaching a video of the behavior. Either I do not understand the trigger conditions correctly, or the system on which I deploy the game server is to blame.

**Comment by danjohnso** [comment]
I think its an issue with the character ability.  The spell itself works correctly when cast by a GM, but something with the Death Knight ability is causing the summon to fail.

**Comment by insunaa** [comment]
Fixed in https://github.com/cmangos/mangos-wotlk/commit/95c98331406a6718f6b96fb4c78a4ffa4c86c958
