### ISSUE TITLE
🐛 [Bug Report] [Quest] Triage [6624] NPC spawn location error. 

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#2944]
### Bug Details

![image](https://user-images.githubusercontent.com/3367999/168306932-a5f566f4-a437-4bc0-b543-c1a6c6c77c27.png)

### Steps to Reproduce

1. .go xyz -3745.375 -4531.835938 11.910 1
2. .learn 7924
3. .setskill 129 225
4. .quest add 6624

### Core SHA1 Commit Hash

033194d32b4781d73b2be27facf22612dbc5fe20

### Database SHA1 Commit Hash

82042c4693226662be565ff663814a5be1639ef1

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
I was there just today and didnt see this.

**Comment by Exxenoz** [comment]
The quest "Triage" seems to be broken in cmangos wotlk. The injured npcs are healing automatically and the quest never ends.

**Comment by AnonXS** [comment]
this is unrelated to this visual bug, if there is a new issue related to this quest, please open a new issue.

**Comment by Grz3s** [comment]
https://github.com/cmangos/wotlk-db/commit/e5cb9bff685fd4248660ec52cb1d2512069a6eaa - fixes WotLK
