### ISSUE TITLE
🐛 [Bug Report] Hunter BM Talent Kindred Spirits stacking

### ISSUE THREAD

**Issue by ReneM** [cmangos/issues#2948]
### Bug Details

Whenever a pet is summoned, a new stack of [Kindred Spirits](https://wotlk-twinhead.twinstar.cz/?spell=56318) is added to its buffs, leading to massive damage numbers:
![image](https://user-images.githubusercontent.com/483707/168675705-6678c0cc-95af-4258-a989-7532a52bbe0a.png)

After a few dismisses/resummons:
![image](https://user-images.githubusercontent.com/483707/168675527-7490dbcb-19a1-475b-977c-41aed9469576.png)

After mounting (which removes the pet) and dismounting (which re-summons it), this is its stats:
![image](https://user-images.githubusercontent.com/483707/168675600-a382e75c-9ae7-4edf-a8d2-d5dc6a01dd7d.png)

The buff is not supposed to stack, so I'm guessing either a removal is missing, or an exists-check is missing somewhere.

### Steps to Reproduce

1. Spec a Hunter into the Beastmastery talent "Kindred Spirits"
2. Summon a pet
3. Either mount up or Dismiss the pet
4. Dismount or "Call pet" - the amount of Kindred Spirit buffs on the pet should have increased.

### Expected behavior

A single stack of Kindred Spirit on the pet.

### Suggested Workaround

Killing the pet seems to reset the stacks.

### Core SHA1 Commit Hash

725b2d511dc9e80791d9e0fb78fba3211f6df2a7

### Database SHA1 Commit Hash

Unknown

### Operating System

Windows

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by danjohnso** [comment]
This fixed it: https://github.com/cmangos/mangos-wotlk/commit/9e8ab1320b2e31527e6123f2ebab2f64f543a71a
