### ISSUE TITLE
🐛 [Bug Report] q.4966/protect-kanati-greycloud script bugged

### ISSUE THREAD

**Issue by yyhhrr** [cmangos/issues#2951]
### Bug Details

When the mission starts, the npc starts to summon enemies infinitely and the mission cannot be completed.
![image](https://user-images.githubusercontent.com/3608322/170477316-ca8cf3eb-4036-4504-b31c-414d541f53b1.png)
![image](https://user-images.githubusercontent.com/3608322/170477348-5d02f0be-584a-49c5-b284-fc9d1c1901e1.png)

### Steps to Reproduce

1.take the task
2.npc starts to summon enemies infinitely
3.the mission cannot be completed

### Core SHA1 Commit Hash

af7fdb9e92ee7b5dd67944466314af24cc3e882b

### Database SHA1 Commit Hash

29b5b76c8c2b6e804e52fa4dd2ca203901d7cf77

### Operating System

win 10

### Client Version

1.1.12 (Classic)

**Comment by yyhhrr** [comment]
It seems like the summoning class of tasks have a common problem. like#2833

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/commit/85221137fadf49f5e5b0a54d9117529cace418ad  
https://github.com/cmangos/tbc-db/commit/b00e9999a9703870d003e42953b681dd2cd0b9d7  

modernized the script, the issue was missing waittime at the end of the waypoints

**Comment by yyhhrr** [comment]
can you port this to classic version,please?

**Comment by killerwife** [comment]
Later this week i will sync cores
