### ISSUE TITLE
🐛 [Bug Report] Increased reputation

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#2952]
### Bug Details

New installation cmangos-classic. mangosd.conf.dist no change.
Increased reputation. Got 75 - really 93. Also, I think it should be 50, not 75.
![1](https://user-images.githubusercontent.com/32430541/170602993-23f87d56-0366-4f66-8572-b1a9c34d0e52.JPG)
![2](https://user-images.githubusercontent.com/32430541/170603004-355ab03c-ae70-403a-aea7-94401b0ca371.JPG)

### Steps to Reproduce

Increased all reputations

### Expected behavior

Normal reputations

### Core SHA1 Commit Hash

20de401363515e37fad31a8d500458fffde05414

### Database SHA1 Commit Hash

29b5b76c8c2b6e804e52fa4dd2ca203901d7cf77

### Operating System

Windows 10

### Client Version

1.1.12 (Classic)

**Comment by AnonXS** [comment]
maybe start with writing down some quest name or id.
