### ISSUE TITLE
💬 [Support Request] 

### ISSUE THREAD

**Issue by howarduong** [cmangos/issues#2962]
### Core Version

mangos-classic

### Support Request Details

Hi! Friends, I saw 1.14.0 support login on youtube, I don't know when the Cmangos server will be updated to support 1.14.0
https://www.youtube.com/watch?v=vAFMiQjdhRM

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

1

### Database SHA1 Commit Hash

1

### Server Operating System

windows11

### Client Version

1.1.12 (Classic)

### Client Operating System

windows11

**Comment by celguar** [comment]
@howarduong Hello, it works, just watch the video you linked 😉

**Comment by howarduong** [comment]
Thank you for your answer. Can Cmangos be directly integrated into the Hermes Proxy code to natively support 1.14.0 clients?

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年5月31日 23:14
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [cmangos/issues] 💬 [Support Request] (Issue #2962)


The system works separately. Cmangos does not need any alterations to work with the hermes proxy (I have been making miniscule changes to fix some crashes). As such you need to refer to Hermes Proxy github to see how to set it up. I am closing this since we already did what was necessary so its compatible.

**Comment by killerwife** [comment]
Native support for 1.14 isnt planned at this point in time. Thats however the point of the proxy, so that we dont need native support. @ratkosrb is the author of Hermes
