### ISSUE TITLE
🐛 [WOTLK] Summoned NPC Pet's behaviour 

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2963]
### Bug Details

If a NPC have a pet, summoned by him, and if we kill the NPC master, shoudln't the pet  despawn also? like in player case?

Cause currently if u kill the NPC master the summoned pet continue to fight

### Steps to Reproduce

1.
2.
3.
4.
find a npc that can summon a pet

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
This is not default generic behavior.

Has to be reviewed case by case and of most open world mobs this is wrong.

**Comment by al3xc1985** [comment]
this is a general open world behaviour that I describe. I don't know in dungeons or instances.

Did u closed it because u guys have it noted down?

**Comment by AnonXS** [comment]
we have it noted, but its not as you say "master dies" "pet despawns" it always differs so either you start opening reports with videos for special cases we dont change it.

**Comment by al3xc1985** [comment]
ok, ty

**Comment by al3xc1985** [comment]
I see from here, and from what we allready have in Issue tracker or wotlk db issue tracker that there is a lot of work for you guys..
And most of not working and needed script for quests are there and u have them noted.

Well, I shall see what I can do with my reports in this case. It might better for me to wait and keep testing and report small things like missing equipment, or a small faction problem not working, or missing loot, or ability, cause in rest u are all aware of what is needed for future.

Well ty, and have a nice day!
