### ISSUE TITLE
Jerky  Movement

### ISSUE THREAD

**Issue by whitegear** [cmangos/issues#297]
Classic:
As much of a bug report as a general question:

I noticed that mobs that change in elevation upon aggro (charging down hill at a player) often show very jerky / choppy movement.  Is there any way this is dictated by the conf. files, or is this primarily a code issue (guessing spline related?)

To replicate:
Locate a mob that is on a hill, aggro the mob with a ranged ability and watch it stutter / jerk / chop its way to you.  

Rev.2401

**Comment by cyberium** [comment]
I think this was improved a lot since 2014
