### ISSUE TITLE
🐛 [Bug Report] AV - Incorrect BG is over text

### ISSUE THREAD

**Issue by henhouse** [cmangos/issues#2980]
### Bug Details

Semi-follow up to issue #

Herald should announce the winner of the BG, but instead we are showing a BG server message instead.

CMaNGOS:
![image](https://user-images.githubusercontent.com/30731/172044398-19a4220d-0a66-4b95-b0b7-80aaf282e703.png)

How it should look:
https://youtu.be/6eSLfOlXLiU?t=1625

Nit-picky thing: looks like Marks of Honor should be awarded BEFORE both these texts go off as well.

### Steps to Reproduce

1. Enter AV
2. Kill a general
3. See the end text

### Core SHA1 Commit Hash

3d36ba976

### Database SHA1 Commit Hash

fd60ec30

### Operating System

Windows 10 x64

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Dont we have this problem in all bgs? Or are the other bgs system msges
