### ISSUE TITLE
🐛 [Wotlk Db] Moon Prietess Amara Guards  not walking along the priestess

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2983]
### Bug Details

Moon Priestess Amara 
https://classic.wowhead.com/npc=2151/moon-priestess-amara
Huntress Nhemai
https://classic.wowhead.com/npc=10604/huntress-nhemai
Huntress Yaeliura
https://classic.wowhead.com/npc=10606/huntress-yaeliura

Ok as the tittle say, the guards are not walking near the priestess but a very long distance. Something is wrong in here. I mean I restart the server and they are not syncronized at all in movement. The priestess continue to walk, and the guards come at long distance. They do get in combat when priestess get in combat, run fast to her but get back to first point after and continue to walk with her, but at very long distance.

Is like her path is loaded when server starts, and guards path is loaded when u enter in visibility

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
I think grind unload/load do the trick

**Comment by Grz3s** [comment]
they need to be moved to spawn groups.. this will resolve old linking issue...
Ill reopen this .. to not forget about it ;)

**Comment by al3xc1985** [comment]
:)) ok ty
