### ISSUE TITLE
🐛 [Wotlk] Discerning Eye of the Beast - does not restore mana

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2985]
### Bug Details

https://wotlk.evowow.com/?item=42992

The item does not restore 2% of your mana whenever u kill a target that gives exp or honor

Instead it gives me like 0.5% in hp

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by DrKittens** [comment]
Is your player character dealing the killing blow and not a pet / summon / party member?

**Comment by al3xc1985** [comment]
player (me)
