### ISSUE TITLE
Detour/Pathfinding - Shallow Water/Exiting/Entering Water

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2986]
### Bug Details

As the tittle say, this creatures can't come out of water to attack u

Greymist Coastrunner
https://classic.wowhead.com/npc=2202/greymist-coastrunner
Greymist Raider
https://classic.wowhead.com/npc=2201/greymist-raider

### More Examples
1. npc=4818 from water into water, getting stuck
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
Sadly yes, general issue with mob going In/Out of water, sometimes it works fine other times not.

E.g why that guy has MMAP Ignore which also does not help seemingly
https://media.discordapp.net/attachments/279269987544203265/983091519500206120/unknown.png

or .go c id 513
https://media.discordapp.net/attachments/279269987544203265/983053132806381588/unknown.png?width=617&height=584

or that one
https://media.discordapp.net/attachments/279269987544203265/934436689588404234/unknown.png

or Object GUID is: Creature (Entry: 16349 Guid: 99434)
https://media.discordapp.net/attachments/279269987544203265/978710121888743474/unknown.png

**Comment by al3xc1985** [comment]
37854 & 37862

**Comment by al3xc1985** [comment]
Tide Crawler
38564 & 38543

**Comment by al3xc1985** [comment]
Also dunno if this is related to smae problem, but the owls in the cave from middle of teldrassil, they have spot where if they reach they get the same simptom. I mena on the middle of the bridge they get stuck and start to evade, only if u go near them u can attack them... 

If this is related just let me know and I shall provide SS and guids, but any owl that get's on the bridge he has like a 75- 80 % chance to get stuck in the middle of ANY bridge

**Comment by AnonXS** [comment]
Recheck cases displayed here.

**Comment by al3xc1985** [comment]
I will check them back and come back with results

**Comment by al3xc1985** [comment]
![image](https://user-images.githubusercontent.com/6240049/218335135-0fa666e5-c6d7-4b57-9be5-38425720ca72.png)

now it has a different problem. u aggro them and they just stay in place. u are outside the water and they are in the water.. if u enter the water they will come to u straight and get out with u from the water
they go back normally back to last point when evade.. all perfect

only problem is that they get stuked and do not come to your out of water until u enter water

**Comment by AnonXS** [comment]
I do not have this issue in tbcmangos. only their movement is shitty, they can enter/exit water.

**Comment by Grz3s** [comment]
wotlk has no issues also...
![1](https://user-images.githubusercontent.com/2374069/218337447-45dc8461-f2ef-4f8d-bef9-e8be89b27036.jpg)
![2](https://user-images.githubusercontent.com/2374069/218337453-b236d11b-fb9a-4244-9ee7-2e5fed302781.jpg)
![3](https://user-images.githubusercontent.com/2374069/218337455-3ff9cb95-7896-4c5d-81ba-0c22cbb37511.jpg)

**Comment by al3xc1985** [comment]
hmm
curious
I did with a fresh new db release. Maybe something is wrong with my core. until new evidence I shall close this (if there is any and I really hope there is no more problem with this)

**Comment by tonymontoya** [comment]
Just deployed a new 1.12.1 (Classic) server in March 2023 and I can confirm this behavior in the Horde Starting area around Sen'Jin Village.  The Crawlers and Makura in the water cannot find a path to the player most of the time and run sideways looking for a way to get to the player.  Player swim movement is also wrong, the player does not swim up, but "jumps" through the water when travelling upwards.

**Comment by AnonXS** [comment]
`Just deployed a new 1.12.1 (Classic) server in March 2023 and I can confirm this behavior in the Horde Starting area around Sen'Jin Village.  The Crawlers and Makura in the water cannot find a path to the player most of the time and run sideways looking for a way to get to the player.  Player swim movement is also wrong, the player does not swim up, but "jumps" through the water when travelling upwards.`

it can also be related to the extraflag: walk in water. - so from what i see is, it works fine, crabs might swim during chasing but not OOC, they can go in and out of water. but if you swim into the water they cant reach you and start chasing around, when they should infact go idle and into evade mode as player is unreachable. - different issue from what is described here.

New Issue: how should crabs behave when they chase someone in water, can they swim then?

**Comment by AnonXS** [comment]
Creature (Entry: 4807 Counter: 4800061) DBGuid: 4800061.

![grafik](https://user-images.githubusercontent.com/19734826/227936547-ab4863ca-b275-4479-8448-7e3b087778db.png)

![grafik](https://user-images.githubusercontent.com/19734826/227938231-330940c3-869a-49cf-8c44-25dd54e121f0.png)

**Comment by Novivy** [comment]
It happens to all creatures in water, unless you add the ExtraFlag `0×00004000 CREATURE_EXTRA_FLAG_MMAP_FORCE_DISABLE` to it.

For info, the creature in the example have the following ExtraFlags: `0×00008000	CREATURE_EXTRA_FLAG_WALK_IN_WATER`, InhabitType is `3	Both Ground And Water Movement`

I tried with HD and non HD maps extracts, same result.

https://user-images.githubusercontent.com/50490687/228079337-58d32423-fcc7-494e-84da-67327a09356a.mp4

0. `.gm off` `.gm visible on` 
1. `.go crea 38516` (entry 2231)
2. Stand 10 yards from the shore and target the creature in water
3. `.damage 1`
4. Creature won't move

**Comment by r4d1sh** [comment]
<details>
 <summary>Clickable - Suggest as a temporary (or permanent) solution</summary>

```diff
diff --git a/src/game/MotionGenerators/PathFinder.cpp b/src/game/MotionGenerators/PathFinder.cpp
index 19661d5..5a065f3 100644
--- a/src/game/MotionGenerators/PathFinder.cpp
+++ b/src/game/MotionGenerators/PathFinder.cpp
@@ -630,7 +630,7 @@ void PathFinder::BuildPointPath(const float* startPoint, const float* endPoint)
                 m_pointPathLimit);    // maximum number of points
         }
 
-        if (pointCount > 2 && sWorld.getConfig(CONFIG_BOOL_PATH_FIND_OPTIMIZE))
+        if (dtStatusSucceed(dtResult) && pointCount > 2 && sWorld.getConfig(CONFIG_BOOL_PATH_FIND_OPTIMIZE))
         {
             uint32 tempPointCounter = 2;
 
@@ -692,6 +692,14 @@ void PathFinder::BuildPointPath(const float* startPoint, const float* endPoint)
         }
     }
 
+    if (pointCount == m_pointPathLimit)
+    {
+        DEBUG_FILTER_LOG(LOG_FILTER_PATHFINDING, "BuildPointPath FAILED! path sized %d returned, lower than limit set to %d\n", pointCount, m_pointPathLimit);
+        BuildShortcut();
+        m_type = PATHFIND_SHORT;
+        return;
+    }
+
     if (pointCount < 2 || dtStatusFailed(dtResult))
     {
         // only happens if pass bad data to findStraightPath or navmesh is broken
@@ -703,14 +711,6 @@ void PathFinder::BuildPointPath(const float* startPoint, const float* endPoint)
         return;
     }
 
-    if (pointCount == m_pointPathLimit)
-    {
-        DEBUG_FILTER_LOG(LOG_FILTER_PATHFINDING, "BuildPointPath FAILED! path sized %d returned, lower than limit set to %d\n", pointCount, m_pointPathLimit);
-        BuildShortcut();
-        m_type = PATHFIND_SHORT;
-        return;
-    }
-
     // first point is always our current location - we need the next one
     setActualEndPosition(m_pathPoints[pointCount - 1]);
 

```
</details>

**Comment by Ohswin** [comment]
I have observed this issue in the lake above farstrider enclave in the ghostlands. The gosts in the water evade your attacks when attacking from outside the water. Once inside the water they act like normal.

tbc-mangos commit: 46ce862172aee1d1ff969f33e20374c3c869d40b
tbc-db commit: 5914db5509a28a4ead85a117096cb18bf0aad613

**Comment by Arnibou** [comment]
On tbc-mangos and it doesn't only do it in combat, during an escort if the npc has to cross the water, he can't find the way!

Example quest: Vorsha the Lasher (id: 6641), Muglash can't find the way to the other side when he has to cross the water, he makes a big detour to the water's edge.

**Comment by al3xc1985** [comment]
@cyberium we need you, help us wise one! /baw
We also got cookies for ya! :)

**Comment by volibear2** [comment]
I can confirm this Bug still existing in 
mangos-tbc: 54629be7c5c3e0e0d3f24cbf18efc4f9758f8975

I saw @cyberium talking about a mmap rework last year in discord, sadly that never came.

Pathing is a big problem imo cause its pretty broken.
Mostly noticable with water mobs, making it realy hard to do quests where you have to kill mobs in water. (imo unplayable, had to skip many quests in with water)
Also noticable with hills/fence, most mobs just ignore fences and walk up straigth into the player, this makes kiting undoable (as mage for example)

**Comment by al3xc1985** [comment]
all we can do is just poke @cyberium again on this one. Maybe in his little time, can give us a light into this matter
