### ISSUE TITLE
🐛 [Wotlk Db] 2 Guards in Fairbreeze Village - Missing movement path

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2990]
### Bug Details

Guids 56887 & 56888 Should have some path defined.
I tested some vids from tbc classic I could not find them standing there. Just standing. I can't provide path for them

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/3580460f9a15be7cb2b5f5e5de1582cd57f9adeb#diff-0f9b609fafb18b5d25692e1237648016c9953ba6017ef25199d9a4f3b8844714R1005
