### ISSUE TITLE
🐛 [Wotlk Db] Helena Atwood - missing ability

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#2997]
### Bug Details

https://tbc.wowhead.com/npc=5669/helena-atwood
she is missing the shot ability,

I mean, shouldn't she have an acid script to allow her to shoot if in combat? use range mode ?

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Grz3s** [comment]
she uses that shoot ... with her RP event (training) ...
if its also used agains players ... then we can add it... but find proof first ;)

**Comment by al3xc1985** [comment]
:))
I would love to give u more, is just logical.  I judged by the spells that she has listed on wowhead. 
Dunno. If u think this is not good, close it, but it was to obvious for me that she is something  to use range on attacks

**Comment by AnonXS** [comment]
Comment points to her using <https://tbc.wowhead.com/npc=5669/helena-atwood#comments:id=303557>
<https://tbc.wowhead.com/spell=9008/shoot> which is purely cosmetic.

**Comment by al3xc1985** [comment]
hmm... need to find... 
I shall try, I don't have an official account, just trying to judge by wowhead info, and old vids...If I don't find evidence I s hall close this

**Comment by al3xc1985** [comment]
can not find any, so closing in.
I was thinking to add the range capabilities through ACID,,,but can't find proof.
The logic was that if she uses gun, even on RP, than why not using it in combat
@Grz3s @AnonXS feel free to reopen if my logic is good or if u find proof

**Comment by AnonXS** [comment]
Does she do RP for us currently?

**Comment by al3xc1985** [comment]
yes

**Comment by al3xc1985** [comment]
I checked her when I reported this, and I shall recheck again in the morning

**Comment by AnonXS** [comment]
good then i've nothing to add, if nobody tests her fighing against her we will never know.

**Comment by al3xc1985** [comment]
well, ya. that is the big thing.
Dunno what tot say. I will still leave it, maybe somebody can test it

**Comment by AnonXS** [comment]
cosmetic rp shoot, no combatai required.
