### ISSUE TITLE
DK-Quest-Into the Realm of Shadows.

### ISSUE THREAD

**Issue by Warrior94** [cmangos/issues#300]
When you kill the rider, you should be able to catch the horse, but can not. The mission does not end and get stuck.

It should catch the horse.

http://www.wowhead.com/quest=12687/into-the-realm-of-shadows

**Comment by Dainara82** [comment]
i have the issue  too  on a fresh installation 
@xfurry 
i use'd your update and it worked fine

**Comment by xfurry** [comment]
> i have the issue too on a fresh installation

Which DB provider are you using?
If you have UDB, then poke @grz3s and open a new issue here: https://github.com/unified-db/Database/issues

**Comment by Grz3s** [comment]
in UDB this part works fine...

**Comment by Dainara82** [comment]
Yes i use unifieddb, i don't know if it different between unified-db and unifieddb
it dont work after an actually fresh installation  i got no errors in the installation part.
so i postet it here,  but the patch worked, so there must be a issue there

**Comment by xfurry** [comment]
@Dainara82 this is what you need to use: https://github.com/unified-db/Database

**Comment by Dainara82** [comment]
if i try to install this DB i get errors, so i can't use it.  i have the unified db link from the installation wiki and in this DB is the error, so there must fix it someone 
"Get the world-database stuff"
"(Latest version) Insert as SVN-URL: https://unifieddb.svn.sourceforge.net/svnroot/unifieddb/trunk"

**Comment by xfurry** [comment]
> if i try to install this DB i get errors, so i can't use it.

What errors do you get?
This is the latest DB and with this all DK quests are working just fine.

**Comment by Grz3s** [comment]
``` quote
"(Latest version) Insert as SVN-URL:
https://github.com/unified-db/Database/issues/6#issuecomment-72368241
```
This is outdated. link .... pls use newest UDB from GIT....

**Comment by xfurry** [comment]
@Dainara82 I updated the install instructions. Please check again and use the latest UDB release, including the hotfixes that we provide almost daily.

**Comment by Dainara82** [comment]
Ok i think i Know where the problem is, i use only linux debian and i missed the InstallFull.sh
I found it in the CurrentRelease Folder and use it
So i get an error while the Updates from mangos/sql/updates are installing
does this script is up-to-date too?

I missed in the Installation Wiki page the Part for Linux from the Database, can you update it please too?

**Comment by Schmoozerd** [comment]
unfortunately the InstallFull.sh script is not yet updated. Probably you only need to adapt a few paths with it to be able to use it

**Comment by Dainara82** [comment]
ok one question, the aktualli DB set the mangos db_version to "UDB 0.12.2 (407) for CMaNGOS 12735 with SD2 SQL for rev. 3041"
in the batch file i see that no updates from mangos are installed.  there is the last Mangos db_version "required_12823_04_mangos_creature"
so
do i need all updates from "12748_01_mangos_spell_template" to the last or
should i set the db_version to "required_12823_04_mangos_creature" that i can start the server
if i need all updates, than i must change the db_version to "12670_01_mangos_spell_template"
that it go

**Comment by Schmoozerd** [comment]
no - you need to apply the (remaining) sql files in order.

**Comment by Schmoozerd** [comment]
You can use http://paste2.org/_XOn43jpO (apply easiest with git am) to get the installer script better working.

**Comment by Dainara82** [comment]
this is the error 
Append core update 12465_01_mangos_spell_template.sql to database ncf1682mangos
ERROR 1054 (42S22) at line 1: Unknown column 'required_12441_01_mangos_npc_spellclick_spells' in 'db_version'

i don't know why,

**Comment by Dainara82** [comment]
ok i fixed the InstallFull.sh
i changed the following Lines
LAST_CORE_REV="12444"
LAST_SD2_REV="2857"
to
LAST_CORE_REV="12735"
LAST_SD2_REV="3041"
now the installation script worked fine
