### ISSUE TITLE
🐛 [Wotlk Db] Quest Unusual Activity

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3015]
### Bug Details

https://tbc.wowhead.com/quest=11886/unusual-activity

U can't even move a finger on this quest because the Tiwlights have friendly faction.
They should be enemy... u need to kill them.

So, I kill by command Twilight Speaker Viktor.. I get the Twilight Correspondence, BUT the second problem is that u can't use the totemic beacon, wich should call a wolf spirit. 
In the tbc.wowhead we have a video with the quest done.. 

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by kelbren** [comment]
It is now possible to attack the Twilight Speaker and obtain the Twilight Correspondence, however using the totemic beacon still gives a invalid target error and fails to summon the wolf spirit and not allowing the quest to complete.
