### ISSUE TITLE
🐛 [Wotlk Db] Strand of Ancients Emissary OR ALL Emissaries

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3017]
### Bug Details

![image](https://user-images.githubusercontent.com/6240049/174428974-48d3af2c-396e-4218-8c31-d905dad5f388.png)

I gave only an example of emissaries that just stand and should have path. But this is a general bug currently.

In all places where this kind of emissaries are spawned they should have waypoints. 
There are more groups of them, if I saw correctly in Stormwind for example, I think is same think in every place where they are

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
They worked fine when i ported them few years back, now only one is single patrolling and the other one is not linked anymore to it. (start checking that, i bet its core issue though)
It would be best porting these packs to spawn_groups to have them active and performing better formation pathing.
