### ISSUE TITLE
🐛 [Bug Report] Clear cooldowns no longer removes worn item cooldowns

### ISSUE THREAD

**Issue by henhouse** [cmangos/issues#3020]
### Bug Details

The GM command `.cooldown clear` and invoking the player func `RemoveAllCooldowns()` no longer removes cooldowns on items the player is wearing. Items in bags, such as potions, do clear as expected.

### Steps to Reproduce

1. Equip a trinket with an on use effect
2. Use the effect
3. Reset cooldowns via command
4. Notice there is still a cooldown

### Expected behavior

Cooldowns on worn items should also reset.

### Core SHA1 Commit Hash

c63efea159b6d6178ba451c80952bd48ae4a9f8a

### Database SHA1 Commit Hash

e1acc3f5b83b1e92afa7829b950f161b9d36366d

### Operating System

Linux (Ubuntu 20.04 LTS)

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/commit/bbca8a95c1ad34a11984b9e61cf1137ce341b467
