### ISSUE TITLE
🐛 [Bug Report] Demoralizing Shout/Roar and Piercing Howl does not removing stealth from players

### ISSUE THREAD

**Issue by henhouse** [cmangos/issues#3022]
### Bug Details

[Demoralizing Shout](https://tbc.wowhead.com/spell=1160/demoralizing-shout), [Demoralizing Roar](https://tbc.wowhead.com/spell=26998/demoralizing-roar), and [Piercing Howl](https://tbc.wowhead.com/spell=12323/piercing-howl) should remove players from stealth if hit. Currently it does not.

Proof: 
> By Daavos [on 2007/04/26](https://tbc.wowhead.com/spell=1160/demoralizing-shout#comments:id=2748698) (Patch 2.0.12)		
Subject: "Any Stealth'd Rogues..."Any Stealth'd Rogues will appear if they are hit with this.

> Groal [on 2007/12/04](https://tbc.wowhead.com/spell=1160/demoralizing-shout#comments:id=2748666:reply=1181930) (Patch 2.3.0)Subject: "Re: is this spell good?"
This now reveals stealthed characters... Found out today, yet I've been playing a warrior from 1-70

> [thomasjs](https://tbc.wowhead.com/user=thomasjs) [on 2007/09/18](https://tbc.wowhead.com/spell=1160/demoralizing-shout#comments:id=103752:reply=15249) (Patch 2.1.3)
I use Demoralizing Shout during PvP in three situations. 1. When I know a 1v1 fight will be close and that little bit of damage reduction will save my life. 2. When allot of physical damage enemies are close to or attacking me. 3. **To de-stealth Rogues and Druids**.

### Steps to Reproduce

1. Cast Demoralizing Shout, Demoralizing Roar, or Piercing Howl near a stealthed rogue
2. Rogue will not be brought out of stealth

### Expected behavior

Stealth should break

### Core SHA1 Commit Hash

c63efea159b6d6178ba451c80952bd48ae4a9f8a

### Database SHA1 Commit Hash

e1acc3f5b83b1e92afa7829b950f161b9d36366d

### Operating System

Linux (Ubuntu 20.04 LTS)

### Client Version

2.4.3 (The Burning Crusade)

**Comment by henhouse** [comment]
Nice @killerwife, but shouldn't this also include Druid's Prowl abilities, Mage's Invisibility, Vanish, Invisibility Potion, Shadowmeld, etc.? All of these are "Stealth" spells.

**Comment by killerwife** [comment]
Vanish uses stealth spell directly, prowl yes, I will add that, invis is utterly different, same with potion and shadowmeld. Go check their proc flags with the new QSW release and you willsee.

**Comment by Oldsalt0** [comment]
@killerwife Unsure if your comment meant those spells need a totally different fix or if they're not meant to be broken with AoEs such as Demo Shout, I tried on TBCC:
- Shadowmeld:

https://user-images.githubusercontent.com/20860048/175785761-0f63f4cb-2fdd-4f49-a042-80953d044a72.mp4

- Mage Invisibility:

https://user-images.githubusercontent.com/20860048/175785917-5f120b00-7f9f-4198-ac95-1263f5f0799d.mp4

**Comment by killerwife** [comment]
I meant that the mechanism through which these should be removed by using demo shout is different.
