### ISSUE TITLE
🐛 [Bug Report] [WoTLK} Compile Error - PlayerbotAI

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3027]
### Bug Details

```
/home/mangos/cmangos/wotlk/src/game/PlayerBot/Base/PlayerbotAI.cpp: In member function ‘bool PlayerbotAI::CanReachWithSpellAttack(Unit*)’:
/home/mangos/cmangos/wotlk/src/game/PlayerBot/Base/PlayerbotAI.cpp:180:38: error: ‘SPELL_ATTR_RANGED’ was not declared in this scope; did you mean ‘SPELL_ARCANE’?
  180 |         if (!spellInfo->HasAttribute(SPELL_ATTR_RANGED))
      |                                      ^~~~~~~~~~~~~~~~~
      |                                      SPELL_ARCANE
/home/mangos/cmangos/wotlk/src/game/PlayerBot/Base/PlayerbotAI.cpp: In member function ‘bool PlayerbotAI::IsRegenerating()’:
/home/mangos/cmangos/wotlk/src/game/PlayerBot/Base/PlayerbotAI.cpp:4345:32: error: ‘SPELL_ATTR_CASTABLE_WHILE_SITTING’ was not declared in this scope; did you mean ‘SPELL_ATTR_ALLOW_WHILE_SITTING’?
 4345 |         if(spell->HasAttribute(SPELL_ATTR_CASTABLE_WHILE_SITTING))
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                SPELL_ATTR_ALLOW_WHILE_SITTING
```

### Steps to Reproduce

1. cmake \~/cmangos/wotlk -DCMAKE_INSTALL_PREFIX=~/wow-servers/wotlk -DBUILD_EXTRACTORS=On -DBUILD_AHBOT=ON -DBUILD_PLAYERBOT=ON -DPCH=0 -DDEBUG=0 -DBUILD_RECASTDEMOMOD=OFF -DBUILD_GIT_ID=0 ; make -j6
cd ~

2.
3.
4.

### Expected behavior

Compile without error

### Suggested Workaround

n/a

### Crash Log

n/a

### Core SHA1 Commit Hash

CMaNGOS-Core revision : 145efbef6c1bb4cf34fb10205f91c11a944bd321 Revision time stamp   : "2022-06-18T00:28:40+02:00"

### Database SHA1 Commit Hash

N/A

### Operating System

Ubuntu 20.04.4 Server LTS

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
Already addressed in https://github.com/cmangos/mangos-wotlk/pull/365
