### ISSUE TITLE
🐛 [Wotlk Db] Viscous Fallout Missing Abilities

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3028]
### Bug Details

https://tbc.wowhead.com/npc=7079/viscous-fallout#comments;mode:normal

The guy has some posion abilities
https://www.youtube.com/watch?v=jGsHRE9viOg

1. Single target poison
2. All targets poison
3. Poison aoe

https://www.youtube.com/watch?v=nyaiSEDVgDg
This is a tbc video, I don't see any abilities.
Maybe his abilities were introduced in wotlk

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
I saw a worgen in this 11 years old movie. Duuno if the info is viable

**Comment by al3xc1985** [comment]
Checking a trinity core server, fiind that they implementeze the abilities. Dumbo If that îs right or fake

**Comment by AnonXS** [comment]
Last time i checked, that was cataclysm.

**Comment by AnonXS** [comment]
Seems it's cata where dungeons were revamped a bit to be more interesting.

https://www.wowhead.com/wotlk/npc=7079/viscous-fallout#abilities;mode:normal
