### ISSUE TITLE
🐛 [Wotlk Db] Mechano-Frostwalker

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3029]
### Bug Details

https://tbc.wowhead.com/npc=6227/mechano-frostwalker#abilities;mode:normal

1.He cast ice blast before get to the players
2.His iceblast freeze himself when casted before getting to players, so I guess is a targeting problem here

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Closed by https://github.com/cmangos/wotlk-db/commit/85c4cba70566990d6569ec6e0be99eb098d4c6fe
