### ISSUE TITLE
🐛 [Wotlk Db] Dark Iron Agent - Land mines missing

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3030]
### Bug Details

`-- Dark Iron Land Mine 8035
('803501','8035','11','0','100','0','0','0','0','0','0','0','11','11816','0','0','11','10831','0','0','50','0','0','0','Dark Iron Land Mine - Cast Land Mine Arming and Reflection Field and Set ReactState Passive on Spawn'),
('803502','8035','29','0','100','0','0','0','0','0','0','0','1','3541','0','0','0','0','0','0','0','0','0','0','Dark Iron Land Mine - Emote on Generic Timer'),
('803503','8035','29','0','100','0','5000','5000','0','0','0','0','1','3542','0','0','0','0','0','0','0','0','0','0','Dark Iron Land Mine - Emote on Generic Timer'),
('803504','8035','29','0','100','0','10000','10000','0','0','0','0','1','3543','0','0','22','1','0','0','0','0','0','0','Dark Iron Land Mine - Emote and Set Phase 1 on Generic Timer'),
('803505','8035','10','5','100','0','0','5','0','0','0','0','11','4043','15','0','41','10000','0','0','37','0','0','0','Dark Iron Land Mine - Cast Detonation and Delayed Despawn OOC LOS (Phase 1)'),`

https://tbc.wowhead.com/npc=6212/dark-iron-agent#abilities;mode:normal

This is the code from acid for land mine.
But dark iron is a different entry

Also, currently on gnomergan, he doesn't put mines.
I believe that the code is not good for this one,even the name should be Dark Iron Agent, and not Dark Iron Land mine

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

7e3d53e065cf52005e7105d841dd4a67f684216b

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/219803996-cb16626c-9ebc-4088-97b2-8e501e9e983a.png)

![grafik](https://user-images.githubusercontent.com/19734826/219804004-036b6452-47d2-411e-90da-a4d358a25327.png)

![grafik](https://user-images.githubusercontent.com/19734826/219804014-474b598c-3c20-49ff-bcf6-02da5d199059.png)
