### ISSUE TITLE
🐛 [Bug Report] Naxx 25 - Thaddius encounter bugged

### ISSUE THREAD

**Issue by danjohnso** [cmangos/issues#3035]
### Bug Details

Couple issues with this encounter.
1) Stalagg and Fuegen never throw the tanks to swap them
2) Thaddius himself never spawns when Stalagg and Fuegen die

### Steps to Reproduce

1.  Engage stalagg and fuegen
2.  Kill simultaneously
3.  Jump down to Thaddius platform, next event never starts
4.

### Expected behavior

Thaddius should activate and attack

### Core SHA1 Commit Hash

ad3ecbe34282a33fc5b06550cdd403e89062fd5f

### Database SHA1 Commit Hash

5ef13c94785bda2150f2be683d631ae4f301579b

### Operating System

Ubuntu 20.04 LTS

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by danjohnso** [comment]
So activation works now, so does the tank toss.  The toss should do a threat swap or reset (don't remember, have to go look for a video), but right now they just leave their platform and go to the other one where their tank went.

Now that I can see Thaddius, the polarity charges are not working either.  Had a negative and positive stand on each other, no damage was taken by either party.

**Comment by insunaa** [comment]
> So activation works now, so does the tank toss. The toss should do a threat swap or reset (don't remember, have to go look for a video), but right now they just leave their platform and go to the other one where their tank went.
> 
> Now that I can see Thaddius, the polarity charges are not working either. Had a negative and positive stand on each other, no damage was taken by either party.

That is strange, I explicitly implemented an aggro swap. I'll rework it.

I'll take a look at the polarity change spellscript. I'm pretty sure it works on TBC too

**Comment by danjohnso** [comment]
Aggro looks good, might test further later today but initial look is good.

The polarity damage is still not working, nothing in combat log from it.

Guess I forgot to copy in some of test results from yesterday, but there should also be a chain lightning damage that goes out if Stalagg or Fuegen get too far from their tether.  Nothing happens right now if they get too far

**Comment by insunaa** [comment]
@danjohnso You added the MySQL stuff I put in the comment?
If so then the spell IDs may have changed from 2.4.x (some have been re-used so I can't be sure)

**Comment by danjohnso** [comment]
Yeah I ran that script

**Comment by insunaa** [comment]
@danjohnso Should be fixed now. Try with the latest code and add
```sql
INSERT INTO spell_scripts(Id, ScriptName) VALUES
(28089,'spell_thaddius_polarity_shift');
```

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-wotlk/commit/fe4b752e14083de6a487c90929ff29f4371cb4a2
