### ISSUE TITLE
🐛 [Bug Report] [WoTLK] [Quest] Unusual Activity, Item: Totemic Beacon, does not work

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3036]
### Bug Details

item=3582 totemic-beacon
quest=11886 unusual-activity

Once you get the correspondence from the Cultist fro the encampment in The Zoram Strand, you use the Totemic Beacon on the sand to summon Earthen Ring Guide. When you use it anywhere is just says "Invalid target" and unable to continue the quest

### Steps to Reproduce

1.Pick up quest Unusual Activity (11886)
2.Goto The Zoram Strand
3.Kill Cultist till correspondence drops 
4.Use Totemic Beacon

### Expected behavior

Earthen Ring Guide to appear

### Suggested Workaround

n/a

### Crash Log

n/a

### Core SHA1 Commit Hash

402d4e856aa23c784afd633855d06ad353d10076

### Database SHA1 Commit Hash

038ce76621a6082649f85d61ca61b97c6a25a5d3

### Operating System

Ubuntu 20.04.3 Server LTS, WIndows 7 Client

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by adellaci** [comment]
Thank you all. I'll test as soon as he done

Jun 23, 2022 4:02:03 AM killerwife ***@***.***>:

**Comment by Grz3s** [comment]
https://github.com/cmangos/wotlk-db/commit/1e28ec88b5467c9e1a3eb7935dd843f7aeb813f4

**Comment by adellaci** [comment]
I'll test it s soon as I get home

Jun 26, 2022 7:42:14 PM Grz3s ***@***.***>:
