### ISSUE TITLE
🐛 [Bug Report] [WoTLK] Blackfathom Deeps - Aku'mai does not patrol lair

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3037]
### Bug Details

The final boss in Blackfathon Deeps at Aku'mai Lair, Aku'mai should be patthng her lair.

npc=4829

### Steps to Reproduce

1.go to Aku'ami Lair
2.observe Aku'ami
3.
4.

### Expected behavior

Aku'mai should patrol Lair

### Suggested Workaround

n/a

### Crash Log

n/a

### Core SHA1 Commit Hash

402d4e856aa23c784afd633855d06ad353d10076

### Database SHA1 Commit Hash

038ce76621a6082649f85d61ca61b97c6a25a5d3

### Operating System

Ubuntu 20.04.3 Server LTS, WIndows 7 Client

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by adellaci** [comment]
@AnonXS I don't know f this matters, but in the "creature_movement_template" there were these entries
```
"4829","0","1","-835.818","-412.169","-33.8906","1.36776","0","0",NULL
"4829","0","2","-841.029","-353.086","-33.891","1.69161","0","0",NULL
"4829","0","3","-835.052","-414.974","-33.8904","4.83319","0","0",NULL
"4829","0","4","-847.368","-454.508","-33.9831","4.3816","0","0",NULL
```

**Comment by AnonXS** [comment]
In what db?

**Comment by adellaci** [comment]
WoTLK

Jun 23, 2022 6:59:17 PM AnonXS ***@***.***>:

**Comment by AnonXS** [comment]
how does that work when creature id has movementtype = 0?

**Comment by adellaci** [comment]
I was trying figure the use of " creature_movement" and "creature_movement_template"

Jun 23, 2022 9:31:08 PM AnonXS ***@***.***>:

**Comment by adellaci** [comment]
It didn't' t work that is why I posted the issue. Just started researching it this morning when I found it. Then I saw you jumped on it last night EST.

Jun 23, 2022 9:31:08 PM AnonXS ***@***.***>:
