### ISSUE TITLE
problem with cooldown resset💬 [Support Request] 

### ISSUE THREAD

**Issue by rmzV** [cmangos/issues#3038]
### Core Version

mangos-wotlk

### Support Request Details

i am using already compiled server and latest db version
after some update (i think it was mangos-wotlk-with-ahbot-889acc04)
some of my characters (3 characters are effected)  have problem with hearthstone: it doesnot starts timer (screen https://dropmefiles.com/T3N74  ) and with keys, (after i used key to open some door in scarlet monastery.. it no longer works too)
how i can reset cd?

### Steps to Reproduce

1. update to latest verion
2. Some of the characters have this problem, some doesnot

### Core SHA1 Commit Hash

last

### Database SHA1 Commit Hash

last

### Server Operating System

win 8

### Client Version

3.3.5a (Wrath of the Lich King)

### Client Operating System

win 8

**Comment by rmzV** [comment]
probably this is related with this update 
[14061_01_characters_fishingSteps.sql](https://github.com/cmangos/mangos-wotlk/blob/master/sql/updates/characters/14061_01_characters_fishingSteps.sql)

**Comment by killerwife** [comment]
![image](https://user-images.githubusercontent.com/7995382/175683195-ad4cecd9-d399-4d84-bda4-8873869895e9.png)

Used it. Latest cmangos-wotlk. Cant reproduce.

**Comment by rmzV** [comment]
what i try without effect:
 .bot add BOTNAME
/invite BOTNAME
/p resset
.bot remove BOTNAME

and its got no effect(

**Comment by rmzV** [comment]
i also added pic of my db characters spell
red painted doesnot works 
green works fine
https://dropmefiles.com/QRNRK

**Comment by GPinkie** [comment]
Characters previously affected by the cooldown bug are permanently bugged out. New characters or characters that did not use an item during that period are not affected. Using the command ( .cooldown clear ) on each character that is bugged, fixed the issue for me.

**Comment by killerwife** [comment]
Clear table character_spell_cooldown.

```
truncate wotlkcharacters.character_spell_cooldown;
```

should do the trick

**Comment by rmzV** [comment]
okey its worked.
I used .cooldown clear  method
