### ISSUE TITLE
🐛 [Bug Report] Warsong Gulch - Cloak of Shadows drops flag

### ISSUE THREAD

**Issue by Oldsalt0** [cmangos/issues#3041]
### Bug Details

Using Cloak of Shadows (Spell ID 31224) while carrying a WSG Flag makes the player drop the flag.

![image](https://user-images.githubusercontent.com/20860048/175773692-1caaf2da-f584-4d7f-b324-30c29837fc20.png)

https://user-images.githubusercontent.com/20860048/175774247-2c77fee9-0051-454e-bc79-85d5b1ec5aee.mp4

### Steps to Reproduce

1. Reach Enemy Flag room
2. Take Enemy Flag
3. Use Cloak of Shadows

### Expected behavior

Cloak of Shadows should not make the rogue automatically drop flag, unlike Vanish/Stealth.

### Core SHA1 Commit Hash

d1ec084fc94a9e06c7460e126d248e690c809cb1

### Database SHA1 Commit Hash

7edee7cd5e0df4a68cd7fecdca7c9eec3ca825d5

### Operating System

Linux (Ubuntu 20.04 LTS)

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
@henhouse i feel like this is same as pally bubble, can u verify?

**Comment by Oldsalt0** [comment]
Was related to a custom change by Henhouse. Resolved by https://github.com/cmangos/issues/issues/3026
