### ISSUE TITLE
🐛 [Bug Report] Infinite recursion crash if Summon Charger is unlearned

### ISSUE THREAD

**Issue by henhouse** [cmangos/issues#3042]
### Bug Details

If you unlearn the [Alliance](https://tbc.wowhead.com/spell=34767/summon-charger) or [Horde Summon Charger](https://tbc.wowhead.com/spell=23214/summon-charger), the core will crash due to `learnSpell()` constantly trying to remove Summon Charger and [Riding (Journeyman)](https://tbc.wowhead.com/spell=33391/riding) infinitely. This seems to be because the `spell_chain` entry for both of these spells classifies it as rank 2, which is wrong. There is no rank 1 of this spell. Summon Warhorse, the lesser 60% speed mount is a separate spell entirely, not a rank 1.

### Steps to Reproduce

1. Make a Paladin
2. Learn it Summon Charger
3. Unlearn the spell or do `.reset spells`
4. Core will crash

### Expected behavior

Spell should be unlearned.

### Suggested Workaround

Setting these entries to rank 1 in their `spell_chain` entries seems to resolve the issue.

### Core SHA1 Commit Hash

d1ec084fc94a9e06c7460e126d248e690c809cb1

### Database SHA1 Commit Hash

7edee7cd5e0df4a68cd7fecdca7c9eec3ca825d5

### Operating System

Linux (Ubuntu 20.04 LTS)

### Client Version

2.4.3 (The Burning Crusade)

**Comment by celguar** [comment]
Possibly related? Or maybe missing down port from wotlk
https://github.com/cmangos/issues/issues/2382

**Comment by henhouse** [comment]
> 

Oh indeed, this seems to be the same issue. Likely not ported yet.
