### ISSUE TITLE
🐛 [Bug Report] Mage - Summon Water Elemental checks Frost Nova's CD

### ISSUE THREAD

**Issue by Oldsalt0** [cmangos/issues#3043]
### Bug Details

 [Summon Water Elemental](https://tbc.wowhead.com/spell=31687/summon-water-elemental) currently checks the cooldown of [Frost Nova](https://tbc.wowhead.com/spell=27088) (Mage Freeze) and copies it into [Freeze](https://tbc.wowhead.com/spell=33395/freeze) **when you summon the Water Elemental**.

https://user-images.githubusercontent.com/20860048/175782893-72422ca4-5ed8-4112-b4c1-a1f7748bb1c0.mp4

This only happens when summoning the Water Elemental. Casting Frost Nova or Freeze while the pet is already summoned won't trigger this issue:

https://user-images.githubusercontent.com/20860048/175782979-54dc8a21-52be-4fd7-80cf-a0908bb989bb.mp4

### Steps to Reproduce

1. Cast Frost Nova
2. Cast Summon Water Elemental
3. Try to cast Freeze

### Expected behavior

Summoning Water Elemental isn't supposed to take Frost Nova's cooldown into Freeze.

Here's some footage from TBCC. Frost Nova is on 3, you can see Freeze has no cooldown after the Elemental is summoned, even though Frost Nova is still on cooldown:

https://user-images.githubusercontent.com/20860048/175783031-54a12bfe-beaf-4293-9ac1-9da9b5036a19.mp4

_Source: https://www.youtube.com/watch?v=-wNcyvFr_j8_

### Core SHA1 Commit Hash

d1ec084fc94a9e06c7460e126d248e690c809cb1

### Database SHA1 Commit Hash

7edee7cd5e0df4a68cd7fecdca7c9eec3ca825d5

### Operating System

Linux (Ubuntu 20.04 LTS)

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Fix is on wotlk branch. https://github.com/cmangos/mangos-wotlk/commit/ad7a1396abe520627f6e8603a69902b40bbffd8d

**Comment by rmzV** [comment]
@killerwife may be it be related with my issue?
