### ISSUE TITLE
🐛 [Bug Report] GM command .modify aspeed, the server crash.

### ISSUE THREAD

**Issue by ckj777** [cmangos/issues#3046]
### Bug Details

If use the GM command .modify aspeed, the server crash.

### Steps to Reproduce

1.
2.
3.
4.

### Crash Log

Revision: 5adcbeaf509c7b90d4efb1ffd1aa439881f0659f
Build: 2022-06-26T17:00:47+02:00
Crash date 27:06:2022. Time 18:49 
//=====================================================
*** Hardware ***
Processor: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Number Of Processors: 8
Physical Memory: 16342 MB (Available: 8421 MB)
Commit Charge Limit: 18774 MB

*** Operation System ***
Windows 10 Professional (Version 10.0, Build 19043)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FFE51BF6D89 01:0000000000025D89 C:\WINDOWS\System32\ucrtbase.dll

Registers:
RAX:3FF0000000000000
RBX:000000DE222FE420
RCX:3FF0000000000000
RDX:000000007FFFFFFF
RSI:000000DE222FE920
RDI:0000000000000800
R8: 3FF0000000000000
R9: 0000000000000000
R10:000000DE222FEEC0
R11:0000000000000000
R12:0000000000000001
R13:000000DE222FE888
R14:00007FFE51BD0000
R15:0000000100000000
CS:RIP:0033:00007FFE51BF6D89
SS:RSP:002B:00000000222FE2A8  RBP:222FE4C0
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010283

Call stack:
Address   Frame     Function      SourceFile
00007FFE51BF6D89  000000DE222FE2A0  strnlen+109
00007FFE51BE2437  000000DE222FE2D0  strtol+A7
00007FFE51BE114A  000000DE222FE350  wcstol+67A
00007FFE51BE0D9E  000000DE222FE3B0  wcstol+2CE
00007FFE51BE0BFB  000000DE222FE8E0  wcstol+12B
00007FF6D345D72C  000000DE222FF140  0001:000000000006C72C D:\cmangos\server-tbc\mangosd.exe
00007FF6D3684D63  000000DE222FF1F0  0001:0000000000293D63 D:\cmangos\server-tbc\mangosd.exe
00007FF6D345A110  000000DE222FF2B0  0001:0000000000069110 D:\cmangos\server-tbc\mangosd.exe
00007FF6D345D8BB  000000DE222FF2F0  0001:000000000006C8BB D:\cmangos\server-tbc\mangosd.exe
00007FF6D37D2497  000000DE222FF440  0001:00000000003E1497 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3450E6A  000000DE222FF4A0  0001:000000000005FE6A D:\cmangos\server-tbc\mangosd.exe
00007FF6D3455B89  000000DE222FF580  0001:0000000000064B89 D:\cmangos\server-tbc\mangosd.exe
00007FF6D344E48E  000000DE222FF5F0  0001:000000000005D48E D:\cmangos\server-tbc\mangosd.exe
00007FF6D344DD24  000000DE222FF6C0  0001:000000000005CD24 D:\cmangos\server-tbc\mangosd.exe
00007FF6D341982F  000000DE222FF6F0  0001:000000000002882F D:\cmangos\server-tbc\mangosd.exe
00007FF6D3405FBF  000000DE222FF720  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe
00007FFE51BF1BB2  000000DE222FF750  _configthreadlocale+92
00007FFE52B77034  000000DE222FF780  BaseThreadInitThunk+14
00007FFE541C2651  000000DE222FF800  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420D3C4  000000DE214FF190  NtDelayExecution+14
00007FFE51F496DE  000000DE214FF230  SleepEx+9E
00007FFE46B130BC  000000DE214FF280  _Thrd_sleep+3C
00007FF6D34060E6  000000DE214FF2E0  0001:00000000000150E6 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3411D98  000000DE214FF790  0001:0000000000020D98 D:\cmangos\server-tbc\mangosd.exe
00007FF6D340B0E7  000000DE214FF9D0  0001:000000000001A0E7 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3A3736C  000000DE214FFA10  0001:000000000064636C D:\cmangos\server-tbc\mangosd.exe
00007FFE52B77034  000000DE214FFA40  BaseThreadInitThunk+14
00007FFE541C2651  000000DE214FFAC0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420D3C4  000000DE218FFA80  NtDelayExecution+14
00007FFE51F496DE  000000DE218FFB20  SleepEx+9E
00007FFE46B130BC  000000DE218FFB70  _Thrd_sleep+3C
00007FF6D3434015  000000DE218FFBD0  0001:0000000000043015 D:\cmangos\server-tbc\mangosd.exe
00007FF6D343CB71  000000DE218FFC50  0001:000000000004BB71 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3405FBF  000000DE218FFC80  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe
00007FFE51BF1BB2  000000DE218FFCB0  _configthreadlocale+92
00007FFE52B77034  000000DE218FFCE0  BaseThreadInitThunk+14
00007FFE541C2651  000000DE218FFD60  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420D3C4  000000DE219FF5F0  NtDelayExecution+14
00007FFE51F496DE  000000DE219FF690  SleepEx+9E
00007FFE46B130BC  000000DE219FF6E0  _Thrd_sleep+3C
00007FF6D3434015  000000DE219FF740  0001:0000000000043015 D:\cmangos\server-tbc\mangosd.exe
00007FF6D343CB71  000000DE219FF7C0  0001:000000000004BB71 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3405FBF  000000DE219FF7F0  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe
00007FFE51BF1BB2  000000DE219FF820  _configthreadlocale+92
00007FFE52B77034  000000DE219FF850  BaseThreadInitThunk+14
00007FFE541C2651  000000DE219FF8D0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420D3C4  000000DE21AFF580  NtDelayExecution+14
00007FFE51F496DE  000000DE21AFF620  SleepEx+9E
00007FFE46B130BC  000000DE21AFF670  _Thrd_sleep+3C
00007FF6D3434015  000000DE21AFF6D0  0001:0000000000043015 D:\cmangos\server-tbc\mangosd.exe
00007FF6D343CB71  000000DE21AFF750  0001:000000000004BB71 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3405FBF  000000DE21AFF780  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe
00007FFE51BF1BB2  000000DE21AFF7B0  _configthreadlocale+92
00007FFE52B77034  000000DE21AFF7E0  BaseThreadInitThunk+14
00007FFE541C2651  000000DE21AFF860  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420D3C4  000000DE21BFF8C0  NtDelayExecution+14
00007FFE51F496DE  000000DE21BFF960  SleepEx+9E
00007FFE46B130BC  000000DE21BFF9B0  _Thrd_sleep+3C
00007FF6D3434015  000000DE21BFFA10  0001:0000000000043015 D:\cmangos\server-tbc\mangosd.exe
00007FF6D343CB71  000000DE21BFFA90  0001:000000000004BB71 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3405FBF  000000DE21BFFAC0  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe
00007FFE51BF1BB2  000000DE21BFFAF0  _configthreadlocale+92
00007FFE52B77034  000000DE21BFFB20  BaseThreadInitThunk+14
00007FFE541C2651  000000DE21BFFBA0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE54210734  000000DE21EFFBE0  NtWaitForAlertByThreadId+14
00007FFE541D4021  000000DE21EFFC60  RtlSleepConditionVariableSRW+131
00007FFE51F6D059  000000DE21EFFCA0  SleepConditionVariableSRW+29
00007FFE46B12B89  000000DE21EFFCD0  ?_Winerror_message@std@@YAKKPEADK@Z+139
00007FFE46B12E1A  000000DE21EFFD00  _Cnd_wait+3A
00007FF6D375FA08  000000DE21EFFD30  0001:000000000036EA08 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3405FBF  000000DE21EFFD60  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe
00007FFE51BF1BB2  000000DE21EFFD90  _configthreadlocale+92
00007FFE52B77034  000000DE21EFFDC0  BaseThreadInitThunk+14
00007FFE541C2651  000000DE21EFFE40  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE54210734  000000DE21FFFAD0  NtWaitForAlertByThreadId+14
00007FFE541D4021  000000DE21FFFB50  RtlSleepConditionVariableSRW+131
00007FFE51F6D059  000000DE21FFFB90  SleepConditionVariableSRW+29
00007FFE46B12B89  000000DE21FFFBC0  ?_Winerror_message@std@@YAKKPEADK@Z+139
00007FFE46B12E1A  000000DE21FFFBF0  _Cnd_wait+3A
00007FF6D375FA08  000000DE21FFFC20  0001:000000000036EA08 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3405FBF  000000DE21FFFC50  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe
00007FFE51BF1BB2  000000DE21FFFC80  _configthreadlocale+92
00007FFE52B77034  000000DE21FFFCB0  BaseThreadInitThunk+14
00007FFE541C2651  000000DE21FFFD30  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE54210734  000000DE220FF5A0  NtWaitForAlertByThreadId+14
00007FFE541D4021  000000DE220FF620  RtlSleepConditionVariableSRW+131
00007FFE51F6D059  000000DE220FF660  SleepConditionVariableSRW+29
00007FFE46B12B89  000000DE220FF690  ?_Winerror_message@std@@YAKKPEADK@Z+139
00007FFE46B12E1A  000000DE220FF6C0  _Cnd_wait+3A
00007FF6D375FA08  000000DE220FF6F0  0001:000000000036EA08 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3405FBF  000000DE220FF720  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe
00007FFE51BF1BB2  000000DE220FF750  _configthreadlocale+92
00007FFE52B77034  000000DE220FF780  BaseThreadInitThunk+14
00007FFE541C2651  000000DE220FF800  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420D3C4  000000DE221FF540  NtDelayExecution+14
00007FFE51F496DE  000000DE221FF5E0  SleepEx+9E
00007FFE46B130BC  000000DE221FF630  _Thrd_sleep+3C
00007FF6D3796B68  000000DE221FF720  0001:00000000003A5B68 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3405FBF  000000DE221FF750  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe
00007FFE51BF1BB2  000000DE221FF780  _configthreadlocale+92
00007FFE52B77034  000000DE221FF7B0  BaseThreadInitThunk+14
00007FFE541C2651  000000DE221FF830  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420CE04  000000DE223FF2E0  NtReadFile+14
00007FFE51F2AF23  000000DE223FF360  ReadFile+73
00007FFE51BE84A9  000000DE223FF400  _read+209
00007FFE51BE8342  000000DE223FF440  _read+A2
00007FFE51BE81B0  000000DE223FF470  _fread_nolock_s+210
00007FFE51C44FEC  000000DE223FF4D0  getc+AC
00007FF6D34041D1  000000DE223FF730  0001:00000000000131D1 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3405FBF  000000DE223FF760  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe
00007FFE51BF1BB2  000000DE223FF790  _configthreadlocale+92
00007FFE52B77034  000000DE223FF7C0  BaseThreadInitThunk+14
00007FFE541C2651  000000DE223FF840  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420CE64  000000DE224FFB00  NtRemoveIoCompletion+14
00007FFE51F61A7F  000000DE224FFB60  GetQueuedCompletionStatus+4F
00007FF6D3414E30  000000DE224FFCB0  0001:0000000000023E30 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3416A64  000000DE224FFD90  0001:0000000000025A64 D:\cmangos\server-tbc\mangosd.exe
00007FF6D340BC7A  000000DE224FFDE0  0001:000000000001AC7A D:\cmangos\server-tbc\mangosd.exe
00007FFE51BF1BB2  000000DE224FFE10  _configthreadlocale+92
00007FFE52B77034  000000DE224FFE40  BaseThreadInitThunk+14
00007FFE541C2651  000000DE224FFEC0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420CDC4  000000DE225FFAE0  ZwWaitForSingleObject+14
00007FFE51F21ACE  000000DE225FFB80  WaitForSingleObjectEx+8E
00007FF6D343A8F3  000000DE225FFBB0  0001:00000000000498F3 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3417705  000000DE225FFBE0  0001:0000000000026705 D:\cmangos\server-tbc\mangosd.exe
00007FFE51BF1BB2  000000DE225FFC10  _configthreadlocale+92
00007FFE52B77034  000000DE225FFC40  BaseThreadInitThunk+14
00007FFE541C2651  000000DE225FFCC0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420CE64  000000DE226FF770  NtRemoveIoCompletion+14
00007FFE51F61A7F  000000DE226FF7D0  GetQueuedCompletionStatus+4F
00007FF6D3414E30  000000DE226FF920  0001:0000000000023E30 D:\cmangos\server-tbc\mangosd.exe
00007FF6D3416A64  000000DE226FFA00  0001:0000000000025A64 D:\cmangos\server-tbc\mangosd.exe
00007FF6D340BCCB  000000DE226FFA50  0001:000000000001ACCB D:\cmangos\server-tbc\mangosd.exe
00007FFE51BF1BB2  000000DE226FFA80  _configthreadlocale+92
00007FFE52B77034  000000DE226FFAB0  BaseThreadInitThunk+14
00007FFE541C2651  000000DE226FFB30  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE54210794  000000DE215FF9F0  ZwWaitForWorkViaWorkerFactory+14
00007FFE541C2DC7  000000DE215FFCF0  TpReleaseCleanupGroupMembers+747
00007FFE52B77034  000000DE215FFD20  BaseThreadInitThunk+14
00007FFE541C2651  000000DE215FFDA0  RtlUserThreadStart+21
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
00007FFE51BF6D89  000000DE222FE2A0  strnlen+109

00007FFE51BE2437  000000DE222FE2D0  strtol+A7

00007FFE51BE114A  000000DE222FE350  wcstol+67A

00007FFE51BE0D9E  000000DE222FE3B0  wcstol+2CE

00007FFE51BE0BFB  000000DE222FE8E0  wcstol+12B

00007FF6D345D72C  000000DE222FF140  0001:000000000006C72C D:\cmangos\server-tbc\mangosd.exe

00007FF6D3684D63  000000DE222FF1F0  0001:0000000000293D63 D:\cmangos\server-tbc\mangosd.exe

00007FF6D345A110  000000DE222FF2B0  0001:0000000000069110 D:\cmangos\server-tbc\mangosd.exe

00007FF6D345D8BB  000000DE222FF2F0  0001:000000000006C8BB D:\cmangos\server-tbc\mangosd.exe

00007FF6D37D2497  000000DE222FF440  0001:00000000003E1497 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3450E6A  000000DE222FF4A0  0001:000000000005FE6A D:\cmangos\server-tbc\mangosd.exe

00007FF6D3455B89  000000DE222FF580  0001:0000000000064B89 D:\cmangos\server-tbc\mangosd.exe

00007FF6D344E48E  000000DE222FF5F0  0001:000000000005D48E D:\cmangos\server-tbc\mangosd.exe

00007FF6D344DD24  000000DE222FF6C0  0001:000000000005CD24 D:\cmangos\server-tbc\mangosd.exe

00007FF6D341982F  000000DE222FF6F0  0001:000000000002882F D:\cmangos\server-tbc\mangosd.exe

00007FF6D3405FBF  000000DE222FF720  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe

00007FFE51BF1BB2  000000DE222FF750  _configthreadlocale+92

00007FFE52B77034  000000DE222FF780  BaseThreadInitThunk+14

00007FFE541C2651  000000DE222FF800  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420D3C4  000000DE214FF190  NtDelayExecution+14

00007FFE51F496DE  000000DE214FF230  SleepEx+9E

00007FFE46B130BC  000000DE214FF280  _Thrd_sleep+3C

00007FF6D34060E6  000000DE214FF2E0  0001:00000000000150E6 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3411D98  000000DE214FF790  0001:0000000000020D98 D:\cmangos\server-tbc\mangosd.exe

00007FF6D340B0E7  000000DE214FF9D0  0001:000000000001A0E7 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3A3736C  000000DE214FFA10  0001:000000000064636C D:\cmangos\server-tbc\mangosd.exe

00007FFE52B77034  000000DE214FFA40  BaseThreadInitThunk+14

00007FFE541C2651  000000DE214FFAC0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420D3C4  000000DE218FFA80  NtDelayExecution+14

00007FFE51F496DE  000000DE218FFB20  SleepEx+9E

00007FFE46B130BC  000000DE218FFB70  _Thrd_sleep+3C

00007FF6D3434015  000000DE218FFBD0  0001:0000000000043015 D:\cmangos\server-tbc\mangosd.exe

00007FF6D343CB71  000000DE218FFC50  0001:000000000004BB71 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3405FBF  000000DE218FFC80  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe

00007FFE51BF1BB2  000000DE218FFCB0  _configthreadlocale+92

00007FFE52B77034  000000DE218FFCE0  BaseThreadInitThunk+14

00007FFE541C2651  000000DE218FFD60  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420D3C4  000000DE219FF5F0  NtDelayExecution+14

00007FFE51F496DE  000000DE219FF690  SleepEx+9E

00007FFE46B130BC  000000DE219FF6E0  _Thrd_sleep+3C

00007FF6D3434015  000000DE219FF740  0001:0000000000043015 D:\cmangos\server-tbc\mangosd.exe

00007FF6D343CB71  000000DE219FF7C0  0001:000000000004BB71 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3405FBF  000000DE219FF7F0  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe

00007FFE51BF1BB2  000000DE219FF820  _configthreadlocale+92

00007FFE52B77034  000000DE219FF850  BaseThreadInitThunk+14

00007FFE541C2651  000000DE219FF8D0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420D3C4  000000DE21AFF580  NtDelayExecution+14

00007FFE51F496DE  000000DE21AFF620  SleepEx+9E

00007FFE46B130BC  000000DE21AFF670  _Thrd_sleep+3C

00007FF6D3434015  000000DE21AFF6D0  0001:0000000000043015 D:\cmangos\server-tbc\mangosd.exe

00007FF6D343CB71  000000DE21AFF750  0001:000000000004BB71 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3405FBF  000000DE21AFF780  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe

00007FFE51BF1BB2  000000DE21AFF7B0  _configthreadlocale+92

00007FFE52B77034  000000DE21AFF7E0  BaseThreadInitThunk+14

00007FFE541C2651  000000DE21AFF860  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420D3C4  000000DE21BFF8C0  NtDelayExecution+14

00007FFE51F496DE  000000DE21BFF960  SleepEx+9E

00007FFE46B130BC  000000DE21BFF9B0  _Thrd_sleep+3C

00007FF6D3434015  000000DE21BFFA10  0001:0000000000043015 D:\cmangos\server-tbc\mangosd.exe

00007FF6D343CB71  000000DE21BFFA90  0001:000000000004BB71 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3405FBF  000000DE21BFFAC0  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe

00007FFE51BF1BB2  000000DE21BFFAF0  _configthreadlocale+92

00007FFE52B77034  000000DE21BFFB20  BaseThreadInitThunk+14

00007FFE541C2651  000000DE21BFFBA0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE54210734  000000DE21EFFBE0  NtWaitForAlertByThreadId+14

00007FFE541D4021  000000DE21EFFC60  RtlSleepConditionVariableSRW+131

00007FFE51F6D059  000000DE21EFFCA0  SleepConditionVariableSRW+29

00007FFE46B12B89  000000DE21EFFCD0  ?_Winerror_message@std@@YAKKPEADK@Z+139

00007FFE46B12E1A  000000DE21EFFD00  _Cnd_wait+3A

00007FF6D375FA08  000000DE21EFFD30  0001:000000000036EA08 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3405FBF  000000DE21EFFD60  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe

00007FFE51BF1BB2  000000DE21EFFD90  _configthreadlocale+92

00007FFE52B77034  000000DE21EFFDC0  BaseThreadInitThunk+14

00007FFE541C2651  000000DE21EFFE40  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE54210734  000000DE21FFFAD0  NtWaitForAlertByThreadId+14

00007FFE541D4021  000000DE21FFFB50  RtlSleepConditionVariableSRW+131

00007FFE51F6D059  000000DE21FFFB90  SleepConditionVariableSRW+29

00007FFE46B12B89  000000DE21FFFBC0  ?_Winerror_message@std@@YAKKPEADK@Z+139

00007FFE46B12E1A  000000DE21FFFBF0  _Cnd_wait+3A

00007FF6D375FA08  000000DE21FFFC20  0001:000000000036EA08 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3405FBF  000000DE21FFFC50  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe

00007FFE51BF1BB2  000000DE21FFFC80  _configthreadlocale+92

00007FFE52B77034  000000DE21FFFCB0  BaseThreadInitThunk+14

00007FFE541C2651  000000DE21FFFD30  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE54210734  000000DE220FF5A0  NtWaitForAlertByThreadId+14

00007FFE541D4021  000000DE220FF620  RtlSleepConditionVariableSRW+131

00007FFE51F6D059  000000DE220FF660  SleepConditionVariableSRW+29

00007FFE46B12B89  000000DE220FF690  ?_Winerror_message@std@@YAKKPEADK@Z+139

00007FFE46B12E1A  000000DE220FF6C0  _Cnd_wait+3A

00007FF6D375FA08  000000DE220FF6F0  0001:000000000036EA08 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3405FBF  000000DE220FF720  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe

00007FFE51BF1BB2  000000DE220FF750  _configthreadlocale+92

00007FFE52B77034  000000DE220FF780  BaseThreadInitThunk+14

00007FFE541C2651  000000DE220FF800  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420D3C4  000000DE221FF540  NtDelayExecution+14

00007FFE51F496DE  000000DE221FF5E0  SleepEx+9E

00007FFE46B130BC  000000DE221FF630  _Thrd_sleep+3C

00007FF6D3796B68  000000DE221FF720  0001:00000000003A5B68 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3405FBF  000000DE221FF750  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe

00007FFE51BF1BB2  000000DE221FF780  _configthreadlocale+92

00007FFE52B77034  000000DE221FF7B0  BaseThreadInitThunk+14

00007FFE541C2651  000000DE221FF830  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420CE04  000000DE223FF2E0  NtReadFile+14

00007FFE51F2AF23  000000DE223FF360  ReadFile+73

00007FFE51BE84A9  000000DE223FF400  _read+209

00007FFE51BE8342  000000DE223FF440  _read+A2

00007FFE51BE81B0  000000DE223FF470  _fread_nolock_s+210

00007FFE51C44FEC  000000DE223FF4D0  getc+AC

00007FF6D34041D1  000000DE223FF730  0001:00000000000131D1 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3405FBF  000000DE223FF760  0001:0000000000014FBF D:\cmangos\server-tbc\mangosd.exe

00007FFE51BF1BB2  000000DE223FF790  _configthreadlocale+92

00007FFE52B77034  000000DE223FF7C0  BaseThreadInitThunk+14

00007FFE541C2651  000000DE223FF840  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420CE64  000000DE224FFB00  NtRemoveIoCompletion+14

00007FFE51F61A7F  000000DE224FFB60  GetQueuedCompletionStatus+4F

00007FF6D3414E30  000000DE224FFCB0  0001:0000000000023E30 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3416A64  000000DE224FFD90  0001:0000000000025A64 D:\cmangos\server-tbc\mangosd.exe

00007FF6D340BC7A  000000DE224FFDE0  0001:000000000001AC7A D:\cmangos\server-tbc\mangosd.exe

00007FFE51BF1BB2  000000DE224FFE10  _configthreadlocale+92

00007FFE52B77034  000000DE224FFE40  BaseThreadInitThunk+14

00007FFE541C2651  000000DE224FFEC0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420CDC4  000000DE225FFAE0  ZwWaitForSingleObject+14

00007FFE51F21ACE  000000DE225FFB80  WaitForSingleObjectEx+8E

00007FF6D343A8F3  000000DE225FFBB0  0001:00000000000498F3 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3417705  000000DE225FFBE0  0001:0000000000026705 D:\cmangos\server-tbc\mangosd.exe

00007FFE51BF1BB2  000000DE225FFC10  _configthreadlocale+92

00007FFE52B77034  000000DE225FFC40  BaseThreadInitThunk+14

00007FFE541C2651  000000DE225FFCC0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE5420CE64  000000DE226FF770  NtRemoveIoCompletion+14

00007FFE51F61A7F  000000DE226FF7D0  GetQueuedCompletionStatus+4F

00007FF6D3414E30  000000DE226FF920  0001:0000000000023E30 D:\cmangos\server-tbc\mangosd.exe

00007FF6D3416A64  000000DE226FFA00  0001:0000000000025A64 D:\cmangos\server-tbc\mangosd.exe

00007FF6D340BCCB  000000DE226FFA50  0001:000000000001ACCB D:\cmangos\server-tbc\mangosd.exe

00007FFE51BF1BB2  000000DE226FFA80  _configthreadlocale+92

00007FFE52B77034  000000DE226FFAB0  BaseThreadInitThunk+14

00007FFE541C2651  000000DE226FFB30  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFE54210794  000000DE215FF9F0  ZwWaitForWorkViaWorkerFactory+14

00007FFE541C2DC7  000000DE215FFCF0  TpReleaseCleanupGroupMembers+747

00007FFE52B77034  000000DE215FFD20  BaseThreadInitThunk+14

00007FFE541C2651  000000DE215FFDA0  RtlUserThreadStart+21

### Core SHA1 Commit Hash

5adcbeaf509c7b90d4efb1ffd1aa439881f0659f

### Database SHA1 Commit Hash

8f71a0b8ddddcf286d685fbf8f652e4c0953ca1f

### Operating System

Windows 10 x64

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
What is the exact string you typed into chat?

**Comment by killerwife** [comment]
I tested it on a brand new character and it works as intended. Again, you will need to post a crash with debug symbols because the trace does not show where it crashed.

**Comment by al3xc1985** [comment]
@AnonXS all works perfect, tested 100 times
