### ISSUE TITLE
🐛 [Bug Report] [WoTLK] [Quest] Legend of Stalvan hung on chain quest #8 to #9

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3050]
### Bug Details

When running the Legend of Stalvan (quest=75) chain 7, I arrive at the Eastvale Logging Camp, and speak to Marshal Haggard  (npc=294) completing chain quest 7 (quest=74). He give you chain quest 8 (quest=75), to go upstairs to get the The Faded Journal Page (item=921) from Marshal Haggard's Chest (object=1562), and return it to him. When i arrive back at Marshal Haggard the question mark over his head is blue. I speak to him and complete the quest and he attempts to give me chain quest 9 (quest=78). When i except the quest it says "You don't meet the requirements for this quest", then the mark over his head changes to a exclamation mark. Speak to him and he gives me quest 8 again, and it continues to loop like this.

### Steps to Reproduce

1. get started on the quest chain (Legend of Stalvan)
2. get to to chain quest 7
3. go to Eastvale Logging Camp and speak to Marshal Haggard
4.  accept chain quest 8
5. goto second floor of the cottage and get the "Faded Journal Page"
6. return to Marsharl Haggard, complete and accept next chain quest 9
7.

### Expected behavior

Be able to accept Legend of Stalvan chain quest 9

### Suggested Workaround

n/a

### Crash Log

n/a

### Core SHA1 Commit Hash

9cbd887f50bff305fce0a61c6a6f4c8915e6594e

### Database SHA1 Commit Hash

0f892ac09ede0245a90d331cdb8fb227b120a3e7

### Operating System

Ubuntu 20.04.3 Server LTS, WIndows 7 Client

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by miraco** [comment]
Just from looking into databas:
You need level 22 and be alliance to acept this quest prev quest is id 75
You sure you have all the requirments?

**Comment by adellaci** [comment]
Human Warlock Alliance Level 34

**Comment by adellaci** [comment]
Thank you @Grz3s it works correctly
