### ISSUE TITLE
🐛 [Bug Report] Quests min level correction

### ISSUE THREAD

**Issue by Erikbmd** [cmangos/issues#3052]
### Bug Details

Quests id 2784, 2621, 2622, 2801, 2681, 2702, 2721, 2743, 2744, 3141, 3508, 3509, 3626 min level should be 45.

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

4db5562e6d73e7950f27bdc31140d02f1376c415

### Database SHA1 Commit Hash

72b35099e6059cadf5becdb5eeca4013d99a6c15

### Operating System

Windows 10 21H2

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/177200974-22142828-88b0-4512-93de-f0fabc9aef84.png)
