### ISSUE TITLE
🐛 [Bug Report] Blackout

### ISSUE THREAD

**Issue by ST369** [cmangos/issues#3054]
### Bug Details
It can only be triggered by direct damage.
### Expected behavior
It can be triggered (on application) by any damage spell from the shadow tree (not Mana Burn, Feedback, etc.), including the racials (Devouring Plague, Touch of Weakness, Shadowguard)
[Menismyforte S4 at 1:08](https://youtu.be/z7_PKSuahYY?t=68) – Mind Flay
[Menismyforte S4 at 2:18](https://youtu.be/z7_PKSuahYY?t=138) – Shadow Word: Pain
[Menismyforte S4 at 3:50](https://youtu.be/z7_PKSuahYY?t=229) – Touch of Weakness
[Classic TBC Arena DannyGaminGnC at 4:02](https://www.youtube.com/watch?v=iENn3yoZ2Nw&t=241s) – Devouring Plague
[Wowhead comments](https://tbc.wowhead.com/spell=15326/blackout#comments:id=229638)
[Reddit comment](https://www.reddit.com/r/classicwow/comments/flleww/human_priest_racial_ability_feedback_and_blackout/fl0ohot/?utm_source=reddit&utm_medium=web2x&context=3)
### Core SHA1 Commit Hash
9d3602ca41bc9e51dee0b0e34b23faf012dac0d1
### Database SHA1 Commit Hash
72b35099e6059cadf5becdb5eeca4013d99a6c15
### Operating System
Windows 10
### Client Version
2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Checking it out today, as likely recent proccing changes broke it.

**Comment by ST369** [comment]
damage over time spells

**Comment by killerwife** [comment]
https://wowpedia.fandom.com/wiki/Blackout wiki states it should not proc on damage over time, nor does Blackout have PROC_FLAG_DEAL_HARMFUL_PERIODIC

Only the initial cast of both mind flay, shadow word pain can proc blackout, and has been verified on Classic TBC PTR. Which I will assume already works properly.

**Comment by killerwife** [comment]
Try with this commit.

**Comment by ST369** [comment]
still no procs from Mind Flay and Vampiric Touch
everything else is fine

**Comment by killerwife** [comment]
Fixed mind flay and vampiric touch, closing.
