### ISSUE TITLE
🐛 [Bug Report] Naxx 10 man Sapphiron not spawning ice blocks in air phase

### ISSUE THREAD

**Issue by Beegeebus** [cmangos/issues#3055]
### Bug Details

Engaged Sapphiron in Naxx 10 man and during air phase the boss never spawns ice blocks to hide behind.

### Steps to Reproduce

1. Enter naxx 10
2. Fight Sapphiron
3. Enter Air Phase

### Expected behavior

During Air Phase Sapphiron should put "ice blocks" around random players that the other players need to hide behind to avoid the wipe mechanic.

### Crash Log

There was no crash log, just a bugged out boss mechanic

### Core SHA1 Commit Hash

9cbd887f50bff305fce0a61c6a6f4c8915e6594e

### Database SHA1 Commit Hash

0f892ac09ede0245a90d331cdb8fb227b120a3e7

### Operating System

Windows Server 2019

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-wotlk/commit/890d74f217e85a2f1b251d0ca93f6a807e59437b
