### ISSUE TITLE
🐛 [Bug Report] Naxx 10 Kel'Thuzad adds spawn but do not move, continue to attack players

### ISSUE THREAD

**Issue by Beegeebus** [cmangos/issues#3057]
### Bug Details

Engage in Kel'Thuzad phase 2, when adds spawn they do not move from their spawn point but continue to attack players.

### Steps to Reproduce

1. Engage Kel'Thuzad
2. Enter phase 2
3. When adds spawn you'll see they are stuck at their spawn point but continue to attack players
4.

### Expected behavior

Adds run to the raid and are usually tanked to the side of Kel'Thuzad

### Core SHA1 Commit Hash

9cbd887f50bff305fce0a61c6a6f4c8915e6594e

### Database SHA1 Commit Hash

0f892ac09ede0245a90d331cdb8fb227b120a3e7

### Operating System

Windows Server 2019

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
To fix this simply add this in SQL:
```sql
UPDATE creature_model_info SET combat_reach=3 WHERE modelid=16586;
```

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-wotlk/commit/b5b52bf43ed33cbb86fe974acb64917dcc8c2138
