### ISSUE TITLE
🐛 [Bug Report] Using Penance in WoTLK does no healing to friendly players

### ISSUE THREAD

**Issue by ncuddemiIT** [cmangos/issues#3058]
### Bug Details

Casting Penance on friendly players causes no healing

### Steps to Reproduce

1. Enter a party with a friendly player, have them take self damage so they are missing health
2. Cast Penance on that player
3. No healing is provided by Penance to that player

### Expected behavior

Penance should heal friendly players when targeted with the spell

### Core SHA1 Commit Hash

9cbd887f50bff305fce0a61c6a6f4c8915e6594e

### Database SHA1 Commit Hash

0f892ac09ede0245a90d331cdb8fb227b120a3e7

### Operating System

Windows Server 2019

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
I'm getting reports that this bug is still active, but I haven't confirmed it myself yet. I'll reopen if it turns out to be true.

**Comment by insunaa** [comment]
I couldn't test it with a second player character, but at least when targeting self Penance still does not heal.

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-wotlk/commit/abc00dd70f0aa41375c77f8c4e09042399d57494
