### ISSUE TITLE
🐛 [Bug Report] Mind Vision

### ISSUE THREAD

**Issue by ST369** [cmangos/issues#3061]
### Bug Details

∙ it breaks instantly on targets 100+ yards away from the priest
∙ if the spell fails (e.g. resist vs cloak of shadows), the priest still gets the debuff

### Steps to Reproduce

1.
2.
3.
4.

### Expected behavior

https://www.youtube.com/watch?v=EiKFO9k9Efw
https://www.youtube.com/watch?v=uPmqqRIs7bo
https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/49611237

### Core SHA1 Commit Hash

852785df69a2fc504f08d3ed1224db5c12d4e9ce

### Database SHA1 Commit Hash

185c1695c0a6a4040ffbe5edb77bfc3df1aee762

### Operating System

Windows 10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/commit/7a2d578684d12a9651ad79b36c04992295906fd9

**Comment by killerwife** [comment]
The resist part is now fixed. Other will follow.
