### ISSUE TITLE
🐛 [Bug Report] Classic - Eviscerate damage

### ISSUE THREAD

**Issue by kepheuswow** [cmangos/issues#3068]
### Bug Details

Damage of Eviscerate is only doing around 1800-1900 damage (critical). Tested this with Eviscerate (Rank 8) and Eviscerate (Rank 9) using a Combat Spec and about the same Gear as in the videos shown below. 

Eviscerate (Rank 8)
https://classic.wowhead.com/spell=11300/eviscerate

Eviscerate (Rank 9)
https://classic.wowhead.com/spell=31016/eviscerate

Gear used:
5/5 Deathdealer Set
4/9 Bonescythe Set
1044 Attack Power

Spec used:
https://classic.wowhead.com/talent-calc/rogue/305320105-3210052020050150231

Improved Eviscerate (Talent):
Increases the damage done by your Eviscerate ability by 15%.
https://classic.wowhead.com/spell=14164/improved-eviscerate

Aggression (Talent):
Increases the damage of your Sinister Strike and Eviscerate abilities by 6%.
https://classic.wowhead.com/spell=18429/aggression

Deathdealer's Embrace Set:
15% increased damage to your Eviscerate ability. (https://classic.wowhead.com/spell=26113/deathdealer-eviscerate-bonus)
https://classic.wowhead.com/item-set=497/deathdealers-embrace

A rogue with 1000 attack power using 5 combo points of Eviscerate Rank 9 will have a damage range of:
Modifier = 1000 * (5 * 0.03) = 150
Eviscerate = (904 + 150) up to (1012 + 150) = 1054 up to 1162 damage
Critical Eviscerate = 2108 up to 2324 damage
Source: https://vanilla-wow-archive.fandom.com/wiki/Eviscerate

### Steps to Reproduce

1. apply 5 combo points
2. use Eviscerate (Rank 8) or (Rank 9)
3.
4.

### Expected behavior

Clips showing that Eviscerate should do more damage. 

Akrios - Eviscerate 2
https://www.youtube.com/watch?v=47SJDplTHUs

Akrios - Eviscerate 3
https://www.youtube.com/watch?v=KBcB3YqKuN8

Kenion - Eviscerape
https://www.youtube.com/watch?v=q51IaZed8u0

### Core SHA1 Commit Hash

e422e76c9a68b47fba8d23878a5f694e9908f483

### Database SHA1 Commit Hash

3e46b560068766439b197335debf81faa894fe0a

### Operating System

Arch Linux

### Client Version

1.1.12 (Classic)

**Comment by killerwife** [comment]
I have setup a rogue for testing on my local. PRE-armor, I tested up to 3000 damage. When testing on Teremus the Devourer, that damage due to his armor got reduced to 1800-ish damage. I imagine on a clothie player it will be way higher.

Please lemme know what weapons you were using and what target you were using as validation.

**Comment by kepheuswow** [comment]
@killerwife After further testing I came up with the following results. 

Gear used:
5/5 Deathdealer Set
4/9 Bonescythe Set
MH Weapon: Gressil, Dawn of Ruin
OH Weapon: Iblis, Blade of the Fallen Seraph

Combat Spec with Improved Expose Armor:
https://classic.wowhead.com/talent-calc/rogue/305300125-3210052020050150231

![1657649631](https://user-images.githubusercontent.com/109022888/178574165-00fc8f28-6ee0-411c-881e-0f0667658d10.jpg)

Hemo Spec:
https://classic.wowhead.com/talent-calc/rogue/305320105101-3-500253000332121

![1657652206](https://user-images.githubusercontent.com/109022888/178574341-0ff2d868-bcfe-40ed-ab8e-04554db1ba0f.jpg)

What I further noticed is that I don't critically hit, if the target is sitting, which it should.

You can then mark this Report as closed.

**Comment by killerwife** [comment]
Okay, checking out the sitting part :)

**Comment by killerwife** [comment]
Autocrit was there on melee attack but not on melee ability. Pushing to tbc branch, will sync branches later this week.

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/commit/3ce1872e40cc501cd8a27c4a21343bb4a71fe065
