### ISSUE TITLE
🐛 [Bug Report]  Gizelton Caravan

### ISSUE THREAD

**Issue by miraco** [cmangos/issues#3072]
### Bug Details

Taken from LV Discord, i will share my researches about this npcs + quests here.

_"Intro"_
![Start](https://user-images.githubusercontent.com/6261245/179057202-3431c521-cbda-4484-8e06-31c96631704c.jpg)
Bugs:

- [x] Respawn positions are wrong. Should be like in the picture
- [x] Vendor List for Vendor-Tron 1000 is wrong (sorting)
- [x] Only Cork gizletone will have gossip at" northside"
- [x] After 10 minutes and 4 seconds Cork Gizletone will say text: 'So sorry to leave a customer but we have places to go and people to swindle. We will be back sometime later today. Good-bye!' id 7505
- [x] After 10 minutes and 13 seconds npc "Vendor-Tron 1000" will despawn
- [x] After 10 minutes and 14 seconds the 'Caravan' will set formationtype to SPAWN_GROUP_FORMATION_TYPE_SINGLE_FILE
- [x] and start movement.

"First Escort pause"
- [x] On Waypoint 16 (from sniffed points) Cork Gizeltone will get Quest Giver Flag and **yell** text 'I am looking for some bodyguards that would like to protect the Gizelton Caravan. We are stopped on the road east of Kormek's Hut, north of Kolkar Centaur Village.' id 7474
- [x] When nothing happens, after 4 minutes Cork Gizeltone will remove quest giver Flag and continue normal waypoints.

"Escort quest 'Bodyguard for Hire'"
- [x] When players start quest "Bodyguard for Hire" Cork Gizeltone will start escort path.
- [x] on point 5,9 and 14 he will stop, say some text with 4 second delay and spawn 4 mobs.
- [x] On point 18 npc says some text (4sec delay) and complete quests for players
- [x] Quest done -> continue "normal path" at point 33

"Southside stop"
- [x]  When reaching southside stop (waypoint ?)  Super-Seller 680 will spawn (delay ~6 seconds after reaching waypoint)
- [x]  Rigger Gizelton get Gossip Flag
- [x]  After 10 minutes and 4 seconds  Rigger Gizelton says text "Time for the Gizleton Caravan to head on out! We'll be back soon but if you cannot wait, head north to Kormek's Hut. We open shop in about an hour." id 7506
- [x] After 10 minutes and 13 seconds Super-Seller 680 gets despawned and Rigger Gizelton removes Gossip Flag
- [x] After 10 minutes and 14 seconds the 'Caravan' will continue their waypoints.

"Escort quest 'Gizelton Caravan'
- [x] Add Point 85 Rigger Gizelton will get questgiver flag and say text "This is Rigger Gizelton asking for assistance escorting my caravan past Mannoroc Coven. I'm on the road east of Shadowprey village." id 7475
- [x] When nothing happens, after 4 minutes Cork Gizeltone will remove quest giver Flag and continue normal waypoints.
- [x] When players start quest  Cork Gizeltone will start escort path 2.

Current things i didnt figured out how to work:

- [x] When npcs respawn and have entry in spawn_group_formation they will instantly get in the shape instead of standing.
- [x] While escorting when resetting (after mobs attacked) the shape gets "changed"

### Steps to Reproduce

1.  go c 28714
2. kill
3. respawn
4.

### Core SHA1 Commit Hash

s

### Database SHA1 Commit Hash

s

### Operating System

Windows

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
thx @miraco
