### ISSUE TITLE
🐛 [Bug Report] Classic - Tame Beast doesn't work

### ISSUE THREAD

**Issue by kepheuswow** [cmangos/issues#3074]
### Bug Details

Created a lvl 60 Hunter (Alliance, Night Elf) and did the lvl 10 Hunter Quest "Taming the Beast" afterwards to get the Spells Tame Beast (https://classic.wowhead.com/spell=1515/tame-beast) etc. During the Questline I had no problem to the tame the mobs with the Item. 

Also the pet should follow you automatically after taming it which was already reported in #2270 and #2946.

After I finished the Quest I wanted to tame a  Beast. But I'm not able to tame a Beast. Tried several times (with Freezing Trap/Scare Beast). Doesn't matter wether it's low level (5-10) or high level. It didn't work.

### Steps to Reproduce

1. create lvl 60 Hunter (Alliance)
2. start and finish the Questline "Taming the Beast" (optional)
3. try to the tame a Beast (low lvl or high lvl) with the spell "Tame Beast"
4.

### Expected behavior

After successfully taming a Beast you should have it as your pet.

Here you can see that the pet should automatically follow you after taming. 
https://www.youtube.com/watch?v=p-elqlrjKA0

### Core SHA1 Commit Hash

e422e76c9a68b47fba8d23878a5f694e9908f483

### Database SHA1 Commit Hash

3e46b560068766439b197335debf81faa894fe0a

### Operating System

Arch Linux

### Client Version

1.1.12 (Classic)

**Comment by Weetermachine** [comment]
Having this same issue.

**Comment by insunaa** [comment]
This does not occur on WotLK. Works fine, including pet following there.
I'll mark this as a classic issue

**Comment by Logandros** [comment]
Confirmed on Horde side, questline can be completed. However spell gained after completion will not allow you to tame a new pet.

**Comment by MilkmanMHOC** [comment]
Just throwing in another comment here as i came across this today.  Can confirm this is not working on Classic currently.  Used to work, doesn't seem to matter the lvl of hunter trying to tame.  Existing pets work fine and as expected.

**Comment by kepheuswow** [comment]
It's also working fine in mangos-tbc.
