### ISSUE TITLE
🚀 [Feature Request] Keep playerbots at feature parity between cores

### ISSUE THREAD

**Issue by hastings101** [cmangos/issues#3076]
### Feature Details

Currently the optional Playerbots system in Classic/TBC/WotLK, depending on the core, is missing some commands, or the results of the commands are different, despite documentation stating otherwise. For example :

Classic - FOLLOW command orders bots to follow.  No subcommands allowed.
WotLK - FOLLOW commands orders bots to follow, allows the subcommands NEAR, FAR, AUTO, RESET, INFO.

Classic - TALENT command and subcommands are unavailable or do not appear to work.
WotLK - TALENT commands and subcommands are available to change bot talents/spec.

### Benefits and Purpose

Despite being optional, Playerbots are a popular feature for small or single-player servers.  CMANGOS is one of the easiest to build and use cores around and would likely benefit a good portion of its users by keeping the Playerbase module consistent and up to date between all cores.  

Keeping Playerbots at a basic feature parity (besides expansion induced differences) would also make it easier to add new features to the bots and for new, interested contributors to work on fixes.  It would also make playing on CMANGOS-based servers more consistent across the board for users who choose to include the Playerbot system and would not limit players to certain cores in order to use certain Playerbot features/commands.

### Core Versions

- [X] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
Closing due to deprecation of the old playerbots.
