### ISSUE TITLE
🐛 [Bug Report] Classic - Warlock and .learn all_myspells/.learn all_myclass, resistance issue

### ISSUE THREAD

**Issue by kepheuswow** [cmangos/issues#3078]
### Bug Details

Created a Warlock used .levelup 59 and .learn all_myspells/.learn all_myclass. After some time I realized that this Warlock has a magical resistance of 120 for all magic schools (Arcane, Fire, Nature, Frost and Shadow). No gear, consumables or something!

### Steps to Reproduce

1. create a Warlock
2. use .levelup 59
3. use .learn all_myspells or .learn all_myclass
4. check the resistances in the character window

### Expected behavior

Magical resistance for all magic schools should be 0 except the character gets it from his racial. 

### Core SHA1 Commit Hash

1f3bc3cd4641232fcd97e0b1b579504e12994555

### Database SHA1 Commit Hash

a8e3ee243e20246e79a99eb41c405955daa7ad5d

### Operating System

Arch Linux

### Client Version

1.1.12 (Classic)

**Comment by celguar** [comment]
Learn_all_x commands are in no way an equivalent of visiting a trainer and will give you tons of wrong spells like talents you don't have or spells you are not supposed to see at all

**Comment by kepheuswow** [comment]
I'm fully aware of that. It was just for testing purposes. But nonetheless it shouldn't be the case that you get resistance if you use such command.

**Comment by AnonXS** [comment]
you probably get the felhunter aura added to you as its a warlock pet spell.

**Comment by kepheuswow** [comment]
I didn't come across such aura/buff. Furthermore did I remove all unnecessary spells with .unlearn. Still had 120 resistance.

**Comment by AnonXS** [comment]
Tamed Pet Passive (DND): 19007, added here: https://github.com/cmangos/issues/issues/3077
