### ISSUE TITLE
Mob AI

### ISSUE THREAD

**Issue by miraco** [cmangos/issues#308]
The Mob AI isn´t working.
Mobs can switch between Range and Melee. - if you got 1time melee they always try to run in melee range and never switch back in range modus.
LoS pulling not working.
when get traped/scattered or something like this they should try to run away to get back to range modus. (example: lady vashj when getting entagle)

A video for this:
http://www.youtube.com/watch?v=gXn7HRgYe1c

**Comment by cala** [comment]
Closing this issue which is similar to #180
