### ISSUE TITLE
🐛 [Bug Report] Heroism / Bloodlust ignores Exhausted / Sated

### ISSUE THREAD

**Issue by insunaa** [cmangos/issues#3083]
### Bug Details

Characters can receive the Heroism/Bloodlust buff even if they are affected by the Exhausted / Sated debuff.

### Steps to Reproduce

1. Cast Heroism
2. Reset your cooldowns (.cooldown clear)
3. Cast Heroism again

### Expected behavior

Heroism should not be added to any target already affected by Exhausted / Sated

### Core SHA1 Commit Hash

95c98331406a6718f6b96fb4c78a4ffa4c86c958

### Database SHA1 Commit Hash

249dc1c18bf33ec082b524b9fb1dc4294ea699dd

### Operating System

Arch Linux

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
Rewrite s.57723,57724 as spellscript. - probably all spells with AddPrecastSpell(); are affected, thats alot.
```
        case SPELLFAMILY_SHAMAN:
        {
            // Bloodlust
            if (m_spellInfo->Id == 2825)
                AddPrecastSpell(57724);                     // Sated
            // Heroism
            else if (m_spellInfo->Id == 32182)
                AddPrecastSpell(57723);                     // Exhaustion
```

```
Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints: 1
Targets: (25, 0) (TARGET_UNIT, TARGET_NONE)
Aura: 4 (SPELL_AURA_DUMMY), value: 1, miscA: 0 (0), miscB: 0, periodic: 0
```

**Comment by insunaa** [comment]
I honestly don't even know what AddPrecastSpell does

**Comment by AnonXS** [comment]
e.g in tbcmangos s.11196 does:
```
Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints: 1
Targets: (21, 0) (TARGET_UNIT_FRIEND, TARGET_NONE)
Aura: 77 (SPELL_AURA_MECHANIC_IMMUNITY), value: 1, miscA: 16 (16), miscB: 0, periodic: 0
```
in wotlkmangos it was changed to be a dummy
```
Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints: 1
Targets: (21, 0) (TARGET_UNIT_FRIEND, TARGET_NONE)
Aura: 4 (SPELL_AURA_DUMMY), value: 1, miscA: 16 (16), miscB: 0, periodic: 0
```
so all of these now have to be scripted in wotlkmangos, else you can bandage, heroism/bl etc all you want without the preventing spells working.
