### ISSUE TITLE
[TBC] Bugged "arena ending screen"

### ISSUE THREAD

**Issue by Lillecarl** [cmangos/issues#309]
Hello!

Well i'll just show you guys these images:
http://puu.sh/66E7v.jpg
http://puu.sh/66EkC.jpg

MSG_PVP_LOG_DATA is the packet sent, clearly something wrong here ^^,

The first image is hordeVhorde, the second is hordeValliance

https://github.com/cmangos/mangos-tbc/commit/84d1ee6c89d7a26471ada731b294b7bb902bfcf0

NOTE: this is 2v2

Regards! :)

**Comment by stfx** [comment]
https://github.com/cmangos/mangos-tbc/commit/6894fe48d5010c19e0427a63281da3227a29c87b
