### ISSUE TITLE
🐛 [Bug Report] Going in the water doesn't switch to swimming

### ISSUE THREAD

**Issue by Nogemard** [cmangos/issues#3093]
### Bug Details

When you go in the water character doesn't switch to swimming and can run under water
![WoWScrnShot_073122_105526](https://user-images.githubusercontent.com/110330018/182019724-e140cc52-6134-405b-8ee5-83028fb4d694.jpg)
![WoWScrnShot_073122_105540](https://user-images.githubusercontent.com/110330018/182019726-b297b6f9-8e9c-484e-a09c-e7ae79f2acfd.jpg)

### Steps to Reproduce

1. Go in the water without jumping into it
2.
3.
4.

### Expected behavior

It should switch to swimming 

### Core SHA1 Commit Hash

effc4dca35d31d43532ee64a444a649491e4ade8

### Database SHA1 Commit Hash

f41a281549464c398f389f2b88928ce5169aed75

### Operating System

Windows 10 21H2

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
This is fully controlled clientside to my knowledge. We do not change anything with this. Closing it as such.
