### ISSUE TITLE
🚀 [Feature Request] Can I release the complete release version directly?

### ISSUE THREAD

**Issue by howarduong** [cmangos/issues#3094]
### Feature Details

Can I release the complete release version directly? I used database import, but it has never been successful, and I have tried many times.

### Benefits and Purpose

In this way, we can just download and play the game without having to perform too many settings.

### Core Versions

- [ ] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [ ] 3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
Can you clarify what you mean?
We literally have daily releases:
https://github.com/cmangos/mangos-tbc/releases/tag/latest
https://github.com/cmangos/tbc-db/releases/tag/latest

**Comment by cyberium** [comment]
No, its a learning project, you have to take time to learn how to do so, how to improve your own skills and then been able to help the community if you want to. You'll find help on our discord for that. Read the readme file.
To play the game without any issue your best choice is [battle.net](https://battle.net)
