### ISSUE TITLE
Quest Warn Bolvar! 11222 - missing afterscript

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#3100]
### Feature Details

Some RP, a bit more than just on screenshot

### Visualizations

![image](https://user-images.githubusercontent.com/7995382/182825859-0ac9833d-a83a-4046-b136-b980158cf776.png)

### Benefits and Purpose

Whitespace

### Core Versions

- [ ] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- #:x:  3.3.5a (Wrath of the Lich King)

**Comment by Grz3s** [comment]
quest has changed in 3.0.x due to diff story line:
2.4.3
```
Warn Bolvar!
Speak to Highlord Bolvar Fordragon in Stormwind Keep.
```

3.x.x
```
Proof of Treachery
Speak to King Varian Wrynn in Stormwind Keep.
```
Will leave to TDB  guys to deal with it
