### ISSUE TITLE
🐛 [Bug Report] Wailing Caverns final boss doesn't appear

### ISSUE THREAD

**Issue by Nogemard** [cmangos/issues#3103]
### Bug Details

The ritual isn't working and Mutanus the Devourer isn't appearing npc id 3654
![WoWScrnShot_080522_220920](https://user-images.githubusercontent.com/110330018/183156150-9a15b57a-786e-4a0a-a6e2-c1ab48deaefc.jpg)

### Steps to Reproduce

1. Do dungeon as usual 
2.
3.
4.

### Expected behavior

The ritual should work

### Core SHA1 Commit Hash

effc4dca35d31d43532ee64a444a649491e4ade8

### Database SHA1 Commit Hash

f41a281549464c398f389f2b88928ce5169aed75

### Operating System

Windows 10 21H2

### Client Version

2.4.3 (The Burning Crusade)

**Comment by miraco** [comment]
https://github.com/cmangos/issues/issues/2833
duplicate
