### ISSUE TITLE
🚀 [Feature Request

### ISSUE THREAD

**Issue by Simbioz163** [cmangos/issues#3105]
### Feature Details

This object is located in the Magisters' dungeon Terrace at the very end . Behind the last boss . By clicking on it , he should send to the island . This object does not work

Object 188173

### Benefits and Purpose

This object is located in the Magisters' dungeon Terrace at the very end . Behind the last boss . By clicking on it , he should send to the island . This object does not work

### Core Versions

- [ ] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [ ] 3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
s.46841
