### ISSUE TITLE
🐛 [Bug Report] TBC-Warsong

### ISSUE THREAD

**Issue by atidot3** [cmangos/issues#3106]
### Bug Details

Related to all the last changes with battleground warsong seems to have side effect now.

1) when a flag is being carried there is no more informations on screen as before:
![image](https://user-images.githubusercontent.com/3525729/183690579-74e6e0ad-1f0b-47c5-a440-63d88c2c65c6.png)

2) when you click on your own flag team after defeating an enemy you endup with the flag aura on your back:
![image](https://user-images.githubusercontent.com/3525729/183690777-677189d5-5c54-4fcb-98ca-c4c13b40472f.png)

Some debug test i made (see comment):
https://github.com/cmangos/mangos-tbc/commit/e82f26324d67c85cab53f09bf2a4b7a25caa802b

### Steps to Reproduce

1. Using a fresh compiled cmangos-tbc + fresh database installation (shell script install)
2. Enter warsong with a second account
3. Take the enemy flag
4. Make the second account kill you
5.Make the second account pick the flag

### Expected behavior

Actually show who's team is carrying the flag.

Do not endup carrying (aura only) your own flag.

### Core SHA1 Commit Hash

7084a0bb3d27e0733d059cd257acde2f97039acc

### Database SHA1 Commit Hash

3b27d1180e35a2734871be9c78ec7116635f2335

### Operating System

W10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by miraco** [comment]
can confirm

**Comment by henhouse** [comment]
Have you tried with latest updates? I know there were some issues for a while during some rewrites, but from what I know things are working as expected now.

**Comment by atidot3** [comment]
I belive this is related: https://github.com/cmangos/mangos-tbc/commit/d41111fd39092f8bdbd9fe26a00924984704d7b3

Havent tested myself.

**Comment by killerwife** [comment]
Closing this as I have addressed some bugs in WSG. Open the issue again should you encounter new issues.
