### ISSUE TITLE
War effort: Loot for random spawns

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#3108]
Add loot for:

https://classic.wowhead.com/npc=15810/eroded-anubisath-warbringer
https://classic.wowhead.com/npc=15813/qiraji-officer-zod
https://classic.wowhead.com/npc=15807/minor-anubisath-warbringer
https://classic.wowhead.com/npc=15814/qiraji-lieutenant-jo-rel
https://classic.wowhead.com/npc=15748/lesser-anubisath-warbringer
https://classic.wowhead.com/npc=15815/qiraji-captain-kaark
https://classic.wowhead.com/npc=15751/anubisath-warbringer
https://classic.wowhead.com/npc=15816/qiraji-major-heal-ie
https://classic.wowhead.com/npc=15754/greater-anubisath-warbringer
https://classic.wowhead.com/npc=15758/supreme-anubisath-warbringer
https://classic.wowhead.com/npc=15743/colossal-anubisath-warbringer
https://classic.wowhead.com/npc=15818/lieutenant-general-nokhor

@AnonXS @miraco

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/aa80da22e9ad5f0bb2034538962d02f27357f9a0
