### ISSUE TITLE
🐛 [Bug Report] Classic - Warsong mangosd crash

### ISSUE THREAD

**Issue by kepheuswow** [cmangos/issues#3110]
### Bug Details

If I try to pickup the enemy flag in Warsong Gulch it doesn't get picked up and the mangosd crashes. 

mangos>Segmentation fault (core dumped) 

### Steps to Reproduce

1. join Warsong Gulch
2. try to pickup the flag
3. mangosd should crash
4.

### Core SHA1 Commit Hash

7d029e0d203bc8fb998a7268a91fbded9f924449

### Database SHA1 Commit Hash

138197d8e3c88b21c280d955884b62f395e18e19

### Operating System

Arch Linux

### Client Version

1.12.1 (Classic)

**Comment by Novivy** [comment]
Just tried it and it does not crash on my end (I m on ef797221800493d26e4f5b17d34389953c591d7b)

**Comment by kepheuswow** [comment]
Tested it again and it is working now. No crashes.  

Core: d2d6631d3824fa7c2c3f28e525d33d2fedf2b510
DB: 1abab1db3866652080ed356b2039f498dee951e5
