### ISSUE TITLE
🐛 [Bug Report] Classic/TBC - mobs can fall through map

### ISSUE THREAD

**Issue by kepheuswow** [cmangos/issues#3111]
### Bug Details

Mobs could sometimes fall slightly through the map. This issue only happened with ranged classes so far. I extracted the maps in high resolution. 

Don't know if this can also happen in manogs-wotlk. 

Can this be fixed/improved?

![1657999567](https://user-images.githubusercontent.com/109022888/184478231-821208c2-bb7d-40ab-b518-2e9d94a8a103.jpg)

### Steps to Reproduce

1. attack a mob with ranged class
2. repeat till issue occurs
3.
4.

### Core SHA1 Commit Hash

7d029e0d203bc8fb998a7268a91fbded9f924449

### Database SHA1 Commit Hash

138197d8e3c88b21c280d955884b62f395e18e19

### Operating System

Arch Linux

### Client Version

1.12.1 (Classic)

**Comment by al3xc1985** [comment]
Try with improve Z option from mangosd

**Comment by al3xc1985** [comment]
Also u should recompile with latest changes. Cyberium did some changes.

**Comment by kepheuswow** [comment]
I pulled the latest changes and recompiled. Without the "PathFinder.NormalizeZ = 1" option the mobs behave really strange (see video below). With the "PathFinder.NormalizeZ = 1" option they sometimes behave like in the video but not all the time. 

But I haven't experienced yet that the mobs fall through the map.

**Core SHA1 Commit Hash**
34296b8b4ff72f9055bcc0791df06c1ccefb4ee2

**Database SHA1 Commit Hash**
b673499ee74a862d7b7f236d2d88d354be3ae814

https://user-images.githubusercontent.com/109022888/185800001-1639b205-c86c-4d08-a01d-6943be6dc6d4.mp4

**Comment by miraco** [comment]
cant see the video

**Comment by AnonXS** [comment]
maps in high resolution seem to be cause of more issues.

**Comment by al3xc1985** [comment]
Should we extract low resolution? Or wait for a proper fix?

**Comment by kepheuswow** [comment]
Cannot reproduce this issue anymore with latest Core & DB and reextracted maps. Normalize Z enabled in mangosd.conf.

**CMaNGOS Classic**
Core: d2d6631d3824fa7c2c3f28e525d33d2fedf2b510
DB: 1abab1db3866652080ed356b2039f498dee951e5

**CMaNGOS TBC**
Core: 4c9ae47acdc3743c1cb5e8e9ec83f39d0e2c96f9
DB: dbf9824ca8382f441ccb5c2f3cb967a8ced0e3ba

**Comment by cpevors** [comment]
Did you re-extract with high definition maps, or no? Simply curious, because I had this issue as well and would like to re-extract my maps if doing so resolves the issue.

**Comment by kepheuswow** [comment]
Yes, always with high res maps.
