### ISSUE TITLE
🐛 [Bug Report] Death Knight using Death Gate causes server to crash

### ISSUE THREAD

**Issue by kelbren** [cmangos/issues#3113]
### Bug Details

Fresh build WotLK
Death Knight cast spell Death Gate, Death Gate is summoned properly, then right click to teleport and server crashes.

### Steps to Reproduce

1. Use Death Gate
2. Server crash
3.
4.

### Expected behavior

Teleport to Ebon Hold

### Core SHA1 Commit Hash

-0c9a7fe9c6d6b6cf8aed2e7c2bd125552ed5116b

### Database SHA1 Commit Hash

-667167d1ceb50e0864e308029cc48c1e72bf20d3

### Operating System

Ubuntu 20.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by MantisLord** [comment]
Not sure if anything changed, but the spell is working fine for me with no crash.
Cannot reproduce.

**Comment by kelbren** [comment]
Works now as it should. closing.
