### ISSUE TITLE
🐛 [Bug Report] Pathfinder Issue 

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#3115]
### Bug Details

There are occasional pathfinding problems in places with water.

https://youtu.be/kGS_IOlPXmQ

### Steps to Reproduce

1..go xyz -3604.20 -3155.82 30.733 1
2.Attack crocodile
3.
4.

### Core SHA1 Commit Hash

3a81d86d7eb0428b66c10d67a764eca05a3dca13

### Database SHA1 Commit Hash

667167d1ceb50e0864e308029cc48c1e72bf20d3

### Operating System

Ubuntu 20

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Nogemard** [comment]
Tbc has same issue i noticed a lot while leveling

**Comment by AnonXS** [comment]
Duplicate https://github.com/cmangos/issues/issues/2986
