### ISSUE TITLE
🐛 [Bug Report] Quests that should spawn NPC doesn't spawn them anymore

### ISSUE THREAD

**Issue by Pnumekin** [cmangos/issues#3116]
### Bug Details

When questing, events that should spawn NPC doesn't seem to work anymore, nothing is spawned.
In the example below, it's not possible to complete the quest as the item "Taelan's Hammer" has to be looted on a spawned NPC.
This quest (and NPC's spawn) was working 1 or 2 month ago, it seem to be broken since last update I made.
It seem to affect other quest's events, but haven't tested myself for others.

### Steps to Reproduce

1. Take quest : Of Forgotten Memories (https://classic.wowhead.com/quest=5781/of-forgotten-memories)
2. Open the pile of dust near to Tirion's grave at 28,86 in eastern Plaguelands

### Expected behavior

Mercutio Filthgorger and 3 Crypt Robbers should spawn, and after defeated them loot quest's objective Taelan's Hammer.

### Core SHA1 Commit Hash

34296b8b4ff72f9055bcc0791df06c1ccefb4ee2

### Database SHA1 Commit Hash

b673499ee74a862d7b7f236d2d88d354be3ae814

### Operating System

Ubuntu 20.04.4 LTS 5.4.0-124-generic

### Client Version

1.12.1 (Classic)

**Comment by Pnumekin** [comment]
As I had the problem with Classic I tried to apply your fix to src/game/OutdoorPvP/OutdoorPvPEP.cpp :

`    if (!source->IsGameObject())
       -return true;
      +return false;`

And it worked thank you :)

**Comment by killerwife** [comment]
I will resolve the other branches soon, but summer is keeping me a bit busy.
