### ISSUE TITLE
💬 [Support Request] Where can I download the client software for TBC 2.4.3 ?

### ISSUE THREAD

**Issue by danperor** [cmangos/issues#3117]
### Core Version

mangos-tbc

### Support Request Details

As we all know, wow official website no longer provides TBC download, so where can we download this client?

### Steps to Reproduce

1.none

### Core SHA1 Commit Hash

NA

### Database SHA1 Commit Hash

NA

### Server Operating System

NA

### Client Version

2.4.3 (The Burning Crusade)

### Client Operating System

windows

**Comment by insunaa** [comment]
We can't help with that, sorry. Closing.
