### ISSUE TITLE
🐛 [Bug Report] Shadow Word: Death backfire damage on Absorb

### ISSUE THREAD

**Issue by miraco** [cmangos/issues#3119]
### Bug Details

When a Priest uses Shadow Word:Death on someone and it gets fully absorbed, the backfire damage is also 0. Thats wrong, it should backfire the damage that got absorbed.

![Wow_dQau3wTCu4](https://user-images.githubusercontent.com/6261245/187423601-ca50f8e7-dfc2-46b8-9cb4-b828afef21e3.png)

### Steps to Reproduce

1. Use 1 Priest as Shadow and 1 as Disc for absorb shield.
2. Start duel
3. Use shadow word: death
4.

### Expected behavior

The Absorbed damage should be used for backfire damage.

https://youtu.be/PVRZKW4jwQo?t=330

If you slow down this video, you can see that the priest uses Shadow Word: Death and it gets absorbed but the caster still gets 515 damage (unit frame) as backfire damage.

### Core SHA1 Commit Hash

ffe2c85f8de53a3b6bc62092748c3acafc1f6e9a

### Database SHA1 Commit Hash

2f3b23e52c3b750d3aa5ab40b41e45e728046a76

### Operating System

Windows

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Resolved through linked PR.
