### ISSUE TITLE
🐛 [Bug Report] [WoTLK] [Warning] In BattleGround.cpp

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3120]
### Bug Details

/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGround.cpp: In member function ‘virtual void BattleGround::EndBattleGround(Team)’:
/home/mangos/cmangos/wotlk/src/game/BattleGround/BattleGround.cpp:1047:37: warning: comparison between ‘enum BattleGroundTypeId’ and ‘enum BattleGroundQueueTypeId’ [-Wenum-compare]
 1047 |     if (winmsg_id && GetTypeId() != BATTLEGROUND_QUEUE_AV)
      |                                     ^~~~~~~~~~~~~~~~~~~~~

### Steps to Reproduce

1. Update WoTLK
2. Compile 

### Expected behavior

To compile with waring

### Suggested Workaround

N/A

### Crash Log

N/A

### Core SHA1 Commit Hash

CMaNGOS-Core revision : 732b334c8070f1351c8ff1648dd709037f649024

### Database SHA1 Commit Hash

N/A

### Operating System

Ubuntu 20.04.3 Server LTS, Client Windows 7

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by adellaci** [comment]
This no longer show warning in the compile

**Comment by evil-at-wow** [comment]
Correct, this has been fixed last week with cmangos/mangos-wotlk@42cd6d0ed1bfad295206cea83bb3d9332f57c9d3.
