### ISSUE TITLE
🐛 [Bug Report] [WoTLK] [Warning] In CreatureEventAI.cpp

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3121]
### Bug Details

home/mangos/cmangos/wotlk/src/game/AI/EventAI/CreatureEventAI.cpp: In member function ‘void CreatureEventAI::InitAI()’:
/home/mangos/cmangos/wotlk/src/game/AI/EventAI/CreatureEventAI.cpp:198:16: warning: zero-length gnu_printf format string [-Wformat-zero-length]
  198 |         printf("");
      |                ^~

### Steps to Reproduce

1. Update WoTLK
2. Compile.

### Expected behavior

Compile without warning

### Suggested Workaround

N/A

### Crash Log

N/A

### Core SHA1 Commit Hash

CMaNGOS-Core revision : 732b334c8070f1351c8ff1648dd709037f64902

### Database SHA1 Commit Hash

N/A

### Operating System

Ubuntu 20.04.3 Server LTS, Client Windows 7

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by adellaci** [comment]
I haven't check in a while, but i did compile today and noticed that this Warning is gone.
CMaNGOS-Core revision : 27999d818ce8b308e30a24526b7705335d5b3dbc
WoTLK-Database revision : b276c0f5b99b0daaca23edd4117eac5c1f73c960

**Comment by evil-at-wow** [comment]
Your timing was excellent because I think this has been fixed only today in cmangos/mangos-wotlk@76fd793f14fe0471b97c9caea7588413b89ed07a!

**Comment by adellaci** [comment]
I am trying to go back through all the issues that i opened and see how many have been fix
