### ISSUE TITLE
🐛 [Bug Report] Curse of Recklessness PVP duration

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#3125]
### Bug Details
the duration is capped at 10 seconds against players
(tested on Smolderforge 2022-9-5)

### Expected behavior
should last for full 2 minutes against players
https://youtu.be/ayHyANB_1YQ?t=227
https://www.youtube.com/watch?v=znHBLg7aqy0

### Client Version
2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
https://www.youtube.com/watch?t=206&v=oo_vcsdBKXc&feature=youtu.be

**Comment by miraco** [comment]
https://github.com/cmangos/mangos-tbc/commit/469d110a6386bc72d6eef8f16391067deb9581c0 should have fixed this
