### ISSUE TITLE
🐛 [Bug Report] Mobs are moving back and forth after being pulled

### ISSUE THREAD

**Issue by Pnumekin** [cmangos/issues#3127]
### Bug Details

When pulling a mob, if you step back, it start to come to you, then go back to it starting point, then come to you, etc... It goes back and forth like this until you stop to stepback or go to his direction, then it only come to you.
I recorded a video as it could be more clear:
https://www.youtube.com/watch?v=R5wUZqusd4E

During this strange "dance" you can easily kite the mob and kill it without taking damage.

### Steps to Reproduce

1. Pull a mob
2. Step back
3. The mob is going back and forth
4. Walk in direction of the mob or stop stepping back
5. The mob is coming to you

### Expected behavior

The mob should come straight after the pull

### Core SHA1 Commit Hash

763e9b3cd92064b6eb0d43b1c3cd4ac3b7879688

### Database SHA1 Commit Hash

0ab946d03882f9751a781009bc92289288a452c2

### Operating System

Ubuntu 20.04.4 LTS 5.4.0-124-generic

### Client Version

1.12.1 (Classic)

**Comment by killerwife** [comment]
@cyberium this is the result of your straight path changes. Retest it if you do anything to it.

**Comment by kepheuswow** [comment]
@killerwife @cyberium I already reported this issue. See my recent comment here #3111.

**Comment by MilkmanMHOC** [comment]
Can anyone confirm that these are caused by the following changes?    https://github.com/cmangos/mangos-classic/compare/1a53b3148126...9c0a31b49697  

This seems to affect pets as well.

If anyone knows specifically which change broke it please let me know.  If not.. i guess i have a project for the weekend instead of playing games, cause its very anoying :P

**Comment by kelbren** [comment]
Wotlk has same issues, I think the changes August 16 is when this behavior started, but I am not completely certian. The mobs tend to run back and forth when running towards the attackers. This is true for pets,  as well.
It makes it much easier to kite mobs with the back and forth pathing.

**Comment by Pnumekin** [comment]
> Can anyone confirm that these are caused by the following changes? [cmangos/mangos-classic@1a53b31...9c0a31b](https://github.com/cmangos/mangos-classic/compare/1a53b3148126...9c0a31b49697)
> 
> This seems to affect pets as well.
> 
> If anyone knows specifically which change broke it please let me know. If not.. i guess i have a project for the weekend instead of playing games, cause its very anoying :P

I have restored these files to their state before the commit, and it fixed the problem with pathfinding. 
`src/game/MotionGenerators/PathFinder.cpp
src/game/MotionGenerators/RandomMovementGenerator.cpp
src/game/Entities/Object.cpp
`

**Comment by killerwife** [comment]
Appreciate the confirmation, if cyberium does not resolve it in a few weeks, I will try to do so, for now keeping it as is because he was doing smth last time he talked to me.

**Comment by betayi** [comment]
> 

and how to restore these ? it's a problem effect every second~~ save the world,pls~~

**Comment by MilkmanMHOC** [comment]
If you compiled the code your self, just replace the files mentioned, with pre aug 16th ones, and recompile.  It fixed it for me, and have been running fine since he posted last month.  If your using prebuild code, im unsure unless you still have a copy from before aug 16th 2022.  I don't think they keep the old builds on github?  Or if they do i don't know where they are?

**Comment by betayi** [comment]
> If you compiled the code your self, just replace the files mentioned, with pre aug 16th ones, and recompile. It fixed it for me, and have been running fine since he posted last month. If your using prebuild code, im unsure unless you still have a copy from before aug 16th 2022. I don't think they keep the old builds on github? Or if they do i don't know where they are?

yes,but where is the source file before the date which is used to replace?

**Comment by Pnumekin** [comment]
You can use github to get these files, check this link 
https://github.com/cmangos/mangos-classic/tree/1a53b3148126cd149505c4e0b6935155a59a4e5f

**Comment by betayi** [comment]
> You can use github to get these files, check this link https://github.com/cmangos/mangos-classic/tree/1a53b3148126cd149505c4e0b6935155a59a4e5f

Thanks ，bro ,works

**Comment by Szymplo** [comment]
Hey, are there any chances for early fix? It's really bad and many players complain. Game experience suffers greatly.

Currently having:
DB: cb2a4370c88f482f913997e093473e823cce1b9f
mangos-TBC: 8ee527d38dbf947492398f2feb05ceca7fd77fb

**Comment by insunaa** [comment]
Haven't seen the dev who made these changes for over a week now, I doubt this will get fixed soon. You can revert the changes on your own version for the time being

**Comment by Szymplo** [comment]
> Haven't seen the dev who made these changes for over a week now, I doubt this will get fixed soon. You can revert the changes on your own version for the time being

Thanks to Pnumekin, Betayi and Insunaa I managed to revert this bad change in files and still have up to date version of rest of code.
Nice to see monsters chasing players correctly again. Thanks!

**Comment by killerwife** [comment]
Pushed a commit to tbc branch, please test out its impact if possible. Linked it to this issue.

**Comment by Pnumekin** [comment]
I tried your patch on TBC an it fixed the problem, but there is still something strange. Mobs have problem with Z coordinate, they are moving on Z axis when walking on a non-flat floor. It looks like they are jumping when walking.
Maybe someone could confirm this behavior ?

**Comment by AnonXS** [comment]
example case? i only noticed this sort of glitching with spawn group formations.
and even better open a new issue for this. as the pingpong pathing is resolved as you said.

**Comment by Pnumekin** [comment]
Ok @AnonXS 
I didn't noticed the first time, but they go throught the map too.
Because a video is better here it is :)
https://youtu.be/npAGywuWHLI

**Comment by AnonXS** [comment]
and which mob is this? in this case it seems he's trying to get to a point very far away, hence a db mistake not core mistake.
commands like .npc info or .guid or anything would help.

**Comment by ckj777** [comment]
Not exact, but creature MovementType = 1 mobs keep moving in straight line somewhere in the same direction.

![20221107_111531](https://user-images.githubusercontent.com/44059601/200213067-1b23f64b-5764-404d-a5eb-9dfe88833d8c.png)

**Comment by AnonXS** [comment]
ah ok that relates to another issue i found and already forwarded to kw, i've spent my recent time in sunken temple so i can say, yes there is something strange going on with random movement, type 1.
but not with all mobs like you show in this pic.

**Comment by AnonXS** [comment]
Most recent commit made it worse and exactly like you discribe here.

**Problem is we're now fighting two different issues, one with random movement and one with Chase MovementGenerator as discribed in the issue head.**

![grafik](https://user-images.githubusercontent.com/19734826/200900612-13731639-a8d5-4255-978e-cea431bb47d3.png)

![grafik](https://user-images.githubusercontent.com/19734826/200900629-97218933-18d1-436e-b343-67c0592d74ca.png)

![grafik](https://user-images.githubusercontent.com/19734826/200900680-33a9b2e6-0859-4e55-851a-ae888b5f9a85.png)

![grafik](https://user-images.githubusercontent.com/19734826/200900718-807d715f-2f08-4461-9d3f-abed677c1bcd.png)

![grafik](https://user-images.githubusercontent.com/19734826/200900738-6932d321-cf21-4f9b-aef7-03030011760b.png)

![grafik](https://user-images.githubusercontent.com/19734826/200900783-1dec6d8f-5f1c-41c5-8f4c-81f282827d32.png)

Random Movement Mobs start glitching towards some imaginary escape point and from there they go back to their spawn location.

Reverting https://github.com/cmangos/mangos-tbc/commit/61ec769b0c9402c773a3dadbedac39effdad9df4 fixes this mass exodus.

**Comment by ssj17vegeta** [comment]
Tried to port the commit to mangos-wotlk to no avail (alas probably due to my meager knowledge of the project :( ). Mobs almost don't move when engaged.

Still, thanks to you @killerwife for working on this difficult issue.

XD Actually laughed out loud at the screenshots, the mobs are living their best lives !

**Comment by AnonXS** [comment]
doublecheck

**Comment by AnonXS** [comment]
Resolved
