### ISSUE TITLE
🐛 [Bug Report] the latest database release is 404 (TBC)

### ISSUE THREAD

**Issue by Jinsheng-Peng** [cmangos/issues#3128]
### Bug Details

https://github.com/cmangos/issues/wiki/Installation-Instructions

TBC → [forum](https://github.com/cmangos/tbc-db/issues) | [core repo](https://github.com/cmangos/mangos-tbc.git) | [database repo](https://github.com/cmangos/tbc-db.git) | [latest database release](https://github.com/cmangos/tbc-db/releases/tag/tbc-db_PreBuild) | [latest core release](https://github.com/cmangos/mangos-tbc/releases/tag/Last_mangos-tbc_PreBuild)

the [latest database release](https://github.com/cmangos/tbc-db/releases/tag/tbc-db_PreBuild) is 404

Excuse me, does anyone have this?  or fix it please，think you。

### Steps to Reproduce

1.none
2.
3.
4.

### Core SHA1 Commit Hash

-

### Database SHA1 Commit Hash

-

### Operating System

-

### Client Version

2.4.3 (The Burning Crusade)

**Comment by MantisLord** [comment]
Thanks for pointing this out.
I believe I've fixed the links here: https://github.com/cmangos/issues/wiki/Installation-Instructions/_compare/e824fff06f903793cdda5dfdab176af34a1132a0...3ff3368c72fdd1d5fb941edba64568f32cbafee9
