### ISSUE TITLE
🐛 [Bug Report] Hunter's Feign Death in some group link combat can not clear threat, Creature keep return In Combat

### ISSUE THREAD

**Issue by betayi** [cmangos/issues#3129]
### Bug Details

Hunter cast  Feign Death after aggro a group link creature（not all group）,then all creatures evade, but keep threat with hunter, after hunter stand up ,creatures will chase him. 

and

some creatures will evade back  and returen to combat again and again

### Steps to Reproduce

1.find a group of creatures that linked together (i tested in SunWell and Tempest Keep)
2.keep the range far enough and aggro any of them
3.cast Feign Death
4.watch creature's statue while they evade back
5.stand up and watch if the group chase you again
6,watch these creature's behaveir, some of they back and return again and again

### Expected behavior

clear group's threat after hunter cast Feign Death
creature should not back and return while in combat 

### Core SHA1 Commit Hash

3f3a2c04b47ff38a3ef615b77d3d64e715f9adca

### Database SHA1 Commit Hash

bc36ec312ce95327a981a174ed25411a1b872f85

### Operating System

unbuntu20.04

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
"(i tested in SunWell and Tempest Keep)"
provide test cases next time.
