### ISSUE TITLE
🐛 [Bug Report] MMAP - Tiles between water and shore are not connected

### ISSUE THREAD

**Issue by Lordron** [cmangos/issues#3139]
### Bug Details

.go 1561.7 -2181.7 92 1 There is a lake with broken patchfinding. Recast demo shows that upper part of the coast and lower (which is below water line) are not connected (gray gap). As you can see on this image path goes below ground. 

[First image](https://i.gyazo.com/9c574742a8f12d41322db5b838e4c373.png)

Once you load neighbor title 29 35 path goes above the water
[Second image](https://i.gyazo.com/1b4ef4b2d1e480e3635d5e6d09e1ac64.png)

I tried to adjust different settings in recast demo (slope angle from 20 to 90 degree), walkableHeight 1-10 and others to make them connect to each others but no luck. 

### Steps to Reproduce

1. log in, gm on
2. .go 1561.7 -2181.7 92 1
3. select any creature in water and .mmap path
4. see how weird path is. Also you can attack creature and verify that he will use this patch to get to you

### Core SHA1 Commit Hash

d8cdcf8621795edf9358a6988c1238fd8168ebb9

### Database SHA1 Commit Hash

bc36ec312ce95327a981a174ed25411a1b872f85

### Operating System

Windows 10 x64

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
https://github.com/cmangos/issues/issues/2986
