### ISSUE TITLE
🐛 [Bug Report] WSG - Cannot cap flag when enemy flag is dropped

### ISSUE THREAD

**Issue by henhouse** [cmangos/issues#3143]
### Bug Details

When your flag has been dropped the enemy team, it is not possible to cap theirs until it has been reset (either time out, or by return--which is currently bugged, see: https://github.com/cmangos/issues/issues/3142).

Screenshot:
![Screenshot at Sep 18 10-51-53](https://user-images.githubusercontent.com/30731/190894676-d63996bf-4f87-4a69-b59b-611fe67361ab.jpg)

### Steps to Reproduce

1. Pick up the flag on two characters, one horde, one Alliance
2. Kill or drop the flag on one character
3. Before it resets, try to cap the flag on the other. It will not capture
4. Wait for the flag to reset back to its base, then notice you can capture it.

### Expected behavior

It should be possible to capture a flag the moment it is dropped by the enemy team.

### Core SHA1 Commit Hash

a741e4dfb08460bcef0408bec2156b7d007a2954

### Database SHA1 Commit Hash

43a28ae92fa3c7f4168b3cc65b1525924a85f7d8

### Operating System

Linux (Ubuntu 20.04 LTS)

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
As msged on discord, i need evidence on this one

**Comment by AnonXS** [comment]
Proof.

**Comment by henhouse** [comment]
I believe I was wrong on this one. Meant to close earlier.

**Comment by celguar** [comment]
@henhouse do you mean it's fixed? I have similar reports

**Comment by henhouse** [comment]
> @henhouse do you mean it's fixed? I have similar reports

No, mean I think it was an invalid report. I asked a few friends who play a lot of BGs and they said the flag cannot be capped until the enemy's flag is returned, not just on the ground.

Maybe that's not right either, but I trusted that is was probably correct behavior and I was just confused.
