### ISSUE TITLE
🐛 [Bug Report] [WoTLK] Glyph of shadow has no effect

### ISSUE THREAD

**Issue by ssj17vegeta** [cmangos/issues#3148]
### Bug Details

The [Glyph of Shadow](https://www.wowhead.com/wotlk/item=42407/glyph-of-shadow) does not trigger its effect when a Shadow Priest crits with a non-periodic spell (Mind Blast, Mind Flay, Improved Devouring Plague...).

- No buff appears in the buff bar.
- No change in spell power when looking at the character stats.

Note : according to the glyph description, the priest must be in Shadow form.

### Steps to Reproduce

1. Have a Shadow priest using shadow form (tested on a level 41 shadow priest).
2. Cast Mind Blast and Mind Flay until it crits.
3. No buff should appear in the buff bar, and no change should occur in spell power.

```
Id: 74 (SPELL_EFFECT_APPLY_GLYPH)
BasePoints: 1
Targets: (0, 0) (TARGET_NONE, TARGET_NONE)
EffectMiscValueA: 262
ClassMask: 0x00000000 00000000 20000000
```
s.55689

### Expected behavior

A buff should appear, along with a spell power bonus (30% of spirit), see [Glyph of Shadow](https://www.wowhead.com/wotlk/item=42407/glyph-of-shadow).

### Core SHA1 Commit Hash

60927f8ee44c937d4f6759b4407b08f947a65d1d

### Database SHA1 Commit Hash

89009a1793350773a2cfc2fef2bb7bc2053e4cf6

### Operating System

Linux (Ubuntu Server 22.04)

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by ssj17vegeta** [comment]
Typing ".cast self 55689" on myself seems to fix the problem.

**Comment by insunaa** [comment]
Can you check in the database (character_glyphs table) whether your shadow priest character has the glyph with ID 262?
If it does then either this particular glyph is missing its assignment in DBC or we've got some very weird reason.

```cpp
void Player::ApplyGlyph(uint8 slot, bool apply)
{
    if (uint32 glyph = GetGlyph(slot))
    {
        if (GlyphPropertiesEntry const* gp = sGlyphPropertiesStore.LookupEntry(glyph))
        {
            if (apply)
            {
                CastSpell(this, gp->SpellId, TRIGGERED_OLD_TRIGGERED);
                SetUInt32Value(PLAYER_FIELD_GLYPHS_1 + slot, glyph);
            }
            else
            {
                RemoveAurasDueToSpell(gp->SpellId);
                SetUInt32Value(PLAYER_FIELD_GLYPHS_1 + slot, 0);
            }
        }
    }
}
```

I don't see how this code could fail to cast 55689 on the player.

If 262 is not present, then there might me some error in the spell that's responsible for adding the glyph

**Comment by ssj17vegeta** [comment]
Just checked the character_glyphs table for the character's guid as you asked, the glyph is there.

The content for the line : `spec = 0, slot = 3, glyph = 262`

Thanks for your answer :)

**Comment by insunaa** [comment]
Can't reproduce anymore. Buff shows up as expected, sp is increased by 30% of spirit.
