### ISSUE TITLE
🐛 [Bug Report] [WoTLK] Shadowform gives player incorrect model

### ISSUE THREAD

**Issue by ssj17vegeta** [cmangos/issues#3150]
### Bug Details

When logging in or changing zone with a Shadow Priest who has Shadowform activated, the player character has a "no texture" model ("chess squares" cube).

As soon as you remove the Shadowform, it's all good. You can activate it back, and the model is still good.

But as soon as you teleport somewhere, enter/leave a dungeon, or logout/relogin, it will revert back to the incorrect model.

Picture 1 shows the bug.
![Screenshot_20220923_014118](https://user-images.githubusercontent.com/734512/191869677-4a635d2e-3d03-4f84-882d-203c900bb045.png)

Picture 2 shows what happens when you deactivate/reactivate Shadowform ( aka the correct model for the player ).
![Screenshot_20220923_014150](https://user-images.githubusercontent.com/734512/191869784-80cbb314-062a-4936-8832-0943319a6d3f.png)

### Steps to Reproduce

1. With a Shadow Priest, activate Shadow form.
2. Change map somehow (teleport somewhere, enter/leave a dungeon, or logout/relogin).
3. The player model is incorrect.

### Expected behavior

It should always be like picture 2.

### Core SHA1 Commit Hash

60927f8ee44c937d4f6759b4407b08f947a65d1d

### Database SHA1 Commit Hash

89009a1793350773a2cfc2fef2bb7bc2053e4cf6

### Operating System

Linux (Ubuntu Server 22.04)

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by ssj17vegeta** [comment]
Additional information : changing your head item does not change the appearance of the character if you're already in shadowform.

**Comment by insunaa** [comment]
Tested and can't confirm. Possibly because you're using a modded client.
