### ISSUE TITLE
🐛 [Bug Report] TBC Using the item Ceremonial Incense in the quest Welcoming the Wolf Spirit will crash the server.

### ISSUE THREAD

**Issue by ckj777** [cmangos/issues#3151]
### Bug Details

Using the item Ceremonial Incense in the quest Welcoming the Wolf Spirit will crash the server.

Quest = https://tbc.wowhead.com/quest=10791/welcoming-the-wolf-spirit

https://www.youtube.com/watch?v=CI5mufg9Raw

### Steps to Reproduce

1.
2.
3.
4.

### Crash Log

 DB-SCRIPTS: WARNING: Process table `dbscripts_on_quest_start` id 10791, command 29 has no OTHER buddy 18384 found - maybe you need to update the script?
 DB-SCRIPTS: Process table `dbscripts_on_quest_start` id 10791, command 29 call for non-creature, skipping.
Attempt get value from nonexistent value field: 46 (count: 26) for object typeid: 5 type mask: 33
Critical Error: A condition which must never be false was found to be false. Server was shut down to protect data integrity.
If this error is occurring frequently, please recompile the software in debug mode to get more details.

Object::HasFlag(): index < m_valuesCount || PrintIndexError(index, false)

### Core SHA1 Commit Hash

eadc7634e55532721065abb0449e41bbdc91d394

### Database SHA1 Commit Hash

f44d449984de50d0c51a2f43a150652b74c0dcd1

### Operating System

Windows 10 x64

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Grz3s** [comment]
confirmed... 
script is very old... will redo it.. tomorrow.

**Comment by AnonXS** [comment]
Confirmed, this currently crashes the server. The underlying crash reason has to be prevented though, we can not have "old" dbscripts crash the server because they dont work anymore.
```
DB-SCRIPTS: WARNING: Process table dbscripts_on_quest_start id 10791, command 29 has no OTHER buddy 18384 found - maybe you need to update the script?
DB-SCRIPTS: Process table dbscripts_on_quest_start id 10791, command 29 call for non-creature, skipping.
```

**Comment by Grz3s** [comment]
are these errors showing up after my fix?

**Comment by ckj777** [comment]
tbc works fine with no errors

**Comment by AnonXS** [comment]
No befor
