### ISSUE TITLE
🐛 [Bug Report] Mage's blizzard channel procedure was break while any of target resist this spell

### ISSUE THREAD

**Issue by betayi** [cmangos/issues#3153]
### Bug Details

as title

### Steps to Reproduce

1.play a mage with blizzard spell
2.cast blizzard and make aoe damage to a group of higher level  training dummy
3.watch the channel out procedure while dummy resist
4.

### Expected behavior

the channel procedure of blizzard should not  broken if caster was not interrupted.

### Core SHA1 Commit Hash

5b67f0d564b6b10ead73dc993b367b98412e3b15

### Database SHA1 Commit Hash

3cf617027540746f66ac703d4ffb7bb3bd3df5ab

### Operating System

unbuntu20.04

### Client Version

2.4.3 (The Burning Crusade)

**Comment by aleigood** [comment]
Confirm that the problem exists.

**Comment by Patrick-Barry** [comment]
This is a problem on the classic core as well. I tested blizzard on air elementals in Silithus and each time I got a resist blizzard would stop casting.

Classic Commit: 6a869f148c482b551cf6778d1301867cd8cd7e7a

**Comment by betayi** [comment]
Been fixed by commit [https://github.com/cmangos/mangos-tbc/commit/9916fd4075c5ab21e77d27678d32ce69e4ccb6b2](url)

**Comment by betayi** [comment]
unfortunately, the fix commit in the upper url can not find any longer, and this problem is still stand

**Comment by insunaa** [comment]
can't confirm this on the latest core+db
![image](https://github.com/cmangos/issues/assets/3718129/fff6e584-4346-4f97-841b-17a687124e81)

**Comment by betayi** [comment]
thx,i will try with latest commit
