### ISSUE TITLE
🐛 [Bug Report] Shaman can not cast weapon spell to the off hand weapon

### ISSUE THREAD

**Issue by betayi** [cmangos/issues#3154]
### Bug Details

Shaman can not cast weapon spell such as (Frostbrand Weapon, Windfury Weapon,Flametongue Weapon,Rockbiter Weapon) to his off-hand weapon equipped on

### Steps to Reproduce

1.use a shamn of level 40 ,with talent of Dual Wield
2.equipped 2 one hand weapon such as item entry 852
3.learn 8033,8232,8024,8017
4.then cast this spell to the off-hand

### Expected behavior

spell should effect while off-hand was equipped 

### Core SHA1 Commit Hash

5b67f0d564b6b10ead73dc993b367b98412e3b15

### Database SHA1 Commit Hash

bc36ec312ce95327a981a174ed25411a1b872f85

### Operating System

unbuntu20.04

### Client Version

2.4.3 (The Burning Crusade)

**Comment by ssj17vegeta** [comment]
Works fine on recent WOTLK core though.

**Comment by insunaa** [comment]
In my testing it works fine in TBC when you do it for the first time, if offhand has no active enchant, but if you want to refresh the enchant in the offhand it always just enchants the mainhand instead

**Comment by ssj17vegeta** [comment]
@insunaa I may be wrong since it's been years, but isn't that the way it worked on retail ?

I remember right-clicking the buffs to get rid of it, and reapplying the weapon enchants.

**Comment by betayi** [comment]
i used a previouse version that without pathfinding problem ,it's the reason ,so i should close this fixed issue.
