### ISSUE TITLE
🐛 [Bug Report] 

### ISSUE THREAD

**Issue by left3721** [cmangos/issues#3159]
### Bug Details

ExtractResources.sh
......
......
Warning: Some models could not be extracted, see below
Could not find file of model World\Generic\Quilboar\Passive Doodads\Leantos\Razorfen_Leanto03.m2
A few not found models can be expected and are not alarming.

Extracting GameObject models...
Extracting World\Wmo\Band\Final_Stage.wmo
No such file World\Wmo\Band\Final_Stage.wmo.
Couldn't open RootWmo!!!
Warning: Some models could not be extracted, see below
Could not find file of model World\Dreaming\Passivedoodads\Flowers\Dreambellflower02.m2
Could not find file of model World\Expansion01\Doodads\Coilfang\Activedoodads\Energytower\Coilfang_Towers_E_Particle.m2
Could not find file of model World\Expansion01\Doodads\Hellfirecitadel\Demonwing\Passivedoodads\Summon_Door\Hellfire_Dw_Summondoor.m2
Could not find file of model World\Generic\Quilboar\Passive Doodads\Leantos\Razorfen_Leanto03.m2
A few of these warnings are expected to happen, so be not alarmed!
Done!

Extract for VMAPs05. Work complete. No errors.
./ExtractResources.sh: 255: Bad substitution

### Steps to Reproduce

1.
2.
3.
4.
![1](https://user-images.githubusercontent.com/21092101/193719733-14d75824-9622-4063-86c2-00c122957e3f.jpg)

### Core SHA1 Commit Hash

ef0b0eb97407bc0f857880c8509407cce0d18615

### Database SHA1 Commit Hash

ec06beaf071858822d55dca2a352b98cebd46ff5

### Operating System

ubuntu 20.4

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
Fixed by https://github.com/cmangos/mangos-classic/pull/492 or https://github.com/cmangos/mangos-wotlk/pull/400
