### ISSUE TITLE
🐛 [Bug Report] Quest: Investigate the Alchemist Shop

### ISSUE THREAD

**Issue by f0n1x** [cmangos/issues#3161]
### Bug Details

Summoning creatures works, able to fight them and capture them. However, attempting to loot the coffers has no effect and therefore is un-completeable.

### Steps to Reproduce

1.Create an Undead or Troll Mage.
2.Level to 15.
3.Acquire and complete the quest "Report to Anastasia" (questid: 1959)
4.Acquire the quest "Investigate the Alchemist Shop" (questid: 1960)
5.Pickup the items: Chest of Containment Coffers (itemid: 7247) and Cantation of Manifestation (itemid: 7308) located behind Anastasia (85,10)
6.Navigate to the area where you can summon the manifestiations ~(55,71)
7.Summon a manifestation by clicking the Cantation of Manifestation (itemid: 7308)
8.Defeat the manifestation then click on the Chest of Containment Coffers (itemid: 7247)
9.Attempt to loot

### Expected behavior

You should receive 1xFilled Containment Coffer (itemid: 7292) per kill/capture/loot.

### Core SHA1 Commit Hash

9098c0b44ff496e476b9f6bec6b551764b29a151

### Database SHA1 Commit Hash

8cb32b8a3f67fbf5bc545c277d6e19a62d30b0ba

### Operating System

Slackware64 15.0

### Client Version

1.12.1 (Classic)

**Comment by ClassicW** [comment]
I confirm, normally, the chest should appear on the ground for the loot but do nothing. This quest work correctly about 1 year ago.

**Comment by AnonXS** [comment]
```
bool Spell::OnCheckTarget(Unit* target, SpellEffectIndex eff) const
{
    switch (m_spellInfo->Id)
    {
        case 5246:                                          // Intimidating Shout
            if (eff != EFFECT_INDEX_0 && target == m_targets.getUnitTarget())
                return false;
            break;
        case 9082:                                          // Create Containment Coffer
            if (!target->HasAura(9032))
                return false;
            break;

```


```


void Spell::EffectDummy(SpellEffectIndex eff_idx)
{
                case 9012:                                  // Attract Rift Spawn
                {
                    if (!unitTarget || !unitTarget->HasAura(9032))
                        return;

                    unitTarget->CastSpell(unitTarget, 9010, TRIGGERED_NONE);
                    return;
                }
            ```

**Comment by f0n1x** [comment]
Retested (2023-07-04) and seems to be working properly as of
core: 1ffc3a574c5fb3611639f1990b9827536352c592
db: 5921c4b4363b224678425eb37789622c0a53c6e8
