### ISSUE TITLE
🐛 [Bug Report] Quest Vorsha the Lasher is not working properly

### ISSUE THREAD

**Issue by Erikbmd** [cmangos/issues#3162]
### Bug Details

Muglash npc id 12717 has some major pathfinding issues and quest 6641 get completed without killing Vorsha npc id 12940
also the mobs are just swimming in circles around the isle https://youtu.be/5Ck0UMAV1EU

### Steps to Reproduce

1. Do the quest 6641
2.
3.
4.

### Expected behavior

this is how the quest is supposed to work https://www.youtube.com/watch?v=Hua5mdj0vT0&t=67s

### Core SHA1 Commit Hash

68efdd78be509d170863b7b1c8bbe5ac19d03cd1

### Database SHA1 Commit Hash

e31bae92f2da33316ed9222c3725fcb5bd0f9e5c

### Operating System

Windows 10 21H2

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
c.12717 ,12940

i tested this recently, no problems with pathing through water/ into water / out of water. - tbc only as provided client version.
