### ISSUE TITLE
🐛 [Bug Report] TileAssembler.cpp internal compiler error: in compute_live_loop_exits, at tree-ssa-loop-manip.c

### ISSUE THREAD

**Issue by Jinsheng-Peng** [cmangos/issues#3165]
### Bug Details

ubuntu22
OpenSSL 1.1.1o
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0

`[ 14%] Building CXX object src/game/CMakeFiles/game.dir/vmap/TileAssembler.cpp.o
during GIMPLE pass: vrp
/home/tbc/LastDev/m20221008/src/game/vmap/TileAssembler.cpp: In member function ‘void VMAP::TileAssembler::exportGameobjectModels()’:
**/home/tbc/LastDev/m20221008/src/game/vmap/TileAssembler.cpp:334:10: internal compiler error: in compute_live_loop_exits, at tree-ssa-loop-manip.c:247
  334 |     void TileAssembler::exportGameobjectModels()
      |          ^~~~~~~~~~~~~
0xe3223b internal_error(char const*, ...)
        ???:0
0xe28d63 fancy_abort(char const*, int, char const*)
        ???:0**
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-11/README.Bugs> for instructions.
make[2]: *** [src/game/CMakeFiles/game.dir/build.make:9181: src/game/CMakeFiles/game.dir/vmap/TileAssembler.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:507: src/game/CMakeFiles/game.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
root@iZwz90lkgiu7ob0rfykl6vZ:/home/tbc/LastDev/m20221008_build# gcc --version
**gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0**
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@iZwz90lkgiu7ob0rfykl6vZ:/home/tbc/LastDev/m20221008_build# g++ --version
**g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0**
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@iZwz90lkgiu7ob0rfykl6vZ:/home/tbc/LastDev/m20221008_build# openssl version
**OpenSSL 1.1.1o  3 May 2022**
root@iZwz90lkgiu7ob0rfykl6vZ:/home/tbc/LastDev/m20221008_build# `

### Steps to Reproduce

1. I download the https://github.com/cmangos/mangos-tbc/releases/tag/latest，upload on 2022-10-8
2. Compile as usual

### Core SHA1 Commit Hash

latest

### Database SHA1 Commit Hash

latest

### Operating System

ubuntu22.04

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
There's a compiler bug in GCC 11. This is not an error in CMaNGOS code. The bug has been fixed by the GCC team upstream and the fix is present in newer versions of gcc.

If you are unable to acquire newer versions of gcc because you are using a point release linux distribution, which nobody should use: This bug is not present in the clang compiler and you can use clang instead of gcc to compile CMaNGOS.
