### ISSUE TITLE
🐛 [TBC-db] Questbug ID 9521

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3166]
### Bug Details

Quest ID 9521 (Report from the Northern Front) could not finished.

Deliver (23778/sentinel-luciels-report) to  (14733/sentinel-farsong) at Silverwing Grove.

But Sentinel Farsong dose not take the Quest to finish! 

Using enUS and deDE Client ... so all language versions seem to be affected

### Steps to Reproduce

1. Start Quest at (17287/sentinel-luciel-starwhisper) in Forestsong
2. Go to Silverwing Grove
3. Give Sentinel Farsong the Report! 

### Expected behavior

Finish the Quest, there are no more steps!

### Suggested Workaround

n/a

### Crash Log

n/a

### Core SHA1 Commit Hash

Built on Oct  7 2022 commit hash(68efdd78be509d170863b7b1c8bbe5ac19d03cd1) committed on 2022-10-05

### Database SHA1 Commit Hash

n/a developement build from same day as core

### Operating System

W10 x64 21h2

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Grz3s** [comment]
wotlk is free from it .. will leave it for @AnonXS

**Comment by AnonXS** [comment]
yea i deved on our classic branch and did updates for 14733, didnt see there is this runto quest added in tbc. will fix
