### ISSUE TITLE
💬 [Support Request] tbc-db-mysql-server Root Password

### ISSUE THREAD

**Issue by InTeL3D** [cmangos/issues#3167]
### Core Version

mangos-tbc

### Support Request Details

Hi guys,
i am using **mangos-tbc** with the standalone sql server.
Everything works fine but I would like to ask you how do I enter the sql server with the root password?
I'm using **tbc-db-mysql-server.zip (353 MB)** and I would need to be able to login in root mode to import / export tables and with default user mangos it is not possible.
Inside the **"start-server.bat"** it says that you can change the root password with the command **"mysql -uroot -e" SET PASSWORD = 'Your_Password'; "**, 
But unfortunately it doesn't work and I get this error: **"ERROR 1045 (28000): Access denied for user 'root' @ 'localhost' (using password: NO)"**
I'm using MySQL Workbench 8.0 CE on Windows 10 x64.
Thankyou

### Steps to Reproduce

1. Unzip **tbc-db-mysql-server.zip (353 MB)**
2. Double click **start-server.bat** (standalone sql server start)
3. Execute command for change root password **mysql -uroot -e "SET PASSWORD = 'Your_Password';"**
4. **"ERROR 1045 (28000): Access denied for user 'root' @ 'localhost' (using password: NO)"**

### Core SHA1 Commit Hash

0

### Database SHA1 Commit Hash

0

### Server Operating System

Windows 10 x64

### Client Version

2.4.3 (The Burning Crusade)

### Client Operating System

Windows 10 x64

**Comment by maikale** [comment]
I need that too

**Comment by insunaa** [comment]
Password should be `cmangos`

**Comment by InTeL3D** [comment]
> Password should be `cmangos`

Correct, thank you so much!

**Comment by AnonXS** [comment]
resolved
