### ISSUE TITLE
🐛 [Bug Report] TBC - Quest could not finischd and some strange pathnotes

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3170]
### Bug Details

2 quests are affected
- 5943/gizelton-caravan (Rigger)
- 5821/bodyguard-for-hire (Cork)

In both quests it is the player's task to escort the caravan through Desolace.

The caravan consists of
- 11625/cork-gizelton
- 11626/rigger-gizelton
- and 2 kodos

### Steps to Reproduce

1. Start Quests
2. Follow the NPC to escord
3. ... quest don't end ! There are no point where the Quest ist 100% compleet

At a certain point, the npcs run across the map and fly in the air: 

![grafik](https://user-images.githubusercontent.com/6404203/195189773-2dd68195-6529-4b3b-8550-371a5a8ad830.png)

### Expected behavior

100% compleet status of both quests

### Suggested Workaround

none ... the escord is endless or fail if player run away 

### Crash Log

none 

### Core SHA1 Commit Hash

68efdd78be509d170863b7b1c8bbe5ac19d03cd1

### Database SHA1 Commit Hash

development build

### Operating System

W10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
Core part is not merged, but yes some issues remain even with core part, which are part of the spawn_group.

https://github.com/cmangos/issues/issues/3072

**Comment by Ischtaratu** [comment]
These are just such things that are explicitly noticeable when playing.
One suggestion would be to make the caravan stationary and shorten the quest. Then the waypoints could be reinserted later. It's just not nice if the quest can't be completed because a script function doesn't run properly or something like that. Then a short hint in the quest text is enough.

**Comment by Ischtaratu** [comment]
First test:
Build 1.1.2023 Core & DB
Quest: 5821/bodyguard-for-hire => Works as intended !

Quest: 5943/gizelton-caravan => Does not work
you can start the quest and run back and forth between the two endpoints and nothing happens. No 100% quest complete ...

**Comment by AnonXS** [comment]
Can confirm, quest completion from the south quest was not triggering in my tests, the switchcase is insufficient.

**Comment by miraco** [comment]
Confirm, found the error and uploaded a pr that should fix the quest.

error was that the group goes into "normal" movement on point 19 at southside quest but quest finishs at point 21.
Point 19 is only for northside quest.

https://github.com/cmangos/mangos-tbc/pull/590

**Comment by Ischtaratu** [comment]
the caravan walks through the passage, then starts running but on an alternate route. Quest was not completed.
![WoWScrnShot_010723_141733](https://user-images.githubusercontent.com/6404203/211152754-35a29c5b-dd39-444b-8cf5-a15c943ce95b.jpg)

**Comment by miraco** [comment]
> the caravan walks through the passage, then starts running but on an alternate route. Quest was not completed.
> ![WoWScrnShot_010723_141733](https://user-images.githubusercontent.com/6404203/211152754-35a29c5b-dd39-444b-8cf5-a15c943ce95b.jpg)

After my change or without?

**Comment by Ischtaratu** [comment]
with the changes. Before, the NPCs stayed on the correct route, but all the time just walked. now they run and leave the road.

**Comment by AnonXS** [comment]
This also happened once while i tested with the initial pull request.
@Ischtaratu  he means have you manually applied https://github.com/cmangos/mangos-tbc/pull/590/files to test this?

**Comment by Ischtaratu** [comment]
no, I can't. I don't currently have a setup installed for development and compilation. 
I only use the daily precompiled packs from Github. Sorry for the confusion. My mistake.

**Comment by AnonXS** [comment]
Testing South Quest with this PR: https://github.com/cmangos/mangos-tbc/pull/590/files
![grafik](https://user-images.githubusercontent.com/19734826/211226702-b106beee-d24f-4418-9ad4-17e01d012666.png)

North Quest:

gizleton gives credit and they now move through the "town" - kw fixed this i think.
![grafik](https://user-images.githubusercontent.com/19734826/211226930-bbf2d722-2d5a-46bb-baf6-9139e3cded6a.png)
then they setup camp at the south location:
![grafik](https://user-images.githubusercontent.com/19734826/211227051-23ecb791-ab28-446b-b424-6d2ac1f337e2.png)

South Quest:

It takes quite a while befor they start moving after accepting.
There were no raid during the south escort, so script seems inactive, only pathing is active. no texts no credit nothing
No quest credit was given and the patrol moves back to quest north start point in walk mode.

![grafik](https://user-images.githubusercontent.com/19734826/211227918-f30f2d7a-599a-4eae-b862-f28c36ae63d1.png)

still bugged, but we're closing in on fixing it. they go now full loop, even if south quest is still bugged and only the waypoints work for it. (after reaccepting north quest, that one is broken too, they dont start moving)

![grafik](https://user-images.githubusercontent.com/19734826/211229233-de2a9643-86ae-4c4e-b878-14113872a5e8.png)

```
UPDATE `dbscripts_on_relay` SET delay = 10000 where delay IN (604000,615000,616000) AND id = '1162501'; -- reduce pause times
```

**Comment by AnonXS** [comment]
Please retest.

**Comment by miraco** [comment]
I retested this now, and found the error.  Mostly the open pr works, aslong you dont have done the other escort quest before.

End() doesnt stop the npc having escort state. i just did the north escort and when i try to start south escort i get the error:
`2023-03-09 20:29:28 <Scripting Library ERROR>: EscortAI attempt to Start while already escorting for npc_cork_gizelton.`

Still the movement (waypoint_path) gets changed thats why they move slowly to north camp.
Ill look and maybe find a solution for this

**Comment by miraco** [comment]
https://github.com/cmangos/mangos-tbc/pull/599

This commit + the other PR ( https://github.com/cmangos/mangos-tbc/pull/590/files ) should finaly fix it.
I will also add some db changes (mostly cosmetic fixes) and maybe update the other pr.

Edit: Tried it now for 10 times both working as intendent with both changes, will upload cosmetic changes now

**Comment by Ischtaratu** [comment]
confirmed for tbc ... both quests working and quest could be compleeted !

**Comment by AnonXS** [comment]
thank you for taking the time!
