### ISSUE TITLE
🐛 [Bug Report] ERROR 1136 (21S01) when initializing world database

### ISSUE THREAD

**Issue by linxiang-dev** [cmangos/issues#3171]
### Bug Details

I was following this guide: https://github.com/cmangos/issues/wiki/Installation-Instructions#initialize-world-database
And when I executed this SQL
`mysql -uroot -p classicmangos < mangos/sql/base/mangos.sql`
The error reported
`ERROR 1136 (21S01) at line 325: Column count doesn't match value count at row 1`

### Steps to Reproduce

1. freshly installed MySQL, no tables or databases exist
2. create empty databases `mysql -uroot -p < mangos/sql/create/db_create_mysql.sql`
3. execute `mysql -uroot -p classicmangos < mangos/sql/base/mangos.sql`
4.

### Expected behavior

The SQL should be executed with no error

### Core SHA1 Commit Hash

c149a0e87d4b432b1c6d6572149e971ef97132af

### Database SHA1 Commit Hash

8d108442839a56a4a4ab5cb979c6af509bfe0f30

### Operating System

Windows 11

### Client Version

1.12.1 (Classic)

**Comment by ellingtonsantos** [comment]
I just post a PR about this issue.

**Comment by insunaa** [comment]
Fixed in https://github.com/cmangos/mangos-classic/pull/494
