### ISSUE TITLE
🐛 [Bug Report] TBC: Zeppelin Debris under Water

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3175]
### Bug Details

Some Fishing Pools on the East-Coast of the Dustwallow Marsh ara under Water:

- 64,4 : 24,4
- 65,4 : 24,4

and so on ... all in near of sight. 7+ spots

They are all named as "Zeppelin Debris"

28116/zeppelin-debris

![grafik](https://user-images.githubusercontent.com/6404203/195650677-b559e3f0-a751-4d3e-98d5-439217307749.png)

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

68efdd78be509d170863b7b1c8bbe5ac19d03cd1

### Database SHA1 Commit Hash

dev build

### Operating System

W10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/195658967-99f737d4-d232-412b-9bdb-f913824ecedc.png)

https://tbc.wowhead.com/quest=11140/recover-the-cargo#videos:id=232250

invalid.
