### ISSUE TITLE
🚀 [Feature Request] Number of max Quest in QuestLog to *.conf

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3178]
### Feature Details

Redirect the definition of how many quest a player can have in questlog and how many daily quest a character can make to the server config mangosd.conf 

You can set when the daily quests are reset. Why not also the amount?

### Visualizations

...
Quest.Questlog.max = 25
Quest.Daily.max = 25
...

### Benefits and Purpose

Convenience and the possibility for server operators to adjust the value. 

### Core Versions

- [X] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
The amount of quests in questlog is tied to player fields of which there are 25 at most. You simply cannot have more. If you wanted more, thats not doable, if you wanted less and make it somehow restricted, thats possible.

**Comment by Ischtaratu** [comment]
Thank you for the explanation.

/closed
