### ISSUE TITLE
🐛 [Bug Report] Wrong NPC Flag 

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3179]
### Bug Details

Error on Serverstart:

"Table `creature_template` have creature (Entry: 7231) with vendor_id 326 but not have flag UNIT_NPC_FLAG_VENDOR (128), vendor items will ignored."

NPC 7231
https://www.wowhead.com/tbc/npc=7231/kelgruk-bloodaxe 

Store could be corrected by setting UNIT_NPC_FLAG_VENDOR, but also with UNIT_NPC_FLAG_TRAINER NPC could not be persuaded to become a trainer (trainer template 3002).

### Steps to Reproduce

On Serverstartup

### Expected behavior

no error

### Suggested Workaround

... make it right ! ;)

### Crash Log

n/a

### Core SHA1 Commit Hash

DevBuild 22.10.

### Database SHA1 Commit Hash

DevBuild 22.10.

### Operating System

W10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/17a3cf31400695968c8cf939aa14464ea3f58140
