### ISSUE TITLE
💬 [Support Request] Classic - 1 core constantly 100% for weeks now.

### ISSUE THREAD

**Issue by Daedalus-code** [cmangos/issues#3183]
### Core Version

mangos-classic

### Support Request Details

Support/Request/bugs
Not sure what this is.

### Steps to Reproduce

1. This started couple of weeks ago or more with latest updates. (something todo with LFG updates..I think)
2. 1 core constantly working.
3. Waiting to see if any new updates does anything to fix this.
4. Testing on other servers, same thing, 1 core constantly screaming.

![cpu_work](https://user-images.githubusercontent.com/59256533/197949292-334f4dd5-41ea-4f08-a92a-e67a7580fb27.jpg)

### Crash Log

Server never crashes.

### Core SHA1 Commit Hash

c99f4a8fd08b86b1a93dd31e8e0ca5ebedf375ee

### Database SHA1 Commit Hash

68c390c05e1bc7d012c9f777560a3de03a6e9235

### Server Operating System

Linux ubuntu 5.4.0-1073-raspi Ubuntu SMP PREEMPT Sat Oct 15 11:13:36 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### Client Version

1.1.12 (Classic)

### Client Operating System

Windows, MacOS

**Comment by olegabr** [comment]
Have same issue

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-classic/commit/2fcb19c183953d4391307054da0813903f2f3d51 this commit shouldve solved that. Update your core.

**Comment by olegabr** [comment]
Updated everything, built, but still 100% CPU

```
./mangosd -v
CMaNGOS Classic/0.18 (2022-10-14T18:20:30+02:00 - f459c47529d570dcf76a6136c32b7b8e48c9d174) for Linux_x64 (little-endian)
Boost version 10.71.0
```

```
git rev-parse HEAD
3ac791ab85a37a0035d7d8d71687ecd6b61553b0
```

This is a my fork merge commit (no changes from my side actually): https://github.com/olegabr/mangos-classic/commit/3ac791ab85a37a0035d7d8d71687ecd6b61553b0

cmake version 3.16.3

cmage flags:

` cmake ../mangos/ -DPCH=1 -DDEBUG=0 -DBUILD_PLAYERBOT=ON -DBUILD_EXTRACTORS=OFF -DCMAKE_INSTALL_PREFIX=/home/mangos/run -DBUILD_AHBOT=OFF -DBUILD_METRICS=OFF`

```
mysql --version
mysql  Ver 8.0.30-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
```

```
uname -a
Linux wow 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by olegabr** [comment]
The fix found: https://github.com/cmangos/mangos-classic/commit/419aef73150fc863c2f59b887a3b9eb51399a67e

Included in this PR by mistake: https://github.com/cmangos/mangos-classic/pull/495

**Comment by killerwife** [comment]
Noted, will adjust.
