### ISSUE TITLE
🐛 [Bug Report] vmap mmap

### ISSUE THREAD

**Issue by rezadxta** [cmangos/issues#3184]
### Bug Details

H! Guys
vmaps and mmap doesn't work

### Steps to Reproduce

upload vmap and mmap folder pls
ty

### Core SHA1 Commit Hash

#vmap #mmap

### Database SHA1 Commit Hash

#vmap #mmap

### Operating System

windows 10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
Please update the issue with details about what is not working and what you tried to get it working.
When/if you've added the required information I'll re-open the issue.
Closing.
