### ISSUE TITLE
🐛 [WOTLK]  Can't acces quest from NPC after switching phases

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3187]
### Bug Details

So the bug is that if u need to talk with a NPC between phases u can't.
If u use the command /reload all will get back to normal. But u need to use that command on every phasing change

So to test this:
1. get the quest  [Grand Theft Palomino] https://www.wowhead.com/wotlk/quest=12680/grand-theft-palomino"
2. Get the palomino from the farm
3. go back and U CAN'T COMPLETE  the quest. The npc won;t talk with u, U
4. Use /reload

1. Get next quest Into the realm of Shadows "https://www.wowhead.com/wotlk/quest=12687/into-the-realm-of-shadows"
2. Fight in the realm of shadows, get the deathchager
3. go back to Salanaar
4. use the horse spell 
5. get out of the realm of shadows
6. Try to talk with Salanaar U WON'T BE ABLE
7. use /reload. and all will work fine

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
also, if u kill a deathcharger raider, get the horse, and unmount it, and wish to attack an other deathcharger to get a new horse, u will not be able. u get near it, but u can't attack it

**Comment by Grz3s** [comment]
fixed

**Comment by al3xc1985** [comment]
will the commit come in the near days? Or should I try and it"s working @Grz3s ?
