### ISSUE TITLE
🚀 [Feature Request] Add SQLite database to database releases

### ISSUE THREAD

**Issue by gtker** [cmangos/issues#3196]
### Feature Details

# Goal

Make access to database contents easier for more people, and provide better grounds for long term archival.

# Reasoning

Currently the database projects ([classic-db](https://github.com/cmangos/classic-db/releases), [tbc-db](https://github.com/cmangos/tbc-db/releases), and [wotlk-db](https://github.com/cmangos/wotlk-db/releases)) releases include:

* SQL file to initialize the world server tables.
* SQL file to initialize all server tables.
* Windows version of MySQL with tables loaded.

I'm proposing adding a zipped SQLite file in addition to the other files for these reasons:

* Loading an SQLite database is significantly easier than standing up a MySQL database and loading from that which means that the database contents are available to more developers, and significantly less effort.
* The SQLite library has bindings in most languages and is easily embedded into statically compiled files. This means that even the lowest spec computing unit can probably load an SQLite DB.
* SQLite files are [recommended by the Library of Congress](https://www.sqlite.org/locrsf.html) for archival purposes, and [SQLite itself is supported through to 2050](https://www.sqlite.org/lts.html) and quite likely even further. This means that even if MySQL bitrots and is unable to load the SQL files, the SQLite database is very highly likely to still be accessible and be supported.

# Implementation

I have a [prototype of what I'm proposing in this repo](https://github.com/gtker/wow_db_sqlite) although the script is for Linux and has some additional overhead in `wget`ting the files from the `cmangos` repos first.

The general outline is to:

* Run [mysql2sqlite](https://github.com/dumblob/mysql2sqlite/tree/d14d22ad7029cdf4d11825ee3c96922e8fbb0122) on the already existing SQL files.
* Pipe that file into `sqlite3` and create a database.
* Compress the database and upload with other artifacts.

I would not mind taking a stab at this although [the build machines are Windows](https://github.com/cmangos/classic-db/blob/68c390c05e1bc7d012c9f777560a3de03a6e9235/.github/workflows/build-release.yml#L9) and I'm not super up to date on windows command line features.

### Benefits and Purpose

Better developer experience for users of the database contents, better long term archival.

### Core Versions

- [X] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
I've been slowly working on that, but the priority of this is really low, so don't expect this to happen any time soon

**Comment by gtker** [comment]
Cool, would you mind if I took a stab at it?

The way I see it the necessary changes for [wotlk-db](https://github.com/cmangos/wotlk-db/blob/master/.github/workflows/build-release.yml) are:

1. Download (or put the file in the repo?) [mysql2sqlite](https://github.com/dumblob/mysql2sqlite)
2. Download the [sqlite3 binaries for Windows](https://www.sqlite.org/download.html)
3. Download [awk](https://gnuwin32.sourceforge.net/packages/gawk.htm) (necessary for `mysql2sqlite`.
4. Run `mysql2sqlite` on all 4 .sql files, rename them to `${finalFullDBFolder}\${{env.WORLD_DB_NAME}}_sqlite.sql` instead of `${finalFullDBFolder}\${{env.WORLD_DB_NAME}}.sql`?
5. Import the files into an SQLite DB.
6. Zip up and upload like other files.

Does that seem like a reasonable approach?

**Comment by insunaa** [comment]
The problem isn't getting the database into an SQLite format, the problem is getting the server to interact with the SQLite database.
I don't mind if you do some SQLite conversions of the database, but that is probably by far the simplest task ahead of this feature

This mess here is our database code: https://github.com/cmangos/mangos-wotlk/tree/master/src/shared/Database

**Comment by gtker** [comment]
> the problem is getting the server to interact with the SQLite database.

Ah, yeah, I don't intend on doing that.

This issue is purely for having the DB repos have an SQLite DB in the release artifacts.

**Comment by gtker** [comment]
With the merging of https://github.com/cmangos/classic-db/commit/7d4ca499ed0a7aa10cf55367c87e1c8efc1a44d1 https://github.com/cmangos/tbc-db/commit/fd720ca65dd103aad9dd075b3cdc7800c8dde152 and https://github.com/cmangos/wotlk-db/commit/d703ff89fbba85cfd52c64e5e3d0346f983637f7 this issue has been fixed.

**Comment by insunaa** [comment]
@gtker Fully implemented loading SQLite databases https://github.com/insunaa/mangos-wotlk/tree/sqlite
tho currently this completely replaces the MySQL functionality. some work needs to be done to allow those to coexist
The branch currently *needs* to be built with meson as I couldn't be bothered to make it work with cmake, yet

**Comment by gtker** [comment]
@insunaa That's very impressive, but my issue was not about using SQLite in the emulators, only in exporting them as part of the database releases.

**Comment by insunaa** [comment]
yeah I know
