### ISSUE TITLE
🐛 [Bug Report] Scholomance Blood Steward of Kirtonos doesnt drop blood of innocents

### ISSUE THREAD

**Issue by Szymplo** [cmangos/issues#3197]
### Bug Details

We can't open door to basement with Jandice. We did it first time, we came to Scholomance but now we cannot. Blood Steward of Kirtonos doesnt drop Blood of Innocents. We tried to kill her 10 times with and without argent down reputation trinket. Blood of Innocents doesnt drop.

When we came first time with quests "Barov's Family Fortune" "Krastinov Bag of Horrors" we managed to get to basement. We did all bosses except one and got 3/4 deeds (all except deed to soutshore)because we didnt manage to kill Jandice). Few weeks later we tried again but now we cannot open door to basement because we can't get blood of innocents. All team is at same Quests progress 3/4 deeds

### Steps to Reproduce

1. Get 3/4 deeds (quest Barov's family fortune)
2. Logout and reset instance
3. Try to kill Blood Stewart to get blood of innocents
4. See that's undoable and door to basement remains closed

### Expected behavior

Blood Stewart of Kirtonos should drop Blood of Innocents which as i remember is necessary to open the basement door where Jandice hides.

### Suggested Workaround

Please check if quest progress doesnt affect it or maybe its something different but i dont know what. Some time ago i sent info about Uldaman (problem that door to last boss wont open even if we kill all golems) The similar thing happened here. For first time all worked fine, but we didnt finish quests. Now we are back and we cannot finish it and it affects our game experience ;)

### Core SHA1 Commit Hash

8ee527d38dbf947492398f2f5eb05ceca7fd77fb

### Database SHA1 Commit Hash

cb2a4370c88f482f913997e093473e823cce1b9f

### Operating System

Debian 11 with MariaDB

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Szymplo** [comment]
[tbc-db_REALM_s245501_v1.8.0_0604_2212292215.sql.gz](https://github.com/cmangos/issues/files/10322203/tbc-db_REALM_s245501_v1.8.0_0604_2212292215.sql.gz)
[tbc-db_CHAR_s245201_v1.8.0_0604_2212292215.sql.gz](https://github.com/cmangos/issues/files/10322204/tbc-db_CHAR_s245201_v1.8.0_0604_2212292215.sql.gz)
[tbc-db_LOGS_s243301_v1.8.0_0604_2212292215.sql.gz](https://github.com/cmangos/issues/files/10322205/tbc-db_LOGS_s243301_v1.8.0_0604_2212292215.sql.gz)

Hi
I attached my test DB Character, Realmd and Log Files
You may check it even in newer version of TBC server - for me it doesn't matter, it seems not to work in any version

Problems

There are our main accounts: szymon, natalia, magda, szczepan - all with password pandemia20
Now we cannot drop blood of innocents. We tried even to abandon and get again quest connected to Jandice
As i wrote at start - When we came first time to Scholomance - Everything worked. Now Blood of innocents never drops

The second problem is mentioned earlier by other players Uldaman. We cannot open door to last boss. We kill golems and three people clicking on thing and door won't open. When we first time did Uldaman it worked fine door opened but later we never didnt manage to do it again

The third problem is - player Eluwina from account Natalia cannot get Argent Dawn Commision quest. IMHO all prerequisites are met but Argent Officer Garush doesnt give her quest to get this item.

I will be happy if get help in any of these problems. I think first and second are connected with same thing (doors won't open for first time it worked - this looks simmilar)

I don't if my database is somehow corrupted or there is some kind of code-problem. But it may be something important in your project or maybe some kind of our fault - dunno.

Greetings and happy new year.

**Comment by AnonXS** [comment]
1. For Blood of Innocents to drop inside the dungeon, Quest ID 5384 Rewarded is the condition.

![grafik](https://user-images.githubusercontent.com/19734826/210073500-00fe7889-7df6-4cd5-a5a8-7df0ec486f56.png)
![grafik](https://user-images.githubusercontent.com/19734826/210073561-0444e7fa-a9d6-4a09-8063-c4930146b90a.png)
![grafik](https://user-images.githubusercontent.com/19734826/210073588-df8c4311-8693-4f4f-8b1c-98ff22f3af69.png)

Also provided onetime by completing quest chain at .go c id 11216

.q com 5382
.q com 5515

![grafik](https://user-images.githubusercontent.com/19734826/210073265-7608074e-c21d-4ca1-88b9-a436cf3d577e.png)

3. Argent Dawn Commission

![grafik](https://user-images.githubusercontent.com/19734826/210021970-546e3bf5-21bd-4380-8e21-de39d8935a2b.png)

https://github.com/cmangos/tbc-db/blob/e15944b890d0cdab9c852640c366edcaa98f5435/Updates/0328_CDB-0434_quest_template.sql#L46 - maybe the exclusive group. and the player has to get new one in EPL.

https://www.wowhead.com/tbc/quest=5401/argent-dawn-commission - alliance only at https://www.wowhead.com/tbc/npc=10840/argent-officer-pureheart
https://www.wowhead.com/tbc/quest=5405/argent-dawn-commission - horde only at https://www.wowhead.com/tbc/npc=10839/argent-officer-garush
https://www.wowhead.com/tbc/quest=5503/argent-dawn-commission - both at https://www.wowhead.com/tbc/npc=11039/duke-nicholas-zverenhoff

Which one does not work for Eluwina (Race?). maybe i added an edgecase by mistake. i'll play around keeping exclusive grp and removing some more complicated condition packing. but when i tested both with horde and alliance chars it worked, lets see.

edit:

-- 10856	Argent Quartermaster Hasana	3421
-- 10857	Argent Quartermaster Lightspark	3441
-- 11536	Quartermaster Miranda Breechlock	3461 these npcs give you the badge if you already did one of the quests and deleted the item.

---

Note:

Kirtonos the Herald flightpath entry is broken?
Kirtonos can be summoned multiple times in same dungeon.

**Comment by Szymplo** [comment]
OK so now I understand that i don't need the blood if Innocents to travel to Jandice because blood is connected to quest which is doable AFTER doin "Krastinov bag of Horrors"

When we first time came to Scholomance we did all bosses and wiped on Jandice. After that we tried to do it again but now the door is always closed and we dont know way to open it

Look at the screenshot - I marked closed door with red. On screenshot there is also minimap showing where it is.
![door_jandice_closed_again](https://user-images.githubusercontent.com/65982308/210117433-cc0e932b-c465-48ae-ad78-c2349cca0d99.png)

**Comment by AnonXS** [comment]
Door spawns open with state 1, animprogress 255 (wotlk sniff, confirmed with CCSDB), strangly enough changing this in db doesnt make the door spawn open (no visible core code that would alter the go state)
```
[456] GAMEOBJECT_FLAGS: 32/4.5E-44
[456] GAMEOBJECT_PARENTROTATION + 2: 1065352577/0.9999619
[456] GAMEOBJECT_PARENTROTATION + 3: 3155098040/-0.00872653
[456] GAMEOBJECT_DYNAMIC: 0/-1
[456] GAMEOBJECT_FACTION: 114
[456] GAMEOBJECT_BYTES_1: 1/0/0/255

later is closed, idk what event, maybe boss encounter, then reopened.

[0] UpdateType: Values
[0] GUID: Full: 0xF11002AE03000143 Type: GameObject Entry: 175619 Low: 323
[0] GAMEOBJECT_FLAGS: 33/4.6E-44
[0] GAMEOBJECT_BYTES_1: 0/0/0/255

add terminate condition? -> Script requested creature with entry 1853, but no npc of this entry was created yet, or it was not stored by script for map 289.
```

Changint state to supposedly open: 1 gives following result ingame while door is still permanently closed
```
Selected object: [Door] GUID: 2890020 ID: 175619
XYZ Map: 198.880005 180.593994 110.108002 289 Orientation: -1.553340
SpawnTime: Full:0s Remain:0s
Current State Information: GOState 1, LootState 1. Collision on, (door closed by default)
```

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/219094563-5cb8c3d2-eb63-4d2a-92e1-b161cac1bc8b.png)

open again after the gameobject_addon conversion.
