### ISSUE TITLE
🐛 [Bug Report] Classic - Oozing bags vanish when opened, no indication it can be opened.

### ISSUE THREAD

**Issue by Daedalus-code** [cmangos/issues#3198]
### Bug Details

![received_Oozing_bag](https://user-images.githubusercontent.com/59256533/199851972-5e6fc546-6ba6-490a-b519-0c1a11016d55.png)

Kill Glutinous Ooze mobs, get bag, no indication you can open it.

https://www.wowhead.com/classic/item=20768/oozing-bag

![Oozing_bag](https://user-images.githubusercontent.com/59256533/199851798-44239af2-f873-4f6d-be5a-ac8c3f6554c8.png)

Open it and its gone, no loot nothing, just vanished.

### Steps to Reproduce

1. Kill Glutinous Ooze mobs
2. Loot bag
3. Open bag
4. No profit, and its gone.

### Expected behavior

There should be junk and a pet I think.
Something.

### Crash Log

No crash.

### Core SHA1 Commit Hash

c99f4a8fd08b86b1a93dd31e8e0ca5ebedf375ee

### Database SHA1 Commit Hash

68c390c05e1bc7d012c9f777560a3de03a6e9235

### Operating System

Windows, MacOS

### Client Version

1.12.1 (Classic)

**Comment by AnonXS** [comment]
Can you provide some videos or something of somebody opening a few of these in classic?

https://www.youtube.com/watch?v=XzWjNy2TBwA&ab_channel=StudenAlbatroz - 1 item + silver per bag

https://www.wowhead.com/tbc/item=20766/slimy-bag
https://www.wowhead.com/tbc/item=20767/scum-covered-bag
https://www.wowhead.com/tbc/item=20768/oozing-bag

use whatever can be used from https://github.com/vmangos/core/commit/ab62382433a369ccc795739ac8f4295096c19e9f, very rarely 2 items per bag (herb + potion) mostly nothing but money

https://www.youtube.com/watch?v=SD7mBSbjE6w&ab_channel=DaveTheGamer
https://www.youtube.com/watch?v=37IM_kWPz1k&ab_channel=StudenAlbatroz
https://www.youtube.com/watch?v=vdfj2umZ8LY&ab_channel=BarakGage

**Comment by Daedalus-code** [comment]
> Can you provide some videos or something of somebody opening a few of these in classic?
> 
> https://www.youtube.com/watch?v=XzWjNy2TBwA&ab_channel=StudenAlbatroz - 1 item + silver per bag
> 
> https://www.wowhead.com/tbc/item=20766/slimy-bag https://www.wowhead.com/tbc/item=20767/scum-covered-bag https://www.wowhead.com/tbc/item=20768/oozing-bag
> 
> use whatever can be used from [vmangos/core@ab62382](https://github.com/vmangos/core/commit/ab62382433a369ccc795739ac8f4295096c19e9f), very rarely 2 items per bag (herb + potion) mostly nothing but money
> 
> https://www.youtube.com/watch?v=SD7mBSbjE6w&ab_channel=DaveTheGamer https://www.youtube.com/watch?v=37IM_kWPz1k&ab_channel=StudenAlbatroz https://www.youtube.com/watch?v=vdfj2umZ8LY&ab_channel=BarakGage

Yes, got one now and it worked, three first bags had nothing in them I guess.
And it stated it could be opened inside the bag.

**Comment by AnonXS** [comment]
This is a valid issue, just provide better sources in the future.

**Comment by Daedalus-code** [comment]
It is? 🤔 okey.
Should bags never be empty when opened?
Will try to make a video.

**Comment by AnonXS** [comment]
yes never empty, because there should be at least money.

**Comment by Daedalus-code** [comment]
And Classic?

**Comment by AnonXS** [comment]
There it is.
