### ISSUE TITLE
🐛 [Bug Report] Riding should not allowed in Deathmine Instance.

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3201]
### Bug Details

I discovered the error rather by accident. In the database under "instance_template" it is noted that riding is allowed on the map ID 36. This should not be correct. Especially since at this level no char should be able to own a mount. 

![grafik](https://user-images.githubusercontent.com/6404203/200169156-67eb2a78-2b44-44d5-85a8-6d25df496fa2.png)

This bug is included in all databases **Vanilla, TBC and WotLK**

### Steps to Reproduce

1.

### Suggested Workaround

UPDATE `instance_template` SET `mountAllowed`=0 WHERE `map`=36;

### Core SHA1 Commit Hash

DevBuild 04.11.2022

### Database SHA1 Commit Hash

DevBuild 04.11.2022

### Operating System

W10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Shouldnt it be possible to mount in the ship cavern? @Tobschinski

**Comment by Ischtaratu** [comment]
It would affect if then also only Chars, which are already overlevel. But even if they drag smaller chars through the instance they will hardly ride ahead ... it makes zero sense to me, if Blizzard should actually have intended so.

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/200178543-fd3aef35-33a4-4e2d-8ec6-ddd91fb55e1e.png)
thx hase

**Comment by killerwife** [comment]
I knew I was right :D
