### ISSUE TITLE
🐛 [WOTLK] Enchant Weapon - Blood Draining

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3203]
### Bug Details

https://www.wowhead.com/wotlk/spell=64579/enchant-weapon-blood-draining

So here is the thing: U get the buff on your weapon. It procs fenomenal. Very nice. BUT
When u get below 35% u get the life according to the number of stacks and it doesn't consume the stacks.

So u can bassically spam this heal passivly, only by healing with anything over 35% and get dmg back under 35% and u continue to heal back and forth 35% of your hp

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
should we open this ticket back?

**Comment by killerwife** [comment]
Just needs to be moved, should work fine alrdy.
