### ISSUE TITLE
🐛 [WOTLK] Paladin Talent - Ardent Defender

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3207]
### Bug Details

https://www.wowhead.com/wotlk/spell=31850/ardent-defender
https://www.wowhead.com/wotlk/spell=31851/ardent-defender
https://www.wowhead.com/wotlk/spell=31852/ardent-defender

The talent does not work anymore. It doesn't trigger anymore, no matter what u do

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
What about this talent doesn't proc anymore? The Heal or the damage reduction?

**Comment by insunaa** [comment]
OK nvm I just checked the core and there's literally no script for Ardent Defender at all in any way, shape or form.
Not for the heal, not for the reduced damage, nothing.

I'm gonna look into it later.
