### ISSUE TITLE
🐛 [WOTLK]  Vigilance of Collosus

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3208]
### Bug Details

![image](https://user-images.githubusercontent.com/6240049/202294232-11855895-67b2-427c-b71c-44c30bb6c76f.png)

The item
https://www.wowhead.com/wotlk/item=27529/figurine-of-the-colossus
use a heal on block, it can heal even for 3+ k . I don't think that is normal!

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
The heal should not scale with spellpower. Maybe that's the issue

**Comment by al3xc1985** [comment]
Yes

**Comment by insunaa** [comment]
```sql
update spell_template set AttributesEx6=134217728 where id=33090;
```
solves this for me, but it also seems to prevent the spell from critting. I believe it could heal critically, but I'm not sure

**Comment by al3xc1985** [comment]
yes, it might probably crit. BUT from 120 as the tooltip say and until 3k+ heal that is a thing

**Comment by AnonXS** [comment]
spellbonus?

**Comment by al3xc1985** [comment]
that is a good question, dunno

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/217707848-db99173a-4c5f-4062-b100-2aefcb7f3a14.png)

**Comment by al3xc1985** [comment]
that is good. It will be ported to wotlk db someday.
Ty
