### ISSUE TITLE
🐛 [Wotlk] Paladin - Sacred Shield damage absorbtion calculation

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3209]
### Bug Details

Sacred Shield does not have a good absorbtion calculation
https://www.wowhead.com/wotlk/spell=53601/sacred-shield
I am full t10 and 28x item level, and I only absorb 620 as seen in ss.
I also need to mention that I have 2002 SP

![image](https://user-images.githubusercontent.com/6240049/202299520-a63cc86d-b52d-45bf-bdbe-e5e3d02b9a7d.png)

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
https://youtu.be/8ZHlkVaWqHo?t=242

I found this video where it is seen that at this gear he has like 1.2k absorbtion dmg. The gear can be found on the beggining of the video

**Comment by al3xc1985** [comment]
https://www.wowhead.com/wotlk/spell=53601/sacred-shield#comments

There it is, I found that it should be SP coeficient around 75%

**Comment by insunaa** [comment]
tested and fixed at some point, don't know when.
