### ISSUE TITLE
🐛 [Bug Report]  cannot loot

### ISSUE THREAD

**Issue by wang460450180** [cmangos/issues#3210]
### Bug Details

If you pick up the LOOT at the farthest distance (within the allowable range), it is likely to cause the problem that you can't pick up the LOOT, which will lead to the inability of the following NPC to pick up the LOOT (you can get money), and the player will continue to squat down to pick up, die, and. start can't reset the effect. Only after you log in to the game again, the bug disappears

### Steps to Reproduce

1.Kill the monster
2.Pick LOOT at the farthest (allowed range)
3.It is likely that the list cannot be opened and the LOOT is not obtained
4.Picking logo turns grey (the same applies to future LOOT). The character is always in the status of picking LOOT, and can only get money but not LOOT
5.Death and. start cannot reset the effect
6.Login the game again and the effect disappears

### Expected behavior

Pick the loot normally

### Suggested Workaround

Maybe can reduce the scope of picking the root

### Crash Log

no

### Core SHA1 Commit Hash

ec1a1b330cee9016f94933dfee910aff46b5a91b

### Database SHA1 Commit Hash

Development Build(2022-11-17)

### Operating System

windows server 2019 datacenter

### Client Version

2.4.3 (The Burning Crusade)

**Comment by rnorden** [comment]
`Core SHA1 Commit Hash` missing. Log into the game on your running server and type `.server info`. Then you can see the commit hash of the core.

edit: `git rev-parse HEAD` is probably simpler and avoids some pitfalls (e.g. need for re-running cmake after you changed and committed core code...)

**Comment by wang460450180** [comment]
thank you sir ,i have updated iti

**Comment by wang460450180** [comment]
> thank you sir ,i have updated it

**Comment by wang460450180** [comment]
> `Core SHA1 Commit Hash` missing. Log into the game on your running server and type `.server info`. Then you can see the commit hash of the core.
> 
> edit: `git rev-parse HEAD` is probably simpler and avoids some pitfalls (e.g. need for re-running cmake after you changed and committed core code...)

thank you sir ,i have updated it

**Comment by aleigood** [comment]
It is confirmed that the same problem occurs frequently. The server does not have an exception log.
Using commit hash(b78d2de643a76510738788355bf39241be4cc54c) committed on 2022-11-11T01:28:36+00:00

**Comment by wang460450180** [comment]
thank you very much @killerwife
