### ISSUE TITLE
🐛 [Bug Report] No matter how far you go, you can't leave combat

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#3212]
### Bug Details

This is a new problem caused by yesterday's commit. I don't know which commit is the cause.
The problem is described in the title, In addition，players often have to wait 4 or 5 seconds to leave combat after the monster dies.

### Steps to Reproduce

1.Enter combat and go a little further.
2.
3.
4.

### Core SHA1 Commit Hash

01b98b1fa68016b7c68de3c998aebbfe1d154940

### Database SHA1 Commit Hash

96b94fbb54b12b642a5de569e45014caf91b578e

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by al3xc1985** [comment]
on wotlk, is the case yet. Cannot confirm it.
Maybe after backports we will encounter same problem

**Comment by al3xc1985** [comment]
I updated to latest core today, and I can't experience this bug

**Comment by aleigood** [comment]
In TBC delete this commit, it return normal.
https://github.com/cmangos/mangos-tbc/commit/f16a73a610e5c16bf7662a64f462c9863386fef5

**Comment by al3xc1985** [comment]
well I can confirm it now in wotlk

How to test?
Go to westfall as paladin, aggro a devil dust, use stun on him, and run
IT will follow u till the end of the world

**Comment by al3xc1985** [comment]
even thow I haven't done 1 single dmg on him, only stun, he followes me to eternity

**Comment by AnonXS** [comment]
Just to confirm that there is a tick timer for combat https://youtu.be/83zZkhGptK8?t=66

**Comment by kelbren** [comment]
I had similar issues after the COMBAT_MANAGER_TICK changes were added as part of the November 20th updates. my characters stay in combat mode long after combat is ended, sometimes 10-20 seconds, and mobs seem to stay in combat, and never leave it, I assume this is why they follow so far but I am just guessing from observation.

I did change the tick value to a lower amount  ~200 and that seemed to resolve it. but there may be other issues by making that change I am not aware of.

**Comment by killerwife** [comment]
I linked a commit that might change this issue.

**Comment by kelbren** [comment]
I tested the commit change in WotLK, combat and mobs seems to work properly again.  I assume it fixes the issue in the other cores as well. The combat timer drops combat almost immediately after combat now and mobs don't follow forever and return to their spot when out of range like I  expect.
Thank you! KW.

**Comment by aleigood** [comment]
Fixed.

**Comment by ClassicW** [comment]
It's been 1 month that it doesn't work on classic, thanks for thinking of us

**Comment by al3xc1985** [comment]
Not yet fixed at this moment in wotlk! @killerwife I believe is a matter a time until u port it?
