### ISSUE TITLE
🐛 [WOTLK] Deathbringer's Will - does not trigger

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3213]
### Bug Details

https://www.wowhead.com/wotlk/item=50362/deathbringers-will
The trinket does not work

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
Please describe this with more detail. What doesn't work about it? The transformation? How does the transformation not work? Are the stats applied but not the model?

**Comment by al3xc1985** [comment]
When I tested it, it didn't proc at all anything

**Comment by insunaa** [comment]
Been working on a fix for this issue but another issue has cropped up, related to system design. KW is looking into it at some point, but a fix is in the works.

**Comment by al3xc1985** [comment]
Well yeah, This kind of system fix, might fix some other problems too, that I didn't discovered

**Comment by insunaa** [comment]
Should be fixed in with this commit: https://github.com/cmangos/mangos-wotlk/commit/98127516ed268aacd8f15dea43b7684f5d80fdf7
Please test again @al3xc1985 
If you report no issues I'll close the issue tomorrow :)

**Comment by al3xc1985** [comment]
working! Nice! Ty
