### ISSUE TITLE
🐛 [Bug Report] Picking and mining will be attacked by neutral creatures

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#3217]
### Bug Details

![bug2](https://user-images.githubusercontent.com/3367999/203332922-49e9aa0d-08bd-4a43-a4f2-887e04bafb13.gif)

### Steps to Reproduce

1. Pick near neutral creatures
2.
3.
4.

### Core SHA1 Commit Hash

01b98b1fa68016b7c68de3c998aebbfe1d154940

### Database SHA1 Commit Hash

96b94fbb54b12b642a5de569e45014caf91b578e

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by miraco** [comment]
For mining that is blizzlike in tbc patch.
Confirmed on tbc classic that if you mine an ore nearby npcs will attack you.

**Comment by evil-at-wow** [comment]
Nearby NPCs in general, sure, but also neutral ones?

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/4ce22de705473700f95100dee56b757365b3b046

Adding neutral for now too, incase someone wants to provide evidence that neutrals also pull, be my friend.
