### ISSUE TITLE
🐛 [Bug Report] [Quest 198] Supplies to Private Thorsen

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#3222]
### Bug Details

The NPC Private Thorsen (738) can not complete the quest.

### Steps to Reproduce

1. .quest add 198
2..go cr id 738
3.
4.

### Core SHA1 Commit Hash

01b98b1fa68016b7c68de3c998aebbfe1d154940

### Database SHA1 Commit Hash

7991e5b928fbda10eae947f0d3f7aebdd3d9f3da

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by MilkmanMHOC** [comment]
Also have this problem on Classic, also i thought he was supposed to patrol but i have not seen him do so.

**Comment by miraco** [comment]
When did you talk to him? While he is standing in the camp or fighting in the jungle? 
iirc this is the npc that has an event (moving away from the camp fighting some npcs)

**Comment by insunaa** [comment]
This NPC walks and stands around for 30 minutes and at that time he only has some generic gossip. After 30 minutes a scripted event starts where he goes down the path from the camp in the direction of Kurzen's camp where he is intercepted by 2 of Kurzen's soldiers. If no players intervene then Thorsen is killed by these 2 soldiers and they eventually despawn (not sure if they have some special script text in that case). If a player intervenes and kills these 2 soldiers then Thorsen will get the quest flag and becomes a quest-giver. after ~3-5 minutes of standing at the site of the ambush as a quest giver he starts running back to the camp, the quest flag having been removed.

Edit: It is only possible to turn this quest in while he is *standing* inside the rebel camp. It's not possible during his patrols and during the event (until you saved him, then you can indeed turn it in). You should also be able to turn it in immediately after he runs back to camp, but before he starts his occasional patrols

^^^^^ this is how it's implemented on the reference at least and is the expected way Thorsen is handled.

**Comment by MilkmanMHOC** [comment]
This IS working as described above.  My apologies for miss understanding how the event was supposed to run and turn ins work.
