### ISSUE TITLE
🐛 [Bug Report] [Quest 6129] Little issue of Curing the Sick

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#3228]
### Bug Details

1. The Gazelle will not run after being cured.
![bug3](https://user-images.githubusercontent.com/3367999/204068357-d773f296-fcad-44d1-9988-cb05a30cac29.gif)

2. This has not about quest, by the way, all the gazelle can't run.
![bug2](https://user-images.githubusercontent.com/3367999/204068934-e55aaf4a-9614-42d8-8bc2-13213e4b0b98.gif)

### Steps to Reproduce

1. .add quest 6129
2. .go xyz -483.6137 -2441.1343 93.6832 1 
3. use Curative Animal Salve to Gazelle 
4.

### Expected behavior

https://youtu.be/GueoMd6UKSQ?t=167

### Core SHA1 Commit Hash

01b98b1fa68016b7c68de3c998aebbfe1d154940

### Database SHA1 Commit Hash

3efdb6e8fdec8d0e443907ddabdb3a0205ec13e6

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
-- Sickly Gazelle 12296 - spell_dummy_npc - Critter - on effect flee!

should work generically imo, unit is set in combat, unselectable

**Comment by aleigood** [comment]
I mean the gazelle should run away after being treated.

**Comment by Grz3s** [comment]
2. Theyre 6 packs of gazelles in Barrens.. Only 1 walks between stops  - all other runs normaly)

**Comment by Grz3s** [comment]
Fixed
