### ISSUE TITLE
🐛 [Bug Report] [Creature] Wrong spawn location

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#3229]
### Bug Details

DBGuid: 80600, It will sneak out of the ground to attack players.

![image](https://user-images.githubusercontent.com/3367999/204072303-2cf7f5a6-701e-49df-bcae-027a1589a901.png)

### Steps to Reproduce

1. go cr id 80600
2.
3.
4.

### Core SHA1 Commit Hash

01b98b1fa68016b7c68de3c998aebbfe1d154940

### Database SHA1 Commit Hash

3efdb6e8fdec8d0e443907ddabdb3a0205ec13e6

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
https://github.com/cmangos/issues/issues/3226 - PathFinder.NormalizeZ = 0!

Edit: Was not able to reproduce with PathFinder.NormalizeZ = 0, spawn xyz for this npc are correct / non corrupted.

**Comment by aleigood** [comment]
> 

Not the same problem, PathFinder NormalizeZ has been set to 0
