### ISSUE TITLE
🐛 [Bug Report] [Creature 16357] Speak use the wrong way

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#3230]
### Bug Details

![bug3](https://user-images.githubusercontent.com/3367999/204086064-16555d00-98b5-4f71-a41f-ba4fffc472ba.gif)

### Steps to Reproduce

1. Attack creature to about 5% of their HP.
2.
3.
4.

### Core SHA1 Commit Hash

01b98b1fa68016b7c68de3c998aebbfe1d154940

### Database SHA1 Commit Hash

3efdb6e8fdec8d0e443907ddabdb3a0205ec13e6

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
hmh not sure how i missed this, was sure i fixed ChatTypeId during development.
maybe i forgot to add it. will do so.
