### ISSUE TITLE
🐛 [WOTLK] Open Chests

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3232]
### Bug Details

Opening chests should trigger also critters in combat?

Cause every time I open a chest and a critter is  near the chest, I trigger that critter to combat!

Shouldn't this be an exception?

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
Should add https://github.com/cmangos/mangos-tbc/commit/e3f1b605c39506ba97500b9322a6b66fa63eb717 back to 
https://github.com/cmangos/mangos-tbc/blob/0c677b032e5307e33d2d3266e1739581fc9d0ac9/src/game/AI/ScriptDevAI/scripts/world/spell_scripts.cpp#L1142 i guess, also exclude neutral mobs.

**Comment by AnonXS** [comment]
Example Case?

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/4ce22de705473700f95100dee56b757365b3b046
