### ISSUE TITLE
🐛 [Bug Report] [Quest 5203] NPC will no longer attack enemies after wearing equipment

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#3233]
### Bug Details

1. NPC will no longer attack enemies after wearing equipment
2. After quest complete, NPC will run back to the hole and walk through the script again.

![bug3](https://user-images.githubusercontent.com/3367999/204141838-6b280b48-09ff-401f-9c21-e2a03ded262d.gif)

### Steps to Reproduce

1. .go cr id 11016
2. .additem 13140 and accept the quest from the key
3. complete the quest from NPC
4. accept a new quest from NPC and Take her away 

### Core SHA1 Commit Hash

01b98b1fa68016b7c68de3c998aebbfe1d154940

### Database SHA1 Commit Hash

3efdb6e8fdec8d0e443907ddabdb3a0205ec13e6

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
```
ServerToClient: SMSG_COMPRESSED_UPDATE_OBJECT (0x01F6) Length: 83 ConnIdx: 0 Time: 03/25/2009 03:05:13.000 Number: 249404
Count: 2
[0] UpdateType: Values
[0] GUID: Full: 0xF130002B0800A765 Type: Creature Entry: 11016 Low: 42853
[0] OBJECT_FIELD_ENTRY: 11018
[0] UNIT_FIELD_HEALTH: 5361
[0] UNIT_FIELD_MAXHEALTH: 5361
[0] UNIT_FIELD_FACTIONTEMPLATE: 250/3.5E-43 (250)
[0] UNIT_VIRTUAL_ITEM_SLOT_ID: 13316
[0] UNIT_FIELD_BOUNDINGRADIUS: 0.3366
[0] UNIT_FIELD_COMBATREACH: 1.6500001
[0] UNIT_FIELD_DISPLAYID: 10402
[0] UNIT_FIELD_NATIVEDISPLAYID: 10402
```

s.18163 - m_creature->UpdateEntry(NPC_ARKONARIN);

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/204143815-907012d8-633c-4acb-a1fd-38d3709313de.png)

**Comment by kelbren** [comment]
Tested on WotLK, once she gets her equipment and starts the walk out, she does not attack anything, and nothing attacks her.  Once she gets to the entrance, the quest is completed, but she does not run off and de-spawn properly, instead she runs back in to the start point, and the loop repeats if you follow her.
