### ISSUE TITLE
🐛 [Bug Report] [Quest 3367] Suntara Stones Missing some events

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#3240]
### Bug Details

NPC walks with his face on the ground. wrong path and missing some events.
![bug3](https://user-images.githubusercontent.com/3367999/204827570-53d93e3f-e5c3-43dc-b142-8409a566cfc6.gif)

### Steps to Reproduce

1. .go cr id 8284
2. accept the quest from Dorius Stonetender

 

### Expected behavior

NPC routes are different, and there are fewer interesting events. 

https://youtu.be/s8qTBCDPJIU

### Core SHA1 Commit Hash

9c7087d7b79d8ebdbb467c0d0de171e8084b9ed9

### Database SHA1 Commit Hash

979a559aa9a53fc39b7b30752a53858e22c7053d

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by maikale** [comment]
This is the exact escort data but he is lying on his face

DELETE FROM `script_waypoint` WHERE `Entry`=8284;
INSERT INTO `script_waypoint` (`Entry`, `PathId`, `Point`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `WaitTime`, `ScriptId`, `Comment`) VALUES
(8284, 0, 1, -7005.02, -1742.09, 234.09, 0, 3000, 0, 'stand up'),
(8284, 0, 2, -7007.01, -1730.48, 234.09, 0, 0, 0, ''),
(8284, 0, 3, -7004.89, -1726.50, 234.25, 0, 0, 0, ''),
(8284, 0, 4, -7000.51, -1727.69, 235.47, 0, 0, 0, ''),
(8284, 0, 5, -6989.39, -1737.25, 240.65, 0, 0, 0, ''),
(8284, 0, 6, -6976.65, -1737.33, 241.83, 0, 0, 0, ''),
(8284, 0, 7, -6954.92, -1742.04, 241.66, 0, 0, 0, ''),
(8284, 0, 8, -6933.73, -1730.35, 241.70, 0, 0, 0, ''),
(8284, 0, 9, -6931.64, -1719.75, 242.27, 0, 0, 0, ''),
(8284, 0, 10, -6909.71, -1714.02, 241.26, 0, 0, 0, ''),
(8284, 0, 11, -6898.56, -1723.56, 243.11, 0, 0, 0, ''),
(8284, 0, 12, -6883.09, -1728.15, 241.00, 0, 0, 0, ''),
(8284, 0, 13, -6879.24, -1737.66, 242.25, 0, 0, 0, ''),
(8284, 0, 14, -6875.63, -1738.84, 244.00, 0, 0, 0, ''),
(8284, 0, 15, -6868.03, -1745.78, 248.92, 0, 0, 0, ''),
(8284, 0, 16, -6865.56, -1747.40, 250.42, 0, 0, 0, ''),
(8284, 0, 17, -6857.70, -1748.29, 251.52, 0, 10000, 0, 'stop'), -- first stop
(8284, 0, 18, -6853.29, -1745.18, 251.52, 0, 0, 0, ''),
(8284, 0, 19, -6861.59, -1732.91, 251.66, 0, 0, 0, ''),
(8284, 0, 20, -6860.00, -1723.85, 252.05, 0, 0, 0, ''),
(8284, 0, 21, -6857.88, -1715.04, 251.52, 0, 0, 0, ''),
(8284, 0, 22, -6850.99, -1698.89, 250.48, 0, 0, 0, ''),
(8284, 0, 23, -6830.43, -1675.30, 251.52, 0, 0, 0, ''),
(8284, 0, 24, -6818.79, -1674.68, 251.31, 0, 0, 0, ''),
(8284, 0, 25, -6814.35, -1671.13, 250.31, 0, 0, 0, 'ambush'), -- second stop
(8284, 0, 26, -6809.37, -1680.91, 250.10, 0, 0, 0, ''),
(8284, 0, 27, -6801.58, -1695.83, 258.82, 0, 0, 0, ''),
(8284, 0, 28, -6790.76, -1703.73, 259.55, 0, 0, 0, ''),
(8284, 0, 29, -6781.22, -1715.15, 259.55, 0, 0, 0, ''),
(8284, 0, 30, -6778.56, -1727.06, 259.55, 0, 0, 0, ''),
(8284, 0, 31, -6777.09, -1744.06, 259.54, 0, 0, 0, ''),
(8284, 0, 32, -6775.59, -1761.05, 257.50, 0, 0, 0, ''),
(8284, 0, 33, -6777.40, -1780.64, 256.85, 0, 0, 0, ''), -- next break
(8284, 0, 34, -6776.03, -1781.77, 256.85, 0, 0, 0, ''),
(8284, 0, 35, -6728.56, -1814.42, 253.44, 0, 0, 0, ''),
(8284, 0, 36, -6700.18, -1814.54, 250.46, 0, 0, 0, ''),
(8284, 0, 37, -6677.81, -1821.25, 250.28, 0, 0, 0, ''), -- start run
(8284, 0, 38, -6640.54, -1884.70, 244.27, 0, 0, 0, ''),
(8284, 0, 39, -6612.79, -1916.98, 244.15, 0, 0, 0, ''),
(8284, 0, 40, -6569.94, -1922.81, 244.16, 0, 0, 0, ''),
(8284, 0, 41, -6540.13, -1938.87, 244.15, 0, 0, 0, ''),
(8284, 0, 42, -6520.90, -1946.45, 244.15, 0, 0, 0, ''),
(8284, 0, 43, -6504.90, -1955.36, 244.15, 0, 0, 0, ''),
(8284, 0, 44, -6483.21, -1965.20, 244.24, 0, 0, 0, ''),
(8284, 0, 45, -6471.10, -1968.55, 244.27, 0, 0, 0, ''),
(8284, 0, 46, -6451.37, -1976.94, 244.45, 0, 0, 0, ''),
(8284, 0, 47, -6405.94, -1974.30, 248.94, 0, 0, 0, ''),
(8284, 0, 48, -6395.49, -1977.74, 247.89, 0, 0, 0, ''),
(8284, 0, 49, -6389.20, -1978.71, 247.48, 0, 0, 0, ''),
(8284, 0, 50, -6388.39, -1983.85, 246.72, 0, 0, 0, ''),
(8284, 0, 51, -6388.39, -1983.85, 246.72, 0, 30000, 0, 'quest complete');

**Comment by AnonXS** [comment]
```
struct npc_dorius_stonetenderAI : public npc_escortAI

    void ReceiveAIEvent(AIEventType eventType, Unit* /*pSender*/, Unit* pInvoker, uint32 uiMiscValue) override
    {
        if (eventType == AI_EVENT_START_ESCORT && pInvoker->GetTypeId() == TYPEID_PLAYER)
        {
            // ToDo: research if there is any text here
            m_creature->SetStandState(UNIT_STAND_STATE_STAND);
            m_creature->SetFactionTemporary(FACTION_ESCORT_A_NEUTRAL_PASSIVE, TEMPFACTION_RESTORE_RESPAWN | TEMPFACTION_TOGGLE_IMMUNE_TO_NPC);
            Start(false, (Player*)pInvoker, GetQuestTemplateStore(uiMiscValue), true);
        }
    }
```
He should stand up on quest accept

He does for me:

![grafik](https://user-images.githubusercontent.com/19734826/205097845-bf51895c-5c41-440d-af70-88c5c4080da2.png)

Issue is that the Standstate is set DB side and restores on evade.

**Comment by maikale** [comment]
recovers on attack

**Comment by maikale** [comment]
End the mission in the middle of the escort

**Comment by AnonXS** [comment]
Credit is given at waypoint 34, npc has 51 points, not sure if we miss something.

![grafik](https://user-images.githubusercontent.com/19734826/205101758-65bbed6e-c9cf-4362-b882-2cf36f7290ad.png)
maybe missing script here.
![grafik](https://user-images.githubusercontent.com/19734826/205101833-696de8be-dd5e-47e3-9cf8-54b994314124.png)
related to missing event.
![grafik](https://user-images.githubusercontent.com/19734826/205101952-afe3c901-6faf-494d-9562-a80b8ea06d77.png)
![grafik](https://user-images.githubusercontent.com/19734826/205102355-8648991b-1aec-4a93-af7b-410cd968643d.png)

i guess ```SELECT * FROM gameobject where id IN (175704);``` should be a tempgo not a permaspawn. spawned by script on this escort.

**Comment by maikale** [comment]
> Кредитът се дава на пътна точка 34, npc има 51 точки, не сме сигурни дали пропускаме нещо.
> 
> ![графика](https://user-images.githubusercontent.com/19734826/205101758-65bbed6e-c9cf-4362-b882-2cf36f7290ad.png) тук може да липсва скрипт. свързан с нищощо събитие. ![графика](https://user-images.githubusercontent.com/19734826/205101833-696de8be-dd5e-47e3-9cf8-54b994314124.png) ![графика](https://user-images.githubusercontent.com/19734826/205101952-afe3c901-6faf-494d-9562-a80b8ea06d77.png) ![графика](https://user-images.githubusercontent.com/19734826/205102355-8648991b-1aec-4a93-af7b-410cd968643d.png)
> 
> предполагам, че `SELECT * FROM gameobject where id IN (175704);`трябва да е tempgo, а не permaspawn. породено от скрипт на този ескорт.



> Credit is given at waypoint 34, npc has 51 points, not sure if we miss something.
> 
> ![grafik](https://user-images.githubusercontent.com/19734826/205101758-65bbed6e-c9cf-4362-b882-2cf36f7290ad.png) maybe missing script here. ![grafik](https://user-images.githubusercontent.com/19734826/205101833-696de8be-dd5e-47e3-9cf8-54b994314124.png) related to missing event. ![grafik](https://user-images.githubusercontent.com/19734826/205101952-afe3c901-6faf-494d-9562-a80b8ea06d77.png) ![grafik](https://user-images.githubusercontent.com/19734826/205102355-8648991b-1aec-4a93-af7b-410cd968643d.png)
> 
> i guess `SELECT * FROM gameobject where id IN (175704);` should be a tempgo not a permaspawn. spawned by script on this escort.

now it works upright how to change the credit of 51 :)

**Comment by maikale** [comment]
It works fine from here https://github.com/vmangos/core/commit/f20750ec50701561058f48d006aa455775a7a078

**Comment by AnonXS** [comment]
> It works fine from here [vmangos/core@f20750e](https://github.com/vmangos/core/commit/f20750ec50701561058f48d006aa455775a7a078)

How do you know this works fine?
Did you import this to your cmangos?
Want to make a pull request porting this script?

**Comment by miraco** [comment]
i have it sniffed and will start reworking it in the next days. 
we have some missing rps here aswell.
