### ISSUE TITLE
🐛 [Bug Report] The water element summoned by the mage will be automatically changed to attack mode

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#3241]
### Bug Details

![bug3](https://user-images.githubusercontent.com/3367999/205205033-7a16326f-1961-448f-8251-5e3e4ce5b980.gif)

### Steps to Reproduce

1.Use the mage to learn the talent of summoning water element
2. Summon the Water Elemental near the monster.
3.
4.

### Core SHA1 Commit Hash

c66c9c063c50da779724962285b15aae2d4053bd

### Database SHA1 Commit Hash

ba4034a260c610edade5ef9cdf35e90424ef4651

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
This might be default behavior if you target a mob you can potentially attack yourself, PROVIDE PROOF THAT IT SHOULD NOT BE THIS WAY.
