### ISSUE TITLE
Unable to extract vmaps, mmaps

### ISSUE THREAD

**Issue by xhyanhao9** [cmangos/issues#3243]
### Core Version

mangos-wotlk

### Support Request Details

Unable to extract vmaps, mmaps

### Steps to Reproduce

1.ad
2.vmap_extractor
3.vmap_assembler
4.MoveMapGen.sh
5.ExtractResources.sh

### Crash Log

no

### Core SHA1 Commit Hash

no

### Database SHA1 Commit Hash

no

### Server Operating System

windows11

### Client Version

1.1.12 (Classic)

### Client Operating System

windows11

**Comment by evil-at-wow** [comment]
I'm afraid we'll need a bit more information here, like logs or the exact errors you're getting when you run commands.

Just so you're aware: you list 5 steps, but practically speaking you can do this:
1. Make sure 'BUILD_EXTRACTORS' is on when you build cmangos (```cmake -DBUILD_EXTRACTORS=ON ...```)
2. Run ExtractResources.sh

The ExtractResources.sh script should be creating log files (MaNGOSExtractor.log and MaNGOSExtractor_detailed.log by default), can you post what these log files contain please?

**Comment by xhyanhao9** [comment]
MaNGOSExtractor_detailed.log:
Sat Dec  3 16:24:57     2022: Start extracting MaNGOS data: DBCs/maps 1, vmaps 1, mmaps 1 using all CPU threads
MaNGOSExtractor.log:
Sat Dec  3 16:24:57     2022: Start extracting dataz for MaNGOS
DBC and map files will be extracted
Vmaps will be extracted
Mmaps will be extracted using all CPU threads

Sat Dec  3 16:24:57     2022: Start extraction of DBCs and map files...
Sat Dec  3 16:24:57     2022: Extracting of DBCs and map files finished

Sat Dec  3 16:24:58     2022: Start extraction of vmaps...

**Comment by xhyanhao9** [comment]
Client Version :  World of Warcraft Wrath of the Lich King 3.3.5a enGB

**Comment by insunaa** [comment]
So you say that you use the 1.12.x vanilla client but you want to extract WotLK maps, is that correct?

**Comment by evil-at-wow** [comment]
I believe it's all Wrath, the original post started with mangos-classic and the Classic client version, but it was edited (partly) to refer to cmangos-wotlk, and the extra comment mentions a Wrath client.

The logs are pretty strange. The last thing the logs mention is 'Start extraction of vmaps...' with nothing in the detailed logs. This is the relevant script fragment in the latest commit:
```
echo "$(date): Start extraction of vmaps..." | tee -a $LOG_FILE
  $PREFIX/vmap_extractor $VMAP_RES $VMAP_OPT_RES | tee -a $DETAIL_LOG_FILE
  exit_code="${PIPESTATUS[0]}"
  if [[ "$exit_code" -ne "0" ]]; then
    echo "$(date): Extraction of vmaps failed with errors. Aborting extraction. See the log file for more details."
    exit "$exit_code"
  fi
  echo "$(date): Extracting of vmaps finished" | tee -a $LOG_FILE
```

Ok, error output of the vmap_extractor is not ending in any log file, but normal output is, and so it should mention something even in case of errors (because the vmap_extractor is not properly splitting normal output and error output). This is clearly not the case, so it's like the vmap_extractor crashes early on, and then the script (hopefully) outputs that extraction failed with errors (but this is also not logged in any log files, it's only shown on the console).

Can you please edit the script contrib/extractor_scripts/ExtractResources.sh locally, add 'set -x' at the top after the line that says 'set -e' and try again please? That should echo all commands in your console and should hopefully reveal a bit more of what's going on. So to make it clear:

* Open contrib/extractor_scripts/ExtractResources.sh in a decent editor.
* Change lines 2-3 from
```
set -e
```
to
```
set -e
set -x
```
* Run the script again and copy/paste all output.

**Comment by Orcman2019** [comment]
I'm having the same problem running it on Linux Mint/Debian..  It seems like once it hits the vmaps part it complains the source is dirty and errors out with a double ./ExtractResources.sh /ExtractResources.sh [[ not found message.

Last output of the detailed log:

Processing Map 649
[################################################################]
Processing Map 650
[################################################################]
Processing Map 658
[################################################################]
Processing Map 668
[################################################################]
Processing Map 723
[################################################################]
Processing Map 724
[################################################################]

Extracting GameObject models...
Extracting World\Wmo\Band\Final_Stage.wmo
No such file World\Wmo\Band\Final_Stage.wmo.
Couldn't open RootWmo!!!
Warning: Some models could not be extracted, see below
Could not find file of model World\Detail\Drkbus02.m2
Could not find file of model World\Detail\Drkbus04.m2
Could not find file of model World\Dreaming\Passivedoodads\Flowers\Dreambellflower02.m2
Could not find file of model World\Dreaming\Passivedoodads\Flowers\Dreampurpleflower03.m2
Could not find file of model World\Dreaming\Passivedoodads\Flowers\Dreamspinningflower01.m2
Could not find file of model World\Expansion01\Doodads\Coilfang\Activedoodads\Energytower\Coilfang_Towers_E_Particle.m2
Could not find file of model World\Expansion01\Doodads\Hellfirecitadel\Demonwing\Passivedoodads\Summon_Door\Hellfire_Dw_Summondoor.m2
A few of these warnings are expected to happen, so be not alarmed!
Done!

Extract for VMAPs05. Work complete. No errors.
(The script then messes up and nothing else gets logged here)

It seems like the ad part and the vmap_extractor part runs then it dies horribly when it should be doing the vmap assembler.
I was able to run the vmap_assembler manually (./vmap_assembler buildings vmaps) and it ran but then running MoveMapGen.sh maps has emptied out the vmaps folder now. Not sure if the script itself is broken or one of the other binaries is doing something weird.

In addition the "pre-compiled" links for Windows Extraction if you built on *nix in that section of the wiki is missing all of the extractor binaries as well, making it pointless. It has both of the game client and login binaries and none of the extractor ones.

**Comment by evil-at-wow** [comment]
> It seems like the ad part and the vmap_extractor part runs then it dies horribly when it should be doing the vmap assembler.

That's very useful information @Orcman2019. Looking at the script again, I suspect the problem could be the ```${PIPESTATUS[0]}``` in the script after vmap_extractor ran (even though the original report doesn't seem to get that far judging by the logs posted).
I think that construct is not a portable POSIX shell thing, so it's going to depend on what /bin/sh actually is. I know some Linux distros symlink it to bash, so for those it should work out fine, but yours probably links it to something else. I don't run Mint/Debian but a quick google suggests Mint links it to dash, and the dash manual doesn't seem to mention PIPESTATUS. So I think we have a bit of work to make those scripts more portable...

**Comment by Orcman2019** [comment]
Hmm interesting.. that makes sense..

I googled a bit, ran sudo dpkg-reconfigure dash to no to use bash.. seems to be getting farther now.

Sun Dec 11 17:49:30 MST 2022: Start extracting dataz for MaNGOS
DBC and map files will be extracted
Vmaps will be extracted
Mmaps will be extracted using all CPU threads

Sun Dec 11 17:49:30 MST 2022: Start extraction of DBCs and map files...
Sun Dec 11 17:50:08 MST 2022: Extracting of DBCs and map files finished

Sun Dec 11 17:50:08 MST 2022: Start extraction of vmaps...
Sun Dec 11 17:51:30 MST 2022: Extracting of vmaps finished
Sun Dec 11 17:51:30 MST 2022: Start assembling of vmaps...
Sun Dec 11 17:52:21 MST 2022: Assembling of vmaps finished

Sun Dec 11 17:52:21 MST 2022: Start creating MoveMaps
Used params: --silent --configInputPath config.json --offMeshInput offmesh.txt
Detailed log can be found in MaNGOSExtractor_detailed.log

Sun Dec 11 20:49:51 MST 2022: Finished creating MoveMaps

**Comment by runningman98** [comment]
> 

shoud i use dash to replace bash shell to exec the Extractor.sh?

**Comment by runningman98** [comment]
stucked here... take so long for the vmaps processing...
14:40 > 14:48...
[https://keycloud.tk/index.php/s/d5kcZ3EFkfZ9HNY/download/Screenshot%202022-12-12%20at%202.48.39%20PM.png](https://keycloud.tk/index.php/s/d5kcZ3EFkfZ9HNY/download/Screenshot%202022-12-12%20at%202.48.39%20PM.png)

**Comment by insunaa** [comment]
Use `bash ./ExtractResources.sh`
The problem is Posix SH not Bash.

**Comment by runningman98** [comment]
> Use `bash ./ExtractResources.sh` The problem is Posix SH not Bash.

It is ok after change the sh to bash in line 1... then run ./ExtractResources.sh in Bash Shell

**Comment by John-Ivar-Flatmo** [comment]
Confirming i have this issue on classic TBC and wrath
needed to clean folders change bin/sh to bin/bash
someone wuld need to look into why its bin/sh maybe it was an accident cuz its working with bash
i also checked that the server accepts the generated files, its fine yeah

**Comment by Muehe** [comment]
> The problem is Posix SH not Bash.

This is a regression, POSIX compliance was ensured [a while back](https://github.com/cmangos/mangos-wotlk/pull/263).

Here are the errors:

```
shellcheck --severity=warning contrib/extractor_scripts/MoveMapGen.sh contrib/extractor_scripts/ExtractResources.sh

In contrib/extractor_scripts/MoveMapGen.sh line 106:
   while read map tile line
                       ^--^ SC2034 (warning): line appears unused. Verify use (or export if used externally).


In contrib/extractor_scripts/ExtractResources.sh line 147:
  if [[ ! -z $line ]]; then
     ^--------------^ SC3010 (warning): In POSIX sh, [[ ]] is undefined.


In contrib/extractor_scripts/ExtractResources.sh line 148:
    if [[ $line =~ ^[1-9+]$ ]]; then
       ^---------------------^ SC3010 (warning): In POSIX sh, [[ ]] is undefined.


In contrib/extractor_scripts/ExtractResources.sh line 255:
  exit_code="${PIPESTATUS[0]}"
             ^--------------^ SC3028 (warning): In POSIX sh, PIPESTATUS is undefined.
             ^--------------^ SC3054 (warning): In POSIX sh, array references are undefined.


In contrib/extractor_scripts/ExtractResources.sh line 256:
  if [[ "$exit_code" -ne "0" ]]; then
     ^------------------------^ SC3010 (warning): In POSIX sh, [[ ]] is undefined.


In contrib/extractor_scripts/ExtractResources.sh line 267:
  exit_code="${PIPESTATUS[0]}"
             ^--------------^ SC3028 (warning): In POSIX sh, PIPESTATUS is undefined.
             ^--------------^ SC3054 (warning): In POSIX sh, array references are undefined.


In contrib/extractor_scripts/ExtractResources.sh line 268:
  if [[ "$exit_code" -ne "0" ]]; then
     ^------------------------^ SC3010 (warning): In POSIX sh, [[ ]] is undefined.

For more information:
  https://www.shellcheck.net/wiki/SC2034 -- line appears unused. Verify use (...
  https://www.shellcheck.net/wiki/SC3010 -- In POSIX sh, [[ ]] is undefined.
  https://www.shellcheck.net/wiki/SC3028 -- In POSIX sh, PIPESTATUS is undefi...
```

**Comment by celguar** [comment]
You should use ExtractResources.sh, not files separately.
On windows I had to change first line of code to PREFIX="."

**Comment by AnonXS** [comment]
Seek immediate support on discord.

script / guide seems to need more attention.

**Comment by dravenlove** [comment]
I'm having the same issue.

Sun May 14 15:35:04     2023: Start extracting MaNGOS data: DBCs/maps 1, vmaps 1, mmaps 1 using 1 CPU threads

Map & DBC Extractor
===================

Extracting dbc files...
Extracted 0 DBC files

Extracting camera files...
Unable to open CinematicCamera.dbc. Camera extract aborted.
Extracting maps...
Read Map.dbc file... Fatal error: Invalid Map.dbc file format!

Extract for VMAPs05. Beginning work ....

Game path: Data\
Opening data files from data directory.
Scanning patch levels from data directory.

Opening Data\terrain.MPQ
Error opening archive 'Data\terrain.MPQ': Does file really exist?
Opening Data\model.MPQ
Error opening archive 'Data\model.MPQ': Does file really exist?
Opening Data\texture.MPQ
Error opening archive 'Data\texture.MPQ': Does file really exist?
Opening Data\wmo.MPQ
Error opening archive 'Data\wmo.MPQ': Does file really exist?
Opening Data\base.MPQ
Error opening archive 'Data\base.MPQ': Does file really exist?
FATAL ERROR: None MPQ archive found by path 'Data\'. Use -d option with proper path.

**Comment by dravenlove** [comment]
Sun May 14 15:35:04     2023: Start extracting dataz for MaNGOS
DBC and map files will be extracted
Vmaps will be extracted
Mmaps will be extracted using 1 CPU threads

Sun May 14 15:35:04     2023: Start extraction of DBCs and map files...
Sun May 14 15:35:04     2023: Extracting of DBCs and map files finished

Sun May 14 15:35:04     2023: Start extraction of vmaps...

**Comment by dravenlove** [comment]
if [ "x${CLIENT_PATH}" != "x" ]
then
  if [ ! -d "${CLIENT_PATH}/Data" ]
  then
    echo "Data folder not found in provided client path [${CLIENT_PATH}]. Plese provide a correct client path."
    exit 1
  fi
else
  if [ ! -d "$(pwd)/Data" ]
  then
    echo "Data folder not found. Make sure you have copied the script to the client folder and the 'Data' folder has the correct case."
    exit 1
  fi
fi

it looks like not mkdir Data.

**Comment by insunaa** [comment]
You need to copy the extractor tools into the WoW directory and run it there.

**Comment by dravenlove** [comment]
Does itneed something else as  dependencies.

**Comment by insunaa** [comment]
It needs all the files from the `tools` directory

**Comment by dravenlove** [comment]
I have not this directory,I reinstall it again,thank you bro.

**Comment by dravenlove** [comment]
i retry it, following the guide but i can't find the tools dirctory.

**Comment by insunaa** [comment]
The directory is literally the place where you found the ExtractResources.sh file in

**Comment by dravenlove** [comment]
If the directorynot exist,what can i check the reason. i compile all file successly by the vs2022.

**Comment by dravenlove** [comment]
and the cmake generate have not mistake.

**Comment by insunaa** [comment]
You used a file from the directory earlier, so where did you get that?

**Comment by dravenlove** [comment]
i ask my leader who build successly,the reason of the failure is that i have not install the client,sry.

**Comment by dravenlove** [comment]
thank you for you help.

**Comment by Daedalus-code** [comment]
Same issue, vmaps, mmaps missing after extracting :/ 
Linux Ubuntu, Classic.

**Comment by insunaa** [comment]
What is the output of your extractor script? How did you start your extractor script? What version of the client are you using?

**Comment by Daedalus-code** [comment]
> What is the output of your extractor script? How did you start your extractor script? What version of the client are you using?

For some reason it worked now, strange but awesome. 🥳
Thanks.

**Comment by xhyanhao9** [comment]
提取出来的是服务端用到的地图文件，目前我用的客户端是1.14.2（42597）
