### ISSUE TITLE
🐛 [Bug Report]Problem with quest Leave Nothing to Chance (12277) 

### ISSUE THREAD

**Issue by LeXXyrus** [cmangos/issues#3245]
### Bug Details

During the execution of the quest, the script does not work completely. After planting the bomb, the timer starts, but the explosion does not occur and the quest is not counted.

### Steps to Reproduce

1.Accept the quest Leave Nothing to Chance
2.Find and take dynamite
3.Place dynamite on marked places
4.Watch the countdown begin

### Core SHA1 Commit Hash

f097235feffa465baa0c2039763c48715092c119

### Database SHA1 Commit Hash

26ecb46be91a9afb91f852b9e0e616c14a1372b6

### Operating System

Ubuntu 18.04 x64

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Grz3s** [comment]
fixed:
https://github.com/cmangos/mangos-wotlk/commit/699c1aaa84caddefdfde00e7a7ae71debeb1ef3c
