### ISSUE TITLE
🐛 [Bug Report] 

### ISSUE THREAD

**Issue by klyxmaster** [cmangos/issues#3247]
### Bug Details

https://www.wowhead.com/quest=62/the-fargodeep-mine
Cannot complete quest. Missing coords.

### Steps to Reproduce

1. Go to designated spot to complete quest - nothing happens

### Expected behavior

Quest should complete once in the correct spot (to explore the cave)

### Suggested Workaround

```
/* 
	forgo mine quest #62
	add coords to it can be completed
*/
UPDATE `quest_template`
SET `PointMapId`='1', `PointX`='41.282', `PointY`='79.349'
WHERE (`quest_template`.`entry` = 62)
;
```

This will fix it and allow you to complete the quest.

### Core SHA1 Commit Hash

f097235feffa465baa0c2039763c48715092c119

### Database SHA1 Commit Hash

26ecb46be91a9afb91f852b9e0e616c14a1372b6

### Operating System

Windows 7

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Grz3s** [comment]
i see no issue ? credit is given in righ
![dwawd](https://user-images.githubusercontent.com/2374069/205467073-aa5dd9fc-6114-481f-bef3-690bb8c40801.jpg)
t place ...

+ source
https://youtu.be/7O1g-A8lU7U?t=148

**Comment by klyxmaster** [comment]
interesting. Only worked after I added the coords. However, glad it works either way.
