### ISSUE TITLE
🐛 [Bug Report] [Quest] The Ashenvale Hunt

### ISSUE THREAD

**Issue by aleigood** [cmangos/issues#3248]
### Bug Details

1. You can also take follow-up quests if you have not completed the previous quests, and players can still see the quest at level 70.
2. NPC should display question mark instead of exclamation mark before receiving quest(6383).

https://www.youtube.com/watch?v=gWvBf-YI5Z0&t=54s

### Steps to Reproduce

1. .quest add 742
2. .go cr id 12696
3. Talk to Senani Thunderheart and complete the quest
4. Accept the new quest

### Core SHA1 Commit Hash

c66c9c063c50da779724962285b15aae2d4053bd

### Database SHA1 Commit Hash

2b79a8e3e0c5e8039f72279442cac4898f2de12c

### Operating System

Ubuntu

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
These are the ashenvalue hunt breadcrumb quests, which you will normally only see one now in the world.

https://github.com/cmangos/tbc-db/blob/4d7927e752ffe2608cbedc3ae9050852bb1e5ef7/Updates/0487_breadcrumbquests.sql#L10
