### ISSUE TITLE
🐛 [Bug Report] quest10905

### ISSUE THREAD

**Issue by zhwblm** [cmangos/issues#3250]
### Bug Details

Task Potion Potion Conversion Master forgot that any one of the experts could not reset the task status, so they could not take other experts' tasks 

### Steps to Reproduce

1.After receiving the potion master task, forget this expertise and no other expertise tasks will be displayed
2.

```
.levelup 69
.learn 28596
.setskill 171 375
.go c id 17909 - no quest
.go c id 19052 - no quest
.go c id 22427 - no quest
```

https://www.wowhead.com/tbc/npc=19052/lorokeem#starts
https://www.wowhead.com/tbc/npc=17909/lauranna-tharwell
https://www.wowhead.com/tbc/npc=22427/zarevhi

3.
4.

### Core SHA1 Commit Hash

c66c9c063c50da779724962285b15aae2d4053bd

### Database SHA1 Commit Hash

2b79a8e3e0c5e8039f72279442cac4898f2de12c

### Operating System

win

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
you currently get the first quest from the outland alchemy trainer, which is correct, looking for "changing" later.

```
SELECT * FROM quest_template where entry IN (10905,10906,10902,10905,10897,10899,10907);
SELECT * FROM creature_questrelation where quest IN (10905,10906,10902,10905,10897,10899,10907);
```

![grafik](https://user-images.githubusercontent.com/19734826/206084192-d92dd289-6be5-48b1-9faa-712be1495032.png)

![grafik](https://user-images.githubusercontent.com/19734826/206084479-a2222e45-fb4d-4c45-afa6-4db35a8301cd.png)

![grafik](https://user-images.githubusercontent.com/19734826/206084495-00224429-8759-4f7c-bf98-0cc1f5c9837d.png)

![grafik](https://user-images.githubusercontent.com/19734826/206084548-9d02db7f-8348-4f0b-b509-c59fc153f329.png)

![grafik](https://user-images.githubusercontent.com/19734826/206084571-d46b3c39-fdbb-4a51-88ae-ccece5dffff9.png)

![grafik](https://user-images.githubusercontent.com/19734826/206084613-9fcf2374-7d7e-425f-829d-0ef1c3204dcf.png)

![grafik](https://user-images.githubusercontent.com/19734826/206084657-0637b3bf-bb0e-474c-9ede-9e5d97ac2f7f.png)

![grafik](https://user-images.githubusercontent.com/19734826/206084680-0f318a84-9b4b-40c5-9d94-f06d929ee6e3.png)

![grafik](https://user-images.githubusercontent.com/19734826/206084708-51c365fd-a57e-46b3-b9a5-72171d724e31.png)

![grafik](https://user-images.githubusercontent.com/19734826/206084829-e051f5d7-f9ba-4d17-9111-890afad3fed9.png)

![grafik](https://user-images.githubusercontent.com/19734826/206084734-6ae4a163-bdaf-419e-bfa2-7a8ff2413df1.png)

![grafik](https://user-images.githubusercontent.com/19734826/206084747-e58c752c-8825-45d2-a884-7cfc64103db3.png)

**Comment by zhwblm** [comment]
The first time is when you can receive a task and get a specialization reward after completing any one of the tasks. If you forget this, you will not be able to receive a task again. Normally, after I forget this, the three tasks will still show that I can accept them

**Comment by AnonXS** [comment]
if you accept one of the "go to x quests" the others go away, maybe should be breadcrumb quests?  https://www.wowhead.com/tbc/quest=10906/master-of-elixirs#comments:id=3001056

**Comment by zhwblm** [comment]
Normally, after you forget this specialization, you will reset the status of the three tasks. When you return to the place where you receive the first task, the three tasks will be displayed. But now you forget and have no tasks to receive

**Comment by AnonXS** [comment]
thats wrong though you can currently swap speccs as i showcased above. you just dont have to do the first part at the honorhold or thrallmar npc to go to the specc trainer.

**Comment by zhwblm** [comment]
Isn't it normal that I can take other tasks to learn other specialties after I choose to forget this specialty?

**Comment by AnonXS** [comment]
no task is required after you've done one of them, you can swap freely after you did one of the quests.

see: https://www.wowhead.com/tbc/quest=10906/master-of-elixirs#comments:id=3001061:reply=1262857

thats how it currently works.

**Comment by zhwblm** [comment]
Thank you. I'll test again

**Comment by AnonXS** [comment]
no more info provided.
