### ISSUE TITLE
🐛 [Bug Report] [Scholomance] Marduk Blackpool's Defiling Aura

### ISSUE THREAD

**Issue by marzipunk** [cmangos/issues#3253]
### Bug Details

I'm playing a level 60 character on a newly-compiled 2.4.3 cmangos server. In Scholomance, Marduk Blackpool (id 10433) has a Defiling Aura (spell id 17695). It is not supposed to affect player characters while he is neutral (he only becomes hostile if one of the mobs in his room is attacked) but it does. Its range is high and hits players through walls even when they're in the unnamed large room after the Chamber of Summoning or in the plagued whelp area. It causes the whole neutral room to become hostile and attack, pulling every mob in the next room (diseased ghouls, risen aberrations and reanimated corpses) with them

### Steps to Reproduce

1. Go to Scholomance, to the aforementioned room
2. Get close to Marduk on the other side of the wall, get hit by his Defiling Aura
3. Become overrun by a horde of undead

### Expected behavior

Marduk's aura should not affect players while he is neutral

### Suggested Workaround

I was able to fix this issue by reducing the aura's radius in the database (spell id 17697)

### Core SHA1 Commit Hash

c66c9c063c50da779724962285b15aae2d4053bd

### Database SHA1 Commit Hash

2b79a8e3e0c5e8039f72279442cac4898f2de12c

### Operating System

Windows 7 Max SP 1

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
In theory this spell should work as you say. It's only supposed to affect enemies in a radius of 30y. For some reason enemy seems to be interpreted as "attackable unit" here and I'm not sure if that's correct or if this spell needs a script to stop that behaviour

**Comment by AnonXS** [comment]
in sniffs he doesnt have the aura pre fight, resolved.
