### ISSUE TITLE
🐛 [Bug Report] Resonating Crystal Formation's all showing even though AQ event is not running

### ISSUE THREAD

**Issue by MilkmanMHOC** [cmangos/issues#3255]
### Bug Details

All the crystals for the AQ event are showing even though the event to spawn them is not running.  They seem to be a visual anomaly only in that they do no mind control or spawn any enemy's.  They are not intractable in anyway.  Their locations seem to all be correct to the event, just should not be visible if the event is not running. 

### Steps to Reproduce

1. Go to any of the locations where the Crystals can spawn and see they are there without any part of AQ activated. 
2.
3.
4.

### Expected behavior

They should not appear until the event to open the gate takes place.

### Core SHA1 Commit Hash

b0090e08faa5bae002e9898be272d42d80aa6919

### Database SHA1 Commit Hash

b36fa81f90348df3112739f24aec0f2c4d8fd8de

### Operating System

WIn7

### Client Version

1.12.1 (Classic)

**Comment by killerwife** [comment]
Gm off?

**Comment by MilkmanMHOC** [comment]
Shows either way, all players reported seeing them, so its not just me. :)

**Comment by AnonXS** [comment]
not sure how this happened as it was directly cherrypicked, even the `` are missing, maybe a search replace mistake on my end.

**Comment by MilkmanMHOC** [comment]
things happen!  Thanks for the quick fix!
