### ISSUE TITLE
🐛 [Bug Report] Segfault Linux install

### ISSUE THREAD

**Issue by Orcman2019** [cmangos/issues#3257]
### Bug Details

Not sure it's related to the extractors issue I had yesterday, that aspect seems to have run to completion with no errors by changing my default shell to bash.

2022-12-12 13:11:19 Loading CreatureEventAI Scripts...
2022-12-12 13:11:19 ERROR CreatureEventAI: Event 63401 Action 1 uses SpellID 5115 that must not target caster (target is 15). Resetting to TARGET_T_NONE.
2022-12-12 13:11:19 ERROR CreatureEventAI: Event 1586102 Action 1 uses nonexistent SpellID 20343.
2022-12-12 13:11:19 ERROR CreatureEventAI: Event 1636301 Action 3 uses nonexistent SpellID 19951.
2022-12-12 13:11:19 ERROR CreatureEventAI: Event 1636302 Action 3 uses nonexistent SpellID 19951.
2022-12-12 13:11:19 ERROR CreatureEventAI: Event 1693903 Action 1 uses SpellID 34239 that must not target caster (target is 15). Resetting to TARGET_T_NONE.
2022-12-12 13:11:19 ERROR CreatureEventAI: Event 1940801 Action 1 uses SpellID 34086 that must not target caster (target is 15). Resetting to TARGET_T_NONE.
2022-12-12 13:11:19 ERROR CreatureEventAI: Event 2105801 Action 1 uses SpellID 36004 that must not target caster (target is 15). Resetting to TARGET_T_NONE.
2022-12-12 13:11:19 ERROR CreatureEventAI: Event 2359702 Action 1 uses SpellID 43249 that must not target caster (target is 15). Resetting to TARGET_T_NONE.
2022-12-12 13:11:19 >> Loaded 26136 CreatureEventAI scripts
2022-12-12 13:11:19
2022-12-12 13:11:19 Initializing Scripting Library...
2022-12-12 13:11:19   _____           _       _   _____
2022-12-12 13:11:19  / ____|         (_)     | | |  __ \
2022-12-12 13:11:19 | (___   ___ _ __ _ _ __ | |_| |  | | _____   __
2022-12-12 13:11:19  \___ \ / __| '__| | '_ \| __| |  | |/ _ \ \ / /
2022-12-12 13:11:19  ____) | (__| |  | | |_) | |_| |__| |  __/\ V /
2022-12-12 13:11:19 |_____/ \___|_|  |_| .__/ \__|_____/ \___| \_/
2022-12-12 13:11:19                    | |
2022-12-12 13:11:19                    |_| http://www.cmangos.net
2022-12-12 13:11:19 SD2: Loading Script Texts...
2022-12-12 13:11:19 Loading texts from script_texts, with additional data
2022-12-12 13:11:19 >> Loaded 4716 text templates from script_texts
2022-12-12 13:11:19
2022-12-12 13:11:19 SD2: Loading Custom Texts...
2022-12-12 13:11:19 Loading texts from custom_texts, with additional data
2022-12-12 13:11:19
2022-12-12 13:11:19 >> Loaded 0 string templates. DB table `custom_texts` is empty.
2022-12-12 13:11:19 SD2: Loading Gossip Texts...
2022-12-12 13:11:19 Loading texts from gossip_texts
2022-12-12 13:11:19 >> Loaded 150 string templates from gossip_texts
2022-12-12 13:11:19
2022-12-12 13:11:19 SD2: Loading Script Waypoints for 121 creature(s)...
2022-12-12 13:11:19
>> Loaded 4686 Script Waypoint nodes.
2022-12-12 13:11:19 SD2: Loading C++ scripts

2022-12-12 13:11:19
2022-12-12 13:11:19 Loading spell scripts...
2022-12-12 13:11:19 >> Loaded 1306 C++ Scripts.
2022-12-12 13:11:19 Initialize game time and timers
2022-12-12 13:11:19 Starting Outdoor PvP System
2022-12-12 13:11:19 >> Loaded 8 Outdoor PvP zones
2022-12-12 13:11:19
2022-12-12 13:11:19 Starting Map System
(Segmentation fault)

Dec 12 13:06:14 DellWrath kernel: [56193.720047] traps: mangosd[25099] general protection ip:560392064ca0 sp:7f78315df6c0 error:0 in mangosd[560391449000+1632000]
Dec 12 13:06:14 DellWrath systemd[1]: Started Process Core Dump (PID 25102/UID 0).
Dec 12 13:06:28 DellWrath systemd-coredump[25103]: Process 25093 (mangosd) of user 1001 dumped core.#012#012Stack trace of thread 25099:#012#0  0x0000560392064ca0 n/a (/home/cmangos/mangos/run/bin/mangosd)
Dec 12 13:10:38 DellWrath kernel: [56457.699171] traps: mangosd[25750] general protection ip:56415c80aca0 sp:7f35215df6c0 error:0 in mangosd[56415bbef000+1632000]
Dec 12 13:10:38 DellWrath systemd[1]: Started Process Core Dump (PID 25753/UID 0).
Dec 12 13:10:50 DellWrath systemd-coredump[25754]: Process 25744 (mangosd) of user 1001 dumped core.#012#012Stack trace of thread 25750:#012#0  0x000056415c80aca0 n/a (/home/cmangos/mangos/run/bin/mangosd)
Dec 12 13:11:20 DellWrath kernel: [56499.378272] traps: mangosd[25768] general protection ip:56054bb3aca0 sp:7f7970dde6c0 error:0 in mangosd[56054af1f000+1632000]
Dec 12 13:11:20 DellWrath systemd[1]: Started Process Core Dump (PID 25771/UID 0).
Dec 12 13:11:36 DellWrath systemd-coredump[25772]: Process 25762 (mangosd) of user 1001 dumped core.#012#012Stack trace of thread 25768:#012#0  0x000056054bb3aca0 n/a (/home/cmangos/mangos/run/bin/mangosd)

Dec 12 13:06:14 DellWrath kernel: [56193.720047] traps: mangosd[25099] general protection ip:560392064ca0 sp:7f78315df6c0 error:0 in mangosd[560391449000+1632000]
Dec 12 13:10:38 DellWrath kernel: [56457.699171] traps: mangosd[25750] general protection ip:56415c80aca0 sp:7f35215df6c0 error:0 in mangosd[56415bbef000+1632000]
Dec 12 13:11:20 DellWrath kernel: [56499.378272] traps: mangosd[25768] general protection ip:56054bb3aca0 sp:7f7970dde6c0 error:0 in mangosd[56054af1f000+1632000]

### Steps to Reproduce

1.
2.
3.
4.

### Expected behavior

Should run at least for a while I'd think

### Core SHA1 Commit Hash

938bda7ee62be41d6567fc7dd7f8b3a7fb27c54c

### Database SHA1 Commit Hash

b17cdeffa2d280b4e483ce86c197bd6700c79028

### Operating System

Linux Mint Tina/Debian Bionic

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
check if your mangosd is linked against openssl 3.0 or openssl 1.1
`ldd mangosd`

**Comment by Orcman2019** [comment]
cmangos@DellWrath:~/mangos/run/bin$ ldd mangosd
```
        linux-vdso.so.1 (0x00007ffd28a46000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc621c89000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fc6217be000)
        libmysqlclient.so.20 => /usr/lib/x86_64-linux-gnu/libmysqlclient.so.20 (0x00007fc6211f1000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc620fed000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc620c64000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc6208c6000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc6206ae000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc6202bd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc623806000)
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fc620030000)
```

**Comment by insunaa** [comment]
ok, you're linking against 1.1 apparently

nominally I'm linking against 3.0, but in the linker commands I'm linking against 1.1, very confusing.

```
	linux-vdso.so.1 (0x00007ffddcba6000)
	libmariadb.so.3 => /usr/lib/libmariadb.so.3 (0x00007fd796b1a000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fd796a32000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007fd796a18000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fd794e00000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fd7951e0000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fd794c19000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fd796bbf000)
	libssl.so.3 => /usr/lib/libssl.so.3 (0x00007fd795140000)
	libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007fd794600000)
```
can you check if other versions of the openssl libs are available for your OS?

**Comment by Orcman2019** [comment]
Might take me a bit but yeah I can see what I can find.

**Comment by insunaa** [comment]
nvm this doesn't seem to be an openssl issue. can you recompile in debug mode and start mangosd with gdb attached?

**Comment by ssj17vegeta** [comment]
I had the same bug on Ubuntu, it's related to OpenSSL. It has been fixed for a few months on the TBC branch. Just copy the changes of [this commit](https://github.com/cmangos/mangos-tbc/commit/6ec6310c1ef22ace34434d58ee9d1d6d05e3f7b2) on your local install until the CMangos team decides to port it to WOTLK :sunglasses:

**Comment by insunaa** [comment]
```diff
diff --git a/src/shared/Auth/SARC4.cpp b/src/shared/Auth/SARC4.cpp
index 33270e4fd..5a4f18703 100644
--- a/src/shared/Auth/SARC4.cpp
+++ b/src/shared/Auth/SARC4.cpp
@@ -18,9 +18,15 @@

 #include "Auth/SARC4.h"
 #include <openssl/sha.h>
+#if defined(OPENSSL_VERSION_MAJOR) && (OPENSSL_VERSION_MAJOR >= 3)
+#include <openssl/provider.h>
+#endif

 SARC4::SARC4(uint8 len)
 {
+#if defined(OPENSSL_VERSION_MAJOR) && (OPENSSL_VERSION_MAJOR >= 3)
+    OSSL_PROVIDER_load(NULL, "legacy");
+#endif
 #if defined(OPENSSL_VERSION_NUMBER) && OPENSSL_VERSION_NUMBER >= 0x10100000L
     m_ctx = EVP_CIPHER_CTX_new();
     EVP_CIPHER_CTX_init(m_ctx);
@@ -35,6 +41,9 @@ SARC4::SARC4(uint8 len)

 SARC4::SARC4(uint8* seed, uint8 len)
 {
+#if defined(OPENSSL_VERSION_MAJOR) && (OPENSSL_VERSION_MAJOR >= 3)
+    OSSL_PROVIDER_load(NULL, "legacy");
+#endif
 #if defined(OPENSSL_VERSION_NUMBER) && OPENSSL_VERSION_NUMBER >= 0x10100000L
     m_ctx = EVP_CIPHER_CTX_new();
     EVP_CIPHER_CTX_init(m_ctx);
@@ -61,6 +70,9 @@ SARC4::~SARC4()

 void SARC4::Init(uint8 const* seed)
 {
+#if defined(OPENSSL_VERSION_MAJOR) && (OPENSSL_VERSION_MAJOR >= 3)
+    OSSL_PROVIDER_load(NULL, "legacy");
+#endif
 #if defined(OPENSSL_VERSION_NUMBER) && OPENSSL_VERSION_NUMBER >= 0x10100000L
     EVP_EncryptInit_ex(m_ctx, nullptr, nullptr, seed, nullptr);
 #else
```

**Comment by Orcman2019** [comment]
I found this, trying to recompile and see if it is happy now.. 

https://linuxhint.com/install-openssl-3-from-source/

It's not :(  It keeps trying to use the old out of date libraries, even if they don't exist..   openssl version shows 3 though.

**Comment by Orcman2019** [comment]
Well after fighting for a while with /usr/lib/ and /usr/local/lib64, ldconfig and cmake.. I think it's better to just toss it and upgrade.. 

Linux Mint 21/Ubuntu Jammy has openssl 3.0 by default so I'm going to start over with that. 

..... And Jeez that failed too...  linker error at 93%, also zlibc dependency doesn't exist anymore and is considered obsolete.. that also failed to compile when I tried to manually add it.  Having a hell of a time finding a distro this will actually work on anymore.

**Comment by ssj17vegeta** [comment]
@Orcman2019 Ubuntu works fine. Ubuntu 22.04+ (22.10 also works) with the commit I mentioned. No hack or other workaround needed, just works with the standard OpenSSL 3 that comes bundled with your distro.

**Comment by Orcman2019** [comment]
I'll give Ubuntu 22.10 server a try.. Linux Mint 21 should be using Ubuntu Jammy but it gets a linker error at 97% and fails:

[ 97%] Building CXX object src/game/CMakeFiles/game.dir/Vmap/MapTree.cpp.o
[ 97%] Building CXX object src/game/CMakeFiles/game.dir/Vmap/ModelInstance.cpp.o
[ 97%] Building CXX object src/game/CMakeFiles/game.dir/Vmap/TileAssembler.cpp.o
during GIMPLE pass: vrp
/home/pi/mangostemp/src/game/Vmap/TileAssembler.cpp: In member function ‘void VMAP::TileAssembler::exportGameobjectModels()’:
/home/pi/mangostemp/src/game/Vmap/TileAssembler.cpp:334:10: internal compiler error: in compute_live_loop_exits, at tree-ssa-loop-manip.c:247
  334 |     void TileAssembler::exportGameobjectModels()
      |          ^~~~~~~~~~~~~
0x7f021b71ad8f __libc_start_call_main
	../sysdeps/nptl/libc_start_call_main.h:58
0x7f021b71ae3f __libc_start_main_impl
	../csu/libc-start.c:392
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-11/README.Bugs> for instructions.
make[2]: *** [src/game/CMakeFiles/game.dir/build.make:11549: src/game/CMakeFiles/game.dir/Vmap/TileAssembler.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:507: src/game/CMakeFiles/game.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
pi@Dellwrath:/sbin$

**Comment by evil-at-wow** [comment]
I remember seeing that issue before, in cmangos/issues#3165. It's a compiler bug (apparently in GCC 11), so using a newer dot version (or newer/older GCC major version for that matter), or a different compiler like clang, could fix that issue.
I can confirm that SUSE's GCC 11.3 works, so it's certainly not every GCC 11 that's broken. Most likely Mint has updates as well.

**Comment by Orcman2019** [comment]
It was fully updated Linux Mint 21 Vanessa which should also be Ubuntu Jammy under the hood.. but I was able to compile with ugly old ubuntu server 22.10 and then I exported all the binaries to the much more user friendly Linux Mint 21 with auto login, auto start, certificate ssh, etc..  so it's happy now, running like a champ.
