### ISSUE TITLE
🐛 [Bug Report] Server crash when entering rookery room in Black Rock Spire

### ISSUE THREAD

**Issue by kelbren** [cmangos/issues#3267]
### Bug Details

When get close enough to trigger the whelp eggs in the rookery room inside black rock spire, I see the animation for the eggs hatching, but whelp does not spawn and server crashes with seg fault.

### Steps to Reproduce

1.  Enter Black Rock Spire instance.
2.  get close to egg in rookery room.
3. crash

### Expected behavior

Spawn of whelp.

### Core SHA1 Commit Hash

2631587dd298d77546c6bebce939dfb85285d122

### Database SHA1 Commit Hash

00f538ed08877f201dfaf8859dfa5588da1228aa

### Operating System

Ubuntu 20.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Pnumekin** [comment]
Can confirm in Classic, server is crashing instead of spawning whelps.

**Comment by AnonXS** [comment]
classicmangos
``` 
>	mangosd.exe!ObjectGuid::operator==(const ObjectGuid & guid) Line 158	C++
 	mangosd.exe!Spell::UpdateOriginalCasterPointer() Line 6791	C++
 	mangosd.exe!Spell::UpdatePointers() Line 6809	C++
 	mangosd.exe!Spell::update(unsigned int difftime) Line 3378	C++
 	mangosd.exe!SpellEvent::Execute(unsigned __int64 e_time, unsigned int p_time) Line 7048	C++
 	mangosd.exe!EventProcessor::Update(unsigned int p_time) Line 47	C++
 	mangosd.exe!Unit::Update(const unsigned int diff) Line 484	C++
 	mangosd.exe!Player::Update(const unsigned int diff) Line 1381	C++
 	mangosd.exe!Map::Update(const unsigned int & t_diff) Line 721	C++
 	mangosd.exe!DungeonMap::Update(const unsigned int & t_diff) Line 1680	C++
 	mangosd.exe!MapUpdateWorker::execute() Line 52	C++
 	mangosd.exe!MapUpdater::WorkerThread() Line 98	C++
```
tbcmangos no crash all working fine.

**Comment by kelbren** [comment]
I was able to fix the server crashing with the following:
````
update `gameobject_template` set `data5` = 900, `data3` = 15745 where `entry` = 175124;
````
I don't know if this is the proper fix, but it does seem to work ok now and not crash server.
perhaps it can be checked and added by a dev.

**Comment by insunaa** [comment]
It's not the proper fix unfortunately.
The problem seems to be that somewhere in the chain a WorldObject or ObjectGuid becomes an invalid pointer

**Comment by rmzV** [comment]
also when you touch eggs -> whelps must be summoned.
its required for achievement "leeeroy" or smth

**Comment by MilkmanMHOC** [comment]
> I was able to fix the server crashing with the following:
> 
> ```
> update `gameobject_template` set `data5` = 900, `data3` = 15745 where `entry` = 175124;
> ```
> 
> I don't know if this is the proper fix, but it does seem to work ok now and not crash server. perhaps it can be checked and added by a dev.

Was this in classic?  I know it doesn't fix the issue properly but would be nice to be able to get past the room without crashing server to continue rest of instance at least?

**Comment by insunaa** [comment]
This tempfix will always summon a whelp when you touch an egg. The correct spell will summon the whelp on a timer. I'm not sure, but I think the correct spell should also have a chance to summon 2 whelps or 0, but I might be imagining that.
