### ISSUE TITLE
🐛 [Bug Report] Frostwolf clan PvP rewards require Stormpike Guard rep instead of Frostwolf Clan rep

### ISSUE THREAD

**Issue by Patrick-Barry** [cmangos/issues#3268]
### Bug Details

A little under half of the Frostwolf clan PvP rewards require Stormpike Guard rep instead of Frostwolf Clan rep making them impossible to buy for the horde.

### Steps to Reproduce

1. Go to Frost Wolf Supply Officer Jekyll Flandring
2. Scroll through items for sale window
3. Items on Page 3-4 have wrong Rep faction requirements

### Expected behavior

These items should have a Frostwolf Clan rep requirment so that Horde players can buy them.

### Core SHA1 Commit Hash

86dd0136ebe372404f0c1fe7e9b32ca950d5d4ed

### Database SHA1 Commit Hash

d9dd03d09bad09513db21e31c105286817f86a8d

### Operating System

Windows 10

### Client Version

1.12.1 (Classic)

**Comment by MantisLord** [comment]
This seems to be a problem in Classic-DB only:

![image](https://github.com/cmangos/issues/assets/16798471/95c7f91d-ed42-4e5a-a34e-ed36e4225777)

In TBC-DB and WotLK-DB, there are no items in item_template which have Stormpike Guard or Frostwolf Clan as the RequiredReputationFaction.

Potential fix for Classic-DB:
```
-- These items should not be tied to a specific faction. The vendors control which factions are allowed to purchase them.
UPDATE item_template SET RequiredReputationFaction=0, RequiredReputationRank=0 WHERE RequiredReputationFaction IN (730,729); -- Stormpike Guard, Frostwolf Clan
```
