### ISSUE TITLE
🐛 [Bug Report] Eye of the Storm Emissary

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3270]
### Bug Details

The two emissaries on their patrol in Stormwind have a strange path through the dwarven district.

They first walk a few steps together, then one turns around and walks away a completely different one.

![WoWScrnShot_122522_130544](https://user-images.githubusercontent.com/6404203/209467591-b58e1280-beca-433b-b9df-d98008379c4c.jpg)
![WoWScrnShot_122522_130624](https://user-images.githubusercontent.com/6404203/209467594-f6dc3bf6-2115-4d7e-a913-2c20ac244766.jpg)

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

bb572100821d1fcfcf3ed5bfb45bf56c00c177ea

### Database SHA1 Commit Hash

24.12.22

### Operating System

W10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
I suggest converting them to spawn groups to see if they move better afterwards, though this only showcases that we fked something up with normal creature_linking formations.
They didnt work as badly befor, sometimes they could become a little glitchy but not like this.

**Comment by Ischtaratu** [comment]
I have followed the path once completely. There is a point where a patrol turns 180 degrees and runs completely in the other direction. Maybe it helps to put both flades on the same waypoints.

**Comment by AnonXS** [comment]
They are linked, one is the leader, other follows by angle of its spawn point (bad design -> convert to spawn group formation)

**Comment by AnonXS** [comment]
Duplicate https://github.com/cmangos/issues/issues/3017
