### ISSUE TITLE
🚀 [Feature Request] Item 1977 (20-slot bag)

### ISSUE THREAD

**Issue by wdstudios2** [cmangos/issues#3276]
### Feature Details

Item #1977, named "20-slot bag", does not appear to be in the database. I believe it should be added.

### Benefits and Purpose

This would allow players to add the 20-slot bag to their servers and alter its properties in whatever way and for whatever reason or purpose they choose without harming or bastardizing any of the existing bags.

### Core Versions

- [X] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
Tempted to close this since you can also just create custom items yourself.
I'm gonna leave it open for now because it is a legitimate feature request, just one that I see no reason to implement. But maybe Anon sees this differently.

RFC

**Comment by killerwife** [comment]
Item is on wowhead, should absolutely exist in item_template since its official

**Comment by AnonXS** [comment]
https://raw.githubusercontent.com/vmangos/core/eb6ee47247835f1878775d2a0cb19ed1120a156e/sql/migrations/20181031130419_world.sql - diff current vmangos for patch 1.13 (patch) missing items that are not present in our dbs.

**Comment by AnonXS** [comment]
https://github.com/cmangos/classic-db/commit/c892dd70327e67ed2653f4a626dab1d891472cc7
