### ISSUE TITLE
🐛 [Bug Report] Scriptbug for Quest 5203/rescue-from-jaedenar

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3277]
Recreation of bugreport: https://github.com/cmangos/wotlk-db/issues/516

### Bug Details

Quest runs in an endless loop!

After Arko'narin has been successfully escorted once and the quest gets its 100% Compleet status, Arko runs back to her prison and the quest starts again. She runs to the box, grabs her clothes (which she already has on) and runs out a second time.

cycle the quest 3 times in a row.
The quest can be finished, but Arko's script has no end ! (except when she dies)

Bug seems to be in TBC and WotLK,
vanilla not tested !

### Steps to Reproduce

lookk at bug details 

### Expected behavior

npc should disappear after 100% compleete status

### Suggested Workaround

let her die

### Core SHA1 Commit Hash

eb86f02ad0d58ebe0d67cd65d0b7934b7cf9fd03

### Database SHA1 Commit Hash

2023/01/07

### Operating System

W10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by kelbren** [comment]
I can confirm in WotLK, quest loops.

**Comment by miraco** [comment]
https://github.com/cmangos/tbc-db/commit/772fb8274d7f7d3dcb898e6534429626bd4e1a3f
Fixed for cmangos-tbc, for wotlk you need to wait that it get ported.

**Comment by Ischtaratu** [comment]
confirmed for tbc ... quest fixed ! 👍
