### ISSUE TITLE
🐛 [Bug Report] Scholomance door perm closed

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3278]
### Bug Details

Reopend Request
https://github.com/cmangos/wotlk-db/issues/468

Door in Scholomance to optional Boss: "Jandice Barov" is permanent closed.
Found no Way to open it, even all other Boss in Scholo are killed. So there is no Trigger to open it.

### Steps to Reproduce

n/a

### Expected behavior

As fare as i know the door should stay always open.

### Core SHA1 Commit Hash

320f16d56790c776b98e6cb0b452daecc93dc626

### Database SHA1 Commit Hash

2023/01/13

### Operating System

W10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Szymplo** [comment]
True. Mentioned it in #3197.

**Comment by AnonXS** [comment]
More info already in the issue above.
