### ISSUE TITLE
🐛 [Bug Report] WOTLK Hunter: "Immolation Trap" and "Serpent Sting"

### ISSUE THREAD

**Issue by maschumacher** [cmangos/issues#3279]
### Bug Details

I'am running cMaNGOS WOTLK under windows 10 and my server crashes when I play a hunter and I pull a creature with the serpent string in an immolation trap.

### Steps to Reproduce

1. place an immolation trap
2. use the serpent string on a target

### Expected behavior

mangos crashs

### Core SHA1 Commit Hash

66406b396c966ab3b4fb5051f6ee46b5dbf0d099

### Database SHA1 Commit Hash

152cf291a8996f8c8eee7adbd7965a2cae10ae5c

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by kelbren** [comment]
I tested and can confirm crash.

**Comment by kelbren** [comment]
_I tracked the crash down to line 8707 in src/game/Entities/unit.cpp
and added a check for caster. It fixed the problem for me, hopefully this can help._

```
for (auto i : mOwnerTaken)
{
    if (i->GetCasterGuid() == caster->GetObjectGuid() && i->isAffectedOnSpell(spellProto))
        TakenTotalMod *= (i->GetModifier()->m_amount + 100.0f) / 100.0f;
}
```

_I changed to:_

```
for (auto i : mOwnerTaken)
{
    if (caster)
        if (i->GetCasterGuid() == caster->GetObjectGuid() && i->isAffectedOnSpell(spellProto))
            TakenTotalMod *= (i->GetModifier()->m_amount + 100.0f) / 100.0f;
}
```

**Comment by maschumacher** [comment]
I changed it like you suggested and it fixed the bug for me too.
Thank you!
