### ISSUE TITLE
🐛 [Bug Report] realmd with postgresql gets segmentation fault (libcrypto related?)

### ISSUE THREAD

**Issue by kjarex** [cmangos/issues#3282]
### Bug Details

I have compiled the last release with the option to use a postgresql database.
on start realmd connects to the database and dies due to Segmentation fault.

```
[CMaNGOS Auth server v0.18] port(3724)


       _____     __  __       _   _  _____  ____   _____ 
      / ____|   |  \/  |     | \ | |/ ____|/ __ \ / ____|
     | |        | \  / |     |  \| | |  __  |  | | (___  
     | |ontinued| |\/| | __ _| . ` | | |_ | |  | |\___ \ 
     | |____    | |  | |/ _` | |\  | |__| | |__| |____) |
      \_____|   |_|  |_| (_| |_| \_|\_____|\____/ \____/ 
      http://cmangos.net\__,_|     Doing emulation right!


Built on Jan 22 2023 at 13:25:44
Built for Linux_x64 (little-endian)
Using commit hash(Git repository not found) committed on 0000-00-00T00:00:00+00:00
Using configuration file ../etc/realmd.conf.

<Ctrl-C> to stop.
Login Database total connections: 2
Segmentation fault
```

Note: with wrong database settings it just fails as it would be expected with an appropriate error message (-> that's why I say the issue happens after/once it is connected)

Also: If I recompile it for mysql, setup the mysql databases, and try it again, the segmentation fault doesn't happen either (and realmd just runs the way it should). Therefor I would assume the issue is indeed directly related to the use of postgresql (and doesn't just happen after connecting to the database in general).

And: while so far nothing would point to it - see the gdb output, and it might be actually related to openssl instead (maybe because in relation with libpq!?) 

### Steps to Reproduce

1. compile it with postgresql flag
2. install it
3. start it
4. be sad because it dies due to segmentation fault

### Expected behavior

Step 4 would be replaced with "connect with client and have fun"
And if that's not possible (as it might be something on my side), then some more meaningful/useful error message during compilation or start.

### Suggested Workaround

I do not have a workaround.

### Crash Log

```
(gdb) run
Starting program: /mangos-classic-latest/run2/bin/realmd 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[CMaNGOS Auth server v0.18] port(3724)


       _____     __  __       _   _  _____  ____   _____ 
      / ____|   |  \/  |     | \ | |/ ____|/ __ \ / ____|
     | |        | \  / |     |  \| | |  __  |  | | (___  
     | |ontinued| |\/| | __ _| . ` | | |_ | |  | |\___ \ 
     | |____    | |  | |/ _` | |\  | |__| | |__| |____) |
      \_____|   |_|  |_| (_| |_| \_|\_____|\____/ \____/ 
      http://cmangos.net\__,_|     Doing emulation right!


Built on Jan 22 2023 at 13:25:44
Built for Linux_x64 (little-endian)
Using commit hash(Git repository not found) committed on 0000-00-00T00:00:00+00:00
Using configuration file ../etc/realmd.conf.

<Ctrl-C> to stop.
Login Database total connections: 2

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6564bc4 in X509_certificate_type () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
```

### Core SHA1 Commit Hash

I downloaded the released archive file

### Database SHA1 Commit Hash

I downloaded the released archive file

### Operating System

Ubuntu 16

### Client Version

1.12.1 (Classic)

**Comment by kjarex** [comment]
Oh, and I should have mentioned (as the gdb output/ reference to libcrypto.so.1.0.0 might suggest otherwise (at least it surprised me)): it was compiled with OpenSSL 1.1.0e (both, the working mysql version, as well as the postgresql version, were compiled exactly the same way except for the postgresql flag) including those flags:

`-DOPENSSL_CRYPTO_LIBRARY=/usr/local/lib/libcrypto.a \
-DOPENSSL_SSL_LIBRARY=/usr/local/lib/libssl.a \
-DOPENSSL_INCLUDE_DIR=/usr/local/include/openssl \
-DBOOST_ROOT=/mangos-classic-latest/boost_1_81_0`

with `/usr/local/lib/` containing the libraries of/for OpenSSL 1.1.0e

Cmake version 3.24.3 was used in the build process (if relevant)

**Comment by insunaa** [comment]
our postgres connector isn't actively maintained. can you post a full backtrace?

**Comment by kjarex** [comment]
Oh okay, then nevermind. But thanks anyway.
