### ISSUE TITLE
[Feature request] Playersbots Improvements

### ISSUE THREAD

**Issue by xBarselonx** [cmangos/issues#3284]
### Feature Details

Is it possible to add the appearance of random bots to the core source files to play together with them, pass dungeons, raids, and complete quests.  
Example:
1. a player creates a character
2. In the server configuration settings specifies whether random playerbots will be enabled, as well as their number and level.
3. The character can invite a random Playerbot to the party and go to meet the switch.

### Benefits and Purpose

This is likely to be interesting for those players who like to play different classes and develop characters individually.

### Core Versions

- [X] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by xBarselonx** [comment]
Let me add to the above.
In other words, is it possible to add to the source files of the server function to manage the characters that are created on another account?

id     name account
1. my account
2. a donor account with previously created characters (maximum 10).
Then the player can specify in the configuration file CMaNGOS the created donor account to play the characters.

Example in the AC did so with the auction bot https://github.com/azerothcore/mod-ah-bot/blob/master/conf/mod_ahbot.conf.dist (see settings of lines: 50,51.

**Comment by celguar** [comment]
I'm not sure what you mean, but since you ask - almost anything is possible, just need someone to write code for it

**Comment by celguar** [comment]
You can change code to allow using bots from another account. If you play alone should not be a problem.

**Comment by xBarselonx** [comment]
> You can change code to allow using bots from another account.

That's right. I play alone. But the problem with writing code is that I'm not a programmer).
Can CMaNGOS developers and subscribers do this? I can assume that there are players among users who would be interested in it.

**Comment by miraco** [comment]
We have a new Bot System now.
