### ISSUE TITLE
🐛 [Bug Report] The Warlock class quest "Imp Delivery" crashes Mangosd

### ISSUE THREAD

**Issue by fangshun2004** [cmangos/issues#3290]
### Bug Details

Follow the task requirements, go to the "scholomance" lab and release the imp, and after releasing the ghost, the imp talks alone, and after 5-6 seconds, the client disconnects and the mangosd disappears

2023-01-29 20:12:22 <Scripting Library ERROR>: Script requested creature with entry 1853, but no npc of this entry was created yet, or it was not stored by script for map 289.
2023-01-29 20:13:28 ERROR:Attempt get value from nonexistent value field: 46 (count: 26) for object typeid: 5 type mask: 33

### Steps to Reproduce

1.Build a Warlock class and upgrade to 60 and above
2.Add quest "Imp Delivery" with gm account, the task ID may be #7629 (I see from the database webpage that this is the number)
3.AddItem 18688 ----Imp in a Jar"
4.Go to the "Scholomance" lab and use items

### Expected behavior

After using the item, it is time to complete the quest

### Core SHA1 Commit Hash

b5e9fc94a8832614f5f7b2438e3c01b57de014df

### Database SHA1 Commit Hash

85243aa2a7a7e4b6bae69cd4c3d9974b518ebee5

### Operating System

win10 19045.2546

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
Resolved
