### ISSUE TITLE
🐛 [Bug Report] Server Crash when targeting enemy as soon as it dies

### ISSUE THREAD

**Issue by John-Ivar-Flatmo** [cmangos/issues#3291]
### Bug Details

NOTE: issue was seperated out from https://github.com/cmangos/issues/issues/3281 originaly belived to be the same issue

the server crashes when selecting an enemy as it dies(log suggests: 2 unselects happening at once) (backtrace suggest: HandleAttackSwingOpcode)

Tested on
Cmangos classic: built 1-2 days ago with -DCMAKE_INSTALL_PREFIX=./built -DBUILD_EXTRACTORS=ON -DPCH=1 -DDEBUG=0 -DBUILD_PLAYERBOT=ON
[lootfix-TargetOnDeath.txt](https://github.com/cmangos/issues/files/10473774/lootfix-TargetOnDeath.txt) -Backtrace+log snipped
Client: vanilla(1.12)
Client: modern(through hermesproxy hosted on serverpc)(1.14)
Mixed clients: 1 vanilla 2 modern: no difference

Notes:
Core SH1 provided in this bug report is not garanted to match server this was tested on, i may have accidentaly build TBC or Wrath afterwards, my server is not in the same folder as where i build it.
Some problemsolving did take place on discord https://discord.com/channels/362206349339262976/362206349339262978/1066025735355121665 -you may need to scroll a bit since originaly we had a playerbot issue we thought was related
not attempted reproduction on TBC, thus cannot confirm
not attempted reproduction on  Wrath, thus cannot confirm

### Steps to Reproduce

1.loot target as soon as you kill it
NOTE: i haven't personally been able to reproduce this but 2 players on my server whom i saw do it while in vc and looking at the server cli, can do it consistently, it think you just have to be quick enough
NOTE: it seems like when executed correctly a single kill is enough to reproduce
NOTE: does not seem to affect playerbots, they may have a delay or simply not act fast enugh, but hose are just guesses.

### Expected behavior

Player loots just fine, and server not crashing

### Suggested Workaround

simple hacky Fix:
in src/game/Combat/CombatHandler.cpp
under WorldSession::HandleAttackSwingOpcode
change
    if (!mover->CanAttackNow(enemy))
    {
        // stop attack state at client
        mover->SendMeleeAttackStop(nullptr);
        return;
    }
to
    if (!mover->CanAttackNow(enemy))
    {
        // stop attack state at client
        //mover->SendMeleeAttackStop(nullptr); //CHANGED LINE
        return;
    }
fix been active for about a week, it works and, seems like there arent any side effects tho all players are currently on modern client trough hermesproxy, so your milage may vary.

### Crash Log

NOTE: same as: [lootfix-TargetOnDeath.txt](https://github.com/cmangos/issues/files/10473774/lootfix-TargetOnDeath.txt)

LOG SNIPPET
05:23:51 Creature (Entry: 8541 Counter: 92596) DBGuid: 92596 stopped attacking Creature (Entry: 12337 Counter: 9000527) DBGuid: 92287
05:23:51 Creature (Entry: 13118 Counter: 9000523) DBGuid: 92289 stopped attacking Creature (Entry: 8541 Counter: 92596) DBGuid: 92596
05:23:51 Creature (Entry: 13118 Counter: 9000524) DBGuid: 92288 stopped attacking Creature (Entry: 8541 Counter: 92596) DBGuid: 92596
05:23:51 Creature (Entry: 13118 Counter: 9000525) DBGuid: 92290 stopped attacking Creature (Entry: 8541 Counter: 92596) DBGuid: 92596
05:23:51 Creature (Entry: 13118 Counter: 9000526) DBGuid: 92291 stopped attacking Creature (Entry: 8541 Counter: 92596) DBGuid: 92596
05:23:51 Creature (Entry: 12337 Counter: 9000527) DBGuid: 92287 stopped attacking Creature (Entry: 8541 Counter: 92596) DBGuid: 92596
05:23:51 Holder of spell 19726 now is in use
05:23:51 Holder of spell 19726 now is in use
05:23:51 Holder of spell 19726 now is in use
05:23:51 Holder of spell 19726 now is in use
05:23:52 PeriodicTick: Player Crakdruid (Counter: 1) attacked Creature (Entry: 2959 Counter: 25520) DBGuid: 25520 for 8 dmg inflicted by 8924
05:23:53 PeriodicTick: Player Crakdruid (Counter: 1) heal of Player Crakdruid (Counter: 1) DBGuid: 1 for 14 health inflicted by 1058
05:23:56 WORLD: Sent SMSG_ATTACKSTART
05:23:56 PeriodicTick: Player Crakdruid (Counter: 1) heal of Player Crakdruid (Counter: 1) DBGuid: 1 for 14 health inflicted by 1058
05:23:56 PLAYER: RewardHonor
05:23:56 Creature (Entry: 2959 Counter: 25520) DBGuid: 25520 stopped attacking Player Crakdruid (Counter: 1) DBGuid: 1
05:23:56 Player Crakdruid (Counter: 1) DBGuid: 1 stopped attacking Creature (Entry: 2959 Counter: 25520) DBGuid: 25520

BACKTRACE
Thread 11 "mangosd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd94ce6c0 (LWP 995543)]
0x0000555556110d85 in Object::GetGuidStr[abi:cxx11]() const (this=0x0) at /V/servers/jifServer-1/build/cmangos/lootFix/src/game/Entities/Object.h:391
(gdb) bt -full
#0  0x0000555556110d85 in Object::GetGuidStr[abi:cxx11]() const (this=0x0) at /V/servers/jifServer-1/build/cmangos/lootFix/src/game/Entities/Object.h:391
No locals.
#1  0x00005555562a03a4 in Unit::SendMeleeAttackStop (this=0x7fffd4312e10, victim=0x0) at /V/servers/jifServer-1/build/cmangos/lootFix/src/game/Entities/Unit.cpp:2746
        data = {<ByteBuffer> = {static DEFAULT_SIZE = 4096, _rpos = 0, _wpos = 7, _storage = std::vector of length 7, capacity 20 = {1 '\001', 1 '\001', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000'}}, m_opcode = SMSG_ATTACKSTOP, m_receivedTime = {__d = {__r = 0}}}
#2  0x00005555566e8316 in WorldSession::HandleAttackSwingOpcode (this=0x7fffb000a7b0, recv_data=...) at /V/servers/jifServer-1/build/cmangos/lootFix/src/game/Combat/CombatHandler.cpp:52
        guid = {m_guid = 17379391011666551728}
        enemy = 0x7fffd71cd640
        mover = 0x7fffd4312e10
#3  0x000055555655c11e in WorldSession::ExecuteOpcode (this=0x7fffb000a7b0, opHandle=..., packet=...) at /V/servers/jifServer-1/build/cmangos/lootFix/src/game/Server/WorldSession.cpp:1158
No locals.
#4  0x0000555556558e77 in WorldSession::Update (this=0x7fffb000a7b0, diff=50) at /V/servers/jifServer-1/build/cmangos/lootFix/src/game/Server/WorldSession.cpp:376
        packet = std::unique_ptr<WorldPacket> = {get() = 0x7fffb000c1e0}
        opHandle = @0x7fffbc0405d8: {name = 0x555556ae1e99 "CMSG_ATTACKSWING", status = STATUS_LOGGEDIN, packetProcessing = PROCESS_INPLACE, handler = (void (WorldSession::*)(WorldSession * const, WorldPacket &)) 0x5555566e8110 <WorldSession::HandleAttackSwingOpcode(WorldPacket&)>}
        recvQueueCopy = std::deque with 2 elements = {std::unique_ptr<WorldPacket> = {get() = 0x7fffb000fcd0}, std::unique_ptr<WorldPacket> = {get() = 0x7fffb000fc90}}
#5  0x000055555660d8ef in World::UpdateSessions (this=0x555557058760, diff=50) at /V/servers/jifServer-1/build/cmangos/lootFix/src/game/World/World.cpp:2070
        pSession = 0x7fffb000a7b0
        itr = {<std::__detail::_Node_iterator_base<std::pair<unsigned int const, WorldSession*>, false>> = {_M_cur = 0x55555af421a0}, <No data fields>}
#6  0x000055555660b8a6 in World::Update (this=0x555557058760, diff=50) at /V/servers/jifServer-1/build/cmangos/lootFix/src/game/World/World.cpp:1498
No locals.
#7  0x000055555606cbda in WorldRunnable::run (this=0x555558147240) at /V/servers/jifServer-1/build/cmangos/lootFix/src/mangosd/WorldRunnable.cpp:56
        diffTick = 50
        diffTime = 3
        overCounter = 5
#8  0x0000555556094499 in MaNGOS::Thread::ThreadTask (param=0x555558147240) at /V/servers/jifServer-1/build/cmangos/lootFix/src/shared/Multithreading/Threading.cpp:84
        _task = 0x555558147240
#9  0x0000555556095128 in std::__invoke_impl<void, void (*)(void*), void*> (__f=@0x555558147100: 0x55555609446e <MaNGOS::Thread::ThreadTask(void*)>) at /usr/include/c++/12/bits/invoke.h:61
No locals.
#10 0x00005555560950b9 in std::__invoke<void (*)(void*), void*> (__fn=@0x555558147100: 0x55555609446e <MaNGOS::Thread::ThreadTask(void*)>) at /usr/include/c++/12/bits/invoke.h:96
No locals.
#11 0x0000555556095029 in std::thread::_Invoker<std::tuple<void (*)(void*), void*> >::_M_invoke<0ul, 1ul> (this=0x5555581470f8) at /usr/include/c++/12/bits/std_thread.h:252
No locals.
#12 0x0000555556094fe2 in std::thread::_Invoker<std::tuple<void (*)(void*), void*> >::operator() (this=0x5555581470f8) at /usr/include/c++/12/bits/std_thread.h:259
No locals.
#13 0x0000555556094fc6 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(void*), void*> > >::_M_run (this=0x5555581470f0) at /usr/include/c++/12/bits/std_thread.h:210
No locals.
#14 0x00007ffff76d44a3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#15 0x00007ffff74a7fd4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736839083712, 4014043039869408591, -176, 11, 140737488344272, 140736830693376, -4014100928548596401, -4014026182194784945}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#16 0x00007ffff752866c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.
(gdb) Quit
(gdb) 

### Core SHA1 Commit Hash

6a869f148c482b551cf6778d1301867cd8cd7e7a

### Database SHA1 Commit Hash

546b0e6485a3e565e337d275382078797c77c0ec

### Operating System

Linux: Debian GNU/Linux bookworm/sid

### Client Version

1.12.1 (Classic)

**Comment by evil-at-wow** [comment]
This should be fixed in all cores now, with the commits referenced above, so closing.
