### ISSUE TITLE
🐛 [Bug Report] manually canceled quests are not removed from the db table

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3292]
### Bug Details

I had taken some quests from the current moon festival. Since I wanted to complete them with another character, I canceled the quest to delete it from the quest log. So I thought. When I later log in the charakter again, the quests were there in Questlog. 

My research showed that although the client deletes the quests from its log, but the information is not processed by the server. There is no change in the corresponding table.

Therefore, even after the client restart all the quests appear again in the quest log.

### Steps to Reproduce

1. Start a Quest
2. Brack the Quest to delete it from Questlog
3. Restart Cliient
4. Quest will be back in Questlog

### Expected behavior

No quest in log after manual break the Quest.

### Suggested Workaround

manual deleete quest ID in DB table

### Crash Log

n/a

### Core SHA1 Commit Hash

b5e9fc94a8832614f5f7b2438e3c01b57de014df

### Database SHA1 Commit Hash

01.02.2023

### Operating System

W10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by MilkmanMHOC** [comment]
This might be related to this issue? https://github.com/cmangos/wotlk-db/issues/502

I also would note that possibly related, once you do a seasonal quest once, it doesn't show back up the next year as available?

**Comment by Ischtaratu** [comment]
As far as I can tell, it's a general problem and applies to all quests. So it points more to the handling of the cancellation of the quests than to specific events.

**Comment by AnonXS** [comment]
I can not replicate that issue.

I had quest https://www.wowhead.com/classic/quest=7629/imp-delivery completed in my log from yesterday.
Teleported to honorhold and took quest https://www.wowhead.com/tbc/quest=10058/an-old-gift at the Inn.
Then i went outside and took the daily pvp quest, and cancelled the dailiy quest and the imp delivery quest.
then i logged out and shutdown the mangosd and realmd.
after restarting both and logging back in only quest 10058 was in my log as suspected.

**Comment by celguar** [comment]
I think how to reproduce did not include restarting server

**Comment by AnonXS** [comment]
Now i have 10058 left in my log, cancelled it and relogged, it's still gone.

We def need more info, like how does his character_queststatus table look like for this character etc. in a specific usecase.

**Comment by Ischtaratu** [comment]
for better Documentation ... i will try to create a short video ...

**Comment by Ischtaratu** [comment]
I have been trying to reproduce the error for an hour. I was sure that this error occurred several times in different quests. But now that I have installed OBS and am ready to record, the error seems to have disappeared completely.

I am unsure and doubt myself.

Therefore, this case can be closed. It would be possible that the server could have just swallowed itself. Since my server does not run 24/7 and I only run it for a few hours a day, I suspect the problem is now gone after the complete reboot.

If the problem occurs again, I will try to document it as comprehensively as possible and open a new case file. 

thanks
