### ISSUE TITLE
🐛 [Bug Report] TBC- CMANGOS  Quest ID:7629 will crash the server

### ISSUE THREAD

**Issue by william19831103** [cmangos/issues#3293]
### Bug Details

Quest ID:7629, Quest Title :Imp Delivery   will crash the server.
I used quest item 18688   near  alchemy lab, J'eevee will appears and run id 8438 of dbscripts_on_event.
At finial step, server will crash and quest is not complete.

### Steps to Reproduce

1. ```.q a 7629```
2. ```.go o 2890065```
3. use item 18688
4. wait process of quest and server will crash

### Crash Log

2023-02-03 21:13:28ERROR:Attempt get value from nonexistent value field: 46 (count: 26) for object typeid: 5 type mask: 33

### Core SHA1 Commit Hash

latest

### Database SHA1 Commit Hash

latest

### Operating System

Win 10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
```
 	ucrtbased.dll!00007ff87f497475()	Unknown
 	ucrtbased.dll!00007ff87f497613()	Unknown
 	ucrtbased.dll!00007ff87f4ad86d()	Unknown
>	mangosd.exe!Object::HasFlag(unsigned short index, unsigned int flag) Line 514	C++
 	mangosd.exe!Spell::CheckCast(bool strict) Line 5013	C++
 	mangosd.exe!Spell::PreCastCheck(Aura * triggeredByAura) Line 3017	C++
 	mangosd.exe!Spell::SpellStart(const SpellCastTargets * targets, Aura * triggeredByAura) Line 3056	C++
 	mangosd.exe!Unit::CastSpell(Unit * Victim, const SpellEntry * spellInfo, unsigned int triggeredFlags, Item * castItem, Aura * triggeredByAura, ObjectGuid originalCaster, const SpellEntry * triggeredBy) Line 1533	C++
 	mangosd.exe!Unit::CastSpell(Unit * Victim, unsigned int spellId, unsigned int triggeredFlags, Item * castItem, Aura * triggeredByAura, ObjectGuid originalCaster, const SpellEntry * triggeredBy) Line 1496	C++
 	mangosd.exe!ScriptAction::ExecuteDbscriptCommand(WorldObject * pSource, WorldObject * pTarget, Object * pSourceOrItem) Line 1998	C++
 	mangosd.exe!ScriptAction::HandleScriptStep() Line 1582	C++
 	mangosd.exe!Map::ScriptsProcess() Line 2025	C++
 	mangosd.exe!Map::Update(const unsigned int & t_diff) Line 819	C++
 	mangosd.exe!DungeonMap::Update(const unsigned int & t_diff) Line 1713	C++
 	mangosd.exe!MapUpdateWorker::execute() Line 53	C++
 	mangosd.exe!MapUpdater::WorkerThread() Line 98	C++
 	[External Code]	

```

```
Attempt get value from nonexistent value field: 46 (count: 26) for object typeid: 5 type mask: 33
Critical Error: A condition which must never be false was found to be false. Server was shut down to protect data integrity.
If this error is occurring frequently, please recompile the software in debug mode to get more details.

Object::HasFlag(): index < m_valuesCount || PrintIndexError(index, false)
```

Lets see if porting <https://github.com/cmangos/wotlk-db/commit/fd923e70ef82f2c40e29d056a594559b35b58baf> helps.

**Comment by Grz3s** [comment]
@AnonXS backport it. - fixes issue
https://github.com/cmangos/wotlk-db/commit/fd923e70ef82f2c40e29d056a594559b35b58baf

**Comment by william19831103** [comment]
> 
It is wotlk-db. Do you have TBC-DB?

**Comment by AnonXS** [comment]
it ususally takes a few weeks for stuff to be ported, if we know something is critical it will be ported sooner usually.

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/216741231-40dbb65d-f1b8-4760-a27a-3e0ede77b5dd.png)

port to classicmangos following.
