### ISSUE TITLE
🐛 [Bug Report]  Tempest Keep dont remove gate to Kael'thas

### ISSUE THREAD

**Issue by william19831103** [cmangos/issues#3294]
### Bug Details

For Raid Tempest Keep,
I killed Boss Al'ar, Tempest Keep,Tempest Keep. but the Gate to Kael'thas still exist.
so I can not go to room of Kael'thas.

### Steps to Reproduce

1. To Raid Tempest Keep
2. Kill Boss Al'ar, Tempest Keep,Tempest Keep
3. To the gate to Kael'thas
4.

### Expected behavior

gate to Kael'thas will disappear after killing 3 boss.

### Core SHA1 Commit Hash

latest

### Database SHA1 Commit Hash

latest

### Operating System

Win 10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by william19831103** [comment]
The Gate Entry 184327,  guid is 5500005. name is Doodad_TK_Raid_Door03

**Comment by Ischtaratu** [comment]
![WoWScrnShot_020423_181311](https://user-images.githubusercontent.com/6404203/216780546-185e8ee9-dac5-4006-bbb3-ba05d302de8b.jpg)
cofirmed ... 3 boss killed, door stay closed !

**Comment by AnonXS** [comment]
There is something wrong going on with gostate, as these doors should be open by default in 2.4.3 as you can go straight for kael'thas then, this is a regression.

thats why the door checks are behind a prenerf check in core and unused in default master.

```
#ifdef PRENERF_2_0_3
            if (CheckDoorOpening())
                OpenDoors();
#endif
```

```
[Patch 2.4.0](https://wowpedia.fandom.com/wiki/Patch_2.4.0) (2008-03-25): You may now fight [Prince Kael'thas](https://wowpedia.fandom.com/wiki/Kael%27thas_Sunstrider) and [Lady Vashj](https://wowpedia.fandom.com/wiki/Lady_Vashj) without first killing all the other bosses in their respective dungeons.
```

**Comment by william19831103** [comment]
> There is something wrong going on with gostate, as these doors should be open by default in 2.4.3 as you can go straight for kael'thas then, this is a regression.
> 
> thats why the door checks are behind a prenerf check in core and unused in default master.
> 
> ```
> #ifdef PRENERF_2_0_3
>             if (CheckDoorOpening())
>                 OpenDoors();
> #endif
> ```
> 
> ```
> [Patch 2.4.0](https://wowpedia.fandom.com/wiki/Patch_2.4.0) (2008-03-25): You may now fight [Prince Kael'thas](https://wowpedia.fandom.com/wiki/Kael%27thas_Sunstrider) and [Lady Vashj](https://wowpedia.fandom.com/wiki/Lady_Vashj) without first killing all the other bosses in their respective dungeons.
> ```

Hi, Any idea to fix it?

**Comment by insunaa** [comment]
```cpp
void instance_the_eye::OnObjectCreate(GameObject* pGo)
{
    switch (pGo->GetEntry())
    {
        case GO_ARCANE_DOOR_HORIZ_3:
        case GO_ARCANE_DOOR_HORIZ_4:
        case GO_KAEL_STATUE_LEFT:
        case GO_KAEL_STATUE_RIGHT:
        case GO_BRIDGE_WINDOW:
            m_goEntryGuidStore[pGo->GetEntry()] = pGo->GetObjectGuid();
            break;
        case GO_RAID_DOOR_3:
        case GO_RAID_DOOR_4:
        case GO_ARCANE_DOOR_VERT_3:
        case GO_ARCANE_DOOR_VERT_4:
            m_goEntryGuidStore[pGo->GetEntry()] = pGo->GetObjectGuid();
#ifndef PRENERF_2_0_3
            if (CheckDoorOpening())
#endif
                pGo->SetGoState(GO_STATE_ACTIVE);
            break;
    }
}
```

try this

**Comment by william19831103** [comment]
> ```c++
> void instance_the_eye::OnObjectCreate(GameObject* pGo)
> {
>     switch (pGo->GetEntry())
>     {
>         case GO_ARCANE_DOOR_HORIZ_3:
>         case GO_ARCANE_DOOR_HORIZ_4:
>         case GO_KAEL_STATUE_LEFT:
>         case GO_KAEL_STATUE_RIGHT:
>         case GO_BRIDGE_WINDOW:
>             m_goEntryGuidStore[pGo->GetEntry()] = pGo->GetObjectGuid();
>             break;
>         case GO_RAID_DOOR_3:
>         case GO_RAID_DOOR_4:
>         case GO_ARCANE_DOOR_VERT_3:
>         case GO_ARCANE_DOOR_VERT_4:
>             m_goEntryGuidStore[pGo->GetEntry()] = pGo->GetObjectGuid();
> #ifndef PRENERF_2_0_3
>             if (CheckDoorOpening())
> #endif
>                 pGo->SetGoState(GO_STATE_ACTIVE);
>             break;
>     }
> }
> ```
> 
> try this

It not working.

For below, it is working.

void instance_the_eye::SetData(uint32 uiType, uint32 uiData)
{
    switch (uiType)
    {
        case TYPE_ALAR:
        case TYPE_SOLARIAN:
        case TYPE_VOIDREAVER:
            m_auiEncounter[uiType] = uiData;
//#ifdef PRENERF_2_0_3
            if (CheckDoorOpening())
                OpenDoors();
//#endif

**Comment by insunaa** [comment]
yeah my bad, you need `#ifdef` in my fix, not `#ifndef`

change that and it'll work. but undo your change, that just breaks things more

```cpp
void instance_the_eye::OnObjectCreate(GameObject* pGo)
{
    switch (pGo->GetEntry())
    {
        case GO_KAEL_STATUE_LEFT:
        case GO_KAEL_STATUE_RIGHT:
        case GO_BRIDGE_WINDOW:
            m_goEntryGuidStore[pGo->GetEntry()] = pGo->GetObjectGuid();
            break;
        case GO_RAID_DOOR_3:
        case GO_RAID_DOOR_4:
        case GO_ARCANE_DOOR_VERT_3:
        case GO_ARCANE_DOOR_VERT_4:
        case GO_ARCANE_DOOR_HORIZ_3:
        case GO_ARCANE_DOOR_HORIZ_4:
            m_goEntryGuidStore[pGo->GetEntry()] = pGo->GetObjectGuid();
#ifdef PRENERF_2_0_3
            if (CheckDoorOpening())
#endif
                pGo->SetGoState(GO_STATE_ACTIVE);
            break;
    }
}
```

try this

**Comment by AnonXS** [comment]
open again after the gameobject_addon conversion.

this fire is also fixed, which was broken during nighttime due to state not being applied correctly.

![grafik](https://user-images.githubusercontent.com/19734826/219095702-ea428d81-4038-48b4-ae27-8e90f46266c5.png)
