### ISSUE TITLE
💬 [Support Request] 

### ISSUE THREAD

**Issue by zZDOCZz** [cmangos/issues#3296]
### Core Version

mangos-tbc

### Support Request Details

i wanted to make a wow tbc server so i followed every step on the guide, but at the end when im about to run the server
./realmd.exe -c realmd.conf
./mangosd.exe -c mangosd.conf
i get this error:

((realmd))

Built on Feb  7 2023 at 10:43:44
Built for Win64 (little-endian)
Using commit hash(eb960e33f165cc1ab97dd9c5ab51d226f3381871) committed on 2023-02-04T13:25:34+01:00
Using configuration file realmd.conf.

<Ctrl-C> to stop.
Login Database total connections: 2
Could not connect to MySQL database at 127.0.0.1: Access denied for user 'mangos'@'localhost' (using password: YES)

Cannot connect to database

((mangosd))

Built on Feb  7 2023 at 10:47:01
Built for Win64 (little-endian)
Using commit hash(eb960e33f165cc1ab97dd9c5ab51d226f3381871) committed on 2023-02-04T13:25:34+01:00
Using configuration file mangosd.conf.

<Ctrl-C> to stop.
World Database total connections: 2
Could not connect to MySQL database at 127.0.0.1: Access denied for user 'mangos'@'localhost' (using password: YES)

Cannot connect to world database 127.0.0.1;3306;mangos;mangos;tbcmangos

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

eb960e33f165cc1ab97dd9c5ab51d226f3381871

### Database SHA1 Commit Hash

b39df8ad0e4edeb4b0bb2882f3d255aa07f4ce7a

### Server Operating System

Windows

### Client Version

2.4.3 (The Burning Crusade)

### Client Operating System

Windows

**Comment by miraco** [comment]
Could not connect to MySQL database at 127.0.0.1: Access denied for user 'mangos'@'localhost' (using password: YES)

wrong configuration from your database settings. Maybe wrong username/password?

**Comment by zZDOCZz** [comment]
nope
i didnt touch the default setting, i didnt even changed the default password.
and i should mention im using xampp and DBeaver.

**Comment by evil-at-wow** [comment]
> Could not connect to MySQL database at 127.0.0.1: Access denied for user 'mangos'@'localhost' (using password: YES)

It sounds like the user you're trying to connect with isn't what MySQL considers to be the user that has been granted all the privileges to the databases tables, so it denies access. I think the culprit is the subtle difference between 127.0.0.1 and localhost (yes, they refer to the same thing generally speaking but not literally).

If I'm not mistaken our SQL files use 'localhost' in the 'CREATE USER ...' and 'GRANT ...' queries, so I would suggest to adjust your config files (mangosd.conf and realmd.conf) and replace '127.0.0.1' by 'localhost' for the database info options (```LoginDatabaseInfo```, ```WorldDatabaseInfo```, etc).

So instead of something like
```
LoginDatabaseInfo = "127.0.0.1;3306;mangos;mangos;tbcrealmd"
```
use 
```
LoginDatabaseInfo = "localhost;3306;mangos;mangos;tbcrealmd"
```

**Comment by zZDOCZz** [comment]
im still getting the same issue, i tried GRANT queries again just in case if there were a problem with that but didn't make any difference, i really wanna make this work is there anything else that i can do to possibly fix it?
