### ISSUE TITLE
🐛 [Bug Report] Server crash on CMSG_ATTACKSWING

### ISSUE THREAD

**Issue by f0n1x** [cmangos/issues#3297]
### Bug Details

When fighting Rotting Worms, the server crashes (when right clicking or when they attack the player?)
I have multiple crash reports that all end with "WORLD: Received opcode CMSG_ATTACKSWING Creature (Entry: 10925 Counter: 90005xx)"
I have experienced this with other creatures as well.

### Steps to Reproduce

1. Take a sufficiently leveled character to Western Plaguelands.
2. Locate a Rotting Cadaver (id: 4474) @ Dalson's Tears.
3. Kill the creature and it will spawn 2x Rotting Worm (id: 10925).
4. Let the creatures attack you and right-click on them to target them and melee.
5. It may take a few attempts, but the server should crash.

### Expected behavior

No server crash.

### Suggested Workaround

Not sure if this is a melee swing issue? (seem to be from the op code) or something else?

### Crash Log

08:34:53 RollMeleeOutcomeAgainst: New attack die: [MISS:480, DODGE:2254, PARRY:480, BLOCK:0, GLANCE:0, CRIT:520, CRUSH:0]
08:34:53 RollMeleeOutcomeAgainst: Rolled 9913, result: HIT
08:34:53 WORLD: Sending SMSG_ATTACKERSTATEUPDATE
08:34:53 DealDamageStart
08:34:53 deal dmg:88 to health:684
08:34:53 DealDamageAlive
08:34:53 DealDamageEnd returned 88 damage
08:34:53 Spell 5302 Effect0 : 6 Targets: Player Fonix (Counter: 901) DBGuid: 901, -, -
08:34:53 Spell: Aura is: 4
08:34:53 Aura: construct Spellid : 5302, Aura : 4 Target : 1 Damage : 0
08:34:53 Aura 4 now is remove mode 1
08:34:53 Holder of spell 5302 now is in use
08:34:53 AttackerStateUpdate: (NPC)    9000544 attacked 901 (TypeId: 4) for 88 dmg, absorbed 0, blocked 0, resisted 0.
08:34:53 WORLD: CMSG_CAST_SPELL, spellId - 11293, data length = 14
08:34:53 Sending SMSG_SPELL_START id=11293
08:34:53 MeleeSpellHitResult: New ability hit die: 11293 [MISS:10, RESIST:0, DODGE:510, PARRY:510, DEFLECT:0, BLOCK:0]
08:34:53 MeleeSpellHitResult: Rolled 2532, result: HIT
08:34:53 Sending SMSG_SPELL_GO id=11293
08:34:53 Spell 11293 Effect0 : 121 Targets: Creature (Entry: 10925 Counter: 9000543) DBGuid: 9000543, -, -
08:34:53 Spell 11293 Effect1 : 80 Targets: Creature (Entry: 10925 Counter: 9000543) DBGuid: 9000543, -, -
08:34:53 DealDamageStart
08:34:53 deal dmg:120 to health:2
08:34:53 DealDamage Player Fonix (Counter: 901) DBGuid: 901 Killed Creature (Entry: 10925 Counter: 9000543) DBGuid: 9000543
08:34:53 PLAYER: RewardHonor
08:34:53 SET JUST_DIED
08:34:53 Creature (Entry: 10925 Counter: 9000543) DBGuid: 9000543 stopped attacking Player Fonix (Counter: 901) DBGuid: 901
08:34:53 Loot::CreateLoot> cannot create corpse loot, FillLoot failed with loot id(0)!
08:34:53 DealDamageAttackStop
08:34:53 DealDamageEnd returned 120 damage
08:34:53 WORLD: Received opcode CMSG_ATTACKSWING Creature (Entry: 10925 Counter: 9000543)

### Core SHA1 Commit Hash

b2940c798686956e64fb5508da42c44c7000f16d

### Database SHA1 Commit Hash

ea7bd1eae4380310d275a52a4868efc4315c070c

### Operating System

Slackware64-current

### Client Version

1.12.1 (Classic)

**Comment by AnonXS** [comment]
Can not reproduce in tbcmangos.
Can not reporoduce in classicmangos on commit b2940c798686956e64fb5508da42c44c7000f16d.
i think your crash reason is somewhere else.

**Comment by f0n1x** [comment]
This is feeling more and more like a loot system issue.
I have actually noticed that the server seems to crash exactly when killing a mob.
I think CMSG_ATTACKSWING may be a red herring and the actual culprit is:
"08:34:53 Loot::CreateLoot> cannot create corpse loot, FillLoot failed with loot id(0)!"
I'm actually rebuilding my server next week and will report back with debug logs.

**Comment by insunaa** [comment]
Please recreate the problem with a debugger attached and then post the full backtrace. Logs are seldom useful when diagnosing memory access violations

**Comment by f0n1x** [comment]
Opened a new report with proper gdb backtraces @ 3307.

**Comment by AnonXS** [comment]
https://github.com/cmangos/issues/issues/3307
