### ISSUE TITLE
💬 [Support Request] 

### ISSUE THREAD

**Issue by zZDOCZz** [cmangos/issues#3299]
### Core Version

mangos-tbc

### Support Request Details

how can i add custom scripts?
like add bosses with custom attack rotation and...

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

eb960e33f165cc1ab97dd9c5ab51d226f3381871

### Database SHA1 Commit Hash

b39df8ad0e4edeb4b0bb2882f3d255aa07f4ce7a

### Server Operating System

Windows

### Client Version

2.4.3 (The Burning Crusade)

### Client Operating System

Windows

**Comment by AnonXS** [comment]
custom scripts are not supported here, support is for setting up the codebase.

i suggest you start out by learning about the existing codebase.
