### ISSUE TITLE
🐛 [Bug Report] Kinds of aoe spell broken after commit [Unit: Implement Chain Immunity setting] commit 9916fd4

### ISSUE THREAD

**Issue by betayi** [cmangos/issues#3301]
### Bug Details

This commit broke kinds of multi target spell , like hunte's multi-shot warlock Felguard‘s Cleave， there're more aoe skill not in test list, but this logic effect a lot

### Steps to Reproduce

1.make a hunter with multi-shot
2.aggro with a lot of creature
3.cast multi-shot
4.only one target make damage done

### Core SHA1 Commit Hash

762fdaa

### Database SHA1 Commit Hash

e20d0ca

### Operating System

unbuntu20.04

### Client Version

2.4.3 (The Burning Crusade)

**Comment by kelbren** [comment]
Confirmed in WotlK as well, multi-shot does not work. only affects one target now.
