### ISSUE TITLE
🐛 [Bug Report] Mage Portals do not work

### ISSUE THREAD

**Issue by f0n1x** [cmangos/issues#3308]
### Bug Details

Casting any of the mage portals works, but clicking on them does nothing.

### Steps to Reproduce

1. Create a Mage.
2. Level to 40 or 50.
3. Learn Portal to Orgrimmar/Undercity/Stormwind/Ironforge (40) or ThunderBluff/Darnassus (50).
4. Obtain reagents (Rune of Portals).
5. Cast a portal for one of the locations.
6. Attempt to right-click on the portal.

### Expected behavior

Person clicking on the portal (if grouped with the mage, or the mage themselves) should be teleported to the location of the portal.

### Crash Log

No crashes, just non-functioning portals.

### Core SHA1 Commit Hash

559c0cc4d127233ac2bae4824cc547717bed2658

### Database SHA1 Commit Hash

45d8f524bfd3b27e0f3aa2d0ca38da53611e25c4

### Operating System

Slackware64-15.0

### Client Version

1.12.1 (Classic)

**Comment by celguar** [comment]
can confirm

**Comment by Pnumekin** [comment]
Confirm this bug, it may be a general problem with portals because other portals are concerned.
Got to Maraudon with Scepter of Celebras, use it in the square portal area, the portal shows up but nothing happens if you click on it.
Warlock TP portal seems to have the same problem.

**Comment by miraco** [comment]
Works for me on mangos-tbc
prob a classic only bug

**Comment by celguar** [comment]
confirmed on latest classic

**Comment by al3xc1985** [comment]
wotlk works

**Comment by f0n1x** [comment]
portals confirmed working in vanilla with this patch, thanks kw!
