### ISSUE TITLE
🐛 [Bug Report] Server crash when Playerbot fighting Atal'ai Deathwalker's Spirit

### ISSUE THREAD

**Issue by f0n1x** [cmangos/issues#3310]
### Bug Details

When playbot is fighting Atalai Deathwalker's Spirits the server may crash

### Steps to Reproduce

1. Enter Sunken Temple
2. Take a hard left and go to the top
3. Target and kill the 6 trolls above the room channeling to keep the shield protecting Jammal'an's room up
4. Enter Jammal'an's room (East wing)
5. Summon a Playerbot and add it to your group
6. Kill an Atal'ai Deathwalker, a spirit will be summoned
7. Let the playerbot attack the summoned Atal'ai Deathwalker's Spirit

### Expected behavior

No server crash

### Crash Log

1st crash:
#0  0x0000000000b5cd8b in PlayerbotAI::Attack(Unit*) ()
#1  0x0000000000b5de88 in PlayerbotAI::DoNextCombatManeuver() ()
#2  0x00000000008ca02b in Player::Update(unsigned int) ()
#3  0x0000000000ada60e in Map::Update(unsigned int const&) ()
#4  0x0000000000aef325 in ?? ()
#5  0x0000000000af9ef0 in MapUpdater::WorkerThread() ()
#6  0x00007f90f48db884 in ?? () from /usr/lib64/libstdc++.so.6
#7  0x00007f90f51a3e45 in start_thread () from /lib64/libpthread.so.0
#8  0x00007f90f472c4af in clone () from /lib64/libc.so.6

2nd crash:
#0  0x00007f714da5c868 in raise () from /lib64/libc.so.6
#1  0x00007f714da43546 in abort () from /lib64/libc.so.6
#2  0x0000000000b5cdd0 in PlayerbotAI::Attack(Unit*) ()
#3  0x0000000000b5de88 in PlayerbotAI::DoNextCombatManeuver() ()
#4  0x00000000008ca02b in Player::Update(unsigned int) ()
#5  0x0000000000ada60e in Map::Update(unsigned int const&) ()
#6  0x0000000000aef325 in ?? ()
#7  0x0000000000af9ef0 in MapUpdater::WorkerThread() ()
#8  0x00007f714dcdb884 in ?? () from /usr/lib64/libstdc++.so.6
#9  0x00007f714e530e45 in start_thread () from /lib64/libpthread.so.0
#10 0x00007f714db2c4af in clone () from /lib64/libc.so.6

3rd crash:
#0  0x0000000000b5d8a0 in PlayerbotAI::IsNeutralized(Unit*) ()
#1  0x0000000000b5cf05 in PlayerbotAI::GetCombatTarget(Unit*) ()
#2  0x0000000000b5cd34 in PlayerbotAI::Attack(Unit*) ()
#3  0x0000000000b5de88 in PlayerbotAI::DoNextCombatManeuver() ()
#4  0x00000000008ca02b in Player::Update(unsigned int) ()
#5  0x0000000000ada60e in Map::Update(unsigned int const&) ()
#6  0x0000000000aef325 in ?? ()
#7  0x0000000000af9ef0 in MapUpdater::WorkerThread() ()
#8  0x00007f39ddedb884 in ?? () from /usr/lib64/libstdc++.so.6
#9  0x00007f39de662e45 in start_thread () from /lib64/libpthread.so.0
#10 0x00007f39ddd2c4af in clone () from /lib64/libc.so.6

4th crash:
#0  0x0000000000b5d8a0 in PlayerbotAI::IsNeutralized(Unit*) ()
#1  0x0000000000b5cf05 in PlayerbotAI::GetCombatTarget(Unit*) ()
#2  0x0000000000b5cd34 in PlayerbotAI::Attack(Unit*) ()
#3  0x0000000000b5de88 in PlayerbotAI::DoNextCombatManeuver() ()
#4  0x00000000008ca02b in Player::Update(unsigned int) ()
#5  0x0000000000ada60e in Map::Update(unsigned int const&) ()
#6  0x0000000000aef325 in ?? ()
#7  0x0000000000af9ef0 in MapUpdater::WorkerThread() ()
#8  0x00007f50160db884 in ?? () from /usr/lib64/libstdc++.so.6
#9  0x00007f5016865e45 in start_thread () from /lib64/libpthread.so.0
#10 0x00007f5015f2c4af in clone () from /lib64/libc.so.6

5th crash:
#0  0x0000000000b5cd8b in PlayerbotAI::Attack(Unit*) ()
#1  0x0000000000b5de88 in PlayerbotAI::DoNextCombatManeuver() ()
#2  0x00000000008ca02b in Player::Update(unsigned int) ()
#3  0x0000000000ada60e in Map::Update(unsigned int const&) ()
#4  0x0000000000aef325 in ?? ()
#5  0x0000000000af9ef0 in MapUpdater::WorkerThread() ()
#6  0x00007f058fcdb884 in ?? () from /usr/lib64/libstdc++.so.6
#7  0x00007f059061ce45 in start_thread () from /lib64/libpthread.so.0
#8  0x00007f058ff2c4af in clone () from /lib64/libc.so.6

### Core SHA1 Commit Hash

559c0cc4d127233ac2bae4824cc547717bed2658

### Database SHA1 Commit Hash

45d8f524bfd3b27e0f3aa2d0ca38da53611e25c4

### Operating System

Slackware64-15.0

### Client Version

1.12.1 (Classic)

**Comment by f0n1x** [comment]
This seems to happen with any playerbot fighting a mob that despawns instead of dying. Maybe due to the lack of some check to see if the mob is still a valid target? I'm hopeful that once evil-at-wow's recent TBC playerbot patches (https://github.com/cmangos/mangos-tbc/compare/2d4e92ab6566...12cc6dfb002e) are backported to classic (vanilla) that this might be resolved.

**Comment by f0n1x** [comment]
Now that a bunch of the playerbot patches have been backported to classic, I decided to revisit this.

New Crash Logs:
1st crash:
#0  std::less<unsigned int>::operator() (this=0x7f1fe2b1f570, __x=<error reading variable>, __y=<optimized out>)
    at /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/stl_function.h:386
386	      { return __x < __y; }
[Current thread is 1 (Thread 0x7f1ffaf44640 (LWP 25431))]
(gdb) bt
#0  std::less<unsigned int>::operator() (this=0x7f1fe2b1f570, __x=<error reading variable>, __y=<optimized out>)
    at /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/stl_function.h:386
#1  std::_Rb_tree<unsigned int, std::pair<unsigned int const, SpellAuraHolder*>, std::_Select1st<std::pair<unsigned int const, SpellAuraHolder*> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, SpellAuraHolder*> > >::equal_range (this=0x7f1fe2b1f570, __k=<optimized out>)
    at /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/stl_tree.h:2003
#2  std::multimap<unsigned int, SpellAuraHolder*, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, SpellAuraHolder*> > >::equal_range (
    this=0x7f1fe2b1f570, __x=<optimized out>) at /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/stl_multimap.h:1048
#3  Unit::GetSpellAuraHolderBounds (this=0x7f1fe2b1efa0, spell_id=118)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/../../Entities/Unit.h:1631
#4  Unit::HasAura (this=0x7f1fe2b1efa0, spellId=118, effIndex=EFFECT_INDEX_0)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Unit.cpp:5472
#5  PlayerbotAI::IsNeutralized (target=0x7f1fe2b1efa0)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/PlayerbotAI.cpp:5438
#6  0x0000000000b7ad45 in PlayerbotAI::GetCombatTarget (this=0x7f1fce8a5290, forcedTarget=<optimized out>)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/PlayerbotAI.cpp:2224
#7  0x0000000000b7ab74 in PlayerbotAI::Attack (this=0x7f1fce8a5290, forcedTarget=0x0)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/PlayerbotAI.cpp:2169
#8  0x0000000000b7bcc8 in PlayerbotAI::DoNextCombatManeuver (this=0x7f1fce8a5290)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/PlayerbotAI.cpp:2314
#9  0x00000000008d89ab in Player::Update (this=0x7f1fb2d70b10, diff=<optimized out>)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Player.cpp:1567
#10 0x0000000000af19de in Map::Update (this=<optimized out>, t_diff=@0x7f1fb2d546a8: 100)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/Map.cpp:736
#11 0x0000000000b0c3e5 in MapUpdateWorker::execute (this=0x7f1fb2d54690)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/MapWorkers.h:52
#12 0x0000000000b16fb1 in MapUpdater::WorkerThread (this=0x56f0c50)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/MapUpdater.cpp:96
#13 0x00007f20220db884 in ?? () from /usr/lib64/libstdc++.so.6
#14 0x00007f202291de45 in start_thread () from /lib64/libpthread.so.0
#15 0x00007f2021f2c4af in clone () from /lib64/libc.so.6

2nd crash:
#0  0x00007f754005c868 in raise () from /lib64/libc.so.6
#1  0x00007f7540043546 in abort () from /lib64/libc.so.6
#2  0x0000000000b7ac10 in Object::GetUInt64Value (this=0x7f7500a1e850, index=0)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Object.h:441
#3  Object::GetGuidValue (this=0x7f7500a1e850, index=0) at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Object.h:465
#4  Object::GetObjectGuid (this=0x7f7500a1e850) at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Object.h:385
#5  PlayerbotAI::Attack (this=0xe088680, forcedTarget=<optimized out>)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/PlayerbotAI.cpp:2178
#6  0x0000000000b7bcc8 in PlayerbotAI::DoNextCombatManeuver (this=0xe088680)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/PlayerbotAI.cpp:2314
#7  0x00000000008d89ab in Player::Update (this=0x7f7516341f20, diff=<optimized out>)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Player.cpp:1567
#8  0x0000000000af19de in Map::Update (this=<optimized out>, t_diff=@0x7f75163b1b88: 100)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/Map.cpp:736
#9  0x0000000000b0c3e5 in MapUpdateWorker::execute (this=0x7f75163b1b70)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/MapWorkers.h:52
#10 0x0000000000b16fb1 in MapUpdater::WorkerThread (this=0x599ec90)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/MapUpdater.cpp:96
#11 0x00007f75402db884 in ?? () from /usr/lib64/libstdc++.so.6
#12 0x00007f7540c15e45 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f754012c4af in clone () from /lib64/libc.so.6

3rd crash:
#0  std::less<unsigned int>::operator() (this=0x7fe474fae000, __x=<error reading variable>, __y=<optimized out>)
    at /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/stl_function.h:386
#1  std::_Rb_tree<unsigned int, std::pair<unsigned int const, SpellAuraHolder*>, std::_Select1st<std::pair<unsigned int const, SpellAuraHolder*> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, SpellAuraHolder*> > >::equal_range (this=0x7fe474fae000, __k=<optimized out>)
    at /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/stl_tree.h:2003
#2  std::multimap<unsigned int, SpellAuraHolder*, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, SpellAuraHolder*> > >::equal_range (
    this=0x7fe474fae000, __x=<optimized out>) at /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/stl_multimap.h:1048
#3  Unit::GetSpellAuraHolderBounds (this=0x7fe474fada30, spell_id=118)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/../../Entities/Unit.h:1631
#4  Unit::HasAura (this=0x7fe474fada30, spellId=118, effIndex=EFFECT_INDEX_0)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Unit.cpp:5472
#5  PlayerbotAI::IsNeutralized (target=0x7fe474fada30)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/PlayerbotAI.cpp:5438
#6  0x0000000000b7ad45 in PlayerbotAI::GetCombatTarget (this=0xbf04890, forcedTarget=<optimized out>)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/PlayerbotAI.cpp:2224
#7  0x0000000000b7ab74 in PlayerbotAI::Attack (this=0xbf04890, forcedTarget=0x0)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/PlayerbotAI.cpp:2169
#8  0x0000000000b7bcc8 in PlayerbotAI::DoNextCombatManeuver (this=0xbf04890)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/PlayerbotAI.cpp:2314
#9  0x00000000008d89ab in Player::Update (this=0x7fe48625c090, diff=<optimized out>)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Player.cpp:1567
#10 0x0000000000af19de in Map::Update (this=<optimized out>, t_diff=@0x7fe4862fb858: 101)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/Map.cpp:736
#11 0x0000000000b0c3e5 in MapUpdateWorker::execute (this=0x7fe4862fb840)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/MapWorkers.h:52
#12 0x0000000000b16fb1 in MapUpdater::WorkerThread (this=0x4be3c90)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/MapUpdater.cpp:96
#13 0x00007fe4b78db884 in ?? () from /usr/lib64/libstdc++.so.6
#14 0x00007fe4b81f7e45 in start_thread () from /lib64/libpthread.so.0
#15 0x00007fe4b772c4af in clone () from /lib64/libc.so.6

4th crash:
#0  0x00007f9f02c5c868 in raise () from /lib64/libc.so.6
#1  0x00007f9f02c43546 in abort () from /lib64/libc.so.6
#2  0x0000000000b7ac10 in Object::GetUInt64Value (this=0x7f9ed0d41160, index=0)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Object.h:441
#3  Object::GetGuidValue (this=0x7f9ed0d41160, index=0) at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Object.h:465
#4  Object::GetObjectGuid (this=0x7f9ed0d41160) at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Object.h:385
#5  PlayerbotAI::Attack (this=0x7f9ece270cd0, forcedTarget=<optimized out>)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/PlayerbotAI.cpp:2178
#6  0x0000000000b7bcc8 in PlayerbotAI::DoNextCombatManeuver (this=0x7f9ece270cd0)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/PlayerbotAI.cpp:2314
#7  0x00000000008d89ab in Player::Update (this=0x7f9ece26ad00, diff=<optimized out>)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Player.cpp:1567
#8  0x0000000000af19de in Map::Update (this=<optimized out>, t_diff=@0x7f9ece39aee8: 101)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/Map.cpp:736
#9  0x0000000000b0c3e5 in MapUpdateWorker::execute (this=0x7f9ece39aed0)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/MapWorkers.h:52
#10 0x0000000000b16fb1 in MapUpdater::WorkerThread (this=0x5826c90)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/MapUpdater.cpp:96
#11 0x00007f9f02edb884 in ?? () from /usr/lib64/libstdc++.so.6
#12 0x00007f9f037d6e45 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f9f02d2c4af in clone () from /lib64/libc.so.6

5th crash:
#0  __gnu_cxx::new_allocator<std::_List_node<ObjectGuid> >::construct<ObjectGuid, ObjectGuid const&> (this=0x7fe6fe36c628, __p=0x7fe6e88bbe70, __args=...)
    at /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/ext/new_allocator.h:162
#1  std::allocator_traits<std::allocator<std::_List_node<ObjectGuid> > >::construct<ObjectGuid, ObjectGuid const&> (__a=..., __p=0x7fe6e88bbe70, __args=...)
    at /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/alloc_traits.h:512
#2  std::__cxx11::list<ObjectGuid, std::allocator<ObjectGuid> >::_M_create_node<ObjectGuid const&> (this=0x7fe6fe36c628, __args=...)
    at /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/stl_list.h:637
#3  std::__cxx11::list<ObjectGuid, std::allocator<ObjectGuid> >::_M_insert<ObjectGuid const&> (this=0x7fe6fe36c628, __position={m_guid = 21}, __args=...)
    at /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/stl_list.h:1911
#4  std::__cxx11::list<ObjectGuid, std::allocator<ObjectGuid> >::push_back (this=0x7fe6fe36c628, __x=...)
    at /usr/bin/../lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../include/c++/11.2.0/bits/stl_list.h:1212
#5  PlayerbotAI::Attack (this=0x7fe6fe36c530, forcedTarget=<optimized out>)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/PlayerbotAI.cpp:2178
#6  0x0000000000b7bcc8 in PlayerbotAI::DoNextCombatManeuver (this=0x7fe6fe36c530)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/PlayerBot/Base/PlayerbotAI.cpp:2314
#7  0x00000000008d89ab in Player::Update (this=0x7fe6fe318240, diff=<optimized out>)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Entities/Player.cpp:1567
#8  0x0000000000af19de in Map::Update (this=<optimized out>, t_diff=@0x7fe6fe39b928: 101)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/Map.cpp:736
#9  0x0000000000b0c3e5 in MapUpdateWorker::execute (this=0x7fe6fe39b910)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/MapWorkers.h:52
#10 0x0000000000b16fb1 in MapUpdater::WorkerThread (this=0x556ac90)
    at /tmp/SBo/mangos-classic-5c64aab6a404d5e1ea36bb20a77866848bdefdcf/src/game/Maps/MapUpdater.cpp:96
#11 0x00007fe727adb884 in ?? () from /usr/lib64/libstdc++.so.6
#12 0x00007fe7283fbe45 in start_thread () from /lib64/libpthread.so.0
#13 0x00007fe72792c4af in clone () from /lib64/libc.so.6

Core SHA1 Commit Hash:
5c64aab6a404d5e1ea36bb20a77866848bdefdcf

Database SHA1 Commit Hash:
008d36f09fdb7e25ba58db34b8da47a8fa05e660

**Comment by insunaa** [comment]
Closing due to deprecation of the old bots.
