### ISSUE TITLE
🐛 [Bug Report] Dire maul Mobs can't attack or be attacked by the player

### ISSUE THREAD

**Issue by AldebaraanMKII** [cmangos/issues#3312]
### Bug Details

This happens on gordok commons. Several mobs there (e.g. Gordok Brutes) don't attack the player nor can be attacked.

### Steps to Reproduce

1. Go to gordok commons
2. Try to attack the mobs or aggro them

### Expected behavior

That they react to the player

### Core SHA1 Commit Hash

559c0cc4d127233ac2bae4824cc547717bed2658

### Database SHA1 Commit Hash

14648a47039f968ec0b09ab395c52fc1135cd9fb

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
https://github.com/cmangos/wotlk-db/commit/110c0f17062dd1f459bdb908504b33ecfa9fcaf1
