### ISSUE TITLE
🐛 [Bug Report] Field Duty quest bugged

### ISSUE THREAD

**Issue by AldebaraanMKII** [cmangos/issues#3313]
### Bug Details

After signing the papers in the quest, you're supposed to talk to Janela Stouthammer for a Hive zora abomination to spawn, but this doesn't occur.

### Steps to Reproduce

1. Sign in the papers while in the camp
2. Talk to Janela Stouthammer
3. No abomination spawns

### Core SHA1 Commit Hash

559c0cc4d127233ac2bae4824cc547717bed2658

### Database SHA1 Commit Hash

14648a47039f968ec0b09ab395c52fc1135cd9fb

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by KernelPanic22** [comment]
Confirmed that the fight with Hive Zora Abomination never starts

Steps to Reproduce
.quest add 8507
.go creature janela stouthammer
talk

FYI Horde side you can turn in the note without the fight.

![Screenshot from 2023-06-25 23-18-29](https://github.com/cmangos/issues/assets/38465292/b3f3e6c2-661e-4321-a9fc-1dce2ae6002a)

![Screenshot from 2023-06-25 23-42-34](https://github.com/cmangos/issues/assets/38465292/82ae8ed2-5133-48d6-9bd6-93de9dedea84)


**Core SHA1 Commit Hash**
afc0f711db2430bc6580b13444829197fe6096ae

**Database SHA1 Commit Hash**
d39846b65747d0184b5a2fadd5354866143a1587

**Comment by KernelPanic22** [comment]
Missed link of Janela Stouthammer with [quest](https://www.wowhead.com/classic/quest=8508/field-duty-papers)
possible fix

 INSERT INTO classicmangos.creature_involvedrelation (id, quest) VALUES(15612, 8508);

INSERT INTO classicmangos.creature_questrelation(id, quest) VALUES(15612, 8508);
