### ISSUE TITLE
🐛 [Bug Report] Gnomeregan Data Rescue Quest crashes the server

### ISSUE THREAD

**Issue by AldebaraanMKII** [cmangos/issues#3314]
### Bug Details

In the Data Rescue Quest, when using the yellow card to obtain the blue card, the server crashes every time
tried twice already
https://www.wowhead.com/classic/quest=2930/data-rescue

### Steps to Reproduce

1. Try to use a yellow card to obtain a blue card in Gnomeregan

### Core SHA1 Commit Hash

559c0cc4d127233ac2bae4824cc547717bed2658

### Database SHA1 Commit Hash

14648a47039f968ec0b09ab395c52fc1135cd9fb

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by kelbren** [comment]
I ran this in my WotLK build, everything is current and no crash. cards worked fine, and quest completed correctly.
I was not able to test TBC or Classic

**Comment by insunaa** [comment]
I just tried, the first time I attempted to do this my server crashed, then when I attached the debugger and tried to recreate the steps I took it didn't crash anymore. I do always get an "Invalid target" message when the yellow punch card is turned into a blue punch card, so maybe the spell isn't quite coded correctly

**Comment by evil-at-wow** [comment]
I tested this several times in TBC (core hash f89e3d712dcf9a5f3719cbc1076f1f50eafcefc9, database hash b48a0814733bea720c06dbdd20863f1642faa290 so more recent than the report but not the latest) in both GM mode on and off, and this seemed to work fine for me. 

I'm not sure what core insunaa tested, but this could be Wrath specific?

**Comment by al3xc1985** [comment]
Wrath tested by me and it crashes 

Server updates till the day I wrote added

**Comment by RaenaLoa** [comment]
Tested yesterday with all code updated through then and this crash still occurs on wotlk. 

Core: 1d8a07a46ee16fc0400e99c03292fe2cda6c974a
DB:    b2e5867a5018f1b2f11e51e2c5e0a3dc6d5eeb2b

**Comment by adellaci** [comment]
I tested today and it did not crash  (WoTLK)
Core: 92612ede3331f05ee148364beee09ef64100d6c1
DB a24bd2dd7cec2345c5b4c0798a359d6d0bab0fb8

If some one could check Classic, & TBC

**Comment by adellaci** [comment]
Checked it today, it is working again. This can be closed.

**Comment by insunaa** [comment]
In my testing the crash only happened sporadically. Are you sure that it's really working again reliably?

**Comment by adellaci** [comment]
I will test it a couple more time, then i will recompile without DPCH and see if that made the difference
