### ISSUE TITLE
🐛 [Bug Report] Hunter's multiple shots, Warrior's cleave, etc. . AOE Spell can only hit one target

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#3318]
### Bug Details

Hunter's multiple shots, Shaman's lightning chain, Warrior's cleave, Druid's sweep, etc. . All AOE Spell can only hit one target;

Because of ChangeTime: 2023/2/5 22:23:13 Hash: 9916fd4075c5ab21e77d27678d32ce69e4ccb6b2

Please repair this problem,Thanks.

### Steps to Reproduce

1. Hunter's multiple shots, Shaman's lightning chain, Warrior's cleave, Druid's sweep, etc.
2. Greater than one enemy creature.
3. Only one enemy creature was hurt.

### Core SHA1 Commit Hash

9916fd4075c5ab21e77d27678d32ce69e4ccb6b2

### Database SHA1 Commit Hash

9916fd4075c5ab21e77d27678d32ce69e4ccb6b2

### Operating System

win10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
This was fixed a while ago. Please update your core.
