### ISSUE TITLE
🐛 [Bug Report] [Wotlk] Silithid Swarm Levels not Setting Properly

### ISSUE THREAD

**Issue by RaenaLoa** [cmangos/issues#3319]
### Bug Details

Silithid swarms spawning in Southern Barrens spawn at inappropriately high levels and prevent completion of the quest in the area (Silithid Eggs)

### Steps to Reproduce

1. Travel to Southern Barrens to silithid area (south of Taurajo)
2. Locate a Silithid Swarmer (ID 3252) and engage combat
3. Silithid swarm (ID 4196) that spawns (via spell ID 6589) is much higher level than summoning npc

### Expected behavior

Silithid swarm should be the NPC level when summoned

### Suggested Workaround

Reduced npc 4196 to max level 20 in DB to prevent higher level spawn but this means the higher level spawns will spawn inappropriately low now but too high makes the lower level quests in Barrens impossible without reduction of level. 

### Core SHA1 Commit Hash

5aaec2250262707f406f3bdde40f6b6d1247661c

### Database SHA1 Commit Hash

833d547627986bbcb8fa30b1ae455388083958c5

### Operating System

Ubuntu Server 20.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
In the end of the day, their level does not influence anything, they have a 100% hit aura passive and always die in one hit.
their level is just cosmetic change in wotlk.
and if you multiply no damage with a multiplier of 0.0001 it is still no dmg for a mob of the same level as the summoner. (but yea maybe check if these base parameters are correctly set)

**Comment by RaenaLoa** [comment]
Just for what it's worth... I was unable to hit them because their damage output was scaling higher and killing you too fast to get the hit off. I'll try to upload some combat logs or video.

**Comment by RaenaLoa** [comment]
https://www.youtube.com/watch?v=GPoDcfwCDOs

**Comment by Grz3s** [comment]
fixed
