### ISSUE TITLE
🐛 [Bug Report] Torgos can't be attacked

### ISSUE THREAD

**Issue by AldebaraanMKII** [cmangos/issues#3320]
### Bug Details

Torgos from [this quest](https://www.wowhead.com/wotlk/quest=10035/torgos) can't be attacked after being spawned by using the carcass.

### Steps to Reproduce

1. Use the carcass at the scarecrow
2. Wait for him to spawn
3. Try to attack (you will receive a notification that you cannot attack that target)

### Core SHA1 Commit Hash

5aaec2250262707f406f3bdde40f6b6d1247661c

### Database SHA1 Commit Hash

833d547627986bbcb8fa30b1ae455388083958c5

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by kelbren** [comment]
I was able to confirm this problem.
solved it by updating the database:
UPDATE `creature_template` SET `UnitFlags` = 0 WHERE  `Entry` = 18707; -- Torgos  

This fixed the issue and quest was completed normally.

**Comment by Grz3s** [comment]
:)
