### ISSUE TITLE
🐛 [Bug Report] Quest: Tablet of the Seven (quest: 4296)

### ISSUE THREAD

**Issue by f0n1x** [cmangos/issues#3325]
### Bug Details

Interactive object (id: 169294) does not open a window to show interactive gossip text. Throws in game error: "Already open".

### Steps to Reproduce

1. Create any character (horde/alliance).
2. Level to 50.
3. Navigate to Flame Crest, Burning Steppes.
4. Speak with Maxwort Uberglint (npc: 9536).
5. Accept the quest "Tablet of the Seven" (quest: 4296).
6. Go to location ~54, 41 in Burning Steppes.
7. Interact with "Tablet of the Seven" (object: 169294).
8. Receive Error: "Already open".

### Expected behavior

Video of expected behavior:
https://www.youtube.com/watch?v=v8zy820PL3U

### Core SHA1 Commit Hash

5a59df65d5662cdc4f3e2a844b35fd1a705096e6

### Database SHA1 Commit Hash

592c8075594a7a63d3fee4f2fe1f95e8fcdf0655

### Operating System

Slackware64-15.0

### Client Version

1.12.1 (Classic)

**Comment by f0n1x** [comment]
To add to the above, I've been digging around in the db, and it seems the quest entry for 4296 under `quest_template` is correct.
The object entry for 'Tablet of the Seven' (169294) under `gameobject_template` says type=2 (questgiver), data2=2 (pagematerial=stone), data3=2187 (gossipID).
Looking at entry 2187 under `gossip_menu` has text_id=2819, however `npc_text.id` does not have an entry for 2819.
There IS however and entry for 2187 under `gossip_menu_option` that seems to have the correct information (with a typo of "Trascript the Tablet" instead of "Transcribe the Tablet"
I could be following my pointers incorrectly or misunderstanding how this is configured, but this is what I'm seeing.

**Comment by Grz3s** [comment]
![regu](https://user-images.githubusercontent.com/2374069/227805464-5d217ee4-202c-429b-9240-04fcadcecf5c.jpg)
can't reproduce this on WoTLKDB

**Comment by f0n1x** [comment]
![tablet7error](https://user-images.githubusercontent.com/31575758/227805819-20a3aca4-d15d-4217-a70c-0dc346d08f27.png)
I know it's somewhat implied, but I'm running vanilla (1.12.1)

**Comment by f0n1x** [comment]
Not sure if a commit fixed this or not, but this is now working.
