### ISSUE TITLE
🐛 [WOTLK] Glyph of Blessing of Wisdom & Might Duration Bug

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3326]
### Bug Details

https://www.wowhead.com/wotlk/item=43366/glyph-of-blessing-of-wisdom
https://www.wowhead.com/wotlk/spell=58314/glyph-of-blessing-of-might

This glyphs should increase duration of blessing of wisdom and might casted on you with 20 min, resulting in a total of 30 min.

Currently no effect occurs when u apply any of this glyphs.

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by virusav** [comment]
Requires intervention from those who understand the spell system.

```C++
void Spell::DoSpellHitOnUnit(Unit* unit, uint32 effectMask, TargetInfo* target, bool isReflected)
...
    // now apply all created auras
    if (m_spellAuraHolder)
    {
        // normally shouldn't happen
        if (!m_spellAuraHolder->IsEmptyHolder())
        {
            int32 duration = m_spellAuraHolder->GetAuraMaxDuration();
            int32 originalDuration = duration;

            if (duration > 0 && target->diminishGroup > DIMINISHING_NONE)
            {
                duration = target->diminishDuration;
                // Fully diminished
                if (duration == 0)
                {
                    delete m_spellAuraHolder;
                    m_spellAuraHolder = nullptr;
                    return;
                }
            }
```
m_spellInfo->Id = 48936 (level 9)
duration = 600000
target->diminishGroup = DIMINISHING_NONE
**target->diminishDuration = 1800000**
**target->effectDuration = 1800000**

We don't get into the block
```C++
            if (duration > 0 && target->diminishGroup > DIMINISHING_NONE)
```
therefore the value is not taken from **target->diminishDuration**.

The **target->effectDuration** value is not taken into account at all.
I added 2 lines **for testing**:
```C++
            if (target->effectDuration != duration)
                duration = target->effectDuration;
```
after the block
```C++
            if (duration > 0 && target->diminishGroup > DIMINISHING_NONE)
```
Now the time is calculated taking into account the glyph.
The buff is applied to other NPCs without taking into account the glyph, as it should be.
On a player without a glyph, time is like on an NPC, as it should be.
![WoWScrnShot_092523_171402](https://github.com/cmangos/issues/assets/323130/39ec13eb-5a39-45ae-a20d-697a2ed554f8)

As I already wrote at the very beginning, only those who understand the spell system can write the right place and the right code.
So let's hope they find the right solution.)

**Comment by insunaa** [comment]
```cpp
            //int32 duration = m_spellAuraHolder->GetAuraMaxDuration();
            //int32 originalDuration = duration;
            int32 duration = target->effectDuration;
            int32 originalDuration = m_spellAuraHolder->GetAuraMaxDuration();
```
in Spell.cpp:1600
should fix it

changed it to this because I think a diminishing spell should also diminish based on the proper maximum value after modifiers, instead of the maximum value before modifiers. not sure if originalDuration should be GetMaxAuraDuration() or a copy of duration tho

**Comment by al3xc1985** [comment]
Fixed by latest changes
