### ISSUE TITLE
🐛 [Bug Report] Creature in water can't move if we attack it from land (mmap issue)

### ISSUE THREAD

**Issue by Novivy** [cmangos/issues#3327]
### Bug Details

It happens to all creatures in water, unless you add the ExtraFlag `0×00004000 CREATURE_EXTRA_FLAG_MMAP_FORCE_DISABLE` to it.

For info, the creature in the example have the following ExtraFlags: `0×00008000	CREATURE_EXTRA_FLAG_WALK_IN_WATER`, InhabitType is `3	Both Ground And Water Movement`

I tried with HD and non HD maps extracts, same result.

https://user-images.githubusercontent.com/50490687/228079337-58d32423-fcc7-494e-84da-67327a09356a.mp4

### Steps to Reproduce

0. `.gm off` `.gm visible on` 
1. `.go crea 38516` (entry 2231)
2. Stand 10 yards from the shore and target the creature in water
3. `.damage 1`
4. Creature won't move

### Expected behavior

Creature can go out the water to attack you

### Core SHA1 Commit Hash

ef797221800493d26e4f5b17d34389953c591d7b

### Database SHA1 Commit Hash

14648a47039f968ec0b09ab395c52fc1135cd9fb

### Operating System

Debian 11

### Client Version

1.12.1 (Classic)

**Comment by miraco** [comment]
https://github.com/cmangos/issues/issues/2986#issuecomment-1485024006
Already reported here
