### ISSUE TITLE
🐛 [Bug Report] Enraged spirits quests

### ISSUE THREAD

**Issue by AldebaraanMKII** [cmangos/issues#3339]
### Bug Details

https://www.wowhead.com/tbc/quest=10458/enraged-spirits-of-fire-and-earth
https://www.wowhead.com/tbc/quest=10480/enraged-spirits-of-water
https://www.wowhead.com/tbc/quest=10481/enraged-spirits-of-air

In the quests above, when using the totem and killing the elementals nearby, the souls don't get captured and thus the quest can't be completed without console commands.

### Steps to Reproduce

1. With the quests active place a totem on the ground
2. Aggro a elemental and kill it near the totem

### Core SHA1 Commit Hash

a90a4a37ded5ea23099335fbc6c18e8de44d93c3

### Database SHA1 Commit Hash

65cc788c47b2b08c94ebff7dab26d0a7cc11b595

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Grz3s** [comment]
duplicate
https://github.com/cmangos/wotlk-db/issues/486
