### ISSUE TITLE
🐛 [Bug Report] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by AldebaraanMKII** [cmangos/issues#3345]
### Bug Details

https://www.wowhead.com/wotlk/quest=12237/flight-of-the-wintergarde-defender

Rescuing villagers doesn't work: they run to the keep but the number of rescued doesn't increase.
The "quest rescue from town square" which involves the same villagers works.

### Steps to Reproduce

1. Kill the geists guarding the villagers

### Core SHA1 Commit Hash

a90a4a37ded5ea23099335fbc6c18e8de44d93c3

### Database SHA1 Commit Hash

65cc788c47b2b08c94ebff7dab26d0a7cc11b595

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Grz3s** [comment]
`Rescuing villagers doesn't work: they run to the keep but the number of rescued doesn't increase.
The "quest rescue from town square" which involves the same villagers works.`
You're wrong here...  You suposed to grab [`c.Helpless Wintergarde Villager`](https://www.wowhead.com/wotlk/npc=27315/helpless-wintergarde-villager)  They are running around `The Carrion Fields`

Just tested it and works perfect:
![dawdwa](https://user-images.githubusercontent.com/2374069/230244442-9cdbfd05-b660-4324-9746-abdde53082fc.jpg)
