### ISSUE TITLE
🐛 [Bug Report] Trying to enter shredder causes player to disconnect

### ISSUE THREAD

**Issue by AldebaraanMKII** [cmangos/issues#3348]
### Bug Details

https://www.wowhead.com/wotlk/quest=12050/lumber-hack
"Player xxx from account id xxx kicked for incorrect speed (must be 6.944441 instead 7.000000)"

### Steps to Reproduce

1. Use the item to spawn the shredder
2. Try to enter it

### Core SHA1 Commit Hash

a90a4a37ded5ea23099335fbc6c18e8de44d93c3

### Database SHA1 Commit Hash

65cc788c47b2b08c94ebff7dab26d0a7cc11b595

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Grz3s** [comment]
Can't reproduce it...
![dwadawułu](https://user-images.githubusercontent.com/2374069/231296949-aa7a1ad9-dd06-4948-81ef-e5d631c38281.jpg)


PLS recheck it with latest core and db ver...

**Comment by al3xc1985** [comment]
I tested that 2 after the map was revised, and worked perfect to me 2
