### ISSUE TITLE
🐛 [Bug Report] Infiltrating Voltarus

### ISSUE THREAD

**Issue by AldebaraanMKII** [cmangos/issues#3350]
### Bug Details

https://www.wowhead.com/wotlk/quest=12661/infiltrating-voltarus
Turning into a ghoul and trying to talk to Drakuru doesn't progress the quest: he doesn't have the quest mark above his head and only responds with "greetings <charname>"

### Steps to Reproduce

1. Use the collar to turn into a ghoul
2. try to talk to Drakuru

### Core SHA1 Commit Hash

a90a4a37ded5ea23099335fbc6c18e8de44d93c3

### Database SHA1 Commit Hash

65cc788c47b2b08c94ebff7dab26d0a7cc11b595

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Grz3s** [comment]
Can't reproduce it...
![fesfesu](https://user-images.githubusercontent.com/2374069/230250042-f6aaecd5-8f0a-4f41-83a0-1eb58bf96f52.jpg)
after using correct item... everything works fine... 

More info how you did it reQ

**Comment by AldebaraanMKII** [comment]
Yeah seems to be working now after recompiling.
