### ISSUE TITLE
🐛 [Bug Report] Weapons of Destruction

### ISSUE THREAD

**Issue by AldebaraanMKII** [cmangos/issues#3356]
### Bug Details

https://www.wowhead.com/wotlk/quest=12660/weapons-of-destruction
After detonating a bomb, it respawns too quickly (in like 5 seconds), allowing the player to easily complete the quest by using the same bomb over and over.

### Steps to Reproduce

1. Take the quest and activate a bomb
2. Wait 5 seconds

### Core SHA1 Commit Hash

a90a4a37ded5ea23099335fbc6c18e8de44d93c3

### Database SHA1 Commit Hash

65cc788c47b2b08c94ebff7dab26d0a7cc11b595

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by virusav** [comment]
Patch: https://github.com/cmangos/wotlk-db/issues/896

**Comment by Grz3s** [comment]
fixed
