### ISSUE TITLE
🐛 [Bug Report] The Mist Isn't Listening

### ISSUE THREAD

**Issue by AldebaraanMKII** [cmangos/issues#3357]
### Bug Details

https://www.wowhead.com/wotlk/quest=12538/the-mist-isnt-listening
The Gorlocs can't be attacked (invalid target)

### Steps to Reproduce

1. Take the quest and try to attack any Gorloc in the vicinity

### Core SHA1 Commit Hash

a90a4a37ded5ea23099335fbc6c18e8de44d93c3

### Database SHA1 Commit Hash

65cc788c47b2b08c94ebff7dab26d0a7cc11b595

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by virusav** [comment]
If you assign yourself a quest using a command, then the NPCs may be unattackable.
If you complete a chain of quests, your reputation with NPCs will deteriorate, after which they can be attacked.

The quest is working.

**Comment by Grz3s** [comment]
fixed already with `Frenzyheart Tribe` quest chain redone
