### ISSUE TITLE
🐛 [Bug Report] [WOTLK] [tested on 21Mar23] [Death Knight] Unholy Talent Crypt Fever

### ISSUE THREAD

**Issue by flashflash-GIT** [cmangos/issues#3378]
### Bug Details

Death Knight: Unholy talent-Crypt Fever, not work properly. 
(Talent Description: Crypt Fever (Rank 3): Your diseases also cause Crypt Fever, which increases disease damage taken by the target by 30%.

When Crypt Fever is activated, it either leads to no damages over time for all three diseases, or immediately killed target with some abnormally high damage.

### Steps to Reproduce

1. Unholy talent tree: no Crypt Fever talent learned
2. Cast spells like Plague Strike and/or Chains of Ice, which cause Blood Plague and/or Frost Fever diseases
3. Damage over time produced form Blood Plague and/or Frost Fever diseases.
4. Unholy talent tree: Crypt Fever talent learned (Rank 3)
5. Cast spells like Plague Strike and/or Chains of Ice, which causes Blood Plague and/or Frost Fever diseases
6. Crypt Fever is activated, along with Blood Plague and/or Frost Fever diseases.
7. No damages over time for all three diseases, or target is immediately killed with some abnormally high damage

### Expected behavior

Crypt Fever should not inhibit damages over time from blood Plague and/or Frost Fever diseases, nor should it cause abnormally high damage/instant kill.

### Core SHA1 Commit Hash

c8feff5b318e7c19448759f2962bdddf3b424dca

### Database SHA1 Commit Hash

45c80d7a6913e5f6389197dea17dd1fc769c411f

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by kelbren** [comment]
![Screenshot at 2024-02-27 16-38-21](https://github.com/cmangos/issues/assets/22120553/438aa2d4-3c60-4911-b047-a389ebff4484)
I can confirm this issue, server is up to date as of today, damage was normal until I trained Crypt Fever. then the damage was way too high.
An order of magnitude to high. 
Any thoughts on this would be cool. It makes the DK a one hit killing machine. Not really what is intended. 
Thanks

**Comment by killerwife** [comment]
Retest after linked commit

**Comment by kelbren** [comment]
Tested for about 30 minutes of constant battle, dps seems good now. no more crazy high numbers

Thanks!!
