### ISSUE TITLE
🐛 [Bug Report] [TBC] 21946/ectoplasmic-distiller

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3392]
### Bug Details

Quest: Hunting for Ectoplasm
Questline: T0.5

Quest: Use the Distiller, to collect Ectoplasm ... 

### Steps to Reproduce

1. Start Quest
2. Go to Questarea ea Silithus
3. Klick on distiller in Inventory
4. Itemcooldown is startet, fuel is used
5. but no distiller is placed on ground

### Expected behavior

there should be spawnd an objekt near Player within mobs should be killed to get the plasm.

### Suggested Workaround

none, only spawn ectoplasm by id 

### Error Log

03:37:10 Gameobject (Entry: 181057) not exist and not created at spell (ID: 27433) cast

### Core SHA1 Commit Hash

a7aa480fd64a290d5ccd64abf26924961d0b0a64

### Database SHA1 Commit Hash

May  3 2023

### Operating System

W11 x64

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Ischtaratu** [comment]
A workaround has already been implemented. The distiller is not required. The mobs drop the corresponding items by themselves. You only need the quest.

But it would be nicer to fix the quest, because otherwise considerable costs can be saved for the actually expensive quest line.

**Comment by AnonXS** [comment]
please link commits to "work arounds", like this you're just assuming something was changed. . .

it can also just be that your installation was faulty and it worked like this all along.

**Comment by Ischtaratu** [comment]
I don't know who and when the workaround was added. I just found that you can get the drops you need without the Distiller.

And my installation was freshly set up today (02 Jul 2023) with the packs downloaded from github.
I can safely rule out an error at this point.

**Comment by evil-at-wow** [comment]
It just happens that the required items were (and are, it seems) part of the mobs loot table. I don't think that was an intended workaround (and a commit we can point to) but more likely just a bug when adding the mob loot which just happens to be convenient. That has been the case since at least 2013, and possibly even longer (I remember seeing this on an old server I was running).

**Comment by AnonXS** [comment]
So what quest and items are we talking about?

**Comment by Ischtaratu** [comment]
21946/ectoplasmic-distiller

and Quest: https://www.wowhead.com/tbc/quest=8924/hunting-for-ectoplasm

its an Item, that should be placed at 3 areas ... Winterspring, Silithus and east plaguelands

**Comment by Ischtaratu** [comment]
The quest can be completed. Nobody would complain about that. However, the production of the Distiller costs over 150g ... which would make the entire quest line far too cheap for the items received. Therefore, the quest series should be implemented in such a way that the costs cannot be avoided. Even if something can't be implemented 1:1 Blizzlike.

**Comment by AnonXS** [comment]
ok,

https://www.wowhead.com/tbc/item=21935/stable-ectoplasm
https://www.wowhead.com/tbc/item=21936/frozen-ectoplasm
https://www.wowhead.com/tbc/item=21937/scorched-ectoplasm

**Comment by evil-at-wow** [comment]
The relevant items that currently drop unconditionally from the mobs if you're on this quest (quest 8924):
* Stable Ectoplasm, item 21935 - drops from creatures 8538, 8539, 8540, 8541 and 8542
* Frozen Ectoplasm, item 21936 - drops from creatures 7523 and 7524
* Scorched Ectoplasm, item 21937 - drops from creatures 12178 and 12179

They should drop from these but only when killed close enough to the item you need to set up first (Ectoplasmic Distiller, item 21946).

**Comment by AnonXS** [comment]
So one should prob look into how these are implemented in tbc (similar quests) then look if spells are working same and apply same fix for "channeling" to classic/tbc version as this quest is one.

**Comment by Ischtaratu** [comment]
currently the item is not placed as an object on the ground when activated. I tried several positions. the object spawn is not triggered.

**Comment by AnonXS** [comment]
ok wrong again, only some visual is missing from go casting.

in future please provide more links and maybe some videos.

![grafik](https://github.com/cmangos/issues/assets/19734826/2bf30a61-d249-4c2b-b09c-46d05ba04a4a)

SELECT * FROM gameobject_template where entry IN (181057); -- missing in tbc, classic/wotlk have it.

so what happens is that the go trap from 181057, 181054 channels a aoe friendly s.27420 on the player that allows gathering the items. no special visual or anything, just the main template missing at this point for further testing.

**Comment by evil-at-wow** [comment]
I was about to mention that - at least from a player's point of view - they behave similar to those elemental quests in Shadowmoon in TBC as part of the Cipher of Damnation chain: Enraged Spirits of Fire and Earth (quest 10458), Enraged Spirits of Water (quest 10480) and Enraged Spirits of Air (quest 10481). There you also place a totem object, and then need to kill some elementals close to the totem. I think those were somewhat recently fixed, so that may lead to some inspiration too, but the difference is that you get a kill count there, rather than an item in the mob's loot (I'm not sure how the quest here is actually implemented on the reference).

**Comment by evil-at-wow** [comment]
Reference video to show how this quest is supposed to work from Classic (PTR it seems): https://www.youtube.com/watch?v=ajD5SQ_3Mpc&t=180 :)

**Comment by Ischtaratu** [comment]
i did the questline in vanilla classic 2020 and i remember needing more rocket fuel as sometimes the mobs seem to actually die a few steps too far.

**Comment by AnonXS** [comment]
Try:
```
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `faction`, `flags`, `ExtraFlags`, `size`, `data0`, `data1`, `data2`, `data3`, `data4`, `data5`, `data6`, `data7`, `data8`, `data9`, `data10`, `data11`, `data12`, `data13`, `data14`, `data15`, `data16`, `data17`, `data18`, `data19`, `data20`, `data21`, `data22`, `data23`, `CustomData1`, `mingold`, `maxgold`, `StringId`, `ScriptName`) VALUES
(181057, 8, 6659, 'Ectoplasmic Distiller', 0, 0, 0, 1.4, 0, 10, 181054, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
```

question remains why the items are lootable when the "visual go" is not appearing, maybe conditions were composed different.

**Comment by f0n1x** [comment]
Some notes/testing:

Classic/Vanilla:
NPCs drop their corresponding ectoplasms without checking for presence of ectoplasmic distiller.
Dropping an Ectoplasmic Distiller works visually.

TBC:
NPCs drop their corresponding ectoplasms without checking for presence of ectoplasmic distiller.
Dropping an Ectoplasmic Distiller does NOT work visually.

WotLK:
NPCs drop their corresponding ectoplasms without checking for presence of ectoplasmic distiller.
Dropping an Ectoplasmic Distiller works visually.

**Comment by AnonXS** [comment]
The quest condition check needs to be changed to an aura check in addition to the missing go template in tbc. seems to be about it.

**Comment by evil-at-wow** [comment]
> question remains why the items are lootable when the "visual go" is not appearing

That's because they're in the loot tables as quest items. For example in creature_loot_template: (8538,21935,-80,0,1,1,0,'Stable Ectoplasm'). And then of course these items in the ReqItemId or ReqSourceId fields of that quest. 
So as you say, I think we'll need to change that bit.

**Comment by evil-at-wow** [comment]
This should be fixed now given cmangos/mangos-tbc@fc424fbd4886019ad9db5ae117c71af9b07f2edb and some database changes that were done several weeks ago in cmangos/tbc-db@bd18add96a5f35c2f76bd709d262de50321d7831.

**Comment by insunaa** [comment]
@evil-at-wow heyo, sorry for asking you in the completely wrong place but I don't know where best to contact you.

Can you use your experience with fixing memory leaks and check out why `MapBuilder::buildTile` keeps allocating but not freeing memory? As far as I can tell it's the `m_terrainBuilder->loadMap` and `m_terrainBuilder->loadVMap` functions, but I'm too incapable to determine what exactly is the issue there.
I've used an address sanitizer but that didn't find any issues (at least not before running out of memory) so I don't know if there's some alloc without a free happening or something :/

**Comment by evil-at-wow** [comment]
Can I suggest to open a new issue to track that? Then we can have the rest of the discussion there. Maybe already add a few details (like platform) and why you think those calls may be the culprit.
It's been a while since I last extracted mmaps (in particular I haven't updated since their version last changed, see cmangos/mangos-tbc@9bf4a4871505b957ff3b807f04b6eb66fdc4126b and the commits just before that), but back then I didn't notice anything pointing to a memory leak (but that's not proving much of course). Note it's unlikely I'll be able to check much before the weekend though.
