### ISSUE TITLE
🐛 [Bug Report] [WOTLK] Quest: It Goes to 11

### ISSUE THREAD

**Issue by Mige5** [cmangos/issues#3397]
### Bug Details

The hits do not get count towards the quest

### Steps to Reproduce

1. Start quest
2. Take control of harpoon
3. Shoot at building

### Expected behavior

The hits should be counted towards quest completion: https://www.youtube.com/watch?v=JBiE2hLGqOE

### Core SHA1 Commit Hash

*

### Database SHA1 Commit Hash

*

### Operating System

Win10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Grz3s** [comment]
![dawdaw](https://user-images.githubusercontent.com/2374069/236921211-fd51647b-1963-4216-ae49-b1190620e0fb.jpg)

**Comment by Mige5** [comment]
Tried again now, still doesnt seem to be working for me :S

**Comment by f0n1x** [comment]
insunaa just confirmed this is working.
Mige5, please provide Hash commits to compare against.
