### ISSUE TITLE
🐛 [Bug Report] [WOTLK] Flying mobs walking in air

### ISSUE THREAD

**Issue by Mige5** [cmangos/issues#3408]
### Bug Details

Atleast in borean tundra & howling fjord it seems like most of the flying mobs are just walking in air. (minor visual bug though)

### Steps to Reproduce

1. Just wander around places where there is flying mobs

### Core SHA1 Commit Hash

*

### Database SHA1 Commit Hash

*

### Operating System

Win10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
can u do please some screenshoots to creatures that does that, to speed up the procces of targeting the exact creature

**Comment by al3xc1985** [comment]
I ehcked the zone and I only found 1 spot. Even tested the Coldarra zone, where there are so many dragons that fligh, and no problem.
All I could find on this maps is:

![image](https://github.com/cmangos/issues/assets/6240049/e34d0e22-1b8c-4e44-a9a4-025b2189e155)

**Comment by Grz3s** [comment]
I wouldnt say "most". 
Issue appeared with c_t_addon reconstructed few weeks ago.. I'm slowly fixing every case spotted. 
So if You guys find more pls report it.
THX
