### ISSUE TITLE
🐛 [Bug Report] [TBC] Crash for no apparent reason and player inactivity

### ISSUE THREAD

**Issue by opiums9** [cmangos/issues#3410]
### Bug Details

I put my character without the rights (0 gmlevel ) to beat the Theramore Combat Dummy, after a while I found that the connection to the server was interrupted. After checking server the log files, I saw a crash.

### Steps to Reproduce

1. nothing
2. crash...

### Expected behavior

Crash with one single player who stood and was a dummy...

### Crash Log

time the crash: 2023-05-16 10:00:01
https://gist.github.com/opiums9/67b024dc86bb105fae519027e82a7aa4

time the crash: 2023-05-16 12:00:02
https://gist.github.com/opiums9/daf098ea057a8cb29e2858274ae5dd11

### Core SHA1 Commit Hash

d56bdc51d01bbaf45d63ec30845fa12feda319b4

### Database SHA1 Commit Hash

a5f845e0224435d78d9806580cec90eae8769abe

### Operating System

Debian GNU/Linux 10 (buster)

### Client Version

2.4.3 (The Burning Crusade)

**Comment by f0n1x** [comment]
I have the same issue on vanilla. I think it has something to do with GameEvent.
Those were the last commands issued in your log and mine as well:

13:00:01 GameEvent 11 "Elemental Invasion: Air" removed.
13:00:01 GameEvent 401 "DayTime 7AM to 12AM" removed.
13:00:01 GameEvent 1024 "Hourly Bells" started.
13:00:01 Next game event check in 60 seconds.

This has happened to me the last 3 days at exactly 13:00:01 local time. It looks like it's happening to opiums9 at exactly 10:00:01.

My vanilla commit hashes:
Core - a01ea731aa3a278d887b1aa510f513d34532892b
DB - 61b7d8c4bb4cfb49de1c17a6ed0576777462c04c

**Comment by opiums9** [comment]
Literally just crashed again

time the crash: 2023-05-17 12:00:01
https://gist.github.com/opiums9/27628d573656affc9f6b0d73e1ac9e5f

**Comment by al3xc1985** [comment]
Here I have 3 crashes 2

https://gist.github.com/al3xc1985/7ec003631bc2a929e344c9156fbb8fc9

**Comment by evil-at-wow** [comment]
@opiums9 Any chance you can quickly apply the patch [here](https://github.com/cmangos/mangos-classic/commit/a6ef7a3751e19798d142a5edf27f23be777f0add.patch) to test if it still crashes (at noon) afterwards?

It's a patch currently in the Classic core that we'll port to TBC and Wrath anyway, but it would be nice if we can confirm that this fixes your crashes too. Thanks!

**Comment by opiums9** [comment]
@evil-at-wow, I applied the patch today around 9 am and it works well. Prior to this, the server was crashing every day at 12:00. I suppose this may be a solution to the problem, but I think it's worth waiting a while. If there are any problems, I will write. Thank you in advance!

**Comment by f0n1x** [comment]
Confirmed fixed on vanilla. Been running for over 24 hours now.

**Comment by evil-at-wow** [comment]
Great to see it confirmed that the patch seems to fix your crashes too!

I don't have time before the weekend anyway to update TBC/Wrath cores, so we'll see what the next few days bring for you. 
Thank you for testing!

**Comment by opiums9** [comment]
A few days later the server is still working fine, I guess this patch is the solution, thanks again
