### ISSUE TITLE
🐛 [Bug Report] Draenei crash survivors should be alive, not dead.

### ISSUE THREAD

**Issue by wdstudios2** [cmangos/issues#3414]
### Bug Details

One of the Draenei noob quests requires using the "Gift of the Naaru" ability on the crash survivors to heal them. This is currently impossible because the survivors are dead.

### Steps to Reproduce

N/A

### Expected behavior

Living survivors

### Core SHA1 Commit Hash

f9b1a16

### Database SHA1 Commit Hash

c54ab0b

### Operating System

Win7

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
![grafik](https://github.com/cmangos/issues/assets/19734826/2414e6a4-194d-4fe6-8506-557699667726)

![grafik](https://github.com/cmangos/issues/assets/19734826/ef0d5022-9d2f-4d23-ad59-f91d6def1ea7)

![grafik](https://github.com/cmangos/issues/assets/19734826/5e33624f-c2d2-4a50-9a18-274f522b33ea)

![grafik](https://github.com/cmangos/issues/assets/19734826/2e375e80-f4b2-4ee2-83b7-c5371c07d91d)

![grafik](https://github.com/cmangos/issues/assets/19734826/a0edc70f-24c2-4c60-bd94-90e529810518)

https://www.youtube.com/watch?v=JXf4h7rdUq0&ab_channel=WCQuests

https://www.wowhead.com/tbc/quest=9283/rescue-the-survivors

```
.go c id 16483
.q add 9283
use racial spell on them.
```

**Comment by wdstudios2** [comment]
Ah, apparently this was fixed some time between 3 days ago and 1 week ago. Never mind.
