### ISSUE TITLE
🐛 [Bug Report] [WoTLK] [Warning] In ScriptMgr.cpp

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3415]
### Bug Details

/home/mangos/cmangos/wotlk/src/game/DBScripts/ScriptMgr.cpp: In member function ‘void ScriptMgr::LoadScripts(ScriptMapType)’:
/home/mangos/cmangos/wotlk/src/game/DBScripts/ScriptMgr.cpp:259:37: warning: too many arguments for format [-Wformat-extra-args]
  259 |                     sLog.outErrorDb("Table `%s` has buddy defined by stringId (SCRIPT_FLAG_BUDDY_BY_STRING_ID) but stringId does not exist, skipping.", tablename, tmp.id, stringId);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### Steps to Reproduce

1. Compile
2.
3.
4.

### Crash Log

N/A

### Core SHA1 Commit Hash

fd3edd6276576f3dafd64b7d7f2828c4a52f0d48

### Database SHA1 Commit Hash

N/A

### Operating System

Ubuntu 20.04 LTS Server

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by evil-at-wow** [comment]
We got it in the TBC core as well. Fairly harmless, but it's fixed with cmangos/mangos-tbc@4bbd86257dda6017f73581aff8433cd6683a19c3 so Wrath and Classic will follow after ports.
