### ISSUE TITLE
🐛 [Bug Report] insunaa, have you even looked at what V. Duskbats are doing lately? This is NOT intended behavior.

### ISSUE THREAD

**Issue by wdstudios2** [cmangos/issues#3419]
### Bug Details

Vampiric Duskbats are currently stunlocking players to death with an ability that they're not supposed to have in the first place. This has never been the way they've behaved and it has never been they way they were intended to behave. I don't mind if you take forever to fix it (I've already fixed it by replacing spell=3242/ravage with "0" in creature_template_spells and with spell=24423/screech in creature_AI-scripts) but at least acknowledge the fact that it's a bug.

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

73dd1ae

### Database SHA1 Commit Hash

6cb4346

### Operating System

Win7

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
Yes I have. Maybe install the database properly before complaining. Thank you and have a nice day.
