### ISSUE TITLE
🐛 [Bug Report] Scarlet Warriors no longer cast Nimble Reflexes

### ISSUE THREAD

**Issue by wdstudios2** [cmangos/issues#3423]
### Bug Details

It looks like AnonXS was a bit too aggressive when he recently "cleaned up" the Tirisfal Glades NPC abilities. When he removed Moss Hide from the Scarlet Warriors (npc=1535), he took their Nimble Reflexes (spell=3238) too!

### Steps to Reproduce

1.
2.
3.
4.

### Expected behavior

Scarlet Warriors in combat should occasionally cast Nimble Reflexes

### Core SHA1 Commit Hash

73dd1ae

### Database SHA1 Commit Hash

6cb4346

### Operating System

Win7

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
Was moved to creature_spell_list, make sure to install the project correctly.

**Comment by miraco** [comment]
Can confirm, npc uses spell correctly.
https://puu.sh/JHqV9/0c04245866.png


Maybe you need to update to latest database/core updates.

**Comment by wdstudios2** [comment]
> Can confirm, npc uses spell correctly. https://puu.sh/JHqV9/0c04245866.png
> 
> Maybe you need to update to latest database/core updates.

I turned NPC HP up to 10x normal and their damage down to 0.1x normal so I could beat them up for several minutes without killing them. They do cast it, but much more rarely than on Blizzard servers. I guess it's fine for now.

**Comment by wdstudios2** [comment]
> Was moved to creature_spell_list, make sure to install the project correctly.

Project is installed correctly. Make sure to not be a condescending asshole in the future.

**Comment by miraco** [comment]
> > Can confirm, npc uses spell correctly. https://puu.sh/JHqV9/0c04245866.png
> > Maybe you need to update to latest database/core updates.
> 
> I turned NPC HP up to 10x normal and their damage down to 0.1x normal so I could beat them up for several minutes without killing them. They do cast it, but much more rarely than on Blizzard servers. I guess it's fine for now.

They use it between 0 and 10 seconds for the first time, and then every 45 seconds. 
Give us proof from retail tbc that they use it more frequently then we can update this, else this will be as it is now.

**Comment by wdstudios2** [comment]
> retail tbc

Does TBC Classic even exist anymore? I was told that all of the TBC servers would be migrated to Wrath regardless of what the players wanted.

**Comment by miraco** [comment]
No, but you can try searching threw videos.
We cant change timers or anything, just because (sry for this wording) a rnd dude on github says he thinks it wasnt like this on tbc. We always need a good source/proof of how it worked. We mostly use sniffs/videos for it.

**Comment by AnonXS** [comment]
With https://github.com/cmangos/mangos-tbc/commit/ac3319fd734019a27a58f49992cd66bc99ca7f6a, this now works exactly how it did befor when it was scripted in EAI.

![grafik](https://github.com/cmangos/issues/assets/19734826/d78c2d54-ef4b-4fbe-ae75-241b70f62f5e)
