### ISSUE TITLE
🐛 [Bug Report] Maggot Eye casts Life Harvest too frequently

### ISSUE THREAD

**Issue by wdstudios2** [cmangos/issues#3424]
### Bug Details

Maggot Eye (npc=1753) can spam Life Harvest (spell=3243) without any pauses or limitations. He casts it far less often on Blizzard realms. This is because he is granted that ability in creature_template_spells, and as I've pointed out already, mobs are currently allowed to spam whatever abilities they're given in creature_template_spells without any pauses or limitations.

### Steps to Reproduce

1.
2.
3.
4.

### Expected behavior

Maggot Eye should cast Life Harvest less frequently.

### Core SHA1 Commit Hash

73dd1ae

### Database SHA1 Commit Hash

6cb4346

### Operating System

Win7

### Client Version

2.4.3 (The Burning Crusade)

**Comment by miraco** [comment]
Not sure how often he uses this ability on retail, but on newest tbc core+db he isnt spamming it.
https://puu.sh/JHqVS/9300c85519.png

First use: 16:46:15
2nd use: 16:46:26
3rd use: 16:46:40
4th use: 16:46:54
5th use: 16:47:04

Maybe thats to often, please provide some proofs from retail how often he should use it.

**Comment by wdstudios2** [comment]
> 

On the core and DB version that I cited, he was casting it closer to every 2 seconds.

You guys have a funny habit of fixing bugs after I report them but before you investigate them...
