### ISSUE TITLE
🐛 [Bug Report] Defias Bandits spam Snap Kick too often

### ISSUE THREAD

**Issue by wdstudios2** [cmangos/issues#3426]
### Bug Details

Defias Bandits (npc=116) spam Snap Kick (spell=8646) every 2 seconds, stunlocking players to death.

UPDATE: Hogger (npc=448) does the same thing with Head Butt (spell=6730)

### Expected behavior

They should cast it, but less often.

### Core SHA1 Commit Hash

a01efa1a

### Database SHA1 Commit Hash

9ff154e

### Operating System

Win7

### Client Version

2.4.3 (The Burning Crusade)

**Comment by miraco** [comment]
Cant confirm, works on mine.
![Wow_TMTySIpbEu](https://github.com/cmangos/issues/assets/6261245/3f00a74a-ed35-446b-918d-74a5effadaed)

**Comment by al3xc1985** [comment]
This is related to cmake. Update cmake. I encountered the same problem with cmake 2.4.x version. Updated to 2.6.x version solves the problem.. Something is going weird with cmake on that version

**Comment by AnonXS** [comment]
I run CMake 3.18.2 and have not encountered this issue.

**Comment by al3xc1985** [comment]
my bad I had 3.24 and updated to 3.26 and encountered that problem
