### ISSUE TITLE
🐛 [Bug Report] Burning Shadow quest doesn't work correctly

### ISSUE THREAD

**Issue by wdstudios2** [cmangos/issues#3427]
### Bug Details

When I talked to Neeru Fireblade to convince him that I was a member of the evil spooky cult, I got the "bong" sound. You know the sound you get when you try to complete a quest, but you can't because your bags are full and there's no space for the quest reward? That's the sound I'm talking about. Anyway... different parts of the game's interface couldn't agree on whether I had completed that part of the quest or not, and trying to talk to Thrall didn't accomplish anything.

I tried closing and restarting the client, but that didn't help.

Then, I abandoned the quest and went back tot he cave to kill the burning blade guy a few more times, but he didn't drop the Eye of Burning Shadow.

Out of desperation, I went into HeidiSQL and modified a vendor to sell the Eye of Burning Shadow. This worked, but when I right-clicked on the eye and tried to accept the quest, I was told that I couldn't because I was already on that quest. My quest log disagreed.

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

a01efa1a

### Database SHA1 Commit Hash

9ff154e

### Operating System

Win7

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
I can not reproduce this issue in either this questline https://www.wowhead.com/classic/quest=5727/hidden-enemies or this quest https://www.wowhead.com/classic/quest=832/burning-shadows

![grafik](https://github.com/cmangos/issues/assets/19734826/9c4f06ef-ae53-4a74-9592-3887f7df7bda)
![grafik](https://github.com/cmangos/issues/assets/19734826/d7f0763a-b370-4be8-b0ce-09d31df05856)
![grafik](https://github.com/cmangos/issues/assets/19734826/dffd9501-dfdd-48c0-a927-7c536368eff2)
![grafik](https://github.com/cmangos/issues/assets/19734826/08056913-baf0-463b-9196-b8c3f9a37439)
