### ISSUE TITLE
🐛 [Bug Report] 2.4.3 server crashing 

### ISSUE THREAD

**Issue by Karrz1** [cmangos/issues#3433]
### Bug Details

The server crashes often,  not sure if its his only but seem to be when a few BGs are running with players. Have compared the file and they seem to be the same so thought would bring it to your attention that it's maybe an issue that is known or has been fixed.

### Steps to Reproduce

1.
2.
3.
4.

### Suggested Workaround

tried and failed

### Crash Log

[c6b5d6fe_mangosd.exe_[26-5_20-35-0].txt](https://github.com/cmangos/issues/files/11579347/c6b5d6fe_mangosd.exe_.26-5_20-35-0.txt)

### Core SHA1 Commit Hash

c6b5d6fea16e7c843f3db833edd2323be0bad705

### Database SHA1 Commit Hash

e7fc554ac508c10922495d6102a10e4f4bb340ac

### Operating System

Windows Server 2022 Standard (Version 10.0, Build 20348)

### Client Version

2.4.3 (The Burning Crusade)

**Comment by celguar** [comment]
Please don't create issues with "celguar's version of the game" or anything not stock cmangos related. You are responsible to use celguar's or any other version of the server and I don't want devs to spend time on custom stuff. Just my opinion

**Comment by celguar** [comment]
Plus this crash might be already fixed in latest code
