### ISSUE TITLE
🐛 [Bug Report] Rune of the Defiler teleports you without any quest

### ISSUE THREAD

**Issue by Tobschinski** [cmangos/issues#3436]
### Bug Details

The Rune of the Defiler in the Blasted Lands teleport you up the mountain without having any quests. This is most likely not correct and should be investigated.

### Steps to Reproduce

1.

### Expected behavior
![image](https://github.com/cmangos/issues/assets/4753528/f5f25b4f-be90-4994-81a6-4620d73bb4ce)

### Core SHA1 Commit Hash

ca933d13283e61c30b99ae955070d09ad71db554

### Database SHA1 Commit Hash

008d36f09fdb7e25ba58db34b8da47a8fa05e660

### Operating System

Win

### Client Version

1.12.1 (Classic)

**Comment by f0n1x** [comment]
Can confirm that currently, simply walking across the runes ports you to the Defiler's Rise. I believe that this is incorrect behavior.

At the very least, you are supposed to talk to the Deathly Usher (npc: 8816) to be ported to the top, not simply walk across the rune as seen in this video: https://www.youtube.com/watch?v=lRbJnnQAJwo

There are a few comments on this thread that explain needing to be on the quest to be ported, but this one is the most clear:
https://www.wowhead.com/classic/quest=3628/you-are-rakhlikh-demon#comments:id=2739410
It also explains that everyone in the party of the person speaking with Deathly Usher and activating his comment "I wish to face the Defiler." will be ported to the top of the mountain regardless of location and alive/dead state.

I am also on Classic.
SHA1 Core: 5c64aab6a404d5e1ea36bb20a77866848bdefdcf
SHA1 DB: 008d36f09fdb7e25ba58db34b8da47a8fa05e660

**Comment by f0n1x** [comment]
After more digging, it seems that the rune should only port you to the top if you (1) are not in a party, and (2) have the Ward of the Defiler (item: 10757) (provided when starting "You are Rakh'likh, Demon" (quest: 3628)) in your bags. If you ARE in a party, the Deathly Usher should be used to port the entire party to the Defiler's Rise (I believe this too requires the Ward of the Defiler).

Sources:
https://web.archive.org/web/20080415093729/http://www.thottbot.com/?qu=3628
https://web.archive.org/web/20060416014418/http://wow.allakhazam.com/db/quest.html?wquest=3628
Point 3 -> https://www.wowhead.com/classic/quest=3628/you-are-rakhlikh-demon#comments:id=2739481

Also, I know it's classic, but here's a video showing someone walking on the rune and NOT being ported to the top (1:48). They are in a group and have the amulet in their bags (4:17):
https://www.youtube.com/watch?v=awRjWw8Dg_4

**Comment by killerwife** [comment]
Can confirm this isnt supposed to happen by default. I did the questline in original classic and its complete and utter ass. I will fix the areatriggers but someone needs to script this whole thing.

**Comment by killerwife** [comment]
Fixed the random teleports using the rune, will port when syncing cores. Linked the commit in case you need it sooner.

**Comment by f0n1x** [comment]
Nah, when you do your regular syncing is fine, thanks KW!
