### ISSUE TITLE
🐛 [Bug Report]  Hatching rookery eggs in UBRS crashes server

### ISSUE THREAD

**Issue by f0n1x** [cmangos/issues#3437]
### Bug Details

After Pyrogard Emberseer's room in Upper Blackrock Spire, you will find the rookery (the same room made famous in the Leeroy Jenkins video). Hatching any of the eggs in this room currently crashed the server.

### Steps to Reproduce

1. Create any level 60 character.
2. Add item 12344 (Seal of Ascension).
3. Teleport to BlackrockSpire.
4. Clear first room and go up the left side of the bridge and immediately turn left.
5. Enter the small hallway with the 6 braziers to light them and open the door (GM mode must be off, and you must have Seal of Ascension in your inventory).
6. Clear each of the small rooms to extinguish the runes and the next door will open.
7. Enter Pyroguard Emberseers room and GM kill him (otherwise you will need 2 other people to summon him, bots won't work).
8. Enter the rookery and approach an egg.
9. You will hear the hatching sound, followed by a server crash.

### Expected behavior

Eggs should spawn whelps, which doesn't seem to happen.

### Crash Log

#0  0x0000000000c2edf5 in ObjectGuid::operator== (this=0x7f2df09f80b8, guid=...)
    at /tmp/mangos-classic-6516f8e06dd9570a7380a3ec92621d3fc6ab04c4/src/game/Entities/ObjectGuid.h:158
#1  Spell::UpdateOriginalCasterPointer (this=0x7f2df09f7f90)
    at /tmp/mangos-classic-6516f8e06dd9570a7380a3ec92621d3fc6ab04c4/src/game/Spells/Spell.cpp:6848
#2  0x0000000000c4d820 in Spell::UpdatePointers (this=0x7f2df09f7f90)
    at /tmp/mangos-classic-6516f8e06dd9570a7380a3ec92621d3fc6ab04c4/src/game/Spells/Spell.cpp:6864
#3  Spell::update (this=0x7f2df09f7f90, difftime=100) at /tmp/mangos-classic-6516f8e06dd9570a7380a3ec92621d3fc6ab04c4/src/game/Spells/Spell.cpp:3429
#4  0x0000000000c593a2 in SpellEvent::Execute (this=0x7f2de0f34470, e_time=584579, p_time=100)
    at /tmp/mangos-classic-6516f8e06dd9570a7380a3ec92621d3fc6ab04c4/src/game/Spells/Spell.cpp:7102
#5  0x000000000096fdcc in EventProcessor::Update (this=0x7f2e0452f3a0, p_time=100)
    at /tmp/mangos-classic-6516f8e06dd9570a7380a3ec92621d3fc6ab04c4/src/framework/Utilities/EventProcessor.cpp:47
#6  Unit::Update (this=0x7f2e0452f2a0, diff=100) at /tmp/mangos-classic-6516f8e06dd9570a7380a3ec92621d3fc6ab04c4/src/game/Entities/Unit.cpp:484
#7  0x00000000008d7ba8 in Player::Update (this=0x7f2e0452f2a0, diff=100)
    at /tmp/mangos-classic-6516f8e06dd9570a7380a3ec92621d3fc6ab04c4/src/game/Entities/Player.cpp:1380
#8  0x0000000000af192e in Map::Update (this=<optimized out>, t_diff=@0x7f2dd22289a8: 100)
    at /tmp/mangos-classic-6516f8e06dd9570a7380a3ec92621d3fc6ab04c4/src/game/Maps/Map.cpp:736
#9  0x0000000000b0c335 in MapUpdateWorker::execute (this=0x7f2dd2228990)
    at /tmp/mangos-classic-6516f8e06dd9570a7380a3ec92621d3fc6ab04c4/src/game/Maps/MapWorkers.h:52
#10 0x0000000000b16f01 in MapUpdater::WorkerThread (this=0x6435c50)
    at /tmp/mangos-classic-6516f8e06dd9570a7380a3ec92621d3fc6ab04c4/src/game/Maps/MapUpdater.cpp:96
#11 0x00007f2e2a4db884 in ?? () from /usr/lib64/libstdc++.so.6
#12 0x00007f2e2adf7e45 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f2e2a32c4af in clone () from /lib64/libc.so.6

### Core SHA1 Commit Hash

6516f8e06dd9570a7380a3ec92621d3fc6ab04c4

### Database SHA1 Commit Hash

008d36f09fdb7e25ba58db34b8da47a8fa05e660

### Operating System

Slackware64-15.0

### Client Version

1.12.1 (Classic)

**Comment by killerwife** [comment]
Will try it in the evening.

**Comment by insunaa** [comment]
Duplicate of https://github.com/cmangos/issues/issues/3267

**Comment by f0n1x** [comment]
Yep, apologies, duplicate of #3267 as noted by insunaa
