### ISSUE TITLE
🐛 [Bug Report][WoTLK] Dreadmurk Shore Shipwreck Debris on ocean bed

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3438]
### Bug Details

North of Theramore Isle along Dreadmurk Shore, to the east of the small island mm(66.76, 28.15) there is a plank on fire. If you swim out to it and then swim to the ocean bed you will find a Shipwreck Debris spawn. you can't fish it because you are swimming.

### Steps to Reproduce

1.Travel to Dreadmurk Shore north of Theramore Isle to co-ordinates 66.76, 28.15
2. Swim down to ocean bed 
3. Shipwreck Debris
4.

### Expected behavior

The Shipwreck Debris should be a on the surface of the ocean

### Crash Log

N/A

### Core SHA1 Commit Hash

e1030e498c2fe967f6a2e0011a7c4fec053ec2f5

### Database SHA1 Commit Hash

97790cc36721cbfbbb516b71d1f94872f24c2dc0

### Operating System

Ubuntu 20.04 LTS Server, Ubuntu 20.04 LTS Desktop Client

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
Thats part of a quest, not a fishable object. . .

questline: <https://www.wowhead.com/tbc/quest=11136/a-disturbing-development> -> https://www.wowhead.com/tbc/quest=11140/recover-the-cargo

https://youtu.be/KL_BBdgcTyA?t=60

**Comment by adellaci** [comment]
Okay thank you @AnonXS

**Comment by adellaci** [comment]
I see that now scattered through out the bay
