### ISSUE TITLE
🐛 [TBC] conditions table has wrong values

### ISSUE THREAD

**Issue by Eonfluxx** [cmangos/issues#3441]
### Bug Details

`select * from conditions where condition_entry>66000;`

It has 2 rows with condition_entry > uint16 max value. 

`LootMgr.cpp
uint16 conditionId         = fields[6].GetUInt16();
`

It is wrong.

### Steps to Reproduce

Select from mangos db

### Core SHA1 Commit Hash

d495ea71411e8cf0fef8fcffe63a1d56a8611635

### Database SHA1 Commit Hash

d495ea71411e8cf0fef8fcffe63a1d56a8611635

### Operating System

win11

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
@AnonXS instance files?

**Comment by miraco** [comment]
Yes. gruul/magtheridon/ramparts/karazhan 

> @AnonXS instance files?

**Comment by AnonXS** [comment]
you run the condition queries against the old data and paste the adjusted data, not what you tryed befor with removing it. xD

question stands if we want this static data to be in instance files to begin with. i vote no as that was not the intend of instance data.

continuing to name and number these conditions after instance file format is something i'd like though, as backporting can be ugly.

```
5650002	42	4804	0	0	0	0	Gruul the Dragonkiller - Trash Respawn
5650001	42	2778	0	0	0	0	Highking Maulgar - Trash Respawn
5440001	42	4805	0	0	0	0	Magtheridon - Trash Respawn
5430001	42	4698	0	0	0	0	Watchkeeper Gargolmar - Encounter completed
5310010	42	4823	0	0	0	0	Temple of Ahn'Qiraj - Battleguard Sartura - Trash Respawn

```
to
```
5650002	42	4804	1	0	0	0	Gruul the Dragonkiller - Trash Respawn
5650001	42	2778	1	0	0	0	Highking Maulgar - Trash Respawn
5440001	42	4805	1	0	0	0	Magtheridon - Trash Respawn
5430001	42	4698	1	0	0	0	Watchkeeper Gargolmar - Encounter completed
5310010	42	4823	1	0	0	0	Temple of Ahn'Qiraj - Battleguard Sartura - Trash Respawn

might be more though, or maybe my db was too out of data, check the query once again on next release

[SQL] -- change of operation enum for CONDITION_WORLDSTATE to official enum
UPDATE conditions SET value2=5 WHERE type=42 AND value2=1;
Affected rows: 15

[SQL] 
UPDATE conditions SET value2=6 WHERE type=42 AND value2=2;
Affected rows: 0

[SQL] 
UPDATE conditions SET value2=1 WHERE type=42 AND value2=0;
Affected rows: 7
```
