### ISSUE TITLE
🐛 [Bug Report] Enemy ability spam is still a systemic problem

### ISSUE THREAD

**Issue by wdstudios2** [cmangos/issues#3443]
### Bug Details

Maggot Eye is STILL spamming his self-heal ability.
Vampiric Duskbats are STILL stunlocking players to death by spamming Ravage.
Captain Melrache spams devotion aura.
Captain Vachon spams improved blocking.
Archmage Ataeric may spam Chains of Ice.
Ravenclaw Guardians spam Improved Blocking.
Southsea Brigands spam Backhand.

And this is JUST in the three zones that I've spent any significant time playing in.

I've heard that a Cmake version issue might be responsible for some or all of this behavior (credit goes to **al3xc1985** for this discovery, if it turns out to be true), and that a bug in an older version of Cmake may be allowing these mobs to cast abilities from a place in the SQL files that they shouldn't be casting from. If you want to try to replicate these bugs, DON'T COMPILE ANYTHING YOURSELF! Instead, download the latest PRECOMPILED releases, unzip them, and run. These are the files that I'm using. They're the ones that are giving me problems. They're probably compiled with the older, buggy version of Cmake. Let's figure out what the hell is actually happening here instead of pretending that it's not happening.

EDIT: I tried compiling the core myself from the latest commit, using Cmake 3.26.4 (the most recent version), and this didn't fix anything. I'm not sure what al3xc1985 thinks he/she found but it's probably a dead end.

Vampiric Duskbat Ravage spam: https://imgur.com/nYcWQUm

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

72ff7f8

### Database SHA1 Commit Hash

237fcde

### Operating System

Win7

### Client Version

2.4.3 (The Burning Crusade)

**Comment by al3xc1985** [comment]
I wrote u down on a different report.
I had the same issue with my core. It is because of Cmake. Update it to lates revision and generate the core again, compile it again fresh and your mobs/npc should not spam anymore.

It's not the fault of the core, it's the fault of cmake

**Comment by al3xc1985** [comment]
And please calm down with spamming the same thing again and again and again!

**Comment by celguar** [comment]
Any explanation for cmake to affect NPC spells?

**Comment by wdstudios2** [comment]
> It is because of Cmake. Update it to lates revision and generate the core again, compile it again

I did. That didn't fix the problem.

Might you have done something else when you updated your Cmake? Maybe that "something else" is what actually fixed the problem.

**Comment by wdstudios2** [comment]
> And please calm down with spamming the same thing again and again and again!

You'll have to discuss that with the developer who told me to file separate reports for every NPC that displayed this problem.

**Comment by al3xc1985** [comment]
I also updated my visual studio

**Comment by al3xc1985** [comment]
@celguar dunno, something is wrong with the compilers.

**Comment by wdstudios2** [comment]
> I also updated my visual studio

This might be why my own compiled cores still have the issue. I'm stuck on Visual Studio 2019 because that's the last version that works on Win7. I guess I could try doing it in a Win10 virtual machine with VS 2022 and see if that helps?

**Comment by al3xc1985** [comment]
yes. Beleive me that was a weird problem for me 2. And it is not because of the core it's something wronge with compilers. Try that also please. I use win 10 and latest VS

**Comment by wdstudios2** [comment]
Compiling in a Win11 virtual machine failed for some reason or another.

The default VS 2022 installation demands 10 gigabytes. That's quite a lot of space on a virtual machine for features that I don't know if I will need or not. If someone could clarify which things I need from the VS 2022 installer and which ones I don't, that would be a big help.

**Comment by al3xc1985** [comment]
Only de c++ u need

**Comment by wdstudios2** [comment]
> Only de c++ u need

I doubt that. Adding packages changed how far I was able to get in the compilation process and what error messages I got.

**Comment by al3xc1985** [comment]
Well ya. Don't forget to install boost. 
I didn't test compilling on win 11 only on 10

**Comment by al3xc1985** [comment]
@wdstudios2 shouldn't we close the reports about this if u figure out what I told u is true?

**Comment by wdstudios2** [comment]
@al3xc1985 You were right. It's a compiler issue.

**Comment by Novivy** [comment]
@al3xc1985 & @wdstudios2 what version of cmake are you using right now?

**Comment by celguar** [comment]
I use Visual Studio 2022, what should I use instead

**Comment by al3xc1985** [comment]
Not visual studio is the problem, but cmake

**Comment by al3xc1985** [comment]
When I get home ai shall see what versions I have on both compiler and precompiler

**Comment by celguar** [comment]
I use same cmake as before. Do you know what version should I use with boost 1.76

**Comment by celguar** [comment]
GitHub build is also affected, it uses latest cmake maybe, not sure

**Comment by al3xc1985** [comment]
VS 2022 17.6
Cmake 3.26.4

**Comment by celguar** [comment]
when was it fixed, if it was? my github build from 10.06 has this issue, but not for all.

**Comment by celguar** [comment]
github build doesn't even specify cmake version, so it uses latest one i assume

**Comment by evil-at-wow** [comment]
That's typically a very recent CMake version indeed. For the TBC core the runner is [windows-2022](https://github.com/cmangos/mangos-tbc/blob/a70aa913f013f16d52bf99576f78d8f47b04ce45/.github/workflows/windows.yml#L17) which GitHub [documents](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md) as having "CMake 3.26.4" installed.

**Comment by AnonXS** [comment]
![image](https://github.com/cmangos/issues/assets/19734826/d434d580-3cb7-4338-b8c3-9b8479db6390)

('175301','1753','2','0','100','1025','75','0','7000','14000','0','0','11','3243','1','0','0','0','0','0','0','0','0','0','Maggot Eye - Cast Life Harvest at 75% HP'),

![image](https://github.com/cmangos/issues/assets/19734826/fdb6091f-2d1e-4388-9786-3db2d33e6dff)

('155401','1554','0','0','100','1025','0','15000','20000','30000','0','0','11','3242','1','0','0','0','0','0','0','0','0','0','Vampiric Duskbat - Cast Ravage'),

![image](https://github.com/cmangos/issues/assets/19734826/5a598bdc-99ee-4ae9-80fe-c4e192354f5a)
![image](https://github.com/cmangos/issues/assets/19734826/941e4003-8bce-4dc2-ab54-bc8eb2046cbb)
![image](https://github.com/cmangos/issues/assets/19734826/5d3f2b80-7edd-472a-92a6-8b7d253e7df9)

![image](https://github.com/cmangos/issues/assets/19734826/8aaffc72-11e2-404d-ad04-ba047af6a899)

('197301','1973','0','0','100','1025','8300','19600','36500','51600','0','0','11','3248','0','0','0','0','0','0','0','0','0','0','Ravenclaw Guardian - Cast Improved Blocking'),

![image](https://github.com/cmangos/issues/assets/19734826/474cccf7-16c3-41bd-a691-f16534e6b52a)

('212003','2120','0','0','100','1025','4500','8600','3300','9700','0','0','11','512','1','1056','0','0','0','0','0','0','0','0','Archmage Ataeric - Cast Chains of Ice'),
