### ISSUE TITLE
🐛 [Bug Report] [WOTLK] Wintergarde keep inn

### ISSUE THREAD

**Issue by Mige5** [cmangos/issues#3445]
### Bug Details

There seems to be no mobs in wintergarde keep inn?

### Steps to Reproduce

1. Go to wintergarde keep inn.

### Expected behavior

Should be mobs?

### Core SHA1 Commit Hash

*

### Database SHA1 Commit Hash

*

### Operating System

Win10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Can confirm.

**Comment by killerwife** [comment]
Confirmed on classic that before all quests, its meant to be empty :D :D :D
