### ISSUE TITLE
🐛 [WOTLK] Heart of the Crusader - Spells like

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3452]
### Bug Details

https://www.wowhead.com/wotlk/spell=21183/heart-of-the-crusader#see-also-other

The paladin talent is about, a thing, and question.

If I learn Heart of the Crusader Rank 1 and I apply it to target, I also have a point in taletns unspent, and after I applied Rank 1 HoC I upgrade it to Rank 2, and I reJudge the target I ALSO apply a Rank 2 HoC.

So bassically I have 2 HoC rank on the same target, and it will give me 3% chance to crit.

Shouldn't Rank 2 overwrite Rank 1?

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
I think this is intended. I know about some speed-guilds that used bugs such as this to debuff-stack Patchwerk in WotLK Naxx for a quicker kill. I'll close this as wontfix for now, if you have objections please reopen.
