### ISSUE TITLE
🐛 [Bug Report] Verog's Head has too low a drop rate

### ISSUE THREAD

**Issue by wdstudios2** [cmangos/issues#3456]
### Bug Details

Verog the Dervish is supposed to drop Verog's Head 100% of the time, as long as you are on the appropriate quest.

I've killed him 4 times while on the quest and he never dropped his head.

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

idk

### Database SHA1 Commit Hash

idk

### Operating System

Win7

### Client Version

2.4.3 (The Burning Crusade)

**Comment by maikale** [comment]
Everything seems to be fine here

creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`, `comments`) VALUES (3395, 5023, -100, 0, 1, 1, 0, 'Verog\'s Head');

**Comment by AnonXS** [comment]
you have to be horde char to make it drop else works fine.

![grafik](https://github.com/cmangos/issues/assets/19734826/a60da551-0c44-4308-9279-e3861df8be45)

**Comment by wdstudios2** [comment]
> you have to be horde char to make it drop else works fine.

I **_am_** a horde character.
