### ISSUE TITLE
I need a clean version of the WoW 1.12.1 client to complete the server extraction

### ISSUE THREAD

**Issue by parashorea** [cmangos/issues#3458]
### Core Version

mangos-classic

### Support Request Details

I need a clean version of the WoW 1.12.1 client to complete the server extraction,I'm so grateful for your assistance.

### Steps to Reproduce

I need a clean version of the WoW 1.12.1 client to complete the server extraction,I'm so grateful for your assistance.

### Core SHA1 Commit Hash

ed06330

### Database SHA1 Commit Hash

ed06330

### Server Operating System

centos

### Client Version

1.1.12 (Classic)

### Client Operating System

Windows

**Comment by miraco** [comment]
> Note: The CMaNGOS project does not supply the retail client files. You must source your own copy of that software.
