### ISSUE TITLE
🐛 [Bug Report] Killing ZG side bosses wont remove Hakkar's big buffs/spells

### ISSUE THREAD

**Issue by ileboii** [cmangos/issues#3463]
### Bug Details

Players are supposed to kill 5 side bosses in ZG (High Priestess Jeklik, High Priest Venoxis, High Priestess Mar'li, High Priest Thekal and High Priestess Arlokk) to get rid of Hakkar's OP abilities.

After the recent change (https://github.com/cmangos/mangos-classic/commit/d07bec6755b3830aca77c0d13fd424f711169c44) those abilities wont get removed anymore, making Hakkar an almost impossible encounter.

### Steps to Reproduce

1. Enter ZG
2. Kill 5 side bosses that are supposed to remove Hakkar's OP abilities (High Priestess Jeklik, High Priest Venoxis, High Priestess Mar'li, High Priest Thekal and High Priestess Arlokk)
3. Pull Hakkar
4. Hakkar still has his OP abilities
5. Wipe

### Expected behavior

1. Enter ZG
2. Kill 5 side bosses that are supposed to remove Hakkar's OP abilities (High Priestess Jeklik, High Priest Venoxis, High Priestess Mar'li, High Priest Thekal and High Priestess Arlokk)
3. Pull Hakkar
4. Hakkar has lost his OP abilities
5. Kill Hakkar

### Core SHA1 Commit Hash

ef797221800493d26e4f5b17d34389953c591d7b

### Database SHA1 Commit Hash

14648a47039f968ec0b09ab395c52fc1135cd9fb

### Operating System

Windows 10

### Client Version

1.12.1 (Classic)

**Comment by killerwife** [comment]
Did you kill them with /die by any chance and if yes, can you try /die 1, instead.

**Comment by killerwife** [comment]
My bad, missing port down from tbc-db. Find one with combat conditions and hakkar. Dont have it handy.

**Comment by AnonXS** [comment]
<https://github.com/cmangos/tbc-db/commit/73a276730b47304776911e391459757f51738d3b>? 

ok our last ported commit to classic is 13 may.

![grafik](https://github.com/cmangos/issues/assets/19734826/1e03a84a-ab61-47a4-ae25-a349817c5bf2)

**Comment by AnonXS** [comment]
Retest with this please.

**Comment by ileboii** [comment]
Nice, Hakkar doesnt get those abilities anymore with that fix! Thank you!

**Comment by ileboii** [comment]
Closing the issue as its fixed
