### ISSUE TITLE
🐛 [Bug Report] Quest 11691 Summon Ahune crashs the server

### ISSUE THREAD

**Issue by betayi** [cmangos/issues#3464]
### Bug Details

Event MidSummer Start a quest of Summon Ahune[11691]; after players finished this quest ,and then use the object IceStone to Summon Ahune, the server will crash.

### Steps to Reproduce

1.event start 1
2.quest accpet 11691
3.go obj id 187882
4.complate this quest
5.use  object IceStone
6.select option of Summon Ahune
7.crash

### Expected behavior

won't crash

### Core SHA1 Commit Hash

3fd7090c2d3a75cfe1129974eb5193afd8191198

### Database SHA1 Commit Hash

d30384e2a9eaf1e64628dd1e1d208b75949f703b

### Operating System

unbuntu20.04

### Client Version

2.4.3 (The Burning Crusade)

**Comment by evil-at-wow** [comment]
Confirmed. 

It looks like we're trying to cast a [spell](https://www.wowhead.com/tbc/spell=45930/ahune-summoning-rhyme-spell-make-bonfire) from a db script that doesn't end well because it's targeting a gameobject:

```
#4  0x000000000116e20a in Object::HasFlag (this=0x61a000044480, index=46, flag=8)
    at cmangos-tbc/src/game/Entities/Object.h:513
#5  0x0000000001a1317a in Spell::CheckCast (this=0x619002127380, strict=true)
    at cmangos-tbc/src/game/Spells/Spell.cpp:5042
#6  0x00000000019fe0e5 in Spell::PreCastCheck (this=0x619002127380, triggeredByAura=0x0)
    at cmangos-tbc/src/game/Spells/Spell.cpp:3068
#7  0x00000000019fe50e in Spell::SpellStart (this=0x619002127380, targets=0x7fffe0525b70, triggeredByAura=0x0)
    at cmangos-tbc/src/game/Spells/Spell.cpp:3107
#8  0x0000000001491ff5 in Unit::CastSpell (this=0x6270005f2900, Victim=0x61a000044480, 
    spellInfo=0x7fffeba9e168, triggeredFlags=64, castItem=0x0, triggeredByAura=0x0, originalCaster=..., 
    triggeredBy=0x0) at cmangos-tbc/src/game/Entities/Unit.cpp:1534
#9  0x0000000001491a30 in Unit::CastSpell (this=0x6270005f2900, Victim=0x61a000044480, spellId=45930, 
    triggeredFlags=64, castItem=0x0, triggeredByAura=0x0, originalCaster=..., triggeredBy=0x0)
    at cmangos-tbc/src/game/Entities/Unit.cpp:1496
#10 0x0000000001247cf9 in ScriptAction::ExecuteDbscriptCommand (this=0x60b000f600c8, pSource=0x6270005f2900, 
    pTarget=0x61a000044480, pSourceOrItem=0x6270005f2900)
    at cmangos-tbc/src/game/DBScripts/ScriptMgr.cpp:2123
#11 0x000000000124314c in ScriptAction::HandleScriptStep (this=0x60b000f600c8)
...
```
So in ```Spell::CheckCast()``` ```target``` turns out to be gameobject, and then calls like ```target->IsTaxiFlying()``` and ```target->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED)``` don't end well because these assume a Unit. 

If you make it to the HasFlag call, the core basically aborts because of an assert: ```MANGOS_ASSERT(index < m_valuesCount || PrintIndexError(index, false));``` (because index = 46 > m_valuesCount = 26).

**Comment by XandrKhv** [comment]
crash occurs when trying to cast spell 45930
blocking the cast of this spell helps avoid crashes
