### ISSUE TITLE
🐛 [Bug Report] Unknown column 'CombatCondition' in 'field list'

### ISSUE THREAD

**Issue by Niam5** [cmangos/issues#3465]
### Bug Details

After commit 23b64e59f3fd5a69fdcf7f86ef1100dd59684459 column CombatCondition does not exist. Database install fails.

### Steps to Reproduce

1. Clone repo
2. Run InstallFullDB.sh
3. Use any option that causes a full world database install
4. Error

### Expected behavior

No error and database installs fully

### Core SHA1 Commit Hash

n/a

### Database SHA1 Commit Hash

785b4b7bc0b92377da71531a09e4868502b4514e

### Operating System

Windows 10

### Client Version

1.12.1 (Classic)

**Comment by Daedalus-code** [comment]
Yes it does. :/
Im on Linux.
