### ISSUE TITLE
🐛 [Bug Report] classic-db install failure

### ISSUE THREAD

**Issue by f0n1x** [cmangos/issues#3467]
### Bug Details

Cannot install classic-db due to latest commit

### Steps to Reproduce

1. Attempt clean/fresh installation of classic-db

### Expected behavior

Successful DB installation

### Suggested Workaround

add the necessary commit for the `CompleteWorldStateID` column to the correct table
-or-
temporary rollback of https://github.com/cmangos/classic-db/commit/f7dfb96352e849e4e2e875993111842cee39a7dc

### Crash Log

  - Applying Updates/4380_blasted_lands_wildlife_3.sql ... SUCCESS
  - Applying Updates/4381_blasted_lands_clack_the_reaver.sql ... SUCCESS
  - Applying Updates/4382_blated_lands_small_thorium_vein.sql ... SUCCESS
  - Applying Updates/4383_swamp_of_sorrows_iron_deposit.sql ... SUCCESS
  - Applying Updates/4384_TDB-0768_hakkar_port.sql ... SUCCESS
  - Applying Updates/4385_burning_steppes_mithril_deposit.sql ... SUCCESS
  - Applying Updates/4386_TDB-0002_creature_spawn_data_template_9989_name.sql ... SUCCESS
  - Applying Updates/4387_TDB-0004_ccsdb_tbc_resistances.sql ... SUCCESS
  - Applying Updates/4388_TDB-0769_worldstate_name_population.sql ... FAILED!
>>> ERROR 1054 (42S22) at line 1: Unknown column 'CompleteWorldStateID' in 'field list'
Press space to continue...

### Core SHA1 Commit Hash

afc0f711db2430bc6580b13444829197fe6096ae

### Database SHA1 Commit Hash

f7dfb96352e849e4e2e875993111842cee39a7dc

### Operating System

Slackware64-15.0

### Client Version

1.12.1 (Classic)

**Comment by AnonXS** [comment]
Missing Core update, when i find it i will add it, seems this update was also pushed in tbc befor the actual core update was ported to db, hence the issue.
