### ISSUE TITLE
TBC - Rare spawns - Patrols

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#3468]
Each comment will be one rare npc detailing which ive gathered data on.

https://www.wowhead.com/tbc/npcs/min-level:57/classification:4#0+3+9

**Comment by killerwife** [comment]
Collidus the warp watcher 4 paths

![image](https://github.com/cmangos/issues/assets/7995382/970b89e5-bace-4afd-8a80-ccb43f125c4f)
- [x]  1

![image](https://github.com/cmangos/issues/assets/7995382/70e198d8-7ba6-44f9-98c1-730f5ae687d8)
- [x]  2

![image](https://github.com/cmangos/issues/assets/7995382/12263ec0-2cf1-45c8-945f-be491e11b33d)
- [x]  3

![image](https://github.com/cmangos/issues/assets/7995382/8d2d6059-06e0-4be9-bbc6-cc2d3d50c17b)

- [x]  4

**Comment by killerwife** [comment]
Ambassador jerrikar 5 paths

![image](https://github.com/cmangos/issues/assets/7995382/11b710af-359a-44d5-bb16-44d5ebfcbbcc)
- [x]  1


![image](https://github.com/cmangos/issues/assets/7995382/a690f008-d7cd-442c-98ae-7745f17f10f5)
- [x]  2


![image](https://github.com/cmangos/issues/assets/7995382/cfa29b16-bc62-41d3-b213-ddf690746d26)
- [x]  3


![image](https://github.com/cmangos/issues/assets/7995382/4668cdee-1d97-4a15-83d5-95f84b9db037)
- [x]  4


![image](https://github.com/cmangos/issues/assets/7995382/eb638eb2-5695-4cdb-b8e8-995fad792b10)
- [x]  5

**Comment by killerwife** [comment]
Kraator - 5 locations - random movement

![image](https://github.com/cmangos/issues/assets/7995382/2cf7b221-7187-43a9-81b9-5e5feecdb904)
- [x]  1

![image](https://github.com/cmangos/issues/assets/7995382/7d1a1e74-db58-402e-bc32-a8c8b5a5c856)
- [x]  2

![image](https://github.com/cmangos/issues/assets/7995382/96614d99-7101-400e-8a15-d678187a9851)
- [x]  3

![image](https://github.com/cmangos/issues/assets/7995382/a13d54c5-9f79-4aed-a40c-07edaa2db272)
- [x]  4

![image](https://github.com/cmangos/issues/assets/7995382/0cfb829e-7e16-41ce-ba86-9ae4cc91e6d8)
- [x]  5

**Comment by killerwife** [comment]
Nuramoc - https://www.wowhead.com/tbc/npc=20932/nuramoc - 3 patrols

![image](https://github.com/cmangos/issues/assets/7995382/ae96fab8-49fe-494e-823a-7e99d41cd64c)
- [x]  1

![image](https://github.com/cmangos/issues/assets/7995382/16e89f8d-05d3-4156-a526-95a12400925d)
- [x]  2

![image](https://github.com/cmangos/issues/assets/7995382/6bdddd08-b2d6-4060-b871-c737fb00288d)
- [x]  3

**Comment by killerwife** [comment]
Chief Engineer Lorthander - https://www.wowhead.com/tbc/npc=18697/chief-engineer-lorthander - 3 paths

![image](https://github.com/cmangos/issues/assets/7995382/be6223f8-2c8b-4c01-876b-ae9593e5729f) 
- [x]  1

![image](https://github.com/cmangos/issues/assets/7995382/4c991550-f36c-4830-b5b2-c9ed4da8bfc9)
- [x]  2 - note, he always dies in the corridor near the end of the loop cos the mobs overwhelm him :D - but it is a looped path sniffed and a couple points have to be made by hand

![image](https://github.com/cmangos/issues/assets/7995382/ffd0eeef-4af6-438b-ad82-68e92db4dcf7)
- [x]  3 - in the mine

<img width="429" alt="image" src="https://github.com/cmangos/issues/assets/7995382/4979f635-8cc1-42d3-ad87-272065e3897a">
seems to talk periodically random texts, if some other rares are discovered to talk, let me know (sniff will prolly see them emote)

**Comment by killerwife** [comment]
Ever core the punisher - https://www.wowhead.com/tbc/npc=18698/ever-core-the-punisher - 3 paths

![image](https://github.com/cmangos/issues/assets/7995382/ac1c3e31-f74a-4259-9b0d-bc65828cabd2)
- [x]  1

![image](https://github.com/cmangos/issues/assets/7995382/997899bf-ac27-480a-9392-305fbde9cab7)
- [x]  2

![image](https://github.com/cmangos/issues/assets/7995382/fb2c6dab-92a2-472b-8f7a-d28a42f4a2b6)
- [x]  3

**Comment by killerwife** [comment]
Speaker Mar'grom - https://www.wowhead.com/tbc/npc=18693/speaker-margrom - 4 paths

![image](https://github.com/cmangos/issues/assets/7995382/5c08a797-ccd6-4f0f-91a2-3d591bbd11eb) - done
![image](https://github.com/cmangos/issues/assets/7995382/00b35444-e933-4593-9481-8bcdd6ca8384) - done
![image](https://github.com/cmangos/issues/assets/7995382/aa977c95-99fc-40c8-95b4-b83eabb4de65) - done
![image](https://github.com/cmangos/issues/assets/7995382/6d1d08f9-ac1d-4872-b9c7-d503a3594cfb) - done

**Comment by killerwife** [comment]
Morcrush - https://www.wowhead.com/tbc/npc=18690/morcrush - 4 paths

![image](https://github.com/cmangos/issues/assets/7995382/6c65f1bc-e54f-4783-8c2f-7a481f863174) - done
![image](https://github.com/cmangos/issues/assets/7995382/928f8946-7ef9-4ea6-ab87-bcb71f873843) - done
![image](https://github.com/cmangos/issues/assets/7995382/e2f14b0c-3e66-4306-9eb8-97b94bf8d978) - done
![image](https://github.com/cmangos/issues/assets/7995382/606ee030-db93-4d82-a598-63862be50c42) - done

**Comment by killerwife** [comment]
Hemation - https://www.wowhead.com/tbc/npc=18692/hemathion - 2 paths

![image](https://github.com/cmangos/issues/assets/7995382/de2c682d-b290-4c08-bf3e-fa18cac5a1ea) - done
![image](https://github.com/cmangos/issues/assets/7995382/ced8e517-9922-411f-9a3e-c73f1b374d90) - done

**Comment by killerwife** [comment]
Marticar - https://www.wowhead.com/tbc/npc=18680/marticar - 3 paths

![image](https://github.com/cmangos/issues/assets/7995382/c0cfa74f-ac6c-45e2-843f-4766cb3d7dcc) - done
![image](https://github.com/cmangos/issues/assets/7995382/88a8e6a9-6da4-431c-812e-392b1d87a83b) - done
![image](https://github.com/cmangos/issues/assets/7995382/9680b8f1-5263-4288-804b-33fc009109f5) - done

**Comment by killerwife** [comment]
Coilfang Emissary - https://www.wowhead.com/tbc/npc=18681/coilfang-emissary - all spawns stationary, some pics for illustration

![image](https://github.com/cmangos/issues/assets/7995382/909b1744-d282-4e72-afb5-64524ea2b1cc)
<img width="158" alt="image" src="https://github.com/cmangos/issues/assets/7995382/ff9e3e47-b208-4352-883a-82bca57ed041">
<img width="47" alt="image" src="https://github.com/cmangos/issues/assets/7995382/1b19e92c-d6bf-467d-81fb-9fd735ef34b7">
![image](https://github.com/cmangos/issues/assets/7995382/a00e465b-5d5e-4e2c-9abb-37c9103fe8f2)
![image](https://github.com/cmangos/issues/assets/7995382/d3d574a4-be0b-4614-89fe-a30fc9e72de3)

**Comment by killerwife** [comment]
Bog Lurker - https://www.wowhead.com/tbc/npc=18682/bog-lurker - 3 paths

![image](https://github.com/cmangos/issues/assets/7995382/3230048c-cf96-4996-ba0c-4584842d767c) - done
![image](https://github.com/cmangos/issues/assets/7995382/fac33f93-7c0a-48c9-813d-77813b80114a) - done
![image](https://github.com/cmangos/issues/assets/7995382/5de1a364-ab46-4d58-abea-829d4b1c3e08) - done

**Comment by killerwife** [comment]
Voidhunter Yar - https://www.wowhead.com/tbc/npc=18683/voidhunter-yar - 1 path

![image](https://github.com/cmangos/issues/assets/7995382/fe6ce4ef-e213-4128-b7ef-ab2773e1c997) - done

**Comment by killerwife** [comment]
Bro'Gaz the Clanless - https://www.wowhead.com/tbc/npc=18684/brogaz-the-clanless - 3 paths

![image](https://github.com/cmangos/issues/assets/7995382/4ab24116-63db-4108-9e2b-6e753f8370e8) - done
![image](https://github.com/cmangos/issues/assets/7995382/4f9c7c97-3cf4-4345-ab24-feba9548cb8c) - done
![image](https://github.com/cmangos/issues/assets/7995382/d5dd19b1-df7e-498e-9504-c167a0b6fcc5) - done

**Comment by killerwife** [comment]
Doomsayer Jurim - https://www.wowhead.com/tbc/npc=18686/doomsayer-jurim - 3 paths

![image](https://github.com/cmangos/issues/assets/7995382/df7be05d-c593-4eaf-8978-0b686bfbce3e) - done - is murdered by peacekeepers on first cycle, likely was meant to go a bit further than that.
![image](https://github.com/cmangos/issues/assets/7995382/ae65ebd3-048a-4b8a-a3bf-5811806d8f4e) - done
![image](https://github.com/cmangos/issues/assets/7995382/b3e9212c-f7e0-43df-806b-8de9af419c6d) - done

**Comment by killerwife** [comment]
Crippler - https://www.wowhead.com/tbc/npc=18689/crippler -  4

![image](https://github.com/cmangos/issues/assets/7995382/ceac2030-68c4-4570-a013-0ea4e85fb211) - done
<img width="84" alt="image" src="https://github.com/cmangos/issues/assets/7995382/1d06ff4f-668b-463d-a994-0edf346f40c2"> - done
![image](https://github.com/cmangos/issues/assets/7995382/f97cabb2-a7ca-42f4-952c-41210b260f3d) - done
<img width="120" alt="image" src="https://github.com/cmangos/issues/assets/7995382/b08cdadb-9a95-4c9a-9e60-f50896f55de4"> - done

**Comment by killerwife** [comment]
Okrek - https://www.wowhead.com/tbc/npc=18685/okrek - 4 patrols

![image](https://github.com/cmangos/issues/assets/7995382/7cad4738-de25-4425-9637-ff20500083ae) - done
![image](https://github.com/cmangos/issues/assets/7995382/e51a31b4-8093-4a9e-b59c-1547b6ea9141) - done
![image](https://github.com/cmangos/issues/assets/7995382/2643c2aa-bb41-4b62-b4ea-014023ececd6) - done
![image](https://github.com/cmangos/issues/assets/7995382/9902579b-f85d-4f79-a456-29293ebd75af) - done

**Comment by killerwife** [comment]
Fulgorge - https://www.wowhead.com/tbc/npc=18678/fulgorge - 3 paths

![image](https://github.com/cmangos/issues/assets/7995382/9de79bc7-04df-4f93-86d6-0365da313065) - done
![image](https://github.com/cmangos/issues/assets/7995382/e5b94bcf-7666-4e5c-8e33-2b0e25efc053) - done
![image](https://github.com/cmangos/issues/assets/7995382/5176f58e-ee02-4939-8424-f87622005480) - done

**Comment by killerwife** [comment]
Megthorg - https://www.wowhead.com/tbc/npc=18677/mekthorg-the-wild - 4 paths

![image](https://github.com/cmangos/issues/assets/7995382/fc9405c4-38ac-4f59-83af-88612a137737) - done
![image](https://github.com/cmangos/issues/assets/7995382/bed0cfaf-d0f2-4535-9983-5c1c12b7ee2a) - done
![image](https://github.com/cmangos/issues/assets/7995382/4e704bb5-e729-4ffb-a39a-75f0adccc9bc) - done
![image](https://github.com/cmangos/issues/assets/7995382/0df26d97-4c91-4e20-affd-5b8464e46a9e) - done

**Comment by killerwife** [comment]
Vorakem Doomspeaker - https://www.wowhead.com/tbc/npc=18679/vorakem-doomspeaker - 4 paths

![image](https://github.com/cmangos/issues/assets/7995382/0410f4fb-782a-46e8-8a7a-d973e4cf97cb) - done
![image](https://github.com/cmangos/issues/assets/7995382/c1fe003c-af42-470c-88d7-4fa53d840190) - done
![image](https://github.com/cmangos/issues/assets/7995382/d85e0499-bdfb-4f66-a1cb-9a198aee52c8) - done
![image](https://github.com/cmangos/issues/assets/7995382/c3523a0c-2a8e-40fc-aff2-bcb9aafd7b60) - done

**Comment by killerwife** [comment]
Goretooth - https://www.wowhead.com/tbc/npc=17144/goretooth - 4 paths

<img width="147" alt="image" src="https://github.com/cmangos/issues/assets/7995382/f9911663-b1dd-4636-9717-9b6ad079515d"> - done
<img width="111" alt="image" src="https://github.com/cmangos/issues/assets/7995382/cd9dc989-b7cc-48cf-a603-62c1ef716555"> - done
<img width="105" alt="image" src="https://github.com/cmangos/issues/assets/7995382/b4f5469c-abf4-4383-96db-c09926b70d0d"> - done
![image](https://github.com/cmangos/issues/assets/7995382/7f488f56-dcf0-4fab-ad9e-42ef64d6d6ab) - done

**Comment by killerwife** [comment]
Shadowmoon data added

**Comment by killerwife** [comment]
Terokkar data added

**Comment by killerwife** [comment]
Nagrand data added

**Comment by killerwife** [comment]
Zangarmarsh, blades edge, hellfire added

**Comment by miraco** [comment]
I think we can close this after your last commits @killerwife?

**Comment by killerwife** [comment]
Yes, I just forgot to create the RP child issue which was the last remaining part.
