### ISSUE TITLE
🐛 [Wiki] About the client file data needed for extraction

### ISSUE THREAD

**Issue by DrKittens** [cmangos/issues#3469]
### Bug Details

Wiki doesnt explicitly note that the CMaNGOS project doesn't provide client files.
That leads to things like https://github.com/cmangos/issues/issues/3458

Suggest amending the Extract Files section to note that we do not provide client files.
Example amendment since github doesn't let you PR wikis or i cant figure it out: https://github.com/drkittens/issues/wiki/Installation-Instructions#extract-files-from-the-client

### Steps to Reproduce

1. N/A

### Expected behavior

End-users following the instructions should not be requesting client data from the project

### Suggested Workaround

Ammend the Extract Files segment to indicate that those files must be self-sourced.

### Core SHA1 Commit Hash

NA

### Database SHA1 Commit Hash

NA

### Operating System

NA

### Client Version

1.12.1 (Classic)

**Comment by miraco** [comment]
> Note: The CMaNGOS project does not supply he retail client files. You must source your own copy of that software.

Thats what you want to add correct?

**Comment by DrKittens** [comment]
> Note: The CMaNGOS project does not supply **t**he retail client files. You must source your own copy of that software.

yup, just not with the typo :P

**Comment by miraco** [comment]
Done.

**Comment by DrKittens** [comment]
Thank you @miraco
