### ISSUE TITLE
🐛 [Bug Report] Annora didn't spawn after you beat all the ten Cleft Scorpid.

### ISSUE THREAD

**Issue by yyhhrr** [cmangos/issues#3479]
### Bug Details

Annora <Master Enchanter> didn't spawn after you beat all the ten Cleft Scorpid.

### Steps to Reproduce

1.beat the Cleft Scorpid
2.no Annora <Master Enchanter> spawn
3.
4.

### Expected behavior

Annora <Master Enchanter> should spawn after you beat all the ten Cleft Scorpid

### Core SHA1 Commit Hash

305486b4208e448434a4380f7bb6c5cf1848c907

### Database SHA1 Commit Hash

ac556b55814e0b2b2bc32420a8228853e3d9a2a5

### Operating System

win 10

### Client Version

1.12.1 (Classic)

**Comment by yyhhrr** [comment]
Still no annora spawn with new fix

**Comment by AnonXS** [comment]
Needs core support, wait or port it in your local.
