### ISSUE TITLE
🐛 [Bug Report] Some Textlines are Hardcoded ! Pls fix

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3480]
### Bug Details

pleas fix this hardcoded Lines to use the DB, that we can make a translation ... !

I really like to work on a translation, but something like this is not helpful !!!!

![grafik](https://github.com/cmangos/issues/assets/6404203/50220fa8-92cc-4c36-a0dc-3c42c8334aab)

### Steps to Reproduce

i was wonder, why the translation from DB dose not work ... so ....

### Core SHA1 Commit Hash

4 Jul 23

### Database SHA1 Commit Hash

4 Jul 23

### Operating System

W11 22H2

### Client Version
2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
I already proposed a fix in discord. You can test it
