### ISSUE TITLE
🐛 [Bug Report]  "The Great Masquerade" quest stuck when all dragon die .

### ISSUE THREAD

**Issue by jerrytt** [cmangos/issues#3482]
### Bug Details

quest was broken.
npc stucked  after  all dragon die

### Steps to Reproduce

just follow the quest .
at last step

### Core SHA1 Commit Hash

3039ef29bd88b73f6ac8336c1ac42149e0d37b3b

### Database SHA1 Commit Hash

b4ec9ee4a8e3e2633284a32af79c76e826569f98

### Operating System

linux

### Client Version

1.12.1 (Classic)

**Comment by jerrytt** [comment]
![2023-07-06-231724_750x525_scrot](https://github.com/cmangos/issues/assets/1201045/269bb29a-b969-40c5-a0a1-ea2e0e8fc43f)

**Comment by jerrytt** [comment]
workaround would be  remove m_guardCheckTimer  = 0 in  wisdsor AI  Reset() .

Reason is  death of windsor will reset all timer for bolvar. which will count for dragon guard death.

**Comment by Ischtaratu** [comment]
![grafik](https://github.com/cmangos/issues/assets/6404203/caa42d42-ec59-447e-ad55-1d9cdd0b3a76)
confirmed ... quest stuck ...

**Comment by Ischtaratu** [comment]
TBC version works, could be used to backport !

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-classic/commit/a23413d69913e5949d0ef56a61aaea2940990d8f
