### ISSUE TITLE
🐛 [Bug Report] Pet pathing problem 

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3484]
### Bug Details

https://youtu.be/q45Vpctq0d0

![grafik](https://github.com/cmangos/issues/assets/6404203/c2e38625-2c11-4267-b41d-5d7c780e9d0c)

### Steps to Reproduce

1. run with a pet through the tunnel
2. at a certain point the pet turns around and runs once around the outside

### Core SHA1 Commit Hash

b889518866fcf5559e69fb9d1e02aab94435969b

### Database SHA1 Commit Hash

 Jul  2 2023

### Operating System

W11 22H2

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Eonfluxx** [comment]
up

**Comment by insunaa** [comment]
Fixed in 71f1dfebb01691933494f9f74d0aa8d37ad9c0c6

**Comment by AnonXS** [comment]
![grafik](https://github.com/cmangos/issues/assets/19734826/9135c73f-1ae9-4731-85fb-d1920f097300)

**Comment by evil-at-wow** [comment]
> Fixed in 71f1dfebb01691933494f9f74d0aa8d37ad9c0c6

Or the TBC equivalent cmangos/mangos-tbc@9bf4a4871505b957ff3b807f04b6eb66fdc4126b given this report was for the TBC core.
