### ISSUE TITLE
🐛 [Bug Report] 

### ISSUE THREAD

**Issue by yajiety** [cmangos/issues#3489]
### Bug Details

[Eluna-CMaNGOS-TBC](https://github.com/Niam5/Eluna-CMaNGOS-TBC)
这个版本出现一个问题，玩家角色进入副本，再出副本，属性会增强，可以无限叠加，以至于达到很高的血量和攻击力；

### Steps to Reproduce

1.[Eluna-CMaNGOS-TBC](https://github.com/Niam5/Eluna-CMaNGOS-TBC)
这个版本出现一个问题，玩家角色进入副本，再出副本，属性会增强，可以无限叠加，以至于达到很高的血量和攻击力；
2.
3.
4.

### Core SHA1 Commit Hash

我是新手，这个地方不知道怎么填写

### Database SHA1 Commit Hash

我是新手，这个地方不知道怎么填写

### Operating System

WIN10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
Please file your bug report with Niam's GitHub, we do not officially support Eluna.
