### ISSUE TITLE
🐛 [Bug Report] 

### ISSUE THREAD

**Issue by yajiety** [cmangos/issues#3490]
### Bug Details

[Eluna-CMaNGOS-TBC-with-eluna-playerbot-ahbot-a29b8771.zip](https://github.com/Niam5/Eluna-CMaNGOS-TBC/releases/download/latest/Eluna-CMaNGOS-TBC-with-eluna-playerbot-ahbot-a29b8771.zip)
这个项目，猎人装备后，远程攻击强度为0；是否是正确的？

### Steps to Reproduce

1.[Eluna-CMaNGOS-TBC-with-eluna-playerbot-ahbot-a29b8771.zip](https://github.com/Niam5/Eluna-CMaNGOS-TBC/releases/download/latest/Eluna-CMaNGOS-TBC-with-eluna-playerbot-ahbot-a29b8771.zip)
这个项目，猎人装备后，远程攻击强度为0；是否是正确的？

### Core SHA1 Commit Hash

我是新手，这个地方不知道怎么填写

### Database SHA1 Commit Hash

我是新手，这个地方不知道怎么填写

### Operating System

WIN10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
Open a bug report on Niam's repository, we don't support Eluna.
