### ISSUE TITLE
🐛 [Bug Report] C’Thun fight missing scripts and mechanics

### ISSUE THREAD

**Issue by rfox33837** [cmangos/issues#3503]
### Bug Details

During the C’Thun fight, going into phase 2, there are missing scripts and mechanics. I.E: Spawning tentacles do not spawn, no eye ball lazor beam, and cannot go inside the boss to remove the damage reduction mechanic

### Steps to Reproduce

1. Enter the temple of Ahn’Qiraj
2. .Go creature C’Thun
3. Start the fight
4. Complete phase 1, going into phase 2
5. Observe phase 2

### Expected behavior

The boss should be spawning tentacles, shooting eye lazor beams around a clockwise rotation, and should be able to enter or be swallowed by the boss to disable the damage reduction mechanic

### Suggested Workaround

The boss is basically a strong meatball.. just keep attacking it for 20-30 mins

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

Windows 11 Pro

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
C'thun does all that already. There's a bug that resets C'thun in the second phase, but none of the things listed here actually apply. Might need to be ported from Classic to WotLK tho

For reference https://github.com/cmangos/issues/issues/3391

Edit2: Not only is the commit hash you posted from cmangos-tbc, it's also from 2021
