### ISSUE TITLE
🐛 [Bug Report] Bug Trio crash in Temple of Ahn’Qiraj

### ISSUE THREAD

**Issue by rfox33837** [cmangos/issues#3504]
### Bug Details

If you kill any one of the bug trio in the Temple of Ahn’Qiraj, the server will crash. This does not happen if you .die after targeting them, however. Only after the fight has started and you kill 1/3 of them.

### Steps to Reproduce

1. Enter AQ40
2. Go to the Bug Trio bosses
3. Engage the bosses and kill at least one with your character

### Expected behavior

Upon on boss dying, the others should be engaging and the dead boss spawns some scarabs / adds, then the fight continues

### Suggested Workaround

Target the bosses and .die

### Core SHA1 Commit Hash

49c8ce69c569622f24b77f3cd84df33da9cb4155

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

Windows 11 Pro

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
Your commit hash is from TBC and from 2021. Update CMaNGOS and report for the correct version, please. I can't reproduce this issue, Bug Trio works fine for me

**Comment by ileboii** [comment]
I've been farming Bug Trio for around three months now with no issues whatsoever - albeit I've been using the most recent SPP (1.12) for this. But since SPP is using cmangos as it's core, I guess it doesn't hurt mentioning this.

**Comment by rfox33837** [comment]
I will fix the hash when I'm home. Apologies for the mistake. I can reassure you this is happening within WoTLk. I have not tested it in a vanilla or tbc though.

**Comment by rfox33837** [comment]
I verified this was resolved in the latest build - Apologies!
