### ISSUE TITLE
🐛 [Wotlk] Hunter Pet - Prowl Ability

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3511]
### Bug Details

https://www.wowhead.com/wotlk/spell=24450/prowl

1. The spell does not reduce pet speed by 50% when pet is stealthed and moving alongside with the hunter. 
IF u attack a target the 50% reduce movement speed start to apply.

So this spell when casted should ALWAYS reduce the 50% movement speed, not just when u command your pet tot attack

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
Actually there is still a missing calibration/ implementation of hunter pets speed, long side spells and talents.

**Comment by insunaa** [comment]
That's not correct. Outside of combat prowl should not reduce the speed of the pet.

**Comment by al3xc1985** [comment]
![image](https://github.com/cmangos/issues/assets/6240049/dc9b0f92-6b8f-4392-816a-f4a978441d7b)

**Comment by miraco** [comment]
https://youtu.be/DVvztO56D1U 
From WOTLK CLassic

**Comment by insunaa** [comment]
This is correct behaviour. A player's pet will always move at the player's speed out of combat. Only in combat will the movement speed be affected

**Comment by al3xc1985** [comment]
Got that . ty
