### ISSUE TITLE
🐛 [Bug Report] [WoTLK] [Quest] The Blackwood Corrupted - Xabraxxis fails to drop Talisman of Corruption

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3514]
### Bug Details

In quest 'The Blackwood Corrupted' (4763) you gather fruit, nut, & grain. Take it to Auberdine Mooonwell and mix it. Take it back to furbolg camp place it in the bonfire. Xabraxxis (4763) appears. When you slay him he should drop Talisman of Coruption (12355) 100% of the time. 

### Steps to Reproduce

1.Take quest The Blackwood Corrupted (4763)
2.Gather three object
3.Mix in bowl at Auberdine Moonwell
4.Place it in furblog camp bonfire closest to Cliffspring River
5. Kill Xabraxxis (10373)

### Expected behavior

Expect Xabraxxis (10373) to drop Talisman of Corruption (12355)

### Suggested Workaround

n/a

### Crash Log

n/a

### Core SHA1 Commit Hash

e8730c6bec98afa7ee50bc57d23751523674a627

### Database SHA1 Commit Hash

f8a48e9e27965dbf310d50774bdab9eb2a6bab86

### Operating System

Ubuntu 20.04 Server LTS

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
Checked it yesterday, and works

**Comment by adellaci** [comment]
It did work this time
