### ISSUE TITLE
🐛 [Bug Report] Commit mangos-wotlk@6c1d505 Broken

### ISSUE THREAD

**Issue by jimmybrancaccio** [cmangos/issues#3518]
### Bug Details

I attempted to update my WotLK instance today however when running `make install` I see the following:

```console
-- Installing: /home/mangos/wotlk/mangos/run/lib/libDetour.a
CMake Error at dep/recastnavigation/Detour/cmake_install.cmake:58 (file):
  file cannot create directory: /recastnavigation.  Maybe need administrative
  privileges.
Call Stack (most recent call first):
  dep/recastnavigation/cmake_install.cmake:47 (include)
  dep/cmake_install.cmake:47 (include)
  cmake_install.cmake:47 (include)
```

I reverted to a different commit - `git checkout 6ad1ff8` and recompiled. When running `make install` it had not issues. It looks like  cmangos/mangos-wotlk@6c1d505 is quite a large commit too 😬

### Steps to Reproduce

1. Clone the `mangos-wotlk` git repository.
2. Check out the commit with the issue - `git checkout 6c1d505`
3. Run `cmake ../mangos -DCMAKE_INSTALL_PREFIX=\../mangos/run -DDEBUG=0 -DPCH=1 -DBUILD_PLAYERBOT=ON -DBUILD_AHBOT=ON -DBUILD_EXTRACTORS=ON -DBUILD_METRICS=ON -DCMAKE_C_COMPILER=/usr/bin/clang-15 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-15 && make -j9`
4. Run `make install`.
5. Observe error posted above.

### Expected behavior

I would expect that `make install` run smoothly without any issues.

### Suggested Workaround

Revert back to a previous commit.

### Crash Log

N/A

### Core SHA1 Commit Hash

6c1d505

### Database SHA1 Commit Hash

N/A

### Operating System

Ubuntu 22.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
Problem is that we're setting BINDIR and LIBDIR, but we're not setting INCLUDEDIR so it tries to install the header-files to an unset path + /recastnavigation suffix => install directly into root /recastnavigation

CMake documentation says that GNUInstallDirs can entirely ignore the CMAKE_INSTALL_PREFIX, so: amazing stuff.

https://github.com/insunaa/mangos-wotlk/tree/meson

Just use meson, CMake is just shit as always

**Comment by insunaa** [comment]
Haven't heard any complaints about WotLK compilation for a while now, so I'm assuming this is fixed. Tentatively closing. Please reopen if it still occurs.
