### ISSUE TITLE
🚀 [Feature Request] The Left Info window

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3522]
### Feature Details

I don't know how to call this window, but on some servers this is found and very interesting and a lot of info about the realm/server can be added there

### Visualizations

![model](https://github.com/cmangos/issues/assets/6240049/72672647-7382-4a7f-b67f-9997fbf36b6e)

### Benefits and Purpose

Nicer

### Core Versions

- [X] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
iirc you need a modified client to change the content of this window, as the URL that it uses to retrieve the content is hard-coded in the client

**Comment by miraco** [comment]
iirc there is another way to do this without modding the client, need to edit a text file in hosts folder

**Comment by insunaa** [comment]
That's still on the client's side, nothing we can change from the side of CMaNGOS, so I'll close this as not planned. If you disagree, alex, comment and I'll reopen

**Comment by killerwife** [comment]
I know how it is done, however this falls under unintended injection of data into client. Ask on a modding discord if you wish to know more but I have no particular interest in sending data to client that wasnt intended to be sent.
