### ISSUE TITLE
🐛 [Bug Report] Human Racials -- Sword/Mace Specialization -- Not Working

### ISSUE THREAD

**Issue by cpevors** [cmangos/issues#3524]
### Bug Details

Humans get +5 permanent bonus to One- and Two-Handed Swords and One- and  Two-Handed Maces. However, that doesn't appear to be working in the current iteration of the project for TBC.

If you see below, you'll see that Swords are capped at the same value as all other weapon skills. (When I lookup the Swords skill, it also indicates that the +perm increase is 0.) I created a Priest and the same behavior holds true for Maces as well. 

![WoWScrnShot_081323_200141](https://github.com/cmangos/issues/assets/139099164/814926b7-21eb-4bc2-b0cb-27dec6320371)

### Steps to Reproduce

1. Create a Human Warrior
2. Open up the Skills tab (hotkey K)
3. Take note that Swords and Maces have the same cap as Axes, Defense, etc.

### Expected behavior

The cap for Swords and Maces should be +5 higher than all other weapon skills, as indicated by their racial abilities, and as evidenced on WoW Classic servers. 

### Core SHA1 Commit Hash

610da379376dbba30c5e358d63bfecc985fe3bcb

### Database SHA1 Commit Hash

08994f501a6bae525c8858173bd395527968600e

### Operating System

Windows 11 Home - 64-bit

### Client Version

2.4.3 (The Burning Crusade)

**Comment by cpevors** [comment]
This seems to affect _all_ races that have a weapon specialization racial, e.g. Orc's Axe Specialization; Troll's Throwing Specialization and Bow Specialization; Dwarf's Gun Specialization. The appropriate weapon skill is not increased by a permanent +5. 

As a flip side and as a possible mechanic to mirror/copy, the profession racials that increase a particular profession skill by +5 or +15 _do_ seem to be working as intended. To test, you could create, say, a Gnome and .learn all_recipes Engineering, and after reviewing the Skills tab see that the Gnome has 390 skill in Engineering, rather than the standard 375. This is to be expected since the Engineering Specialization racial increases the Engineering skill by +15. 

(Similarly, and just to further illustrate, create a Draenei and .learn all_recipes Jewelcrafting; you'll see the Draenei has 380 Jewelcrafting skill -- +5 more than the standard 375, which is to be expected due to the Gemcutting racial.)

So it seems the missing skill increases from racials affect only weapon skills, _not_ profession skills.

**Comment by al3xc1985** [comment]
I am not ar the computer, but as I remmember it's a wotlk issue 2

**Comment by killerwife** [comment]
tbc and wotlk increase expertise, was changed mid tbc, not a bug. Read your racials in spellbook pls.

![image](https://github.com/cmangos/issues/assets/7995382/a239ed5c-73df-4ed8-9056-5456b8844418)

**Comment by al3xc1985** [comment]
I are right

**Comment by al3xc1985** [comment]
I was too lazy 2 corect that
