### ISSUE TITLE
🐛 [Bug Report] Hammer of Wrath always misses

### ISSUE THREAD

**Issue by f0n1x** [cmangos/issues#3525]
### Bug Details

Casting the Paladin ability, Hammer of Wrath, will always miss.
[Video](https://youtu.be/T071WsI85hI)

### Steps to Reproduce

1. Create a Paladin
2. Level to at least level 44 to learn Hammer of Wrath (Rank 1)
3. Fight a mob and reduce it's health to =< 20%
4. Cast Hammer of Wrath

### Expected behavior

Hit and damage.

### Crash Log

N/A

### Core SHA1 Commit Hash

b788602466d629c15dd630aa7f03d6900352d0e9

### Database SHA1 Commit Hash

c6a92ebd20b29abf3d84b186e187627fc8e46763

### Operating System

Slackware64-15.0

### Client Version

1.12.1 (Classic)

**Comment by f0n1x** [comment]
Interesting update here... Hammer of Wrath does hit it's target in a duel with a player.

**Comment by killerwife** [comment]
I linked a commit in tbc branch, that will eventually make it to vanilla branch as well 1:1. Use that if you want to try test this again.

**Comment by f0n1x** [comment]
Thanks KW, appreciate all your work! Will test later and report back.

**Comment by f0n1x** [comment]
There is no matching line in classic for Unit::CalculateEffectiveMissChance() for weapon (only ranged)?
const bool weapon = (!ability || ability->EquippedItemClass == ITEM_CLASS_WEAPON);
should be @ line 3690.
I tried applying the patch anyway by removing line 56, but Hammer of Wrath is still missing.

**Comment by f0n1x** [comment]
Confirmed fixed with d6b4106.
