### ISSUE TITLE
🐛 [BUG] ignoreM2Model allow to cast through textures

### ISSUE THREAD

**Issue by Eonfluxx** [cmangos/issues#3526]
### Bug Details

There's some checks of `WorldObject::IsWithinLOSInMap` that using ignoreM2Model as true. When checking casting, it always ignoring client textures, including BG and arenas. Why it should be like that? It is wrong by all means. 

It is should be like at the screen, but it casting through.
![image](https://github.com/cmangos/issues/assets/131963204/151416ef-5698-41ed-8e43-77be56e42fce)

Please, explain me why it's like that.

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

last

### Database SHA1 Commit Hash

last

### Operating System

win11

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Please tell me on map where you were testing :) This screenshot is not enough.

**Comment by Eonfluxx** [comment]
> Please tell me on map where you were testing :) This screenshot is not enough.

.go xyz 7127 -7037 48 530 and spawn a creature behind the tree. Then try to cast any target spell.

**Comment by Eonfluxx** [comment]
For thix example 
`if (m_spellInfo->HasAttribute(SPELL_ATTR_EX5_ALWAYS_LINE_OF_SIGHT) ||
                    (!IsIgnoreLosSpellCast(m_spellInfo) && !m_IsTriggeredSpell))
                    if (!m_trueCaster->IsWithinLOSInMap(target, true))
                        return SPELL_FAILED_LINE_OF_SIGHT;
`

In Spell.cpp should have ` if (!m_trueCaster->IsWithinLOSInMap(target))`

**Comment by killerwife** [comment]
![image](https://github.com/cmangos/issues/assets/7995382/3410d6ac-a4d7-4429-924a-d87a58b2baf3)
Classic wotlk - used ranged ability through tree to kill it.

![image](https://github.com/cmangos/issues/assets/7995382/29348b18-6d62-4cac-8774-af342ad1de94)
Very much blizzlike.

**Comment by Eonfluxx** [comment]
Of course Blizzard did it this way to reduce the load on the servers, but it shouldn't be the case in Battlegrounds and Arenas. Casting through pillars in Nagrand Arena or stumps in Warsong is ridiculous.

**Comment by insunaa** [comment]
That is accurate to the source material

**Comment by killerwife** [comment]
Feel free to provide videos of arenas and battlegrounds with the evidence. This was super easy to check for me, but despite your reservations to the source, that is not a reason to change it in an emulation project.

**Comment by insunaa** [comment]
![image](https://github.com/cmangos/issues/assets/3718129/29149429-da8c-4d95-ae75-d5630aa9ea90)
this is on CMaNGOS. the nagrand arena is a WMO, and WMOs are *not* affected by the LoS ignore attribute

**Comment by killerwife** [comment]
Correction, they can be, but are not flagged m2.

**Comment by Eonfluxx** [comment]
Warsong

![image](https://github.com/cmangos/issues/assets/131963204/c6529e25-8582-48ca-a81d-be412b4deae0)

**Comment by killerwife** [comment]
Ok but please provide evidence it shouldnt be this way from official servers. These to my knowledge do not prevent los on official either.

**Comment by insunaa** [comment]
In warsong this is the correct behaviour.

**Comment by miraco** [comment]
No bug, thats intended 
video from wotlk classic  https://youtu.be/GYNt6bSHSY0

**Comment by Eonfluxx** [comment]
I would never have believed that on the official server so. Well, thank you for the answers.
