### ISSUE TITLE
🐛 [BUG] Cheat Death not working at all

### ISSUE THREAD

**Issue by Eonfluxx** [cmangos/issues#3527]
### Bug Details

After the recent fix, [Cheat Death] has ceased to function properly. With the talent at 3/3 and a 100% chance, you immediately die.

### Steps to Reproduce

1. duel with rog 3/3 [Cheat Death]
2. attack him till death
3. [Cheat Death] will never trigger

### Core SHA1 Commit Hash

last

### Database SHA1 Commit Hash

last

### Operating System

win11

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
There were a few minor bugfixes needed, but it was still functioning nonetheless. Did you fully rebuild db?

**Comment by insunaa** [comment]
Can't replicate on latest build with latest DB.
