### ISSUE TITLE
🐛 [Bug Report] TBC - Rogue Talent Precision not working

### ISSUE THREAD

**Issue by kepheuswow** [cmangos/issues#3540]
### Bug Details

When I skill the Rogue Talent Precision [https://www.wowhead.com/tbc/spell=13705/precision](url) I don't get the increased chance to hit with weapons. 

![1693678973](https://github.com/cmangos/issues/assets/109022888/318bc2d7-9d43-4726-9514-91a76991482b)

![1693678983](https://github.com/cmangos/issues/assets/109022888/1c554b0b-73a4-4920-a793-b48cf7f3fdf0)

### Steps to Reproduce

1. Skill the Talent Precision
2. Check Melee Stats for Hit Rating
3.
4.

### Expected behavior

Each Rank of Precision should give the character 1% hit chance. 

### Core SHA1 Commit Hash

4c9ae47acdc3743c1cb5e8e9ec83f39d0e2c96f9

### Database SHA1 Commit Hash

dbf9824ca8382f441ccb5c2f3cb967a8ced0e3ba

### Operating System

Arch Linux

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
![grafik](https://github.com/cmangos/issues/assets/19734826/2e3b2827-6850-494e-ae04-ee05b31d69e4)

![grafik](https://github.com/cmangos/issues/assets/19734826/c0a73beb-22c8-479e-914e-4f64ff1bc32f)

**Comment by kepheuswow** [comment]
Sorry. Wasn't aware of this. In Classic it shows me Hit Chance (from Gear + Talent).

How to confirm that it is working or can you confirm this?
