### ISSUE TITLE
🐛 [Bug Report] Quest Freedom For All Creatures

### ISSUE THREAD

**Issue by ekg98** [cmangos/issues#3541]
### Bug Details

The door of the captured sprite darter cage is always open.  Even if you make it to the cage you cannot free any of the sprite darters.  You cant complete this quest.

### Steps to Reproduce

1.Find kindal Moonweaver
2.Get quest.
3.Follow quest

### Expected behavior

Cage should be opened by player.  Then you can free the sprite darters.
https://www.wowhead.com/wotlk/quest=2969/freedom-for-all-creatures

### Suggested Workaround

N/A

### Crash Log

N/A

### Core SHA1 Commit Hash

0b6ed145724bbfe54f426dc34e27de563eb3bc54

### Database SHA1 Commit Hash

660efa422ec93931a3284e72205a0200ceec5cbc

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Grz3s** [comment]
Fixed
https://github.com/cmangos/wotlk-db/commit/7caa1455029bb8137ecda08f20716f0bd26528dc
