### ISSUE TITLE
🐛 [Bug Report] Various Blasted lands quest creature objective not showing

### ISSUE THREAD

**Issue by ekg98** [cmangos/issues#3543]
### Bug Details

Various quests in the Blasted lands don't have their quest objectives appear when mousing over creatures.  They play like a quest from classic before when you were not told what items a particular creature will loot for which quest while mousing over them.

Vulture's Vigor
The Basilisk's Bite 
A Boar's Vitality
Snickerfang Jowls
The Decisive Striker

There could be more.

### Steps to Reproduce

1.Goto blasted lands
2.Get quests
3.
4.

### Expected behavior

I believe quest objectives should be displayed on each creature when mousing over them.  The items required for the quest.  Lungs, Gizzards, etc.  I was playing last night and noticed it right away.  If this area is supposed to be different than the rest then I have no idea.

### Suggested Workaround

N/A

### Crash Log

N/A

### Core SHA1 Commit Hash

0b6ed145724bbfe54f426dc34e27de563eb3bc54

### Database SHA1 Commit Hash

660efa422ec93931a3284e72205a0200ceec5cbc

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
Not sure if it's relevant, but the items required for these blasted lands quests are *not* designated as quest items (by design). They can be traded and auctioned. It's possible that this design decision precludes them from the quest helper.

**Comment by ekg98** [comment]
> Not sure if it's relevant, but the items required for these blasted lands quests are _not_ designated as quest items (by design). They can be traded and auctioned. It's possible that this design decision precludes them from the quest helper.

This could be the case. Any idea how to know what behavior is correct?
