### ISSUE TITLE
🐛 [Bug Report] TBC - Priest Psychic Scream spell bugged

### ISSUE THREAD

**Issue by kepheuswow** [cmangos/issues#3546]
### Bug Details

The bot (Playerbot) is still attacking you while feared. Just white damage, no skills/spells.

Spell used: https://www.wowhead.com/tbc/spell=8124/psychic-scream
Spell IDs: 8122, 8124, 10888, 10890

https://github.com/cmangos/issues/assets/109022888/b519902f-98b0-4b5c-a623-3b732d8c60a1

### Steps to Reproduce

1. do a Duel against a bot (Playerbot)
2. cast Psychic Scream
3.
4.

### Expected behavior

Bot should flee like a regular Player and shouldn't be able to attack.

### Core SHA1 Commit Hash

4c9ae47acdc3743c1cb5e8e9ec83f39d0e2c96f9

### Database SHA1 Commit Hash

dbf9824ca8382f441ccb5c2f3cb967a8ced0e3ba

### Operating System

Arch Linux

### Client Version

2.4.3 (The Burning Crusade)

**Comment by kepheuswow** [comment]
Edit: Corrected my report. On TBC it is only bugged in PVP. In PVE it is working fine.

Also tested it on Classic and it is working fine in PVP / PVE. 

Core: d2d6631d3824fa7c2c3f28e525d33d2fedf2b510
DB: 1abab1db3866652080ed356b2039f498dee951e5

**Comment by kepheuswow** [comment]
In the video shown above I dueled against a bot (Playerbot). When I duel against a Player I don't have this issue. Maybe it has something to do with the Playerbot?

**Comment by insunaa** [comment]
Closing due to deprecation of the old bots.
