### ISSUE TITLE
🐛 [Bug Report] Classic/TBC - Kurzen Commando, Shadowmaw Panther & Syndicate Spy not stealthed

### ISSUE THREAD

**Issue by kepheuswow** [cmangos/issues#3552]
### Bug Details

Shadowmaw Panthers in Stranglethorn Vale are not stealthed. Some are but many of them are not. Also noticed this for Kurzen Commando, Elder Shadowmaw Panther, Syndicate Spy and Syndicate Assassin. 

And Kurzen Commando does not restealth when for example Sap dissipates from them. Should this be the case? If I pull a Shadowmaw Panther, I then run away, they loose aggro and they do restealth. 

Same applies for CMaNGOS Classic. 

**Core**
d2d6631d3824fa7c2c3f28e525d33d2fedf2b510

**DB**
1abab1db3866652080ed356b2039f498dee951e5

https://www.wowhead.com/tbc/npc=684/shadowmaw-panther
https://www.wowhead.com/tbc/npc=1713/elder-shadowmaw-panther
https://www.wowhead.com/tbc/npc=938/kurzen-commando
https://www.wowhead.com/tbc/npc=2242/syndicate-spy
https://www.wowhead.com/tbc/npc=2246/syndicate-assassin

### Steps to Reproduce

1. Check the mob locations
2.
3.
4.

### Expected behavior

All Shadowmaw Panthers should be stealthed. Same goes for Kurzen Commando, Syndicate Spy and Syndicate Assassin.

Also checked Netherwing (Stormforge) and Chromiecraft. They have them all stealthed.

**Kurzen Commando**
https://youtu.be/knerdsGNzT8?feature=shared&t=109

**Shadowmaw Panther**
https://www.youtube.com/watch?v=m8rg1SUqyh4 - official

Here is another one which shows the other Location.
https://youtu.be/MdLuEF3BFtc?feature=shared&t=375 - official

**Syndicate Spy**
https://www.youtube.com/watch?v=siB0ZfqiAdc - official

**Syndicate Assassin**
https://www.youtube.com/watch?v=SWHMw4yAMN4 - official

### Core SHA1 Commit Hash

4c9ae47acdc3743c1cb5e8e9ec83f39d0e2c96f9

### Database SHA1 Commit Hash

dbf9824ca8382f441ccb5c2f3cb967a8ced0e3ba

### Operating System

Arch Linux

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
proof that all are stealthed, always. my data has shown that they dont always restealth on respawn but will do so if left alone for some while.

**Comment by kepheuswow** [comment]
Noticed the same for Syndicate Spy. Needs to be checked.

https://www.wowhead.com/tbc/npc=2242/syndicate-spy

Videos:
https://www.youtube.com/watch?v=kg3WtbZEqzU
https://www.youtube.com/watch?v=5G8xYndFUQs
https://www.youtube.com/watch?v=siB0ZfqiAdc

**Comment by kepheuswow** [comment]
Same with Syndicate Assassin.

https://www.wowhead.com/tbc/npc=2246/syndicate-assassin

Videos:
https://www.youtube.com/watch?v=5G8xYndFUQs
https://www.youtube.com/watch?v=SWHMw4yAMN4

**Comment by kepheuswow** [comment]
EDIT: Updated my main post with all the information.

**Comment by AnonXS** [comment]
Bue proofs nothing, all privat server footage, please dont use that channel as proof in the future. all other links updated as official to be reviewed.

**Comment by kepheuswow** [comment]
Sorry, didn't know that. 

Added a new video from Savix YT channel.
