### ISSUE TITLE
🐛 [Bug Report] TBC - Duskwood Quest window doesn't close on completion

### ISSUE THREAD

**Issue by kepheuswow** [cmangos/issues#3553]
### Bug Details

When I click on "Complete Quest" the Quest will be completed but the window is still open. 

https://www.wowhead.com/tbc/quest=163/raven-hill
https://www.wowhead.com/tbc/quest=165/the-hermit

### Steps to Reproduce

1. Accept the Quest
2. Turn in the Quest 
3. Window stays open
4.

### Expected behavior

The Quest window should automatically be closed upon completion.

### Core SHA1 Commit Hash

4c9ae47acdc3743c1cb5e8e9ec83f39d0e2c96f9

### Database SHA1 Commit Hash

dbf9824ca8382f441ccb5c2f3cb967a8ced0e3ba

### Operating System

Arch Linux

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
That's a client issue. Usually happens when you turn in a quest and then immediately the questgiver starts a script that removes his quest-giver flag. This is normal behaviour
