### ISSUE TITLE
💬 [Support Request] 

### ISSUE THREAD

**Issue by teckkev** [cmangos/issues#3555]
### Core Version

mangos-wotlk

### Support Request Details

Followed (https://github.com/cmangos/issues/wiki/Installation-Instructions) walk-through.   After fixing MySWL Server, everything is setup properly.  

~/cmangos/run/bin/realmd -c ~/cmangos/run/etc/realmd.conf - No errors just waiting on mangosd.

~/cmangos/run/bin/mangosd -c ~/cmangos/run/etc/mangosd.conf -a ~/cmangos/run/etc/ahbot.conf - I have issues!

ySQL client library: 8.0.34
MySQL server ver: 8.0.34-0ubuntu0.20.04.1 

Realm running as realm ID 1

Using World DB: WoTLKDB v1.7+ 'Drakkaris Dream' for CMaNGOS-WOTLK 14065
Using creature EventAI: ACID 3.3.5a (Wrath of the Lich King) for CMaNGOS-WOTLK (3.3.5a Client)

Using DataDir /home/cmangos/run/bin/
WORLD: VMap support included. LineOfSight:1, getHeight:1, indoorCheck:1
WORLD: VMap data directory is: /home/cmangos/run/bin/vmaps
WORLD: MMap pathfinding enabled

Map file '/home/cmangos/run/bin/maps/0004331.map': was not found!
Correct *.map files not found in path '/home/cmangos/run/bin/maps' or *.vmtree/*.vmtile files in '/home/cmangos/run/bin/vmaps'. Please place *.map and vmap files in appropriate directories or correct the DataDir value in the mangosd.conf file.
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted (core dumped)

The file is there!  I searched and saw others with issue but those dated back some years ago and no fixes to help my situation.  I have client copied to my NAS for this step (not sure if that info helps).  I am doing that step again but 1/2 the cores being used and no to high resolution to see if that helps.  This part of setup I am a newbie at.  I have dealt with tre files from swgemu, but WoW is new to me.

### Steps to Reproduce

1.Fresh Ubuntu 20.04 VM / Following https://github.com/cmangos/issues/wiki/Installation-Instructions
2.chmod +x ExtractResources.sh MoveMapGen.sh (not sure what it did)
3.bash ./ExtractResources.sh
4.move the folders maps, dbc, and vmaps - optionally mmaps and Cameras - that have been created to ~/cmangos/run/bin

### Core SHA1 Commit Hash

na

### Database SHA1 Commit Hash

na

### Server Operating System

Ubuntu 20.04 LTS under Oracle VM

### Client Version

3.3.5a (Wrath of the Lich King)

### Client Operating System

Win11, Oracle VM, Ubuntu 20.04 LTS

**Comment by insunaa** [comment]
This is often caused by a modified or corrupted WoW client.

Check your client against these checksums
```
43c62b96fec96cc0c9722fe6ab4dca580d49146c204534492bb6a8aa4accc02c  ./expansion.MPQ
a80aa02c92da5c71e58f03b00539e61f6899e10fdd28f5c535aa079cb9c61b12  ./lichking.MPQ
2880efe61d93b40030bd71946594647414c37bb8f0c48732d07e02bab74bf580  ./common-2.MPQ
c8b78bb75bcf5773e9ae99e11bdfcabc2a37aed3da947367d8af808d4d3c23c6  ./patch-2.MPQ
9101ca1a22e51b2aaf43dc5d171c7e39ba7e0794ea847a04bd6f4dda9e5cc64b  ./patch.MPQ
3ffbd354ebdc5f6c55625eb9386904a0cc704f0c401f520fc5d989f3bad184c5  ./enGB/lichking-locale-enGB.MPQ
9658b915be4f6d5a4403392f8ec357f71999d5018dd29a8bbe63d736725c2357  ./enGB/patch-enGB-3.MPQ
60b4ff552a8184f2e7c802b7c03da98d4b1eb3a3b7a55866f65cc7dce8b8ba91  ./enGB/expansion-locale-enGB.MPQ
4be72a7bca4cfc8004c8643c2362ea12f9c70eb516b7cf06c673a4b1ae01c699  ./enGB/locale-enGB.MPQ
a03035cef4059488bae350147a4fe46d168e9031622c276c6763f7a27c015af0  ./enGB/patch-enGB.MPQ
65dc674102c595f5df7fc930160424364ced628e87e3f5997247c90733260e5a  ./enGB/speech-enGB.MPQ
1d85bffec023d018c8404ae1b954a3574ab86b6ac21a4e6042faa4ad4c1fa2cd  ./enGB/lichking-speech-enGB.MPQ
3b454816cab8dfa550aa1c805540fd4ea8737920cf4f65e01886086c06e8a13d  ./enGB/backup-enGB.MPQ
88e29873cefdd040f134cc4bce101a887857997210af19362dd754d78496c1db  ./enGB/patch-enGB-2.MPQ
6552a1c26bd8a450553de0991be6ca40106f2b60a99f6185c208a58af24c7d77  ./enGB/base-enGB.MPQ
067295eeb18df15952414aa50c88b015d2281a30464e90c26cca3d662a6ce1c1  ./enGB/expansion-speech-enGB.MPQ
4e7d2e42e0c6fb677de564898d81b376d4804ea53fdc34d934bd8626591ac837  ./common.MPQ
56dbbfc8f9ce7182ca88538d75284e738020138a7ca4217d72d8168865510dd3  ./patch-3.MPQ
```

```bash
find /path/to/your/Data/directory -type f -name "*.MPQ" -exec sha256sum {} \;
```
