### ISSUE TITLE
🐛 [Bug Report] Murmur cast resonance always.

### ISSUE THREAD

**Issue by Nightingale9002** [cmangos/issues#3556]
### Bug Details

Murmur （creature id 18708 / 20657 heroric）should cast resonance （spell id 33657） only when there is no target inside melee range, but it can always cast the spell. (creature_spell_list id  1870801 2065701 )

### Steps to Reproduce

1. go to the instance 
2.  battle with murmur
3.

### Expected behavior

Murmur should cast resonance only when there is no target inside melee range

### Core SHA1 Commit Hash

mangos-tbc-master.zip  E1D27B58F1A9B8DD65991F93AED41898EC724175

### Database SHA1 Commit Hash

tbc-db-master.zip AA2850C632C2114233CF4F8B1575B947DC18DDBD

these .zip file are download at 2023/8/25

### Operating System

Windows 11

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Nawakland** [comment]
I can confirm this behaviour, Murmur cast many resonance in a row at melee range or not.

Same behaviour with Warchief Kargath Bladefist in Shattered Halls. Blade dance can be cast indefinitely.
There is a lot of mobs to that have no cooldown on their spell so you can be perma disarm or stunt.

Looks like their is a trouble with the timer system with CombatAI.

**Comment by miraco** [comment]
As a small round up:
Murmur resonance spell_list uses combatcondition 321 with SelfCondition (unit_condition) 361
UnitCondition 361 = NUMBER_OF_MELEE_ATTACKERS equals 0
initialMin = 5000
InitialMax = 12000
RepeatMin = 5000
InitialMax = 12000

I tested it on current db+core with staying out of the ring:
![Wow_SF7EZdRfzD](https://github.com/user-attachments/assets/1f1f5396-ac58-4a04-ba60-a57df68a6222)

Looks right to me for range and here a combatlog while staying in his melee range:
![Wow_Nb5ZmK8n99](https://github.com/user-attachments/assets/c537d016-9e4e-468c-a655-3834c7d6d1c5)

Looks also right for me.
Are you sure you use a unmodified current db/core? Could you maybe provide a video or smth showing that its buged?

**Comment by Nightingale9002** [comment]
> As a small round up: Murmur resonance spell_list uses combatcondition 321 with SelfCondition (unit_condition) 361 UnitCondition 361 = NUMBER_OF_MELEE_ATTACKERS equals 0 initialMin = 5000 InitialMax = 12000 RepeatMin = 5000 InitialMax = 12000
> 
> I tested it on current db+core with staying out of the ring: ![Wow_SF7EZdRfzD](https://private-user-images.githubusercontent.com/6261245/365421451-1f1f5396-ac58-4a04-ba60-a57df68a6222.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODEzMzUsIm5iZiI6MTcyNTc4MTAzNSwicGF0aCI6Ii82MjYxMjQ1LzM2NTQyMTQ1MS0xZjFmNTM5Ni1hYzU4LTRhMDQtYmE2MC1hNTdkZjY4YTYyMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDhUMDczNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjBkNWU5OGRjMzU0NGNiMGVmZWY3ZGRmYzNkMmVlZDIxNDY1ODRlYjRlMTY2Nzk2MTFjN2E0MmU0ZGE4NDU1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Z8V7EIxdFvdQoMLlEoIDpnjmXxwZ3aBnesTaSHDInqc)
> 
> Looks right to me for range and here a combatlog while staying in his melee range: ![Wow_Nb5ZmK8n99](https://private-user-images.githubusercontent.com/6261245/365421543-c537d016-9e4e-468c-a655-3834c7d6d1c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODEzMzUsIm5iZiI6MTcyNTc4MTAzNSwicGF0aCI6Ii82MjYxMjQ1LzM2NTQyMTU0My1jNTM3ZDAxNi05ZTRlLTQ2OGMtYTY1NS0zODM0YzdkNmQxYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDhUMDczNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTM0NTM2YjQxNTljNGMxOTljYWI2OTk4NDA1OGRlNWQ1MzZkNDJjZmMxODMzNjc1MWU5NDc2YWE0NGRmZTIyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hmXZeeiGRJ-5fGXcGCBIfSYM4-MyIRkIyQkacDVc8ZI)
> 
> Looks also right for me. Are you sure you use a unmodified current db/core? Could you maybe provide a video or smth showing that its buged?

I used unmtached database version when doing this, It's OK after updating
