### ISSUE TITLE
🐛 [Bug Report] TBC - Sap and combat

### ISSUE THREAD

**Issue by kepheuswow** [cmangos/issues#3560]
### Bug Details

When I sap a mob, going out of stealth and stand close to the mob then this doesn't get me into combat.  

![1695412614](https://github.com/cmangos/issues/assets/109022888/d17f2e22-e105-4d21-8802-a54dffa7bbc8)

### Steps to Reproduce

1. use Sap on a humanoid NPC
2. go out of stealth
3. stand close to the NPC
4. 

### Expected behavior

If I stand close / I'm close to a sapped mob then I should be in combat. 

https://www.wowhead.com/tbc/spell=6770/sap#comments:id=298514

### Core SHA1 Commit Hash

4c9ae47acdc3743c1cb5e8e9ec83f39d0e2c96f9

### Database SHA1 Commit Hash

dbf9824ca8382f441ccb5c2f3cb967a8ced0e3ba

### Operating System

Arch Linux

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Go inside a dungeon. Outdoors its not correct behavior.

**Comment by insunaa** [comment]
iirc sapping a mob should always completely disable aggro/combat, regardless of dungeon or outdoors. you should be able to walk right through sapped mobs without entering combat.

**Comment by kepheuswow** [comment]
Okay, than it's different in TBC.
