### ISSUE TITLE
🐛 [Bug Report] Wand attack cannot miss.

### ISSUE THREAD

**Issue by santaslittlehelper2** [cmangos/issues#3561]
### Bug Details

Auto attack with Wand never miss only resist if its some element attack. (Fire wand etc...)
Skill 0 can hit any level as well. 

### Steps to Reproduce

1. Equip wand.
2. Attack any target with skill 0.
3. Profit.

### Core SHA1 Commit Hash

5a2a4a20a00239ba4941baa66536b1bab357dbfc

### Database SHA1 Commit Hash

942758213e17b69a4e29f3f8eab6004421d33771

### Operating System

windows 

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Fixed in https://github.com/cmangos/mangos-tbc/commit/fcc3019ad99e6d0de6c3c8dab6d471500c2ccaaf

**Comment by santaslittlehelper2** [comment]
You are such a sweetheart!
