### ISSUE TITLE
🐛 [Bug Report] AnyFriendlyUnitInObjectRangeCheck returns non-friends

### ISSUE THREAD

**Issue by Rochet2** [cmangos/issues#3563]
### Bug Details

Related ticket: https://github.com/ElunaLuaEngine/Eluna/issues/447

> Description: I did some testing in cmangos classic (latest from Niam5). It seems that the Unit:GetFriendlyUnitsInRange( range ) returns table of enemies and neutrals. Not friendlies.
> ![image](https://github.com/cmangos/issues/assets/468816/fa49e16e-be09-4fb6-978a-add4ef3f4433)
> ![image](https://github.com/cmangos/issues/assets/468816/7419e354-b6b7-405b-b204-836ddd530cb8)

It looks like the core side implementation on cmangos classic is not checking for friendliness:
* trinitycore: https://github.com/TrinityCore/TrinityCore/blob/fe2da02cc65a4c549bfea5709d7655c367dca1e9/src/server/game/Grids/Notifiers/GridNotifiers.h#L1007
* cmangos classic: https://github.com/cmangos/mangos-classic/blob/eaa38a9fe61a77d6a50fa448414cb35fd4f09f7a/src/game/Grids/GridNotifiers.h#L994
* mangos zero (classic): https://github.com/mangoszero/server/blob/28425a37e2326c721191895590798f90013f2fe6/src/game/WorldHandlers/GridNotifiers.h#L868

So it looks like a core side issue for cmangos classic.
Looks like in [this commit](https://github.com/cmangos/mangos-classic/commit/d7ff7e15a2ccaa7be81a6776d312b90278975834) the old friendly searcher was renamed and a new one was made that doesnt actually check for friendliness 
![image](https://github.com/cmangos/issues/assets/468816/f3cd4b00-9f0b-4b0b-b762-4cb103d5e8c9)
It probably should check for friendliness also.

### Steps to Reproduce

1. Create a script that uses AnyFriendlyUnitInObjectRangeCheck
2. Go near some unfriendly units and run the script
3. Observe how the AnyFriendlyUnitInObjectRangeCheck returns also hostile creatures in range

### Expected behavior

Only friendly (green, and possibly yellow non hostile?) units should be returned.

### Suggested Workaround

Maybe this function could be used by the gridsearcher to distinct between friend and foe

https://github.com/cmangos/mangos-classic/blob/eaa38a9fe61a77d6a50fa448414cb35fd4f09f7a/src/game/Server/DBCStructure.h#L399

### Core SHA1 Commit Hash

2f61c81298c8c50e6ae505dfbab0332a0df6121d

### Database SHA1 Commit Hash

-

### Operating System

-

### Client Version

1.12.1 (Classic)

**Comment by killerwife** [comment]
Resolved in tbc, i will sync all cores in coming weeks.
