### ISSUE TITLE
🐛 [Bug Report] The Mark of Vashj (WotLK)

### ISSUE THREAD

**Issue by cpevors** [cmangos/issues#3565]
### Bug Details

The Mark of Vashj quest (https://www.wowhead.com/quest=10900/the-mark-of-vashj) should be available to Level 70 characters who venture to Heroic: Slave Pens. At present, it is not. 

### Steps to Reproduce

1. .level 69
2. Set Dungeon Difficulty to 5-Player Heroic
3. .go creature Skar’this

### Expected behavior

He should offer the attunement quest if the character is Level 70. He should not offer if the character is above Level 70. 

### Core SHA1 Commit Hash

N/A

### Database SHA1 Commit Hash

N/A

### Operating System

Windows 11

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Gamemechanicwow** [comment]
I believe you also need to complete the Cypher of Damnation and Naaru trials questlines.

**Comment by cpevors** [comment]
Definitely not required to be completed before. That was not the behavior on Classic live (you can even review WoWhead’s step-by-step attunement guide).

**Comment by cpevors** [comment]
Seems like a simple fix. Change the MaxLevel value in the quest_template table for Quest 10,900 to 70, change the 1,212 value in the Required column to 0. 

Tweaked those manually in my database, and the quest functions as it should.

**Comment by insunaa** [comment]
Gamemechanicwow is correct. This is part of a quest chain and not freely available. I think it may even have been removed entirely in WotLK
