### ISSUE TITLE
🐛 [Bug Report] Memory leak in Extractors

### ISSUE THREAD

**Issue by insunaa** [cmangos/issues#3568]
### Bug Details

There's a memory leak in the extractors, specifically in the function `MapBuilder::buildTile()`

I've commented out every line individually in this function to test whether or not it affects the allocation or not, and the leak only stopped when I commented out `m_terrainBuilder->loadMap()` and `m_terrainBuilder->loadVMap()` and replaced the meshData that they're supposed to fill with bogus data.

I checked the code to the best of my abilities, and there's no heap allocated with new or malloc that isn't deleted or freed, as far as I can tell. Other local variables like meshData and meshDataCopy should run out of scope and be deallocated automatically.

@evil-at-wow 

### Steps to Reproduce

1. Build extractors
2. Run ./MoveMapGen (or the full extractor script)
3. Notice how new memory is allocated but memory usage never goes down until system RAM is filled

### Expected behavior

Files loaded into memory, or other heap allocations should be freed when the function returns.

### Core SHA1 Commit Hash

2545a9d4b8bd0635215c5e45b938666700e0e31a

### Database SHA1 Commit Hash

cc7f08b62c9b2af662468f648dbe606eca96561b

### Operating System

Linux

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Foritus** [comment]
Oh I experienced this! I thought it was odd that I needed 70GB of RAM when extracting TBC maps now (before I never had to worry about it). I don't have a machine with enough RAM to do WOTLK, it gets oomkilled on my 80GB box.

**Comment by insunaa** [comment]
The issue seems to be caused by the internal memory management of G3D.
Why exactly the issue occurs is still not known, but switching from G3D memory management to system memory management solves the issue. To use this workaround apply the following patch:

```patch
diff --git a/dep/g3dlite/System.cpp b/dep/g3dlite/System.cpp
index 6daa3bd53..b6228d92a 100644
--- a/dep/g3dlite/System.cpp
+++ b/dep/g3dlite/System.cpp
@@ -35,7 +35,7 @@
 
 // Uncomment the following line to turn off G3D::System memory
 // allocation and use the operating system's malloc.
-//#define NO_BUFFERPOOL
+#define NO_BUFFERPOOL
 
 #if defined(__i386__) || defined(__x86_64__) || defined(G3D_WIN32)
 #    define G3D_NOT_OSX_PPC
```

**Comment by killerwife** [comment]
I summon thee, @cyberium oh great G3D sorcerer. (I find this to be very unlikely this happened after your recent change)

**Comment by insunaa** [comment]
~~I think the leak was always present, but the expanded parameters that Cyberium is now using have revealed it because it allocates much more memory, which was never freed either before or after Cyberium's changes~~

I should still have unmodified vanilla extractors, I'll test

I retract my statement, in the old extractor (built in June) there's also no leak that I can see (tho the virtual memory allocations are off the charts)

**Comment by insunaa** [comment]
Fixed in https://github.com/cmangos/mangos-wotlk/commit/5c4aa5fb9c3e26fc42705dec49a8a9249bf5b628

**Comment by Foritus** [comment]
Confirmed fixed, just built WOTLK high res maps and it worked first time 🙂 thank you! 💖💖💖
