### ISSUE TITLE
💬 [Support Request] TBC mangosd - lots of errors

### ISSUE THREAD

**Issue by cpevors** [cmangos/issues#3569]
### Core Version

mangos-tbc

### Support Request Details

The following 'error' crops up a lot in my mangosd.

`Call customer support, ChooseDisplayId can not select native model for creature entry 12999, model from creature entry 1 will be used instead.`

I am running the latest commits. 

### Steps to Reproduce

1. Update mangos-tbc and tbc-db to latest commits
2.
3.
4. Launch mangosd

### Core SHA1 Commit Hash

ffd44eab952d4650f43f715939340281f5c1e724

### Database SHA1 Commit Hash

573bbb8f8be331ef721fc0d528b663753c8c25f7

### Server Operating System

Windows 11 64-bit

### Client Version

2.4.3 (The Burning Crusade)

### Client Operating System

Windows 11 64-bit

**Comment by insunaa** [comment]
just ignore them

**Comment by evil-at-wow** [comment]
To be fair, the errors says to 'Call customer support', and here cpevors is, calling customer support! :wink:

On a more serious note, I hope we're not logging errors so people can simply ignore them all. It would be nice to handle this eventually, although I understand this is probably one of those 'special' cases slipping through the cracks seeing creature entry 12999 is a 'World Invisible Trigger'...

**Comment by evil-at-wow** [comment]
I believe this may have been fixed by cmangos/tbc-db@df28d44dd165d5562ee3ef03d047feb160dba245.
