### ISSUE TITLE
Classic database fails to install 🐛 [Bug Report] 

### ISSUE THREAD

**Issue by Patrick-Barry** [cmangos/issues#3570]
### Bug Details

When running ./InstallFullDB.sh and choosing option #2 ( 2) Install fresh Classic-DB only to 'classicmangos') the following error occurs:

> Trying to apply CMaNGOS fixes to dbc datas ...
  - Applying Spell.sql ... FAILED!
>>> ERROR 1054 (42S22) at line 325: Unknown column 'FacingCasterFlags' in 'field list'

### Steps to Reproduce

1. Run ./InstallFullDB.sh
2. Choose option 2

### Expected behavior

Database should install without error.

### Core SHA1 Commit Hash

c6d06ec012aff7a635197c57bd3ba792232b7e50

### Database SHA1 Commit Hash

c63c6475f8b76d0a5904f2140733754030e37d19

### Operating System

Windows 10

### Client Version

1.12.1 (Classic)

**Comment by killerwife** [comment]
Done.
