### ISSUE TITLE
🐛 [Bug Report] Kazzak spell Twisted Reflection don't work right.

### ISSUE THREAD

**Issue by Nightingale9002** [cmangos/issues#3572]
### Bug Details

Kazzak‘s spell Twisted Reflection heals tank, not kazzak.
creature id 18728
spell   20163  20164

### Steps to Reproduce

1.battle with kazzak, waiting for cast Twisted Reflection 
2.
3.
4.

### Expected behavior

Twisted Reflection should heal kazzak.

### Core SHA1 Commit Hash

Relase 23-9-30

### Database SHA1 Commit Hash

Updates 216

### Operating System

Windows 11

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
Which kazzak. Doom lord kazzak. highlord kruul or Lord kazzak.

**Comment by Nightingale9002** [comment]
> 哪个卡扎克。末日领主卡扎克。克鲁尔勋爵或卡扎克勋爵。

doom lord kazzak  18728
