### ISSUE TITLE
🐛 [Bug Report] SQL Error installing Wotlk database

### ISSUE THREAD

**Issue by Patrick-Barry** [cmangos/issues#3591]
### Bug Details

While installing the wotlk database I received the following error: 

 - Applying Updates/5163_c.4855.sql ... FAILED!
>>> ERROR 1064 (42000) at line 7: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE Entry = 4855' at line 1

I don't know SQL very well, but it appears as if one too many commas are on the line. There is one just before the "WHERE Entry = 4855"

### Steps to Reproduce

1. Run ./InstallFullDB.sh
2. Select 2 to install the database

### Expected behavior

Database should install without error.

### Core SHA1 Commit Hash

d28db40fb17a2d32c8db2964ce867197f2df8692

### Database SHA1 Commit Hash

c3b8940b7231d2e1784121b02f405b60ff07dab4

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by dunjeon** [comment]
Can confirm. I just removed that file, for now.
