### ISSUE TITLE
🐛 [Bug Report] Digging for Prayer Beads quest - Fei Fei behaviour

### ISSUE THREAD

**Issue by LEO33SoFo** [cmangos/issues#3592]
### Bug Details

The dog **[Fei Fei](https://www.wowhead.com/tbc/npc=20206/fei-fei)** doesn't move when feeding him with [Fei Fei Doggy Treat](https://www.wowhead.com/tbc/item=31799/fei-fei-doggy-trea) while doing the [Digging for Prayer Beads](https://www.wowhead.com/tbc/quest=10916/digging-for-prayer-beads) quest.

### Steps to Reproduce

I did the quest normally without GM commands.
Otherwise:
1. `.quest add 10916`
2. `.additem 31799`
3. `.go creature id 20206`
4. Feed the dog and check for the aforementioned issue.

### Expected behavior

The dog either should go to the correct hidden place of [Fei Fei's Cache](https://www.wowhead.com/tbc/object=185302/fei-feis-cache#contains) or move around to specific places according to Wowhead's [comments](https://www.wowhead.com/tbc/quest=10916/digging-for-prayer-beads#comments).

### Core SHA1 Commit Hash

7f53efbc9de308e28924701fa7c1480e4d54a42b

### Database SHA1 Commit Hash

40ecf15ce40a3865d27187c5724604f8a2f552b1

### Operating System

Windows 8.1 Pro with Update 3 64bit

### Client Version

2.4.3 (The Burning Crusade)

**Comment by MantisLord** [comment]
This is reported in the console when you turn in quest 10919:
```
 DB-SCRIPTS: WARNING: Process table `dbscripts_on_quest_end` id 10919, command 20 has no OTHER buddy 20206 found - maybe you need to update the script?
 DB-SCRIPTS: Process table `dbscripts_on_quest_end` id 10919, command 20 call for non-creature, skipping.
```
In this case we don't need a buddy creature with entry 20206 because we turn in the quest to creature 20206 already. The search is unnecessary.
We also need to correct Fei Fei's movement dbscripts for the same reason:
```
 DB-SCRIPTS: WARNING: Process table `dbscripts_on_creature_movement` id 2020601, command 25 has no OTHER buddy 20206 found - maybe you need to update the script?
 DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2020601, command 25 call for non-creature, skipping.
  DB-SCRIPTS: WARNING: Process table `dbscripts_on_creature_movement` id 2020602, command 20 has no OTHER buddy 20206 found - maybe you need to update the script?
 DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 2020602, command 20 call for non-creature, skipping.
