### ISSUE TITLE
🐛 [Bug Report] Paladin Judgement of Command 

### ISSUE THREAD

**Issue by Dwyriel** [cmangos/issues#3596]
### Bug Details

Judgement of Command is supposed to deal a certain damage against non-stunned enemies, and increased damage against stunned or incapacitated enemies, but it's currently always dealing increased damage on every enemy.
Tested with all 5 ranks of Seal of Command, images from when I was still leveling up (SoC Rank 3).
![img1](https://github.com/cmangos/issues/assets/61030926/9fca8138-7024-4f1b-8e56-3200c6af00ed)
![img2](https://github.com/cmangos/issues/assets/61030926/8f90e612-af1c-4535-9e74-73454b7101d4)
![img3](https://github.com/cmangos/issues/assets/61030926/b9a2d1a5-418d-48a5-90cd-0ac677d60fba)
ps: I'm somewhat new to vanilla/classic and to paladin, I'm sorry if this is the expected behavior for the skill in PvE scenarios.

### Steps to Reproduce

1. Use Seal of Command (any rank)
2. Use Judgement on a stunned or incapacitated enemy  
3. Repeat last two steps but without stunning or incapacitating the enemy
4. Observe damage dealt.

### Expected behavior

Judgement of Command to deal proper (decreased) damage when enemy isn't stunned/incapacitated.

### Core SHA1 Commit Hash

c6d06ec012aff7a635197c57bd3ba792232b7e50

### Database SHA1 Commit Hash

9e3786e4c38c31877839691054d119565eda15bd

### Operating System

Linux

### Client Version

1.12.1 (Classic)

**Comment by MantisLord** [comment]
I wasn't able to reproduce this in TBC - it seems to work properly there at least:

![image](https://github.com/cmangos/issues/assets/16798471/a44e0b34-1e9d-418e-a989-6f75dafe1a90)

It does full damage by default, but it is halved if the target is not stunned.
This is the relevant code here: https://github.com/cmangos/mangos-classic/blob/master/src/game/Spells/SpellEffects.cpp#L356

**Comment by Dwyriel** [comment]
Haven't updated the server and database since those commits: https://github.com/cmangos/mangos-classic/commit/c6d06ec012aff7a635197c57bd3ba792232b7e50 https://github.com/cmangos/classic-db/commit/65a758271680f9f32f636fb955eb390ed3f6905e. So the issue might or might not have been fixed since then.

I just tested again to make sure it was bugged (as it's been a few months since I opened this issue and played the game) and yeah it is. Always deals the stunned damage no matter the rank of Seal of Command or if it was a crit or not. 

Some pics:
Theramore dummy (SoC Rank 1):
![first](https://github.com/cmangos/issues/assets/61030926/ba073635-60c2-4823-8d4b-be0513ba9128)

Lvl 61 enemy (SoC Rank 1):
![sec](https://github.com/cmangos/issues/assets/61030926/62c4ec9c-2c7d-481a-a2c5-f292356a6b99)
![third](https://github.com/cmangos/issues/assets/61030926/6d5d1a83-e90d-493d-b57a-7b0b8544952e)

Lvl 57 enemy (SoC Rank 5):
![fifth](https://github.com/cmangos/issues/assets/61030926/7ae16bcc-0ade-4583-8b1d-e6de909f5513)
![fourth](https://github.com/cmangos/issues/assets/61030926/3fa995cf-a2d1-46d9-9dcb-a8e7fc6ec4fc)

PS: if there's a way to debug this issue more in-depth without having to run the server through a debugger let me know how to and I'd be more than happy to do so.

**Comment by MantisLord** [comment]
It seems it's caused by a difference in the spell data for Judgement of Command in Vanilla when compared to TBC+.
```
select Id,SpellFamilyFlags,SpellFamilyName from spell_template where Id IN (20467,20963,20964,20965,20966,27171);
select Id,SpellFamilyFlags,SpellFamilyName from classicmangos.spell_template where Id IN (20467,20963,20964,20965,20966,27171);
```
TBC
![image](https://github.com/cmangos/issues/assets/16798471/2e56453a-91c8-41f7-aee5-83ce1074bc94)

Vanilla
![image](https://github.com/cmangos/issues/assets/16798471/a41ca705-f8e7-45ae-bc31-7e6ba3350352)

In Vanilla, we have no SpellFamilyFlags/Name for the spells, so the code I mentioned above is never hit.
We can see it ends up going to the SPELLFAMILY_GENERIC path instead of SPELLFAMILY_PALADIN:
![image](https://github.com/cmangos/issues/assets/16798471/c4aaf871-73f4-4e51-9582-93fab5e69bfb)

**Comment by MantisLord** [comment]
Should be all set now. We don't need this in WotLK because they changed how the ability worked by then.
