### ISSUE TITLE
🚀 [Feature Request] Implement subcommand to .tele

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3598]
### Feature Details

We currently have a problem to teleport to a map that is arena. The server does not let u teleport to an arena map.

I suggest to implement a command especially for this matter so we (gm's) can teleport to an arena map/ arena match (how is it stored? by id? so we can teleport to that arena map match id, but simplu arena map in general.

For example I suspect that we miss some spawns to arena of lordaeron ruins but in current implementation I can't tele over there

### Visualizations

a

### Benefits and Purpose

a

### Core Versions

- [ ] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by killerwife** [comment]
Its done through .goname command to a specific player, so its already possible. Currently the teleportation to a specific instance would be too annoying to do. (someone can PR it) Otherwise wont spend time on this.
