### ISSUE TITLE
🐛 [Bug Report] Enchanting other player's items does not consume materials 

### ISSUE THREAD

**Issue by Dwyriel** [cmangos/issues#3599]
### Bug Details

When enchanting another players items no materials are consumed. This issue seems to have been fixed for TBC, but never backported to Classic, or if it was it has been reverted since then.
Commit: https://github.com/cmangos/mangos-tbc/commit/706a0e8062da73995a48bd7d8a84e47bb236d568 
Issue: #2789

### Steps to Reproduce

Enchant someone else's items while paying attention to how much of each material you have. 

### Core SHA1 Commit Hash

https://github.com/cmangos/mangos-classic/commit/c6d06ec012aff7a635197c57bd3ba792232b7e50

### Database SHA1 Commit Hash

https://github.com/cmangos/classic-db/commit/9e3786e4c38c31877839691054d119565eda15bd

### Operating System

Linux

### Client Version

1.12.1 (Classic)

**Comment by f0n1x** [comment]
Confirmed bugged, and confirmed that https://github.com/cmangos/mangos-tbc/commit/706a0e8062da73995a48bd7d8a84e47bb236d568 fixes the issue on vanilla/classic.

**Comment by yajiety** [comment]
巫妖王之怒3.3.5版本，也存在此问题未修复。

**Comment by Exxenoz** [comment]
Tested and works after https://github.com/cmangos/mangos-classic/commit/f6cf658c33404603ac2f42cc705c40539f6d9603

Issue can be closed.
