### ISSUE TITLE
🐛 [WOTLK] Blackblade of Shahram -  2 Hand Sword

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3601]
### Bug Details
https://www.wowhead.com/wotlk/item=12592/blackblade-of-shahram#comments

This item has a proc chance to summon
https://www.wowhead.com/wotlk/npc=10718/shahram#abilities;mode:40player

But I don;t know if the chance on hit  is good in cmangos (Need to be verified)

When it summons Shahram he should be alive only until he finish to cast one of his spells , random cast
![image](https://github.com/cmangos/issues/assets/6240049/51f7b142-dfd2-4ed7-ba5b-f6ed6a978db3)
https://www.wowhead.com/wotlk/spell=16597/curse-of-shahram
https://www.wowhead.com/wotlk/spell=16600/might-of-shahram
https://www.wowhead.com/wotlk/spell=16601/fist-of-shahram
https://www.wowhead.com/wotlk/spell=16599/blessing-of-shahram
https://www.wowhead.com/wotlk/spell=16598/will-of-shahram
https://www.wowhead.com/wotlk/spell=16596/flames-of-shahram
Now what is interesting is that if u can hit multiple targets at once, he should be spawned one for each target that he procs for
https://www.youtube.com/watch?v=rakfLOlB-xc

Also what is important that the effects do stack

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
This might be double in Acid, not sure

**Comment by al3xc1985** [comment]
This might help
c mangos introduced it I believe
https://github.com/vmangos/core/commit/2c4ec612dcedb33c4fd3903ac221a67e89932eef

**Comment by fatalieror** [comment]
i have made already a ticket issues/2568

**Comment by al3xc1985** [comment]
ok, ty
