### ISSUE TITLE
🐛 [WOTLK] Kagani Nightstrike - Small error in db that can be fixed

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/issues#3603]
### Bug Details

![image](https://github.com/cmangos/issues/assets/6240049/bf9b79a5-a451-4321-ad38-8dd079e5757a)

In db he has a small mistake in spell id
![image](https://github.com/cmangos/issues/assets/6240049/1c627c79-e446-4bf7-9c25-d0a55447a89e)

wich also gives first image error.

it should be 44289 and not 44288, cause he has this spell
![image](https://github.com/cmangos/issues/assets/6240049/6b570296-1028-4b59-bafd-9ec0f65765cc)

that is an aura casted on spawn (specific rogue)

Also he misses one more spell
![image](https://github.com/cmangos/issues/assets/6240049/63aa6811-ebc6-457c-a22b-a844cfeb9d87)

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

4aa81134be302fed4a22f1c2e01374e3c3

### Database SHA1 Commit Hash

87d213957c5f6d4e2e3679eaf81986eb43e32525

### Operating System

windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by al3xc1985** [comment]
@AnonXS I am poking u for this one to see, please

**Comment by al3xc1985** [comment]
so modification in script and instance file is required

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/f74ec94f5d4cd295319458ebb9c5972e416efb42
