### ISSUE TITLE
🐛 [Bug Report] Quest "Hunting for Ectoplasm"

### ISSUE THREAD

**Issue by Dwyriel** [cmangos/issues#3604]
### Bug Details

Related issues: #3392 #537

Currently the [Ectoplasmic Distiller](https://www.wowhead.com/classic/item=21946/ectoplasmic-distiller) item, when used, does not apply the [buff](https://www.wowhead.com/classic/spell=27420/ectoplasmic-distiller) to the player, or to nearby enemies. It does, however, visually work.

The enemies that are supposed to drop those items (21937, 21936, 21935) also currently do not drop them, though if what I read on the other issues related to this quest hasn't changed they should be dropping the ectoplasms without requiring the use of the distiller.

I've killed around 40 legitimately in all 3 areas and also killed whole camps using `.die` to see if they'd drop anything or not. Done so over multiple sessions and on two different characters.

Video:
https://youtu.be/Rk5EjsqVld8

### Steps to Reproduce

See above.

### Core SHA1 Commit Hash

https://github.com/cmangos/mangos-classic/commit/c6d06ec012aff7a635197c57bd3ba792232b7e50

### Database SHA1 Commit Hash

https://github.com/cmangos/classic-db/commit/65a758271680f9f32f636fb955eb390ed3f6905e

### Operating System

Linux

### Client Version

1.12.1 (Classic)

**Comment by f0n1x** [comment]
Classic still needs https://github.com/cmangos/mangos-wotlk/commit/c5a27bb5364fd499a7bd9bcac17d1d7c88b68cab implemented/backported.

**Comment by Exxenoz** [comment]
> Classic still needs [cmangos/mangos-wotlk@c5a27bb](https://github.com/cmangos/mangos-wotlk/commit/c5a27bb5364fd499a7bd9bcac17d1d7c88b68cab) implemented/backported.

It was backported here: https://github.com/cmangos/mangos-classic/commit/e3796fc2654e75ce8e70ff71a61c291bffd9d3de

**Comment by Dwyriel** [comment]
Is the quest currently working then? I haven't updated my server/db in a long while plus I'm on a trip right now and can't quite test it myself

**Comment by cpevors** [comment]
> Is the quest currently working then? I haven't updated my server/db in a long while plus I'm on a trip right now and can't quite test it myself

Yes!

**Comment by Dwyriel** [comment]
Alrighty, closing this issue then :)
