### ISSUE TITLE
🐛 [Bug Report] Failed compilation extractors (only ad and vmap_extractor) on w11

### ISSUE THREAD

**Issue by Arnibou** [cmangos/issues#3606]
### Bug Details

On windows 11 and visual studio community 2022 -> Failed compilation: ad and vmap_extractor (vmap_assembler and MoveMapGen works) with option BUILD_EXTRACTORS in cmake.

Tested: cmangos_classic et cmangos_tbc-> failed both

### Steps to Reproduce

1. Configure et generate cmangos with cmake (check BUILD_EXTRACTORS)
2. Generate solution with visual studio community 2022

### Crash Log

[log_build_w11.txt](https://github.com/cmangos/issues/files/13311164/log_build_w11.txt)

### Core SHA1 Commit Hash

b634d2649183124fec2b7d6af96ad8f01b0b82c1

### Database SHA1 Commit Hash

423f741d1f8210be6563aa62af555950b42af8ba

### Operating System

Windows 11

### Client Version

1.12.1 (Classic)

**Comment by Niam5** [comment]
Solution is to remove dep/libmpq/win/stdint.h. Cyberium should be porting down the changes to all the repos sometime today. Until that happens remove the file, clear cmake cache, rerun cmake, and build. Should build fine.

**Comment by Arnibou** [comment]
Thanks, it works

**Comment by Arnibou** [comment]
Fixed
