### ISSUE TITLE
🚀 [Feature Request] Is there a Chinese version of the file?

### ISSUE THREAD

**Issue by alexyang-sea** [cmangos/issues#3607]
### Feature Details

1, I just compiled the classic, but after entering the game, I found that when I use 1.12 client, the NPCs and quests are all in English, but when I use 1.14 client to enter, the NPCs are in Chinese, but the quests are still in English, and the skill introduction is all in Chinese. I would like to ask, does mangos-classic have any Chinese sql, if so, in which file and which table to import? If not, is it possible to consider Chineseisation like AzerothCore? 
2、I'm trying to compile playerbot into classic, and after compiling, I'm importing all the sql provided by playerbot into characters, but several of the sql from vallia are prompted an error, I don't know where I can find the detailed steps and parameter settings about how to import playerbot's sql.

### Benefits and Purpose

I hope it can have Chinese sql like AzerothCore and support Chinese.
1. When importing the sql provided by Playerbot in characters using Mysql workbench, the weight... and node... and node... sql will report an error
2. Into the game, only the skill introduction is in Chinese, quests and NPCs are in English, where can I find the Chinese database!

### Core Versions

- [X] 1.1.12 (Classic)
- [ ] 2.4.3 (The Burning Crusade)
- [ ] 3.3.5a (Wrath of the Lich King)

**Comment by cailei0596** [comment]
1.14的客户端还能连上？不是说只支持1.12

**Comment by alexyang-sea** [comment]
我从有爱论坛下了个支持112服务端的别人改过的114客户端，也可以进去，只不过稳定性不知道如何，没有怎么体验，因为我还是想把机器人编译进去，只不过还没成功，不知道该怎么导入机器人哪些数据库到哪些表里

**Comment by uty3714** [comment]
我也是刚编译，登录上之后但是一直开登录游戏服务器，不能创建角色，不知道为啥。我已经试了好多次了。 ubuntu20.04

**Comment by cailei0596** [comment]
> 我也是刚编译，登录上之后但是一直开登录游戏服务器，不能创建角色，不知道为啥。我已经试了好多次了。 ubuntu20.04

realmlist表address字段没有配置对

**Comment by uty3714** [comment]
> > 我也是刚编译，登录上之后但是一直开登录游戏服务器，不能创建角色，不知道为啥。我已经试了好多次了。 ubuntu20.04
> 
> realmlist表address字段没有配置对

是的，我改成了服务器的ip可以了，我记得以前127.0.0.1 是可以的。

**Comment by alexyang-sea** [comment]
> > > 我也是刚编译，登录上之后但是一直开登录游戏服务器，不能创建角色，不知道为啥。我已经试了好多次了。 ubuntu20.04
> > 
> > 
> > realmlist表address字段没有配置对
> 
> 是的，我改成了服务器的ip可以了，我记得以前127.0.0.1 是可以的。

你们进去后是不是跟我一样有些任务NPC的对话没有汉化，有些是半英文半中文的？虽然我已经安装了中文配置。另外，如何用命令提升GM呢？常用的“account set gmlevel “提示命令不存在

**Comment by uty3714** [comment]
> > > > 我也是刚编译，登录上之后但是一直开登录游戏服务器，不能创建角色，不知道为啥。我已经试了好多次了。 ubuntu20.04
> > > 
> > > 
> > > realmlist表address字段没有配置对
> > 
> > 
> > 是的，我改成了服务器的ip可以了，我记得以前127.0.0.1 是可以的。
> 
> 你们进去后是不是跟我一样有些任务NPC的对话没有汉化，有些是半英文半中文的？虽然我已经安装了中文配置。另外，如何用命令提升GM呢？常用的“account set gmlevel “提示命令不存在

我的全部未汉化，1.12版本， 命令可以用。

**Comment by alexyang-sea** [comment]
> > > > > 我也是刚编译，登录上之后但是一直开登录游戏服务器，不能创建角色，不知道为啥。我已经试了好多次了。 ubuntu20.04
> > > > 
> > > > 
> > > > realmlist表address字段没有配置对
> > > 
> > > 
> > > 是的，我改成了服务器的ip可以了，我记得以前127.0.0.1 是可以的。
> > 
> > 
> > 你们进去后是不是跟我一样有些任务NPC的对话没有汉化，有些是半英文半中文的？虽然我已经安装了中文配置。另外，如何用命令提升GM呢？常用的“account set gmlevel “提示命令不存在
> 
> 我的全部未汉化，1.12版本， 命令可以用。

SPP可以在安装界面选择有个选项是transnation,然后选择安装中文就可以，但进去后还是有部分英文。ike3的需要自己手动导入汉化文件，其实就是用的芒果的本地文件。
