### ISSUE TITLE
🐛 [Bug Report] classic db typo

### ISSUE THREAD

**Issue by s20blast** [cmangos/issues#3609]
### Bug Details

creature_template table
entry 7168 - there is a space before name Polly. " Polly"
entry 5683 - his name is corma. not comar. https://www.wowhead.com/classic/npc=5683/corma-villard
entry 17249 - first name only. family name "Longshot" is needed. https://www.wowhead.com/classic/npc=17249/landro-longshot

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

b634d2649183124fec2b7d6af96ad8f01b0b82c1

### Database SHA1 Commit Hash

28288663b1c265d0d0a212a06603547c7b74ef72

### Operating System

macos

### Client Version

1.12.1 (Classic)

**Comment by AnonXS** [comment]
```
ServerToClient: SMSG_CREATURE_QUERY_RESPONSE (0x0061) Length: 72 ConnectionIndex: 0 Time: 12/02/2007 23:02:18.000 Number: 22156
Entry: 5683
[0] Name: Comar Villard
```

-- sniffbuild "31727" - " Polly"

```
ServerToClient: SMSG_CREATURE_QUERY_RESPONSE (0x0061) Length: 89 ConnectionIndex: 0 Time: 11/01/2007 08:43:58.000 Number: 9116
Entry: 17249
[0] Name: Landro Longshot
```
