### ISSUE TITLE
🐛 [Bug Report] The Binding (q.1795) uncompleteable

### ISSUE THREAD

**Issue by f0n1x** [cmangos/issues#3610]
### Bug Details

Strahad Farsan despawns at the end of "The Binding" and the quest cannot be completed.

### Steps to Reproduce

1. Create a Warlock
2. Level to 30
3. Start the Felhunter quest chain from your class trainer, "Seeking Strahad" (q.2996 or q.3001 or q.1798)
4. Complete the chain until you get to "The Binding" (q.1796)
5. Complete the quest as normal and attempt to turn it in.
6. Strahad Farsan (n.6251) will show the completed yellow "?" but you will be unable to interact with him and he will despawn within 5-10 seconds.

### Expected behavior

Not have the npc (strahad Farsan) despawn and have him interactable.

### Suggested Workaround

Unsure if this is an ACID script or db issue. I'll dig deeper to see if I can find a workaround/solution, but I wanted to get this documented.

### Crash Log

N/A

### Core SHA1 Commit Hash

b634d2649183124fec2b7d6af96ad8f01b0b82c1

### Database SHA1 Commit Hash

423f741d1f8210be6563aa62af555950b42af8ba

### Operating System

Slackware64-15.0

### Client Version

1.12.1 (Classic)

**Comment by miraco** [comment]
Maybe missing backport from tbc
https://github.com/cmangos/tbc-db/commit/c35165481c09441adc62a611379b32f74a19257c

Edit: nvm already got backported https://github.com/cmangos/classic-db/commit/8c7558b4577063e3fb3f4ab0651a1c498c3c0cc9

**Comment by f0n1x** [comment]
Not sure if it's relevant or not, but he hasn't respawned after 10 hours

**Comment by AnonXS** [comment]
![image](https://github.com/cmangos/issues/assets/19734826/7620791d-a79d-4c41-a820-b82b9c14979e)

![image](https://github.com/cmangos/issues/assets/19734826/d68c8c67-108b-44a6-b93a-9a9e8bf5f92a)

currently mob despawns very fast if not instantly attacked after it is summoned, guy walks back out, after shortly despawned and respawned in the hut. (maybe the issue)

![image](https://github.com/cmangos/issues/assets/19734826/3d481dc7-7445-4aff-abd2-8e8da44458dc)

my problem is guy cant be talked to after he walks back outside.

![image](https://github.com/cmangos/issues/assets/19734826/f86c83ac-e403-4b18-881e-2d8699e7ae98)

when killed and respawned it works.

![image](https://github.com/cmangos/issues/assets/19734826/db1375bb-28f7-47fa-82f9-556c1ddde91d)

![image](https://github.com/cmangos/issues/assets/19734826/51ff3616-36d7-4348-9b24-cc4ba1b7a0a6)

![image](https://github.com/cmangos/issues/assets/19734826/1c4815a9-1a5b-4a7b-ac49-55b189c0f54e)

![image](https://github.com/cmangos/issues/assets/19734826/56e54177-fdc7-4c34-ab94-c79d1f0d9a6f)

**Comment by f0n1x** [comment]
So... he's not despawned or dead, he's just invisible to non-gm players, also cannot talk to him as a gm. Killing him and letting him respawn or forcing a .respawn does temporarily resolve the issue, but I don't think that's intended behavior nor a long term solution.

**Comment by AnonXS** [comment]
I've just looked at it from player perspective, he despawns and respawn in the hut then goes back outside, but i could not turn in the quest when i killed the mob.

so yes should be looked at again imo.

**Comment by f0n1x** [comment]
I wasn't trying to be dismissive. You're 100% correct. Really, I was trying to correct my original assessment that he doesn't "despawn" he's still there if you turn on GM mode, so no amount of waiting is going to result in him "returning". I actually think we're arguing the same thing here.

**Comment by miraco** [comment]
Seems like a mangos-classic only problem, on fresh tbc its working as intended.

Can show you video if needed, i dont have a classic client/core+db on my pc cause i only programm on tbc, so cant rly help you with this, sry

**Comment by f0n1x** [comment]
[The Binding](https://youtu.be/_J1Bi-nP5B4)

**Comment by miraco** [comment]
Can you do „.npc info“ when he is back at his position?

**Comment by f0n1x** [comment]
Ok, doing some more testing while getting npc info:
If you "fail" (not a true fail, but you will have to abatdon and re-accept the quest) the quest by either not summoning a felhunter (by using the book) or not attacking the summoned felhunter in time (very short timer, like 5s), Strahad does NOT disappear for the player. You are able to interact with him, abandon quest and re-accept and he will run his script but still enter a bad state on success.
Also, Strahad only disappears for the player when you walk far enough away from him, but it is a fairly short distance. If you stay close to him, he will stay visible but un-interactable.
Here is the npc info for various states:

Before quest (script):
Player selected: Creature (Entry: 6251 Counter: 14366) DBGuid: 14366.
Faction: 35.
npcFlags: 3.
Entry: 6251.
DisplayID: 4940 (Native: 4940).
Level: 60.
Health (base): 2884. (max): 2884. (current): 2884.
UnitFlags: 768 | DynamicFlags: 0 | ExtraFlags: 65538
SpawnTime: Full:4m35s Remain:0s
Corpse decay remaining time: 0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 0
Position: -785.911987 -3723.260010 40.515202.
Combat timer: 0
Is in evade mode: false
UNIT_FIELD_BYTES_0: 0 : 8 : 0 : 0
UNIT_FIELD_BYTES_1: 0 : 0 : 0 : 0
UNIT_FIELD_BYTES_2: 1 : 16 : 0 : 0
Spell Lists enabled ID 0
Combat timer: 0 Leashing disabled: false
Combat Script: false
Movementflags: 256

After quest (script) - before disappearing:
Player selected: Creature (Entry: 6251 Counter: 14366) DBGuid: 14366.
Faction: 35.
npcFlags: 51.
Entry: 6251.
DisplayID: 4940 (Native: 4940).
Level: 60.
Health (base): 2884. (max): 2884. (current): 2884.
UnitFlags: 768 | DynamicFlags: 0 | ExtraFlags: 65538
SpawnTime: Full:4m35s Remain:0s
Corpse decay remaining time: 0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 0
Position: -785.911987 -3723.260010 40.452801.
Combat timer: 0
Is in evade mode: false
UNIT_FIELD_BYTES_0: 0 : 8 : 0 : 0
UNIT_FIELD_BYTES_1: 0 : 0 : 0 : 0
UNIT_FIELD_BYTES_2: 1 : 16 : 0 : 0
Spell Lists enabled ID 0
Combat timer: 0 Leashing disabled: false
Combat Script: false
Movementflags: 4194561
*** is a trainer!

After quest (script) - after disappearing:
Player selected: Creature (Entry: 6251 Counter: 14366) DBGuid: 14366.
Faction: 35.
npcFlags: 51.
Entry: 6251.
DisplayID: 4940 (Native: 4940).
Level: 60.
Health (base): 2884. (max): 2884. (current): 2884.
UnitFlags: 768 | DynamicFlags: 0 | ExtraFlags: 65538
SpawnTime: Full:4m35s Remain:0s
Corpse decay remaining time: 0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 0
Position: -785.911987 -3723.260010 40.452801.
Combat timer: 0
Is in evade mode: false
UNIT_FIELD_BYTES_0: 0 : 8 : 0 : 0
UNIT_FIELD_BYTES_1: 0 : 0 : 0 : 0
UNIT_FIELD_BYTES_2: 1 : 16 : 0 : 0
Spell Lists enabled ID 0
Combat timer: 0 Leashing disabled: false
Combat Script: false
Movementflags: 256
*** is a trainer!

Failed quest (script):
Player selected: Creature (Entry: 6251 Counter: 14366) DBGuid: 14366.
Faction: 35.
npcFlags: 3.
Entry: 6251.
DisplayID: 4940 (Native: 4940).
Level: 60.
Health (base): 2884. (max): 2884. (current): 2884.
UnitFlags: 768 | DynamicFlags: 0 | ExtraFlags: 65538
SpawnTime: Full:4m35s Remain:0s
Corpse decay remaining time: 0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 0
Position: -785.911987 -3723.260010 40.452801.
Combat timer: 0
Is in evade mode: false
UNIT_FIELD_BYTES_0: 0 : 8 : 0 : 0
UNIT_FIELD_BYTES_1: 0 : 0 : 0 : 0
UNIT_FIELD_BYTES_2: 1 : 16 : 0 : 0
Spell Lists enabled ID 0
Combat timer: 0 Leashing disabled: false
Combat Script: false
Movementflags: 4194561

The differences seem to be npcFlags, Position, Movementflags, and whether or not he is flagged as a trainer.

Lastly, is there a way to force the felhunter to attack the summoning player?

**Comment by miraco** [comment]
I see the error.
in tbc creature_template NpcFlags is different to classic. On TBC he has NpcFlags 51:
UNIT_NPC_FLAG_TRAINER_CLASS, UNIT_NPC_FLAG_TRAINER, UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAG_GOSSIP

in classic npc flags 51 would be:
UNIT_NPC_FLAG_SPIRITHEALER, UNIT_NPC_FLAG_TRAINER, UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAG_GOSSIP

https://github.com/cmangos/classic-db/commit/8c7558b4577063e3fb3f4ab0651a1c498c3c0cc9#diff-a0ac8a5b3d91dd6e49d4460005aa10a034244b42bac4c131d39ea49b6dbfa8a4R24
This line will need to get changed, but im not sure what  flags he should actualy have in classic.

Iirc the Fehlhunter despawns when he is 6 seconds ooc (after getting spawned) "failing" the quest and let strahad move back to his position.
i would need to look into sniffs, but iirc felhunter shouldnt attack the player by default

**Comment by f0n1x** [comment]
I think just drop the UNIT_NPC_FLAG_SPIRITHEALER flag (32), so 19? I'll make the change in my db and test.

**Comment by miraco** [comment]
Yes and no, he has npcflags 3 before, so it should be 3 after again.
idk if he is already a trainer in classic or not

**Comment by f0n1x** [comment]
19 would be 16+2+1 so, it would still be keeping the 3. I'm only removing 32 (Spirit Healer flag).
the old flags were 51, which is 32+16+2+1

**Comment by f0n1x** [comment]
nvm, I see what you meant, he starts as 3 and I'm adding 16 by using 19.

**Comment by f0n1x** [comment]
Removing 32 worked btw, I'll write a PR to change the line to 3 as I don't see him as a trainer in classic as you mentioned.
