### ISSUE TITLE
🚀 [Feature Request] How come there's no playerbot?

### ISSUE THREAD

**Issue by alexyang-sea** [cmangos/issues#3611]
### Feature Details

I compiled mangos-classic, but when I enter the game I don't see the playerbot, but in the compiled file I see the playerbot config file, do I need to download the bot module separately?

### Benefits and Purpose

很想编译出带playerbot的mangos-classic

### Core Versions

- [X] 1.1.12 (Classic)
- [ ] 2.4.3 (The Burning Crusade)
- [ ] 3.3.5a (Wrath of the Lich King)

**Comment by Dwyriel** [comment]
Are you perhaps confused as to what playerbots should be? PlayerBots are not autonomous accounts that play the whole game by themselves. They are simply semi-autonomous AIs for your other characters that you can add to the game and control using the `.bot` commands ([here's a list of said commands](https://github.com/cmangos/mangos-classic/blob/master/doc/PlayerBot/commands.txt)). 

They'll follow you around and try to assist you with whatever you're doing, they can complete quests, use items, etc. But you're still "their master".

**Comment by alexyang-sea** [comment]
Of course I know what playerbots are, they are random bots built by the system that can also go online and quest and upgrade together with their characters under the same number. I have compiled playerbots and experienced them in AzerothCore. But now classicmangos I compiled and entered the game and I'm alone in the world, there are no random bots and I can't go online with my character under the same number. So I don't know which step is the problem. playerbot's configuration has not been changed at all!

**Comment by kelbren** [comment]
Playerbots in Cmangos are not random player bots populating the world. They are characters on the same account you have logged in with that can join you. for example, create 2 characters on the same account, say bob and sally. login with bob and use the .bot add sally. Sally will login and join you.

If you looking for the original ike3 type player bots, Celguar maintains a cmangos core with ike3 random bots. 
https://github.com/celguar

**Comment by alexyang-sea** [comment]
@kelbren Thanks, I've been compiling celguar's ike3 bots for the past few days, but I've been unsuccessful in importing the bot database. Also, does classicmangos not have a localised database file?
