### ISSUE TITLE
🐛 [Bug Report] Fel Iron and Adamantite nodes only ever have 1 ore instead of random amount

### ISSUE THREAD

**Issue by Patrick-Barry** [cmangos/issues#3612]
### Bug Details

When using the mining skill on fel iron and normal adamantite ore nodes they only ever have 1 of the ore. Other items that can be looted from the nodes such as motes/gems seem to be normal though. 

### Steps to Reproduce

1. Mine fel iron or a normal adamantite ore node
2.
3.
4.

### Expected behavior

Nodes should have a random amount of ore. (I think its between 1-3 pieces)

### Core SHA1 Commit Hash

bf770ecdfaf99101df9392ac7727f67f90e47e98

### Database SHA1 Commit Hash

c422bbfbae9f08c1ea11e73e65d82dc5c9165cc4

### Operating System

Windows 10

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
https://github.com/cmangos/wotlk-db/commit/e481ff3897f68417a29df9fd96add30f0dc4b245
