### ISSUE TITLE
🐛 [Bug Report] TBC Zul'Gurub arlokk bug！

### ISSUE THREAD

**Issue by Yuukiring** [cmangos/issues#3616]
### Bug Details

1.Arlokk can be summoned indefinitely by banging the gong, 
and after defeating Arlokk, the Zul'Gurub Trigger will attack players, causing them to be stuck in combat.

2.Using commands related to gobs such as 'gobject near' can cause the game to crash.

### Steps to Reproduce

1.go arlokk
2.
3.
4.

### Core SHA1 Commit Hash

latest

### Database SHA1 Commit Hash

latest

### Operating System

win10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by celguar** [comment]
https://github.com/cmangos/issues/issues/3474 for classic

**Comment by AnonXS** [comment]
duplicate
