### ISSUE TITLE
🚀 [Feature Request] Does playerbot have a corresponding plugin?

### ISSUE THREAD

**Issue by alexyang-sea** [cmangos/issues#3622]
### Feature Details

There are a lot of commands for playerbot, it's still a bit inconvenient to control it with commands every time, I don't know if there's any corresponding plugin I can use?Besides, the bots with the same number are all crowded together, I don't seem to see any command that can make them spread out a little bit, after I use /t botname fowwow far, I will be prompted that there is no such subcommand.

### Benefits and Purpose

About Plug-ins

### Core Versions

- [X] 1.1.12 (Classic)
- [ ] 2.4.3 (The Burning Crusade)
- [ ] 3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
There is no official addon for playerbots
