### ISSUE TITLE
Can't view Numeric HP of NPCs💬 [Support Request] 

### ISSUE THREAD

**Issue by LastWoWProject** [cmangos/issues#3628]
### Core Version

mangos-tbc

### Support Request Details

i Can't view Numeric HP of NPCs,it only show percentage.

How can i see numberic hp?

Thanks

### Steps to Reproduce

1.numeric hp for npc and mobs/bosses
2.
3.
4.

### Core SHA1 Commit Hash

latest

### Database SHA1 Commit Hash

linux

### Server Operating System

linux

### Client Version

2.4.3 (The Burning Crusade)

### Client Operating System

windows

**Comment by AnonXS** [comment]
mangosd.conf

```
#    Visibility.FogOfWar.Health
#        Sets visibility mode for absolute health values. Fog Of War settings are not applied to GMs.
#        Default: 0 (Pre-3.0 standard setting: players can see health values of units in their own group)
#                 1 (players can see health values of same faction units)
#                 2 (Post-3.0 standard setting: players can see health values of all units)
```
