### ISSUE TITLE
💬 [Support Request] about tbc anticheat

### ISSUE THREAD

**Issue by Yuukiring** [cmangos/issues#3631]
### Core Version

mangos-classic

### Support Request Details

Is cmangos-tbc's anticheat ineffective? It's not effective at all, accelerating up to 10x doesn't even detect it, instead there are a bunch of useless false detections.
Is there a way to port anticheat from vmangos, that one is more perfect.

### Steps to Reproduce

1.
2.
3.
4.
no

### Core SHA1 Commit Hash

latest

### Database SHA1 Commit Hash

latest

### Server Operating System

2012R2

### Client Version

2.4.3 (The Burning Crusade)

### Client Operating System

win10

**Comment by insunaa** [comment]
The anticheat is unfinished and therefore in a semi-disabled state. To enable overspeed detection etc. you need to change the settings in anticheat.conf

**Comment by killerwife** [comment]
Also I will add one thing, our vanilla one is actually the same as the vmangos one (originated from same author initially). The differences that are across expansions are not trivial.
