### ISSUE TITLE
🐛 [Bug Report] Daggerfen Assassin stealth attack and Ethereal Plunderer backstab ability problem

### ISSUE THREAD

**Issue by Szymplo** [cmangos/issues#3632]
### Bug Details

Doing quest "Message to the Daggerfen" leaves not good game-experience. Daggerfen Assasin while stealth just run towards player but he doesn't do any damage.

Ethereal Plunderers are sometimes trying to attack from behind but they attack looks to be unfinished. 

### Steps to Reproduce

1. Go to Zangarmarsh 25.5 25.5 and pull Daggerfen Assasin
2. He attacks normally and deal domage till goes stealth. After that he just run after u doin nothing
1b. Go to Tomb with Ethereal Plunderer wait until he will try to attack from behind
2b. See that he just try to backstab but it seems that he doesnt make a finishing move just stand for a while behind you

### Expected behavior

Daggerden Assasin and Ethereal Plunderer supprise attacks should deal damage

### Core SHA1 Commit Hash

162cd3f237022e229da6cc976295a607e0a1cc76

### Database SHA1 Commit Hash

9cc4fb63c86a908c0d2ac387fdec0d560bff65b1

### Operating System

Debian 11 with MariaDB

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
backstab seems to work.

![image](https://github.com/cmangos/issues/assets/19734826/667fb16d-aac8-4336-911f-bf375dacea72)

**Comment by Szymplo** [comment]
Hey, what about Daggerfen Assasins? Did you check it? Cause if it works right im going to upgrade Server.
