### ISSUE TITLE
🐛 [Bug Report] Quest "Vengeful Harbringer" Face does not spawn - can't finish quest

### ISSUE THREAD

**Issue by Szymplo** [cmangos/issues#3636]
### Bug Details

Quest Looks really good there are flying bodies and waves attacking. Sadly after all of them are killed and guard make something with body of last enemy and the purple thing are flying around Face doesn't spawn and I cannot finish the quest

### Steps to Reproduce

1. Go to Tomb and use the Tomb Relic
2. Notice that the guardian spawns and everything works nice until u take care of last mob
3. Guardian dies and the body of last enemy fly up (which is good)
4. Sadly after purple things start to dance there is no face to finish quest
5. I did quest chain "I See dead people" thinking this is necessary but it didnt help
6. Tried to do that quest twice (same effect)

### Expected behavior

After killing last mob guardian go to its body dies and body fly up. Purple things dancing but in the end the face should appear

### Core SHA1 Commit Hash

162cd3f237022e229da6cc976295a607e0a1cc76

### Database SHA1 Commit Hash

9cc4fb63c86a908c0d2ac387fdec0d560bff65b1

### Operating System

Debian 11 with MariaDB

### Client Version

2.4.3 (The Burning Crusade)

**Comment by rayonpt** [comment]
can confirm this issue too, tested and does not spawn object 

Draenei Ascendant - 184830

Object can be seen in GM MODE, just needs script to spawn it when event finishes.

**Comment by tehmasterer** [comment]
Confirmed.

Gave this half a dozen attempts on my questing to 70.

After killing the Vengeful Harbinger...
- He floats into the air and get shocked by the orbs before disappearing.
- The orbs swirl around for a bit.
- You hear the sound of a corpse hitting the ground like 10x in a row.
- The orbs disappear.
- The Ascendant never spawns.

**Comment by AnonXS** [comment]
duplicate https://github.com/cmangos/issues/issues/3238
