### ISSUE TITLE
🐛 [Bug Report] TBC - Interacting with "Tear of Tilloa" spawns two hostile "Unseen"

### ISSUE THREAD

**Issue by tehmasterer** [cmangos/issues#3638]
### Bug Details

Tear of Tilloa is a lootable item found in Duskwood, that is part of the quest "A Noble Brew". When looting this item on cmangos, two hostile Unseen spawn, which is not part of the quest. These are level 49-51 invisible enemies that will crush the average person questing in Duskwood.

As it stands, the quest cannot be completed at the appropriate level, unless you cheat the item in.

### Steps to Reproduce

1. Start looting the Tear of Tilloa.
2. Two invisible, Unseen spawn and start attacking.
3. You die.

### Expected behavior

No Unseen should spawn. They are not related to the quest.

### Suggested Workaround

Cheating the item in. Item code 2779.

### Core SHA1 Commit Hash

46ce862172aee1d1ff969f33e20374c3c869d40b

### Database SHA1 Commit Hash

5914db5509a28a4ead85a117096cb18bf0aad613

### Operating System

Linux

### Client Version

2.4.3 (The Burning Crusade)

**Comment by tehmasterer** [comment]
Forgot to add the screenshot I took.

![unseen-bug](https://github.com/cmangos/issues/assets/33169068/ed76855d-0813-48f8-bd5e-89cefbdaba4e)

**Comment by MantisLord** [comment]
This is an interesting bug. As far as I can tell, the Unseen are invisible mobs which aren't supposed to attack the player normally unless they're seen/attacked themselves. However what's happening in this case is the quest object is a Chest type, and chests have a special script which aggros nearby enemies. See here: https://github.com/cmangos/mangos-tbc/blob/master/src/game/AI/ScriptDevAI/scripts/world/spell_scripts.cpp#L1118
If we compare this to the VMaNGOS counterpart, we can see the logic is quite different:
https://github.com/vmangos/core/blob/development/src/game/Objects/GameObject.cpp#L1472
It uses the faction of the gameobject to help make the determination of which nearby enemies to aggro. Maybe that approach is more appropriate here, but this requires some more research.

**Comment by miraco** [comment]
This was easier to fix then I thought. 
According to my sniffs from classic and conspiring npcs with vmangos, this npcs should just have a different faction, now they shouldn’t attack anymore.
