### ISSUE TITLE
🐛 [Bug Report] Create Healthstone consumes SoulShard but no Healthstone in bag appear

### ISSUE THREAD

**Issue by Szymplo** [cmangos/issues#3639]
### Bug Details

Tested on Warlock lvl 65 with Create Healthstone - Spell (rank 5)
  

### Steps to Reproduce

1. Create Healthstone (rank 5) having one ore more SoulShards in bag
2. See that ShoulShard is consumed but even if there is a place in bags no healthstone appears

### Expected behavior

Healthstone should be created if there is a place in Bag and there is SoulShard needed to create it

### Core SHA1 Commit Hash

46ce862172aee1d1ff969f33e20374c3c869d40b

### Database SHA1 Commit Hash

5914db5509a28a4ead85a117096cb18bf0aad613

### Operating System

Debian 11

### Client Version

2.4.3 (The Burning Crusade)

**Comment by CaptainJaySolo** [comment]
I have also encountered this issue.
Not sure if it's for all Warlocks, but I tested this on an Undead Warlock.
When using the spell "Create Healthstone" the animation plays and the Soul Stone gets consumed, however no Healthstone gets put in the inventory.

**Comment by cpevors** [comment]
I have successfully created Healthstone of all ranks on a Human and an Undead without issue. I cannot replicate.

**Comment by Szymplo** [comment]
Hey just upgraded server to recent version
tbc-db version 4628fead00eb634246164c3c7fc4ddb426bd4e13
mangos-tbc version 49d61a35905ac3e41dd920c8621d625790d0c1b4
AND now it works correctly. Thank You!

**Comment by kjarex** [comment]
I didn't check what the issue in detail has been here - but in classic(!) there is a `!` missing in `GetUsableHealthStoneItemType` quite at the beginning in the line which should read `if (!target || !target->IsPlayer())`

**Comment by MilkmanMHOC** [comment]
Just to confirm, this is an issue in classic and i can confirm changing line 112 in warlock.cpp to add the missing "!" fixes the issue.

**Comment by Exxenoz** [comment]
Tested and works after https://github.com/cmangos/mangos-classic/commit/107e480f3ac48380fe7de90440a9cd2136ba3ac3

Issue can be closed.
