### ISSUE TITLE
🐛 [Bug Report] [WoTLK] [Warning] SpawnManager.cpp

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3651]
### Bug Details
~~~
/home/mangos/cmangos/wotlk/src/game/Maps/SpawnManager.cpp: In member function ‘bool SpawnManager::IsEventGuid(uint32, HighGuid) const’:
/home/mangos/cmangos/wotlk/src/game/Maps/SpawnManager.cpp:233:1: warning: control reaches end of non-void function [-Wreturn-type]
  233 | }
      | ^
~~~

### Steps to Reproduce

1.Compile Lastest
2.
3.
4.

### Core SHA1 Commit Hash

27999d818ce8b308e30a24526b7705335d5b3dbc

### Database SHA1 Commit Hash

N/A

### Operating System

Ubuntu Server LTS 20.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
Fixed in https://github.com/cmangos/mangos-wotlk/pull/493

**Comment by adellaci** [comment]
It is and thank you
