### ISSUE TITLE
🐛 [Bug Report] Terokk's Downfall quest - Terokk can't be killed

### ISSUE THREAD

**Issue by LEO33SoFo** [cmangos/issues#3655]
### Bug Details

During the [Terokk's Downfall](https://www.wowhead.com/tbc/quest=11073/terokks-downfall) quest, when fighting [Terokk](https://www.wowhead.com/tbc/npc=21838/terokk), he can't be killed when going with him at the blue flame markers, his [Divine Shield](https://www.wowhead.com/tbc/spell=40733/divine-shield) aura is not temporarily dropped.

### Steps to Reproduce

1. Buff yourself in order to solo him.
2. `.quest add 11073`
3. `.go object id 185928`
4. Summon **Terokk** and fight him.

### Expected behavior

According to [Warcraft Wiki](https://warcraft.wiki.gg/wiki/Terokk), **Terokk**'s shield aura should be dropped for few seconds when approaching the blue flame markers.

### Core SHA1 Commit Hash

3615f1ce6128270de85ef2d7ff78d02f86cf9e40

### Database SHA1 Commit Hash

4b654fbf0f2c2efeb295622954d6fe772d1035a5

### Operating System

Windows 8.1 with Update 3 Professional 64bit

### Client Version

2.4.3 (The Burning Crusade)

**Comment by miraco** [comment]
Works fine for me on newest cmangos-tbc core/db
https://youtu.be/R75R2iYu_Xw

**Comment by LEO33SoFo** [comment]
Yeah, after updating to the newest current TBC core/DB, this problem is fixed.
It's safe to close this issue now I think.
