### ISSUE TITLE
🐛 [Bug Report] Ghost Mushroom on Skulk Rock don't respawn

### ISSUE THREAD

**Issue by Szymplo** [cmangos/issues#3661]
### Bug Details

The Ghost mushrooms on Skulk Rock (The Hinterlands) don't respawn. 
I checked it multiple times on test server without any people.
The only way to get Skulk Rock Ghost Mushrooms respawned is - Server Restart
I waited 3 days - none of them did respawn.

### Steps to Reproduce

1.Go to Skulk Rock (The Hinterlands) and gather all Ghost Mushrooms from Skulk Rock
2.Wait 3 or more days and get back there
3.Check if you find any of them again
4.

### Expected behavior

I Think Skulk Rock Ghost Mushrooms should respawn 

### Core SHA1 Commit Hash

49d61a35905ac3e41dd920c8621d625790d0c1b4

### Database SHA1 Commit Hash

4628fead00eb634246164c3c7fc4ddb426bd4e13

### Operating System

Debian 11 + Mariadb

### Client Version

2.4.3 (The Burning Crusade)

**Comment by miraco** [comment]
Can you provide some guids from thos objects?

**Comment by killerwife** [comment]
I bet they are pooled in some hillarious way.

**Comment by Tobschinski** [comment]
![image](https://github.com/cmangos/issues/assets/4753528/b199d453-4824-4af1-9ad2-9b36df8270ad)
![image](https://github.com/cmangos/issues/assets/4753528/c65d3a83-233a-471c-9ba0-628e5d3c3806)

**Comment by Tobschinski** [comment]
Should be 3 in Jintha'Alor, 3 in Skulk Rock and 1 in Sharpbeak's Cave.
