### ISSUE TITLE
🐛 [Bug Report] [WoTLK] Professions Training Missing 

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3662]
### Bug Details

Several professions are missing training. I am going through all the training and will be listing the missing training from trainer/vendor

### Steps to Reproduce

1.Deneb Walker [2805] is located at Stromgarde Keep in Arathi Highlands
   Balai Lok'Wein [13476] is located at Brackenwall Village in Dustwallow Marsh
         Expert First Aid - Under Wraps [16084] Manual: Heavy Silk Bandage [16112], Manual: Mageweave Bandage [16113]
2.Alma Jainrose [812] is located at Lakeshire in Redridge Mountians
   Brant Jasperbloom [4898] is located at Theramore in Duskwallow Marsh
   Firodren Mooncaller [4204] is located at The Temple Gardens in Darnassus
   Cemmorhan [16736] is located at The Vault of Lights in Exodar
   Plora Silverwind [908] is located at Booty Bay in Stanglethorn Vale
   Herbalist Pomeray [1218] is located in Elwynn Forest
   Heur [17385] is located Azure Watch in Azuremyst Isle
   Kali Healtouch [1473] is located at Thelsamar in Loch Modan
   Malorne Bladeleaf [3604] ist laocated at Dolnaar in Teldrassil
         Expert Herbalism [3570]

### Core SHA1 Commit Hash

92612ede3331f05ee148364beee09ef64100d6c1

### Database SHA1 Commit Hash

a24bd2dd7cec2345c5b4c0798a359d6d0bab0fb8

### Operating System

Ubuntu Server LTS 20.04 / Ubuntu Desktop 22.04 Client

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
Can't reproduce this. All of these trainers do offer training up to level 225. level 300 you get from the artisan trainers and those first aid books as well as the first aid quest were removed with WotLK and can just be learned from trainers regularly

**Comment by adellaci** [comment]
Then i have something wrong with my DB. I have not finished going through all the other professions. If first is no long a book, it is not at my trainer as an option.

**Comment by adellaci** [comment]
I used a different toon and Heavy Silk Bandages is a available. I am working to see why

**Comment by adellaci** [comment]
Yes it has to do with only one toon, I will close this out.

**Comment by adellaci** [comment]
Very odd. I went to the First Aid Trainer (Shaiana) and Heavy Silk Bandage is not availiable. Toon is level 38, skill training of 210.
I also opened character's First Aid Profession, typed '.learn 7929' It showed up in the character's first aid profession, and now it is showing in Shaina Fullerdialog box. Its the only character that appears to be having that issue.
