### ISSUE TITLE
🐛 [Bug Report] The elevator in the Mechanar disappears

### ISSUE THREAD

**Issue by LEO33SoFo** [cmangos/issues#3670]
### Bug Details

The elevator which takes me to the second level disappears from view when entering the tunnel, unable to progress the dungeon normally.
[Video preview of the bug.](https://streamable.com/qdope0)

Perhaps https://github.com/cmangos/issues/issues/3668#issuecomment-1929146054 is related with this issue?

### Steps to Reproduce

1. `.go xyz 222.881210 52.421066 -0.005578 554`
2. Check for the aforementioned problem.

### Core SHA1 Commit Hash

85ce2f56d445fb099c37ed17d306e76d87b1c4c1

### Database SHA1 Commit Hash

6915d71b6de5d074e4eb512a20a84c9863618156

### Operating System

Windows 8.1 with Update 3 Professional 64bit

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
Not an issue with unmodified CMaNGOS. Change your VisibilityConfig for Dungeons from 200 to 170 (the default)
