### ISSUE TITLE
🐛 [Bug Report] Crashes after WorldSession changes

### ISSUE THREAD

**Issue by Shettelight** [cmangos/issues#3672]
### Bug Details

Hello, we got some issues, seems after build https://github.com/cmangos/mangos-tbc/commit/a0b44d1f8750cbaea1c8eb4eb3be78d9d26881c2
there log https://pastebin.com/sE5uCGDV
@k

### Steps to Reproduce

1. Build
2. Run
3. Play
4. Done

### Expected behavior

Stable

### Suggested Workaround

Not stable

### Crash Log

https://pastebin.com/sE5uCGDV

### Core SHA1 Commit Hash

a0b44d1f8750cbaea1c8eb4eb3be78d9d26881c2

### Database SHA1 Commit Hash

a0b44d1f8750cbaea1c8eb4eb3be78d9d26881c2

### Operating System

*Unix

### Client Version

2.4.3 (The Burning Crusade)

**Comment by killerwife** [comment]
This is going to be some weird other compiler issue that I cannot reproduce. Nonetheless, I added a couple safeguards. Test them out.

**Comment by al3xc1985** [comment]
@Shettelight did u encountered crash anymore? can this be closed?

**Comment by insunaa** [comment]
closing as stale. please reopen if it still occurs.
