### ISSUE TITLE
Im too short for this adventure? - Classic Mining 🐛 [Bug Report] 

### ISSUE THREAD

**Issue by Daedalus-code** [cmangos/issues#3675]
### Bug Details

Tried jumping.
...
No profit.

### Steps to Reproduce

1. Loch Modan near the Stronghold.
2. Seeing Tin Vein inside mountain, some are reachable some are too high up.
3. ...
4. Profit

### Expected behavior

I should be able even tho Im a tiny leprechaun.
![tin1](https://github.com/cmangos/issues/assets/59256533/296910e5-fb55-4a8f-bbd5-270b71f4aa65)

![tin2](https://github.com/cmangos/issues/assets/59256533/8aaa5ddb-beb9-456d-b8ea-00b072670f78)

### Core SHA1 Commit Hash

23f2b9dd2bf0a148c229096621e0b38e806b49b3

### Database SHA1 Commit Hash

8b14771867c03fdd348f69238181f98d5b6f61c6

### Operating System

Linux Ubuntu

### Client Version

1.12.1 (Classic)

**Comment by Tobschinski** [comment]
There's probably a lot more faulty Copper Veins in Loch Modan, but the Tin Veins are at least covered by https://github.com/cmangos/classic-db/commit/9bf6d4ed25212e818325ae4f790e1e02a0784004
