### ISSUE TITLE
🐛 [Bug Report] Crashes by WorldPackets on last rev

### ISSUE THREAD

**Issue by Shettelight** [cmangos/issues#3676]
### Bug Details

Unresolved issue with WorldPackets at last revision. Here log
https://pastebin.com/6biSrMAt
Before crash it gives info about 'WorldSocket::ProcessIncomingData: Received opcode beyond range of opcodes: 67072'

### Steps to Reproduce

1. No direct way to reproduce
2.
3.
4.

### Expected behavior

No crashes

### Core SHA1 Commit Hash

c29a57bda22ac50eb90a4b95b65d0ca1b8619f40

### Database SHA1 Commit Hash

6567d8321dbdd4feb680a349c0b9840c6ad9e12d

### Operating System

*Unix

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Shettelight** [comment]
@killerwife summon

**Comment by Shettelight** [comment]
Maybe issue with size_t - it could`ve not uint8  in case if header->size`ll less than 4 it cause a inverted byte sequence.
Idk, maybe checks there?

**Comment by killerwife** [comment]
Ok this helps shit, cos it seems like its a heap corruption during allocation. However, I have a fix in the pipeline for a race condition, which could easily cause this. I will have it pushed to mangos-tbc sometime tomorrow because I still need to refactor it, when I push it, I will link it in this issue.

**Comment by killerwife** [comment]
Linked as promised.

**Comment by Shettelight** [comment]
@killerwife still happened after ur fix https://pastebin.com/y8t5Z5wE

**Comment by killerwife** [comment]
Ok I will need a lot more information here. Are you running with playerbots, which linux distribution are you running, is there a specific moment when this happens, how many players do you have online.

**Comment by Shettelight** [comment]
> Ok I will need a lot more information here. Are you running with playerbots, which linux distribution are you running, is there a specific moment when this happens, how many players do you have online.

Debian 11, online average ~ 50, no playerbots enabled. 
We couldn`t detect way to reproduce btw

**Comment by killerwife** [comment]
I found a check i was missing from the old code that is still applicable. On a different note, I have no idea how that stuff is coming to your server, and my best guess would be someone attacking your server trying to crash it. Check latest commit.

**Comment by al3xc1985** [comment]
@Shettelight can this be closed? is it fixed? Did u encountered anymore?

**Comment by Shettelight** [comment]
@al3xc1985 no, ty, u close
