### ISSUE TITLE
🐛 [Bug Report] TBC Hellfire Ramparts Vazruden Heroic level 62 instead of 72

### ISSUE THREAD

**Issue by rayonpt** [cmangos/issues#3678]
### Bug Details

NPC Vazruden is level 62 instead of 72 in Heroic Mode

.npc info on creature points to the correct creature on DB that is level 72 but in-game is 62.

![Captura de ecrã 2024-02-20 161549](https://github.com/cmangos/issues/assets/9625733/f7dc647a-f130-4d7a-ac19-0f2568642afe)

### Steps to Reproduce

1. Go to Hellfire Ramparts HC mode
2. Go to last boss Vazruden the Herald
3. Kill the 2 starting NPC
4. Wait for Vazruden the Herald to summon Vazruden

### Expected behavior

NPC should be 72 instead of 62

### Core SHA1 Commit Hash

411ecb739455a4364cc24976c8f8ec0df422bec

### Database SHA1 Commit Hash

411ecb739455a4364cc24976c8f8ec0df422bec

### Operating System

Windows 11

### Client Version

2.4.3 (The Burning Crusade)

**Comment by miraco** [comment]
Can Confirm
Just some quick infos from my tests:

Spawning the npc manual with "npc add 18434" takes correct level.
Also Nazan has the correct Level, so i would assume it has something to do with the summoning spell  `SPELL_SUMMON_VAZRUDEN = 30717,`

**Comment by rayonpt** [comment]
Yes I forgot to mention, I think it is something with the spell.
I already did that tests and I can confirm your teory. Also tried to check the spell in DB and seems fine.

**Comment by killerwife** [comment]
Found issue and why it occurs, I will push a fix in a bit.
