### ISSUE TITLE
🐛 [Bug Report] Vile Familiars spell missing

### ISSUE THREAD

**Issue by Namok** [cmangos/issues#3680]
### Bug Details

The Vile Familiar creature doesn't cast the spell Fireball when it's close enough to you.
Vile familiar ID: 3101
Fireball ID: 11921

### Steps to Reproduce

1. .go xyz -218.40 -4352.49 63.95 1
2. Aggro a Vile Familiar

### Expected behavior

Basically when you attack this creature it should approach you and when close enough it should cast the spell Fireball.
Reference video: https://www.youtube.com/watch?v=6A0OlvrNZKg

### Core SHA1 Commit Hash

c5e25dc80c0b604c33613f1c562f840f3e9e9b91

### Database SHA1 Commit Hash

8911e9f719b383bd984ffe51f531cb4cf67b5347

### Operating System

Windows 11 Build 22631.3155

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
they do but as in your video very irregular, currently at intervalls ```'15000','40000','35000','45000'``` ms which might be too much.

/edit or not by what your numbers say, can we discuss this with better data?

**Comment by Namok** [comment]
Thank you for you comment @AnonXS
I guess the intervalls can be reduced a bit, here is what I get after killing 10 mobs:
1: Cast Fireball at 1:30
2: Cast Fireball at 0:30
3: Cast Fireball at 1:43
4: Cast Fireball at 1:31
5: Cast Fireball at 1:12
6. Cast Fireball at 2:02
7. Cast Fireball at 0:38
8. Cast Fireball at 1:04
9. Cast Fireball at 0:39
10. Cast Fireball at 0:37

Regular fight with a Vile Familiar recorded from my local server: Just recorded a video from my local server: https://youtu.be/Y_-WGJXDeE0

**Comment by maikale** [comment]
@Namok He's right I have problems

**Comment by al3xc1985** [comment]
https://youtu.be/K7FOfKOImJ0

This is how it should work,
1. Once the mob get to melle range he should cast fireball
2. he has a long cd on his fireball that is why we need to add it to spell list

he will cast like 1 fireball pe fight, cause he doesn't resist to long to your dmg and cd from spellist will help to make it blizzlike

**Comment by miraco** [comment]
https://github.com/cmangos/tbc-db/commit/ff27fb2bbd3588ea8618bbeb497fbe4c82c38551
