### ISSUE TITLE
🐛 [Bug Report] [WoTLK] Compile Error in Pet.cpp with DPCH=0

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3682]
### Bug Details

Failed to compile at about 84%. 

Compiler version 12.30
Git  version  2.34.1

```
/home/mangos/cmangos/wotlk/src/game/Entities/Pet.cpp: In member function ‘virtual void Pet::ForcedDespawn(uint32, bool)’:
/home/mangos/cmangos/wotlk/src/game/Entities/Pet.cpp:2453:24: error: invalid use of incomplete type ‘class InstanceData’
 2453 |             mapInstance->OnCreatureDespawn(this);
      |                        ^~
In file included from /home/mangos/cmangos/wotlk/src/game/Entities/Unit.h:30,
                 from /home/mangos/cmangos/wotlk/src/game/Entities/Creature.h:23,
                 from /home/mangos/cmangos/wotlk/src/game/Entities/Pet.h:24,
                 from /home/mangos/cmangos/wotlk/src/game/Entities/Pet.cpp:19:
/home/mangos/cmangos/wotlk/src/game/Entities/Object.h:112:7: note: forward declaration of ‘class InstanceData’
  112 | class InstanceData;
      |       ^~~~~~~~~~~~
make[2]: *** [src/game/CMakeFiles/game.dir/build.make:8308: src/game/CMakeFiles/game.dir/Entities/Pet.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:683: src/game/CMakeFiles/game.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### Steps to Reproduce

1. cmake ~/cmangos/wotlk -DCMAKE_INSTALL_PREFIX=~/wow-servers/wotlk -DBUILD_EXTRACTORS=ON -DBUILD_AHBOT=ON -DBUILD_PLAYERBOT=ON -DPCH=0 -DDEBUG=0 -DBUILD_RECASTDEMOMOD=OFF -DBUILD_GIT_ID=0; make -j6
2.
3.
4.

### Expected behavior

To compile without error

### Core SHA1 Commit Hash

d093f4ea1f2b57efda664e4be86d6f354411049d

### Database SHA1 Commit Hash

n'a

### Operating System

Ubuntu Server LTS 20.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by adellaci** [comment]
Is anyone else having this issue? And if not which Linux compiler version are you using?

**Comment by insunaa** [comment]
kw forgot to include a headerfile, which makes the build fail without PCH. He'll fix it eventually

**Comment by killerwife** [comment]
Fix is on tbc and vanilla branches, will add it at the end of ports to wotlk core.

**Comment by adellaci** [comment]
Thank you @killerwife. Was not sure if this was a compiler version issue

Mar 24, 2024 11:15:39 killerwife ***@***.***>:

**Comment by adellaci** [comment]
I'll enable the  PCH and test

Mar 24, 2024 10:50:40 insuna ***@***.***>:

**Comment by adellaci** [comment]
With PCH enable it compiles just fine

**Comment by adellaci** [comment]
CMaNGOS-Core revision : 0a1914803fcf4afb6d7cdca47fac01cc56c7ee6e
Revision time stamp   : "2024-04-01T10:17:54+02:00"
cmake ~/cmangos/wotlk -DCMAKE_INSTALL_PREFIX=~/wow-servers/wotlk -DBUILD_EXTRACTORS=ON -DBUILD_AHBOT=ON -DBUILD_PLAYERBOT=ON -DPCH=0 -DDEBUG=0 -DBUILD_RECASTDEMOMOD=OFF -DBUILD_GIT_ID=0; make -j6

Download this morning and compiled. It compiled without error.

**Comment by adellaci** [comment]
I should have closed this as it still with DPCH=0

**Comment by insunaa** [comment]
Can't reproduce the error in Pet.cpp
Re-Open the issue if you're *sure* that PCH=0 errors in Pet.cpp, because it does neither on my System nor in CI/CD

**Comment by adellaci** [comment]
@insunaa Sorry it took so long to reply i did pull
-- CMaNGOS-Core revision : c3455a8b2c0dda6d4be572a7a83d1d91bf0a1fd9
-- Revision time stamp   : "2024-04-06T19:58:29+02:00"
and ran it with -DPCH=0 and it completed without error. It did have 5 warnings, but not sure it's worth reporting
