### ISSUE TITLE
🐛 [Bug Report] mangos.conf set Instance.IgnoreRaid = 1, but go to BWL it still show error

### ISSUE THREAD

**Issue by altmangood** [cmangos/issues#3684]
### Bug Details

It still show :  **You must be part of a raid group and at least 50th level to enter.**

And I set `Instance.IgnoreRaid` = 1   &`Instance.IgnoreLevel` = 1
and player is 60 level.

### Steps to Reproduce

1. go to 60 level
2. go to BWL
3. 
4.

### Expected behavior

Player can go to Instance

### Core SHA1 Commit Hash

cc39299

### Database SHA1 Commit Hash

e0a8f15

### Operating System

Windows 10 Proferssional

### Client Version

2.4.3 (The Burning Crusade)

**Comment by altmangood** [comment]
TBC 2.4.3 client

**Comment by cpevors** [comment]
I can confirm -- even with the configuration file options indicated above, it's not possible to .tele into the raid, nor zone in via the portal. 

![WoWScrnShot_032524_221943](https://github.com/cmangos/issues/assets/139099164/12b97f67-f3bb-430a-90cc-2378047d2900)
![WoWScrnShot_032524_222051](https://github.com/cmangos/issues/assets/139099164/f9fdc094-ab2e-44b6-9fde-f51a942fbbe9)

**Comment by celguar** [comment]
This config doesn't remove the attunement requirement. I think that's why this message is shown...

**Comment by altmangood** [comment]
> This config doesn't remove the attunement requirement. I think that's why this message is shown...

could you tell me which attunement requirement?  I set ignore level and ignore raid are all to 1

**Comment by cpevors** [comment]
I also don’t know that the attunement issue is the case here. Unless I’m woefully misremembering, BWL didn’t have a strict attunement process that you NEEDED to complete; rather, getting attuned alleviated needing to otherwise run UBRS to get to the raid portal. 

Moreover, trying to zone into Onyxia’s Lair, which does have a strict attunement process, indicates pretty discretely that you need to have the Drakefire Amulet in your inventory to enter (see below).

![WoWScrnShot_032724_115118](https://github.com/cmangos/issues/assets/139099164/0d989a10-4db2-4de9-889c-926415e220e9)

**Comment by celguar** [comment]
you can check wowpedia for BWL attunement if you're not sure. Also check areatrigger_teleport table to see if it has quest requirement. In vanilla it does. Also I heard the only way to enter BWL after attunement is by using the sphere in blackrock mountain. so lot of stuff to check

**Comment by cpevors** [comment]
My memories from 2005 are that attunement isn't _required_ to enter Blackwing Lair. It simply provides you quicker, easier access to the instance. If you weren't attuned, you'd need to enter the raid through Upper Blackrock Spire. It was certainly the case for Molten Core as well, as the raid instance portal to Molten Core was very often used while on the attunement quest to zone out of Blackrock Depths before the attunement quest was handed in.

I can find a whole host of confirmations of the same on the WoW forums and on Reddit, etc., but I'll leave it here as I don't want to peddle conjecture or anecdotes as gospel.

**Comment by celguar** [comment]
I agree it's wierd. And in classic cmangos I can't enter MC without attunement from BRD too

**Comment by altmangood** [comment]
Now, in the BWL case, it is accessible when I complete the quest of this.

https://www.wowhead.com/classic/quest=7761/blackhands-command
