### ISSUE TITLE
🐛 [Bug Report] Mage's Molten Armor reflect damage too high

### ISSUE THREAD

**Issue by betayi** [cmangos/issues#3685]
### Bug Details

as title, Mage's Molten Armor reflect damage too high, at least 2-3 times  more than it should be

### Steps to Reproduce

1.get a mage with Molten Armor
2.cast Molten Armor as aura  
3.just melee with any enemy
4.watch the relection damage value , far higher than it should be

### Core SHA1 Commit Hash

6d1e246e16bcc738eec816c9bc54442a976bc63c

### Database SHA1 Commit Hash

e0a8f15b1daf01aea1e855fd1788ac3390d0e061

### Operating System

ubuntu22

### Client Version

2.4.3 (The Burning Crusade)

**Comment by miraco** [comment]
We will definitely need more infos on this.
What’s the Formular for the dmg output, or should this be a static value?
Should it do more dmg with more spelldmg/fire dmg? Are other talents improving the dmg? 
just as an example, just saying it’s to high is never good enough for issues like this 
+ we need good evidence before changing something 
Old tbc videos for example

**Comment by betayi** [comment]
it's a dynamic damage result with diffrent euipment , just compare with feel before update, a normal level 70 mage can kill a wild enemy  with this aura ,just only hold his positon. and I can not upload a youtub video for some firewall reason , so sorry about this.

**Comment by MantisLord** [comment]
Need to check SP coefficients on the spells. Perhaps this was caused in some way by https://github.com/cmangos/mangos-tbc/commit/61990fb7661595a0143a6f483c033c779e84a513
Unfortunately I won't have time to dig into it for awhile.

**Comment by miraco** [comment]
> it's a dynamic damage result with diffrent euipment , just compare with feel before update, a normal level 70 mage can kill a wild enemy with this aura ,just only hold his positon. and I can not upload a youtub video for some firewall reason , so sorry about this.

Im currently not having an active local server to test this but "feel before update" is never a good source, i also feel my hunter should just oneshot everything but thats not how it works. There is so much math behind spells and how things work.



> Need to check SP coefficients on the spells. Perhaps this was caused in some way by [cmangos/mangos-tbc@61990fb](https://github.com/cmangos/mangos-tbc/commit/61990fb7661595a0143a6f483c033c779e84a513) Unfortunately I won't have time to dig into it for awhile.

https://www.wowhead.com/tbc/spell=30482/molten-armor
This spell has EffectBonusCoefficient1-3 = 0 (EffectBonusCoefficientFromAP1-3 also 0) on current tbc db

So the question still remains, what formular/spellcoef does this spell use to calculate dmg output.

**Comment by betayi** [comment]
> > it's a dynamic damage result with diffrent euipment , just compare with feel before update, a normal level 70 mage can kill a wild enemy with this aura ,just only hold his positon. and I can not upload a youtub video for some firewall reason , so sorry about this.
> 
> Im currently not having an active local server to test this but "feel before update" is never a good source, i also feel my hunter should just oneshot everything but thats not how it works. There is so much math behind spells and how things work.
> 
i know my description has not a comparable evidence for the debug work, cauze this spell's act normally while player was naked, and can kill same level enemy just with reflect damage when player euipped well. i can not calculate the damage value the character should be , but i also know the damage is not how it works, i'll try to get a compare a value from some other server that with priviouse version. this is a issue , just without good comparable evidence.

**Comment by killerwife** [comment]
Default coefficient calculation had to be removed. I am aware this will likely cause trouble, however it can probably be mitigated if it becomes an issue by importing 0 values from the previous data and then setting default coeff for everything else. For AP however it will be non issue.

**Comment by betayi** [comment]
this https://github.com/cmangos/mangos-tbc/commit/f2798ea538c9e5157a3f478d5d4590f804bcb1a0 is useless for this issue , the problem is still there.

**Comment by betayi** [comment]
> this [cmangos/mangos-tbc@f2798ea](https://github.com/cmangos/mangos-tbc/commit/f2798ea538c9e5157a3f478d5d4590f804bcb1a0) is useless for this issue , the problem is still there. should not be complete and close this.

this https://github.com/cmangos/mangos-tbc/commit/f2798ea538c9e5157a3f478d5d4590f804bcb1a0 is useless for this issue , the problem is still there. should not be complete and close this.

**Comment by betayi** [comment]
> Default coefficient calculation had to be removed. I am aware this will likely cause trouble, however it can probably be mitigated if it becomes an issue by importing 0 values from the previous data and then setting default coeff for everything else. For AP however it will be non issue.

this https://github.com/cmangos/mangos-tbc/commit/f2798ea538c9e5157a3f478d5d4590f804bcb1a0 is useless for this issue , the problem is still there. should not be closed as complete.

**Comment by killerwife** [comment]
This time I rechecked.

**Comment by betayi** [comment]
> This time I rechecked.

nice job! it works!
