### ISSUE TITLE
🐛 [Bug Report] Character keep online forever if player close client not from game menu

### ISSUE THREAD

**Issue by betayi** [cmangos/issues#3687]
### Bug Details

characters won't be logout and won't set AFK if player close his client with alt+f4 or the close button of game window,  till login again and click the game menu exit  option . 

it should be a little while then logout the world if player close the window directly.

### Steps to Reproduce

1.normal account login to the world wherever in wild or city
2.close the client with alt f4 directly
3.wait some while and type "account online" in console 
4.gm account login watch the character , not logout ,not afk

### Expected behavior

character should logout the world what ever reason  player close their client for some while

### Core SHA1 Commit Hash

6d1e246e16bcc738eec816c9bc54442a976bc63c

### Database SHA1 Commit Hash

latest

### Operating System

ubuntu22

### Client Version

2.4.3 (The Burning Crusade)

**Comment by al3xc1985** [comment]
So this bassically would lead to some sort of memmory leaks or higher conssumtion, dunno how to call it?
I mena for example I alt f4 my char , my char is still there, a mob comes and kills my char, it goes to spirit healer. and it stays there until I am loged out automatticaly by the server. And futher on until server kicks my client because of inactivity

**Comment by killerwife** [comment]
Char is meant to logout either - after 1 minute after alt+f4 or after leaving combat. If he never left combat, he will stay online forever. Not sure if this impacts this issue but stating that here first.

**Comment by celguar** [comment]
had same thing...alt +f4 char stayed there for ~5mins (until I logged on it). I could whisper it etc

**Comment by rayonpt** [comment]
can confirm this too, warden kicks the user after sometime

**Comment by lightningcal** [comment]
I'm running into this as well (on the current build). Regardless of using Logout, Exit, or Alt+F4. In my server.log is shows my character as logged in. and I can't log back in, it is stuck at "Retrieving Characters".  Only after the Warden boots me can I retrieve my characters again and re-login.

**Comment by rayonpt** [comment]
Disable anticheat and it is working fine, so it's a anticheat/warden problem

**Comment by al3xc1985** [comment]
Nice catch

**Comment by celguar** [comment]
I never use anti cheat

**Comment by cpevors** [comment]
Was intrigued by @celguar's mentioning he doesn't use anti-cheat. I never use anti-cheat either, and I, too, can confirm the issue. Unlike @celguar, I didn't log back in after ~5 minutes, and even 15-20 minutes later the disconnected character is still online.

**Comment by kelbren** [comment]
I can confirm this as well in wotlk fresh pull and compile,  if you close the client via (x) or crash it,  the char stays in the world and never logs off. If I enable warden, it will kick the char, but then fills the log with constant info about the account not logged off, at that point you can not log back in and gets stuck at retrieving chars screen.  It appears the session is not timing out like it should.

**Comment by lightningcal** [comment]
Same, I disabled anti-cheat and warden after seeing rayonpt's comment. With it disabled I can at least log back in again (no longer stuck at retrieving characters), but in my server.log it continues to say "Sessions online: 1" despite me having closed the game client. (no one else is using this server except me). I'm using vanilla 1.12.1 cmangos btw.

**Comment by rayonpt** [comment]
I think this anticheat is missing some updates

https://github.com/vmangos/core/commit/62d2959264d1321465b9438208ba1745ea447c4e

**Comment by gujinjian** [comment]
> 同样，我在看到rayonpt的评论后禁用了反作弊和典狱长。禁用它后，我至少可以再次登录（不再卡在检索字符上），但在我的 server.log 中，尽管我已经关闭了游戏客户端，但它仍然显示“在线会话：1”。（除了我之外没有其他人使用该服务器）。顺便说一句，我正在使用 vanilla 1.12.1 cmangos。

tbc  has same problem

**Comment by gujinjian** [comment]
> Same, I disabled anti-cheat and warden after seeing rayonpt's comment. With it disabled I can at least log back in again (no longer stuck at retrieving characters), but in my server.log it continues to say "Sessions online: 1" despite me having closed the game client. (no one else is using this server except me). I'm using vanilla 1.12.1 cmangos btw.

TBC has  the  same problem

**Comment by rayonpt** [comment]
Anyone able to solve this? I will put some money on the table if needed

**Comment by al3xc1985** [comment]
https://discord.com/channels/543558148146069515/543560253694803968

You can allways support this guys there

**Comment by Cgbd42** [comment]
@rayonpt please join this discord https://discord.gg/unaA6hE4UA

**Comment by kelbren** [comment]
I have a solution I came up with for wotlk, I have not tried it on tbc or classic.  It requires a timer against the ping from the client. I currently have a 3 minute timeout and it kicks the char. seems to work fine. I dunno if this is the accepted way to do it, but it works so far with no issues.

**Comment by gujinjian** [comment]
The anti cheating function can be turned on to enable offline characters after being disconnected, but once a character is taken offline, the result is a data rollback. My understanding is that T offline did not perform a data saving action. If the tick action is implemented, a data saving action can be added before implementation.. This problem is easily solved.. Currently using anti cheating.. Lost character data may occur

**Comment by gujinjian** [comment]
> I have a solution I came up with for wotlk, I have not tried it on tbc or classic. It requires a timer against the ping from the client. I currently have a 3 minute timeout and it kicks the char. seems to work fine. I dunno if this is the accepted way to do it, but it works so far with no issues.

could you tell me how this problems solve

**Comment by al3xc1985** [comment]
can u guys try with 
https://github.com/cmangos/mangos-tbc/commit/2709cf19d293c36e7d4aa122075c37577d21206a

**Comment by rayonpt** [comment]
al3xc1985, solved with that last fix! if you logout and login again it works and if you alt+f4 after 1 min or less you go offline.
amazing GJ

**Comment by al3xc1985** [comment]
see, our big brother @killerwife is the man.
@killerwife u got your confirmation that everything is ok
