### ISSUE TITLE
🐛 [Bug Report] Magister's Terrace - Orb of Translocation Clickable but does nothing (checked on normal Difficulty)

### ISSUE THREAD

**Issue by Szymplo** [cmangos/issues#3692]
### Bug Details

![orb_of_tanslocation_clickable_but_dont_do_anything](https://github.com/cmangos/issues/assets/65982308/2aba29f7-883d-4286-9733-7987cc366ec1)

Orb of Translocation in Magister's Terrace (behind room of Kaelthas) - is clickable but doesn't work.

### Steps to Reproduce

1.Do Magister's terrace Instance on normal difficulty (we wiped 2 times on Kaelthas) 
2.Go to Orb of Translocation - and realise that it is clickable but does nothing
3.
4.

### Expected behavior

Orb of Translocation should work fine - do teleport players.

### Core SHA1 Commit Hash

fc48782065341d29bc9bc9e4867bf2cbbac61959

### Database SHA1 Commit Hash

ff4773b529086dd0ea1cbd72f8ed7f287c34eca8

### Operating System

Debian 11 with MariaDB

### Client Version

2.4.3 (The Burning Crusade)

**Comment by heyitsbench** [comment]
https://github.com/cmangos/issues/issues/3681

**Comment by Szymplo** [comment]
Closing it was already reported: 
https://github.com/cmangos/issues/issues/3681 
sorry
