### ISSUE TITLE
💬 [Support Request] Error 1136 when attempting a Full default CMaNGOS-core and TBC-DB Install

### ISSUE THREAD

**Issue by cpevors** [cmangos/issues#3694]
### Core Version

mangos-tbc

### Support Request Details

I am trying to do a new Full Install of the DB on a new system, and I'm getting the following error when applying mangos.sql: ERROR 1136 (21S01) at line 1411: Column count doesn't match value count at row 1

![image](https://github.com/cmangos/issues/assets/139099164/42704a09-42c4-4e0b-9afa-1044f5f6da26)

### Steps to Reproduce

1. Pull down the latest DB commits.
2. Run InstallFullDB.sh
3. Choose 4. 
4. Choose 1.

### Core SHA1 Commit Hash

b7886070de8d74f3404e632e1f6b06e2a6c54ed5

### Database SHA1 Commit Hash

ff4773b529086dd0ea1cbd72f8ed7f287c34eca8

### Server Operating System

Windows 11 64-bit

### Client Version

2.4.3 (The Burning Crusade)

### Client Operating System

Windows 11 64-bit

**Comment by cpevors** [comment]
Pardon the conjecture (I'm very much a layperson at this stuff), but I believe this commit is why the Install is failing. We added CharmSpellList, but at Line 1411 in mangos.sql, we don't INSERT a 90th value into creature_template to account for it. 

https://github.com/cmangos/mangos-tbc/commit/b7886070de8d74f3404e632e1f6b06e2a6c54ed5

**Comment by cpevors** [comment]
I 'tested' this by adding an additional 0 into Line 1411, and the Install went through successfully. I can't speak to whether or not 0 is the appropriate value, but adding that column value (right, wrong, or indifferent) did get me past the error.

**Comment by insunaa** [comment]
Resolved in https://github.com/cmangos/mangos-tbc/commit/5a6e5dc8afdd3dc3ab6758bfddfa52e009884cc0
