### ISSUE TITLE
🐛 [Bug Report] Past commit left stale code in classic and wotlk repository

### ISSUE THREAD

**Issue by orygg** [cmangos/issues#3695]
### Bug Details

Commits
https://github.com/cmangos/mangos-classic/commit/0da1a501f6539033a4d23346d3d83fda7e24b22d and
https://github.com/cmangos/mangos-wotlk/commit/cb1444fe7de8e0da0bd43a07931bb07b76de038c
did not remove Socket.cpp like the tbc commit, https://github.com/cmangos/mangos-tbc/commit/a0b44d1f8750cbaea1c8eb4eb3be78d9d26881c2,  did.

### Steps to Reproduce

1. Look at the linked commits and observe the difference.

### Expected behavior

Files should have been deleted.

### Suggested Workaround

Non necessary

### Core SHA1 Commit Hash

10b7680bf5827a53da03f40a5e00032a0a86700f

### Database SHA1 Commit Hash

10b7680bf5827a53da03f40a5e00032a0a86700f

### Operating System

all

### Client Version

1.12.1 (Classic)

**Comment by Exxenoz** [comment]
Can be closed when the file got removed from wotlk repository as well.
