### ISSUE TITLE
🐛 [Bug Report] Naxxramas Plague Quarter Inaccessible

### ISSUE THREAD

**Issue by cpevors** [cmangos/issues#3696]
### Bug Details

Immediately upon zoning in to 40-man Naxxramas, I noticed the Plague Quarter was inaccessible. There is a plague waterfall at the front entryway that is barring entry. All other Quarters are accessible. 

![WoWScrnShot_040724_214846](https://github.com/cmangos/issues/assets/139099164/fa789226-0591-4e51-a416-0ae6c9bdcc69)

### Steps to Reproduce

1. .gm on (just to ensure you can zone in)
2. .tele Naxxramas
3. Zone into Naxxramas
4. Navigate to the hallway to the Plague Quarter

### Expected behavior

I do not believe this entry should be barred outside of an active boss encounter. 

### Core SHA1 Commit Hash

b7886070de8d74f3404e632e1f6b06e2a6c54ed5

### Database SHA1 Commit Hash

ff4773b529086dd0ea1cbd72f8ed7f287c34eca8

### Operating System

Windows 11 Home - 64-bit

### Client Version

2.4.3 (The Burning Crusade)

**Comment by cpevors** [comment]
There is also a waterfall barring entry before and after the guantlet hallway before Noth.

**Comment by insunaa** [comment]
Might be because all gameobjects in Naxxramas use dynguid now, maybe they're not correctly initialized due to that.

**Comment by cpevors** [comment]
That would make sense -- I appreciate your insight!

**Comment by insunaa** [comment]
OK turns out it's just incorrectly ported data. I'll talk with a db dev about it once one becomes available.

**Comment by cpevors** [comment]
My hero. Means a ton, truly.

**Comment by cpevors** [comment]
Closed with https://github.com/cmangos/tbc-db/commit/2cf8e0c1624e92eb5d798ae4e7b50be610b5d957

**Comment by insunaa** [comment]
Should be resolved with https://github.com/cmangos/tbc-db/commit/2cf8e0c1624e92eb5d798ae4e7b50be610b5d957

**Comment by insunaa** [comment]
damn sorry my github didn't show me the current version of the thread :D

**Comment by Vigerus** [comment]
@cpevors @insunaa this ticket is also valid for classic, i have the same issue there

**Comment by cpevors** [comment]
Oh! @AnonXS, apologies for the ping, is this something you can also port to Classic for @Vigerus?

**Comment by AnonXS** [comment]
https://github.com/cmangos/classic-db/commit/0c267fb812b4f01f31535e53dc2d62e7f2db281e

If there are more, open a new issue please.
