### ISSUE TITLE
🐛 [Bug Report] The Defias Brotherhood escort quest - The Defias Traitor NPC is missing a waypoint path

### ISSUE THREAD

**Issue by soniquete0** [cmangos/issues#3702]
### Bug Details

The Defias Trator in the The Defias Brotherhood quest chain is missing a waypoint path. It has already been implemented to TBC in this commit ( https://github.com/cmangos/tbc-db/commit/aa9aca55403100c9be0f7054a0740acb0bb82046 ) but didn't make it's way to vanilla (and likely WotLK as well).

### Steps to Reproduce

1. Start the quest
2. Watch the NPC not doing anything

### Expected behavior

The NPC should move.

### Core SHA1 Commit Hash

x

### Database SHA1 Commit Hash

x

### Operating System

Win 10

### Client Version

1.12.1 (Classic)

**Comment by katz1** [comment]
Confirmed on:

Core SHA1 Commit Hash: 0e32ab652f9b44868bdadf99638002faca426c9d
Database SHA1 Commit Hash: 6885b120d8ef9338359ddf462239d8de27e679ee
