### ISSUE TITLE
🐛 [Bug Report] Missing In Action quest - Corporal Keeshan NPC is missing a waypoint path

### ISSUE THREAD

**Issue by soniquete0** [cmangos/issues#3703]
### Bug Details

Corporal Keeshan in the Missing in Action quest is missing a waypoint path. It has already been implemented to TBC in this commit ( https://github.com/cmangos/tbc-db/commit/df201dd671b4aeb004cb8e3a05e1929436a1256f ) but didn't make it's way to vanilla (and likely WotLK as well).

### Steps to Reproduce

1. Start the quest
2. Watch the NPC not doing anything

### Expected behavior

The NPC should move.

### Core SHA1 Commit Hash

x

### Database SHA1 Commit Hash

x

### Operating System

Win 10

### Client Version

1.12.1 (Classic)

**Comment by al3xc1985** [comment]
I believe when kw will do his periodic backports, will do this one 2

**Comment by soniquete0** [comment]
Is there a list of these?

**Comment by al3xc1985** [comment]
well, KW has them noted down

**Comment by soniquete0** [comment]
So not publicly available.

**Comment by al3xc1985** [comment]
why closed it?

**Comment by soniquete0** [comment]
I don't see a reason to have an open issue for something that is in the works. Don't know your process. I can reopen it if you want.

**Comment by al3xc1985** [comment]
So let me explain, KW like all the other devs have their part of this project that they work on.
From time to time, when KW decide and have time, he is backporting all stuff from a repo to all others accordingly to their researche.

It can sometimes to forget a certain update to backport.
In this case an issue report is made like you did, and wait patiently until the moment comes.

It is our reposnsability to give a hand and see from time to time what updates are in the repo that we observe, and if a dev forget to close our bug report, close it ourselfs.

Bug reports are welcome, that is why we are a community to help each others and wait. Our devs are like big brothers. Need to help them as much as we can.


So yes, reopen it and wait till it;s backported

and You did a gret job to link the link missing

**Comment by soniquete0** [comment]
Alright, makes sense. Thanks for the info. Reopened the issue. I'll report more in case I spot them.

**Comment by AnonXS** [comment]
https://github.com/cmangos/classic-db/commit/ec76b323b47425b802c92ed51a30126ded99b3d0
