### ISSUE TITLE
🐛 [Bug Report] Error building playerbots for TBC

### ISSUE THREAD

**Issue by Patrick-Barry** [cmangos/issues#3705]
### Bug Details

When compiling with the new playerbots enabled the following error is given:

'PlayerbotHolder::playerBots': cannot access private member declared in class 'PlayerbotHolder' D:\cmangos-tbc\mangos\src\modules\PlayerBots\playerbot\RandomPlayerbotMgr.cpp   on line 1503	

This was with playerbot commit 5b57ab4

### Steps to Reproduce

1. Build with the new playerbots enabled

### Expected behavior

Should compile without error

### Core SHA1 Commit Hash

52db10a77bc7a67a682d5f8eb7aa52ef10799ec3

### Database SHA1 Commit Hash

d3a2d512f0507ba1cf6dfa664f0758240ee37168

### Operating System

Windows 10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by flekz-games** [comment]
Should be fixed now
