### ISSUE TITLE
🐛 [Bug Report] [Arathi Highlands] NPC 30's Levels1 Hit Point

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3706]
### Bug Details

Several NPC that are in the level 30 - 32 range have 1 hit point.

Boulderfist Ogre level 32 hit points should be around 1163 (npc=2562)
Most Highland Strider, levels 30-31 hit points should be around 1050 (npc=2559)
Plains Creeper, level 32 hit points should be around 1221 (npc=2563)
Witherbark Troll, level 30 hit point should be around 1051 (npc=2552)
Young Mesa Buzzard, level 31 - 32 hit points should be around 1107 (npc=2578)
Syndicate Highwayman Level: 30 - 31, hit points should be around 1107 (npc=2586)
Syndicate Mercenary, Level: 31 - 32, hit pint should be around 1107 (npc=2589)
Syndicate Pathstalker, Level: 32 hit point should be around 1063 (npc=2587)

I could not find a Syndicate Pathstalker, Level: 33 to verify if they have the same issue

### Steps to Reproduce

1.
2.
3.
4.

### Expected behavior

Have the right amount of hit points

### Core SHA1 Commit Hash

48e327e51bfb1b207e8d658e4470ceb81b97d8d1

### Database SHA1 Commit Hash

639dd8949c167fe6ab18f22a5e5e9699b40c8567

### Operating System

Ubuntu Server LTS 20.04 / Ubuntu Desktop 22.04 Client

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
It's an issue with CLS and will be resolved soon.
