### ISSUE TITLE
🐛 [Bug Report] Tiny Crimson Whelping spawn dead ( friendly pet )

### ISSUE THREAD

**Issue by Moriropi** [cmangos/issues#3709]
### Bug Details

Tiny Emerald Whelping ( id 8498 ) and Tiny Crimson Whelping ( id 8499 )  pets spawn dead and keep following the player.

### Steps to Reproduce

1. .additem 8498
2. Use the item to spawn to whelping
3.
4.

### Expected behavior

The 3D model of the whelping should be the "alive" version.

### Suggested Workaround

cls for pets hp ?

### Core SHA1 Commit Hash

[f928d608e104682d750b202ee9864744da2eec5a](https://github.com/cmangos/mangos-classic/commit/f928d608e104682d750b202ee9864744da2eec5a) - edit AnonXS

### Database SHA1 Commit Hash
[
51c1a1075c9cca63b1d0c0e078407948de227258](https://github.com/cmangos/classic-db/commit/51c1a1075c9cca63b1d0c0e078407948de227258) - edit AnonXS

### Operating System

Mac + Wineskin for windows 11

### Client Version

1.12.1 (Classic)

**Comment by Moriropi** [comment]
Looks like a duplicate :)

**Comment by Moriropi** [comment]
It looks like it was fixed for the TBC core only : https://github.com/cmangos/issues/issues/3708

**Comment by AnonXS** [comment]
Seems already partly or totally fixed on my end:

![grafik](https://github.com/cmangos/issues/assets/19734826/eb2ec9d8-87ca-43ad-9dae-bcc6ee184a8d)

![grafik](https://github.com/cmangos/issues/assets/19734826/27b9e61e-2d6b-4727-8b91-f8af0bdd8ec0)

**Comment by al3xc1985** [comment]
Update please to latest core and db, and come back with a feedback please

**Comment by insunaa** [comment]
Closing as duplicate
