### ISSUE TITLE
🐛 [Bug Report] The compiled program equipment can not correctly add the normal coefficient value to the character attack information

### ISSUE THREAD

**Issue by gujinjian** [cmangos/issues#3710]
### Bug Details

The compiled program equipment can not correctly add the normal coefficient value to the character attack information。
There is a read difference between the MANGOSD log and the windows log in the item entry。

system：ubuntu22.04 
mysql：8.0

### Steps to Reproduce

1.
![WoWScrnShot_051224_174535](https://github.com/cmangos/issues/assets/82714805/7ee8fa48-c784-4c7c-ad39-a36efe8869a2)

- This script builds the MaNGOS server.
  Options that can be used in order to configure the process:
    CMAKE_INSTALL_PREFIX    Path where the server should be installed to
    PCH                     Use precompiled headers
    DEBUG                   Include additional debug-code in core
    WARNINGS                Show all warnings during compile
    POSTGRESQL              Use PostgreSQL instead of mysql
    BUILD_GAME_SERVER       Build game server (core server)
    BUILD_LOGIN_SERVER      Build login server (auth server)
    BUILD_EXTRACTORS        Build map/dbc/vmap/mmap extractor
	BUILD_PLAYERBOTS        Build Playerbots mod
    BUILD_AHBOT             Build Auction House Bot mod
    BUILD_METRICS           Build Metrics, generate data for Grafana
    BUILD_RECASTDEMOMOD     Build map/vmap/mmap viewer
    BUILD_GIT_ID            Build git_id
    BUILD_DOCS              Build documentation with doxygen
    CMAKE_INTERPROCEDURAL_OPTIMIZATION Enable link-time optimizations
    BUILD_DEPRECATED_PLAYERBOT         Build Playerbot mod (deprecated)
    BUILD_SCRIPTDEV         Build scriptdev. (Disable it to speedup build
                                in dev mode by not including scripts)

    DEV_BINARY_DIR          Target directory for executables on Windows only

  To set an option simply type -D<OPTION>=<VALUE> after 'cmake <srcs>'.
  Also, you can specify the generator with -G. see 'cmake --help' for more details
  For example:
    Build server
    cmake -DCMAKE_INSTALL_PREFIX=../opt/cmangos ..

    Build full server with extractor
    cmake -DCMAKE_INSTALL_PREFIX=../opt/cmangos -DBUILD_EXTRACTORS=ON ..

    Build only server without scripts and extractors and in debug mode
    cmake -DCMAKE_INSTALL_PREFIX=../opt/cmangos -DDEBUG=ON -DBUILD_ALL_SCRIPTS=OFF ..

    Build only login server
    cmake -DCMAKE_INSTALL_PREFIX=../opt/cmangos -DBUILD_GAME_SERVER=OFF ..

-- Detected 64-bit platform
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- GCC: SFMT enabled, SSE2 flags forced
-- cotire 1.7.6 loaded.
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found OpenSSL libraries: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
CMake Warning at CMakeLists.txt:267 (message):
  OpenSSL: Your OpenSSL version is critically vulnerable or no longer being
  maintained, consider upgrading

-- CMaNGOS-Core revision : e073f1d78c4bbfb8a44cd6e810c35bdbc7a56e45
-- Revision time stamp   : "2024-05-11T01:22:26+02:00"
-- Install server to     : /home/gujinjian/build
-- Use PCH               : Yes (default)
-- Build in debug-mode   : No  (default)
-- Build game server     : Yes (default)
-- Build login server    : Yes (default)
-- Build ScriptDev       : Yes (default)
-- Build AHBot           : No  (default)
-- Build METRICs         : No  (default)
-- Build OLD Playerbot   : No  (default)
-- Build Playerbots      : No  (default)
-- Build extractors      : Yes
-- Build RecastDemoMod   : No  (default)
-- Build git_id          : No  (default)
-- Link-time optimizations : No  (default)
-- Target directory for dev binaries(DEV_BINARY_DIR) = /home/gujinjian/build

-- Setting up zlib ...
-- zlib 1.2.13 successfully installed!
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gujinjian/build

### Crash Log

[Realmd.log](https://github.com/cmangos/issues/files/15285735/Realmd.log)
[Server.log](https://github.com/cmangos/issues/files/15285736/Server.log)

### Core SHA1 Commit Hash

e073f1d78c4bbfb8a44cd6e810c35bdbc7a56e45

### Database SHA1 Commit Hash

e073f1d78c4bbfb8a44cd6e810c35bdbc7a56e45

### Operating System

ubuntu22.04

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Anastasija1234** [comment]
Guys, it's me Anastasija from Discord. PLS keep in mind my memory lacks and that i am TOTALLY NEW to bug reporting, as of now. So PLS evaluate all my reports here in comparance to other reports, since I might make some mistakes at the first days here. THX.   ///  With FULL  "normal" T6 (so: not any socketed gems/not any enchants for testing!) not even close to "Crit Imunity Value", although Crit Imunity value should be achieved allready by full T6 alone (without gems, enchants on it), IF I remember correctly.... (Because you already achieved 415 defense with heroic dungeons gear...) So yes, IF i assume right, it really seems to be wrong values: Screenshot as prove added.
![WoWScrnShot_051224_131735](https://github.com/cmangos/issues/assets/51851815/08101541-456c-4e90-a7f7-714c22a35b09)  /// Branch: TBC

Core SHA1 Commit Hash
e073f1d78c4bbfb8a44cd6e810c35bdbc7a56e45

Database SHA1 Commit Hash
88670400c2d535c9f54a80590d264d9536c781c0

System: Windows 10 Home

**Comment by gujinjian** [comment]
thank you  Anastasija    . Character based attacks are not bonus.. From weapons or equipment.. Take a closer look at my picture. T6 equipment and spell damage weapons.. There are a total of 1000+spell damage, but level 1 fireball only has 26 damage points.. I don't know why this problem occurred at the moment. I suspect it may have occurred during the compilation process.. But currently, all compilations are carried out according to system requirements. No other impact, pure system. Ubuntu22.04

**Comment by Anastasija1234** [comment]
There has to really be something wrong on calculations... Even with Full T6 AND socketed ALL the HIGHEST available def-rating+ gems, you dont achieve crit-imunity-minimal-cap of 415... New pic with, like writen, all sockets def+ :

![WoWScrnShot_051224_153927](https://github.com/cmangos/issues/assets/51851815/3d76d3d5-2d42-4b7e-abf1-76e2a6cf2fed)

**Comment by insunaa** [comment]
Does not occur on WotLK
Can't confirm on TBC either:
![image](https://github.com/cmangos/issues/assets/3718129/d3e958ab-16b1-4cc4-8478-8af42944e056)
![image](https://github.com/cmangos/issues/assets/3718129/7aee38a3-efd1-4e9a-aced-2136e5a99ae7)

**Comment by Anastasija1234** [comment]
I went through gems again, and 410 is max. u can reach (with even full T6 and all  max. def gems+ socketed), so still 5 under crit-imune-cap of 415. Normally u achieve this yet with even gear for tbc heroic dungeons... So yeah. The other stats look like normal, but the defence values is definately not correct calculated. (TBC Branch), sreenshot: 

![WoWScrnShot_051224_161659](https://github.com/cmangos/issues/assets/51851815/090a0076-ab4b-42dd-87ad-2fe431574756)

**Comment by insunaa** [comment]
@Anastasija1234 That's a completely separate issue and has nothing to do with this, as far as I can tell.

**Comment by gujinjian** [comment]
> @Anastasija1234就我所知,这是一个完全独立的问题,与此无关。

For now. The data from the equipment, the character panel is correct. But the actual output and attack and defense values are incorrect. This is under Linux. Win is right. I hope the teacher can help

**Comment by gujinjian** [comment]
> @Anastasija1234

For now. The data from the equipment, the character panel is correct. But the actual output and attack and defense values are incorrect. This is under Linux. Win is right. I hope the teacher can help

**Comment by gujinjian** [comment]
Is it a problem with my compilation environment. Please help me.. I installed it according to the commands in WIKI.. Ubuntu22.04

**Comment by insunaa** [comment]
According to my own calculations the amount of damage you do with Rank 1 fireball is exactly correct. Are you sure that this is an actual issue?
Edit: See https://warcraft.wiki.gg/wiki/Downranking#Burning_Crusade
