### ISSUE TITLE
🐛 [Bug Report] TBC worldserver crash during loading

### ISSUE THREAD

**Issue by ImmortalusDev** [cmangos/issues#3713]
### Bug Details

Worldserver is crashing during loading after clean installation.
Also, DB updater says that i have DB up to date.

Source version            : [1.10.0] Return of the Vengeance
Last source content update: [0413_nonworldlootitems]
Database content version  : []

Info: Your DBs seem to be up to date with core revision.

### Steps to Reproduce

1. Compile TBC
2. Setup databases
3. Run bnet + world
4. Watch worldserver crash during loading

### Expected behavior

Worldserver should not crash during loading

### Crash Log

https://gist.github.com/ImmortalusDev/480f3bf7ba0fa2627a8c03bb789ad2c3

### Core SHA1 Commit Hash

e073f1d

### Database SHA1 Commit Hash

a6d463f

### Operating System

Win 10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by cpevors** [comment]
You don’t seem to have actually installed your databases if your “Database content version” is []. 

Return to InstallFullDB.sh and select Option 4.

**Comment by ImmortalusDev** [comment]
https://github.com/cmangos/tbc-db/tree/master/Full_DB + Updates

**Comment by cpevors** [comment]
Did you run the shell script that actually dumps the data into your database? The content version wouldn't be [] if your database had tables and data.

**Comment by ImmortalusDev** [comment]
I did...

> Trying to process last world (mangos) CORE updates

  CORE UPDATE PROCESSED: 0
  CORE UPDATE FOUND BUT ALREADY IN DB: 129

> Trying to process last Characters CORE updates

  CORE UPDATE PROCESSED: 0
  CORE UPDATE FOUND BUT ALREADY IN DB: 31

> Trying to process last Realm CORE updates

  CORE UPDATE PROCESSED: 0
  CORE UPDATE FOUND BUT ALREADY IN DB: 9

> Trying to process last Logs CORE updates

  CORE UPDATE PROCESSED: 0

**Comment by cpevors** [comment]
You updated only the core. There is no content in your database. That’s why your content version is blank. 

Please select Option 4. You’ll be prompted to ‘DeleteAll.’ Do so.

**Comment by ImmortalusDev** [comment]
This is what i did and now it says it's up to date...

Please enter your choice.....: 3
> Trying to process last world (mangos) CORE updates
  - Applying s2467_01_mangos_creature_static_flags.sql ... SUCCESS
  - Applying s2468_01_mangos_visibility.sql ... SUCCESS
  - Applying s2469_01_mangos_trainer_ability.sql ... SUCCESS
  - Applying s2470_01_mangos_worldstate_expression_spawn_group.sql ... SUCCESS
  - Applying s2471_01_mangos_pursuit.sql ... SUCCESS
  - Applying s2472_01_mangos_precision_decimal.sql ... SUCCESS
  - Applying s2475_01_mangos_spell_template.sql ... SUCCESS
  - Applying s2476_01_mangos_spell_template_ap.sql ... SUCCESS
  - Applying s2477_01_mangos_charmed_spell_list.sql ... SUCCESS
  - Applying s2478_01_mangos_creature_cls_stats.sql ... SUCCESS
  - Applying s2479_01_mangos_displayid_probability.sql ... SUCCESS

  CORE UPDATE PROCESSED: 11
  CORE UPDATE FOUND BUT ALREADY IN DB: 118

> Trying to process last Characters CORE updates

  CORE UPDATE PROCESSED: 0
  CORE UPDATE FOUND BUT ALREADY IN DB: 31

> Trying to process last Realm CORE updates

  CORE UPDATE PROCESSED: 0
  CORE UPDATE FOUND BUT ALREADY IN DB: 9

> Trying to process last Logs CORE updates

  CORE UPDATE PROCESSED: 0
  CORE UPDATE FOUND BUT ALREADY IN DB: 1

**Comment by ImmortalusDev** [comment]
WDB have now around 159 MB, but still crashing on the same spot.
I used https://github.com/cmangos/tbc-db/tree/master/Full_DB and then i applied updates using shell script.

**Comment by cpevors** [comment]
This is what your InstallFullDB.sh main manager screen should look like if you updated your databases correctly? **Please note that it very plainly says that my Database content version is... something. Yours at present says [], i.e. no content has been uploaded to your database.**

![image](https://github.com/cmangos/issues/assets/139099164/424a3ef7-d5cd-47b1-b824-163cf0bc6157)

If you pressed Option 3, you only updated your core. You need to do a full installation in order to populate your database with actual content. **Please select Option 4 on this main screen -- Full installation (create all DB and MySQL user, root required)**.

You will be prompted to enter your root username and password. Once you have done so, **please select Option 1 -- Full default CMaNGOS-core and TBC-DB installation (all DB with MySQL user)**. 

![image](https://github.com/cmangos/issues/assets/139099164/b96d1416-88c0-44a4-883d-60ea897d3404)

You will be brought to a screen in which you are prompted to type 'DeleteAll'; please do type **DeleteAll** and wait for the shell script to finish.

**Comment by ImmortalusDev** [comment]
For some reason i can't even type there password...

![Git](https://github.com/cmangos/issues/assets/49400575/45c441bc-a434-45c1-8060-903e992bc376)

**Comment by cpevors** [comment]
You are typing. It just doesn't show that you're typing.

**Comment by ImmortalusDev** [comment]
It worked, thanks! My bad, i overlooked step 3/4.

**Comment by cpevors** [comment]
All good! Glad it worked.

Just a head's up: You will _not_ want to use Option 4 to load in the latest commits going forward. On the main manager screen, you can use **Option 2) Install fresh TBC-DB only to 'tbcmangos'**. If you go through a full installation when you're simply trying to update your databases with the latest content revisions, you'll delete your characters.

If the manager alerts you that your core is out of date, you can, of course, use **Option 3) Install core updates only**.
