### ISSUE TITLE
🐛 [Bug Report] Character won't get logged off

### ISSUE THREAD

**Issue by dripone** [cmangos/issues#3716]
### Bug Details

The characters stay online for ever. Server should kick them out after a minute, but that just won't happen. No matter if the player is using "Exit game" from menu or ALT+F4. The exact same thing happens with both methods.

### Steps to Reproduce

1. Create a new character. Play some time with it.
2. Log out using the "Exit game" button from the menu ( or you can use the ALT+F4 too, because the same thing happens )
3. Log into a GM account. Go to the place where you logged out with the previous character.
4. The character stands still at that location. It won't have <AFK> flag and will not be kicked after 1 minute. The one i'm posting the picture about, is there for 2 days already.
![WoWScrnShot_051724_095057](https://github.com/cmangos/issues/assets/166992353/85302723-e33c-4276-92bb-a56bc974a1ad)

### Expected behavior

After a minute the character should be logged off.

### Core SHA1 Commit Hash

0e32ab652f9b44868bdadf99638002faca426c9d

### Database SHA1 Commit Hash

b5e1b21fa3648baaa642b758410cb2593948ad60

### Operating System

Windows Server 2022 Datacenter (Version 10.0, Build 20348)

### Client Version

1.12.1 (Classic)

**Comment by cpevors** [comment]
Seems like a duplicate in some ways of https://github.com/cmangos/issues/issues/3687. Different cores, same issue.

**Comment by insunaa** [comment]
closing as duplicate
