### ISSUE TITLE
🐛 [Bug Report] Warlock Immolate -- Two ticks happen at 2 seconds remaining

### ISSUE THREAD

**Issue by cpevors** [cmangos/issues#3717]
### Bug Details

I was putzing around on a new Warlock when I noticed that "2 hits" of my Immolate were happening at 2 seconds remaining on the debuff -- and no damage was ticking when the debuff ultimately fell off the mob. To my knowledge, this is not intended behaviour -- one tick should happen at 2 seconds remaining, and the last tick of the debuff should fire at 0 seconds remaining, as the debuff falls off the target.

See video below for reference. 

https://www.youtube.com/watch?v=h-dLGNhwcCQ&ab_channel=Supgad

### Steps to Reproduce

1. Create a Warlock
2. .learn 348
3. Cast Immolate on a mob -- and watch the damage as the debuff periodically ticks
4. Profit

### Expected behavior

One tick of damage should happen at 2 seconds remaining; the final tick should happen at 0 seconds remaining, just as the debuff falls off the mob.

### Core SHA1 Commit Hash

06dc7833393250527e9380996263550610f07d55

### Database SHA1 Commit Hash

d037d535a0b63a9bff6f0dcc3bee984152c6a2b8

### Operating System

Windows 11 Home - 64-bit

### Client Version

2.4.3 (The Burning Crusade)

**Comment by al3xc1985** [comment]
is this working good now?

**Comment by cpevors** [comment]
I was a dunce, and posted this as a bug, but it persists only when using the Proxy. Once I fired up a native 2.4.3 client, all ran seamlessly. 

So yes, it’s working as intended, and I’ve learned a valuable lesson. 😅
