### ISSUE TITLE
🐛 [Bug Report] TileAssembler compile error with GCC-12

### ISSUE THREAD

**Issue by gregclout** [cmangos/issues#3723]
### Bug Details

Issue compiling cmangos on *nix machine. Targeting TBC release.

I am following this guide: https://github.com/cmangos/issues/wiki/Installation-Instructions

There are 2 warnings in the build step

1. Compiler warning:

```
CMake Warning at cmake/compiler/gcc/settings.cmake:20 (message):
  GCC: This version is known to be affected by internal compiler bugs, do
  upgrade if build fails
Call Stack (most recent call first):
  cmake/platform/unix/settings.cmake:17 (include)
  cmake/macros/CheckPlatform.cmake:18 (include)
  CMakeLists.txt:105 (include)
```

2. SSL warning

```
CMake Warning at CMakeLists.txt:267 (message):
  OpenSSL: Your OpenSSL version is critically vulnerable or no longer being
  maintained, consider upgrading
```

Given the instructions and this [previous issue](https://github.com/cmangos/issues/issues/3576) point to this being caused by a GCC 11, I have updated this to gcc-12.

```
gcc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### Steps to Reproduce

1. follow guide up until compile step
2. Run `cmake ../mangos -DCMAKE_INSTALL_PREFIX=~/cmangos/run -DBUILD_EXTRACTORS=ON -DPCH=1 -DDEBUG=0 -DBUILD_PLAYERBOT=ON`
3. run `make`

### Expected behavior

Compiles successfully.

### Crash Log

```
usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
during GIMPLE pass: vrp
/home/mangos/cmangos/mangos/src/game/vmap/TileAssembler.cpp: In member function ‘void VMAP::TileAssembler::exportGameobjectModels()’:
/home/mangos/cmangos/mangos/src/game/vmap/TileAssembler.cpp:332:10: internal compiler error: in compute_live_loop_exits, at tree-ssa-loop-manip.c:247
  332 |     void TileAssembler::exportGameobjectModels()
      |          ^~~~~~~~~~~~~
0x7e2736c29d8f __libc_start_call_main
	../sysdeps/nptl/libc_start_call_main.h:58
0x7e2736c29e3f __libc_start_main_impl
	../csu/libc-start.c:392
```

### Core SHA1 Commit Hash

65c4966bdb44b5be7d2e5671dcd3c60843109f40

### Database SHA1 Commit Hash

ef8d502cb24270477e98dea4ae46ba9ba4f8c1b8

### Operating System

Pop_OS! 22.04 LTS

### Client Version

2.4.3 (The Burning Crusade)

**Comment by gregclout** [comment]
I was able to get through the compile using the clang compiler, although with warnings.

![Screenshot from 2024-06-08 10-12-32](https://github.com/cmangos/issues/assets/853662/dd0502c4-fa8c-49c7-a37b-841d12450bd1)

For those landing here, to install clang and its dependencies I used:

`sudo apt install clang libstdc++-12-dev`

And then added the required parameters of `DCMAKE_C_COMPILER` and `DCMAKE_CXX_COMPILER` to by build string, eg:

`cmake ../mangos -DCMAKE_INSTALL_PREFIX=~/cmangos/run -DBUILD_EXTRACTORS=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++`

**Comment by insunaa** [comment]
see https://github.com/cmangos/issues/wiki/Installation-Instructions#troubleshooting
![image](https://github.com/cmangos/issues/assets/3718129/4513ab39-76fe-4b2b-9d93-82bdbca0bb63)

and

![image](https://github.com/cmangos/issues/assets/3718129/2267627f-2001-4d61-899b-773ec2a86686)

**Comment by gregclout** [comment]
@insunaa Thanks for that. I had seen that and had upgraded to GCC 12.3, and the compile error still persists.

**Comment by insunaa** [comment]
@gregclout I'll update the instructions.
