### ISSUE TITLE
🐛 [Bug Report] Pick Lock deleete lockbox without open it

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3727]
### Bug Details

Using skill Pick Lock on a closed Lockbox delete the Lockbox from inventory but not open it.

### Steps to Reproduce

1. use skill on lockbox in inventory
2. lockbox disapear
3. no box, no items
4.

### Core SHA1 Commit Hash

 hash(65c4966bdb44b5be7d2e5671dcd3c60843109f40)

### Database SHA1 Commit Hash

some days old

### Operating System

W11

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Ischtaratu** [comment]
thats odd ... now it works ... nevermind
/closed

**Comment by AnonXS** [comment]
Its a loot matter due to issues one or the other item can sometimes be empty which should not be.

if you want tell me the item you looted with pickpocketing?
