### ISSUE TITLE
🐛 [Bug Report] Raid The_Eye , Boss_Kaelthas , 4 advisors not respawn after players failed at any phase .

### ISSUE THREAD

**Issue by betayi** [cmangos/issues#3728]
### Bug Details

as title, players can not continue next fight once they failed at any phase. cause advisors not reset.

### Steps to Reproduce

1. goto the_eye and start the Boss_Kaelthas fight
2.kill all advisors enter the next phase,  then fail this fight at any phase
3.watch the advisors, not respawn
4.

### Expected behavior

 advisors should be respawn at there position while boss_Kaelthas enter EvadeMode

### Core SHA1 Commit Hash

6d1e246e16bcc738eec816c9bc54442a976bc63c

### Database SHA1 Commit Hash

latest

### Operating System

ubuntu22

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
Already fixed a month ago in https://github.com/cmangos/mangos-tbc/commit/537d7280736dd19c586327d4aed202da90581b6a
Also please ensure that you're not reporting bugs for significantly changed forks of CMaNGOS in the main repo. If you are using Niam's fork, please report issues there first, unless you have confirmed that they're also present on the latest unmodified CMaNGOS core.

**Comment by betayi** [comment]
thanks for your patience ：）
