### ISSUE TITLE
Dark Rider of Acherus Movement Bug (Into the Realm of Shadows Quest)

### ISSUE THREAD

**Issue by Warrior94** [cmangos/issues#373]
This is the man: http://www.wowhead.com/npc=28768/dark-rider-of-acherus

The Dark Rider´s horse moves independently of him rider. Many times you find the rider looking in another direction, and the horse to another address. The rider and his horse behave like two different units, one hostile and other passive.

When you fight against the rider, does not approach you, because the horse moves where he wants.

So it should work properly: http://www.youtube.com/watch?v=83DhZ-QZkGg

Greetings.

**Comment by Tauriella** [comment]
Bump

**Comment by jimmybrancaccio** [comment]
@Warrior94 Can you confirm if this is still an issue in the latest commits?

**Comment by Grz3s** [comment]
fixed long time ago ;)
