### ISSUE TITLE
🐛 [Bug Report] Renataki spell_thousand_blades_renataki too high damage

### ISSUE THREAD

**Issue by yyhhrr** [cmangos/issues#3732]
### Bug Details

Renataki spell_thousand_blades_renataki too high damage.When Renataki use spell_thousand_blades the server lag and you dead immediately.

### Steps to Reproduce

1.Renataki spell_thousand_blades_renataki too high damage.When Renataki use spell_thousand_blades the server lag and you dead immediately.
2.
3.
4.

### Core SHA1 Commit Hash

4a3e2845458935721a8f16103d9592da15370b64

### Database SHA1 Commit Hash

652013132d8c60b4f9bcf07f6f88941818a1d94e

### Operating System

win 11

### Client Version

1.12.1 (Classic)

**Comment by insunaa** [comment]
Try this patch
```patch
diff --git a/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/zulgurub/boss_renataki.cpp b/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/zulgurub/boss_renataki.cpp
index 050cd15438..9fd30b00b8 100644
--- a/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/zulgurub/boss_renataki.cpp
+++ b/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/zulgurub/boss_renataki.cpp
@@ -28,7 +28,7 @@ EndScriptData
 
 enum
 {
-    SPELL_THOUSAND_BLADES   = 24649,
+    SPELL_THOUSAND_BLADES   = 24767,
     SPELL_VANISH            = 24699,
     SPELL_GOUGE             = 24698,
     SPELL_TRASH             = 3391,
```
and report if it solves the issue

**Comment by yyhhrr** [comment]
Thank you!It solves the issue,but there is another issue,when boss vanished and come out again,he wouldn't attack player.
