### ISSUE TITLE
🐛 [Bug Report] [WoTLK] [Spawn Group] spawn_group_spawn creature dbGuid 5400173 belongs to more than one spawn_group.

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3745]
### Bug Details

LoadSpawnGroups: spawn_group_spawn creature dbGuid 5400173 belongs to more than one spawn_group. Skipping.

### Steps to Reproduce

1. Start Server
2.
3.
4.

### Core SHA1 Commit Hash

547c0eb3d21ea2cc6c3e3f3f33677444e2a4a245

### Database SHA1 Commit Hash

c87702219e9388b7bf094dacc53522e4236f4dc4

### Operating System

Ubuntu Server LTS 22.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by Grz3s** [comment]
backport error.
Fix with next pack of backports..

**Comment by adellaci** [comment]
@Grz3s Thank you
