### ISSUE TITLE
🐛 [Bug Report] [WoTLK] [Spell Script] Spell 57415 has script spell_the_reckoning in spell_scripts but script does not exist.

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3746]
### Bug Details

```
Loading spell scripts...
Spell 57415 has script spell_the_reckoning in spell_scripts but script does not exist. Skipping.
```

### Steps to Reproduce

1.Start Server
2.
3.
4.

### Core SHA1 Commit Hash

547c0eb3d21ea2cc6c3e3f3f33677444e2a4a245

### Database SHA1 Commit Hash

c87702219e9388b7bf094dacc53522e4236f4dc4

### Operating System

Ubuntu Server LTS 22.04

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
was fixed "long" ago actually, did you not update the core? https://github.com/cmangos/mangos-wotlk/commit/526d2fbc4f33c68abbee7dfd25b331e025f1c118
