### ISSUE TITLE
🐛 [Bug Report] Warden Auth Kick

### ISSUE THREAD

**Issue by Shettelight** [cmangos/issues#3748]
### Bug Details

https://github.com/cmangos/mangos-tbc/commit/3fadd9f8d685943ea00c6b260c4cdd71a2b17288
Check wrong or smth else, but kick at auth.
@Kill

### Steps to Reproduce

1. Build & Launch server by win32 (debug mode)
2. Try connect to server
3. u`ll disconnected
4.  no available connect to the server

### Expected behavior

Not kick at auth

### Core SHA1 Commit Hash

3fadd9f8d685943ea00c6b260c4cdd71a2b17288

### Database SHA1 Commit Hash

HEAD

### Operating System

Win32

### Client Version

2.4.3 (The Burning Crusade)

**Comment by Arnibou** [comment]
Confirmed !

![Capture d'écran 2024-07-31 102117](https://github.com/user-attachments/assets/3432e14b-731a-45fa-8f32-602cba745f50)

and db:
![Capture d'écran 2024-07-31 102158](https://github.com/user-attachments/assets/91e0f526-2fb1-4b5e-81ad-bf37174eaa95)

https://github.com/cmangos/mangos-tbc/commit/3fadd9f8d685943ea00c6b260c4cdd71a2b17288

why +1 in this condition ?

`if (length > (recvData.size() - (recvData.rpos() + 1)))`
