### ISSUE TITLE
[Classic] [PVP] [PVE] - Parry attacks from behind

### ISSUE THREAD

**Issue by Tobschinski** [cmangos/issues#375]
Right now, mobs can http://www.wowwiki.com/Parry attacks from behind.
The shown mob parried twice in a row while running away in fear. 

![parryfrombehind](https://f.cloud.github.com/assets/4753528/2062054/11770906-8c79-11e3-99fa-ee409a8878ae.png)

It should be like

![parrynotes](https://f.cloud.github.com/assets/4753528/2062055/15afb360-8c79-11e3-9696-f820e6be53c7.png)

**Comment by Warlockbugs** [comment]
All facing and unit state issues related to parry are now resolved.
