### ISSUE TITLE
🐛 [Bug Report] Player Bot Add Loot Action warns: Lupos (my pet name) is blocking ..., must ...

### ISSUE THREAD

**Issue by pucelle** [cmangos/issues#3750]
### Bug Details

I checked and find this issue is caused by `GetAllHostileNonPlayerUnitsAroundWO`, I guess it should also ignore pets.

### Steps to Reproduce

1. Be a hunter, have a pet.
2. invites some bots.
3. Accept a quest needs looting object.
4. Warns "Lupos (my pet name) is blocking ..., must ..."

### Core SHA1 Commit Hash

f887e6471646105124553368d9b661119ab84be3

### Database SHA1 Commit Hash

68371b84375ca7e972af388e755dfb0d0aaf9661

### Operating System

Windows 10

### Client Version

1.12.1 (Classic)

**Comment by Redbu11dev** [comment]
fixed in https://github.com/cmangos/playerbots/pull/36

**Comment by pucelle** [comment]
Thanks

**Comment by al3xc1985** [comment]
@pucelle can u close this if done pls?

**Comment by pucelle** [comment]
Ok
