### ISSUE TITLE
🚀 [Feature Request] EventAI - TARGET_SUMMONED

### ISSUE THREAD

**Issue by miraco** [cmangos/issues#3755]
### Feature Details

Add TARGET_SUMMONED to creature_ai_scripts, to handle specific events onto summoned.

Example:
1) Creature A, can summon Creature B in fight. When Creature A dies, Creature B should keep fighting the player. If Player dies, Creature B will evade and despawn.
Creature A can use ThorwAiEvent with target_spawned to tell the summoned creature B that he is dead. CreatureB uses ACTION_T_SET_DESPAWN_AGGREGATION on ReciveAIEvent, and will despawn on evade.

2) Creature A, can summon Creature B in fight. After summoning creature b, creature A switches to Phase 2. In Phase 2 creature A can cast buff spells onto Creature B.

### Benefits and Purpose

While reworking some open World NPCs i noticed different behavior of Summoning NPCs and how their summones (pets) act after master dies.
Example:
Burning Blade Apprentice will summon 1 Voidwalker when being OutOfCombat.
When Voidwalker dies, Burning Blade Apprentice will summon a new Voidwalker if OutOfCombat again.

If Burning Blade Apprentice dies the Voidwalker will keep attacking the Player and despawn on Death or on Reaching Home.
If Burning Blade Apprentice and Voidwalker are alive while killing the Player, both will just normaly reset.

Currently we are always despawning and respawning the voidwalker if the player dies.

### Core Versions

- [X] 1.1.12 (Classic)
- [X] 2.4.3 (The Burning Crusade)
- [X] 3.3.5a (Wrath of the Lich King)

**Comment by AnonXS** [comment]
L4G Core had a nice implementation for it, it worked with castflag 32 and seemingly checked if npc is already spawned (also worked for totems), hence on resetting the main mob would not resummon a pet. currently we use this strange workaround.

**Comment by miraco** [comment]
Oh yeah I remember this, my idea to implement this is pretty simple tho 
Summoning npc sets phase to 1 on spawn 
Summoning npc can cast summoning spell on phase 1 and sets phase to 0 
Summoning npc Switches to phase 1 on SummonedJustDied

this all works do far only thing that’s missing is to tell the summoned npc that he should respawn on evade if summoner is dead

**Comment by Grz3s** [comment]
`hence on resetting the main mob would not resummon a pet. currently we use this strange workaround.` 
This was quick and simple solution for spamming summons..or not having resummon again until masters respawn (not correct in many cases)
The way of fixing it.. is to go through each individal and check how it should be. 


You also may have npcs that on first look they are summoned.. but they're simply part of spawn group. (master dies - companion stays).
You can be 100% sure only by checking correct data:
```code
SummonedBy: Full: 0x0
CreatedBy: Full: 0x0
CreatedBySpell: 0x0
```

example:
![42342342](https://github.com/user-attachments/assets/55ebdca9-0493-4858-bf92-8d70d1d73d23)

UPDATE:
Ive got checked many TBC/Wotlk creatures... and they will be added in future*

**Comment by miraco** [comment]
You are absolutely correct, those summoners often behacke differently, and I think most of them can get scripted very easily.

but the case I described currently seems to be unsupported, and I think the solution I had in mind to use would be pretty simple 
But I’m also open for other suggestions how we can script mobs like this without using core scripts
