### ISSUE TITLE
🐛 [Bug Report] Cmangos TBC and Classic handle questgiver_greeting differently from WoTLK

### ISSUE THREAD

**Issue by SeelGit** [cmangos/issues#3756]
### Bug Details

In Cmangos TBC (and Classic, judging by the code) even if the NPC has a single quest, they will still show guest giver greeting if the NPC has greeting specified in questgiver_greeting table. If they don't - the quest text for a quest will be shown instead. 
WoTLK Cmangos first checks that there are multiple quests OR that CONFIG_BOOL_ALWAYS_SHOW_QUEST_GREETING is set, and will only then display the greeting.

https://github.com/cmangos/mangos-classic/blob/master/src/game/Entities/Player.cpp#L12034
https://github.com/cmangos/mangos-tbc/blob/27f97760bfa57d3774086b771593de08c46b2428/src/game/Entities/Player.cpp#L12842
https://github.com/cmangos/mangos-wotlk/blob/846d352eb9cc0109d47bdf25beafd36e571fb28c/src/game/Entities/Player.cpp#L13920

### Steps to Reproduce

1. Go to [Ragnar Thunderbrew - 1267](https://www.wowhead.com/classic/npc=1267/ragnar-thunderbrew) in Dun Morogh as a level <50 character, he will offer [quest 384](https://www.wowhead.com/classic/quest=384/beer-basted-boar-ribs). Even though this is a single quest available, questigiver_greeting entry will still be displayed along quest list with that single quest.
![image](https://github.com/user-attachments/assets/a392a911-b05f-4bb1-9861-bf2951be6f0b)

3. [Pilot Stonegear - 1377](https://www.wowhead.com/classic/npc=1377/pilot-stonegear) nearby will do the same when offering [quest 313](https://www.wowhead.com/classic/quest=313/the-grizzled-den)
![image](https://github.com/user-attachments/assets/411fa0a8-dd7d-4cae-8135-1d676f8d7c57)

### Expected behavior

WoTLK logic should be applicable to TBC and Classic. 
Still allowing to use CONFIG_BOOL_ALWAYS_SHOW_QUEST_GREETING should be very useful when checking content correctness, so this should also be kept in TBC and Classic.

### Suggested Workaround

Port check from WoTLK Cmangos.

### Core SHA1 Commit Hash

155217c690b9dbddc0615f309248429adf074fb7

### Database SHA1 Commit Hash

a56aff0dafe006242cdc54b24ebae7337e6e5e6d

### Operating System

Win 11

### Client Version

2.4.3 (The Burning Crusade)

**Comment by SeelGit** [comment]
Video from before Cata (dated 2009) showing that the greeting is not shown:
https://www.youtube.com/watch?v=v5Ti1QBz60c

**Comment by killerwife** [comment]
Merely missing backport.
