### ISSUE TITLE
💬 [Support Request] How to add new 'description' text field to spell_template

### ISSUE THREAD

**Issue by ablohme86** [cmangos/issues#3757]
### Core Version

mangos-classic

### Support Request Details

When I try to add a new field 'description' to the spell_template I get error (expecting 159 fields) in mangosd, how do I go about adding this?

### Steps to Reproduce

1. Alter table to add 'text' description field in spell_template
2.
3.
4.

### Core SHA1 Commit Hash

N/A

### Database SHA1 Commit Hash

N/A

### Server Operating System

debian arm

### Client Version

1.1.12 (Classic)

### Client Operating System

Raspberry Pi

**Comment by insunaa** [comment]
Don't add random fields if you're not sure what you're doing.

**Comment by celguar** [comment]
If  you want do add some field you are supposed to know why you are doing it, also how server loads this table and where in code it happens, and how to handle it.

**Comment by killerwife** [comment]
Check spell fmt in sql loaders. You need to add another string.
