### ISSUE TITLE
[Looting] - How it should work / how it is working right now!

### ISSUE THREAD

**Issue by Tobschinski** [cmangos/issues#376]
There are 5 different options a leader can choose to distribute http://www.wowwiki.com/Loot and one special procedure to quest-items.

![5lootingoptions](https://f.cloud.github.com/assets/4753528/2061875/d2d97a06-8c70-11e3-9e49-b64060e65128.png)

Right now, many loot options do not work as intended.

e.g. Group-looting, the standard option, is a mix between free for all and need before greed. Every single player that has been involved in killing the mob, is able to loot it. (gold, quest-items, items of all qualities). 

As the basics of looting are untouched, these following information are still valid for vanilla realms.

**Comment by Argonn** [comment]
Any info regarding the TC fix ?

**Comment by cyberium** [comment]
Please try to check if all of those issue are resolved in latest classic core.
It will be ported to TBC and WoTLK when all will be fine.

**Comment by cyberium** [comment]
fixed
