### ISSUE TITLE
🐛 [Bug Report] The_Eye Kaelthas Spell_Flame_Strike Damage Actived Without Delay

### ISSUE THREAD

**Issue by betayi** [cmangos/issues#3762]
### Bug Details

The Eye, Kaelthas will cast Spell_Flame_Strike at phase 4, the spell summon a npc(Flame Strike Trigger (Kael) NPC Entry:21369) invisible at the position of random player, and then -the problem is- make direct huge damage aura like nova(Spell Entry :36731) which should actived after a few second dummy(Spell Entry :36730) effect.   

### Steps to Reproduce

1.Enter Raid The Eye and start Kael's combat to phase 4( after the 4 Advisors defeated again)
2.Wait Kael to cast spell Flame_Strike ,watch there's two effect at player actived at same time
3.
4.

### Expected behavior

Spell 36731 effect should be actived 4-5 second after the dummy spell 36730

### Core SHA1 Commit Hash

6d1e246e16bcc738eec816c9bc54442a976bc63c

### Database SHA1 Commit Hash

latest

### Operating System

ubuntu22

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
Try this
```patch
diff --git a/src/game/AI/ScriptDevAI/scripts/outland/tempest_keep/the_eye/boss_kaelthas.cpp b/src/game/AI/ScriptDevAI/scripts/outland/tempest_keep/the_eye/boss_kaelthas.cpp
index 0c3f4184d..f10943d54 100644
--- a/src/game/AI/ScriptDevAI/scripts/outland/tempest_keep/the_eye/boss_kaelthas.cpp
+++ b/src/game/AI/ScriptDevAI/scripts/outland/tempest_keep/the_eye/boss_kaelthas.cpp
@@ -1397,6 +1397,8 @@ struct FlameStrikeKael : public AuraScript
 {
     void OnApply(Aura* aura, bool apply) const override
     {
+        if (apply)
+            return;
         aura->GetTarget()->CastSpell(nullptr, 36731, TRIGGERED_OLD_TRIGGERED, nullptr, aura);
         if (aura->GetTarget()->IsCreature())
             static_cast<Creature*>(aura->GetTarget())->ForcedDespawn(10000);
```

**Comment by betayi** [comment]
works!
