### ISSUE TITLE
🐛 [Bug Report] Random Crash

### ISSUE THREAD

**Issue by d3athbl0w** [cmangos/issues#3764]
### Bug Details

I haven't been able to figure out exactly where it crashes, it's usually when users are in dungeons.

### Steps to Reproduce

1.
2.
3.
4.

### Crash Log

[crash.txt](https://github.com/user-attachments/files/16809388/crash.txt)

### Core SHA1 Commit Hash

8397e7ba4ddce8d2fcea677e4521400595f63ed2

### Database SHA1 Commit Hash

21871f15cc3d4809409dce42e601aaea1ca10a07

### Operating System

Debian 11 and 12

### Client Version

2.4.3 (The Burning Crusade)

**Comment by cpevors** [comment]
It appears to be some sort of segmentation fault that occurs at a section in the code where it attempts to update all world objects.

```c++
   // update all objects
    for (auto wObj : objToUpdate)
    {
        wObj->Update(t_diff);
        ++count;
    }
```

I haven't been able to produce this crash at all. Can you give me some idea which dungeon(s) are more likely to trip this crash?

**Comment by d3athbl0w** [comment]
> It appears to be some sort of segmentation fault that occurs at a section in the code where it attempts to update all world objects.
> 
> ```c++
>    // update all objects
>     for (auto wObj : objToUpdate)
>     {
>         wObj->Update(t_diff);
>         ++count;
>     }
> ```
> 
> I haven't been able to produce this crash at all. Can you give me some idea which dungeon(s) are more likely to trip this crash?

This is extremely rare, we did the same procedure again and it didn't happen

https://streamable.com/zpgbl5

**Comment by Arnibou** [comment]
Same , even if nobody in game (starting world)

**Comment by mostlikely4r** [comment]
https://github.com/cmangos/mangos-tbc/pull/699

Maybe related. Pr is to fix a crash in the same location.

**Comment by d3athbl0w** [comment]
Thanks @mostlikely4r crash solved! <3
