### ISSUE TITLE
[TBC] Micro-teleporting while moving | MovementFlags2

### ISSUE THREAD

**Issue by Ankso** [cmangos/issues#377]
The movement packets are a little bit "broken" in the TBC core, It seems that it's related to MovementFlags2, at least according to this post http://cmangos.net/thread-500-post-3323.html in the CMaNGOS forums.

I have uploaded a video to showcase the problem: https://www.youtube.com/watch?v=IlPjsUxrmTQ

It's happening with the latest core version.

Greetings!

**Comment by krullgor** [comment]
i addressed this issue in https://github.com/cmangos/mangos-tbc/commit/32bd10bbd6f546c0107307a9217fb06ffda69062

**Comment by stfx** [comment]
Awesome stuff krullgor
