### ISSUE TITLE
🐛 [Bug Report] 

### ISSUE THREAD

**Issue by cpevors** [cmangos/issues#3774]
### Bug Details

After freeing the third hostage, Kraz, in Zul'Aman, he explodes his trunk, leaving behind piles of gold and Kraz's Package (https://www.wowhead.com/tbc/object=186667/krazs-package), which is supposed to contain an epic ring. However, while the trunk blows up, and the piles of gold are lootable, I am never able to interact with Kraz's Package and loot the ring.

![WoWScrnShot_102124_224349](https://github.com/user-attachments/assets/61969634-40a8-4bdf-94ab-6bda25219a5d)

### Steps to Reproduce

1. You may need to first adjust`entry = 187359` in the `gameobject_template` table of `tbcmangos`. Change `t.data0 =1`, so that you alone can hit the gong in Zul'Aman to open the gates.
2. Create a new character, if you do not have one already, and `.level` it to level 70. 
3. `.tele Zul'Aman`
4. Talk to Harrison Jones, and when able, ring the gong. 
5. Proceed through the raid, or bee-line it to Jan'alai. Kill Jan'alai, head back down the stairs, speak with Kraz. 
6. Allow Kraz's RP to commence, and after he blows up his trunk, he should say "Please, friends, accept this offering with Kraz's thanks," at which point Kraz's Package becomes lootable.

### Expected behavior

Kraz's Package should be lootable, and it should contain one of five (5) epic rings.

### Core SHA1 Commit Hash

8be3aaf39d11ed4668dd00253f260b7fd81e8f03

### Database SHA1 Commit Hash

3088562e9ce806c302d16db3b450665e5626be89

### Operating System

Windows 11 Home 24H2

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
What's Kraz' creature entry?

**Comment by insunaa** [comment]
![image](https://github.com/user-attachments/assets/04905433-4efe-4ae5-a9a0-9fb7102f577e)
on wotlk it works

**Comment by miraco** [comment]
Iirc the loot on those objects are not fixed it’s more based on what boss you kill first.

For example when you start the time run and go straight to Jan Alai (iirc the boss where kraz stands) the object should drop the loot from 1 time event 

The reason behind this was to hold the mount back to the 4th spawned object, Else every group could just go straight to kill hallazzi (4th boss) and get the mount 

Anyway I’ll look into it when I’m back home

**Comment by insunaa** [comment]
iirc every boss has this little bonus loot treasure, but the mount is separate from that, as it's spawned by an event only when all timed bosses are defeated.

this loot does seem incorrect, but the point was more that the chest correctly becomes clickable/lootable.

One other issue I noticed is that the chest doesn't smoke before it explodes, even tho it should. This spell is applied to the chest https://www.wowhead.com/tbc/spell=43418/cosmetic-explosive-charge-w-aoe-knockback and then a smoke plume should rise until it explodes to reveal the package and the gold coins

**Comment by miraco** [comment]
Yes, every boss has this bonus loot if you killed it in time 
But there is a specific order;
1 boss 1 of 8 items 
2 bosses 1 of 6 weapons 
3 bosses 1 of 5 rings 
4 bosses mount

the problem with not lootable will prob be in zulaman core script cause it’s all hardcoded in core

**Comment by insunaa** [comment]
ok the spell for the smoke is https://www.wowhead.com/tbc/spell=43452/cosmetic-small-white-smoke-flare

```patch
diff --git a/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/zulaman/zulamanScripts.cpp b/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/zulaman/zulamanScripts.cpp
index 9ce1f5086..a0978356c 100644
--- a/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/zulaman/zulamanScripts.cpp
+++ b/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/zulaman/zulamanScripts.cpp
@@ -1437,6 +1437,7 @@ enum
     NPC_TEXT_ID_KRAZ_DONE       = 11602, // unknown gossip menu entry
     NPC_TEXT_ID_KRAZ_DONE2      = 11604, // unknown gossip menu entry
 
+    SPELL_SMOKE_VISUAL          = 43452,
     SPELL_EXPLOSIVE_CHARGE      = 43418,
 
     SAY_KRAZ_HELP_1             = -1568105,
@@ -1535,6 +1536,11 @@ struct npc_krazAI : public ScriptedAI
                         break;
                     case 4:
                         DoScriptText(SAY_KRAZ_EVENT_3, m_creature);
+                        if (GameObject* chest = m_instance->GetSingleGameObjectFromStorage(GO_KRAZS_CHEST))
+                        {
+                            if (Creature* invisMan = GetClosestCreatureWithEntry(chest, NPC_EXTERIOR_INVISMAN, 15.0f))
+                                invisMan->CastSpell(nullptr, SPELL_SMOKE_VISUAL, TRIGGERED_OLD_TRIGGERED);
+                        }
 
                         m_uiEventTimer = 1000;
                         m_uiEvent = 5;
@@ -1553,12 +1559,12 @@ struct npc_krazAI : public ScriptedAI
                         break;
                     case 7:
 
-                        if (GameObject* pChest = m_instance->GetSingleGameObjectFromStorage(GO_KRAZS_CHEST))
+                        if (GameObject* chest = m_instance->GetSingleGameObjectFromStorage(GO_KRAZS_CHEST))
                         {
-                            if (Creature* pInvisMan = GetClosestCreatureWithEntry(pChest, NPC_EXTERIOR_INVISMAN, 15.0f))
-                                pInvisMan->CastSpell(pInvisMan, SPELL_EXPLOSIVE_CHARGE, TRIGGERED_OLD_TRIGGERED);
+                            if (Creature* invisMan = GetClosestCreatureWithEntry(chest, NPC_EXTERIOR_INVISMAN, 15.0f))
+                                invisMan->CastSpell(nullptr, SPELL_EXPLOSIVE_CHARGE, TRIGGERED_OLD_TRIGGERED);
 
-                            pChest->Delete();
+                            chest->Delete();
                         }
 
                         GetGameObjectListWithEntryInGrid(lCoinList, m_creature, GO_GOLD_COINS_1, 25.0f);
```

**Comment by cpevors** [comment]
> Yes, every boss has this bonus loot if you killed it in time But there is a specific order; 1 boss 1 of 8 items 2 bosses 1 of 6 weapons 3 bosses 1 of 5 rings 4 bosses mount
> 
> the problem with not lootable will prob be in zulaman core script cause it’s all hardcoded in core

You’re correct; loot is determined by order, I apologise for misspeaking there. In my run, Kraz was the third hostage saved, so his Package should have included Rings. Alas, my issue is more that the game object is not lootable. 

I’ll commit to providing a video later this afternoon, when I’m back home behind my computer. 

Appreciate everyone’s eyes on this.

**Comment by miraco** [comment]
Can you try with different order so kraz bag is first 2nd or 4th? 
would help to know if it’s a bag thing or order thing

**Comment by cpevors** [comment]
Would be my pleasure. Should be home in a couple of hours, will provide video/follow-up promptly.

**Comment by cpevors** [comment]
Well, now I can't replicate it. Tried running it where Kraz was 1st, 2nd, and 3rd, and his box was lootable every time today. *side-eye*.
