### ISSUE TITLE
🐛 [Bug Report] TBC client stuck on login after commit b1bec88bd15d05fac78d29d069cf9620383027f3

### ISSUE THREAD

**Issue by kotsmotritnastul** [cmangos/issues#3778]
### Bug Details

newest commit broke the server, i cant log in because client stuck on "connected" and doesnt get me to the characters list.

### Steps to Reproduce

1. update to newest commit https://github.com/cmangos/mangos-tbc/commit/b1bec88bd15d05fac78d29d069cf9620383027f3
2. compile it with `cmake .. -DCMAKE_INSTALL_PREFIX=path/to/cmangos/mangos/run -DPCH=1 -DDEBUG=0 -DBUILD_PLAYERBOTS=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ && make && make install`
3. go to `~/cmangos/run/bin` in terminal
4. launch `~/cmangos/run/bin/mangosd -c ~/cmangos/run/etc/mangosd.conf -a ~/cmangos/run/etc/ahbot.conf`
5. try to log in
6. client stuck on "connected" and you will never get to characters list

### Expected behavior

i can log in and see characters list.

### Suggested Workaround

1. `cd` to mangos directory
2. run `git checkout 877d6070026d6ea687ddbd522a0fd40e696a57f2`
3. compile it with `cmake .. -DCMAKE_INSTALL_PREFIX=path/to/cmangos/mangos/run -DPCH=1 -DDEBUG=0 -DBUILD_PLAYERBOTS=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ && make && make install`
4. now it works and i can log in without problems

### Crash Log

it doesnt crash but commit https://github.com/cmangos/mangos-tbc/commit/b1bec88bd15d05fac78d29d069cf9620383027f3 definitely broke something since client stucks on log in process with it but works flawlessly if I revert this commit before compiling server.

also i noticed server cannot be shut down by `server shutdown 1` - now i have to manually kill the process `mangosd`. if i go back to commit `877d6070026d6ea687ddbd522a0fd40e696a57f2` then i can shut down the server with `server shutdown 1`.

### Core SHA1 Commit Hash

b1bec88bd15d05fac78d29d069cf9620383027f3

### Database SHA1 Commit Hash

b1bec88bd15d05fac78d29d069cf9620383027f3

### Operating System

fedora 40/alma linux 9

### Client Version

2.4.3 (The Burning Crusade)

**Comment by insunaa** [comment]
fixed in https://github.com/cmangos/mangos-tbc/commit/c0611abe648a78be7b50888b95b0d16c2456aaed
