### ISSUE TITLE
Amani Pass - Missing RP

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#3779]
Prigmon https://www.wowhead.com/tbc/npc=23761/prigmon - missing pathing and working on things (emotes

Samir https://www.wowhead.com/tbc/npc=23724/samir - missing pathing around periodically

Packhorse - 191025 - seems to be possibly random with overworked nag  
Also mean to path and sniff corpses  

https://www.wowhead.com/tbc/npc=23764/marge
https://www.wowhead.com/tbc/npc=23766/morgom
https://www.wowhead.com/tbc/npc=23762/brend
These 3 are on a loop with each other. Periodically marge picks up grog, they throw it at burning building. Occasionally marge argues with someone and starts chasing either morgom or brend with some text. Loop repeats again.

Kurzel https://www.wowhead.com/wotlk/npc=23748/kurzel - missing pathing around

Budd Nedreck https://www.wowhead.com/tbc/npc=23559/budd-nedreck  - missing pathing around

Budds bodyguard https://www.wowhead.com/tbc/npc=25145/budds-bodyguard - seem to be in wrong place vs data - maybe also path?

**Comment by miraco** [comment]
https://github.com/cmangos/tbc-db/commit/78282be9720a191ed22c80311a61248d3b7adc75

All reports from this should be fixed with last update.
