### ISSUE TITLE
[classic] Hunter Taming Attack Speeds.

### ISSUE THREAD

**Issue by scotty0100** [cmangos/issues#378]
I have raised a DB issue. But I believe taming pets currently does not give you their true attack speed based on what they have set in the DB, instead its giving a default attack speed of 2, this was not the case in Classic, it used DB values.

This was fixed in TBC, but was a 'bug' in Classic.

DB Issue I raised:
"Just got around to taming some pets which should have different attack speeds, Broken Tooth most famously which is supposed to have a 1 second, caster-killer attack speed.

However, all the pets I tamed so far, including Broken Tooth have the default 2 second attack speed. In reality, a lot of pets should have unique attack speeds. For example, Rak'shiri (rare aqua-coloured saber in Winterspring) should have a 1.5 second attack speed but he/she also has 2.0 instead.

Here's proof for Broken Tooth:

http://www.wowhead.com/npc=2850#comments:id=3315

Further proof with a comprehensive list of pets/beasts and what attack speeds they should have:

http://web.archive.org/web/20061112230516/http://tkasomething.com/attackspeeds.php

**Comment by Phatcat** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/c018db951028b9a2e45ed6f137791f836f82164c
