### ISSUE TITLE
🐛 [Bug Report] [WoTLK] Error in SD2: Loading C++ scripts

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#3781]
### Bug Details

>> Loaded 4415 Script Waypoint nodes.
SD2: Loading C++ scripts

Script registering but ScriptName npc_snowpack_target is not assigned in database. Script will not be used.

Loading spell scripts...
No script found for ScriptName 'npc_icicle_target'.

### Steps to Reproduce

1.Start server (World)
2.
3.
4.

### Core SHA1 Commit Hash

ca73e495db76c5ea291e412660489ede8be8c764

### Database SHA1 Commit Hash

d46577d2603e42290f557654497c6e9daea21b8e

### Operating System

Ubuntu 22.04.5 Server LTS

### Client Version

3.3.5a (Wrath of the Lich King)

**Comment by insunaa** [comment]
It's coming in a future commit.

**Comment by adellaci** [comment]
Thank you @insunaa
