### ISSUE TITLE
🐛 [Bug Report] 

### ISSUE THREAD

**Issue by Pip1987** [cmangos/issues#3796]
### Bug Details

Troll Rogue is unable to acquire the level 10 rogue quest [Therzok]. From my research this should quest should be accessible to orc and troll rogues. The requiredRaces flag is set to 2 (orc) when it should be set to 130 (troll or orc).

### Steps to Reproduce

1. Create a troll rogue
2. Get to level 10
3. Go to Razor Hill
4. Kaplak in the bunker should have the quest for you but does not.

### Expected behavior

Kaplak should offer both troll and orc rogues [Therzok] but does not. 

### Suggested Workaround

Change classicmangos.quest_template entry 1859 [Therzok] column RequiredRaces to 130. or run the following sql
```UPDATE `classicmangos`.`quest_template` SET `RequiredRaces` = '130' WHERE (`entry` = '1859');```

### Core SHA1 Commit Hash

0a8b156c15365c4b141f53356ead3a4663b6ef4f

### Database SHA1 Commit Hash

dbfaedf1be29fefe358f9e70f2938eb75fd8b2ba

### Operating System

Ubuntu 24.04.1

### Client Version

1.12.1 (Classic)

**Comment by al3xc1985** [comment]
check quest_template table for level requirement

and also check a valid source to see if that quest doesn't have a prequest to complete

**Comment by Grz3s** [comment]
please read comments about it in WoWHead:
https://www.wowhead.com/wotlk/quest=1859/therzok#comments

**Comment by al3xc1985** [comment]
And there is my confirmation... Ty @Grz3s

**Comment by Pip1987** [comment]
Yep further digging in my end informs me I was too hasty.

**Comment by al3xc1985** [comment]
close this bug report tpls
