### ISSUE TITLE
💬 [Support Request]I'm hoping to fix the problem I'm currently having by modifying the database

### ISSUE THREAD

**Issue by nangongzhou** [cmangos/issues#3805]
### Core Version

mangos-tbc

### Support Request Details

![Snipaste_2024-11-22_16-32-40](https://github.com/user-attachments/assets/d2831216-9064-4061-9e39-2221eca0cb49)
Thank you for the kind people who clicked in to see it

I want all my walock's pet, to have 1.5 times more attack，TO FIX THE BUG THAT APPEARS IN THE DIAGRAM

Is there somebody can tought me,Can I do this by changing the values in the data table?

I solved this problem by asking questions in the normal way, but no one was able to reproduce my problem, so I had to think of this way

### Steps to Reproduce

1.
2.
3.
4.

### Core SHA1 Commit Hash

87e8721f2af08a3376665392ed0707e47b4a86f0

### Database SHA1 Commit Hash

08ee90de86f43f82e03a1646fc3e969551c4d7d3

### Server Operating System

ubuntu-22.04.5-live-server-amd64

### Client Version

2.4.3 (The Burning Crusade)

### Client Operating System

win10 LTSC

**Comment by cpevors** [comment]
You'd want to adjust the values in the `pet_levelstats` table of the `tbcmangos` database. I don't believe you can adjust attack, as I believe the `pet_levelstats` table has hp, mana, and then primary stats. 

And then the question would be, which minion are you wanting to adjust? The Voidwalker? All Warlock minions?

If you wanted, to say, adjust the Strength value of your Voidwalker by 1.5x, you could run a simple SQL script against the `pet_levelstats` table. Something like:

```c++
UPDATE pet_levelstats
SET str = str * 1.5
WHERE creature_entry = 1860;
```

Not sure if that'll accomplish what you're after, if your primary concern is that your Voidwalker's attack is so low that it can't hold aggro, but hopefully that's enough to get you off to the races. I would encourage you to backup your database before you execute any query against a given table therein, especially if you have custom content elsewhere in your database.

If you want to adjust the value of other minions, you'd need to first find the `creature_entry` value from the `creature_template` table within the `tbcmangos` database. 

I don't personally believe that CMaNGOS is "bugged" in the way you think it is, but good luck.

**Comment by AnonXS** [comment]
classicmangos:
![grafik](https://github.com/user-attachments/assets/f7ab2006-079f-4c10-a816-a051e63ce6ae)
![grafik](https://github.com/user-attachments/assets/8fd0a51a-4cdb-4285-9e17-3786b8606285)

tbcmangos:
![grafik](https://github.com/user-attachments/assets/df172d5d-ef4b-4d0e-89b5-1008779db503)
![grafik](https://github.com/user-attachments/assets/1734d2c7-d6af-453b-af8a-cb9a6f4b1618)

maybe after levelup stats from gear dont get recalculated or something, in general i dont see anything wrong.

equpping from 60 to 61:
![grafik](https://github.com/user-attachments/assets/8cc0761a-1a03-46f1-9ede-27a07ecf40f9)
![grafik](https://github.com/user-attachments/assets/f215a851-dcbd-471e-abe7-5f2a85a9fd43)

nope seems not levelup dependend, talents maybe find out.

**Comment by nangongzhou** [comment]
> You'd want to adjust the values in the `pet_levelstats` table of the `tbcmangos` database. I don't believe you can adjust attack, as I believe the `pet_levelstats` table has hp, mana, and then primary stats.
> 
> And then the question would be, which minion are you wanting to adjust? The Voidwalker? All Warlock minions?
> 
> If you wanted, to say, adjust the Strength value of your Voidwalker by 1.5x, you could run a simple SQL script against the `pet_levelstats` table. Something like:
> 
> ```c++
> UPDATE pet_levelstats
> SET str = str * 1.5
> WHERE creature_entry = 1860;
> ```
> 
> Not sure if that'll accomplish what you're after, if your primary concern is that your Voidwalker's attack is so low that it can't hold aggro, but hopefully that's enough to get you off to the races. I would encourage you to backup your database before you execute any query against a given table therein, especially if you have custom content elsewhere in your database.
> 
> If you want to adjust the value of other minions, you'd need to first find the `creature_entry` value from the `creature_template` table within the `tbcmangos` database.
> 
> I don't personally believe that CMaNGOS is "bugged" in the way you think it is, but good luck.

thank you so much ,for Typing so many words to help me

I looked through a lot of database tables one by one, and I couldn't find any values that could adjust the attack power, so I came to ask for help

It's really a shortcut to change the damage by adjusting the strength value, I originally looked at my picture, the strength of the two pets is exactly the same, but the damage is so different, I thought the damage was controlled by a field, but I didn't find it, it seems that I was wrong. Presumably this damage is written in the source code

Thank you dude for your kind help

**Comment by nangongzhou** [comment]
> maybe after levelup stats from gear dont get recalculated or something, in general i dont see anything wrong.
> 

> nope seems not levelup dependend, talents maybe find out.

thank you

When I was doing data table research, I also found this strange problem about all warlock's pet，Felguard，Succubus,Voidwalker, there is no table that records this value, it should be defined in the source code file, and then it should be multiplied by a constant value as the new value after the upgrade
