### ISSUE TITLE
🐛 [Bug Report] Mob trigger intire massive groups on top on hellfire ramparts

### ISSUE THREAD

**Issue by SIGGISMALLZ** [cmangos/issues#3806]
### Bug Details

On Hellfire ramparts Bleeding hallow darkcaster on the bottom on the first boss triggering a massive group of enemy´s on the top floor.

![20241214_075454](https://github.com/user-attachments/assets/f59481c3-ec57-497a-97c9-a69a6c9a408f)
![WoWScrnShot_121424_235855](https://github.com/user-attachments/assets/3e387147-4110-4165-8b03-16004c35ad9a)

### Steps to Reproduce

1. combat with bleeding hallow darkcaster on the bottom on first boss
2. wait few moments 
3. massive group of mobs coming down the stairs
4.

### Expected behavior

He shouldnt trigger the massive group 

### Core SHA1 Commit Hash

574a2d65e5ad40085c03d309acdd51598e7f1bc

### Database SHA1 Commit Hash

TBC-DB 1.10.0 Return of the Vengeance

### Operating System

Win10

### Client Version

2.4.3 (The Burning Crusade)

**Comment by AnonXS** [comment]
Resolved with https://github.com/cmangos/tbc-db/commit/6d31e514de61365d42e6fb34df289e3926aee120
