### ISSUE TITLE
💬 [Support Request] WOTLK server want start

### ISSUE THREAD

**Issue by rmzVI** [cmangos/issues#3811]
### Core Version

mangos-wotlk

### Support Request Details

after pc not normal shutdown. i get errors when starts server again.. see screen
https://dropmefiles.com/8nZq2

">>> Localization strings loaded
Loading Auctions__ 
Critical Error: A condition which must never he false was found to he false. Server was shut down to protect data integrity. If this error is occurring frequently, please recompile the software in debug mode to get more details_ 
AuctionHouseMgr::AddAItem<>: mAitem.find<it—>GetGUIDLow<>> == mAitems.end<> "

how can i fix it??

### Core SHA1 Commit Hash

latest version

**Comment by insunaa** [comment]
clear the auctions table

**Comment by rmzVI** [comment]
with one?

**Comment by insunaa** [comment]
which ones are there?

**Comment by rmzVI** [comment]
db wotlkCharacters, table "auction"? this one?

it works thanks
