### ISSUE TITLE
🐛 [Bug Report] Naxx Attunement not working

### ISSUE THREAD

**Issue by Ischtaratu** [cmangos/issues#3813]
### Bug Details

None of the attune Quests for Naxx (9121 - 9123) will attune the charakter to enter naxx ... missing questflag ?

it seems the wrong quest 9378 has this trigger (thanks to Colin)

maybe same in vanilla branch ... 9378 is a WotLK Quest 

### Steps to Reproduce

1. take the quest
2. turn in
3. go to Naxx
4. you can't enter ... :(

### Core SHA1 Commit Hash

73e50e0cfe36467e4d4233718f81d4cbaadb72ee

### Database SHA1 Commit Hash

latest

### Operating System

W11 2402

### Client Version

2.4.3 (The Burning Crusade)

**Comment by cpevors** [comment]
Have confirmed. The appropriate attunement quests don’t seem to apply Arcane Cloaking (spell ID: 28006).

**Comment by cpevors** [comment]
What's weird is that the `RewSpellCast` column of the `quest_template` table for `entry=9121,9122,9123` lists `28006` for each attunement quest. When you turn in the quest, the quest giver does, in fact, appear to cast the spell on our player characters. We are not able to access the raid instance, however.

If you `.cast 28006` on your player character, you can thereafter enter the raid.

**Comment by killerwife** [comment]
Linked a commit, pls test

**Comment by cpevors** [comment]
Confirmed to be working as intended with the latest commit. Thank you!
