### ISSUE TITLE
Some Spells Can Be Cast While Facing Wrong Direction

### ISSUE THREAD

**Issue by Patman64** [cmangos/issues#384]
Spells with SPELL_RANGE_IDX_COMBAT can be cast even while facing away from the target due to mishandling in Spell::CheckRange. The function returns in the switch before the facing check is hit.

``` c++
SpellCastResult Spell::CheckRange(bool strict)
{
    Unit* target = m_targets.getUnitTarget();

    // special range cases
    switch (m_spellInfo->rangeIndex)
    {
        // ... code ...
        case SPELL_RANGE_IDX_COMBAT:
        {
            if (target)
            {
                // ... code ...
                // with additional 5 dist for non stricted case (some melee spells have delay in apply
                // RETURNS HERE, MISSING THE CHECK FOR FACING TARGET
                return m_caster->CanReachWithMeleeAttack(target, range_mod) ? SPELL_CAST_OK : SPELL_FAILED_OUT_OF_RANGE;
            }
            break;                                          // let continue in generic way for no target
        }
    }
    // ... code ...
    if (target && target != m_caster)
    {
        // ... code ...
        // THIS IS MISSED FOR SPELL_RANGE_IDX_COMBAT
        if (m_caster->GetTypeId() == TYPEID_PLAYER &&
                (sSpellMgr.GetSpellFacingFlag(m_spellInfo->Id) & SPELL_FACING_FLAG_INFRONT) && !m_caster->HasInArc(M_PI_F, target))
            return SPELL_FAILED_UNIT_NOT_INFRONT;
    }
    // ... code ...
}
```

The check for facing the target should be probably be lifted out of CheckRange into CheckCast.

**Comment by cyberium** [comment]
Interesting work for @killerwife or @Warlockbugs
Is it still needed btw?

**Comment by killerwife** [comment]
I have no idea about this.

**Comment by Ve1vet** [comment]
@cyberium @killerwife  this issue only for melee based spells, all ranged/magic spells have proper checks.
Part of this spells Killerwife fiexed in this commit https://github.com/cmangos/mangos-tbc/commit/c91fda2725bc392e1c40d486d507c74c962fc818
For Target_Chain_Damage i give him reworked function in witch this part also fixed.
Just need to get other spells that also still can be casted not in front of target. I can help fix them. I just need to know what spells need to have those checks.

**Comment by cyberium** [comment]
Ok then we can close this and if there is other spell iam sure new specific issues will be opened
