### ISSUE TITLE
[classic] Debuff & DoT Stacking / Sunder Armor Stacking

### ISSUE THREAD

**Issue by scotty0100** [cmangos/issues#388]
How to replicate the bug: get two tanks apply sunder armor

What happens: one is being overwritten, it should not be reapplied by another warrior and the original sunder stack(s) lost.

What should happen:an enemy target can have a sunder up to 5 times stacked from a tank, if another warrior uses sunder armor it either adds a stack unless its stacked up to 5 times already in that case case it will just refresh the duration on the target. This isn't happening.

Extra Information:

I believe same issue for DoTs across the board eg. Warlock's Corruption, they just overwrite each other instead of both stacking which is a pretty big issue for raiding.

**Comment by ROKB** [comment]
@cyberium it work nice but some spell's not work like Mind Flay..

**Comment by Warlockbugs** [comment]
Fixed in:
https://github.com/cmangos/mangos-tbc/commit/f14a867aa666df8869f9cf8d37ae654389d35ba9
https://github.com/cmangos/mangos-classic/commit/0206d01e4c31ae1a0795c191f60615bb25829277
