### ISSUE TITLE
Quest/Gossip item limit

### ISSUE THREAD

**Issue by stfx** [cmangos/issues#396]
Related to https://github.com/cmangos/mangos-wotlk/commit/5e15f3bd50266d6dc8db81d785197bad61cc8cb6

According to @lillecarl the quest item limit is 16 and the gossip item limit is 15 (1 button is used as a spacer) in TBC.

**Comment by cyberium** [comment]
will be closed if no one care much about this.

**Comment by jimmybrancaccio** [comment]
Closing this one out since it doesn't seem there's much interest in it. Please re-open a new case with full details if you wish to pursue this.

**Comment by Lillecarl** [comment]
@jimmybrancaccio
Is it a good idea to close issues because there's currently no interest in fixing them? It's still an issue.

**Comment by jimmybrancaccio** [comment]
@Lillecarl Closed per Cyberiums comment above. I'm all for keeping them open if it's making things more Blizzlike though.
