### ISSUE TITLE
AttackDistance and CallForAssistance (and Chasing)

### ISSUE THREAD

**Issue by Tobschinski** [cmangos/issues#400]
Greetings,

I am pretty sure this have been discussed before, but since I could not find it, I will try to start a discussion at least.

In order to design any dungeon, in any expansion correctly, it is needed to get the possibility to change creatures' AttackDistance, the range of its CallForAssistance-Shout (and maybe Chasing-distance for outdoor mobs)

As you can see and probably know already, this was done by Blizzard themselves.

![cyynlpc - copy](https://cloud.githubusercontent.com/assets/4753528/2534902/58829cdc-b584-11e3-9826-ecbe23c34ffd.png) (Thanks to Patman64 for sharing)

The currently used mechanics for AttackDistance have been developed on sources taken from wowpedia.org (the comments seem to match) and use a set value of 20 yards.

This will remove the difficulty of many encounters, as, at some, the pull is meant to be the hardest part. 

I would suggest to add these fields to `creature_template` in order to alter predefined values.

**Comment by Phatcat** [comment]
Look at that beatiful call for assistance at 0:38 here https://www.youtube.com/watch?v=fy1AsFrj4qU <- Do we do anything like that on cmangos currently (besides sm cath)?

**Comment by AnonXS** [comment]
this is ai, not base implementation like the `callforhelp` column in `creature_template` implies, should be done with linking/ai.

**Comment by Phatcat** [comment]
Oh, I see, it's scripted and not generic. Good to know. Do you know if he is currently set to do that on cmangos atm?

Would you happen to have a generic example of callforhelp from retail I can see so I can tell what it actually is then? (:

Also yeah I know about the SM one, dunno what mana-tombs is, guessing tbc or later.

**Comment by AnonXS** [comment]
I'll add it now just need to have a little more info if there is a chat text emote involved and how big the radius is and what %HP he does it. from looking at hunter taming videos it seems to be  indeed on hp threshold.

**Comment by Phatcat** [comment]
There is no emote; https://www.youtube.com/watch?v=cTcAEAsr0Bg

Watch at 7:27 ... also.. how short is the respawn rate of vanilla rares in wotlk? That seems ridiculous. (dunno if he actually waited for hours and then cut the video, but why would he, though..)

Also sorry for poluting this issue with unrelated stuff.
