### ISSUE TITLE
Some Auras Should Persist Through Evade

### ISSUE THREAD

**Issue by Tobschinski** [cmangos/issues#401]
Auras, that were set on spawn and should last forever (like stealth detection) are removed once a creature evades. 

This does not occur on retail servers. The aura should persist until the creature dies.

In order to not need to add a single spell in different phases, a change may be useful.

**Comment by killerwife** [comment]
Fixed by implementing SPELL_ATTR_SS_IGNORE_EVADE for spell_template AttributesServerside column. Has to be fixed on a case by case basis.
