### ISSUE TITLE
[CLASSIC] Priest - Mind Soothe

### ISSUE THREAD

**Issue by scotty0100** [cmangos/issues#403]
Casting Mind Soothe aggros the target regardless of if its resisted or not.

Should soothe the target, reducing it's aggro range.

**Comment by canidae** [comment]
This is still an issue. Soothe only angers mobs.

### Version & Environment
  - Client: "1.12.1" (CLASSIC)
  - Server: [CLASSIC](https://github.com/cmangos/mangos-classic/tree/3b3df96c90e06691ae6324cfb0b3341180d2e414)
  - Database: [CLASSIC](https://github.com/cmangos/classic-db/tree/e15ef1e135943f59961746cb1fbfae974e8cb16e)
  - OS: Linux Arch

**Comment by killerwife** [comment]
Solved by implementing SPELL_ATTR_EX_UNK21 as SPELL_ATTR_EX_THREAT_ONLY_ON_MISS
