### ISSUE TITLE
[classic] Shaman - Searing Totem

### ISSUE THREAD

**Issue by scotty0100** [cmangos/issues#404]
If you drop a searing totem, it attacks neutral targets. Should only attack hostile enemies.

Source:
http://www.wowwiki.com/Searing_Totem

"When dropped, the totem randomly selects an enemy within range and continuously attacks until A.) the totem expires, B.) the target leaves range or C.) the target dies. If B or C occur, the totem randomly chooses another target in range and begins attacking it. If there are no targets within range, it does nothing until an enemy comes in range. Also note that the totem only engages hostile targets on its own; it ignores neutral targets, unless you engage them first."

Can this be fixed DB side? I know some totems have been fixed like that recently - if so let me know, this one seemed more code based.

**Comment by scotty0100** [comment]
How it works as of now: 

Searing Totem will attack anything that is neutral, from critters to neutral faction NPC's marked friendly by the player. It will also attack Alliance players in their friendly territory that are not flagged for PvP.

How it should be:

Searing Totem should only attack hostile targets within range. Neutral targets are only attacked when the shaman has engaged them. Alliance players not flagged for PvP shouldn't be attacked by the totem.

**Comment by SilvioDoMine** [comment]
This is still a issue. (After 4 yerars)
