### ISSUE TITLE
[classic] Priest - Mind Flay & Warlock - Mana Drain

### ISSUE THREAD

**Issue by scotty0100** [cmangos/issues#405]
Two Shadow Priests are unable to cast this together, they interrupt each other. Possible another stacking issue REF: #388 

Proof/Source: 

https://www.youtube.com/watch?feature=player_detailpage&v=yAmXZPuS7L0#t=374

The famous 40 Priests vs Onyxia video. If you watch the two shadow priest tanks there are two continuous Mind Flay beams going at one time. (6:20 ish)

Mana Drain has the same problem

It's not all channelled spells though as Life Drain for Warlocks can both be cast together.

**Comment by ROKB** [comment]
confirm Drain Soul same problem.

**Comment by dagochen** [comment]
Arcane Missiles too....

**Comment by ROKB** [comment]
bump still bug

**Comment by dazidkk** [comment]
Any fix for this ever found?

**Comment by dagochen** [comment]
should be easy, just make channeled spells stack

**Comment by dazidkk** [comment]
How so?

**Comment by Warlockbugs** [comment]
Fixed in:
https://github.com/cmangos/mangos-tbc/commit/f14a867aa666df8869f9cf8d37ae654389d35ba9
https://github.com/cmangos/mangos-classic/commit/0206d01e4c31ae1a0795c191f60615bb25829277
