### ISSUE TITLE
[classic] Mage - Winter's Chill

### ISSUE THREAD

**Issue by scotty0100** [cmangos/issues#406]
Stacking issue very similar to: REF: #388 

If one mage with Winter's Chill gets a stack of 5 Winter's Chill, another mage that also has Winter's Chill spec could cast a Frostbolt which would then drop the stack back down to 1. The same is happening to Warrior's Sunders Armor at the moment.

They should stack together, not reset.

Proof/Souce:

https://www.youtube.com/watch?v=SOgT8go6tFA#t=114

As they are about to burn down on Onyxia, check how fast the Winter's Chills stack up. There's no way a single mage could cast that many Frostbolts in that time. (1:59 ish)

**Comment by Warlockbugs** [comment]
Fixed sometime ago.
