### ISSUE TITLE
Defender of the Timbermaw bugged

### ISSUE THREAD

**Issue by zwisus** [cmangos/issues#407]
This trinket (http://www.wowhead.com/item=21326) is rewarded from the Timbermaw faction once you reach exalted with them, and is currently not working as intended.

What it currently does:

A Timbermaw Ancestor (http://old.wowhead.com/npc=15720#comments) is spawned for 30 seconds. It acts like an aggressive combat pet and melees for about 40 damage per hit.

What it should do:

The timbermaw ancestor should have two spells, lightning bolt and healing wave. From a quote on wowhead:

-It seems to have ~500 hp
-It is level 60, but isn't very tough even versus lower level melee
-It seems to heal you ONLY if you drop below 50% HP, and this also seems to be subjective to if it's attacking something or not. You can exert some control over this by ensuring that all targets around you are CCd when you want it to heal you. As a rogue I blind, then gouge and start a bandaid while he casts a heal.
-I've seen it's heals range from 200-900 however I wasn't paying attention to mortal strike or critical heals.
-It spams a lightning bolt that is ~2 second cast time for 250 damage.
-It will not attack anything unless something attacks you while it's summoned, however it will heal if there are no enemies around and you are under ~50%
-It is obtainable for a level 49 (my 49 rogue has it, and i don't use it that often.)

The wowhead website does not list the timbermaw ancestor's spell abilities, however I doubt the commentator made up his experiences. Perhaps because the trinket is so old, wowhead doesn't have accurate data. These spells (http://old.wowhead.com/spell=23381 , http://old.wowhead.com/spell=15234 ) seem to fit the description of what the timbermaw ancestor should use.

I know that this is a very niche trinket that not many people will get, however it takes a collosal effort to reach exalted with the timbermaw faction and it's unfortunate that the trinket rewarded at the end of the grind is bugged.

**Comment by Phatcat** [comment]
I dug this for a much more horrible thing to fix: EventAI doesn't work for player summoned guardians. Don't ask me why.

Precalculated stats is taken care of, this guardian is summoned with appropriate stats (if that insanely high mana is to be considered correct)
this is sadly still a core issue, otherwise we could have closed this.

**Comment by cala** [comment]
Closed by: https://github.com/cmangos/mangos-classic/commit/e4bdd72b909066f7fc163c62439334ee96d49748 and https://github.com/ACID-Scripts/Classic/commit/6d27ef20fa3527250a204a250cc8f52e8bd3bcf9
(there similar commits for TBC and WotLK branches).
Thanks @cyberium and @Phatcat for their work on the matter.
