### ISSUE TITLE
[CLASSIC] In Some Cases the Game Gets Stuck While (Re)Loading Data

### ISSUE THREAD

**Issue by Neotmiren** [cmangos/issues#408]
In Single Player mode you can "enter" such erroneous state after logging in, after using teleport, after entering instance...

You can move but cannot cast spells, cannot logout (only Alt-F4 works), cannot run server commands from chat.

This may somehow depend on events-specific objects. For example, ".tele Stormwind" or logging in at the spot of Stormwind teleport destination gets stuck during Midsummer Fire Festival but works fine after ".event stop 1".

Also it depends on map coordinates. With the above Stormwind example the problem vanishes after you have moved a short distance to mailbox near Stormwind City Bank, pressed Alt-F4 and relogged.

The same problem appears in some areas of Ironforge during Midsummer Fire Festival. 

Right at this moment the game gets stuck every time after entering Blackrock Spire normally or after teleporting with ".go c Voone" command (to one of LBRS NPCs).

CAN anyone confirm this ISSUE?

**Comment by Neotmiren** [comment]
Classic DB has now working Midsummer event with greater number of gameobjects... And this extremely annoying Classic client  failure appeared again for those who maximize visibility range (greater ranges are really good in single player mode for several reasons)...

The cause of "false empty world" state in WoW 1.12 client lies in too big update packet size, sent from VisibleNotifier::Notify(). Now I have rewritten related code, splitted one large packet (about 100 Kbytes) into a few smaller ones, and it seems working.

Now can use 533 distance everywhere (guard at the Gates of Stormwind can be kept targeted from Goldshire, distance ~523), contrary to previously 300 on Continents and only 240 in Dungeons (client choked in Blackrock Depths, when logging in/teleporting to some central point, on the Bridge). 300/240 are not that bad, but they were very unsafe (could fail with active game events) and moreover required some other simple "crutches" in server code, like artificially reducing visibility distance for the first sending.

**Comment by cyberium** [comment]
Still replicable we have to find the cause.

**Comment by al3xc1985** [comment]
problem not replicable ... @killerwife  I believe this is fixed... I trried to replicate with no succes

**Comment by killerwife** [comment]
This should be opened again if someone actually finds a cause at least.
