### ISSUE TITLE
[classic] Feral Fearie Fire Talent

### ISSUE THREAD

**Issue by scotty0100** [cmangos/issues#412]
To replicate this bug: Spec 1 point Feral Fearie Fire Talent, go to a level 60 druid trainer and level it up. (Keep the skill window open) once training it to level 2, you will notice it disappears from your talents and resets to 0.

After this you are then unable to respec into Feral Fearie Fire Talent, and then it is also usable without having the talent at all.

**Comment by Warlockbugs** [comment]
Should be resolved in https://github.com/cmangos/mangos-classic/commit/04054c28fbd94a85f91ffe22edea3e7dd06bf988.
