### ISSUE TITLE
[CLASSIC] Intimidating Shout

### ISSUE THREAD

**Issue by scotty0100** [cmangos/issues#416]
The tooltip says:

Intimidating Shout
250 mana
10 yd range
Instant 180 sec cooldown
The warrior shouts, causing the targeted enemy to cower in fear. Up to 5 total nearby enemies will flee in fear. Lasts 8 sec.

Currently all enemies are getting feared along with the targeted enemy. Targeted enemy should cower in fear.

**Comment by BenDol** [comment]
Tested and not able to reproduce in the latest TBC core/db
