### ISSUE TITLE
4.3.4: Fix / Improved Gossip For All-Profession Trainers

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#417]
There is something new with Cata for profession trainers. There is now some single trainers that will train for ALL professions. Currently in Elwynn Forest There is one in Goldshire. It has been completely setup with all of the gossip required but we require some advanced gossip options.

I suspect we need to expand Gossip_Menu_Option for some additional Option_ID values. On official when you talk to this npc they will have a menu of all the different professions you then select one and then you will get some information about them and you cans elect to learn the profession and then come up with a trainer list for ONLY that profession. So there is some sort of Filter that will only show the desired profession skills you can learn.

http://www.wowhead.com/npc=47384

Right now how it is working is that if you select a specific profession it will open up Option_ID 16 and show you the trainer list for ALL things you can train from this NPC (So ALL of the Professions are displayed at the same time).

I am not sure how to best approach this but I think some sort of improvements to flags or something that you can specify for the gossip what profession you would like displayed for in a similar way how we handle these:

GOSSIP_OPTION_UNLEARNTALENTS    16*
GOSSIP_OPTION_UNLEARNPETTALENTS     16*
GOSSIP_OPTION_LEARNDUALSPEC     16*

SO we might want something like:

GOSSIP_OPTION_BLACKSMITH_PROFESSION  16*
GOSSIP_OPTION_SKINNING_PROFESSION  16*
GOSSIP_OPTION_MINING_PROFESSION  16*

and so on...

**Comment by Wolf-DK** [comment]
I have this issue... so *bump*

Trainer in Dusthaven (Worgen zone):
Need a DB update to actually display the things you can learn:

--Fix set trainer type flag:
update creature_template set TrainerType=2 where entry=50247;

But as pr. topic all the professions are shown in a big unsorted pile, some even have some strange conditions shown.

/Wolf :Q

**Comment by cyberium** [comment]
CMaNGOS officially stop cata development.
