### ISSUE TITLE
Damage spells cast by creatures on death, result in 0 damage

### ISSUE THREAD

**Issue by xfurry** [cmangos/issues#429]
Here is the problem:
There are many cases in which creatures on death cast spells which deal damage to the surrounding players / creatures.

However, this thing doesn't work, and it's probably recently. So I've did deep into the core systems and I found the root cause.
Let's say that we have this script: http://paste2.org/a7gd63ap
At line 66 you can see the on JustDied the creature casts a Shadow Nova damage spell.

The JustDied function is called in the core here:

```c++
void Unit::JustKilledCreature(Creature* victim, Player* responsiblePlayer)
{
    victim->m_deathState = DEAD;                            // so that isAlive, isDead return expected results in the called hooks of JustKilledCreature
                                                            // must be used only shortly before SetDeathState(JUST_DIED) and only for Creatures or Pets

    // some critters required for quests (need normal entry instead possible heroic in any cases)
    // .......... some code here.......

    // Interrupt channeling spell when a Possessed Summoned is killed
   // .......... some code here.......

    /* ******************************* Inform various hooks ************************************ */
    // Inform victim's AI
    if (victim->AI())
        victim->AI()->JustDied(this);
    // .......... more code here...........
}
```

This means that m_deathState = DEAD is set before the JustDied function is called.

However the damage calculation is done in the spell cast:

```c++
void Unit::CalculateSpellDamage(SpellNonMeleeDamage* damageInfo, int32 damage, SpellEntry const* spellInfo, WeaponAttackType attackType)
{
    SpellSchoolMask damageSchoolMask = damageInfo->schoolMask;
    Unit* pVictim = damageInfo->target;

    if (damage < 0)
        return;

    if (!this || !pVictim)
        return;
    if (!this->isAlive() || !pVictim->isAlive())
        return;

    // Check spell crit chance
    // ........... more code here...........
}
```

but at this point the creature is already dead => (!this->isAlive()) => so the damage is 0.
Because SpellNonMeleeDamage is initialized as

```c++
SpellNonMeleeDamage(Unit* _attacker, Unit* _target, uint32 _SpellID, SpellSchoolMask _schoolMask)
        : target(_target), attacker(_attacker), SpellID(_SpellID), damage(0), schoolMask(_schoolMask),
          absorb(0), resist(0), physicalLog(false), unused(false), blocked(0), HitInfo(0)
    {}
```

So the solution that I'm proposing would be this one:

```diff
@@ -1014,13 +1014,10 @@ struct PetOwnerKilledUnitHelper
     Unit* m_victim;
 };
 
 void Unit::JustKilledCreature(Creature* victim, Player* responsiblePlayer)
 {
-    victim->m_deathState = DEAD;                            // so that isAlive, isDead return expected results in the called hooks of JustKilledCreature
-                                                            // must be used only shortly before SetDeathState(JUST_DIED) and only for Creatures or Pets
-
     // some critters required for quests (need normal entry instead possible heroic in any cases)
     if (victim->GetCreatureType() == CREATURE_TYPE_CRITTER && GetTypeId() == TYPEID_PLAYER)
     {
         if (CreatureInfo const* normalInfo = ObjectMgr::GetCreatureTemplate(victim->GetEntry()))
             ((Player*)this)->KilledMonster(normalInfo, victim->GetObjectGuid());
@@ -1107,10 +1104,13 @@ void Unit::JustKilledCreature(Creature* victim, Player* responsiblePlayer)
     }
 
     bool isPet = victim->IsPet();
 
     /* ********************************* Set Death finally ************************************* */
+    victim->m_deathState = DEAD;                            // so that isAlive, isDead return expected results in the called hooks of JustKilledCreature
+                                                            // must be used only shortly before SetDeathState(JUST_DIED) and only for Creatures or Pets
+
     DEBUG_FILTER_LOG(LOG_FILTER_DAMAGE, "SET JUST_DIED");
     victim->SetDeathState(JUST_DIED);                       // if !spiritOfRedemtionTalentReady always true for unit
 
     if (isPet)
         return;                                             // Pets might have been unsummoned at this place, do not handle them further!

```

I think this will fix the issue without creating new ones.
Please let me know your thoughts.

**Comment by xfurry** [comment]
Here is a possible fix to this problem. The solution isn't very nice, but it works.
```diff
@@ -1356,11 +1356,12 @@ void Unit::CalculateSpellDamage(SpellNonMeleeDamage* damageInfo, int32 damage, S
     if (damage < 0)
         return;
 
     if (!this || !pVictim)
         return;
-    if (!this->isAlive() || !pVictim->isAlive())
+    // units which are not alive cannot deal damage except for dying creatures
+    if ((!this->isAlive() || !pVictim->isAlive()) && (this->GetTypeId() != TYPEID_UNIT && this->getDeathState() != DEAD))
         return;
 
     // Check spell crit chance
     bool crit = IsSpellCrit(pVictim, spellInfo, damageSchoolMask, attackType);
 

```

Now, obviously this needs to be tested to make sure that it doesn't break anything.

**Comment by cala** [comment]
I have some creatures on my list with spell cast on death (with and without damage) and that I will test and report back during the week. :)

**Comment by cala** [comment]
I ran a few tests on NPCs casting spell on death. I only have one issue to report :
* NPC casts spell on TARGET_T_HOSTILE doing damage/debuff/whatever: according to server log, EventAI is triggered, spell is casted but target is not aware of this (no damage/debuff received of appearing in player combat log…). I assume spell is casted without target
Here are the other cases I tested, all successfully :
* NPC casts spell on itself doing area of effect damage with or without DoT effects: OK
* NPC casts debuff on TARGET_T_ACTION_INVOKER: OK
* NPC summons NPC on death (various spell target): OK
* NPC summons GO on death: OK
* NPC casts spell on itself doing splash damage to nearby NPCs : OK

In fact, it seems that TARGET_T_HOSTILE_* are not working. I can't tell if it was working before the patch (I will report back soon on this point) and I can't tell if this is an ACID issue (it does not look it would be).

If there are some specific cases I did not test and you want me to look at, feel free to ask.

**Comment by xfurry** [comment]
@cala I think you missed the point of this patch. :smile: 
The purpose of this patch isn't to fix casting spells on death. This already works fine provided that the script has the right setup. (having CAST_TRIGGERED flag set for spells cast on death).

The purpose of this patch is to fix spells with effect SPELL_EFFECT_SCHOOL_DAMAGE that are casts on death. Currently these spells are cast but deal 0 damage. My patch is supposed to fix this. 
This is independent of the target type. Usually the spells that are cast on death have TARGET_T_SELF but it should work with any target type.

**Comment by cala** [comment]
@xfurry I understood the point of this patch, but I'm affraid my report was not clear. :wink: 

I tested if your patch fixed spells with effect SPELL_EFFECT_SCHOOL_DAMAGE that are casts on creature death. It does.
Then, I tested if other spell cast on death cases were still working like before and I found no regression. I was then asking if there were other cases you wanted me to look for possible regression.

The only issue I found is related to target type, but I think this is unrelated to your patch.I suppose that threat list for unit is probably deleted on unit death and then there is no eligible target on spell cast.

Said otherwise: your patch works and I found no (direct) issue. :+1:

**Comment by xfurry** [comment]
@cala Thanks, now your report makes sense to me.

For the failed cases, please give me some examples (eventAI ids / script names) so I can check what is the problem before pushing this to master.

**Comment by cala** [comment]
Sure. :)
This is a list of few eventAI ids where spell seems to not be cast on target (or at least not hit it):
2281601
1722902
2038701
Target in script is set to TARGET_T_HOSTILE. To be honest, I did not check that this is the proper targeting for the spells used by those scripts : I need to grab spellwork for TBC/WotLK first.

**Comment by xfurry** [comment]
poke @cala 
Please open a ticket on Acid-scripts for the broken scripts. They need to be fixed as the targets are clearly wrong.
