### ISSUE TITLE
Update on the NPC when you hover over it

### ISSUE THREAD

**Issue by virusav** [cmangos/issues#432]
After https://github.com/cmangos/issues/issues/428: "Cursor is drawn at boot NPC in the world, and when the conditions for spellclick not redrawn".

Duplicate the topic from the forum cmangos (http://cmangos.net/thread-6540.html):
cmangos_335a_12674_sd2_3021
Tested on NPC 35803.
I went into the game, standing near the NPC, direct on over and see the "sword" (NPC attack).
Quest and receive an item desired, direct on NPC, but nothing changes.

If you kill the NPC and resurrect, the cursor changes to a "gear".
Throw out an item and refuse the quest, but the cursor does not change.

05.02.2011 I wrote a patch for spell 1462, which should be transmitted flag only to caster.
I changed void Aura::HandleAuraEmpathy(bool apply, bool /\* Real */) and prescribed treatment in the Object::BuildValuesUpdate.

In the end, everything worked as it should.
With spellclick problem, so interested, because could rewrite the work Object::BuildValuesUpdate since.

At what point is a sending data to the client when the cursor on the NPC?

**Comment by virusav** [comment]
Checking relevance.

**Comment by BenDol** [comment]
@virusav how's the check going?

**Comment by virusav** [comment]
I don't have a server right now, so I can't check.

**Comment by killerwife** [comment]
Okay, this is an ongoing issue. We now have an option for rebroadcasting updateflags, specifically dynamic updateflags. This has to be done at case by case basis, there is no magical fix. The rebroadcast is doable with UF_FLAG_DYNAMIC and an example is inside HandleAuraEmpathy
