### ISSUE TITLE
Classic Druid: Talent Feline Swiftness

### ISSUE THREAD

**Issue by stormrage-project** [cmangos/issues#434]
The druid talent feline swiftness is increasing the overall speed by 30% instead of just increasing the speed in cat form.

**Comment by ROKB** [comment]
bump still bug

**Comment by robinsch** [comment]
You need to UpdateSpeed when Shapeshifting

**Comment by robinsch** [comment]
`diff --git a/src/game/Player.cpp b/src/game/Player.cpp
index 34bc1cf..760ad13 100644
--- a/src/game/Player.cpp
+++ b/src/game/Player.cpp
@@ -5622,6 +5622,8 @@ void Player::CheckAreaExploreAndOutdoor()
             SpellEntry const* spellInfo = sSpellStore.LookupEntry(itr->first);
             if (!spellInfo || !IsNeedCastSpellAtOutdoor(spellInfo) || HasAura(itr->first))
                 continue;
+            if (GetErrorAtShapeshiftedCast(spellInfo, GetShapeshiftForm()) != SPELL_CAST_OK)
+                continue;
             CastSpell(this, itr->first, true, nullptr);
         }
     }
`

**Comment by didafetz** [comment]
Thanks a lot for the fix, how can I recompile the core with the edited Player.cpp it returns an error during cmake (I use Ubuntu 14.04 LTS).
Do we need this to be fixed in the github before we can recompile?

**Comment by leewalkergm** [comment]
I have had a commit for this in a fork for a while!

I've created a pull request: https://github.com/cmangos/mangos-classic/pull/115

**Comment by kartoffelsup** [comment]
Also happens in TBC. As soon as you spend a Talent point, your movement speed increases.

**Comment by cyberium** [comment]
Should be fixed https://github.com/cmangos/mangos-tbc/pull/102
