### ISSUE TITLE
Non physical melee damage gets reduced by armor.

### ISSUE THREAD

**Issue by Tobschinski** [cmangos/issues#435]
**Non physical melee damage (elemental - fire, shadow, etc.) gets reduced by armor. That is not correct. Resistances should be needed to reduce these attacks.**

---

[Lupos](http://www.wowhead.com/npc=521/lupos) - a unique pvp pet for hunters would have been useless. It was famous for dealing true damage to high armor classes in BGs, because he was doing shadow damage.
Changed to physical damage in 1.9.

> All hunter pets will now always deal Physical damage for their base attack.

Retail - if you hop onto retail and try to kill Baron Geddon, you will find out, that even a level 90 takes full of its damage (without any resistances). It is fire damage and isn't reduced by armor.

Video - a level 60 priest was tanking Baron Geddon. If the damage wouldn't have been reduced by resistances, he would probably have died there.

http://www.youtube.com/watch?v=zdMu1cuNE7s

**Comment by Phatcat** [comment]
> Classic core, Baron Geddon hits hard enough with fiery attacks to **see the difference between having a lot and zero armor**.

-

> I agree with @Tobschinski . Runed few test and **results are the same**. When your wearing heavy armor. It feels like your in plain characters. **There is no damage reduction**.

Conflicting reports, we need to re-test this against latest master

**Comment by AnonXS** [comment]
Resolved due to reworks by @Warlockbugs
