### ISSUE TITLE
[Classic] Shaman - Flametongue Weapon

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [cmangos/issues#437]
I am using the current build as of today in the repos. Same goes for ClassicDB and SD2.

When using flametongue weapon it is supposed to cause fire damage to enemies based on the weapon's speed. This appears to happen, but instead of doing a weapon-swing, the shaman throws his or her hands out as though they're casting a shock spell. In other words, when FT procs, you get a spell-casting animation instead of a weapon-swing.

**Comment by cyberium** [comment]
i saw something related to flametong recently @killerwife or @Warlockbugs

**Comment by killerwife** [comment]
This does not occur on TBC branch, hence I cannot comment. (I did a lot of TBC playtesting)

**Comment by cyberium** [comment]
It should be fixed then
