### ISSUE TITLE
[Classic] Quest 882 reward bugged...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [cmangos/issues#438]
When you finish quest 882 you are supposed to be given a buff known as "Ishamuhale's Rage". However, it claims you will LEARN the buff (you do not) and no buff is given. This is on the current build as of today.

**Comment by cyberium** [comment]
Well, first the aura is not visible (defined by flag).
Seconth, the tooltip is incorrect (+2 stamina and it should be +2 spirit)
Finaly, the aura is correctly applyed (you could see +2 spirit in your char windows)
So its not a core issue.
