### ISSUE TITLE
[cata] FreeBSD - need 2 small patches to fix build

### ISSUE THREAD

**Issue by walker0643** [cmangos/issues#448]
The follow two patches have been floating around for a while, but have never been committed to cmangos GIT.

The first one fixes the build on FreeBSD, at least versions 8 thru 10 and probably 11:
  https://github.com/cmangos/issues/issues/72  (patch by @Morenn)

And the second fixes the build for 32-bit FreeBSDs. This one comes from Mangos but was never applied to cmangos:
  https://github.com/mangosthree/server/commit/07ce932383a1900e274d93a0ad346ef038781240

Thanks :)

**Comment by cyberium** [comment]
CMaNGOS officially stop cata development.
