### ISSUE TITLE
Seal of Command Crits Does Not Trigger Vengeance

### ISSUE THREAD

**Issue by scotty0100** [cmangos/issues#463]
The Paladin talent Vengeance which triggers on a spell, weapon or ability critical does not trigger if Seal of Command critical hits an enemy.

Tested on classic build today and broken.

**Comment by killerwife** [comment]
This is related to an attribute that I implemented recently on vengeance for this exact purpose. It also fixes shadowguard bug somewhere else on the repo in relation with blackout. I will export it after we deal with spell.dbc PR, along with about 5 more attributes I have lined up :)

**Comment by al3xc1985** [comment]
@killerwife did you do the export? Can we close it? Or close ir and  the export will come

**Comment by al3xc1985** [comment]
tested and not working...issue still persist

**Comment by killerwife** [comment]
Tested now, works.
