### ISSUE TITLE
Windfury Weapon Issues

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#467]
At the moment you don't get your two additional hits immediately after the hit that lets windfury weapon procc. Instead, the game tells you that it did procc but you get your additional hits after the next hit. P.ex. hit A + procc --> hit B + 2 addtional hits.

https://web.archive.org/web/20051226140903/http://wow.allakhazam.com/db/guides.html?guide=351 (Windfury is a speed buff. It gives you a 20% chance after every hit, that you could do two more hits instantly. In other words, like extra attacks with no delay. If you're VERY lucky, the Windfury proc-ed hits could proc it AGAIN giving you a string of several attacks. Hence why it is so coveted by Shamans and why it has everyone else screaming overpowered. )
https://www.youtube.com/watch?v=Y2QIBBKJ1CY
http://wowpedia.org/Windfury_Weapon

Content Version: Classic DB version 1.4.1 'Toward the Fiery Heart'. For CMaNGOS z2525 and Scriptdev2 z2703 (update 0786_quest_template applied to mangos db)
Creature AI: ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

**Comment by cyberium** [comment]
yeah as we improve spell system we should be able to handle that now

**Comment by killerwife** [comment]
Windfury weapon should be working fine now.
