### ISSUE TITLE
Supply Crate Stratholme

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#468]
When you open a supply crate one of the following things should happen:
- You get normal loot.
- Some rats/maggots (seems like 2-4) spawn who immediately start to attack the player.
- You get a debuff
- It's empty and just breaks into pieces.

Bug:
The crate that contains loot can be opened just like other crates . Crates without loot, spawns oder debuff activation don't do anything when you try to click on them. 

Crate: http://www.wowhead.com/object=176224
Rat: http://www.wowhead.com/npc=10441
Maggot:http://www.wowhead.com/npc=10536
Debuff: No source told me enough to find the debuff
Video: https://www.youtube.com/watch?v=opFRb4Y0WzM

**Comment by cyberium** [comment]
Should work
