### ISSUE TITLE
Magmus Blackrock Depths

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#471]
Bug: 
- There should be flames only during fighting against magmus. At the moment there are also flames before the fight.

Magmus: NPC: http://www.wowhead.com/npc=9938
Ironhand Guardian: http://www.wowhead.com/npc=8982 (produces flames)
Spell: http://www.wowhead.com/spell=15529

Videos:
https://www.youtube.com/watch?v=tK46LmHyvFM (from 3:36 on)
https://www.youtube.com/watch?v=phBzWcCPgn0  (from 0:30 on)

**Comment by cyberium** [comment]
ACID or DB stuff

**Comment by xfurry** [comment]
@TheTrueAnimal can you please open this issue to the respective section of our project?
If it's script related, then it goes to SD2 or database. I'm not sure where exactly should we assign this one.

**Comment by TheTrueAnimal** [comment]
I don't know anything about bugfixing. That's why i sometimes open things here when i'm not sure where to post it. I opened the bugreport at DB.

**Comment by Schmoozerd** [comment]
This is no problem. We know that this difficulty exists and hence we just mention it ;)

In general there are a few rules:
* If it is about crashs, spells, crazyness it ususally belongs to the core (here)
* If it is about AI behaviour it belongs to SD2/ Acid (depending on .npc aiinfo returning a scriptname respectively EventAI)
* Anything else belongs to the databases

**Comment by Ulduar** [comment]
``` Quote
If it is about AI behaviour it belongs to SD2/ Acid (depending on .npc aiinfo returning a scriptname respectively EventAI)
```
And if to add a script command in the DB, then it goes to the core, it is responsible for it. Well there EVENT_T_EVENTAI, SCRIPT_COMMAND _..., ACTION_T_CHARGE (lol example).
