### ISSUE TITLE
Apple Bob

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#477]
If you click on the gameobject nothing happens. It should give you bobbing apples.

Gameobjekt: http://www.wowhead.com/object=180523
Item: http://www.wowhead.com/item=20516
Source: http://www.wowwiki.com/Apple_Bob

**Comment by cyberium** [comment]
It should work now
(@cala?)

**Comment by linuxpng** [comment]
I just pulled and applied the latest DBs, this is still not working for me.
DB Hash:
$ git rev-parse HEAD
846bb2b754d6d91ccb968a6e156a4c9a00ccd9e0

Mangos Hash:
$ git rev-parse HEAD
fa55bf677e7df1e8af1d1218c625a530b9507687
