### ISSUE TITLE
Group Loot: Explicit passed still locked for looting after timer runs out.

### ISSUE THREAD

**Issue by RyeNCode** [cmangos/issues#479]
I've spent MANY hours on this.  I can confirm how Group Loot appears to break:
1. when someone loots a corpse that has a Roll-able item (green+ by default) The rolls will start for each player.
2. at least one person explicitly passes by pressing the X
3. at least one person passes by letting the timer expire.
4. No player chooses need/greed or DE
5. After the timer expires, the 'Everyone passed' message is sent.
6. Players who explicitly passed with the X seem to get the message that the item is still being rolled for when trying to loot the item.
7. The player(s) who let the timer run out appear to be able to loot the item normally.

As far as I can tell, the steps above work every time to reproduce this.

The server does mark the item as not blocked for pickup, but the clients seem to not care in some cases. The case when the person pressed the X is of concern today.

cmangos WOTKRevision: c1182124266ac106732770e7422fb18622f46520
Author: Xfurry <xfurry@scriptdev2.com>
Date: 9/21/2014 12:53:59 PM

using PSDB, ACID and ScriptDev2

I traced through the code, using breakpoints etc, working mostly in the group.cpp file seeing what if any events happen and the like.  I don't know enough about what the client expects for the SendLootAllPassed or why some player's clients don't seem to get the message that the loot is now OK to loot on first come, first serve. I haven't found (though not an exhaustive search) the event if any when the player tries to loot the specific item and receiving the incorrect message. I suspect this may be a client only check, and the clients that passed are stuck with a state that says the roll is still happening and for some reason not getting the update.

Thanks, hope this helps

oh: might be related to :
https://github.com/cmangos/issues/issues/240
and 
https://github.com/cmangos/issues/issues/376

**Comment by cyberium** [comment]
fixed
