### ISSUE TITLE
 Baroness Anastari - Possess

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#484]
The boss should possess a player and disappear while the player is possessed by him. The other players have to do damage to him until he's at 50% life. Than the boss appears.
Spell: http://www.wowhead.com/spell=17244
Boss: http://www.wowhead.com/npc=10436
Video: https://www.youtube.com/watch?v=wqygMyNzwe4 (from 1:05 on)
Source: http://wowpedia.org/Baroness_Anastari
http://hordeguides.de/Instanz/Classic/Boss/10436/Baroness-Anastari/index.htm (german)

At the moment we have the following bugs:
- The debuff is a buff and when you klick on it you get rid of it. It is possible that the boss does NOT appear immediately. The (de)buff can jump to another player instead of making the boss appear.
- You can't attack the possessed player. He can still behave as normal and can't attack the group. He gets a damage boost as he should.
- It can take some time until the boss appears after getting rid of it by clicking on it.

**Comment by cyberium** [comment]
Similar issue https://github.com/cmangos/issues/issues/487

**Comment by cala** [comment]
Mind control fixed by several updates recently, mainly thanks to @cyberium work (with contributions from @Warlockbugs and @killerwife if memory serves). Baroness encounter now works fine.
