### ISSUE TITLE
Jandice Barov

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#486]
When the NPCs summons its illusions you should loose your target so that you have to find her. At the moment she is still your target.

NPC: http://www.wowhead.com/npc=10503

Sources:
https://web.archive.org/web/20070817110742/http://wow.allakhazam.com/db/mob.html?wmob=11439
http://wowpedia.org/Jandice_Barov_%28original%29
http://wowdata.buffed.de/npc/Jandice-Barov-10503#comments (german)

**Comment by cyberium** [comment]
ACID or DB issue
