### ISSUE TITLE
Hunter doesn't stop autoshot

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#489]
As a hunter you can't stop shooting at an enemy. Only by turning around so that you're standing with your back to the enemy, you can stop shooting. Sometimes you still shoot at a dead target which also costs ammo.
When switching the target (both targets alive) the hunter still auto-shoots at the first target although all special abilities are used at the new target. (shoot at A and use all abilities at it --> switch to B --> all abilities work with B, autoshot has still A as target)

**Comment by cyberium** [comment]
duplicate
https://github.com/cmangos/mangos-classic/issues/217
