### ISSUE TITLE
Buffs getting removed by equal icons

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#490]
Buffs get removed by debuffs which have the same icon. Example:
If you cast Abolish disease http://db.vanillagaming.org/?spell=552 on yourself it disappears when you get Silithid Pox http://www.wowhead.com/spell=8137. The disease does not get cured. The buff just disappears.

Content Version: Classic DB version 1.4.1 'Toward the Fiery Heart'. For CMaNGOS z2525 and Scriptdev2 z2703 (update 0786_quest_template applied to mangos db)
Creature AI: ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

**Comment by Warlockbugs** [comment]
"Same icon" is no longer the case in:
https://github.com/cmangos/mangos-tbc/commit/f14a867aa666df8869f9cf8d37ae654389d35ba9
https://github.com/cmangos/mangos-classic/commit/0206d01e4c31ae1a0795c191f60615bb25829277
