### ISSUE TITLE
Super-Seller 680

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#493]
At the moment the NPC is spawned permanently. He should only be spawned when the caravan is at the southern end of its route.

NPC: http://www.wowhead.com/npc=12246
Gizelton Caravan Kodo: http://www.wowhead.com/npc=11564

**Comment by cala** [comment]
This is related to the two Gizelton Caravan escort quests and is expected to be fixed by a mix of SD2 and DB update.
Closing here. Thank you.
