### ISSUE TITLE
[Classic] Halloween Event is Semi-Working

### ISSUE THREAD

**Issue by MarcoPolo87** [cmangos/issues#496]
Content Version:   Classic DB version 1.4.1 'Toward the Fiery Heart'. For CMaNGOS z2525 and Scriptdev2 z2703  (update 0786_quest_template applied to mangos db)
Creature AI:  ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)
Mangos DB:  update z2533_sxxxx_xxxxx_01_mangos_spell_chain (applied to mangos db)
ScriptDev2 DB:  update r2703 and r23704 (applied to mangos db)

Currently Halloween is semi-working.  

Trick or Treating:  From what I tested, it seems that the player is unable to "trick or treat" with any inn keeper on the continent of Kalimdor.  "Trick or treat" works with the inn keepers on the continent of the Eastern Kingdoms.  Also, the Bat "trick" costume is a debuff then can not be "right+clicked" to remove, as it says in the tooltip.  That causes the player to be unable to do anything, or interact with anything, for one real world hour since the debuff is 60 minutes.

Bobbing for Apples:  Does not seem to work on either continent.  Not every apple bob displayed a cogwheel, when you mouse over it.  https://github.com/cmangos/issues/issues/477 is another submitted issue on the Apple Bob.

Wicker-man Event:  I see two small static wicker-men outside Brill and outside Goldshire.  I have not seen the Event spawn so far.  If anyone knows what time, time on server, that the event spawns, that would help a lot.

*edit: Updated to add in Bat Costume bug."

**Comment by cyberium** [comment]
I think all of this are almost fixed now.
@cala reopen it if iam wrong
