### ISSUE TITLE
Getting kicked off custom channels

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#502]
When you leave an area (p.ex. leaving goldshire and entering elwynn forest) you automatically also leave selfmade channels.

**Comment by jimmybrancaccio** [comment]
@TheTrueAnimal Can you confirm if this is still an issue in the latest commits? Also what version was this happening under?

**Comment by jimmybrancaccio** [comment]
Closing this issue out. If anyone is still having a problem, please open a new issue with full details.
