### ISSUE TITLE
Autohit-NPCs

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#504]
Instead of using their abilities many NPCs are just autohitting. I took a look at the database and there was no script or AI. Example: http://www.wowhead.com/npc=11883
At the moment I'm testing all NPCs which will take some time. I can sometimes open a new issue with SOME tested NPCs (without sources), open an issue with ALL tested autohit-NPCs (without sources and can take some weeks) or open issues with sources (very complicated because it's hard to find videos to analyse when they use their spells). Please tell me how you want me to post it.

Classic Mangos

**Comment by cyberium** [comment]
DB/ACID stuff, For me the best is to report them to ACID repository.
