### ISSUE TITLE
[Master] Unknown player(s)

### ISSUE THREAD

**Issue by HerrTrigger** [cmangos/issues#505]
Cmangos 12748
SD2 3054
UDB 407
Acid 18/10/14
Win7 x64 (compiled x86 release)
Playerbot (blueboy/portal)

1 'Master' client
2 'Slave' clients, each 1 bot
( http://i.imgur.com/uySqAva.jpg )

The following is a long running bug, but (my) former forum postings got lost over the years.
Started happening shortly after the switch to wotlk if I remember correctly.
Hard to reproduce though. :/

When the master client logged out upto character select screen, and logged back in, all other former party members were shown as 'unknown' for this client, on the unit frames. Mousing over unitframes or characters, displays 'unknown' aswell in the tooltip popup. 
This results in not being able to switch party leader, master loot roll etc etc.
Loot messages in chat window also show 'uknown has looted .....' for that client.
Weird thing is that under the social tab -> who -> refresh, the correct player names are still shown for that client.
The unit frames also display 4 copies of 1 char, instead of 4 individuals, with the health bar + mana/rage bar doing the same.
So 4 times cloned behaviour + cloned display on unit frames.

Doing a full restart of the master client didn't help.
Doing a full restart of the 2 slave clients made it worse, since now all clients saw eachother as 'unknown'.
A server restart resolved the issue.

Some possibly related server log msgs (I was the only one on server):
ERROR:WorldSession::HandleGroupUninviteGuidOpcode: leader Player Medivache (Guid: 421) tried to uninvite himself from the group.
ERROR:SESSION: received unexpected opcode CMSG_NAME_QUERY (0x0050) the player has not logged in yet
ERROR:SESSION: received unexpected opcode CMSG_CANCEL_TRADE (0x011C) the player has not logged in yet and not recently logout
(full server.log: http://pastebin.com/geMtygV1 )
edit: (full char.log, might help interpret server.log: http://pastebin.com/2JwJUZuD)

Note:
Imho not related to playerbot nor multiple clients on same machine:
- It appeared way before I started using playerbot already.
- And with my misses her pc being next to mine, we witnessed this aswell during play with some friends of ours. 5 players, each pc running just 1 client.

(I'll try to capture some screenshots next time, to make this wall of text a bit clearer.)

**Comment by HerrTrigger** [comment]
Hi Cyberium, 


I'm having no access to my desktop pc for a while (moving to new location), so I won't be able to test this for a while, very sorry. :( 
Thank you for taking note of the issue though. 


Kind regards, 

Christophe. 

----- Oorspronkelijk bericht -----

Van: "cyberium" <notifications@github.com> 
Aan: "cmangos/issues" <issues@noreply.github.com> 
Cc: "HerrTrigger" <trigger1979@telenet.be> 
Verzonden: Maandag 29 december 2014 18:10:41 
Onderwerp: Re: [issues] [Master] Unknown player(s) (#505) 



It would be very nice if i get feedback for that patch -> cyberium/mangos-wotlk@ 2682243 


Tell me if it work.

**Comment by cala** [comment]
I will test this soon.

**Comment by cala** [comment]
Bump for myself.

**Comment by cala** [comment]
Tested successfully. :+1:
