### ISSUE TITLE
The Spider God

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#508]
When you're on the quest you should be able to read a second page when clicking on the gameobject. A the moment there is no second page and you can't complete the quest.

Quest: http://www.wowhead.com/quest=2936
Object: http://www.wowhead.com/object=142715
http://wowpedia.org/Tablet_of_Theka

**Comment by cala** [comment]
That sounds like a DB issue more than a core one.

**Comment by TheTrueAnimal** [comment]
Classic

**Comment by cyberium** [comment]
DB issue
