### ISSUE TITLE
Onu is meditating

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#510]
The quest is made to get an item with whichone you can talk to the npc if you lost the item.  There is the blue question mark over its head and it offers you the quest but if you click on the red icon to complete the quest nothing happens and you don't get the item. You need it to start the next quest in chain.

Quest: http://www.wowhead.com/quest=961
NPC: http://www.wowhead.com/npc=3616
Item: http://aowow.wow-castle.de/?item=5251

**Comment by cyberium** [comment]
DB stuff
