### ISSUE TITLE
Hex is a buff

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#512]
The spell Hex can be removed because it's a buff instead of a debuff. 
http://www.wowhead.com/spell=16097

**Comment by cyberium** [comment]
not confirmed on WotLk

**Comment by cala** [comment]
I confirm this on Classic. I assume the flags in the Classic DBC are wrong if this does not occurs on WotLK. Question is : how to properly fix this ? There are a few other spells that are wrongly set as buff instead of debuff (or vice versa).

**Comment by cyberium** [comment]
Oh then i need to find a way to reproduce it because i cannot. Maybe its because i use french DBC?

**Comment by xfurry** [comment]
This is about positive / negative spells.
This spell should be negative, but maybe on classic it works as a positive.

Anyway our spell system may not work right in all cases, so it needs to be investigated.

**Comment by cyberium** [comment]
> This is about positive / negative spells.
This spell should be negative, but maybe on classic it works as a positive.

Ofc i think i understood that from the begining :)
So well for me as you can see in the image,
- the caster cast the spell and he is safe from it.
- enemy near of the caster are polymorphed.
- the debuff appear in debuff zone (so in negative aura normal place)
- i cant remove it my self

Is there another thing that i must test to say it is considered as a positive spell?
