### ISSUE TITLE
TBC Areatrigger Teleport

### ISSUE THREAD

**Issue by Tafuna** [cmangos/issues#513]
AreaTrigger Teleport on some Instances sice the Area improve commit broken example here on screenshot moltencore on onyxia a other instance what enter is broken you need a item to enter onyxia but wehn you have you cant enter.

http://www.imgbox.de/users/public/images/bwbrMnYfYP.jpg

**Comment by cyberium** [comment]
Try
```UPDATE areatrigger_teleport SET required_quest_done = 7848 where id = 3529;```
The quest reqierement seem bad.

**Comment by cyberium** [comment]
closing as no answer.
Note : AreaTrigger code need some improvement anyway.
