### ISSUE TITLE
[TBC] Druid Trainer's

### ISSUE THREAD

**Issue by D3thw0lf** [cmangos/issues#521]
All Druid Class Trainer's don't give the flight Form nor have the quest to learn this.

Tested on rev. 2229
with latest DB-Updates (required_s2201_12748_01_mangos_spell_template)

**Comment by evil-at-wow** [comment]
@stfx That's possible, yes. I'll test.

**Comment by cyberium** [comment]
@evil-at-wow  reopen this if its a core issue wich i doubt :)

**Comment by vovk** [comment]
@cyberium this is DB issue. I have Silvermoon DB for TBC first flight form learn every trainer. Second by quest whitch starts in Moonglade.
So author should look in his DB.
