### ISSUE TITLE
[TBC] Herbalism Bug

### ISSUE THREAD

**Issue by D3thw0lf** [cmangos/issues#522]
You can collect as much as you would but the skill don't raise up. If you start learning Herbalism you'll stay on 1 for ever and all who have already learned it and could skill stay on their level for ever. Sorry I can't describe it better. :3

Tested on rev. 2229
with latest DB-Updates (required_s2201_12748_01_mangos_spell_template)

**Comment by cyberium** [comment]
Not confirmed if you have more input on this you can answer here.

![alt text](http://i.imgur.com/iNZumXe.jpg "before pickup the plant")
![alt text](http://i.imgur.com/snM8gUK.jpg "after pickup the plant the skill growed up")
