### ISSUE TITLE
Rogue: Sap not removed through attacks

### ISSUE THREAD

**Issue by idl0r** [cmangos/issues#526]
A sap will not be removed when attacking a mob. It will be however removed properly when the time is up.

cmangos-tbc, scriptdev2, tbc-db, acid all latest as of 2014/12/05.

**Comment by killerwife** [comment]
Tested it on the latest revision, all updated, works properly now. U can close the issue.

**Comment by cyberium** [comment]
Thank you

**Comment by trimken** [comment]
UP!  **Sap Rank 3** - work perfectly!  But **rank 1 ** & **rank 2** - not removed by attacks
