### ISSUE TITLE
Hunting for Ectoplasm

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#537]
For the quest you have to place an Ectoplasmic Distiller on the ground and kill special mobs inside its radius. If they die inside this radius they drop some special items. At the moment it is not neccessary to use the Ectoplasmic Distiller. They always drop the items if you're on the quest.

Quest: http://www.wowhead.com/quest=8924
Ectoplasmic Distiller: http://www.wowhead.com/item=21946
Drops: http://www.wowhead.com/item=21937
http://www.wowhead.com/item=21936
http://www.wowhead.com/item=21935

**Comment by cyberium** [comment]
Script or DB issue

**Comment by evil-at-wow** [comment]
I can confirm the issue. And you probably need both DB and scripts: the fact that the items drop as soon as you have the quest is a DB issue. Actually making the quest work as intended probably can't be handled by the DB alone. I remember similar quests in Shadowmoon Valley (10458, 10480, 10481), and I believe these were handled by SD2.
