### ISSUE TITLE
[Classic] Paladin Tier 3 - 6 Piece Bonus - Holy Power

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#538]
As of currently it does absolutely nothing. From what I can see from my server console, the Dummy Aura nor any of the Real Auras get triggered at all.

What bonus each class should receive: http://www.wowhead.com/spell=28789#comments:id=410
Spell IDs:
28789 - Dummy Aura (T3 6P Bonus)
28793 - Spell Power Bonus
28795 - MP5 Bonus
28791 - Attack Power Bonus
28790 - Armor Bonus

Just a side idea, in vanilla shaman's are not listed in the link above since shaman's are horde only.. but it would be nice to still implement it for them for servers who which to cross faction instead of just leaving shamans out. If you choose to do so, they would probably fall under the MP5 Bonus due to itemsets being for healing in vanilla.

**Comment by Tobschinski** [comment]
is working
