### ISSUE TITLE
Too much energy when switching into cat form

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#539]
When a druid switches into cat form he instantly has 100 energy

**Comment by cala** [comment]
Energy should be zero if no talent set.
It could be more depending on points spent on some talents (or with certain items equiped).

**Comment by TheTrueAnimal** [comment]
At the moment it doesn't matter if Furor (http://db.vanillagaming.org/?spell=17061) is skilled.

**Comment by cala** [comment]
Confirm, switching to cat form (Classic) automatically grants full energy.

**Comment by cala** [comment]
As of https://github.com/cmangos/mangos-classic/commit/92fa3d947140f252ab8ff867d19cd7623174d0b4 the energy granted when switching into cat form seems ok to me: only the talent bonus are awarded.

Can you check that this is also fine for you now, please?

**Comment by cala** [comment]
Unless I missed something, this is working as it should.
I'm closing the issue. Thanks.
