### ISSUE TITLE
Talent Furor 

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#540]
You don't get any rage when you shateshift into bear form.

Spell: http://db.vanillagaming.org/?spell=17061

Classic Mangos.

**Comment by Kelzior** [comment]
Spell Furor (5/5) gives you 100% chance to gain 10 Rage when you shapeshift into Bear and Dire Bear Form or 40 Energy when you shapeshift into Cat Form.

-> Bug nr 2; You always get 100% Energy when you enter cat form. even without the talent "Furor"

**Comment by Phatcat** [comment]
This issue can be closed, just tested it on cmangos classic and you do get rage from talent Furor, also when you shift into cat form you don't start with 100 energy, you start with 0 without the talent and 40 with the talent, so everything reported here has been resolved.

**Comment by AnonXS** [comment]
thanks!
