### ISSUE TITLE
Diremaul North Halls of Destruction missing NPCs

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#541]
Gordok Reavers are missing in the Halls of Destruction in Diremaul North.

https://www.youtube.com/watch?v=d8vflNfYe_g  (1:20)
http://www.wowhead.com/npc=11450

**Comment by Tobschinski** [comment]
https://github.com/classicdb/database/issues/690

**Comment by cala** [comment]
This is a database issue. Closing here. Thank you.
