### ISSUE TITLE
General Drakkisath - Conflagration

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#543]
The NPC should be able use Conflagration on the tank. At the moment it seems like the tank never gets target of this spell.

NPC: http://www.wowhead.com/npc=10363
Spell: http://www.wowhead.com/spell=16805
https://www.youtube.com/watch?v=ZZ2XcEVjx68
https://www.youtube.com/watch?v=y4SQ-Y8i7YQ
http://www.wowwiki.com/General_Drakkisath

**Comment by Schmoozerd** [comment]
This would be an eventAI issue.

('1036304','10363','0','0','100','3','15000','15000','18000','18000','11','16805','5','0','0','0','0','0','0','0','0','0','General Drakkisath - Cast Conflagration'),

> 5    TARGET_T_HOSTILE_RANDOM_NOT_TOP    Any Random Target Except Top Threat

So correct: This spell currently does not target the tank.

The target-type should be set to 4 there.
Poke @ACID-Scripts/WOTLK about this.

**Comment by cyberium** [comment]
poke @cala or @x-savior

**Comment by TheTrueAnimal** [comment]
@cala I shall poke you.

I found out, that Conflagration ALWAYS goes on the tank.

"Drakkisath's Conflagration attack will cause the victim to become confused and run about in circles all the while dealing AE damage to nearby party members. This last 6 seconds and deals roughly 3,000 damage to the target. While this effect is in place, the General will turn on the next player highest on his hate list. If two tanks are utilized, there is less of a chance that the General will chase after a priest or mage, or similar class who will fold under his attack. Once the conflagration effect wears off the main tank, they can go back to work gaining aggro and trying to attain second place on the General's hate list as he most likely will conflagrate the second tank. The tanks can trade off aggro in this fashion while the rest of the party whittles the General down. Because of the AOE effect of the Conflagration attack and the General's breath weapon, it's important for the tank to turn the General away from the rest of the party and to maintain some distance from them as well."  "When kiting drakk stay as far as him as possible, if you get within 30 yards you will get Conflagurated and probably die"(wowhead)
https://web.archive.org/web/20070702055202/http://www.thottbot.com/c10363 (several comments show that conflagration is a problem for the person pulling the general away)
