### ISSUE TITLE
The Beast Spells

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#548]
The Beast in UBRS seems to have problems with its spells. We were there with two chars (gms) and pulled the boss several times. 
- it never used its charge
- it had a really HUGE hitbox
- at the first pull, it didn't use its flamebreak (i did not record this try)
- then it didn't use its immolate.

I recorded our test when i found out, that the boss doesn't use its spells as it should.
https://www.youtube.com/watch?v=lQOXv5UYAOw&feature=youtu.be

The Beast: http://www.wowhead.com/npc=10430
https://www.youtube.com/watch?v=ohu6unEXygA
https://www.youtube.com/watch?v=8Eu0myyS6Ms
https://www.youtube.com/watch?v=gyE877c3CN8

**Comment by cyberium** [comment]
SD2/ACID?

**Comment by xfurry** [comment]
Let's discuss this here: https://github.com/ACID-Scripts/Classic/pull/15

**Comment by TheTrueAnimal** [comment]
@xfurry: This discussion approached the spawn of Finkle Einhorn, but not the bug that the Beast sometimes doesn't use its spells.

**Comment by xfurry** [comment]
I think it does use the spells. Maybe check in https://github.com/ACID-Scripts/Classic if it has all the spells, but as far as I remember it does.

**Comment by TheTrueAnimal** [comment]
It does not use its charge (I didn't find out which spell-id it is) and as you can see in my video it sometimes misses a spell duing the whole fight.
