### ISSUE TITLE
[Classic] Dark Moon Faire Cannon Faulty.

### ISSUE THREAD

**Issue by raymerjacque** [cmangos/issues#552]
The DarkMoon faire Event, the cannon is meant to shoot you up into the air and you glide back down to the ground after you click on it.  It is not working, instead when you click on it you turn into a demon for a few seconds... you never leave the ground.

**Comment by Patman64** [comment]
Hi. Thanks for the bug report, but this board is for cmangos core issues only. Please post future classic content issues [here](https://github.com/classicdb/database/issues).
