### ISSUE TITLE
[Classic] DeadMines

### ISSUE THREAD

**Issue by raymerjacque** [cmangos/issues#554]
at the last boss in deadmines, the captain that walks around the cabin is not scripted correctly, the 2 mobs standing outside are meant to walk with him, they are meant to walk all three in a group around that cabin.  

At the gobline boiler room, where the big pot of molten gold is, there is 3 mobs that patrol that area, they are also not scripted properly, only 2 patrol together, the 3rd is completely out of sync and comes walking Way after and only covers half the distance of the other 2

**Comment by Patman64** [comment]
[Closed for this reason.](https://github.com/cmangos/issues/issues/553#issuecomment-70026351)
