### ISSUE TITLE
[Classic] Sunken Temple not scripted

### ISSUE THREAD

**Issue by raymerjacque** [cmangos/issues#555]
Sunken Temple is unscripted, there is not a single spawn that moves in the temple. no patrols or anything.

**Comment by Patman64** [comment]
[Closed for this reason.](https://github.com/cmangos/issues/issues/553#issuecomment-70026351)

**Comment by cala** [comment]
@raymerjacque Could you report in https://github.com/classicdb/database/issues ?
Please, open 1 issue per error (NPCs missing, NPCs not moving, quest broken, object at the wrong place and so on...) and describe things as accurately as possible (NPC name should move from here to there and do such emote).
I'm willing to improve this instance, but with only
>  there is not a single spawn that moves in the temple. no patrols or anything

It will be difficult to know where to start and what to do.
