### ISSUE TITLE
Dire Maul North Buffs given by Guards

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#557]
When all guards are friendly they should give you buffs. At the moment you can't interact with them.

http://wow.gamepedia.com/Guard_Slip%27kik
http://wow.gamepedia.com/Fengus
http://wow.gamepedia.com/Guard_Mol%27dar
http://wow.gamepedia.com/Dire_Maul_tribute_run

**Comment by cyberium** [comment]
@cala and @Grz3s for me its DB issue, if not please reopen the issue.

**Comment by cala** [comment]
DB stuff and part of it is fixed or in the way of being fixed (pending WotLK SD2/UDB backport).
