### ISSUE TITLE
Crash Client on Enter Shattered Halls instance.

### ISSUE THREAD

**Issue by Ulduar** [cmangos/issues#558]
Version-Cata 4.3.4 - i don't know, how to add a label.
http://www.wowhead.com/zone=3714/the-shattered-halls
I go into the dungeon, held for 3 seconds and the client is frozen, no logs does not.
The problem of the year.

**Comment by Metalica** [comment]
Post back trace logs. As i did one or two post's bellow.

**Comment by Schmoozerd** [comment]
If the client freezes there exists nothing like backtrace logs unfortunately.
Usually these things happen if some bad data is sent from the server (in the past we had such issues for example with stunned mobs that were sending movement packages)

**Comment by Metalica** [comment]
@Schmoozerd 

 What about client error logs ? Would there almost not help ? (i seriusly doubt it).

**Comment by Schmoozerd** [comment]
maybe they would yes, but as we do not have the client's sources they are very hard to make use of.

The cases so far i had to track down these client-freezes i went by logging all sent information and readding npcs one-by-one to the map until i got the one creating the problems and then tracking down which properties caused the issues...

**Comment by evil-at-wow** [comment]
[offtopic]
> I don't know, how to add a label.

You probably don't see the edit buttons. [The guides](https://guides.github.com/features/issues/#filtering) say you only see them when you have permission to edit the issue.

**Comment by Patman64** [comment]
Maybe related? https://github.com/cmangos/issues/issues/235

**Comment by Ulduar** [comment]
Seems to me that nothing to do with the kernel can in the database flags or aura addons spoil the whole thing.
