### ISSUE TITLE
Warpwood Pod

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#559]
When you get near the GOB or open it one of the following things should happen:
- 5-6 NPCs should spawn  http://www.wowhead.com/npc=13022
- you get poisoned with naturedamage (i didn't find the spell)
- dropps 5-10 http://www.wowhead.com/item=18255 and/or 1 http://www.wowhead.com/item=18297
- casts  http://www.wowhead.com/spell=339
- doesn't do anything

GOB: http://www.wowhead.com/object=179526
http://wowdata.buffed.de/object/Wucherborkenkapsel-179526
http://www.wowwiki.com/Warpwood_Pod

**Comment by cyberium** [comment]
Probably DB too

**Comment by xfurry** [comment]
Yes, poke @cala  and @grz3s and assign this to DB team.
