### ISSUE TITLE
Portals of the Legion

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#560]
You should use an item at the portals. They begin to glow as they should after the cast has completed but the NPC doesn't spawn. Because of this you can't complete the killquest. Thereafter the portals should despawn but they don't.

Quest: http://www.wowhead.com/quest=5581
Item: http://www.wowhead.com/item=14547
Portals: http://db.vanillagaming.org/?item=14547#unlocks
NPC: http://www.wowhead.com/npc=11937
Video: https://www.youtube.com/watch?v=IYmLOBbDVTE
https://www.youtube.com/watch?v=KAAajp3z_us

**Comment by cyberium** [comment]
DB issue?

**Comment by xfurry** [comment]
poke @cala and @grz3s and assign it to DBscripts.
