### ISSUE TITLE
Need ACTION_T_ATTACK_START And DamageTaker(pDealer)

### ISSUE THREAD

**Issue by Ulduar** [cmangos/issues#561]
Cata 4.3.4.
Example - http://www.wowhead.com/npc=49869/stormwind-infantry
1)Should attack start http://www.wowhead.com/npc=49871/blackrock-worg
Waypoints they do not. Db_script_on_creature_movement will not help here, although as a hack to come down.
2)What is most interesting - health have not deducted when reaching a certain percentage. And worgs too. But if Worg takes damage from a player, the damage absorb effects are removed and it can kill. Stormwind infantry can not do this.
Solution:
Add ACTION_T_ATTACK_START(pTypeID, pfloatradius, pCreature(if TYPEID=UNIT)
Add EVENT_T_DAMAGE_TAKEN(pDealer = TYPEID(case PLAYER and cast UNIT)

Hacking solution - at the moment is for AttackStart. Give a link, it will be clear.
https://github.com/mangosthree/database/pull/15/files
For DamageTaken - there is no even the hacks solutions unfortunately
Only Cata. There are many NPC.

**Comment by xfurry** [comment]
You have SCRIPT_COMMAND_ATTACK so you can use that.
In eventAI that doesn't make too much sense, because you don't always have a 3rd party source that triggers the event. Moreover the attack should start because of faction & unit flags. There are very few cases where you need to enforce the attack.

**Comment by Ulduar** [comment]
``` quote
You have SCRIPT_COMMAND_ATTACK so you can use that.
```
Aarghhhh. And how does this help me if they do not have waypoints? Hack or something?
``` quote
In eventAI that doesn't make too much sense, because you don't always have a 3rd party source that triggers the event. Moreover the attack should start because of faction & unit flags. There are very few cases where you need to enforce the attack.
```
Did you look in the database (YTDB 4.3.4 or UDB 4.3.4) - and you will see that Worgs have a neutral faction, and rightly so. No scripts, it does not change.
``` quote
There are very few cases where you need to enforce the attack.
```
So what? This means it is not necessary to implement this?

**Comment by Ulduar** [comment]
@Schmoozerd, @X-Savior, @NeatElves - I need your help! Help please, convince him. Adding creature_movement essentially has no points, only to use SCRIPT_COMMAND_ATTACK_START - this is a hack and you want to add this feature in EventAI. And EVENT_T_DAMAGE_TAKEN also needed. For this offlike.

**Comment by Ulduar** [comment]
@xfurry I hack or something? Issue close?
``` Quote
You have SCRIPT_COMMAND_ATTACK so you can use that.
```
You understand that this is a hack?
Stormwind Infantry Do not has waypoint and a timer out of combat attack worgs.

**Comment by cyberium** [comment]
So, can we close this?

**Comment by Ulduar** [comment]
``` QUOTE
So, can we close this?
```
@Cyberium, The issue is not resolved. So that please do not yet closed.

**Comment by xfurry** [comment]
@Ulduar are you 100% sure that this is not a DB issue?
Maybe try to test the Stormwind infantry part using this db: https://github.com/UDB-434/Database

**Comment by Ulduar** [comment]
``` QUOTE
Maybe try to test the Stormwind infantry part using this db: https://github.com/UDB-434/Database
```
About Attack Start - yes. Or that they are in SD2 script writing? And worg and infantry?

**Comment by Ulduar** [comment]
So what? Which is the solution?
``` QUOTE
You have SCRIPT_COMMAND_ATTACK so you can use that.
```
Write each waypoint NPC - What do you mean kidding.

**Comment by Ulduar** [comment]
``` QUOTE
Maybe try to test the Stormwind infantry part using this db: https://github.com/UDB-434/Database
```
Would read to the end.
40 rows in the database, or 1 line in EAI.
