### ISSUE TITLE
 [WOTLK] SPELL_EFFECT_INEBRIATE

### ISSUE THREAD

**Issue by virusav** [cmangos/issues#562]
http://cmangos.net/thread-6858.html
When a player uses a weak alcoholic beverage, the inventory must enter an item (empty bottle).

Patch:
```DIFF
diff --git a/src/game/SpellEffects.cpp b/src/game/SpellEffects.cpp

index f7cd73b..15d7b1d 100644
--- a/src/game/SpellEffects.cpp
+++ b/src/game/SpellEffects.cpp
@@ -10045,6 +10045,10 @@ void Spell::EffectInebriate(SpellEffectIndex /*eff_idx*/)
     }
 
     player->SetDrunkValue(drunkValue, m_CastItem ? m_CastItem->GetEntry() : 0);
+
+    // create empty brew bottle
+    if (m_spellInfo->SpellIconID == 1306 && m_spellInfo->SpellVisual[0] == 11359)
+        player->CastSpell(player, 51655, true);         // BOTM - Create Empty Brew Bottle
 }
 
 void Spell::EffectFeedPet(SpellEffectIndex eff_idx) 

```

1. What should happen if a player has a full inventory?
2. I wrote a patch for the spell, on which there was information. Does anyone have any information on other spell with a similar action?

**Comment by cyberium** [comment]
If i understaind correctly, for some drink, when they are used an empty bottle should be added to inventory.
I remember that, but cannot rember where i saw that.
Anyway, for your first question i think if drink are not stackable it will be deleted then you at least have one place for it on your inventory. If its stackable then you'll get a message as your inventory is full and will loose that bottle.

**Comment by VladimirMangos** [comment]
I think linked spells already have more appropriate place in spell cast code instead effect code.

**Comment by virusav** [comment]
At some functions are better to place the code?

**Comment by VladimirMangos** [comment]
In Spell::cast as other linked spells maybe?

**Comment by virusav** [comment]
You said that it is necessary to place the code in place of other losses and ask me where? )

**Comment by xfurry** [comment]
@virusav let me know if this patch works fine:

```diff
@@ -3156,10 +3156,13 @@ void Spell::cast(bool skipCheck)
             else if (m_spellInfo->Id == 20594)
                 AddTriggeredSpell(65116);                   // Stoneskin - armor 10% for 8 sec
             // Chaos Bane strength buff
             else if (m_spellInfo->Id == 71904)
                 AddTriggeredSpell(73422);
+            // Weak Alcohol
+            else if (m_spellInfo->SpellIconID == 1306 && m_spellInfo->SpellVisual[0] == 11359)
+                AddTriggeredSpell(51655);                   // BOTM - Create Empty Brew Bottle
             break;
         }
         case SPELLFAMILY_MAGE:
         {
             // Ice Block

```

**Comment by virusav** [comment]
xfurry, at your option while casting spells 42254 and 42261 there is no trigger spell casting.
In my version castes work.

To get the message that there is no room in your inventory, you have to change the caste:
player-> CastSpell (player, 51655, false);
but in this case we get a message is "Interrupted" (for example, cast spells 42256), although the bottle is created.

**Comment by VladimirMangos** [comment]
> You said that it is necessary to place the code in place of other losses and ask me where? )
I select setence in question form just because I am not in position now do strong recomendations.
Too many time from active development pass for me...

**Comment by virusav** [comment]
xfurry, what else you need from me information or tests?

**Comment by cyberium** [comment]
this seem work.
```diff
@@ -3156,10 +3156,13 @@ void Spell::cast(bool skipCheck)
             else if (m_spellInfo->Id == 20594)
                 AddTriggeredSpell(65116);                   // Stoneskin - armor 10% for 8 sec
             // Chaos Bane strength buff
             else if (m_spellInfo->Id == 71904)
                 AddTriggeredSpell(73422);
+            // Weak Alcohol
+            else if (m_spellInfo->SpellIconID == 1306 && m_spellInfo->SpellVisual[0] == 11359)
+                AddPrecastSpell(51655);                     // BOTM - Create Empty Brew Bottle
             break;
         }
         case SPELLFAMILY_MAGE:
         {
             // Ice Block

```
note:
- no message if your bag is full (well i am sure its not needed in this case)
- interrupted message is shown, this is due to fear, Fear (here spell 49750) will fire a StopCast() and as precedent cast (42254) is not finished its interrupted. Not sure how to fix this in best way.
- an error is also fired in log concerning invalid mover. Its another issue related to Fear code poke @Schmoozerd about this check -> https://github.com/cmangos/mangos-wotlk/blob/master/src/game/MovementHandler.cpp#L397

log of this spell
```
Sending SMSG_SPELL_GO id=42254
Spell 51655 Effect0 : 24 Targets: Player Teba (Guid: 8), -, -
STORAGE: CanStoreItem bag = 0, slot = 255, item = 38626, count = 1
STORAGE: StoreItem bag = 255, slot = 35, item = 38626, count = 1
UpdateCraftSkill spellid 51655
Spell 42254 Effect0 : 100 Targets: Player Teba (Guid: 8), -, -
Spell 42254 Effect1 : 64 Targets: Player Teba (Guid: 8), -, -
Sending SMSG_SPELL_GO id=49750
Spell 49750 Effect0 : 64 Targets: Player Teba (Guid: 8), -, -
Spell 50095 Effect0 : 6 Targets: Player Teba (Guid: 8), -, -
Spell: Aura is: 26
Aura: construct Spellid : 50095, Aura : 26 Target : 1 Damage : 1
Holder of spell 50095 now is in use
Spell 49750 Effect1 : 28 Targets: Player Teba (Guid: 8), -, -

Creature 151147 used AI is AggressorAI.
Creature (Entry: 27866 Guid: 151147) enters grid[37,43]
Creature 151148 used AI is AggressorAI.
Creature (Entry: 27866 Guid: 151148) enters grid[37,43]
Creature 151149 used AI is AggressorAI.
Creature (Entry: 27866 Guid: 151149) enters grid[37,43]
Creature 151150 used AI is AggressorAI.
Creature (Entry: 27866 Guid: 151150) enters grid[37,43]

Spell 49750 Effect2 : 6 Targets: Player Teba (Guid: 8), -, -
Spell: Aura is: 7
Aura: construct Spellid : 49750, Aura : 7 Target : 1 Damage : 1

Player Teba (Guid: 8) flee from Player Teba (Guid: 8)
Holder of spell 49750 now is in use

WORLD: Received opcode CMSG_MOVE_NOT_ACTIVE_MOVER
STORAGE_SIZE: 32
01 08 00 08 00 00 00 00 | B9 CF 8D 05 00 C0 33 45
CD F4 BA 45 B2 83 5A 40 | A4 19 1D 40 D3 00 00 00
HandleMoveNotActiveMover: incorrect mover guid: mover is Player Teba (Guid: 8) and should be Player Teba (Guid: 8) inste
ad of Player Teba (Guid: 8)

Aura 7 now is remove mode 7
Aura 26 now is remove mode 7
```

**Comment by virusav** [comment]
Spell 42254:
Effect 0: Id 100 (SPELL_EFFECT_INEBRIATE)
BasePoints = 5
Targets (1, 0) (TARGET_SELF, NO_TARGET)

Maybe castes to be processed on the effects rather than the whole?

There are 3 options (for example, to spell with 3 effects, where the effect of the number 2 should not work):
1. Cast spell is interrupted if at least one of the effects is not activated (the effects of 1, 2 and 3 did not work).
2. Cast spell is interrupted for an effect that does not work, and the effects that follow them (the effects of 2 and 3 did not work).
3. Cast spells never interrupted, but can not operate all the effects (effect 2 did not work).

Had already had problems with spells in which inflicts damage to multiple species and the target was immune to only one of them.

If the problem is in the spell system, let the code will be void Spell::cast (bool skipCheck), if there is more necessary.
I was guided by the fact that the effect was always fire for processed patch spells.

**Comment by virusav** [comment]
https://github.com/cmangos/issues/issues/562#issuecomment-71360870
