### ISSUE TITLE
Need Expands from SCRIPT_COMMAND_DESPAWN_SELF

### ISSUE THREAD

**Issue by Ulduar** [cmangos/issues#564]
Add addition flags For example there are NPC Well Sanity. Four of them. After Yogg Saron defeated, they also have to go into despawned. They have the same entry. I predlayua add something like this to more effectively you can use the buddy system.
Example
``` CPP
// despawn all marksmen
        std::list<Creature*> lMarksmenInRange;
        GetCreatureListWithEntryInGrid(lMarksmenInRange, m_creature, NPC_THERAMORE_MARKSMAN, 100.0f);

        for (std::list<Creature*>::const_iterator itr = lMarksmenInRange.begin(); itr != lMarksmenInRange.end(); ++itr)
            (*itr)->ForcedDespawn(30000);
```
Send to despawned entire sheet these creatures within 200 meters say.

**Comment by xfurry** [comment]
Creature linking? Won't that work for this case?

**Comment by Ulduar** [comment]
Whom you will appoint a master then? Yogg-Saron? Disappears, he summons in phase 2 combat.
Sara? Also eliminates it as the voice of Yogg-Saron despawn in phase 3. Freya? She even do not have a script.
Therefore, I ask again - who will you assign a master?
You wrote this script(thanks for working), and you also are asking me this question - strange.

**Comment by xfurry** [comment]
This will solve your problem:

```sql
-- Ulduar - despawn Sanity Well on wipe / complete
DELETE FROM creature_linking_template WHERE entry=33991;
INSERT INTO creature_linking_template VALUES
(33991,603,33280,8192,0);
```

**Comment by Ulduar** [comment]
This idea was ruined in the bud(
The truth is not the only example.

**Comment by xfurry** [comment]
Well, for your example, this is the simplest way to fix it. :smile: 

What other examples can you provide?

**Comment by Ulduar** [comment]
Ragnaros in Firelands, there is a lot of servants who despawned for various conditions (although you again say that can enable SD2.)
Cho'gall in Twilight Bastion.

**Comment by Ulduar** [comment]
Another example - M'uru and Entropius encounter.
If M'uru evade - berserker rage, void sentinel and berserker mage should force despawn. Yes, this is done through creature_linking_template, but there is one thing.
If M'uru translate into a second phase (Phase Entropius) - without killing the adds and kill Entropius - they all go to the same despawned, now you understand why I needed this expands?
I beg reopened issue.

**Comment by xfurry** [comment]
> If M'uru translate into a second phase (Phase Entropius) - without killing the adds and kill Entropius - they all go to the same despawned, now you understand why I needed this expands?

I don't understand what are you trying to say.... Please be more explicit.

**Comment by Ulduar** [comment]
``` CPP 
I don't understand what are you trying to say.... Please be more explicit.
```
If Mu'ru Evade - Humanoids and Void Sentinel should despawn(complete in creature_linking_template)
else if Entropius die - Humanoids and Void Sentinel also should despawn(if Humanoids and Sentinel alive) - handled missing.
Than blizzlike.
Need expands SCRIPT_COMMAND_FORCE_DESPAWN and i add despawn adds after Entropius death with help db_script_on_creature_death.

**Comment by Schmoozerd** [comment]
Why not simply add
 FLAG_DESPAWN_ON_DEATH = 0x0010,
to these?

**Comment by Ulduar** [comment]
``` QUOTE
Why not simply add
FLAG_DESPAWN_ON_DEATH = 0x0010,
to these?
```
You understand that these are two different boss? And that slave can not have two masters at the same time.

**Comment by xfurry** [comment]
I will check this later and see what is the best action plan.

**Comment by Schmoozerd** [comment]
hmm, indeed, this makes things more complicated.

**Comment by Ulduar** [comment]
SD2 solutuon(maybe hack, maybe not, maybe wrong code)
https://github.com/scriptdev2/scriptdev2-cata/pull/16
