### ISSUE TITLE
[WOTLK] Server crash by using .lookup and .send from client

### ISSUE THREAD

**Issue by MasterHal** [cmangos/issues#566]
Server crashes when use following command from wow-client:
.send
.lookup npc

Crashlog:

Revision: 2015-01-10 23:30:48 12814 f1d83628b97e5e5efe62bde00fff12d3267c1e0d
Date 24:1:2015. Time 14:31 
//=====================================================
*** Hardware ***
Processor: Intel(R) Pentium(R) D CPU 3.00GHz
Number Of Processors: 2
Physical Memory: 4192728 KB (Available: 2457724 KB)
Commit Charge Limit: 4194303 KB

*** Operation System ***
Windows Server 2008 R2 Service Pack 1 (Version 6.1, Build 7601)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  74DAD0AC 01:0007C0AC C:\Windows\system32\MSVCR100.dll

Registers:
EAX:2876E52D
EBX:FFF97DDD
ECX:7FFFFFFE
EDX:0891E373
ESI:00000000
EDI:2876E52D
CS:EIP:0023:74DAD0AC
SS:ESP:002B:0891E0D8  EBP:0891E364
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010202

Call stack:
Address   Frame     Function      SourceFile
74DAD0AC  00000000  _vcwprintf_s+19A0
74D97462  00000000  _vsnprintf_l+83
74D974A3  00000000  _vsnprintf+18
005129FA  00000000  ?PSendSysMessage@ChatHandler@@QAAXHZZ+3A
0052402C  00000000  ?ShowHelpForSubCommands@ChatHandler@@IAE_NPAVChatCommand@@PBD@Z+10C
00524161  00000000  ?ShowHelpForCommand@ChatHandler@@IAE_NPAVChatCommand@@PBD@Z+E1
00524351  00000000  ?ExecuteCommand@ChatHandler@@IAEXPBD@Z+B1
0052455E  00000000  ?ParseCommands@ChatHandler@@QAE_NPBD@Z+11E
00884FB4  00000000  ?HandleMessagechatOpcode@WorldSession@@QAEXAAVWorldPacket@@@Z+2B4
0060EEE1  00000000  ?ExecuteOpcode@WorldSession@@AAEXABUOpcodeHandler@@PAVWorldPacket@@@Z+21
006111AE  00000000  ?Update@WorldSession@@QAE_NAAVPacketFilter@@@Z+CE
00487684  00000000  ?SetVisibleAura@SpellAuraHolder@@QAEX_N@Z+4E44
00489634  00000000  ?SetVisibleAura@SpellAuraHolder@@QAEX_N@Z+6DF4
00455092  00000000  ??4BarGoLink@@QAEAAV0@ABV0@@Z+4D22
70DE7064  00000000  ?invoke@ACE_OS_Thread_Adapter@@UAEKXZ+74
74D8C556  00000000  _endthreadex+3A
74D8C600  00000000  _endthreadex+E4
75B3338A  00000000  BaseThreadInitThunk+12
77A19F72  00000000  RtlInitializeExceptionChain+63
77A19F45  00000000  RtlInitializeExceptionChain+36

------------------------------------

Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
74DAD0AC  00000000  _vcwprintf_s+19A0

74D97462  00000000  _vsnprintf_l+83

74D974A3  00000000  _vsnprintf+18

005129FA  00000000  ?PSendSysMessage@ChatHandler@@QAAXHZZ+3A

0052402C  00000000  ?ShowHelpForSubCommands@ChatHandler@@IAE_NPAVChatCommand@@PBD@Z+10C

00524161  00000000  ?ShowHelpForCommand@ChatHandler@@IAE_NPAVChatCommand@@PBD@Z+E1

00524351  00000000  ?ExecuteCommand@ChatHandler@@IAEXPBD@Z+B1

0052455E  00000000  ?ParseCommands@ChatHandler@@QAE_NPBD@Z+11E

00884FB4  00000000  ?HandleMessagechatOpcode@WorldSession@@QAEXAAVWorldPacket@@@Z+2B4

0060EEE1  00000000  ?ExecuteOpcode@WorldSession@@AAEXABUOpcodeHandler@@PAVWorldPacket@@@Z+21

006111AE  00000000  ?Update@WorldSession@@QAE_NAAVPacketFilter@@@Z+CE

00487684  00000000  ?SetVisibleAura@SpellAuraHolder@@QAEX_N@Z+4E44

00489634  00000000  ?SetVisibleAura@SpellAuraHolder@@QAEX_N@Z+6DF4

00455092  00000000  ??4BarGoLink@@QAEAAV0@ABV0@@Z+4D22

70DE7064  00000000  ?invoke@ACE_OS_Thread_Adapter@@UAEKXZ+74

74D8C556  00000000  _endthreadex+3A

74D8C600  00000000  _endthreadex+E4

75B3338A  00000000  BaseThreadInitThunk+12

77A19F72  00000000  RtlInitializeExceptionChain+63

77A19F45  00000000  RtlInitializeExceptionChain+36

========================
Global Variables
	 <user defined> '_wctype'
	 <user defined> 'memcpy'
	 <user defined> 'memchr'
	 <user defined> '_memccpy'
	 <user defined> 'memmove'
	 <user defined> 'memset'
	 <user defined> 'strcpy'
	 <user defined> 'strcat'
	 <user defined> 'strcmp'
	 <user defined> 'strcspn'
	 <user defined> 'strlen'
	 <user defined> 'strncat'
	 <user defined> 'strncpy'
	 <user defined> '_strnset'
	 <user defined> 'strpbrk'
	 <user defined> 'strrchr'
	 <user defined> '_strrev'
	 <user defined> '_strset'
	 <user defined> 'strspn'
	 <user defined> '_EH_prolog'
	 <user defined> '_NLG_Return'
	 <user defined> '_inp'
	 <user defined> '_inpw' = C3ED660424548B66
	 <user defined> '_inpd'
	 <user defined> '_outp'
	 <user defined> '_outpw'
	 <user defined> '_outpd'
	 <user defined> '_local_unwind4'
	 <user defined> '_seh_longjmp_unwind4'
	 <user defined> '_except_handler2'
	 <user defined> '_setjmp'
	 <user defined> '_setjmp3'
	 <user defined> '_CIsqrt'
	 <user defined> 'sqrt'
	 <user defined> 'acos'
	 <user defined> '_CIacos'
	 <user defined> 'asin'
	 <user defined> '_CIasin'
	 <user defined> 'atan'
	 <user defined> '_CIatan'
	 <user defined> 'cos'
	 <user defined> '_CIcos'
	 <user defined> 'log'
	 <user defined> '_CIlog'
	 <user defined> 'log10'
	 <user defined> '_CIlog10'
	 <user defined> 'sin'
	 <user defined> '_CIsin'
	 <user defined> 'tan'
	 <user defined> '_CItan'
	 <user defined> '_ftol'
	 <user defined> 'ceil'
	 <user defined> 'floor'
	 <user defined> 'modf'
	 <user defined> 'fmod'
	 <user defined> '_CIfmod'
	 <user defined> 'pow'
	 <user defined> '_CIpow'
	 <user defined> 'atan2'
	 <user defined> '_CIatan2'
	 <user defined> 'sinh'
	 <user defined> 'cosh'
	 <user defined> 'tanh'
	 <user defined> '_CIsinh'
	 <user defined> '_CIcosh'
	 <user defined> '_CItanh'
	 <user defined> '_except_handler3'
	 <user defined> '_seh_longjmp_unwind'
	 <user defined> '_global_unwind2'
	 <user defined> '_local_unwind2'
	 <user defined> '_abnormal_termination'
	 <user defined> '_NLG_Dispatch2'
	 <user defined> '_NLG_Return2'
	 <user defined> 'exp'
	 <user defined> '_CIexp'
	 <user defined> '??_7exception@std@@6B@'
	 <user defined> '??_7bad_cast@std@@6B@'
	 <user defined> '??_7bad_typeid@std@@6B@'
	 <user defined> '??_7__non_rtti_object@std@@6B@'
	 <user defined> 'strstr'
	 <user defined> 'strchr'
	 <user defined> '??1type_info@@UAE@XZ'
	 <user defined> '??_7exception@@6B@'
	 <user defined> '_longjmpex'
	 <user defined> 'longjmp'
	 <user defined> 'memcpy_s'
	 <user defined> 'free'
	 <user defined> '??3@YAXPAX@Z' = D2EB5DEC8B55FF8B
	 <user defined> '??_V@YAXPAX@Z'
	 <user defined> 'malloc'
	 <user defined> '_ultow_s'
	 <user defined> '__set_flsgetvalue'
	 <user defined> 'ldiv'
	 <user defined> 'div'
	 <user defined> 'wcsnlen'
	 <user defined> '_getptd'
	 <user defined> '_errno'
	 <user defined> 'iswctype'
	 <user defined> '_wcsicmp'
	 <user defined> 'memmove_s'
	 <user defined> '_lock'
	 <user defined> '_unlock'
	 <user defined> 'wcschr'
	 <user defined> '_itow_s'
	 <user defined> '_malloc_crt'
	 <user defined> 'wcstol'
	 <user defined> '_wcstol_l'
	 <user defined> '_wtol'
	 <user defined> '_wtoi' = E2EB5DEC8B55FF8B
	 <user defined> 'wmemcpy_s'
	 <user defined> 'bsearch'
	 <user defined> 'wcspbrk'
	 <user defined> '_fputwc_nolock'
	 <user defined> '_vsnwprintf_l'
	 <user defined> '_vsnwprintf'
	 <user defined> '_mbtowc_l'
	 <user defined> '_calloc_crt'
	 <user defined> '_initptd'
	 <user defined> 'wcsstr'
	 <user defined> '_itow'
	 <user defined> 'isdigit'
	 <user defined> 'wcslen'
	 <user defined> '_fgetwc_nolock'
	 <user defined> 'wcsncmp'
	 <user defined> 'wcsncpy_s'
	 <user defined> 'calloc'
	 <user defined> 'iswspace'
	 <user defined> '_iswspace_l'
	 <user defined> '??2@YAPAXI@Z'
	 <user defined> 'wcsrchr'
	 <user defined> 'swprintf_s'
	 <user defined> 'wcsspn'
	 <user defined> '_waccess_s'
	 <user defined> 'iswdigit'
	 <user defined> '_iswdigit_l'
	 <user defined> 'wcscpy_s'
	 <user defined> 'wcscat_s'
	 <user defined> '_isleadbyte_l'
	 <user defined> '_towlower_l'
	 <user defined> '_ltow'
	 <user defined> '_msize'
	 <user defined> '_initterm'
	 <user defined> '_initterm_e'
	 <user defined> '__dllonexit'
	 <user defined> '_wcslwr'
	 <user defined> '_freefls'
	 <user defined> '_vswprintf_s_l'
	 <user defined> 'vswprintf_s'
	 <user defined> '_vscwprintf'
	 <user defined> 'towlower'
	 <user defined> '_wcslwr_s_l'
	 <user defined> '_wcslwr_s'
	 <user defined> '_time64'
	 <user defined> 'wcsncpy'
	 <user defined> '_wfullpath'
	 <user defined> '__iob_func'
	 <user defined> '__p__iob'
	 <user defined> '_wsplitpath_s'
	 <user defined> 'swscanf_s'
	 <user defined> '_ungetwc_nolock'
	 <user defined> '_wcsicmp_l'
	 <user defined> '_isdigit_l'
	 <user defined> 'wcstok'
	 <user defined> '_snwprintf'
	 <user defined> 'wcstoul'
	 <user defined> '_wcstoul_l'
	 <user defined> 'realloc'
	 <user defined> '_recalloc'
	 <user defined> '_realloc_crt'
	 <user defined> '_wcsnicmp'
	 <user defined> 'wcscspn'
	 <user defined> 'strcpy_s'
	 <user defined> 'strcat_s'
	 <user defined> 'qsort'
	 <user defined> '??_U@YAPAXI@Z'
	 <user defined> 'wcstok_s'
	 <user defined> 'setlocale'
	 <user defined> '_wcstombs_s_l'
	 <user defined> 'wcstombs_s'
	 <user defined> '_atoflt_l'
	 <user defined> '_freea'
	 <user defined> '_freea_s'
	 <user defined> '__crtLCMapStringA'
	 <user defined> 'strncpy_s'
	 <user defined> 'memcmp'
	 <user defined> '_itoa_s'
	 <user defined> '_CRT_RTC_INIT'
	 <user defined> '_CRT_RTC_INITW'
	 <user defined> '_wtof_l'
	 <user defined> '_wtof'
	 <user defined> '_wsplitpath'
	 <user defined> '___lc_handle_func'
	 <user defined> '___lc_codepage_func'
	 <user defined> '__pctype_func'
	 <user defined> '_unlock_file'
	 <user defined> '_lock_file'
	 <user defined> '_fileno'
	 <user defined> '_get_osfhandle'
	 <user defined> '_close'
	 <user defined> '_fclose_nolock'
	 <user defined> 'fclose'
	 <user defined> '_set_purecall_handler'
	 <user defined> '_onexit'
	 <user defined> '__doserrno'
	 <user defined> '_dosmaperr'
	 <user defined> '_read'
	 <user defined> '_wsopen_s'
	 <user defined> '_get_fmode'
	 <user defined> '_setmbcp'
	 <user defined> '_ismbblead'
	 <user defined> '_encoded_null'
	 <user defined> '??0exception@std@@QAE@ABQBDH@Z'
	 <user defined> '__set_app_type'
	 <user defined> '_wfsopen'
	 <user defined> '??1__non_rtti_object@std@@UAE@XZ'
	 <user defined> '??1bad_cast@std@@UAE@XZ'
	 <user defined> '??1exception@std@@UAE@XZ'
	 <user defined> '??1bad_typeid@std@@UAE@XZ' = EB74D3FC7401C7
	 <user defined> '?_Tidy@exception@std@@AAEXXZ'
	 <user defined> '??4exception@std@@QAEAAV01@ABV01@@Z'
	 <user defined> '??0exception@std@@QAE@ABV01@@Z'
	 <user defined> '_control87'
	 <user defined> '_controlfp_s'
	 <user defined> 'atexit'
	 <user defined> '__AdjustPointer'
	 <user defined> '??0__non_rtti_object@std@@QAE@ABV01@@Z'
	 <user defined> '_wfopen_s'
	 <user defined> '_wcsupr_s_l'
	 <user defined> '_wcsupr_s'
	 <user defined> 'fgetws'
	 <user defined> '_filbuf'
	 <user defined> 'isprint'
	 <user defined> 'isleadbyte'
	 <user defined> 'mbtowc'
	 <user defined> '__getmainargs'
	 <user defined> 'strncmp'
	 <user defined> '_isatty'
	 <user defined> '_write'
	 <user defined> '_flsbuf'
	 <user defined> '_wmakepath_s'
	 <user defined> 'strnlen'
	 <user defined> 'fflush'
	 <user defined> '_fflush_nolock'
	 <user defined> 'wcsncat_s'
	 <user defined> '_vsprintf_s_l'
	 <user defined> 'sprintf_s'
	 <user defined> '_tolower_l'
	 <user defined> '_strnicmp_l'
	 <user defined> '_strnicmp'
	 <user defined> '_ungetc_nolock'
	 <user defined> '_isspace_l'
	 <user defined> 'isspace'
	 <user defined> 'sscanf_s'
	 <user defined> '_wctomb_s_l'
	 <user defined> 'wctomb_s'
	 <user defined> 'vfwprintf'
	 <user defined> 'atoi'
	 <user defined> '_wcsnicoll_l'
	 <user defined> '_wcsnicoll'
	 <user defined> 'strtol'
	 <user defined> 'atol'
	 <user defined> '_wdupenv_s'
	 <user defined> '_waccess'
	 <user defined> '_wcsnicmp_l'
	 <user defined> '_wsearchenv_s'
	 <user defined> 'iswascii'
	 <user defined> '_isalnum_l'
	 <user defined> 'isalnum'
	 <user defined> 'strncat_s'
	 <user defined> '_fwrite_nolock'
	 <user defined> 'fwrite'
	 <user defined> '_lseek'
	 <user defined> '_ftell_nolock'
	 <user defined> 'ftell'
	 <user defined> '?_NumberOfSpins@?$_SpinWait@$0A@@details@Concurrency@@IAEKXZ'
	 <user defined> '?_NumberOfSpins@?$_SpinWait@$00@details@Concurrency@@IAEKXZ'
	 <user defined> '__unDNameEx'
	 <user defined> '_wcsdup'
	 <user defined> '_flushall'
	 <user defined> 'vsprintf_s'
	 <user defined> '_strnicoll_l'
	 <user defined> '_mbsnbicoll_l'
	 <user defined> '_mbsnbicoll'
	 <user defined> 'getenv'
	 <user defined> 'setvbuf'
	 <user defined> 'fseek'
	 <user defined> '_fseek_nolock'
	 <user defined> '_wputenv_s'
	 <user defined> '_mbschr_l'
	 <user defined> '_mbschr'
	 <user defined> '__wgetmainargs'
	 <user defined> '_wgetenv_s'
	 <user defined> 'rewind'
	 <user defined> '_fullpath'
	 <user defined> '_set_invalid_parameter_handler'
	 <user defined> '_fread_nolock_s'
	 <user defined> 'fread_s'
	 <user defined> 'fread'
	 <user defined> 'fputws'
	 <user defined> '_wunlink' = EB5DEC8B55FF8B
	 <user defined> '_wremove'
	 <user defined> '_wspawnve'
	 <user defined> '_wspawnvpe'
	 <user defined> '_wspawnvp'
	 <user defined> '_getmbcp'
	 <user defined> '??2@YAPAXIHPBDH@Z'
	 <user defined> '_splitpath_s'
	 <user defined> '_makepath_s'
	 <user defined> '_mbsdec_l'
	 <user defined> '_mbsdec'
	 <user defined> '_atof_l'
	 <user defined> 'atof'
	 <user defined> '_ltoa_s'
	 <user defined> '_ultoa_s'
	 <user defined> '__unDName'
	 <user defined> '_strlwr_s_l'
	 <user defined> '_strlwr_s'
	 <user defined> 'fputwc'
	 <user defined> '_get_wpgmptr'
	 <user defined> '_vswprintf_c_l'
	 <user defined> '_strdup'
	 <user defined> 'strtoul'
	 <user defined> '__tzname'
	 <user defined> '_get_timezone'
	 <user defined> '_get_daylight'
	 <user defined> '__timezone'
	 <user defined> '__daylight'
	 <user defined> '__dstbias'
	 <user defined> '__crtCompareStringW'

**Comment by MasterHal** [comment]
Sorry:
cMangos: Rev. 12814
ScriptDev2:  Rev. 3082

**Comment by Schmoozerd** [comment]
You probably use an outdated translation for the commands.
Hence the command format-strings do not match the proper ones.

Easiest is to delete the localisation for mangos_string.

**Comment by MasterHal** [comment]
You are my Hero, thanks. 
I'll try it.

**Comment by xfurry** [comment]
@MasterHal if this solvers your problem, please close the issue. Thanks.

**Comment by MasterHal** [comment]
You'r right Schmoozerd.

In table mangos_string, at entry = 8:

- content_default = "Command %s have subcommands:" 
- content_loc3 = "Befehl %s hat Unterbefehle: %s"

I changed the value in content_loc3 in "Befehl %s hat Unterbefehle:" (without the %s at the end)

It works.

Thank you for helping me.
MasterHal
