### ISSUE TITLE
Classic: Improved Sap

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#569]
Core: Lastest

Rogue talent [Improved Sap] 3/3
http://db.valkyrie-wow.org/?spell=14095

Regardless of points spent on specific talent the effect is the same, it will not allow the rogue to restealth after sapping the target.

**Comment by yyhhrr** [comment]
https://github.com/yyhhrr/portalclassic/commit/1bba223acbf206d10f29093ebb9dac5f4a144e87
Maybe this will help.It is worked for me.

**Comment by Kelzior** [comment]
Thanks
