### ISSUE TITLE
Need SCRIPT_COMMAND_SET_RESPAWN_TIME. Or SCRIPT_COMMAND_RESPAWN.

### ISSUE THREAD

**Issue by Ulduar** [cmangos/issues#572]
Quest example:
http://www.wowhead.com/quest=13631/all-is-well-that-ends-well
http://wowpedia.org/Quest:All_Is_Well_That_Ends_Well
http://www.wowwiki.com/Quest:All_Is_Well_That_Ends_Well
https://github.com/scriptdev2/scriptdev2-cata/issues/3
Rhonin should  respawn a few seconds after despawning after using the teleport visual spell.
Proof:
https://github.com/TrinityCore/TrinityCore/commit/87b973c2806fa635648dde39bef2bd1c65d28c50
And my eye!
Set Respawn Delay in DB - full hack and not acceptable.

**Comment by cyberium** [comment]
@Schmoozerd or @xfurry please give any feedback here and close issue if its not possible.

**Comment by Ulduar** [comment]
@cyberium, @Schmoozerd  or @Xfurry please see https://github.com/cmangos/mangos-wotlk/pull/148
I tried to create a patch, but Travis swears errors.
