### ISSUE TITLE
12701 - Massacre At Light's Point

### ISSUE THREAD

**Issue by Dainara82** [cmangos/issues#574]
this quest is buggy,
if i jump into the Lore, nothing happend, the movement way's from the mineworkers don't go, all mineworker stay with there lore and not walk

**Comment by Grz3s** [comment]
you should ... say what DB u're using...
in newest UDB this part works fine

**Comment by Dainara82** [comment]
i use the db in the winstallation wiki
Get the world-database stuff
(Latest version) Insert as SVN-URL: https://unifieddb.svn.sourceforge.net/svnroot/unifieddb/trunk

**Comment by Grz3s** [comment]
pls check again all instalation instructions....
info there was outdated...
its fixed now!
for future pls use...
https://github.com/unified-db

**Comment by cyberium** [comment]
Not related to the core
