### ISSUE TITLE
Need spelldifficulty_dbc server side dbc and maybe spell_linked table.

### ISSUE THREAD

**Issue by Ulduar** [cmangos/issues#578]
Cata 4.3.4
For Ragnaros Encounter:
``` CPP
DELETE FROM `spelldifficulty_dbc` WHERE `id` IN (99235, 99236, 99172);
INSERT INTO `spelldifficulty_dbc` (`id`, `spellid0`, `spellid1`, `spellid2`, `spellid3`) VALUES
(99235, 99235, 100178, 100179, 100180),
(99236, 99236, 100181, 100182, 100183),
(99172, 99172, 100175, 100176, 100177);
```
All of these missing in the  SpellDifficulty.dbc
Spell_linked_need also, because:
``` CPP
-- Linked spells for Molten Seed to supress code size
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` IN (-98520, -100888);
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES
('-98520', '-100153', '0', 'Molten Elemental - Remove Invisibility'),
('-98520', '98518', '0', 'Molten Elemental - Cast Molten Inferno'),
('-98520', '100157', '0', 'Molten Elemental - Cast Molten Aura'),
('-100888', '-100153', '0', 'Molten Elemental - Remove Invisibility'),
('-100888', '98518', '0', 'Molten Elemental - Cast Molten Inferno'),
('-100888', '100157', '0', 'Molten Elemental - Cast Molten Aura');
```

**Comment by xfurry** [comment]
spelldifficulty_dbc is already in DBC, hence not required.

spell_linked_spell might be an interesting idea, especially related to what we discussed here: https://github.com/cmangos/issues/issues/562
However this looks incomplete to me, because you can't link a spell to another spell without providing the caster and target.
So for your example I think the place of those linked spells is in the script itself.

Closed.

**Comment by Ulduar** [comment]
``` QUOTE
spelldifficulty_dbc is already in DBC, hence not required.
```
That's the way these spells missing in the DBC
spell_linked - need, I have already described why

**Comment by xfurry** [comment]
Nothing is missing, as per spellwork:
```
Spell difficulty Ids:
Normal 10: 99235
Normal 25: 100178
Heroic 10: 100179
Heroic 25: 100180
```

For spell linked I told you already what is missing.
On top of this, you provided some SQL code... 
If you want to have this feature, then provide the C++ code as a patch and we'll talk about it.

**Comment by Ulduar** [comment]
``` QUOTE
Badly looked, sorry!
```
``` CPP
If you want to have this feature, then provide the C++ code as a patch and we'll talk about it.
```
I'm not strong in the core to be honest, I have no idea how to implement.
