### ISSUE TITLE
SPELL_ASCEND_HEAVENS

### ISSUE THREAD

**Issue by Ulduar** [cmangos/issues#580]
SpellWork Info:
``` CPP

Id: 64487
Name: Вознесение в небеса
Description: Наносит $s1 ед. урона от тайной магии противникам.
ToolTip: Нанесение противникам $s1 ед. урона от тайной магии.
General info
Category = 0, SpellIconId = 2139, ActiveIconId = 0, SpellVisual = (13663, 0)
SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x00000000 00000000 00000000
SpellSchoolMask = 64 (SCHOOL_MASK_ARCANE, SCHOOL_MASK_SPELL, SCHOOL_MASK_MAGIC, SCHOOL_MASK_ALL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
Attributes
Attributes: 0x20000000 (SPELL_ATTR_UNAFFECTED_BY_INVULNERABILITY)
AttributesEx1: 0x00000088 (SPELL_ATTR_EX_UNK3, SPELL_ATTR_EX_NEGATIVE)
AttributesEx2: 0x00000004 (SPELL_ATTR_EX2_CANT_REFLECTED)
AttributesEx6: 0x00002000 (SPELL_ATTR_EX6_UNK13)
Advanced info
Spell Level = 0, BaseLevel 0, MaxLevel 0, MaxTargetLevel 0
Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange (Id 1) "Self Only"
MinRange = 0
MaxRange = 0
CastingTime (Id 5) = 2.00
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 0, charges - 0
Effects
Effect 0:
Id: 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
BasePoints = 655500 to 724500 
Targets (22, 15) (TARGET_CASTER_COORDINATES, TARGET_ALL_ENEMY_IN_AREA)
Radius (Id 41) 150.00
Effect 1:
NO EFFECT
Effect 2:
NO EFFECT
```
Even if I have an aura SPELL_AURA_PHASE, it should fall on me, ignoring the phase and cause me damage.

**Comment by Ulduar** [comment]
Need implemented SPELL_ATTR_EX6_UNK13.
SPELL_ATTR_EX6_UNK13 =     SPELL_ATTR6_CAN_TARGET_INVISIBLE             = 0x00002000, // 13 ignore visibility requirement for spell target (phases, invisibility, etc.)

**Comment by xfurry** [comment]
I think it's not that easy....
The attribute might be required, but we also need to change the target processing in the core in order to support targets that are in a different phaseMask than the caster.

**Comment by Ulduar** [comment]
Need check attribute SPELL_ATTR_EX6_UNK13, SPELL_AURA_MOD_INVISIBILITY, SPELL_AURA_PHASE and SPELL_AURA_326(SPELL_AURA_PHASE_2). Maybe check need in Spell.cpp and Unit.cpp?

**Comment by xfurry** [comment]
I think the following wasn't clear enough
> we also need to change the target processing in the core in order to support targets that are in a different phaseMask than the caster

=> this has nothing to do with the attributes. It's about overall target processing, which requires a lot of rework.
