### ISSUE TITLE
TBC: Spirit towers Oudoor PvP

### ISSUE THREAD

**Issue by Undergarun** [cmangos/issues#581]
Terokkar Spirit towers should reset every 6 hours. Currenctly not works till next server reset.

**Comment by cyberium** [comment]
I think this is fixed @killerwife confirm and close

**Comment by killerwife** [comment]
Uh, it works on my server, idk if the code is different, it wasnt changed in past 2 years afaik at all.

**Comment by Undergarun** [comment]
Now is working. Thanks
