### ISSUE TITLE
TBC: Group loot

### ISSUE THREAD

**Issue by Undergarun** [cmangos/issues#584]
Group loot mode should randomly allow players to loot stuff. Currently all players can take whatever. First one who loots get it.

**Comment by evil-at-wow** [comment]
Yes, loot related mechanics are quite buggy in general, for all cores (see #272 and #376).

The good news is that fixes are finally on the way! Over the past few weeks, @cyberium has been busy fixing loot mechanics, and his changes are currently being tested. I have backported the changes to TBC, so if you're interested to [check them out](https://github.com/evil-at-wow/cmangos-tbc/commits/loot) and do some testing, you're more than welcome!

Currently know issues (to avoid duplicate reports):
* When in a group, you can't see the money for corpses tagged with someone else's name.
* When in a group, looting gameobjects like chests doesn't bring up a roll dialog for above treshold items.
* When in a group, the loot doesn't become free for all after someone loots a corpse tagged with his/her name only partially.

**Comment by cyberium** [comment]
must be fixed
