### ISSUE TITLE
[WOTLK] Hallow's End Candy

### ISSUE THREAD

**Issue by virusav** [cmangos/issues#585]
Patch for spell 42919:

``` DIFF
diff --git a/src/game/SpellAuras.cpp b/src/game/SpellAuras.cpp
index 25455aa..3ecab3f 100644
--- a/src/game/SpellAuras.cpp
+++ b/src/game/SpellAuras.cpp
@@ -8009,8 +8009,9 @@ void Aura::PeriodicDummyTick()
 //              case 42774: break;
 //              // Headless Horseman Climax - Summoning Rhyme Aura
 //              case 42879: break;
-//              // Tricky Treat
-//              case 42919: break;
+                case 42919:                                     // Tricky Treat
+                    target->CastSpell(target, 42966, true);     // Upset Tummy
+                break;
 //              // Giddyup!
 //              case 42924: break;
 //              // Ram - Trot 
```

Questions:
1. In the block "switch" to spell 42919 in most cases indicate "return", but is simply "break", as in 42621.
How to determine what needs to be specified for a particular spell, "return" or "break"?
2. When cast spell 24930 occurs castes one of 4 other spells.
If you believe the comments that cast spell 24926 should lead to a change in the player model pirate.
For this purpose there spells 44742 (female) and 44743 (male).
How should be a change of player models to stay buff from 24926, which occurs when you cancel the return player models?
3. Cast spells sweets hangs buff the player.
Should there be a player the opportunity to remove these buffs right mouse button?
And whether they should be substituted for each other, for example, in the case of 24930?

**Comment by virusav** [comment]
1. Are there any comments on the patch?
2. Is there enough to do spells 24926, 44742 and 44743 do not replace each other and shoot 44742 and 44743, if 24926 canceled?

**Comment by Schmoozerd** [comment]
q1: return will stop further processing of the spell.
If you only break ie SD2-OnEffectDummy will be called.
Usually you will use "return" for a proper (and completely) implemented spell

So likely spell 42621 should also use the "return"

q2: In wotlk/tbc 24926  is only a swim-speed aura, in classic it also included the model.
So i agree that in wotlk/tbc 44742 / 44743 should be cast as well with 24926  (in some place)

I do not know how we would - in such a case - "link" the spells together. Except of course use an override in Swim-Speed aura apply/remove to cast/remove the 44* spells

q3: Well, this should be researched based on retail behaviour. (old comments, old vids, ... )

**Comment by virusav** [comment]
What about the patch for spell 42919?
It just cast another spell.

**Comment by xfurry** [comment]
for point 2 I think this would help, but I'm not sure it it's complete

```diff
@@ -1190,10 +1190,13 @@ void Spell::EffectDummy(SpellEffectIndex eff_idx)
                     m_caster->CastSpell(m_caster, 23782, true);
                     m_caster->CastSpell(m_caster, 23783, true);
                     return;
                 case 24930:                                 // Hallow's End Treat
                 {
+                    if (m_caster->GetTypeId() != TYPEID_PLAYER)
+                        return;
+
                     uint32 spell_id = 0;
 
                     switch (urand(1, 4))
                     {
                         case 1: spell_id = 24924; break;    // Larger and Orange
@@ -1201,10 +1204,14 @@ void Spell::EffectDummy(SpellEffectIndex eff_idx)
                         case 3: spell_id = 24926; break;    // Pirate
                         case 4: spell_id = 24927; break;    // Ghost
                     }
 
                     m_caster->CastSpell(m_caster, spell_id, true);
+
+                    // handle transformation after 2.x
+                    if (spell_id == 24926)
+                        m_caster->CastSpell(m_caster, ((Player*)m_caster)->getGender() == GENDER_FEMALE ? 44742 : 44743, true);
                     return;
                 }
                 case 25860:                                 // Reindeer Transformation
                 {
                     if (!m_caster->HasAuraType(SPELL_AURA_MOUNTED))
```

**Comment by virusav** [comment]
Checking relevance.
