### ISSUE TITLE
NPC Caster don't always move when LoS is broken

### ISSUE THREAD

**Issue by Dainara82** [cmangos/issues#588]
Many Caster don't move if you go behind a wall, they cast the aktually cast finish and than they stay so long as they see you
area of Stormgarde in arathi highlands
uldaman
northern stranglethorn  in the cave by the kurzen's
in the castle  in redrigemountain
...

**Comment by xfurry** [comment]
I think this is related to eventAI scripts.
Not sure if the script should be fixed or AI behavior improved.
Let's see what other guys think.

**Comment by Schmoozerd** [comment]
It is a bit an issue of both.
We need better AI support for the generic behaviour on the one hand,
and on the other hand the AI scripts (mostly EventAI here) need to be improved a bit.

Personally i wait on feedback at http://cmangos.net/thread-6742-post-42494.html#pid42494 - as i am pretty sure that we can (and should!) use direct methods within the EventAI supports as main effort.
Implementational Details (like maybe a CasterChaseMMGen or such) might then still be implemented as things evolve.

**Comment by cala** [comment]
More feedback on the issue: https://github.com/cmangos/issues/issues/180
(I'm trying to keep everything in one place: here)

**Comment by krullgor** [comment]
i created a patch for this a year ago: http://cmangos.net/thread-503-post-41259.html#pid41259 i forgot about it because no one was replying anymore. feel free to test!
important: this solution needs acid/database support! a test script is included.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-wotlk/commit/e40b35e5fdb0d7031fc13fbba97f5a608ed4e288
ACID needs to be updated (only TBC is up-to-date).
