### ISSUE TITLE
[WOTLK] Some DeathKnight Spells Are Not Working Correctly

### ISSUE THREAD

**Issue by Dainara82** [cmangos/issues#589]
Blood of the North
should Permanently transforms your Blood Runes into Death Runes.
## Doesn't work, the rune get an normal cooldown

Death Grip
Harnesses the energy that surrounds and binds all matter, drawing the target toward the Death Knight and forcing the enemy to attack the Death Knight for 3 sec.
## Doesn't work, the Spell only spott the enemy's

Raise Dead
Raises a ghoul to fight by your side.  You can have a maximum of one ghoul at a time.
Doesn't work as spell and doesn't work with reagents

**Comment by killerwife** [comment]
Raise dead works now.

**Comment by killerwife** [comment]
All work now.
