### ISSUE TITLE
Mobs turn around when stunned

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#590]
When you stun a target (e.ex. with gouge) it tourns around and seems to look into the opposite direction. This is a visual bug.

**Comment by virusav** [comment]
Target "remember" orientation facing the caster.
When running as a spell with a stunning effect, the target rotates in the same direction, which has been turned up stunning.

Test: cast spell 25 on NPC, waiting for the end of the aura, then go around the target at an angle and then cast spell 25 - target is turned to the side, where the player after the first aura.

**Comment by vovk** [comment]
Target turns aroung only visible. This is bug sending packet to client. You can try gouge rogue, then try any ability thet cat be use only from behind, you'll see that you can hit stuned target only in face.

**Comment by cyberium** [comment]
must be fixed on classic update this if its not the case
