### ISSUE TITLE
DB Script command 34 TERMINATE_CONDITION leads to server crash

### ISSUE THREAD

**Issue by weishan1981** [cmangos/issues#591]
I complete the quest -"Translation to Ello"(entry=252) and go back to NPC Lord Ello Schwarzhaupt,but everytime when i click him,the server crash .
Please fix it ,thanks.

**Comment by cala** [comment]
I can't reproduce the bug. Can you provide more detail, please (crash log, DB/SD2/Core versions, OS...)?

**Comment by cala** [comment]
After discussing with @scotty0100 and performing some tests with him, it appears the crash is related to the use of DB scripts command 34 TERMINATE_CONDITION . All scripts using that command crash the server when command is executed.
However, I never had a crash with that command, so I assume this is something related to the plateform hosting the server (or the build target).

Example list of quests with that issue: 252, 667 & 3382 (there are probably more).

@scotty0100 provided me a crash log, I'll post it here when I'm back at home (unless he post it first).

**Comment by cala** [comment]
I renamed the issue accordingly.
All the report are for Classic core, but no tests were made on TBC/WotLK so the bug may also exist there.

**Comment by scotty0100** [comment]
I reverted back to some older commits which now makes these quests work again - I will soon be able to isolate the exact commit that starts to break it. Will update this once I know.

Some Extra Info: Server is running on Windows Server 2012, Built using VS2013.

**Comment by scotty0100** [comment]
After lots of testing this is the commit that breaks it for me:

https://github.com/cmangos/mangos-classic/commit/7593dd659a014de36e6823e970cca096ad402565

@Schmoozerd Do you know why this commit would affect this at all?

**Comment by Schmoozerd** [comment]
very weird. can you provide some crash log? this looks a little like some memory corruption or similar from the description

**Comment by scotty0100** [comment]
Oh yup, sure. 
http://pastebin.com/dNhiheiQ

**Comment by Schmoozerd** [comment]
Anyhow. Personally I would expect a crash related to conditions here in classic!

There had been an error when backporting the db-scripts condition:
https://github.com/cmangos/mangos-classic/blob/7593dd659a014de36e6823e970cca096ad402565/src/game/ObjectMgr.cpp#L6797
 There is no corresponding (dummy) string for CONDITION_FROM_RESERVED_1 = 8,
Hence accessing the array of size 9 with index 9 must fail..

Update: TBC also has this error: https://github.com/cmangos/mangos-tbc/blob/master/src/game/ObjectMgr.cpp#L7274

Way to fix:
1) Add reserved string
or
2) Decrement the index for CONDITION_FROM_DBSCRIPTS

**Comment by stfx** [comment]
I would assume option 1 is preferred due to https://github.com/cmangos/mangos-tbc/commit/3523feecffa769413a4cd4b2b5f12debed8ca45d saying something about compatibility

**Comment by evil-at-wow** [comment]
@stfx I agree that was the preferred option, so I acted accordingly.
