### ISSUE TITLE
[Classic] Dire Maul NPC Mizzle der Gewiefte BUG

### ISSUE THREAD

**Issue by weishan1981** [cmangos/issues#592]
After you kill NPC König Gordok,NPC Mizzle der Gewiefte will appear,he will talk something and give player a box.
the bug is ,after you open the box and get something from it ,you can click  Mizzle der Gewiefte and get a box again......again

**Comment by evil-at-wow** [comment]
I'm going to close this one because this is a database issue - and it has already been reported here: classicdb/database#203.
