### ISSUE TITLE
[Classic]Dire Maul BUFF

### ISSUE THREAD

**Issue by weishan1981** [cmangos/issues#593]
Dire Maul buffs  not work

**Comment by evil-at-wow** [comment]
Can you be a bit more specific please? Which buffs do you mean?

If you're talking about the 'King of the Gordok' buff, that one should be fixed for some time, see classicdb/database#204.

**Comment by Tobschinski** [comment]
The only thing I can think of: The spell is NEVER removed from the player, it is up until he dies. He isn't able to reset and re-do the dungeon with this spell being up.

The spell must be removed when the player leaves the map.

**Comment by Rushor** [comment]
is the faction of the ogers right? afaik it should be 45 in order to achieve that the buff chances the faction to friendly for the player
