### ISSUE TITLE
Classic: Baron's Prisoner Event Bug

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#599]
Core: Lastest

Would like to report the Baron's Prisoner Event Bug, Spell ID: 27861
http://db.vanillagaming.org/?spell=27861
For malicious activity, specifically continuing processing even after Baron himself is dead and also the fact
that the prisoner NpC itself, Ysida Harmoon is nonexistent
Even after killing baron the Buff is still there yet no NpC/prisoner to be seen.

**Comment by Phatcat** [comment]
This whole event has been reworked 'recently' and all of this should have been taken care of, if you find any issues with the current implementation please open up a new issue as I'm gonna close this one.

**Comment by cala** [comment]
Thanks! I thought to have closed all the related issues when I pushed the scripts. :+1:
