### ISSUE TITLE
[CLASSIC] Tyrande and Remulos Quest Issue

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#601]
Core: Lastest

https://classic.wowhead.com/quest=8734/tyrande-and-remulos

It says - quest is not available to your race. - (Horde)

**Comment by MantisLord** [comment]
I cannot reproduce this issue on any core. The quest is acceptable by Horde characters. Ensure your reputation with Brood of Nozdormu is at least Neutral.
