### ISSUE TITLE
Classic: Quest: D2 QuestLine (Dead Man's Plea)

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#602]
Core: Lastest

the Dungeon Set 2 Quest-Line is seemingly
Bugged, as they say, in what aspect ?

http://db.vanillagaming.org/?quest=8945

Quest Does not seem to work, Taking it offers you directly the reward Ysida's Satchel which doesn't seem to even show on the quest tracker, and this reward should be received from Ysidla herself in Stratholme.

Not to mention the fact... That She's not there of course. Supposed to be caged.
Regardless of defeating Baron or not.

Leaving that Aside, after supposedly, ''Instantly'' completing the quest, of coruse the Quest NpC http://db.vanillagaming.org/?npc=16016 wants the Quest Item, Ysida's Locket , and well...
The quest doesn't even seem to be in the Quest Tracker anymore...

**Comment by TheTrueAnimal** [comment]
https://www.youtube.com/watch?v=opFRb4Y0WzM  (4:15)
https://www.youtube.com/watch?v=qJALGWssQk0  (5:15)
http://www.wowwiki.com/Quest:Dead_Man%27s_Plea
http://www.wowhead.com/quest=8945/dead-mans-plea

At the moment the Buff disappears when you die. Maybe also when you bubble and use Ice Block. It should persist until the time is over.
http://www.wowhead.com/spell=27861/the-barons-ultimatum
http://www.wowhead.com/spell=27863/the-barons-ultimatum
http://www.wowhead.com/spell=27864/the-barons-ultimatum
http://www.wowhead.com/spell=27865/the-barons-ultimatum

**Comment by TheTrueAnimal** [comment]
Maybe this could help (I'm not a dev but I've got some ideas):
- at the moment an event seems to start and gives the buff to characters. If the event lasts 45 minutes after its start, it could automatically despawn Ysida, who was there from the beginning on.
