### ISSUE TITLE
Classic: Client Crash (quest)

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#605]
Core: Lastest

http://db.vanillagaming.org/?quest=9223
&
http://db.vanillagaming.org/?quest=9226

Both of which crash the game client on attempt to start.

**Comment by krullgor** [comment]
I cannot reproduce this client crash with english client, core version 2644 and classicdb 982, could you try this again?

**Comment by Fabi** [comment]
You should upload crashlogs of the client somewhere. these will help to find the problem
