### ISSUE TITLE
Classic: Essential Herbalism Item Bug

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#606]
Lastest Core

Would like to report a substantial item Bug in the herbalism profession:
Object ID: 174615 [Cleansed Songflower]

http://db.vanillagaming.org/?object=174615
Is not responding properly to player actions:

Whenever attempting to acquire the item the error message : [Another action is in progress] pops up.

This and many other herbs offer a temporary buff to the herbalist and is an important aspect for those who pick this profession, ignoring this object would be taking away benefits the profession itself offers.

**Comment by cala** [comment]
Thanks for this report.

The felwood plant buffs are mainly handled by DB. Currently, all DB projects have bad or partial data for those gameobjects. Only YTDB has something acceptable (but not perfect) and Classic DB is in the worst shape of all DB (lucky me...).

Good news, I already have it 90% properly working from DB fixes (issue in Classic DB: https://github.com/classicdb/database/issues/387). The last 10% may require a core update to despawn the quest giving gameobject to let the buffing gameobject spawn in its stead. In my opinion, this should be part of what is currently discussed here: http://cmangos.net/thread-6810.html

**Comment by cyberium** [comment]
@cala when you got some time please update this, if it require some core side then we'll add it.

**Comment by cala** [comment]
Now fixed. There is an issue with the "corrupted" GO not despawning on use but this will be handled in Gameobject code rework that I intend to do at some point (much needed)
