### ISSUE TITLE
Force Self bow has no effect

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#611]
The spell "Force Self bow" from the Lunar Festival doesn't have any effect on the players characters.
http://www.wowhead.com/spell=25716/force-self-bow

**Comment by virusav** [comment]
25716 - SPELL_EFFECT_DUMMY - `dbscripts_on_spell` (`command`=1, ...)
Do you have a record in the table?

**Comment by TheTrueAnimal** [comment]
I don't even have that id in my dbscripts_on_spell list.

**Comment by xfurry** [comment]
Try this:

```sql
DELETE FROM dbscripts_on_spell WHERE id=25716;
INSERT INTO dbscripts_on_spell (id, command, datalong, comments) VALUES
(25716, 1, 2, 'Force Self - Bow - emote');
```

**Comment by virusav** [comment]
CMangos - 12851, SD2 - 3112, database - YTDB: player bows to no records in the table `dbscripts_on_spell`.

**Comment by virusav** [comment]
How to find out where the treatment for spell effect SPELL_EFFECT_DUMMY?

**Comment by xfurry** [comment]
> How to find out where the treatment for spell effect SPELL_EFFECT_DUMMY?

Can you please be more specific? I don't understand the question.
Do you want to know where is the effect dummy handled in the core, or something else?

**Comment by virusav** [comment]
Spell 25716:
Effect 0: Id 3 (SPELL_EFFECT_DUMMY) - emotion bow
BasePoints = 1
Targets (1, 0) (TARGET_SELF, NO_TARGET)

Effect 1: NO EFFECT

Effect 2: NO EFFECT

Neither the core or in the script or in the base I could not find the treatment.
Nevertheless, the effect of the bow running.

There is an attribute spell SPELL_ATTR_HIDDEN_CLIENTSIDE.
Perhaps this is the case.

Where is the bow for this spell?

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/053952caf9527c07f71d9e453f4a7934f515f5ee
Thanks @xfurry
