### ISSUE TITLE
Alliance Reputation doesn't work

### ISSUE THREAD

**Issue by TheTrueAnimal** [cmangos/issues#612]
For all "...the Elder" quests from Lunar Festival you get reputation with "alliance"/"horde". This should give you the stated reputation at all homefactions. In fact, it doesn't give you any reputation there although the log says that you get it with "alliance"/"horde".

**Comment by virusav** [comment]
CMangos - 12851, SD2 - 3112, database - YTDB, quest - 8642: i've completed the quest, saw the writing, that the ratio of the Alliance to me improved by 82.
Checked the Reputation tab - all right.
Canceled and again passed the quest - that's right.

What exactly is not working?
And where do you see that the reputation is given?

**Comment by TheTrueAnimal** [comment]
Before finishing the quest, my reputation was:
Darnassus 6172
Gnomeregan 3254
Ironforge 10786

After finishing the quest (the log told me, that I've been given 82 reputation with Alliance):
Darnassus 6172
Gnomeregan 3254
Ironforge 10786

**Comment by virusav** [comment]
I did not see the version of the game in the description of the problem, tested on WOTLK.

**Comment by jimmybrancaccio** [comment]
Closing this out as an incomplete issue. If this is still a problem please open a new issue with full details. Thanks.
