### ISSUE TITLE
2.4.3 TBC core npc movement bug

### ISSUE THREAD

**Issue by stan84** [cmangos/issues#619]
after implementing lastest commints, the npc's who moving along waypoints runs after each walk point. it looks like   walk 0-->1 ->run->2->walk->3->run--->4etc

**Comment by stfx** [comment]
Will be fixed soon: https://github.com/cmangos/mangos-tbc/commit/ae7d6aa8c698f5858f36b2a1d05bf226a6b5c7c3#commitcomment-10032896
