### ISSUE TITLE
[Classic] [Shaman] [Mana Tide Totem]

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#623]
Core: 2612

It is immune to everyone, provides no mana and burns out after a minute.

**Comment by krullgor** [comment]
thanks for reporting, i found there was a backport from wotlk missing! https://github.com/cmangos/mangos-classic/commit/92fa3d947140f252ab8ff867d19cd7623174d0b4

**Comment by Kelzior** [comment]
👍
