### ISSUE TITLE
[Classic] more than two CC spells conflict on creatrues(blind, polymorgh, and fear etc.)

### ISSUE THREAD

**Issue by yumyrather** [cmangos/issues#626]
Eg, a rogue blinds  a creature. Before blind finish, a mage polymorgh the same creature. Then, when the blind end, the creature can move and attack freely even thought it still is a sheep. Similarly, casting polymorgh  follow a fear will cause the same result.

**Comment by Warlockbugs** [comment]
Should be fixed in https://github.com/cmangos/mangos-classic/commit/47664238b4e0e82ad0a6762beefcbf5e33c6b462.
