### ISSUE TITLE
[Cata] Missing semicolon in SQL file

### ISSUE THREAD

**Issue by RHOPKINS13** [cmangos/issues#627]
Missing semicolon at the end of c12868_01_mangos_spell_template.sql in cmangos-cata. Not sure what other repos may have this issue. Relatively small issue, but it's a nuisance when I've got scripts using copy /B to make full .sql database files.

**Comment by evil-at-wow** [comment]
The WoTLK repository has the same issue (see sql/updates/12670_01_mangos_spell_template.sql). It was corrected in the backport to TBC and later Classic, so these are fine.

If no one has done it in the meantime, I'll correct it one of these days when I'm at my dev machine.

**Comment by RHOPKINS13** [comment]
Thanks
