### ISSUE TITLE
[Cata] No Loot with YTDB

### ISSUE THREAD

**Issue by RHOPKINS13** [cmangos/issues#629]
Took a fresh build and loaded YTDB + Updates from http://svn2.assembla.com/svn/ytdbase/Mangos/Cataclysm/R72/. I can login, I can see NPCs and get quests, I can see creatures and kill them, but there's no loot. Log files below.

DBErrors.log: https://www.dropbox.com/s/zb7zfvwyo76tm5l/DBErrors.log?dl=1
SD2Errors.log: https://www.dropbox.com/s/vefrhd67cz2cays/SD2Errors.log?dl=1
Server.log: https://www.dropbox.com/s/jyyctuwm7ayj8cv/Server.log?dl=1

**Comment by xfurry** [comment]
I did some investigation on this.

Here is the good news:
I found the possible problem on this. It seems that the loot tables are somehow not loaded properly
The bad new:
I have no idea on how exactly, or what exactly needs to be fixed.

I only know the problem might be in one of these functions
https://github.com/cmangos/mangos-cata/blob/master/src/game/LootMgr.cpp#L93
https://github.com/cmangos/mangos-cata/blob/master/src/game/LootMgr.cpp#L214
https://github.com/cmangos/mangos-cata/blob/master/src/game/LootMgr.cpp#L1259

Poke @Dramacydal: Do you have any clue of what can be the problem with the loot?

**Comment by RHOPKINS13** [comment]
Thanks

**Comment by Ulduar** [comment]
Nice.
Thanks
