### ISSUE TITLE
Is there any way to get the rest time of a debuff of unit

### ISSUE THREAD

**Issue by kevinct** [cmangos/issues#631]
For example, if I cast a fear or polymorgh on a unit, do the system provide some function which can get the rest time of the fear or polymorgh on this unit?
Thanks a lot for your help.

**Comment by VladimirMangos** [comment]
SpellAuraHolder::GetAuraDuration()
Or something like:

AuraList const& auras = unit->GetAurasByType(SPELL_AURA_MOD_FEAR);
int32 dur = auras.empty() ? 0 : auras[0]->GetAuraDuration();

**Comment by VladimirMangos** [comment]
But like questions better ask at forum
