### ISSUE TITLE
[Classic] Gnomish Battle Chicken 

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#638]
Core 2644
Gnomish Battle Chicken ( http://db.vanillagaming.org/?spell=12906 ) - animation exists, but nothing happens

**Comment by ROKB** [comment]
bumg still bug

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/caa6b80d06c230923501ccd3fe4981091077fee3

**Comment by cala** [comment]
Now working.
