### ISSUE TITLE
[CLASSIC] Tier 1 for Hunter (Giantstalker) Bonuses Not Working

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#640]
Core 2644

The 5/8 bonus from Tier 1 for hunter (Giantstalker) does not work correctly.

What it is doing right now : increases maximum health of pet, but the health bar never fills up (so it is actually just a strange visual effect). Also the resistances are not increased at all.

What it should do : increase pet stamina by 30 and all resistances by 40.

http://db.vanillagaming.org/?search=giantstalker

I have not tested this for the Tier 2 set (Dragonstalker), but I`m pretty much sure it is bugged the same way.

http://db.vanillagaming.org/?search=dragonstalker#items

**Comment by dagochen** [comment]
Huntner T2 same problem confirmed

**Comment by ROKB** [comment]
confirm warlock same problem

**Comment by TarasHots** [comment]
Reproducable. All 4 sets(hunter's T1 and T2, warlock's T1 and T2) have broken 5/8 bonus set. Currently working on this. Only fixed resistances + small fixes when you've just tamed or summoned your pet, and aura wasn't applied at all(even no aura icon on pet).

**Comment by ROKB** [comment]
@TarasHots paladin t3 2set not work.. can you fix it?

and warlock t3 2set have some bug(almost 100%)

**Comment by TarasHots** [comment]
@ROKB I would like to) Will start with this right after T1/T2 fix

**Comment by ROKB** [comment]
@TarasHots oh thx god.. will waiting.

**Comment by jimmybrancaccio** [comment]
@Kelzior Can you confirm if this is still an issue in the latest commits?
