### ISSUE TITLE
[Classic][Quest][Seal of Ascension]

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#644]
Core 2644

Link to db - http://db.vanillagaming.org/?quest=4742

The quest giving NPC is not present ( http://db.vanillagaming.org/?npc=10296 ).
He should be disguised as an enemy mob, that mob is present.

Expected result : Should behave like https://www.youtube.com/watch?v=VVxOPiDVwNQ
Actual result : Nothing happens. The NPC is hostile even on your approach.

**Comment by cala** [comment]
This issue is supposed to be fixed since https://github.com/cmangos/mangos-classic/commit/c9f0dee2b65f706490bb59e634cd3520fff024b1
Can you confirm that the problem still persists after that update, please ? You also need to have ACID installed.

**Comment by Kelzior** [comment]
@cala Seems like fixed. Thanks
