### ISSUE TITLE
[Classic][Quest][The Pledge of Secrecy]

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#645]
Core 2644

Link to the quest : http://db.vanillagaming.org/?npc=7406
Problem : quest is not available. Quest giving NPC will complete pre-requirement quest tho this one will not become available

**Comment by Sinoxan** [comment]
This is a database problem, there are multiple prerequisite quests for this but only one is set in the database so unless you do that specific one you can't get the follow up quest, I'll push a patch to fix this to ClassicDB as soon as I get a chance.

**Comment by Kelzior** [comment]
Thanks @Sinoxan

**Comment by Muehe** [comment]
Assuming you talk about the mechanic chicken quest, did you complete all three prequests? You need to do 648, 836 and 2767 before 3721 becomes available, which is correctly set in the DB, see:

    select * from quest_template where (entry = 648 or entry = 836 or entry = 2767)

**Comment by Sinoxan** [comment]
I'll push a fix for this tomorrow just making a few notes.

Gnome Engineering: 2 Chains, Horde and Alliance
Alliance 3630, 3632, 3634 to 3640 to 3641
Horde 3635, 3637 to 3642 to 3643
Goblin Engineering: 1 Neutral Chain
Neutral 3526, 3629, 3633, 4181 to 3638 to 3639

Also need to make sure they are all QuestLevel 47, MinLevel 30 and set correct factions.

**Comment by Muehe** [comment]
`UPDATE quest_template SET RequiredRaces='178' WHERE entry='3642';`

Works fine with this, RequiredRaces was set to 77 (Alliance) for this horde quest. All other quests seem fine (DB-wise).

**Comment by cala** [comment]
This is a DB issue (only affecting Classic). See link above.
