### ISSUE TITLE
[Classic][The Prophet Skeram]

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#652]
Core 2644

The Prophet Skeram is completely bugged. http://db.vanillagaming.org/?npc=15263
First of all, you can loot his illusion copies as a normal boss, so everyone have free loot you might say.

Regards

**Comment by evil-at-wow** [comment]
I believe this has been fixed recently in scriptdev2/scriptdev2-classic@ba6a8ef623bc1fae6388d95d4e79093f5166a5e8.

**Comment by Kelzior** [comment]
Thanks
