### ISSUE TITLE
Ahn'Qiraj Questline

### ISSUE THREAD

**Issue by Fears313** [cmangos/issues#654]
There are a few buggy Quest in the big Ahn'qiraj Quests.

For example: The Wrath of Neptulon:

There is no Swirling Maelstrom so I can't spawn him.

Also the Quest: Decoy!

I can't summon the gnom. 

It would be very kind if you could fix it Smile

Thanks

Best Regards

Fears313

**Comment by jimmybrancaccio** [comment]
Closing this out as an incomplete issue. If this is still a problem please open a new issue with full details. Thanks.
