### ISSUE TITLE
[CLASSIC] Client Freezes During Some PvP Activities

### ISSUE THREAD

**Issue by yumyrather** [cmangos/issues#655]
I have found this issue on several wow servers based on cmangos. The client sometimes freezes only when pvp with the hostile faction's players. Usually, as a mage, my client freeze after my using frost nova, but other classes also may meet the same problem.
Until now, I cannot find the real reason causing this issue.
The key words are, 
1. Client freezes over several seconds,somtimes even more than half a minute.
2. Only happen when pvp with other faction
3. Sometimes, not usual
4. Use frost nova easily cause this problem.
5. Other class also meet the problem.

**Comment by AnonXS** [comment]
There were some commits related to this, could need an update, but its only reproducable in "heavy" pvp combat situations or certain npc abilities.

**Comment by Warlockbugs** [comment]
Resolved some time ago in all 3 branches.
