### ISSUE TITLE
[*Classic*] Fear + Aggro = Mob wont attack anymore

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#659]
Core 2656

Player 1 fears the mob, player 2 gets aggro and the mob wont attack you anymore.
But the player still can attack the mob.

**Comment by yyhhrr** [comment]
https://github.com/yyhhrr/portalclassic/commit/9a190eb177a75079f1f34fa69fde310c55b9a737
Maybe this will help.

**Comment by Kelzior** [comment]
Not sure about that

**Comment by Kelzior** [comment]
I will test it tonight

**Comment by Kelzior** [comment]
Yes, this did work. Thanks for the fix.
