### ISSUE TITLE
[CLASSIC] Aegis of Preservation Spell Issue

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#660]
Core 2656

http://db.valkyrie-wow.org/?item=19345

http://db.valkyrie-wow.org/?spell=23781

 The healing component of this trinket is taking 100% of my +healing. I don't know the original percentage but I do know that the trinket shouldn't make you 100% unkillable in melee for 20 secs.

**Comment by dagochen** [comment]
Patch 1.7.0
All item based self heals will no longer be effected by equipment that provides bonuses to healing. This change affects both the Arcanite Champion and the Crusader Enchantment.

http://andreasaronsson.com/2008/03/18/wow-aegis-of-preservation/
