### ISSUE TITLE
[*Classic*] PX-238 Winter Wondervolt

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#661]
Core 2656

http://db.valkyrie-wow.org/?spell=26274

The spell is getting dispelled after 7-15 sec. Should last for 30 min.

**Comment by Grz3s** [comment]
well can confirm that spell should last = 30min
ID - 26274 PX-238 Winter Wondervolt
Duration: ID (30)  1800000, 0, 1800000 - here
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0

**Comment by cala** [comment]
Somehow fixed now.
