### ISSUE TITLE
Waypoints Problem with orientation.

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#665]
On lastest rev of cmangos core all waypoints have orientation set to 100 when adding them. I posted on Cmangos website. But, I guess posting here is the best place... :)

Thanks for your work... ;)

**Comment by Schmoozerd** [comment]
yes, they should have orientation 100..

Meaning of 100 is "no orientation set"

Unluckily this is how it has been since ages, but the default value was not used this way within the db :(

**Comment by Rog360** [comment]
Thanks @Schmoozerd ! Glad to know. Now, I can get back to my Waypoints... :)
I apologize for the false report... ;)
