### ISSUE TITLE
[CLASSIC] Night Dragon's Breath and Whipper Root Tuber Cooldown Issues

### ISSUE THREAD

**Issue by yyhhrr** [cmangos/issues#666]
If you use Whipper Root or Night Dragon's Breath first,then you use Superior Healing Potion ,seems like the right cooldown.But if you use Superior Healing Potion first ,then use Whipper Root or Night Dragon's Breath,you will not allow to do that.

**Comment by Phatcat** [comment]
This issue seems to have been resolved, healing pots and whipper root/night dragon don't share cooldowns, you can use one and then the other in whatever order you want
