### ISSUE TITLE
Classic: Boats don't work properly.

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#693]
1. Upon arrival to the opposite continent, the boat disappears leaving the player stranded in the fatigue water. 
2. The Feathermoon Ferry doesn't even show up while you're waiting for it on the pier. It only appears when you're too far away to catch it.

**Comment by MarcoPolo87** [comment]
Can you please elaborate further.  After 5 hours of testing, and riding the three boats & three zeppelins (that swap continents), I was unable to reproduce the issue.of falling off any of the transports.  

As for the Feathermoon Ferry...
1) It works fine from Feathermoon Dock.
2) It does not show up when on you are standing on the Dock on the Feralas Mainland.
3) Speculation is that the ship paths outside the "loaded zone" and that would be where it may get "stuck."

The only "transport" that took a long time (that was working as intended) was the Grom'Gol zeppelin from Brill.  This zeppelin may also suffer from the same issue as the Feathermoon Dock.  It doesn't seem to reliably show up (as in time between arrivals varies).

---------------------------------------------------------------

Classic DB version 1.5.0 'The Great Swimming Pool'. For core z2656 and SD2 z2734
ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)
required_z2621_s2263_12823_04_mangos_creature

**Comment by krullgor** [comment]
i think the transport problem is mac client related, there is an existing issue open concerning this: https://github.com/cmangos/issues/issues/198 please continue discussion there
