### ISSUE TITLE
[cata] Exessive XP granted in Worgen and Goblin Starter zone

### ISSUE THREAD

**Issue by Wolf-DK** [cmangos/issues#698]
Killing mobs in starter areas will give about 1500-2000 XP.
Tested in Map 651 (Worgen) and 648 (Goblin).

This occur because areas are tagged as "CONTENT_81_85" in DBCStores.cpp
This is used in Formulas.h to set nbaseExp:
uint32 nBaseExp;
           switch (content)
           {
               case CONTENT_1_60:  nBaseExp = 45;  break;
               case CONTENT_61_70: nBaseExp = 235; break;
               case CONTENT_71_80: nBaseExp = 580; break;
               case CONTENT_81_85: nBaseExp = 1878; break;
               default:
                   sLog.outError("BaseGain: Unsupported content level %u", content);
                   nBaseExp = 45;  break;
           }

Suggested fix:
Change the sub in DBCStores.cpp:

ContentLevels GetContentLevelsForMap(uint32 mapid)
{
   MapEntry const* mapEntry = sMapStore.LookupEntry(mapid);
   if (!mapEntry)
       return CONTENT_1_60;

    if (mapid = 654)                      //654 = Worgen Starter area. 
       return CONTENT_1_60;

    if (mapid = 648)                     //648 = Goblin Starter area. 
       return CONTENT_1_60;

   switch (mapEntry->Expansion())
   {
       default: return CONTENT_1_60;
       case 1:  return CONTENT_61_70;
       case 2:  return CONTENT_71_80;
       case 3:  return CONTENT_81_85;
   }
}

**Comment by Wolf-DK** [comment]
Those dots mark the added lines and should have been plus sign (+).

/Wolf :Q

**Comment by xfurry** [comment]
Can  you please post as patch form

**Comment by Wolf-DK** [comment]
Not sure how to do this, but here goes:
http://paste2.org/WBwEDGJ5

And I have made a fork and created a proposed change as well...
https://github.com/cmangos/mangos-cata/commit/589c140f2e59ea1d28f88909e10f2a36bf1132b0

Let me know how to do this propberly if this is not the right way... sorry I am new to Git.

/Wolf

**Comment by Wolf-DK** [comment]
Figured out I needed to make a pull request, which I have done.

Do let me know if I am doing something wrong.

/Wolf
