### ISSUE TITLE
Classic Crash Log!

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#700]
Revision: * * 2665 *
Date 19:6:2015. Time 7:34 
//=====================================================
*** Hardware ***
Processor: AMD Opteron(tm) Processor 4334                 
Number Of Processors: 6
Physical Memory: 4194303 KB (Available: 4194303 KB)
Commit Charge Limit: 4194303 KB

*** Operation System ***
Windows Server 2008 R2 Service Pack 1 (Version 6.1, Build 7601)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00A275D7 02:001545D7 C:\Users\root\Desktop\_Server\Core\mangosd.exe

Registers:
EAX:00000000
EBX:01874E70
ECX:00A32D40
EDX:00000012
ESI:083AFEC8
EDI:083AFF14
CS:EIP:0023:00A275D7
SS:ESP:002B:083AFEB0  EBP:083AFEC0
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010212

Call stack:
Address   Frame     Function      SourceFile
00A275D7  00000000  FreezeDetectorRunnable::run+E7  c:\users\muzaffer\desktop\rwrealm\src\mangosd\master.cpp line 94
00A4C6C1  00000000  ACE_Based::Thread::ThreadTask+21  c:\users\muzaffer\desktop\rwrealm\src\shared\threading.cpp line 186
7138C8C5  00000000  ?invoke@ACE_OS_Thread_Adapter@@UAEKXZ+E5
7130315A  00000000  ace_thread_adapter+2A
72BB3651  00000000  _beginthreadex+1A1
72BB3861  00000000  _endthreadex+181
749633AA  00000000  BaseThreadInitThunk+12
76F49F72  00000000  RtlInitializeExceptionChain+63
76F49F45  00000000  RtlInitializeExceptionChain+36
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
00A275D7  00000000  FreezeDetectorRunnable::run+E7  c:\users\muzaffer\desktop\rwrealm\src\mangosd\master.cpp line 94
punting on symbol curtime
punting on symbol this

00A4C6C1  00000000  ACE_Based::Thread::ThreadTask+21  c:\users\muzaffer\desktop\rwrealm\src\shared\threading.cpp line 186
punting on symbol param
punting on symbol _task

7138C8C5  00000000  ?invoke@ACE_OS_Thread_Adapter@@UAEKXZ+E5

7130315A  00000000  ace_thread_adapter+2A

72BB3651  00000000  _beginthreadex+1A1

72BB3861  00000000  _endthreadex+181

749633AA  00000000  BaseThreadInitThunk+12

76F49F72  00000000  RtlInitializeExceptionChain+63

76F49F45  00000000  RtlInitializeExceptionChain+36

========================
Global Variables
	 <user defined> 'sDurabilityQualityStore$initializer$' = 92CA10
punting on symbol _Fac_tidy_reg
	 <user defined> 'sCreatureDataAddonStorage$initializer$' = 92E310

**Comment by Kelzior** [comment]
@xfurry

**Comment by evil-at-wow** [comment]
This is the freeze detection kicking in (```FreezeDetectorRunnable::run```), which causes the server to commit suicide. This is typically done so the process can be restarted by a script or another process. 

So the real question here is: why isn't the world updating any more... 
Also, what is the value of ```MaxCoreStuckTime``` in your configuration file?

**Comment by Kelzior** [comment]
Its set to 10 secs

**Comment by Kelzior** [comment]
Closing, opened a new clear one
