### ISSUE TITLE
[WOTLK] Warlock Pet Bug

### ISSUE THREAD

**Issue by Tauriella** [cmangos/issues#708]
Warlock Summon Imp don't cast  the firebolt spell, makes only melee attack
 Imp spell Blood Pact [Buff] works fine

 If you create a new character and summon your FIRST Imp thats works fine, but if your release the Imp and you summon a new Imp does not work anymore.

 I have testet with CMangos 12891/SDEV2 3141/Latest UDB with all updates

**Comment by Enverex** [comment]
No movement on this? Looks like it's still an issue.

**Comment by SilvioDoMine** [comment]
Still an issue.

**Comment by Phatcat** [comment]
Imp should not even be able to melee; maybe bump your DB team of choise to import this: https://github.com/classicdb/database/pull/869

Gonna look into this tonight.

**Comment by Phatcat** [comment]
Could you guys try updating to current master and be sure to apply all the latest db updates; I am **not** experiencing this issue on the latest cmangos wrath master using the latest udb.

**Comment by Phatcat** [comment]
Looks like the issue was not a core issue;
https://github.com/unified-db/Database/issues/231
