### ISSUE TITLE
[*Classic*] MIND CONTROL doesn't work(lack of core support?)

### ISSUE THREAD

**Issue by xfury** [cmangos/issues#710]
cmangos/mangos-classic version:z2673
scriptdev2/scriptdev2-classic version:z2734
------------------------------------------------------
all mind control(caster is unit not player)doesn't work.
sample spell:ID:13181
http://db.vanillagaming.org/?spell=13181
sample spell:ID:20604
http://db.vanillagaming.org/?spell=20604
sample spell:ID:24327
http://db.vanillagaming.org/?spell=24327
I have search for a long time and still haven't found the solution.

**Comment by Rushor** [comment]
change your name please xD
there is already an Xfurry https://github.com/xfurry :D

**Comment by cala** [comment]
Issue already discussed here: https://github.com/cmangos/issues/issues/484
Thank you.
