### ISSUE TITLE
[Classic] NPC's and Players Portrait BUG

### ISSUE THREAD

**Issue by cooler-SAI** [cmangos/issues#715]
Sometimes (specially when logg in) we have incorrected portrait visual BUG when you speak with Vendor,Trainer or any NPC, then it dissapear and come back again. I don't have any Addons, reinstall Client, reextracted all dbc's, install another client from another source - nothing changed

Core version:   [z2673]  https://github.com/cmangos/mangos-classic/commit/103e1eb12916d44981baf6b0feb2a4f6686f4b1b

![sasdas](https://cloud.githubusercontent.com/assets/812439/8732494/7b2983dc-2c06-11e5-860a-01f1f0a2d9b3.jpg)

**Comment by Rushor** [comment]
off topic:
@cooler-SAI : i love all your work to the cataclysm sais :)

**Comment by cooler-SAI** [comment]
@Rushor : thanks a lot :) use all for Trinity, your fixes in DB good too

**Comment by cooler-SAI** [comment]
any Ideas?

**Comment by jimmybrancaccio** [comment]
@cooler-SAI Can you let us know if this is still an issue in the latest commits? I don't recall it but I would love your input.

**Comment by cooler-SAI** [comment]
now all works)

**Comment by Warlockbugs** [comment]
Clientside redndering bug, no relation to the server. Looks like it was running under WINE. I've seen similar texture issues in other Blizzard-made games.
