### ISSUE TITLE
[Vanilla] Weird Crash coming from AQ40!

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#719]
Lastest Core + SD2

Also did test with; (map.cpp line 53)

     delete i_data;
     i_data = NULL;

Still getting the same error

![zzzz](https://cloud.githubusercontent.com/assets/9686159/8812884/2bc5144e-2fff-11e5-8686-128a50e7020a.png)
![map531](https://cloud.githubusercontent.com/assets/9686159/8812885/2be44b16-2fff-11e5-9b0a-cf29edd24c19.png)
![gfhghf](https://cloud.githubusercontent.com/assets/9686159/8812886/2cbecc14-2fff-11e5-9da6-727d15a0fb11.png)
![eezaeaz](https://cloud.githubusercontent.com/assets/9686159/8812888/2e6a1370-2fff-11e5-9f23-017ea1a0a3e1.png)

**Comment by Kelzior** [comment]
@xfurry 
@cala

**Comment by xfurry** [comment]
hi
what did you do to get the crash?

**Comment by Kelzior** [comment]
Some were raiding.. add me on skype if you want

**Comment by xfurry** [comment]
Which boss?

**Comment by xfurry** [comment]
I think I have some idea...
Did it happen at the point when the instances were supposed to be reset?

**Comment by Kelzior** [comment]
Nope

**Comment by Kelzior** [comment]
Players were at prophet skeram, (logs say BugTrio boss?)

**Comment by Kelzior** [comment]
oh wait, yes

**Comment by Kelzior** [comment]
yes @xfurry

**Comment by xfurry** [comment]
I thought that this was fixed on master some time ago...
Wasn't the fixed backported? Poke @cala or @evil-at-wow

**Comment by cala** [comment]
I don't remember such a commit in Classic, but I can be wrong (I don't remember all of them). If you can point out when it was done on master or at least by whom, I could investigate if it was backported.

**Comment by cala** [comment]
Note: when I say "when", I mean what year and if possible what part of the year. I don't need an exact date. :wink:

**Comment by xfurry** [comment]
I'm talking about this commit:
https://github.com/cmangos/mangos-wotlk/commit/f9cbf321dd10b60f7e7a5c4e53024c0ec47c833f

**Comment by cala** [comment]
Then, it was backported to Classic last fall: https://github.com/cmangos/mangos-classic/commit/a6a271078f724ec542469b40eca0bc9b88bf70ca

**Comment by xfurry** [comment]
Then, maybe it doesn't work for classic.
Would you be able to test it? (I don't have Classic client right now)

**Comment by Kelzior** [comment]
got another crashlog, possibly the same problem. http://pastebin.com/aesMFAqv

**Comment by Kelzior** [comment]
bump @cala

**Comment by cala** [comment]
Sorry. Quite busy at the moment. I'll test it when I can spare the time.

**Comment by Kelzior** [comment]
bump

**Comment by xfurry** [comment]
Well, this clearly looks like a map unload / reset problem.
When the map is unloaded https://github.com/cmangos/mangos-classic/blob/master/src/game/MapManager.cpp#L195  something goes wrong before this line https://github.com/cmangos/mangos-classic/blob/master/src/game/Map.cpp#L53 and server crashes.

Not sure if players are removed before that.
Maybe this function isn't called before unloading: https://github.com/cmangos/mangos-classic/blob/master/src/game/Map.cpp#L1485
You should put some debug messages before so we can check what is actually happening.

**Comment by Kelzior** [comment]
Crashlogs or??

**Comment by Kelzior** [comment]
? @xfurry

**Comment by xfurry** [comment]
Sorry, I don't have classic client, so I can't test this.
Poke @cala  and @evil-at-wow as they are more familiar with the old clients.

**Comment by cala** [comment]
As I said, I'm busy at the moment. I can give it a look on monday.

**Comment by Kelzior** [comment]
Alright thanks

**Comment by Kelzior** [comment]
Let me know if I can do anything

**Comment by cala** [comment]
As for now, I could not reproduce the issue on Classic core. Every raid reset (AQ40, MC, BWL) had the players teleported to their binding location. I'll try other settings. 
@Kelzior : does this still happen if you force reset the raid by running `.server resetallraid` in command line?

**Comment by Kelzior** [comment]
Nope does not happen. I closed aq40 for like 1 week now and im not getting those crashes anymore. So its smt from aq40 for sure

**Comment by xfurry** [comment]
Is this only for AQ40? This is really weird.
I will check again, maybe there is some bug in the instance...

**Comment by cala** [comment]
Very strange indeed. By any chance, did you change the output location of the instance in the database (i.e. where the players are supposed to be teleported when they zone out of the instance or disconnect while being in it)?
It should be:

id  | target map | target_position_x | target_position_y | target_position_z | target_orientation
--- | -------------- | --------------------- | ---------------------- | --------------------- | -----------------------
4012 | 1 | -8242.67 | 1992.06 | 129.072 | 0 

What could help to understand: does it happens if players never disconnect while being in the instance (this means that there is no offline players in AQ40 when it resets) ?

**Comment by Kelzior** [comment]
the output location is the same.

I will test "offline players in AQ40 when it resets" and report you later

**Comment by Schmoozerd** [comment]
related to the log itself:
It looks like delete i_data creates the crash.
i_data is of type ScriptedInstance*

Might be stupid, but is there a reason why in the aq40.h file is no destructor listed (contrary to other scripted instances)

Also in theory there might be a virtual missing in some positions;
somebody would need to check the exact meaning of the virtual inheritance for destructors, i do not remember them in detail.

**Comment by Kelzior** [comment]
So I tested it on the test realm yesterday, I logged out in AQ40 (saved) (should reset after +-15h) and the server crashed around 6am

http://pastebin.com/bFatii4e

**Comment by Kelzior** [comment]
and the reset didnt me teleport out of AQ40. Not sure about this since i was in AQ40 with a GM char.

**Comment by Kelzior** [comment]
but when it resets in naxx, it does teleport you.

**Comment by Schmoozerd** [comment]
you not having been teleported might be the source as well as the reason for the crash:
* source: Player in map -> deletion not properly doable. Might be related to AQ40 having always had some issues with the "where" information of a player
*result: Map unload crashes for some other reason -> transaction to reset the player's DB position not commited.

Can you check adding the deconstructor into AQ40 header file (Sd2) and then recompiling?

**Comment by Kelzior** [comment]
Will try it

**Comment by Kelzior** [comment]
I added the deconstructor to the file, recompiled and I got this crash ~2hours before the reset.

http://pastebin.com/ztv6FvHt
As you can see its coming from AQ40 again.

Now I'm waiting for the reset, (1h left). Will report the rest tomorrow

**Comment by Kelzior** [comment]
Aaaand it did crash again (at reset time) http://pastebin.com/N2PBFbyS

**Comment by Kelzior** [comment]
but the server is also "freezing" for a long time when the Raid resets are happening. Try .server res and wait some mins. You will see that it will freeze for some time. So more saved raids = more server freeze. Thats why I also get "FreezeDetector" crashs. You guys really should look at this.

**Comment by Schmoozerd** [comment]
Actually i found a possible issue in the SD2's AQ40 code:

m_auiEncounter[9] must be removed (twice) from ScriptDev2\scripts\kalimdor\temple_of_ahnqiraj\instance_temple_of_ahnqiraj.cpp

This could result in memory corruption  however i could not reproduce a crash.

**Comment by Kelzior** [comment]
Alright thanks! I will remove that line and try again

**Comment by Kelzior** [comment]
seems fixes, closing. Thanks alot

**Comment by Kelzior** [comment]
Schmoozerd referenced this issue from a commit in scriptdev2/scriptdev2

Forgot scriptdev classic? :)

**Comment by evil-at-wow** [comment]
That will be taken care of when @xfurry does the periodical batch of backporting from WoTLK to TBC to Classic. 

I'll gently remind him, because it's been a fair while since the last one happened in the ScriptDev2 repositories.

**Comment by xfurry** [comment]
Which raises the question: would it be good to have some extra help with the SD2 backrpots for TBC and Classic?
Currently I am unable to do any Classic or TBC backports as I don't have the setup for this.
I only use 3.x and 4.x recently, so I need to download and setup the old cores in order to do backports and check the builds.
So I guess that you'll have to wait for a few more days...

**Comment by krullgor** [comment]
i can do the backports for you later today, should i send a pull request?

**Comment by xfurry** [comment]
Backports are not pull requests...

**Comment by krullgor** [comment]
yeah but i dont have access to scriptdev repos, i was thinking about how i can provide them to you

**Comment by xfurry** [comment]
Well the idea was to create a group in SD2 that will have access to do backports to TBC and Classic.
But I can't do that as only @Schmoozerd and @NoFantasy  are the only admins on SD2

**Comment by Schmoozerd** [comment]
please define whom to add ;)

**Comment by xfurry** [comment]
I don't know...
First we need a list of candidates who are willing to do this.

I was thinking of @evil-at-wow and @cala as the most experienced ones, because they are also doing this for core already.
We can also consider other people if the first two are not available or unwilling to take this responsibility.

**Comment by krullgor** [comment]
![I volunteer as tribute](https://readingwithdragons.files.wordpress.com/2015/02/i-volunteer-as-tribute-2.gif)

**Comment by Schmoozerd** [comment]
it neither fun nor games :P

**Comment by cala** [comment]
Since I develop for Classic and push to master I already have local core and SD2 repositories along with clients set for either WotLK, TBC and Classic.

So, I'll be happy to do backports for SD2 Classic and even TBC if no one has time to do it. :smile:

**Comment by evil-at-wow** [comment]
I can do the TBC backports for SD2 if you want. The fact that I do (most of) the backports for the core already is not really a problem. In fact, it can be an advantage because I can time backports for both projects to make sure that things keep building when SD2 changes require more recent core revisions.

I don't have loads of time available, but the backports shouldn't take ages. Looking at the commits in master, there are like ten commits a month (and some don't even apply to TBC/Classic), so we should be able to handle that.

**Comment by cala** [comment]
> I can do the TBC backports for SD2 if you want. The fact that I do (most of) the backports for the core already is not really a problem. In fact, it can be an advantage because I can time backports for both projects to make sure that things keep building when SD2 changes require more recent core revisions.

> I don't have loads of time available, but the backports shouldn't take ages. Looking at the commits in master, there are like ten commits a month (and some don't even apply to TBC/Classic), so we should be able to handle that.

Like my evil friend above. Just replace "TBC" by "Classic", and I'm your man for the SD2 Classic backports.

I could even do the TBC backports sometimes when evil-at-wow is busier than me (we are toughly competiting on the "over-busy" thing :wink: ).
