### ISSUE TITLE
[CLASSIC] Grounding Totem Issues

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#722]
spell id : 8177
Actual : Totem absorbs warrior charges and intercepts, probably some other abilities he should not consume.

Expected : Should only consume spells.

**Comment by vovk** [comment]
Look here. This function completly wrong.

Unit* Unit::SelectMagnetTarget(Unit* victim, Spell* spell, SpellEffectIndex eff)
{
    if (!victim)
        return NULL;

    // Magic case
    if (spell && (spell->m_spellInfo->DmgClass == SPELL_DAMAGE_CLASS_NONE || spell->m_spellInfo->DmgClass == SPELL_DAMAGE_CLASS_MAGIC))
    {
        Unit::AuraList const& magnetAuras = victim->GetAurasByType(SPELL_AURA_SPELL_MAGNET);
        for (Unit::AuraList::const_iterator itr = magnetAuras.begin(); itr != magnetAuras.end(); ++itr)
        {
            if (Unit* magnet = (*itr)->GetCaster())
            {
                if (magnet->isAlive() && magnet->IsWithinLOSInMap(this) && spell->CheckTarget(magnet, eff))
                {
                    if (SpellAuraHolder* holder = (*itr)->GetHolder())
                        if (holder->DropAuraCharge())
                            victim->RemoveSpellAuraHolder(holder);
                    return magnet;
                }
            }
        }
    }
    // Melee && ranged case
    else
    {
        AuraList const& hitTriggerAuras = victim->GetAurasByType(SPELL_AURA_ADD_CASTER_HIT_TRIGGER);
        for (AuraList::const_iterator i = hitTriggerAuras.begin(); i != hitTriggerAuras.end(); ++i)
        {
            if (Unit* magnet = (*i)->GetCaster())
            {
                if (magnet->isAlive() && magnet->IsWithinLOSInMap(this) && (!spell || spell->CheckTarget(magnet, eff)))
                {
                    if (roll_chance_i((*i)->GetModifier()->m_amount))
                    {
                        if (SpellAuraHolder* holder = (*i)->GetHolder())
                            if (holder->DropAuraCharge())
                                victim->RemoveSpellAuraHolder(holder);
                        return magnet;
                    }
                }
            }
        }
    }

    return victim;
}

You can remove spell->m_spellInfo->DmgClass == SPELL_DAMAGE_CLASS_NONE and also remove all "else" state. It would fix intercept & charge but not fully fix grounding totem. Good luck.

**Comment by jimmybrancaccio** [comment]
@Kelzior @Ve1vet Do you know if this is an issue in the latest commits?

**Comment by killerwife** [comment]
I changed these functions, so this should be fixed now.

**Comment by cala** [comment]
I’m pretty sure @killerwife fixed this with his magnetized spells/objects commits.
