### ISSUE TITLE
Vanilla - Elementium Bar

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#726]
Bug: Npc missing spell.
Name: Master Elemental Shaper Krixix
Npc ID: 14401
Zone: Blackwing Lair

What happens: You cant smelt elementium since the NPC doesn't have spell/skill: Smelt Elementium.
What should happend: To be learned the skill, you must mind control him and than use Smelt Elementium.
Spell ID: 22968

**Comment by Schmoozerd** [comment]
That is a db thing.
creature_template_spells you need to simply add 22968

poke @cala

**Comment by Tobschinski** [comment]
https://github.com/classicdb/database/commit/9ccdd290a3cb463a30b972515bb8273752d0ea9e
