### ISSUE TITLE
Spell 51655 is not always creating the item as expected.

### ISSUE THREAD

**Issue by evil-at-wow** [cmangos/issues#732]
Core revisions tested: WoTLK (cmangos/mangos-wotlk@3d9fb306) and TBC (cmangos/mangos-tbc@81249c6a).

When testing the backport of the WoTLK commit, I noticed that some 'Weak Alcohol' spells create the [Empty Brew Bottle] as expected, while others do not.

Test session to reproduce:
- `.cast 42263` results in the item, [Empty Brew Bottle], being created. So this is OK.
- `.cast 42261` results in the item _not_ being created. Instead I get a red 'Interrupted' on screen, that prevents the creation.

**Comment by virusav** [comment]
Discussion and patch: https://github.com/cmangos/issues/issues/562
Description of problem, etc.: https://github.com/cmangos/issues/issues/562#issuecomment-71360870
