### ISSUE TITLE
Spells Required for Quest 11174 Not Working in TBC

### ISSUE THREAD

**Issue by evil-at-wow** [cmangos/issues#734]
The spells required for this quest were implemented in cmangos/mangos-wotlk@618dc049, and they seem to work when I test with my WoTLK client.

However, when I tested the backport of this commit to the TBC repository some time ago, none of this seemed to work, so the quest is not working at all in my TBC core. Let's have a closer look to find out what's going on.

Note: I've skipped this commit for the time being because adding stuff that doesn't work at all is pretty pointless.

**Comment by xfurry** [comment]
@evil-at-wow I remember that on TBC the spell logic is slightly different.
We need to check this again and amend the commit as required.

**Comment by jimmybrancaccio** [comment]
@evil-at-wow or @xfurry Do we know if this is still an issue with the latest code?

**Comment by evil-at-wow** [comment]
I don't know, but I'll try to test it again one of these days.

**Comment by jimmybrancaccio** [comment]
Awesome, thanks @evil-at-wow!

**Comment by evil-at-wow** [comment]
I just tested this again, and it seems to be working as intended now. A search in the git history confirms this is not a coincidence: it was fixed a while ago by cmangos/mangos-tbc@b169db77f2fdc4fc81fc198408bb940057e9eb10.
