### ISSUE TITLE
[Classic] Client Freezes

### ISSUE THREAD

**Issue by cooler-SAI** [cmangos/issues#737]
I have Client Freezes 3-4 seconds, 2 people Online, Windows 8.1, x64 build
On mangos-onedon't have any problems.
All settings set to Low in Video
Rev:
https://github.com/cmangos/mangos-classic/commit/103e1eb12916d44981baf6b0feb2a4f6686f4b1b

**Comment by cyberium** [comment]
thank you, this bug is already on issue list.
-> https://github.com/cmangos/issues/issues/655
