### ISSUE TITLE
Small Weather System Bug

### ISSUE THREAD

**Issue by tarwyn** [cmangos/issues#741]
So it started raining in Dun Morogh and I figured that can't be right. DB checked out, weather loading code checked out. Then I stumbled on this here bit:

weather.cpp@149:
~~~
    // At this point, only weather that isn't doing anything remains but that have weather data
    uint32 chance1 =          m_weatherChances->data[season].rainChance;
    uint32 chance2 = chance1 + m_weatherChances->data[season].snowChance;
    uint32 chance3 = chance2 + m_weatherChances->data[season].stormChance;

    uint32 rnd = urand(0, 99);
    if (rnd <= chance1)
        m_type = WEATHER_TYPE_RAIN;
    else if (rnd <= chance2)
        m_type = WEATHER_TYPE_SNOW;
    else if (rnd <= chance3)
        m_type = WEATHER_TYPE_STORM;
    else
        m_type = WEATHER_TYPE_FINE;
~~~

"No chance" of a weather type is defined as 0, but the urand() statement can also return 0. Which means that if a player is in a zone with no chance of rain and the random number generator provides a 0, it will rain anyway, simply because it's the first check and will be true.

urand(1,100) should fix this (or 1 to 99 if somebody sees a reason why rnd can't be 100).

**Comment by VladimirMangos** [comment]
Fix commited in https://github.com/cmangos/mangos-wotlk/commit/5ef2f17b52fddc5e3a7faf6d67dc536592f9962b . Thank you.

**Comment by evil-at-wow** [comment]
Excellent catch! :+1:
