### ISSUE TITLE
[CLASSIC] Totem of Life is Not Working at All

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#745]
https://db.valkyrie-wow.org/?item=22396

"Equip: Increases healing done by Lesser Healing Wave by up to 80."

Does not work at all.

**Comment by jimmybrancaccio** [comment]
@Kelzior Is this still an issue with the latest versions?

**Comment by cala** [comment]
Poking @killerwife but I think he fixed this mechanics earlier this year.

**Comment by killerwife** [comment]
@cala doublecheck this:
select * from spell_affect where entry IN(27855);
'27855', '0', '128'
tbc-db has it fixed indeed

**Comment by cala** [comment]
The SQL change was indeed missing (not yet ported, probably) from Classic DB. This is now fixed (applied and tested in-game).

**Comment by cala** [comment]
@jimmybrancaccio by the way: thanks for changing the colour for most of the labels: there are more readable (and less agressive) in my opinion.
