### ISSUE TITLE
classic : drain soul

### ISSUE THREAD

**Issue by ROKB** [cmangos/issues#748]
Drain Soul cant cast this together, they interrupt each other. Possible another stacking 
#405

**Comment by xfury** [comment]
all channel spell has this bug. i have found that other core has solved this problem




     SpellEntry const* aurSpellInfo = Aur->GetSpellProto();
 
     spellEffectPair spair = spellEffectPair(Aur->GetId(), Aur->GetEffIndex());
-
-    bool stackModified=false;
-    // passive and persistent auras can stack with themselves any number of times
+    bool stackModified = false;  
+
+    // Handle aura stacking down below...
     if (!Aur->IsPassive() && !Aur->IsPersistent())
     {
         for (AuraMap::iterator i2 = m_Auras.lower_bound(spair); i2 != m_Auras.upper_bound(spair);)
         {
             Aura* aur2 = i2->second;
-            if (aur2->GetCasterGUID() == Aur->GetCasterGUID())
-            {
-                if (!stackModified)
-                {
-                    // replace aura if next will > spell StackAmount
-                    if (aurSpellInfo->StackAmount)
-                    {
-                        // prevent adding stack more than once
-                        stackModified=true;
-                        Aur->SetStackAmount(aur2->GetStackAmount());
-                        if (uint32(Aur->GetStackAmount()) < aurSpellInfo->StackAmount)
-                            Aur->SetStackAmount(Aur->GetStackAmount()+1);
-                    }
-
-                    // Allow mongoose procs from different weapon stacks
-                    if (Aur->GetId() == 28093 || Aur->GetId() == 20007)
-                    {
-                        if (Aur->GetCastItemGUID() != i2->second->GetCastItemGUID())
-                        {
-                            i2++;
-                            continue;
-                        }
-                    }
-
-                    RemoveAura(i2,AURA_REMOVE_BY_STACK);
-                    i2 = m_Auras.lower_bound(spair);
-                    continue;
-                }
-            }
-            switch(aurSpellInfo->EffectApplyAuraName[Aur->GetEffIndex()])
-            {
-                // DOT or HOT from different casters will stack
-                case SPELL_AURA_PERIODIC_DAMAGE:
-                case SPELL_AURA_PERIODIC_HEAL:
-                case SPELL_AURA_PERIODIC_TRIGGER_SPELL:
-                case SPELL_AURA_PERIODIC_ENERGIZE:
-                case SPELL_AURA_PERIODIC_MANA_LEECH:
-                case SPELL_AURA_PERIODIC_LEECH:
-                case SPELL_AURA_POWER_BURN_MANA:
-                case SPELL_AURA_OBS_MOD_MANA:
-                case SPELL_AURA_OBS_MOD_HEALTH:
-                    ++i2;
-                    continue;
-            }
-            RemoveAura(i2,AURA_REMOVE_BY_STACK);
-            i2=m_Auras.lower_bound(spair);
-            continue;
-        }
-    }
-
+            if (aur2 && !stackModified && aur2->GetId() == Aur->GetId() && aurSpellInfo->StackAmount)
+             if (uint32(aur2->GetStackAmount()) < aurSpellInfo->StackAmount)
+             {
+                 // Allow mongoose procs from different weapon stacks
+                 if (Aur->GetId() == 28093 || Aur->GetId() == 20007 && Aur->GetCastItemGUID() != i2->second->GetCastItemGUID())
+                 { i2++; continue; }
+				 
+                 // Increment aura's stack, one stack per one call
+                 Aur->SetStackAmount(aur2->GetStackAmount()+1);
+                 stackModified = true;
+
+                 // Existing aura will be replaced with the newly created one 
+                 RemoveAura(i2,AURA_REMOVE_BY_STACK);
+                 i2 = m_Auras.lower_bound(spair);
+                 continue;
+             }
+             // Do not let the stack size exceed the maximum stack limit
+             // Insteed of adding a new stack, just reset the duration time
+             else 
+             { 
+                 aur2->SetAuraDuration(aur2->GetAuraMaxDuration());
+                 aur2->UpdateAuraDuration();
+                 delete Aur; return false; 
+             }
+             ++i2;
+        }
+    }
     // passive auras stack with all (except passive spell proc auras)
     if ((!Aur->IsPassive() || !IsPassiveStackableSpell(Aur->GetId())) &&
         !(Aur->GetId() == 20584 || Aur->GetId() == 8326))



this code fix this.but it is use on TC code.

**Comment by ROKB** [comment]
@xfury where put in this code? i dont know....
where put in(plus) or where put out(remove)

**Comment by xfury** [comment]
sorry.i don't know how to manager the code here.

**Comment by ROKB** [comment]
@xfury can u transfer cmangos code?.. maybe cant?

**Comment by ROKB** [comment]
maybe aur2 wotlk code?

**Comment by xfury** [comment]
yes .it works well on TC code.  i have already tried to transfer to cmangos code. but failed.

**Comment by ROKB** [comment]
hm... cant  fix now?

**Comment by vovk** [comment]
@xfurry TC core rework stacking auras in TBC, there is absolutely different code.
@ROKB code with stacking auras should be completely reworked. At this time all you can do - add hack fixes for stacking, but even in this case it may not work...

**Comment by ROKB** [comment]
@vovk so.. fundamental problem's not solved?
can you show me hack fix code?

**Comment by Warlockbugs** [comment]
Fixed in:
https://github.com/cmangos/mangos-tbc/commit/f14a867aa666df8869f9cf8d37ae654389d35ba9
https://github.com/cmangos/mangos-classic/commit/0206d01e4c31ae1a0795c191f60615bb25829277
