### ISSUE TITLE
[Classic] Warden Anticheat

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#750]
Not a bug report but a very usefull feature,
Warden for 1.12.1

https://github.com/mangoszero/server/commit/29c30bd62095b4a5061747835966c2739bb7bd77
https://github.com/mangoszero/server/tree/develop21/src/game/Warden

Would be nice if someone has time to add this for cmangos-classic

Regards

**Comment by Fabi** [comment]
warden is just useless... like any other client side anticheat

**Comment by cyberium** [comment]
Its not an issue please use forum for this case.
