### ISSUE TITLE
[Wotlk] Quest: The hunt is on

### ISSUE THREAD

**Issue by Argonn** [cmangos/issues#751]
While doing the alliance quest in the Valiance Keep you need to use the item before you should be able to 'unmask' the npcs. But now you can talk to them before using the item, and you will instant-finish your objective, instead of having to fight them (they dont even start the small scene they used to make)

Quest information:
Vindicator Yaala wants you to use the Oculus of the Exorcist in three different locations in Valiance Keep to uncover and defeat Cult of the Damned members.
Quest:
http://www.wowhead.com/quest=11794/the-hunt-is-on
Quest item:
http://www.wowhead.com/item=35125/oculus-of-the-exorcist
Video:
https://www.youtube.com/watch?v=pLUzRDqLfeM

**Comment by xfurry** [comment]
Please report all quests here: https://github.com/unified-db/Database/issues
If core or SD2 fix is required, the DB devs will inform us.

**Comment by Argonn** [comment]
will do,

**Comment by Argonn** [comment]
Moved to https://github.com/unified-db/Database/issues/116
