### ISSUE TITLE
Recastnavigation folder out of date

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#755]
This folder needs to be brought in line with https://github.com/memononen/recastnavigation in all cores. Its missing some readmes, configs, warnings, samples, font etc. Tried to do it myself but travisCI said there is a problem.

**Comment by cyberium** [comment]
Its never an easy task to update a dependency ;)
Its good idea to update that critical one btw, i'll get on it when i'll had time.
Howewer its not an issue so i'll close this.
