### ISSUE TITLE
'MoveMapGen --debugOutput true' is Not Working Properly

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#757]
Lets say I execute following command MoveMapGen.exe 530 --debugOutput true
I should get .obj files for whole outland, yet I get a small fraction of them. The only way to get all of them is to manually generate them using --tile [xx,yy]

**Comment by namreeb** [comment]
Which version are you using?

**Comment by killerwife** [comment]
Mangos-tbc both compiled one, and precompiled one.
