### ISSUE TITLE
[Classic] Client crash when accepting quests 

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#761]
Quests:
NPC
Quartermaster Miranda Breechlock - 11536

Epic Armaments of Battle - Friend of the Dawn - 9222
Epic Armaments of Battle - Honored Amongst the Dawn - 9224
Epic Armaments of Battle - Revered Amongst the Dawn - 9225
Epic Armaments of Battle - Exalted Amongst the Dawn - 9228

The Perfect Poison" ID: 9023 from npc Dirk Thunderwood ID: 16091

**Comment by Laizerox** [comment]
These quests have "QuestTimer?"

**Comment by evil-at-wow** [comment]
I don't think the "Epic Armaments of Battle" quest series has timers. They are basically just trading a bunch of reputation tokens for an epic item.

**Comment by cala** [comment]
They don't have timer and I'm unable to reproduce the issue (no crash for me). So we need a bit more details on the matter.

**Comment by cyberium** [comment]
not reproducible
