### ISSUE TITLE
classic : Reckoning

### ISSUE THREAD

**Issue by ROKB** [cmangos/issues#767]
Reckoning can have max 5stack but now only 1stack..

**Comment by SatyPardus** [comment]
Yep. It only stacks once. Should be able to get 4 stacks aka 5 hits on next attack. Any way to change this per code? I was expirimenting a little bit and tried to set the StackAmount of the SpellEntry, but it is all constant. So is there no was to change that easly?

**Comment by sidsukana** [comment]
https://github.com/anathemareborn/core/commit/65a6735f4542b95b1b4a664751507ace8b4c4cf7
but I doubt that Mangos take it solution)

**Comment by SatyPardus** [comment]
Oh that looks good. I gonna test that asap

**Comment by jimmybrancaccio** [comment]
Closing this out as an incomplete issue. If this is still a problem please open a new issue with full details. Thanks.
