### ISSUE TITLE
[classic] Characters move out of map. Don't aggro, or reset.

### ISSUE THREAD

**Issue by trihugger** [cmangos/issues#768]
In noticed this on the start up zone for orcs/trolls. 

Inside the cave, inside the chambers where the pick is, and down to where you kill the mob for the medallion, i notice:

1) The mobs will reset if you move back a few steps. 
2) Some mobs will not engage if you are range.
3) Others, you have to be really on top of them for them to aggro.
4) Mobs will sometimes go underground or above the chamber. (this also happened to me on the Tauren starting zone, near the thornchief area.)

Could this be a vmap issue?

Tri

**Comment by killerwife** [comment]
try .mmap path and post screenshot of where it happens.

**Comment by trihugger** [comment]
I used the .mmap, and I have some screenshots to see if we can find anything.









![wowscrnshot_100415_110934](https://cloud.githubusercontent.com/assets/14881238/10268599/d8d1893a-6a8b-11e5-88e7-e32cda3dcf04.png)
![wowscrnshot_100415_111429](https://cloud.githubusercontent.com/assets/14881238/10268601/d8d1cdd2-6a8b-11e5-9fd2-2a6b1c1f42b2.png)
![wowscrnshot_100415_110601](https://cloud.githubusercontent.com/assets/14881238/10268600/d8d19e8e-6a8b-11e5-9cc4-adbaa8df8625.png)
![wowscrnshot_100415_110604](https://cloud.githubusercontent.com/assets/14881238/10268602/d8d21fb2-6a8b-11e5-90db-d3e41b8d3ba9.png)
![wowscrnshot_100415_110606](https://cloud.githubusercontent.com/assets/14881238/10268603/d8d423c0-6a8b-11e5-91ea-22f90dd19359.png)
![wowscrnshot_100415_110846](https://cloud.githubusercontent.com/assets/14881238/10268604/d8d57306-6a8b-11e5-939a-e684ec2e4b83.png)
![wowscrnshot_100415_110850](https://cloud.githubusercontent.com/assets/14881238/10268605/d8fe2558-6a8b-11e5-9fda-a6df659bc1b2.png)
![wowscrnshot_100415_110928](https://cloud.githubusercontent.com/assets/14881238/10268606/d970944e-6a8b-11e5-9bf9-91a2ac11070e.png)

**Comment by Grz3s** [comment]
im glad ... that someone else reported this issue... 
I reported this long time ago...  but.. it was forgotten...
First .. this is not only Classic -- (happens in WoTLK and im sure TBC also)
They're lots of places where this werid thing happens...(i could give here some examples, but this one will be enough)
first thought - was mmaps... but now i know... that mmaps only holds them on the ground... and real problem must be map itself (smth with extractor - im sure ppl who worked on maps vmaps and mmaps could say smth here)
You can see what happens to these creatures if we will use "Force mmaps OFF" flag for them.
https://youtu.be/VSXoeJUeizk

Im sure that @cyberium with his briliant graphic program:
http://cmangos.net/thread-88.html?highlight=navmesh
... could tell us more whats wrong here.. and if this problem can be solved...

**Comment by Laizerox** [comment]
Problem is in invalid height.

For some reason map is trying to get surface height instead of ground and sometimes if there is dungeon below the ground it's trying to get that z.

This results in long and invalid path and returns PATH_ICOMPLETE if I remember correctly.

**Comment by BeerfishWoW** [comment]
Charging these mobs could furthermore result in falling through the floor.

**Comment by cyberium** [comment]
i investigated a lot this bug, something is wrong in BIH files for any reason. I havent been able to found the cause till yet but its seem that there is clearly a zone that have no data.
You can see it here between the pink lines

![alt text](http://i.imgur.com/PNU6yCD.jpg "Zonz without data")


So this require more work and skill than i have right now. If somebody want to help ;)

**Comment by BeerfishWoW** [comment]
@cyberium What tools are you using to analyze the areas in WoW?

**Comment by cyberium** [comment]
http://cmangos.net/thread-88-post-41309.html#pid41309 ;) renewed the link

**Comment by Grz3s** [comment]
they're many places ... with same problem...
- cave in Shadowmoon Valley
- Place where Akama is hidden etc...

**Comment by Rushor** [comment]
could someone try to disable the mmaps for these creatures and retest them?

**Comment by Grz3s** [comment]
https://youtu.be/VSXoeJUeizk <--- this avi shows what happens when MMAPS are Disabled.

**Comment by Rushor** [comment]
hmkay well then maybe disabling the pathfinding

**Comment by cyberium** [comment]
This bug have nothing to do with mmap. Its a VMAPS bug.
For an unknown bug there is no data returned for theses specifics places.
From my investigation, there is a problem either in BIH generation or in BIH request. Unfortunaly these code are pretty hard to read...
