### ISSUE TITLE
classic : Ghostly Strike

### ISSUE THREAD

**Issue by ROKB** [cmangos/issues#769]
dodge not work.

**Comment by Rushor** [comment]
spellids? links?

**Comment by ROKB** [comment]
@Rushor you don't have spell txt?

**Comment by Rushor** [comment]
a nice bugreports always contains spellids from wowhead or other sides

**Comment by jimmybrancaccio** [comment]
Closing this out as an incomplete issue. If this is still a problem please open a new issue with full details. Thanks.
