### ISSUE TITLE
[Classic] The Dead Fields quest

### ISSUE THREAD

**Issue by Etherstream** [cmangos/issues#775]
Killing Rot Hide Gladerunners (id 1772) and Rot Hide Mystics (id 1773) for the quest The Dead Fields (id 437) should have a chance to spawn Nightlash (id 1983) instead of her just being permanently there.

**Comment by Muehe** [comment]
The summon is mentioned as of [September 3, 2006](http://wowwiki.wikia.com/wiki/Nightlash?direction=next&oldid=208919) on WoWWiki, which is before [2.x Launch](http://wowwiki.wikia.com/wiki/Patches/2.x), and is still in the [current article revision](http://wowwiki.wikia.com/wiki/Nightlash), so the bug probably applies to all versions.

**Comment by Etherstream** [comment]
The quest was removed in [Cataclysm world revamp in patch 4.0.3a](http://wow.gamepedia.com/Quest:The_Dead_Fields) and [Nightlash became a rare mob](http://www.wowhead.com/npc=46981/nightlash) after that. Probably applies to all versions before Cataclysm.

**Comment by cala** [comment]
Are you sure she is summoned? Comments on wowhead seem to indicates this is urban legend. I check the spells DBC also and there is none related to her spawning (while it is usually how mobs summon another one).

So before doing something about it (probably via ACID), I'd like to be sure.

**Comment by Etherstream** [comment]
I'm not even sure anymore. I remember doing this on a pretty dead retail server with no one around in Silverpine Forest and Nightlash wasn't there. After killing a few Rot Hides (or just being around) she did spawn. At least [the highest rated comment](http://www.wowhead.com/npc=1983/nightlash#comments:id=210844) states that it would work how I always thought it worked.

**Comment by killerwife** [comment]
Well she is supposed to be there only if you summoned her by killing. In case she was already there, thats because someone failed to kill her, OR was just running around randomly without having the qst. Tho I cant confirm whether only people who have the q can spawn her.

**Comment by cala** [comment]
The Nightlash AI/DB script is very incomplete, I'll rewrite it later.
I'm closing the issue here as it is not related to core at all. I'll track it elsewhere.
