### ISSUE TITLE
classic : fishing

### ISSUE THREAD

**Issue by ROKB** [cmangos/issues#776]
player use fishing skill, motion is fine.
but casting bar's missing(suddenly)
so cant fishing...
@cyberium  check plz 8a8

**Comment by cyberium** [comment]
i dont see any problem -> https://youtu.be/ekKqbfaS_jk

**Comment by ROKB** [comment]
Make new character and learn fishing. And process problem.

**Comment by cyberium** [comment]
Can you do some video? Could someone other confirm this?
I cant replicate.

**Comment by ROKB** [comment]
@cyberium um.. i cant right now.
hm.. will be upload video

**Comment by ROKB** [comment]
@cyberium 
https://youtu.be/bjYEXRSzESg check plz :P

**Comment by cyberium** [comment]
I cannot reproduce.
Please go to mangosd.conf file and be sure
LogLevel = 3
LogFilter_SpellCast = 0

Then try to fish and send me the log you have.
Please use a service like pastbin.com if its more than 5-10 lines :)

**Comment by ROKB** [comment]
@cyberium 
http://pastebin.com/gXg6KDaa

**Comment by cyberium** [comment]
thank you,
But i dont see anything :(
Anyway it seem more spell related than loot problem.
Maybe try to clean your client WTF folder or try with english version of the client?

**Comment by ROKB** [comment]
@cyberium ok i will try remove wtf.
but english v client need a lot of time.

**Comment by cyberium** [comment]
You mean same problem for english client?
Do you have clean cmangos tbc core?
@evil-at-wow could you please test that on your side?

**Comment by ROKB** [comment]
@cyberium it's classic core. yeah have clean core.

**Comment by ROKB** [comment]
@cyberium any progress?

**Comment by cyberium** [comment]
cannot reproduce
