### ISSUE TITLE
[TBC] Looting locked chests always bug

### ISSUE THREAD

**Issue by Arnibou** [cmangos/issues#777]
On the last rev. TBC with DB TBC, it still doesn't work even with the new loot system. In the log, the server sending out the loot to the player but the window doesn't open and the trunk closes as soon.

**Comment by cyberium** [comment]
Could you give me concrete exemple please?
Where to find that chest?

**Comment by Arnibou** [comment]
Ex:
Benedict's Chest (id: 3239)
.go gobject 1746
Key for epenning id: 4882

**Comment by Arnibou** [comment]
For info, on classic it work fine but no on TBC

**Comment by cyberium** [comment]
So, Thank you very much for that complement of information.

My result
The client correctly show the chest content if we open it with lockpicking skill.
The client dont open loot windows whe we use the Benedict's key.

After more research
The client start opening the loot windows but close it imediatly.
I confirm the loot windows close at soon at client recieve the order to delete Benedict's key wich is happenning as soon as the server send loot.
So i have to ask DB maintainer here, @cala @Grz3s
Is it realy how is supposed to work? Benedict's Key have only one charge? No matter we looted or not the box content? Or is it supposed to be delete at loot release?

And yes it work on classic and its same code so difference is only client side.

**Comment by Arnibou** [comment]
i'd compared the code and it was the same. I've testing, in comment TakeCatsitem(); (to destroy the key) it work (the Windows loot is open side client), so the problem lies in the destruction of the key.

**Comment by Grz3s** [comment]
```quote
Is it realy how is supposed to work? Benedict's Key have only one charge? No matter we looted or not the box content? Or is it supposed to be delete at loot release?
```
yes ... chest contain q.item that starts another quest... if u'll forget to take item... u need to go back and kill Lieutenant Benedict again. 
Just checked on Wotlk - works fine.

**Comment by cyberium** [comment]
Thank you very much @Grz3s.
So well i'll double check the code and if everything seem correct then it seem its a client "bug" that have to be workarounded in TBC.

**Comment by Arnibou** [comment]
After research, it's at moment to send opcode in th file object.cpp, in the fonction:
void Object::DestroyForPlayer(Player* target) const;
The bug appear, in comment inside this fonction, it's work. So why?
