### ISSUE TITLE
[CLASSIC][TBC] Channeled Spells at Max Range

### ISSUE THREAD

**Issue by Kudos5** [cmangos/issues#781]
Casting channeled spells at absolutely max range will cause manacost and global cooldown to be triggered, while the spell is immediately interrupted. Tested with mind flay rank 1 and drain soul rank 1 on a clean cmangos-tbc server.

The problem seems to be that the function WorldObject::IsWithinDistInMap returns false when checking the range in SpellAuraHolder::Update thus interrupting the cast, even though Spell:CheckRange has already approved the range.

Fixing this seems simple. You could just increase max_range by some amount, or use a different function, like Unit::GetCombatDistance. This is just from looking at the CheckRange function. I also don't know if you need to use IsWithinDistInMap for this purpose or if there is something wrong with this function.

Also, this prevents you form channeling spells when the target runs even slightly out of range. I don't know, but I would it expect it to be like spells, where the spell will finish casting even though the target is slightly out of range.

**Comment by ROKB** [comment]
classic too

**Comment by AnonXS** [comment]
Is this still a thing?

**Comment by killerwife** [comment]
It is probably still a thing in cmangos. I only recently reworked range calculations and its not in public.

**Comment by killerwife** [comment]
Resolved.
