### ISSUE TITLE
script to close your client

### ISSUE THREAD

**Issue by metacreo** [cmangos/issues#782]
[wotlk] If you send pm to another user (example):
 /script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:11318\124h[А теперь гонки на баранах... Или вроде того.]\124h\124r");

user client has been crashed. need add to server some filter of /script

**Comment by Zakamurite** [comment]
All that /script does here is client side. Who crashes? You or the person who you whisper to?

**Comment by metacreo** [comment]
both clients crashes... but some scripts allows to crash only target clients
I understand that the script on the client side, but the communication is performed through the server. It should be able to filter the scripts. I see on trinity is fixed..

**Comment by metacreo** [comment]
Anyone can hurt someone

**Comment by Dramacydal** [comment]
try to increase ChatStrictLinkChecking.Severity parameter in your config, this will filter broken chat links and disallow to send the to other players. nothing can be done to fix this issue on sender side

**Comment by metacreo** [comment]
ChatStrictLinkChecking.Severity up. all ok thank you

**Comment by metacreo** [comment]
Oh no ! ChatStrictLinkChecking.Severity parameter not help.
1. start chat with another player (whisp)
2. copy/paste this:
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:783\124h[ffck some queestt]\124h\124r");
3. hold shift and click on quest name then press enter

both client crash 100%
in server log hothing

**Comment by cyberium** [comment]
well i dont understaind the script itself but i presume "/script" mean the following will be used by only the client where it was typed. So if that command are send in server its wrong. Client had to block it.
Well as we can't change the client we can block all command starting by "/script" in the server if that can help.

**Comment by namreeb** [comment]
@cyberium, the script part just adds it locally to give him something to shift-click on.  It is the whisper, chat, etc. that causes the crash.  We (the server) do indeed need to filter this out, since we cannot fix the bug in the client.

**Comment by metacreo** [comment]
It seems to a very good idea try to to block through server "/script"
if it passes through the server, it does not need.

**Comment by cyberium** [comment]
@metacreo could you please try -> https://gist.github.com/cyberium/3275f8a531129b6b1d14

And i cannot reproduce it on my side with french client... No opcode sent when there is /script on the message. No matter /w or /s...

**Comment by cyberium** [comment]
please ignore my last comment i am now able to reproduce it. Thank @namreeb for more explanation.

**Comment by metacreo** [comment]
https://gist.github.com/cyberium/3275f8a531129b6b1d14 Im tried, compiled with patch, with ChatStrictLinkChecking.Severity 1 and 2 the same have crash both clients.
with ChatStrictLinkChecking.Severity 3 param all ok, real work.. sender have disconect and target nothing... 
all ok thanks for all for help.. sorry for my eng.
