### ISSUE TITLE
[Wotlk] Lord Marrowgar - Bone spike Targeting

### ISSUE THREAD

**Issue by Rushor** [cmangos/issues#789]
```c++
class BoneSpikeTargetSelector : public std::unary_function<Unit*, bool>
{
    public:
        BoneSpikeTargetSelector(UnitAI* ai) : _ai(ai) { }

        bool operator()(Unit* unit) const
        {
            if (unit->GetTypeId() != TYPEID_PLAYER)
                return false;

            if (unit->HasAura(SPELL_IMPALED))
                return false;

            if (unit->HasAura(SPELL_SPIRIT_OF_REDEMPTION))
                return false;            
            
            if (unit->isDead())
                return false;

            return true;
        }

    private:
        UnitAI* _ai;
};
```

This check must be added in the castscript 
https://github.com/cmangos/mangos-wotlk/blob/master/src/scriptdev2/scripts/northrend/icecrown_citadel/icecrown_citadel/boss_lord_marrowgar.cpp#L262
The boss should not select dead, impaled or player with aura (    SPELL_SPIRIT_OF_REDEMPTION  = 27827). moreover pets should not be selected for the bonespike

**Comment by Ulduar** [comment]
https://github.com/cmangos/mangos-wotlk/commit/978cb1377022de6874d7de03a6fa8bb11186b032#diff-6e2ad27531ee8eb7bafce8a41909816aR9393

**Comment by Rushor** [comment]
kay
