### ISSUE TITLE
[Wotlk] Lord Marrowgar - Greetingtext

### ISSUE THREAD

**Issue by Rushor** [cmangos/issues#792]
```c++
            void MoveInLineOfSight(Unit* who)
            {
                if (!_introDone && me->IsWithinDistInMap(who, 70.0f))
                {
                    Talk(SAY_ENTER_ZONE);
                    _introDone = true;
                }
```

if you run at least 70 yards closer to him, marrowgar should talk one line:
SAY_ENTER_ZONE

Text yell: This is the beginning AND the end, mortals. None may enter the master\'s sanctum!

**Comment by Ulduar** [comment]
https://github.com/cmangos/mangos-wotlk/blob/master/src/scriptdev2/scripts/northrend/icecrown_citadel/icecrown_citadel/instance_icecrown_citadel.cpp#L87
https://github.com/cmangos/mangos-wotlk/blob/master/src/scriptdev2/scripts/northrend/icecrown_citadel/icecrown_citadel/instance_icecrown_citadel.cpp#L517
https://github.com/cmangos/mangos-wotlk/blob/master/src/scriptdev2/scripts/northrend/icecrown_citadel/icecrown_citadel/icecrown_citadel.h#L139
In game:
.go triigger 5732 and enjoy.

**Comment by Rushor** [comment]
ah nice, didn't saw this :)
