### ISSUE TITLE
[wotlk] ChatStrictLinkChecking.Severity not work and allow crash clients

### ISSUE THREAD

**Issue by metacreo** [cmangos/issues#794]
[wotlk] **[security]** ChatStrictLinkChecking.Severity not work and allow crash clients (continue issue #782)
cfg parameters:
ChatFakeMessagePreventing = 1
ChatStrictLinkChecking.Severity = 1 (or 2 or 3 ....)
ChatStrictLinkChecking.Kick = 1

1. start chat with another player (whisp)
2. copy/paste in chat this:
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:783\124h[ffck some queestt]\124h\124r");
3.  and press enter
4. press enter to start simple(common) chat
5. hold shift and right-click on quest name (ffck some queestt, name not specified) to copy it to common chat
6. press enter

**both client crash 100%**
in server log hothing
tested on various servers

**Comment by cyberium** [comment]
@Dramacydal is correct, set ChatStrictLinkChecking.Severity to 3 work fine for me.
Please check that you are a normal player, because moderator and gm bypass that check.
A normal user should not be able to send that link.

**Comment by metacreo** [comment]
set ChatStrictLinkChecking.Severity to 3  look as all ok... sender have disconnect, target nothing.
thank for all
