### ISSUE TITLE
Very high priority Areatrigger.problem. Only in Cata 4.3.4.

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#796]
https://github.com/scriptdev2/scriptdev2-cata/blob/master/scripts/northrend/howling_fjord.cpp#L133
Example:
.go trigger 4778
or .go trigger 4779 - not started event, if have completed conditions(aura, quest)
at_icecrown_citadel
Player Enter in instance.
After enter .go trigger 5732 - not init intro speech event.
Stage 2 - leave instance, .instance unbind all, .go 5732(without entering the instance) - intro speech working, but The following areatrigger - Deathwhisper speech and other - no longer work.
On Wotlk working fine, but on Cata not working.
The problem is very old. How to solve - no idea, I know that MiscHandler to be added, but that it have no idea.
Very high priority, because many quests simply do not work, and the entrance of the instance is also a problem.

**Comment by xfurry** [comment]
is the area trigger OP code handled in Cata?
If not, we can fix it quickly. Otherwise, we might need to investigate the details.

**Comment by Ulduar** [comment]
Most likely it opcode, as well as teleport system - changed in Cata.

**Comment by Ulduar** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9ef63d7e8de30b32045faa4ff3abcdcc7a54cbc7
maybe can help.

**Comment by Ulduar** [comment]
Areatrigger struct for Wotlk 3.3.5a.
``` CPP
struct AreaTriggerEntry
{
    uint32  id;                                             // 0        m_ID
    uint32  mapid;                                          // 1        m_ContinentID
    float   x;                                              // 2        m_x
    float   y;                                              // 3        m_y
    float   z;                                              // 4        m_z
    float   radius;                                         // 5        m_radius
    float   box_x;                                          // 6        m_box_length
    float   box_y;                                          // 7        m_box_width
    float   box_z;                                          // 8        m_box_heigh
    float   box_orientation;                                // 9        m_box_yaw
};
```
Areatrigger struct for Wotlk 4.3.4 Cataclysm.
``` CPP
struct AreaTriggerEntry
{
    uint32  id;                                             // 0        m_ID
    uint32  mapid;                                          // 1        m_ContinentID
    float   x;                                              // 2        m_x
    float   y;                                              // 3        m_y
    float   z;                                              // 4        m_z
    //uint32                                                // 5
    //uint32                                                // 6
    //uint32                                                // 7
    float   radius;                                         // 8        m_radius
    float   box_x;                                          // 9        m_box_length
    float   box_y;                                          // 10       m_box_width
    float   box_z;                                          // 11       m_box_heigh
    float   box_orientation;                                // 12       m_box_yaw
};
```
Three new uint32 fields.

**Comment by Ulduar** [comment]
Also Areatrigger used for no implemeted in core SPELL_EFFECT_179 - Create Areatrigger.
Example:
``` CPP
ID - 30000 Испытательное заклинание Александера
=================================================
Description: Подсказки для победителей.

ToolTip: |cFFFFAA00Beware the flavor. For it is rich and mighty.|r

Normal Tooltip.
Category = 0, SpellIconID = 1796, activeIconID = 1764, SpellVisual = (22012,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 64 (SPELL_SCHOOL_MASK_ARCANE)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
AttributesEx3: 0x00100000 (SPELL_ATTR3_DEATH_PERSISTENT)
=================================================
Spell Level = 20, base 20, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 13) "Anywhere":
    MinRangeNegative = 0, MinRangePositive = 0
    MaxRangeNegative = 50000, MaxRangePositive = 50000

Speed 20,00
Cast time (Id 190) = 0,10
RecoveryTime: 0 ms, CategoryRecoveryTime: 0 ms
StartRecoveryCategory = 133, StartRecoveryTime = 1500,00 ms
Duration: ID (8)  15000, 0, 15000
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x02000000
Chance = 0, charges - 0
=================================================
Effect 0: Id 179 (SPELL_EFFECT_CREATE_AREATRIGGER)
BasePoints = 0
Targets (18, 0) (TARGET_DEST_CASTER, NO_TARGET)
EffectMiscValueA = 131
```

**Comment by Ulduar** [comment]
Alizabal in Baradin Hold for intro speech use 7246 - Thanks https://github.com/scriptdev2/scriptdev2-cata/issues/33

**Comment by Ulduar** [comment]
More examples:
Enter in ICC:
Clear Sindragosa thrash and dragons - Sindragosa spawn and not move point on platform.
https://github.com/scriptdev2/scriptdev2-cata/blob/master/scripts/northrend/icecrown_citadel/icecrown_citadel/icecrown_citadel.h#L141
And now dances with a tambourine!
Sequence:
1) .tele Sunwell
2) .go trigger 5604 - not init.
3) .tele Sunwell
4) .go trigger 5604 - not init.
5) .tele Sunwell
6) .go trigger 5604 - not init.
7) .tele Sunwell
8) .go trigger 5604 - Finally, init Sindragosa event.

**Comment by xfurry** [comment]
Will fix the areatrigger soon. Thanks for the info.

First I would like to close https://github.com/cmangos/issues/issues/795.
Any help for that is welcomed!

**Comment by Ulduar** [comment]
nullptr replace on NULL and all.

**Comment by VladimirMangos** [comment]
I not see in commit log any fixes for this issue.

**Comment by Rushor** [comment]
omg @VladimirMangos is alive <3

**Comment by X-Savior** [comment]
Vlad :D

Glad to see you still alive! Swing by IRC and visit with us someday!

**Comment by xfurry** [comment]
> I not see in commit log any fixes for this issue.

We didn't have time to look at this yet.
I think the guy who opened it, got frustrated and just closed the issued. (and deleted his account)

**Comment by VladimirMangos** [comment]
xfurry, this is and my point also. That why I reopen issue for avoid it lost in history)

**Comment by SADraco** [comment]
Hi there Vlad - wow didnt think ill ever see you again on here.

Glad you re-open this as this is a huge bug and does slow down the db side by going in and out instances to repair them

**Comment by xfurry** [comment]
@SADraco the problem with this issue is that I don't really understand what is the problem. :smile: 
DBC structure looks the same between 3.x and 4.x, so if the area triggers aren't working, there must be something else.

**Comment by SADraco** [comment]
hi Furry - thanks for response
the problem we are having is that the client hangs when he enters the dungeon - and only way you can overcome this you have to close client and log in again. and same if you exit the dungeon it looks like it have something to do with the portals because when you .tele out of dungeon say to dalaran it does not hang. i can do a small video of this just to show you.

**Comment by SADraco** [comment]
hi guys any more progress on this - sorry i ask - just frustrating that you need to keep loging in and out of dungeon just to get in and out  of dungeon

Thanks in advance

**Comment by xfurry** [comment]
I can't really replicate the issue.
I tested this myself and the area triggers seem to be working fine.

The only problem that I noticed, is that for some reason, if you turn GM on, the area triggers indeed stop working.
I'm not yet sure why is this. I will try to investigate, as I assume that this is the problem that we are talking about.

**Comment by VladimirMangos** [comment]
I think this is expected for gm mode. Maybe limit it to inviisble mode only maybe...

**Comment by VladimirMangos** [comment]
Too fast comment, sorry. I not see any code part that can affect this, so I ma wrong in it.

**Comment by SADraco** [comment]
Hi Furry

have you tried the new cataclysm dungeons - as those seems to be the ones that stuck all the time

**Comment by xfurry** [comment]
> have you tried the new cataclysm dungeons - as those seems to be the ones that stuck all the time

No. Will try.
I only tried the old ones, like Stockades.

**Comment by SADraco** [comment]
yea stockades let you in first time or 2 times but go in and out a couple of times

**Comment by SADraco** [comment]
here is a screen shot of error report when it hangs when trying to enter dungeon

https://www.dropbox.com/s/qq29qvd6wdlbnhb/Screenshot%202016-01-27%2021.03.12.png?dl=0

**Comment by SADraco** [comment]
this is what errors show when it logs up

**Comment by SADraco** [comment]
hi guys any help on this yet

it still dont work and still cant enter and exit dungeons without relogging

**Comment by xfurry** [comment]
hi @SADraco 
I will try to see if I can do something about it.
the problem is that people are not very interested in Cata nowadays and also my time to work on stuff is very limited lately.

**Comment by xfurry** [comment]
@SADraco I tried to test one more time with the new Cata dungeons using the latest YTDB.
I still can't replicate the problem.

Maybe it's because of a problem on the client side. Also, keep in mind that WoW.exe needs to be patched.
I'm using version 434 (14495) x86

**Comment by SADraco** [comment]
furry can you send me a link to that patch please ill try it then

**Comment by cyberium** [comment]
CMaNGOS officially stop cata development.
