### ISSUE TITLE
[CLASSIC][WOTLK] Spell: Charge [#11578]

### ISSUE THREAD

**Issue by Argonn** [cmangos/issues#798]
When using the warrior's charge ability, you will end-up 1-2 yards to far away for you to be able to attack the target.

https://github.com/unified-db/Database/issues/139

**Comment by Argonn** [comment]
tested this with a Draenei smurf. (maybe it matters, maybe not)

**Comment by Argonn** [comment]
Some 'fun' with charge, which send me in hyper-speed trough some part of the cave.
http://www.twitch.tv/beerfishtv/v/25075055 (from 1:47:20)

**Comment by cirquedecarnage** [comment]
same problem on classic

**Comment by Phatcat** [comment]
Can't reproduce on classic, if you charge an enemy you get close enough and will automatically start attacking it. Can't reproduce on wotlk either, same thing, can't reproduce there either, charge gets you all up in your targets face.
