### ISSUE TITLE
[WOTLK] Spell: Victory Rush [#34428]

### ISSUE THREAD

**Issue by Argonn** [cmangos/issues#799]
The warrior ability vicotry rush, should proc from each kill (when not already under the effect) where you dealt the killing blow. This doesn't seem to be the case, for now it rarely procs.

Also, when it procs, you should receive a 'buff' timer to show the 20second window in which you need to use the ability. The buff is not visible to the player.

Wowhead:
http://www.wowhead.com/spell=34428/victory-rush

**Comment by Argonn** [comment]
After some more testing, we found out that when a teammate 'tags' the target. You will never get vicotry rush, when you have dealt the first hit. You will get victory rush on killingblow.

So in team play, the warrior should always deal the first hit for now. Otherwise you will not get victory rush.

**Comment by killerwife** [comment]
Seems to work correctly alreaady after some testing.
