### ISSUE TITLE
[WOTLK] Talent: Arcane Potency [#31571]

### ISSUE THREAD

**Issue by Argonn** [cmangos/issues#800]
The mage talent Arcane Potency always 'procs' when i cast 'Arcane Intellect'. While arcane intellect give no effect like 'Clearcasting' or 'Presence of Mind' the 'Arcane Potency' proc will still trigger 100% of the time when casting 'Acane Intellect'. This will give the mage a super amount of damage when taking AI into their rotation.

This happens when:
self-casting;
casting it on a NPC;
casting it on a other player;

> > Tooltip:
> > "Increase the critical strike change of your next damaging spell by 30% after gaining Clearcasting of Presence of Mind."

https://github.com/unified-db/Database/issues/133

**Comment by killerwife** [comment]
Already fixed
