### ISSUE TITLE
[WOTLK] Talent: Missile Barrage [#44404]

### ISSUE THREAD

**Issue by Argonn** [cmangos/issues#801]
This talent is bugged, as it DOES reduce the channel time, it also only deals halve the damage in total.

(testing on lvl 68)
While normal casting this spell:
Channel time: 5 seconds,
Missiles: 5
Damage: 5 x 490~ = 2500~

While casting this spell with Missile Barrage:
Channel time: 2.5 seconds,
Missiles: 2 (I guess 2.5 rounded down)
Damage: 2 x 490~ = 1000~

This should not be a talent to nerf mages, this talent should still give 5 missiles but within half the time.

Tooltip:

> > Gives your Arcane Blast a 40% change, and your Arcane Barrage, Fireball, Frostbolt and FrostFire Bolt spells a 20% change to reduce the channeled duration of the next Arcane Missisles spell by 2.5 secs, reduce the mana cost by 100% and missiles will fire every .5 secs.

UDB report:
https://github.com/unified-db/Database/issues/134

**Comment by killerwife** [comment]
Fixed already
