### ISSUE TITLE
[Wotlk] Core: Ranged enemies not moving on LOS

### ISSUE THREAD

**Issue by Argonn** [cmangos/issues#802]
When the player pulls a mage/ranged NPC, and then move out of sight (behind a wall, pillar, door etc) the creature will enter a passive stance, and will remain onspot until the player who has agro on the mob moves back into LOS again.

This also happens on spellcasters being silenced, they will not move for the duration. So you cannot pull a spellcaster with silence.

UDB report:
https://github.com/unified-db/Database/issues/127

**Comment by Argonn** [comment]
http://cmangos.net/thread-503-page-3.html for some 'fixes' and information discussion

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-wotlk/commit/e40b35e5fdb0d7031fc13fbba97f5a608ed4e288
ACID needs to be updated (only TBC is up-to-date).
