### ISSUE TITLE
[classic] crash 

### ISSUE THREAD

**Issue by gaosheng136** [cmangos/issues#804]
Call stack:
Address   Frame     Function      SourceFile
00000001403FCF27  000000000713C8D0  BIH::intersectRayVMAP::WModelRayCallBack+2D7  h:\cmangos\mangos-classic\src\game\vmap\bih.h line 190
00000001403FDFD4  000000000713C920  VMAP::WorldModel::IntersectRay+64  h:\cmangos\mangos-classic\src\game\vmap\worldmodel.cpp line 431
0000000140324664  000000000713C9E0  GameObjectModel::intersectRay+1C4  h:\cmangos\mangos-classic\src\game\vmap\gameobjectmodel.cpp line 158
0000000140398B0D  000000000713CA10  BIHWrap<GameObjectModel,BoundsTrait<GameObjectModel> >::MDLCallback<DynamicTreeIntersectionCallback>::operator()+2D  h:\cmangos\mangos-classic\src\game\vmap\bihwrap.h line 40

**Comment by cyberium** [comment]
should be fixed
