### ISSUE TITLE
[Wotlk] Spell: Raise Ally [#61999]

### ISSUE THREAD

**Issue by Argonn** [cmangos/issues#805]
The Death Knight spell raise ally doesn't do anything it keeps giving the message 'Target is alive'

Spell:
http://www.wowhead.com/spell=61999

**Comment by cyberium** [comment]
Hi, could you please describe me how it should work at worlk time?

**Comment by Argonn** [comment]
It should create a ghoul from a player (which they can control) with your normal ghoul abilities and stats (count in the talents as well).

The abilities can be checked here: https://www.youtube.com/watch?v=4F1V0V2llZ0

Patch 3.3.0
Raise Ally: The cooldown on this ability has been reduced from 15 minutes to 10 minutes. Cannot be used in Arenas.

**Comment by cyberium** [comment]
Thank you i'll take a look at this, i may have more question thought ;)

**Comment by Argonn** [comment]
Made some updates (above) with the data I could find.

**Comment by cyberium** [comment]
So, Player A (any class) died.
Player B is a DeatnKnight and have abilitie to launch Raise Ally spell.

Player B launch Raise Ally on near and just died (and not released?) player A.
Player A will appear like he have a new Ghoul Pet but that pet is controlable by Player A even if he is died (and not released?).
That Ghoul remain 5 min. After the 5 min the Ghoul just disapear and the Player A have choice to release his body.
That have nothing to do with the Player B own Ghoul if it was up.

I have still unable to find out how to compute the Ghoul Damage. A percentage of player B weapon. Well we'll see.

Is that correct?

**Comment by BeerfishWoW** [comment]
@cyberium Got some more information for you about Raise Ally, including the abilities that risen ally will be able to use:
http://thedeathanddecay.blogspot.nl/2010/04/ghoul-school.html
http://www.wowhead.com/forums&topic=102865/raise-ally
http://www.wowhead.com/forums&topic=110772/raise-ally-never-successfully-used

The two WoWHead topics go a bit more into detail concerning the specifics of Raise Ally.

**Comment by Argonn** [comment]
@cyberium  Correct, but while being a ghoul, there is no option to release your corpse (off course)
And you will become a pet of your self, (read about that the ghoul is a vehicle that you control)

**Comment by cyberium** [comment]
Hey guys thank very much for your research here. Just to show you a bit where i am, here is a video of the first semi working version.
You'll see that iam facing some serious problem now that i dont yet have found the solution.
- Remove death effect
- Remove player ghost
- Set correctly stats of the summoned ghoul
- Remove Raise Ally aura when ghoul explode
- Let ghoul corpse decay a bit more (that's why we cant see correctly explode effect)
- Remove completly ghoul spells (only disabled it seem currently)

And probably lot of more issues...
Click on the image to see the video.

<a href="http://www.youtube.com/watch?feature=player_embedded&v=KDrXTfVhVJ0
" target="_blank"><img src="http://img.youtube.com/vi/KDrXTfVhVJ0/0.jpg" alt="Raise Ally progress" width="640" height="480" border="10" /></a>

**Comment by Argonn** [comment]
It looks pretty awesome as is right now man. You can already play as ghoul, I would call the other things minor. Is there anything i could help out with? Research, Testing or getting some old data from the interwebs.

**Comment by cyberium** [comment]
At this point only some sniff may help me to know what is missing/wrong with my implementation.
I'll push it only when it will not cause any problem like now..
For now there is too much issues to release it.

@xfurry iam wondering how the spawn in animation work.
something like -> https://youtu.be/IrXro2ZuhqY?t=21
The ghoul is now only spawned normaly i saw that spell -> http://www.wowhead.com/spell=47448/risen-ghoul-spawn-in have to be used but how?
Spawning the creature via SummonCreature but i dont see where/when to cast these spell.
Do you have any exemple?

**Comment by xfurry** [comment]
> Do you have any exemple?

I'll get back to you with this, in the evening.

**Comment by xfurry** [comment]
@cyberium 
For these kind of animations, usually we use spells with effect 46 -SPELL_EFFECT_SPAWN or spells with effect SPELL_EFFECT_DUMMY but which have a specific SpellVisual

In your particular case, spell 47448 should be cast by the summoned creature on spawn, either by SD2 or by ACID.


As an example I can show you this example https://github.com/cmangos/mangos-wotlk/commit/40965b350017007de0bda0fa4dd53aa9bac5d229 using spell 26586

**Comment by cyberium** [comment]
Thank you for the ACID script @xfurry. I see the spell in log are sent so that part is correct. Unfortunaly it not show the animation.
@Grz3s any treasure in your log about spell 61999 or any raise dead spell?
Or any other that can help for sniff ofc ;)

**Comment by Argonn** [comment]
Its sad blizz changed this spell completely to a battle-res in the next version. So this give 0 information on retail currently.
Anything I could help out with?

**Comment by cyberium** [comment]
Do you know if when the ghoul is spawned the area range where we can control it is limited?
Actual if go out a certain range the ghoul despawn and i force the player to retrieve the control of his character.

Here is new video ->
<a href="http://www.youtube.com/watch?feature=player_embedded&v=6xJ2jomUgpM
" target="_blank"><img src="http://img.youtube.com/vi/6xJ2jomUgpM/0.jpg" alt="Raise Ally progress" width="640" height="480" border="10" /></a>

**Comment by Argonn** [comment]
Given the ghoul is a vehicle, I would say there is no max to the range (Also no data found on any range, after some hours of searching the internet). No max between the DK and the Ghouled Ally, and no max range between the corpse and the Ghouled Ally.

**Comment by cyberium** [comment]
That ghoul is not a vehicle, i dont see any evidence of it. Its a simple possessed creature.
There must be a range somewhere like usual (we cannot control unit from too far)
The client itself force me to go back to the corpse so there is still some error/limitation/forget in the code to allow larger range.

**Comment by Argonn** [comment]
Could you give it the same range as "eye of the beast" as from hunters? In the tool-tip it states that the range is unlimited. Seeing this is pretty much a equal ability (from a players perspective).
http://wowwiki.wikia.com/wiki/Eyes_of_the_Beast

**Comment by cyberium** [comment]
Lastest progress.
Its near to be released.
I think all main feature are implemented.

<a href="http://www.youtube.com/watch?feature=player_embedded&v=7toBFHiClQM
" target="_blank"><img src="http://img.youtube.com/vi/7toBFHiClQM/0.jpg" alt="Raise Ally progress" width="640" height="480" border="10" /></a>

Remaining (but will be released without at first stage)
- Trash spell is not implemented.
- Stun at the spawn-in animation don't work.
- Stats of the ghoul are not correct.
- Special DK talents related to ghoul are ignored.
- probably more when you'll be able to test it ;)

**Comment by cyberium** [comment]
Its probably not perfect but its fixed :)

**Comment by Argonn** [comment]
You sir did wonders on this! Thank you so much.
