### ISSUE TITLE
Windows Compile Error ( BOOST )

### ISSUE THREAD

**Issue by Tauriella** [cmangos/issues#810]
Can't compile latest src
I use Visual Studio Express 2013

Fehler	56	error C1189: #error :  "VERSION undeclared"	D:\MangosSRC335\src\shared\SystemConfig.h	30	1	ScriptDev2
Fehler	57	error C1189: #error :  "VERSION undeclared"	D:\MangosSRC335\src\shared\SystemConfig.h	30	1	ScriptDev2
Fehler	41	error C1083: Datei (Include) kann nicht geöffnet werden: "boost/version.hpp": No such file or directory	D:\MangosSRC335\src\realmd\Main.cpp	44	1	realmd
	58	IntelliSense: Die Datei "Quelle" kann nicht geöffnet werden: "boost/version.hpp".	d:\MangosSRC335\src\realmd\Main.cpp	44	1	realmd
	59	IntelliSense: Der Bezeichner ""BOOST_VERSION"" ist nicht definiert.	d:\MangosSRC335\src\realmd\Main.cpp	112	53	realmd
Fehler	54	error C1083: Datei (Include) kann nicht geöffnet werden: "boost/version.hpp": No such file or directory	D:\MangosSRC335\src\mangosd\Main.cpp	37	1	mangosd
Fehler	44	error C1189: #error :  "VERSION undeclared" (..\..\src\game\AuctionHouseBot\AuctionHouseBot.cpp)	D:\MangosSRC335\src\shared\SystemConfig.h	30	1	game
Fehler	45	error C1189: #error :  "VERSION undeclared" (..\..\src\game\Level0.cpp)	D:\MangosSRC335\src\shared\SystemConfig.h	30	1	game
Fehler	46	error C1189: #error :  "VERSION undeclared" (..\..\src\game\Level3.cpp)	D:\MangosSRC335\src\shared\SystemConfig.h	30	1	game
Fehler	47	error C1189: #error :  "VERSION undeclared" (..\..\src\game\World.cpp)	D:\MangosSRC335\src\shared\SystemConfig.h	30	1	game

**Comment by cyberium** [comment]
Please note that from this commit you'll need to have boost installed and BOOST_ROOT environement set.
For prebuilt binaries of boost go to -> http://sourceforge.net/projects/boost/files/boost-binaries/1.59.0/
Download the one corresponding to your compiler version and install it in some folder.
Then go to your advanced setup in windows and add a vaiable environement named BOOST_ROOT with value set to your boost folder installation.

**Comment by Tauriella** [comment]
Is Boost 1.57.0 not compatible ?

I have Installed Boost 1.57.0 and i think i have the correct path
My Variable is BOOST_ROOT and c:\locale\boost_1_57_0

But i think i must install VS2015 grrrr and Boost1.59.0

or have you any idea?

**Comment by cyberium** [comment]
i dont see any reason that 1.57 is not compatible howewer i didnt test it, Also VS2013 is still supported by us so feel free to tell us if there is another problem.

**Comment by namreeb** [comment]
Are you using cmake?

**Comment by namreeb** [comment]
Also, please note that the wiki has been updated with boost related installation and configuration instructions.  See here: https://github.com/cmangos/issues/wiki/Installation-Instructions#installing-boost

**Comment by Tauriella** [comment]
Hi
So i have now installed VS2015 now it works i can compile :+1: 
BUT i can only make a 32Bit compile
If i compile a 64Bit release i have a Error

Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile
Fehler	MSB6006	"cmd.exe" wurde mit dem Code 3 beendet.	shared	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171

@namreeb i use the .sln

I think VS2013 is out of date BOOST does not works with VS2013

**Comment by namreeb** [comment]
@Tauriella, even if 1.59.0 does not work with VS2013, earlier versions of boost will almost certainly work with cmangos currently.  Now, that may end up changing in the near future as we start to actually use boost.  This commit resembles mostly just its introduction.  There is no real use of it as yet.

I am a bit puzzled by your inability to compile in x64 mode in VS2015.  It works just fine for me.  Can you post a more complete build log?  Would it be possible to change the output to english, as well?

**Comment by Tauriella** [comment]
Sorry i cant change the language

1>------ Erstellen gestartet: Projekt: tbb, Konfiguration: Release x64 ------
1>  generating tbb.def file
1>  win64-tbb-export.def
1>  Assembling ..\..\dep\tbb\src\tbb\ia32-masm\lock_byte.asm...
1>     Bibliothek "..\..\dep\lib\x64_Release\tbb.lib" und Objekt "..\..\dep\lib\x64_Release\tbb.exp" werden erstellt.
1>  Code wird generiert.
1>  0 of 884 functions ( 0.0%) were compiled, the rest were copied from previous compilation.
1>    0 functions were new in current compilation
1>    0 functions had inline decision re-evaluated but remain unchanged
1>  Codegenerierung ist abgeschlossen.
1>  tbb.vcxproj -> D:\MangosSRC335\win\VC140\..\..\dep\lib\x64_Release\tbb.dll
2>------ Erstellen gestartet: Projekt: tbbmalloc, Konfiguration: Release x64 ------
2>  building atomic_support.obj
2>   Assembling: ../../dep/tbb/src/tbb/intel64-masm/atomic_support.asm
2>  Microsoft (R) Macro Assembler (x64) Version 14.00.23026.0
2>  Copyright (C) Microsoft Corporation.  All rights reserved.
2>
2>  generating tbbmalloc.def file
2>  win64-tbbmalloc-export.def
2>  Assembling ..\..\dep\tbb\src\tbb\ia32-masm\lock_byte.asm...
2>     Bibliothek "..\..\dep\lib\x64_Release\tbbmalloc.lib" und Objekt "..\..\dep\lib\x64_Release\tbbmalloc.exp" werden erstellt.
2>  Code wird generiert.
2>  0 of 165 functions ( 0.0%) were compiled, the rest were copied from previous compilation.
2>    0 functions were new in current compilation
2>    0 functions had inline decision re-evaluated but remain unchanged
2>  Codegenerierung ist abgeschlossen.
2>  tbbmalloc.vcxproj -> D:\MangosSRC335\win\VC140\..\..\dep\lib\x64_Release\tbbmalloc.dll
3>------ Erstellen gestartet: Projekt: shared, Konfiguration: Release x64 ------
3>  Extract revision
3>  Das System kann den angegebenen Pfad nicht finden.
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" wurde mit dem Code 3 beendet.
4>------ Erstellen gestartet: Projekt: realmd, Konfiguration: Release x64 ------
4>     Bibliothek "..\..\bin\x64_Release\realmd.lib" und Objekt "..\..\bin\x64_Release\realmd.exp" werden erstellt.
4>  realmd.vcxproj -> D:\MangosSRC335\win\VC140\..\..\bin\x64_Release\realmd.exe
5>------ Erstellen gestartet: Projekt: mangosd, Konfiguration: Release x64 ------
5>     Bibliothek ".\mangosd__x64_Release\mangosd.lib" und Objekt ".\mangosd__x64_Release\mangosd.exp" werden erstellt.
5>  mangosd.vcxproj -> D:\MangosSRC335\win\VC140\..\..\bin\x64_Release\mangosd.exe
5>  ..\..\dep\lib\x64_Release\ACE.dll
5>  ..\..\dep\lib\x64_Release\libeay32.dll
5>  ..\..\dep\lib\x64_Release\libmySQL.dll
5>  ..\..\dep\lib\x64_Release\tbb.dll
5>  ..\..\dep\lib\x64_Release\tbbmalloc.dll
5>          5 Datei(en) kopiert.
6>------ Erstellen gestartet: Projekt: ScriptDev2, Konfiguration: Release x64 ------
6>     Bibliothek "..\..\bin\x64_Release\mangosscript.lib" und Objekt "..\..\bin\x64_Release\mangosscript.exp" werden erstellt.
6>  ScriptDev2.vcxproj -> D:\MangosSRC335\win\VC140\..\..\bin\x64_Release\mangosscript.dll
========== Erstellen: 5 erfolgreich, 1 fehlerhaft, 7 aktuell, 0 übersprungen ==========

**Comment by namreeb** [comment]
Is the genrevision binary there?

**Comment by Tauriella** [comment]
Yes

**Comment by Tauriella** [comment]
Now i have try to use CMake 
I use Cmake 3.4.0
2 Errors

CMake Error at src/scriptdev2/CMakeLists.txt:63 (target_link_libraries):
  Target "mangosd" of type EXECUTABLE may not be linked into another target.
  One may link only to STATIC or SHARED libraries, or to executables with the
  ENABLE_EXPORTS property set.


CMake Error at src/scriptdev2/CMakeLists.txt:63 (target_link_libraries):
  The "debug" argument must be followed by a library.

**Comment by cyberium** [comment]
You have to install boost binaries version 64bit from http://sourceforge.net/projects/boost/files/boost-binaries/1.59.0/ too
You can install it in same folder than 32 bits.

Be aware taking the 64 bit version corresponding with vs2015 so this one -> http://sourceforge.net/projects/boost/files/boost-binaries/1.59.0/boost_1_59_0-msvc-14.0-64.exe/download

**Comment by namreeb** [comment]
Can you try executing it manually, and see if it succeeds?

**Comment by Tauriella** [comment]
@namreeb  yes the bin works
Server start without error
i use the 64Bit release with 1 compile error
CMaNGOS/0.18 (2015-11-20 20:53:10 - feeadc7eaac1e38cf8ef5ef7ce67d5bb6fab6a61)

**Comment by Tauriella** [comment]
@cyberium 
I have installed this Boost Version "boost_1_59_0-msvc-14.0-64.exe"

**Comment by namreeb** [comment]
@Tauriella I meant literally which version of git are you using, not which version of CMaNGOS.  Run git --version and paste the results, please.

**Comment by Tauriella** [comment]
ups i have wrong understand
I do not understand what has to do with git?
i use
C:\>git --version
git version 1.9.5.msysgit.0

**Comment by namreeb** [comment]
Well, if I understood your error message correctly, the custom build step which executes genrevision is failing somehow.  I am referring to this:

> 3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" wurde mit dem Code 3 beendet.

The code for genrevision will attempt to extract the most recent commit from git's internal data to generate the revision.h file.  But since you said that genrevision works when you execute it manually, I really have no explanation for this error.

**Comment by Tauriella** [comment]
Hmmm,
But I don't understand why I can 32 bit compile without error.
strange
