### ISSUE TITLE
[Classic][BG][Alterac Valley]

### ISSUE THREAD

**Issue by Kelzior** [cmangos/issues#811]
BG AV 

The reinforcements doesnt show but the biggest problem is that AV doesnt when you burned all towers etc.

Another big issue: the HP of Drek & Vanndar Stormpike do not drop when a tower is burned etc.

Is it working well on the wotlk version?

**Comment by Tobschinski** [comment]
> The reinforcements doesnt show but the biggest problem is that AV doesnt when you burned all towers etc.

Patch 2.3.0: The Horde and Alliance now have a limited number of reinforcements available in the battle for Alterac Valley. The number of reinforcements available is reduced upon player death, loss of towers, and death of Captain Galvangar or Balinda Stonehearth. In addition, all available reinforcements are lost upon the death of General Drek'Thar or Vanndar Stormpike. If a team is reduced to zero reinforcements, the opposing team wins the battle.

> Another big issue: the HP of Drek & Vanndar Stormpike do not drop when a tower is burned etc.

Patch 2.4.0: Major buffs have been applied to Warmasters and Marshalls; Warmasters and Marshalls now increase each other's maximum health and maximum damage by 25%. This is a stacking buff.

ID - 45822 Iceblood Warmaster
ID - 45823 Tower Point Warmaster
ID - 45824 West Frostwolf Warmaster
ID - 45826 East Frostwolf Warmaster
ID - 45828 Dun Baldar North Marshal
ID - 45829 Dun Baldar South Marshal
ID - 45830 Stonehearth Marshal
ID - 45831 Icewing Marshal

**Comment by Kelzior** [comment]
Oh dang, thanks but the BG won't end even while I burned all towers and killed balina etc. 1h+ still not end.

**Comment by Kelzior** [comment]
Thanks for the info @Tobschinski
