### ISSUE TITLE
[classis] crash

### ISSUE THREAD

**Issue by gaosheng136** [cmangos/issues#813]
: 000000080001B906
R9: 000007FF980FDF00
R10:000000000726D860
R11:000007FFE0DE2D40
R12:0000000000000000
R13:000007FF9DEC6080
R14:000007FF9DEC6080
R15:0000005E00000001
CS:RIP:0033:0000000006F99C1B
SS:RSP:002B:000000000726D820  RBP:9DEC6080
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010202

Call stack:
Address   Frame     Function      SourceFile
0000000006F99C1B  000000000726D840  instance_ruins_of_ahnqiraj::OnCreatureDeath+15B  h:\cmangos\mangos-classic\src\scriptdev2\scripts\kalimdor\ruins_of_ahnqiraj\instance_ruins_of_ahnqiraj.cpp line 135
000000014012A298  000000000726D890  Unit::JustKilledCreature+1D8  h:\cmangos\mangos-classic\src\game\unit.cpp line 977
00000001401250A1  000000000726E9D0  Unit::DealDamage+8C1  h:\cmangos\mangos-classic\src\game\unit.cpp line 770
0000000140125F03  000000000726EA40  Unit::DealSpellDamage+1B3  h:\cmangos\mangos-classic\src\game\unit.cpp line 1332
000000014037EE20  000000000726EB20  Spell::DoAllEffectOnTarget+560  h:\cmangos\mangos-classic\src\game\spell.cpp line 1054
0000000140387DF0  000000000726EB50  Spell::handle_immediate+60  h:\cmangos\mangos-classic\src\game\spell.cpp line 2785
00000001403875EB  000000000726EB80  Spell::cast+32B  h:\cmangos\mangos-classic\src\game\spell.cpp line 2769
0000000140388FD8  000000000726EBB0  Spell::update+358  h:\cmangos\mangos-classic\src\game\spell.cpp line 3032
000000014037F695  000000000726EBE0  SpellEvent::Execute+25  h:\cmangos\mangos-classic\src\game\spell.cpp line 6065
0000000140489613  000000000726EC10  EventProcessor::Update+63  h:\cmangos\mangos-classic\src\framework\utilities\eventprocessor.cpp line 47
0000000140134AE2  000000000726EC40  Unit::Update+32  h:\cmangos\mangos-classic\src\game\unit.cpp line 295
00000001401CFBA0  000000000726ECD0  Player::Update+70  h:\cmangos\mangos-classic\src\game\player.cpp line 1140
0000000140161946  000000000726FDC0  Map::Update+1A6  h:\cmangos\mangos-classic\src\game\map.cpp line 468
00000001402586F7  000000000726FE10  MapManager::Update+67  h:\cmangos\mangos-classic\src\game\mapmanager.cpp line 177
00000001400DF5AD  000000000726FE50  World::Update+14D  h:\cmangos\mangos-classic\src\game\world.cpp line 1427
00000001400B4C91  000000000726FE80  WorldRunnable::run+61  h:\cmangos\mangos-classic\src\mangosd\worldrunnable.cpp line 67
00000001400C7E8D  000000000726FEB0  std::_LaunchPad<std::_Bind<1,void,void (__cdecl*const)(void * __ptr64),void * __ptr64> >::_Go+1D  c:\program files (x86)\microsoft visual studio 12.0\vc\include\thr\xthread line 188
000007FEF817D204  000000000726FEF0  ?_Release@_Pad@std@@QEAAXXZ+6C
000007FEF2BF51BF  000000000726FF20  _beginthreadex+107
000007FEF2BF5366  000000000726FF50  _endthreadex+192
0000000076E0652D  000000000726FF80  BaseThreadInitThunk+D
0000000076F3C521  000000000726FFD0  RtlUserThreadStart+21

**Comment by cyberium** [comment]
not enough data to reproduce
