### ISSUE TITLE
[CLASSIC] Naxx - Thaddius Doesn't Activate

### ISSUE THREAD

**Issue by gaosheng136** [cmangos/issues#814]
[classis]NAXX thaddius cant Activation

**Comment by Rushor** [comment]
more details on this issue pls.

provide a detailed issuereport with a clear reproduction und links to wowhead/wowwiki

**Comment by xfurry** [comment]
Most probably a DB issue.

**Comment by gaosheng136** [comment]
Classic DB version 1.6.0 'Shadowforge City'. For core Classic z2683.

**Comment by xfurry** [comment]
Poke @cala . Can you please check if the Naxx instance has all the npcs spawned in the right place.
I know that there are a bunch of triggers for Thaddius encounter that need to be there in order for the boss to work.

**Comment by cala** [comment]
Hi,

I'm pretty sure that Thaddius flags are OK in Classic DB for the **classic version** of the encounter. I can't tell for the various triggers, I will have a look at these for sure.

Unfortunately OP will have to be patient: though Naxxramas 40 is my favorite raid instance, I promised to look at other issues/PR first, thus I will keep my word and look at them before. :smile: 

I assigned myself to this issue.

**Comment by xfury** [comment]
I'm also sure that Thaddius Activation well.just kill two BOSS and wait.

**Comment by gaosheng136** [comment]
two pet have be kiied BUG Thaddius  not Activation

**Comment by gaosheng136** [comment]
two pet have be kiied but Thaddius not Activation

**Comment by gaosheng136** [comment]
two pet have be kiiled but Thaddius not Activation

**Comment by cavaclub** [comment]
same with me

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/4d984395fde415d9159a3b5db05e83cb3b9204b7
