### ISSUE TITLE
[TBC] Implement Karazhan Mini-Boss Spawning Event

### ISSUE THREAD

**Issue by X-Savior** [cmangos/issues#816]
Ok, so we are missing the SD2 Script for Spawning the Mini-Bosses in Servants Quarters.

Here is some info:
http://wowwiki.wikia.com/wiki/Karazhan
http://www.wowhead.com/npc=16181/rokad-the-ravager#comments

So here is the deal... to get a Mini-Boss to summon you must clear the Servants Quarters and then the boss will summon. But there is a trick to it:

Update: The Spawning is not as random as we were lead to believe. When clearing the trash, save your last kill spider/dog/bat for whatever rare you want to spawn.

Killing a dog last in the trash clear spawns Rokad the Ravager
Killing a spider last in the trash clear spawns Hyakiss the Lurker
Killing a bat last in the trash clear spawns Shadikith the g-l-i-d-e-r

So what we need to do is implement a script to check for any NPC spawns for the trash in this section (NPC ID are listed below) and also to check the ID of the last one killed so we know what Mini-Boss should be spawned. Each Mini-Boss also has it's own Emote that happens that everyone in the instance can see when the boss is spawned.

Additional Note: Once all the trash NPC respawn in this section and you clear them again you can spawn the Mini-Boss again. So there needs to be some kind of check for this also. Respawn times are at least 30 mins...

So here is the groupings of trash NPC:

Bats:
Shadowbat (16173)
Greater Shadowbat (16174)
Vamperic Shadowbat (16175)

Boss Spawned: Shadikith the glider (16180)
Emote on Spawn: "Shadikith the Glider flaps down from the ceiling..."
-------
Dogs:
Phase Hound (16178)
Dreadbeast (16177)
Shadowbeast (16176)

Boss Spawned: Rokad the Ravager (16181)
Emote on Spawn: "???"  <=== We will figure this one out soon.
-------
Spiders:
Coldmist Widow (16171)
Coldmist Stalker (16170)

Boss Spawned: Hyakiss the Lurker (16179)
Emote on Spawn: "Hyakiss the Lurker emerges from the shadows..."

**Comment by X-Savior** [comment]
XFurry, I will update this with the spawn coordinates for each boss and I will try and get the final emote used also.

**Comment by Tobschinski** [comment]
[Rokad the Ravager](http://www.wowhead.com/npc=16181/rokad-the-ravager)

x  | y | z | o
------------- | ------------- | ------------- | ------------- 
-10900.01  |  -2085.47 | 49.55751 | 1.343904

__ServerToClient: SMSG_CHAT__
SlashCmd: MonsterEmote (16)
Language: Universal (0)
Sender: Entry: 16181
Target: Player
Text: %s howls through the halls...

--------------------------------------------------------

[Shadikith the Glider](http://www.wowhead.com/npc=16180/shadikith-the-glider)

x  | y | z | o
------------- | ------------- | ------------- | ------------- 
-10939.75  |  -2041.114 | 49.55752 | 1.361357

__ServerToClient: SMSG_CHAT__
SlashCmd: MonsterEmote (16)
Language: Universal (0)
Sender: Entry: 16180
Target: Player
Text: %s flaps down from the ceiling...

--------------------------------------------------------

[Hyakiss the Lurker](http://www.wowhead.com/npc=16179/hyakiss-the-lurker)

x  | y | z | o
------------- | ------------- | ------------- | ------------- 
-10959.11  |  -1940.862 | 46.1975 | 3.769911

__ServerToClient: SMSG_CHAT__
SlashCmd: MonsterEmote (16)
Language: Universal (0)
Sender: Entry: 16179
Target: Player
Text: %s skitters out from the shadows...

**Comment by Tobschinski** [comment]
> Update: The Spawning is not as random as we were lead to believe. When clearing the trash, save your last kill spider/dog/bat for whatever rare you want to spawn.

I cannot confirm this. The last creature I killed was a bat and I got Rokad the Ravager ...

**Comment by Rushor** [comment]
i think it's random - if you killed all 50 trashmobs (bat, dog and so on) one of three randombosses must spawn

**Comment by Tobschinski** [comment]
Would make more sense to me, because I did not had to kill everything in there.

**Comment by X-Savior** [comment]
guys seriously it is not random.

I provided documentation but it is based on the final NPC you kill.... jeez I outlined it.

Read the info and I have confirmed it on Blizz.... the final NPC in the servants quarters determines the boss spawned.

again.... I HAVE CONFIRMED IT MYSELF ON BLIZZ WITH 100% ACCURACY.

Rushor, you just read that comment but it was an uneducated comment by some player who was just retarded.

**Comment by X-Savior** [comment]
Also thanks Tobi for the emote data!

**Comment by X-Savior** [comment]
I wonder if it is random based on the 50th NPC killed. Tobi, when you killed the final NPC was it then the emote happened? I am confused cause I read the comment based on final npc killed and it made sense from the 5 runs I did (4 times I had spider spawn and then when I switched to dog it was the dog boss).

**Comment by Tobschinski** [comment]
I'll do a couple of more tests right away.

**Comment by Tobschinski** [comment]
# | amount killed  | last type killed | boss
------------- | ------------- | ------------- | -------------
1 | 55  |  dog | Hyakiss the Lurker

**Comment by X-Savior** [comment]
Ok Tobi, you have proven it is random without a doubt. I must have just had bad luck.

Ok so lets implement random spawn and I believe based on these results we could go so far as to random the spawn to occur between 50-59 kills ???

Do not forget that you can again respawn the boss after the NPC respawn in a few hours plus killing the mini-boss does NOT lock you to the instance either. so in theory you could go in and farm the mini boss and never get locked to the instance until you have killed a full boss.

I say go ahead and implement based on data provided. We have all the emotes, the spawn coordinates and proof it is random spawn,

Thank You!
