### ISSUE TITLE
Ubuntu 14.04 gcc compile failing

### ISSUE THREAD

**Issue by namreeb** [cmangos/issues#820]
Currently failing when PCH is enabled.  As reported by @BeerfishWoW and @alysher.

@BeerfishWoW compiler info and revision.h:

@namreeb The code I use is the code I pull from the official CMaNGOS WotLK branch. My OS: Ubuntu 14.04 LTS. My compiler: gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4. Here's the content of revision.h in my build directory:
# ifndef REVISION_H
# define REVISION_H
# define REVISION_ID "a70007fb67b7e8657723577756aaf640ec4671f4"
# define REVISION_DATE "2015-11-29"
# define REVISION_TIME "12:59:08"
# define VERSION "0.18"
# endif // REVISION_H

**Comment by namreeb** [comment]
Information about my virtual machine:
> Linux ubuntu 3.16.0-46-generic #62~14.04.1-Ubuntu SMP Tue Aug 11 16:27:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

GCC version:
> g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

I built like this:

> git clone https://github.com/cmangos/mangos-wotlk.git mangos-wotlk
> cd mangos-wotlk
> mkdir build
> cd build
> cmake .. -DCMAKE_INSTALL_PREFIX=/home/n/mangos.bin/
> make -j8

And the build succeeded.  

> n@ubuntu:~/cmangos-wotlk/build$ ls -l src/mangosd/mangosd src/realmd/realmd 
-rwxrwxr-x 1 n n 9342815 Dec  1 18:01 src/mangosd/mangosd
-rwxrwxr-x 1 n n  401528 Dec  1 17:49 src/realmd/realmd
n@ubuntu:~/cmangos-wotlk/build$ 

My revision.h:
```
#ifndef __REVISION_H__
#define __REVISION_H__
 #define REVISION_ID "cce53ced2257ebbb00c5c9286b985b498907c0e7"
 #define REVISION_DATE "2015-12-01"
 #define REVISION_TIME "17:41:14"
 #define VERSION "0.18"
#endif // __REVISION_H__
```

**Comment by namreeb** [comment]
@BeerfishWoW @alysher, can one of you please try updating cmake to 3.x and building fresh?  I suspect this is due to the default cmake (2.8.12) in Ubuntu 14 not supporting generator expressions in the set_directory_properties() macro.

**Comment by alysher** [comment]
i got an email about updating cmake, but the message isnt here atm. however i just checked my cmake version and im running 3.0.2

**Comment by namreeb** [comment]
Yeah.  I deleted the message because I tried it myself and it didn't solve the problem.  I am continuing to work on it.

**Comment by Grz3s** [comment]
hey @namreeb 
any idea why win7 fails on fresh compile?
Log from VS2015
http://paste2.org/0pE46HHO

**Comment by namreeb** [comment]
@Grz3s can you open a new issue for it and @ me?  Let us try and prevent two conversations from occurring in the same place.

**Comment by Dainara82** [comment]
have  problems with PCH too
Debian 8.2 jessie
everything up to date

[ 13%] Generating pchdef.h.gch/game_Release.h++
<command-line>:0:4: warning: ISO C99 requires whitespace after the macro name
<command-line>:0:4: error: expected ‘,’ or ‘...’ before ‘/’ token
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.9/include/immintrin.h:43:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/4.9/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/4.9/bits/opt_random.h:33,
                 from /usr/include/c++/4.9/random:50,
                 from /usr/include/c++/4.9/bits/stl_algo.h:66,
                 from /usr/include/c++/4.9/algorithm:62,
                 from /home/mangoswotlk/wotlk/run/include/ace/Intrusive_List.inl:5,
                 from /home/mangoswotlk/wotlk/run/include/ace/Intrusive_List.h:128,
                 from /home/mangoswotlk/wotlk/run/include/ace/Cleanup.h:30,
                 from /home/mangoswotlk/wotlk/run/include/ace/Object_Manager_Base.h:28,
                 from /home/mangoswotlk/wotlk/run/include/ace/OS_NS_stdlib.inl:6,
                 from /home/mangoswotlk/wotlk/run/include/ace/OS_NS_stdlib.h:449,
                 from /home/mangoswotlk/wotlk/run/include/ace/OS_Memory.h:337,
                 from /home/mangoswotlk/wotlk/run/include/ace/OS_NS_Thread.h:36,
                 from /home/mangoswotlk/wotlk/run/include/ace/Thread_Mutex.h:31,
                 from /home/mangoswotlk/wotlk/run/include/ace/Atomic_Op.h:23,
                 from /home/mangoswotlk/wotlk/run/include/ace/Event_Handler.h:24,
                 from /home/mangoswotlk/wotlk/run/include/ace/Service_Object.h:24,
                 from /home/mangoswotlk/wotlk/run/include/ace/Task.h:17,
                 from /home/mangoswotlk/wotlk/run/include/ace/Svc_Handler.h:25,
                 from /home/mangoswotlk/wotlk/src/game/WorldSocket.h:29,
                 from /home/mangoswotlk/buildwotlk/src/game/pchdef.h:2:
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/avx2intrin.h: In function ‘__m128d _mm_mask_i32gather_pd(__m128d)’:
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/avx2intrin.h:1251:56: error: expected primary-expression before ‘)’ token
   return (__m128d) __builtin_ia32_gathersiv2df ((__v2df)src,
                                                        ^
<command-line>:0:5: error: ‘game’ was not declared in this scope

**Comment by adellaci** [comment]
For the last 3 or 4 months i have been using -DPCH=1 with no issues or errors. When it started working again i post a thread asking if anything had changed, [post](http://cmangos.net/thread-7386.html?highlight=-DPCH%3D1), but i never got a response. 

System:
Ubuntu 14.04 LTS Server x64
cmake version 3.5.0
GNU Make 3.81 x86_64-pc-linux-gnu
gcc (Ubuntu 4.9.3-8ubuntu2~14.04) 4.9.3

**Comment by cyberium** [comment]
should be fixed
