### ISSUE TITLE
area disconnecting problem

### ISSUE THREAD

**Issue by cervinzon** [cmangos/issues#821]
Hello all
I am building classic server and have an issue - often got disconnected from server and after lots of try i can tell it is depend on area where ï am (got kicked from 10 to 40 seconds there or so) . South of Tauren starting village for example. other places seems ok for now... but meybe is problem  in something completely different ...

I did try all, I think of including new database, recompiling core, reextracting maps etc... still same problem

I am using fresh git clone git://github.com/cmangos/mangos-classic.git mangos

and compiled in VS2013 with no errors

there is detailed server log and video of the same test

video http://cerv.gods.cz/cmangos/wow_error.mp4

log http://cerv.gods.cz/cmangos/Server_errlog.txt

help pls,

thanks

Cervinzon

**Comment by cyberium** [comment]
Not reproducible

**Comment by Hyperorx** [comment]
This is reproducible, my server is having the same issue. if you type in an in-correct password then it will connect after typing the correct credentials
