### ISSUE TITLE
[WotLK] win7 compile fails (VS2015) 

### ISSUE THREAD

**Issue by Grz3s** [cmangos/issues#822]
hey @namreeb 
Any idea why win7 fails on fresh compile?
Log from VS2015
http://paste2.org/0pE46HHO
thx

**Comment by namreeb** [comment]
@Grz3s From this line:
> 12>..\..\src\mangosd\Main.cpp(37): fatal error C1083: Cannot open include file: 'boost/version.hpp': No such file or directory

I would guess that your BOOST_ROOT environment variable is not set, or not set correctly.

**Comment by xfurry** [comment]
@Grz3s   https://github.com/cmangos/issues/wiki/Installation-Instructions
You need to setup a new environment variable called BOOST_ROOT that will point to the bin directory of your boost install. 
If you still have issues, let me know and I can give you more details.

**Comment by Grz3s** [comment]
thx 
I'll try... ;)
