### ISSUE TITLE
[TBC] Karazhan - Moroes Encounter Fixes Required

### ISSUE THREAD

**Issue by X-Savior** [cmangos/issues#824]
Issue #1: When Moroes vanishes he only is stealthed for a second or less. Should last 10 seconds (spell=29448)  

NOTE: Appears that for some reason this spell gets dispelled by the priest...

Issue #2: Adds on Moroes do not despawn when pulled beyond the Boss room after Moroes is Dead

NOTE: "After Moroes is dead, the raid may kill any remaining adds or despawn them by leaving the room." -http://wowwiki.wikia.com/wiki/Moroes

Issue #3: Moroes Randomly drops threat. 
Seems to be related to his gouge spell. If you try to solo him, he resets combat before you get affected by gouge. Seems like he removes you from the threat list when he uses it.

Issue #4: Towards the end of the fight, he stops using his abilities. 

If you guys can look into this please.

**Comment by tonymontoya** [comment]
I just tested this on the latest build from June 2020 and it appears to be working as expected now.  I would suggest closing the issue.

**Comment by killerwife** [comment]
Resolved.
