### ISSUE TITLE
[TBC][WOTLK] Karazhan - Maiden of Virtue Encounter Fixes Required

### ISSUE THREAD

**Issue by X-Savior** [cmangos/issues#826]
Issue 1: Able to line of sight repentance. (Check if  this is fixed)

Issue 2: Consecration should tick instantly, currently a slight delay of 1 second before damage starts.

**Comment by xfurry** [comment]
on point one, this is defined by the spell attributes and it's correct.
On point 2, I think you mean spell 29512. There is a delay indeed to this spell. We need to confirm if we need to use a lower timer

**Comment by vovk** [comment]
@xfurry yes, wee neen. Concentration should break repentance ftom meele & tank instant. Instead they all in repentance & Maiden goes to kill healers/range dps

**Comment by al3xc1985** [comment]
can be closed,,, working good @killerwife
