### ISSUE TITLE
[TBC][WOTLK] Karazhan - Chess Event Fixes and Improvements

### ISSUE THREAD

**Issue by X-Savior** [cmangos/issues#827]
Issue 1: Pet abilities Move(spell=30012) not working.      

Issue 2: Change Facing(spell=30284) not working.       

Issue 3: AoE abilities such as Rain of Fire(spell=37465) are doing damage to players controlling and not controlling pieces.       

Needs further testing on all abilities.     

Issue 4: Using a chess piece cause the normal action to be replaced with the pet action bar. Couldn't move chess piece or actual character

**Comment by killerwife** [comment]
Just fyi, this month.

**Comment by jimmybrancaccio** [comment]
@killerwife Any updates on this one?

**Comment by killerwife** [comment]
Afaik I did do the exports that month. Needs retest. Chess should work now in cmangos.

**Comment by jimmybrancaccio** [comment]
Awesome, thanks @killerwife 👍 I will move this into Needs Testing!

**Comment by killerwife** [comment]
Done incrementally over the last couple of years.
