### ISSUE TITLE
[TBC][WOTLK] Karazhan - Terestian Illhoof Encounter Fixes Required

### ISSUE THREAD

**Issue by X-Savior** [cmangos/issues#828]
Issue 1 Spawns an additional Kil'rek(npc=17229) at beginning of fight.     

Issue 2 Empty chains were spotted a couple occasions so possibly a player resisted.        

Issue 3 Chains being cast on main tank.        

Issue 5: If priest dies in chains and has spirit redemption form, chains will remain after priest dies.

**Comment by al3xc1985** [comment]
I tested a little bit... and kil'rek is not spawned at begining of fight.. he is there even if you kill terestian and respawn him, kil'rek will spawn with terestian, he is not spawned
