### ISSUE TITLE
[TBC][WOTLK] Fix Shade of Aran Encounter in Karazhan

### ISSUE THREAD

**Issue by X-Savior** [cmangos/issues#829]
Issue 1: Blizzard(spell=29969) appearance is  perhaps a bit large. ( Blizzard should be moving around the room in a circle. Currently is just everywhere.)

Issue 2 Arcane Missle doing only 350 damage a tick.

Issue 3 When teleporting players to the center it appears the Z value is off because players fly up in the air and land in random places.

Issue 4 Does not Summon Water Elementals (spell=29962, 37051, 37052, 37053).

Issue 5 Flame Wreath does no damage (spell=30004, 29946).

Issue 6 Shade of Aran does not teleport to the middle of the room when casting Arcane Explosion

**Comment by xfurry** [comment]
Point 1 and 4 are DB issues.
Point 6, also possible DB issue, as there is no dummy npc to teleport to in the middle of the room.
Point 5, has some missing spells which I don't know what exactly should do. Need more details.
Point 2 and 3, I think they are a non-issue.

**Comment by killerwife** [comment]
Fully reworked long time ago.
