### ISSUE TITLE
[TBC][WOTLK] Fix Netherspite Encounter in Karazhan

### ISSUE THREAD

**Issue by X-Savior** [cmangos/issues#830]
Issue 1: Netherspite aggro range is very large- will aggro players basically as soon as they are in the doorway.

Issue 2: No visual ray between the Nether Portals (spell=30468, 30466, 30467).

Issue 3: Needs further testing on breath and burn spells.

**Comment by AnonXS** [comment]
http://www.wowhead.com/npc=15689/netherspite

**Comment by killerwife** [comment]
Fully reworked long time ago.
