### ISSUE TITLE
[TBC] Prince Malchezzar Encounter in Karazhan

### ISSUE THREAD

**Issue by X-Savior** [cmangos/issues#832]
Issue 1: Infernals do not do any damage with their hellfire ability.

Issue 2: Weapons models for phase are missing or mob is invisible- you can still see name/nameplate and they are doing damage.

**Comment by xfurry** [comment]
Both are DB issues.
Please check with UDB.

**Comment by Saben65** [comment]
The correct modelID for the axes appears to be 33542. The displayID for the creature seems to be correct (it hides the character model and only shows the weapon) so I assume this creature just needs an equip_template with a dummy item added to item_template?

Creature Entry is 17650.

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/blob/75a9226c6301f7a0ee6c8cfe0eadadd4b657bc48/Updates/051_Fix_Princes_Axes.sql#L4

https://github.com/cmangos/tbc-db/blob/c5f5885080c480ccd76ddd7984f58a75b4eea2e0/Updates/269_creature_equip_template.sql#L6827

---

Resolved?

**Comment by jimmybrancaccio** [comment]
@X-Savior Can you confirm if this is still an issue in the latest commits?

**Comment by killerwife** [comment]
Old.
