### ISSUE TITLE
[WotLK] CMangos server crash when going online

### ISSUE THREAD

**Issue by Dainara82** [cmangos/issues#833]
Hi,
i have the following problem,
i have a fresh installation with new mangosDB 
the charactersDB i have updated
i installed all sql files from 12931_01_characters_guild.sql
couse the server don't start with not updatest characterDB
the mangos db is everything right

when the server is running and i will connect than crash the server with this Message
ERROR:SESSION: received not allowed opcode CMSG_LFG_GET_STATUS (0x0296)
the server will go on but no one can connect, if i log me out, the characters are not loading

what i can do?
please help
i set the server loglevel from 3 to 1  but the same

thx bb
Dainara

**Comment by HerrTrigger** [comment]
Topic:
http://cmangos.net/thread-7317.html
