### ISSUE TITLE
[WOTLK] DeathKnight Skill - Blood - Death Rune Mastery

### ISSUE THREAD

**Issue by Dainara82** [cmangos/issues#835]
Death Rune Mastery (Rank3)  Spell ID 50034
Whenever you hit with Death Strike or Obliterate there is a 100% chance that the Frost and Unholy Runes will become Death Runes when they activate. Death Runes count as a Blood, Frost or Unholy Rune.
it doesne't do that
Death Rune Mastery (Rank2)  Spell ID 50033       i don't know if it is here too
Death Rune Mastery (Rank1)  Spell ID 49467       i don't know if it is here too

**Comment by xfurry** [comment]
It seems that Death Rune conversion requires quite some rework in our system.
I think I've already done something like that for Cata, so I will try to implement a similar solution on Wotlk.
Stay tuned.

**Comment by jungleman2** [comment]
@xfurry any news on this?

**Comment by killerwife** [comment]
Fixed.
