### ISSUE TITLE
[WOTLK] DeathKnight Skill - Frost - Blood of the North

### ISSUE THREAD

**Issue by Dainara82** [cmangos/issues#836]
Blood of the North (Rank3)  Spell ID 54637
Increases Blood Strike and Frost Strike damage by 10%. In addition, whenever you hit with Blood Strike or Pestilence there is a 100% chance that the Blood Rune will become a Death Rune when it activates. Death Runes count as a Blood, Frost or Unholy Rune.
it doesne't do that
Blood of the North (Rank2)  Spell ID 54638       i don't know if it is here too
Blood of the North (Rank1)  Spell ID 54639       i don't know if it is here too

**Comment by killerwife** [comment]
Fixed.
