### ISSUE TITLE
Blackfathom Deeps - Altar of the Deeps

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#840]
In Blackfathom Deeps, in Aku'mai's Lair (x=-839.290283,y=-478.257751,z=-30.712105), if you click on the Altar of the Deeps it should teleport you to Darnassus(x=10073.755859,y=2356.2573.24,z=1331.892822,o=4.0)

**Comment by xfurry** [comment]
Poke @grz3s.
Looks like a DB issue.

**Comment by adellaci** [comment]
Thank you
