### ISSUE TITLE
[classic] overlapping veins

### ISSUE THREAD

**Issue by RichardGe** [cmangos/issues#842]
version 0.12.3

![asup_bugwow](https://cloud.githubusercontent.com/assets/2279126/12531865/f4f85c5c-c205-11e5-9b09-e2916b2acb28.png)

Sometimes, 1 spawn vein can contain several veins of different types.
On my screenshot, there are 5 different veins at the same point.
I see this bug in the entrance of Uldaman.

**Comment by cala** [comment]
Thank you. This is a DB issue.
Could you go to that place, run the command `.gps` and give me the zone and area id displayed in the output, please.

**Comment by RichardGe** [comment]
All the vein spawn points in this area have the issue :
![asup_spot1](https://cloud.githubusercontent.com/assets/2279126/12549795/ecdd934c-c35f-11e5-9e40-c3a1c1e29279.png)

I have also noticed this one, under water that contains 5 types of vein:
![asup_spot2](https://cloud.githubusercontent.com/assets/2279126/12549794/ecd7609e-c35f-11e5-8369-549072a08df9.png)

**Comment by RichardGe** [comment]
Here is another one  :)

![asup_another](https://cloud.githubusercontent.com/assets/2279126/12813851/00e2cb7c-cb3b-11e5-8c4f-e8c5d9e52735.png)

Thanks.

**Comment by cala** [comment]
I understand why the Uldaman vein nodes where not pooled, but the last two puzzle me however. I will look at this. Thanks!

**Comment by cala** [comment]
Ok, this is fixed and will be in the next release of Classic DB (in March).  :)

**Comment by RichardGe** [comment]
Cool, thanks :)

**Comment by cala** [comment]
Closed by https://github.com/classicdb/database/commit/a2bff2576a69fa069a6eb2f301c7a06113858cfa
