### ISSUE TITLE
[TBC] Pet Focus Does Not Regenerate

### ISSUE THREAD

**Issue by mrkarp** [cmangos/issues#843]
None of the current tamable pets regenerate their focus (mana) before / after combat.

**Comment by mrkarp** [comment]
Commented out:
void Creature::RegeneratePower()
{
   // if (!IsRegeneratingPower())
   //     return;

Temp. fix.

**Comment by Phatcat** [comment]
Just tested this on the latest master and hunters pets do regenerate focus both in and out of combat.
