### ISSUE TITLE
[TBC] Mob Loot Issues

### ISSUE THREAD

**Issue by mrkarp** [cmangos/issues#844]
So everything that isn't an instance boss / rare only drops plans / recipes. I googled for 4 days and the closest thing i could find to solving / explaining my issues is this: In Player.cpp there is no Player::SendLoot() method. I saw that someone resolved my issues in Cata's build by:
<addr>
https://github.com/cmangos/mangos-cata/commit/25f81faa9bfc21aab8f0dc38c4c5c3d983b4e015
</addr>

I cannot find anything of that nature in the TBC version so I'm guessing loot is dealt with another way.

**Comment by X-Savior** [comment]
I believe the loot issues are DB related.

DB Team requires MASSIVE overhaul of loot. Entire loot system handling on DB side is totally wrong and requires proper World Loot Implementation.

**Comment by mrkarp** [comment]
Ok, tonight I will go through the methods that handle the "Loot Groups" and see what Loot Groups are being assigned when a mob dies, then i can reference the table and check the loot that it is supposed to drop.

**Comment by mrkarp** [comment]
Any update on this? Ideas? Anyone else running into this? Getting alot of emails about changes, I cant be the only one with this issue.

**Comment by cyberium** [comment]
As its db issue we cannot realy help you currently.
However @X-Savior is right about the need to implement "World Loot" mechanism. Its more near of what Blizz realy do.
