### ISSUE TITLE
[TBC] Compilation error Visual Studio 2015

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#845]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'boost/version.hpp': No such file or directory	realmd	C:\GitHubCode\mangos-tbc\src\realmd\Main.cpp	44	
Error	C1083	Cannot open include file: 'boost/version.hpp': No such file or directory	mangosd	C:\GitHubCode\mangos-tbc\src\mangosd\Main.cpp	37	
Error	LNK1181	cannot open input file 'mangosd.lib'	ScriptDev2	C:\GitHubCode\mangos-tbc\win\VC140\LINK	1	
Configuration - Release x64/x86

**Comment by killerwife** [comment]
Same Issue in wotlk Release x64 and x86, visual studio 2015
Possible fix, comment both those lines. But there is most likely a reason why its there.

**Comment by devmaximus** [comment]
there is whole other section discussing this

https://github.com/cmangos/issues/issues/810

and solution

https://github.com/cmangos/issues/wiki/Installation-Instructions#installing-boost

compiled fine for me on windows following the installation-boost instructions:

========== Build: 7 succeeded, 0 failed, 6 up-to-date, 0 skipped ==========

**Comment by killerwife** [comment]
Closing issue. Thanks.
