### ISSUE TITLE
[TBC] Water Elemental Bugs

### ISSUE THREAD

**Issue by Tixlenra** [cmangos/issues#847]
The water elemental casts a frostbolt-like-spell but it isn't activated on its spellbars, its 'Waterbolt' spell should be activated automatically, but it disables itself everytime the water elemental is resummoned, yet it still manages to cast some type of spell. You cannot use the water elementals "Freeze" when it is casting, infact I haven't been able to use the spell "Freeze" at all. The pet attacks when its passive, ignores all commands and is unresponsive and this counts for the warlock pets too, so no doubt the same as the hunter pets.

**Comment by trimken** [comment]
try this
https://github.com/trimken/mangos-tbc/commit/de6d4b22e3e3bd82220b0ae2b601e2f3d2f58f3b

**Comment by Phatcat** [comment]
Closing this due to how outdated it is (lots of the issues solved, and those that aren't yet are reported cleaner in other issue tickets)
