### ISSUE TITLE
[TBC] Warlock Pet Bugs

### ISSUE THREAD

**Issue by Tixlenra** [cmangos/issues#848]
The warlock pets are unresponsive. the succubus will continue to cast charm even when the duration is over, so she basically just stands there with her hand out doing nothing. She attacks on passive, and when she eventually does cast charm, she breaks it herself, making the CC totally useless.

Video: https://www.youtube.com/watch?v=K-jqmQ7QcT0&feature=youtu.be

**Comment by Phatcat** [comment]
Just retested this on the latest master and the issue is no longer present.
She no longer breaks her own cc, she seems to be using it rather reasonably now, even on autocast.
