### ISSUE TITLE
[classic] bug quest "Lunar Fireworks"

### ISSUE THREAD

**Issue by RichardGe** [cmangos/issues#849]
version 0.12.3

Hi, it seems the quest "Lunar Fireworks" doesn't work :

![asup_buglunar](https://cloud.githubusercontent.com/assets/2279126/12697608/a521ddec-c788-11e5-95aa-0ec4d64b0df1.png)

**Comment by cala** [comment]
There is the same issue opened DB side: https://github.com/classicdb/database/issues/720
I did not look yet at it, so I can't tell if this indeed a DB issue.

**Comment by cala** [comment]
And thank you for reporting, by the way. ;)

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/e723950c5094a8c76d6490af9330c8e2db3716bd
