### ISSUE TITLE
Quest autocompletion after gossip

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#850]
If a gossip_menu_option is -1 and quest has the same NPC in reqcreatureorGOid as the gossip_menu,
a quest is autocompleted after talking to NPC.
Problematic code  TalkedToCreature(pSource->GetEntry(), pSource->GetObjectGuid());
in void Player::OnGossipSelect(WorldObject\* pSource, uint32 gossipListId, uint32 menuId)
in Player.cpp
It conflicts with quests like this https://www.youtube.com/watch?v=DdtsK8WGVMM&feature=youtu.be
The quest completion should be awarded several seconds into the script. This kind of behaviour is supported by dbscripts, and is out of place in code. Without removing this "remnant" which seems to be from before scriptdev was implemented, one cannot make nice/proper scripts.
Ideas?

**Comment by Grz3s** [comment]
confirmed... for [WotlK] 
Has same problem .. few Times...

**Comment by killerwife** [comment]
Ive devised a query that checks all quests that are impacted by this
select * from gossip_menu_option a join gossip_menu b on (a.menu_id=b.entry) join creature_template c on (b.entry=c.GossipMenuId) 
join quest_template d on(c.entry=d.ReqCreatureOrGOId1) where a.action_menu_id=-1; 
and on a new tbc-db it will not break a single quest. All of them already have a dbscript for "award kill objective" or have a different means of achieving it. Therefore we can change this without problems I think.

**Comment by xfurry** [comment]
I'm not sure if I understand the issue.
You say that a quest should be automatically completed after talking to an NPC given the right requirements. I think this line: https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Player.cpp#L12918

This can be done by DBscripts and I think it should work fine.

So then are you saying that this functionality is obsolete, and should be removed?

**Comment by killerwife** [comment]
Yes, because I did it in DBscripts and with this in code, it completes the quest at second 0, and should be completed in second 8. I even tested the removal since, and it works fine. The closegossip is working as intended, just the TalkedToCreature after it is mucking up dbscripts that want to close gossip window after clicking gossip.

**Comment by xfurry** [comment]
Well, then we need to know if the DB providers are ready for this.
Poke @Grz3s, @Neatelves and @cala

**Comment by killerwife** [comment]
Thats why ive written the SQL query in my other post. Ive looked at all the quests that will be affected by this, and all of them have dbscripts already.

**Comment by Grz3s** [comment]
Let me show an example:
this quest:
https://github.com/unified-db/Database/commit/4ef39e95f0cd8c599e5beaf23f63f962d0df3d09
vid:
https://www.youtube.com/watch?v=9ZyPaaXQzL4    look at 0:50

So what happened... 
with action_menu_id = -1 (gossip should close)  and script should run... but becouse smth is wrong... player was reciving credit stright after gossip closed. (werid)
What i did... 
You can see on gossip_menu_option... i set "action_menu_id = 0" and by script... 
+(921801,0,29,1,2,0,0,0,0,0,0,0,0,0,0,0,'NPCFlags removed'), -- i removed his NPC (gossip) flag ...
this way works briliant... gossip closes ... no credit is given... and script can continue fine...

So:
Do we need do anything with that problem??? (maybe they're quests that req. this thing:) )..
or 
Just use method .. i gave you here... 


BTW:
I'll check soon quest "And Now, the Moment of Truth ID: 10201" - if anything is wrong there ... im sure ill fix this using same method.

**Comment by killerwife** [comment]
My beef with your solution is that instead of changing code that is behaving not according to ANY logic, you made a workaround. The fact that quests finish after action_menu_id is not mentioned anywhere, and I had to dig in code to understand what the hell is happening. The quest I was scripting does not need such a complicated behaviour as remove npc gossip flag, and is in my oppinion a witty solution, but a convoluted one.
Im 100% sure you can solve it this way, but its unintuitive, too complicated (not to mention, you have to run one more script) and obsolete.

**Comment by Grz3s** [comment]
its not complicated.. to chane "-1" to "0"
also its not complicated to remove npcflag ( dont forget that if you want to make this quest run fine - you "must" create dbscript anyway) ,,, so what hard is to add one more line?
Anyway:
Look at this from other side:
what will happen if 2 players will come to the same npc with the same quest?
1st will use gossip few secs before second one??? what will happen if second person usee gossip again?
In my opinion ... flag must be removed anyway... no diff ... if this problem exist or not.

Finally: As i said before... I confirmed.. that this werid problem happens... but becouse we know how to avoid it... i dont know if whis should be looked at  - at all.
;)

**Comment by killerwife** [comment]
Because its a simple fix to remove one line, and the core still contains things from before DBscripts and scriptdev2 existed, and the logic of the core must be consistent.

**Comment by Grz3s** [comment]
if its that easy... do this then ;)
i'll be also happy with it

**Comment by killerwife** [comment]
Yes, your scripts has 2 unnecessary commands due to this obsolete feature, I sent the script to X-Savior so he will eventually add it to TBC-DB. Oh and you have timings wrong, the second say is before kill credit. @cala and @xfurry  let me know about your verdict, so I can make a pull request in case.

**Comment by Grz3s** [comment]
(...)Oh and you have timings wrong, the second say is before kill credit. (...)
no you're wrong ...
look at this pic: (comes from your vid)
![quest](https://cloud.githubusercontent.com/assets/2374069/12826905/2b0fbe98-cb75-11e5-8a34-dec306f3136e.png)
- text is not fully shown yet (just appearing) + emote (u can see him already doing emote=15 .. credit is given (also in same moment)

So:
Both quest credit  text+emote comes in same time ;)
i made a small update for script. 
Now should be fine :)

**Comment by cyberium** [comment]
@killerwife is that still relevant?

**Comment by killerwife** [comment]
Nope.
