### ISSUE TITLE
[All] new ACTION 'RUN' in EAI

### ISSUE THREAD

**Issue by Grz3s** [cmangos/issues#851]
Looking for new action in EventAi

xx = ACTION_RUN:
so
we could set run at spawn...

Req. for creatures like ghouls/ zombies... that running on spawn
Also req. for summoned creatures that we dont know xyz and they should run also//
Example:
https://youtu.be/3jHP8KhsTTo   0:36
thx

**Comment by xfurry** [comment]
Well, there are a couple of things we need to think about.
First I'm not sure if this will work as expected, if the creature already has WP movement. 
Second, if we want to have the creature run directly when spawned / summoned, I'm thinking it might be a better way to do this (maybe).

Let me know your thoughts.
Otherwise, the ACTION_RUN it's pretty easy to develop.

**Comment by Grz3s** [comment]
Well I'll be happy with any tool that allow us to set run for creatures at spawn...

**Comment by cala** [comment]
> Well, there are a couple of things we need to think about.
First I'm not sure if this will work as expected, if the creature already has WP movement. 

I think @xfurry is right: the spline system will allow the creature to update movement data (like its speed) on the next spline point (i.e. the next waypoint) after it got the change speed command. That means, that NPCs with waypoint movement and ACTION_RUN will walk until the second WP where they will start to run. Thus, we will need to duplicate the first waypoint to make the NPC *looks* like it runs from the first waypoint.

For NPCs without waypoint movement, ACTION_RUN should be fine. :)

**Comment by Grz3s** [comment]
Well... im asking about creatures ... without waypoints (summoned etc)

Good example.. can be ghouls in DK zoone ..they are spawned by spells... and in lots of random places... and running around :)
waypoints wont help here at all ;)

**Comment by killerwife** [comment]
Set respawned by script, and spawn them, they will have the AI you want them to have.

**Comment by Grz3s** [comment]
and how this will  help with 'running' problem?

**Comment by killerwife** [comment]
From my understanding, the gossip script will respawn the monsters, they will have an entry in the creature table, which means they can have an AI assigned to them. This AI will then run along the waypoints like for example during a normal escort quest.

**Comment by Grz3s** [comment]
- summon doesnt mean "respawn" - this means that creature can be sumoned anywhere without static guid
- waypoint will be good for static guids(if we know xyz for them) or entry from cr._template (if he has wp at all)
- AI is missing "run" option - and this is what im asking for :)

On vid i gave as example: -- u can see the same ID creatures summoned (no static guids) in 10 diff locations....  They all have waypoints... (one created for template) ... and run is set on first wp..
- so they all need to get to first wp ...and then will start running)

I simply looking for smth that allow me to set 'RUN' stright after spawn

**Comment by killerwife** [comment]
you will summon an invisible creature, you will give the "creature_template" an AI, and tell the AI to look for these dummies around it, and if it finds it to run to it, then you will run to the next dummy in range, next, next, and you have qvasi waypoints

**Comment by cala** [comment]
> Well... im asking about creatures ... without waypoints (summoned etc)

Creatures with random movement will also have the same behaviour: walking until they reach their first random point. Running afterward.
I don't know for summoned NPCs though, but it might be similar.

**Comment by Grz3s** [comment]
@cala .. but why we want to wait... until creature will reach first wp? 
I know we can set 1wp duplicating spawnpoint (i did that trick milion Times) ... but this trick wont work..
if ill give u 20 same id creatures... (summoned - spawned  - whatever) in diff locations.
- where im going to set that "25 SCRIPT_COMMAND_SET_RUN " ?? if idont know guids for them?
Using `creature_movement_template` -- ill force everyone to come to the same wp =1 and then set it? 

I thought that.. using simple new EAI action - set run at spawn will solve problem in easy way...

BTW: script for vid i showed as example can be found here:
https://github.com/unified-db/Database/commit/862cf24f75349d1d38d2323d211058e55c47d59f
And it uses method that was mentioned here  - set run on first reached wp. (its ok but could look better)

**Comment by xfurry** [comment]
@Grz3s try this and let me know if it works fine:

```diff
diff --git a/doc/EventAI.txt b/doc/EventAI.txt
index dd0bb92..bb6aa55 100644
--- a/doc/EventAI.txt
+++ b/doc/EventAI.txt
@@ -155,6 +155,7 @@ For all ACTION_T_RANDOM Actions, When a Particular Param is selected for the Eve
 47   ACTION_T_SET_STAND_STATE               StandState                      Set the unit stand state (Param1) of the current creature.
 48   ACTION_T_CHANGE_MOVEMENT               MovementType, WanderDistance    Change the unit movement type (Param1). If the movement type is Random Movement (1), the WanderDistance (Param2) must be provided.
 49   ACTION_T_DYNAMIC_MOVEMENT              EnableDynamicMovement           Enable dynamic movement behavior (1 = on; 0 = off)
+50   ACTION_T_SET_RUN                       EnableRun                       Enable run (1 = on; 0 = off)
 
 * = Use -1 where the param is expected to do nothing. Random constant is generated for each event, so if you have a random yell and a random sound, they will be linked up with each other (ie. param2 with param2).
 
@@ -922,6 +923,11 @@ Parameter 2: WanderDistance - Wander distance to be used in case the movement ty
 -------------------------------
 Parameter 1: EnableDynamicMovement - Enable dynamic movement behavior. 1 = on / 0 = off.
 
+----------------------
+50 = ACTION_T_SET_RUN:
+----------------------
+Parameter 1: EnableRun - Enable run. 1 = on / 0 = off.
+
 =========================================
 Target Types
 =========================================
diff --git a/src/game/CreatureEventAI.cpp b/src/game/CreatureEventAI.cpp
index 4917863..230e8d7 100644
--- a/src/game/CreatureEventAI.cpp
+++ b/src/game/CreatureEventAI.cpp
@@ -1055,6 +1055,11 @@ void CreatureEventAI::ProcessAction(CreatureEventAI_Action const& action, uint32
             SetCombatMovement(!m_DynamicMovement, true);
             break;
         }
+        case ACTION_T_SET_RUN:
+        {
+            m_creature->SetWalk(!action.setRun.state, true);
+            break;
+        }
         default:
             sLog.outError("CreatureEventAi::ProcessAction(): action(%u) not implemented", static_cast<uint32>(action.type));
             break;
diff --git a/src/game/CreatureEventAI.h b/src/game/CreatureEventAI.h
index a6885c8..7f61ad1 100644
--- a/src/game/CreatureEventAI.h
+++ b/src/game/CreatureEventAI.h
@@ -121,6 +121,7 @@ enum EventAI_ActionType
     ACTION_T_SET_STAND_STATE            = 47,               // StandState, unused, unused
     ACTION_T_CHANGE_MOVEMENT            = 48,               // MovementType, WanderDistance, unused
     ACTION_T_DYNAMIC_MOVEMENT           = 49,               // EnableDynamicMovement (1 = on; 0 = off)
+    ACTION_T_SET_RUN                    = 50,               // EnableRun (1 = on; 0 = off)
 
     ACTION_T_END,
 };
@@ -422,6 +423,13 @@ struct CreatureEventAI_Action
             uint32 unused1;
             uint32 unused2;
         } dynamicMovement;
+        // ACTION_T_SET_RUN                                 = 50
+        struct
+        {
+            uint32 state;                                   // bool: 1 = on; 0 = off
+            uint32 unused1;
+            uint32 unused2;
+        } setRun;
         // RAW
         struct
         {
diff --git a/src/game/CreatureEventAIMgr.cpp b/src/game/CreatureEventAIMgr.cpp
index 3d89a7a..5fe13f8 100644
--- a/src/game/CreatureEventAIMgr.cpp
+++ b/src/game/CreatureEventAIMgr.cpp
@@ -837,6 +837,7 @@ void CreatureEventAIMgr::LoadCreatureEventAI_Scripts()
                     case ACTION_T_RANGED_MOVEMENT:          // Distance, Angle
                     case ACTION_T_CALL_FOR_HELP:            // Distance
                     case ACTION_T_DYNAMIC_MOVEMENT:         // EnableDynamicMovement (1 = on; 0 = off)
+                    case ACTION_T_SET_RUN:                  // // EnableRun (1 = on; 0 = off)
                         break;
 
                     case ACTION_T_RANDOM_SAY:

```

**Comment by Grz3s** [comment]
@xfurry :+1: 
pls http://paste2.org/ ;)

**Comment by xfurry** [comment]
There you go: http://paste2.org/PE0aIny6

**Comment by Grz3s** [comment]
this will be more diffucult :)

Compiled fine:
...
 I tried this line:
```sql
('1749501','17495','11','0','100','0','0','0','0','0','50','1','0','0','0','0','0','0','0','0','0','0','Stillpine Raider - Set Run on Spawn'),
```
- for creature (static spawn/summon) with randomovement = doesnt work - they walk
- for  creature (static spawn/summon) with waypoints:
Creature will walk to first WP .. and then will start running (this works exact the same like db-script = 25 SCRIPT_COMMAND_SET_RUN"

I remember when 'RUN' command was broken... and then someone explained ..that running is the default movement for all creatures ... and walk is set for each spawn by core.
So probably ... exception from this, need to be done directly in core  ...
Any idea ?:)

**Comment by Ulduar** [comment]
https://github.com/cmangos/mangos-cata/pull/48/files
My old pull, all of the commands tested a bunch of times, and not me alone.
A lot of commands on many occasions. Examples will, brought a billion times.

I posted this in order to support @Grz3s

**Comment by killerwife** [comment]
Hmm possibly add to dbscripts TEMP_SUMMON_CREATURE "spawn running" or something. Yesterday I encountered this problem and I had to postpone waypoint movement until after SD2 reset function to make it work properly.

**Comment by Ulduar** [comment]
``` QUOTE
spawn running
```
Bullshit.
I suggest you the normal solution.

**Comment by killerwife** [comment]
Those commands are a little unintuitive, why is there ACTION_T_SET_RUN and ACTION_T_DISABLE_RUN instead of a 0 1 parameter (thats how rest of EventAI is done), in addition to that, even that won't solve Grz3s problem, because the creature will still walk to the first waypoint.
To make the creature not walk to the first waypoint you have to do "creature->setWalk" before bool Creature::AIM_Initialize()/before its added to map (not exactly sure which).

**Comment by killerwife** [comment]
@Grz3s What about this. Command TEMP_SUMMON_CREATURE will have an optional parameter to spawn a creature with RUN set to true. Which means that before the first waypoint is done through spline, it will already be running. Since only dataints are free at this point, lets say set dataint1 to 1 and the running will be set at spawn. As I said previously, for this to work with waypoint movement, it needs to be set during spawning, not later.

**Comment by xfurry** [comment]
It might be a good idea

**Comment by killerwife** [comment]
https://github.com/killerwife/mangos-wotlk/commit/8fe3eaedfd62630913f66337afde54833ef1cc1f

There you go, done. Tested it on morladim in duskwood using dbscript on gossip.

INSERT INTO dbscripts_on_gossip VALUES(5750,0,10,522,0,0,0,0,1,0,0,0,-10389,383.148,46.9751,6.15685,'Test tempsummon run');

Notice the 1 in the dataint.

**Comment by Grz3s** [comment]
:+1:

**Comment by xfurry** [comment]
@Grz3s please confirm if this code works fine for you.

**Comment by Grz3s** [comment]
@xfurry 
Yes .. it works fine.. just tested with fresh newest compile...
Creatures run on spawn
:+1:
