### ISSUE TITLE
[classic] item "Charges" doesn't decrement when used.

### ISSUE THREAD

**Issue by RichardGe** [cmangos/issues#852]
Hi,

The Charges of the item : http://wowwiki.wikia.com/wiki/Dog_Whistle   doesn't decrement when used. So it can be used infinite number of time.
Don't know if it's core or database issue.
Not 100% sure, but I think I remember that it's not the first time that I see an object with bugged Charges decrementation...

![asup_charge](https://cloud.githubusercontent.com/assets/2279126/12846447/022e6608-cc0d-11e5-8227-8b4b81b157a1.png)

**Comment by RichardGe** [comment]
I have tested with other items, it seems that all items with  spellcharges_1  <  0   doesn't have a decrement. Why spellcharges_1 is negative for those items ? Maybe this negative number explain why the decrement doesn't work ?

items tested that doesn't decrement :
Dog Whistle  (entry = 3456)   (spellcharges_1 = -3)
Mechanical Greench  (entry 21325)    (spellcharges_1 = -3)
Rotten Apple  (entry 15875)    (spellcharges_1 = -5)
...etc... I think all items don't work....

**Comment by cala** [comment]
spellcharges<0 means infinite charges if my memory serves. That would explain what happens. :)

**Comment by cala** [comment]
Could you please test those items with a positive values? Merci.

**Comment by RichardGe** [comment]
I have changed spellcharges_1 of Rotten Apple from -5 to +10.
The number of charges has been changed correctly to 10 in game. But it still doesn't decrement.

**Comment by 0x2aff** [comment]
Cant confirm.  [898f9ad](https://github.com/cmangos/mangos-classic/commit/898f9ad4125f6179fa5003852523751efdc6868b) works perfectly.

**Comment by cala** [comment]
Thank you for this update. Could @RichardGe confirms that the bug still exists, please?

**Comment by RichardGe** [comment]
I have double checked, this bug was caused by a modification of the database done on my side, my bad.
So, yes, 'charges' works perfectly, 
Ticket can be closed.
