### ISSUE TITLE
[Wotlk] genrevision error on compile

### ISSUE THREAD

**Issue by Grz3s** [cmangos/issues#853]
Hi
Looking for help... 
It always worked fine...
I tried to compile fresh cmangos for [Wotlk] on Win7... and reciving an error
pls look at this pic when it happens:
![nowy obraz mapy bitowej](https://cloud.githubusercontent.com/assets/2374069/12866799/6ad1b7a2-ccd3-11e5-8b68-8a08b9965ca0.jpg)
Sor for lang: .. it jjust simple says - program genrevision.exe stoped working :/

I tried to debug this issue.. and here what it shows:
![blad](https://cloud.githubusercontent.com/assets/2374069/12866815/adaeb1c4-ccd3-11e5-8c5a-b05fdf2f1fe8.png)
And dump from "output"
http://paste2.org/nUGp6h7s

It may be only issue on my cpu... but I tried to do all i can without positive result:
- tried remove visual studio 2015 (install from scratch)
- new cmangos (sources)
- fresh BOOST install

Anyone has any idea what may fix this issue?
Thanks for any help.

**Comment by xfurry** [comment]
I have no idea, but I would maybe start by deleting the bin folder and the VCxxx subfolders.
I'm using VC120 and I didn't encounter such a problem.

**Comment by cala** [comment]
Building on Mac OS X, I obviously did not have that issue. And the core compiles fine as of https://github.com/cmangos/mangos-wotlk/commit/fd63dd2d0e88d9d78a710ed6f0f4d82d092aba91 for me. Sorry for being of such little help, here.

**Comment by Grz3s** [comment]
well ... last hope :)
I'll reinstal win7 + all programs (req.) -- last Chance for this :/

**Comment by Grz3s** [comment]
ok.... new win7 + all req. programs  = no Change ..
still got same error:
Also i found few stupid ideas like 
- run vs as administrator didnt help
- tried both versions of boost for boost_1_60_0-msvc-14.0-32 and boost_1_60_0-msvc-14.0-64 ,,,
log from compile:
http://paste2.org/dgnHFPVG

-- if ill build genrevision first,,,
and then jumpt to shared "Build only shared"
-- im reciving that crash (look at first pic -- that genrevision stoped working)
and this error:
"1>------ Build started: Project: shared, Configuration: Release Win32 ------
1>  Extract revision
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code -1073741819.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped =========="

-- from error list:
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"cmd.exe" exited with code -1073741819.	shared	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	

Im giving up.
Lost last weekend + monday on this :/
So It looks like this is it. 
If anyone has any idea ...
thanks

**Comment by xfurry** [comment]
Poke @cyberium

**Comment by cyberium** [comment]
Oh sorry you have so much issues.

I unfortunatly have no time currently, however i'll try to look at this problem asap.
Please confirm its VS2015 or VS2013?
I remeber had some issue too when @stfx worked on removing revision number. Maybe he have more input han me on this at first glance.

**Comment by Grz3s** [comment]
VS2015

**Comment by xfurry** [comment]
Try with 2013

**Comment by Grz3s** [comment]
i did small trick... 
I created missing (FAKE) revision.h file in  ...\mangos\src\shared\.
```code
#ifndef __REVISION_H__
#define __REVISION_H__
 #define REVISION_ID "*"
 #define REVISION_DATE "*"
 #define REVISION_TIME "*"
 #define VERSION "0.0"
#endif // __REVISION_H__
```
and then i started from genrevision... and step by step.. 12 solutions (all without error)
and only solution i didnt build was that "Shared"

All looks fine - core starts.. with small issue (not important i hope)
```sql
2016-02-09 19:21:53 CMaNGOS/0.0 (* * - *) for Win32 (little-endian) [world-daemon]
2016-02-09 19:21:53 <Ctrl-C> to stop.
2016-02-09 19:21:53 
``` 
no rev time and version is set :)

So my question is... 
Is that "shared"  important to build? (i mean ... do i missing smth?)
or its ok to build in this way ( read i have no other option) :)
@cyberium @xfurry 
Thank you

**Comment by cyberium** [comment]
Ofc Shared is important, but revision is not. Seem's that it fail to get correct revision from github hash. Nice that you isolated the issue so i think i could reproduce it if i remove revision.h

**Comment by evil-at-wow** [comment]
Looking at the screenshot of your debugger, the code in genrevision.cpp is not prepared to handle the input it gets on your system, so I'm saying it's wrong. I can assure you that Visual Studio or your system are not at fault here!

What genrevision does is read whatever is in .git/logs/HEAD in your WoTLK repository. That is a file maintained by git. Looking at the code, genrevision expects this file to contain lines of the format `<hash> <hash> <git user> <e-mail address> <timestamp>[TAB]<commit description>`. In my repositories, that seems to be the case indeed. In your case however, your debugger shows this file contains at least one line that does not end with a tab and a commit description (see the 'time' variable in your debugger - it ends with the timestamp and a newline). I'm not sure how to get in this git state, but that doesn't really matter. What matters is that this causes `strchr(time, '\t')` to return a null-pointer, so assigning a value to it on the next line is crashing the application.

Considering that the code that follows this part also seems wrong - there is more than one space in the part with the e-mail address - I'm starting to wonder if this code was ever called at all. And if it wasn't called before, I'm wondering what's changed so it's called now.

Anyway, I'm not going to figure that out now, so as a quick and dirty workaround you can try to change the genrevision code where you debugger stopped as follows:

```
if (!strcmp(data.rev_str, hash))
{
    char *tab = strchr(time, '\t');
    if (tab) 
        *tab = '\0';

    time = strrchr(time, '>') + 1;
    rev_time = atoi(time);

    break;
}
```

With that change, you should be able to build and run genrevision again.

**Comment by Grz3s** [comment]
@evil-at-wow your explanation... gave me another idea... 
I not only removed all sources... and then clone fresh into same folder..
This time i created a new one with diff name ... and on diff location and then...
using git bash i cloned wotlk once again.
Gues what: 
```code
========== Build: 13 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
How the hell ... even with system reinstall +  vc + git + etc... (all fresh)
some corrupted info was still kept in that old folder and even with fresh sources .. was still doing the same :/ (mystery what created this issue anyway)

Where this info is hidden?

Thank you very much.. and all ppl here for your time... (i almost gave up with this sh*^).
*beer* :+1:

**Comment by evil-at-wow** [comment]
You've probably reinstalled your OS and software, but kept your data (for obvious reasons). That didn't help, because the unexpected data was in your repository itself, namely in the .git directory that git creates in each repository (note the dot in the directory name). I don't remember if Windows Explorer is showing you directories that start with a dot by default, so you might have to turn on the option to show hidden files, but it should be there.
