### ISSUE TITLE
[Classic]Hive'Ashi Scout Report

### ISSUE THREAD

**Issue by yyhhrr** [cmangos/issues#856]
Currently Cenarion Scout Jalia does not offer the report.I saw there was db script that support the item.But the npc did't show the gossip util I set GM ON.Who can reproduce this?

**Comment by cala** [comment]
Could you please try on your DB:
```SQL
UPDATE `gossip_menu_option` SET `condition_id` = 1111 WHERE `menu_id` = 6691 AND `id` = 0; 
```
Restart realmd and mangosd and tell me if this works, now.

**Comment by yyhhrr** [comment]
Great!It works.

**Comment by cala** [comment]
Thanks!
