### ISSUE TITLE
spell_template  spell needs two effects

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#857]
This spell http://www.wowhead.com/spell=37097/crate-disguise#comments
The triggered server-side spell missing from dbc needs to do two things, trigger event 13852 and cast a stun aura on the player for the duration of the spell. Our spell_template table only supports one effect per server-side spell. 
Workaround is to add stun aura apply and remove on 37097 aura effect 0 application and removal.
Any verdict upon this issue?

**Comment by Grz3s** [comment]
server side spells - are a big problem to all. Many Times this subject was in ppls heads.. and asu can see still nothing changed in this case;)
I wouldnt even try again - its just impossible to get them (like we have other stuff)
Best way is to know exact. how they work - what changes they do to player, creatures etc...
Then use DbScripts on spell if we can - or script them directly in core. 

Looking at this spell - i dont know where this info about event = 13852 comming from?(maybe i missed smth. with fixing this quest - but it was few years ago so everything is possible ;)
but this i what we know about it:
```code
ID - 37097 Crate Disguise
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 56 (SPELL_AURA_TRANSFORM), value = 1, misc = 21629 (21629), miscB = 0, periodic = 0

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 3
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 139 (SPELL_AURA_FORCE_REACTION), value = 3, misc = 73 (73), miscB = 0, periodic = 0

Effect 2: Id 64 (SPELL_EFFECT_TRIGGER_SPELL)
BasePoints = 1
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Trigger spell (37492) Not found, Chance = 101
```
37492 - this spell is missing and i dont think that we'll ever get it :(

Anyway quest is scripted fine for both races in Wotlk.
I remember that X-Savior had a problem with backporting it into TBC.. (smth was forgotten in core updates (backports between WOTLK --> TBC)), So script didnt work correctly there.
If q. still doesnt work for TBC - I would start with checking whats missing in core.

BTW:
If you are interested how it works in WoTLK... i recorded it few mins ago ...
https://www.youtube.com/watch?v=IgOdQ0oIJCU&feature=youtu.be

**Comment by killerwife** [comment]
Thank you but I already fixed the quest this morning and gave it to X-Savior. Also I implemented the root mechanic when the player is the "box" in the core.
The information I spoke of was on the trinitycore github, and Id rather not link the issue here for obvious reasons. I need to ask a question tho. What spell or script did you use so that the player doesnt move? BTW your fix needs a core side fix, the "box buff" is supposed to be a debuff, so it cant be dispelled. Check it out on youtube.

**Comment by Grz3s** [comment]
(...)is supposed to be a debuff, so it cant be dispelled(...)
yes its true.
About spell:
ID - 48342 Stun Self

**Comment by killerwife** [comment]
Thank you, im gonna close this issue then. Should you come by IRC, spam me, Im gonna give you a list of TBC quests im working on for X-Savior.

**Comment by xfurry** [comment]
@killerwife 
if you find a missing spell in DBC usually you should try to implement it in core / script.
In case you really need some effect from a missing spell, you can go ahead and add the spell with the desired effect, while keeping the rest in core / script.

**Comment by killerwife** [comment]
What I did is add spell to spell_template to trigger specific event, and add 48342 spell on aura apply and remove spell 48342 on aura removal. Yes it works as intended, but it required spellauras.cpp addition. I just thought it was a bit cumbersome.
