### ISSUE TITLE
[CLASSIC] Stats Are Not Scaling Correctly

### ISSUE THREAD

**Issue by ghost** [cmangos/issues#858]
Hi.

Just made a 29 twink and geared it up. The crit seems really low for the amount of agility it has. If I recall correctly my 29 rogue on retail had somewhere around 30% with worse gear.

No idea if this is a known issue but never the less I thought It's worth a mention.

http://i.imgur.com/6sOL3Ra.jpg

**Comment by Warlockbugs** [comment]
This not only affects crit, but pretty much everything. Vanilla's stats system is crooked.

The non-exhaustive list of leveling issues:
* Melee Crit chance
* Ranged Crit chance
* Spell Crit chance
* Dodge chance
* Regen
* Player leveled stats (per race/class/level) are a complete copy from TBC and need to be verified

Recently i've touched Spell Crit and found out that Hunter's base spell crit chance and spell crit from Int are also missing completely from vanilla core.

In TBC and WotLK we use a set of DBCs for scaling:
```
gtOCTRegenHP.dbc
gtOCTRegenMP.dbc
gtRegenHPPerSpt.dbc
gtRegenMPPerSpt.dbc
gtChanceToMeleeCrit.dbc
gtChanceToMeleeCritBase.dbc
gtChanceToSpellCrit.dbc
gtChanceToSpellCritBase.dbc
```
A replacement implementation highly wanted for Vanilla.

**Comment by killerwife** [comment]
https://github.com/vmangos/core/blob/development/src/game/StatSystem.cpp#L492
