### ISSUE TITLE
Flyby "use item" Missions to Damage Same Creature More Times

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#859]
http://www.wowhead.com/quest=10438/on-nethery-wings
Quests such as these require the player and the creature to stay in combat longer than the standard time, especially since the creature that is targeted does not engage the player in any way.

The issue here is that once the player hits the creature, they enter combat for a split second and they leave again, leaving the creature regenerating.

Current workaround is to place the creature in combat with the zone, but this can have issues when the creature is unloaded from grid and player is not removed from combat. Basically with specific creatures the combat removal should work like in PVP, (baseline timer until which combat will not expire) or with a completely different mechanic like "is still in range" with a specific margin, because the monster is not supposed to regenerate until the flyby is done. Another workaround is to set creature regen to false, but im not quite sure this would be blizzlike per se.

Any ideas?

**Comment by cala** [comment]
Good point. The in/out of combat needs a bit of improvement indeed.

**Comment by killerwife** [comment]
As far as I know, the problem is only with creatures that are stationary and don'­t attack back, but currently I'm not familiar enough with the combat code to provide any solution.

**Comment by killerwife** [comment]
Resolved at least for nethery wings.
