### ISSUE TITLE
[3.5.5a]Ike3 AHBOT and playerbots trinitycore

### ISSUE THREAD

**Issue by sout12** [cmangos/issues#862]
My questions are related to this http://ike3.github.io/mangosbot-docs/.

1) How to make the bots only alliance.
2) How to make the bots all teleport to one place or spawn in one place.
3) Any updates coming out?
4) How to get bot to train spells and use talents
5) How to make the bots have better armor
6) HOw to the make the bots the parameters for the best performance
7) How to make the bots be faster at reacting at attacking them or healing some1
8) Anyway to make bots arena,bg or basically invite random bots to join together and level or pvp or something just in a group?
9) How to make the bots level on their own such as quest and such
11) No bot Death Knights?
12) How to fix the dungeon finder, if i have a full group, it doesn't find a group, 3 dps 1 healer 1 tank.
13) How to make the bots que for dungeons themselves
I realize most of my questions or basically request because most of the questions i ask are very hardly to code i understand that, but if anyone is willing to...
14) Bots keep spamming for me to join a dungeon while in a party, how to fix?
AHBOT problems.
Well here is my worldserver.conf http://pastebin.com/L3N4kFrJ
My AHBOT.conf http://pastebin.com/4bdPE9Qu
What am i doing wrong?
I set the intervals to 50 because i was trying to test and see if it would be faster but it is still set to 300 seconds and it says in the world console and it doesn't buy or sell items fast. Well it hasn't bought any of my items at all.
Their is only 71 total items on the auctionhouse and its been that way before i set the intervals, it does not sell items fast ;c
Can you set the it up where bots buy bots items also?

**Comment by cala** [comment]
I'm sorry, but most your questions are related to Ike playerbot, not the CMaNGOS core that is Blizzlike and as such does not have bots. I suggest you contact the developpers/admins of http://ike3.github.io/mangosbot-docs/ for questions related to bots.
For your other questions, you are refering to the TrinityCore implementation of AHBot. Again, I suggest you contact the relevant dev team: https://github.com/trinitycore

If you have any questions regarding CMaNGOS core, we will be happy to help you.
