### ISSUE TITLE
Set creature parry dynamically

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#864]
Currently, I do not know of any way to dynamically make a monster attain parry passive. Spells for parry require the target to be a player. The only way to alter this is to change ExtraFlags in creature_template.

The issue here is that Prince Malchezaar parries only during second phase of the encounter. Thats why we need a means to change it between phases. 

I propose addition of a bool to Creature class canParry, similar to Player class where it is already present. Alterations will have to be made to the combat evaluation code but that is a minor nuisance.

**Comment by Warlockbugs** [comment]
The feature is now implemented.
