### ISSUE TITLE
LOS overriding

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#865]
There are some spells, that require ignoring of LOS. Currently I havent seen an attribute that indicates this. Such spells that require this are 30835, 35514. First one is in karazhan, summoning infernal in the proper way, and second is salaadins tesla, used to make a beam between an npc in a tube and a different npc.

Currently, the workaround is to place return true in checktarget right before checking for LOS, any other suggestions?

**Comment by cala** [comment]
IIRC, currently you can also set which spells should ignore LOS in mangosd.conf.
Probably not the proper way to do it, though.

**Comment by killerwife** [comment]
Well there is one more spell, 30836, + all of these spells have SPELL_ATTR_UNK8. Wonder what that means.

**Comment by xfurry** [comment]
I think there is already some attribute that makes spells ignore LoS.

**Comment by killerwife** [comment]
Also one thing to note, all of these spells have maximum 50000 radius "anywhere". Maybe such spells should ignore los everytime?

**Comment by Schaka** [comment]
Spells that have such a radius are Mind Vision, Far Sight, Eagle Eye, etc. All of these ignore LoS. 
There are other spells that should ignore LoS though, like those that qualify as "auras". For example Bloodlust/Heroism and that contain "to party/raid members" or your pet (Mend Pet).

So I'm sure there are some attributes why which you can tell they should ignore LoS.

**Comment by xfurry** [comment]
> Also one thing to note, all of these spells have maximum 50000 radius "anywhere". Maybe such spells should ignore los everytime?

If we are talking about 3.x version, I already replied before that there is an attribute for LoS ignore and it works well. We shouldn't ignore LoS every time for these spells, as most of them actually use script targets and they need LoS.

Most of the spells already have cast radius which is used to calculate the targets impacted and some spell hit radius in case of auras, that defines the aura radius.
The spells that apply to party / raid targets, then only the party / raid members are affected.

**Comment by killerwife** [comment]
Understood. So the spells I mentioned have to be solved case by case until further stuff pops up.

**Comment by xfurry** [comment]
Well, I'm not sure why are you mentioning spell 30836.
This is just a simple summon spell, so I think you are actually talking about http://www.wowhead.com/spell=30835/infernal-relay which is the main spell that triggers 30836

**Comment by killerwife** [comment]
Well there is an invisible ceiling above prince which means that every spell, including 30836 is LOSed :)
But I also figured out the reason behind 30834 tho thats related to fel reaver visibility :)

**Comment by cyberium** [comment]
Lot of work was done about LOS i think we can close this. Reopen if its not yet fixed
