### ISSUE TITLE
Creature attack plays wrong sounds

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#866]
Creature http://db.vanillagaming.org/?npc=3206#drop plays sword attack sound when attacking with staff. Any idea why? Might be a global issue, currently unknown if localised.

**Comment by cala** [comment]
IIRC, sounds are defined in DBC for items/creatures, more precisely by their model.
So if this issue only occurs with this mob, we can assume that the DBC are wrong (that already happened elsewhere with a male NPC model using female voice).

**Comment by cyberium** [comment]
@killerwife is this still occuring?

**Comment by killerwife** [comment]
Yes, unfixable issue without modifying client. Issue in clients DBCs. So unless we plan to redistribute illegal client code that would get us a shutdown, you can close this.
