### ISSUE TITLE
Quest To catch a Thistlehead script missing

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#867]
Harha implemented a quest script, I just cleaned it up. https://gist.github.com/killerwife/adc47e9634395c27a5ed
X-Savior will take care of the ACID change, if possible someone review it and commit it to cmangos :)

**Comment by Grz3s** [comment]
Hi @killerwife 
Pls remember that Cmangos is a Core... for few diff versions of WoW:
1.x.x 
2.x.x
3.x.x
4.x.x
Also  They're few Database providers for this core.
UDB
YTDB
Project Silvermoon
and sory If i missed smth/

Your fix is for Database not Core ;)... and should go to correct place.
Anyway if im right only into 2.x.x becouse all other have this quest fixed alredy ;)

**Comment by killerwife** [comment]
There is a diff inside for core as well. I pasted it in one place so its public. It is not my job to decide whether to implement it into wotlk/tbc. This fix requires both database and code changes, without both it will not function properly.

**Comment by Grz3s** [comment]
Once TBC-BD was sync. with UDB Wotlk ... but i see this is not a case anymore.
I'll (and Cala) keep sync.
https://github.com/classicdb/database/commits/classic
https://github.com/unified-db/Database/commits/master
as much as its possible...
So pls ...   precise what ver is req. for your fixes.
Im not going to upset you anymore :D ... sory 
Anyway: Thanks for your work ;) 

@xfurry can you pls add [TBC] to this...
Wotlk do not need this fix at all.

BTW:
Aggro texts works perfectly fine with ACID.

**Comment by killerwife** [comment]
Yes but you cant despawn a gameobject through DBSCRIPTS that is not source of spell_effect_send_event, therefore you cant despawn bundle of bloodthistle through DB only. I have a list of quests that are bugged on TBC. Should you come by IRC, I am gonna give you a list and you can tell me which quests are not bugged on wotlk so I can find them and notify you guys. If I had known that this quest was done in UDB/Wotlk I wouldve ported it. Right now I dont have a wotlk client.

**Comment by Grz3s** [comment]
well its done in this way:
https://github.com/unified-db/Database/commit/a41527d0dbc8c68232fd75ec0ec762ffe952920c

**Comment by killerwife** [comment]
*facepalm

I will edit my fix to remove script part and will edit my GIST so its done DB only.

**Comment by killerwife** [comment]
One thing to note, Grz3s, I found your fix. Why does it have dbscript COMMAND EMOTE instead of EMOTE in db_script_string ^^ When the creature speaks the emote, it can perform the emote in db_script_string as well, without additional dbscript commands. I thought I'd let you know. I will give your fix to X-Savior

**Comment by Grz3s** [comment]
because script was made before we were able to set emote in db_script_string.
You can simply update it. if u want to.

**Comment by killerwife** [comment]
Didnt know that. Yes I am updating it but not because its bad, but because the DB works slightly differently in TBC.
