### ISSUE TITLE
Special Creatures Visibility Range

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#868]
Do we know how to make certain creature be visible from afar? Good example is Fel Reaver in Hellfire Peninsula or Infernal Relay spell in karazhan.

**Comment by VladimirMangos** [comment]
Possible will help make it active object (it will triggering load cell around self and must be visible).

**Comment by AnonXS** [comment]
recently saw in code that something is in place for "GuardAI" npcs so maybe they also need something similar.

**Comment by al3xc1985** [comment]
Fixed @killerwife
