### ISSUE TITLE
Make creature_addon_template Be Usable with Mini-Pets

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#869]
There are pets that have inherent auras example Living Flare 24916 aura 44880.

Two issues arise, GetGUIDLow() of minipets is conflicting with normal creature GetGUIDLow().
Second, one can not access m_originalEntry of minipet from outside (I also don't understand why minipet doesn't have normal entry, since this creates a different issue when we want to check for specific minipet).

Proposed solution: Check for HIGHGUID_PET in GetCreatureAddon() and in Create of minipet assign proper creature entry.

Functionality is needed for quest http://www.wowhead.com/quest=11516/blast-the-gateway

**Comment by LordUsagi** [comment]
Not only used for this quest case either. Creatures like Egbert have passive auras present that control its behavior.

**Comment by Phatcat** [comment]
@killerwife was this not fixed back in 2016? I'm pretty sure it fixed oozlings for classic and tbc and it was a commit you made yourself addressing this specific issue.
https://github.com/cmangos/issues/issues/107#issuecomment-226961687
https://github.com/cmangos/mangos-classic/pull/124/commits/47274eb44943a92e1d60a0268655dd11b6b1183c#diff-07d7427618f296efb8683a3b3cc8a31cR1956

**Comment by killerwife** [comment]
Resolved a long time ago.
