### ISSUE TITLE
[TBC] Boar "Charge" is Bugged

### ISSUE THREAD

**Issue by Tixlenra** [cmangos/issues#870]
Tame any boar, it will come with charge and be broken. You can spam it EVEN THOUGH it has a cooldown. It doesn't charge to the target, it just walks like normal to it (though it glows red like it's supposed to).

**Comment by BareRose** [comment]
On classic the cooldown works correctly and charge cannot be spammed, however the boar doesn't actually charge to the target and just walks normally. Possible that the underlying problem is the same in both classic and TBC.

**Comment by BareRose** [comment]
(No idea what happened with the assign there, definitely wasn't intentional.)

**Comment by Phatcat** [comment]
Yet it might have as well, not part of the team and havn't been for a while.

**Comment by BareRose** [comment]
Oh. You'll continue contributing here and there though, right?

BTW is there any way for me to contact you directly? Been meaning to ask and if you're no longer active on cMangos I might not bump into you again. I'd've just sent a PM but github doesn't have those and last I check you weren't on the cMangos forums.

**Comment by Phatcat** [comment]
I am on discord, just not on the cmangos servers, you can join this generic server I've set up for random chat; https://discord.gg/8y7WKFD

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/df77a1d5a219cf68358134e1e3d0ace81ca9350f
