### ISSUE TITLE
NPC Buster Worm Visual Bug

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#871]
The npcs scripted in struct npc_burster_wormAI : public ScriptedAI have a strange bug.
When the mob is about to properly resurface, a brief maybe 0.4 second popup occurs before the actual "birth" spawn animation occurs.

So far I have only found out that it is caused by removal of SPELL_TUNNEL_BORE_PASSIVE (which should be removed), because a visual update is called in between removal of this passive and the BIRTH spell.

Any ideas how to fix it? This problem occurs on TBC, maybe on other cores.

**Comment by Grz3s** [comment]
belive or not ... we spent on this worm enough time to get to point where it is now.
It was so difficult ... to make him working correctly...
and this funny visual bug.. is nothing compare to what it was before..
profit to @xfurry for this.
more info you will find here:
https://github.com/unified-db/Database/issues/124

**Comment by killerwife** [comment]
I have investigated every piece of code xfurry wrote, dont worry, I know he did an amazing job. I spent almost 6 hours trying every possible combination of aura removal and other tricks to force the aura to not be updated until the "birth" begins. 

My theory is that since everything is multithreaded, the removal is sent for visual update just before the birth visual update. When the server is forced into specific conditions of not keeping up, the popup doesnt happen because grid update is not called between removal and birthing. My guess is that we need some sort of synchronization after removal of bore passive to prevent this bug.

**Comment by killerwife** [comment]
spellid 26062 named Birth Cast, possibly something to do with the animation

**Comment by xfurry** [comment]
Hello.
What is the issue with this creature again? I thought we fixed this for good some time ago.

The animation works fine, but because of the core behavior, the creature model is first shown in full for a fraction of a second, and only after it casts the animation spell. I think this is because there is some object visibility update in between the two actions. I don't know how to fix this, and I don't think it's a very big issue.

**Comment by killerwife** [comment]
Yes, that is exactly what I came up with myself when thoroughly debugging. I doubt that blizz had some sort of weird synchronization solution, there is most likely a spell that postpones the visual update. I'm gonna play with it later on to see what that 26062 spell does.

**Comment by xfurry** [comment]
There is no other spell. This is just a sync issue, that's all. And it happens to all creatures which cast a visual spell on spawn that involves changes in the creature model.

**Comment by killerwife** [comment]
Fixed by me a long time ago.
