### ISSUE TITLE
MCd creature spell CD

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#873]
**Current behavior**: 
When controlling a creature, or DoSummonPossesed in certain quests, when a creature uses its spells, the cast bar doesnt reflect the cooldown.
**Expected behavior**: 
Cooldown should be show equally for all spells.
**Steps to reproduce**:

MC a creature or use item that does DoSummonPossesed

**Client version**: 
2.4.3
**Commit hash**: 
newest mangos-tbc
**Database version**: 
newest TBC-DB

**Comment by AnonXS** [comment]
Linked to https://github.com/cmangos/issues/issues/1688, but rather serverside core implementation for cooldowns being displayed correctly. Maybe is even resolved with correct cooldown being applied.

**Comment by killerwife** [comment]
This one was actually reported due to quest Smallest Creatures. That quest even has a bug on retail. Hence, declaring this one non-issue. The other linked ones are still valid tho.
