### ISSUE TITLE
Wrong Cooldown Data for Creature Spells

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#874]
**Current behavior**: 
Creatures that are supposed to have spells in creature_template_spell have wrong cooldown data, hence the spells can be abused when a player Mind Controls a creature.
**Expected behavior**: 
Such spell is supposed to have a normal cooldown to prevent abuse.
**Steps to reproduce**:
1. Mind Control a creature with creature_template_spell entry
2. Notice no cooldown on most spells

**Client version**: 
TBC - 2,4,3 tho most likely in all versions.

**Database version**: 
TBC-DB tho most likely in all versions.

Example of creatures: 21057,20609,20614,20601 and their spells 35924,11975,35922,36508 respectively

**Comment by AnonXS** [comment]
Linked to https://github.com/cmangos/issues/issues/1688

**Comment by al3xc1985** [comment]
@killerwife i believe you fixes it on the new mind control/enslave patch that is coming. If I remember corect tgia is fixed, just need to be ported.

Than we can close this one and rhe other one linked by anonxs

**Comment by killerwife** [comment]
Data still needs to be added but resolved finally through addition of spell lists, creature_spell_list

**Comment by AnonXS** [comment]
Whats going to happen with https://github.com/cmangos/issues/wiki/creature_template_spells?
