### ISSUE TITLE
[WOTLK] No Action at Move/Turn Commands

### ISSUE THREAD

**Issue by Kandric** [cmangos/issues#875]
**Current behavior**: 
When i take .gameobject turn/move or .npc move the NPC/Gameobject didnt turn/move ingame. The changes will be written to the database.
**Expected behavior**: 
It should turn/move.

**Client version**: 
3.3.5a

**Database version**: 
Project-Silvermoon (r396) for 3.3.5a
**Operating system**: 
Debian jessie

**Comment by Grz3s** [comment]
yes ...
command .move works like that long time already. (for me not a big problem - most of changes I'm doing in code anyway) 
- But can Confirm this small "issue" - if i can call it like that ;)

**Comment by killerwife** [comment]
Non issue, dbscripts work.
