### ISSUE TITLE
[WOTLK] Error at compile with PCH on Debian

### ISSUE THREAD

**Issue by Kandric** [cmangos/issues#876]
**Current behavior**: 
I get an error if i compile the core with -DPCH=1. Without PCH i have no problems.

**Steps to reproduce**:
1. cmake .. -DCMAKE_INSTALL_PREFIX=/xxxx -DPCH=1
2. make

**Client version**: 
3.3.5a
**Error Message**: 
src/game/CMakeFiles/pch_Generate_game.dir/build.make:53: recipe for target 'src/game/pchdef.h.gch/game_Release.h++' failed
make[2]: **\* [src/game/pchdef.h.gch/game_Release.h++] Error 1
CMakeFiles/Makefile2:760: recipe for target 'src/game/CMakeFiles/pch_Generate_game.dir/all' failed
make[1]: **\* [src/game/CMakeFiles/pch_Generate_game.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: **\* [all] Error 2

**Operating system**: 

Debian Jessie

**Comment by namreeb** [comment]
I believe @cyberium said he would try and address this.

**Comment by cyberium** [comment]
Yes i will, the best however is to wait until ACE is removed.

**Comment by adellaci** [comment]
I believe this is fixed, at least it is working once again on my Ubuntu 14.04 LTS x64 system

**Comment by cyberium** [comment]
fixed
