### ISSUE TITLE
[WOTLK] RA omitting last character of command

### ISSUE THREAD

**Issue by antiroot** [cmangos/issues#877]
**Current behavior**: 
When issuing commands via RA using telnet the last character of any line of text is omitted, including entering the username and password. However adding a space or another character following the desired input will then simply ignore the extra character and the input will be accepted.
**Expected behavior**: 

**Steps to reproduce**:

1. Enable RA
2. telnet to RA socket
3. enter anything that requires the full text (usrname/password/quit)

**Client version**: 
3.3.5a
**Commit hash**: 
a6b0038dffb962c981aa177e306d6242afcecd78

**Operating system**: 
FreeBSD 10.1-RELEASE-p10

It seems that commit f365ffd3cb64f20b6670c70165cc60bd6aff6a69 rewrote parts of RA and the file  src/mangosd/RASocket.cpp on line 91 has "newLine - 1" removing the minus one resolves the issue, but logically the code looks like the minus one should be there since it's to strip the newline character when the user presses enter.

**Comment by emeric254** [comment]
Same behaviour, running on Debian.
The last character send is removed (the one before '\n').
Maybe it's a normal things for Windows system assuming they add an '\r' at this place ...

**Comment by mityada** [comment]
This issue presents in all mangos cores. It is solved by cmangos/mangos-classic#185. It's in mangos-classic, but the code is exactly the same, so it can be easily ported to both mangos-tbc and mangos-wotlk.
