### ISSUE TITLE
Timed quests

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#878]
**Current behavior**: 
Client crash.
**Expected behavior**: 
Quest works normally, and time is counted down.
**Steps to reproduce**:
1.  Start a timed quest. Etc. 
   http://www.wowhead.com/quest=4492/lost
   http://www.wowhead.com/quest=28/trial-of-the-lake

**Database version**: 
TBC-DB
**Operating system**: 
Win and Mac

I will update this issue with some crash logs when i get my hands on them.

**Comment by cyberium** [comment]
Apparently you never replicated 👍

**Comment by Warlockbugs** [comment]
Questhelper addon issue: https://github.com/cmangos/issues/issues/1340
