### ISSUE TITLE
mangos-wotlk build errors

### ISSUE THREAD

**Issue by apo126** [cmangos/issues#879]
Latest commit a2bbf88, built with VS2013. There are 4 errors and 16 warnings.

error	6	error LNK1104: could not open the file“libboost_thread-vc120-mt-1_59.lib”	D:\mangos-wotlk-master\win\VC120\LINK	realmd
error	7	error MSB6006: “link.exe”has quit, the code is 1104。	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	607	5	realmd
error	19	error LNK1104: could not open the file“libboost_system-vc120-mt-1_59.lib”	D:\mangos-wotlk-master\win\VC120\LINK	mangosd
error	20	error LNK1181: cannot open input file“mangosd.lib”	D:\mangos-wotlk-master\win\VC120\LINK	ScriptDev2

**Comment by Konctantin** [comment]
You must register the boost in environtment variables, such as here:
![boost](https://cloud.githubusercontent.com/assets/82728/13897196/7cdd7ace-edb9-11e5-8a6f-47bb2423e5c5.PNG)

**Comment by cyberium** [comment]
As @Konctantin said its only a mather of setting up correcttly your lib folder
Your BOOST_ROOT seem fine however you have to put precompiled boost lib in your "BOOST_ROOT\lib\win32" or "BOOST_ROOT\lib\x64" depending of your architecture.
