### ISSUE TITLE
Movement ACK Messages Are Handled Incorrectly

### ISSUE THREAD

**Issue by tripleslash** [cmangos/issues#880]
Currently if any player around you mounts up YOUR own client will send an Ack message with the foreign players GUID as mover. The reason is that SMSG_FORCE_(SPEED)_CHANGE and other messages are sent to the current set instead of the local mover only. Foreign players should receive SMSG_(SPEED)_CHANGE and not SMSG_FORCE_(SPEED)_CHANGE.

Fix:
SMSG_FORCE_... opcodes should be sent to the person that currently controls this unit i.e. the  `Unit::m_movedPlayer`.

Example:

Stand in a crowded place and watch players around you mount up and dismount, then watch your clients outgoing packet traffic.

Packet log: http://underflow.in/i/yUvI3.png
None of these packets actually belong to me.

Fixing this would result in lots of reduced trash traffic in crowded areas.

I encountered this when I started to implement a proper movement anticheat into TC and have fixed it in a commit, you can cherrypick the relevant parts from here:

https://github.com/tripleslash/TrinityCore/commit/88d662f7b867f804629cbe1dbfb8fd2988de81d0

PS: The code in TC and CMaNGOS is exactly the same so it doesn't matter.

**Comment by cyberium** [comment]
Thank you for pointing, i already faced that issue but did not had time to investigate it more. Your work seem awsome.
I will review it asap.

**Comment by tripleslash** [comment]
Just to point this out. This is NOT meant to be merged, instead just pick the relevant lines where it says SendMessageToSet. I will rework the whole movement stuff entirely and from scratch when I have more time.

**Comment by cyberium** [comment]
Who forget about that? :( I need to come back on that.

**Comment by tripleslash** [comment]
@chaodhib from the guys over at TrinityCore did an excellent job with fixing some of the major issues with movement lately. Theres an open pull request that implements some baseline handling for ACK's (even tho it's not perfect yet). You might wanna look at the related issues that were linked over there.

**Comment by Lillecarl** [comment]
https://github.com/chaodhib/TrinityCore/commit/88d662f7b867f804629cbe1dbfb8fd2988de81d0

**Comment by tripleslash** [comment]
Look at the pull request here instead: https://github.com/TrinityCore/TrinityCore/pull/18771

**Comment by killerwife** [comment]
Resolved by me by reworking it on all 3 branches.
