### ISSUE TITLE
Core crash on start up during "Loading Loot Tables..."

### ISSUE THREAD

**Issue by xfurry** [cmangos/issues#881]
**Current behavior**:  Core crash on start up, during "Loading Loot Tables..."

**Steps to reproduce**: http://paste2.org/O3Vvp4Oe

**Client version**: 3.3.5a

**Commit hash**: https://github.com/cmangos/mangos-wotlk/commit/fade6cf0057db0ed67e8b8d4623568cad6d48e88

**Database version**: https://github.com/unified-db/Database/commit/fe68ce09f537cc6ab8826b8c605557c401392ee5

**Operating system**: Win 7

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cyberium** [comment]
Not reproducible on VS 2015 32bit debug version and windows10. Could you try to debug it?
