### ISSUE TITLE
Water Ele/Pet Bugs (Explained In Detail)

### ISSUE THREAD

**Issue by wrsx** [cmangos/issues#882]
Firstly pet bar settings don't save for Water Eles. Each time a new one is summoned, all settings on the bar are reverted to default, and the pet bar doesn't actually reflect what the default settings are properly. Waterbolt is set to autocast and Freeze is set to manual cast by default, but the bar shows both of them being set to manual cast when a Water ele is summoned. Not a HUGE deal but still a bug nonetheless. 

Pets cant be set to passive once they enter combat. Not a big deal if you keep your pet on passive and use /petattack and /petfollow to control your pet (this is what hunters can do), but this doesn't exactly work that well for Mages or Warlocks. 

The reason is /petfollow doesn't cancel the pet cast, and if you do it mid-cast your pet will finish it's cast then stop attacking, but the game still thinks your pet is 'attacking' even though it's not, so you need to /petfollow a second time when it's not casting before you can instruct it to start attacking again.

What should happen: 
Pet bar settings should save for Water Elementals, and the pet bar should correctly display the default settings (Waterbolt autocast, Freeze manual cast).

Pets should be able to be set to passive during combat

Setting a pet to passive/ordering it to follow while it's casting should immediately cancel the cast and stop it attacking entirely.

I think that summarizes ALL pet bugs and if they're fixed, pets should work perfectly =) At least I haven't encountered anything that doesn't stem from the above issues.

**Comment by jimmybrancaccio** [comment]
@wrsx Can you confirm if this is still an issue in the latest builds?

**Comment by killerwife** [comment]
This one needs a manual recheck.

**Comment by wrsx** [comment]
@jimmybrancaccio I dont play anymore so unfortunately cant test this, sorry!

**Comment by jimmybrancaccio** [comment]
No problem @wrsx We'll get it tested on our end.

**Comment by Phatcat** [comment]
>What should happen:
>Pet bar settings should save for Water Elementals, and the pet bar should correctly display the >default settings (Waterbolt autocast, Freeze manual cast).

The bar settings are getting correctly saved and reapplied on resummon. It however doesn't display the default settings of waterbolt being autocast and on by default, freeze is however correctly displayed as manual from default. 

>Pets should be able to be set to passive during combat
>
>Setting a pet to passive/ordering it to follow while it's casting should immediately cancel the cast >and stop it attacking entirely.

This is what currently happens on master, pets are able to be set passive and will stop spellcasting and attacking and return to their owner.

**Comment by Phatcat** [comment]
This can be closed now
