### ISSUE TITLE
[TBC] All NPC Damage incorrect

### ISSUE THREAD

**Issue by cooler-SAI** [cmangos/issues#885]
Using Last TBCDB  https://github.com/TBC-DB/Database/commit/9ba445f8a7e531ab32c9345b40c387ff91e45343

Using Last Core https://github.com/cmangos/mangos-tbc/commit/30cc0eafaebc687a6f44a0e729e1293ead97f3ff

Problem:
All NPC's Make1-3 Hit, it doesn't metter what  are they Level have
in mangosd.conf all Rates set to defaults, DB have correct values. I think that it's a core problem.
When I set in conf Rate to 5 - nothing happens

Build Win 8.1 X64

**Comment by killerwife** [comment]
Afaik Wotlk combat code was not ported to TBC yet.

**Comment by Muehe** [comment]
http://cmangos.net/thread-7347.html

**Comment by killerwife** [comment]
Hmmm, then its the result of TBC-DB being only actively developed by Vengeance of Azeroth. Should anyone want to help us, lemme know, we lack the manpower to export a LOT of the data.

**Comment by cooler-SAI** [comment]
@killerwife I can Report Bugs, tell me where

**Comment by killerwife** [comment]
Come to IRC and we can talk about stuff. I'm there all the time.

**Comment by cala** [comment]
This issue is not related to core development so I'm closing it. 
Please, refer to your DB provider because it clearly seems that the DB for TBC currently supported by CMaNGOS is no longer in sync with the core it is supposed to work with.
