### ISSUE TITLE
[WOTLK/?] Debian 8.4 (32bit) mangos internal tbb compilation not possible (broken include paths?)

### ISSUE THREAD

**Issue by sapier** [cmangos/issues#889]
**Current behavior**: 
internal tbb (2.2) compile failes due to incorrect include folders

**Expected behavior**: 
compilation without error

**Steps to reproduce**:
1. clone cmangos (e.g. at 2016 04 07)
2. create separate build folder
3. cmake  -DCMAKE_INSTALL_PREFIX=/opt/mangos_wotlk_12939_20160407 -DTBB_USE_EXTERNAL=0  ../mangos-wotlk_12939_20160407

**Client version**: 
-- not relevant

**Commit hash**: 
cd54a86ff9595ed828fb999f4615a3b441f9bcd7 ( but it's in there for more then half a year now!)

**Database version**: 
--not relevant

**Operating system**: 
Debian 8.4 (32 bit)

https://gist.github.com/sapier/0da9d5248a6327522d52fd702202d721

All the missing includes do exist but it doesn't look like the include paths are set correct in tbb. Debian would provide libtbb itself (4.2) but although mangos does compile flawless with it it doesn't actually "run" afterwards. Mangos is completely unusable compiled against debian 8.4 tbb4.2.

**Comment by sapier** [comment]
tried on debian 8.4 64bit there it does work (fixed caption too)

**Comment by Fabi** [comment]
Not longer related. TBB removed since
https://github.com/cmangos/mangos-wotlk/commit/5b0f690dcf91a61a967acf772578619ccff9b749
