### ISSUE TITLE
[Classic] Mage Frost Nova fails to root (intermittently)

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#890]
**Current behavior**: 
Mage's Frost Nova intermittently roots anything within Frost Nova range. Note: mob is hit and takes frost nova ONLY damage, just not rooted. Rank does not seem to make a difference, fails for ranks 1-4. 

**Expected behavior**: 
 Mage casting Frost Nova should do some damage and root mob for up to 8 seconds

**Steps to reproduce**:
 get close to mob and cast Frost Nova on it.

1. 
2. 
3. 

**Client version**: 
1.12

**Commit hash**:
commit f448ad09f2bd7a4ca4afaa5b13b50760a3ad4d60

**Database version**: 
'Classic DB version 1.6.5 \'The Wailing Pet, The MidSummer Joy and all that sort of things\'. For core Classic z2683.', 'ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)', NULL

**Operating system**: 
Windows 8.1

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by lduguid** [comment]
After some more testing, I will modify from frost nova  _mostly_ does not root to _intermittently_, sometimes it will work and sometimes it will fail many times in a row. Mob level and resistance does not seem to influence it, it appears so far to be random BUT it definitely fails much more than you would expect.

**Comment by Schaka** [comment]
Probably the damage breaking the aura itself. Try it with rank 1 frostnova on high level NPCs and see if the effect changes.

**Comment by sidsukana** [comment]
Procs occur immediately after the imposition of effects. The first effect has damage, spell procs at myself and drop the second effect

**Comment by Phatcat** [comment]
Every item which deals damage with a side-effect of either rooting or stunning is affected by this as well. This means just about half the goblin engineering arsenal. This makes me sad. I like engineering. but it does explain why so many of the things that stunned would not stun during my initial engineering testing.
