### ISSUE TITLE
[CLASSIC] Fishing is Broken in Some Areas

### ISSUE THREAD

**Issue by RichardGe** [cmangos/issues#894]
**Current behavior**: 

in some areas, it's impossible to catch something.

I have done the investigation :
For example, if you are in The Savage Coast (Zone 33 - Area 301), 
this will call the loot  entry :  fishing_loot_template , entry 301
in this entry, you have only 1 fish:  item=16969  (for the Nat Paggle Quest : 6607 - "Nat Pagle, Angler Extreme")
If you don't have this quest, you will never have a single fish in this area, no matter how many time you try to fish.

**Expected behavior**: 

In the Loot::Loot function , in the LOOT_FISHING case there are 2 tries of FillLoot.
the 1st one is for the subzone, and the second one is for the zone.
In the current version, we only execute the second try of FillLoot if the first try FillLoot of the subzone has no data.
imo, if we want to solve this issue, we should also do the 2nd try of FillLoot if the first try of FillLoot has returned an empty loot.

**Comment by TarasHots** [comment]
Sources are telling me that 'Savage Coast Blue Sailfin' fish is the only fishing loot there...

From the other side, adding more logic won't add more fish. That logic is completely legit, I guess. So if we even want to change fishing loot there we need to fill it into DB

**Comment by RichardGe** [comment]
ok.. Maybe your sources are right. It just seems to me that it's not normal not being able to catch a single fish along a large beach. But honestly, I don't remember exactly how was finishing during Vanilla, and if those no-fish zone existed.

**Comment by TarasHots** [comment]
You mentioned that there are several areas with this kind of problem. Could you list them?

**Comment by cala** [comment]
> But honestly, I don't remember exactly how was finishing during Vanilla, and if those no-fish zone existed.

There was some places/zones in Vanilla where there were nothing fishable. Usually, trying to fish in those places would display an error. @RichardGe could you list others zones you found without fish loot, please?

> Let's check another place, like Blackwolf River, and you can see nice suff here. I guess this source is pretty reliable to check

If you are speaking of dbvanilla as a reliable source, I'm sorry but I disagree. Chances are very high that this DB is based on a early versions of the DB for Classic supported by CMaNGOS. That DB still has some bugs we fixed long ago (and the other way is probably also true).

**Comment by RichardGe** [comment]
The exhaustive list is: all entries of fishing_loot_template that only have negative ChanceOrQuestChance:

300   -  Misty Reed Strand
301   -  The Savage Coast
598   -  Sar'theris Strand
1578  -  Southern Savage Coast
2521  -  Verdantis River

If you don't have the quest corresponding to the fish of this area, you won't be able to catch a single fish here. I don't think this is normal, because some of these area correspond to great lakes or coasts.
And we have no message saying that there is nothing fishable.

**Comment by w5860363** [comment]
`DELETE FROM `fishing_loot_template`  WHERE entry=301;
NSERT INTO `fishing_loot_template` VALUES ('301', '4603', '19.1', '0', '1', '1', '0', '0', '0');
INSERT INTO `fishing_loot_template` VALUES ('301', '6308', '0.2', '0', '1', '1', '0', '0', '0');
INSERT INTO `fishing_loot_template` VALUES ('301', '6355', '0.4', '0', '1', '1', '0', '0', '0');
INSERT INTO `fishing_loot_template` VALUES ('301', '6357', '0.5', '0', '1', '1', '0', '0', '0');
INSERT INTO `fishing_loot_template` VALUES ('301', '6359', '11.7', '0', '1', '1', '0', '0', '0');
INSERT INTO `fishing_loot_template` VALUES ('301', '6362', '54.4', '0', '1', '1', '0', '0', '0');
INSERT INTO `fishing_loot_template` VALUES ('301', '8365', '0.2', '0', '1', '1', '0', '0', '0');
INSERT INTO `fishing_loot_template` VALUES ('301', '16969', '-100', '0', '1', '1', '0', '0', '0');`
