### ISSUE TITLE
CLASSIC Dwarf Racial not removing disease.

### ISSUE THREAD

**Issue by Draparn** [cmangos/issues#896]
**Current behavior**: 
The dwarven racial "Stoneform" does not remove currently applied Disease effects.
**Expected behavior**: 
Stoneform should remove and prevent further applications of Bleed, Poison and Disease effects during it's duration.
**Steps to reproduce**:
1. Get a disease effect on you (tip: Old Murk-Eye has one which is the cause this report. It might just be this particular spell)
2. Use Stoneform ability

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 

**Operating system**: 

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Phatcat** [comment]
This should be fixed by https://github.com/cmangos/mangos-classic/commit/0181ff1332a78e707d65d5992f1d79ff7af5bd48
