### ISSUE TITLE
[Classic] Warrior quest: The Affray (id: 1719)

### ISSUE THREAD

**Issue by Primus11** [cmangos/issues#897]
Warrior quest: The Affray (id: 1719 = warrior quest for berserk stance)

I took the quest and went into the "little arena / in the middel of the crowd". 
The quest shows properly:  "Stepping into the arena: complete".

But after that nothing happens. I waited for 2 minutes at that place but "Big Willi" don´t appear.
(quest goal is to slain "Big Willi" -> http://wowwiki.wikia.com/wiki/Quest:The_Affray)

Client version: 1.21.1

Database version: 16/4/16 classicdb (https://github.com/classicdb/database)
16/4/16 Cmangos + Scripdev2 + Acid

Operating system: Windows 10

**Comment by TarasHots** [comment]
Can't confirm tho. Quest is working fine on either Horde or Alliance side. After stepping on to the grate, there are several challengers there and after them Big Willi appears, berserker stance is obtainable.

DB: 11ac74e5100bc3a3fa79909e75033568397333fb
ACID: e8a070abdc9939770d2ae7cd87fe65f92ae55b7a
(both are up to date)

[Here are the screenshots](https://imgur.com/a/AJq5t)

I've also tried to not stay on the grate and it worked fine as well.

**Comment by Primus11** [comment]
Thanks for your commet. Looks like the quest is working. Maybe i should mention that i did the quest on lvl 60...i will try the quest again and update my post

**Comment by Primus11** [comment]
The problem was due to a wrong server complimation (SD2 databse was not working) . 
So this issue is closed.
