### ISSUE TITLE
[Classic] Casters do not move to aggroed target position when moving out of LOS

### ISSUE THREAD

**Issue by lduguid** [cmangos/issues#898]
**Current behavior**: 
When a caster has targeted a player and is casting an  offensive spells etc. If the player moves out of LOS, the npc will just stand their mid cast and not move forward. Sometimes they will move a little bit forward and will resume to start a cast but not complete it until the player moves back into LOS. Moving back out of LOS the npc will once again just stand their mid cast but not move forward to the player.

**Expected behavior**: 
 Caster npc will move to player position when player has aggroed them and moves to out of LOS.

**Steps to reproduce**:
Aggro and caster, let them cast at you and then move out of LOS.

1. 
2. 
3. 

Client version: 
1.12.x

Commit hash:
commit f448ad09f2bd7a4ca4afaa5b13b50760a3ad4d60

Database version: 
'Classic DB version 1.6.5 \'The Wailing Pet, The MidSummer Joy and all that sort of things\'. For core Classic z2683.', 'ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)', NULL

Operating system: 
Windows 8.1

**Comment by lduguid** [comment]
OK, I dug a little deeper, checking out creature_ai_scripts, i did this;
SELECT * FROM mangos.creature_ai_scripts where action1_type=49 or action2_type=49 or action3_type=49
and got back a result count of 1306 rows. I tested on some of the caster mobs that had this enabled and they do indeed move forward to the player when they move out of LOS.  Nice.

However, a question, is it now required to find all the npc casters where they do not move to the player on moving out of LOS and make sure that they have an EventAI in creature_temlpate and in turn that one of their action types is now set to 49 (ACTION_T_DYNAMIC_MOVEMENT) ?

**Comment by cala** [comment]
ACID team is in the process of moving the old behaviour to the new one by using the `ACTION_T_DYNAMIC_MOVEMENT` . This will take some time though. 
As this is not a real issue, I'm closing this here. Thank you.
