### ISSUE TITLE
[Classic] priest quest: Garments of Darkness (id: 5650)

### ISSUE THREAD

**Issue by Primus11** [cmangos/issues#899]
I took the quest in Brill and went to "Deathguard Kel". I applied "Lesser Heal (Rank 2)" and "Power Word: Fortitude" on him, but nothing happens. (He kneels at his place)

Client version: 1.21.1

Database version: 16/4/16 classicdb (https://github.com/classicdb/database)
16/4/16 Cmangos + Scripdev2 + Acid

Operating system: Windows 10

**Comment by cala** [comment]
I tested the quest this morning and it was working as intended. Given the other issue you opened (https://github.com/cmangos/issues/issues/897), I wonder if SD2 is working on your config. Do you have a SD2 error log running and what is in, please?

**Comment by Primus11** [comment]
Thanks for your note. I´ve checked the SD2 error log and it tells me that a lot of scripts are not assigned in the database (probably all SD2 scripts). So the errors are due to my wrong database installation.
Sorry for the incorrect issues and your efforts. I compiled my first server a moth ago, so i´m  total beginner in that topic.

**Comment by cala** [comment]
I'm glad you fixed it. :+1:
