### ISSUE TITLE
Prince malchezaar

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#901]
@xfurry 

https://gist.github.com/killerwife/9d1911840a37325e472e
 and
UPDATE creature_template SET ExtraFlags=0 WHERE entry=17644; -- make creature visible
UPDATE creature_template SET ExtraFlags=4098 WHERE entry=17645; -- make creature loaded at all times

https://drive.google.com/open?id=0B667IIG121UQWmo3VHlsUE4wWmM

In case you need some help lemme know. The files are ordered in order of application.

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/blob/75a9226c6301f7a0ee6c8cfe0eadadd4b657bc48/Updates/035_ChangeVisibility.sql

https://github.com/cmangos/tbc-db/blob/75a9226c6301f7a0ee6c8cfe0eadadd4b657bc48/Updates/034_AddActiveFlags.sql

Can be closed?

**Comment by jimmybrancaccio** [comment]
@killerwife @AnonXS Safe to close this one out?

**Comment by killerwife** [comment]
I believe can be closed. I did some changes in June.
