### ISSUE TITLE
MMap Build Failure - DetourNavMesh.h: No such file or directory

### ISSUE THREAD

**Issue by Enverex** [cmangos/issues#902]
When trying to build "mmap" it fails with the following:

```
[ 98%] Building CXX object CMakeFiles/MoveMapGen.dir/src/TerrainBuilder.cpp.o
In file included from /opt/mangos-wow/mangos-wotlk/contrib/mmap/src/TerrainBuilder.h:24:0,
                 from /opt/mangos-wow/mangos-wotlk/contrib/mmap/src/IntermediateValues.h:23,
                 from /opt/mangos-wow/mangos-wotlk/contrib/mmap/src/IntermediateValues.cpp:19:
/opt/mangos-wow/mangos-wotlk/contrib/mmap/../../src/shared/../../src/game/MoveMapSharedDefines.h:23:62: fatal error: ../recastnavigation/Detour/Include/DetourNavMesh.h: No such file or directory
compilation terminated.
```

Which is odd as this most definitely exists. I've built Detour and the file exists (in dep/recastnavigation/Detour/Include/DetourNavMesh.h).

I've even tried adding the full, absolute path to the folder to the CMakeLists.txt file (/opt/mangos-wow/mangos-wotlk/dep/recastnavigation/Detour/Include) and rebuilding, but no improvement.

Am I missing something obvious here or is the build currently broken?

**Comment by Enverex** [comment]
Ok, I managed to get past that by symlinking the dep/recastnavigation folder into the src folder, which is odd but ok. Now it gets further (up to 99% from a clean build) but it's now failing with...

```
[ 99%] Building CXX object CMakeFiles/MoveMapGen.dir/src/VMapExtensions.cpp.o
/opt/mangos-wow/mangos-wotlk/contrib/mmap/src/MapBuilder.cpp: In member function ‘void MMAP::MapBuilder::getGridBounds(uint32, uint32&, uint32&, uint32&, uint32&)’:
/opt/mangos-wow/mangos-wotlk/contrib/mmap/src/MapBuilder.cpp:156:16: error: ‘INT_MAX’ was not declared in this scope
         maxX = INT_MAX;
                ^
/opt/mangos-wow/mangos-wotlk/contrib/mmap/src/MapBuilder.cpp:158:16: error: ‘INT_MIN’ was not declared in this scope
         minX = INT_MIN;
                ^
CMakeFiles/MoveMapGen.dir/build.make:110: recipe for target 'CMakeFiles/MoveMapGen.dir/src/MapBuilder.cpp.o' failed
```

**Comment by Enverex** [comment]
Adding "#include <limits.h>" to the head section of MapBuilder.cpp fixes this error, but guessing that it should already be included here or elsewhere.

**Comment by Muehe** [comment]
@Enverex @namreeb This diff fixed the problem from the initial report, the one you symlinked around.

```diff
diff --git a/src/game/MoveMapSharedDefines.h b/src/game/MoveMapSharedDefines.h
index 0a88e42..74be6c8 100644
--- a/src/game/MoveMapSharedDefines.h
+++ b/src/game/MoveMapSharedDefines.h
@@ -20,7 +20,7 @@
 #define _MOVE_MAP_SHARED_DEFINES_H
  
 #include "Platform/Define.h"
-#include "../recastnavigation/Detour/Include/DetourNavMesh.h"
+#include "../../dep/recastnavigation/Detour/Include/DetourNavMesh.h"
  
 #define MMAP_MAGIC 0x4d4d4150   // 'MMAP'
 #define MMAP_VERSION 4
 
```

Now this is for classic. The include path for wotlk [looks slightly different](https://github.com/cmangos/mangos-wotlk/blob/master/src/game/MoveMapSharedDefines.h) but I guess you need to change it to this as well, because there is no /src/game/DetourNavMesh.h (namreeb changed it to that in https://github.com/cmangos/mangos-wotlk/commit/1cb24973faee7ba168a52ac2134e61e94b16115b).

I assume this was no problem in Windows due to the additional VS include paths in the vcxproj
 files?
