### ISSUE TITLE
mmap_extract.py - Wrong Python Version

### ISSUE THREAD

**Issue by Enverex** [cmangos/issues#903]
The shebang in this file specifies `#!/usr/bin/python` but should really use `#!/usr/bin/python2` as it doesn't work with Python 3. Trying to run the script on a modern distro (e.g. directly or with `python (file)`) will result in it erroring out with a syntax invalid notice.

**Comment by namreeb** [comment]
What distro did you install that comes with python 3 by default?

**Comment by Enverex** [comment]
I'm using Arch Linux.

**Comment by Lillecarl** [comment]
We're using the bash version of this now, closing.
