### ISSUE TITLE
[Classic] Npc: Palemane Poacher (id: 2951)

### ISSUE THREAD

**Issue by Primus11** [cmangos/issues#905]
The Npc Palemane Poacher can be found in Mulgore (and is part of a quest). 
When getting in combat with that NPC, he first makes a bow shot. Than he rans towards the player and stand infront of him instead of doing meele attack.

So i guess that the Npc has no meele values/scripts?

Client version: 1.12.1 (De) 

Sever contains the recent Cmangos files: 23.04.2016 
(Cmangos Classic, Acid, Scriptdev2 and Classic DB)

Operating system:  Windows 10

**Comment by cala** [comment]
Thanks for your report.
This is probably an ACID (creature AI) issue. There was a bug in the TBC scripts for the hunter-like NPCs that I did not *yet* backport to Classic.

**Comment by Primus11** [comment]
Thanks for your note. Since the last updates, the problem is solved - don´t know why =D... so i close this issue.
