### ISSUE TITLE
[Classic] Hunter Auto Shot not repeating fire

### ISSUE THREAD

**Issue by canidae** [cmangos/issues#906]
**Current behavior**: 
Auto Shot fires one arrow/bullet upon activation, but won't continue firing.

**Expected behavior**: 
Auto Shot should continue firing every <attack speed> second until cancelled.

**Steps to reproduce**:
1. Create Hunter (tested with Night Elf and Orc).
2. Attack stationary target with Auto Shot.

**Client version**: 
1.12.1

**Commit hash**: 
mangos: commit 8512e330a423f2b71a0d33071da1f593ab9c1d21

**Database version**: 
classicdb: commit 7d95dd9808b163817a8eaa02edcda7bfba1aba77

**Operating system**: 
Debian GNU/Linux 8 (jessie)

**Comment by killerwife** [comment]
I made PR for fix, should be commited in the next few days.

**Comment by canidae** [comment]
Quick reply, I assume it's this PR: https://github.com/cmangos/mangos-classic/pull/118

**Comment by killerwife** [comment]
Yup

**Comment by canidae** [comment]
Great, good job. Looking forward to test it (will wait until PR is accepted), will close this issue then (unless someone beats me to it).

**Comment by xfurry** [comment]
@killerwife Please note that there are some channeled spells that need to be interrupted.
We already implemented some functionality for this. so we need to make sure that, it still works.Here are the commits
https://github.com/cmangos/mangos-wotlk/commit/5330f918b26c5e1a54eb56a3f686b66bb7d51c7a
https://github.com/cmangos/mangos-wotlk/commit/02796394c1c5d871cc5be1b67b0b415cb78c7ed6

**Comment by killerwife** [comment]
the fix doesnt affect channeled spells at all, once the pr is merged

**Comment by canidae** [comment]
I applied the patch from @killerwife, it fixes the issue with Auto Shot. I did not test whether it affects channeled spells.

**Comment by namreeb** [comment]
The fix from @killerwife has been merged, although I am still concerned that there is a larger issue here.

**Comment by canidae** [comment]
Great. Closing this issue as it's been resolved.
