### ISSUE TITLE
Files missing (boost)

### ISSUE THREAD

**Issue by ilikesomething** [cmangos/issues#907]
**Current behavior**: 
Since i pulled your last changes today on /mangos-wotlk, when compiling i get 3 errors  (i didn't pulled changes for a month)

> fatal error LNK1104:
> Can't open libboost_thread-vc140-mt-1_60.lib
> Can't open libboost_system-vc140-mt-1_60.lib
> Can't open mangosd.lib
> 

**Expected behavior**: 

it should compile without theses errors. I have an older version (about one month ago) where it's still working today.
i have /boost (latest stable build)  under the /shared folder

**Steps to reproduce**:

1. Pull the current master
2. Compile

**Client version**: not revelant

**Commit hash**: not revelant

**Database version**: not revelant

**Operating system**: Windows 7, compiling in win32 release with visual 2015

Thanks for your help

**Comment by keyshuwen** [comment]
I got the same question:
error LNK1104: Can't open libboost_thread-vc120-mt-1_55.lib
error LNK1104: Can't open libboost_system-vc120-mt-1_55.lib
error LNK1181: Can't open mangosd.lib

:(

**Comment by Phatcat** [comment]
Could you guys possibly try doing (re-doing if you already did) the steps of 
http://cmangos.net/thread-7365.html?highlight=boost ?

**Comment by keyshuwen** [comment]
Thank you, you have solved the problem.
