### ISSUE TITLE
[WotLK] EventAI on spawn *interrupts* Waypoint System 

### ISSUE THREAD

**Issue by Grz3s** [cmangos/issues#908]
Hi
im always checking everything with newest ad fresh compile of cmangos without any changes.

**Current behavior**: 
Take any creature with waypoints and EventAI casting anything on spawn example:
- mages casts frost/fire etc armor on themselfs
- warriors casts "battle/defence etc stance on themselfs"

Creature with waypoints after spawn casts spell on himself and then stops ..and wont continue path for long time. (sometimes will get to 1st wp point -- Probably all depends what goes first ... spell or command go to 1st wp)
It looks simmilar to, when player talks to npc with waypoints ... and npc will stop for few mins ... and then continue wps..

Also i noticed that this problem doesnt happen with randommovement.

**Expected behavior**:
Creature should continue his waypoints without any stop.

**Steps to reproduce**:
will give 2 examples:
1st. Warrrior with battle stance:

1. use this code:
```code
-- test with "battle stance"
DELETE FROM creature WHERE guid=151045;
INSERT INTO creature VALUES (151045,2168,1,1,1,0,38,6950.94,-575.823,43.3669,5.51002,180,0,0,386,0,0,2);
DELETE FROM creature_movement WHERE id = 151045;
INSERT INTO creature_movement (id, point, position_x, position_y, position_z, waittime, script_id, orientation, model1, model2) VALUES
(151045,1,6950.43,-588.236,43.7438, 0, 0,4.91681, 0, 0),
(151045,2,6963.34,-571.427,43.7242, 0, 0,3.48739, 0, 0),
(151045,3,6965.83,-586.554,42.691, 0, 0,2.41925, 0, 0);
-- Blackwood Warrior
Delete from `creature_ai_scripts` where `creature_id`= 2168;
Insert into `creature_ai_scripts` values       
('216801','2168','11','0','100','1','0','0','0','0','11','7165','0','0','0','0','0','0','0','0','0','0','Blackwood Warrior - Cast Battle Stance on Spawn'), 
('216802','2168','9','0','100','1','0','8','16000','21000','11','8078','0','1','0','0','0','0','0','0','0','0','Blackwood Warrior - Cast Thunderclap');
UPDATE creature_template SET AIName = 'EventAI' WHERE `entry` = '2168';
```

Second example:
-- Mage with Frost armor
-- already exist on map so we just need to teleport there...
```code
.go creature 63486
.kill   -- use command on him
.respawn
```
and see what happens

**Client version**: 
[3.3.5a] it may happen on other ones ... no idea... need TBC and Classic ppl to confirm

**Commit hash**: 
no idea - when this problem start to happen

**Database version**: 
newest UDB.

**Operating system**: 
Win7 64bit

Thank to anyone who will look on this issue.

**Comment by Grz3s** [comment]
small update to this:
problem existed before 19th of march. 2016.
I added this commit:
https://github.com/unified-db/Database/commit/c1ad2d0982e5ab09c683e8610226cb1108a448fe
and I remember i saw this issue already... but i had no idea .. it will be that serious.

**Comment by Laizerox** [comment]
That is a good point honestly, didn't think of it when implementing.

I will check it out this week and probably make a patch for you to test!

**Comment by cala** [comment]
I can confirm this. Many patrols in Scholomance/Stratholme cast a spell on themselves at spawn and they stay idle then instead of moving.
Note that after some long time, they start following the waypoints. I did not find yet what make this.

**Comment by Grz3s** [comment]
@Laizerox any update for this?

**Comment by xfurry** [comment]
Well, the issue is complicated.
```JustRespawned();``` is called when the creature is created in eventAI and also on creature deathState = DEAD.

On the first case it won't create any problem as the spell is casted independent of when the movement is initialized.
However on the second case, the spell is casted after the movement generators are activated, hence the creature will stop.

Now, technically it's not 100% correct to only stop movement in combat, but I think this should fix the issue.

```diff
diff --git a/src/game/CreatureAI.cpp b/src/game/CreatureAI.cpp
index 0659773..a42c844 100644
--- a/src/game/CreatureAI.cpp
+++ b/src/game/CreatureAI.cpp
@@ -55,7 +55,7 @@ CanCastResult CreatureAI::CanCastSpell(Unit* pTarget, const SpellEntry* pSpell,
         if (m_creature->GetPower((Powers)pSpell->powerType) < Spell::CalculatePowerCost(pSpell, m_creature))
             return CAST_FAIL_POWER;
 
-        if (!m_creature->IsWithinLOSInMap(pTarget) && m_creature != pTarget)
+        if (!pSpell->HasAttribute(SPELL_ATTR_EX2_IGNORE_LOS) && !m_creature->IsWithinLOSInMap(pTarget) && m_creature != pTarget)
             return CAST_FAIL_NOT_IN_LOS;
     }
 
@@ -113,8 +113,9 @@ CanCastResult CreatureAI::DoCastSpellIfCan(Unit* pTarget, uint32 uiSpell, uint32
             if (uiCastFlags & CAST_INTERRUPT_PREVIOUS && pCaster->IsNonMeleeSpellCasted(false))
                 pCaster->InterruptNonMeleeSpells(false);
 
-            // Creature should always stop before it will cast a new spell
-            pCaster->StopMoving();
+            // Creature should always stop before it will cast a new spell (logic only applies to combat movement)
+            if (pCaster->isInCombat())
+                pCaster->StopMoving();
 
             pCaster->CastSpell(pTarget, pSpell, !!(uiCastFlags & CAST_TRIGGERED), nullptr, nullptr, uiOriginalCasterGUID);
             return CAST_OK;

```

**Comment by Grz3s** [comment]
:+1:  
this fixes problem with waypoints
Also i didnt see any problems with Dynamic movement
Creatures stops while casting normaly... 

Maybe someone else who knows DYNAMIC_MOVEMENT well, could test it also... 
thanks
