### ISSUE TITLE
[TBC] Start-up Error 

### ISSUE THREAD

**Issue by zhy9934** [cmangos/issues#909]
**Current behavior**: 

Some required *.dbc files (2 from 66) not found or not compatible:
Data/dbc/gtOCTRegenHP.dbc (exist, but have 0 fields instead 1) Wrong client version DBC file?
Data/dbc/gtRegenHPPerSpt.dbc (exist, but have 0 fields instead 1) Wrong client version DBC file?

**Expected behavior**: 

no error

**Steps to reproduce**:

I extract files from the client according to the wiki, then the dbc files is error

**Client version**: 
2.4.3(8606)
**Commit hash**: 
latest
**Database version**: 
latest
**Operating system**: 
WIN7

**Comment by Saben65** [comment]
I just extracted the dbc files fine. Is this still an issue for you with the latest revision?

**Comment by cyberium** [comment]
Should work now
