### ISSUE TITLE
Instant "Failed attempt" on gathering

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#910]
**Current behavior**: 
When mining an ore while it's profession skill requirement is 'orange', there is chance of failure. This failure happens instantly, not after the mining action is finished.
Probably same applies to other gathering skills like herbalism and skinning.

**Expected behavior**: 
The gathering action should always start and channel until the end (unless interrupted). The 'Failed attempt' message should be only displayed after the gathering is finished.

**Steps to reproduce**:

1. Try mining copper with a mining skill of 1.
2. Eventually you will see 'Failed attempt' messages, without any mining action.

**Client version**: 1.12.1
**Commit hash**: 898f9ad4125f6179fa5003852523751efdc6868b
**Database version**: classicdb 7d95dd9808b163817a8eaa02edcda7bfba1aba77

**Comment by katz1** [comment]
I tried looking into this a bit and I thought I share my findings. It is important to note that Skinning works as it should, while Mining and Herbalism does not (did not test Lockpicking).

I checked the code where the failure is decided, but even though skinning is handled separately from the rest (SPELL_EFFECT_SKINNING) I did not find any relevant differences. In Spell::prepare Spell::CheckCast returns SPELL_FAILED_TRY_AGAIN and a similar cast result is sent in every case. I checked the spells themselves as well, but the differences in InterruptFlags and Attributes doesn't seem to be relevant.

**Comment by killerwife** [comment]
Thats the thing, the spell::prepare should not check this at all, this should be checked during spell::cast where a different parameter is used for checkcast, the problem with that I think is that mining/herbalism are channeled? casts and channels are not exactly pitch perfect in cmangos (procs being handled in wrong places, behaving completely differently alltogether etc)

Try to look at the conditions so that during the first check of checkcast in prepare this check is skipped and its stopped in spell::cast

**Comment by Phatcat** [comment]
Skinning does not work exactly as it should, but it is unrelated to this issue. 
The skinning time should vary depending on your profession skill in vanilla:
> The casting time for skinning a corpse increases with your level of training. Apprentice skinners only take 1 second to skin a rabbit, while Artisans take 3 seconds to skin that same rabbit.

> "Proficiency 	Level   Skill 	  Cast
> Apprentice 	5 	    - 75 	  1 sec
> Journeyman 	10 	50 - 150 	  2 sec
> Expert   	20 	125 - 225   2.5 sec
> Artisan   	35 	200 - 300   3 sec"

**Comment by killerwife** [comment]
@Phatcat is this 1.12.1 tho?

**Comment by Phatcat** [comment]
@killerwife 
Forgot to post link http://wowwiki.wikia.com/wiki/Skinning?oldid=338768
cached november 2006

**Comment by killerwife** [comment]
Well the cast time should be a relatively easy fix for a custom override in cast time calculation. Get some spellid links for skinning/herbalism/mining so the information in this thread is complete.

**Comment by devmaximus** [comment]
should be similar to pet tame

**Comment by devmaximus** [comment]
sorry wrong button ^^

**Comment by katz1** [comment]
@killerwife 
> Try to look at the conditions so that during the first check of checkcast in prepare this check is skipped and its stopped in spell::cast

Thanks, this appears to be working. I wonder if it would be a bit better to remove this check completely from Spell::CheckCast and place it somewhere directly in Spell::cast instead?
I will test this for a bit more before making a pull request.

**Comment by cala** [comment]
Closed by: https://github.com/cmangos/mangos-classic/commit/923ded41c03cb98182f670221a6b87748acad482
