### ISSUE TITLE
[Classic] mangosd loading crash

### ISSUE THREAD

**Issue by cooler-SAI** [cmangos/issues#914]
Server crash on VS 2013 x64 compile, when mangosd loading, on Loot Loading. The same problem here
http://cmangos.net/thread-7427.html

Client 1.12.1
Server version : https://github.com/cmangos/mangos-classic/commit/6f501dedc751b6acc7a272823f4f70d2fec1b7c9

**Comment by cyberium** [comment]
Could you please try last revision?
If crash still occur could you please upload a full crashlog (from a debug core)

Thank you

**Comment by keyshuwen** [comment]
@cyberium 

on Loot Loading.crash  .

Revision: * * *
Date 4:5:2016. Time 21:33 
//=====================================================
*** Hardware ***
Processor: Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz
Number Of Processors: 8
Physical Memory: 8315328 KB (Available: 4481044 KB)
Commit Charge Limit: 8839616 KB

*** Operation System ***
Windows 8 (Version 6.2, Build 9200)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FFC8A8D9250 01:0000000000048250 C:\WINDOWS\SYSTEM32\MSVCR120.dll

Registers:
RAX:000000007FFFFFFE
RBX:000000000000112F
RCX:000000000000112F
RDX:0000000000000007
RSI:0000000000000000
RDI:0000000000000073
R8: 00007FFC8A890000
R9: 0000000000000000
R10:0000000000000200
R11:00000000FFFFFFFF
R12:000000000014F630
R13:000000000000003C
R14:0000000140591813
R15:0000000000000001
CS:RIP:0033:00007FFC8A8D9250
SS:RSP:002B:00000000001371B0  RBP:001372B0
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010202

Call stack:
Address   Frame     Function      SourceFile
00007FFC8A8D9250  00000000001374B0  _mbctombb_l+25B0
00007FFC8A8C37E5  0000000000137510  _vsnprintf_l+91
00007FFC8A8C374D  0000000000137550  _vsnprintf+11
000000014008B35A  000000000014F5A0  vutf8printf+3A  d:\mangos\cmangos\core\src\shared\util.cpp line 454
000000014008586E  000000000014F600  Log::outString+8E  d:\mangos\cmangos\core\src\shared\log.cpp line 388
00000001402FB357  000000000014F720  LootStore::LoadLootTable+3E7  d:\mangos\cmangos\core\src\game\lootmgr.cpp line 173
00000001402FAF1A  000000000014F770  LootStore::LoadAndCollectLootIds+1A  d:\mangos\cmangos\core\src\game\lootmgr.cpp line 216
00000001402FB413  000000000014F810  LoadLootTemplates_Creature+53  d:\mangos\cmangos\core\src\game\lootmgr.cpp line 2374
00000001400BB0A9  000000000014F840  LoadLootTables+9  d:\mangos\cmangos\core\src\game\lootmgr.h line 364
00000001400BD6A1  000000000014F960  World::SetInitialWorldSettings+B81  d:\mangos\cmangos\core\src\game\world.cpp line 1087
00000001400776EA  000000000014FD00  Master::Run+16A  d:\mangos\cmangos\core\src\mangosd\master.cpp line 134
0000000140070BF6  000000000014FF20  main+BB6  d:\mangos\cmangos\core\src\mangosd\main.cpp line 201
0000000140082477  000000000014FF50  __tmainCRTStartup+10F  f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c line 626
00007FFCA2958102  000000000014FF80  BaseThreadInitThunk+22
00007FFCA370C5B4  000000000014FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFCA3756D44  00000000001352F0  NtGetContextThread+14
00007FFCA0199F0A  0000000000135320  GetThreadContext+A
00000001400818BE  0000000000135850  WheatyExceptionReport::printTracesForAllThreads+BE  d:\mangos\cmangos\core\src\shared\wheatyexceptionreport.cpp line 281
00000001400809A1  0000000000135EE0  WheatyExceptionReport::GenerateExceptionReport+321  d:\mangos\cmangos\core\src\shared\wheatyexceptionreport.cpp line 380
000000014008120A  0000000000136180  WheatyExceptionReport::WheatyUnhandledExceptionFilter+14A  d:\mangos\cmangos\core\src\shared\wheatyexceptionreport.cpp line 107
00007FFCA01F7E1E  0000000000136280  UnhandledExceptionFilter+1AE
00007FFCA375D998  00000000001362C0  memset+2098
00007FFCA3745B26  0000000000136330  __C_specific_handler+96
00007FFCA3759AED  0000000000136360  __chkstk+FD
00007FFCA36E4FE9  0000000000136A70  RtlImageNtHeaderEx+4B9
00007FFCA3758BFA  00000000001371A0  KiUserExceptionDispatcher+3A
00007FFC8A8D9250  00000000001374B0  _mbctombb_l+25B0
00007FFC8A8C37E5  0000000000137510  _vsnprintf_l+91
00007FFC8A8C374D  0000000000137550  _vsnprintf+11
000000014008B35A  000000000014F5A0  vutf8printf+3A  d:\mangos\cmangos\core\src\shared\util.cpp line 454
000000014008586E  000000000014F600  Log::outString+8E  d:\mangos\cmangos\core\src\shared\log.cpp line 388
00000001402FB357  000000000014F720  LootStore::LoadLootTable+3E7  d:\mangos\cmangos\core\src\game\lootmgr.cpp line 173
00000001402FAF1A  000000000014F770  LootStore::LoadAndCollectLootIds+1A  d:\mangos\cmangos\core\src\game\lootmgr.cpp line 216
00000001402FB413  000000000014F810  LoadLootTemplates_Creature+53  d:\mangos\cmangos\core\src\game\lootmgr.cpp line 2374
00000001400BB0A9  000000000014F840  LoadLootTables+9  d:\mangos\cmangos\core\src\game\lootmgr.h line 364
00000001400BD6A1  000000000014F960  World::SetInitialWorldSettings+B81  d:\mangos\cmangos\core\src\game\world.cpp line 1087
00000001400776EA  000000000014FD00  Master::Run+16A  d:\mangos\cmangos\core\src\mangosd\master.cpp line 134
0000000140070BF6  000000000014FF20  main+BB6  d:\mangos\cmangos\core\src\mangosd\main.cpp line 201
0000000140082477  000000000014FF50  __tmainCRTStartup+10F  f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c line 626
00007FFCA2958102  000000000014FF80  BaseThreadInitThunk+22
00007FFCA370C5B4  000000000014FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFCA37587E4  000000000070FB40  NtWaitForWorkViaWorkerFactory+14
00007FFCA36DB5E8  000000000070FF50  RtlAcquireSRWLockShared+3E28
00007FFCA2958102  000000000070FF80  BaseThreadInitThunk+22
00007FFCA370C5B4  000000000070FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFCA37587E4  000000000080FB40  NtWaitForWorkViaWorkerFactory+14
00007FFCA36DB5E8  000000000080FF50  RtlAcquireSRWLockShared+3E28
00007FFCA2958102  000000000080FF80  BaseThreadInitThunk+22
00007FFCA370C5B4  000000000080FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFCA37587E4  000000000090FB40  NtWaitForWorkViaWorkerFactory+14
00007FFCA36DB5E8  000000000090FF50  RtlAcquireSRWLockShared+3E28
00007FFCA2958102  000000000090FF80  BaseThreadInitThunk+22
00007FFCA370C5B4  000000000090FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFCA3755154  00000000025EFC80  ZwWaitForSingleObject+14
00007FFCA014AADF  00000000025EFD20  WaitForSingleObjectEx+8F
00007FFC8A89744F  00000000025EFD60  ?EnableTracing@Concurrency@@YAJXZ+3AF
00007FFC8A8AEAAA  00000000025EFDC0  ?wait@Concurrency@@YAXI@Z+96
000000014002495A  00000000025EFE20  std::this_thread::sleep_for<__int64,std::ratio<1,1000> >+AA  e:\microsoft visual studio 12.0\vc\include\thread line 163
00000001400A5D75  00000000025EFE50  MaNGOS::Thread::Sleep+15  d:\mangos\cmangos\core\src\shared\threading.cpp line 137
00000001400A976F  00000000025EFE80  SqlDelayThread::run+3F  d:\mangos\cmangos\core\src\shared\database\sqldelaythread.cpp line 50
00000001400A5E0D  00000000025EFEB0  std::_LaunchPad<std::_Bind<1,void,void (__cdecl*const)(void * __ptr64),void * __ptr64> >::_Go+1D  e:\microsoft visual studio 12.0\vc\include\thr\xthread line 188
00007FFC8A81D24C  00000000025EFEF0  ?_Release@_Pad@std@@QEAAXXZ+6C
00007FFC8A8B4F7F  00000000025EFF20  _beginthreadex+107
00007FFC8A8B5126  00000000025EFF50  _endthreadex+192
00007FFCA2958102  00000000025EFF80  BaseThreadInitThunk+22
00007FFCA370C5B4  00000000025EFFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFCA37587E4  00000000026EFB40  NtWaitForWorkViaWorkerFactory+14
00007FFCA36DB5E8  00000000026EFF50  RtlAcquireSRWLockShared+3E28
00007FFCA2958102  00000000026EFF80  BaseThreadInitThunk+22
00007FFCA370C5B4  00000000026EFFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFCA3755154  00000000027EFC80  ZwWaitForSingleObject+14
00007FFCA014AADF  00000000027EFD20  WaitForSingleObjectEx+8F
00007FFC8A89744F  00000000027EFD60  ?EnableTracing@Concurrency@@YAJXZ+3AF
00007FFC8A8AEAAA  00000000027EFDC0  ?wait@Concurrency@@YAXI@Z+96
000000014002495A  00000000027EFE20  std::this_thread::sleep_for<__int64,std::ratio<1,1000> >+AA  e:\microsoft visual studio 12.0\vc\include\thread line 163
00000001400A5D75  00000000027EFE50  MaNGOS::Thread::Sleep+15  d:\mangos\cmangos\core\src\shared\threading.cpp line 137
00000001400A976F  00000000027EFE80  SqlDelayThread::run+3F  d:\mangos\cmangos\core\src\shared\database\sqldelaythread.cpp line 50
00000001400A5E0D  00000000027EFEB0  std::_LaunchPad<std::_Bind<1,void,void (__cdecl*const)(void * __ptr64),void * __ptr64> >::_Go+1D  e:\microsoft visual studio 12.0\vc\include\thr\xthread line 188
00007FFC8A81D24C  00000000027EFEF0  ?_Release@_Pad@std@@QEAAXXZ+6C
00007FFC8A8B4F7F  00000000027EFF20  _beginthreadex+107
00007FFC8A8B5126  00000000027EFF50  _endthreadex+192
00007FFCA2958102  00000000027EFF80  BaseThreadInitThunk+22
00007FFCA370C5B4  00000000027EFFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFCA3755154  00000000028EFC80  ZwWaitForSingleObject+14
00007FFCA014AADF  00000000028EFD20  WaitForSingleObjectEx+8F
00007FFC8A89744F  00000000028EFD60  ?EnableTracing@Concurrency@@YAJXZ+3AF
00007FFC8A8AEAAA  00000000028EFDC0  ?wait@Concurrency@@YAXI@Z+96
000000014002495A  00000000028EFE20  std::this_thread::sleep_for<__int64,std::ratio<1,1000> >+AA  e:\microsoft visual studio 12.0\vc\include\thread line 163
00000001400A5D75  00000000028EFE50  MaNGOS::Thread::Sleep+15  d:\mangos\cmangos\core\src\shared\threading.cpp line 137
00000001400A976F  00000000028EFE80  SqlDelayThread::run+3F  d:\mangos\cmangos\core\src\shared\database\sqldelaythread.cpp line 50
00000001400A5E0D  00000000028EFEB0  std::_LaunchPad<std::_Bind<1,void,void (__cdecl*const)(void * __ptr64),void * __ptr64> >::_Go+1D  e:\microsoft visual studio 12.0\vc\include\thr\xthread line 188
00007FFC8A81D24C  00000000028EFEF0  ?_Release@_Pad@std@@QEAAXXZ+6C
00007FFC8A8B4F7F  00000000028EFF20  _beginthreadex+107
00007FFC8A8B5126  00000000028EFF50  _endthreadex+192
00007FFCA2958102  00000000028EFF80  BaseThreadInitThunk+22
00007FFCA370C5B4  00000000028EFFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFCA37587E4  000000000488FB40  NtWaitForWorkViaWorkerFactory+14
00007FFCA36DB5E8  000000000488FF50  RtlAcquireSRWLockShared+3E28
00007FFCA2958102  000000000488FF80  BaseThreadInitThunk+22
00007FFCA370C5B4  000000000488FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFCA37587E4  000000000498FB40  NtWaitForWorkViaWorkerFactory+14
00007FFCA36DB5E8  000000000498FF50  RtlAcquireSRWLockShared+3E28
00007FFCA2958102  000000000498FF80  BaseThreadInitThunk+22
00007FFCA370C5B4  000000000498FFD0  RtlUserThreadStart+34

Call stack:
Address   Frame     Function      SourceFile
00007FFCA37587E4  0000000004A8FB40  NtWaitForWorkViaWorkerFactory+14
00007FFCA36DB5E8  0000000004A8FF50  RtlAcquireSRWLockShared+3E28
00007FFCA2958102  0000000004A8FF80  BaseThreadInitThunk+22
00007FFCA370C5B4  0000000004A8FFD0  RtlUserThreadStart+34
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
00007FFC8A8D9250  00000000001374B0  _mbctombb_l+25B0

00007FFC8A8C37E5  0000000000137510  _vsnprintf_l+91

00007FFC8A8C374D  0000000000137550  _vsnprintf+11

000000014008B35A  000000000014F5A0  vutf8printf+3A  d:\mangos\cmangos\core\src\shared\util.cpp line 454
punting on symbol out
punting on symbol str
punting on symbol ap
	Local  wchar_t* 'wtemp_buf'
	Local  char* 'temp_buf'
	Local  unsigned int 'wtemp_len' = 7FF5FFE7BF60

000000014008586E  000000000014F600  Log::outString+8E  d:\mangos\cmangos\core\src\shared\log.cpp line 388
	Local  <user defined> 'this' = 7FF5F9EBB6A0
	Parameter  char* 'str' = FFFFFFFFFFFFFFFE
	Local  char* 'ap' = 38EA6
	Local  std::lock_guard<std::mutex>
		 <user defined>  mutex_type
			 <user defined>  std::_Mutex_base
				 <user defined>  _Mutex_base
				 <user defined>  _Mutex_base
					 <user defined> 
					 <user defined> 
					 <user defined>  this = 7FF5F9EBB6A0
					 int  _Flags = FFFFFFFE
					 <user defined> 
					 <user defined> 
				 <user defined>  ~_Mutex_base
					 <user defined> 
					 <user defined> 
					 <user defined>  this = 0
					 <user defined> 
				 <user defined>  operator=
				 <user defined>  lock
					 <user defined> 
					 <user defined> 
					 <user defined>  this = 7FF5F9EBB6A0
					 <user defined> 
					 <user defined> 
				 <user defined>  try_lock
				 <user defined>  unlock
					 <user defined> 
					 <user defined> 
					 <user defined>  this = 7FF5F9EBB6A0
					 <user defined> 
					 <user defined> 
				 <user defined>  native_handle_type = 14055D738
				 <user defined>  native_handle
				 <user defined>  _Mtx = 14055D738
				 <user defined>  __dflt_ctor_closure
				 <user defined>  __vecDelDtor
			 <user defined>  mutex
			 <user defined>  mutex
				 <user defined> 
				 <user defined> 
				 <user defined>  this = 7FF5F9EBB6A0
				 <user defined> 
				 <user defined> 
			 <user defined>  operator=
			 <user defined>  ~mutex
				 <user defined> 
				 <user defined> 
				 <user defined>  this = 0
				 <user defined> 
			 <user defined>  __vecDelDtor
		 <user defined>  lock_guard<std::mutex>
		 <user defined>  lock_guard<std::mutex>
		 <user defined>  lock_guard<std::mutex>
			 <user defined> 
			 <user defined> 
			 <user defined>  this = 7FF5F9EBB6A0
			 <user defined>  _Mtx = FFFFFFFFFFFFFFFE
			 <user defined> 
			 <user defined> 
		 <user defined>  ~lock_guard<std::mutex>
			 <user defined> 
			 <user defined> 
			 <user defined>  this = 7FF5F9EBB6A0
			 <user defined> 
			 <user defined> 
		 <user defined>  operator=
		 <user defined>  _MyMutex = 14055D738
		 <user defined>  __vecDelDtor

**Comment by cyberium** [comment]
Omg thank i was sure i was fixed that its a backport pending... -> https://github.com/cmangos/mangos-wotlk/commit/fbdf049c1187ddf3297b174571db90a94de1bed2

**Comment by keyshuwen** [comment]
Thank you.

**Comment by cyberium** [comment]
This should be fixed now please confirm.

**Comment by keyshuwen** [comment]
There is no problem now. :+1:

**Comment by cooler-SAI** [comment]
@cyberium ,all good now! Thank you :+1: I close It
