### ISSUE TITLE
MaxPrimaryTradeSkill / CONFIG_UINT32_MAX_PRIMARY_TRADE_SKILL Capped At 10

### ISSUE THREAD

**Issue by Enverex** [cmangos/issues#917]
This value has a hard-limit of 10 which was fine for Vanilla and BC, but WotLK has 11 skills meaning it's insufficient if someone wants to set a "allow all skills" value.

Is there any reason CONFIG_UINT32_MAX_PRIMARY_TRADE_SKILL cannot be set to a max of 11 rather than 10?

If not, then it's a simple case of updating https://github.com/cmangos/mangos-tbc/blob/master/src/game/World.cpp#L542 and the comment lines in mangos.conf.

**Comment by Enverex** [comment]
I rebuilt with CONFIG_UINT32_MAX_PRIMARY_TRADE_SKILL set to an allowed max of 11 and haven't ran into any so far, the game has successfully allowed me to learn 11 skills.

**Comment by jimmybrancaccio** [comment]
Closing this one out as per last comment. Please open a new issue with full details if you're still experiencing any problems. Thanks!
