### ISSUE TITLE
[CLASSIC] Last Stand Spell Causes Un-revivable Death

### ISSUE THREAD

**Issue by ROKB** [cmangos/issues#918]
**Current behavior**: 
Use spell after die cant revive. need to relogin game.
**Expected behavior**: 
cant revive
**Steps to reproduce**:
1. use last stand
2. die
3. cant revive

**Client version**: 
1.12.1
**Commit hash**: 
LAST 
**Database version**: 
LASE V
**Operating system**: 
OS WINDOW SERVER 2012 R2

**Comment by jimmybrancaccio** [comment]
@ROKB Can you confirm if this is still an issue in the latest builds?

**Comment by Phatcat** [comment]
I can't reproduce this, dying with last stand on causes no issues, can revive by releasing and running back to the corpse, speaking with the spirit healer, having another player ress me, all without any issues.
