### ISSUE TITLE
Random weird crashes

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#919]
**Database version**: 
TBC-DB
**Operating system**: 
Linux

1. https://gist.github.com/killerwife/84fcc78a0ab60021b1ccc824fdc4008d
2. https://gist.github.com/killerwife/e1f26b4529ff5e250b05a90df92ab9e5
3. https://gist.github.com/killerwife/3c7b84fcb875ba0cec470af791d67831
4. https://gist.github.com/killerwife/a070b8e82a67482cd2669dc785a7ad61

Please keep in mind this is for the VoA core, even though the code responsible for it is 1:1.

**Comment by killerwife** [comment]
https://gist.github.com/killerwife/0742e6246c20a278e92c6c89f1e157ab
new one
@namreeb

**Comment by Phatcat** [comment]
They all have a thing in common, they all stall at the function; 
> in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by Laizerox** [comment]
That's where they start :)

**Comment by Phatcat** [comment]
That's the bottom of the stack? lol...

**Comment by killerwife** [comment]
Yes :D

**Comment by killerwife** [comment]
Merged TC fix a while ago that solves these issues.
