### ISSUE TITLE
creature_template : Rank

### ISSUE THREAD

**Issue by Zooke** [cmangos/issues#921]
**Current behavior**:  Rank 2 : Rare Elite shows a gold portrait
**Expected behavior**:  Portrait should be silver

**Steps to reproduce**:

1. Any creature with rank set to 2 shows gold portrait
2. 
3. 

**Client version**: 1.12.1

**Commit hash**: latest

**Database version**: latest

**Operating system**: win 7

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by killerwife** [comment]
To my knowledge thats how vanilla worked :) They added the whole silver dragon thing later down the line.

**Comment by cala** [comment]
I agree, full silver dragon was added after Classic. The icon displayed is handled by the client based on the rank set by the server in the OPCode and as far as I know, this part is ok. 
Source: http://wow.gamepedia.com/index.php?title=Rare_mob#History

**Comment by Zooke** [comment]
I apologise, it appears the elite rares were coloured silver to match normal rares in World of Warcraft Client Beta Patch 2.0.3-6244 according to this post from Dec 2006
[http://www.taultunleashed.com/worldofwarcraft-discussions/wow-2-0-3-patch-notes-t42036.html](url)
Note to self : memories are rose tinted, check the facts.
