### ISSUE TITLE
[CLASSIC] NPCs still get aggro while in escape/fear/sheep state- Causing weird behaivior

### ISSUE THREAD

**Issue by SatyPardus** [cmangos/issues#923]
**Current behavior**: 
All mobs have a chance, that when they are feared, sheeped or scared (running away low health) that they still pull aggro. At the moment they pull aggro they will "ignore" their current action and run towards the player, even still in sheep/fear/flee mode. That causes to a problem and let the creature stuck in a state, where he is not attacking but also dont going away. He just stick to the player with the pulled aggro.

**Expected behavior**: 
Don't get aggro while in a fear/sheep/flee mode. Just wait the time until the action run out and attack again.

**Steps to reproduce**:
Make a group, go into combat with any mob, fear/sheep the mob. Then a healer has to heal the person with the current aggro on that mob. As soon as he heals enough to pull aggro, the mob will run towards him (still feared/sheeped) and does nothing anymore. Even works with bosses!

**Client version**: 
1.12.1

**Database version**: 
Newest

**Operating system**: 
Linux Debian 64bit

**Comment by Appled** [comment]
I can confirm this on TBC

**Comment by Warlockbugs** [comment]
Please, verify if this still happens after https://github.com/cmangos/mangos-classic/commit/47664238b4e0e82ad0a6762beefcbf5e33c6b462.

**Comment by cyberium** [comment]
seem that is not happen :)
