### ISSUE TITLE
[CLASSIC] The Murloc Lurkers in Elwynn Forest does their backstab ability from the front too

### ISSUE THREAD

**Issue by SatyPardus** [cmangos/issues#924]
**Current behavior**: 
The Murloc Lurkers in Elwynn Forest does their backstab ability from the front too

**Expected behavior**: 
Only do it from the back

**Steps to reproduce**:
Attack Murloc Lurkers in Elwynn Forest

**Client version**: 
1.12.1

**Commit hash**: 
N/A

**Database version**: 
N/A

**Operating system**:
Linux

**Comment by cala** [comment]
Greetings and thank you for your report. This issue also extends to every NPC with the backstab ability.
An issue is already open about that: #239, so I'm closing this one.
