### ISSUE TITLE
[CLASSIC] Spell Duplication on Training

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#925]
**Current behavior**: 
When training a spell which should replace an old one, there will be two instance of the new spell in the player's spellbook.
Examples:
- Learning Sinister Strike (Rank 2) from a trainer will result in having two Sinister Strike (Rank 2) spells.
- Learning Journeyman Skinning from a trainer will result in having two Journeyman Skinning spells.

The duplicated spell is cleaned up after a logout.

**Expected behavior**: 
Spells replacing old ones should not create duplicates. Only the new spell should be in the spellbook.

**Client version**: 
1.12.1

I am planning to look into this.

**Comment by Phatcat** [comment]
Can't reproduce this, spells replacing old ones no longer create duplicates. tried with both examples given in the description.
