### ISSUE TITLE
[Classic] [class quest]The Tome of Divinity (6)

### ISSUE THREAD

**Issue by cavaclub** [cmangos/issues#926]
**Current behavior**: when i use http://db.vanillagaming.org/?item=6866 on Henze don't bring him to life, only Complete quest, but as i need henze live to return quest to him, i can't do anything to continue the quest sequence.

**Expected behavior**: bring Henze to life and give me the next sequence quest

**Steps to reproduce**:

1. we use http://db.vanillagaming.org/?item=6866 to bring Henze to life. (not working)
2. complete quest (work)
3. return to him to complete quest (not working since he continue dead)

**Client version**:  1.12.1

**Commit hash**: 

**Database version**:

**Operating system**:  ubuntu server 14 LTS

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Emky** [comment]
i just tested it and it seem to work fine, i ressed him and he is alive and also gave me the next quest
http://i.imgur.com/lB5lbWh.jpg  , also while i was typing this he also died again apprently, but it probably should be like that so the next person can take it.

**Comment by cavaclub** [comment]
i will reinstall world db

**Comment by cavaclub** [comment]
my fault, sorry...
