### ISSUE TITLE
Pet issues

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#931]
## Pet bugs

**Case 1: SPELL_EFFECT_SUMMON_CRITTER (mini pet)**
- Pet cannot be killed by AoE effects from enemies, this is wrong, they should take damage on AoE (this may be a DB issue, though...)

**Case 2: Hunter Pet**
- Pet should have its owner as it's target just after being tamed.

**Case 3: General Pet issues**
- Pets that normally cannot enter water... well.. they don't swim, they just slide along with you in the water, just sliding... I dunno what to do about this honestly. Should these pets be staying on land, not entering the water with the owner? Update: In patch 1.13.2 they actually swim alongside you, regardless of their ability to follow you in water as a mob, as a hunter's pet, they swim.
- When a pet is told to do a spell which requires a target, when you have no target, it says the pet is in combat. If you tell a pet to do a spell on a non-attackable mob it will say it is in combat... yeah... we need more error messages than just that the pet is in combat... we need a message for lack of target, for wrong kind of unit, etc.

**Comment by Phatcat** [comment]
Moving your comment here since it may be nuked when I drop the 2 commits.

@Chero commented on 86cb54f an hour ago
> What the hell is this... Pet modifiers are spells, called Tamed Pet Passive (DND).
For example 17206 gives 7% bonus damage to bats, 17208 gives -9% damage, 5% armor and 8% HP to bears. This kind of handling is wrong.

Thank you for telling me this. Do you know if we apply these or not? Cause if not then it needs to be added to this list of stuff TODO for the next pet update.

**Comment by dagochen** [comment]
Not so sure about case 6....Pets should get XP related to Hunter Kill XP.

**Comment by Phatcat** [comment]
Hmm.... 
http://wowwiki.wikia.com/wiki/Patch_1.7.0
Because I read this:
> Hunter pets now gain experience based on the level difference between them and their target rather than the difference between the Hunters and their target. This will make it much easier to level up a low level pet.

I must admit though that I did miss what it says right after;
> Keep in mind that the Hunter must still kill creatures from which he/she will gain experience.

**Comment by dagochen** [comment]
Well then its ok. I thought you might missed the part of mobs must be green or higher.

**Comment by Blumfield** [comment]
Thought i'd let you know that pet when summoned should be on the left side of your character and there is also something weird, the pet seems to "look" at your character( when you move it will face towards where your char is facing but when you stop moving, the pet "look" at you, it shouldn't do that )

I hope you'll understand what I mean

**Comment by Phatcat** [comment]
I consider those minor issues, something which does not change gameplay nor even game balance at all, it does however break immersion a bit and hopefully will get fixed eventually down the line.

I would be more than happy to look into this asap, but first I needs for pets to settle across all cores, and we recently just had problems with creature minions on wrath and currently we still have issues with PetAI and PetHandler regarding mind control across all cores, which makes it kind of hard for me to develop those any further as long as these issues persist, or I may in fact be finding myself regressing mind control even further.

**Comment by Phatcat** [comment]
Updated and removed issues that have already been fixed.

**Comment by DeTosc** [comment]
**Case 2:** (hunter pet exp gain) is even worse while in a group!

In the file "mangos-classic/src/game/Group.cpp":

```
static void RewardGroupAtKill_helper(Player* pGroupGuy, Unit* pVictim, uint32 count, bool PvP, float group_rate, uint32 sum_level, bool is_dungeon, Player* not_gray_member_with_max_level, Player* member_with_max_level, uint32 xp)
(...)
           uint32 itr_xp = (member_with_max_level == not_gray_member_with_max_level) ? uint32(xp * rate) : uint32((xp * rate / 2) + 1);
		   
            pGroupGuy->GiveXP(itr_xp, pVictim);
            if (Pet* pet = pGroupGuy->GetPet())
                // TODO: Pets need to get exp based on their level diff to the target, not the owners.
                // the whole RewardGroupAtKill needs a rewrite to match up with this anyways:
                // http://wowwiki.wikia.com/wiki/Formulas:Mob_XP?oldid=228414
                pet->GivePetXP(itr_xp / 2);

```
=> While in a group, the hunter pet receives half of the exp of its owner only.

Please consider to "hotfix" the last line to: 

`pet->GivePetXP(itr_xp);`
