### ISSUE TITLE
[CLASSIC] Some caster/bow NPC's are not attacking melee

### ISSUE THREAD

**Issue by SatyPardus** [cmangos/issues#932]
**Current behavior**: 
Some caster/bow NPC's will stop attacking you, when to close.

**Expected behavior**: 
Attack melee when to close

**Steps to reproduce**:
Get a NPC that uses a bow (NPC ID 3120)
Get close

**Client version**: 
Newest

**Database version**: 
Newest + Acid newest + SD2 Newest

**Operating system**: 
Win 10 and Linux Debian (Both 64 bit)

**Video:**
https://youtu.be/fyTthlmnedM

**Additional:**
I set up the database and core completly new, as i was thinking it's maybe a bug on my side, but still same behaivior.

**Comment by SatyPardus** [comment]
Found out that it's an acid bug. Posted it in the acid issues

**Comment by cala** [comment]
I updated the AI for many creatures yesterday. Could you tell me if this fixed the issue? If not, could you give the name/entry of the creatures still not working, please?
