### ISSUE TITLE
Linux build has set paths instead of pointing up a directory

### ISSUE THREAD

**Issue by knuxyl** [cmangos/issues#935]
**Current behavior**: 
When built on Linux with prefix INSTALL_PREFIX the program actually compiles to point to this *full* directory.
**Expected behavior**: 
Instead of pointing to */installpath/etc/X.conf* or */installpath/lib/X*, it should just use *../etc/X.conf* and *../lib/X*. This way the server can be moved and be portable. I'd rather have all the files just be in one folder though.
**Steps to reproduce**:

1. cd ~/Desktop/cmangossrc
2. mkdir build
3. cd build
4. cmake -DCMAKE_INSTALL_PREFIX=/home/user/Desktop/cmangos/ ../
5. make
6. make install

**Client version**: 
20MAY2016
**Database version**: 
TBCDB_1.5.0_cmangos-tbc
**Operating system**: 
Xubuntu 15.10 x64

**Error**:
bin, etc, and lib folders are now in /home/user/Desktop/Servers/tbc
Could not find configuration file /home/user/Desktop/cmangos/etc/realmd.conf.

**More**:
I know it is not an environmental variable or something of the sort because I noticed this error from a fresh install of Xubuntu and received that error.

**Comment by katz1** [comment]
I've run into this as well when I wanted to relocate my classic build. It seems the full path is burned to the binaries.

**Comment by cyberium** [comment]
this should be fixed please update your source
