### ISSUE TITLE
Stitches

### ISSUE THREAD

**Issue by Phatcat** [cmangos/issues#936]
Stitches is currently not a thing. I miss him... it.

The event is supposed to start when you turn in the quest Translation for Ello.
http://wowwiki.wikia.com/wiki/Stitches?oldid=2057678

Guards are supposed to come running in waves to try to stop him. You seem to be able to kite him past these without him aggroing them.
https://www.youtube.com/watch?v=4aWrUYgGe84

**Comment by cala** [comment]
Hi,

I just tested it on Classic and it works. Not much of a help for you, you might say… ;)
I did
```
.go creature id 263
.quest remove 252
.quest add 252
// Get quest reward with NPC
.go creature id 289
```
And I saw Stitches (neutral faction for now) moving from the hut to the forest, as I scripted it (him?) to do one or two years ago.

So if what is above does not work on your side, could you retry it after either:
- forcing the whole map 0 to load at startup time (in mangosd.conf)
- making Stitches an active creature by default `UPDATE creature_template SET ExtraFlags= ExtraFlags + 4096 WHERE Entry=412;`

**Comment by killerwife** [comment]
Hmmm sounds like a job for that active thing we have ^^

**Comment by Phatcat** [comment]
That is weird, because yesterday, i did do quest add 252 - then turned it in, then followed the road back towards the hut and never saw stitches.... Let me just try doing that again, I may have messed something up.

**Comment by killerwife** [comment]
I think Stitches should be one of those creatures that has that movement by default. Reason is that unless you turn off force loading of active creatures by default, a server will choke when it has 200 ish players. Just food for thought ^^

**Comment by Phatcat** [comment]
Yeah stitches is there, guess I was way too impatient. Sorry for the faulty report.

**Comment by cala** [comment]
No worries: better safe than sorry! :)
