### ISSUE TITLE
[classic]ice block

### ISSUE THREAD

**Issue by ROKB** [cmangos/issues#937]
ice block cant defense first time shooting spell[but after spell's immun]
maybe like divine shield too

ex)

p1 begins to cast soul fire.
you gain ice block
p1's soul fire crits you for 1197 fire damage.
ice block fades from you.

**Comment by Appled** [comment]
This is because hit results are calculated when spell cast is ended, not when the spell hits unit.

**Comment by cyberium** [comment]
Not confirmed it work now
