### ISSUE TITLE
Deep Run Tram Issue

### ISSUE THREAD

**Issue by Rog360** [cmangos/issues#939]
**Current behavior**: 
3 trams on one side are not running together. One side doesn't show up at all. All Spawns and addons are the same on udb, ytdb and psdb. Can't use Classicdb or TBCdb data as they have no gameobject_addon template.

**Expected behavior**: 
Both trams should arrive on each track [Front & Back] at opposite times.

**Steps to reproduce**:
1. Login
2. .tele deepruntram
3. Notice both trams don't arrive on each end. Trams that do arrive get out of sync after you use them.
4. Try it with different characters and you will see different results.

**Client version**: 
3.3.5a

**Commit hash**: 
33a65ae313b28cc0eb97a575e405adfd5f5f0811

**Database version**: 
Project-Silvermoon 

**Operating system**: 
Windows 7

**Comment by Phatcat** [comment]
Unable to reproduce in classic. Trams seem to works as intended here. Just getting that out there.

**Comment by cala** [comment]
Possibly a DB issue. Could you check the GO orientation/rotation against those in Classic DB?

**Comment by Rog360** [comment]
Tried Classic and only one side shows up and 2 of the trams on other side are going into the wall. Because, classic has no gameobject_addon template. So, maybe just WotLK Core has this problem... :(

**Comment by Vladskywolf** [comment]
I can confirm this is happening in WotLK core, UDB 408 update 491. The difference for me is that on one side the three cars are together, though on the other side they run separately. If you get on a single car, the other cars will end up going through you while traveling in the opposite direction.

Tested with:
build 12939 (w/cala's playerbot), commit 568a5a1e18b6f686fba2511692ea9d4f52b3d98c
build 12940, commit c529b71edb295b634cb80582516acf763ee38286

In my previous build, 12938, I never saw tram cars operating separately with the UDB 408_updatepack applied, with no further updates added as it was an older build.

**Comment by Valkirie** [comment]
This bug is part of a bigger issue core side. It has been fixed already on mangoszero after 3 phases of patch.

> https://github.com/mangoszero/server/commit/59156f5ec15d9ab7428afcffe5bb0d5ef800941c
> https://github.com/mangoszero/server/commit/e803c57c9f436da02b8099122e93d2efc361e4c5
> https://github.com/mangoszero/server/commit/9283f4309bec802f477087d2f4d454a55a81de75

**Comment by ulfgebhardt** [comment]
Seen this happen, i had one track go with 3 carts together and the other with 2carts + 1 cart (first lane).
This referes to TBC

**Comment by TULOA** [comment]
Is the patch in Valkirie mentioned addable to the WOTLK core? Has anyone tried?

Otherwise I am also noticing this issue.

**Comment by killerwife** [comment]
As a matter of fact, I am trying this on TBC branch, but its a huge project and I am nowhere near done. I will try to square it off inch by inch and when its in a working state I will add it to cmangos ofc to all 3 cores.

**Comment by TULOA** [comment]
Thanks alot killerwife I will be looking forward to it. Kinda nice because theres more ability to get back and forth between ironforge and stormwind lol.

**Comment by BenDol** [comment]
Any update on this issue?

**Comment by insunaa** [comment]
Probably fixed when this issue was fixed, which I believe to be a duplicate: https://github.com/cmangos/issues/issues/2339
