### ISSUE TITLE
[CLASSIC] Like Attacking all Nearby Enemies

### ISSUE THREAD

**Issue by ROKB** [cmangos/issues#941]
Sweeping Strikes, Whirlwind etc.. like Attacking all nearby enemies for normal damage  spell crash

**Comment by jimmybrancaccio** [comment]
@ROKB Can you let us know if this is still an issue in the latest Classic builds?

**Comment by Phatcat** [comment]
This is no longer an issue no, sweeping strikes and whirlwind seem to be working as intended and it's not crashing.
