### ISSUE TITLE
[CLASSIC] Warlock : Improved Shadowbolt

### ISSUE THREAD

**Issue by ROKB** [cmangos/issues#942]
Your Shadow Bolt critical strikes increase Shadow damage to the target by 20% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12sec.

The debuff doestn work correctly - the debuff reduce on every spell (like immolate / wand hit)
Would be nice if you can fix it, because its pretty significant for warlocks

**Comment by Argonn** [comment]
So the stacks are removed from non-periodic sources?  Seems about right if you ask me. 
Or does the ticks from Immolate also remove stacks?
Or does it give +20% damage on everything? (since immolate = fire damage and not shadow)

**Comment by ROKB** [comment]
Yeah the both problem. Immolate wand.. bla..

**Comment by bdebaere** [comment]
Still present in the commits below. Non Shadow damage spells remove charges from Shadow Vulnerability. They are however unaffected by the 20% bonus, which is good.

CMaNGOS Repo & Commit Hash:  [CLASSIC](https://github.com/cmangos/mangos-classic/commit/7fa4124748e2f378e209c82bd7d0dea448482f02)

Database Repo & Commit Hash: [CLASSIC](https://github.com/cmangos/classic-db/commit/c02a5131930c04e7b0a0fa2fca6ad726c025cac9)

**Comment by al3xc1985** [comment]
@killerwife can be closed....work as intended
