### ISSUE TITLE
[Classic] Fishing: instant pool respawn

### ISSUE THREAD

**Issue by Argonn** [cmangos/issues#943]
**Current behavior**: 
When you are fishing in a fishing pool, and 'clear out' the pool. A new pool will spawn instantly on the same location (tested 4-5 times)
**Expected behavior**: 
When you 'clear out' a fishing pool, there should be a timer before a new pool/wreckage will spawn on that location

**Steps to reproduce**:

1.  Learn fishing
2.  Set skill fishing 300 300
3.  Find a fishing pool (Ratchet / Feralas )
4. Start fishing until the pool runs out (2-5 times)

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
Classic DB 1.6.5 "The wailing pet. the midsummer joy and all that"

**Operating system**: 
Windows 7 Enterprise

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by cala** [comment]
Is this true for all fishing pools or only some of them?

**Comment by Argonn** [comment]
Tried multiple of them, (Ratchet and Feralas). Both with wreckage and with fish-pools. All with the same result.

**Comment by Argonn** [comment]
I could try some other areas. But looking at the code, there doesn't seem to be area specific handling. So I would assume its an general issue.

**Comment by cala** [comment]
What I'm trying to see is if this is a core or a DB issue. If you can spot a difference between two spots, then this is related to the DB, if all spots respawn as fast, then it may be from core/pool system.

**Comment by Argonn** [comment]
Lol nevermind. I tested this.... when you are a GM you always see the fishing pools.
