### ISSUE TITLE
[TBC] Healing Items For Specific Spells Give No +Healing Effect

### ISSUE THREAD

**Issue by Leadballoon2000** [cmangos/issues#944]
Current behavior: 
No +healing bonus is given to named healing spell
Items affected:
- [x] Idol of Rejuvenation itemid 22398
- [x] Harold's Rejuvenating Broach itemid 25643
- [x] Totem of the Plains itemid 25645 
- [x] Totem of Sustaining itemid 23200 
- [x] Totem of Life itemid 22396
- [x] Libram of Light itemid 23006
- [x] Libram of Divinity itemid 23201
- [x] Blessed Book of Nagrand itemid 25644
- [x] Libram of the Lightbringer itemid 28296 - https://github.com/cmangos/mangos-tbc/commit/f4f0f43a57913b7d08952788997dd85475875b40 / https://github.com/cmangos/tbc-db/commit/4944490420f74c63b84ed38d52327b8f11587613
- [x] Idol of the Emerald Queen itemid 27886
- [ ] Totem of Spontaneous Regrowth itemid 27544
- [ ] Libram of Souls Redeemed itemid 28592

- check if done

Expected behavior: 
Item gives bonus to healing.

Steps to reproduce:

Equip item
Cast named spell
Compare healed value with value when item isn't equipped
Average over a number of casts

Client version: 
2.4.3

Commit hash:

Database version: 
1.5

Operating system:

**Comment by Leadballoon2000** [comment]
https://github.com/TBC-DB/Database/pull/39
https://github.com/cmangos/mangos-tbc/pull/56

**Comment by al3xc1985** [comment]
Libram of Light itemid 23006

Libram of Divinity itemid 23201

Blessed Book of Nagrand itemid 25644

work as intended.. more to test

**Comment by al3xc1985** [comment]
Libram of the Lightbringer itemid 28296 does NOT work

**Comment by al3xc1985** [comment]
Libram of Souls Redeemed itemid 28592 ONLY the part with flash of light work

**Comment by al3xc1985** [comment]
Totem of the Plains itemid 25645   -- Works
Totem of Sustaining itemid 23200  -- Works
Totem of Life itemid 22396 -- Works

**Comment by al3xc1985** [comment]
Totem of Spontaneous Regrowth itemid 27544  -- does NOT work

**Comment by al3xc1985** [comment]
Idol of Rejuvenation itemid 22398 -- works
Harold's Rejuvenating Broach itemid 25643 -- works
Idol of the Emerald Queen itemid 27886 -- works

**Comment by al3xc1985** [comment]
So, does NOT WORK 

Totem of Spontaneous Regrowth itemid 27544 -- does NOT work
Libram of Souls Redeemed itemid 28592 ONLY the part with flash of light work need to add holy light bonus

@killerwife  test is done here, you can take care forward

**Comment by fatalieror** [comment]
This is also true for classic repo.
Libram of divinity does not increase Flash of Lights healing.
