### ISSUE TITLE
[CLASSIC] High Rank Spellcasting on Friendly Low Level NPCs Bug

### ISSUE THREAD

**Issue by Zooke** [cmangos/issues#950]
**Current behavior**: Spell never completes giving 'Another action is in progress' error and leaving the spell highlighted.

**Expected behavior**: npc receives appropriate spell rank for their level.

**Steps to reproduce**:
1. 60 priest cast highest level buff on low level npc. In my case this was Volcor (http://db.vanillagaming.org/?npc=3692#wh-comments) whilst looking at the escort quest.

Seeing as the npc does actually receive the corrected spell rank, I am going to take a wild stab in the dark and suggest that the core then wrongly completes (or tries to) that spell rank rather than the one originally cast.

**Comment by Phatcat** [comment]
> Expected behavior: npc receives appropriate spell rank for their level.

Should actually not apply the buff is the target is too low level, it should send an error to the player about the target being too low level; automatic downranking was done with macros in vanilla, was not added to the game until later (either tbc or wrath, don't ask me)

Also, please stop using unreliable sources like db vanillagaming (...) and instead use cached wowwiki or cached allakhazam sites..

**Comment by Zooke** [comment]
As you point out, it would seem that the spell should not be allowed to be cast.

I do however find it difficult to believe that on 1.12 retail you had to logout to be able to cast again if you made the mistake of accidentally casting a high level spell on a low level player.

But as it seems I am getting a 'schooling' today. I will close this issue and accept that this was just one of those vanilla quirks.

**Comment by Phatcat** [comment]
> I do however find it difficult to believe that on 1.12 retail you had to logout to be able to cast again if you made the mistake of accidentally casting a high level spell on a low level player.

No, you are right, it is indeed bugged as it should produce an error message and send it to the player. We do not do this currently. I am sorry if you feel I was a bit harsh on you, it was not my intention at all.

**Comment by Zooke** [comment]
Re-opened because currently it does lockout spellcasting whereas they should as Phatcat points out, not cast at all and provide an on-screen error remark of some kind. Target level too low or something very similar seems to ring a bell in my head.

**Comment by Phatcat** [comment]
This reminds me of another issue we're having on at least vanilla; casting a low level spell will overwrite a higher level spell; ie; A rank 1 rejuvenation will overwrite and delete an already active rank x rejuvenation. It should instead send an error message saying something along the lines of 'a higher level spell is already active' or something.
Maybe I should open a seperate issue for this..

**Comment by Phatcat** [comment]
http://wowwiki.wikia.com/wiki/Patch_2.0.1
> When casting a buff on a low level target, the appropriate rank of the buff will automatically be applied.

**Comment by al3xc1985** [comment]
@killerwife this can be closed... works as intended
