### ISSUE TITLE
SPELL_EFFECT_ACTIVATE_OBJECT Quirks

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#951]
I have recently discovered that the SPELL_EFFECT_ACTIVATE_OBJECT when in conjunction with darkmoon faire cannon is supposed to do a different from default behaviour.

While normal click on GO should start firing script, the usage of this spell should result in playing of "Custom Animation". Therefore as of now it requires quite the ugly switch case in EffectActivateObject for spell 24731.

Should anyone have more clues about the general behaviour of stuff feel free to share, because I feel this handler needs work.

**Comment by VladimirMangos** [comment]
Possible related code must be in GameObject::Use for specific game type

**Comment by killerwife** [comment]
Yes, and no. I will upload

**Comment by killerwife** [comment]
Yes and no. Problem is that Use is used when player uses it. I need different behaviour during this spell effect and during player usage (one starts custom animation, one casts spell). I will upload the code that is the source of this issue.

**Comment by killerwife** [comment]
@VladimirMangos https://github.com/killerwife/mangos-tbc/commit/4a5999e242ffb800472329949311bdfeb802f187

This code works 100% in relation to vanila/TBC faire cannon behaviour. (requires db part but i thats x-saviors ownership). As you can see i need different behaviour during spell usage. Also I am using a random root effect, because I suspect blizzard used a serverside spell.

**Comment by xfurry** [comment]
@killerwife the code that you need to look at is here: https://github.com/cmangos/mangos-wotlk/blob/master/src/game/SpellEffects.cpp#L10343

Depending on EffectMiscValue the action needs to be different.
I know from my previous research that there should be some spells that are used for fireworks (value = 3).

Please check the current logic and let me know if there is anything we need to change.

**Comment by VladimirMangos** [comment]
In referenced spell miscvalue = 1 but expected work as case 13 possible with direct alternative state set

**Comment by VladimirMangos** [comment]
I can't suggest proper way code required store triggered spell for aura look too strange for normal spell system work. Maybe we missing some other way selection or spll dependent from targeted GO check... not sure...

**Comment by xfurry** [comment]
Usually the custom animation is tagged to the GO itself, and not with the spell that is using the GO.
There are a few exceptions for the GOs that SendCustomAnim(). That can be found in the GO::Use() in the GO_Trap (type 6) related code.

**Comment by killerwife** [comment]
@xfurry look at videos of usage of the cannon and ull see why i did it the way i did it

**Comment by xfurry** [comment]
@killerwife can you show me the videos then?

**Comment by killerwife** [comment]
https://www.youtube.com/watch?v=ywEpt0u0Qa8 @xfurry

**Comment by killerwife** [comment]
@xfurry if you put custom animation in template, it will play animation on usage by player as well

**Comment by xfurry** [comment]
Then we don't need to add the change in EffectActivateObject()

**Comment by killerwife** [comment]
Huh? Where do you want to add the change to then? Clearly current core doesnt support the behaviour to that script right now.

**Comment by Grz3s** [comment]
interesting... :) I wanted speak with @xfurry about exact same thing: long time ago...
But amount of work i had.. so i put this on hold...
Part you showed here:
```code
// this appear to be ok, however others exist in addition to this that should have custom (ex: 190510, 188692, 187389)
            if (info->goober.customAnim)
                SendGameObjectCustomAnim(GetObjectGuid());
            else
                SetGoState(GO_STATE_ACTIVE);
```

Many times I had problem with custom_anim for goobers (10) ... they never wanted to work correctly...
Let me give you an example ... I took few (updated: also added object GO 180452 - from this topic)
Pls look how they work:

current code:
https://www.youtube.com/watch?v=36p1msiU1ow&feature=youtu.be

You can see ...that only one works correctly - that wooden box.. rest work wrongly or doesnt work at all.

So i removed this:
```code
-            // this appear to be ok, however others exist in addition to this that should have custom (ex: 190510, 188692, 187389)
-            if (info->goober.customAnim)
-                SendGameObjectCustomAnim(GetObjectGuid());
-            else
-                SetGoState(GO_STATE_ACTIVE);

 -           m_cooldownTime = time(nullptr) + info->GetAutoCloseTime();
```
and  replaced that code ... using simmilar from traps:

```code
            SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE);
            SetLootState(GO_ACTIVATED);

+            // TODO: Improve this when more information is available, currently these goobers are known that must send the anim (test)
 +           if (GetDisplayId() == 245 || GetDisplayId() == 345 || GetDisplayId() == 528 || GetDisplayId() == 4473 || GetDisplayId() == 6544 || GetDisplayId() == 6869)
 +              SendGameObjectCustomAnim(GetObjectGuid());

            if (user->GetTypeId() == TYPEID_PLAYER)
```

And pls look what we have  after change:
https://www.youtube.com/watch?v=BmRsGlhzACc&feature=youtu.be

Objects used:
```sql
181699 - Barrel of Filth - 6869         		-- Without = doesnt work -- with works fine
184661 - Smoke Beacon - 6544            		-- Without = doesnt work -- with works fine
190510 - Captured Jormungar Spawn - 528 		-- Without = works       -- with works also
188692 - Valiance Keep Cannon - 245     		-- Without = player casts multiple spell ???  -- with better animation from gun
187389 - Falling Rocks - 4473 --        		-- Without = work partly -- with much better (full animation)
184694 - Zelana's Alchemy Set - 345     		-- Without = doesnt work -- with works fine
180452 - Blastenheimer 5000 Ultra Cannon - 6429 -- Without = doesnt work -- with works fine


Note:
Code i gave you... is only to proof that current code is wrong and doesnt work as it should...
Also... Main problem with new code is fact ..that "displayID" must be added manualy for each goober to have it working correcly (but that the same what we have with traps)

**Comment by xfurry** [comment]
@Grz3s thanks for info.
I'm checking the logic of this right now. Basically the GO code is very ancient and it never worked too well.

**Comment by xfurry** [comment]
How about use ```SendGameObjectCustomAnim(GetObjectGuid());``` for all type 6 and type 10 GOs on Use()?
Would that do any harm?

**Comment by killerwife** [comment]
thats whats being done atm and thats what the problem is ^^ (if you mean GameObject->Use())

**Comment by Grz3s** [comment]
Another object can be added into my Patch list:
187432 - Alliance Flag - 5651       -- Without = doesnt work  -- with works fine

**Comment by xfurry** [comment]
@Grz3s ok, I'll add that to the list.
Just note, that your patch is not fully correct. I need to do a deep investigation of this, because currently it breaks other game objects.

**Comment by Grz3s** [comment]
can you pls give me entrys -- that this patch damages?

**Comment by cala** [comment]
I'd like to add another stone to that thread.

I'm currently fine tuning the Rookery in UBRS. This room is full of a GO trap (entry 175124).
When players come near the GO, the trap is triggered (spell cast, GO animation played and GO despawned). This is correct and working as intended.

Those GOs can also be activated by NPCs ([from this event](https://github.com/cmangos/mangos-wotlk/blob/master/src/scriptdev2/scripts/eastern_kingdoms/blackrock_spire/instance_blackrock_spire.cpp#L593)). I'm currently scripting [NPC 10264](http://www.wowhead.com/npc=10264/solakar-flamewreath) to this intended. The NPC casts [a spell](http://www.wowhead.com/spell=16556) with SPELL_EFFECT_ACTIVATE_OBJECT that targets the trap GO. The trap spell is triggered but the GO animation is not played and the GO is not despawned. This is wrong, it should have the exact same behaviour than a trap GO triggered by a nearby player.

I could not find out why activating the trap by spell results in a different behaviour that triggering the trap by a player in trap radius.

**Comment by al3xc1985** [comment]
You implemented it, don't you @killerwife

**Comment by killerwife** [comment]
There is support for it, yes. This is pending research but now it can be done in spell system partly.
