### ISSUE TITLE
[TBC] Prospecting doesn't work 

### ISSUE THREAD

**Issue by zypr** [cmangos/issues#953]
Prospecting no longer works on the same stack after you've already use it once

https://www.youtube.com/watch?v=Rs045jRCD6g

**Client version**: Version 2.4.3 (8606)

**Commit hash**: https://github.com/cmangos/mangos-tbc/commit/5065d0e1aa8edf32c8dc148f5177cae66083dd6e

**Database version**: https://github.com/TBC-DB/Database/commit/9ba445f8a7e531ab32c9345b40c387ff91e45343

**Comment by Lankytim** [comment]
I also noticed the same problem, on an earlier commit (or maybe even before but I can't be sure).

**Commit hash:** https://github.com/Lankytim/mangos-tbc/commit/69bf156f8956e4bf7c4421f1d5e81835944af161

**Comment by cyberium** [comment]
Its from loot rewriting. I have to fix that but i had some question and no correct answer.
What does happen on classic, tbc and wotlk when we close an opened loot windows not fully looted?

**Comment by Zooke** [comment]
This is a good question, I can see no alternative than the loot being lost though.
Otherwise players would have continually prospected the ore until they got a favourable drop. And this definitely did not happen.

**Comment by cyberium** [comment]
I more think its like disenchanting, i mean as soon as the spell is finished the ore are deleted, the loot windows is opened and if we dont loot the items they are lost. This however is true only for TBC. In WoTLK the items are send in the bag if there is enough space or lost.
Are you all ok with this?

**Comment by cala** [comment]
Agree.

**Comment by Phatcat** [comment]
>as soon as the spell is finished the ore are deleted, the loot windows is opened and if we dont loot the items before closing that windows they are lost.

Not at all how I remember mining; shouldn't the ore NOT be deleted until the loot has been removed from it?

**Comment by cyberium** [comment]
its not mining, its prospecting :)

**Comment by Phatcat** [comment]
... I gotta learn to read; My knowledge of TBC is embarrassing given the amount I played that, forgot prospecting was for like jewelcrafting shit.....
Disregard what I said.

**Comment by cyberium** [comment]
Should be working now after https://github.com/cmangos/mangos-tbc/commit/d2bd17056d87a683cc376b0b0a690f29075e8d07
