### ISSUE TITLE
[Classic] Event AI Bug..

### ISSUE THREAD

**Issue by keyshuwen** [cmangos/issues#954]
**Current behavior**: 
action1_type = 12 ,Creatures will summon a lot..
**Expected behavior**: 
 Can cause the server to become very card.
**Steps to reproduce**:
1. Stand on the top of the house. Attack NPC.
   For example: Runk Windtamer
## ![image](https://raw.githubusercontent.com/keyshuwen/mangos-classic/master/bug_images/20160606152640.png)

![image](https://raw.githubusercontent.com/keyshuwen/mangos-classic/master/bug_images/20160606153322.png)
**Client version**: 

**Commit hash**: 

**Database version**: 
  https://github.com/classicdb/database/commit/537d336bdf1f2b04f24058f9c90ee748ad6f5df8

**Operating system**:

**Comment by SatyPardus** [comment]
But looks very cool. So is it a feature? :D

**Comment by keyshuwen** [comment]
No...It is a Bug... :D

**Comment by AnonXS** [comment]
Taxi Flight npcs probably missing hidden serverside for summoning these npcs which then should be despawned on evade or have shorter/other despawntime scripted into the spell.

```
-- Runk Windtamer
('1517801','15178','4','0','100','0','0','0','0','0','12','9297','1','30000','12','9297','1','30000','1','-548','0','0','Runk Windtamer - Summon Enraged Wyverns and Yell on Aggro'),
```
