### ISSUE TITLE
Elemental damages on weapons are handled as physical damages

### ISSUE THREAD

**Issue by cala** [cmangos/issues#957]
**Current behavior**: 
When using a wand or a weapon dealing elemental damages, the target receive physical damage instead.

**Expected behavior**: 
The target should take damages of the elemental type used by the wand/weapon.

**Steps to reproduce**:
1. Give physical immunity to a NPC (requires commit of CMaNGOS Classic core https://github.com/cmangos/mangos-classic/commit/666b414471f7abf599afac7779be7fea68a11dd3) and give fire immunity to another NPC
2. Change a melee weapon damage to fire and do the same for a wand
3. Equip the weapon and wand on a player
4. Attack the two NPCs: the physical immune will take no damage, the fire immune will take damage (physical one)

**Client version**: 
Classic 1.12.1

**Commit hash**: 
https://github.com/cmangos/mangos-classic/commit/666b414471f7abf599afac7779be7fea68a11dd3

**Database version**: 
Classic DB v1.6.5

**Operating system**: 
No relevant.

**Comment by cala** [comment]
See https://github.com/cmangos/mangos-classic/pull/119 for more information.
Also commit https://github.com/cmangos/mangos-classic/pull/119/commits/79784a931ea1e4e1d037fd4a223d882f31ceba7e by @sidsukana proposes a way of fixing this for wand. I suggest we look for a more generic approach of the issue.

**Comment by sidsukana** [comment]
@cala what are you weapon use (with elemental damage) not wand and not subdamage? enchantment?

**Comment by Saben65** [comment]
Going back to what Sidsukana asked, what other weapons primary damage is elemental that a generic solution would be needed? And if there are none, can we get Sidsukana's wand fix pushed? Half the fun of running Karazhan as a caster is having to hit Mana feeders with a stick because they are immune to your spells AND wand -_-.

**Comment by killerwife** [comment]
The reality of the situation is that:
1. Yes we know its needed
2. Noone has time to work on it atm
There is a PR by @cala on cmangos which is not finished and if someone were to finish it, and be willing to support changes, I am sure it would be expedited much more quickly.

**Comment by AnonXS** [comment]
Resolved due to recent reworks by @Warlockbugs
