### ISSUE TITLE
[CLASSIC] Quest 2478 scripts

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#960]
The horde rogue poison quest had some fairly unique scripts on retail, which made it possible to solo the quest even on level 20. Some NPCs instantly died from a successful ambush and the HP of the final boss was dropped to 50% from a successful ambush (regardless of the actual damage done). Check the comments [here](http://db.vanillagaming.org/?quest=2478#wh-comments) for the details.

Non of these are happening here, so the quest may be hard to solo even for a level 30.

**Comment by killerwife** [comment]
Should be easily doable in EAI :)

**Comment by cala** [comment]
Pretty sure this was somehow implemented recently (I remember reading comments about this). But we need to check before closing this issue.

**Comment by killerwife** [comment]
Implemented them all myself.
