### ISSUE TITLE
[TBC] Quest: 10506 - A Dire Situation

### ISSUE THREAD

**Issue by Leadballoon2000** [cmangos/issues#962]
**Current behavior**: 
The provided "Rina's Diminution Powder" shrinks the wolves but you get no credit for doing so

**Expected behavior**: 
Using the quest item gives quest credit

**Steps to reproduce**:

1. Target wolf quest mob
2. Use item
3. Profit

**Client version**: 
2.4.3

**Commit hash**: 

**Database version**: 
1.5

**Operating system**:

**Comment by killerwife** [comment]
:O you fixed a pending buged quest on vengeance, awesome, this is like christmas for me

**Comment by Leadballoon2000** [comment]
Nuts, I didn't notice that this had been assigned :P
