### ISSUE TITLE
Lair Brute does not call for help

### ISSUE THREAD

**Issue by Blumfield** [cmangos/issues#964]
**Current behavior**: 
 Lair brute does not call for help

**Expected behavior**: 
 Lair brute should call for help at near death (15% of HP)

**Steps to reproduce**:

1. Look for the first Lair brute in gruul's lair
2. Damage him to 15% hp
3. Nothing happen

**Client version**: 
2.4.3

**Commit hash**: 
cb0fca1b377dff0181c29e6e3e5e92d32797eaec

**Database version**: 
Lastest TBC-DB

**Operating system**: 
Windows

http://wowwiki.wikia.com/wiki/Lair_Brute

Currently I created this SQL 
INSERT INTO `creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES (1938904, 19389, 2, 0, 100, 0, 15, 0, 0, 0, 39, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Lair Brute - Call for Help at 15% HP');

It doesn't seems to work, did I miss something ?

**Comment by cala** [comment]
Thanks for your report. From what I read here: https://github.com/ACID-Scripts/TBC/commit/b13e68ea25c3516dd9b0a6babf9cf5df2bd6ed41, the Lair Brute should already call for help on low HP. Could you check that you have ACID for TBC correctly installed and set? Also look for all the ACID scripts for this NPCs and check if the "call for help" one is indeed there.

**Comment by Blumfield** [comment]
It works, this is my bad I completely forgot about ACID repo, thanks again and sorry
