### ISSUE TITLE
[CLASSIC] Druid: Improved mark of the Wild doesnt apply

### ISSUE THREAD

**Issue by SatyPardus** [cmangos/issues#967]
**Current behavior**: 
The talent changes the tooltip of mark of the wild, but doesnt increase the actuell buff

**Expected behavior**: 
Increase the buff

**Steps to reproduce**:

1. Put talent point in improved mark of the wild
2. Cast it on someone
3. Profit

**Client version**: 
Newest

**Operating system**: 
Linux Debian 64 bit

**Comment by sidsukana** [comment]
you try cast  Mark of the Wild again?

**Comment by sidsukana** [comment]
It's a basic simple modified aura, and it not just break

**Comment by SatyPardus** [comment]
What do you mean? I tried it multiple times. Even reset the talent points and tried it again. It doesnt modify the stats of the buff, when applied.

Only the tooltip of the buff is changed, in the spellbook.

**Comment by SatyPardus** [comment]
Okay, after checking again, yes it works. But the applied buff tooltip seems to be wrong.
Is this a standard classic bug or something we can fix? I gonna close this when it is normal.

**Comment by Laizerox** [comment]
If the problem is in "Buff tooltip" then it's client side issue.

**Comment by SatyPardus** [comment]
Ah okay, then close^^
