### ISSUE TITLE
[Classic] Spell "Eyes of the Beast" to crash the program

### ISSUE THREAD

**Issue by vanrhy** [cmangos/issues#968]
**Current behavior**: 
program crashes,When I use "Eyes of the Beast".The console display "Camera::SetView, viewpoint is not in map with camera's owner" 
**Expected behavior**: 

**Steps to reproduce**:

**Client version**: 
1.12
**Commit hash**: 

**Database version**: 

**Operating system**: 
windows 7
windows 10

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by shnibble** [comment]
I was able to reproduce this on Classic core

**Comment by vanrhy** [comment]
I found this problem come from [SpellAuras.cpp](https://github.com/cmangos/mangos-classic/blob/master/src/game/SpellAuras.cpp#L2130),I think this TypeId was wrong.

I was change the TYPEID_PLAYER to TYPEID_CORPSE,problem solved.

**Comment by shnibble** [comment]
Indeed it does fix the issue. Good find!

**Comment by SilvioDoMine** [comment]
@cyberium I tried and this does not fix the issue on TBC. When I use the spell, the server crashes after 3-5 seconds. I can see the beeing dismissed and the aura of "Eyes of the Beast" active.

**Comment by cyberium** [comment]
yes its confirmed issues. There is some backport pending to resolve it in near future.

**Comment by SilvioDoMine** [comment]
@cyberium is there a way to disable the spell or something to prevent the server from crashing? Thanks away for the hard work.

**Comment by Phatcat** [comment]
Solved by https://github.com/cmangos/mangos-classic/commit/e010c157cbbe4c767ef1b22ca1f06044d0145f07
