### ISSUE TITLE
[WotLK] Server crash on a perticular event

### ISSUE THREAD

**Issue by adellaci** [cmangos/issues#969]
**Current behavior**: Crash upon "Spell 9653 Effect0 : 56 Targets: Creature (Entry: 4651 Guid: 27269), -, -"

**Expected behavior**: Not crash

**Steps to reproduce**:

1. Did git pull on 06/19/16 of "mangos", "Database", and "acid" 
2. Compiled, no errors, and the usual warning.
3. Install over compiled server from 06/11/16
4. Start mangosd.sh
5. After a period of time the server stops with the same last entries

**Client version*3.3.5a, but N/A*: 

**Commit hash**: CMaNGOS/0.18 (2016-06-19 08:12:31 - a01e8684a6320fa27c57107c8d93e400549d58e8) for Linux_x64

**Database version**: UDB_0.12.2_mangos_11792_SD2_2279.sql with updates up to 493_quest_11608.sql

**Operating system**: Ubuntu 14.04 LTS x64 up to date as of 06/18/16

I started up the server 3 times and the same thing happens. All three times I end up with the same entries in the log. I realized that "/mangos/sql/base/mangos.sql" & "/mangos/sql/scriptdev2/scriptdev2.sql". processed them in order, and re-ran "InstallFullDB.sh" from UDB.

Code: from server log
2016-06-19 08:58:53 Sending SMSG_SPELL_START id=9653
2016-06-19 08:58:53 Sending SMSG_SPELL_GO id=9653
2016-06-19 08:58:53 Spell 9653 Effect0 : 56 Targets: Creature (Entry: 4651 Guid: 27269), -, -

It seems to be related to an NPC (Gelkis Earthcaller) in Desolace. 

I will tomorrow night compile with debug on, wipe the out the server, including the database, and install from scratch incase it is related to install over last weeks CMaNGOS update.

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Phatcat** [comment]
You are probably crashing due to missing this commit: https://github.com/cmangos/mangos-wotlk/commit/a337420ba86f0a0a696293f94cb76eeaf33494ea

It was merged on the 20th, so..

**Comment by adellaci** [comment]
Thank you Phatcat. I will re-pull tomorrow night and run it. I will reply after it has been up for a couple of hours

**Comment by adellaci** [comment]
I'm going to pull now and let it run over night, and reply back when i get home tomorrow

**Comment by adellaci** [comment]
Pulled "mangos, "Database", and "acid"
processed "/mangos/sql/scriptdev2/scriptdev2.sql", "/Database/Updates/494_*.sql and 495_*.sql", & "/acid/acid*.sql".
Compiled CMaNGOS, and server is up and running. Will report back tomorrow.

**Comment by adellaci** [comment]
check it be leaving for work, server stopped after 23 minutes, same three lines at the end of the log file

**Comment by cyberium** [comment]
@Phatcat 
https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Pet.cpp#L946
https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Pet.cpp#L892

You use pInfo pointer without checking the validity.
To reproduce it just do ".cast 9653"

**Comment by Phatcat** [comment]
@cyberium Does that not indicate an issue with the spell 9653? like missing pet_levelinfo - remember our chat here: https://github.com/cmangos/mangos-classic/commit/c018db951028b9a2e45ed6f137791f836f82164c#commitcomment-17878058 ?

But please, just give me the go-ahead to push https://github.com/cmangos/mangos-classic/pull/151/commits/af6171a7f9d096ce3403246d61998bd8513bf418 to all 3 cores and I'll do it in a manner of minutes, but I'm telling you, we're nt gonna get nearly as much feedback then and we're no longer truly notified about missing data in pInfo (cause noone is going to read the error log if the server don't crash - especially not non-developers)

**Comment by killerwife** [comment]
@Phatcat they most likely want you to extract the fix for it from it and deploy it separately ASAP

**Comment by Phatcat** [comment]
Okay, gonna be home in roughly 20 min, will do it right away then.

**Comment by Phatcat** [comment]
Yepp, issue is actually not this at all, issue is that the pet type is set to Summon_pet for this spell and any other summon_pet function, while it shouldn't. all mobs should only have guardian creature types within the new system. this is why it's currently failing, a mixture of missing a fallback if no pointer as well as not even being supposed to use any case containing any pointers.

I cannot just slap that patch on it as it does not fix the actual problem here it just hides it. . .

**Comment by Phatcat** [comment]
That was a poor choise of words; creature PETS should only ever be set to guardian_pet, not summon_pet - summon_pet and hunter_pet should be reserved for players only.

The thing is I don't know what players can summon controllable pets in wrath as I didn't play wrath so I'm gonna need a bit of info here.

**Comment by cyberium** [comment]
Its true we have to "hide" the problem in some way. Its better than let the server crash.
Here is my solution:
```cpp
PetLevelInfo const* pInfo = sObjectMgr.GetPetLevelInfo(1, petlevel);
if (!pInfo)
{
    for (int i = STAT_STRENGTH; i < MAX_STATS;++i)
        SetCreateStat(Stats(i), 1.0f);
    sLog.outError("blabla");
}
else
    for (int i = STAT_STRENGTH; i < MAX_STATS;++i)
       SetCreateStat(Stats(i), float(pInfo->stats[i]));
```
That way users will complain of bad stats and db devs will be able to do something.

**Comment by Phatcat** [comment]
Currently testing a fix locally.

**Comment by adellaci** [comment]
let me know when you commit it and I'll test also it right away

**Comment by adellaci** [comment]
I see that there was an update to "pet.ccp". I compiled it and running

**Comment by Phatcat** [comment]
You are very welcome to test if https://github.com/Phatcat/mangos-wotlk/commit/ab5c9ac2ae10dd56e9719147e90e16b0eb3041cc does the trick.

**Comment by adellaci** [comment]
Thank Phatcat.
I've make the changes to SpellEffects.cpp, compiled, and the server is up. I get back later tonight on the result

**Comment by adellaci** [comment]
The server has been up for 4 hours no issue.

**Comment by adellaci** [comment]
I have yet to log in and try running around the world

**Comment by brentonannan** [comment]
Gday. I merged this fix on the advice of adellaci on the forum, and it fixed the random crashing, however I'm getting a segfault again when I summon the ghost wolf for the quest "rite of vision" - I thought it might be related (because of the `EFFECT_SUMMON` line)? Output of the server:

```
LoadPath: loading waypoint path for Creature (Entry: 3220 Guid: 25849)
WORLD: Received opcode CMSG_TIME_SYNC_RESP: counter 33, client ticks 14557525, time since last sync 9981 
 WORLD: Opcode CMSG_TIME_SYNC_RESP -- Our ticks: 14557725, diff 200, latency 53                          
Sending SMSG_SPELL_GO id=4981
Spell 4981 Effect0 : 28 Targets: Player Jurgen (Guid: 1), -, -
Spell Effect EFFECT_SUMMON (28) - summon without destination (spell id 4981, effIndex 0)
Creature (Entry: 2983 Guid: 151145) enters grid[27,31]
LoadPath: loading waypoint path for Creature (Entry: 2983 Guid: 151145)
Creature 151145 used AI is ReactorAI.
Segmentation fault (core dumped)
```

I'm using `mangos-woltk@3af38d5d2e955492fbc13c4db5aa0ba8689a36d3` and `unified-db/Database@531480b073faf96c324a2cf77eb5237f06d4d0e6q`

If this is not related, where would y'all recommend reporting it.

Thanks.

**Comment by killerwife** [comment]
Please, you need to provide complete backtrace to be of any help.

**Comment by brentonannan** [comment]
That's all the server output, with LogLevel 3. If you could provide a link with how to debug with a full backtrace, I'd be happy to.

**Comment by killerwife** [comment]
Windows or linux?

**Comment by brentonannan** [comment]
Linux. Ubuntu 14.04.

**Comment by killerwife** [comment]
Then go read how to do core dumps, and then in GDB just write "bt"

**Comment by brentonannan** [comment]
Great, thanks. It's late here, will probably do it tomorrow.

**Comment by brentonannan** [comment]
Ok, here's the bt:

```
(gdb) bt
#0  0x000000000083c7c7 in Spell::DoSummonWild(std::vector<Spell::CreaturePosition, std::allocator<Spell::
CreaturePosition> >&, SummonPropertiesEntry const*, SpellEffectIndex, unsigned int) ()
#1  0x00000000008461e7 in Spell::EffectSummonType(SpellEffectIndex) ()
#2  0x00000000007f406c in Spell::HandleEffects(Unit*, Item*, GameObject*, SpellEffectIndex, float) ()
#3  0x00000000007f4a7a in Spell::DoSpellHitOnUnit(Unit*, unsigned int) [clone .part.246] ()
#4  0x00000000007f5477 in Spell::DoAllEffectOnTarget(Spell::TargetInfo*) [clone .part.409] ()
#5  0x00000000007fe56a in Spell::handle_immediate() ()
#6  0x0000000000804306 in Spell::cast(bool) ()
#7  0x0000000000804f74 in SpellEvent::Execute(unsigned long, unsigned int) ()
#8  0x000000000093250f in EventProcessor::Update(unsigned int) ()
#9  0x00000000006d2ee1 in Unit::Update(unsigned int, unsigned int) ()
#10 0x000000000068d744 in Player::Update(unsigned int, unsigned int) ()
#11 0x00000000007ad9b1 in Map::Update(unsigned int const&) ()
#12 0x00000000007ba52d in MapManager::Update(unsigned int) ()
#13 0x000000000087726b in World::Update(unsigned int) ()
#14 0x0000000000551cda in WorldRunnable::run() ()
#15 0x00007f5c54dcca60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007f5c545e9184 in start_thread (arg=0x7f5c37588700) at pthread_create.c:312
#17 0x00007f5c5431637d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by Phatcat** [comment]
Looks like a summon / pet issue, I guess that one is on me.
Honestly, both Wrath and TBC need a bit more love in the pet department as the outer workings of the systems in the versions differ quite a bit more than I thought, and I did my initial pet work for vanilla.

**Comment by brentonannan** [comment]
@Phatcat I got the same problem when using the Digging Claw in the quest Egg Hunt in Southern Barrens. The backtrace looks the same:

```
(gdb) bt
#0  0x000000000083c7c7 in Spell::DoSummonWild(std::vector<Spell::CreaturePosition, std::allocator<Spell::
CreaturePosition> >&, SummonPropertiesEntry const*, SpellEffectIndex, unsigned int) ()
#1  0x00000000008461e7 in Spell::EffectSummonType(SpellEffectIndex) ()
#2  0x00000000007f406c in Spell::HandleEffects(Unit*, Item*, GameObject*, SpellEffectIndex, float) ()
#3  0x00000000007f49fd in Spell::DoSpellHitOnUnit(Unit*, unsigned int) [clone .part.246] ()
#4  0x00000000007f5477 in Spell::DoAllEffectOnTarget(Spell::TargetInfo*) [clone .part.409] ()
#5  0x00000000007fe56a in Spell::handle_immediate() ()
#6  0x0000000000804306 in Spell::cast(bool) ()
#7  0x0000000000804f74 in SpellEvent::Execute(unsigned long, unsigned int) ()
#8  0x000000000093250f in EventProcessor::Update(unsigned int) ()
#9  0x00000000006d2ee1 in Unit::Update(unsigned int, unsigned int) ()
#10 0x000000000068d744 in Player::Update(unsigned int, unsigned int) ()
#11 0x00000000007ad9b1 in Map::Update(unsigned int const&) ()
#12 0x00000000007ba52d in MapManager::Update(unsigned int) ()
#13 0x000000000087726b in World::Update(unsigned int) ()
#14 0x0000000000551cda in WorldRunnable::run() ()
#15 0x00007fd72211ca60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007fd721939184 in start_thread (arg=0x7fd7049be700) at pthread_create.c:312
#17 0x00007fd72166637d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by Phatcat** [comment]
I'll look into it, thank you.

You should consider opening a new issue for these 2 crashes as they seem unrelated to this crash.

**Comment by brentonannan** [comment]
Yeah, I wasn't sure. I'll go ahead and do that now.
