### ISSUE TITLE
[CLASSIC] Hunter: Pet stops attacking when target switch

### ISSUE THREAD

**Issue by SatyPardus** [cmangos/issues#970]
**Current behavior**: 
When you pull 2 mobs and your pet attacks one of it, as soon as it dies, the pet will stop attacking and is "stuck in place". After setting passiv and back to attack mode the pet will run to its target but doesnt attack it. Sometimes after setting passiv and attack again it works again, but only sometimes.

**Expected behavior**: 
Switch target and attack.

**Steps to reproduce**:

1. Make Hunter and get a pet (In my case a cat ID 311)
2. Attack one mob, where another is near so that both come to you
3. Kill one
4. Profit

**Client version**: 
Newest

**Database version**: 
Newest

**Operating system**: 
Linux Debian 64 bit

Additional:
Sometimes not reproduceable.

**Comment by Phatcat** [comment]
I'm not sure but this may be related to this: https://github.com/cmangos/issues/issues/179

**Comment by SatyPardus** [comment]
To make it more clear, a video: https://www.youtube.com/watch?v=1X6HKu08TVQ
Dont know if it is related.

**Comment by Phatcat** [comment]
Okay, I see you play with pet on passive.... that may actually have a say in this sadly...

**Comment by Zooke** [comment]
>> Okay, I see you play with pet on passive.... that may actually have a say in this sadly...

It's the only way to play, otherwise your pet pulls anything in range. Passive, so that your pet only attacks targets you attack or are attacking you.

**Comment by SatyPardus** [comment]
Nah. This happens on all three. Even if i manually select what the pet should attack. When 2 mobs are pulled, the pet gets bugged. The video shows the moment when you have luck and it starts attacking again. But only after the second try as you see.

**Comment by Phatcat** [comment]
Okay, I am on this asap.

**Comment by SatyPardus** [comment]
I am also looking. But i am not as expirienced :P

**Comment by SatyPardus** [comment]
Also, this can be related with https://github.com/cmangos/issues/issues/923 as the behavior is the same. The pet is following, but not attacking. It's like the sheep, that follow but not attack. And when he unsheeps, he just stands there and does nothing, just like the pet.

I think it has something to do with the aggro. Looks like, when they should not get any aggro, that they get it somehow and abort their current action (Like going back to owner, do sheep stuff, flee) and get stuck in this follow but not attack state.

**Comment by Phatcat** [comment]
> I think it has something to do with the aggro.

It's a long shot but you are very welcome to test if [this](https://github.com/cmangos/mangos-classic/pull/151) branch fixes the issue, it has 2 commits relating to aggro.

**Comment by Phatcat** [comment]
I'm not quite sure it's to do with aggro, though, as we see the pet run in and do a single hit on the second target in which it bugs out afterwards.

**Comment by Phatcat** [comment]
>> Okay, I see you play with pet on passive.... that may actually have a say in this sadly...

>It's a style of play mostly used by hunters who do everything by macros because it gives the most control.

He was however playing on defensive when this happened, i guess I wasn't paying much attention to the pet bar until later in the vid, and while it's on purpose that a pet on passive is not supposed to fight back unless you tell it, it very much should in defensive and aggressive.

**Comment by SatyPardus** [comment]
How do i pull a not merged commit?^^

**Comment by Phatcat** [comment]
You mad have to add the repository to remote by doing

`git remote add name* link_to_git_repo*`
* replace with appropriate.

Afterwards you do a

`git fetch name`

and now you're ready to pull it in.

Whereever you wanna pull in commits from this repo you do

`git cherry-pick commit_hash*`

You can of course experience merge issues with this as you can pull in from any repo you add to remote and fetch, it doesn't have to be a cmangos repo, it could be anything really.

**Comment by cyberium** [comment]
As its a PR you can also do
> git pull https://github.com/cmangos/mangos-classic +refs/pull/151/head

where 151 is the number of the pull request :)

**Comment by SatyPardus** [comment]
Hmm^^ I better test this not with my main repo. Don't want to mess stuff up :D Gonna try it later with a fresh one

**Comment by SatyPardus** [comment]
After multible tests with exact same pet, mobs and stuff, the bug still apears.
So this is not a fix^^

**Comment by SatyPardus** [comment]
I found the bug. When the pet switches its target, sometimes it happen that he gets stuck on the direction. https://github.com/cmangos/mangos-classic/blob/master/src/game/Unit.cpp#L355 is the line wich is called when the pet doesnt attack. I test it a little bit more

**Comment by SatyPardus** [comment]
Possible fix that works after 10 minutes of testing, assing the following code to https://github.com/cmangos/mangos-classic/blob/master/src/game/PetAI.cpp#L337

`if (!m_creature->HasInArc(2 * M_PI_F / 3, victim))
		{
			sLog.outString("Not in view");
			m_creature->SetInFront(victim);
			if (victim->GetTypeId() == TYPEID_PLAYER)
				m_creature->SendCreateUpdateToPlayer((Player*)victim);

			if (owner && owner->GetTypeId() == TYPEID_PLAYER)
				m_creature->SendCreateUpdateToPlayer((Player*)owner);
		}`

**Comment by Phatcat** [comment]
@SatyPardus Looks legit, I personally see no issue but I am not strong on client-server communication... You maybe want to do a pull request for the change so it's easier to review this change and make comments on it?
I'll guide you through it if needed.

**Comment by SatyPardus** [comment]
A guide would be great. The last time i pushed something it went wrong :D

**Comment by Phatcat** [comment]
I trust you are familiar enough with git to understand a few basics, just ask if in doubt:

First you make a clean branch of cmangos/master , call it something related and it'll make things easier for yourself

Then you locate the files you want to modify and you make your changes, then you review your changes and verify them, and if they're correct, you commit them.

Then you publish your branch and then you can go and open a pull request and compare changes accross forks, choose your own fork, choose the appropriate branch and then write and appropriate title and message.

I use the Github client for all of these 'basic' operations since I find it somewhat nice to work with.
Doing more complicated things require that you learn some commands and go down that route but that can be all avoided in this case.

**Comment by SatyPardus** [comment]
Opened a pull request https://github.com/cmangos/mangos-classic/pull/159

**Comment by Phatcat** [comment]
Closed by Saty's own commit; 
https://github.com/cmangos/mangos-classic/commit/acfa2a0cd438aff38268f5c8ddb7e2a909105143
https://github.com/cmangos/mangos-tbc/commit/7ea80e15ab548d8c463ce1945ac12507e5015885
https://github.com/cmangos/mangos-wotlk/commit/d1f4ca4dbf23977cfd80c2a871c5bffd2d3ad9d6

**Comment by irgc** [comment]
hi guys

Why not attack!
hunter pet?
i use tdb 63!
