### ISSUE TITLE
Gathering npc_text ids for no longer existing content

### ISSUE THREAD

**Issue by harlynx** [cmangos/issues#972]
What is the general consent on implementing npc_text entries (for example cached gossip box texts)  which are no longer obtainable in the live version? It is impossible to retrieve the id for those entries.
I've got the text data here, but have no idea what ids they have had.

Looking at the existing npc_text table data and the usage of it, it seems that it is very strict with its ids (no custom ids, just the ones retrieved from the WDB files). Then there are also lines like [these](https://github.com/cmangos/mangos-wotlk/blob/cc498495104cce91e1079e30002978201d553b8f/src/scriptdev2/scripts/world/npc_professions.cpp#L539) where it simply says "unknown text ids" and it is not implemented or [this example](https://github.com/cmangos/mangos-wotlk/blob/cc498495104cce91e1079e30002978201d553b8f/src/scriptdev2/scripts/eastern_kingdoms/blackwing_lair/boss_vaelastrasz.cpp#L49-L52) where it just takes the default "Greetings" text which could be improved.

What is the way to go here?

**Comment by shnibble** [comment]
This should probably be discussed on the forums http://cmangos.net/index.php, could you please post a thread there?

I hope you don't mind but I'm closing the issue for now as it doesn't reference anything specific.
