### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by apo126** [cmangos/issues#973]
Revision: * * *
Date 22:6:2016. Time 19:57 
//=====================================================
*** Hardware ***
Processor: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
Number Of Processors: 4
Physical Memory: 4194303 KB (Available: 4194303 KB)
Commit Charge Limit: 4194303 KB

*** Operation System ***
Windows 7 Service Pack 1 (Version 6.1, Build 7601)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  0054A288 01:00149288 D:\Games\Mangos\mangosd.exe

Registers:
EAX:00000017
EBX:F8AC72B2
ECX:00000000
EDX:0000001E
ESI:0000001D
EDI:EDD62B00
CS:EIP:0023:0054A288
SS:ESP:002B:0864F630  EBP:0864F67C
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010297

Call stack:
Address   Frame     Function      SourceFile
0054A288  00000000  Pet::InitStatsForLevel+498
008B619E  00000000  Spell::EffectSummonPet+44E
007D7940  00000000  Spell::HandleEffects+220
007D517B  00000000  Spell::DoSpellHitOnUnit+40B
007D47BB  00000000  Spell::DoAllEffectOnTarget+1BB
007E1652  00000000  Spell::handle_immediate+52
007E0C49  00000000  Spell::cast+7C9
007D84E7  00000000  Spell::Prepare+C7
007DDDF6  00000000  Spell::SpellStart+E6
004FC101  00000000  Unit::CastSpell+2A1
006EFDAE  00000000  CreatureAI::DoCastSpellIfCan+FE
006F3F53  00000000  CreatureEventAI::ProcessAction+413
006F62D8  00000000  CreatureEventAI::ProcessEvent+13B8
006F67EC  00000000  CreatureEventAI::UpdateAI+9C
00526D18  00000000  Creature::Update+2E8
0053DBB5  00000000  MaNGOS::ObjectUpdater::Visit+85
0053131E  00000000  VisitorHelper<MaNGOS::ObjectUpdater,Creature>+E
00531340  00000000  VisitorHelper<MaNGOS::ObjectUpdater,Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > >+10
0053D7DB  00000000  Map::Update+6BB
00699D59  00000000  MapManager::Update+69
004B55F4  00000000  World::Update+2B4
004782DF  00000000  WorldRunnable::run+4F
0049BC41  00000000  std::_LaunchPad<std::_Bind<1,void,void (__cdecl*const)(void *),void *> >::_Go+11
6771F33C  00000000  ?_Release@_Pad@std@@QAEXXZ+6C
649FC01D  00000000  __get_tlsindex+6F
649FC001  00000000  __get_tlsindex+53
7712338A  00000000  BaseThreadInitThunk+12
77809902  00000000  RtlInitializeExceptionChain+63
778098D5  00000000  RtlInitializeExceptionChain+36
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
0054A288  00000000  Pet::InitStatsForLevel+498
punting on symbol petlevel
	Local  <user defined> 'createResistance'
punting on symbol scale
punting on symbol mDmg
punting on symbol dMaxLevel
punting on symbol val
punting on symbol hMaxLevel
punting on symbol mMaxLevel
punting on symbol mMinLevel
punting on symbol hMinLevel

008B619E  00000000  Spell::EffectSummonPet+44E
	Local  <user defined> 'eff_idx'
	Local  <user defined> 'pos'
punting on symbol py
punting on symbol px
punting on symbol pz
	Local  <user defined> 'new_name'

007D7940  00000000  Spell::HandleEffects+220
	Local  <user defined> 'pUnitTarget'
	Local  <user defined> 'pItemTarget'
	Local  <user defined> 'pGOTarget'
	Local  <user defined> 'i'
punting on symbol DamageMultiplier

007D517B  00000000  Spell::DoSpellHitOnUnit+40B
	Local  <user defined> 'unit'
punting on symbol effectMask
punting on symbol multiplier
punting on symbol duration

007D47BB  00000000  Spell::DoAllEffectOnTarget+1BB
	Local  <user defined> 'target'
punting on symbol crit
punting on symbol absorb
punting on symbol gain
	Local  <user defined> 'damageInfo'
	Local  <user defined> 'itr'
punting on symbol bp
	Local  <user defined> 'damageInfo'

007E1652  00000000  Spell::handle_immediate+52

007E0C49  00000000  Spell::cast+7C9
punting on symbol skipCheck

007D84E7  00000000  Spell::Prepare+C7

007DDDF6  00000000  Spell::SpellStart+E6
	Local  <user defined> 'targets'
	Local  <user defined> 'triggeredByAura'

004FC101  00000000  Unit::CastSpell+2A1
	Local  <user defined> 'Victim'
	Local  <user defined> 'spellInfo'
punting on symbol triggered
	Local  <user defined> 'castItem'
	Local  <user defined> 'triggeredByAura'
	Local  <user defined> 'originalCaster'
	Local  <user defined> 'triggeredBy'
	Local  <user defined> 'targets'

006EFDAE  00000000  CreatureAI::DoCastSpellIfCan+FE
	Local  <user defined> 'pTarget'
punting on symbol uiSpell
punting on symbol uiCastFlags
	Local  <user defined> 'uiOriginalCasterGUID'

006F3F53  00000000  CreatureEventAI::ProcessAction+413
	Local  <user defined> 'action'
punting on symbol rnd
punting on symbol EventId
	Local  <user defined> 'pActionInvoker'
	Local  <user defined> 'pAIEventSender'
punting on symbol reportTargetError
	Local  <user defined> 'i'

006F62D8  00000000  CreatureEventAI::ProcessEvent+13B8
	Local  <user defined> 'pHolder'
	Local  <user defined> 'pActionInvoker'
	Local  <user defined> 'pAIEventSender'
	Local  <user defined> 'pList'
	Local  <user defined> 'pList'

006F67EC  00000000  CreatureEventAI::UpdateAI+9C
	Local  <user defined> 'diff'

00526D18  00000000  Creature::Update+2E8
punting on symbol update_diff
punting on symbol diff

0053DBB5  00000000  MaNGOS::ObjectUpdater::Visit+85
	Local  <user defined> 'm'

0053131E  00000000  VisitorHelper<MaNGOS::ObjectUpdater,Creature>+E
	Local  <user defined> 'v'
	Local  <user defined> 'c'

00531340  00000000  VisitorHelper<MaNGOS::ObjectUpdater,Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > >+10
	Local  <user defined> 'v'
	Local  <user defined> 'c'

0053D7DB  00000000  Map::Update+6BB
	Local  <user defined> 't_diff'
	Local  <user defined> 'updater'
	Local  <user defined> 'updater'
	Local  <user defined> 'area'
	Local  <user defined> 'cell'
	Local  <user defined> 'area'
	Local  <user defined> 'cell'

00699D59  00000000  MapManager::Update+69
punting on symbol diff

004B55F4  00000000  World::Update+2B4
punting on symbol diff

004782DF  00000000  WorldRunnable::run+4F

0049BC41  00000000  std::_LaunchPad<std::_Bind<1,void,void (__cdecl*const)(void *),void *> >::_Go+11

6771F33C  00000000  ?_Release@_Pad@std@@QAEXXZ+6C

649FC01D  00000000  __get_tlsindex+6F

649FC001  00000000  __get_tlsindex+53

7712338A  00000000  BaseThreadInitThunk+12

77809902  00000000  RtlInitializeExceptionChain+63

778098D5  00000000  RtlInitializeExceptionChain+36

========================
Global Variables

**Comment by Phatcat** [comment]
https://github.com/cmangos/issues/issues/969#issuecomment-227887144
