### ISSUE TITLE
[CLASSIC] SMSG_CANCEL_COMBAT Doesn't Cancel Ranged Attacks

### ISSUE THREAD

**Issue by SatyPardus** [cmangos/issues#978]
**Current behavior**: 
SMSG_CANCEL_COMBAT cancels only meele attacks, a comment in the core says it also stops ranged.
After some seaching and testing i noticed, that this leads to some problems with hunter. Mend Pet seems to be aborted to this and on a target switch, it still attacks the old target. ( This is related to https://github.com/cmangos/issues/issues/895 )

**Expected behavior**: 
Abort ranged attacks.

Is the Opcode maybe from a newer version? And was different back then?

**Comment by Phatcat** [comment]
This should very well be resolved

**Comment by Tobschinski** [comment]
should...?

**Comment by Phatcat** [comment]
Well the issues he is describing is no longer present, but I don't know if we properly handle SMSG_CANCEL_COMBAT

**Comment by al3xc1985** [comment]
@killerwife I believe we can close this
