### ISSUE TITLE
[TBC] Serrated Blades Talent Tooltip Not Showing

### ISSUE THREAD

**Issue by killerwife** [cmangos/issues#980]
**Current behavior**: 
Talent Serrated blades shows 0 tooltip
**Expected behavior**: 
Should show level scaling tooltip, based on rank
**Steps to reproduce**:
1. Make a rogue.
2. Get level 70
3. Look at talents

**Cmangos version**: 
TBC, possibly Classic

**Comment by SilvioDoMine** [comment]
I was looking into it today. It is just a tooltip error, @killerwife?

**Comment by killerwife** [comment]
To this day I do not know for certain.

**Comment by killerwife** [comment]
Resolved by sending correct aura flags.
