### ISSUE TITLE
[Classic] Distracted units change their facing server side

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#981]
At first glance rogue's distract works as intended. The targeted mob will stop it's movement and face towards the correct direction for up to 10 seconds. To my experience however, the facing of the distracted mob can change server side. Sometimes I can't use backstab-like abilities on a distracted mob (getting the 'you are not behind' error, even though I am behind), but more often the mob spots me even though I am perfectly behind it's back.

This has only happened to me with mobs that move around, so my guess is that a MovementGenerator can somehow override the facing of the unit, which was explicitly set by the distract. (And this override has no effect client side, so the mob appears to be facing the right direction.)

To reproduce the issue:
1. Find a mob with random movement
2. Distract it to a direction it's currently facing, right before you expect it to move again
3. Try to Ambush / Backstab / Garrote the distracted mob
(It may take a few tries.)

**Comment by killerwife** [comment]
Simple,     unitTarget->SetFacingTo(unitTarget->GetAngle(m_targets.m_destX, m_targets.m_destY)); changes facing clientside. You need to add SetOrientation or make SetFacingTo change orientation serverside as well :)
Lemme know if it works, I saw it somewhere I think.

**Comment by katz1** [comment]
@killerwife 
Thanks! If I put it after the DistractMovementGenerator is added to the stack, it appears to be working neatly. Made a PR.

**Comment by killerwife** [comment]
^^ get it approved by @cyberium and there we go. Prolly needs to be in all version.
