### ISSUE TITLE
[Classic] Mobs turn after getting stunned

### ISSUE THREAD

**Issue by katz1** [cmangos/issues#983]
Sometimes (~5% of the time) mobs change their facing right after getting stunned, and stay like that until the stun is over. This facing change appears to be client side only. Like mobs turn away from me after receiving a Gouge, but I have to still run to the other side to be able to Backstab them.

Just as a side note, I remember this exact same bug while playing on private servers ~8 years ago.

**Comment by killerwife** [comment]
I encountered this very same issue when scripting Karazhan chess. For some unknown reason client side, shit is turning left and right causing a headache. I assume there might be a flag that disables this kind of behaviour or a spline/w/e that affects it. As of yet I havent found such an indication, but i didnt have time to experiment with it either.

**Comment by Warlockbugs** [comment]
Please, verify if this still happens after recent changes to CC effects.

**Comment by katz1** [comment]
I've played for quite a while and I did not run across it once.
Thanks for fixing it!

**Comment by katz1** [comment]
I did run into this issue again in the end. Mobs very rarely turn after getting a Kidney Shot. At first I thought it was only because I stunned them right after they were about to flee, but it did happen to non-fleeing mobs a numerous times as well.

**Comment by AnonXS** [comment]
Also happens in TBC Core

**Comment by AnonXS** [comment]
Orientation Update on Stun Aura - Export pending

**Comment by killerwife** [comment]
Actually exported already. https://github.com/cmangos/mangos-tbc/commit/523941d3d1093e009bfb7b3da35b831784626091#diff-ca2439f8cc7d37988fda1b6f07e25e7fR9818
