### ISSUE TITLE
[WotLK] Server log - ERROR:SESSION: received not allowed opcode CMSG_LFG_GET_STATUS (0x0296)

### ISSUE THREAD

**Issue by Vladskywolf** [cmangos/issues#986]
**Current behavior**: 
As the title says, I am seeing this error message in my server log:

ERROR:SESSION: received not allowed opcode CMSG_LFG_GET_STATUS (0x0296)

I noticed I could easily reproduce it (see below), though I'm not certain of what else might trigger it.

**Steps to reproduce**:
1. Enter or exit the Deeprun Tram 'instance' from Stormwind.

**Client version**: 
3.3.5 (12340)

**Commit hash**: 
c529b71edb295b634cb80582516acf763ee38286

**Database version**: 
UDB 408 updated to 491

**Operating system**: 
Ubuntu 12.04

**Comment by adellaci** [comment]
Current behavior:
ERROR:SESSION: received not allowed opcode CMSG_LFG_GET_STATUS (0x0296)

Steps to reproduce:

    I receive the same error. It happen when i enter into the world.

Client version:
3.3.5 (12340)

Commit hash:
Don't have it off hand at the moment, but it was compile from my pull on 8/6/16

Database version:
UDB 408 updated to 491

Operating system:
Ubuntu 14.04

Note: It doesn't appear to create any in game issue nor does it crash the server. @Vladskywolf are you running any addons? I am. Going to test tomorrow night with all addons off.

**Comment by cyberium** [comment]
Guys its not realy an error. LFG wywtem is not yet implemented that why we get that error. We probably have to disable that misleading error.

**Comment by adellaci** [comment]
@Cyberium
Thank you for the info. Like I noted, the error message is not creating any issues for me.
