### ISSUE TITLE
Not working lock server

### ISSUE THREAD

**Issue by BungiSk** [cmangos/issues#987]
**Current behavior**: 
Not working lock server, i set allowedSecurityLevel 1 and no working. Players can still go to the server. I try restarting the server, but to no avail.

**Expected behavior**: 
Accounts with a lower gmlevel than allowedSecurityLevel should not be granted access to the server.

**Steps to reproduce**:
1. Update `allowedSecurityLevel` on realmd database to 1;
2. Create a level 0 account;
3. Login with said account;

**Client version**: 
1.12.1
**Commit hash**: 

**Database version**: 
1.65
**Operating system**: 
Win64, Win 7

**Comment by shnibble** [comment]
Confirmed on classic core. Same operating system as above: Windows 7, 64-bit.

I also updated your comment to include expected behavior and steps to reproduce.

**Comment by MrMarvin** [comment]
Isn't this something the mangosd should handle, but doesnt really?

As far as my few minutes looking at the realmd code showed the decision is actually just if the realm is listed online in the realm list, or not. If a client already knows about the realm (e.g. having connected before) or its the only realm available and therefore auto suggested to the player, there is nothing realmd can do to prevent the client from connecting. At least thats what I read and could reproduce locally...

**Comment by cyberium** [comment]
You dont use this feature the right way.
To make it work as intended you simply have to modify your mangosd.conf
```
#    PlayerLimit
#        Maximum number of players in the world. Excluding Mods, GM's and Admins
#        Default: 100
#                 0 (for infinite players)
#                -1 (for Mods, GM's and Admins only)
#                -2 (for GM's and Admins only)
#                -3 (for Admins only)
```
So do not modify it in DB.

I understand it may be a bit misleading. We'll maybe in some future rework that. (When @Fabi new realmd will be ready...)
