### ISSUE TITLE
[TBC] Crash on Water Elemental/Shadowfiend unsummon

### ISSUE THREAD

**Issue by wowx** [cmangos/issues#988]
**Current behavior**: 
On unsummoning Water Elemental or Shadowfiend server crash
**Expected behavior**: 
http://pastebin.com/SX8rbDqm
**Steps to reproduce**:
Just wait to unsummon minion
**Client version**: 
TBC
**Commit hash**: 

**Database version**: 

**Operating system**: 
linux debian 8.2 64bit jessie

**Comment by killerwife** [comment]
@Phatcat

**Comment by Phatcat** [comment]
On it.

**Comment by Phatcat** [comment]
Yeah, found it, pushing fix to master in a bit.
