### ISSUE TITLE
Gossip Text for Zeppelin Master

### ISSUE THREAD

**Issue by NocFenix** [cmangos/issues#989]
**Current behavior**: 
When you talk to the Zeppelin masters they all have an option for "Where is the zeppelin now?"
When you click on this, for most of them nothing happens, for the others they always say "The zeppelin should have just departed (city where you want to go to with the zeppelin)" If they provide any text when clicking where is the zeppelin is it to always tell you that the zeppelin just departed the other city, even if it is right in front of you.

**Expected behavior**: 
When you click on "Where is the zeppelin now?" You should get an actual update of where the zeppelin is: "The zeppelin should have just reached ... " "The zeppelin should have just arrived at ... " This is to help the player know when/where to expect the zeppelins.

**Steps to reproduce**:
1. Talk to any zeppelin master in Grom'gol or Durotar and ask "Where is the zeppelin now?" and they respond that it will have departed the opposite continent, regardless of zeppelin location; all zeppelin masters in Tirisfal do nothing when asked "Where is the zeppelin now?"

**Client version**: 
Mac Client: 1.12.1
Win Client: 1.12.1

**Commit hash**: 
f61622cfa610b52692b866da24fd6085625144f2

**Database version**: 
ClassicDB: 
A content database for [mangos-classic][10], and _World of Warcraft Client Patch
1.12_ - [_Drums of War_][50]

**Operating system**: 
OS X
Win 10

**Comment by xfurry** [comment]
I think this is kind of complicated to implement.
The only way I can see this happening, is using the event ids which are triggered by the MO transport handlers, to change conditions for gossip.

Quite complicated and I'm not sure if it's worth the effort and risk, just for a simple gossip...

**Comment by killerwife** [comment]
I think it can be implemented with the "world" conditions we talked about that we need for zangar PVP :)

**Comment by NocFenix** [comment]
Hey, give me some pointers on proper debugging and I'm more than happy to tinker, troubleshoot and mess with my own instance. I just cannot seem to get my Visual Studio to run in debug mode to do any true troubleshooting. I know how to code and make changes, the problem I've run in to is getting a good understanding of c-Mangos and running in debug mode.

**Comment by NocFenix** [comment]
Or, another, temporary solution, would be to use the npc_text.ID 11163: "I'm not sure where the zeppelin is right now, actually..." and just make sure that it properly pops whenever someone clicks "Where is the zeppelin right now?" I'd rather get something ambiguous than nothing or something incorrect...

**Comment by xfurry** [comment]
> I think it can be implemented with the "world" conditions we talked about that we need for zangar PVP :)

Yes
But for that, we actually need to have that functionality implemented somehow similar to R2 and we also need to define some custom world states for these kind of events.
Also, this requires the MOT patch developed by @Exxenoz 
https://github.com/Exxenoz/mangos-wotlk/commits/CMOT

**Comment by killerwife** [comment]
He didnt finish it?

**Comment by Exxenoz** [comment]
No. Unfortunately I'm currently very busy, but I will find some time this summer to get this feature running. It's about time.

**Comment by killerwife** [comment]
Fair enough, thx for letting us know :)

**Comment by AnonXS** [comment]
Seems to not be an issue for classic and resolve dor tbc+ https://github.com/cmangos/tbc-db/commit/1f512d1f7328c84e7606ec1eea478d23f57557b5

**Comment by cala** [comment]
Discussed with @killerwife : this was implemented after Classic. So the issue can be closed. Possibly the gossips in Classic are misleading. I'll look into this next time I get the chance.
