### ISSUE TITLE
[TBC] Haste But on Off Hand

### ISSUE THREAD

**Issue by celroot** [cmangos/issues#994]
**Current behavior**: 
When you make custom items, and add haste over 5k, or if the weapon speed is under 0.30 it got bug and the off hand weapon isn't used, so this make you an -1 weapon and the procs or spells implemented on this don't work. (On hit procs got bug, equip doesn't)

**Expected behavior**: 
The offhand should be used, the spells or procces added on her should be executed too. 

**Steps to reproduce**:
N/n
**Client version**: 
Tbc 2.4.3 (Build 8606) 

**Operating system**: 
Windows 10 Pro

**Comment by kartoffelsup** [comment]
> When you make custom items, and add haste over 5k
Who would want to do that?

**Comment by celroot** [comment]
Custom servers like Plagueland or the old Acolytes Online maybe?. The situation is that player should attack with both weapons no matter how much haste they have.

**Comment by jimmybrancaccio** [comment]
@celroot Can you confirm if this is still an issue?

**Comment by jimmybrancaccio** [comment]
Closing this issue out. If anyone is still having a problem, please open a new issue with full details.
