### ISSUE TITLE
[All] We need special realmd for each version

### ISSUE THREAD

**Issue by stas730** [cmangos/issues#996]
**Current behavior**: 
I saw "BNET", "12340" and other non-vanilla stuff in VANILLA realmd.
**Expected behavior**: 
We need special realmd for each version
**Steps to reproduce**:

1. Open Github
2. Open realmd code
3. Read

**Client version**: 
All
**Commit hash**: 
322e391
**Database version**: 
I'm not using ©MaNGOS now.
**Operating system**: 
All

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)

**Comment by Phatcat** [comment]
So what is the issue exactly? Doesn't realmd work for vanilla?

If this is a suggestion then 'need' is kind of a misleading term isn't it? also I don't get why we'd ever need to further specialize the realmds - you know we are trying to sync up as much of the code as possible, right? - the only reason to keep them different at all is because it'd be needed in order for us to be able to reach true emulation; anything else is just an excuse which makes it harder on us developers.

**Comment by Phatcat** [comment]
That's more than 2 weeks with no answer; as this is not really an issue and goes against syncing up the cores I will close this.
Please don't see this as me turning you down, I am just doing github house-keeping and suggestions like these belong on the forum in my opinion.

**Comment by Laizerox** [comment]
I don't really understand what's the issue. Many years ago we combined specific version realmd's into one since you need only one.

Clients are being sent their correct packet structures regardless of client version. So using one realmd you can have one realmlist for all versions.

**Comment by cyberium** [comment]
> I don't really understand what's the issue. Many years ago we combined specific version realmd's into one since you need only one.

Then iam waiting your super patch as iam agree with you on that point :)
Iam also agree with @Phatcat closing this issue because its not an issue its a feature request.

**Comment by stas730** [comment]
Reopen.
For example, we haven't Battle.net functions in Vanilla and TBC. But we have it in realmd.

**Comment by sidsukana** [comment]
> For example, we haven't Battle.net functions in Vanilla and TBC. But we have it in realmd.
And? These function work obly for needed patches.  The rest of the working code is common to all.
I do not understand your desire to write a lot of duplicate code? This is a very bad trend.

**Comment by Laizerox** [comment]
cmangos/mangos-classic@096792

Please see following commit. All versions use same realmd and in future there will be single repository fro realmd. Each client is handled specially inside realmd code.
