### ISSUE TITLE
[TBC] Crashes related to pet system and motion master.

### ISSUE THREAD

**Issue by Undergarun** [cmangos/issues#997]
**Current behavior**: 
Crash.

**Expected behavior**: 
Should not Crash.

**Steps to reproduce**:

1. http://pastebin.com/SvgxRk6E
2. http://pastebin.com/aAvMNCrE
3. http://pastebin.com/hc83HLrj

**Client version**: 

**Commit hash**: 

**Database version**: 
TBC-DB

**Operating system**: 
Ubuntu Server 16.04 LTS

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)
http://pastebin.com/SvgxRk6E
http://pastebin.com/aAvMNCrE
http://pastebin.com/hc83HLrj

**Comment by Phatcat** [comment]
> Current behavior:
Crash.

> Expected behavior:
Should not Crash.

Haha, that's funny, not the crash but the formulation ^^

Thank you for the report, I'll look into this asap.

**Comment by Undergarun** [comment]
updated with one more crash. Number 3.

**Comment by Phatcat** [comment]
> `#10 0x00000000008ee9d9 in WorldSession::HandlePetAction (this=0x743198000ce0, recv_data=...) at /root/WorldOfWarcraftTheBurningCrusade/src/game/PetHandler.cpp:103`
        petGuid = {m_guid = 17379391011851101678}
        targetGuid = {m_guid = 17379391011851101678}
        spellid = 1
        flag = 7 '\a'
        pet = 0x7431c6311db0

[Line 103 of PetHandler;](https://github.com/cmangos/mangos-tbc/blob/master/src/game/PetHandler.cpp#L103)
> pet->GetMotionMaster()->MoveFollow(_player, PET_FOLLOW_DIST, PET_FOLLOW_ANGLE);

Are you sure you are running stock cmangos?

**Comment by Phatcat** [comment]
> `#1  0x00000000008eeaaf in WorldSession::HandlePetAction (this=0x6e871c001060, recv_data=...) at /root/WorldOfWarcraftTheBurningCrusade/src/game/PetHandler.cpp:126`
        targetUnit = 0x6e8743593c60
        petGuid = {m_guid = 17379391011851101678}
        targetGuid = {m_guid = 17379391012941621365}
        spellid = <optimized out>
        flag = 7 '\a'
        pet = 0x6e87433a57b0

[Line 126 of PetHandler](https://github.com/cmangos/mangos-tbc/blob/master/src/game/PetHandler.cpp#L126)
> pet->GetMotionMaster()->Clear();

**Comment by Phatcat** [comment]
That last third crash you tagged onto this one as well doesn't seem to belong here; i couldn't find a single mention of pets anywhere in it at all.

**Comment by Phatcat** [comment]
Yeah, unless you can confirm that these crashes happened running stock mangos and provide me with some steps to reproduce or at least give me something to go by I'm going to have to close this as I am not experiencing any issues with pets and motion master, let alone any crashes.

**Comment by Phatcat** [comment]
That's 2 weeks and no answer, closing.
