### ISSUE TITLE
Realmd LogTime config option

### ISSUE THREAD

**Issue by goldspy98** [cmangos/issues#998]
**Current behavior**: On realmd config file if we set LogTime option to 1 the daemon won't execute.

**Expected behavior**: Realm daemon should work with LogTime option enabled.

**Steps to reproduce**:

1. Compile source code and prepare realmd.conf file
2. Change LogTime on realmd.conf file from 0 to 1
3. Run ./realmd

**Client version**: TBC

**Commit hash**: a5cbd85f47880100ea5ef34a2ea8ccd622e07b79

**Database version**: Not applicable

**Operating system**: Ubunto 14.04.4 x64

**Comment by Phatcat** [comment]
This one we have already been informed of, but I don't believe it has its own report so thank you.
