### ISSUE TITLE
[TBC] Quest 10722 - Meeting at the Blackwing Coven

### ISSUE THREAD

**Issue by Leadballoon2000** [cmangos/issues#999]
**Current behavior**: 
No gossip on quest mob

**Expected behavior**: 
Kolphis Darkscale provides gossip that completes quest

**Steps to reproduce**:
1. Do quest
2. Keep doing it
3. 

**Client version**: 
2.4.3

**Database version**: 
1.5

**Comment by Leadballoon2000** [comment]
https://github.com/TBC-DB/Database/pull/44

**Comment by Phatcat** [comment]
Thank you very much for this; 
however, if you are well aware this is a DB issue then there's no need to raise an issue here; especially if you've raised a PR with the DB; the issue actually belongs on the DB's issue tracker in all honesty. but again, thank you. I am in no way complaining, just letting you know =)

These tickets are mainly for stuff that the cmangos core (including scriptdev) team can solve.

**Comment by killerwife** [comment]
Only one thing im gonna mention, when you start investigating a quest, sometimes you end up finding out that its a core issue even thought its 99% DB. So I think quest scripts can be kept here.

**Comment by xfurry** [comment]
Looks like a DB issue to me.

**Comment by killerwife** [comment]
Yes but 1. The person writing the issue doesnt have to know right away its a DB issue.
2. Its an issue in both UDB and TBC-DB, meaning you would have to make two db issues IF you knew its a DB issue.

**Comment by Grz3s** [comment]
> 2. Its an issue in both UDB and TBC-DB, meaning you would have to make two db issues IF you knew its a DB issue.

Quest 10722 works fine in UDB ...

**Comment by killerwife** [comment]
*sigh oooooh well, thx for letting me know I guess :D @Leadballoon2000 look in UDB for the fix pls, I know its a bother, but we need to be in sync with our fellas....

**Comment by Leadballoon2000** [comment]
OK I'll take another look. I had previously checked UDB for the gossip entries. I guess I missed it.

**Comment by killerwife** [comment]
Make sure u have all updates installed.

**Comment by Leadballoon2000** [comment]
I see now in update 405 the quest's gossip is added, sorry for not noticing that.

Two differences between the Trinity and UDB changes are that Trinity has a quest completed gossip npc_text id 10540. I can't confirm the text because noone in videos goes back to talk to the NPC and I don't have access to live.
Also, Kolphis Darkscale NPC id 22019 has Whirlwind and Enrage abilities when he's hostile.

**Comment by Leadballoon2000** [comment]
The gossip added from the Trinity change is mostly the same as the UDB change although Trinity has no gossip 8440 quest termination text. 

I see that the changes are incompatible as regards the condition handling, UDB has columns in gossip_menu_option for the quest condition whereas TBC-DB and Trinity have a conditions table.

**Comment by killerwife** [comment]
Yes, just port it. I already ported a lot from the UDB patches, just make sure you insert the conditions correctly and you test it :)

**Comment by Leadballoon2000** [comment]
The PR is tested and ready to pull.

**Comment by jimmybrancaccio** [comment]
@Leadballoon2000 Do you have a link to the PR? I'm not seeing it. Resubmit if necessary. Thanks!

**Comment by AnonXS** [comment]
https://github.com/TBC-DB/Database/pull/44/files

**Comment by jimmybrancaccio** [comment]
Duh, completely missed that comment above, thanks @AnonXS!

**Comment by jimmybrancaccio** [comment]
@killerwife or @AnonXS Would this be something we could look at getting into the database, would you guys prefer it to be a PR against cmangos/tbc-db instead?

**Comment by jimmybrancaccio** [comment]
Retagging @AnonXS and @killerwife for feedback.

**Comment by killerwife** [comment]
Cmangos should have all of this by now. Someone test it.

**Comment by berserkingyadis** [comment]
I tested it. Talking to the mob and clicking through its dialogue completed the quest, while wearing the disguise. 

https://gfycat.com/vengefulsphericaljenny

Not sure about the disguise tho, I was playing female character and it transformed me into male dreanai in disguise.

@killerwife

**Comment by killerwife** [comment]
Thats related to DB data of creature entry 21981, so thats legit.
